### ISSUE TITLE
Password should not be lost on neo4j upgrade

### ISSUE THREAD

**Issue by billscheidel** [neo4j/neo4j#10028]
I recently upgraded to Neo4j Enterprise 3.2.3 and noticed that my password had been reset back to `neo4j`.  Since I do upgrades in an automated fashion, this ended up causing failures since the upgrade reports no errors but my clients can no longer connect.

- Neo4j version: 3.2.3
- Operating system: Ubuntu 16.04
- API/Driver: Cypher

### Steps to reproduce
Upgrade to latest stable build using apt-get

### Expected behavior
Database would continue to use the password that I previously set.

### Actual behavior
Database password was reset to `neo4j`.

**Comment by jennyowen** [comment]
I tested this with 3.4 and it seems to have been fixed since you reported the issue. 
I've added tests so it shouldn't happen again. 
Thanks for reporting the issue!
