### ISSUE TITLE
Cypher: DISTINCT reverses the result list, breaking SKIP and LIMIT

### ISSUE THREAD

**Issue by billscheidel** [neo4j/neo4j#10031]
I'm creating a basic linked list and traversing the list using SKIP and LIMIT.  I noticed that if I use DISTINCT in the query, the result list apparently gets reversed such that SKIP and LIMIT act from the end of the list to the start instead of from the start of the list to the end.  

Not sure if this is expected behavior, if so it would be nice to get a warning about it or at least get it noted on the ref card.

- Neo4j version: 3.2.3
- Operating system: Ubuntu 16.04
- API/Driver: Cypher-Shell

### Steps to reproduce

Setup:

````
CREATE (:Entity {id:"dYjyzMcn36G",name:"p1",object:"entity"})
CREATE (:Entity {id:"dYjyzMcnHDR",name:"c1",object:"entity"})
CREATE (:Entity {id:"dYjyzMcnHDS",name:"c2",object:"entity"})
CREATE (:Entity {id:"dYjyzMcnWLd",name:"c3",object:"entity"})

MATCH (s)-[r:LIST { id: "dYjyzMcn36G" }]->(n)
WHERE n.id <> t.id
MERGE (t)-[:LIST { id: "dYjyzMcn36G" }]->(n)
DELETE r

MATCH (s)-[r:LIST { id: "dYjyzMcn36G" }]->(n)
WHERE n.id <> t.id
MERGE (t)-[:LIST { id: "dYjyzMcn36G" }]->(n)
DELETE r

MATCH (s)-[r:LIST { id: "dYjyzMcn36G" }]->(n)
WHERE n.id <> t.id
MERGE (t)-[:LIST { id: "dYjyzMcn36G" }]->(n)
DELETE r
````

Query:

````
MATCH (p:Entity { id: "dYjyzMcn36G" })
WITH p

MATCH (p)-[:LIST*1..3 { id: "dYjyzMcn36G" }]->(e:Entity)
WITH DISTINCT e SKIP 1 LIMIT 2
````

### Expected behavior

Should return (c2)->(c1) since (c3) should be skipped.

### Actual behavior

Returns (c3)->(c2) since apparently (c1) was skipped as result list was reversed.

The following query returns the expected results (note that DISTINCT has been removed):

````
MATCH (p:Entity { id: "dYjyzMcn36G" })
WITH p

MATCH (p)-[:LIST*1..3 { id: "dYjyzMcn36G" }]->(e:Entity)
WITH e SKIP 1 LIMIT 2
````

**Comment by systay** [comment]
Thanks for reporting!

If you want dependable ordering, you need to use `ORDER BY`. This is unfortunate, but one of the costs of using a declarative language. The planner/runtime will use what it thinks is the best plan, and if you don't specify ordering, that will not be taken into consideration.

**Comment by billscheidel** [comment]
So SKIP and LIMIT are basically random without ORDER BY in all cases?  That would be a good thing to document more clearly.

I know in general the ordering is unknown (such as with `MATCH (e:Entity) RETURN e`). However, it seems like list traversal deserves to be a special case where results are added to the result list in the order traversed.  Since `[:LIST*1..3]` takes the traversal order into account (it never suddenly decides to start looking at the end of the list), a SKIP or LIMIT on such a statement should as well.  And it does seem to work as expected, except when using DISTINCT.

**Comment by systay** [comment]
Good point. The manual is not at all explicit about this. /cc @petraselmer 

It's very important for the planner that ordering to be an explicit concern and not something coming out of the implementation details. We are working on lots of cool things to make queries faster, and a lot of these will result in ordering changing because of some new implementation detail. I think making ordering an explicit concern is a good way of making sure we don't accidentally break anyone's queries.

Of course, if you feel strongly about it, I suggest you bring it up with openCypher, maybe as a [CIR](https://github.com/opencypher/openCypher).

**Comment by systay** [comment]
By the way @billscheidel, have you looked at the two query plans? Could it be that the `DISTINCT` one is using `PruningVarExpand`?
