### ISSUE TITLE
3.2 - Backslash not used as escape character

### ISSUE THREAD

**Issue by meilechh** [neo4j/neo4j#10034]
I discovered that backslashes are not used as escape characters in version 3.2, tried the same thing in 3.1 and it worked as expected.
I also tried it in cypher-shell and it also worked as expected.

**Neo4j Version:** 3.2.3
**Operating System:** Oracle Linux
**API:** Javascript driver and Browser

### Steps to reproduce
Run this query in browser: `with "\\" as backslash return backslash;`

### Expected behavior
According to https://neo4j.com/docs/developer-manual/current/cypher/syntax/expressions/ result should be `\`.

### Actual behavior
Result is double backslash `\\`.

**Comment by sherfert** [comment]
We have confirmed this and we will deal with it.

**Comment by meilechh** [comment]
Thanks for the commit. Did it also fixed the problem in JavaScript driver?
