### ISSUE TITLE
Querying for two matches, where one involves a transitive closure, returns unexpected results

### ISSUE THREAD

**Issue by jfischer** [neo4j/neo4j#10048]
I have three nodes N1, N2, and N3. N2 has a relationship pointing to N1. N3 has a relationship that transitively points to N1. If I try to retrieve N2 and N3 in the same query, it only works if N2 and N3 have separate paths. If N2 is on the path to N1 from N3, then no results are returned. 

**Neo4j Version:** Community Edition 3.1.1
**Operating System:** MacOs 10.12.6
**API:** Neo4j Browser 2.0.0-M10

### Steps to reproduce
Set up a small graph of three nodes, where n3 => n2 => n1:
```
create (n1:Test {value:1});
create (n2:Test {value:2});
create (n3:Test {value:3});
match (n1:Test), (n2:Test) where n1.value=1 and n2.value=2 create (n2)-[r:REFERENCES]->(n1) return r;
match (n2:Test), (n3:Test) where n2.value=2 and n3.value=3 create (n3)-[r:REFERENCES]->(n2) return r;
```

Run a few basic queries as sanity checks:
```
match (n2:Test)-[:REFERENCES]->(n1:Test) where n1.value=1 return n1.value,n2.value;
// returns 1, 2
match (n3:Test)-[:REFERENCES]->(n2:Test) where n2.value=2 return n3.value,n2.value;
// returns 3, 2
match (n3:Test)-[:REFERENCES]->(n2:Test), (n2:Test)-[:REFERENCES]->(n1:Test) where n1.value=1 return n3.value, n2.value, n1.value;
// returns 3, 2, 1
```

The query that fails:
```
match (n3:Test)-[:REFERENCES*]->(n1:Test), (n2:Test)-[:REFERENCES]->(n1:Test) where n1.value=1 return n3.value, n2.value, n1.value;
```
### Expected behavior
The query should return 3, 2, 1

### Actual behavior
The query returns no results.

Note that the following query does succeed:
```
match (n3:Test)-[:REFERENCES*]->(n2:Test)-[:REFERENCES]->(n1:Test) where n1.value=1 return n3.value, n2.value, n1.value;
// returns 3, 2, 1
```
However, this alternative query does not handle the case where n3 uses a different path to n1, not along n2.

**Comment by sherfert** [comment]
For comma-seperated patterns in the same MATCH clause, we enforce relationship uniqueness. Since both patterns refer to the same relationship, no results can be found. Changing the query to
```
match (n3:Test)-[:REFERENCES*]->(n1:Test) MATCH (n2:Test)-[:REFERENCES]->(n1:Test) where n1.value=1 return n3.value, n2.value, n1.value;
```
gives you two results:
```
2,2,1
3,2,1
```
That is the expected result (given that you only expressed a predicate on node n1 in the WHERE clause).

For more details, refer to https://neo4j.com/docs/developer-manual/current/cypher/introduction/uniqueness/
