### ISSUE TITLE
Database backup fails in read-only mode

### ISSUE THREAD

**Issue by Gudahtt** [neo4j/neo4j#10089]
The command `neo4j-admin backup` fails if the database being backed up is in read-only mode.

**Neo4j Version:** 3.2.2 (Enterprise)
**Operating System:** Tested with the database running on Ubuntu 16.04, neo4j-admin was tested from Ubuntu 16.04 and Windows 10 v1703
**API:** neo4j-admin

### Steps to reproduce
1. Run neo4j-admin backup, pointed at a running database (either remotely or from the same machine)

### Expected behavior
It should create a backup of the running database

### Actual behavior
It fails with the following output:
`Doing full backup...`
`command failed: Backup failed: Unable to force ContractCheckingIndexProxy -> OnlineIndexProxy[accessor:org.neo4j.kernel.api.impl.schema.LuceneIndexAccessor@ae4d8a8, descriptor:Index( GENERAL, :label[39](property[51]) )]`

**Comment by chrisvest** [comment]
Thanks for the report. We're looking into it.
