### ISSUE TITLE
Transactional behavior when a query fail

### ISSUE THREAD

**Issue by nmervaillie** [neo4j/neo4j#10098]
Currently, executing a query within a transaction makes the transaction rollback.
It is described in the documentation [in the REST doc](https://neo4j.com/docs/developer-manual/3.2/http-api/#rest-api-handling-errors) and [in the reference doc](http://neo4j.com/docs/developer-manual/current/reference/status-codes/#_classifications).

Unless I missed something, it is an intended behavior and has been discussed in #4137 and #5258.

However, for some errors like ClientError, it could be interesting to let the application side decide if it wants to rollback or not, for example :

- integrating data from legacy systems could lead to constraint violations, which can sometimes be considered as "normal". In that case, the application may want to continue processing within the same transaction.
- integrating in an environment like Spring / SDN, in which the transaction manager is supposed to decide of the issue of transaction, according to the kind of error being raised.

To be a bit more specific about Spring / SDN : the current behavior is not compatible with Spring's [declarative transaction management](https://docs.spring.io/spring/docs/current/spring-framework-reference/html/transaction.html#transaction-declarative). In case of error when executing a query, regardless of what's declared in the application code, the transaction will always be rollbacked by Neo4j.

Unless there are technical limitations, please consider having explicit transactions driven by the application side, and not by the result of query execution (at least for ClientError).

**Comment by nmervaillie** [comment]
https://jira.spring.io/browse/DATAGRAPH-995

**Comment by zhenlineo** [comment]
We've discussed within team and the the current behaviour is more clear in the general case that all errors shall be rollback. We aware that there might be some cases that your suggestion is really valid. We will take your suggestion and consider it in our development descriptions.

Thanks again for raising this issue.
