### ISSUE TITLE
Presence of an index corrupts query results

### ISSUE THREAD

**Issue by EugeneWagner** [neo4j/neo4j#10132]
**Neo4j Version:** 3.3.0-beta02
**Operating System:** Windows7

## How to Reproduce
###Create a small graph with 4 Nodes

`create (:Person{id:1, name:'Bob', version:1});`
`create (:Person{id:1, name:'Bob', version:2});`
`create (:Person{id:2, name:'Sam', version:1});`
`create (:Person{id:2, name:'Sam', version:2});`

###Run a simple query:
`match(p1:Person{id:1}), (p2:Person{id:2}) return distinct p1.id,p2.id;`
(returns "1, 2")

###Corrupt things by adding an index
`create Index on:Person(id);`

###Rerun the same query
`match(p1:Person{id:1}), (p2:Person{id:2}) return distinct p1.id,p2.id;`
(returns "1, 2  \n 2, 2")

A Snipit of my Browser was attached as "Browser.PNG"
![browser](https://user-images.githubusercontent.com/32197608/30745284-c9f2b9d8-9fa5-11e7-945b-8e20c057ec9b.PNG)

**Comment by wil222** [comment]
I dont have this issue one 3.1.4 on linux mint

**Comment by sherfert** [comment]
We've confirmed the bug and we're working on it.

**Comment by sherfert** [comment]
This has been solved by #10200 :)
