### ISSUE TITLE
Change edge type

### ISSUE THREAD

**Issue by 2gavy** [neo4j/neo4j#10181]
How do I change an existing edge type? I am already able to change my existing node type with no issues.

Thank you in advance.

**Comment by chrisvest** [comment]
You can't. Node labels and relationship types are not the same in that respect. You have to delete and recreate the relationship. APOC has a `apoc.refactor.setType(rel, 'NEW-TYPE')` produce to help with this, though: https://neo4j-contrib.github.io/neo4j-apoc-procedures/index32.html#_graph_refactoring_3
