### ISSUE TITLE
OSX Build Instructions don't mention java8 requirement

### ISSUE THREAD

**Issue by eastlondoner** [neo4j/neo4j#10225]
As of September java 9 is the current version of java. OSX users on who have installed jdk with homebrew will now have java 9.

This project uses maven plugins that are not compatible with java 9 and `mvn install` fails with java API exceptions when mvn is using java 9.

I think that wither the README should be changed to explicitly warn OSX users that they should be using java 8 or the maven plugins should be updated to java 9 compatible versions.

**Comment by eebus** [comment]
@eastlondoner 
Thanks for the feedback. 
We have some docs on the required version in the manual https://neo4j.com/docs/operations-manual/3.3/installation/requirements/ .

**Comment by eastlondoner** [comment]
Hi @eebus 

With the Ubuntu instructions it's made clear:

> With apt-get on Ubuntu
> `apt install maven openjdk-8-jdk`

I'm talking about people who are using the GitHub repository to build Neo - I don't think it should be expected that they go spelunking the operations manual looking for information on how to build an open source project.

All I think you need to do is add a section in the readme OS X section warning people that java9 will cause problems. I can make a PR if you would like an example

**Comment by eebus** [comment]
Oh 
Agree that seems like something we should add.
Feel free to make a PR, will also forward to the team that has edited that part of the README.

**Comment by eebus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [OSX Build Instructions don't mention java8 requirement](https://trello.com/c/mzdvHQSP/2778-osx-build-instructions-dont-mention-java8-requirement)

**Comment by craigtaverner** [comment]
@eastlondoner I don't see a PR or a change to the README. Perhaps more recent work to support newer JVM's has reduce the need. But feel free to make the PR or re-open this issue.
