### ISSUE TITLE
neo4j-import: Support glob patterns

### ISSUE THREAD

**Issue by freethejazz** [neo4j/neo4j#10221]
When running `neo4j-import` (or it's eventual successor, `neoj-admin import`), it's possible to list several CSV files per node or relationship being created:
```
--nodes:User user-headers.csv,users-data-1.csv,users-data-2.csv,users-data-3.csv
```

This feature is super helpful but I've found myself wanting to be able to add many CSVs programmatically, which can be quite cumbersome. For example, when writing CSVs using spark, you end up with a directory with many CSV files (`part-00000...,part-00001...,etc`). It would be super helpful if the import tool would accept glob patterns, like:
```
--nodes:User user-headers.csv,users-data-*.csv
```

Is that something that you all would be interested a contribution for? If so, do you have any thoughts on design or other considerations before I start?

**Comment by tinwelint** [comment]
It's supported already. The pattern you write will have to be regex, so in your example:

`--nodes:User user-headers.csv,users-data-.*\.csv`

or simply

`--nodes:User user-headers.csv,users-data-.*`

**Comment by MishaDemianenko** [comment]
As @tinwelint pointed out it's already supported, so will close this issue. Feel free to reopen if the problem remains.
