### ISSUE TITLE
Process dying after a few seconds due to missing regkey

### ISSUE THREAD

**Issue by TomMaier1** [neo4j/neo4j#10234]
Hello,

I would like to report the following bug.

- Neo4j version: 3.2.6
- Operating system: Windows 10 RS2
- API/Driver: none
- **Steps to reproduce**
- Expected behavior
NeoJS launching successfully
- Actual behavior
Process NeoJS starting but dying after a few seconds

After a short troubleshooting I found out that NeoJS was trying to read a regkey that didn't exist

HKU\S-1-5-21-1659004503-2025429265-725345543-164945\SOFTWARE\ej-technologies\exe4j\pids\

I created it manually and NeoJS would start up successfully again.

I have attached the ProcMon logfile for your investigation on this.

If you have any questions feel free to ask me.

Cheers,
Tom Maier

[NeoJS regkey missing.zip](https://github.com/neo4j/neo4j/files/1368498/NeoJS.regkey.missing.zip)

**Comment by zhenlineo** [comment]
Hi @TomMaier1,
NeoJs is not maintained by us. If you have any problem to use NeoJs with Neo4j, maybe you want to raise the issue there https://github.com/PaulFreund/neojs?
Pls be free to reopen this issue if it is a issue related to Neo4j directly.

Cheers,
Zhen
