### ISSUE TITLE
Database has encountered ... (tx recovery/restart) doesn't mark server offline

### ISSUE THREAD

**Issue by tim-hanssen** [neo4j/neo4j#10230]
When the Neo4j server runs out of disk space an exception "Database has encountered some problem, please perform necessary action (tx recovery/restart)" is triggered.

From that moment the server will not process any requests. But the server keeps marked as 'available' in the cluster.

**Config**
- Neo4j version: 3.2.2 Enterprise
- Operating system: Ubuntu 14.04 LTS (trusty) 64bit
- API/Driver: Cypher

**Expected behavior**
Server should be marked as 'unavailable' so that the proxy can switch to other slaves.

**Comment by martinfurmanski** [comment]
Sorry about the slow response. I agree with your analysis and rough design of how it should work. This is unfortunately not a common problem in practice, so we haven't really got around to prioritising it. I will keep you informed of any progress though.

**Comment by RagnarW** [comment]
Closing due to unsupported version
