### ISSUE TITLE
Thoughts on updating to Jetty 9.4.x or relocating the classes via shading rules

### ISSUE THREAD

**Issue by nicktrav** [neo4j/neo4j#10238]
Jetty 9.4 has been available for a while now (Jan 2017). The neo4j project currently uses the 9.2.x branch.

Internally we run services that depend on Neo4j in a monorepo setup, so all third-party dependencies are pinned to a specific version. We use Jetty as our web server, which means that to enable us to update to Jetty 9.4, we either have to shade out the version of Jetty used in neo4j, or update the version of Jetty to 9.4 in neo4j. Both of these we'd have to do to a forked version of neo4j. We've gone with the latter for now.

Wondering what the appetite is for either updating to Jetty 9.4 or providing a shading rule to relocate the Jetty classes, so that downstream projects do not have to match versions themselves?

In the case of the former, we're happy to offer up what we have used internally to bump the Jetty version. It was a minimal patch.

**Comment by chrisvest** [comment]
In my opinion, that's the cost of embedding. You can in your own project create a module dedicating to pulling in the Neo4j dependencies and expose itself in whatever shaded form you prefer, and then the rest of your project depends on that. That way you shouldn't need to outright fork Neo4j. Likewise if you exclude Jetty from the transitive Neo4j dependencies and enforce your own version, assuming 9.4 if sufficiently compatible.

**Comment by nicktrav** [comment]
Not exactly sure why this ticket was closed so hastily? I was hoping for an answer to my questions. 

Opinions about other workflows and build styles aside, is there any plan to at least update the version of Jetty used in Neo4j?

While the 9.2.x branch is still actively developed, both 9.3 and 9.4 have been available for some time now. We're more than happy to offer a patch to update Neo4j to 9.4 (it compiles and tests clean).

Failing that, if upgrading _isn't_ an option, a common alternative is to relocate the packages of your dependencies, so clients of your code don't have to worry about version mismatches (coincidentally, [Apache Spark does this for Jetty](https://issues.apache.org/jira/browse/SPARK-3996)).

Unfortunately, excluding Jetty isn't an option when the underlying Jetty APIs have changed.

**Comment by chrisvest** [comment]
We tried upgrading a while back ourselves a little while back and ran into problems in Jetty itself. We are waiting for them to produce a 9.4 release that includes this fix: https://github.com/eclipse/jetty.project/commit/7768a781bec1c0686906649f241ead99776a40cd

I think you can continue with your fork work around until we have a release out with Jetty 9.4.

A PR with your upgrade might interest @praveenag who knows more about the problems we ran into in our first upgrade attempt.

**Comment by nicktrav** [comment]
That sounds reasonable, thanks!

fwiw - our Neo4j fork runs fine with Jetty 9.4.6. We ran into the same issues with 9.4.7.

**Comment by nmervaillie** [comment]
This is also an issue for SDN users who use recent Spring Boot versions and run tests with the test harness (`ClassNotFoundException`s).
Observed running Spring Boot `2.0.0.M5`, depending on jetty is `9.4.7.v20170914`.

**Comment by fbiville** [comment]
FWIW, same thing with Spring Boot 1.5.8.RELEASE (same Jetty version).

**Comment by tommichiels** [comment]
Same issue here Spring Boot 2.0.0.M5 problems with test-harness.

**Comment by tommichiels** [comment]
By the way made a workaround by using tomcat as my servlet engine in test scope. 

this is the definition i use to force the usage of tomcat.

@Configuration
@AutoConfigureBefore(ServletWebServerFactoryAutoConfiguration.class)
public class ForceTomcat {

    @Bean
    TomcatServletWebServerFactory tomcat() {
         return new TomcatServletWebServerFactory();
    }
}

**Comment by fbiville** [comment]
@chrisvest the bugfix you mentioned seems to be included in release `jetty-9.4.8.v20171121`

**Comment by nicktrav** [comment]
Bump. @chrisvest - thoughts on updating Jetty now that the issue is resolved upstream?

**Comment by praveenag** [comment]
@nicktrav https://github.com/neo4j/neo4j/pull/10927 :)

**Comment by chrisvest** [comment]
Closing because we're using Jetty 9.4.8.v20171121 since Neo4j 3.4-alpha8.
