### ISSUE TITLE
Missing bolt configuration documentation

### ISSUE THREAD

**Issue by senica** [neo4j/neo4j#10254]
Here: https://neo4j.com/docs/operations-manual/3.1/reference/configuration-settings/

I know of three that are not documented on the website...at least not that I can see

This changes the address that the browser uses to connect to bolt
**dbms.connector.bolt.advertised_address=:7688**

This changes the address that the server listens to bolt on. This and the top address might be different, if say, you are using docker. You could change the above setting, and leave this alone and then in docker expose port 7688:7687 and the neo4j browser would connect to 7688. If however, you are installing directly on server, you would need to change this as well to listen to port 7688
**dbms.connector.bolt.listen_address=:7688**

This changes the port that the browser uses. Instead of using localhost:7474, this would be localhost:7475
**dbms.connector.http.listen_address=:7475**

These were crucial to me in setting up a test environment.

**Comment by mariascharin** [comment]
@senica I apologize for the very late response on this issue!

All the connector configuration is available on the dedicated page https://neo4j.com/docs/operations-manual/3.1/configuration/connectors/ (or https://neo4j.com/docs/operations-manual/current/configuration/connectors/ for the most recent release).

Regards,
Maria
