### ISSUE TITLE
Neo4j Match (n:Label) return n Empty result while such nodes are present in db.

### ISSUE THREAD

**Issue by chaudharyakash** [neo4j/neo4j#10266]
- Neo4j version:  3.0.5
- Operating system: macOsSierra
- Neo4j `Match (n:Label) return n` Empty result while such nodes are present in db. but `Match (n) where "Label" in labels(n)  return n` returns nodes that have labels.
-  `127.0.0.1:7474` I click on Labels returns empty result .
-  This might be portability issue I created database using Neo4j version: 3.1.1.

**Comment by sherfert** [comment]
Hi @chaudharyakash 
Sorry for the late reply. Do you have any additional information we can use? Can you get us a copy of the corrupted store? Has the problem been resolved? Thanks

**Comment by sherfert** [comment]
No reply... feel free to reopen
