### ISSUE TITLE
possible bug when returning boolean values

### ISSUE THREAD

**Issue by HassanHashemi** [neo4j/neo4j#10285]
i have this cypher query which yields to 
`  (no changes, no records)`
if x is null

    Match(x:Music_Music) where x.musicID = 106565650 return x is not null as Exists;

if it is not null it returns as expected "Exists = true"

expected result "Exists = false"

**Comment by fbiville** [comment]
If nothing matches your pattern, no rows will be produced and the result will not contain any records.

Therefore, the expected result of your query is: no records.

**Comment by HassanHashemi** [comment]
@fbiville if nothing matches the pattern then the variable "m" should be null and therefore the `x is not null` should be evaluated to false rather than nothing.
am i reasoning correctly?

**Comment by fbiville** [comment]
Think of the query result as a table.

`RETURN` produces as many rows as there are `Music_Music` matched nodes (as defined per your `MATCH` and `WHERE` clauses). 

If nothing is matched, no rows are produced.
If you want to coalesce `x` as `null`, you should use `OPTIONAL MATCH`.

Does it make sense?

**Comment by HassanHashemi** [comment]
@fbiville yeah, i think it makes sense now.

**Comment by HassanHashemi** [comment]
@fbiville however what is the value of x if the predicate dose not match, should`nt it default to "null" ?

**Comment by fbiville** [comment]
If the pattern does not match, there won't be any x.
If you were to rephrase in a more imperative fashion:

 1. scan all nodes of label `Music_Music`
 2. filter these nodes by property `musicID`, it must equal 106565650
 3. **for each of the matching nodes**, project the column `Exists` as the result of the null check of each node

If the predicate does not match, your return is ignored and you get no result.
That's not a bug, it works as it should.

We can continue the conversation of neo4j-users.slack.com / in #help-cypher channel if you have more questions or need more explanations, no harm in learning! :)

Meanwhile, the issue can be closed as there really is no bug about this.

**Comment by HassanHashemi** [comment]
@fbiville thanks, closing the issue.
