### ISSUE TITLE
New Feature : Exploring paths against a given node 

### ISSUE THREAD

**Issue by grv1207** [neo4j/neo4j#10301]
Hi, I was wondering if there some API in neo4j that we can use to explore paths around a given node and then restrict our traversing to a particular depth? Because I'm using a cypher query to explore such paths but it takes a lot of time when the path length is more than 2 and also when we have multiple relations between same set of nodes

**Comment by sherfert** [comment]
Hi @grv1207 and thanks for your question.

You can use a variable length path expression and then express predicates on nodes or relationships of that path path, e.g.

```
MATCH p=(n:Label)-[*1..2]->(m)
WHERE all(x IN nodes(p) WHERE exists(x.property))
```

Would that work for your particular case?

**Comment by grv1207** [comment]
Hello @sherfert I\m already using a cypher query, but it is really slow when I give a path length of more than 2 and in many cases I my browser never returns result

**Comment by grv1207** [comment]
I was using
 Match p =  (n{ConceptID: '<>'})-[*2..5]-(m) 
WHERE ALL (r IN relationships(p) WHERE r.RelationLabel CONTAINS "<>")
RETURN p
and it is not very optimal when the graph is dense. In my case I have around 15 millions nodes and 27 relationships

**Comment by sherfert** [comment]
In that case you are not asking for an API (you basically found it) but rather experiencing a performance problem, did I get that right? Or is there anything you are missing from that syntax that you think could make the query execute this in a faster way?

**Comment by grv1207** [comment]
@sherfert  I'm really not sure how I can speed up the query. I think  doing this at at low level(JAVA) would be fast.

**Comment by sherfert** [comment]
Sorry for getting back so late. If you know the labels of `n` and `m` and your relationships, you can insert them in the query and that should speed up the query, at least somewhat.

E.g.

```
Match p = (n:NodeLabel {ConceptID: '<>'})-[:RelLabel *2..5]-(m:OtherNodeLabel)
WHERE ALL (r IN relationships(p) WHERE r.RelationLabel CONTAINS "<>")
RETURN p
```

Using the low level API is usually faster, but it comes at the cost of less flexibility.

**Comment by craigtaverner** [comment]
If you are happy writing Java code, the low level API is accessible in two ways, either directly when using Neo4j as an embedded library, or by writing a procedure.  The relevant part of the Java API for your case would be the TraversalDescriptor, which has a fluent API for creating a specification of graph traversal, which you then run starting at your start node. There are many examples online (search for Neo4j Traversal). One some example I wrote is at https://github.com/neo4j-contrib/spatial/blob/master/src/main/java/org/neo4j/gis/spatial/rtree/RTreeIndex.java#L695.

For information on writing procedures that can be called from Cypher, so you can embed your custom Java code in the server and still access it from remote client code using Cypher, refer to the documentation. https://neo4j.com/docs/java-reference/current/#server-extending

**Comment by craigtaverner** [comment]
Can we assume that the information on writing a procedure using the traversal API is a sufficient answer to your question?

On the other hand, the Cypher query you wrote should not produce memory issues, as Cypher uses a depth-first search to avoid maintaining too much state. Could you tell us which version of Neo4j you experienced this issue on?
