### ISSUE TITLE
Publish SHA hash for Neo4j releases

### ISSUE THREAD

**Issue by billscheidel** [neo4j/neo4j#10307]
Currently, none of the download links on https://neo4j.com/download/other-releases/ include a SHA hash for verifying the integrity of the download.  It would be great if this information could be published along side the links (see https://www.elastic.co/downloads/elasticsearch or https://github.com/antirez/redis-hashes/blob/master/README for examples).

**Comment by aileenrose** [comment]
Yes, indeed. I will forward this request to our build team.  Thank you!

**Comment by jennyowen** [comment]
Closing this because it looks to have been implemented: 
https://neo4j.com/download/other-releases/ :tada:
