### ISSUE TITLE
Cypher query doesn't use index when querying using property IN STR_ARRAY

### ISSUE THREAD

**Issue by Meatballs1** [neo4j/neo4j#10310]
Profiling the following query gave a NodeLabelScan rather than a NodeIndexScan when using a WHERE statement IN a list of string values:

```
MATCH (object2:LABEL) WHERE object2.name = "blah"
WITH object2
MATCH (object:LABEL) WHERE object.ID IN object2.allowedIDs
RETURN object
``` 

Michael suggested doing 

```
MATCH (object2:LABEL) WHERE object2.name = "blah"
WITH object2.allowedIDs AS allowedIDs
MATCH (object:LABEL) WHERE object.ID IN allowedIDs
RETURN object
```

which correctly did a NodeIndexSeek.

Note when allowedIDs was empty [] it did a NodeIndexSeek.

**Comment by sherfert** [comment]
Pretty good find, thank you!

Setup can be done with

```
CREATE INDEX ON :LABEL(ID)
CREATE (:LABEL {ID: 1})
CREATE (:LABEL {name: "blah", allowedIDs:[1], singleID: 1})
```

Interestingly, this also produces the worse plan

```
EXPLAIN MATCH (object2:LABEL) WHERE object2.name = "blah"
MATCH (object:LABEL) WHERE object.ID = object2.singleID
RETURN object
```

**Comment by sherfert** [comment]
The problem with this is that whether the `NodeIndexSeek` is the best plan, depends on the length of `allowedIDs`. So a heuristic that always plans it can lead to regressions for longer lists. A cost evaluation of the alternatives would be the right thing to do here. Unfortunately, that is not so easy to include at this part. We decided, for now, not to fix this problem. I hope you understand.

**Comment by sherfert** [comment]
The problem with this is that whether the `NodeIndexSeek` is the best plan, depends on the length of `allowedIDs`. So a heuristic that always plans it can lead to regressions for longer lists. A cost evaluation of the alternatives would be the right thing to do here. Unfortunately, that is not so easy to include at this part. We decided, for now, not to fix this problem. I hope you understand.
