### ISSUE TITLE
Use of maps in patterns works inconsistently in WHERE clause

### ISSUE THREAD

**Issue by szarnyasg** [neo4j/neo4j#10316]
In `MATCH` clauses, maps can be added to nodes/relationships to filter results. This also works in `WHERE`, but with some inconsistencies, as the examples demonstrate.

- Neo4j version: 3.2.6
- Operating system: Ubuntu 16.04
- API/Driver: web browser

### Steps to reproduce and actual behaviour

Create a sample dataset:

```
CREATE (n:Label {prop1: 'a'})-[:REL {prop2: 'b'}]->({prop3: 'c'})
```

Run the following queries:

```
MATCH (n:Label {prop1: 'a'})--()
RETURN n
```

```
MATCH (n)
WHERE (n:Label {prop1: 'a'})--()
RETURN n
```

Both of these work fine and return the node with the label `Label`.

Try to remove the `--()` from the WHERE clause:

```
MATCH (n)
WHERE (n:Label {prop1: 'a'})
RETURN n
```

This does not compile:

```
Invalid input 'R': expected whitespace, comment or a relationship pattern (line 3, column 1 (offset: 39))
"RETURN n"
 ^
```

It seems that if there is only a single node, the compiler treats it differently than for chain of nodes-relationships. Actually, once we have a pattern chain, adding properties works fine.

```
MATCH (n)
WHERE (n:Label {prop1: 'a'})-[{prop2: 'b'}]-({prop3: 'c'})
RETURN n
```

This also returns the node with `Label`.

## Expected behavior

To resolve this inconsistency:

* either all queries above should compile
* or it should be forbidden to use maps for filtering in the `WHERE` clause.

**Comment by sherfert** [comment]
Hi. You are right that the current state is inconsistent. There is a lot of work going on in openCypher to introduce subqueries which is very related and would add a new and consistent syntax.

Check out https://github.com/opencypher/openCypher/pull/217

**Comment by InverseFalcon** [comment]
Just to note, the approach for these queries is not performant.

```
EXPLAIN MATCH (n)
WHERE (n:Label {prop1: 'a'})-[{prop2: 'b'}]-({prop3: 'c'})
RETURN n
```

This will first perform an all nodes scan, and then attempt to filter them based upon the pattern. That will result in increasingly bad performance as the number of nodes in the database grows. We do not recommend using this approach for your queries.

**Comment by fickludd** [comment]
Pending a formalization from OpenCypher, we will not change the current Neo4j Cypher to support Pattern maps in `WHERE` clauses. The current syntax allows expressing the wanted query as

```
MATCH (n)
WHERE n:Label AND properties(n) = {prop1: 'a'}
RETURN n
```
