### ISSUE TITLE
[feature] Prometheus endpoint for metrics

### ISSUE THREAD

**Issue by giannello** [neo4j/neo4j#10320]
The current version of neo4j supports exposing metrics with CSV files or by pushing them to Graphite (https://neo4j.com/docs/operations-manual/3.2/monitoring/metrics/)

It would be great to have an http endpoint reporting metrics in the prometheus format (https://prometheus.io/docs/instrumenting/exposition_formats/) so that they can be collected.

**Comment by adamrothman** [comment]
Alternatively, there could be a separate exporter (see https://prometheus.io/docs/instrumenting/exporters/). But +1! Would be awesome to get Neo4j metrics in Prometheus.

**Comment by klaren** [comment]
PR #10613 is up. This will most likely be in the next alpha release, would be wonderful if you could give it a spin once it's available, I'll keep you posted.

**Comment by giannello** [comment]
Thanks @klaren , will roll it out in our staging environment as soon as the docker image is available.

**Comment by klaren** [comment]
Docker images are available at https://hub.docker.com/r/neo4j/neo4j-experimental/tags/

**Comment by giannello** [comment]
Awesome, thanks
