### ISSUE TITLE
question

### ISSUE THREAD

**Issue by markk12** [neo4j/neo4j#10335]
i d like to try neo4j . it is my first graph database. I m a curiosity about cypher language:
neo4j makes a index call for every vertex subquery and edge subquery present in the query? Pratically neo4j make many index calls for every query right?

**Comment by chrisvest** [comment]
No, Neo4j uses index-free adjacency to traverse directly between neighbouring vertices. This is called "expand" in query terminology. Prefix your queries with `PROFILE ` or `EXPLAIN ` to see what they do.
