### ISSUE TITLE
Unable to start neo4j server with server plugin jar file

### ISSUE THREAD

**Issue by grv1207** [neo4j/neo4j#10346]
I have created 2 server separate server plugins and copy them one by one to start neo4j server. With one jar file I'm able to start the server, but with other I'm unable to start the server and get error on CLI.
   

- Neo4j version: 3.2.0
- Operating system: (Ubuntu 16.04
- API/Driver: Java API

### Expected behavior
I should be able to start the server with any jar file

### Actual behavior
instead I get en error
Okt 26 13:01:05 gaurav-GB-BSi3-6100 neo4j[24787]: at org.neo4j.kernel.impl.proc.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:146) Okt 26 13:01:05 gaurav-GB-BSi3-6100 neo4j[24787]: at org.neo4j.kernel.impl.proc.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:118) Okt 26 13:01:05 gaurav-GB-BSi3-6100 neo4j[24787]: at org.neo4j.collection.PrefetchingRawIterator.peek(PrefetchingRawIterator.java:50) Okt 26 13:01:05 gaurav-GB-BSi3-6100 neo4j[24787]: at org.neo4j.collection.PrefetchingRawIterator.hasNext(PrefetchingRawIterator.java:36) Okt 26 13:01:05 gaurav-GB-BSi3-6100 neo4j[24787]: at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProcedures(ProcedureJarLoader.java:91) Okt 26 13:01:05 gaurav-GB-BSi3-6100 neo4j[24787]: at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProceduresFromDir(ProcedureJarLoader.java:82) Okt 26 13:01:05 gaurav-GB-BSi3-6100 neo4j[24787]: at org.neo4j.kernel.impl.proc.Procedures.start(Procedures.java:275) Okt 26 13:01:05 gaurav-GB-BSi3-6100 neo4j[24787]: at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434) Okt 26 13:01:05 gaurav-GB-BSi3-6100 neo4j[24787]: ... 11 more Okt 26 13:01:05 gaurav-GB-BSi3-6100 neo4j[24787]: 2017-10-26 11:01:05.344+0000 INFO Neo4j Server shutdown initiated by request

**Comment by Lojjs** [comment]
@grv1207 Thanks for reporting, this looks like a bug. We will investigate it and come back to you.
/Louise, Neo4j Cypher Team

**Comment by craigtaverner** [comment]
@grv1207 Can you tell us more about this issue. The stack trace does not seem complete, as there is no actual error, only the last part of the stack trace. Could you do the following:

* Send the entire stack trace with error included (or attached the neo4j.log file)
* Tell us more about the plugins you installed, which ones and which versions

We know of an issue where plugins that depend on different versions of 3rd party libraries could conflict with one another, and it would be useful to know if this is the same issue, and if so which 3rd party libraries are causing the conflict.

**Comment by grv1207** [comment]
@craigtaverner, I investigated the issue and found that because I was not properly initializing the class name inside the server plugin file that was causing such error.

 However it would be very useful if a full stack trace error  mechanism is implemented in future version as the error message that I have pasted above is the only thing that I see in my terminal and in many cases I'm clueless as to what could be the exact error and I have to start again from scratch in order to get clear idea.
