### ISSUE TITLE
"Expected to be a property container" error for certain Cypher statements after 3.1.2 -> 3.3.0 upgrade

### ISSUE THREAD

**Issue by heavydawson** [neo4j/neo4j#10353]
I discovered that certain cypher queries were no longer working after an upgrade from 3.1.2 -> 3.3.0. the failures were the same with all clients
**Neo4j Version:** 3.3.0
**Operating System:** OSX / CentOS  
**API:** neo4j-rb / neo4j browser

### Steps to reproduce
1. Queries of the following form previously worked without issue:
```
MATCH (n:LBL1 {prop0:'foo'})-[]->(o:LBL1 WHERE EXISTS(o.prop1) WITH o OPTIONAL MATCH (o)-[:rel1]->(p:LBL2) WITH p OPTIONAL MATCH (p)-[:rel2]->(e:LBL3) WHERE p.prop2 IS NOT NULL RETURN p
```
2. This was working without issue in Neo4j 3.1.2. However it fails immediately in 3.3.0 with the following error:
```
Neo.ClientError.Statement.TypeError
Expected p to be a property container.
```
3. Removal of the final WHERE seems to fix the issue:
```
...WHERE p.prop2 IS NOT NULL...
```
4. It appears the combination of OPTIONAL MATCH + WITH + WHERE is causing the issue. 

### Expected behavior
Existing CYPHER queries should run without issue on 3.3.0, unless otherwise stated in the upgrade notes

### Actual behavior
Existing Cypher queries break with cryptic errors when they match a certain criteria

**Comment by NickG123** [comment]
In case it helps narrow down the problem, I also experienced this issue when updating from 3.2.6 to 3.3.0.

**Comment by lfrancisxavier** [comment]
Me too. the cypher which is working on 3.1.1 (CE) started throwing the above said error in 3.3.0 (CE)

**Comment by InverseFalcon** [comment]
This is related to a similar recently-fixed bug, the cypher team will be taking a look at this one to see if it requires a separate fix.

**Comment by Lojjs** [comment]
@heavydawson @NickG123 @lfrancisxavier Thanks for reporting this quite serious bug on our 3.3 community version. As @InverseFalcon noted we have been working on a related bug fix and I have confirmed that it also solves your problem. As soon as the next patch release is out your code will work as before, thanks for your patience! /Louise, Cypher team

**Comment by heavydawson** [comment]
@Lojjs thanks!
