### ISSUE TITLE
Dot Problem in Query

### ISSUE THREAD

**Issue by akyuznurettin** [neo4j/neo4j#10388]
Hi, I have a problem that is specific. After I load the triples from RDF file with plugins, some properties or relations are look like 

Relation Example ===>             [:Country.city] 
Property Example ==>               city.name
 
there is a dot between these words. They can be created with plugins There is  no problem. But when i write query from this 127.0.0.1:7474 interface, i cant write dot '.'  to write property name or relation name.  But the property name is contain dot. I need to write it . 

Query Example MATCH (x)-[:Contain]->(y) WHERE x.city.name="London" RETURN x,y 

Query Example MATCH (x)-[:Country.city]->(y) RETURN x,y

Result : Syntax error invalid input '.'

How can I write correctly this propertie or relation name?

**Comment by chrisvest** [comment]
You can quote the names with backticks. Something like this:

```
MATCH (x)-[:Contain]->(y) WHERE x.`city.name`="London" RETURN x,y
MATCH (x)-[:`Country.city`]->(y) RETURN x,y
```

**Comment by akyuznurettin** [comment]
Thank you. It works. 👍
