### ISSUE TITLE
Poor write performance with neo4j 3.2.3

### ISSUE THREAD

**Issue by cloudhuang** [neo4j/neo4j#10395]
For developing with neo4j, I need sync my data to neo4j on **online mode**, so seems what I can do is only execute the query via the session. ~LOAD CSV~ cypher shell or batch import etc... need the neo4j in offline mode.

The sample query is like

```
MERGE n1 ON CREATE SET .... ON MATCH SET n1.XXX = YYY, ......
MERGE n2 ON CREATE SET .... ON MATCH  SET n2.XXX = YYY, ......
....

MATCH (n1{ID: ""})
MATCH (n2: {ID: ""})
MERGE (n1)-[r:REL]->(n2)
ON CREATE SET
.....
ON MATCH SET
r.XXX = YYY
......
```
(the query is generated based on the real data )

So I used the pure ogm driver to execute the pre-parsed cypher query, no parameter indeed.

but I got the poor write performance actually, my server has 40 cores, 30G mem, SSD disk,  following is the basis neo4j configuration for the memory:

```
dbms.memory.heap.initial_size=14g
dbms.memory.heap.max_size=14g

dbms.memory.pagecache.size=10g
```

and also I created the index for nodes(ID), then I create 40 threads with dedicated session to execute the query above, but I only get almost 1000 query/second write performance in my test environment where I have ~400GB data need to sync to neo4j database.

![image](https://user-images.githubusercontent.com/4601460/32530851-90bb484c-c47b-11e7-9a7c-8ed9a272932a.png)

And for the huge write query, the neo4j service will become unavailable, I cannot login with neo4j browser.
![image](https://user-images.githubusercontent.com/4601460/32533451-baa13a3a-c48b-11e7-865b-184bd5fc7199.png)

**Comment by jexp** [comment]
*You're missing a label in your queries. *

If you profile them you'll see nonindrx is used. 

OGM is not the best for mass updates if you want to push all the data through. If you only call a proc or command it's fine though 

Only neo4j-import needs offline, the rest not

You can use load csv with periodic commit easily

And if you want to parallelize check out load csv to drive the update in apoc.periodic.commit

**Comment by jexp** [comment]
SEe also http://jexp.de/blog/2017/03/5-tips-tricks-for-fast-batched-updates-of-graph-structures-with-neo4j-and-cypher/

**Comment by cloudhuang** [comment]
@jexp Thanks, its has the concrete label and I created the index for the necessary fields indeed.

**Comment by sherfert** [comment]
@cloudhuang have you been able to see any performance improvements when not using an OGM?

**Comment by cloudhuang** [comment]
@sherfert , due to the business requirements, I cannot dump the data to neo4j in offline mode, so seems LOAD CSV or CREATE/MERGE is the only way, but the performance still not good for now.

**Comment by jexp** [comment]
Are you using parameters?
Why do you use `on match set`?

Did you change your import query to unwind of batches of $rows parameters?

**Comment by cloudhuang** [comment]
@jexp I also need to update the node properties after next run, so add the `on match set` to update the properties. no parameters used, I generated all the query with concrete data.
(Sorry for the sample cypher query and I updated it to remove the confusing)

**Comment by cloudhuang** [comment]
@sherfert Sorry for missing your message, as I need to update the data in online mode, so now I'm using LOAD CSV and the performance is better then using OGM as it can use the "batch" mode with PERIODIC COMMIT, thanks.
