### ISSUE TITLE
Transient Cypher SyntaxError with pattern relationhhsip UNNAMED1

### ISSUE THREAD

**Issue by tathamoddie** [neo4j/neo4j#1040]
This query, works ~95% of the time:

    START story=node:Stories({p0})
    MATCH story<-[?:USER_POSTED_STORY]-poster,story-[?:STORY_TAGGED_COMMODITY]->commodity
    WHERE 1=1 AND commodity.Name IN ["Chromite"]
    WITH story, poster, collect(commodity) as commodities
    RETURN story AS StoryNode, poster AS PostedBy
    ORDER BY story.DateCreated DESC
    LIMIT {p1}

About 5% of the time in production, it results in an HTTP 400 Bad Request from the REST API.

Neo4j 1.9.2.

The response from Neo4j is:

    {
        "message" : "Can't re-use pattern relationship ' UNNAMED1' with different start/end nodes.",
        "exception" : "SyntaxException",
        "fullname" : "org.neo4j.cypher.SyntaxException",
        "stacktrace" : [ "org.neo4j.cypher.internal.executionplan.builders.PatternGraphBuilder$$anonfun$buildPatternGraph$3.apply(MatchBuilder.scala:99)", "org.neo4j.cypher.internal.executionplan.builders.PatternGraphBuilder$$anonfun$buildPatternGraph$3.apply(MatchBuilder.scala:93)", "scala.collection.immutable.List.foreach(List.scala:309)", "org.neo4j.cypher.internal.executionplan.builders.PatternGraphBuilder$class.buildPatternGraph(MatchBuilder.scala:93)", "org.neo4j.cypher.internal.executionplan.ExecutionPlanImpl.buildPatternGraph(ExecutionPlanImpl.scala:35)", "org.neo4j.cypher.internal.executionplan.ExecutionPlanImpl.validatePattern(ExecutionPlanImpl.scala:101)", "org.neo4j.cypher.internal.executionplan.ExecutionPlanImpl.checkFirstQueryPattern(ExecutionPlanImpl.scala:95)", "org.neo4j.cypher.internal.executionplan.ExecutionPlanImpl.prepareExecutionPlan(ExecutionPlanImpl.scala:47)", "org.neo4j.cypher.internal.executionplan.ExecutionPlanImpl.<init>(ExecutionPlanImpl.scala:36)", "org.neo4j.cypher.ExecutionEngine$$anonfun$prepare$1.apply(ExecutionEngine.scala:80)", "org.neo4j.cypher.ExecutionEngine$$anonfun$prepare$1.apply(ExecutionEngine.scala:80)", "org.neo4j.cypher.internal.LRUCache.getOrElseUpdate(LRUCache.scala:37)", "org.neo4j.cypher.ExecutionEngine.prepare(ExecutionEngine.scala:80)", "org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:72)", "org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:76)", "org.neo4j.cypher.javacompat.ExecutionEngine.execute(ExecutionEngine.java:79)", "org.neo4j.server.rest.web.CypherService.cypher(CypherService.java:94)", "java.lang.reflect.Method.invoke(Unknown Source)", "org.neo4j.server.rest.security.SecurityFilter.doFilter(SecurityFilter.java:112)" ]
    }

**Comment by jakewins** [comment]
This was a bug in in optional relationships. Those had a series of other issues as well relating to usability, so they have been replaced by `OPTIONAL MATCH`, where this issue is no longer present.
