### ISSUE TITLE
browser very slow

### ISSUE THREAD

**Issue by kdwykleingeld** [neo4j/neo4j#10438]
Hi, i am using latest version of neo4j on windows 7 using firefox as browser. I noticed for some time (also in earlyer versions) that the browser becomes very very very slow in response to typing in queries .. actually it seems to start behaving like that when syntax checking was introduced some time ago.. 

So is there a way to bypass this syntaxt directed edting / checking ? Maybe some parameters i can set ? Other cause ?

thanks Koen

**Comment by oskarhane** [comment]
Thanks for the report @kdwykleingeld.
The browser repo is over at https://github.com/neo4j/neo4j-browser, could you please open the issue there instead?

Unfortunately there is currently no way of disabling the syntax checking completely yet, but we will provide such an option in the future.
We will also have a look at the general performance of the editor.
