### ISSUE TITLE
QueryExecutionKernelException in 3.3.0 - Expression [x] has to type from semantic analysis

### ISSUE THREAD

**Issue by jonpacker** [neo4j/neo4j#10444]
Having an issue with a complicated (and admittedly hacky) cypher query. 

- Neo4j version: 3.3.0
- Operating system: OSX 10.13.1
- API/Driver: Cypher via REST API
- Expected behavior: query succeeds
- Actual behavior: get error `org.neo4j.kernel.impl.query.QueryExecutionKernelException: Expression Property(Variable(  video@114),PropertyKeyName(rel)) has to type from semantic analysis`

I have query which rewrites a property `position` on a set of relationships between `:video` nodes and `:folder` nodes. For example, in the end project, if a `video` is inserted at the top of a folder, all other videos in folder need their `position` increased by 1. This query accomplishes that.

```
MATCH (folder:folder)<-[rel:in_folder]-(video:video)
WHERE id(folder) = {folderId}
WITH {video:video, rel:rel} as video ORDER BY video.rel.position, video.video.created
WITH collect(video) AS videos
WITH videos, CASE WHEN {position} = 'end' THEN size(videos) - 1 ELSE {position} END as position,
     range(0, size(videos)-1) as iterator,
     reduce(x=[-1,0], v IN videos | CASE WHEN id(v.video) = {videoId} THEN [x[1],x[1]+1] ELSE [x[0], x[1]+1] END)[0] as movingVideoPosition
FOREACH (index IN iterator | FOREACH (rel IN [videos[index].rel] | SET rel.position =
  CASE WHEN id(videos[index].video) = {videoId} THEN position
       WHEN (index < movingVideoPosition AND index < position) OR (index > movingVideoPosition AND index > position) THEN index
       WHEN movingVideoPosition < position THEN index - 1
       ELSE index + 1 END))
```

This query is supplied the following parameters: `videoId`, `folderId`, `position`.

I'm not sure if trying walk through the query will help, or if someone who understands the neo4j internals can spot the problem pretty quickly. If you need me to explain something in the query I can do that.

Here's a full stack trace: https://gist.github.com/jonpacker/1f9f217d45f44b567a369ac2bc03a521

Please let me know if there's any additional information needed that would be helpful.

**Comment by sherfert** [comment]
Hi @jonpacker 
That seems to be a bug. We will look into this. Thanks for the report.

**Comment by Lojjs** [comment]
@jonpacker We have investigated this and it is a bug related to that one of your properties has the same name as a node (video). If you want to fix it now you can change the variable names in your query so that video doesn't have ambiguous meaning or you can wait for the next patch release of 3.3 where the bug fix will be included.

**Comment by jonpacker** [comment]
Awesome! That fixed it. Thanks everyone!
