### ISSUE TITLE
Neo4j Version 3.3.0 docker - java.lang.IllegalArgumentException: Base directory for SSL policy with name 'default' does not exist

### ISSUE THREAD

**Issue by mcolburn** [neo4j/neo4j#10467]
**Neo4j Version:** 3.3 (Community)
**Operating System:** Ubuntu 16.04 
**API:** Docker

### Steps to reproduce
1. Assuming that `/var/lib/neo4j` is the base directory for the conf, certificates, data, logs, etc....
2. In the certificates directory, create a directory named `default`, and within it, the subdirectories `revoked` and `trusted`.
3. Place your certificate file in the `default` directory and name it `public.crt`.
4. Place your key file in the `default` directory and name it `private.key`.
5. Edit the `neo4j.conf` file by uncommenting the following line: `dbms.ssl.policy.default.base_directory=certificates/default`
6. run the following docker command: `docker run --publish=7473:7473 --publish=7687:7687 --volume=/var/lib/neo4j/data:/data --volume=/var/lib/neo4j/logs:/logs --volume=/var/lib/neo4j/conf:/conf neo4j:3.3`

### Expected behavior
Neo4j should successfully start and be available via SSL, protected by the installed certificate.

### Actual behavior
Neo4j reports `Component 'org.neo4j.server.database.LifecycleManagingDatabase@10e31a9a' was successfully initialized, but failed to start. Please see the attached cause exception "Base directory '/var/lib/neo4j/certificates/default' for SSL policy with name 'default' does not exist.".`

Also, there are many warnings about `causal_clustering` such as `WARN  Unknown config option: causal_clustering.discovery_listen_address`

### Note
The base directory `/var/lib/neo4j/certificates/default` does exist.

**Comment by eebus** [comment]
@mcolburn 
Thanks for the feedback 
This seems to be an issue with Neo4j for docker. Could you reopen the issue in https://github.com/neo4j/docker-neo4j/issues ? 
Thanks

**Comment by mcolburn** [comment]
Done.
