### ISSUE TITLE
[neo4j-community-3.3.0] Crash on startup if dbms.memory.pagecache.size >= 512g

### ISSUE THREAD

**Issue by perduamour** [neo4j/neo4j#10468]
- Neo4j version: 3.3.0 (Community)
- Operating system: RHEL7.4 / macOS High Sierra 10.13.1

### Steps to reproduce
1. set dbms.memory.pagecache.size = 512g in /etc/neo4j/neo4j.conf
2. start neo4j

### Expected behavior
neo4j server start successfully

### Actual behavior
crash on startup, and nothing left in debug.log, only a crash log file generated by java.
[crash.log](https://github.com/neo4j/neo4j/files/1481318/crash.log)

**Comment by chrisvest** [comment]
Yes, you have found an integer overflow bug. It looks like 512 GiB is exactly the point where the bug occurs, so if you reduce your page cache to 511 GiB then you will work around it. We'll have a fix out for this soon.

**Comment by cloudhuang** [comment]
@pablopareja What the total PC memory ?
