### ISSUE TITLE
Incorrect warning pointer positioning

### ISSUE THREAD

**Issue by sergejskovtuns** [neo4j/neo4j#10472]
**Neo4j Version:** 3.3.0
**Operating System:** Linux Mint 18.2
**API:** Neo4j Browser

### Steps to reproduce
1. Open Neo4j Browser
2. Run EXPLAIN on query with missing name label. Example:
`EXPLAIN MATCH p = (head:Topic) RETURN p`
3. Go to Warn tab

### Expected behavior
Pointer should point on the beginning of missing label.
```
The provided label is not in the database.
One of the labels in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing label name is: Topic)
MATCH p = (head:Topic) RETURN p
                ^
```
### Actual behavior
Pointer is misleading and pointing on different character.
```
The provided label is not in the database.
One of the labels in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing label name is: Topic)
MATCH p = (head:Topic) RETURN p
                        ^
```

**Comment by Lojjs** [comment]
@sergejskovtuns Thanks for reporting, this seems like a bug. I will let you now when it's fixed.

**Comment by sherfert** [comment]
@sergejskovtuns or  @oskarhane Can you confirm this issue is fixed? (And close the issue in that case?)
