### ISSUE TITLE
heap and pagecache suggestion memory

### ISSUE THREAD

**Issue by cloudhuang** [neo4j/neo4j#10483]
For huge data in neo4j with 200,000,000+ nodes and 200,000,000+ relationships, the db size is almost ~250GB, please suggest the minimum heap mem and pagecache mem, thanks.

**Comment by chrisvest** [comment]
You ideally want your page cache to fit the store, so 250 GiB for that.
Heap usage depends on your queries and transactions, and how many of them you are running concurrently. My guess would be 16-32 GiB in your case. See https://neo4j.com/docs/operations-manual/current/performance/#memory-tuning for more details.

**Comment by cloudhuang** [comment]
Thanks.
