### ISSUE TITLE
Checking of empty embedded database is very slow

### ISSUE THREAD

**Issue by schernolyas** [neo4j/neo4j#10494]
- Neo4j version: 3.2.6
- Operating system: Ubuntu 17.04
- API/Driver: Java API

Start of application that uses embedded database is very slow. 
See [debug.log](https://github.com/neo4j/neo4j/files/1498153/debug.log)

Code for create database:
GraphDatabaseBuilder builder = new GraphDatabaseFactory().newEmbeddedDatabaseBuilder( dbLocation );
		setConfigurationFromLocation( builder, configurationLocation );
		setConfigurationFromProperties( builder, configuration );
		final ClassLoader neo4JClassLoader = builder.getClass().getClassLoader();
		final Thread currentThread = Thread.currentThread();
		final ClassLoader contextClassLoader = currentThread.getContextClassLoader();
		try {
			//Neo4J relies on the context classloader to load its own extensions:
			//Allow it to load even the ones we're not exposing directly to end users.
			currentThread.setContextClassLoader( neo4JClassLoader );
			return builder.newGraphDatabase();
		}
		finally {
			currentThread.setContextClassLoader( contextClassLoader );
		}

**Comment by schernolyas** [comment]
Hi!
The same situation with 3.3.1 version.
[debug.log](https://github.com/neo4j/neo4j/files/1552214/debug.log)
_________
public class App {
	public static void main (String[] argv) {
		System.out.println("RUN"  );
		String dbLocation = "/home/osboxes/IdeaProjects/neo4jtest/target/db";
		long start = System.currentTimeMillis();
		GraphDatabaseBuilder builder = new GraphDatabaseFactory().newEmbeddedDatabaseBuilder( new File( dbLocation) );
		long start1 = System.currentTimeMillis();
		System.out.println( "1. " +( start1-start ) );
		GraphDatabaseService graphDatabaseService = builder.newGraphDatabase();
		System.out.println( "2. " +( System.currentTimeMillis()-start ) );

	}
}
_____

The code shows :
1. 162 ms
2. 6422 ms

**Comment by tinwelint** [comment]
Some of this time seems to be spent opening the store files and rebuilding the `.id` files, which involves I/O, roughly 200-300 ms per store. I'd bet class loading in general takes some amount of this time too. Two questions:

- debug.log says that it's rebuilding the id files, was the store cleanly shut down?
- If you shut down the db and, in the same JVM, open it again... will it be faster the second time? I.e. start on clean and no class loading?

**Comment by schernolyas** [comment]
Hi @tinwelint !

1. I close JVM by System.exit().  No "kill -9" or "kill -6"
2. Yes. it faster. 
RUN
1. 123 Fri Dec 15 14:50:19 MSK 2017
2. 9281 Fri Dec 15 14:50:28 MSK 2017
3. 2963 Fri Dec 15 14:50:33 MSK 2017
Point 3 is start in same JVM after shutdown by "graphDatabaseService.shutdown();"

I am contributor of project Hibernate OGM ( http://hibernate.org/ogm/ ) and we use Neo4j for testing too. Dialect for Ne4j works slow. May be .... Could you create some option for  using in test enviroment only ? For testing, we don't need worrying about data safety. But ... startup time is more important.

**Comment by ragadeeshu** [comment]
Hello @schernolyas . Please make sure to always shutdown the database with graphDatabaseService.shutdown(); _before shutting down the jvm_. This should help reduce the startup times as you wouldn't need to go through recovery.

**Comment by tinwelint** [comment]
If you're using the db for testing only and don't require data to be persistent between runs then you _could_ use `ImpermanentGraphDatabase` which just lives in memory and is suitable for small data sizes.

**Comment by schernolyas** [comment]
Okey @tinwelint .

 A lot of thanks for consulting.

**Comment by schernolyas** [comment]
Thanks @ragadeeshu  and @tinwelint !
I checked your idea. It helps!
It reduce startup time from 7 till 3 seconds.
