### ISSUE TITLE
 not support `"resultDataContents" : [ "graph" ]` mode when using allShortestPaths?

### ISSUE THREAD

**Issue by cloudhuang** [neo4j/neo4j#10493]
I there, 
when I try to find the shortest path over the HTTP API, I found the `"resultDataContents" : [ "graph" ]` is not support in the response, it always return the "row" response.

Please and suggest is there any existing tool to transform the neo4j "row" response to "graph" format? (there is no relationship in the row format directly)

Neo4j Version: 3.2.3

Thanks.

**Comment by zhenlineo** [comment]
@cloudhuang Sorry for the long wait. We will look into this. Meanwhile, you might want to try our driver API, it provides a slightly better representation of `Path`.

**Comment by technige** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Rejuvenate HTTP transactional endpoint](https://trello.com/c/ALFE4DKx/383-rejuvenate-http-transactional-endpoint)

**Comment by technige** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bolt over HTTP: Full type system support and transaction semantics](https://trello.com/c/OIqgU81q/161-bolt-over-http-full-type-system-support-and-transaction-semantics)
