### ISSUE TITLE
Inconsistencies in  GraphDatabaseBuilder setConfig deprecated methods

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#105]
@FlorentE: 'Hi,

The method   
```java
public GraphDatabaseBuilder setConfig(String name, String value)
```
is marked as Deprecated

but the method
```java
public GraphDatabaseBuilder setConfig(Map<String, String> config)  
```

is only a wrapper around the first one, so it should be marked as depracted as well.
'

**Comment by jakewins** [comment]
+1 it's now deprecated as well.
