### ISSUE TITLE
neo4j-import tools import relationships, not working, and not exit, no error message.

### ISSUE THREAD

**Issue by Yalye** [neo4j/neo4j#10519]
## Guidelines
I just use neo4j-import tool to import large data set into graphdb on Ubuntu, when it runs at 'Relationships, start' step, just 3 minutes, the step is done, but i have billions of relationship, it can't be that quick. Then i checked the graphdb directory, it's so small. I use the --stacktrace option， no error message. 
- Neo4j version: 3.2.1
- Operating system: Ubuntu
- API/Driver:  neo4j-import
- **Steps to reproduce**
- Expected behavior
- Actual behavior

**Comment by chrisvest** [comment]
There is probably a mistake in your command line arguments or your CSV headers. What do they look like? Did `neo4j-import` produce any log files?

**Comment by tinwelint** [comment]
No reply in a month on this one. @Yalye ping.
