### ISSUE TITLE
Add BoltWorker.halt() to MonitoredWorker.SessionMonitor

### ISSUE THREAD

**Issue by virtuald** [neo4j/neo4j#10518]
Some monitors might be interested in knowing when a monitored BoltWorker is halted. I imagine you could expose this in the metrics extension in addition to sessions started.

https://github.com/neo4j/neo4j/blob/3.4/community/bolt/src/main/java/org/neo4j/bolt/v1/runtime/MonitoredWorkerFactory.java#L106

**Comment by ali-ince** [comment]
Hi @virtuald,

We're planning to add couple of more monitor methods including `#connectionClosed` as part of our next release.

We'll keep this issue updated when the work is submitted as a PR.

Thanks.

**Comment by ali-ince** [comment]
Closing this as the new metrics related to `BoltConnection`s, which also include `connectionClosed`, are released as part of neo4j 3.4 series.
