### ISSUE TITLE
Would Like to Be able to Apply Styles (labels really) to Relationships in Webadmin

### ISSUE THREAD

**Issue by jbisbee** [neo4j/neo4j#1053]
Currently using neo4j to visualize system architecture.  My graph data consists of every of every system and process in my production environment and I'm looking to visualize the relationships.  (I'm new and system is not well documented)  So I'm presently just creating relationships based on how processes have dependencies on other processes within the system.  I'd like to be able to style these relationships (would be a certain directory one process drops files in, could be a database connection, some other sort of IPC)  The point is that I'd like to be able to visually style those relationships accordingly.  

Thanks, Jeff

**Comment by oskarhane** [comment]
Webadmin is now removed from the product and the viz in Neo4j Browser have most features in this issue. If you still miss something, please open a new ticket on the [neo4j-browser](https://github.com/neo4j/neo4j-browser) repo.
