### ISSUE TITLE
Some resource was not correct release after org.neo4j.unsafe.batchinsert.BatchInserter.shutdown()

### ISSUE THREAD

**Issue by pyzhou-talend** [neo4j/neo4j#10534]
I'm using org.neo4j-3.2.6.jar . I got a java.io.Exception when I try to delete the whole database after shut dowm. It seems some file stream was not released. ```{databse.root}\schema\index\lucene\1\1``` this folder is the one which have been left and cause the java.io.Exception
Note that, this only occurs when a IndexEntryConfilctException was happening.

**Comment by burqen** [comment]
@pyzhou-talend Thank you for reporting!
To make further investigations I'd like to ask you some questions:
- Have you got the full stack trace from the exception?
- Was the shutdown successful before deleting this store? 
- Do you have any logs from the incident? Most notably the `debug.log` is of great interest.
- Have you found a reliable way to reproduce it?

**Comment by burqen** [comment]
Closing this issue due to lack of answer. Please open again if you have additional information that would make investigation possible.
