### ISSUE TITLE
Neo4j browser doesn't correctly handle inputted bolt address for connection

### ISSUE THREAD

**Issue by DFoxinator** [neo4j/neo4j#10554]
**Neo4j Version:** 3.3.0
**Operating System:** Mac OS/Chrome

### Steps to reproduce
1. Go to the Neo4j browser
2. Set up the connection for a database where the bolt host is different from the IP of the instance itself. This use-case occurs for me when I'm using an SSH tunnel to access a Neo4j instance, so the browser wants to use the private IP of the instance, but I need to to use 127.0.0.1:port
3. Use the browser. It will work correctly.
4. Refresh the page
5. Now, the browser ignores the previously entered bolt host, and starts using the private instance IP which is incorrect.

### Expected behavior
The browser should not override the previous saved value entered for the bolt host

### Actual behavior
The browser changes the previous saved bolt host URL to use the instance IP instead, which breaks the browser when you're using it with an SSH tunnel and need to 
route through 127.0.0.1 or some other IP. It works fine the first time you enter it - the issue only occurs when you reload the page.

**Comment by oskarhane** [comment]
Hi, thanks for the report @DFoxinator!
Would you mind opening the issue over at the [neo4j-browser repo](https://github.com/neo4j/neo4j-browser)?
The browser trusts what the server sends as `[your-connector].advertised_address`. Try to adjust that one and it should be automatic.

**Comment by DFoxinator** [comment]
@oskarhane thanks for the response! I didn't realize there was a repo for browser specifically. I went ahead and created it there.

I don't think advertised_address can be used to solve this, if I understand correctly. Our cluster functions as expected and the members communicate on the IPs they need to. This problem is specifically with being able to access the Neo4j browser through an SSH tunnel. The tunnel maps the instance to localhost, so you need to be able to enter 127.0.0.1:7687 as the bolt port.

The behavior when you first enter the connection info in browser is as expected. It properly uses your entry to talk to Neo4j. The problem is somewhere after that, in the local storage saving mechanism. When you refresh the page, it forgets that entry you made and tries to use the wrong IP. I don't see how both behaviors can be correct, I would expect the same result when I enter connection info into browser as when I reload browser and it uses saved connection info.
