### ISSUE TITLE
Send deep object as param over HTTP to Cypher

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#106]
@wingy: 'It doesn't seem sending a deep object structure as param to cypher works.

Here is the use case.

Let's say I have an array of users I want to create in Neo4j (in JavaScript):

    // Sending HTTP request with params
    params: {
      users: [{name: 'foo', age: 12}, {name: 'bar', age: 34}, {name: 'baz', age: 23}]
    }

Then in the query use:

    FOREACH (user in {users}: RELATE ({name: user.name, age: user.age})-[:IS_ONE_OF_MANY]->(users))

or even better (since perhaps they don't have the same properties so I can't predefine them):

    FOREACH (user in {users}: RELATE (user)-[:IS_ONE_OF_MANY]->(users))

and:

    params: {
      user: {name: 'foo', age: 12, phone: 08-709265396}
    }

    RELATE ({user})-[:IS_ONE_OF_MANY]->(users))

It seems like this is a fairly common use case. And it would be a perfect match for the RELATE and MATCH pattern.

This would mean that we don't need to define the properties of any object in advance. We can create whatever sent from the backend which means more flexibility. Neo4j already is like CouchDB/MongoDB in that way that is allows dynamic data structure, but then you have to predefine this in the Cypher query, which seems contradicting. Whatever I send to CouchDB/MongoDB will be created in the database, it would be great if that was the same for Neo4j as well.

Also we could just send whatever properties to MATCH. Since we don't know the predefined properties created we can't write Cypher with predefined properties to match (for filtering and searching). With this MATCH:ing would get really flexible as well.

What I am doing right now is letting my users create whatever properties they want. I have no idea what properties they will create.

Just for comparison, here is my current solution (in CoffeeScript):

    properties = (for key, value of params.properties
      if value.isString()
        """
        #{key}: "#{value}"
        """
      else if value.isNumber()
        """
        #{key}: #{value}
        """
    ).join()

    neo4j.cypher
      query: """
        START root = node(0)
        CREATE (item {#{properties}})
        RELATE (root)-[:HAS_MANY]->({name: "Item types"})<-[:IS_ONE_OF_MANY]-(itemType {name: "#{params.itemTypeName}"})
        RELATE (root)-[:HAS_MANY]->({name: "Items"})<-[:IS_ONE_OF_MANY]-(item)-[:IS_IN]->(itemType)
        RETURN ID(item)
      """
    , callback

As you can see it's way too hacky and bad for caching.

Feature benefits:

1. Allowing multiple objects being created rather than one at a time
2. Allowing 100% dynamic data structure with no predefined properties in the Cypher queries
3. No wheel reinvention and complex hack for people who need this
4. Better caching

Would this be a good feature you think?'

**Comment by jakewins** [comment]
This should now work without issue.
