### ISSUE TITLE
Community version doesn't check parameters were provided

### ISSUE THREAD

**Issue by frant-hartm** [neo4j/neo4j#10607]
Community version doesn't check parameters are provided when there is no match.

- Neo4j version: 3.3.0
- Operating system: Xubuntu 16.04
- API/Driver: Bolt and browser
- **Steps to reproduce**

I expect following code to fail on empty database (or a database with no `Person` nodes) because the parameter name is not provided:
```
        try (Driver driver = GraphDatabase.driver("bolt://localhost")) {

            try (Session session = driver.session()) {

                try (Transaction tx = session.beginTransaction()) {

                    StatementResult run = tx.run("MATCH (n:Person {name:{name}}) RETURN n");
                    run.consume();

                    tx.success();

                }
            }
        }
```

- Expected behavior
Fail with 
```
Exception in thread "main" org.neo4j.driver.v1.exceptions.ClientException: Expected a parameter named name
```
This fails as expected on enterprise version or on community when there are some nodes with `Person` label.
- Actual behavior
Just returns no results.

**Comment by eebus** [comment]
@frant-hartm Thanks for reporting, this seems like a bug. I will let you know when it's fixed.

**Comment by craigtaverner** [comment]
This will come out in the next version of 3.3.x.
