### ISSUE TITLE
Query via REST API => CypherExecutionException, same query via web interface does not.

### ISSUE THREAD

**Issue by dosumis** [neo4j/neo4j#10661]
- Neo4j version: 3.2.1 Enterprise
- Operating system: docker instance  https://hub.docker.com/r/rcourt/docker-neo4j-knowledgebase/
- API/Driver: REST API 
- **Steps to reproduce**
```python
import requests
import json
endpoint = "http://kb.virtualflybrain.org"
usr = ''
pwd = ''
query = "MATCH (ds:DataSet { label : 'Jenett2012'} ) " \
    "<-[hs:has_source]-(a:Individual) with ds,hs, a " \
    "OPTIONAL MATCH (ds)-[:has_site]-(s:Site) " \
    "WITH ds, hs, a, s " \
    "OPTIONAL MATCH (a)-[dbx:hasDbXref]-(s) " \
    "RETURN DISTINCT ds.label AS sname, " \
    "dbx.accession as extID, s.link_base as pre, " \
    "s.link_postfix as post, a.iri as iIRI,  " \
    "a.short_form as iID, a.label as iname"
payload = { 'statements': [ { 'statement' : query }]}
r = requests.post(url = endpoint + "/db/data/transaction/commit", auth = (usr, pwd), data = json.dumps(payload))
r.json()
```  

### Expected behavior

Returns data - this works when the same query is run via the web endpoint and for other values of ds.label, e.g. 'Cachero2010', when the query is run via the API as above.

### Actual behavior

```js
{'errors': [{'code': 'Neo.DatabaseError.Statement.ExecutionFailed',
   'message': 'Unable to load NODE with id -1.',
   'stackTrace': 'org.neo4j.cypher.CypherExecutionException: Unable to load NODE with id -1
```

For full stack trace, run snippet above.

The database was built and maintained entirely via API requests. I'm worried about our long term commitment to neo4j if DB instances can easily end up in this state (I've seen something similar with a local instance in the past).

I can provide full logs and a copy of the DB if this is useful for diagnosing the problem.  

Many thanks.

CC @Robbie1977

**Comment by Lojjs** [comment]
@dosumis Thanks for reporting, this sounds like a bug. Full logs and a copy of the DB would be really helpful. You can send it to me at louise.soderstrom@neo4j.com if you don't want to post it here. 
Best regards Louise, Neo4j Cypher team

**Comment by Lojjs** [comment]
@dosumis Since we haven't got the required info from you to be able to debug this, I will close your issue for now Please feel free to re-open it later if you still need support on this.
