### ISSUE TITLE
Control flow

### ISSUE THREAD

**Issue by Euklios** [neo4j/neo4j#10672]
I'm searching for an easy way to do something like this:
```
MATCH (n) WHERE n.name = "Test value"
IF(NOT EXISTS(n.sample_list) | 
    SET n.sample_List = []
)
```
There is currently a workaround. It looks like this:
```
FOREACH(ignoreMe IN CASE WHEN EXISTS(n.sample_list) THEN [] ELSE [1] END |
    SET n.sample_List = []
)
```
But this looks rather nasty and it's sometimes harder to debug.

**Comment by Lojjs** [comment]
@javaWidmer  If you don't need to process all nodes `(n)` further after your query, you can rewrite it to
```
MATCH (n) WHERE n.name = "Test value" AND NOT EXISTS (n.sample_list)
SET n.sample-list = []
```
This will however lead to that you drop the access to the nodes that already had a sample_list.  There is a proposal on adding a `WHEN` statement to Cypher that will handle this kind of cases but this is currently in the hands of the Cypher Language Group. For now, if you need to do further processing of all nodes, you can instead use the procedure `apoc.do.when(condition, true-statement, [false-statement], [params])`.

**Comment by Euklios** [comment]
This is sadly not possible in my case. I search for specific nodes, but can't say for sure, if the list already exists or not. If the nodes don't have a sample list yet, the cypher should create one. Afterwards, in both cases, a value should be appended to the sample_list.

@Lojjs Could you provide a link to the proposal you mentioned?

**Comment by InverseFalcon** [comment]
An alternative here is to use a SET using COALESCE:

```
MATCH (n) 
WHERE n.name = "Test value" 
SET n.sample-list = COALESCE(n.sample-list, []) + <whatever value to append>
```

If the property exists, it will be set with its same value. If it doesn't exist, it will be set to an empty list.

**Comment by Lojjs** [comment]
@javaWidmer 
The CLG proposal including ideas for how to do conditional updates can be found here: https://github.com/petraselmer/openCypher/blob/CIP-nested-subqueries/cip/1.accepted/CIP2016-06-22-nested-updating-and-chained-subqueries.adoc. Note that this proposal hasn't been accepted yet, so it is potentially subject to change.

The apoc library`when` function is described here: https://neo4j-contrib.github.io/neo4j-apoc-procedures/index32.html#_conditional_cypher_execution. 

However, I personally prefer @InverseFalcon's solution above over my own suggestion.
