### ISSUE TITLE
possible cypher/scala memory leak after redeploy on tomcat

### ISSUE THREAD

**Issue by wouterv** [neo4j/neo4j#1070]
Hi,

We are using tomcat for running our webapplication backed by embedded neo4j and on redeploy we get this error:

aug 13, 2013 10:52:55 AM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [] created a ThreadLocal with key of type [scala.util.DynamicVariable$$anon$1] (value [scala.util.DynamicVariable$$anon$1@5d99bd24]) and a value of type [scala.None$] (value [None]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

I have looked in our maven dependencies, and the only library that is using scala is neo4j-cypher. 

When we redeploy to tomcat a couple of times we eventually get an OutOfMemoryError: PermGen space 

We already added the following to the jvm args, but the only thing it did is postpone the issue:
-XX:MaxPermSize=256m
-XX:+CMSClassUnloadingEnabled
-XX:+CMSPermGenSweepingEnabled

I also had a head dump done and the only thing that really stands out that there are a LOT of classes in memory, which is what you would expect when a classloader cant be cleaned up.

Specs: Neo4j 1.9.2, spring-data-neo4j 2.2.1,  Windows server 2008 R2, Java 1.7.0_21, Tomcat 7.0.40

So, could this be an issue in neo4j's scala usage?

Thanks
Wouter

**Comment by jakewins** [comment]
As per above, this is an issue with scala itself. More details on workarounds here: https://groups.google.com/forum/#!topic/scala-user/QuM4YKpGCvs
