### ISSUE TITLE
properties() cannot be used to return node properties in a statement with a MERGE clause

### ISSUE THREAD

**Issue by mcandocia-rmarkbio** [neo4j/neo4j#10719]
The `properties()` function cannot be used to return properties within a statement beginning with `MERGE`.

**Neo4j Version:** 3.3.0 (Enterprise)
**Operating System:** macOS Sierra 10.12.1
**API:** Neo4J Browser/Python
**Neo4j Desktop Version:** 1.0.9

### Steps to reproduce
1. Execute `MERGE (test:test_type {example_attr:"123"}) RETURN properties(test)`

### Expected behavior
The attributes should be returned as `{"example_attr":"123"}`

### Actual behavior
The program does not finish running, and this error is logged in the Neo4J Desktop log:

    2018-01-03 22:06:14.255+0000 ERROR Client triggered an unexpected error [UnknownError]: null, reference 40c2f8ee-ec47-4129-a5cf-45812facf4a0.

**Comment by InverseFalcon** [comment]
Can confirm in 3.3.1 as well.

**Comment by Lojjs** [comment]
@mcandocia-rmarkbio This seems to be the same issue as https://github.com/neo4j/neo4j/issues/10656. Your query is a bit more spot on though. This is a 3.3 bug about updating properties in the same query as a calling the `properties()` function. We in the Cypher team are currently looking into it.

**Comment by sherfert** [comment]
There is a bugfix for this in the soon to be released 3.3.2
