### ISSUE TITLE
NoClassDefFoundError in DebugUtil::trackTest() in neo4j-kernel not catched

### ISSUE THREAD

**Issue by ollio** [neo4j/neo4j#10722]
* Neo4j version: 3.3.1
* Neo4j module: neo4j-kernel
* Operating system: MacOS 10.13.2

### Steps to reproduce:

I have written a TestNG Test in a Spring Boot application and have configured the embedded Neo4J driver. In the Instantiation Phase DebugUtil::trackTest() will be called. When iterating over the stack trace in line 330 a class `org.testng.TestRunner` will be found and throws Exeption of type `java.lang.NoClassDefFoundError`.

### Actual behavior: 
embedded driver can't be instantiated for TestNG tests.

### Possible solution:
The fix is easy, just add the NoClassDefFoundError to the catch block in line 344:

`
                catch ( ClassNotFoundException | SecurityException | NoSuchMethodException | NoClassDefFoundError e )
                {
                    // This is so weird, but hey, who am I to judge all ours precious JVM and class loader
                    continue;
                }
`

**Comment by WolfgangFahl** [comment]
I get a java.lang.NoClassDefFoundError: org/apache/lucene/store/NRTCachingDirectory in a similar situation with the code:

```
@Rule
  // https://maxdemarzi.com/2015/07/05/using-the-testing-harness-for-neo4j-extensions/
  public Neo4jRule neo4j = new Neo4jRule().withFixture(CYPHER_STATEMENT)
```

is this the same or a different bug?

**Comment by ollio** [comment]
Maybe the exception is the same and can also have the same reason. 
Attached is the patched version of DebugUtil, you can give it a try. 

[DebugUtil.java.zip](https://github.com/neo4j/neo4j/files/1623266/DebugUtil.java.zip)

**Comment by WolfgangFahl** [comment]
@ollio - in my case it was an incompatible apache lucence which was introduced by using  apache pdfbox-lucene. I manually added a newer lucene reference and all was well.

**Comment by h3xstream** [comment]
For users encountering the same bug..

If you get a NoClassDefFoundError with `com/google/inject/Module` or `com/google/inject/Injector`, this is caused by this bug.

```
Caused by: java.lang.NoClassDefFoundError: com/google/inject/Module
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethod(Class.java:2128)
	at org.neo4j.kernel.impl.util.DebugUtil.trackTest(DebugUtil.java:337)
	at org.neo4j.kernel.impl.util.Neo4jJobScheduler.init(Neo4jJobScheduler.java:58)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:406)
	... 36 more
Caused by: java.lang.ClassNotFoundException: com.google.inject.Module
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 more
```

## Workaround

Add the following dependency to your project.
```xml
        <dependency>
            <groupId>com.google.inject</groupId>
            <artifactId>guice</artifactId>
            <version>4.2.0</version>
        </dependency>
```

## Background info

Neo4j was loading information of method definitions. Including the annotation. However, annotations are optional and Guice should be an optional dependency of TestNG. A try / catch should have been present.
