### ISSUE TITLE
Java - getDegree() taking too long to find number of specified relationship

### ISSUE THREAD

**Issue by 0xshippor** [neo4j/neo4j#10752]
- Neo4j version: 3.3.1
- Operating system: Win 10/Debian 9
- API/Driver: Java API

My database consists of 2 types of nodes Address and Transaction. A simple transaction looks like this:
![image](https://user-images.githubusercontent.com/14165372/34697393-2f12dda2-f4d3-11e7-810a-cc8eca7b65fa.png)
Usually (90% of the time) single address is used exactly once a sender and once a receiver in whole database, but there are exceptions where address can be used more times as both sender and receiver. I need list of such addresses.

I tried using Java to get this done, but I am getting really slow response time. Simple insight in my code
`if(address != null && address.getDegree(RelationshipType.withName("SENT")) > 1)`
where `address` is of type `Node` returned from `db.findNodes(Label.label("Address"))` where `db` is my Graph Database Service. I get the result for about 70 Address Nodes per second, which is very slow for my needs. Using multiple threads (24 cores 2.260 GHz) I am able to get to 125 per second (that is still very slow for my requirements).  

Also I tried the same using cypher, but without any speedup.

Currently I am working only on 1/5 of database which consists of roughly 36M Address Nodes and 40M Transaction Nodes.

I am sure that these are not limitations of Neo4j and I am doing something wrong.

**Comment by MishaDemianenko** [comment]
Hi @cabrenn , thx for your report.
Without more detailed execution profile it's hard to see why its taking that long for you.
But as you correctly suspecting, it should not take that long.
To check performance on some test database I have created this simple test ( you can easily convert it to JMH test, but even this oversimplified test should be enough so far) :
```
import org.junit.Rule;
import org.junit.Test;

import java.util.ArrayList;

import org.neo4j.graphdb.Label;
import org.neo4j.graphdb.Node;
import org.neo4j.graphdb.RelationshipType;
import org.neo4j.graphdb.ResourceIterator;
import org.neo4j.graphdb.Transaction;
import org.neo4j.test.rule.EmbeddedDatabaseRule;

public class DegreeTest
{
    @Rule
    public EmbeddedDatabaseRule database = new EmbeddedDatabaseRule();

    @Test
    public void oldManDegreePerformanceSmokeTest()
    {
        RelationshipType sent = RelationshipType.withName( "sent" );
        Label address = Label.label( "address" );
        for ( int labeledNodes = 0; labeledNodes < 100_000; labeledNodes++ )
        {
            try ( Transaction transaction = database.beginTx() )
            {
                Node addressNode = database.createNode( address );
                for ( int nodeRelationships = 0; nodeRelationships < 10; nodeRelationships++ )
                {
                    Node sentRecord = database.createNode();
                    addressNode.createRelationshipTo( sentRecord, sent );
                }
                transaction.success();
            }
        }

        long startTime = System.currentTimeMillis();
        ArrayList list = new ArrayList();
        try ( Transaction transaction = database.beginTx() )
        {
            ResourceIterator<Node> nodes = database.findNodes( address );
            while ( nodes.hasNext() )
            {
                list.add( nodes.next().getDegree( sent ) );
            }
        }
        long finishTime = System.currentTimeMillis();
        long duration = finishTime - startTime;
        System.out.println( list.size() + " lookups took " + duration + " ms." );
    }
}
```
by running it you should be able to see that performance for pure getDegree call is much much higher comparing to what you describing.
So to give more hints and explanations we would need at least some profiling information (async, jrf, etc) otherwise feel free to modify provided example in a way that will help to observe described slowness.

**Comment by MishaDemianenko** [comment]
Closing due to reporter inactivity. Please feel free to reopen if that's still a problem
