### ISSUE TITLE
Mac OS *dmg download

### ISSUE THREAD

**Issue by adadgio** [neo4j/neo4j#10781]
Where is the MacOS DMG file download link ?

Its has been removed from your website. Why ? Did you drop this ?

**Comment by jjaderberg** [comment]
The desktop packaging was completely reworked for Neo4j 3.3. You can download Neo4j Desktop at https://neo4j.com/download/ and read more about it at https://neo4j.com/product/#neo4j-desktop

Closing this issue, please reach out here or on the `neo4j-users` Slack if you have further questions.
