### ISSUE TITLE
Can not start an object, expecting field name

### ISSUE THREAD

**Issue by ddesna** [neo4j/neo4j#10812]
I'm trying to execute some statements via Neo4j Rest API that cause the following error:

```json
"code": "Neo.TransientError.Network.CommunicationError",
"message": "Can not start an object, expecting field name",
"stackTrace": "org.codehaus.jackson.JsonGenerationException: Can not start an object, expecting field name at org.codehaus.jackson.impl.JsonGeneratorBase._reportError(JsonGeneratorBase.java:480) ..."
```

Neo4j version: 3.3.1 (Community)

This is the full request:
````
POST /db/data/transaction/commit

{
	"statements": [
		{
			"statement": "START r=rel({relIds}) FOREACH (row in filter(row in {rows} where row.relId = id(r)) | SET r += row.props) RETURN ID(r) as ref, ID(r) as id, {type} as type",
			"parameters": {
				"relIds": [
					56607
				],
				"rows": [
					{
						"relId": 56607,
						"props": {
							"note": null,
							"external": false,
							"multiple": false,
							"name": null,
							"description": null,
							"state": "0"
						}
					}
				],
				"type": "rel"
			},
			"resultDataContents": [
				"row"
			],
			"includeStats": false
		},
		{
			"statement": "START r=rel({relIds}) DELETE r",
			"parameters": {
				"relIds": [
					55870
				],
				"rows": [
					{
						"relId": 55870
					}
				]
			},
			"resultDataContents": [
				"row"
			],
			"includeStats": false
		}
	]
}
````

What could be the reason of the following error ?

Thanks.

**Comment by ddesna** [comment]
I have tried to change statment from
`START r=rel({relIds}) FOREACH (row in filter(row in {rows} where row.relId = id(r)) | SET r += row.props) RETURN ID(r) as ref, ID(r) as id, {type} as type`
to
`MATCH ()-[r]-() WHERE id(r) IN {relIds} FOREACH (row in filter(row in {rows} where row.relId = id(r)) | SET r += row.props) RETURN ID(r) as ref, ID(r) as id, {type} as type`

and `START r=rel({relIds}) DELETE r` to `MATCH ()-[r]-() WHERE id(r) IN {relIds} DELETE r`.
and it is not produce the error anymore.

Could be the reason of the error the deprication of [START](https://neo4j.com/docs/developer-manual/current/cypher/clauses/start/) clause ?

**Comment by systay** [comment]
Hi @ddesna!

I'm pretty sure you found the problem and solved it yourself. It's a weird error message you are getting, but the solution is to not use `START`.

Thanks for letting us know!
