### ISSUE TITLE
Syntax check and auto complete makes Firefox unresponsive

### ISSUE THREAD

**Issue by SimonThordal** [neo4j/neo4j#10898]
Neo4j Browser version 3.1.4
Debian 9 Stretch
Firefox 57.01

When writing long queries in the Neo4j browser Firefox often becomes slow or unresponsive until syntax checking is completed. It would be great to have an option to turn it off in the same way that you can with auto-complete (which also seems to slow down Firefox a lot).

**Comment by eebus** [comment]
Hello @SimonThordal 
Thanks for reporting. 
Could you reopen this issue in the browser repository? https://github.com/neo4j/neo4j-browser/issues

**Comment by SimonThordal** [comment]
Sure, didn't notice it had its own repo :)
