### ISSUE TITLE
Cannot start neo4j on restart of server

### ISSUE THREAD

**Issue by samuelcentaurm** [neo4j/neo4j#10926]
- Neo4j version: community edition / neo4j 3.3.2
- Operating system: Ubuntu 16.04

**Steps to reproduce**
install neo4j / java 8 etc.. from apt-get on fresh install of ubuntu 16.04 lts (amazon ami) updated to all latest packages - following instructions on neo4j site for debian installs

- Expected behavior
install neo4j working
restart server for whatever reason sudo neo4j start - should start neo4j

- Actual behavior
neo4j running
restart server for whatever reason sudo neo4j start - should start neo4j
sudo neo4j start - produces this error:
Starting Neo4j.
/usr/share/neo4j/bin/neo4j: line 411: /var/run/neo4j/neo4j.pid: No such file or directory

i can manually make the directory and neo4j does start - but i have to do this on every reboot

**Comment by allentiak** [comment]
Also confirmed on Debian 'testing'.

**Comment by jennyowen** [comment]
The fix for #11954 should also fix this issue. I verified this in Ubuntu 16.04 and Neo4j 3.3.8.
The fix is in 3.3.8 and will be in 3.4.10 and 3.5.0  when they are released.
Thanks for reporting the issue!
