### ISSUE TITLE
Bug: Procedure gets called once for each item in a node list

### ISSUE THREAD

**Issue by rothn** [neo4j/neo4j#10959]
A custom procedure (Personalized PageRank) gets called for each item in its input node list with an input list of cardinality 1. Since it is a single *list*, the procedure should only get called once with the *full* input list. In other words, this is what happens:
CALL algo.personalizedPageRank.stream([a])
CALL algo.personalizedPageRank.stream([b])
CALL algo.personalizedPageRank.stream([c])
CALL algo.personalizedPageRank.stream([d])
CALL algo.personalizedPageRank.stream([e])
CALL algo.personalizedPageRank.stream([f])
CALL algo.personalizedPageRank.stream([g])
CALL algo.personalizedPageRank.stream([h])

And this is what should happen:
CALL algo.personalizedPageRank.stream([a, b, c, d, e, f, g, h])

Read below for details. I didn't use the CODE macro since GitHub concatenates all of the lines together (i.e. it removes the newline characters) when I do.

- Neo4j version: 3.3.2
- Operating system: macOS 10.12.6
- API/Driver: Unknown -- using Desktop version downloaded 2/2/2018

### Steps to reproduce
1) Drop my Personalized PageRank jar into the plugins directory
2) Restart Neo4j with the GUI
3) Create a basic graph:
_CREATE (home:Page{name:'Home'})
,(about:Page{name:'About'})
,(product:Page{name:'Product'})
,(links:Page{name:'Links'})
,(a:Page{name:'Site A'})
,(b:Page{name:'Site B'})
,(c:Page{name:'Site C'})
,(d:Page{name:'Site D'})
CREATE (home)-[:LINKS]->(about)
,(about)-[:LINKS]->(home)
,(product)-[:LINKS]->(home)
,(home)-[:LINKS]->(product)
,(links)-[:LINKS]->(home)
,(home)-[:LINKS]->(links)
,(links)-[:LINKS]->(a)-[:LINKS]->(home)
,(links)-[:LINKS]->(b)-[:LINKS]->(home)
,(links)-[:LINKS]->(c)-[:LINKS]->(home)
,(links)-[:LINKS]->(d)-[:LINKS]->(home)_
4) Invoke Personalized PageRank with no weights on each node in the graph (useful for checking the accuracy of the results against regular PageRank)
_MATCH p = (n)
CALL algo.personalizedPageRank.stream(nodes(p), 'Page', 'LINKS', {iterations:20, dampingFactor:0.85})
YIELD node, score
RETURN node,score order by score desc limit 20_

### Expected behavior
The personalizedPageRank.stream procedure should be invoked once on a nodeSet of cardinality 8
### Actual behavior
The personalizedPageRank.stream procedure is invoked 8 times on a nodeSet of cardinality 1

### Server Log
Starting Neo4j.
2018-02-03 19:57:56.004+0000 INFO  ======== Neo4j 3.3.2 ========
2018-02-03 19:57:56.030+0000 INFO  Starting...
2018-02-03 19:57:57.400+0000 INFO  Bolt enabled on 127.0.0.1:7687.
2018-02-03 19:57:57.419+0000 INFO  Initiating metrics...
2018-02-03 19:58:00.985+0000 INFO  Started.
2018-02-03 19:58:01.176+0000 INFO  Mounted REST API at: /db/manage
2018-02-03 19:58:01.838+0000 INFO  Remote interface available at http://localhost:7474/
THIS IS WHERE WE START (node set cardinality: 1)
2018-02-03 19:58:09.185+0000 INFO  [neo4j.Pooled-11] LOADING 100%
Initial node count: 8
2018-02-03 19:58:09.190+0000 INFO  Personalized PageRank: overall memory usage: 0 Bytes
Final node count: 8
Final node iteration; processing external node (0) = internal node (0) with score 0.47296600000000016
Final node iteration; processing external node (1) = internal node (1) with score 0.13327150000000001
Final node iteration; processing external node (2) = internal node (2) with score 0.13327150000000001
Final node iteration; processing external node (3) = internal node (3) with score 0.13327150000000001
Final node iteration; processing external node (4) = internal node (4) with score 0.02244
Final node iteration; processing external node (5) = internal node (5) with score 0.02244
Final node iteration; processing external node (6) = internal node (6) with score 0.02244
Final node iteration; processing external node (7) = internal node (7) with score 0.02244
THIS IS WHERE WE START (node set cardinality: 1)
2018-02-03 19:58:09.203+0000 INFO  [neo4j.Pooled-11] LOADING 100%
Initial node count: 8
2018-02-03 19:58:09.204+0000 INFO  Personalized PageRank: overall memory usage: 0 Bytes
Final node count: 8
Final node iteration; processing external node (0) = internal node (0) with score 0.39944050000000003
Final node iteration; processing external node (1) = internal node (1) with score 0.262438
Final node iteration; processing external node (2) = internal node (2) with score 0.11243799999999998
Final node iteration; processing external node (3) = internal node (3) with score 0.11243799999999998
Final node iteration; processing external node (4) = internal node (4) with score 0.0188955
Final node iteration; processing external node (5) = internal node (5) with score 0.0188955
Final node iteration; processing external node (6) = internal node (6) with score 0.0188955
Final node iteration; processing external node (7) = internal node (7) with score 0.0188955
THIS IS WHERE WE START (node set cardinality: 1)
2018-02-03 19:58:09.208+0000 INFO  [neo4j.Pooled-11] LOADING 100%
Initial node count: 8
2018-02-03 19:58:09.209+0000 INFO  Personalized PageRank: overall memory usage: 0 Bytes
Final node count: 8
Final node iteration; processing external node (0) = internal node (0) with score 0.39944050000000003
Final node iteration; processing external node (1) = internal node (1) with score 0.11243799999999998
Final node iteration; processing external node (2) = internal node (2) with score 0.262438
Final node iteration; processing external node (3) = internal node (3) with score 0.11243799999999998
Final node iteration; processing external node (4) = internal node (4) with score 0.0188955
Final node iteration; processing external node (5) = internal node (5) with score 0.0188955
Final node iteration; processing external node (6) = internal node (6) with score 0.0188955
Final node iteration; processing external node (7) = internal node (7) with score 0.0188955
THIS IS WHERE WE START (node set cardinality: 1)
2018-02-03 19:58:09.218+0000 INFO  [neo4j.Pooled-11] LOADING 100%
Initial node count: 8
Final node count: 8
Final node iteration; processing external node (0) = internal node (0) with score 0.34934149999999997
2018-02-03 19:58:09.218+0000 INFO  Personalized PageRank: overall memory usage: 0 Bytes
Final node iteration; processing external node (1) = internal node (1) with score 0.098226
Final node iteration; processing external node (2) = internal node (2) with score 0.098226
Final node iteration; processing external node (3) = internal node (3) with score 0.24822600000000003
Final node iteration; processing external node (4) = internal node (4) with score 0.04198149999999999
Final node iteration; processing external node (5) = internal node (5) with score 0.04198149999999999
Final node iteration; processing external node (6) = internal node (6) with score 0.04198149999999999
Final node iteration; processing external node (7) = internal node (7) with score 0.04198149999999999
THIS IS WHERE WE START (node set cardinality: 1)
2018-02-03 19:58:09.223+0000 INFO  [neo4j.Pooled-11] LOADING 100%
2018-02-03 19:58:09.224+0000 INFO  Personalized PageRank: overall memory usage: 0 Bytes
Initial node count: 8
Final node count: 8
Final node iteration; processing external node (0) = internal node (0) with score 0.39944050000000003
Final node iteration; processing external node (1) = internal node (1) with score 0.11243799999999998
Final node iteration; processing external node (2) = internal node (2) with score 0.11243799999999998
Final node iteration; processing external node (3) = internal node (3) with score 0.11243799999999998
Final node iteration; processing external node (4) = internal node (4) with score 0.16889550000000003
Final node iteration; processing external node (5) = internal node (5) with score 0.0188955
Final node iteration; processing external node (6) = internal node (6) with score 0.0188955
Final node iteration; processing external node (7) = internal node (7) with score 0.0188955
THIS IS WHERE WE START (node set cardinality: 1)
2018-02-03 19:58:09.227+0000 INFO  [neo4j.Pooled-11] LOADING 100%
Initial node count: 8
2018-02-03 19:58:09.228+0000 INFO  Personalized PageRank: overall memory usage: 0 Bytes
Final node count: 8
Final node iteration; processing external node (0) = internal node (0) with score 0.39944050000000003
Final node iteration; processing external node (1) = internal node (1) with score 0.11243799999999998
Final node iteration; processing external node (2) = internal node (2) with score 0.11243799999999998
Final node iteration; processing external node (3) = internal node (3) with score 0.11243799999999998
Final node iteration; processing external node (4) = internal node (4) with score 0.0188955
Final node iteration; processing external node (5) = internal node (5) with score 0.16889550000000003
Final node iteration; processing external node (6) = internal node (6) with score 0.0188955
Final node iteration; processing external node (7) = internal node (7) with score 0.0188955
THIS IS WHERE WE START (node set cardinality: 1)
2018-02-03 19:58:09.232+0000 INFO  [neo4j.Pooled-11] LOADING 100%
2018-02-03 19:58:09.233+0000 INFO  Personalized PageRank: overall memory usage: 0 Bytes
Initial node count: 8
Final node count: 8
Final node iteration; processing external node (0) = internal node (0) with score 0.39944050000000003
Final node iteration; processing external node (1) = internal node (1) with score 0.11243799999999998
Final node iteration; processing external node (2) = internal node (2) with score 0.11243799999999998
Final node iteration; processing external node (3) = internal node (3) with score 0.11243799999999998
Final node iteration; processing external node (4) = internal node (4) with score 0.0188955
Final node iteration; processing external node (5) = internal node (5) with score 0.0188955
Final node iteration; processing external node (6) = internal node (6) with score 0.16889550000000003
Final node iteration; processing external node (7) = internal node (7) with score 0.0188955
THIS IS WHERE WE START (node set cardinality: 1)
2018-02-03 19:58:09.236+0000 INFO  [neo4j.Pooled-11] LOADING 100%
2018-02-03 19:58:09.237+0000 INFO  Personalized PageRank: overall memory usage: 0 Bytes
Initial node count: 8
Final node count: 8
Final node iteration; processing external node (0) = internal node (0) with score 0.39944050000000003
Final node iteration; processing external node (1) = internal node (1) with score 0.11243799999999998
Final node iteration; processing external node (2) = internal node (2) with score 0.11243799999999998
Final node iteration; processing external node (3) = internal node (3) with score 0.11243799999999998
Final node iteration; processing external node (4) = internal node (4) with score 0.0188955
Final node iteration; processing external node (5) = internal node (5) with score 0.0188955
Final node iteration; processing external node (6) = internal node (6) with score 0.0188955
Final node iteration; processing external node (7) = internal node (7) with score 0.16889550000000003

### Source code excerpt (for context):
    @Procedure(value="algo.personalizedPageRank.stream", mode=Mode.READ)
    @Description(value="CALL algo.personalizedPageRank.stream(nodeSet:List<Node>, label:String, relationship:String, {weightProperty:'', iterations:20, dampingFactor:0.85, concurrency:4}) YIELD node, score - calculates page rank and streams results")
    public Stream<PageRankScore> personalizedPageRankStream(@Name(value="nodeSet", defaultValue="[]") List<Node> nodeSet, @Name(value="label", defaultValue="") String label, @Name(value="relationship", defaultValue="") String relationship, @Name(value="config", defaultValue="{}") Map<String, Object> config) {
    System.err.println("THIS IS WHERE WE START (node set cardinality: " + nodeSet.size() + ")");

**Comment by InverseFalcon** [comment]
Not a bug.

In Cypher operations execute per row, including procedure calls. 

The result of this: `MATCH p = (n)` is 8 rows, so your procedure will be called 8 times, once per row.

If you want your procedure to only execute once for all nodes in the graph, collect those nodes so you only have a single row with the node list.

```
MATCH (n)
WITH collect(n) as nodes
CALL algo.personalizedPageRank.stream(nodes, 'Page', 'LINKS', {iterations:20, dampingFactor:0.85})
YIELD node, score
RETURN node,score order by score desc limit 20
```
