### ISSUE TITLE
REDUCE function giving error.

### ISSUE THREAD

**Issue by Mahesh-gupta542** [neo4j/neo4j#10978]
The REDUCE function is not able to execute when iterating over a concatenation of two sub lists. When I tried to get the sum of the elements of two separate lists it throws error of type mismatch.

**Neo4j Version:** 3.2.9  
**Operating System:** Windows 10
**API:** The built-in web app running over bolt

### Steps to reproduce
1. Start the database service on your local system
2. Go to the neo4j console in your web browser (localhost:7474)
3. Execute the below sample query
`RETURN REDUCE(s = 0, p in [5,8,2,9] + [1,2] | s + p)`

### Expected behavior
It should return one 27 which is the sum of all the elements in both list.

### Actual behavior
It throws the below error 
`Type mismatch: accumulator is Integer but expression has type Float (line 1, column 57 (offset: 56))
"RETURN REDUCE(s = 0, p in [5,8,2,9] + [1,2] | s + p)"
                                                     ^`

**Comment by Lojjs** [comment]
@Mahesh-gupta542 Thanks for reporting this bug. We will have a look at it and come back to you.

Best regards Louise, Neo4j Cypher team
