### ISSUE TITLE
Escaping | char in cypher?

### ISSUE THREAD

**Issue by Meatballs1** [neo4j/neo4j#10987]
Can't work out how:

```
╒══════════════════╕
│"split("a|b","|")"
╞══════════════════╡
│["a","|","b"]     
└──────────────────┘
```

```
╒═══════════════════════╕
│"split("a|b","\u007c")"                          
╞═══════════════════════╡
│["a","|","b"]                                           
└───────────────────────┘
```

I've tried blackslash, backticks, single and double quotes? 

Should work like below:

```
╒══════════════════╕
│"split("a&b","&")"
╞══════════════════╡
│["a","b"]         
└──────────────────┘
```

**Comment by Lojjs** [comment]
@Meatballs1 Which version of Neo4j are you using? 

In 3.3 your original query works exactly like your example with `&`, i.e.
```
RETURN split("a|b","|")
```
returns
`["a", "b"]`

**Comment by Meatballs1** [comment]
Somewhere in 3.4... I will try and get the commit

**Comment by Lojjs** [comment]
@Meatballs1 Yes, it seems to be a bug in 3.4. We in the Cypher team will have a look at it and then come back to you.
