### ISSUE TITLE
How to buy NEO4J Enterprise?

### ISSUE THREAD

**Issue by dcbasso** [neo4j/neo4j#10993]
We try several times to buy the license but the sales of Neo4J never returns with the value of licenses.
We work for a huge company of Agricultural business and we really wont to buy the license, but as we not get the answer we are thinking to avoid this product.
Can anyone here help me get the answer we are looking for, a really good sales contact.

Thanks

**Comment by ryguyrg** [comment]
Hi there @dcbasso -- I believe we're now in touch through Kevin.  Feel free to reach out to devrel -at- neo4j.com at any time.

@jexp please close issue.
