### ISSUE TITLE
neo4j-desktop-offline-1.0.13-x86_64.AppImage execution fails with "GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference" 

### ISSUE THREAD

**Issue by dakra137** [neo4j/neo4j#11001]
**Neo4j Version:** neo4j-desktop-offline-1.0.13-x86_64.AppImage
**Operating System:** Ubuntu 14.04 
**API:** haven't gotten that far
 
**Steps to reproduce via GUI**
Execute from Nautilus by clicking or right clicking and selecting Run:

- Expected behavior
launch the installation sequence

- Actual behavior 
produces no output, but leaves processes running:
	dakra     4530  1878  2 11:36 ?        00:00:00 /tmp/.mount_neo4j-KaH0go/app/neo4j-desktop
	dakra     4537  1878 99 11:36 ?        00:00:03 /media/dakra/Windoze7/Software/Neo4j/neo4j-desktop-1.0.13-x86_64.RD4.AppImage
	dakra     4553  4530  0 11:36 ?        00:00:00 /tmp/.mount_neo4j-KaH0go/app/neo4j-desktop --type=zygote --no-sandbox
	dakra     4555  3095  0 11:36 pts/7    00:00:00 grep --color=auto neo4

**Steps to reproduce via bash command line**
execute from command line:  **/media/dakra/Windoze7/Software/Neo4j/neo4j-desktop-offline-1.0.13-x86_64.AppImage**

- Expected behavior
launch the installation sequence

- Actual behavior

myuserid@MYMACHINEID:/media/dakra/Windoze7/Software/Neo4j$ **/media/dakra/Windoze7/Software/Neo4j/neo4j-desktop-offline-1.0.13-x86_64**
.AppImage installed: X-AppImage-BuildId=7e08d5c0-080f-11a8-1170-53454c5a18c2 image: X-AppImage-BuildId=7e08d5c0-080f-11a8-1170-53454c5a18c2
[11:31:40:0343] [info] App starting
/tmp/.mount_neo4j-1S4J3k/app/neo4j-desktop: relocation error: /tmp/.org.chromium.Chromium.fjxmTg: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERmm, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference

/* [This leaves no processes running.] */

**REQUEST: Commands to fix the missing link problem.**

- Other info: GLIBCXX 
myuserid@MYMACHINEID:/media/dakra/Windoze7/Software/Neo4j$ **strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX**
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_DEBUG_MESSAGE_LENGTH

Previously, I had been getting "GLIBCXX_3.4.21' not found" . I resolved that:

myuserid@MYMACHINEID:~$ **/media/dakra/Windoze7/Software/Neo4j/neo4j-desktop-1.0.13-x86_64.AppImage** 
installed: X-AppImage-BuildId=dadb4f50-0803-11a8-1c15-abbd9592a091 image: X-AppImage-BuildId=dadb4f50-0803-11a8-1c15-abbd9592a091
A JavaScript error occurred in the main process
Uncaught Exception:
Error: **/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/.org.chromium.Chromium.XJgFxV)**
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    ....
The resolution for that was from: 
[askubuntu](https://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error)

sudo apt-get install libstdc++6

This should already be installed by default, but try it anyway. If it doesn't solve it, just do the following:

sudo add-apt-repository ppa:ubuntu-toolchain-r/test 
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade

**Comment by oskarhane** [comment]
Thanks for the detailed report!
Could you open this in the public neo4j-desktop repo instead, so we can track it there?
https://github.com/neo4j-apps/neo4j-desktop
