### ISSUE TITLE
New Feature: Support transaction isolation level  over REST API

### ISSUE THREAD

**Issue by bunkat** [neo4j/neo4j#1103]
Currently there doesn't seem to be a way to configure the isolation level for a transaction (especially SERIALIZABLE) when using the REST API.  

I'm trying to create friendly id's for child objects using the following:

```
CREATE (o:Foo {name: 'parent', nextChildId: 1})

MATCH (o:Foo)
WHERE o.name = 'parent'
CREATE (o)-[:HAS]->(c:Child {name: 'child1', friendlyId: o.nextChildId})
SET o.nextChildId = o.nextChildId + 1

// if this call comes in before the previous SET, we have a problem
MATCH (o:Foo)
WHERE o.name = 'parent'
CREATE (o)-[:HAS]->(c:Child {name: 'child2', friendlyId: o.nextChildId})
SET o.nextChildId = o.nextChildId + 1
```

But without being able to take a lock on the `parent` node there isn't a way to prevent two `child` nodes from getting assigned the same friendly id.

**Comment by jakewins** [comment]
So! Custom transaction isolation levels are not likely to come soon, but we've implemented [unique constraints](http://neo4j.com/docs/developer-manual/current/cypher/schema/constraints/#query-constraint-unique-nodes) that will ensure you don't get clashing ids; together with the automatic retry built into the new neo4j drivers, I believe this pattern will work:

    session.writeTransaction( (tx) => {
        tx.run("MATCH (o:Foo)
            WHERE o.name = 'parent'
            CREATE (o)-[:HAS]->(c:Child {name: 'child1', friendlyId: o.nextChildId})
            SET o.nextChildId = o.nextChildId + 1");
    });

And, there's a workaround that emulates SQLs "SELECT .. FOR UPDATE" hack, that works by locking the node by writing to an unrelated property first. This isn't as pretty, but it's an option if you don't like client side retries; combining this with the unique constraint would be both safe and performant.

    MATCH (o:Foo)
    WHERE o.name = 'parent'
    SET o._lock = true
    WITH o
    CREATE (o)-[:HAS]->(c:Child {name: 'child1', friendlyId: o.nextChildId})
    SET o.nextChildId = o.nextChildId + 1");

**Comment by PAX523** [comment]
Still inacceptable! Please consider:

https://stackoverflow.com/questions/30109292/how-to-manually-manage-neo4j-locks-in-spring-managed-transaction

https://stackoverflow.com/questions/50665958/neo4j-error-for-relationship-property-property-values-can-only-be-of-primitive

It seems that Neo4j isn't eligible for reasonable use with Spring Data. Unbelievable.
