### ISSUE TITLE
Incorrect query return behavior with REST HTTP API

### ISSUE THREAD

**Issue by gotomgo** [neo4j/neo4j#11040]
## Overview
The following query does not return expected result a majority of the time. It returns a valid result somewhat randomly, and infrequently. I was unable to deduce any discernible pattern across many small variations of what I returned from the query:

match (x:X{id:$id})-[:HAS]->(y:Y)
where y.prop=0
set y.prop=timestamp()
return true

It's counterpart exhibits the same issue:

match (x:X{id:$id})-[:HAS]->(y:Y)
where y.prop<>0
set y.prop=0
return true

### Expected Result
Assuming the condition is met, the query should return this:
{"results":[{"columns":["true"],"data":[{"row":[true],"meta":[null]}]}],"errors":[]}

### Actual Result
but a majority of the time it returns this:
{"results":[{"columns":["true"],"data":[]}],"errors":[]}

**The erroneous result is returned even though the where condition is met, and the property value is changed.**

The queries work perfectly in the browser (as expected.)

To work around the issue, I dropped the where clause, and the result is as expected 100% of the time

## Details

Version 3.2.2 CE 
Docker image running on AWS Linux AMI
Requests using REST HTTP does not provide return value (98% of the time)

**Comment by zhenlineo** [comment]
Hi @gotomgo,
The result you got `{"results":[{"columns":["true"],"data":[]}],"errors":[]}` is returned when `match` and `where` find 0 row to return. 

For example, for query
`MATCH (n) RETURN true LIMIT 1`
returns
```
| true | // column name
| true | // row 1
```
and another query
`MATCH (n) RETURN true LIMIT 2`
returns
```
| true | // column name
| true | // row 1
| true | // row 2
```
So if no row is found, it only returns
```
| true | // column name with no row
```

However you mentioned that you could receive 0 row even if where condition is met and condition value is changed (where 1 row result shall be expected). For this case maybe there are some race conditions in your system?

We tested our REST endpoint with the query you provided and other simple queries. We did not find any issue. The result returned as expected. 
We also tested with our current bolt driver. The results returned from bolt are consistent with the HTTP endpoint.

I am closing this issue given the explanation above. Pls be free to reopen the issue if you disagree with the conclusion we got.

Cheers,
Zhen
