### ISSUE TITLE
TX log file build up in incremental backup directory

### ISSUE THREAD

**Issue by kyle-rader** [neo4j/neo4j#11058]
## Incremental backups do not clean up tx log files and eats up disk space fast!

I discovered after starting to use nightly incremental backups that the older tx log files do not get cleaned up so each incremental backup adds all the tx log files since the last incremental backup growing the size of the backup directory _very_ quickly.

These are the transaction log files that get rotated and cleaned up in your database as specified by the log retention policy and tx log size configuration parameters (and a few others).

The size of our backups more than doubled in the span of 5 days (these are sent each night to S3 so there is cost component to storing extra data).

* **Neo4j Version:** 3.3.1-enterprise
* **Operating System:** (Docker) The official Neo4j image which uses `openjdk:8-jre-alpine` as its base.

### Steps to reproduce

I've created a stand alone project to demonstrate this issue in real-time.
Head on over to https://github.com/kyle-rader/neo4j_incremental_backup_issue and follow the README steps to reproduce locally. (Uses `docker` and `docker-compose`).

### Expected behavior
The size of the backup directory should be consistent with the database data directory. Old tx logs should be removed.

### Actual behavior
The size of the backups increases by _# tx logs since last backup_ X _tx log size_ on each incremental backup.

All tx logs since starting incremental backups are still in the backup directory. This is very problematic for write heavy applications using Neo4j.

**Comment by andreikoval** [comment]
@phughk can you pls check if this is the same issue as #11055  or #11068 ?

**Comment by kyle-rader** [comment]
@andreikoval After reading [this test](https://github.com/neo4j/neo4j/pull/11055/files#diff-6e04d14cf58caffed932f5753d592bd8R145) from #11055 I think this is the same error.

**Comment by phughk** [comment]
@andreikoval  @kyle-rader sorry for the delay - yes, it is the same issue, we are working to fix it.
