### ISSUE TITLE
Error in the Operations Manual

### ISSUE THREAD

**Issue by pumpadump** [neo4j/neo4j#11073]
Example 9.3. in the Operations Manual shows wrong commands:
```
$neo4j-home> ls data/databases/graph.db/*store.db* | du -ch | tail -1
```
Should be
```
$neo4j-home> ls data/databases/graph.db/*store.db* | xargs du -ch | tail -1
```

the other command seems to be also wrong:
```
find data/databases/graph.db/schema/index -regex '.*/native.*' | du -hc | tail -1
```
I don't have a quick correct solution at hand.

**Comment by mariascharin** [comment]
@pumpadump Thank you, and apologies for the very late response!
We have actually removed platform-specific commands with the thought that a sys admin would know the appropriate commands for their particular platform.
For 3.4 and onwards, we use the `neo4j-admin memrec --database` for advice about sizing. 
Regards, 
Maria

**Comment by mariascharin** [comment]
@pumpadump Thank you, and apologies for the very late response!
We have actually removed platform-specific commands with the thought that a sys admin would know the appropriate commands for their particular platform.
For 3.4 and onwards, we use the `neo4j-admin memrec --database` for advice about sizing. 
Regards, 
Maria

**Comment by mariascharin** [comment]
@pumpadump Thank you, and apologies for the very late response!
We have actually removed platform-specific commands with the thought that a sys admin would know the appropriate commands for their particular platform.
For 3.4 and onwards, we use the neo4j-admin memrec --database for advice about sizing.
Regards,
Maria
