### ISSUE TITLE
Creating a new Database in Neo4j Desktop version 1.0.15 fails after upgrade

### ISSUE THREAD

**Issue by rescuehero** [neo4j/neo4j#11075]
I found out, that on the new Desktop version the Database creating does not work for me.

- Neo4j Desktop Version: 1.0.15
- Neo4j version: 3.3.3 CE
- Operating system: Win7, Win10
- Steps to reproduce : Upgrade from desktop version 1.0.14 to Desktop version 1.0.15
- Expected behavior: creating a new database works flawless in a few seconds
- Actual behavior: creates the folder of the database in neo4j path, but the client keeps loading and loading
![grafik](https://user-images.githubusercontent.com/11653204/36483101-82121bf8-1715-11e8-88de-2a3e4d2fbd4d.png)

If you need some more information, i am going to share it as fast as i can.

**Comment by oskarhane** [comment]
Thanks for the report! May I ask you to open this issue in the [neo4j-desktop](https://github.com/neo4j-apps/neo4j-desktop) repo instead since this isn't a Neo4j issue?

**Comment by rescuehero** [comment]
yep right, sorry about that :)
thank you for noticing me about the other repo
