### ISSUE TITLE
[apoc subgraphAll] relationshipFilter not expected behavior

### ISSUE THREAD

**Issue by zunio** [neo4j/neo4j#11070]
```
match (n:node {id: 1})
call apoc.path.subgraphAll(n,{maxLevel:1,bfs:true, relationshipFilter:'rel_1|rel_2',labelFilter:'-label1|-label2'}) yield nodes,relationships
return nodes,relationships
```

With apoc "subgraphAll" and maxLevel=1,  the "relationshipFilter" is applied on the search of direct neighbors but not on the relationships between his neighbors.
Is this the expected behavior of this apoc?

**Apoc Version:** 3.2.3.5
**Neo4jVersion:** 3.2.6 Enterprise

**Comment by jexp** [comment]
Wrong repo: -> http://github.com/neo4j-contrib/neo4j-apoc-procedures
