### ISSUE TITLE
neo4j debian .deb neo4j_1%3a3.3.3_all.deb cannot install into Ubuntu 14.04 

### ISSUE THREAD

**Issue by dakra137** [neo4j/neo4j#11074]
- Neo4j version: 3.3.3 latest in the repository
- Operating system: Ubuntu 14.04 up to date
- Steps to reproduce
**sudo apt-get update**
- Expected behavior
**successful update**
- Actual behavior
**dpkg-deb: error: archive '/var/cache/apt/archives/neo4j_1%3a3.3.3_all.deb' has premature member 'control.tar.xz' before 'control.tar.gz', giving up**
dpkg: error processing archive /var/cache/apt/archives/neo4j_1%3a3.3.3_all.deb (--unpack):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 **/var/cache/apt/archives/neo4j_1%3a3.3.3_all.deb**
E: Sub-process /usr/bin/dpkg returned an error code (1)

Description:

As packaged, with its **control.tar.xz** file, the .deb cannot be installed into Ubuntu 14.04, at least not with  **apt-get update** . This is due to an known and accepted ubuntu defect, which could be circumvented by packaging the .deb with **control.tar.gz** rather than **control.tar.xz** . 

See [xz compressed control.tar files not supported](https://bugs.launchpad.net/ubuntu/+source/dpkg/+bug/1730627)

Example output:
**apt-get upgrade**
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  neo4j
1 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Need to get 0 B/86.2 MB of archives.
After this operation, 7,168 B disk space will be freed.
Do you want to continue? [Y/n] Y
Preconfiguring packages ...
**dpkg-deb: error: archive '/var/cache/apt/archives/neo4j_1%3a3.3.3_all.deb' has premature member 'control.tar.xz' before 'control.tar.gz', giving up**
dpkg: error processing archive /var/cache/apt/archives/neo4j_1%3a3.3.3_all.deb (--unpack):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 **/var/cache/apt/archives/neo4j_1%3a3.3.3_all.deb**
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by lonelywm** [comment]
same issue

**Comment by mkrogh** [comment]
Still no update after 12 days?

**Comment by hsmfedor** [comment]
same issue

**Comment by froschi** [comment]
This was an issue in dpkg (https://bugs.launchpad.net/ubuntu/+source/dpkg/+bug/1730627). A fix is now in the <yourdistro>-proposed repository in Ubuntu. I installed the version of dpkg from there (1.17.5ubuntu5.8) and was then able to successfully install the neo4j package.

**Comment by mkrogh** [comment]
@froschi Nice with a workaround, though it would be nice to not have the deb package use xz compression, before 14.04 is end of life.

**Comment by ronaldcornet** [comment]
Hi all,
Update to dpkg is coming, according to this page:
https://bugs.launchpad.net/ubuntu/+source/dpkg/+bug/1730627

If you don't want to wait, here is what I did (no guarantee to work for others, although I wouldn't know why). I basically followed this: https://wiki.ubuntu.com/Testing/EnableProposed

1. Add this line to /etc/apt/sources.list
deb http://archive.ubuntu.com/ubuntu/ trusty-proposed restricted main multiverse universe

2. Enter these 3 lines into (newly created for me): /etc/apt/preferences.d/proposed-updates
Package: *
Pin: release a=trusty-proposed
Pin-Priority: 400

3. Run: sudo apt-get update

4. Run: apt-get install dpkg/trusty-proposed
This installs the fixed dpkg version

5. Run: apt-get upgrade
Now neo4j installs smoothly.

Hope this helps!

**Comment by jennyowen** [comment]
Thanks for taking the time to report the issue.

I'm going to close this since it seems to be an Ubuntu bug that's since been fixed. 
I tried installing 3.3.3 on ubuntu 14.04 and it installed as expected. I checked Neo4j 3.3.4 and it uses tar.gz compression on control instead of tar.xz.
