### ISSUE TITLE
PageCacheStressTest.Builder does not have 'with' method to pass a PageCursorTracerSupplier.

### ISSUE THREAD

**Issue by Samathy** [neo4j/neo4j#11087]
The PageCacheStressTest.Builder class has a member `PageCursorTracerSupplier pageCursorTracerSupplier` but no `with` method to set it.

PageCursorTracerSupplier needs to be set to get interesting PageCacheCounters information out of stress test. (hits, faults, etc)

**Comment by digitalstain** [comment]
@chrisvest I think you may be interested in this - is the suggested change the proper way to go about this?

**Comment by chrisvest** [comment]
Yes, I've approved the PR.
