### ISSUE TITLE
Dubious results

### ISSUE THREAD

**Issue by spantazis** [neo4j/neo4j#11083]
I have been having some dubious results with the shortest path function with the attached dataset.

Here's what I get if I look for the shortest path with LIMIT 1 (which should be meaningless I suppose but is actually not):

![1-pic](https://user-images.githubusercontent.com/1118958/36503108-58047874-174c-11e8-951e-754c53906305.PNG)
![1-code](https://user-images.githubusercontent.com/1118958/36503115-5ea054a0-174c-11e8-9af2-21e7cd67e980.PNG)

and here's what I get for LIMIT 2 - notice the blue path being shorter than the previous answer. Am I doing something wrong?

![2-pic](https://user-images.githubusercontent.com/1118958/36503139-73f9d7c2-174c-11e8-9c28-07d6c0d5f87b.PNG)
![2-code](https://user-images.githubusercontent.com/1118958/36503156-77333726-174c-11e8-89b6-9f963fe3e796.PNG)

Dataset
---------
[create-course-data.txt](https://github.com/neo4j/neo4j/files/1745559/create-course-data.txt)

General Info
--------------
Running Neo4j 3.3.1 Enterprise
Windows 10
Cypher

**Comment by hdk** [comment]
Execute your query without the LIMIT statement and click on "Text view". 
Neo4j finds 30 paths containing up to 2 :HAS_CONTACT relations - and LIMIT just limits the number of returned paths (the first one has length 2, the second one length 1)

**Comment by spantazis** [comment]
Yes, this is exactly what happens, but why return paths containing 2 "HAS_CONTACT" relations if we are looking for the shortest path? If I understand the function definition correctly, it should only return a list of paths with 1 "HAS_CONTACT" relation. Or at least this is the result I would like to have.

EDIT: For even further clarification, I expected a list of four paths with length 1 as a result of shortestPath on this dataset.

**Comment by hdk** [comment]
You are looking for all (5) Matrix actors and for all (6) Top Gun actors, and then for the shortest paths between all of them => 30 shortest paths, 4 have length 1 and 26 have length 2.

**Comment by spantazis** [comment]
This is what I got, but this is not what I am looking for :-) Ok, so shortestPath works on each of these thirty actor combinations (the first of Matrix & the first of Top Gun, then the first of Matrix and the second of Top Gun and so on). I guess that explains everything. Now I have to concentrate on somehow finding the shortest of these paths. Thanks a lot.

**Comment by InverseFalcon** [comment]
@spantazis You can do this easily using [APOC's path expander procedures](https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_expand_paths)

In the recent winter releases (3.2.3.6 and 3.3.0.2, depending on your version of Neo4j), we added the capability to define specific end nodes and terminator nodes for the expansion, and the procedures already support a limit and breadth-first-search expansion, so by starting from a collection of all actor nodes for one of the movies, and performing a bfs expansion and limiting to the first result found of the collection of other actors, we'll have found the shortest path between the two sets. The important part will be gathering the actors into lists before the procedure call:

```
MATCH (movMat:Movie{title:'The Matrix'}), (movTop:Movie{title:'Top Gun'})
WITH movMat, movTop, [(actMat:Person)-[:ACTED_IN]->(movMat) | actMat] as matActors, [(actTop:Person)-[:ACTED_IN]->(movTop) | actTop] as topActors
CALL apoc.path.expandConfig(matActors, {relationshipFilter:'HAS_CONTACT', limit:1, terminatorNodes:topActors}) YIELD path
RETURN path, length(path), movMat, movTop
```
