### ISSUE TITLE
[C# driver]Cannot break in the result foreach loop

### ISSUE THREAD

**Issue by ninaqms** [neo4j/neo4j#11116]
To help us understand your issue, please specify important details, primarily:

- Neo4j version: 1.5.2
- Operating system: windows 10
- API/Driver: .Net

Code:
using (var session = driver.Session())
                {
                    foreach(var sg in sgs)
                    {
                        var result = session.Run(string.Format(@"
                        MATCH path = (sg:GROUP)< -[*] - (user:USER) 
                        WHERE sg.SamAccountName = '{0}'
                        RETURN user.SamAccountName as logon, EXTRACT(n in nodes(path) |  n.SamAccountName) as path, sg.SamAccountName as root", sg));
                        foreach (var record in result)
                        {
                            List<string> path = record["path"].As<List<string>>();
                            if (path.GroupBy(x => x).Any(g => g.Count() > 1))
                            {
                                break;
                            }
                            Console.WriteLine(string.Format("{0}\t{1}\t{2}", record["logon"].As<string>(), JsonConvert.SerializeObject(path), record["root"].As<string>()));
                        }
                    }
                }

- **Steps to reproduce**
- Expected behavior
If the path contains loop, then exit the current foreach. The app consume to handle the next sg.

- Actual behavior
The application hang there, cannot execute the next session run.

**Comment by technige** [comment]
@ninaqms To enable us to track this properly, please could you re-raise this issue against the .NET driver repository: https://github.com/neo4j/neo4j-dotnet-driver.

**Comment by lutovich** [comment]
Closing in favour of https://github.com/neo4j/neo4j-dotnet-driver/issues/276
