### ISSUE TITLE
Import freeze on large dataset with duplicate nodes

### ISSUE THREAD

**Issue by davidcdupuis** [neo4j/neo4j#11207]
Hi,

I'm currently working with "Neo4j community version 3.3.3" with a server with the following configurations: Debian GNU/Linux version 9 with 500GB of RAM and 56 cores. (for research purposes)

I am importing a large dataset into Neo4j. 
I use four files for this import:
- edges.csv which contains about 1.46B edges (25GB)
- nodes.csv which I created using a basic python script to extract nodes from edges.csv (40M nodes, 16GB) (I did not bother removing all duplicates from this file)
- nodes_header.csv > "userId:ID"
- rel_header.csv > ":START_ID (tab) :END_ID" 

When I run the command: "./neo4j-admin import --ignore-duplicate-nodes ... " the import process freezes after a couple of minutes when attempting to deduplicate the nodes. 

I tested the import with small sample files which worked. I then modified my script to eliminate duplicates and I observed drastic performance improvement.
For a little more than 10M nodes in nodes.csv and 10M relationships in edges.csv total import time went from: **3 minutes** with duplicates to > **18 seconds** without duplicates to > **16 seconds** if I leave out the command "--ignore-duplicate-nodes"

Hopefully there is a solution to improve the --ignore-duplicate-nodes command and stop it from freezing with large datasets.

**Comment by davidcdupuis** [comment]
I can confirm that getting rid of duplicate nodes using a simple script prevented the import process from freezing. It managed to import the dataset in 19minutes.

**Comment by tinwelint** [comment]
Hi, there have been great improvements for handling duplicate nodes in the 3.4 branch, which is in beta stage right now. Both memory usage, which is much lower, but also performance of it.

It would be interesting to see how much difference that makes in your case.

**Comment by ragadeeshu** [comment]
@davidcdupuis Could you download the 3.4 rc1 and give your dataset a try?

**Comment by chrisvest** [comment]
3.4.0 has been released now, with many improvements to the handling of duplicates. I'm going to close this issue, but feel free to reopen if it's still a problem even on 3.4.
