### ISSUE TITLE
Multi-site neo4j can't recover from site failure as operations manual says it can.

### ISSUE THREAD

**Issue by mikernorton** [neo4j/neo4j#11216]
- Neo4j version: 3.2.9
- Operating system: Centos 7.3
- Steps to reproduce:

1. Create a causal cluster with two sites and three cores at each site, leader on the site 1
2. Block traffic between sites so that they become isolated.
3. Wait for Neo4j cores on site 2 to recognize that site 1 is unavailable
4. follow the procedure in https://neo4j.com/docs/operations-manual/3.2/clustering/causal-clustering/multi-data-center/disaster-recovery/#_procedure_for_recovering_from_data_center_loss

- Expected behavior
Site recovers with 3 nodes and processes normally.
- Actual behavior
Site does not recover. The neo4j cores stay down. It is clear that no leader can be elected because there the cores are still counting on 6 nodes to be in the cluster
Election started with vote request: Vote.Request from MemberId{a0692463} {term=13, candidate=MemberId{a0692463}, lastAppended=39, lastLogTerm=5} and members: [MemberId{80465299}, MemberId{fb8845df}, MemberId{4a53d6c3}, MemberId{092d6a5a}, MemberId{a0692463}, MemberId{a44dcc3d}]

[cluster_recovery.txt](https://github.com/neo4j/neo4j/files/1798485/cluster_recovery.txt)

**Comment by mikernorton** [comment]
Martin Furmanski helped me with this on slack. There is a missing step in the procedure, step 2.5: neo4j-admin unbind. That works. Could we update the docs?

**Comment by RagnarW** [comment]
Closing due to unsupported version
