### ISSUE TITLE
Okami Match p = (n:CaseInfo { XKBH : '1000000' }) - [*1..5]-() return p optimization

### ISSUE THREAD

**Issue by 444728248** [neo4j/neo4j#11298]
Hello Okami
I do not have a large amount of data, but my data layer is very large, only 100 thousand nodes, the query speed is very slow. for example，
CQL --- Match p = (n:CaseInfo { XKBH : '1000000' }) - [*1..5]-() return p
This is I query 5 layers of relationships, how to use a paging method to query all relationships?

**Comment by eebus** [comment]
Hello @444728248 
I guess that you are running the query using Okami.
Please Reopen the issue at:  https://github.com/opencypher/cypher-for-apache-spark
