### ISSUE TITLE
Okami Neo4j cpyher statistical problems

### ISSUE THREAD

**Issue by 444728248** [neo4j/neo4j#11295]
In my graph database, how to query all related entity nodes from a node is also a question of how to count the number of graphs in my database. The problem is that neo4j doesn't seem to have such a mechanism.

**Comment by eebus** [comment]
Hello @444728248 
It seems like this is a CAPS: Cypher for Apache Spark or Okami issue.
Could you reopen the issue in https://github.com/opencypher/cypher-for-apache-spark ?

**Comment by 444728248** [comment]
Hello Okami
I do not have a large amount of data, but my data layer is very large, only 100 thousand nodes, the query speed is very slow. for example，
CQL  --- Match p = (n:CaseInfo { XKBH : '1000000' }) - [*1..5]-() return p
This is I query 5 layers of relationships, how to use a paging method to query all relationships?
