### ISSUE TITLE
Neo4J web admin incorrect display of large Long property values (code attached)

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#113]
@johnoa: 'The web admin interface incorrectly displays large long property values stored on relationships.

The attached Unit test proves this.  Here you can see that the long value: 20020000000346382l is correctly held in neo4j and can be retrieved as such, however when viewed in the admin interface it is displayed as: 20020000000346384

Unit test with instructions available at:

https://gist.github.com/gists/2836562/download

This bug is specific to the web admin gui, http://localhost:7474/webadmin/#/data/search/rels%3A1/

'

**Comment by jakewins** [comment]
This has been resolved in the new neo4j-driver for javascript, which is will be included in the Neo4j browser for Neo4j 3.x
