### ISSUE TITLE
debian version numbers - now with 1: prefix

### ISSUE THREAD

**Issue by MysterAitch** [neo4j/neo4j#11342]
At some point during the last month or so (not sure precisely when as I've been away from this project for a small while), the version numbers within the debian repository seem to have gained a `1:` prefix. See below for a list of the available versions.

I have discovered the altered version numbers as they have broken some of my automated install scripts (used within vagrant to provision throwaway Ubuntu 16.04 testing/development boxes with a specific version of Neo4j installed). 

Similar output is also present in an existing server installation, leading me to believe it is not isolated to the vagrant / virtualbox environment.

```
$ apt-cache show neo4j | grep -i version
Version: 1:3.3.4
Version: 1:3.3.3
Version: 1:3.2.10
Version: 1:3.2.9-1
Version: 1:3.1.8
Version: 3.3.2
Version: 3.3.1
Version: 3.3.0
Version: 3.2.9
<etc...>
```

After doing a plain `sudo apt-get install neo4j` on a fresh box it seems that version `1:3.3.4` is currently being installed by default (as opposed to the expected but non-existent `3.3.4`) per the dpkg output below: 

```
$ dpkg -l neo4j
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                        Version            Architecture       Description
+++-===========================-==================-==================-===========================================================
ii  neo4j                       1:3.3.4            all                graph database server
```

**Comment by billscheidel** [comment]
I just hit this today as well.  Is this the new versioning scheme or will it be rolled back to standard version numbers again?

**Comment by praveenag** [comment]
Hi @MysterAitch and @billscheidel 
Few weeks back we refactored our Debian packages to follow [Debian's policy](https://www.debian.org/doc/debian-policy/#s-f-version) Unfortunately this resulted in `3.3.3` being replaced with `1:3.3.3`. 
Going forward we are adopting an epoch `1:` to our Debian packages to help us in getting the right order of upgrades. 
More details on this can be found [here](https://neo4j.com/docs/operations-manual/current/installation/linux/debian/#_installing)
