### ISSUE TITLE
neo4j-admin DOES NOT EXIST on 3.2.3 CE Windows

### ISSUE THREAD

**Issue by xznhj8129** [neo4j/neo4j#11362]
I need to dump the database and i have looked absolutely everywhere; and the admin tools, or any other kind of tool, are totally absent from the /bin in Program Files. All there is is the cypher-shell, which cannot do anything. Documentation refers to completely different things; nothing it says makes any sense for Community Edition and i cannot find any CE specific documentation. How do i get my data out of Community Edition?!

**Comment by InverseFalcon** [comment]
I just downloaded 3.2.3 Community Edition for Windows, and in the unzipped file I can see `/bin/neo4j-admin.bin` is present, so the file is absolutely there.

Where did you download this, and how did you install it? Is this the zipped version for Windows, or is this via the Desktop app?

**Comment by chrisvest** [comment]
It's not included in the `.exe` installer. You need to grab the zip file, or download via the new (and completely different) Neo4j Desktop.
