### ISSUE TITLE
Connection to the server lost. Reconnecting...

### ISSUE THREAD

**Issue by chirag912** [neo4j/neo4j#11417]
@oskarhane Im, having a very similar issue. This is my etc/neo4j/neo4j.conf data

#*****************************************************************
# Neo4j configuration
#
# For more details and a complete list of settings, please see
# https://neo4j.com/docs/operations-manual/current/reference/configuration-settings/
#*****************************************************************

# The name of the database to mount
#dbms.active_database=graph.db

# Paths of directories in the installation.
dbms.directories.data=/var/lib/neo4j/data
dbms.directories.plugins=/var/lib/neo4j/plugins
dbms.directories.certificates=/var/lib/neo4j/certificates
dbms.directories.logs=/var/log/neo4j
dbms.directories.lib=/usr/share/neo4j/lib
dbms.directories.run=/var/run/neo4j
dbms.directories.metrics=/var/lib/neo4j/metrics

# This setting constrains all `LOAD CSV` import files to be under the `import` directory. Remove or comment it out to
# allow files to be loaded from anywhere in the filesystem; this introduces possible security problems. See the
# `LOAD CSV` section of the manual for details.
dbms.directories.import=/var/lib/neo4j/import

# Whether requests to Neo4j are authenticated.
# To disable authentication, uncomment this line
#dbms.security.auth_enabled=false

# Enable this to be able to upgrade a store from an older version.
#dbms.allow_upgrade=true

# Java Heap Size: by default the Java heap size is dynamically
# calculated based on available system resources.
# Uncomment these lines to set specific initial and maximum
# heap size.
#dbms.memory.heap.initial_size=512m
#dbms.memory.heap.max_size=512m

![screen shot 2018-03-29 at 3 06 50 am](https://user-images.githubusercontent.com/5563689/38057853-61123b4a-32fe-11e8-9e87-c0b5ce21bbc3.png)

This is the error that i get as soon as i click on connect.

Ok, the Neo4j is installed on a open stack server. And im creating a ssh channel like this

ssh -L :7474:127.0.0.1:7474 ubuntu@208.75.00.001  -v -v

from my mac os terminal.

the firewall on the remote server is off as well.

I have tried many things. Please any help here would be really appreciated.

**Comment by sim51** [comment]
You are doing a tunnel on the port `7474`, so you can access the browser, but you have forgotten the BOLT port `7687`. without it, the browser can't connect to the database.

**Comment by craigtaverner** [comment]
I believe the answer above regarding the lack of ssh tunnel for the bolt port is correct and am closing this issue. Please reopen with more details on the configuration of the ssh tunnels if and the open-stack configuration if the problem is persisting.
