### ISSUE TITLE
Windows platform- Database failed to create: Error: Could not change password

### ISSUE THREAD

**Issue by incansvl** [neo4j/neo4j#11429]
- Neo4j version: Tested in Neo4J desktop 10.0.18 and 10.0.19 (engine 3.3.4)
- Operating system: Windows 10 64 bit
- API/Driver: N/a

**Issue Outline**
Although Neo4J Desktop installs and runs, attempting to create a database fails with the error-

_Database failed to create: Error: Could not change password_

I have tried various database names and passwords to prove that is not simply (say) a database name that maps to an invalid Windows pathname. I have also tried installing Neo4J for personal use (single user) or shared use (in the C;\Program Files folder).

This issue has been described in the Neo4J Stackoverflow forums by another user, so I am not the only user seeing this problem.

I have reason to believe the problem is caused by incorrect handling of file paths in Neo4J Desktop on Windows, (see below for details).

### Steps to reproduce
1. Download the installer **_neo4j-desktop-offline-1.0.19-setup.exe_**
2. Install Neo4J with default settings
3. Run Neo4J desktop
4. Select the default **_My Project_** project 
5. Select the **_New Graph->Local Graph_** option
6. Use the database name **_Database_** (default) and password **_password_**.

### Expected behavior
New graph should be created

### Actual behavior
Error occurs-

_Database failed to create: Error: Could not change password_

###Investigation
Looking at the Neo4J log file (stored at "C:\Users\myname.CORP\.Neo4jDesktop\log.log" in my case) I can see the error-

```
[2018-03-29 11:20:04:0542] [info] Executing 'C:\Users\myname.CORP\.Neo4jDesktop\neo4jDatabases\database-c2c04041-5a81-43fe-a004-56b1c47f4c1c\installation-3.3.4\bin\neo4j-admin.bat' [ 'set-initial-password', 'password' ]
[2018-03-29 11:20:08:0511] [error] Neo4jAdmin: Invoke-Neo4jAdmin : An object at the specified path C:\Users\MYNA~1.COR does not exist.
At line:1 char:163
+ ... agement.psd1'; Exit (Invoke-Neo4jAdmin set-initial-password password)
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

The **_neo4j-admin.bat_** script does actually exist at the pathname specified, but Neo4J isn't finding it.

My suspicions are (these are guesses)-

1. Neo4J hasn't been tested on a windows setup where some elements of the pathnames to either the Neo4J installation itself, or the user's personal folder (the equivalent of _~username_ for Windows) contain "long" filenames.

In our case our corporate machines are set up with personal folders that look like- `c:\users\myname.CORP`

2. Neo4J is falling foul of Windows "filename mangling" where long filenames are converted to the old DOS "8.3" format.

3. Neo4J is checking for the existence of the **_neo4j-admin.bat_** script using an incorrectly mangled pathname (maybe by truncating the pathname at a space) and therefore saying the script cannot be found.

Unfortunately the error reported at the Neo4J desktop is not  very informative.

**UPDATE**
I was able to get a new virtual machine provisioned to test Neo4J on. On the new machine my user profile directory was a "normal" (short) style name. Neo4J desktop WAS able to start and set up a new database in this environment. So to be clear:

```
User Profile Folder (example)           Result
-------------------------------        -------
C:\users\myname                        Neo4J Desktop works ok
c:\users\myname.domain                 Neo4J fails- Database failed to create: Error: Could not change password
```

**Comment by novikovag** [comment]
The same problem. Windows 10 64 bit

**Comment by ovictorain** [comment]
The same error. 

**Source of the problem:**
Some files Neo4j needed was interrupted by anti-virus software / firewall, e.g. java.exe

**My solution:**
`Remove related files from the isolation region or shutdowm anti-virus software.`

**Environment:**
Windows 7 64bit
Neo4j Desktop Version: 1.0.19

**Log:**
log.log:
```
...
[2018-04-02 10:06:35:0048] [info] Executing 'C:\Users\MyName\.Neo4jDesktop\neo4jDatabases\database-1e59e3dd-c458-4297-b787-2badbf9802e5\installation-3.3.4\bin\neo4j-admin.bat' [ 'set-initial-password', 'password' ]
[2018-04-02 10:06:35:0910] [info] Process [2504] exit with code '0', signal 'null'
[2018-04-02 10:06:35:0927] [info] Action[DATABASE_CREATION_FAILED] { id: 'database-1e59e3dd-c458-4297-b787-2badbf9802e5',
  type: 'DATABASE_CREATION_FAILED' }
[2018-04-02 10:06:37:0310] [warn] Analytics failed Error: connect ETIMEDOUT 172.217.11.78:443
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
```

**Comment by guofangfang** [comment]
我也遇到这个问题了。。关闭了杀毒软件也没用啊。。。

**Comment by ali-ince** [comment]
Hi All,

This issue should have been resolved with #11469. 

The fixed script will be included in upcoming releases. For the time being, you can override your `TEMP` and `TMP` environment variables with a path that doesn't contain MSDOS8.3 convention path entries (as suggested by @chrisp429 in #9646).

Feel free to re-open the issue if you encounter the error again with new versions.

Thanks for reporting this issue.

**Comment by mafshin** [comment]
@ali-ince  I experienced the same error on the latest version. My `TEMP` and `TMP` variables also refer to `D:\TEMP`

**Environment:**
Windows 10 64bit
Neo4j Desktop 1.1.0
Neo4j : 3.3.0 and 3.3.5

**Comment by novikovag** [comment]
I drop down neo4j

**Comment by ali-ince** [comment]
Hi @mafshin & @novikovag,

Having `TEMP` and `TMP` variables referring to `D:\Temp` or any other folder that doesn't by default fall-back to `MSDOS8.3` style naming should work fine with any version. I suspect you are experiencing another problem and kindly ask you to check related log files (which should be under `C:\Users\<Your Username>\.Neo4jDesktop` folder) and provide more details about the failure / your environment.

If you're not using Neo4j Desktop, you can also get more information about the problem if you pass `-verbose` option when invoking `neo4j.bat` script.

Thanks.

**Comment by mafshin** [comment]
@ali-ince I'm getting the same error in 1.1.7

When I try to create a new db graph in Neo4j Desktop, I face "**Database failed to create: Error: Could not change password**" error.

### Steps to reproduce

- Create a new graph db in Neo4j Desktop

Log:
[2018-07-11 21:29:31:0808] [info] Executing 'D:\Neo4j\neo4jDatabases\database-2e8bdfd4-bf24-45dd-be36-0f10db2103c3\installation-3.4.1\bin\neo4j-admin.bat' [ 'set-initial-password', '***' ]
[2018-07-11 21:29:35:0169] [error] Neo4jAdmin: Exception in thread "main" 
[2018-07-11 21:29:35:0169] [error] Neo4jAdmin: java.nio.file.InvalidPathException: Trailing char < > at index 13: C:\neo4j\conf 
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:191)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at org.neo4j.commandline.admin.AdminTool.main(AdminTool.java:45)

[2018-07-11 21:29:36:0054] [info] Process [25752] exit with code '1', signal 'null'
[2018-07-11 21:29:36:0064] [info] Action[DATABASE_CREATION_FAILED] { id: 'database-2e8bdfd4-bf24-45dd-be36-0f10db2103c3',
  type: 'DATABASE_CREATION_FAILED' }
[2018-07-11 21:30:02:0286] [info] Function[persistAppSettingsThunk]
[2018-07-11 21:30:02:0290] [info] Action[APPLICATION_OFFLINE] { type: 'APPLICATION_OFFLINE' }
[2018-07-11 21:30:02:0338] [info] Action[APPLICATION_SETTINGS_SAVED] { settings: { enableOfflineMode: true },
  type: 'APPLICATION_SETTINGS_SAVED' }
[2018-07-11 21:30:06:0590] [info] Action[SIDEBAR_OPEN_TAB] { sidebarTab: 'projects', type: 'SIDEBAR_OPEN_TAB' }

- Neo4j version: 1.1.7
- Operating system: Windows 10 64bit Enterprise Build 1803
- Desired Behavior: Create a database
- Actual: Database failed to create: Error: Could not change password

**Comment by geronimus** [comment]
I experienced this issue. The log was as follows:
```
\installation-3.4.1\bin\neo4j-admin.bat' [ 'set-initial-password', '***' ]
[2018-07-27 00:00:03:0282] [error] Neo4jAdmin: Missing closing '}' in statement block or type definition.

[2018-07-27 00:00:03:0282] [error] Neo4jAdmin:     + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException

[2018-07-27 00:00:03:0283] [error] Neo4jAdmin:     + FullyQualifiedErrorId : MissingEndCurlyBrace
```
There was a curly brace character in my password. Removing it cleared the error.

I think someone should look into this as it indicates there might be a vulnerability to statement injection attacks somewhere deep in the app.

**Comment by aonamrata** [comment]
I downloaded latest app today and still getting this error.. I tried to keep password simple as test123 still no luck. I tried setting the TMP env too and restart.

![image](https://user-images.githubusercontent.com/1792005/47735565-c6983580-dc92-11e8-98a2-1f8f470039ce.png)

**Comment by xiaozw123** [comment]
I also encountered such a problem, uninstall or reinstall the same error.

**Comment by anacarlagb** [comment]
Hello guys. 
 I have found encountered the same problem in Windows 8.
 How to fix this problem? 
Thank you.

**Comment by ali-ince** [comment]
Hi @geronimus,

Thanks for pointing out the statement injection problem you've experienced.

This is now addressed with commits https://github.com/neo4j/neo4j/commit/78bc19699ea292041eb8dcb925dadac782ee17f8 and https://github.com/neo4j/neo4j/commit/d86a4f5d4aeeacdabf2e4456a2d5194ab8fb9ff5 which will be included in upcoming 3.5 releases.

Thanks again.

Ali

**Comment by ali-ince** [comment]
@aonamrata, @xiaozw123 and @anacarlagb - a similar issue is already being tracked in neo4j-desktop project site at https://github.com/neo4j-apps/neo4j-desktop/issues/40. It would be really helpful if you could also post your configuration and verbose log outputs as suggested in the issue.

I'm closing this once since the original issue (MSDOS8.3 path string not being recognised) and the statement injection problem reported later on are now addressed.

Thanks.

**Comment by tomerh2001** [comment]
has anyone managed to fix the problem?
i am trying to get started with neo4j for my company and i can't start because i can't even create a graph to start using the program....

i've been searching for a solution for a couple of hours without even starting with neo4j beacuse i just cant...

**Comment by aonamrata** [comment]
Hey @tomergt45 I was able to get this working with latest neo4j desktop version and have my own local database created from UI on windows. 
```
About Neo4j Desktop
Version: 1.1.15
```
and database with `Neo4j 3.4.9 `  Try https://neo4j.com/download/

**Comment by mafshin** [comment]
You can use it with Docker, it's easier to setup than on Windows

https://neo4j.com/developer/docker

**Comment by Sceurpien** [comment]
I had the same issue, and I wrote a simple article how you can manage to start Neo4j on a Win10 computer.

https://www.linkedin.com/pulse/how-kill-neo4j-soon-you-start-g%C3%A1bor-imre-bata-kov%C3%A1cs/

I hope it helps.

**Comment by wilsonmar** [comment]
I'm encountering the same error message, but I'm on MacOS Mojave, trying with neo4j/3.5.12/ installed from brew. I don't see a client folder in /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin
