### ISSUE TITLE
APOC ProcedureCallFailed

### ISSUE THREAD

**Issue by 444728248** [neo4j/neo4j#11435]
#CQL
MATCH (user:CaseInfo) WHERE user.XKBH = 'K00001'
CALL apoc.path.subgraphAll(user, {maxLevel:2,relationshipFilter:'DNA串并'}) YIELD nodes, relationships
RETURN nodes, relationships;

## Neo.ClientError.Procedure.ProcedureCallFailed
Failed to invoke procedure `apoc.path.subgraphAll`: Caused by: java.lang.NoClassDefFoundError: org/apache/commons/collections/IteratorUtils

**Comment by sim51** [comment]
You should open this issue on the APOC respository, not on the Neo4j one : https://github.com/neo4j-contrib/neo4j-apoc-procedures/

Moreover, can you give more details ? (neo4j version, apoc version, etc)
