### ISSUE TITLE
multiple optional match takes too much time. Suggest better way

### ISSUE THREAD

**Issue by rishu5391** [neo4j/neo4j#11444]
MATCH (m:Merchant)-[:HAVING_CATEGORY]->(c:Category) WHERE ( m.status IN [1,2]) WITH m, c OPTIONAL MATCH (m)-[:HAVING_STORE]->(s:Store) WITH m,c,s OPTIONAL MATCH (s)-[:HAVING_COUPON]->(d:Coupon) WITH m,c,s, d OPTIONAL MATCH (u:User)-[rd:REDEEMED]->(d) WITH m, c, s, d, rd, u OPTIONAL MATCH (d)<-[f:HAVE_FAVORITE]-(fu:User)  OPTIONAL MATCH (v:Activity {activity:1, coupon_id:d.id}) OPTIONAL MATCH (rmp:Redeemption {merchant_id:m.id}) WITH m, c, s, d, rd, u, fu, v, rmp RETURN DISTINCT id(m) as id, m.id as merchant_id, m.name as name,  m.email as email, m.contact as contact, m.created_date as created, m.status as status, m.address as address, c.name as category_name, count(DISTINCT s) as store, count(DISTINCT d) as deal, m.subcategory_items as venue_type, m.price_range as price_range, m.classification as classification, count(DISTINCT rd) as redeemed_deal, count(DISTINCT u) as total_user, count(DISTINCT fu) as favorite, count(DISTINCT v.user_id) as views, sum(rmp.total_amount) as performance ORDER BY created DESC SKIP 0 LIMIT 10

**Comment by InverseFalcon** [comment]
I'll have to take a deeper look later, but from the look of this you only want this to be limited to 10 merchants (the rest of the data is aggregated).

If this is so, then you can move your ORDER BY and LIMIT up near the top:

```
MATCH (m:Merchant)-[:HAVING_CATEGORY]->(c:Category) 
WHERE m.status IN [1,2]
WITH m, c
ORDER BY m.created_date DESC
SKIP 0 LIMIT 10
...
```

This way you limit yourself to 10 nodes at the very beginning (assuming a merchant only has a single category), and the subsequent operations only act upon those 10 nodes. Currently your limit is at the end, so you perform your operations on all possible :Merchant nodes that match, which could be a huge number of nodes and calculations, and only then do you perform the limit.

**Comment by billscheidel** [comment]
The short answer is to never use OPTIONAL MATCH.  You can use this syntax instead which does the standard match and then optionally matches additional nodes if they exist.

````
MATCH (n:Foo)-[:IS_A]->(m:Bar)
WITH n, m, [(m)-[:HAS]->(b:Baz) | b] AS bazes
````

This query will optionally return the `bazes` that `m` has.  It will be null if there were none but the query will continue.

**Comment by InverseFalcon** [comment]
@billscheidel Close, but when using [pattern comprehension](https://neo4j.com/docs/developer-manual/current/cypher/syntax/lists/#cypher-pattern-comprehension) as in your example, `bazes` is a collection, so if there are no such matches from the pattern, `bazes` will be an empty collection.

As you say, though, the query will continue, and this is a great way to avoid cardinality issues in a query if you want a collection of results rather than rows.

**Comment by SaschaPeukert** [comment]
Are you happy with that approach @daflidafli ?

**Comment by rishu5391** [comment]
MATCH (m:Merchant)-[:HAVING_CATEGORY]->(c:Category) 
WHERE m.status IN [1,2]
WITH m, c
ORDER BY m.created_date DESC
SKIP 0 LIMIT 10

this approach is good but in case if i want to add dynamic order by which is based on aggregation, its taking too much time
