### ISSUE TITLE
Performance issue encountered with cypher query

### ISSUE THREAD

**Issue by rolandobermudez** [neo4j/neo4j#11463]
- Neo4j version: 3.3.4 Enterprise
- Operating system: CentOS 7
- API/Driver: Web Console/Cypher
- We reproduce it in our database
- Normal Performance
- Statement execution performing a database scan

## Bug report

We discovered that the queries were taking too long, too many db hits, specifically the following query.

`PROFILE MATCH (n:Identity:Principal:T4:Taggable:User:UserAccount)-[r:HAS_STATUS]->(m) WHERE ID( n ) = 2307238 AND (m:T4 OR m:T0) RETURN n, r, m`

Profiler results:

[query 1 profiler.txt](https://github.com/neo4j/neo4j/files/1876924/query.1.profiler.txt)

Now if i change the direction of the match clause, the execution plan does not perform a database scan and execution time is highly reduced.

`PROFILE MATCH (m)<-[r:HAS_STATUS]-(n:Identity:Principal:T4:Taggable:User:UserAccount) WHERE ID( n ) = 2307238 AND (m:T4 OR m:T0) RETURN n, r, m;`

Profiler results:

[query 2 profiler.txt](https://github.com/neo4j/neo4j/files/1876927/query.2.profiler.txt)

Forcing the use of CYPHER 3.2 at execution time solves the problem.

`PROFILE CYPHER 3.2 MATCH (n:Identity:Principal:T4:Taggable:User:UserAccount)-[r:HAS_STATUS]->(m) WHERE ID( n ) = 2307238 AND (m:T4 OR m:T0) RETURN n, r, m`

The issue is not present on Neo4j 3.1.1 Enterprise

**Comment by Lojjs** [comment]
@rolandobermudez Thanks for reporting, this sounds like a bug. We will take a look and come back to you.

Best regards Louise, Neo4j Cypher team

**Comment by systay** [comment]
Hi @rolandobermudez!

This was an interesting bug. It's difficult to reproduce the problem on our end without a copy of the db. If you are able and willing to share the db, it would really help us figure out where the planning is going wrong.

Best, Andrés

**Comment by rolandobermudez** [comment]
@systay @Lojjs Thank you for getting back on this, i will have a copy of the database soon to share.

**Comment by rolandobermudez** [comment]
@systay i have a 489 MB db backup, let me know where should i put it for you to get it.

**Comment by systay** [comment]
If you contact me privately we'll figure something out: andres `at` neo4j `dot` com. Thanks for sharing!
