### ISSUE TITLE
multiple spaces in query not work

### ISSUE THREAD

**Issue by saiwaiyanyu** [neo4j/neo4j#11490]
## Guidelines

- Neo4j version: 3.3.0
- Operating system: MAC OSX
- **Steps to reproduce**
- Expected behavior
- Actual behavior

Additionally, include (as appropriate) log-files, stacktraces, and other debug output.

---

## example 1
1. `neo4j-shell`
2. `RETURN LENGTH('1 2') AS L1;`
3. `RETURN LENGTH('1            2') AS L1;`

there`re **multiple spaces** between 1 and 2;

both results

```
+----+
| L1 |
+----+
| 3  |
+----+
```

---
## example 2
```
CREATE (:TEST{TEST_ID:'1 2'});
CREATE (:TEST{TEST_ID:'1  2'});
CREATE CONSTRAINT ON (n:TEST) ASSERT n.TEST_ID IS UNIQUE;
```
result is 
```
WARNING: Unable to create CONSTRAINT ON ( test:TEST ) ASSERT test.TEST_ID IS UNIQUE:
Both Node(108) and Node(148) have the label `TEST` and property `TEST_ID` = '1 2'
```
it seems that the spaces in the strings  don`t work?

**Comment by Lojjs** [comment]
@saiwaiyanyu Thanks for reporting, this seems like a bug. We in the Neo4j Cypher team will have a look and come back to you.

Best regards Louise

**Comment by craigtaverner** [comment]
The fix is in https://github.com/neo4j/neo4j/pull/11584 and should come out in the next maintenance releases of 3.1 and above.
