### ISSUE TITLE
performance issue in importing file with cypher queries using cypher shell

### ISSUE THREAD

**Issue by kirancodify** [neo4j/neo4j#11532]
While trying to import data into neo4j using the cypher shell, the import takes a very long time to complete . 

Neo4j DB:
  Version:  3.3.4
  Edition: Community

Environment:
  Ubuntu VM 64-bit
  CPU: 2 cores
  RAM: 8 GB 

Neo4j configuration
    dbms.memory.heap.initial_size=4096m
    dbms.memory.heap.max_size=4096m
   dbms.memory.pagecache.size=2g

Graph info
   total nodes  524,917
   total relationships 2,987,757 

The export using the apoc library takes less than a minute for the graph using 
#Export all batch size 10000
time cypher-shell -a $url -u $user -p $password "$exportAllBatchSize10000"
Output : 
1 row available after 50006 ms, consumed after another 0 ms
real    0m53.879s
user    0m1.388s
sys     0m0.092s

But importing the same data back using the cypher-shell command to a new instance with the same configurations and environment is taking over 3 hours.
cypher-shell -a $url -u $user -p $password < "$importCypherShell">"$outputFile"
real    181m14.310s
user    51m13.460s
sys     5m10.196s

Is this an expected behavior? . Is there a way to expedite the process so that the import performance is better.

**Comment by craigtaverner** [comment]
Can you provide the apoc and cypher queries, in particular the contents of the files defined by:

* exportAllBatchSize10000
* importCypherShell

**Comment by mnd999** [comment]
This is an old update which hasn't received any updates in some time so I will close it. If you're still having the issue, please feel free to reopen it.
