### ISSUE TITLE
NEO4J Cypher Query: Relationship Direction Bug in Where Clause

### ISSUE THREAD

**Issue by srinathganesh1** [neo4j/neo4j#11542]
Sample Graph:
![image](https://user-images.githubusercontent.com/11017158/38729992-83701118-3f32-11e8-9815-5a67489d71ae.png)

Sample Query:
```
CREATE (a1:A {title: "a1"})
CREATE (a2:A {title: "a2"})
CREATE (a3:A {title: "a3"})

CREATE (b1:B {title: "b1"})
CREATE (b2:B {title: "b2"})

MATCH (a:A {title: "a1"}), (b:B {title: "b1"})
CREATE (a)-[r:LINKS]->(b)

MATCH (a:A {title: "a2"}), (a1:A {title: "a1"}) 
CREATE (a)-[:CONNECTED]->(a1)

MATCH (a:A), (b:B) return a,b
```

**Objective: Finding some connections in the where clause**

Now lets write some variations to find A's not directly connected to B (a2 and b3)

```

// Q1. Both work fine
MATCH (a:A) WHERE (a)--(:B) RETURN a
MATCH (a:A) WHERE (:B)--(a) RETURN a

// Q2. Works
MATCH (a:A)-[r]-(b:B) WHERE (a)-[r]-(b) RETURN a

// Q3. Fails
MATCH (a:A)-[r]-(b:B) WHERE (b)-[r]-(a) RETURN a
```

Any idea why Q2, Q3 are not behaving the same way even if the direction is specified as bi-directional? Is this a NEO4J **bug**?

All credits to [stdob](https://stackoverflow.com/users/4989460/stdob) for narrowing down this anomaly for me. 

Stackoverflow post:
- [Post](https://stackoverflow.com/questions/49814707/neo4j-cypher-query-relationship-direction-bug-in-where-clause)
- [Related](https://stackoverflow.com/questions/49797354/neo4j-finding-disconnected-nodes/49798661#49798661)

**Comment by Lojjs** [comment]
@SrinathG910 Thanks for reporting, in order to investigate this further, we need to know which version of Neo4j you are using?

Best regards Louise, Neo4j Cypher Team

**Comment by srinathganesh1** [comment]
My neo4j is **neo4j-community-3.3.1** and based on the stackoverflow comments, discussions I doubt that this is version dependent.

**Comment by Lojjs** [comment]
@SrinathG910, thanks I can reproduce it in earlier versions also, so will we aim for 3.1 (which is the earliest currently supported version) with the fix.

/Louise

**Comment by sherfert** [comment]
@fickludd Did your PR fix this issue?

**Comment by fickludd** [comment]
@sherfert yes, this is fixed.
