### ISSUE TITLE
relationships cannot be added to nodes with a certain label

### ISSUE THREAD

**Issue by pawpawya** [neo4j/neo4j#11558]
our neo4j version is 3.2.1. 

Sometimes relationships cannot be added to nodes with a certain label, when others are not, but the exists relationships attached to those nodes can be deleted.

And the only thing we can do to recover it is restarting our neo4j.
Our data is not very big, just fifty thounds nodes and twice relationships.

This has happened several times , is that a bug with the db lock? or if someone can give me some advice.

**Comment by pawpawya** [comment]
the problem happened again, but this time only the node with some certain properties cannot be create.
we have uniqueness constraint on our Label A(code) , 
my cypher is  like create (n:A {code:"a"}) . i execute it on the web with no response.
but when i change the state to  create (n:A {code:"b"}), it's ok.

S: we use neo4j-ogm in our java project, i find this problem always happened after some statement violating the uniqueness constraint.

**Comment by SaschaPeukert** [comment]
Hey @pawpawya , what edition of neo4j (community/enterprise) are you using? I tried to reproduce your problem with enterprise 3.2.11 but it worked for me so far. Could you try to update to 3.2.11 (or higher) and tell me how to reproduce the problem if it still occurs?

**Comment by pawpawya** [comment]
Thank you for your attention @SaschaPeukert . My neo4j version is  neo4j3.2.1-enterprise, using cypher.default_language_version=3.1.
We have fix this problem. It's a bug of neo4j-ogm2.1.2.When statement violating the uniqueness constraint it happened. But after updating to neo4j-ogm 3.0.0 ,it works fine.
