### ISSUE TITLE
More consistent version number details (from REST)

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#116]
@nigelsmall: 'Currently, the version number returned by the root REST endpoint has limited value to consuming applications. Not only does the format vary a great deal (mixture of separators, words and numbers) but often there is a lack of any real connection to the actual server version being accessed.

For example, I am currently running against "1.8-SNAPSHOT" but am given a neo4j_version value of "jenkins-community-1553" which does not even mention "1.8". Build numbers are of course useful, but it would be good to see a standardisation which matches the download page, plus the build information if deemed necessary.

There are two main uses that I can think of for version numbers from a library perspective - to allow the user to access for display or use within their application and to allow feature "detection" by sniffing the version (which may not be the best pattern but is the only tool I have for some features). Neither of those are well supported with the current information available.'

**Comment by jakewins** [comment]
This has now been standardized to use semver. Also we hired the issue reporter here, and we have now implemented a new protocol with a single incrementing integer as version, I guess you were going for the long con here all along Nige..
