### ISSUE TITLE
Neo4J Desktop Signin is disabled

### ISSUE THREAD

**Issue by bonej079** [neo4j/neo4j#11608]
- Neo4j version: 3.3.5
- Neo4J desktop version: 1.0.22
- Operating system: Ubuntu 16.04.4 LTS (running MATE desktop)
- **Steps to reproduce**
Installed Neo4J Desktop
Signin button should be enabled

- Actual behavior
Signin button is disabled

On hover, the link shows "Offline"

Also, about box is blank, ie. it shows nothing.

Thanks,
JB
![neo4j-report](https://user-images.githubusercontent.com/11914535/38987597-a4ba7c62-43d0-11e8-9b4e-fb5e4f16b1e6.png)

**Comment by oskarhane** [comment]
Closing this since there have been several updates since April. If the issue still persists, please open a new issue in https://github.com/neo4j-apps/neo4j-desktop
