### ISSUE TITLE
Weird behaviour in load csv

### ISSUE THREAD

**Issue by lapwat** [neo4j/neo4j#11624]
Hello, I am trying to load from a csv file with:

This query does not return anything
```cypher
LOAD CSV WITH HEADERS FROM "file:///file.csv" AS line
WITH line
MATCH o=(:Place {id: line.id_origin})-[:Child*]->(), d=(:Place {id: line.id_destination})-[:Child*]->()
return o, d
```

Whereas those one return something:
```cypher
LOAD CSV WITH HEADERS FROM "file:///file.csv" AS line
WITH line
MATCH o=(:Place {id: line.id_origin})-[:Child*]->()
return o
```
```cypher
LOAD CSV WITH HEADERS FROM "file:///file.csv" AS line
WITH line
MATCH d=(:Place {id: line.id_destination})-[:Child*]->()
return d
```

I don't understand what I do wrong because d and o are independant...

Thanks for your help,
lapwat

**Comment by SaschaPeukert** [comment]
@lapwat Thanks for reporting, in order to investigate this further, could you provide us with a sample dataset (or some cypher statements to generate it) and a matching CSV file, where you observed this behavior? Also, could you tell us which version of Neo4j you are using?

**Comment by lapwat** [comment]
I am unable to give you the sample I am sorry. It has been a while and I have switched on a custom solution.
Thank you for your response.
