### ISSUE TITLE
Problems when starting -neo4j start-

### ISSUE THREAD

**Issue by denebtech** [neo4j/neo4j#11649]
It does not start the neo4j service and when executing the following command, it gives me this result:

admin@admin-W240HU-W250HUQ:~$ sudo service neo4j status
● neo4j.service - Neo4j Graph Database
   Loaded: loaded (/lib/systemd/system/neo4j.service; disabled; vendor preset: enabled)
   Active: inactive (dead)

abr 24 19:09:20 topomix-W240HU-W250HUQ neo4j[13448]: Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.databas
abr 24 19:09:20 topomix-W240HU-W250HUQ neo4j[13448]:         at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:46
abr 24 19:09:20 topomix-W240HU-W250HUQ neo4j[13448]:         at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
abr 24 19:09:20 topomix-W240HU-W250HUQ systemd[1]: neo4j.service: Main process exited, code=exited, status=1/FAILURE
abr 24 19:09:20 topomix-W240HU-W250HUQ systemd[1]: neo4j.service: Unit entered failed state.
abr 24 19:09:20 topomix-W240HU-W250HUQ systemd[1]: neo4j.service: Failed with result 'exit-code'.
abr 24 19:09:20 topomix-W240HU-W250HUQ systemd[1]: neo4j.service: Service hold-off time over, scheduling restart.
abr 24 19:09:20 topomix-W240HU-W250HUQ systemd[1]: Stopped Neo4j Graph Database.
abr 24 19:09:20 topomix-W240HU-W250HUQ systemd[1]: neo4j.service: Start request repeated too quickly.
abr 24 19:09:20 topomix-W240HU-W250HUQ systemd[1]: Failed to start Neo4j Graph Database.

**Comment by DouglasLapsley** [comment]
I'm getting this for the first time today too.  Did you find a solution please?

**Edit:**  Solved.  In my case I had just changed the folder name for the project and so the entry in /etc/neo4j/neo4j.conf was making it fail because it had the old path.  Doh!

**Comment by sageantony** [comment]
I got this error today. In my case, the JVM is auto-upgraded to v10, whereas,  the neo4j server require JVM v8. Once I pointed the JVM back to v8, the issue is solved.

**Comment by MishaDemianenko** [comment]
@sageantony may I ask You to provide logs to see what exactly went wrong? Thx in advance!

**Comment by sageantony** [comment]
@MishaDemianenko Hi!  The logs were same as above. I knew that my neo4j.service file is right. And, I tried doing the below:

systemctl daemon-reload
systemctl stop neo4j
systemctl disable neo4j
systemctl enable neo4j
systemctl start neo4j

But still, the problem persisted. Then I checked my neo4j.conf file to find if any issues there. Everything seemed to be OK. Later, I realized that after the recent system update, JVM started pointing to v10 instead of v8 (I have both v8 and v10 installed in my development machine). So, I used the below command and pointed to v8.

sudo update-alternatives --config java

This fixed my problem.

**Comment by elR1co** [comment]
Hi,

following my discussion with @jexp [here](https://community.neo4j.com/t/neo4j-community-compatability-with-java-11/2537/19), I have the same problem described here.

I am able to run Neo4j with Java 11 on a brand new Amazon Linux 2 instance, but it fails to start again after instance reboot. And I get the same error message than [above](https://github.com/neo4j/neo4j/issues/11649#issue-317415951). With Amazon Linux 1, Neo4j doesn't even start with Java 11. Moving back to Java 8 is the only way to start it.

I see that people above have all solved the problem by moving back to Java 8. But is there any way to run definitely Neo4j with Java > 8 ?

Thanks.

**Comment by calvindoro** [comment]
> I'm getting this for the first time today too. Did you find a solution please?
> 
> **Edit:** Solved. In my case I had just changed the folder name for the project and so the entry in /etc/neo4j/neo4j.conf was making it fail because it had the old path. Doh!

Hi Douglas, could u explain what do u mean by just changing the folder name ?

**Comment by DouglasLapsley** [comment]
Sure.  In file /etc/neo4j/neo4j.conf you specify the location of your database file.  It's an entry something like this, depending on what your setup is:

`# Paths of directories in the installation.
dbms.directories.data=/home/doug/Desktop/myWorkingFolder/someSubfolder`

I just had the wrong path in there.  Updating that to the correct location worked (I had just been working with other DBs).
