### ISSUE TITLE
Cypher performing allNodesScan instead of nodeByIdSeek

### ISSUE THREAD

**Issue by fpusch** [neo4j/neo4j#11677]
When performing the following two queries cypher performs an allNodesScan instead of a nodeByIdSeek for the first one.

**Neo4j Version:** 3.3.5
**Operating System:** RHEL 7.3
**API:** Cypher

### Steps to reproduce
1. Let cypher explain this query: 
```
EXPLAIN
MATCH (aNode) WHERE id(aNode) = 12345
WITH aNode 
MATCH (bNode) WHERE id(bNode) = 54321 
RETURN *
```
2. Let cypher explain this query
```
EXPLAIN
CYPHER 2.3
MATCH (aNode) WHERE id(aNode) = 12345
WITH aNode 
MATCH (bNode) WHERE id(bNode) = 54321 
RETURN *
```

### Expected behavior
Both queries should perform an id seek.

### Actual behavior
Only the second query seeks by Id.

A query similar to the one above is executed for example by Spring Data Neo4j / Neo4j OGM when persisting `@RelationshipEntities` leading to poor performance.

This issue looks similar to [11463](https://github.com/neo4j/neo4j/issues/11463), however setting Cypher 3.2 does not solve the issue.

Edit:
I have done some further local testing with a clean database on Windows. 

It appears to be an issue limited to Neo4j 3.3.5. Performing the same queries on Neo4j 3.3.4 leads to both queries performing the same faster nodeByIdSeek. Upgrading to Neo4j 3.3.5 and running the queries results in the explained issue.

**Comment by SaschaPeukert** [comment]
@fpusch Thanks for reporting. I could reproduce it and this seems like a bug to me. I will let you know when it's fixed.

Best regards
Sascha, Neo4j Cypher Team

**Comment by OliviaYtterbrink** [comment]
This has been fixed by https://github.com/neo4j/neo4j/pull/11555, though the introduced setting is disabled by default for older versions as mentioned in the PR.

3.3.6 will contain this fix, disabled by default. In 3.4.0 it is enabled by default and your example query does indeed use the nodeByIdSeek operator.
