### ISSUE TITLE
Java 10: Illegal reflective access by org.neo4j.io.pagecache.impl.SingleFilePageSwapper

### ISSUE THREAD

**Issue by cypressious** [neo4j/neo4j#11728]
- Neo4j version: 3.4.0-RC01
- Operating system: Windows 10

When starting an embedded instance of Neo4j 3.4.0-RC01 on a JDK 10, the following warning is written to the console:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.neo4j.io.pagecache.impl.SingleFilePageSwapper (file:/C:/Users/Kirill/.gradle/caches/modules-2/files-2.1/org.neo4j/neo4j-io/3.4.0-rc01/e8f517ee0c8eacd452c938d77f8fe2778023b329/neo4j-io-3.4.0-rc01.jar) to field sun.nio.ch.FileChannelImpl.positionLock
WARNING: Please consider reporting this to the maintainers of org.neo4j.io.pagecache.impl.SingleFilePageSwapper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by chrisvest** [comment]
We know about it. Neo4j 3.4 is based on Java 8, and we have no plans to change that until 4.0. Until then, you can either ignore the warning – it's harmless – or run Neo4j on Java 8.

**Comment by joelhandwell** [comment]
For those who came via google here, you can suppress the warning by giving following JVM option or set ```JAVA_OPTS``` environment variable:

```
--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED 
```
