### ISSUE TITLE
Neo4J-community-3.3.5 Unable to determine the version of the installation Neo4j-Management.psd1

### ISSUE THREAD

**Issue by glaulom** [neo4j/neo4j#11779]
After downloading Neo4J 3.3.5 Community and unzipping the .zip, I tried to launch it with my console (as administrator) and encountered the following error : 

<img width="536" alt="capture" src="https://user-images.githubusercontent.com/25532110/40064767-83ab098e-5860-11e8-95aa-f3b835d73aab.PNG">

**Neo4j Version:** 3.3.5  
**Operating System:** Windows 10 Professional 
**API:** jdk-8u171-windows-x64
**Path** : I've added _C:\Program Files\Java\jre1.8.0_171\bin_ in my PATH

### Steps to reproduce
1. Unzip _neo4j-community-3.3.5-windows.zip_
2. Launch bin\neo4j console

I have not been able to find other people with this error, am I missing out something or is this a concrete bug ?

**Comment by glaulom** [comment]
Even stranger, I've downloaded again the .zip, extracted it at the exact same path, and now

> bin\neo4j console

 is working perfectly... I can't see what could have changed between this time and the last one as I have not used the computer in between.

**Comment by craigtaverner** [comment]
@glaulom Thanks for reporting this. If no-one else has seen this error, and it is no longer occurring for you, I think we can close it for now, but feel free to re-open it if you see this problem again.

**Comment by germain05** [comment]
i have the same problem actually
