### ISSUE TITLE
Incorrect behaviour of the explicit/manual indexes

### ISSUE THREAD

**Issue by Artgit** [neo4j/neo4j#11789]
Neo4j version: Neo4j 3.3.5 Community Edition
APOC apoc-3.3.0.2-all.jar

I found the following issue with Neo4j manual indexes when the index is not updated(and lost their data) on relationship property update. Looks like this issue relates to the Neo4j core.

**How to reproduce the issue with APOC:**

I have created the following trigger:

    CALL apoc.trigger.add('TEST_TRIGGER', "UNWIND keys({assignedRelationshipProperties}) AS key UNWIND {assignedRelationshipProperties}[key] AS map WITH map WHERE type(map.relationship) = 'LIVES_IN' CALL apoc.index.addRelationship(map.relationship, keys(map.relationship)) RETURN count(*)", {phase:'before'})

verified that trigger exists by `CALL apoc.trigger.list()`

create the following nodes and relationship:

    CREATE (p:Person) return p
    CREATE (c:City) return c
    
    MATCH (p:Person), (c:City) CREATE (p)-[r:LIVES_IN]->(c) RETURN type(r)

tried to access it by index query:

    MATCH (p:Person)-[r:LIVES_IN]->(c:City) CALL apoc.index.in(c, 'LIVES_IN', 'time:10') YIELD node AS person RETURN person

the query returns empty result which is fine for now.

assigned relationship new property `time` with value = `10`:

    MATCH (p:Person)-[r:LIVES_IN]->(c:City) SET r.time = 10 RETURN r

tried to access it by index query:

    MATCH (p:Person)-[r:LIVES_IN]->(c:City) CALL apoc.index.in(c, 'LIVES_IN', 'time:10') YIELD node AS person RETURN person

the query successfully returns the expected `Person` node

Now, I reassigned the `time` property another value = `11`

    MATCH (p:Person)-[r:LIVES_IN]->(c:City) SET r.time = 11 RETURN r

tried to access it by index query one more time:

    MATCH (p:Person)-[r:LIVES_IN]->(c:City) CALL apoc.index.in(c, 'LIVES_IN', 'time:10') YIELD node AS person RETURN person
    MATCH (p:Person)-[r:LIVES_IN]->(c:City) CALL apoc.index.in(c, 'LIVES_IN', 'time:11') YIELD node AS person RETURN person

the query returns empty result for both of them.. 

What am I doing wrong and why was the index not updated after the property change? 

This is also the corresponding StackOverflow question on this issue: https://stackoverflow.com/questions/50254049/neo4j-apoc-assignedrelationshipproperties-removedrelationshipproperties-trigger

**Comment by Artgit** [comment]
**How to reproduce this issue on Neo4j built-in procedures to manage and use explicit indexes:**

I have created the following trigger:

    CALL apoc.trigger.add('TEST_TRIGGER', "UNWIND keys({assignedRelationshipProperties}) AS key UNWIND {assignedRelationshipProperties}[key] AS map WITH map WHERE type(map.relationship) = 'LIVES_IN' CALL apoc.index.addRelationship(map.relationship, keys(map.relationship)) RETURN count(*)", {phase:'before'})

verified that trigger exists by `CALL apoc.trigger.list()`

create the following nodes and relationship:

    CREATE (p:Person) return p
    CREATE (c:City) return c
    
    MATCH (p:Person), (c:City) CREATE (p)-[r:LIVES_IN]->(c) RETURN type(r)

tried to access it by index query:

    MATCH (c:City)  CALL db.index.explicit.searchRelationshipsOut('LIVES_IN', c, 'time:10') yield relationship RETURN relationship

the query returns error `Neo.ClientError.LegacyIndex.LegacyIndexNotFound: Relationship index LIVES_IN not found` which I think is fine for now.

assigned relationship new property `time` with value = `10`:

    MATCH (p:Person)-[r:LIVES_IN]->(c:City) SET r.time = 10 RETURN r

tried to access it by index query:

    MATCH (c:City)  CALL db.index.explicit.searchRelationshipsOut('LIVES_IN', c, 'time:10') yield relationship RETURN relationship

the query successfully returns the expected relationship.

Now, I reassigned the `time` property another value = `11`

    MATCH (p:Person)-[r:LIVES_IN]->(c:City) SET r.time = 11 RETURN r

tried to access it by index query one more time:

    MATCH (c:City)  CALL db.index.explicit.searchRelationshipsOut('LIVES_IN', c, 'time:10') yield relationship RETURN relationship
    MATCH (c:City)  CALL db.index.explicit.searchRelationshipsOut('LIVES_IN', c, 'time:11') yield relationship RETURN relationship

the query returns empty result for both of them.. 

I'd be really grateful if you can verify and fix this issue because right now I'm blocked in my work :(

**Comment by SaschaPeukert** [comment]
Hej @Artgit !
Thanks for reporting. Its a bit tricky for me to decide if this is an apoc or neo4j issue. Could you provide us with steps to reproduce this without apoc in them? Also, your parameter "assignedRelationshipProperties" is not defined, which makes this a bit hard to understand/debug.

**Comment by Artgit** [comment]
Hi @SaschaPeukert , I apologize but I tried to reproduce it with pure Neo4j procedures but failed. Also, I'd like to add that this issue is gone with Neo4j 3.4.0 and last APOC version.
