### ISSUE TITLE
[Cypher][3.3.5][3.4] Node property not treated as null

### ISSUE THREAD

**Issue by ikwattro** [neo4j/neo4j#11784]
**Neo4j Version:** 3.3.5 and 3.4
**Operating System:** any
**API:** Browser

### Steps to reproduce

```
CREATE (n:Document) SET n.title = "Hello World"
```

```
MATCH (n:Document) SET n.text = n.title + ". " + n.text
```

### Expected behavior

A new property `text` is assigned to the node with value `Hello World. `

### Actual behavior

No property `text` is assigned.

Note that the behaviour is the same if I use another non-existing property, for eg : 

```
MATCH (n:Document) SET n.text = n.title + ". " + n.description
```

will have the same behavior

**Comment by hdk** [comment]
You are concatenating nulls (n.text is null) and so the resulting string is null!
see https://stackoverflow.com/questions/26107677/concatenating-nulls-in-cypher

use something like 
.... SET n.text = n.title + ". " + coalesce(n.text,"")

**Comment by ikwattro** [comment]
Yeah, thanks. My bad.
