### ISSUE TITLE
Batch inserting API improvement

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#118]
@fgavilondo: 'I would like to suggest an improvement to the batch inserting API.

As explained in http://docs.neo4j.org/chunked/stable/batchinsert.html, you can either work with plain BatchInserters, which in turn can be used to create BatchInserterIndexProviders, or you can work with a batch graph database obtained via BatchInserters.batchDatabase(), but then you get no indexing functionality since the batch database's own inserter is not exposed (package private visibility); and creating a separate inserter just for indexing probably won't have the desired outcome.

I want to be able to do both, use a batch graph db and indexing in a simple way. Essentially, I'm suggesting this:

GraphDatabaseService batchDb = BatchInserters.batchDatabase("graph.db");
BatchInserterIndexProvider indexProvider = new LuceneBatchInserterIndexProvider(batchDb); // not possible today
BatchInserterIndex index = ...

Now, I think I can achieve the above today with a nasty trick by creating a class in the corresponding neo4j package in my code base:

package org.neo4j.unsafe.batchinsert;

import org.neo4j.graphdb.GraphDatabaseService;

public final class BatchDbWorkAround {
    public static BatchInserterIndexProvider createLuceneBatchInserterIndexProvider(GraphDatabaseService batchDb) {
        BatchInserter inserter = ((BatchGraphDatabaseImpl) batchDb).getBatchInserter();
        return new LuceneBatchInserterIndexProvider(inserter);
    }
}

But I'm not sure that it is safe to do so and I think there should be an easier way.

'

**Comment by tinwelint** [comment]
Marking as closed since the batch graph database service have been removed in later versions of Neo4j
