### ISSUE TITLE
Neo4j backup is not working when custom KernelExtensionFactory is used

### ISSUE THREAD

**Issue by vikshe** [neo4j/neo4j#11805]
- Neo4j version: 3.3.5 Enterprise
- Operating system: (Unix)

- **Steps to reproduce**
- Write custom KernelExtensionFactory which has dependency for GraphDatabaseService
- Run backup

**Actual behavior
 Backup failed. Error message:
Initiating metrics...
command failed: Failed to do consistency check on backup: Component 'com.ubs.gdd.lineage.neo4j.procedures.config.MyLifecycle@5b9396d3' was successfully initialized, but failed to start. Please see the attached cause exception "No dependency satisfies type interface org.neo4j.graphdb.GraphDatabaseService".

Code is working fine when deployed and running neo4j. but it fails only for backups on linux. on windows it is working fine.

Code :
public class MyExtensionFactory extends KernelExtensionFactory<MyExtensionFactory.Dependencies> {
    public MyExtensionFactory() {
        super("MyExtensionFactory");
    }

    @Override
    public Lifecycle newInstance(KernelContext kernelContext, Dependencies dependencies) throws Throwable {
        return new MyLifecycle(dependencies);
    }

    public interface Dependencies {
        GraphDatabaseService db();

        JobScheduler scheduler();

        Procedures procedures();

        LogService log();

        Config config();
    }

}

public class MyLifecycle extends LifecycleAdapter {
    private MyExtensionFactory.Dependencies dependencies;

    public MyLifecycle(MyExtensionFactory.Dependencies dependencies) {
        this.dependencies = dependencies;
    }

    @Override
    public void start() throws Throwable {
        dependencies.db();
    }

    @Override
    public void stop() throws Throwable {
       
    }
}

**Comment by chrisvest** [comment]
Call the `Dependencies.db()` method inside your `MyExtensionFactory.newInstance()` method.

Also, kernel extensions are not meant to be public API. If you can find a way to not use kernel extensions, then that would be for the better.
