### ISSUE TITLE
How i can extract week number from date using cypher

### ISSUE THREAD

**Issue by rishu5391** [neo4j/neo4j#11812]
I want to extract week number from date something like this

RETURN apoc.date.fields('2015-01-02 03:04:05 EET', 'yyyy-MM-dd HH:mm:ss zzz').weekdays

**Comment by eebus** [comment]
Hello @daflidafli 
It seems like you have a problem with APOC, could you please reopen your issue in https://github.com/neo4j-contrib/neo4j-apoc-procedures/ ?
