### ISSUE TITLE
neo4j backup app in Embedded Mode ran into Out Of Memory

### ISSUE THREAD

**Issue by socialsampath** [neo4j/neo4j#1181]
Hi,

I am trying to create a simple neo4j backup app with below steps

1) Create Online Backup complete/incremental
2) Execeute few cypher queries on new backedup data
3) Bring Neo4j up in embedded mode with Backed up DB
4) Bring WrappingNeoServerBootstrapper up
5) Perform some read operations through Web Admin
6) Shutdown WrappingNeoServerBootstrapper using WrappingNeoServerBootstrapper.shutdown();
7) Shutdown EmbeddedGraphDatabase using EmbeddedGraphDatabase.shutdown();
8) Repeat steps 1 - 7 after regular intervals

After couple of successful backups, shutdowns/startups it ran into OutOfMemory. The heapdump suggested below leak suspect -

The class "java.lang.ApplicationShutdownHooks", loaded by "<system class loader>", occupies 54,33,81,152 (73.14%) bytes. The memory is accumulated in one instance of "java.lang.Object[]" loaded by "<system class loader>".

Keywords
java.lang.Object[]
java.lang.ApplicationShutdownHooks

The Accumulated objects refer to many threads as below:

org.neo4j.server.Bootstrapper$1 @ 0x886d24b8 Thread-122
org.neo4j.server.Bootstrapper$1 @ 0x8e2b61b0 Thread-260
org.neo4j.server.Bootstrapper$1 @ 0x8ea612c8 Thread-272
org.neo4j.server.Bootstrapper$1 @ 0x89dc36a8 Thread-158
org.neo4j.server.Bootstrapper$1 @ 0x8b4bd4c0 Thread-196
.....

Kindly suggest if I am missing something while shutting down Wrapper/GraphDB. Thanks.

**Comment by jakewins** [comment]
WrappingNeoBootstrapper is deprecated and was not meant for production use - and notably should not be needed to perform backups. Please refer to the Neo4j manual for performing backups: http://neo4j.com/docs/stable/operations-backup.html
