### ISSUE TITLE
Bolt around large string values

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4j/neo4j#11819]
This might be my bug or your bug.  I'm not completely sure yet ;)

- Neo4j version: 3.3.4
- Operating system: Mac OS 10.12.6 (Neo4j running inside of Docker)
- API/Driver: Ruby (alpha version in `master` that I am developing)

## Example bug report

I have tests that cover the different adaptors in the `neo4j-core` gem (Bolt/HTTP/embedded) to make sure that they all support querying the same way.  [One set of tests](https://github.com/neo4jrb/neo4j-core/blob/master/spec/neo4j/core/shared_examples/adaptor.rb#L237) is there to see that if I pass in a value as a parameter to Neo4j that I'll get the same value back out.  My hope is that this would be a sanity check for packing and unpacking of parameters.  Everything is mostly fine, though [this test](https://github.com/neo4jrb/neo4j-core/blob/master/spec/neo4j/core/shared_examples/adaptor.rb#L254) is failing only on SSL.  The value that that test is testing in a string with "bar" 10,000 times and it's giving me a timeout.  I changed the size of the string until I found a point at which is seemed to break and it seems to be 5,443 "bar"s or 16,326 characters.  With a little further testing I found that it also times out if I repeat one character 16,327 times.  I'm not sure why 16,327 has a problem, but I note that 2^14 is 16,384, so maybe with the size of the query string and the bytes specifying the parameter it's hitting some limit limit...  Does that seem like something you've encountered?  Here are the two byte streams with a lot of the middle cut out:

### Steps to reproduce

I'm not sure if this is reproducible in other drivers or not, but that would probably give a clue.  To try to reproduce this, one can run the Cypher query `WITH {param} AS param RETURN param` and pass in the `param` parameter with a string of `"bar"` repeated 10,000 times.

### Expected behavior
No timeout

### Actual behavior
Timeout

**Comment by cheerfulstoic** [comment]
I just tried this query in Python and it seemed to work fine even with 100,000 `"bar"`s, so I'd currently suspect that this is something with the Ruby bolt implementation.  So my main question would be if this seems like anything familiar.

**Comment by lutovich** [comment]
Hi @cheerfulstoic,

We have not seen such issues before. I tried long strings in Java and JavaScript drivers via cypher-shell and neo4j-browser respectively and everything seems to work fine.

**Comment by cheerfulstoic** [comment]
Yeah, I figured that might be the case.  Thanks Konstantin.  I'll close this issue, but if I get anymore information I might ask here `¯\_(ツ)_/¯`
