### ISSUE TITLE
CachingInputIterable does not cache relationships

### ISSUE THREAD

**Issue by feldoh** [neo4j/neo4j#11835]
I discovered that in the CachingInputIterable class it only caches nodes and always returns a node iterator despite appearing more generic. CachedInput generates a CachingInputIterable for both nodes and relationships but on Relationships it still only has the nodes cached (i.e. nothing) and returns a node iterable. This means in the InputIterable any vistor.endOfEntity calls result in NullPointerException.

Neo4j Version: 3.4.0
API: Batch Importer

Potential Fixes:
* Deprecate CachingInputIterable and replace with two subclasses with CachedInput constructing the appropriate type.
* Add EntityType to the constructor and a switch to cache the relevant type.
* We could make the InputCache agnostic given that it returns the same type.

/cc @sarmbruster

**Comment by tinwelint** [comment]
https://github.com/neo4j/neo4j/blob/3.5/community/kernel/src/test/java/org/neo4j/unsafe/impl/batchimport/input/InputCacheTest.java is green and it tests caching and retrieving both nodes and relationships. Do you have a test case showing the issue?

**Comment by feldoh** [comment]
I'll make one. The issue is in https://github.com/neo4j/neo4j/blob/25bd3fa979ebd45938a422b55bf927bfdd849cf0/community/kernel/src/main/java/org/neo4j/unsafe/impl/batchimport/input/CachingInputIterable.java#L61 not the input cache itself. So you pass CachingInputIterable an input cache which contains relationships. But the iterator always caches nodes never relationships.

**Comment by tinwelint** [comment]
Thanks for noticing! It turns out that after recent changes to the importer the input caching isn't actually used anymore. I'll fix this anyway and leave it in because it may be used in the wild somehow, but I'll make ImportLogic not use it anymore.

**Comment by feldoh** [comment]
Ah great 👍 Glad I could be of service. I'll have to check out the new code to see if I can switch my usage as well.

**Comment by tinwelint** [comment]
Hmm, I ended up removing the InputCache and all that entirely since nothing is using it anymore. Are you using this thing manually some way?

**Comment by feldoh** [comment]
I can't remember how I worked around it. I don't have access to the code from here so I'll have to check tomorrow. But even if I am I can easily change the code the project is still pre-prod.
