### ISSUE TITLE
percentileDisc(null, 0.5) BUG

### ISSUE THREAD

**Issue by Antti-Kaikkonen** [neo4j/neo4j#11845]
# Bug with percentileDisc(null, 0.5);

- Neo4j version: 3.3.5 community edition
- Operating system: Ubuntu 16.04
- API/Driver: Cypher via Neo4j browser

### Steps to reproduce
1. Open Neo4j browser
2. Run this cypher query: "RETURN percentileDisc(null, 0.5);"

### Expected behavior
returns null; (Even the [documentation](https://neo4j.com/docs/developer-manual/current/cypher/functions/aggregating/#functions-percentiledisc) says it should return null)

### Actual behavior
query hangs (loading indicator stays forever in the Neo4j browser).

**Comment by SaschaPeukert** [comment]
Hej!
Thanks for reporting. The good news is that this problem has already been reported in https://github.com/neo4j/neo4j/issues/11663 and was fixed a few days ago. Expect the fix in the next release of 3.3 and 3.4
