### ISSUE TITLE
Neo4j manual/explicit indexes and non-string range queries

### ISSUE THREAD

**Issue by Artgit** [neo4j/neo4j#11870]
I was able to port my Neo4j 3.4.0 application to use manual indexes and APOC procedures instead of queries over the indexles relationship properties. Everything is working like a charm except one last thing - I ran into the issue with non-string Lucene range queries. 

They are not working as expected, for example:

I'm applying the following Lucene query predicate in order to get all inclusive numbers in `2 to 6` range:

    value:[2 TO 6]

and receive the documents with the following values:

    567986400000
    567986400000
    567986400000
    536450400000
    536450400000
    599608800000
    536450400000
    567986400000

that is obviously not the something that was expected.

Is there anything in Neo4j/APOC that I can do in order to get it working properly?

**Comment by SaschaPeukert** [comment]
Can you provide some steps to reproduce this issue? What has to be in the graph and what Neo4j surface do you use for your query?

**Comment by Artgit** [comment]
I use Neo4j 3.4.0, apoc-3.4.0.1-all.jar 

I have created the following triggers which add all of the relationship properties into the manual index:

```
CALL apoc.trigger.add('HAS_VALUE_ON_CREATED_RELATIONSHIPS_TRIGGER', 
"UNWIND {createdRelationships} AS r WITH r 
WHERE type(r) = 'HAS_VALUE_ON' 
CALL apoc.index.addRelationship(r, keys(r)) RETURN true", 
{phase:'before'})

CALL apoc.trigger.add('HAS_VALUE_ON_ASSIGNED_RELATIONSHIP_PROPERTIES_TRIGGER', 
"UNWIND keys({assignedRelationshipProperties}) AS key 
UNWIND {assignedRelationshipProperties}[key] AS map WITH map 
WHERE type(map.relationship) = 'HAS_VALUE_ON' 
CALL apoc.index.addRelationship(map.relationship, keys(map.relationship)) RETURN true", 
{phase:'before'})
```

One of my relationship property contains Long timestamp values but looks like by default Neo4j Lucene index treats them as Strings and this is why when I call the query with the following Lucene predicate on this index: `value:[2 TO 6]`,  let's say:

`CALL apoc.index.between(decision,'HAS_VALUE_ON',characteristic,'value:[2 TO 6]') YIELD rel`

I receive the following response:

```
567986400000
567986400000
567986400000
536450400000
536450400000
599608800000
536450400000
567986400000
```

I have created the corresponding SO question regarding the Lucene behavior there https://stackoverflow.com/questions/50540788/lucene-query-language-and-numeric-range and received the answer:

> To achieve a proper range query you need to use specific defined fields from lucene. See [Field javadoc][1]
> 
>  - IntPoint: int indexed for exact/range queries. 
>  - LongPoint: long indexed for exact/range queries. 
>  - FloatPoint: float indexed for exact/range queries. 
>  - DoublePoint: double indexed for exact/range queries.
> 
> So you need to be sure that your field you add this query is one of this types. As you said you use a Neo4j generated lucene index. There has to be an option to create this kind of fields otherwise you're not able to execute proper range queries.

Does Neo4j have the options to control the Lucene field types and if no, could you please create it?

  [1]: https://lucene.apache.org/core/7_0_1/core/org/apache/lucene/document/Field.html

**Comment by Hunterness** [comment]
Hi, as to my knowledge there is no way to influence the Lucene types in current Neo4j. We will keep your suggestion in mind for further development.

**Comment by craigtaverner** [comment]
Explicit indexes have been deprecated for a long time (replaced by Schema indexes in neo4j 2.0). However they are still possible to access using APOC (as you tried here). They will no exist at all (not even via APOC, I believe) in 4.x releases. I strongly recommend you move to schema indexes.

However, if you really need to use explicit indexes, I did find some documentation relating to the configuration of the underlying Lucene index which might be possible with the APOC procedures. See https://neo4j.com/docs/java-reference/current/indexing/#indexing-create-advanced

Another option is to ask the APOC developers, but submitting an issue at https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues
