### ISSUE TITLE
MATCHing on negative integer throws error in 3.3

### ISSUE THREAD

**Issue by tomzeppenfeldt** [neo4j/neo4j#11904]
**Neo4j Version:** 3.3.5.  
**Operating System:** Ubuntu 15.10  
**UI  :7474/browser

### Steps to reproduce

MATCH (n)
where id(n) = -1
RETURN n
### Expected behavior
(no changes, no records)
### Actual behavior

Neo.DatabaseError.General.UnknownError: Access to record Node[-1,used=false,rel=-1,prop=-1,labels=Inline(0x0:[]),light,secondaryUnitId=-1] went out of bounds of the page. The record size is 15 bytes, and the access was at offset -15 bytes into page 0, and the pages have a capacity of 8190 bytes. The mapped store file in question is /home/pdm/neo4j/data-neo4j-community-3.3.5/data/databases/graph.db/neostore.nodestore.db

### Workaround
Insert 'CYPHER 3.2'
 
CYPHER 3.2 
MATCH (n)
WHERE id(n) = -1
RETURN n

**Comment by SaschaPeukert** [comment]
@ophileon Thanks for reporting this. We will take a look at this

Best regards,
Sascha, Neo4j Cypher Team

**Comment by fickludd** [comment]
@ophileon This has been [fixed](https://github.com/neo4j/neo4j/commit/aed54d20c5f8f7a61ed0223424b17ba2887a803d#diff-d53d8bcd7957017281b2bc752328340c) in `3.3.6`. Patch and you should be fine 👍
