### ISSUE TITLE
Sort on non existing value

### ISSUE THREAD

**Issue by tim-hanssen** [neo4j/neo4j#11901]
Neo4j version: 3.4.0
Operating system: Unbuntu 16.4 LTS

In 3.4 the sorting is returning an error if you try to sort on a non existing value:
"Neo.ClientError.Statement.TypeError: Type mismatch: expected a map but was NO_VALUE"

**Steps to reproduce**
RETURN environment ORDER BY environment.environment_group.Name
If we don't set the enviroment_group to be in environment the query crashes:

**Expected behavior**
Without a change in the release notes, it should be resulting in the same result as in 3.3.

**Comment by SaschaPeukert** [comment]
@tim-hanssen Thanks for reporting. We will look into it.

Best regards,
Sascha, Neo4j Cypher Team

**Comment by SaschaPeukert** [comment]
This should be fixed in the next release of 3.4 which is `3.4.2`
