### ISSUE TITLE
Return count(*) not working, I have a graph with almost 2500 nodes and all of them come under the label "Art", there are 1.8 million relationships between these nodes.The edges have a weight called "ed_sc", when running the following query the result is displayed in 7 sec when limit is 10, even for limit 100k it shows that the query is executed in almost 7 sec .But when I try to return the count of the total number of rows, there is no response even after an hour. The query is :  MATCH (a:Articles)-[r1]->(b:Articles)-[r2]->(c:Articles)-[r3]->(d:Articles)WHERE a.url<>c.url and b.url<>d.url and a.url<>d.url RETURN a.url,r1.ed_sc,b.url,r2.ed_sc,c.url,r3.ed_sc,d.url limit 10;

### ISSUE THREAD

**Issue by YashMishra96** [neo4j/neo4j#11927]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests.  If you have questions on how to use Neo4j, please ask on [StackOverflow](http://stackoverflow.com/questions/tagged/neo4j) instead of creating an issue here.

If you want to make a feature request then there is no guideline, so feel free to stop reading and open an issue. If you have a bug report however, please continue reading.
To help us understand your issue, please specify important details, primarily:

- Neo4j version: X.Y.Z
- Operating system: (for example Windows 95/Ubuntu 16.04)
- API/Driver: (for example Cypher/Java API/Python driver vX.Y.Z)
- **Steps to reproduce**
- Expected behavior
- Actual behavior

Additionally, include (as appropriate) log-files, stacktraces, and other debug output.

## Example bug report

I discovered that when I mount `data/` to a volume on my host, and then stop the container, the `write.lock` is not removed as well as a number of other files not being cleaned up properly.

**Neo4j Version:** 3.0M03  
**Operating System:** Ubuntu 15.10  
**API:** Docker

### Steps to reproduce
1. Pull the image: `docker pull neo4j/neo4j:3.0.0-M03`
2. Create a directory on the host that will be a mount for the data: `mkdir /home/neo4j-data`
3. Start a new container that mounts to this directory: `docker run -d --name neo4j-test -p 7474:7474 -v /home/neo4j:/data neo4j/neo4j:3.0.0-M03`
4. Navigate to the `write.lock` file located in the directory: `/data/databases/graph.db/schema/label/lucene/labelStore/1/`
5. Stop the container: `docker stop neo4j-test`

### Expected behavior
`write.lock` should be removed now.

### Actual behavior
`write.lock` is still present and preventing access by other programs.

**Comment by InverseFalcon** [comment]
Change your title...please. Short and concise. Put all this in your bug report description (looks like you're still using the default placeholder)

**Comment by SaschaPeukert** [comment]
Hej @YashMishra96,

Since there hasn't been an update for a while now, I am gonna close this and ask you to open another issue if you still have a problem. Please keep the comment from @InverseFalcon in mind when doing so.

Cheers,
Sascha

Neo4j Cypher Team
