### ISSUE TITLE
Neo4j Browser 3.1.7 doesn't work with bolt on port 80

### ISSUE THREAD

**Issue by TobiasLeo** [neo4j/neo4j#11935]
It is not possible to connect to the Neo4j database through the web gui with bolt on port 80 with version 3.1.7 of the browser.
If Neo4j is configured to bind bolt to port 80 the web gui replaces port 80 with 7687 when connecting.
The problem only seems to be with the web gui, as older versions of the web gui (3.1.4 tested) are still able to connect to the newer server with bolt on port 80 without any problems.

**Neo4j Version:** 3.3.5, 3.4.0 - both ship with browser version 3.1.7. Versions of the browser up to and including 3.1.4 seem to be UNAFFECTED by this problem.
**Operating System:** Windows 7/10 (tested client and server side), RHEL/OpenShift (tested server side)

### Steps to reproduce
1. Use Windows zip distribution of Neo4j server community 3.3.5 OR 3.4.0. (It is likely any distribution of these versions may be appropriate here, as long as they all still ship with browser version 3.1.7.)
3. In conf/neo4j.conf configure it to run bolt on port 80 `dbms.connector.bolt.listen_address=:80`
4. Start the Neo4j server
5. This has been tested in Chrome: Open the web gui, check the developer console. Errors should be appearing about failed WebSocket connections. According to the errors it tries to connect on port 7687 instead of the configured port 80. It also fails in Internet Explorer 11 and Microsoft Edge, but they provide less information in their errors.

### Expected behavior
The Neo4j browser connects to the server automatically when the browser gui is opened.
I should also be able to user `:server connect` and successfully connect in a manual fashion.

### Actual behavior
The server fails to connect because it changes port 80 to 7687 (bolt default port). Errors are printed to the JavaScript console. When connecting to for example bolt://localhost:80 it changes to bolt://localhost:7687. Any other port seems to work as it should.
This stands true for when the web client tries to connect automatically and when connecting manually using `:server connect`.

**Connecting: (authentication disabled in this instance)**
![neo4j-connect](https://user-images.githubusercontent.com/1366922/41230062-a8b48934-6d7e-11e8-8fc7-766868ce0cfb.png)

**Errors in Google Chrome after attempting to connect. The multiple errors are because of both serveral automatic attempts and a manual attempt. Notice that the port has changed:**
![neo4j-error](https://user-images.githubusercontent.com/1366922/41230069-ad920fa8-6d7e-11e8-9d11-fe9f510379be.png)

**Comment by oskarhane** [comment]
This was actually a driver issue that should have been resolved with https://github.com/neo4j/neo4j-javascript-driver/pull/364 and work in later releases of the driver (and therefore in neo4j-browser).
If it still persists, feel free to open a new issue in the [neo4j-browser repo](https://github.com/neo4j/neo4j-browser
