### ISSUE TITLE
Feature request  :  pattern comprehension with multiple patterns

### ISSUE THREAD

**Issue by tomzeppenfeldt** [neo4j/neo4j#11931]
Pattern comprehension now supports 

```
RETURN [(a)-->(b)-->(c) WHERE b:Movie | [b.year,c.prop1] ] AS myColl
```
but is does not support 

```
RETURN [(a)-->(b)-->(c),(b)-->(d) WHERE b:Movie | [b.year,c.prop1,d.prop2] ] AS myColl
```

**Comment by Hunterness** [comment]
Good idea, thanks for the input. We will consider it for future development.

**Comment by fickludd** [comment]
Hi @ophileon,

Richer pattern comprehensions would indeed be pleasant, but this functionality will be added as part of true subqueries, which is in the works at a language level. Feel free to help out with comments and feedback on the relevant Cypher improvement proposal: https://github.com/opencypher/openCypher/pull/217.

We are closing this issue as it essentially duplicates that effort.
