### ISSUE TITLE
3.4.0 Multiple MATCH clauses with reference to previous MATCH variable

### ISSUE THREAD

**Issue by LouisSayers** [neo4j/neo4j#11932]
- Neo4j version: 3.4.0
- Operating system:  MacOS High Sierra
- API/Driver: Cypher
- **Steps to reproduce**
## setup
```
CREATE (actor1:Person{name: "An Actordirector"})
CREATE (movie:Movie{title: "A Movie"})
CREATE (actor1)-[:ACTED_IN]->(movie)
CREATE (actor1)-[:DIRECTED]->(movie)
CREATE (actor2:Person{name: "Just Actor"})
CREATE (actor2)-[:ACTED_IN]->(movie)
```

## action
```
MATCH (movie:Movie)
MATCH (director:Person)-[:DIRECTED]->(movie)
MATCH (director)-[:ACTED_IN]->(movie)
RETURN movie.title, director.name
```

- Expected behavior
Returns only directors that have acted in a movie
actor1.name, movie.title

- Actual behavior
Returns any actor that has ACTED_IN relationship to a movie but not DIRECTED relationship
actor1.name, movie.title
actor1.name, movie.title
actor2.name, movie.title

**Comment by InverseFalcon** [comment]
You may want to delete your graph and repopulate it and try again. Using your graph creation query and subsequent actor/director query, I could not reproduce your results.

**Comment by LouisSayers** [comment]
hmm... I did an update of Neo4j Browser, and retried this and it seems to be working correctly now.

I had a couple students that had the issue above which is why I started looking into it, but likewise unable to replicate atm.

Thanks for looking into it. I'll close this issue.
