### ISSUE TITLE
Can't find the .zip of Neo4j version 3.1.3 for windows

### ISSUE THREAD

**Issue by sofiane01234** [neo4j/neo4j#11933]
I need the server version of Neo4j database to use but I can't find neither .exe nor .zip to install it. 
I've looked for it in the official [website ](https://neo4j.com/download/other-releases/#releases) but i couldn't find it and in the gitub repo but I only found the source code. 
Any one can help please !

**Comment by craigtaverner** [comment]
3.1.3 is no longer a supported release. The website you linked above does have a 3.2.13 release for windows, and a link for the .zip file (see the link titled `Neo4j 3.2.13 (zip)`. If you specifically need 3.1.3, you could try the link https://neo4j.com/artifact.php?name=neo4j-community-3.1.3-windows.zip
