### ISSUE TITLE
apoc.periodic.iterate fails when updating from a map

### ISSUE THREAD

**Issue by gregcarlin** [neo4j/neo4j#11940]
I'm using `apoc.periodic.iterate` to update a large number of nodes at once. Specifically, each node has a property called "details" that contains a json object serialized as a string. I want to update each node so the key-value pairs in the json object become properties of the node. Specifically, I am wondering why the following query fails:

    CALL apoc.periodic.iterate('MATCH (n) RETURN n', 'SET n += apoc.convert.fromJsonMap(n.details)');

(specifically, each batch fails with a NullPointerException) but this query succeeds:

    CALL apoc.periodic.iterate('MATCH (n) RETURN ID(n) AS i', 'MATCH (n) WHERE ID(n) = i SET n += apoc.convert.fromJsonMap(n.details)');

Is this expected behavior? I can't find any documentation indicating why the original query wouldn't work, and similar queries, such as this one, are fine:

    CALL apoc.periodic.iterate('MATCH (n) RETURN n', 'SET n.test += apoc.convert.fromJsonMap(n.details).field');

I built the server from a recent source (ie. I'm running 3.5-SNAPSHOT) and am using the neo4j shell bundled in the build.

**Comment by ryguyrg** [comment]
@gregcarlin suggest moving the issue over to the APOC issue tracker.  APOC is not part of the core Neo4j product and thus isn't covered by this repository. https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues.  of course, if you're not sure it's an issue, you an also post on stackoverflow.

**Comment by gregcarlin** [comment]
Sounds good! Moved to https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/846
