### ISSUE TITLE
"NOT path" clause doesn't work with pattern comprehension.

### ISSUE THREAD

**Issue by kizhaev** [neo4j/neo4j#11941]
It seems like the 'NOT' keyword doesn't work in pattern comprehension context.

**Neo4j Version:** 3.3-3.4 
**Operating System:** Ubuntu 16.04
**API:** ANY

### Steps to reproduce
1. Run the following query:

```
CREATE (bonus:Bonus)-[:FOR]->(movie:Movie)-[:BY]->(director:Director), 
       (user:User)-[:REVIEWED]->(movie1:Movie)-[:BY]->(director)
WITH user, movie, director
RETURN 
    [(bonus:Bonus)-[:FOR]->(movie) 
        WHERE NOT (user)-[:REVIEWED]->(:Movie)-[:BY]->(director) | id(bonus)] AS bonus, 
    [(bonus:Bonus)-[:FOR]->(movie) 
        WHERE size([(user)-[r:REVIEWED]->(:Movie)-[:BY]->(director) | r]) = 0 | id(bonus)] AS bonus1
```

The point of the query is to fetch bonus for a movie by a director that user has not reviewed yet.
I would expect here `bonus` and `bonus1` to be equal.

### Expected behavior
bonus == bonus1 == []

### Actual behavior
bonus == [1234], bonus1== []

**Comment by SaschaPeukert** [comment]
@kizhaev Thanks for reporting. We will look into it

**Comment by fickludd** [comment]
@kizhaev This is fixed by https://github.com/neo4j/neo4j/commit/54cec41387c024c5da3c9e68cd1b22420112d0f4, which will be a part of `3.3.7`

**Comment by kizhaev** [comment]
Great! Thank you!
