### ISSUE TITLE
How to set up a developer environment to contribute to neo4j

### ISSUE THREAD

**Issue by fferegrino** [neo4j/neo4j#11948]
Hello, I'm looking forward to contributing to the development of neo4j, however, I'm struggling to set up a working environment to work with the code base (specially having both Scala and Java in the same project). It would be great if you can share the details of the environment that you recommend to work with the neo4j codebase.

With the "environment", I'm talking about the IDE/Editor/Debugging tool that you recommend. I'm currently using only the remote debugger which is not an ideal situation. Ideally, I'd like to debug using the tools provided by an IDE.

I hope this is the right place to ask such questions.

**Comment by chrisvest** [comment]
Intellij IDEA Community Edition with the Scala and Maven plugins work nicely. No special setup required. You just open the top-level directory as a project.

**Comment by fferegrino** [comment]
Thanks for replying.

That's what I've been doing, however, everything goes bad for me when it comes to actually run the project, can you tell me which configuration are you using?

<img width="209" alt="screen shot 2018-06-20 at 15 28 33" src="https://user-images.githubusercontent.com/1820946/41664912-a9ee8170-749e-11e8-8e7c-f714722a9d2b.png">

Sorry if this is a novice question but I've never worked with both languages in the same project.

**Comment by chrisvest** [comment]
There is no such thing as "running (the whole) project". You pick tests to run, usually.

**Comment by fferegrino** [comment]
Oh, ok. 

I'll try that. Thanks!
I'll close this issue now, however, I'd appreciate if you can help me if something comes up.

Thanks again.
