### ISSUE TITLE
Trigger is empty/null after upgrade to 3.4.0 

### ISSUE THREAD

**Issue by razbar** [neo4j/neo4j#11947]
- Neo4j version: 3.4.0
- Operating system: AWS Linux

- **Steps to reproduce**
- Expected behaviour: Upgrade DB version from 3.2.9 -> 3.4.0 triggers should work as it was
- Actual behaviour: After the upgrade the trigger query is null

**Comment by NivTikolski** [comment]
It happened to me too, all my triggers queries are null after the upgrading to 3.4.0.

**Comment by chrisvest** [comment]
This sounds like an APOC issue. That's the library that gives you triggers, isn't it? Make sure you've upgraded APOC to a version that matches your Neo4j version, and then report the problem on the APOC repository is the problem continues.

**Comment by razbar** [comment]
I've opened the issue on the APOC repository.

**Comment by jexp** [comment]
@chrisvest there might be an issue with updating graph properties though. This is the 2nd mention of it.
