### ISSUE TITLE
Debian package for 3.4.1 does not create /var/run/neo4j

### ISSUE THREAD

**Issue by rito-mg** [neo4j/neo4j#11954]
## Bug report

The `/var/run/neo4j` directory is not created by the installer. If you run `systemctl start neo4j`, no pid file is created.

**Neo4j Version:** 3.4.1
**Operating System:** Ubuntu 16.04

#### Prepare to install
```
root# u1=root; u2=neo4j; printf "%s\tsoft\tnofile\t60000\n%s\thard\tnofile\t60000\n%s\tsoft\tnofile\t60000\n%s\thard\tnofile\t60000\n" "$u1" "$u1" "$u2" "$u2" >> /etc/security/limits.conf
root# shutdown -r now
```
#### Log back in and verify ulimit for number of files has increased to 60000.
```
root# ulimit -n
```

#### Install the neo4j repository.
```
root# wget -O - https://debian.neo4j.org/neotechnology.gpg.key | apt-key add -
```
#### Make sure local hostname resolves before proceeding.
```
root# echo 'deb https://debian.neo4j.org/repo stable/' | tee -a /etc/apt/sources.list.d/neo4j.list
root# apt-get update && apt-get install -y neo4j=1:3.4.1
```

### Expected behavior
```
root# mkdir -m 750 /var/run/neo4j
root# chown neo4j:neo4j /var/run/neo4j
```

### Actual behavior
`/var/run/neo4j` is not created.

**Comment by jennyowen** [comment]
Thanks for reporting this!
The fix will be released in versions 3.3.8, 3.4.10 and the 3.5 release candidate.
