### ISSUE TITLE
Accessing components of Duration (Temporal value) provides conflicting results

### ISSUE THREAD

**Issue by Manish-Giri** [neo4j/neo4j#11959]
- Neo4j version: 3.4.1
- Operating system: Windows 10, Mac OS High Sierra
- API/Driver: (for example Cypher/Java API/Python driver vX.Y.Z) Cypher
- **Steps to reproduce** - execute queries shown below

I have an entity with a property whose value is duration in days (ex: 36). I'm trying to get the value of this duration in milliseconds, so I can add this to another entity's property value (in epoch milliseconds) to create an interval (like start date and end date).

Based on the [documentation on Duration](https://neo4j.com/docs/developer-manual/current/cypher/syntax/temporal/#cypher-temporal-durations), If you execute the following query - 
```
WITH duration('P1D') AS theDuration
RETURN theDuration.milliseconds
```
When you access this duration's components, like `theDuration.hours` or `theDuration.minutes`, you would expect these values to show the value of the final Duration in the corresponding units. So, for `duration('P1D')  AS theDuration`,  you would expect `theDuration.hours` to return `24`. But instead it returns 0.

In fact, with the duration as `duration('P1D')`, all components like `hours`, `minutes`, `milliseconds` etc somehow return 0.
 
However, if you create a duration like so - `duration('P5M1.5D')` (example from docs), accessing it's components gives the right value - 

```
WITH duration('P5M1.5D') AS theDuration
RETURN theDuration.minutes
```
This returns `720`.

Either I missed something in the docs, or something's not working right.

**Comment by sherfert** [comment]
@Manish-Giri In Table 3.42 of the documentation you linked the component group of each accessor is listed. `.days` belongs to the component group `Days` and `.milliseconds` belongs to the component group `Seconds`. These component groups are distinct and not automatically converted. This is admittedly quite confusing. In the example of `duration('P5M1.5D')` the `0.5 days` result in 720 minutes (part of the `Seconds` component group).

To solve your particular issue, you need to create the duration that you save as a property with `duration.inSeconds(a, b)` (See https://neo4j.com/docs/developer-manual/current/cypher/functions/temporal/#functions-duration-computing ). That will save the time difference using only the `Seconds` component group.

Alternatively, you need a `DateTime` or `ZonedDateTime` to base your duration on (let's call that `$base`). Without that, there is no way knowing how many milliseconds a certain number of days are - daylight saving could fall into the range and that would result in 1 hour more or less than expected. You would then write 

```
WITH duration('P36D') AS theDuration
RETURN duration.inSeconds($base, $base + theDuration).milliseconds
```

I hope this helps.
