### ISSUE TITLE
Neo4j graph visualization in Gephi error: Node without property name "name"  throwing an exception

### ISSUE THREAD

**Issue by SOUMAJYOTI** [neo4j/neo4j#11950]
The issue is with using the APOC procedure for streaming data from Neo4j to Gephi for visualization. On using the **apoc.gephi.add()** procedure, if the nodes in the Neo4j graph database do not contain the property "name" (exactly this string), then it raises the cypher error :

> Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `apoc.gephi.add`: Caused by: org.neo4j.graphdb.NotFoundException: NODE[0] has no property with propertyKey="name".

Even if the node contains properties with the substring 'name' (example, "propertyname"), it throws the same error. On checking the code in [https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/3.2/src/main/java/apoc/gephi/Gephi.java](https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/3.2/src/main/java/apoc/gephi/Gephi.java), it looks like the last block of code in the method **caption(Node n)** should take care of it (the absence of a node property with string "name"). However, for some reason, it is not able to detect the substring "name" in the property names. Can someone fix this issue?

**Neo4j Version:** 3.2.12
**Operating System:** Windows 10
**APOC Version:**  3.2.03
**Gephi Version.** 0.9

### Steps to reproduce
1. Create a simple graph database with a few nodes and relationships and without any node property names containing the string "name".
2. Start the Gephi streaming server. (before that, download and add the gephi plugin in the neo4j folder)
3. Type the following query in the Neo4j Cypher window:

match path = (n1)-[r]->(n2)
WITH path LIMIT 1000
with collect(path) as paths
call apoc.gephi.add(null,'workspace1', paths) yield nodes, relationships 
return nodes, relationships

4. The "workspace1" in the above procedure input can be changed to the workspace being used in Gephi, however if you generally open one workspace in Gephi 0.9, it is by default workspace1.

### Expected behavior
Graph display in the Gephi window.

### Actual behavior
The error message displayed above.

**Comment by chrisvest** [comment]
It doesn't look like your APOC version fully matches your Neo4j version. You can try upgrading it. Otherwise this sounds like a problem that should be reported to APOC first.

**Comment by SOUMAJYOTI** [comment]
The APOC version was not the error - it was a bug in the APOC version 3.2.03 which was fixed in 3.2.04 - so updating the APOC plugin to 3.2.04 fixed the error. 
Reference the commit log: [link](https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/8b25b05fa461ae0177db1b0604f628b73f12e08d#diff-d27b3f05da2e50dbcd2c95ca367b0e65)
