### ISSUE TITLE
Unable to access Neo4j database installed behind Nginx in AWS Cloud

### ISSUE THREAD

**Issue by abhi2495** [neo4j/neo4j#11951]
I have been trying to setup neo4j server in public cloud (installed in Amazon AWS EC2, Ubuntu 16 AMI) which I need to access from remote machine. Since I have to access it from a restricted Corporate Network,I decided to set up Nginx as proxy. I followed the Neo4j Doc and bunch of stackoverflow questions.With these I could hit the Neo4j server ,but couldnt connect to it's DB. Here is the Browser Snapshot. Can someone help me out if I am missing something here? What should I do to access the DB?

Network Connector Configuration of Neo4j:

`
dbms.connectors.default_listen_address=0.0.0.0
dbms.connectors.default_advertised_address=ec2-xx-xx-xx-xx.compute-1.amazonaws.com

dbms.connector.bolt.enabled=true
dbms.connector.bolt.listen_address=:17687
dbms.connector.bolt.advertised_address=:7687

dbms.connector.http.enabled=true
dbms.connector.http.listen_address=:17474

dbms.connector.https.enabled=true

`

**Neo4j Version:** 3.4.1
**Operating System:** Ubuntu 16.04
**API:** Java Driver

### Steps to reproduce
1. Install Neo4j: sudo apt-get install neo4j=1:3.4.0 in EC2
2. Make necessary changes in /etc/neo4j/neo4j.conf as mentioned above and restart neo4j
3. Install Nginx: sudo apt-get install nginx in EC2
4. Map both communication channels: HTTP and bolt in Nginx Config and restart Nginx
4a. For the HTTP part, I added the following inside the server section of /etc/nginx/sites-available/default this snippet: 
      location /neo4j/ {
                proxy_pass http://localhost:17474/; 
      }
4b. For the bolt protocol, I amended to /etc/nginx/nginx.conf this snippet:
      stream {
                   server {
                               listen 7687;
                               proxy_pass localhost:17687; 
                             }
                   }
5. Navigate to - http://ec2-xx-xx-xx-xx.compute-1.amazonaws.com/neo4j  OR Call the Java Driver to connect to the DataBase

### Expected behavior
Should be able to communicate with DB and ask for username, password only (in Browser), and should be able to connect to Db through Java Driver

### Actual behavior
In Browser, Showing "Database access not available. Please use :server connect  to establish connection. There's a graph waiting for you." Asking for Host.
In Java Console, showing "unable to connect to ...,, ensure the database is running and that there is a working network connection to it."

**Comment by zhenlineo** [comment]
Hi @abhi2495,

This is not a bug report or feature request but a discussion for how to setup HTTP/bolt server with Nginx. Please refer to https://community.neo4j.com/ for questions like this. 

Before you raise a question in community, check if you have encryption handled. Your Nginx config cannot handle any encrypted data which bolt client is have encryption on by default.

Cheers,
Zhen
