### ISSUE TITLE
import large csv file problems

### ISSUE THREAD

**Issue by dysuwen** [neo4j/neo4j#11952]
v3.4.1 enterprise
I am testing the database performance, generated 17 CSV files, total size 2.7T, contains 7 billion nodes, 8 billion relationships, 12 billion propertys, my server memory is 512G, configuration neo4j-admin heap_size for 32G(too low report illegel seek ). in the import process, system not enough memory, /var/log/messages report

Jun 23 17:59:38 hostname Kernel:XFS:java (76613) Possible memory allocation size deadlock in 4194320 (Kmem_relloc)

The kill Java process becomes zombie state. I tried every 5 minutes to go to run echo 3 >/proc/sys/vm/drop_cache free memory, the effect is not obvious, do not know how to solve the problem ?

**Comment by jexp** [comment]
Can you add your exact command line invocation 

And all output from the tool

**Comment by dysuwen** [comment]
my english not good, a part using google translation.

neo4j.conf main parameters:
dbms.memory.heap.initial_size=16g
dbms.memory.heap.max_size=16g
dbms.memory.pagecache.size=256g
dbms.record_format=high_limit

nodes csv format, average of 400-800 million lines.

id,name,num,desc1,desc2,desc3,date4,int5:int,float6:float,bln7:bollean,bln8:boolean
id0000000001,name0000000001,num0000000001,desc10000000001,desc20000000001,desc30000000001,20180610,2808,5603.97,false,true

import command 
/usr/local/neo4j/bin/neo4j-import --into graph.db --additional-config /usr/local/neo4j/conf/neo4j.conf\
--id-type string \
--nodes:AA AA.csv \
--nodes:BB BB.csv \
--nodes:CC CC.csv \
--nodes:DD DD.csv \
--nodes:EE EE.csv \
--nodes:FF FF.csv \
--nodes:GG GG.csv \
--nodes:HH HH.csv \
--nodes:II II.csv \
--relationships:Decompose AA-BB.csv \
--relationships:Decompose BB-CC.csv \
--relationships:Allocate CC-DD.csv \
--relationships:SatisfyDD DD-EE.csv \
--relationships:Contains FF-EE.csv \
--relationships:RelateTo EE-HH.csv \
--relationships:Relate FF-GG.csv \
--relationships:Contains GG-II.csv

console output：

Import staring 2018-06-23 10:16:54.005+0800
   Estimated  number of nodes: 9.26 G
   Estimated  number of node properties: 116.54 G
   Estimated  number of relationships: 10.10 G
   Estimated  disk space usgae: 6.13 TB
   Estimated required memory usage: 124.30 GB

InteractiveReporterInteractions command list (end with ENTER):
   c: Print more detialed information about current stage
   i：Print more detailed information


(1/4) Node import 2018-06-23 10:16:54.104+0800
   Estimated number of nodes: 9.26 G
   Estimated disk space usage: 3.37 TB
   Estimated required memory usage: 124.30 GB
.......... .......... .......... .......... ..........  5%
.......... .......... .......... .......... ..........  10%
.......... .......... .......... ...

After about 2 hours, the progress did not reponse, system messages report

Jun 23 12:45:50 hostname Kernel:XFS:java (76613) Possible memory allocation size deadlock in 4194320 (Kmem_relloc)
Jun 23 12:46:33 hostname Kernel:XFS:java (76613) Possible memory allocation size deadlock in 4194320 (Kmem_relloc)
Jun 23 12:47:57 hostname Kernel:XFS:java (76613) Possible memory allocation size deadlock in 4194320 (Kmem_relloc)
....
....

**Comment by tinwelint** [comment]
I know I've seen XFS allocation deadlocks myself before. Often caused by heavily fragmented disk. See some more elaborate investigation e.g. https://blog.codecentric.de/en/2017/04/xfs-possible-memory-allocation-deadlock-kmem_alloc/

I'm not sure this is a Neo4j issue

**Comment by tinwelint** [comment]
@dysuwen  I'll close this issue if no response in a week or two
