### ISSUE TITLE
Filtering by relationship types is not working in cycles of length 1

### ISSUE THREAD

**Issue by leorodriguez** [neo4j/neo4j#11956]
I have found an issue when filtering on relationship types over cycles of length 1 (self loops).

**Neo4j version:** 3.4.1 (causal cluster with 2 cores, no read replica)
**Operative system**: Debian 9
**API/Driver:** Cypher
**Steps to reproduce:**
_Create a self loop:_
`merge (x:V)-[:R]->(x)`
_Query for a non existing relationship type_
`match (x:V)-[:NON_EXISTENT]->(x) return x`
**Expected behaviour:**
No records found
**Actual behaviour:**
A node is returned.

**Thank you.**

**Comment by leorodriguez** [comment]
the issue is also present in cycles of length > 1, is anyone else experiencing this?

**Comment by NivTikolski** [comment]
i have a similar issue, i think it caused from the same reason.
i upgrade my database(local, without cluster) from 3.2.9 to 3.4.0/3.4.1

i have: (a:Profile)-[:Test]->(b:Profile)
if i query:
match (a:Profile {id: 1})-[r:Follow]->(b:Profile {id:2})
return type(r)
**the result**: "Test"

more weird situation: if the two profiles add another relation, lets say Test2
so the result of the query will be: "Test", "Test2"

i try to back to the 3.2.9 version, works well. 
after lots of work i have done, it looks like problem with the store migration between 3.2.9 to >3.4 version.

update:
we talked with andrew.bowman.neo at the slack, we add workaround using 
CYPHER runtime=interpreted.
**now the result is fine. but the plan is still not fine. i added images.**
![plan](https://user-images.githubusercontent.com/7282159/42209455-57422abc-7eb7-11e8-9178-a01c3b376e4a.png)
--------------------------
![plan 1](https://user-images.githubusercontent.com/7282159/42209456-5762756a-7eb7-11e8-9b26-f9f4ce66072c.png)
--------------------------
![plan 2](https://user-images.githubusercontent.com/7282159/42209457-577f7e8a-7eb7-11e8-8f80-4de4aa27efb1.png)

i think its getting you close to solve the problem.

help will be appreciated
Niv.

@jexp

**Comment by SaschaPeukert** [comment]
@leorodriguez @NivTikolski Thanks for reporting this problem. I will let you know when it is fixed

Best regards
Sascha, Neo4j Cypher Team

**Comment by SaschaPeukert** [comment]
In the meantime, if you are running on enterprise, I'd advice you to use 
`CYPHER runtime=slotted` as a query prefix to get around this and get better performance than interpreted.

**Comment by NivTikolski** [comment]
@SaschaPeukert  
hi, you have a guess when it will be fixed? 
this issue stops our upgrade to 3.4 in production.

thanks,
Niv.

**Comment by jexp** [comment]
you can just set the default runtime to slotted in your server config for all queries

`unsupported.cypher.runtime=SLOTTED`

**Comment by SaschaPeukert** [comment]
@NivTikolski The fix was merged today. It should be part of the upcoming `3.4.5` release

**Comment by InverseFalcon** [comment]
3.4.5 is out, I believe that should have the fix.

If some can confirm here, we should be able to close this one.

**Comment by NivTikolski** [comment]
@InverseFalcon 
checked, works!
thanks :)
