### ISSUE TITLE
Cypher Bug/Regression 3.3.6 - pattern comprehensions fails when using path matching in WHERE clause

### ISSUE THREAD

**Issue by panthershark** [neo4j/neo4j#11967]
- Neo4j version: 3.3.6, 3.4.1
- Operating system: Mac, Linux for sure. Did not test others
- API/Driver: Cypher

## bug report

Cypher has changed behavior since 3.3.5 and has a bug/regression. WHERE clause in pattern comprehensions are being ignored when attempting to match a path.

### Steps to reproduce

1. Setup an empty instance of neo4j 3.3.6.
2. Add a small graph like this:
`CREATE (a:kid {key:"a"})<-[:HAS_CHILD]-(:big_guy {key:"b"})-[:HAS_CHILD]->(b:kid {key:"c"}), (p:user {key:"d"})-[:KNOWS]->(b)`
3. Query the graph like this
```
MATCH (p:user),(a:big_guy) 
RETURN a,p,[(k:kid)<-[:HAS_CHILD]-(a) WHERE (p)-[:KNOWS]->(k) | k] as kids
```

### Expected behavior
Query in step 3 should only return 1 item in kids.

### Actual behavior
Query in step 3 returns 2 items in kids.

**Comment by SaschaPeukert** [comment]
@tommymessbauer Thanks for reporting this. I am happy to say that the problem has already been fixed ( https://github.com/neo4j/neo4j/issues/11941 ) and should be in the upcomming `3.3.7` and `3.4.4`

**Comment by panthershark** [comment]
![Excellent!](https://media.giphy.com/media/l46CDHTqbmnGZyxKo/giphy.gif)
