### ISSUE TITLE
Neo4j Debian repo SSL certificate has been expired

### ISSUE THREAD

**Issue by amadfida** [neo4j/neo4j#11963]
SSL certificate for https://debian.neo4j.org/repo/stable/Package has been expired and needs to be updated. 
<img width="730" alt="image" src="https://user-images.githubusercontent.com/2160973/42426506-5472047c-82dd-11e8-96a4-4061f87f89d1.png">

**Comment by lucapaganotti** [comment]
Yess, unable to update  :-(

**Comment by chrisvest** [comment]
Thanks for notifying us. The certificate should be renewed now.
