### ISSUE TITLE
Neo4j Desktop: Failure to execute cypher query in Browser comes with Neo4j Desktop

### ISSUE THREAD

**Issue by cuigm85** [neo4j/neo4j#11968]
- Neo4j version: 3.3.5 to 3.4.1
- Operating system:  Windows 10
- API/Driver: Neo4j Desktop 1.1.7
- **Steps to reproduce**
1. import sample data : 
```
:play movies
```
2.1 Connect to neo4j with browser ( **Firefox, Chrome** etc.) and execute query and works.
```
MATCH (a)-[r:DIRECTED]->(m)<-[:DIRECTED]-(b)
WITH a,m,b
WHERE NOT (a-[:WROTE]-m)
RETURN a,m,b
```
2.2 Connect to neo4j with **browser comes with Neo4j Desktop** and execute same query and it fails to execute with error message.

```
Neo.ClientError.Statement.SyntaxError
Neo.ClientError.Statement.SyntaxError: Invalid input '<': expected whitespace, [ or '-' (line 3, column 14 (offset: 69))
"WHERE NOT (a-<missing ')'>[:WROTE]-m"
              ^

```

This query works fine.
```
MATCH (a)-[r:DIRECTED]->(m)<-[:DIRECTED]-(b)
WITH a,m,b
WHERE NOT ((a)-[:WROTE]-(m))
RETURN a,m,b
```

- Expected behavior
Same query should return same result or same error.

- Actual behavior
Browser comes with Neo4j Desktop return error but web browser return result correctly.

**Comment by jexp** [comment]
Please restart/refresh your desktop, it fetches a browser version (3.2.5) that fixes this issue.
It was because of the new multi-statement support which was added recently and broke some queries. That feature is for the time being now enabled with a config setting in the sidebar.
