### ISSUE TITLE
bug with OPTIONAL MATCH and RETURN DISTINCT

### ISSUE THREAD

**Issue by EtienneMdG** [neo4j/neo4j#11964]
I have a database with Sessions followed by a chain of Visits. Each Visit point to a Page.

The structure of the data is as follow:

A Session is followed by a chain a Visit:

`(:Session)-[:FIRST]->(:Visit)-[:NEXT]->(:Visit)-[:NEXT]-> ... -[:NEXT]->(:Visit)`

Each Visit links to a Page:
`(:Visit)-[:CONSISTS_IN)->(:Page)`

I want to query for each Page the number of Sessions ending at this Page. I want a result for each page, even if the result is 0, which justify the OPTIONAL.

The query i wrote is:

`MATCH (pa:Page) OPTIONAL MATCH (ses:Session)-[:FIRST]->(:Visit)-[:NEXT*0..]->(v1:Visit)-[:CONSISTS_IN]-(pa) WHERE NOT (v1)-[:NEXT]->() RETURN pa, count(DISTINCT v1)`

It is returning 0 for each page, which is not expected.

Removing the OPTIONAL, the DISTINCT or a label on a relationship give an expected result, with regard to the modified query.

I built a small example wich seems to not work as expected:

`CREATE (:A)-[:Y]->(:B)-[:X]->(:B)`
 
`OPTIONAL MATCH (:A)-[:Y]->(b:B)-[:X*0..]->(a:B) WHERE NOT (a)-[:X]->() RETURN DISTINCT a;`

Here, the query return null, despite a final node in the chain. Removing the OPTIONAL, the DISTINCT or a label on a relationship will give here too a correct answer.

This bug has been observed in neo4j 3.3.4

We also noticed this bug was not present in neo4j 2.3.2

Thank you

- Neo4j version: 3.3.4
- Operating system: Debian GNU/Linux 8
- API/Driver: OGM and browser

**Comment by SaschaPeukert** [comment]
@EtienneMdG Thanks for this report. I could reproduce it with 3.3.6 and even 3.4.4. We will make sure that it will be fixed and let you know about it
