### ISSUE TITLE
Neo4j won't start after update

### ISSUE THREAD

**Issue by razaulhaq** [neo4j/neo4j#11960]
There was a Neo4j update for like more than two months and I always skipped it but yesterday I installed it, now Neo4j won't start there nothing in logs not even a single line for new databases and for old ones there are only old logs nothing new is getting there I have even tried restarting system, currently I am using Neo4j 3.3.5 with Neo4j desktop 1.17 with windows 10

**Comment by eebus** [comment]
Hello @razaulhaq 
Have you followed https://neo4j.com/docs/operations-manual/current/upgrade/ ?

**Comment by craigtaverner** [comment]
@razaulhaq, I'm guessing this is an issue related to 'Neo4j Desktop'. Is that how you installed and upgraded Neo4j?

**Comment by oskarhane** [comment]
Could you please open the issue in Neo4j Desktops repository instead @razaulhaq?
https://github.com/neo4j-apps/neo4j-desktop
