### ISSUE TITLE
Relationship Types are not being posted into neo4j sandbox

### ISSUE THREAD

**Issue by aryamaia** [neo4j/neo4j#11961]
Hi,
Nodes are being posted, relationship Types are not being posted into neo4j sandbox through rest calls but being posted into desktop one, any help here?

**Comment by craigtaverner** [comment]
I'm sorry, I am not able to understand your report. Can you clarify by describing exactly what REST calls you are making onto exactly what REST service? You mention the sandbox, does that mean you are running a Neo4j server on the sandbox service at https://neo4j.com/sandbox-v2/? Are you trying to post something to a REST endpoint on the Neo4j server? Please give the exact query you are posting and what you expect to happen and what happens instead.

**Comment by zhenlineo** [comment]
@aryamaia Could you give us more information by answering @craigtaverner 's questions above for us to understand your problem more?

**Comment by aryamaia** [comment]
Solved it. Thank you for your time.
