### ISSUE TITLE
Confusing documentation for point type with no CRS

### ISSUE THREAD

**Issue by cleishm** [neo4j/neo4j#11977]
### Actual behavior

```
neo4j> CREATE (n:Test {loc: point({x:22, y:44})})
RETURN n.loc.crs, n.loc.srid;
+--------------------------------------+---------------------------------------+
| n.loc.crs                            | n.loc.srid                            |
+--------------------------------------+---------------------------------------+
| cartesian                            | 7203                                  |
+--------------------------------------+---------------------------------------+
```

### Expected behavior

According to [the documentation](https://neo4j.com/docs/developer-manual/current/cypher/functions/spatial/#functions-point-wgs84-2d), "If the coordinates are specified using `x` and `y`, then either the `crs` or `srid` field is required if a geographic CRS is desired.".

It would be clearer to word this in the same manner as for WGS-84 points, "If the coordinates are specified using `latitude` and `longitude`, the `crs` or [sic] `srid` fields are optional and inferred to be `'WGS-84'` (srid=4326).".

Example: "If the coordinates are specified using `x` and `y`, the `crs` _and_ `srid` fields are optional and inferred to be 'cartesian' (srid=7203)."

**Comment by SaschaPeukert** [comment]
Thanks for pointing that out. You are right, this sounds better! I'll make sure it gets updated

**Comment by petraselmer** [comment]
Hi @cleishm there is now a PR for this at [https://github.com/neo4j/neo4j-documentation/pull/238](https://github.com/neo4j/neo4j-documentation/pull/238)

Thanks for drawing our attention to this.

**Comment by craigtaverner** [comment]
We started making the suggested changes and realised they actually do not work. These suggetions make sense if the _considerations_ section was for a general section on the `point` function, which it is not. There are four sections, one for each of the CRS. The thinking is that each user would want to know how to make a point for their CRS of interest. The _consideration_ sections are all different, each specific to the CRS under consideration, and written from that perspective. The asymmetry observed here is deliberate and correct.
