### ISSUE TITLE
Error when returning point types using bolt protocol (Neo4j 3.4.1)

### ISSUE THREAD

**Issue by cleishm** [neo4j/neo4j#11975]
## Actual behavior

```
neo4j> :set format=csv
neo4j> CREATE (n:Test {location:point({latitude:18.25,longitude:334.34})});
Created 1 node, set 1 property, added 1 label
0 rows returned in 2ms (rendered after 6ms)
neo4j> MATCH (n:Test) RETURN n;
"n"
<interactive>:0:0: error: Point is not yet supported as a return type in Bolt
```

## Expected behaviour

Either:

a) Return a simple map instead (e.g. `{crs:'WGS84', latitude:334.34, longitude:18.25}`), which provides good backward compatibility; or
b) Provide a clearer error (e.g. "cannot return value of type Point as it is not supported by the connection protocol (Bolt V1)").

Providing backward compatibility (using a map) would be preferable until there is a documented proposal for a future version 2 of the bolt protocol (and it is agreed and accepted by the community).

Likely the same issue occurs for other datatypes introduced in Neo4j 3.4

**Comment by SaschaPeukert** [comment]
I tried to reproduce this with the current version but it works without errors. So I would say that it is fixed in (at least) Neo4j 3.4.7
