### ISSUE TITLE
Request - Improve error messages to specify actual issue

### ISSUE THREAD

**Issue by Manish-Giri** [neo4j/neo4j#11970]
I was writing a query in Cypher which uses a `case` statement to return a `commonPostScore` based on two items - `allPostCount`, `commonPostCount`. If `allPostCount` is 0, I want to return 0 as the final number, or else `commonPostCount/allPostCount`.

The relevant part of my query is shown below -

```
RETURN friend.id as friendId, friend.firstName + ' ' + friend.lastName + ', ' + friend.gender AS friend, friendCityName
CASE allPostCount
  WHEN 0 THEN 0.0
  ELSE commonPostCount/allPostCount
END AS commonInterestScore
ORDER BY commonInterestScore DESC
LIMIT 10
```
I was writing the query based on the documentation on [Cypher expressions](https://neo4j.com/docs/developer-manual/current/cypher/syntax/expressions/). The first example didn't use a `,` right before the `CASE` keyword -
```
MATCH (n)
RETURN
CASE n.eyes
WHEN 'blue'
THEN 1
WHEN 'brown'
THEN 2
ELSE 3 END AS result 
```

which is what I followed in my query.

I got an error, but more importantly, the error message was very cryptic and had no relevant information as to what went wrong -

![screenshot 2018-07-12 03 51 20](https://user-images.githubusercontent.com/11348778/42619776-0235336c-8587-11e8-9944-52a58f144cb0.png)

Consequently, I spent a lot of time researching what was wrong, and eventually landed on this [SO question](https://stackoverflow.com/questions/43187222/case-right-after-with-in-neo4j-and-cypher) which had a similar error. I realized I was missing a `,` after looking at the answer.

So, it'd be really helpful if the error message actually provided some meaningful information related to the cause, if not pinpoint the exact cause.

`Invalid input 'S': expected 'l/L'` doesn't really help me figure out that there's a comma missing somewhere. 

- Neo4j version: 3.4.1
- Operating system: Mac OSX High Sierra
- API/Driver: Cypher

**Comment by cleishm** [comment]
The error message results from the parser trying to calculate what the next valid token would be. Because the comma is missing, the next token is probably the start of a clause, like "RETURN", "WITH", "MATCH", "MERGE", "CALL", etc. And the "CA" matches the start of the "CALL" clause. Therefore, the only next valid letter after "CA" must be the "L" (or "l"), which is why the error is "expected 'l/L'": it's the only possible letter that could occur at this position to make the preceding characters correct.

Of course, in your case, the real problem is that several preceeding characters are incorrect (the "CA"), due to the missing comma before them. This is much harder for the parser to realize, and it doesn't do it automatically. But it might be possible to update the parser to recognise it, and given this is probably not an unusual situation, that "fix" would be to add rules to the parser at this position to match anything _not_ a clause name and emit an error about a missing comma.

**Comment by Hunterness** [comment]
Hi, this seems like a nice idea but like @cleishm stated, this is not straight forward work but we will take it into consideration.

**Comment by fickludd** [comment]
Hi @Manish-Giri ,

The cypher parser can indeed generate very confusing error messages for some broken queries. However, solving this for the general case is very hard, as it often amounts to _guessing what the user intended_. This is unfortunately not something that we currently can prioritize, so we will have to suffer the inconvenience of confusing error messages for now.

**Comment by cleishm** [comment]
@fickludd / @Hunterness: to be fair to @Manish-Giri, while this isn't easily solvable _in general_, it would be fairly straightforward to solve this specific case (that of a missing comma in the return clause).

**Comment by cleishm** [comment]
As I'm not one to make flippant comments without backing them up, here's an example approach:

```diff
diff --git a/community/community-it/cypher-it/src/test/scala/org/neo4j/cypher/ErrorMessagesTest.scala b/community/community-it/cypher-it/src/test/scala/org/neo4j/cypher/ErrorMessagesTest.scala
index 35a25bfdbf5..b7bfb64e4b2 100644
--- a/community/community-it/cypher-it/src/test/scala/org/neo4j/cypher/ErrorMessagesTest.scala
+++ b/community/community-it/cypher-it/src/test/scala/org/neo4j/cypher/ErrorMessagesTest.scala
@@ -255,6 +255,12 @@ class ErrorMessagesTest extends ExecutionEngineFunSuite {
     )
   }
 
+  test("should identify missing comma in RETURN clause") {
+    expectError("RETURN 1, 2 CASE 1 WHEN 1 THEN 'ONE' ELSE 'DEFAULT' END",
+      "Invalid infix expression (missing comma?)"
+    )
+  }
+
   private def expectError(query: String, expectedError: String) {
     val error = intercept[CypherException](executeQuery(query))
     assertThat(error.getMessage, containsString(expectedError))
diff --git a/community/cypher/front-end/ast/src/main/scala/org/neo4j/cypher/internal/v3_5/ast/semantics/SemanticExpressionCheck.scala b/community/cypher/front-end/ast/src/main/scala/org/neo4j/cypher/internal/v3_5/ast/semantics/SemanticExpressionCheck.scala
index 4f869210d61..ddbcceb098f 100644
--- a/community/cypher/front-end/ast/src/main/scala/org/neo4j/cypher/internal/v3_5/ast/semantics/SemanticExpressionCheck.scala
+++ b/community/cypher/front-end/ast/src/main/scala/org/neo4j/cypher/internal/v3_5/ast/semantics/SemanticExpressionCheck.scala
@@ -417,6 +417,11 @@ object SemanticExpressionCheck extends SemanticAnalysisTooling {
       case x:BooleanLiteral =>
         specifyType(CTBoolean, x)
 
+      case x:InvalidInfixExpression =>
+        SemanticError(
+          "Invalid infix expression (missing comma?)",
+          x.position)
+
       case x:SemanticCheckableExpression =>
         x.semanticCheck(ctx)
 
diff --git a/community/cypher/front-end/expressions/src/main/scala/org/neo4j/cypher/internal/v3_5/expressions/OperatorExpression.scala b/community/cypher/front-end/expressions/src/main/scala/org/neo4j/cypher/internal/v3_5/expressions/OperatorExpression.scala
index 8e91a621f89..6874e4543f6 100644
--- a/community/cypher/front-end/expressions/src/main/scala/org/neo4j/cypher/internal/v3_5/expressions/OperatorExpression.scala
+++ b/community/cypher/front-end/expressions/src/main/scala/org/neo4j/cypher/internal/v3_5/expressions/OperatorExpression.scala
@@ -15,6 +15,7 @@
  * limitations under the License.
  */
 package org.neo4j.cypher.internal.v3_5.expressions
+import org.neo4j.cypher.internal.v3_5.util.InputPosition
 
 trait OperatorExpression {
   self: Expression =>
@@ -58,3 +59,4 @@ trait MultiOperatorExpression  extends OperatorExpression {
   override def asCanonicalStringVal: String = s"$canonicalOperatorSymbol( ${exprs.map(_.asCanonicalStringVal).mkString(", ")}"
 }
 
+case class InvalidInfixExpression()(val position: InputPosition) extends Expression with OperatorExpression
diff --git a/community/cypher/front-end/parser/src/main/scala/org/neo4j/cypher/internal/v3_5/parser/Expressions.scala b/community/cypher/front-end/parser/src/main/scala/org/neo4j/cypher/internal/v3_5/parser/Expressions.scala
index 585b61cfae0..d986b691d90 100644
--- a/community/cypher/front-end/parser/src/main/scala/org/neo4j/cypher/internal/v3_5/parser/Expressions.scala
+++ b/community/cypher/front-end/parser/src/main/scala/org/neo4j/cypher/internal/v3_5/parser/Expressions.scala
@@ -136,9 +136,14 @@ trait Expressions extends Parser
       | group(keyword("CONTAINS") ~~ Expression2) ~~>> (expressions.Contains(_: Expression, _))
       | keyword("IS NULL") ~~>> (expressions.IsNull(_: Expression))
       | keyword("IS NOT NULL") ~~>> (expressions.IsNotNull(_: Expression))
+      | InvalidInfixExpressions ~~>> ((_: Expression) => expressions.InvalidInfixExpression())
     ): ReductionRule1[Expression, Expression])
   }
 
+  private def InvalidInfixExpressions: Rule0 = rule("an expression") (
+      CaseExpression ~~% (_ => {})
+  )
+
   private def Expression2: Rule1[Expression] = rule("an expression") {
     Expression1 ~ zeroOrMore(WS ~ (
         PropertyLookup
```
