### ISSUE TITLE
Feature: editable UI

### ISSUE THREAD

**Issue by xenoterracide** [neo4j/neo4j#11978]
I like Neo4j, but what I've realized is that my initial use case for it isn't really as a database, but rather as an advanced mind map of sorts. A way to document complex node structures. Problem I encounter with using neo4j for this is that the Web UI view isn't editable, and that I'd have to write queries just to create simple relationships. I doesn't seem like it would be impossible to be able to click to create a node, or draw a relationship, and even edit it. One way I'm looking at this, is with SQL I have a large number of "table oriented" editors to choose from... I don't see that so much with Neo4j, and given the pretty web ui it has I would more expect one to be a part of it.

**Comment by akollegger** [comment]
Thanks for the feature request @xenoterracide , it's sensible and something we agree is needed. We are starting to build up more client-side capability within Neo4j Desktop. The builtin web ui, Neo4j Browser, will continue to evolve as a developer or admin oriented tool. Applications like Neo4j Bloom will be more end-user oriented, featuring capabilities like code-free editing.
