### ISSUE TITLE
Temporal type naming confusion

### ISSUE THREAD

**Issue by cleishm** [neo4j/neo4j#11985]
It's confusing to figure out which temporal types are "local" (without a timezone) and which do include timezone information, as they do not seem to follow any common naming and the documentation is unclear.

Can someone clarify?

**Comment by SaschaPeukert** [comment]
This page explains exactly that: https://neo4j.com/docs/developer-manual/current/cypher/syntax/temporal/#cypher-temporal-introduction

Was that helpful for you?

**Comment by cleishm** [comment]
Hi @SaschaPeukert! Yes, that page is great. The documentation I was reading wasn't as clear to me: https://neo4j.com/docs/developer-manual/current/cypher/functions/temporal/

Perhaps there shouldn't be two different pages for this?

**Comment by cleishm** [comment]
Although the page you mentioned is referenced from the one I read, so I guess shame on me for not reading that too :)
