### ISSUE TITLE
Neo4j server stop operation takes unusually long time - Windows 10

### ISSUE THREAD

**Issue by SOUMAJYOTI** [neo4j/neo4j#11984]
The Neo4j server on Windows 10 takes unusually long time to stop (3 to 4 minutes). Earlier it used to take just <5 seconds to stop but suddenly it is taking a long time to stop. The start operation works fine.
I have attached the log files from the system.

- Neo4j version: 3.2.12
- Operating system:  Windows 10
- API/Driver: Not Applicable
- **Steps to reproduce**

 Specific to this system.

Open the Windows 10 command prompt and start and stop the server.

> net start neo4j (works fast and fine)
> net stop neo4j (takes unusually long time)

- Expected behavior
The Neo4j server should stop within a short time (typically takes < 5 seconds)

- Actual behavior
Neo4j server takes about 3 minutes  to stop

- Log files:

[debug.log](https://github.com/neo4j/neo4j/files/2202551/debug.log)
[neo4j.log](https://github.com/neo4j/neo4j/files/2202552/neo4j.log)
[neo4j-service.2018-07-17.log](https://github.com/neo4j/neo4j/files/2202553/neo4j-service.2018-07-17.log)
[service-error.log](https://github.com/neo4j/neo4j/files/2202554/service-error.log)

**Comment by FuYouJ** [comment]
hello,I had the same problem, what caused it?
