### ISSUE TITLE
Neo4j Desktop update process misbehaving

### ISSUE THREAD

**Issue by colingoldberg** [neo4j/neo4j#11988]
Hi,

Restarting my mac caused Neo4j Desktop (current version 1.1.7) to show a message indicating that version 1.1.8 was available. However, the message contained no buttons or links or any way to indicate that I wanted to update the version on my mac. And when I went to neo4j.com and clicked Download, it showed it would download 1.1.7.

![image](https://user-images.githubusercontent.com/2991417/42963265-b958671e-8b61-11e8-9610-8efadef347c8.png)

**Comment by InverseFalcon** [comment]
Hi there,

This is a small visual bug, you should be able to zoom out (using the View menu) in combination with resizing the screen until the buttons are visible at the bottom of the dialog.

**Comment by colingoldberg** [comment]
Thanks - that worked. Needless to say, your solution is not intuitively obvious.
