### ISSUE TITLE
Extract annotation processor classes to separate module/library

### ISSUE THREAD

**Issue by stefanneuhaus** [neo4j/neo4j#11987]
## Request

Classes in the package "org.neo4j.kernel.impl.annotations" from the module "neo4j-kernel" define annotations and corresponding annotation processors. The request is to extract these classes from "neo4j-kernel" and provide them via separate modules for both the annotations and the annotation processors.

## Motivation
With the current dependency/library structure of neo4j there does not seem to be a way to build projects using neo4j with Gradle [>= 4.6](https://docs.gradle.org/4.6/release-notes.html#putting-annotation-processors-on-the-compile-classpath-or-explicit--processorpath-compiler-argument) without warnings:

In my Gradle build file I have a "compile" dependency to neo4j:
```groovy
    compile('org.neo4j:neo4j:3.4.4')
```

When building I get the following warning:
```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings
```

When building with the Gradle CLI option `--warning-mode=all` I get the more detailed explanation:
```
The following annotation processors were detected on the compile classpath: 
'org.neo4j.kernel.impl.annotations.ServiceProcessor' and 'org.neo4j.kernel.impl.annotations.DocumentationProcessor'. 
Detecting annotation processors on the compile classpath is deprecated and Gradle 5.0 will ignore them. 
Please add them to the annotation processor path instead. 
If you did not intend to use annotation processors, you can use the '-proc:none' compiler argument to ignore them.
```

Without implementing this feature request the only options to get rid of the warnings seem to be:
- suppress all warnings via `--warning-mode=none`
- use the `-proc:none`compiler option. Without further modifications to the build this would break projects that
  - use other annotation processors (e.g. Lombok, Immutables etc.) in the compile configuration
  - use the annotation `@org.neo4j.helpers.Service.Implementation`or `@org.neo4j.kernel.impl.annotations.Documented` (they have to add "neo4j-kernel" to the "annotationProcessor" configuration

Also projects using these annotations being built by Gradle 5 will require to not only add the "neo4j" dependency to the classpath. Thus the instructions on how to declare the dependencies with Gradle should be adapted. Even builds with Gradle >= 4.6 would benefit from this new proposed way to declare the dependencies.

**Comment by chrisvest** [comment]
We've moved the annotation processors to a separate module as of the next 3.5 patch release.
