### ISSUE TITLE
Field with -- not read (example: Age--years)

### ISSUE THREAD

**Issue by prabin525** [neo4j/neo4j#11995]
I had a field name Age--years in a product Node and i ran a query 

`MATCH (a:Product)
RETURN max(a.Age--years)` but the query didn't run and threw an error

`
Neo.ClientError.Statement.SyntaxError: Variable `years` not defined (line 2, column 19 (offset: 36))
"RETURN max(a.Age--years)"
`

- Neo4j version: 3.4.3
- Operating system: Arch Linux 
- API/Driver: Cypher and Python driver

**Comment by chrisvest** [comment]
You can quote the name with backticks, like this:

```
MATCH (a:Product) RETURN max(a.`Age--years`)
```
