### ISSUE TITLE
Feature Request: Cannot delete property with DETACH DELETE

### ISSUE THREAD

**Issue by folowpig** [neo4j/neo4j#11994]
Using "DETACH DELETE" command, I was able to delete all node labels and relationships, but the properties were not deleted. 
I wish that the DETACH DELETE command delete all data including the properties.

![image](https://user-images.githubusercontent.com/10948585/43118697-ed82c8dc-8f4d-11e8-88fa-490c17a93f55.png)
![image](https://user-images.githubusercontent.com/10948585/43118679-dfd375d8-8f4d-11e8-990f-ee0066a068f9.png)

**Comment by chrisvest** [comment]
Properties are also deleted by `DETACH DELETE`. We just don't report how many were there, because then we'd have to go through the effort to count them.

**Comment by folowpig** [comment]
Yes, you are right chris. The value of properties are deleted, but the property keys are still visible on the database information tab. Do you know how to delete those property keys?
