### ISSUE TITLE
Creating relationships with multiple labels (Cyper 2.0.0 M4)

### ISSUE THREAD

**Issue by bunkat** [neo4j/neo4j#1199]
It would be nice to be able to create a relationship with multiple labels such as:

```
CREATE n-[:LABEL1:LABEL2]->t
```

Currently this results in `SyntaxException: unclosed bracket`. While most of the time this scenario can be handled with two relationships, it would be nice to support multiple labels for situations in which one relationship cannot exist without the other (i.e. if the relationship with LABEL1 is deleted, the relationship with LABEL2 must also be deleted).

**Comment by mdw00d** [comment]
This results in a regrettable inconsistency between nodes and edges/relationships.  When the neomodel library is used with neo4j, class inheritance for nodes is modeled by associating a label with a node corresponding to each inherited class.  It would be desirable if this same behavior happened for relationships, allowing the inheritance structure to be represented within the graph.
