### ISSUE TITLE
Would like date(null) to return null and not today?

### ISSUE THREAD

**Issue by soetang** [neo4j/neo4j#12008]
It seems that currently:
`Return date(null)`
returns today

I dont know if this is intentional, however i dont like it. Why should null = today ? I would prefer that it returns null. For people unaware of this, this might have problematic consequences.

The refcard: https://neo4j.com/docs/cypher-refcard/current/ currently states that:
"Arithmetic expressions, comparisons and function calls (except coalesce) will return null if any argument is null." 

This is not consistent with the behavior above, so in case you don't believe `return date(null)` should return null the refcard should probably be updated.

I have the desktop veision:
Version: | 3.4.5
Edition: | Enterprise

**Comment by SaschaPeukert** [comment]
@soetang Thanks for reporting this. I am happy to say that we agree with you (it should return null) and have already fixed this issue. It will be included in the next release: `Neo4j 3.4.6`
