### ISSUE TITLE
Neo.DatabaseError.General.UnknownFailure

### ISSUE THREAD

**Issue by yasirkk** [neo4j/neo4j#12001]
I am trying retrieve the node using the query `MATCH (node:User) WHERE id(user) IN [1,2,3,4,....4000,4001,....n] RETURN n.user_data ` and encounter an error Neo.DatabaseError.General.UnknownFailure and i tried the same query `MATCH (node:User) WHERE id(user) IN {ids} RETURN id(n)` and id passed as parameter and now get the error invalid syntax. In my db there is more than 10000 users and it still growing. Is there any limitations in `IN`. I noticed that maximum no.of node id accepted is around 4000.
Any method to resolve this issue , please help me.
Neo4j Version : 2.2.2

**Comment by SaschaPeukert** [comment]
Hi @yasirkk 

You are running on a quite old version of Neo4j that is not supported anymore. Could you update to any of the currently supported versions (I would recommend 3.4.5) and test if that fixes your problem? https://neo4j.com/download-center/#releases

**Comment by sherfert** [comment]
We haven't heard from @yasirkk in quite a while. Please reopen if this issue still exists for you on a newer, supported, version.
