### ISSUE TITLE
Cannot view righthand edge of neo4j browser input/output windows on Mac OS X desktop version

### ISSUE THREAD

**Issue by DrYort** [neo4j/neo4j#12005]
Bug report - neo4j Desktop running on Mac OS X

When I open the Neo4j browser I cannot see the right-hand side of the code input and output display windows, regardless of whether I resize the window by dragging the edge. Therefore I cannot close an output window, or click with a mouse/cursor on the execute code triangle button in the top right, as this part of the window is not visible.

Neo4j Desktop Version running on a Macbook: 1.1.8 (1.1.8.704)  
Operating System: OS X 10.11.6  
API: unsure

Steps to reproduce
1. Start any graph/project.
2. Open Browser.
3. Fault evident upon opening the browser.

Expected behavior
Should be able to see right hand edge of window of the code input and the output windows. Should be able to see window buttons on top-right.

Actual behavior
Cannot view right hand edge of code input and output windows.

Apologies in advance if this report is missing any key information as I am very new to this.

![screen shot of neo4j bug in browser running on os x_2018-08-07](https://user-images.githubusercontent.com/39147026/43760730-5565641e-9a66-11e8-9428-da4d17e6a656.jpeg)

**Comment by JonasR888** [comment]
I'm experiencing the same..

**Comment by oskarhane** [comment]
Sorry, we didn't see this one when it was created due to it's in the wrong repo.
Could any of you please open this again in the [neo4j-desktop](https://github.com/neo4j-apps/neo4j-desktop) repo instead?

Thanks

**Comment by DrYort** [comment]
I've opened the issue again in the neo4j-desktop repo...

Note that I resolved it by deleting the instance of Neo4j on my laptop, and then re-installing it - which does not assist in determining the cause of the issue.
