### ISSUE TITLE
Possible bug duration.inDays

### ISSUE THREAD

**Issue by soetang** [neo4j/neo4j#12013]
Possible bug:

On the slack channel i was asked to post this here:

- Neo4j version: 3.4.5
- Operating system: Ubuntu 16.04
- API/Driver: Python driver 

Have a long query:

`match (r1:Regnskab{UUID:$UUID})<-[hr1:har_regnskab]-(v:Virksomhed) with v, xyz,... optional match (v)-[r:har_direktoer]->(p:Person) with avg(duration.inDays(r.fra, r.til).days) as avg_days_dir, xyz .. return avg_days_dir, xyz`.

If the second pattern is not found i get the error message: `Provided input was [NO_VALUE, NO_VALUE]` which makes sense since `r.fra` and `r.til` is null in that case. However it is not consistent with the ref card, which states:

_Arithmetic expressions, comparisons and function calls (except coalesce) will return null if any argument is null._

I tried to fix it with:
`optional match (v)-[r:har_direktoer]->(p:Person) with CASE WHEN r is not null THEN avg(duration.inDays(r.fra, r.til).days) ELSE null END as avg_days`. However even though `r` is null i still get the error message, as if the query still evaluates avg(duration.inDays(r.fra, r.til).days). 

### Expected behavior
When a null value is passed to duration.inDays i would expect it to return null in accordance with the refcard.

When a part of the case statement is not true i would expect it to not execute that part.

### Actual behavior
Both of the above returns: `Provided input was [NO_VALUE, NO_VALUE]`  instead.

I dont know if this is really two bugs? but if at least one of them is fixed i can make a query that works.

**Comment by SaschaPeukert** [comment]
@soetang Thanks for reporting this. We will take a look at it

**Comment by sherfert** [comment]
Hi @soetang . The fix for this will be included in the upcoming 3.4.6 release. Please let us know afterwards if there remains any problem.
