### ISSUE TITLE
neo4j listening port process not starting 

### ISSUE THREAD

**Issue by Oadegbite** [neo4j/neo4j#12015]
I'm trying to start a cluster with 2 servers on the same network both are running Neo4j enterprise 3.5 on Ubuntu Server 16.04 LTS. First I'm not sure if a Neo4j cluster can be started with 2 servers but the operations manual said that was the minimum number.

I've tested that I can connect and run both as single instances of neo4j but when I try to set up the cluster it gets stuck and this is the status output.

● neo4j.service - Neo4j Graph Database
   Loaded: loaded (/lib/systemd/system/neo4j.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2018-08-14 16:45:28 EDT; 27s ago
 Main PID: 2864 (java)
    Tasks: 114
   Memory: 1.3G
      CPU: 25.002s
   CGroup: /system.slice/neo4j.service
           └─2864 /usr/bin/java -cp /var/lib/neo4j/plugins:/etc/neo4j:/usr/share/neo4j/lib/*:/var/lib/neo4j/plugins/* -server -XX:+UseG1GC -XX:-OmitStackTraceInFastThrow -XX:+AlwaysPreTouch -XX:+Un

Aug 14 16:45:30 ubuntu-srv-16 neo4j[2864]: 2018-08-14 20:45:30.310+0000 INFO  Starting...
Aug 14 16:45:33 ubuntu-srv-16 neo4j[2864]: 2018-08-14 20:45:33.549+0000 INFO  Initiating metrics...
Aug 14 16:45:33 ubuntu-srv-16 neo4j[2864]: 2018-08-14 20:45:33.824+0000 INFO  My connection info: [
Aug 14 16:45:33 ubuntu-srv-16 neo4j[2864]:         Discovery:   listen=0.0.0.0:5000, advertised=192.168.3.1:5000,
Aug 14 16:45:33 ubuntu-srv-16 neo4j[2864]:         Transaction: listen=0.0.0.0:6000, advertised=192.168.3.1:6000,
Aug 14 16:45:33 ubuntu-srv-16 neo4j[2864]:         Raft:        listen=0.0.0.0:7000, advertised=192.168.3.1:7000,
Aug 14 16:45:33 ubuntu-srv-16 neo4j[2864]:         Client Connector Addresses: bolt://192.168.3.1:7687,http://192.168.3.1:7474,https://192.168.3.1:7473
Aug 14 16:45:33 ubuntu-srv-16 neo4j[2864]: ]
Aug 14 16:45:33 ubuntu-srv-16 neo4j[2864]: 2018-08-14 20:45:33.826+0000 INFO  Discovering cluster with initial members: [192.168.3.1:5000, 192.168.3.2:5000]
Aug 14 16:45:33 ubuntu-srv-16 neo4j[2864]: 2018-08-14 20:45:33.827+0000 INFO  Attempting to connect to the other cluster members before continuing...

What I've noticed is that on one server the process for the Transaction port doesn't start.
Here are a few commands I used to look at the ports

tomi@server1:~$ nc -zv 192.168.3.1 5000 6000 7000
Connection to 192.168.3.1 5000 port [tcp/*] succeeded!
nc: connect to 192.168.3.1 port 6000 (tcp) failed: Connection refused
Connection to 192.168.3.1 7000 port [tcp/afs3-fileserver] succeeded!

tomi@server2:~$ nc -zv 192.168.3.2 5000 6000 7000
Connection to 192.168.3.2 5000 port [tcp/*] succeeded!
Connection to 192.168.3.2 6000 port [tcp/x11] succeeded!
Connection to 192.168.3.2 7000 port [tcp/afs3-fileserver] succeeded!

tomi@server2:~$ sudo lsof -i tcp | grep neo4j
java    30525 neo4j  276u  IPv6 1768138      0t0  TCP 192.168.3.2:5000 (LISTEN)
java    30525 neo4j  470u  IPv6 1763075      0t0  TCP *:afs3-fileserver (LISTEN)
java    30525 neo4j  492u  IPv6 1776019      0t0  TCP 192.168.3.2:58869->192.168.3.1:5000 (ESTABLISHED)
java    30525 neo4j  877u  IPv6 1774726      0t0  TCP *:x11 (LISTEN)
java    30525 neo4j  974u  IPv6 1774759      0t0  TCP localhost:6362 (LISTEN)

tomi@server1:~$ sudo lsof -i tcp | grep neo4j
java    2864    neo4j  275u  IPv6  27388      0t0  TCP 192.168.3.1:5000 (LISTEN)
java    2864    neo4j  277u  IPv6  17200      0t0  TCP 192.168.3.1:5000->192.168.3.2:58869 (ESTABLISHED)
java    2864    neo4j  470u  IPv6  27899      0t0  TCP *:afs3-fileserver (LISTEN)

tomi@server2:~$ sudo lsof -i tcp:6000
COMMAND   PID  USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
java    30949 neo4j  878u  IPv6 1763120      0t0  TCP *:x11 (LISTEN)

tomi@server1:~$ sudo lsof -i tcp:6000
This provides no output

I was wondering if this is a bug and if there is a way to manually start the listening for neo4j on that port.

I've made sure that they can communicate on that port and tried changing the listening port but that hasn't worked.

I installed neo4j via the package manager with apt-get and have tried uninstalling and reinstalling and reinstalling.

Unfortunately, I’m on a restrictive university network so I can’t attempt to connect to an outside server to test creating the cluster with another server at the moment, Thanks for the help.

**Comment by RagnarW** [comment]
Closing due to unsupported version
