### ISSUE TITLE
Cypher query returning node with wrong label

### ISSUE THREAD

**Issue by vigorouscoding** [neo4j/neo4j#12017]
I discovered that a cypher query returns a node that does not have all the labels that I have requested.
In my query I ask for `:NodeInterface:Principal` but the returned node has the labels `:NodeInterface:IndexedWord`.

**Neo4j Version:** 3.4.5
**Operating System:** Mac OS 10.13.4

### Steps to reproduce
1. Install Neo4j 3.4.5 (Enterprise)
2. Run the following Cypher statements

````
CREATE
	(:NodeInterface:Principal {name: "user 1", eMail:"user1@structr.com"}),
	(:NodeInterface:Principal {name: "user 2", eMail:"user2@structr.com"}),
	(:NodeInterface:Principal {name: "user 3", eMail:"user3@structr.com"}),
	(:NodeInterface:Principal {name: "user 4", eMail:"user4@structr.com"}),
	(:NodeInterface:Principal {name: "user 5", eMail:"user5@structr.com"});

CREATE 
	(:NodeInterface:IndexedWord {name: "sales"});
````

3. Query for a principal (result should be 0 rows - as intended)

````
MATCH (n:NodeInterface:Principal) WHERE n.`name` = "sales" OR n.`eMail` = "sales" RETURN DISTINCT n ORDER BY n.`name`
````

4. Add the following indexes:
````
CREATE INDEX ON :NodeInterface(name);
CREATE INDEX ON :Principal(eMail);
````

5. Query for a principal again - this should still be 0 users. But one row `:NodeInterface:IndexedWord` is returned

````
MATCH (n:NodeInterface:Principal) WHERE n.`name` = "sales" OR n.`eMail` = "sales" RETURN DISTINCT n ORDER BY n.`name`
````

### Additional Information

It seems that 5 principal nodes is the magic number. With 4 principal nodes it does not happen. Using `EXPLAIN` you can see that with 4 nodes a `NodeByLabelScan` is used and with 5 nodes a `NodeIndexSeek` is used.

### Expected behavior
The query should return only nodes that have the labels that were requested. In this small example case this would mean not returning any rows.

### Actual behavior
The query returns 1 row with only one of the requested labels.

**Comment by muralimani** [comment]
I tried the same steps above. It seems to be a bug, due to CREATE INDEX / indexing command.

**Comment by Lojjs** [comment]
@vigorouscoding Thanks for reporting. This turned out to be a bug in our cost planner about the combination of OR and two NodeIndexSeeks with different labels. We now have a fix for it that will be included in the next patch releases of all supported versions (3.2.13, 3.3.7, 3.4.7 and 3.5.0-alpha08).

Best regards Louise, Neo4j Cypher team
