### ISSUE TITLE
Neo4j 3.4.4 - no more threads available

### ISSUE THREAD

**Issue by NivTikolski** [neo4j/neo4j#12014]
hi,
I upgrade the production(cluster) environment to neo4j 3.4.4 and .net driver 1.6.1 two weeks ago.
from then something like twice/three times a day i get lots of this error: 
**Neo4j.Driver.V1.TransientException: There are no available threads to serve this request at the moment. You can retry at a later time or consider increasing max thread pool size for bolt connector(s).**

if i rollback the neo4j version everything works perfectly. 
hope you can help somehow, or can give me some tools how to give you more information.

Thanks,
Niv.

**Comment by ali-ince** [comment]
Hi @NivTikolski,

Before 3.4.0 each established Bolt connection was assigned a dedicated thread on the server, whereas with 3.4.0 onward they are backed by a thread pool.

The error message tells that all threads in the thread pool are currently handling work from active connections and cannot handle more work. There're two points to consider here;

a. It could be the case that your client application requires a larger thread pool than the defaults,
b. Your client application is leaking transactions/statements and keeping the threads (of the thread pool) busy.

You can read more about the Bolt thread pool [here](https://neo4j.com/docs/operations-manual/current/performance/bolt-thread-pool-configuration/).

Thanks.

**Comment by NivTikolski** [comment]
@ali-ince 
-you can give an example of what you define as leaking transaction? 
for every transaction we close the session.

-there is a way to check how much threads are in the pool? somehow to investigate this?
because everyday we have this and the production stops working for 10 minutes, it's a big problem for us of course.

thanks,
niv.

**Comment by ali-ince** [comment]
If you're using transaction functions (i.e. `Session.ReadTransaction` and `Session.WriteTransaction`) you're mostly safe - however if you have places where you are making use of `Session.Run` or `Session.BeginTransaction` then it would be the case that you do not consume the results and/or close the transaction/session objects. 

Below are very simple snippets showing a couple of possible scenarios;

```csharp
// GOOD
var session = driver.Session();
try
{
    var cursor = await session.RunAsync("RETURN 1");
    var result = await cursor.ToListAsync();
    
    // do something with result
}
finally
{
	await session.CloseAsync();
}
// finally block will ensure that the resources are closed as required

```

```csharp
// GOOD
var session = driver.Session();
try
{
    var result = await session.ReadTransactionAsync(async tx =>
    {
        var cursor = await tx.RunAsync("RETURN 1");
        var list = await cursor.ToListAsync();
        return list;
    });
}
finally
{
	await session.CloseAsync();
}
// finally block will ensure that the resources are closed as required
```

```csharp
// BAD
var session = driver.Session();
var cursor = await session.RunAsync("RETURN 1");
// an unconsumed result/cursor with an unclosed session will leave the connection
// open keeping both client and server resources busy
```

```csharp
// BAD
var session = driver.Session();
var transaction = await session.BeginTransactionAsync();
var cursor = await transaction.RunAsync("RETURN 1");
var result = await cursor.ToListAsync();
// an explicit transaction needs to be closed (committed/rolledback) although the
// result/cursor is consumed. If not, it will leave the connection
// open keeping both client and server resources busy
```

```csharp
// BAD
var session = driver.Session();
var transaction = await session.BeginTransactionAsync();
var cursor = await transaction.RunAsync("RETURN 1");
var result = await cursor.ToListAsync();
await transaction.CommitAsync();
// although there's a call to CommitAsync, things may go wrong above and it may end up
// being not executed because of exceptions. Close operations should ideally be handled on a 
// finally block (or enclosed with a using block - which may end up running synchronous network 
// operations)
```

Please refer to the developer manual [here](https://neo4j.com/docs/developer-manual/current/drivers/sessions-transactions/).

As described on Bolt thread pool configuration page, the default maximum thread pool size is `400` and you're apparently hitting that limit. You can enable metrics monitoring (described [here](https://neo4j.com/docs/operations-manual/current/monitoring/metrics/) and specifically look at values reported by `neo4j.bolt.*` metrics described [here](https://neo4j.com/docs/operations-manual/current/monitoring/metrics/reference/#metrics-general-purpose).

Thanks.

**Comment by NivTikolski** [comment]
@ali-ince 
thanks,
it looks like we working perfectly with the transactions.
i will add monitoring to the graphite and will check if can see something from there, because it is very weird problem, our traffic is low and the minimum threads are 400 and maximum 800, if we get to that it will be very strange.

thanks,
Niv.
