### ISSUE TITLE
Can't connect Neo4j Database

### ISSUE THREAD

**Issue by NtHawk101** [neo4j/neo4j#12012]
My first time here and attempting to get an instance of LogonTracer to run. Any suggestions would be much appreciated as I try to learn how to work in Debian.

- Neo4j version: 3.4.5
- Operating system: Debian 9.5
- API/Driver: Python 3.5.3
- **Steps to reproduce**
-Installed per direction here and get [IP address}:7474 to open correctly
-Then run Python3 logontracer.py -r -o -n xxx -p xxx -s [IP address of the server]

What I get back is a bunch of messages stating RunTimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88

At the end of these, I then see the message [!] hmmlearn must be installed for this script
- Expected behavior
 Expected [IP address of the server}:8080 to open to Logontracer web page
- Actual behavior
 Blank web page stating this site can't be reached. Refused to connect message

I ran netstat -an and never see port 8080 listening
I checked and verified that hmmlearn is installed. Re-running the requirements.txt file indicates requirements already satisfied.

Wondering if I should revert to an older Debian version

what log should I be looking at to get more information?

Thank you!

**Comment by zhenlineo** [comment]
Hi @NtHawk101 ,

After reading your description, we do not think this is related to Neo4j or our official python driver directly.
Pls open an issue on `LogonTracer` project instead.

Regards,
Zhen
