### ISSUE TITLE
Problem with a logical expression

### ISSUE THREAD

**Issue by hakami1024** [neo4j/neo4j#12029]
I'm running the following query:
```
RETURN
(
  (
    (
      7414 IN [7372, 7414]
    ) 
    AND 
    (
       67542.0 <= 64547.0
    )
  ) 
  OR 
  (
    (
      7414 IN [7371, 7368, 7413, 7410] 
    )
    AND 
    (
       67542.0 <= 4061660.0
    )
  )
);
```
On
- Neo4j version: 3.1.3
- Operating system: Ubuntu 16.04 
- Connecting through [http://localhost:7474/browser/]
it returns `false`. That looks OK.

But!
On
- Neo4j version: 3.4.7
- Operating system: ArchLinux 
- Connecting through [http://localhost:7474/browser/]
it returns `true`.

This bunch of numbers is a heavily reduced part of my match-where query, which matched more nodes than expected.

Is this a bug? Or am I just missing something about the Cypher's syntax?

**Comment by hakami1024** [comment]
Neo4j version: 3.4.1
Operating system: Ubuntu 16.04
Connecting through [http://localhost:7474/browser/]
-- also `true`

**Comment by hakami1024** [comment]
```
RETURN
(
  (
    (
      7414 IN [7372, 7414]
    ) 
    AND 
    (
       67542.0 <= 64547.0
    )
  ) 
  OR 
  (
    (
      7414 IN [7371, 7368, 7413, 7410] 
    )
    AND 
    (
       67542.0 <= 4061660.0
    )
  )
),

(
  (
    7414 IN [7372, 7414]
  ) 
  AND 
  (
      67542.0 <= 64547.0
  )
),

(
  7414 IN [7371, 7368, 7413, 7410] 
)
AND 
(
  67542.0 <= 4061660.0
),

false OR false;
```
-- `true, false, false, false` on 3.4.7

And on v. 3.3.2 no problem.

**Comment by SaschaPeukert** [comment]
Hej @hakami1024 ,

Thanks for reporting this. We will take a look!

Cheers,
Sascha

Neo4j Cypher Team

**Comment by hdk** [comment]
even shorter (in 3.4.0 and 3.4.7):

return  ( ( "a" IN ["a", "b"] ) AND false ) OR ( **"X"** IN ["c", "d"] ) ;
=> false

return  ( ( "a" IN ["a", "b"] ) AND false ) OR ( **"a"** IN ["c", "d"] ) ;
=> true
