### ISSUE TITLE
Can't logon to cypher shell if the password contains special characters

### ISSUE THREAD

**Issue by smadurange** [neo4j/neo4j#12021]
I'm using Neo4j 3.4.5 Enterprise Edition. I have a user with a password that contains `!4`. When the user tries to logon to cypher shell with this password on a CentOS deployment, we get the error: `-bash: !4: event not found`. 

We tried typing the password surrounded by "", but we still get the same error.

**Comment by jexp** [comment]
Try single quotes

**Comment by smadurange** [comment]
@jexp Oops, single quotes work. Thanks.
