### ISSUE TITLE
neo4j-admin: ERROR! Neo4j cannot be started using java version 10.0.1.

### ISSUE THREAD

**Issue by jelinekb** [neo4j/neo4j#12023]
## Guidelines
- Neo4j version: neo4j-desktop-1.1.8-x86_64.AppImage
- Operating system: Ubuntu 18.04
- API/Driver: Bolt/Python Driver
- Issue:
Attempting to start neo4j-admin results in the following error message:
`ERROR! Neo4j cannot be started using java version 10.0.1. `

**Comment by eebus** [comment]
Hello @jelinekb 
We do not support java version 10. 
Please try with Java 8.
Here is the docs https://neo4j.com/docs/operations-manual/current/installation/requirements/
