### ISSUE TITLE
Feature Request:  Queue queries to execute in browser

### ISSUE THREAD

**Issue by mdfrenchman** [neo4j/neo4j#12020]
I have a dozen or so cypher statements I'd like to run (using the browser). Some of them lock nodes that other statements would want to add relationships and/or properties to, so I can't fire them all off at once.

It'd be really cool if there was a queue feature to add a bunch of statements and let it loop through them in sequence.

**Comment by oskarhane** [comment]
Hi,
in recent versions of Neo4j Browser you can toggle the settings option "Enable multi statement query editor" which does just what you're asking for.

Btw, neo4j-browser has it's own repository and issue tracker, please see https://github.com/neo4j/neo4j-browser for future issues / questions.
