### ISSUE TITLE
Help me! automatically generate graph

### ISSUE THREAD

**Issue by beeme0** [neo4j/neo4j#12026]
I have sample data 2 columns
![11](https://user-images.githubusercontent.com/42713474/44627597-36bccf00-a963-11e8-8ee0-dd305908fb8b.png)

I want build a graph similar this issue but I must create one by one line. Actually, I need automatically generate it because I have data more than 10K. I can't create one by one. 
![12](https://user-images.githubusercontent.com/42713474/44627605-5c49d880-a963-11e8-91e5-6f9f1a4aeeaa.png)

CREATE (aa:Person { name: "Associate_Justice_of_the_Supreme_Court_of_the_United_States" }),
(ab:Person { name: "Woodrow_Wilson" }),
(ac:Person { name: "Richard_Nixon" }),
(ad:Person { name: "John_Quincy_Adams" }),
(ae:Person { name: "George_H._W._Bush" }),
(af:Person { name: "Vice_President_of_the_United_States" }),
(ag:Person { name: "United_States_Congress" }),
(ah:Person { name: "General_counsel" }),
(ai:Person { name: "Barack_Obama" }),
(aj:Person { name: "Warren_G._Harding" }),
(ak:Person { name: "John_Adams" }),
(al:Person { name: "Chief_Information_Officer-GB" }),
(am:Person { name: "George_W._Bush" }),
(an:Person { name: "Franklin_D._Roosevelt" }),
(ao:Person { name: "Abraham_Lincoln" }),
(ap:Person { name: "Herbert_Hoover" }),
(aq:Person { name: "James_A._Garfield" }),
(au:Person { name: "William_Howard_Taft" }),
(ar:Person { name: "James_Buchanan" }),
(as:Person { name: "Ulysses_S._Grant" }),
(at:Person { name: "Bill_Clinton" }),
(auu:Person { name: "Harry_S._Truman" }),
(av:Person { name: "United_States_Secretary_of_the_Treasury" }),
(aw:Person { name: "James_K._Polk" }),
(ax:Person { name: "Chief_Financial_Officer-GB" }),
(ay:Person { name: "James_Monroe" }),
(az:Person { name: "James_Madison" }),
(azz:Person { name: "Dwight_D._Eisenhower" }),

(ab)-[:know]->(aa),
(ac)-[:know]->(aa),
(ad)-[:know]->(aa),
(ae)-[:know]->(aa),
(ag)-[:know]->(af),
(ai)-[:know]->(ah),
(aj)-[:know]->(aa),
(ak)-[:know]->(aa),
(al)-[:know]->(am),
(an)-[:know]->(aa),
(ao)-[:know]->(aa),
(ap)-[:know]->(aa),
(aq)-[:know]->(aa),
(au)-[:know]->(aa),
(ar)-[:know]->(aa),
(as)-[:know]->(aa),
(at)-[:know]->(aa),
(ai)-[:know]->(aa),
(ai)-[:know]->(av),
(aw)-[:know]->(aa),
(ai)-[:know]->(ax),
(ay)-[:know]->(aa),
(auu)-[:know]->(aa),
(az)-[:know]->(aa),
(aj)-[:know]->(au),
(azz)-[:know]->(aa)

Neo4j Community Edition Browser version 1.1.9
Windows10

**Comment by jexp** [comment]
Please ask these questions in https://community.neo4j.com/c/neo4j-graph-platform/import-export

GitHub issues are for reporting issues / bugs.
