### ISSUE TITLE
Typo in comment in store/counts/KeyFormat

### ISSUE THREAD

**Issue by testmkkm** [neo4j/neo4j#12034]
Please note typo in comment:
```
    /**
     * Key format:
     * <pre>
     *  0 1 2 3 4 5 6 7   8 9 A B C D E F
     * [t,0,0,0,i,i,i,i ; 0,0,0,0,0,0,0,k]
     *  t - index entry marker - "{@link #INDEX}"
     *  k - entry (sub)type - "{@link #INDEX_STATS}"
     *  i - index id
     * </pre>
     * For value format, see {@link org.neo4j.kernel.impl.store.counts.CountsUpdater#replaceIndexSample(long , long, long)}.
     */
    @Override
    public void visitIndexSample( long indexId, long unique, long size )
    {
        indexKey( INDEX_SAMPLE, indexId );
    }

```
should be replaced with

>     /**
>      * Key format:
>      * <pre>
>      *  0 1 2 3 4 5 6 7   8 9 A B C D E F
>      * [t,0,0,0,i,i,i,i ; 0,0,0,0,0,0,0,k]
>      *  t - index entry marker - "{@link #INDEX}"
>      *  k - entry (sub)type - "{@link #INDEX_SAMPLE}"
>      *  i - index id
>      * </pre>
>      * For value format, see {@link org.neo4j.kernel.impl.store.counts.CountsUpdater#replaceIndexSample(long , long, long)}.
>      */
>     @Override
>     public void visitIndexSample( long indexId, long unique, long size )
>     {
>         indexKey( INDEX_SAMPLE, indexId );
>     }

**Comment by andreikoval** [comment]
Fixed
