### ISSUE TITLE
How to Handle Mass Data Import Resulting in out of Memory?

### ISSUE THREAD

**Issue by yangop8** [neo4j/neo4j#12031]
We convert our RDF data set to Nodes and Relationships. And then we use `neo4j-import` to import this data set.
Since we have change the _JVM_size_ and _dbms.memory.heap.initial_size_ and _dbms.memory.heap.max_size_ in `neo4j.conf`, and the available resources output is shown below:

> Total machine memory: 125.52 GB
> Free machine memory: 122.06 GB
> Max heap memory: 26.67 GB
> Processors: 32
> Configured max memory: 85.86 GB

However, when it comes to _Relationship counts_, **import failed** because of the following Error:

> Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded

We know it's about Garbage Collection and Heap Memory, and we try our methods to overcome this error but failed. Also, when the import is running, the memory used is full all the time.

**So, how could we overcome this problem? Or neo4j with 128GB memory can't import so much a data set?**

**Comment by jexp** [comment]
What is the size of your dataset?

And do you just import RDF 1:1 into neo4j or do you transform it into a property-graph structure upfront?

Do you have duplicate nodes or non-existing relationships (i.e. where either start or end node is missing?)

Please share more details about the structure of the CSV files and the command you run for the import.

**Comment by yangop8** [comment]
@jexp 
The initial size of RDF dataset is 100 million triples, and about 14.66G.
We transform it into a property-graph structure, the entity size is 1G and the relationship size is 5.3G.

We create different IDs for different entities so there has no duplicate nodes. Since there are not many predicates, we simply assume all the nodes have all the properties. 

We show the head of entities and relationships as follow:

> 5212741,http://db.uwaterloo.ca/~galuc/wsdbm/AgeGroup0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
> 5212740,http://db.uwaterloo.ca/~galuc/wsdbm/AgeGroup1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
> 5212735,http://db.uwaterloo.ca/~galuc/wsdbm/AgeGroup2,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
> 5212736,http://db.uwaterloo.ca/~galuc/wsdbm/AgeGroup3,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
> 5212738,http://db.uwaterloo.ca/~galuc/wsdbm/AgeGroup4,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
> 5212733,http://db.uwaterloo.ca/~galuc/wsdbm/AgeGroup5,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
> 5212734,http://db.uwaterloo.ca/~galuc/wsdbm/AgeGroup6,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
> 5212737,http://db.uwaterloo.ca/~galuc/wsdbm/AgeGroup7,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
> 5212739,http://db.uwaterloo.ca/~galuc/wsdbm/AgeGroup8,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
> 5212431,http://db.uwaterloo.ca/~galuc/wsdbm/City0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

> 5212000,http://www.w3.org/1999/02/22-rdf-syntax-ns#type,5212001
> 5212002,http://www.w3.org/1999/02/22-rdf-syntax-ns#type,5212003
> 5212004,http://www.w3.org/1999/02/22-rdf-syntax-ns#type,5212005
> 5212006,http://www.w3.org/1999/02/22-rdf-syntax-ns#type,5212007
> 5212008,http://www.w3.org/1999/02/22-rdf-syntax-ns#type,5212009
> 5212010,http://www.w3.org/1999/02/22-rdf-syntax-ns#type,5212011
> 5212012,http://www.w3.org/1999/02/22-rdf-syntax-ns#type,5212013
> 5212014,http://www.w3.org/1999/02/22-rdf-syntax-ns#type,5212007
> 5212015,http://www.w3.org/1999/02/22-rdf-syntax-ns#type,5212016

Finally, we use the following command to run the import:
`/usr/bin/neo4j-import --into graph.db --nodes /home/yanglei/watdiv_100M/entityHead_100M.csv,/home/yanglei/watdiv_100M/entity_100M.csv --relationships /home/yanglei/watdiv_100M/relation_100M.csv`

We hope these details could help you to find the problems for us.
Thanks!

Best Wishes!

**Comment by tinwelint** [comment]
OK so interestingly it's during the Relationship count phase... could you share the entire stack trace? Also do you have lots of relationship types and different labels?

**Comment by yangop8** [comment]
@tinwelint 
I only saved this picture as below, the Relationship count phase has not finished:
![wechatimg139](https://user-images.githubusercontent.com/23276343/45101423-0264c200-b15e-11e8-96ef-c88cdb08feda.png)
Since our dataset is transformed from RDF, and the relationship types are only part of predicates, so it couldn't be so many. Maybe the labels are too much I think.
Another thing I need to say is that, when the RDF dataset is 10M triples, it works. But when it comes to 100M, it fails.

**Comment by tinwelint** [comment]
Thanks. You do have a lot of memory, so it should not be a problem regardless, unless you have millions of different label names and thousands of different relationship type ids. What's the neo4j version you're running?

**Comment by yangop8** [comment]
@tinwelint 
The neo4j version I running is _3.3.4_.
And I have counted the number of different label names and relationship types.
There are _**5212385**_ different label names and less than _**86**_ different relationship types( because I counted all the RDF predicates and  `the number of predicates = the number of properties + the number of relationships`).

Best Wishes!

**Comment by jexp** [comment]
You said you created a proper property graph model?
From what you're describing it doesn't look like that?

Normally domains have a few hundred or at most a thousand entity types.
Neo4j supports multi-labels so you don't have to combine them into cross-product-labels.

**Comment by yangop8** [comment]
@jexp 
Thanks. I know what you mean. Maybe what we created is not a totally proper property graph model, but there are two reasons for what we must do so:
First, since we need to transform RDF dataset to property-graph structure, we couldn't exactly distribute different labels because its huge cost of time.
Second, what we want to do is to compare neo4j and some other RDF-based graph database. So unless we transform dataset like this, we couldn't find the equivalence between SPARQL and Cypher(We also need to transform the benchmark query from SPARQL to Cypher).
Meanwhile,  when the RDF dataset is 10M triples, it works. But when it comes to 100M, it fails.
**So, I wanna to know whether we can successfully import 100M-triples dataset like what we create or not?** If not, I think I need to transform dataset like what you said and then figure out how to find the equivalence between SPARQL and Cypher.

Best Wishes!

**Comment by tinwelint** [comment]
OK so with that many labels it's possible to get that OOM since each thread doing this calculation will have allocated memory for all labels and relationships, and combinations thereof. The importer (the counting stage) could check this and limit number of threads doing the counting if there isn't enough memory. It allocates one thread per available processor (including hyper threading).

**Comment by jbarrasa** [comment]
Hi @yangop8, from your statement "There are 5212385 different label names" I understand you mean your data set has 5212385 different objects in triples of this type:
`<instance_uri> rdf:type <class_uri>` 
Is this correct? 

I also understand that you're modelling each different type as a label in Neo4j, right? Basically, you're converting triples of the form `<instance_uri> rdf:type <class_uri>` into nodes with a label
 `(:<class_uri> { uri: <instance_uri>} )` (or something similar)

In this situation, having so many labels is not very useful. Based on the numbers you've shared I guess most of your labels (if not all) apply to a single node which completely defeats the purpose of a label in a Property Graph. 
My recommendation would be to model it in a different way. I would create a class node and link the instance node with a 'rdf_type' relationship to the class. Something like this:
`( { uri: <instance_uri>} )-[:RDF_TYPE]->(:Class { uri: <class_uri> })`.

There are other considerations when migrating from RDF to LPG but for now this should solve your data load.

I hope this helps.


JB.

**Comment by yangop8** [comment]
@jbarrasa 
Thank you very much for suggesting. I will have a try. Because what we want to do is to compare neo4j and some other RDF-based graph database, we need to find the equivalence between SPARQL and Cypher. Hence, I don't know whether it works, but I will try it.
Thanks again.

**Comment by tinwelint** [comment]
@yangop8 I want you to try running this import with `--processors=16` or 8.

This is of course while waiting for the real fix, but I don't know when that could make it in.

**Comment by jbarrasa** [comment]
@yangop8 

While they both use the graph as their underlying abstraction, the RDF model and the Property Graph model are **very different**. Similarly, RDF DBs (triple stores) and Native Graph DBs like Neo4j are **hugely different** in the way they store, query and manipulate data. 

https://www.youtube.com/watch?v=OVweE--RJqM
http://bit.ly/howSemanticIsYourGraph

I am a bit skeptical when people try to compare "equivalence" between the two, both at the model and at the storage levels. There will be some inevitable modeling choices but in my opinion, to provide a valid comparison you have to use data stores the way they are intended to be used. 

I'll try to explain with an example: Let's say you're trying to do the same exercise and compare the advantages/disadvantages of storing RDF data both in a triple store and in a relational DB. In order to do that, taking your example data set, you could create 5Million+ tables (one per class) each one containing a single record. Why not?  You would get 'interesting' results from the experience, but would it really make any sense?

I'd like to know your thoughts on this.

**Comment by yangop8** [comment]
@tinwelint I will have a try, thank you.

**Comment by yangop8** [comment]
@jbarrasa 
Hey, JB. I have tried your method, it really works in importing dataset. But it remove the property **TYPE** to filter the result, and make the query very slow beyond imagination. I will try what @tinwelint said to do the experiment. 
As to my thoughts on the comparison, I also think it pointless. Since the RDF model and the Property Graph model have different storages, different data structures, different indexs and so on, we don't need to really find which one is better.
However, neo4j maybe the benchmark of graph database. So if you create a new graph database, whether RDF-based or Property Graph-based, using up-to-date algorithm or index, you will be willing to compare the advantages/disadvantages with neo4j.
By the way, the finest thing is to enjoy the process. As to whether the result is what you imagine, who cares. Above all is what I want to say.
Best Wishes!

**Comment by jbarrasa** [comment]
@yangop8 
If you used my recommendation on modeling: 
`( { uri: <instance_uri>} )-[:RDF_TYPE]->(:Class { uri: <class_uri> })` 
All you need to do is create an index on the uri property on classes. Something like this:
`CREATE INDEX ON :Class(uri)` (adapt to your specific model)
Then query like the following should be super fast
`MATCH (:Class { uri : <your_class>})<-[:RDF_TYPE]-(x) RETURN x`

I'm asuming what you're trying to simulate is 'get all instances of a particular type' as in this sparql query: 

`SELECT x
WHERE {
x rdf:type <your_class>
}`

**Comment by tinwelint** [comment]
@yangop8 Does your project hinge on neo4j version 3.3.x specifically, or would it be allright to have fixed in 3.4.x and your moving to that version instead? The importer has had a couple of improvements in 3.4 compared to 3.3 already, so it should be better all around. Although I suspect that this specific problem should still be a problem in 3.4 though.

**Comment by yangop8** [comment]
@tinwelint Thank you for still remembering my problem. I will try it on version 3.4. I have tried your approach by limiting the processors, but it also not worked. Also, I change the **Label** column to property, it only just set a trade-off between _import time delay_ and _query time delay_. So I will find out another effective way to solve this problem.
Thanks again for giving me a possible solution.
Best Wishs!
