### ISSUE TITLE
Neo4j Desktop APOC Plugin Card Warning Applying to Remote Graphs

### ISSUE THREAD

**Issue by MichaelRBlack** [neo4j/neo4j#12039]
## Summary

In the desktop, there's a card for the plugins that are installed. The APOC card is displaying a warning that it is not installed on all graphs in my project. My project has a remote graph defined. My remote graph does have APOC installed but I wouldn't expect Neo4j Desktop to know about remote graphs, but at the same time the APOC card shouldn't show a warning about a remote graph that it can't analyze. 

**Neo4j Desktop Version:** 1.1.10
**Operating System:** Windows 10

### Steps to reproduce
1. Install the APOC plugin in Neo4j Desktop
2. Create a connection to a remote graph

### Expected behavior
No APOC installation status for remote graph connections

### Actual behavior
A yellow warning on the APOC plugin card

**Comment by oskarhane** [comment]
Thanks for reporting this issue @MichaelRBlack. 
It does sound like we could handle the that in a better way not to confuse or worry users.

We have a [neo4j-desktop](https://github.com/neo4j-apps/neo4j-desktop) repo to capture issues. Would you mind creating a new issue [over there](https://github.com/neo4j-apps/neo4j-desktop/issues) instead?
