### ISSUE TITLE
The type is a point query error

### ISSUE THREAD

**Issue by bingo919** [neo4j/neo4j#12036]
hi 
 neo4j version 3.4.0
The gps node contains three attributes:
   coordinates: point
   location: string
   type: string
eg:
coordinates: point({srid:4326, x:30.655691, y:104.081602}) ,location: shanghai ,type: gps

I encountered an error while querying:
curl http://IP:PORT/db/data/transaction/commit -u xxxx:xxxx -H  "Content-Type: application/json" 
  -d "{
	"statements": [{
		"statement": "match (n:gps) return n",
		"parameters": {},
		"includeStats": true,
		"resultDataContents": ["rest"]
	}]
}
"
Error is as follows：
"code": "Neo.TransientError.Network.CommunicationError",
"message": "Current context not an ARRAY but OBJECT",
"stackTrace": "org.codehaus.jackson.JsonGenerationException: Current context not an ARRAY but OBJECT

But the following procedure was successful

curl http://IP:PORT/db/data/transaction/commit -u xxxx:xxxx -H  "Content-Type: application/json" 
  -d "{
	"statements": [{
		"statement": "match (n:gps) return n.coordinates,n.type,n.loacation",
		"parameters": {},
		"includeStats": true,
		"resultDataContents": ["rest"]
	}]
}
"

**Comment by SaschaPeukert** [comment]
Hej @bingo919 ,

Thanks for reporting this. We will have a look at it!

Cheers,
Sascha

Neo4j Cypher Team

**Comment by pontusmelke** [comment]
Hi @bingo919 
I am looking at your issue. I am not able to reproduce the issue with a node with `coordinates: point({srid:4326, x:30.655691, y:104.081602})`, however with `coordinates: [point({srid:4326, x:30.655691, y:104.081602})] - i.e. an array of points rather than a single point - I seem to be getting the same error. Can you verify if this is what you have as well?

Best Regards,
Pontus

**Comment by bingo919** [comment]
HI @pontusmelke 
When I use arrays, I still report the same error.

eg:
`CREATE (g:gps{type:"gps",location:"shanghai", coordinates:[point({srid:4326, x:30.655691, y:104.081602})] });`

```
 curl http://IP:PORT/db/data/transaction/commit -u xxxx:xxxx -H "Content-Type: application/json"
-d "{
"statements": [{
"statement": "match (n:gps) return n",
"parameters": {},
"includeStats": true,
"resultDataContents": ["rest"]
}]
}
"
```

Error is as follows：
"code": "Neo.TransientError.Network.CommunicationError",
"message": "Current context not an ARRAY but OBJECT",
"stackTrace": "org.codehaus.jackson.JsonGenerationException: Current context not an ARRAY but OBJECT

**Comment by pontusmelke** [comment]
Yes I am able to reproduce the error when using arrays, however when not using arrays it works as expected. Are you sure you see the error also for single points? e.g. does this scenario fail for you?

```
CREATE (g:gps{type:"gps",location:"shanghai", coordinates:point({srid:4326, x:30.655691, y:104.081602}) });
```

```
curl http://IP:PORT/db/data/transaction/commit -u xxxx:xxxx -H "Content-Type: application/json"
-d "{
"statements": [{
"statement": "match (n:gps) return n",
"parameters": {},
"includeStats": true,
"resultDataContents": ["rest"]
}]
}
"
```
?

**Comment by bingo919** [comment]
yes 

cypher must 
`match (n:gps) return n ` 

**This error is only reported when "n" is returned.**

if return  n.coordinates it ok!!!!

Is your environment the same as mine?

neo4j version 3.4.0 
linux os

**Comment by pontusmelke** [comment]
Yes I see the exact same thing - i.e. with `RETURN n` you get an error but `RETURN n.coordinates` works fine. I have found the error and have a fix for it. However the problem only manifests when you have arrays of points. Could it be that you have some nodes with arrays of points and some with single points, in that way the query `match (n:gps) return n` will hit on some nodes with a point array?

If you could test doing:

```
CREATE (:NEW_LABEL{coordinates:point({srid:4326, x:30.655691, y:104.081602}) });
```

```
curl http://IP:PORT/db/data/transaction/commit -u xxxx:xxxx -H "Content-Type: application/json"
-d "{
"statements": [{
"statement": "match (n:NEW_LABEL) return n",
"parameters": {},
"includeStats": true,
"resultDataContents": ["rest"]
}]
}
```

BTW, thanks for reporting this :)

**Comment by bingo919** [comment]
Thank you for reminding me. @pontusmelke 

I did it according to the above. It is also wrong.

neo4j> CREATE (:NEW_LABEL{coordinates:point({srid:4326, x:30.655691, y:104.081602}) });
0 rows available after 9 ms, consumed after another 0 ms
Added 1 nodes, Set 1 properties, Added 1 labels
neo4j> match(n:NEW_LABEL) return n;
+---------------------------------------------------------------------------+
| n                                                                         |
+---------------------------------------------------------------------------+
| (:NEW_LABEL {coordinates: point({srid:4326, x:30.655691, y:104.081602})}) |
+---------------------------------------------------------------------------+

1 row available after 4 ms, consumed after another 1 ms
neo4j> :exit


curl http://IP:PORT/db/data/transaction/commit -u username:passwd -H "Content-Type: application/json"  -d "{\"statements\":[{\"statement\":\"match (**n:NEW_LABEL**) **return n** \",\"parameters\":{},\"includeStats\":true,\"resultDataContents\":[\"rest\"]}]}"
{"results":[{"columns":["n"],"data":[{"rest":[{"metadata":{"id":3636999,"labels":,"errors":[{"code":"Neo.TransientError.Network.CommunicationError","message":"**Current context not an ARRAY but OBJECT"**,"stackTrace":"org.codehaus.jackson.JsonGenerationException: Current context not an ARRAY but OBJECT\n\tat org.codehaus.jackson.impl.JsonGeneratorBase._reportError(JsonGeneratorBase.java:480)\n\tat org.codehaus.jackson.impl.Utf8Generator.writeEndArray(Utf8Generator.java:354)\n\tat org.neo4j.server.rest.transactional.ExecutionResultSerializer.writeRows(ExecutionResultSerializer.java:465)\n\tat org.neo4j.server.rest.transactional.ExecutionResultSerializer.statementResult(ExecutionResultSerializer.java:113)\n\

**Comment by pontusmelke** [comment]
Weird.

Thanks I have fixed the issue of arrays but I am not seeing that same error, but I'll continue to investigate.

Thanks for helping out!

**Comment by bingo919** [comment]
@pontusmelke  I remember it.

"resultDataContents": ["rest"]
resultDataContents must be "rest" ,
When it is "row" or "graph", it will not be wrong.

**Comment by pontusmelke** [comment]
I see it now. It happens when you use `"resultDataContents": ["rest"]`.

Thanks!
