### ISSUE TITLE
Subgraph Isomorphism Feature

### ISSUE THREAD

**Issue by hoptical** [neo4j/neo4j#12048]
Hi,
Is there any plan for adding subgraph isomorphism and graph matching features in the Neo4j?
Thanks.

**Comment by SaschaPeukert** [comment]
Hej @hoptical,

Thanks for your feature request. We are most interested in both and will consider them for future development.

Best regards Sascha, 
Neo4j Cypher team

**Comment by hoptical** [comment]
Hey @SaschaPeukert 

Thanks for your answer.
