### ISSUE TITLE
Cant seem to get high-io to read True when using the Neo4j Admin import

### ISSUE THREAD

**Issue by bsquire0128** [neo4j/neo4j#12043]
Cant seem to get high-io to read True when using the Neo4j Admin import. Here is my bash cmd:

~/../../../usr/bin/neo4j-admin import --nodes "import/uids-header.csv,import/uid_no." --nodes "import/identitylink-header.csv,import/idlink_no." --nodes "import/bluekai-header.csv,import/bk_no." --nodes "import/acxiom-header.csv,import/axm_no." --nodes "import/adobe-header.csv,import/adb_no." --nodes "import/lr-header.csv,import/lr_no." --nodes "import/viant-header.csv,import/vnt_no." --nodes "import/ga-header.csv,import/ggl_no." --nodes "import/segment-header.csv,import/seg_no." --nodes "import/email-header.csv,import/email_no." --relationships:RELATED_TO "import/rels-header.csv,import/idlink_li.,import/bk_li.,import/axm_li.,import/adb_li.,import/lr_li.,import/vnt_li.,import/ggl_li.,import/seg_li.,import/email_li.*" --high-io=true --ignore-duplicate-nodes=true --ignore-missing-nodes=true --delimiter="_" --max-memory=95%

This is read out of Available resources:
Total machine memory: 240.09 GB
Free machine memory: 238.17 GB
Max heap memory : 26.67 GB
Processors: 32
Configured max memory: 192.08 GB
High-IO: false

I am on a AWS EC2 with IOS SSD EBS storage with 8000 IOPS which I figured would help speed up my import and transaction/query speed when I scale to a multi-TB dataset.

Expected behavior: High-IO : True
Resulting behavior: High-IO : false

**Comment by tinwelint** [comment]
Which Neo4j version is this on?

**Comment by bsquire0128** [comment]
Version: | 3.4.0

**Comment by bsquire0128** [comment]
Ec2 info: r4.8xlarge 2TB EBS with 8000 IOPS

Ubuntu 16.04 LTS
Linux 4.4.0-127-generic #153-Ubuntu x86_64 x86_64 x86_64 GNU/Linux

**Comment by chrisvest** [comment]
@bsquire0128 does it work if you use lower-case `true`? The argument value matching might be too strict.

**Comment by chrisvest** [comment]
This is fixed in more recent versions of 3.4. I tried it on a 3.4.4 I had lying around, and it did not have this problem, so you just need to upgrade.

**Comment by bsquire0128** [comment]
I tried using 3.4.9 and confirmed high-io = true works. 3.4.0 must not be able to do high-io import
