### ISSUE TITLE
The database is not cleanly shutdown. The database needs recovery, in order to recover the database, please run the old version of the database on this store.

### ISSUE THREAD

**Issue by rmgpinto** [neo4j/neo4j#12045]
I'm having a problem restoring a backup from neo4j 3.1.3 database into a fresh 3.4.7 causal clustering.

- Neo4j version: 3.4.7
- Operating system: Amazon Linux AMI 2018.03
- API/Driver: N/A

##Steps to reproduce
1. Backup 3.1.3 database:
```
neo4j-admin backup \
    --backup-dir=. \
    --name=2018-10-03 \
    --from=<IP_ADDRESS> \
    --fallback-to-full=true \
    --check-consistency=true

```
2. Restore backup on 3.4.7 database:
```
neo4j-admin restore --from=/neo4j/backups/2018-10-03 --database=graph.db --force
```
3. neo4j.conf has:
```
dbms.allow_upgrade=true
```

I get the following error:

"The database is not cleanly shutdown. The database needs recovery, in order to recover the database, please run the old version of the database on this store."

**Comment by chrisvest** [comment]
It's annoying, but this can happen if the last backup was incremental. To fix it you have to first start the database up on 3.1.3, wait for it to complete recovery, and shut it down again. Then try starting it on 3.4.7 again.

**Comment by rmgpinto** [comment]
I did a full backup, I'm going to try starting the database in 3.1.3 and then upgrading it.
Thanks

**Comment by rmgpinto** [comment]
I have restored a backup from a 3.1.3 version in a single neo4j 3.4.7 instance successfully.

My problem is restoring in a causal cluster, I have 3 nodes, perform a restore on all 3 before starting neo4j. And after I start neo4j I have the error: "The database is not cleanly shutdown. The database needs recovery, in order to recover the database, please run the old version of the database on this store." on the LEADER node.

**Comment by martinfurmanski** [comment]
@rmgpinto Please follow the advice and "run the old version of the database on this store" (standalone instance) before you proceed with seeding a cluster.
