### ISSUE TITLE
LOAD CSV error when checking property keys

### ISSUE THREAD

**Issue by tomasonjo** [neo4j/neo4j#12044]
I discovered the bug when I wanted to check the property keys of a csv to help me import all the relevant data. I tried it on a clean Neo4j to validate and the same problem persists. I also tried on a different CSV and it worked fine so it must be something do to with the specific csv file and specific query, because other queries work. 

**Neo4j Version:** 3.4.7 Community edition   
**Operating System:** Ubuntu 16.04  
**API:** Community Server

### Steps to reproduce
1. Download the Neo4j 3.4.7 community edition
2. Download the data at https://www.kaggle.com/datafiniti/electronic-products-prices
3. Start Neo4j
4. Run query:
```
LOAD CSV WITH HEADERS FROM "file:///DatafinitiElectronicsProductsPricingData.csv" as row
RETURN keys(row) limit 1
```
### Expected behavior
It should return an array of property keys

### Actual behavior
error

> Neo.DatabaseError.General.UnknownError

**Comment by SaschaPeukert** [comment]
Hej @tomasonjo,

Thanks for reporting this. We will take a look at it.

Cheers,
Sascha

**Comment by pontusmelke** [comment]
Hi @tomasonjo 
Thanks for reporting this. I have fix for the issue, however just FYI the header of the file you are using ends with five consecutive `,` - which will be interpreted as `null` for the header name. Not sure if that is intentional?
