### ISSUE TITLE
Neo4j - Too Many Open files! Sudden Death!

### ISSUE THREAD

**Issue by ranlandau** [neo4j/neo4j#12050]
## Guidelines

- Neo4j version: 3.4.1
- Operating system: Ubuntu 18.04
- API/Driver: None
- **Steps to reproduce**
Failed to Start

Following Error:

> ct 09 13:47:11 ip-10-1-32-39 neo4j[1252]: 2018-10-09 13:47:11.058+0000 INFO  ======== Neo4j 3.4.1 ========
Oct 09 13:47:11 ip-10-1-32-39 neo4j[1252]: 2018-10-09 13:47:11.123+0000 INFO  Starting...
Oct 09 13:47:12 ip-10-1-32-39 neo4j[1252]: 2018-10-09 13:47:12.416+0000 INFO  Initiating metrics...
Oct 09 13:48:14 ip-10-1-32-39 neo4j[1252]: 2018-10-09 13:48:14.416+0000 INFO  Sending metrics to CSV file at /var/lib/neo4j/metrics
Oct 09 13:48:39 ip-10-1-32-39 neo4j[1252]: 2018-10-09 13:48:39.991+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@7731431f' was
successfully initialized, but failed to start. Please see the attached cause exception "eventfd() failed: Too many open files". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleMana
gingDatabase@7731431f' was successfully initialized, but failed to start. Please see the attached cause exception "eventfd() failed: Too many open files".
Oct 09 13:48:39 ip-10-1-32-39 neo4j[1252]: org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@7731431f' was successfully init
ialized, but failed to start. Please see the attached cause exception "eventfd() failed: Too many open files".
Oct 09 13:48:39 ip-10-1-32-39 neo4j[1252]:         at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
Oct 09 13:48:39 ip-10-1-32-39 neo4j[1252]:         at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:220)
Oct 09 13:48:39 ip-10-1-32-39 neo4j[1252]:         at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
Oct 09 13:48:39 ip-10-1-32-39 neo4j[1252]:         at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
Oct 09 13:48:39 ip-10-1-32-39 neo4j[1252]:         at com.neo4j.server.enterprise.CommercialEntryPoint.main(CommercialEntryPoint.java:22)
Oct 09 13:48:39 ip-10-1-32-39 neo4j[1252]: Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@7731431f' was successfully initialize
d, but failed to start. Please see the attached cause exception "eventfd() failed: Too many open files".
Oct 09 13:48:39 ip-10-1-32-39 neo4j[1252]:         at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
Oct 09 13:48:39 ip-10-1-32-39 neo4j[1252]:         at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
Oct 09 13:48:39 ip-10-1-32-39 neo4j[1252]:         at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:212)
Oct 09 13:48:39 ip-10-1-32-39 neo4j[1252]:         ... 3 more
Oct 09 13:48:39 ip-10-1-32-39 neo4j[1252]: Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /var/lib/neo4j/data/databases/graph.db
Oct 09 13:48:39 ip-10-1-32-39 neo4j[1252]:         at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:212)
Oct 09 13:48:39 ip-10-1-32-39 neo4j[1252]:         at org.neo4j.kernel.enterprise.EnterpriseGraphDatabase.<init>(EnterpriseGraphDatabase.java:39)
Oct 09 13:48:39 ip-10-1-32-39 neo4j[1252]:         at org.neo4j.server.enterprise.OpenEnterpriseNeoServer.lambda$static$1(OpenEnterpriseNeoServer.java:78)
Oct 09 13:48:39 ip-10-1-32-39 neo4j[1252]:         at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:88)
Oct 09 13:48:39 ip-10-1-32-39 neo4j[1252]:         at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
Oct 09 13:48:39 ip-10-1-32-39 neo4j[1252]:         ... 5 more
Oct 09 13:48:39 ip-10-1-32-39 neo4j[1252]: Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.bolt.transport.NettyServer@3716574a' was successfully initialized, but failed t
o start. Please see the attached cause exception "eventfd() failed: Too many open files".
Oct 09 13:48:39 ip-10-1-32-39 neo4j[1252]:         at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
Oct 09 13:48:39 ip-10-1-32-39 neo4j[1252]:         at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
Oct 09 13:48:40 ip-10-1-32-39 systemd[1]: neo4j.service: Main process exited, code=exited, status=1/FAILURE
Oct 09 13:48:40 ip-10-1-32-39 systemd[1]: neo4j.service: Unit entered failed state.
Oct 09 13:48:40 ip-10-1-32-39 systemd[1]: neo4j.service: Failed with result 'exit-code'.
Oct 09 13:48:40 ip-10-1-32-39 systemd[1]: neo4j.service: Service hold-off time over, scheduling restart.
Oct 09 13:48:40 ip-10-1-32-39 systemd[1]: Stopped Neo4j Graph Database.
Oct 09 13:48:40 ip-10-1-32-39 systemd[1]: Started Neo4j Graph Database.
Oct 09 13:48:40 ip-10-1-32-39 neo4j[2016]: Active database: graph.db
Oct 09 13:48:40 ip-10-1-32-39 neo4j[2016]: Directories in use:
Oct 09 13:48:40 ip-10-1-32-39 neo4j[2016]:   home:         /var/lib/neo4j
Oct 09 13:48:40 ip-10-1-32-39 neo4j[2016]:   config:       /etc/neo4j
Oct 09 13:48:40 ip-10-1-32-39 neo4j[2016]:   logs:         /var/log/neo4j
Oct 09 13:48:40 ip-10-1-32-39 neo4j[2016]:   plugins:      /var/lib/neo4j/plugins
Oct 09 13:48:40 ip-10-1-32-39 neo4j[2016]:   import:       /var/lib/neo4j/import
Oct 09 13:48:40 ip-10-1-32-39 neo4j[2016]:   data:         /var/lib/neo4j/data
Oct 09 13:48:40 ip-10-1-32-39 neo4j[2016]:   certificates: /var/lib/neo4j/certificates
Oct 09 13:48:40 ip-10-1-32-39 neo4j[2016]:   run:          /var/run/neo4j
Oct 09 13:48:40 ip-10-1-32-39 neo4j[2016]: Starting Neo4j.

**Comment by maxlever** [comment]
have you tried increasing your open files limit?
https://neo4j.com/docs/operations-manual/current/installation/linux/tarball/#linux-open-files
(change the two lines in step 2 to start with your username)

**Comment by MishaDemianenko** [comment]
Hi @ranlandau, please try to increase your system open file limit, as recommended above. I will close the issue but please feel free to reopen it in case problem persist after settings update.

**Comment by harshayalburgi** [comment]
The  lsof | grep -i lucene | wc -l
249120
in RHEL 7.2 and neo4j 3.4.1

Even after restart - its same in numbers

**Comment by chrisvest** [comment]
@harshayalburgi Try upgrading to 3.4.12: https://github.com/neo4j/neo4j/wiki/Neo4j-3.4-changelog#3412
