### ISSUE TITLE
Document behaviour for repeated keys in neo4j.conf

### ISSUE THREAD

**Issue by frant-hartm** [neo4j/neo4j#12056]
It seems that when there is the same property key repeated multiple times in neo4j.conf, it uses the last value of the property.

I could not find anywhere in the documentation that this is the behaviour, but it seems to come from this impl of the config loader: https://github.com/neo4j/neo4j/blob/3.4.7/community/kernel/src/main/java/org/neo4j/kernel/configuration/Config.java#L375

This behaviour simplifies some of our deployment scripts. It would be great to have it clarified in the documentation somewhere. E.g. here https://neo4j.com/docs/operations-manual/current/reference/configuration-settings/

**Comment by chrisvest** [comment]
> It seems that when there is the same property key repeated multiple times in neo4j.conf, it uses the last value of the property.

This is unfortunately not supported behaviour. You cannot rely on it.

We will update the documentation to say so.
