### ISSUE TITLE
Setting cypher.lenient_create_relationship doesn`t work

### ISSUE THREAD

**Issue by GreenGood** [neo4j/neo4j#12059]
It seems that setting `cypher.lenient_create_relationship=true` doesn't work. After restart server i still receive errors
`org.neo4j.kernel.impl.query.QueryExecutionKernelException: Failed to create relationship '  UNNAMED102', node 'm' is missing. If you prefer to simply ignore rows where a relationship node is missing, set 'cypher.lenient_create_relationship = true' in neo4j.conf`

My statement:
`merge (n:Node {Ogrn: "4"})
with n optional match (m:Node { Ogrn: "4"}) where id(n) <> id(m) merge (n)-[:HasSameOgrn]->(m)`

**Neo4j Version:** 3.4.9 community edition  
**Operating System:** Windows 10  
**API:** Cypher

### Steps to reproduce
1. Set `cypher.lenient_create_relationship=true`
2. Stop server
3. Create new database
4. Start server
5. Open browser and execute statement

### Expected behavior
Statement executes without errors

### Actual behavior
Statetement executes with errors `
Failed to create relationship '  UNNAMED102', node 'm' is missing. If you prefer to simply ignore rows where a relationship node is missing, set 'cypher.lenient_create_relationship = true' in neo4j.conf`

Log file: 
[debug.zip](https://github.com/neo4j/neo4j/files/2510135/debug.zip)

Conf file:
[neo4j.zip](https://github.com/neo4j/neo4j/files/2510134/neo4j.zip)

**Comment by SaschaPeukert** [comment]
Hej @GreenGood ,

Thanks for reporting this. We will have a look at this problem.

Cheers,
Sascha 
Neo4j Cypher Team

**Comment by lavkan** [comment]
Hi,

I face the same issue with version 3.5. Is this issue being addressed?

**Comment by Hunterness** [comment]
Hi,

It should have been fixed in https://github.com/neo4j/neo4j/commit/418e0b5795a732eb4aede1769ff4f83b25df1222, so you might see a different error with the same behavior. 

Please open a new issue detailing your issue and setup and we will look into it again.

Cheers,
Therese
Neo4j Cypher Team

**Comment by waigitdas** [comment]
this is not fixed in v 4.1

from Putty to my Neo4j VM on Azure

dastumpf@neo4jVM:~$ neo4j status
/usr/share/neo4j/bin/neo4j: line 196: export: `cypher_lenient_create_relationship = true': not a valid identifier
