### ISSUE TITLE
Linkedin Oauth User Authentication did not work

### ISSUE THREAD

**Issue by kdwykleingeld** [neo4j/neo4j#12061]
During install of desktop 1.1.10 i noticed that the "linkedin" federated oauth authentication method did not work. Nothing happend and i only saw a blank screen. Using the GitHub based oauth method worked fine. Something to test maybe.

BTW.. the upgrade process to 3.4.9 resulted in teh fact that i could not start the database anymore and had to de-install the desktop and reinstall it after which i was able again restart my graph again. This only worked after i manually deleted several neo4j related (hidden) .desktop kind of folders. I suggest that the deinstall process will be extended to clean-up up everything 

Running on w7.

thanks koen

**Comment by oskarhane** [comment]
Hi and thanks for the report @kdwykleingeld!
Could you please open it in [the neo4j-desktop repo](https://github.com/neo4j-apps/neo4j-desktop) instead, since this is only for the database itself.

Thanks in advance.
