### ISSUE TITLE
neo4j-desktop segmentation fault when trying to start on Ubuntu 18.10

### ISSUE THREAD

**Issue by kaerumy** [neo4j/neo4j#12068]
- Neo4j version: neo4j-desktop-1.1.10-x86_64.AppImage
- Operating system: Ubuntu 18.10

Segmentation fault when trying to start
### Steps to reproduce

1. Start existing or newly downloaded App Image 

~/dev$ ./neo4j-desktop-1.1.10-x86_64.AppImage

### Expected behavior
neo4j Desktop starts and opens
### Actual behavior
Segmentation fault (core dumped)

**Comment by oskarhane** [comment]
Hi, thanks for the report @kaerumy. 
Could you please close this and open a new issue in the [Neo4j Desktop](https://github.com/neo4j-apps/neo4j-desktop) repo instead?

**Comment by kaerumy** [comment]
Filed issue in correct neo4j-desktop repo https://github.com/neo4j-apps/neo4j-desktop/issues/37
