### ISSUE TITLE
solr search engine with Neo4j

### ISSUE THREAD

**Issue by shenGrant** [neo4j/neo4j#12064]
## Guidelines

Hi,
I have an issue about if Neo4j can be integrated with solr. My purpose is to add personal recommendation using graph calculations in searching. Are there some solutions for me to implement?

thanks a lot.

- Neo4j version: 3.4.9
- Operating system: windows 7

**Comment by chrisvest** [comment]
In 3.4 you can use the (deprecated) explicit indexes to do fulltext search: https://neo4j.com/docs/developer-manual/current/cypher/schema/index/#explicit-indexes-procedures

In 3.5, there will be support for fulltext schema indexes: https://neo4j.com/docs/cypher-manual/3.5-preview/schema/index/#schema-index-fulltext

**Comment by chrisvest** [comment]
I assume that answered your question. If not, then feel free to reopen and provide more detail on what you have in mind.
