### ISSUE TITLE
load csv to update new data into neo4j,but the memory consuming is increasing all the time

### ISSUE THREAD

**Issue by Duanexiao** [neo4j/neo4j#12069]
where I use load csv to update new data into neo4j,the server memory consuming is increasing all the time.
At last,the server will left 3G (almost 1.2% ram) memory.Why? any methods to optimize it?
Another problem is that,When I apply the same cypher query,the returned results are all the same,while
the data should be different. Looking foraward your reply, thank you

**Comment by craigtaverner** [comment]
Please could you describe the problem in more detail. In particular we need to know the Cypher query you used to load the data, whether you used PERIODIC COMMIT or not and how large the CSV file is that you imported.

You have also reported a second issue with a second Cypher query. We also need to know what that query is in order to be able to provide any help.

**Comment by chrisvest** [comment]
Also, have you configured the page cache and heap memory sizes? If you haven't, then do that first: https://neo4j.com/docs/operations-manual/current/performance/memory-configuration/

**Comment by Duanexiao** [comment]
> Please could you describe the problem in more detail. In particular we need to know the Cypher query you used to load the data, whether you used PERIODIC COMMIT or not and how large the CSV file is that you imported.
> 
> You have also reported a second issue with a second Cypher query. We also need to know what that query is in order to be able to provide any help.

Hello,My Cypher command is below: USING PERIODIC COMMIT 1000 LOAD CSV WITH HEADERS FROM "file:///38640439_38644166_mid_neo4j_update_data.csv" as row merge (p:uidInfo {uid: row.uid}) merge (n:midInfo {mid:row.node_info}) merge (p)-[r:has]->(n)

**Comment by Duanexiao** [comment]
> Also, have you configured the page cache and heap memory sizes? If you haven't, then do that first: https://neo4j.com/docs/operations-manual/current/performance/memory-configuration/

Thank you,I had configured them.Using the recommend setting by "neo4j-admin memrec --database=graph.db"

**Comment by chrisvest** [comment]
What settings are `neo4j-admin memrec --database=graph.db` giving you? Also, you have 3 GiB of RAM, correct? And how big is your `graph.db` folder, excluding the transaction logs (the `transaction.db*` files)?

**Comment by Duanexiao** [comment]
> What settings are `neo4j-admin memrec --database=graph.db` giving you? Also, you have 3 GiB of RAM, correct? And how big is your `graph.db` folder, excluding the transaction logs (the `transaction.db*` files)?

The command tells me how to set the page cache size and initial and max heap memory size.My RAM is 256GB,graph.db folder excluding the transaction logs occupied 8GB

**Comment by Duanexiao** [comment]
> > What settings are `neo4j-admin memrec --database=graph.db` giving you? Also, you have 3 GiB of RAM, correct? And how big is your `graph.db` folder, excluding the transaction logs (the `transaction.db*` files)?
> 
> The command tells me how to set the page cache size and initial and max heap memory size.My RAM is 256GB,graph.db folder excluding the transaction logs occupied 8GB

belows are the recommend setting:

```
# Memory settings recommendation from neo4j-admin memrec:
#
# Assuming the system is dedicated to running Neo4j and has 258400m of memory,
# we recommend a heap size of around 31g, and a page cache of around 206300m,
# and that about 20400m is left for the operating system, and the native memory
# needed by Lucene and Netty.
#
# Tip: If the indexing storage use is high, e.g. there are many indexes or most
# data indexed, then it might advantageous to leave more memory for the
# operating system.
#
# Tip: The more concurrent transactions your workload has and the more updates
# they do, the more heap memory you will need. However, don't allocate more
# than 31g of heap, since this will disable pointer compression, also known as
# "compressed oops", in the JVM and make less effective use of the heap.
#
# Tip: Setting the initial and the max heap size to the same value means the
# JVM will never need to change the heap size. Changing the heap size otherwise
# involves a full GC, which is desirable to avoid.
#
# Based on the above, the following memory settings are recommended:
dbms.memory.heap.initial_size=31g
dbms.memory.heap.max_size=31g
dbms.memory.pagecache.size=206300m
#
# The numbers below have been derived based on your current data volume in database and index configuration of database 'graph.db'.
# They can be used as an input into more detailed memory analysis.
# Lucene indexes: 602.0
# Data volume and native indexes: 241600m
```

**Comment by chrisvest** [comment]
Memrec says your data volume is 253 GiB (241600m), not 8 GiB. It also says that it leaves around 20 GiBs for the OS and other stuff, but I guess this isn't enough. So you can just reduce the `dbms.memory.pagecache.size` (and maybe the heap size) a little to get more head room.

**Comment by Duanexiao** [comment]
> Memrec says your data volume is 253 GiB (241600m), not 8 GiB. It also says that it leaves around 20 GiBs for the OS and other stuff, but I guess this isn't enough. So you can just reduce the `dbms.memory.pagecache.size` (and maybe the heap size) a little to get more head room.

Sorry for mistaken copy.The dbms.memory.pagecache.size setting not used the recommended parameter,but 160GB,and that does not work.The recommended parameter also tried, also not work

**Comment by mnd999** [comment]
Will close this very old issue. If you are still having problems, please let us know.
