### ISSUE TITLE
Disabling authentication on monitoring endpoint for ha or causal mode failed

### ISSUE THREAD

**Issue by treilhes** [neo4j/neo4j#12060]
## bug report

Trying to monitor a causal cluster using ansible, i need to access monitoring endpoints without any authentication. Happy first to find it was a built-in feature then disapointed to find the configuration options were not effective

**Neo4j Version:** 3.4.6
**Operating System:** RedHat 7  
**API:** REST in browser

### Steps to reproduce
1. turn on security : dbms.security.auth_enabled=true
2. turn off security on ha endpoints : dbms.security.ha_status_auth_enabled=false
3. turn off security on causal endpoints : dbms.security.causal_clustering_status_auth_enabled=false

### Expected behavior
Access granted on http://ip:7474/db/manage/server/causalclustering/writable and return "true"
Access granted on http://ip:7474/db/manage/server/ha/master and http status 403

### Actual behavior
User/Password prompts

**Comment by RagnarW** [comment]
Closing due to unsupported version
