### ISSUE TITLE
Uniqueness: Relationships are filtered when cannot be the same

### ISSUE THREAD

**Issue by Izhaki** [neo4j/neo4j#12074]
This is not a bug per-se, but more of an optimisation issue.

- Neo4j version: 3.4.9
- Operating system: Mac
- API/Driver: Browser

**Steps to reproduce**
```
PROFILE MATCH (user:User { name: 'Adam' })-[r1:FRIEND]->()-[r2:FRIEND]->(friend_of_a_friend)
RETURN friend_of_a_friend.name AS fofName
```
**Expected behavior**

It should not add the filter operator `not r1 = r2` after the second `Expand(all)` operator - these two relationships are directional and not opposite and hence can never be the same.

It should only filter if:

- Direction is not specified for either relationships.
- Direction is specified for both, and these are opposite.

**Actual behavior**
It add the filter operator.

![plan](https://user-images.githubusercontent.com/880132/48266839-8a01d200-e428-11e8-8815-1fbd18f94e3c.png)

**Comment by craigtaverner** [comment]
Hi @Izhaki. Thanks for the suggestion. However, it does not work in all cases. That query could match self-relationships where 'Adam' is a friend of 'Adam'. Even if there is only one node in the graph, the pattern you described above would match if we did not filter for r1!=r2.

Cypher has what is called 'edge isomorphism' which means we do not allow the same relationship to exist in two places in the same pattern expression, so we have to filter for this even in your query where the directions almost seem to imply that r1 cannot be r2 (but can be for self-relationships).

**Comment by Izhaki** [comment]
OOOOOOH! I completely ignored relationship-to-self possibility.

Jolly brilliant this is!

Thanks so much for the reply and detailed explanation.

**Comment by craigtaverner** [comment]
Glad to help!
