### ISSUE TITLE
Improve error reporting in cypher queries for invalid syntax

### ISSUE THREAD

**Issue by macheeto** [neo4j/neo4j#12075]
For this query:
MATCH (person:Person{id:$personId})<-[:IS_GRANTED_TO]-(perm:Permission)-[:HAS_ACCESS_TO]->(item:DataItem)
OPTONAL MATCH (item)-[:IS_CHILD_OF]->(parent:DataItem{typeName:"Group"})
RETURN DISTINCT item, parent, perm

Neo4j console returns this error:
Neo.ClientError.Statement.SyntaxError: Query cannot conclude with MATCH (must be RETURN or an update clause) (line 1, column 1, (offset: 0)) "MATCH (person:Person ..."

The actual problem is that keyword OPTIONAL is not spelled right (OPTONAL, missing letter I).
Instead of reporting a simple syntax error on the next line Neo4j indicates a more complex error on the line before.

My request is to update error handling so it can indicate the actual problem.

Neo4j version is 3.4.4, community edition running on OSX.

**Comment by Hunterness** [comment]
Hi, you are in luck, this is already fixed. If you upgrade to 3.4.10 you will get the more relevant and correct error message.
