### ISSUE TITLE
Cannot choose path where I want to store application data in Windows 10

### ISSUE THREAD

**Issue by willvelida** [neo4j/neo4j#12073]
- Neo4j version: 3.0.0
- Operating system: Windows 10 Pro

- **Steps to reproduce**
1. Download Neo4j for Desktop from website
2. Install as admin
3. Open Neo4j for Desktop.

- Expected behavior - Neo4j for Desktop starts normally
- Actual behavior - I can pick a path to choose to store application data, but I cannot confirm as the confirm button doesn't work.

**Comment by chrisvest** [comment]
Sounds like you are using the old Neo4j Desktop application, that has a single embedded Neo4j instance. Upgrade to the new one, which is the main download on https://neo4j.com/download/

**Comment by HaigBernard** [comment]
closed but doesn't solve issue

**Comment by vairavan92** [comment]
the issue is that user has corrupted PATH env variable.
First, he needs to check if the wmic.exe is present in C:\windows\system32\wbem directory.
If true - add that path to env variable PATH.
If not - use system-wide search to find that executable. it should be somewhere inside Windows folder.

**Comment by jamesvrt** [comment]
I'm having the same problem using the installer I downloaded using @chrisvest's link (`neo4j-desktop-offline-1.2.7-setup.exe`). I am also on Windows 10 Pro.

@vairavan92's tip didn't resolve the issue. `wmic.exe` was already accessible via `PATH`.

**Comment by alexpghayes** [comment]
New user here. Ran into this with a fresh download and install today.

`WMIC.exe` is present in `C:\Windows\System32\wbem\` for me. Adding `C:\Windows\System32\wbem` to my PATH resolved my issue. I'm on Windows 8. I also upgraded to a recent version of Powershell along the way.

**Comment by imparassharma** [comment]
I am facing the same issue. I tried to update my PATH variable also but there is no WMIC.exe file present anywhere in my system..

**Comment by kostaskr13** [comment]
any solution?

**Comment by imparassharma** [comment]
> any solution?
> 

I think there is an online browser version where you can work on most of the things. You can check that. Find a tutorial how to setup that because I have forgot what were the steps for the online version exactly.
