### ISSUE TITLE
Unable to open Neo4j Browser on Fedora 29

### ISSUE THREAD

**Issue by andreylh** [neo4j/neo4j#12070]
I'm unable to open Neo4j Browser on Fedora 29. I installed following the instructions https://neo4j.com/docs/operations-manual/current/installation/linux/rpm/.

**Neo4j Version:** 3.4.9
**Neo4j Browser Version:** 1.1.12
**Operating System:** Fedora 29 (KDE spin)

Error:

neo4j-desktop killed by SIGSERV - abrt

--- Running report_uReport ---
Problem comes from unpackaged executable. Unable to create uReport.
('report_uReport' exited with 1)

**Comment by oskarhane** [comment]
Hi @andreylh, could you please open this issue over in the [Neo4j Desktop](https://github.com/neo4j-apps/neo4j-desktop) repo instead?
