### ISSUE TITLE
When attempting to run a merge with a null variable the runtime error will not identify the line where the problem lies.

### ISSUE THREAD

**Issue by pdrangeid** [neo4j/neo4j#12080]
I run a query attempting to perform a merge operation and the variable used is null or non-existent.  If It is a particularly long or complex CYPHER query the lack of a specific line number or example of the failing command makes it difficult to identify what part of the query is providing a null value (which may need a CASE/WHEN or a coalesce to remediate the issue

- Neo4j version: 3.4.7
- Operating system: Windows 10
- API/Driver: Cypher (Neo Browser)
- Attempt to perform a MERGE operation using a null value or non-existent variable
- Error message identifying the line and specific code that provided the null value
- Obscure runtime error: Neo.DatabaseError.Statement.ExecutionFailed: Expected to find a node at ref slot 9 but found instead: null

**Comment by fickludd** [comment]
Hi @pdrangeid, it would be very helpful if you could provide a small sample query + graph that exhibits this behavior, and maybe an example of the error-message that you would like to get. 

And a wild guess: are you aware that there is a config setting `cypher.lenient_create_relationship` that might be relevant to your problem? https://github.com/neo4j/neo4j/blob/3.5/community/kernel/src/main/java/org/neo4j/graphdb/factory/GraphDatabaseSettings.java#L236

**Comment by Hunterness** [comment]
Hi @pdrangeid, did @fickludd comment help to fix your problem?

**Comment by Lojjs** [comment]
@pdrangeid As this issue has been stale for years and we cannot proceed without the requested information, I will close it. Always feel free to open a new issue if needed.

Best regards Louise, Neo4j Cypher team
