### ISSUE TITLE
Delete node within a transaction is not atomic 

### ISSUE THREAD

**Issue by BalazsBago** [neo4j/neo4j#12082]
When I am accessing and reading the database from two separated processes sometimes the reader process does not find the requested nodes, however I refresh the database within a write transaction. 

### Environment:
- Neo4j version: neo4j-community-3.4.9 (docker image: neo4j:3.4.9)
- Operating system: Ubuntu 18.04
- API/Driver: python3.6, neo4j-driver 1.6.2

### Steps to reproduce
1. Start the container   
```bash
 docker run -d --name test_neo4j -p 7687:7687 -p 7474:7474 -e NEO4J_AUTH=none neo4j:3.4.9  
```
3. Start the first python3 script to refresh the database regularly
```python
from neo4j.v1 import GraphDatabase, WRITE_ACCESS

if __name__ == '__main__':

    driver = GraphDatabase.driver("bolt://localhost:7687")
    while True:
        with driver.session(WRITE_ACCESS) as session:
            tx = session.begin_transaction()
            tx.run("MATCH (n) DELETE n")
            for i in range(100):
                tx.run("CREATE (n:Number {value: $value}) return ID(n)", value=i).data()
            tx.commit()
  ```
3. Start the second python3 script to obtain data from the database regularly, content:  
```python
from neo4j.v1 import GraphDatabase, READ_ACCESS  
  
if __name__ == '__main__':  
    print("Missing nodes:")  
    driver = GraphDatabase.driver("bolt://localhost:7687")  
    while True:  
        with driver.session(READ_ACCESS) as session:  
            for i in range(100):  
                d = session.run("Match (n:Number) where n.value=$value return ID(n)", value=i).data()  
                if len(d) == 0:  
                    print(i)

```
###  Expected behaviour
The second script always finds the requested nodes.

### Actual behaviour
The second script does not find some nodes.

### Example output
Missing nodes:
20
92
29
90
5
6
82
50
51
24
3
4
75
76

**Comment by technige** [comment]
The behaviour demonstrated here is expected. The level of isolation observed is what is guaranteed in the absence of locking for read operations. This is not done by default in Cypher queries, which would require acquisition of read locks on every entity touched by a query.

To achieve this there are two commonly used remedies. One is to do a "dummy write" on every node used - like adding and removing, in the same query, a placeholder property that will guarantee a write lock will be grabbed. The other is to move operations that must have this visibility guarantee in a procedure and explicitly grab read locks on the entities through the Transaction object and then call that procedure remotely.

**Comment by zhenlineo** [comment]
Actually I am going to close this issue as there is no bug to fix for this particular case.
