### ISSUE TITLE
why interfaces/classes of two similar versions exist?

### ISSUE THREAD

**Issue by bluejoe2008** [neo4j/neo4j#12094]
I want to introduce new property types into neo4j in my application, when I write code to pack/unpack custom values via bolt messaging, I am confused to find there are always TWO versions of interfaces/classes exist in `neo4j-bolt` and `neo4j-java-driver` project.

for example, 
`neo4j-java-driver` defines an `org.neo4j.driver.internal.value.InternalValue`, while neo4j-bolt defines an `org.neo4j.driver.v1.Value`
`neo4j-java-driver` defines an `org.neo4j.driver.internal.packstream.PackStream.Unpacker`, while neo4j-bolt defines an  `org.neo4j.bolt.v1.messaging.Neo4jPackV1.UnpackerV1`

What is the difference and relationship between them? 
Why not using interfaces/classes of one version instead of two?

Should I write custom code of TWO versions in my project?

- Neo4j version: 3.4.0
- Neo4j-java-driver version: 1.6.0
- Operating system: MacOS 11

**Comment by technige** [comment]
Hi @bluejoe2008. The two sets of classes exist in the two separate projects: the server and the client. Each is optimised for use in that environment and the driver and server are managed, built and released on separate schedules.

Why are you trying to add new property types though? Adding types to the type system is an extremely complex piece of work and would generally require support through the entire stack. This is not something we would recommend or advise people to do. In terms of these API in particular, these are internal and not part of the documented public interface. While you _could_ use them, we can provide no guarantee of stability or support for you doing so.

**Comment by zhenlineo** [comment]
Closing this as it is not related to any bug report or feature request. If any further question, pls discuss in http://neo4j.com/slack for example.
