### ISSUE TITLE
neo4j-3.5 compilation failure  while running "mvn clean install -DskipTests"

### ISSUE THREAD

**Issue by GerJeffrey** [neo4j/neo4j#12092]
hi:
   My java version is  java_11 and maven version is 3.6.0, when I compile neo4j_3.5 with command "mvn clean install -DskipTests", and then I get a Compilation failure:
Compilation failure: 
[ERROR] /Users/lonthtech/neo4j-3.5/community/kernel/src/test/java/org/neo4j/test/rule/system/TestSecurityManager.java:[319,5] 方法不会覆盖或实现超类型的方法
[ERROR] /Users/lonthtech/neo4j-3.5/community/kernel/src/test/java/org/neo4j/test/rule/system/TestSecurityManager.java:[322,49] 找不到符号
[ERROR]   符号:   方法 checkTopLevelWindow(java.lang.Object)
[ERROR]   位置: 类型为java.lang.SecurityManager的变量 securityManager
[ERROR] /Users/lonthtech/neo4j-3.5/community/kernel/src/test/java/org/neo4j/test/rule/system/TestSecurityManager.java:[322,87] 找不到符号
[ERROR]   符号: 方法 checkTopLevelWindow(java.lang.Object)
[ERROR] /Users/lonthtech/neo4j-3.5/community/kernel/src/test/java/org/neo4j/test/rule/system/TestSecurityManager.java:[338,5] 方法不会覆盖或实现超类型的方法
[ERROR] /Users/lonthtech/neo4j-3.5/community/kernel/src/test/java/org/neo4j/test/rule/system/TestSecurityManager.java:[343,28] 找不到符号
[ERROR]   符号:   方法 checkSystemClipboardAccess()
[ERROR]   位置: 类型为java.lang.SecurityManager的变量 securityManager
[ERROR] /Users/lonthtech/neo4j-3.5/community/kernel/src/test/java/org/neo4j/test/rule/system/TestSecurityManager.java:[347,18] 找不到符号
[ERROR]   符号: 方法 checkSystemClipboardAccess()
[ERROR] /Users/lonthtech/neo4j-3.5/community/kernel/src/test/java/org/neo4j/test/rule/system/TestSecurityManager.java:[351,5] 方法不会覆盖或实现超类型的方法
[ERROR] /Users/lonthtech/neo4j-3.5/community/kernel/src/test/java/org/neo4j/test/rule/system/TestSecurityManager.java:[356,28] 找不到符号
[ERROR]   符号:   方法 checkAwtEventQueueAccess()
[ERROR]   位置: 类型为java.lang.SecurityManager的变量 securityManager
[ERROR] /Users/lonthtech/neo4j-3.5/community/kernel/src/test/java/org/neo4j/test/rule/system/TestSecurityManager.java:[360,18] 找不到符号
[ERROR]   符号: 方法 checkAwtEventQueueAccess()
[ERROR] /Users/lonthtech/neo4j-3.5/community/kernel/src/test/java/org/neo4j/test/rule/system/TestSecurityManager.java:[403,5] 方法不会覆盖或实现超类型的方法
[ERROR] /Users/lonthtech/neo4j-3.5/community/kernel/src/test/java/org/neo4j/test/rule/system/TestSecurityManager.java:[408,28] 找不到符号
[ERROR]   符号:   方法 checkMemberAccess(java.lang.Class<capture#1, 共 ?>,int)
[ERROR]   位置: 类型为java.lang.SecurityManager的变量 securityManager
[ERROR] /Users/lonthtech/neo4j-3.5/community/kernel/src/test/java/org/neo4j/test/rule/system/TestSecurityManager.java:[412,18] 找不到符号
[ERROR]   符号: 方法 checkMemberAccess(java.lang.Class<capture#2, 共 ?>,int)

How can I fix the problem? thx!

**Comment by GerJeffrey** [comment]
I think it's a compatibility problem, perhaps it's because that the java version is too high?  But I have already compiled my backend system with java 11. Please help me!

**Comment by chrisvest** [comment]
I'd recommend compiling Neo4j with Java 8, and then you can try running it on Java 11. You can also just get the pre-built jars from Maven or a Neo4j release download.

**Comment by MishaDemianenko** [comment]
@GerJeffrey neo4j can't be compiled with java 11 atm so please follow @chrisvest advise and compile it with java 8. Then you should be able to run it with Java 11 as your runtime environment without any problems.

**Comment by GerJeffrey** [comment]
I get it, TKS!
