### ISSUE TITLE
Inconsistent behavior of query planner with respect to indexed property

### ISSUE THREAD

**Issue by josh-porter** [neo4j/neo4j#12096]
Because of a quirk in my data model, I'm doing manual query optimization using apoc.cypher.run(). In the process, I've discovered some strange query planner behavior.

**Neo4j Version:** Enterprise 3.4.5
**Operating System:** Red Hat Enterprise Linux Server release 6.8 (Santiago)
**API:** Cypher

### Steps to reproduce
I first create an index on the UUID property of Person nodes:
`CREATE INDEX ON :Person(UUID);`

Now I run the following query:
```
CALL apoc.cypher.run("
MATCH (n1_2017:Person:Y2017)-[:KNOWS]->(n2:Person)
RETURN DISTINCT n1_2017, n2
", {}) YIELD value WITH value.n1_2017 AS n1_2017, value.n2 AS n2
CALL apoc.cypher.run("
MATCH p=(n1_2016:Person:Y2016)-[:KNOWS*1..8]->(n3:Person)
WHERE n1_2017.UUID = n1_2016.UUID
RETURN DISTINCT n1_2017, n2, p, n1_2016, n3
", {n1_2017: n1_2017, n2: n2}) YIELD value WITH value.n1_2017 AS n1_2017, value.n2 AS n2, value.p AS p, value.n1_2016 AS n1_2016, value.n3 AS n3
RETURN DISTINCT n1_2017, n2, relationships(p) AS rn1n3, n1_2016, n3 LIMIT 100;
```

apoc.cypher.run() constructs the second subquery as follows:
```
WITH {`n1_2017`} as `n1_2017` , {`n2`} as `n2`
MATCH p=(n1_2016:Person:Y2016)-[:KNOWS*1..8]->(n3:Person)
WHERE n1_2017.UUID = n1_2016.UUID
RETURN DISTINCT n1_2017, n2, p, n1_2016, n3
```

### Expected behavior
Since the first subquery MATCHed the node n1_2017, and the result is passed to apoc.cypher.run(), the quantity n1_2017.UUID is known, and the plan for the second subquery should begin by looking up n1_2016 using the index on :Person(UUID).

### Actual behavior
When I EXPLAIN the second subquery as written, the plan begins with a NodeByLabelScan. But if I change the line "WHERE n1_2017.UUID = n1_2016.UUID" to put n1_2017 on the right side of the expression and n1_2016 on the left, the plan for the second subquery begins with a NodeIndexSeek, which is much more efficient. Also, I can force the NodeIndexSeek using a query planner hint.

Still, in principle, shouldn't "WHERE b = a" produce the same query plan as "WHERE a = b"?

**Comment by Hunterness** [comment]
Hi, could you try to run the query with the newest Neo4j 3.4 (3.4.10) and see if your problem is solved. 

If not, could you supply us with some dataset where you observe the problem so we can try and reproduce it?

**Comment by mnd999** [comment]
This is a very old issue we haven't heard anything back on for some time so I will close for now. If it's still a problem, feel free to reopen.
