### ISSUE TITLE
Neo4j Web Interface not killing tasks

### ISSUE THREAD

**Issue by Legolash2o** [neo4j/neo4j#12091]
Ubuntu 18.04.1
Neo4j 3.4.10

Nodes: 40m
Edges: 72m

Whenever I run a query and want to cancel it, it fails to do so.

**Query**
The query I ran was simply clicking on a property (boolean) on the left hand side. Not all 'Node' have the property.

**Actual**
I click the queries (:queries), select the task I want to kill but it never works and just keeps going. The only way to cancel it is to restart the neo4j service.

**Expected**
To stop running the query.

**Comment by oskarhane** [comment]
Hi and sorry for the late response @Legolash2o.
Are you positive that the queries never aren't killed?
The query killing isn't instant, if the server is under heavy load it can take some time.

**Comment by Legolash2o** [comment]
Positive. I have Auto-Refresh on as well as manually refreshing and opening up a new tab.

It was the only thing running, even with a fresh restart of the server/service.

**Comment by GittiHab** [comment]
I am experiencing similar issues. I have the feeling that neo4j has trouble killing heavy queries in general. Also neo4j won't stop using `neo4j stop` if the memory runs too low.
