### ISSUE TITLE
JMX big decimal properties cause an error, b/c of PropertyDispatcher usage.

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#121]
@jexp: 'see: https://groups.google.com/d/topic/neo4j/LOFtBiAZC2E/discussion

@thobe says:

This is a bug, JMX attributes are not properties, therefore the PropertyTypeDispatcher is not apt to dispatch them. It has worked "by accident" in most cases, because most beans return attribute value objects that happen to match our property types, but this guy has some bean that returns a BigDecimal, which is perfectly valid JMX, but not a valid Neo4j property.

I see two ways of fixing this:
1. Don't use PropertyTypeDispatcher for this purpose, use some other conversion mechanism for converting JMX attributes to serializable representation.
2. Extend PropertyTypeDispatcher ever so slightly so that instead of just throwing an exception straight away it invokes a method for "unknownNumberType(Number number)" (and similar for other places where exceptions are thrown), the default implementation of these methods would throw exception, but it would allow to override those methods for further dispatch in a subclass as in this case.
'

**Comment by burqen** [comment]
Issue added to backlog.

**Comment by tinwelint** [comment]
I'm sorry, none of the supported releases has the webadmin surface/endpoint anymore, so will close this.
