### ISSUE TITLE
[question] - beyond limits of 34.4 billion nodes, 34.4 billion relationships

### ISSUE THREAD

**Issue by archenroot** [neo4j/neo4j#12109]
Hello, 

in the FAQ section available at https://github.com/neo4j-contrib/neo4j-faq I found first topic regarding limitations of neo4j.

> What is the maximum number of nodes supported? What is the maximum number of edges supported per node?
> 
> At the moment it is 34.4 billion nodes, 34.4 billion relationships (35 bit each), and at a minimum 68.7 billion properties (36bit) (maximum is 274 billion, depending on the property types), in total. We plan to up these numbers to about 40 bit so 1 trillion.

Q: When do you plan to go beyond these limitations, any realistic road map available?

**Comment by jexp** [comment]
Yes, sorry. That faq is outdated. 

Neo4j enterprise has a high-limit mode that removes those limits

**Comment by archenroot** [comment]
@jexp - cool, I was under impression that the info is already obsolete, thx for confirmation.

**Comment by bradnussbaum** [comment]
@jexp Neo4j Enterprise is now closed source and propriety as of 3.5. I think it’s best to represent what is now possible with open data formats only that don’t lock users into a proprietary database format.
