### ISSUE TITLE
3.5 full text search - call db.indexes() output

### ISSUE THREAD

**Issue by graphadvantage** [neo4j/neo4j#12107]
Just a little thing

CALL db.indexes() 
 
the type of index for relationships is listed as node_label_property, might be better listed as relationship_type_property for clarity

"INDEX ON RELATIONSHIP:ACTED_IN(role)" | "role_one_index" | ["ACTED_IN"] | ["role"] | "ONLINE" | "node_label_property" | 100.0 | {   "version": "1.0",   "key": "fulltext" } | 9

**Comment by chrisvest** [comment]
Hi, thanks for reporting. It's one of those little things we didn't get to in time for GA.
