### ISSUE TITLE
Random Could not compile query due to insanely frequent schema changes errors in our build

### ISSUE THREAD

**Issue by graemerocher** [neo4j/neo4j#12108]
With the latest version of the driver we get random errors like the following:

```
org.neo4j.driver.v1.exceptions.DatabaseException: Could not compile query due to insanely frequent schema changes
    at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:122)
    at org.neo4j.driver.internal.ExplicitTransaction.close(ExplicitTransaction.java:117)
    at grails.gorm.tests.GormDatastoreSpec.cleanup(GormDatastoreSpec.groovy:91)
```

This did not occur in earlier versions of the driver.

**Neo4j Version:** 3.5.0 Community  
**Neo4j Mode**: Single instance  
**Driver version**: Java driver 1.7.2
**Operating System:** Mac OS X

### Steps to reproduce
1. git clone git@github.com:grails/gorm-neo4j.git
2. ./gradlew grails-datastore-gorm-neo4j:test
3. See random errors (sometimes build passes)

**Comment by graemerocher** [comment]
I will try out 3.4 and report back. Thanks

**Comment by youb93** [comment]
Hello, 
have the same error with neo4j 3.4.9 and neo4j-java-driver 1.7.0.

With this on the database side : 

`2019-01-24 12:48:43.823+0000 INFO  Bulk operation succeeded`
`2019-01-24 12:55:05.720+0000 ERROR Client triggered an unexpected error [Neo.DatabaseError.General.UnknownError]: Could not execute query due to insanely frequent schema changes, reference 45213471-f08d-4f1f-9c1c-df1b555df9cd.`

**Comment by wdroste** [comment]
Any progress on this? I'm seeing this as well w/ Neo4j test harness 3.5.4 and java driver 1.7.5

**Comment by wdroste** [comment]
Fails on 3.4.9 and 1.7.5

**Comment by OliviaYtterbrink** [comment]
@wdroste What is the setup you're using when you see this problem? 
I can't reproduce it with the setup from the first post.
It would help us if we could get a way to reproduce it.

**Comment by OliviaYtterbrink** [comment]
Since we cannot reproduce this without data, we're closing the issue. If this becomes a problem again, please re-open the issue and provide sample data.
