### ISSUE TITLE
No sudo rights on `neo4j-admin load` gives wrong feedback string

### ISSUE THREAD

**Issue by jberends** [neo4j/neo4j#12101]
- Neo4j version: 3.4.10
- Operating system: Ubuntu 18.04

## feature request report

I discovered many small annoyances regarding management of the neo4j server, including amoungst others the `neo4j-admin load ...` message that is shown without the correct rights.

Without the proper rights you get: `command failed: the database is in use -- stop Neo4j and try again` which is not the case if you do `sudo ps aux | grep neo` -> shows no neo4j processes. 

### Expected behavior
 A string that says that you do not have access to the database directories

### Actual behavior
 a string is shown: `command failed: the database is in use -- stop Neo4j and try again`

**Comment by tinwelint** [comment]
We are working on providing a better error message on permission problems.

**Comment by Roxling** [comment]
An attempt to reproduce this shows that the error message now is `CommandFailedException: You do not have permission to load the database.` which is accurate. This has probably been the case since 4.0, but only verified on the latest version. I consider this solved.
