### ISSUE TITLE
neo4j-admin import hanging during relationship linking phase

### ISSUE THREAD

**Issue by ghost** [neo4j/neo4j#12110]
## Slow neo4j-admin import

I was trying to import a large dataset (900 mln nodes, 3 bln properties, 4 bln relationships) of CSV to Neo4j using neo4j-admin import tool. I could see both nodes and relationships import (phase 1 and 2) completed very fast in less than an hour, but relationship linking phase slows down at 40% and eventually making the process very slow and the whole import completed in around 14 hours.

**Neo4j Version:** 3.4.1 Community
**Operating System:** Linux x86_64
**Processors:** 12
**RAM:** 32GB
**API/Driver:** Using neo4j-admin import command line tool

### Stats from my run

**Available resources:**

Total machine memory: 31.26 GB
Free machine memory: 30.00 GB
Max heap memory : 19.56 GB
Processors: 12
Configured max memory: 10.54 GB
High-IO: true

Import starting 2018-12-12 23:19:23.740+0000
Estimated number of nodes: 896.16 M
Estimated number of node properties: 3.05 G
Estimated number of relationships: 3.97 G
Estimated number of relationship properties: 15.18 G
Estimated disk space usage: 430.98 GB
Estimated required memory usage: 12.01 GB

**Current top stats**
%Cpu(s): 2.3 us, 1.8 sy, 0.0 ni, 27.6 id, 68.2 wa, 0.0 hi, 0.0 si, 0.0 st
KiB Mem : 32780080 total, 240616 free, 19537508 used, 13001956 buff/cache
KiB Swap: 4194300 total, 3052484 free, 1141816 used. 12778128 avail Mem

PID USER PR NI VIRT RES SHR S %CPU %MEM TIME+ COMMAND
1739 xxx 20 0 37.5g 18.2g 0 S 41.9 58.3 931:43.81 java

IMPORT DONE in 14h 39m 14s 210ms. 
Imported:
  864665185 nodes
  3757814196 relationships
  2918217693 properties
Peak memory usage: 10.66 GB

Thread dump available [here](https://drive.google.com/file/d/1buKWJGln9h2FpzMcLlKpppEOj6yWOfxj/view?usp=sharing)

Heap dump available [here](https://drive.google.com/open?id=1otiVng6YhZIMEgjc34z0IZTAkn6gOdAi)

**Comment by jiangxjcn** [comment]
I meet the similiar problem.
Have you found a solution?

**Comment by tinwelint** [comment]
This is very likely due to one of the phases where it will read the relationship store backwards and do relationship chain linking (the former pass goes forward). Reading a file backwards is, on an OS/FS level apparently way slower. This has been fixed in a development version for release later, but it may be considered for back-porting.

**Comment by jiangxjcn** [comment]
I have solve my problem.
I have too many relationships TYPE for the first time , and when i set all the relationships the same type,the import time reduce to 10 minutes from around 20 hours.
The total number of my graph including around 5000W nodes and 3.5E relationships.

**Comment by tinwelint** [comment]
Right OK then it's most of a memory issue, you see the importer will need a piece of memory _per relationship type_ when linking them together and it will try to fit as many types as possible per pass through the relationship store and go multiple rounds through the relationship store until all types have been processed. If you would have had more memory available (not heap memory, but just more machine memory available) it would have required fewer passes and would have helped too.

OK to close this issue, you think?
