### ISSUE TITLE
TestGraphDatabaseFactory is not available in 3.5

### ISSUE THREAD

**Issue by jcornaz** [neo4j/neo4j#12118]
Since Version 3.5 of neo4j-kernel (test-jar) the class `org.neo4j.test.TestGraphDatabaseFactory` is no longer available.

### Environment
- Neo4j version: 3.5.1
- Operating system: Windows 10
- API/Driver: Java API

### Steps to reproduce
  1.  Create a project with the dependency: `org.neo4j:neo4j-kernel:3.5.1:tests`
  2. Write a simple (empty) class and the following import: `import org.neo4j.test.TestGraphDatabaseFactory`
  3. Try to compile (`gradlew classes`)

### Expected behavior
Since `TestGraphDatabase` was available (and not deprecated) in version `3.4.10`. It should still be accessible. `import org.neo4j.test.TestGraphDatabaseFactory` should not cause any compilation issue.

### Actual behavior
  * Compilation fails with `Unresolved reference: TestGraphDatabaseFactory`

**Comment by hugofirth** [comment]
So it looks like this class has been moved, and maven doesn't handle transient `test-jar` dependencies. If you depend upon the `org.neo4j.community.it-test-support` module directly you should be able to import the class. **However** you should note that `TestGraphDatabaseFactory` is not part of our public api, so unfortunately it may change again at any point in the future.

**Comment by jcornaz** [comment]
Thank you very much for the tip of using `org.neo4j.community.it-test-support`.

Please write that down in the documentation.

>you should note that TestGraphDatabaseFactory is not part of our public api

`TestGraphDatabaseFactory` *is* part of the public API:
* Official documentaion: https://neo4j.com/docs/java-reference/current/tutorials-java-embedded/#tutorials-java-unit-testing
* Usage example referenced by the official documentation : https://github.com/neo4j/neo4j-documentation/blob/3.5/embedded-examples/src/test/java/org/neo4j/examples/Neo4jBasicDocTest.java#L72

If you want to make it no-longer a public API, it is fine. For that:
1. Deprecate the class (and make it *package protected* in future releases).
2. Remove it from the documentation (Or at least explicitly state it is an internal API)
3. Document what is the alternative

**Comment by MishaDemianenko** [comment]
Hi @jcornaz classes that are public API are part of javadoc that are available at https://neo4j.com/docs/java-reference/current/javadocs
and there is no point to mark any class that is not a public API that its not part of it.

But I agree that as soon as it already sneaked into documentation examples those pages should be properly updated with instructions on how to write tests in a supported way. Thx for pointing that out!

While TestGraphDatabaseFactory is _mostly_ internal class you can also take a look into Neo4jRule from neo4j-harness. Its a convinient junit 4 rule that provides access to neo4j and can be used as yet another rule during your testing.

**Comment by jcornaz** [comment]
@MishaDemianenko, i would not expect it to appear be in that javadoc, since it is from another artifact. No matter if it is public API or not.

But since:
1. It is mentionned in https://neo4j.com/docs/java-reference/current/
2. The class is *public* (and not package protected)
3. The class does not have a naming suggesting it is internal (like finishing by `Impl` or `Internal`)
4. The class is not in a package `internal` in its name.

All that make it part of the public API. Even if it wasn't intended in the first place.

But again, it is fine to make it no longer public. It should just be done properly (through deprecation, and documentation update)

**Comment by MishaDemianenko** [comment]
@jcornaz provided javadoc is neo4j global public java doc. For example, it includes `org.neo4j.jmx` which is not part of kernel artifact, but still, its included.

Let me answer point by point as well:
1. Valid point.
2. The fact that some class is public does not mean that its part of public API of any sort. Only classes that included into javadoc is part of public API. Class is public for our own internal purposes. End users can still use that for sure but public visibility does not make it publically supported API.
3-4. We have quite a large codebase that survived quite some time and not all of the parts following any naming conventions or follows different conventions to make it even better. You should not rely on that at all. Only classes covered by javadoc are part of public API.

And yep that was not intended to be exposed in a first place, as you can see its originaly as part of `test-jar` only but point taken and documentation will be updated accordinly. Thx!

**Comment by jcornaz** [comment]
Thanks @MishaDemianenko 

I just quickly want to say two things:

The need of public visibility internally doesn't mean that there is no way of making sure users don't use it by indavertance. Naming, package-name, documentation and annotations, can help for that.

I understand the codebase is large, and may not be perfect. But it doesn't mean it cannot be improved. If I open this issue and explains the rational behind my arguments, it is in the hope to help improve its quality. In this case, if the will is to not having that class public, then it shall be deprecated, and internal version should be placed in an `internal` package.

Anyway, thank you very much for the support. I'll let you close this issue after documentation update.

**Comment by MishaDemianenko** [comment]
pull request that will update manual with new instruction and deprecation created (in a separate repo) and will be published as part of the next 3.5.x release.

**Comment by jcornaz** [comment]
>pull request that will update manual with new instruction and deprecation created (in a separate repo)

Can you share the link please?

**Comment by MishaDemianenko** [comment]
@jcornaz Now latest updated documentation is available at https://neo4j.com/docs/java-reference/current/tutorials-java-embedded/#tutorials-java-unit-testing

**Comment by jcornaz** [comment]
Thank you @MishaDemianenko
