### ISSUE TITLE
Strange behavior of aggregations, aliased in WITH clause

### ISSUE THREAD

**Issue by Icebreaker454** [neo4j/neo4j#12112]
## Strange behavior of aggregations, aliased in WITH clause

**Neo4j Version:** 3.4.0
**Operating System:** Fedora 26

Hello!

I've been using Neo4j for quite a while, and noticed some strange behavior regarding aggregations, aliased in the WITH clause of the Cypher query.
 
I have the following node setup in Neo4j:
![image](https://user-images.githubusercontent.com/6199897/50238039-0e9c2480-03c7-11e9-8c71-2dbcb16415cb.png)

### Steps to reproduce
```cypher
MATCH (g:Grey)-[:TypeRel3]-(y:Yellow)-[:TypeRel1]-(p:Pink)
WITH g, y, p, COUNT(DISTINCT y) as _count1, COUNT(DISTINCT p) as _count2
RETURN y.name, _count1, _count2
```
### Expected behavior
| y.name        | _count1           | _count2  |
| ------------- |:-------------:| -----:|
| "x"      | 1 | 3 |

### Actual behavior
| y.name        | _count1           | _count2  |
| ------------- |:-------------:| -----:|
| "x"      | 1 | 1 |
| "x"      | 1 | 1 |
| "x"      | 1 | 1 |

However, when I use `COUNT(...)` functions in the `RETURN` statement instead of the `_count1` and `_count2` aliases from the `WITH` clause as follows:

```cypher
MATCH (g:Grey)-[:TypeRel3]-(y:Yellow)-[:TypeRel1]-(p:Pink)
WITH g, y, p, COUNT(DISTINCT y) as _count1, COUNT(DISTINCT p) as _count2
RETURN y.name, COUNT(DISTINCT y), COUNT(DISTINCT p)
```

the results show  as expected:

| y.name        | COUNT(DISTINCT y)           | COUNT(DISTINCT p)  |
| ------------- |:-------------:| -----:|
| "x"      | 1 | 3 |

So far I haven't found anything in the documentation or related issues. Am I missing something?
I'd appreciate any help regarding this.

**Comment by jexp** [comment]
This is correct behavior as you're aggregating **with `g,y,p` as grouping keys**, so the cardinality for each of those groups is 1.

To achieve what you want to do is to leave off p and g from the grouping.
**Unless you have duplicate names for `y` you will never get a count > 1**

```
MATCH (g:Grey)-[:TypeRel3]-(y:Yellow)-[:TypeRel1]-(p:Pink)
WITH y, count(distinct p) as _count2
RETURN y.name,  count(distinct y), _count2
```
