### ISSUE TITLE
Neo4j 3.5.0 Dump after moving to 3.5.0 failing

### ISSUE THREAD

**Issue by folterj** [neo4j/neo4j#12119]
We've been working with NEO since around 3.4.0, using dump/load to backup/restore our database. After moving from version 3.4.11 to version 3.5.0 (or 3.5.1), I can no longer dump after a load (without making any changes or even running the database).

- Neo4j version: 3.5.0
- Operating system: Neo4j Desktop

neo4j-admin load --from=data\db.dump --database=graph.db

neo4j-admin dump --database=graph.db --to=data\db2.dump

command failed: Active logical log detected, this might be a source of inconsistencies.
Please recover database before running the dump.
To perform recovery please start database and perform clean shutdown.

**Comment by hugofirth** [comment]
Hi @folterj  - what happens if you follow the instructions (i.e. start and stop)?

**Comment by folterj** [comment]
Thanks for the reply @hugofirth - indeed one of the first things I tried, the issue persists.
It seems there are various problems trying to upgrade from pre-3.5 to 3.5 according to the log using Neo4j Desktop (on Windows).
All of which were resolved by loading the same dump into the Linux server version, then backing up (dump) from there, instead of using Neo4j Desktop.

PS: Suggest adding 'Neo4j Desktop' to thread title.

**Comment by tinwelint** [comment]
So, what is the root cause of this, upgrading 3.4.11 to 3.5? Have you gotten past this issue?

**Comment by jdefolter** [comment]
Thanks for the response @tinwelint - our issue disappeared some time ago, I believe in particular with the new storage format, however we continue to prefer DUMP from our main server to ensure data integrity.

**Comment by folterj** [comment]
Thanks for the response @tinwelint - our issue disappeared some time ago, I believe in particular with the new storage format, however we continue to prefer DUMP from our main server to ensure data integrity.

**Comment by folterj** [comment]
On version 4.0.2 again this same issue. This is a persistent bug.
I found many references to this and FINALLY found out why. As far as I know this is caused when stopping a database on neo4j Desktop by simply pressing the stop button.

I found this work-around:

- shutdown database
- open terminal
- run bin/neo4j console
- after startup, hit Ctrl+C to shutdown database
- run neo4j-admin dump

(Source: https://stackoverflow.com/questions/54081703/neo4j-admin-dump-is-failing)

**Comment by p-buglewicz** [comment]
Same here:
with version 4.0.4 shutting down with following script:

```bash
if [ ! "$(/var/lib/neo4j/bin/neo4j stop)" ]; then
  while [ "$(/var/lib/neo4j/bin/neo4j status)" ];
  do
    sleep 1
    echo "Still waiting for database to close"
  done;
fi
```
still sometimes produces the same issue.

Workaround with opening console does not apply here as I want to dump with a script within a docker container.

**Comment by folterj** [comment]
Another work-around after making changes:

- Stop
- Start
- Stop
