### ISSUE TITLE
[FullText Schema] Cannot drop index when normal schema index exist

### ISSUE THREAD

**Issue by ikwattro** [neo4j/neo4j#12136]
- Neo4j version: 3.5.1
- Operating system: any
- API/Driver: any

### Steps to reproduce
```
CREATE INDEX ON :Book(title)
CALL db.index.fulltext.createNodeIndex('books', ['Book'], ['title'])
CALL db.index.fulltext.drop('books')
```

```
Neo.DatabaseError.General.UnknownError: Found more than one matching index, IndexRule[id=7, descriptor=Index( GENERAL, :label[0](property[2]) ), provider={key=native-btree, version=1.0}] and IndexRule[id=9, descriptor=Index( GENERAL, NODE:label[0](property[2]) ), provider={key=fulltext, version=1.0}]
```

NOTE : If you create first the fulltext index and then the normal schema index, then you can drop the fulltext index without issue.

### Expected behavior
exception is thrown

### Actual behavior
should not throw exception

**Comment by burqen** [comment]
Hi @ikwattro 
This issue is solved by this commit which will be part of next patch release. https://github.com/neo4j/neo4j/commit/b0a23b8dc5faf610007600aff84c92fb63a23194 
Thank you for reporting 👍
