### ISSUE TITLE
Returns different property key then created

### ISSUE THREAD

**Issue by tim-hanssen** [neo4j/neo4j#12135]
We have encountered a really strange behaviour in our production db. When we create a specific property it's returned as another property. A match query will work on both names (the wrong one, and the property key we created).

- Neo4j version: 3.4.10 (Causal cluster)
- Operating system: Ubuntu 18.04.01 LTS 
- API/Driver: PHP via BOLT (or Neo4j browser directly)
- We runned a consistency check to check for errors, but the db returns consistent without failures.

1.
```
MATCH (n:Dummy { Id : "a7c26b61-2cf3-8e68-fbf0-c90ce7ee0025"})
SET n.Appearance = 'test-value'
RETURN n
```

2.
The browser returns:
```
{
  "Id": "a7c26b61-2cf3-8e68-fbf0-c90ce7ee0025",
  "UnpublishOn_NLNL": "test-value"
}

```
3.
Now both queries will return the node:

```
MATCH (n:Dummy { UnpublishOn_NLNL : 'test-value'})
RETURN n

MATCH (n:Dummy { Appearance : 'test-value'})
RETURN n
```

For now we can only reproduce this with this specific property key `Appearance` that always changes in `UnpublishOn_NLNL`.

### Expected behavior
Node contains the set property with the right key.

### Actual behavior
Node contains another key for the set property.

We restored a backup from the prod db to our (single running server) on acc running the same store and same Neo4j version, I cannot reproduce it on that server.

**Comment by tim-hanssen** [comment]
We have the same issue with a relationship label, "ENTRY_TITLE" changes to "UPDATED_PUBLICATION" and both give the same match query result.

--

After some digging we discovered that one of our core servers did not respond to the wrong label or param. So it just showed the wrong one, but would not match on the one we created. After this we restarted all core servers one by one, deleting de graph.db store. After the server synced back the issue was gone on that server as well. So for us this fixed the issue for now, but I looks a like a clustering bug.

**Comment by tim-hanssen** [comment]
Hi Guys,

We're experiencing the issue again. The db returns paramters that don't exists, and is setting params that dont need to be set. As speciified about.

MATCH (:Environment)-[:HAS_PUBLICATION]->(n:Publication)-[rel:CONTAINS]->(r)
WHERE EXISTS (rel.TimelineConstraintHash)
RETURN rel.ElementId, rel.TimelineConstraintHash

The Element.Id doenst exists if i look at the object (it should exists) and is renemad for a newly introduced parameter. Still it also returns the correct name.


RETURN rel.ElementId | rel.TimelineConstraintHash
"227ad1af-e378-44d4-9df4-50b874329258" | "227ad1af-e378-44d4-9df4-50b874329258"

{
  "Locale": "nl-NL",
  "TimelineConstraintHash": "227ad1af-e378-44d4-9df4-50b874329258",
  "Label": "nl-NL.rhgfdghfgh.items.0.items.table",
  "ElementBox": "nl-NL.rhgfdghfgh",
  "ElementPosition": "nl-NL.rhgfdghfgh.items.0"
}

TimelineConstraintHash should be ElementId

It looks like this issue is triggered by introduction of a new parameter `TimelineConstraintHash` did not exist before this morning.

Neo4j version: 3.5.14 (Causal cluster)
Operating system: Ubuntu 18.04.01 LTS
API/Driver: PHP via BOLT (or Neo4j browser directly)


-- 

We took one core server down, unbinded, deleted the graph.db folder and resyned.
This changed the issue on that exact server to only returning the broken property instead of both. But it looks like the database has some serious issues.

--

The provided property key is not in the database

One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: ElementId)
WHERE EXISTS (rel.ElementId)

It looks like the new Property has completly taken over the place of the existing property.

**Comment by RagnarW** [comment]
Closing due to unsupported version
