### ISSUE TITLE
Heap size environment variable is overwritten by default config setting in docker

### ISSUE THREAD

**Issue by chrstnb** [neo4j/neo4j#12130]
When trying to run `bin/neo4j-admin import` with `HEAP_SIZE=16gb` in a docker container with `neo4j:3.5.1`, the Java memory option for the heap size is overridden by the default config value for the max heap size.

**Neo4j Version:** 3.5.1  
**Operating System:** Ubuntu 16.04.5
**API:** Docker

### Steps to reproduce
1. Pull the image: `docker pull neo4j:3.5.1`
2. Run `docker run -it --memory 30gb -v [import directories] -e HEAP_SIZE=600g neo4j:3.5.1 bin/neo4j-admin import... [import args]`
3. You will find that the "Available resources" show `Max heap memory : 491.00 MB` (or some value near but below the default of 512 MB)
4. In a separate shell on the same machine, run `docker ps` and note the name of the container you just created
5. Run `docker exec -it $CONTAINER_NAME sh`
6. Run `ps auxww` and note that the command running with neo4j is something like this:
`/usr/lib/jvm/java-1.8-openjdk/jre/bin/java -XX:+UseParallelGC -Xmx600g -Xms512M -Xmx512M...`
Note that the `-Xmx600g` arg is being overridden by the more recent `-Xmx512M` arg.

### Expected behavior
The max heap memory should be what is set in the environment variable, especially where no custom config file is being used. I couldn't find the expected behavior/priority where both a custom config file is used and the environment variable is set, however the environment variable taking priority seems more intuitive. 

### Actual behavior
Running on docker appends configurations to the neo4j.config file [code here](https://github.com/neo4j/docker-neo4j/blob/master/src/3.5/docker-entrypoint.sh#L127), which then overrides an environment variable even if set [code here](https://github.com/neo4j/neo4j/blob/3.5/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j-admin#L104).

I couldn't figure out where the code lives that calls [setup_heap](https://github.com/neo4j/neo4j/blob/3.5/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j-admin#L47) before the code that reads the config file, but it seems these could be reversed to resolve the issue if it's important that the configurations be appended to the neo4j.conf file.

**Comment by chrisvest** [comment]
The `bin/neo4j-admin` script doesn't read heap memory options from `neo4j.conf`, but `bin/neo4j` does. The `setup_heap` function is called just prior to calling the `call_main_class` at the bottom of the script. Does it work for you if you try it without docker?

**Comment by chrstnb** [comment]
Yes, the non-docker version doesn't have the options appended to `neo4j.conf` that set a default for `dbms.memory.heap.max_size`, so the environment variable will be used. Of course, a workaround to the docker issue is to make changes to and import a custom conf file, but for the environment variable to not work with a fresh docker image seems like unexpected behavior.

**Comment by chrisvest** [comment]
Sounds like it's probably the same issue as https://github.com/neo4j/docker-neo4j/issues/159 - can I ask you to add details to that issue?

**Comment by slothkong** [comment]
lol I wasted a good 6 hours becuase of this. Guess Ill just try rollingback version until my configs are applied...

**Comment by sherfert** [comment]
Closing since we have https://github.com/neo4j/docker-neo4j/issues/159
