### ISSUE TITLE
Unable to connect to bolt://localhost:7687 through web interface behind https.

### ISSUE THREAD

**Issue by darkl0rd** [neo4j/neo4j#12137]
I am running Neo4J in Docker behind a reverse proxy (Traefik) which performs SSL termination. I would expect to be able to connect to bolt://localhost:7687.

**Neo4j Version:** 3.5.1 
**Operating System:** Ubuntu 18.04  
**API:** Docker

### Expected behavior
Browsing to https://neo4j.my.domain.com shows the web interface and I am able to connect to bolt://localhost:7687 in the web interface.

### Actual behavior
The attempted connection to bolt://localhost:7687 fails and throws the following error:

> ServiceUnavailable: WebSocket connection failure. Due to security constraints in your web browser, the reason for the failure is not available to this Neo4j Driver. Please use your browsers development console to determine the root cause of the failure. Common reasons include the database being unavailable, using the wrong connection URL or temporary network problems. If you have enabled encryption, ensure your browser is configured to trust the certificate Neo4j is configured to use. WebSocket `readyState` is: 3

In the container, I am able to use Cypher Shell and and can confirm the port (7687) is open.

**Comment by jgrobbel** [comment]
This is a limitation in traefik. They have not yet added TCP support which bolt relies on. As you note http[s] is what they support.

https://github.com/containous/traefik/issues/10

**Comment by darkl0rd** [comment]
They also support ws/wss, but that's not the problem I am facing here.
I am not exposing 7687 to the outside world through traefik, only 7474; the web interface.
Through the web interface, I am trying to connect directly to localhost:7687 (that is inside the container itself, this traffic does not go over traefik) - which fails.

**Comment by jgrobbel** [comment]
I don't fully follow.
It sounds like you are successfully downloading the browser over http[s] from your remote container. If you then try to connect to `localhost:7687` it will look for something client-side, i.e. on your machine not the pod.

**Comment by darkl0rd** [comment]
What I didn't realize when I started setting this up, is that the connection which is being setup through the Neo4J UI is built-up from the client (browser) and not initiated from the server. That is "localhost" is not the container, but the client on which the browser session runs.

**Comment by jgrobbel** [comment]
Correct, happy to close this then?

**Comment by istiaque-a** [comment]
I also get the message while inserting any data. My code in Laravel controller is:

        $country_info = new Country();
        $country_info->country='India';
        $relation = $country_info->save();




It says:
 RuntimeException
Cannot connect to any server on alias: default with Uris: ('bolt://localhost:7687') 

How to solve the problem ?
