### ISSUE TITLE
Unexpected behaviour with Cypher where clause conditions

### ISSUE THREAD

**Issue by amitsuryavanshi** [neo4j/neo4j#12141]
**Neo4j Version:** 3.5.1-enterprise  
**Operating System:** OSX-10.13.6  
**API:** Query Browser

### Steps to reproduce
1. Open Query Bowser at `localhost:7474`
2. Execute following cypher
```
MATCH (n:User)
WHERE true OR false AND false
RETURN n
```

### Expected behavior
```
MATCH (n:User)
WHERE true OR false AND false
RETURN n
```
Expecting above cypher to not return any nodes, but it returns all the nodes with `User` label.
The condition ` true OR false AND false` inside `WHERE` clause should evaluate to `false` but it is evaluated to `true`.

### Actual behavior
Above cypher returns all the nodes with `User` label.

**Comment by Hunterness** [comment]
Hi @amitsuryavanshi, 

I don't believe this is the wrong behavior, AND do have a higher precedence than OR which makes the WHERE clause evaluate to `true OR (false AND false)` which is true. This is also the behavior in java (as can be seen in the precedence table here https://docs.oracle.com/javase/tutorial/java/nutsandbolts/operators.html).

If you want it to be false you can add parenthesis around the OR, giving it a higher precedence `(true OR false) AND false`. 

Best Regards,
Team Cypher

**Comment by amitsuryavanshi** [comment]
@sherfert Thanks for looking into this.
I predominantly work in ruby, where `true or false and false`  is evaluated as `false`. hence the confusion.
