### ISSUE TITLE
Neo4J 3.5 :  Query Execution Failure when using List Expansions in Where Clauses on Indexed Properties

### ISSUE THREAD

**Issue by otgitelr** [neo4j/neo4j#12149]
## Query Execution Failure when using List Expansions in Where Clauses on Indexed properties

When using a list expansion in a where clause on an indexed property, Neo4J throws an error: Neo.DatabaseError.Statement.ExecutionFailed.  Removing the index/constraint allows the query to execute successfully.  Prefix the query with `CYPHER runtime=interpreted` and it also executes successfully.

**Neo4j Version:** 3.5.0-enterprise, 3.5.1-enterprise, 3.5.2-enterprise
**Operating System:** Alpine (openjdk:8-jre-alpine) via Docker
**API:** Cypher

### Steps to reproduce
1. Pull the image: `docker pull neo4j/neo4j:3.5.0-enterprise`
2. Start a new container: `docker run -d -e NEO4J_ACCEPT_LICENSE_AGREEMENT=yes --name neo4j-test -p 7474:7474 -p 7687:7687 neo4j:3.5.0-enterprise`
3. Change the default password via cypher-shell: `echo "CALL dbms.changePassword('testing');" | cypher-shell -u neo4j -p neo4j`
4. Start a cypher-shell session using the new password: `cypher-shell -u neo4j -p testing`
5. Execute the following statements and observe the results:
  * `CREATE (a:Album { Name: "Piece of Mind", lc_name: "piece of mind"}) CREATE (b:Album { Name: "Somewhere in Time", lc_name: "somewhere in time"}) RETURN a,b;`
  * `MATCH (a:Album) WHERE a.lc_name IN [ id IN ["Somewhere in Time","Piece of Mind","Killers"] | toLower(id) ] WITH a {ref: a.Name,id:a.lc_name} RETURN COLLECT(a) AS Map;
CREATE INDEX ON :Album(lc_name);`
  * `MATCH (a:Album) WHERE a.lc_name IN [ id IN ["Somewhere in Time","Piece of Mind","Killers"] | toLower(id) ] WITH a {ref: a.Name,id:a.lc_name} RETURN COLLECT(a) AS Map;`
  * `CYPHER runtime=interpreted MATCH (a:Album) WHERE a.lc_name IN [ id IN ["Somewhere in Time","Piece of Mind","Killers"] | toLower(id) ] WITH a {ref: a.Name,id:a.lc_name} RETURN COLLECT(a) AS Map;`
  * `DROP INDEX ON :Album(lc_name);`
  * `MATCH (a:Album) WHERE a.lc_name IN [ id IN ["Somewhere in Time","Piece of Mind","Killers"] | toLower(id) ] WITH a {ref: a.Name,id:a.lc_name} RETURN COLLECT(a) AS Map;`

### Expected behavior
After creating an index on :Album(lc_name), matching the records using a list expansion should return the list of matched nodes.

### Actual behavior
After creating an index on :Album(lc_name), matching the records using a list expansion returns an execution failure: `Ouch, no suitable slot for key id = String("Somewhere in Time")
Slots: SlotConfiguration(longs=0, refs=0, slots=Map(), cachedProperties=Map())`

### Stack Traces & Sessions
[neo4j-3.5.0-enterprise-stack-trace.txt](https://github.com/neo4j/neo4j/files/2813192/neo4j-3.5.0-enterprise-stack-trace.txt)
[neo4j-3.4.12-enterprise-cypher-session.txt](https://github.com/neo4j/neo4j/files/2813193/neo4j-3.4.12-enterprise-cypher-session.txt)
[neo4j-3.5.0-enterprise-cypher-session.txt](https://github.com/neo4j/neo4j/files/2813194/neo4j-3.5.0-enterprise-cypher-session.txt)

**Comment by Hunterness** [comment]
Hi @otgitelr, thanks for reporting. We will look into this.

Best Regards,
Team Cypher

**Comment by sherfert** [comment]
We've just merged a fix. I expect that to be part of 3.5.3.

**Comment by Gudahtt** [comment]
Which commit was this fixed in? Did this make it into 3.5.3?

Edit: Oh, I'm guessing this change was in a private repository.
