### ISSUE TITLE
3.5 FTS: Support composite indexing and RETURN both nodes

### ISSUE THREAD

**Issue by markmssd** [neo4j/neo4j#12142]
Hi!

I'm currently using the deprecated indexing to perform Full Text Search on my entries. My query looks like this:

```
MATCH (r:Room)-[:BELONGS_TO]-> (v:Venue)-[:BELONGS_TO]->(b:Building)
WHERE r.code STARTS WITH "xx" OR b.code STARTS WITH "yy"
```

Where Room.code and Building.code properties have been indexed with:
```
CREATE INDEX ON :Room(code)
CREATE INDEX ON :Building(code)
```

Now I'm trying to move over to the new 3.5 FTS. From the doc, I could use [here](https://neo4j.com/docs/cypher-manual/current/schema/index/#schema-index-substring-search-using-contains-single-property-index), it seems like the same could be achieved like this:

```
CALL db.index.fulltext.createNodeIndex('buildingRooms', ['Room', 'Building'], ['code'])
```

However, it does not behave the same way. It sometimes returns Room nodes, and other times Building nodes.

It would be nice if the same scenario could be achieved like so. I wouldn't want to add `Building` properties on the `Room` and index only the room properties to do so.

Do you guys think it would be feasible?
Thanks!

**Comment by chrisvest** [comment]
It should return a mix of Room and Building nodes. Any node with one or both of those labels, that has a matching property should be returned. How do you query your full text index? Do you have any other mapping layer (SDN, OGM) between your query result and your code?

**Comment by markmssd** [comment]
Thanks I will give it another try and let you know!

To answer your question, yes I do have a custom OGM, borrowed from an old Neo4J client, but I doubt it’s my issue, I have a ton of unit test passing through this OGM.

(I will post how I query it shortly)

**Comment by markmssd** [comment]
**UPDATE:** Here is how I am running the search query:

```
MATCH (r:Room)-[:BELONGS_TO]-> (v:Venue)-[:BELONGS_TO]->(b:Building)
CALL db.index.fulltext.queryNodes("buildingRooms", "H 420") YIELD node, score
RETURN node, score
```

If I query only for `H`, I get back the building with code `H`. If I query only for `420`, I get back the room with code `420`.

What I need is the equivalent of
```
MATCH (r:Room)-[:BELONGS_TO]-> (v:Venue)-[:BELONGS_TO]->(b:Building)
WHERE r.code STARTS WITH "xx" OR b.code STARTS WITH "yy"
RETURN { room: r, building: b } AS results
```

Maybe I've misunderstood the capabilities of FTS, and it's not meant for my use case?

Thanks!

**Comment by chrisvest** [comment]
Hi, sorry it took so long to get back to this.

In your query with the full-text index, the match clause doesn't have the effect I think you want. The full-text index query will produce results for the whole index -- the results will not be restricted to what the preceding match clause returns. Also, I think the index will be queried for each row returned by the match clause.

The full-text query is also not implicitly an OR-sequence of STARTS WITH queries. They are more like CONTAINS queries, except the meaning of CONTAINS is decided by the analyzer.

When I run this query, I only get matches where `H` or `420` are whole tokens of the `code` properties:

```
CALL db.index.fulltext.queryNodes("buildingRooms", "H 420") YIELD node, score
RETURN node, score
```

To STARTS WITH like semantics, I have to write the query like this:

```
CALL db.index.fulltext.queryNodes("buildingRooms", "H* 420*") YIELD node, score
RETURN node, score
```

See

![image](https://user-images.githubusercontent.com/7993/70897627-4d24e900-1ff3-11ea-82a4-b5251712f15d.png)

vs

![image](https://user-images.githubusercontent.com/7993/70897701-6e85d500-1ff3-11ea-9413-0595d2792e32.png)

**Comment by chrisvest** [comment]
Teaching Cypher how to use full-text indexes to answer STARTS WITH, ENDS WITH and CONTAINS is on the road map, and should make it easier to write these sorts of queries, but until then you will have to rewrite your queries to either find the rooms first or the buildings first, and then perform a graph traversal from there to match your pattern.

**Comment by markmssd** [comment]
Thanks a lot for this very complete answer @chrisvest , really appreciate it!
