### ISSUE TITLE
Database load (neo4j-admin load --force) fails with EOFException: null

### ISSUE THREAD

**Issue by fhureau** [neo4j/neo4j#12147]
- Neo4j version: Docker container neo4j:3.3.2
- Operating system: Container-Optimized OS on GCP (based on Chromium OS)

Hello,
I have a daily database dump exported via the following command:

```
docker run \
--publish=7473:7473 \
--publish=7687:7687 \
--volume=$HOME/neo4j/data:/data \
--volume=$HOME/neo4j/logs:/logs \
--volume=$HOME/neo4j/conf:/conf \
--volume=$HOME/neo4j/plugins:/plugins \
--volume=$HOME/neo4j/import:/import \
--volume=$HOME/neo4j/scripts:/scripts \
--volume=$HOME/neo4j/ssl:/ssl \
--volume=$TEMP/graph.db:/graph.db \
--ulimit=nofile=40000:40000 \
--name=neo4j-dump \
-id \
neo4j:3.3.2 \
/bin/bash -c "bin/neo4j-admin dump --database=graph.db --to=/graph.db/$TAG.dump"
```
And when I try to load it in another instance (same version of the container) with the following command:

```
docker run \
--publish=7474:7474 \
--publish=7473:7473 \
--publish=7687:7687 \
--volume=$HOME/neo4j/data:/data \
--volume=$HOME/neo4j/logs:/logs \
--volume=$HOME/neo4j/ssl:/ssl \
--volume=$HOME/neo4j/backups:/backups \
--volume=$HOME/neo4j/conf:/conf \
--ulimit=nofile=40000:40000 \
--env-file=$HOME/neo4j.env \
--name=neo4j-admin \
-it \
neo4j:3.3.2 \
/bin/bash -c "bin/neo4j-admin load --from=/backups/graph.db/$TAG.dump --database=graph.db --force=true"
```
I systematically get the following error : `command failed: unable to load database: EOFException: null`

What could be the issue? How can I test if my daily backup dump is corrupted?
I can still duplicate my database by copy/pasting the graph.db folder but it is not recommended so I'd rather use the dump and load method...

Thanks

**Comment by kcrimson** [comment]
Can you share logs?

**Comment by fhureau** [comment]
Thanks for your reply.

I solved my problem by removing the -id flag when dumping the database and replacing it with --rm, and now the dump is clean and normally loadable. 

So closing the issue, thanks!
