### ISSUE TITLE
java.lang.ClassNotFoundException: org.neo4j.cypher.internal.frontend.v3_4

### ISSUE THREAD

**Issue by rimmmmm** [neo4j/neo4j#12154]
Hi all
I would like to run a scala code which uses CAPS (cypher for spark)
I added many jars including 
_ neo4j-cypher-frontend-3.3-3.3.4.jar
_neo4j-cypher-frontend-3.4-3.4.0-alpha08.jar
but none resolves the following not found class 
java.lang.ClassNotFoundException: org.neo4j.cypher.internal.frontend.v3_4.semantics.SemanticFeature$Cypher10Support$
best

**Comment by Hunterness** [comment]
Hi, thanks for reporting, we will look into it.

/Team Cypher

**Comment by fickludd** [comment]
Hi @rimmmmm,

It seems like `SemanticFeature.Cypher10Support` was some temporary solution that was not released, [removed in march 2018](https://github.com/neo4j/neo4j/commit/a8a6411d6a6a9639400cda585bdd3228137089c9#diff-21483d3aad688278a781d86c61f7bcce). What CAPS version are you using? Also: are you separately depending on some Neo4j version?

**Comment by s1ck** [comment]
Hi @rimmmmm 
Why don't you use the front-end version that CAPS ships with? 
This would be `org.opencypher:front-end-9.0:9.0.20181030`

What is it you want to achieve? Are you using Neo4j and CAPS in the same project?

@fickludd The flag is not a temporary solution and is still part of the current front-end: https://github.com/neo4j/neo4j/blob/3.5/community/cypher/front-end/ast/src/main/scala/org/neo4j/cypher/internal/v3_5/ast/semantics/SemanticFeature.scala#L24

**Comment by rimmmmm** [comment]
Hi all 
thank you for your replies,
I would like to run the examples from command-line how to do? and which version I can use for Neo4j ?
as following
scala -J-Xmx5g -classpath $jars org.opencypher.spark.examples.CaseClassExample
such that $jars contains all required jars: caps, scala, spark, neo4j
best

**Comment by fickludd** [comment]
@rimmmmm this does not seems to be an issue with Neo4j, but rather with Cypher for Apache Spark. Since it seems like I cannot move issues to another github repository yet, you'll have to re-open the issue [against Cypher for Apache Spark instead](https://github.com/opencypher/cypher-for-apache-spark/issues), and I'm sure @s1ck and friends can help you further.
