### ISSUE TITLE
Map Comprehensions

### ISSUE THREAD

**Issue by lhannest** [neo4j/neo4j#12152]
There are list comprehensions:
`[x IN xs WHERE p(x) | f(x)]`

It would also be nice to have map comprehensions, maybe with the following syntax:

`{k, v IN map WHERE p(k, v) | f(k) : g(v)}`

This would be useful for loading CSV's, e.g.:

```
LOAD CSV WITH HEADERS FROM "file:///nodes.csv" AS row
WITH {k, v IN row WHERE v CONTAINS ";" | k : SPLIT(v, ";")} AS row
MERGE (n {id: row.id}) ON CREATE SET n += row;
```
```
LOAD CSV WITH HEADERS FROM "file:///nodes.csv" AS row
WITH {k, v IN row WHERE NOT v IS NULL | k : v} AS row
MERGE (n {id: row.id}) ON CREATE SET n += row;
```

**Comment by jexp** [comment]
Great idea.

as a _workaround_ you can use:

`[k IN keys(map) WHERE p(x, map[k]) | [ f(k), g(map[k]] ]`

and you could apoc.map.fromPairs() to turn it back into a map

**Comment by Mats-SX** [comment]
Hello @lhannest and thank you for this suggestion.

I have created a CIR (Cypher Improvement Request) on the `openCypher` repository, where language changes are tracked and managed: https://github.com/opencypher/openCypher/issues/352

If you have further comments, please engage with us on that issue.
