### ISSUE TITLE
neo4j source problem

### ISSUE THREAD

**Issue by BrokenWingsIcarus** [neo4j/neo4j#12157]
I downloaded the source code of neo4j. But I want to start it directly by running main instead of by building. When I run Community Entry Point, all kinds of class not foundation errors always pop up. Who can help me? Thank you

**Comment by BrokenWingsIcarus** [comment]
o(╥﹏╥)o  Pain.

**Comment by fantaga** [comment]
me too,branch 3.4 snapshot, project were imported into IDEA,but when I run CommunityEntryPoint#main method,the project builds and lots of errors poped up.

**Comment by BrokenWingsIcarus** [comment]
Who can give me a reply? It's low.

**Comment by jeymer** [comment]
What version of JDK are you using?

**Comment by fantaga** [comment]
> What version of JDK are you using?

jdk-8u121-windows-x64

**Comment by chrisvest** [comment]
This works fine for me. You need to make sure that the classpath for your run configuration is correct. I opened it as a Maven project in intellij and set the JDK and language level to be Java 8, and then Intellij gets the classpath right on its own. Maybe it helps to do `mvn clean install -DskipTests` first.

**Comment by BrokenWingsIcarus** [comment]
Yeah... I did that. But something went wrong. The JDK version was the normal "8u191" and the MVN version was 3.5.4...

**Comment by BrokenWingsIcarus** [comment]
Is there any relevant information (blog, document....)? Of course it's very low, but I haven't found any valid documents outside the Chinese environment. Can you help me?

**Comment by fantaga** [comment]
Install scala sdk,and mark scala directory as source directory.Some classes wrote by scala.

**Comment by BrokenWingsIcarus** [comment]
It is recommended that code after release be used instead of using the latest submission, which is error-prone.

**Comment by BrokenWingsIcarus** [comment]
http://www.k6k4.com/blog/show/aaavurkwu1547605733514 提供给想要阅读源码的中文学习者
