### ISSUE TITLE
Neo4j Desktop 1.1.15 installs OK but will not start on Windows 7 Ultimate N SP1

### ISSUE THREAD

**Issue by ma2ts** [neo4j/neo4j#12166]
Have been happily running Neo4j Desktop 1.1.10 (with its various updates) since October 2018.

Updated today through the GUI to version 1.1.15 and now Neo4j Desktop will not launch at all. Or to be more precise, the "Neo4j Desktop.exe" process(es) do start (2 are listed in Task Manager, one using c.82K memory, one using c.5K memory) but the GUI itself simply does not appear.

Tried rebooting PC (made no difference). Tried fully uninstalling and then re-installing 1.1.15 (still no difference).

**Comment by oskarhane** [comment]
Hi, I'm sorry to hear that @ma2ts.
This is however the wrong repo for Neo4j Desktop issues.

Could you re-open this issue over in https://github.com/neo4j-apps/neo4j-desktop and also add more info on your environment (Windows version, account type etc) and we'll try to figure out what's going on.
