### ISSUE TITLE
Fresh installation of Neo4J 3.5.3 Community Edition does not work

### ISSUE THREAD

**Issue by antoniocicchetti** [neo4j/neo4j#12162]
I just downloaded and uncompressed the TAR archive for Mac OS systems containing the Neo4J Sever Community edition version 3.5.3. As per instructions, I set an appropriate environment variable for NEO4J_HOME and tried to run ./bin/neo4j console, however I get the following error, that seems related to SSL configuration. I tried to run the command as root, re-download the TAR, and also to download a different version, but I get exactly the same issue.

**Neo4j Version:** 3.5.3  
**Operating System:** Mac OS Hig Sierra

### Steps to reproduce
1. Download the installation archive for Mac OS
2. Untar the archive at <NEO4J_HOME>
3. Set an appropriate environment variable for NEO4J_HOME
4. cd $NEO4J_HOME
5. ./bin/neo4j console
![screenshot 2019-02-18 16 26 50](https://user-images.githubusercontent.com/1730012/53093940-15572d00-3519-11e9-83eb-b68ea84710c3.png)

**Comment by florinpatrascu** [comment]
@antoniocicchetti - it seems to work. I followed exactly the steps you described above, and the server started properly. Excerpt:

```
$ export $NEO4J_HOME=/Users/florin/Downloads/neo4j-community-3.5.3
$ cd $NEO4J_HOME
~/Downloads/neo4j-community-3.5.3 $ ./bin/neo4j console
Active database: graph.db
Directories in use:
  home:         /Users/florin/Downloads/neo4j-community-3.5.3
  config:       /Users/florin/Downloads/neo4j-community-3.5.3/conf
  logs:         /Users/florin/Downloads/neo4j-community-3.5.3/logs
  plugins:      /Users/florin/Downloads/neo4j-community-3.5.3/plugins
  import:       /Users/florin/Downloads/neo4j-community-3.5.3/import
  data:         /Users/florin/Downloads/neo4j-community-3.5.3/data
  certificates: /Users/florin/Downloads/neo4j-community-3.5.3/certificates
  run:          /Users/florin/Downloads/neo4j-community-3.5.3/run
Starting Neo4j.
2019-02-23 15:11:18.372+0000 INFO  ======== Neo4j 3.5.3 ========
2019-02-23 15:11:18.383+0000 INFO  Starting...
2019-02-23 15:11:20.728+0000 INFO  Bolt enabled on 127.0.0.1:7687.
2019-02-23 15:11:22.093+0000 INFO  Started.
2019-02-23 15:11:22.928+0000 INFO  Remote interface available at http://localhost:7474/
```

My Java version: 
```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by antoniocicchetti** [comment]
@florinpatrascu thanks for your feedback. I have updated the OS to Mojave and installed JDK version 11, but I had no luck. I still get the same issue with SslPolicyConfig, I wonder if I should clean-up some Neo4J configuration files to get it to work.

Thanks,
                                                      Antonio

**Comment by florinpatrascu** [comment]
can you try starting neo4j with its original config file (conf/neo4j.conf)? Maybe your current SSL policy configuration is borked? Here's the relevant section from a default neo4j.conf file, for brevity: 

```ini
#*****************************************************************
# SSL system configuration
#*****************************************************************

# Names of the SSL policies to be used for the respective components.

# The legacy policy is a special policy which is not defined in
# the policy configuration section, but rather derives from
# dbms.directories.certificates and associated files
# (by default: neo4j.key and neo4j.cert). Its use will be deprecated.

# The policies to be used for connectors.
#
# N.B: Note that a connector must be configured to support/require
#      SSL/TLS for the policy to actually be utilized.
#
# see: dbms.connector.*.tls_level

#bolt.ssl_policy=legacy
#https.ssl_policy=legacy

#*****************************************************************
# SSL policy configuration
#*****************************************************************

# Each policy is configured under a separate namespace, e.g.
#    dbms.ssl.policy.<policyname>.*
#
# The example settings below are for a new policy named 'default'.

# The base directory for cryptographic objects. Each policy will by
# default look for its associated objects (keys, certificates, ...)
# under the base directory.
#
# Every such setting can be overridden using a full path to
# the respective object, but every policy will by default look
# for cryptographic objects in its base location.
#
# Mandatory setting

#dbms.ssl.policy.default.base_directory=certificates/default

# Allows the generation of a fresh private key and a self-signed
# certificate if none are found in the expected locations. It is
# recommended to turn this off again after keys have been generated.
#
# Keys should in general be generated and distributed offline
# by a trusted certificate authority (CA) and not by utilizing
# this mode.

#dbms.ssl.policy.default.allow_key_generation=false

# Enabling this makes it so that this policy ignores the contents
# of the trusted_dir and simply resorts to trusting everything.
#
# Use of this mode is discouraged. It would offer encryption but no security.

#dbms.ssl.policy.default.trust_all=false

# The private key for the default SSL policy. By default a file
# named private.key is expected under the base directory of the policy.
# It is mandatory that a key can be found or generated.

#dbms.ssl.policy.default.private_key=

# The private key for the default SSL policy. By default a file
# named public.crt is expected under the base directory of the policy.
# It is mandatory that a certificate can be found or generated.

#dbms.ssl.policy.default.public_certificate=

# The certificates of trusted parties. By default a directory named
# 'trusted' is expected under the base directory of the policy. It is
# mandatory to create the directory so that it exists, because it cannot
# be auto-created (for security purposes).
#
# To enforce client authentication client_auth must be set to 'require'!

#dbms.ssl.policy.default.trusted_dir=

# Client authentication setting. Values: none, optional, require
# The default is to require client authentication.
#
# Servers are always authenticated unless explicitly overridden
# using the trust_all setting. In a mutual authentication setup this
# should be kept at the default of require and trusted certificates
# must be installed in the trusted_dir.

#dbms.ssl.policy.default.client_auth=require

# It is possible to verify the hostname that the client uses
# to connect to the remote server. In order for this to work, the server public
# certificate must have a valid CN and/or matching Subject Alternative Names.

# Note that this is irrelevant on host side connections (sockets receiving
# connections).

# To enable hostname verification client side on nodes, set this to true.

#dbms.ssl.policy.default.verify_hostname=false

# A comma-separated list of allowed TLS versions.
# By default only TLSv1.2 is allowed.

#dbms.ssl.policy.default.tls_versions=

# A comma-separated list of allowed ciphers.
# The default ciphers are the defaults of the JVM platform.

#dbms.ssl.policy.default.ciphers=
```
HTH

**Comment by antoniocicchetti** [comment]
I am already running Neo4J with the default configuration file.

**Comment by antoniocicchetti** [comment]
As an update, I have made several tries and it looks like that when I set NEO4J_HOME to a **different** path than the one neo4j is installed, the server succeeds to run. I have tried on different paths, I have always the same phenomenon. Maybe some permission issue?

Regards,
                                                                    Antonio

**Comment by florinpatrascu** [comment]
@antoniocicchetti - are you still trying to install it in `/Applications`, as per your earlier screenshot?  If so, I am afraid that `/Applications` has a different type of permissions constraints than your own (user) folders i.e. such as the ones in `/Users/<your_user_name>`. If you insist your app to be in `Applications` folder, then at least use your own applications folder, as in `$HOME/Applications`. I'd also recommend creating a folder in your `/Users/<your_user_name>`, say: `tools`, and install the server in that folder. That's what I did, as you can see from my earlier post, and I never had any issues. Also, avoid using spaces in your folder's name; it's safer ;)

**Comment by antoniocicchetti** [comment]
@florinpatrascu - as written before I made several different tries, as suspecting the same problem that you described. I also noticed that when I run the server I get Neo4J version 3.2.0 running (please see the screenshot attached). Might it be some file of the old version that is creating this mess? I have tried to remove everything about the old installations but apparently something is still there.

Antonio
![screenshot 2019-03-07 16 16 45](https://user-images.githubusercontent.com/1730012/53966949-850e1000-40f4-11e9-9305-7bf0d41bb68e.png)

**Comment by mnd999** [comment]
Closing as 3.5 is no longer supported
