### ISSUE TITLE
ResourcesService.java references a non existent resource

### ISSUE THREAD

**Issue by makpcheng** [neo4j/neo4j#12161]
- Neo4j version: Community Edition 3.5.0
- Operating system: Any OS
- API/Driver: in the neo4j-server-3.**.jar file
- **Steps to reproduce**
1) Include neo4j jar and dependency jars in any war files WEB-INF/lib directory.
2) Deploy the war file in Websphere 8 or higher.
3) Websphere then attempts to preload all classes with JAX-RS annotation which ResourcesService.java falls into this category.
The static code block in ResourcesService.java attempts to load resource "htmlbrowse.js" which does not exist.

static
    {
        // FIXME This is so very ugly, it's because when running it with maven
        // it won't add the src/main/resources to the classpath
        String body = null;
        try
        {
            body = readResourceAsString( "htmlbrowse.js" );
        }
        catch ( Exception e )
        {
            body = readFileAsString( "src/main/resources/htmlbrowse.js" );
        }
        JAVASCRIPT_BODY = body;
    }

- Expected behavior
Should not throw an exception during jar file loading.

- Actual behavior
The following exception is thrown and the web application does not successfully start:
Caused by: java.io.FileNotFoundException: src/main/resources/htmlbrowse.js (No such file or directory)
	at java.io.FileInputStream.open(FileInputStream.java:212)
	at java.io.FileInputStream.<init>(FileInputStream.java:152)
	at java.io.FileInputStream.<init>(FileInputStream.java:104)
	at org.neo4j.server.rest.web.ResourcesService.readFileAsString(ResourcesService.java:68)
	... 24 more

Either the htmlbrowse.js file is really missing from the jar file (if it's really needed) or the ResourcesService.java is a garbage class and should be removed.

**Comment by chrisvest** [comment]
Thanks for the report. It'll be removed in the next 3.5 release.
