### ISSUE TITLE
How to add a base prefix to Neo4j bolt port?

### ISSUE THREAD

**Issue by DachuanZhao** [neo4j/neo4j#12165]
[https://stackoverflow.com/questions/49822502/adding-a-base-prefix-to-neo4j-bolt-port](https://stackoverflow.com/questions/49822502/adding-a-base-prefix-to-neo4j-bolt-port)

**Comment by technige** [comment]
@DachuanZhao We have no plans to implement configuration for this, but be aware that since the browser files are static, it should be possible to serve them from elsewhere by simply copying them.
