### ISSUE TITLE
IllegalAccessError from executing the algorithm

### ISSUE THREAD

**Issue by BrokenWingsIcarus** [neo4j/neo4j#12170]
When I use neo4j for source learning, I put the plugin into the folder of neo4j's plugin. I throw an error when calling the algorithm 'Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `algo.spanningTree.minimum`: Caused by : java.lang.IllegalAccessError: tried to access class org.neo4j.kernel.impl.newapi.Read from class org.neo4j.kernel.impl.newapi.InternalReadOps'
Neo4j source code version number: 4.3.12
Neo4j plugin version: 3.4.0
Java version number: 8u191
Operating system: windows 7

**Comment by BrokenWingsIcarus** [comment]
why?

**Comment by jexp** [comment]
Try to update the plugin to the last version for 3.4.x

There is not 4.3.12 so I guess that’s a typo.

**Comment by fickludd** [comment]
Hi @chinausers,

Since you have not written back, I'm going to assume @jexp suggestion solved your problem. Please reopen the issue if that is not the case.
