### ISSUE TITLE
Creating relations ships is very slow. I have 50, 000 nodes in the same label and creating relations ships is taking 20 minutes

### ISSUE THREAD

**Issue by happymishra** [neo4j/neo4j#12177]
Neo4j version: 4 i.e. latest one

Node structure: id:1; child: 2, 3, 4;

I have index on id

Create Relationship query:
         MATCH (n), (b)
        WHERE b.id IN n.child
        CREATE (n) - [:MADE_FROM] -> (b)

Here I have not mentioned the label in the Match as I have only one Label. 

This is the warning I am getting:

This query builds a cartesian product between disconnected patterns.
If a part of a query contains multiple disconnected patterns, this will build a cartesian product between all those parts. This may produce a large amount of data and slow down query processing. While occasionally intended, it may often be possible to reformulate the query that avoids the use of this cross product, perhaps by adding a relationship between the different parts or by using OPTIONAL MATCH (identifier is: (b))

Query plan

![QuerPlan](https://user-images.githubusercontent.com/8353529/54198436-7e184080-44ec-11e9-86dd-33a3618318f3.png)

**Comment by jexp** [comment]
But you don't use labels in your query so the index is not used:

try

```
MATCH (n:Label), (b:Label)
WHERE b.id IN n.child
CREATE (n) - [:MADE_FROM] -> (b)
```

**Comment by happymishra** [comment]
@jexp Thanks for the prompt reply. It does solves the issue and reduces the time considerably. 
Thanks once again.

**Comment by rajvaj** [comment]
I used label still very slow 
MATCH (a:Source), (b:Domain) WHERE a.Name = "X" AND b.Name = "Y"  CREATE (a)-[r: SRC_IMPACTED_BY]->(b)  RETURN a,b;

**Comment by jexp** [comment]
Did you create an constraint on :Source(Name) and :Domain(Name)?

**Comment by honeysabu** [comment]
MATCH (s:Student),(c:Course)
WHERE s.Name = "XXX" AND c.Name = "YYY"
CREATE (s)-[r:ATTENDS]->(c)
RETURN s,c,r

This query does not create a relationship and show 'This query builds a cartesian product between disconnected patterns.'

**Comment by jexp** [comment]
. Did you create the two constraints?
An no typos in property names (case sensitive) and values?

**Comment by honeysabu** [comment]
I already created Student and Course and no typos

**Comment by InverseFalcon** [comment]
Please double-check that you have an index or constraint on both `:Student(Name)` and `:Course(Name)`. Also please send a PROFILE plan of a run of the query, as that would show both the flow of rows during execution (this can show where rows drop to 0 and if indexes are being properly used).
