### ISSUE TITLE
Fulltext Index Allow Leading Wildcards

### ISSUE THREAD

**Issue by jastax** [neo4j/neo4j#12171]
Leading wilcards are not allowed on the fulltext index yet. It would be nice if they were allowed :-)
i. e.

**SimpleFullTextIndexReader.java**

 @Override
    public ScoreEntityIterator query( String queryString ) throws ParseException
    {
        MultiFieldQueryParser multiFieldQueryParser = new MultiFieldQueryParser( properties, analyzer );
        **multiFieldQueryParser.setAllowLeadingWildcard( true );**
        Query query = multiFieldQueryParser.parse( queryString );
        return indexQuery( query );
    }

**Comment by chrisvest** [comment]
Thanks for the suggestion. We will take a look.

**Comment by jastax** [comment]
Will this be included in the next update?

**Comment by jastax** [comment]
@chrisvest any update on this? I feel like this is a small but very important issue. I can't use the new indexes without this.

**Comment by chrisvest** [comment]
It's on the backlog. We have a lot of indexing related work going on.

**Comment by chrisvest** [comment]
Our next 3.5.x release will have this.

**Comment by Marc-Roth** [comment]
I also stumble very often across that one and can't find any notes about "fulltext starting with wildcard" in the change log [https://github.com/neo4j/neo4j/wiki/Neo4j-3.5-changelog](url)
Is it already released?
