### ISSUE TITLE
JVM bug causes wrong number of cores on import tool

### ISSUE THREAD

**Issue by dmsolow** [neo4j/neo4j#12176]
I'm trying to run the neo4j import tool (`neo4j-admin import`) in Kubernetes. The issue I'm running into is that the import tool uses `Runtime.getRuntime().availableProcessors()` to get the number of cores, and there's a JVM bug where this returns the wrong value in a Docker container.

There is a java setting (`XX:ActiveProcessorCount`) to override this value, and it works in my environment. So I'm wondering if there's a way to pass this setting to the import tool.

Any other ways to fix this problem would also be appreciated.

Thanks

**Comment by kcrimson** [comment]
JAVA_OPTS="-XX:ActiveProcessorCount [number of processors]" ./neo4j-admin import should help
