### ISSUE TITLE
Cannot set variable with a number at the beginning

### ISSUE THREAD

**Issue by toshiro92** [neo4j/neo4j#12173]
Hi !

When I've tried to add a node with variable `04061960804`, like below:

`CREATE (04061960804:Person { name: "Emil", from: "Sweden", klout: 99 })`

I have the following error:

> Neo.ClientError.Statement.SyntaxError: Invalid input '0': expected whitespace, a variable, node labels, a property map, ')' or org$neo4j$cypher$internal$v3_5$parser$Patterns$$PatternElement (line 1, column 9 (offset: 8))
> "CREATE (04061960804:Person { name: "Emil", from: "Sweden", klout: 99 })"

But when I add a chart in front of the numeric variable:

`CREATE (s04061960804:Person { name: "Emil", from: "Sweden", klout: 99 })`

The node is added into neo4j:
> Added 1 label, created 1 node, set 3 properties, completed after 184 ms.

Is it an excepted behavior ?

My Neo4j version is:

```
Version: 3.5.3
Edition: community
```

**Comment by chrisvest** [comment]
Yes, this is expected behaviour. Variable names must start with an alphabetic letter: https://neo4j.com/docs/cypher-manual/current/syntax/naming/

**Comment by casclayton** [comment]
@chrisvest thank you very much
