### ISSUE TITLE
can't backup on Kubernetes 

### ISSUE THREAD

**Issue by protheusfr** [neo4j/neo4j#12175]
Environment  : 
- Neo4j version: neo4j:3.3.6-enterprise
- Operating system: Docker version
- Kurbernetes : v1.13.3

From a container with the same image as Neo4j server (neo4j:3.3.6-enterprise) execture a command like : 
`/var/lib/neo4j/bin/neo4j-admin backup --from $NEO4J_HOST --backup-dir=/backup/ --name=test.backup`

- Expected behavior
Doing the backup

- Actual behavior
Backup command fail with the following message : `Backup failed: BackupClient could not connect from null to neo4j.prod.svc.cluster.local:6362`

This fail only when both server and backup client are deployed on Kubernetes cluster.  

The same command success if run from outside of the kubernetes cluster.  
From the POD point of view, everything seems normal : both client and server can resolve their hostname and remote hostname / IP.  
No NetworkPolicy deployed or nothing can block traffic, a telnet from client to server on port 6362 success.

**Comment by jexp** [comment]
did you see: https://medium.com/neo4j/how-to-backup-neo4j-running-in-kubernetes-3697761f229a

perhaps that helps.

**Comment by protheusfr** [comment]
Thank you Michael, but unfortunately no.
I had read this article, but it's not really useful.

I've not found the code portion that log `Backup failed: BackupClient could not connect from ` in the repo.  
I assume this part is probably not open sourced.  
I would like to understand why the log mention "null" as local hostname.  

Can you post (or send me) just the part of code that surround this message ?

**Comment by RagnarW** [comment]
Closing due to unsupported version
