### ISSUE TITLE
Neo4j Cluster Fails to Cluster After Restoring from Backup

### ISSUE THREAD

**Issue by detmitchell** [neo4j/neo4j#12183]
- Neo4j version: 3.2.2 Enterprise
- Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-1075-aws x86_64)
- Java
###Expected Behavior
Cluster should start and form after restoring from backup.
###Actual Behavior
Cluster fails to start and form after restoring from backup.

###Steps to reproduce
- Created Neo4j cluster with 3 CORE and 1 READ on EC2s
- Cluster started and clustered successfully with empty graph DB
- Stopped cluster and restored from backup by removing graph DB, copying backup from S3, and moving backup to graph DB location
- Restarted cluster, cluster is failing to form

After performing these steps, the instances starts but fails to cluster. Two of the core instances enter and remain in "Attempting to cluster" state, but the third encounters an error while clustering and bounces the service repeatedly. The instance that is failing to start can change each time the cluster is manually restarted (is not specific to any one core, a different one may be selected each time). I will include the logs.

LOGS FOR 2 INSTANCES THAT SUCCESSFULLY ENTER "WAITING TO CLUSTER"
![image](https://user-images.githubusercontent.com/9358258/54546644-1ccff180-4972-11e9-95f9-23282d1aaa65.png)

LOGS FOR THE INSTANCE THE ENTERS RESTART LOOP
![image](https://user-images.githubusercontent.com/9358258/54546660-28231d00-4972-11e9-8e95-a135ffb43b45.png)

**Comment by RagnarW** [comment]
Closing due to unsupported version
