### ISSUE TITLE
uninstall neo4j

### ISSUE THREAD

**Issue by SreenijaK** [neo4j/neo4j#12184]
First time i installed neo4j i changed it to bolt. later i uninstalled it and re-installed but still gives me bolt connector. How do i get it to default

**Comment by kcrimson** [comment]
how do you installed neo4j? From zip? or a package manager (like apt or yum)? Please also share OS details and version of neo4j.

**Comment by sherfert** [comment]
Hi @SreenijaK  . Without more information there is little we can do here. Please reopen this issue with more information.
