### ISSUE TITLE
Sharding in Neo4j is it possible

### ISSUE THREAD

**Issue by happymishra** [neo4j/neo4j#12180]
I have asked these question on stackoverflow. We are doing evaluation of database for our enterprises and would like to know if Neo4j supports these. Can you guys please respond

1. https://stackoverflow.com/questions/55193568/does-neo4j-supports-sharding
2. https://stackoverflow.com/questions/55163615/need-to-get-data-recursively-in-graphql

**Comment by kcrimson** [comment]
Neo4j does not support sharding. For high availability, the enterprise edition supports causal clustering, which supports a number of read-write "core servers" and multiple read-only "replica servers".
