### ISSUE TITLE
[QUESTION] Where I can find the CI service?

### ISSUE THREAD

**Issue by gustavosizilio** [neo4j/neo4j#12186]
Is this project using continuous integration services (e.g., Travis-CI or Jenkings)? Or has it used at any point of its lifetime?

**Comment by jimwebber** [comment]
Hello @gustavosizilio,

Neo4j is under Continuous Integration by the Neo4j core committers (mostly Neo4j employees). Any releases of the product are predicated on a green pipeline which includes a plethora of non-functional tests as well as functional and unit testing.

The CI service and test infrastructure is not public however.

**Comment by gustavosizilio** [comment]
Thank you very much!
