### ISSUE TITLE
How do the cypher execution plan to run?

### ISSUE THREAD

**Issue by ggservice007** [neo4j/neo4j#12190]
In the org.neo4j.cypher.internal.ExecutionEngine

```cmd
context.executingQuery().compilationCompleted(executableQuery.compilerInfo, supplier(executableQuery.planDescription()))
      executableQuery.execute(context, preParsedQuery, combinedParams)
```

I want the change the disk file to memory by using distributed memory.

I can not understand how the execute method invoke the functions related to disk.

Any ideas?

**Comment by chrisvest** [comment]
The store accesses happen at a _much_ lower level. You probably want to build an alternative implementation of `org.neo4j.io.pagecache.PageCache`, and make `PlatformModule.createPageCache` return your implementation.

**Comment by ggservice007** [comment]
I have read the source code for about two weeks. 
The PageCache does not meet our requirements.

Actually, I want to change the disk store with memory like RedisGraph.

**Comment by chrisvest** [comment]
Then I guess you want to reimplement the Kernel API: `org.neo4j.internal.kernel.api.Kernel`.

**Comment by ggservice007** [comment]
For example， 
```java
try(Transaction tx = graphDb.beginTx();
        Result result = graphDb.execute( "MATCH (n) RETURN n" )) {
  ...
}
```

After I debug, the program run to executableQuery.execute(context, preParsedQuery, combinedParams).

I can not find which class or method is invoked in the org.neo4j.internal.kernel.api.Kernel package.

**Comment by Jackge1979** [comment]
I also have this demand. @ggservice007 Is there any good idea? @chrisvest
