### ISSUE TITLE
Need progress bar on Neo4j-Admin Dump

### ISSUE THREAD

**Issue by bsquire0128** [neo4j/neo4j#12197]
This is a request.

Neo4j-admin dump can take a really long time. I have a 660 GB store size without any indexes added yet and don't have any idea when neo4j-admin dump will finish. 

Can a progress bar or read out like neo4j admin import be added to make it clear where the loading is at?

Also a page-cache, heap size recommendation for the dump like mem-rec would be useful.

**Comment by chrisvest** [comment]
Not a bad idea with a progress bar.

The dump command doesn't use any page cache memory, and very little heap memory. The performance is likely bound by either IO, or the performance of its gzip compressor.

**Comment by chrisvest** [comment]
Next 3.5 version should have much faster `dump` and `load` commands, with progress output.
