### ISSUE TITLE
dbms.security.changePassword

### ISSUE THREAD

**Issue by dineshlt** [neo4j/neo4j#12203]
Hi,

```
There is no procedure with the name `dbms.security.changePassword` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.
There already exists an index NODE:label[0](property[0], property[1]).
```

I am getting the above error While I migrate docker and neo4j using the below command

`sudo docker-compose exec neo4j migrate`

my docker and docker compose versions both are same which one is given below

`Docker version 18.09.5`

Kindly give me any needful suggestion.

Thanks...

**Comment by kcrimson** [comment]
Can you, please, follow our guidelines regarding issue reporting, we need more details to be able to help you. You will find issue template here, https://github.com/neo4j/neo4j/blob/3.5/ISSUE_TEMPLATE.md.

**Comment by sherfert** [comment]
Hi @dineshlt 
Without more information there is little we can do here. Please reopen this issue with more information.
