### ISSUE TITLE
COnfigure neo4j bolt URL on Loadbalancer

### ISSUE THREAD

**Issue by kamathsachin7** [neo4j/neo4j#12204]
Hi All,

Is there a way to configure neo4j bolt URL on loadbalancer ?

**Comment by kcrimson** [comment]
@kamathsachin7  Can you be more specific and provide more details? What load balancer? What is your setup and what you are trying to achieve at the end?

**Comment by sherfert** [comment]
Hi @kamathsachin7 . Without more information there is little we can do here. Please reopen this issue with more information.
