### ISSUE TITLE
Neo4J Version 3.5.4 Doesn't Use Index

### ISSUE THREAD

**Issue by scottmanny** [neo4j/neo4j#12209]
We have enterprise edition of 3.5.4 installed in a 5 core cluster (and/ 4 read nodes).  With this version we have noticed that Neo does not use the index whenever the parameters are in the WHERE IN clause of the query.  Please see the attached document for a very detailed and simple example.

The strange thing here is that we did not experience this slowness until just recently.  And now our entire system is unusable since we have a number of apps that use the WHERE IN clause.  The EC2 instances that our Neo4J database run on are at 100% CPU usage and some times cause neo itself to crash. Please give us some guidance as to how to address this and reach out if you have any questions.

Neo4j Version: 3.5.4-enterprise.
[Neo4J - Indexing Issue.pdf](https://github.com/neo4j/neo4j/files/3133726/Neo4J.-.Indexing.Issue.pdf)

**Comment by jexp** [comment]
Thanks a lot for the update.

It seems that for the query in 3.5 a different runtime is used, perhaps that's the reason.

Could you also share the expanded query planes (double arrow in lower right corner)

As a workaround, can you add an `USING INDEX myPartyInstance:PartyInstance(globalPartyIdentifier)` 
after the MATCH statement?

Is it correct that those are not constraints but just indexes?

Between 3.3 and 3.5 the index format changed for string, numeric, boolean, datetime and spatial types.

You might want to recreate the indexes on those databases.

**Comment by scottmanny** [comment]
Dropping and re-creating the indexes solved our problem!  Thank you so much for the fast response.

A couple of side notes
* Before the fix we did try specifically telling Neo to use the index to no avail.
* The index mentioned above was just an index (not a constraint)
* Since it's now working, I can't give you the expanded query planes, but they were complete label scans and were scanning tens of millions of nodes.

**Comment by jexp** [comment]
I guess something went wrong with the migration. Eg wrong selectivity information in your index. If you still have it around the not working store would be useful.
