### ISSUE TITLE
How to use gremlin plugin in neo4j 3.x?

### ISSUE THREAD

**Issue by zhujiajunup** [neo4j/neo4j#12213]
gremlin-plugin only support neo4j 2.x，I want to use gremlin plugin for neo4j server 3.4.11，how can I get a plugin for this version.

**Comment by kcrimson** [comment]
I see that you have opened the same issue at https://github.com/neo4j-contrib/gremlin-plugin/issues/43, I am closing this here, as neo4j-contrib is the right place to ask these kinds of questions
