### ISSUE TITLE
Window 10 cannot confirm path to store application data

### ISSUE THREAD

**Issue by lmei33** [neo4j/neo4j#12217]
-Neo4j version: desktop_offline_1.1.22

-Operating system: Windows 10 Pro

-Steps to reproduce

-Download Neo4j for Desktop from website
-Install as admin
-Open Neo4j for Desktop.
-Expected behavior - Neo4j for Desktop starts normally
-Actual behavior - I can pick a path to choose to store application data, but I cannot confirm as the confirm button doesn't work. I'm sure that I downloaded the latest version from the official website.

**Comment by oskarhane** [comment]
Hi @lmei33, could you open this issue over in https://github.com/neo4j-apps/neo4j-desktop instead and this is about Neo4j Desktop and not Neo4j itself.
Thanks.
