### ISSUE TITLE
Feature Request: Optional Name for Schema Indexes

### ISSUE THREAD

**Issue by mdfrenchman** [neo4j/neo4j#12219]
I noticed in looking at indexes for fulltext and explicit that they're named, and that schema ones show up with null for the name **on version 3.4.0** and in version 3.5.5 have place holder names like 'index_1' . It **might** (or might be a bag of worms) be useful to allow for regular property and composite indexes to be explicitly named as well. It would be an added benefit, in some cases, for schema management on graphs with a lot of indexes.
An example might be:
```cypher
CREATE INDEX 'PersonName' ON :Person(name)
CREATE CONSTRAINT 'PersonKey' ON (p:Person) ASSERT (p.Name) IS NODE KEY
```
OR similar to db.index.fulltext.createNodeIndex
```cypher
db.index.create(indexName, label, propertyNames)
```

While I couldn't find this feature request anywhere. It looks like based on 3.4 => 3.5.5  internal team is possibly moving in this direction anyway.

**Comment by chrisvest** [comment]
Yeah, our end-goal is to make the name mandatory.

**Comment by mdfrenchman** [comment]
Excellent! Should I close this issue then?

**Comment by Hunterness** [comment]
Hi, 

In 4.0 there will be possible to give schema indexes (and constraints) names, but not yet mandatory to do so. We have also updated the syntax for creating indexes and deprecated the old syntax.

The syntax will be (with the name being optional):

```
CREATE INDEX name FOR (n:Label) ON (n.property)
CREATE CONSTRAINT name ON (p:Person) ASSERT (p.name) IS NODE KEY
```

There will also be possible (and preferred) to drop indexes and constraints using their names

```
DROP INDEX name
DROP CONSTRAINT name
```

All the old `DROP` commands using the index/constraint schema will also be deprecated. 

Best Regards,
Therese

**Comment by mdfrenchman** [comment]
That's SO much nicer! Thanks!
