### ISSUE TITLE
Different behavior between Windows Neo4j and docker version when using UNION

### ISSUE THREAD

**Issue by Draluy** [neo4j/neo4j#12216]
Using neo4j version 3.5.5, if I play a certain request on an empty database, I end up with a different node count between windows and the docker image.

The windows version is the one embedded with Neo4J desktop  1.1.22, which is 3.5.5
The docker version is pulled using a docker compose image with the command `image: neo4j:3.5.5`

In both cases I used the Neo4J browser : http://localhost:7474/browser/

### Steps to reproduce
1. Play the request below using the browser on an empty database ("Enable multi statement query editor" must be activated):

```
MATCH (n)
DETACH DELETE n;

:param {list:[{"members":["toto","titi"],"id":"1"}]};

unwind {list} as element
  create (assocNode { id: element.id })
  return 1

UNION

unwind {list} as element
  match(assocNode{id:element.id})
  with element
  unwind element.members as member
  create (memberNode)
  return 1
 
```

2.Check the number of nodes in the database. You could use this query:

`MATCH (n)
RETURN count(n) as count`

### Expected behavior
There should be the same number of nodes

### Actual behavior
There is 1 node in the windows version, and 3 in the docker image version.

### Additional notes

If, instead of using a UNION, you play the two parts of the query consecutively, then the two versions of the database behave the same.

Also, I don't think this is related to a specific version, this behavior seemed to be the same with version 3.5.3.

**Comment by Hunterness** [comment]
Hi, thanks for reporting, we will look into it

/Team Cypher

**Comment by InverseFalcon** [comment]
Not on the Cypher team, but I don't think we've provided any guarantees about the order of execution when performing a UNION of multiple queries. 

It generally isn't advised to have this kind of query, where one query in the union depends on the data added in the execution of the other query. I'd chalk this up to a misuse of UNION here. In this case you should probably execute these as two separate Cypher queries.

**Comment by sherfert** [comment]
@Draluy The comment above is completely right. You cannot make any assumptions about which side of a UNION gets to get executed first, or even if the executions are intermingled. Even when the assumption that the left side executes before the right side holds _often_, it does not hold in general.
If you write queries where the left side and the right side of a union have dependencies on each other, that will result in undefined behavior.

To avoid that, issue two consecutive queries instead.

**Comment by Draluy** [comment]
Understood, thx.
