### ISSUE TITLE
headers incorrect order after apoc csv export in enterprise edition 3.5.4, 3.5.5

### ISSUE THREAD

**Issue by borick** [neo4j/neo4j#12210]
- Neo4j version: >= 3.5.4 - only happens in the enterprise edition, not the community edition! (also happens on 3.5.5)
- Operating system: Tested on MacOSX, Ubuntu
- API/Driver: (for example Cypher/Java API/Python driver vX.Y.Z) - apoc-3.5.0.3-all.jar
- steps to reproduce - 

1) We have a specific database here when we do an apoc query similar to this: 
`CALL apoc.export.csv.query("MATCH (n:Document {pk:'5921569'}) return n.pk as pk, n.copyright as copyright", "/tmp/out.csv", {})` - the headers in the export are reversed, 
e.g. in the file out.csv we see:
Note: Using the apoc.export.csv.query is required to reproduce the bug.

```
"copyright","pk"
"5921569","
(c) 2018 Hovsepian, Albanese, et al. ""ASCB(r),"" ""The American Society for Cell Biology(r),"" and ""Molecular Biology of the Cell(r)"" are registered trademarks of The American Society for Cell Biology.
2018

This article is distributed by The American Society for Cell Biology under license from the author(s). Two months after publication it is available to the public under an Attribution-Noncommercial-Share Alike 3.0 Unported Creative Commons License.

"
```

2) Afterwards, when we query the Neo4j via Browser, we can see the same output without APOC call e.g. just MATCH (n:Document {pk:'5921569'}) return n.pk as pk, n.copyright as copyright in the browser

```
╒═══════════╤══════════════════════════════════════════════════════════════════════╕
│"copyright"│"pk"                                                                  │
╞═══════════╪══════════════════════════════════════════════════════════════════════╡
│"5921569"  │"
(c) 2018 Hovsepian, Albanese, et al. "ASCB(r)," "The American Societ│
│           │y for Cell Biology(r)," and "Molecular Biology of the Cell(r)" are reg│
│           │istered trademarks of The American Society for Cell Biology.
2018

Thi│
│           │s article is distributed by The American Society for Cell Biology unde│
│           │r license from the author(s). Two months after publication it is avail│
│           │able to the public under an Attribution-Noncommercial-Share Alike 3.0 │
│           │Unported Creative Commons License.

"                                 │
└───────────┴──────────────────────────────────────────────────────────────────────┘
```
Note: the data here contains a " and \n in the output,but using similar nodes with similar data, was unable to reproduce it.
3) if we restart the neo4j service, the query in browser returns the header in the correct order
- Expected behavior
Headers are displayed correctly in export and browser (even after using apoc export)
- Actual behavior
Headers are in the wrong order for certain pieces of data (after using the apoc export)

**Comment by jexp** [comment]
For apoc can you raise the issue at github.com/neo4j-contrib/neo4j-apoc-procedures
In APOC recently implemented a feature request to sort headers, but that was only meant for the graph export not for queries.

**Comment by borick** [comment]
> For apoc can you raise the issue at github.com/neo4j-contrib/neo4j-apoc-procedures
> In APOC recently implemented a feature request to sort headers, but that was only meant for the graph export not for queries.

I have raised it there as https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1188 - thank you. let me know if anything else is needed.
