### ISSUE TITLE
Min() is broken?

### ISSUE THREAD

**Issue by bsquire0128** [neo4j/neo4j#12224]
To help us understand your issue, please specify important details, primarily:

- Neo4j version: 
3.5.5 Enterprise
- Operating system: Linux 
- **Steps to reproduce**
In some cases min always returns first position. This is especially problematic with instances where you want the min between two nodes such as the last example.
###Doesn't work
return min(6,4)
6
###Works
return min(6.0,4.0)
4.0
###Works
UNWIND [6,4] as val
RETURN min(val)
4
##Doesn't work
Match (c1:Collision)-->(c2:Collision) where id(c1) < id(c2) return id(c1),id(c2), min(id(c2),id(c1)) as min limit 10
- Expected behavior
min(6,4)
4
min(6.0,4.0)
4.0
Match (c1:Collision)-->(c2:Collision) where id(c1) < id(c2) return id(c1),id(c2), min(id(c2),id(c1)) as min limit 10
id(c1)

**Comment by jexp** [comment]
`min` is an aggregation function it should only take a single parameter.

There is no traditional min function, you can use `apoc.coll.min([1,2,3])`

**Comment by bsquire0128** [comment]
well it does not give an error when multiple values are given and when they are specified as floats with .0 then it gives the correct answer. Not sure if that is intended.

**Comment by jexp** [comment]
nope that's the actual bug :)

**Comment by sherfert** [comment]
Hi @bsquire0128 
We are aware of the situation that min/max can take more than 1 parameter. Unfortunately we cannot fix it in 3.5 without breaking queries where people did pass in multiple arguments (although it is likely that then the query does not what they want).
It will be fixed in the next mayor release, 4.0.
