### ISSUE TITLE
Edge ID is the same if two nodes are connected multiple times

### ISSUE THREAD

**Issue by ghost** [neo4j/neo4j#12229]
Neo4j Desktop 1.1.15

### LIST API call on relationships

[
    {
        "id": "104",
        "a_uid": "bf1b364d8b084f46ac42083a8a75ad95",
        "b_uid": "e22d5b5b577a400faf93b724aafa23b1"
    },
    {
        "id": "104",
        "a_uid": "bf1b364d8b084f46ac42083a8a75ad95",
        "b_uid": "e22d5b5b577a400faf93b724aafa23b1"
    },
    {
        "id": "104",
        "a_uid": "bf1b364d8b084f46ac42083a8a75ad95",
        "b_uid": "e22d5b5b577a400faf93b724aafa23b1"
    },
    {
        "id": "104",
        "a_uid": "bf1b364d8b084f46ac42083a8a75ad95",
        "b_uid": "e22d5b5b577a400faf93b724aafa23b1"
    },
    {
        "id": "104",
        "a_uid": "bf1b364d8b084f46ac42083a8a75ad95",
        "b_uid": "e22d5b5b577a400faf93b724aafa23b1"
    },
    {
        "id": "104",
        "a_uid": "bf1b364d8b084f46ac42083a8a75ad95",
        "b_uid": "e22d5b5b577a400faf93b724aafa23b1"
    }
]

### Two relationships same edge id

(Pdb) relationships[0].id
104
(Pdb) relationships[1].id
104

(Pdb) relationships[0].start_node()
<A: {'uid': 'bf1b364d8b084f46ac42083a8a75ad95', 'created_at': datetime.datetime(2019, 5, 19, 20, 51, 28, 944089, tzinfo=<UTC>), 'updated_at': datetime.datetime(2019, 5, 19, 20, 51, 30, 887846, tzinfo=<UTC>),  'id': 90}>
(Pdb) relationships[1].start_node()
<A: {'uid': 'bf1b364d8b084f46ac42083a8a75ad95', 'created_at': datetime.datetime(2019, 5, 19, 20, 51, 28, 944089, tzinfo=<UTC>), 'updated_at': datetime.datetime(2019, 5, 19, 20, 51, 30, 887846, tzinfo=<UTC>),  'id': 90}>

(Pdb) relationships[0].end_node()
<B: {'uid': 'e22d5b5b577a400faf93b724aafa23b1', 'created_at': datetime.datetime(2019, 5, 19, 20, 51, 23, 831198, tzinfo=<UTC>), 'updated_at': datetime.datetime(2019, 5, 19, 20, 51, 26, 423874, tzinfo=<UTC>),  'id': 71}>
(Pdb) relationships[1].end_node()
<B: {'uid': 'e22d5b5b577a400faf93b724aafa23b1', 'created_at': datetime.datetime(2019, 5, 19, 20, 51, 23, 831198, tzinfo=<UTC>), 'updated_at': datetime.datetime(2019, 5, 19, 20, 51, 26, 423874, tzinfo=<UTC>), 'id': 71}>

**Comment by sherfert** [comment]
Hello @HashRocketSyntax . Are you referring to the REST API, i.e. http://localhost:7474/db/data/node/xx/relationships/all ? Or is it another API you are using? Please also provide whatever commands you ran previous, or instructions how to get the database into the state it is in. Otherwise it is impossible for us to reproduce this.

**Comment by sherfert** [comment]
@HashRocketSyntax please comment with the required information above and we will reopen the issue.
