### ISSUE TITLE
Pagecache warmup significantly slower on v3.5.5

### ISSUE THREAD

**Issue by swayam18** [neo4j/neo4j#12228]
After upgrading to 3.5.5 from 3.4.14 pagecache warmup takes considerably longer. I investigated this using iostat and I'll show my findings here:

Neo4j version: 3.5.5 (enterprise)
OS: Ubuntu 18.04

### Steps to reproduce
1. Setup neo4j 3.4.14
2. Seed neo4j with atleast 100GB of data
3. Stop neo4j
4. Start neo4j, while running `iostat -m 1 -x`
5. Note down `r/s, rMB/s, aqu-sz, rareq-sz` (read iops, read MBps, average queue size and average request size)
6. Repeat steps 1 - 5 with Neo4j 3.5.5

### Expected behavior
The iostats should be similar

### Actual behavior
Neo4j 3.5.6 iostats are much slower while warming page cache. We noticed that the average request size is 4-10 times smaller, average queue size hover around 1 and throughput is 8 times slower. 

Note: we ran this on identical hardware, so it doesn't seem to be a hardware issue.

**Comment by swayam18** [comment]
Did the kernel team manage to reproduce this problem @sherfert ?

**Comment by chrisvest** [comment]
You should have an INFO log line that looks like `Page cache warmup completed. %d pages loaded. Duration: %s.` Can you find it in the debug.log?

**Comment by chrisvest** [comment]
Pretty much the only thing that changed in the page cache warmup code between 3.4 and 3.5, is that we now print that log line.

I'm thinking that perhaps the upgrade misplaced the profile files, and therefore don't know what to read back in during warmup.

**Comment by chrisvest** [comment]
I will close this for now. Please reopen if it is still an issue and there is more information to shed light on the problem.
