### ISSUE TITLE
Neo.DatabaseError.General.UnknownError: NOT PART OF CHAIN!

### ISSUE THREAD

**Issue by Ashwanthkumard** [neo4j/neo4j#12234]
I am facing the following issue when trying to run a simple query as follow:
`MATCH (s)-[:HAS_PROFILE]->(p)
WHERE p.id='XXXX' RETURN s`

Issue:
`Neo.DatabaseError.General.UnknownError: NOT PART OF CHAIN! RelationshipTraversalCursor[id=70577, open state with: denseNode=false, next=70577, mode=regular, underlying record=Relationship[70577,used=false,source=68813,target=71331,type=14,sCount=26,sNext=55067,tCount=2,tNext=70529,prop=-1,secondaryUnitId=-1, sFirst, tFirst]]`

How can I fix this? Pretty sure the issue is not because of error. Stuck with the issue.

**Comment by fickludd** [comment]
Hey @Ashwanthkumard,

That error could indicate that you have a corrupt store. Could you run the consistency checker and report any findings here? https://neo4j.com/docs/operations-manual/current/tools/consistency-checker/

**Comment by Ashwanthkumard** [comment]
@fickludd
Here is the consistencty checker report:

```
> ERROR: The next record in the source chain is a relationship between two other nodes.
> 	Relationship[80071,used=true,source=2899,target=4939,type=11,sPrev=106092,sNext=70577,tPrev=80435,tNext=80111,prop=-1,secondaryUnitId=-1,!sFirst,!tFirst]
> 	Inconsistent with: Relationship[70577,used=false,source=68813,target=71331,type=14,sCount=26,sNext=55067,tCount=2,tNext=70529,prop=-1,secondaryUnitId=-1, sFirst, tFirst]
> ERROR: The next record in the target chain is a relationship between two other nodes.
> 	Relationship[80111,used=true,source=4939,target=2501,type=1,sPrev=80071,sNext=-1,tPrev=106093,tNext=70581,prop=-1,secondaryUnitId=-1,!sFirst,!tFirst]
> 	Inconsistent with: Relationship[70581,used=false,source=18927,target=71367,type=13,sPrev=75870,sNext=61089,tCount=2,tNext=70603,prop=-1,secondaryUnitId=-1,!sFirst, tFirst]
> ERROR: The previous record in the target chain is a relationship between two other nodes.
> 	Relationship[80071,used=true,source=2899,target=4939,type=11,sPrev=106092,sNext=70577,tPrev=80435,tNext=80111,prop=-1,secondaryUnitId=-1,!sFirst,!tFirst]
> 	Inconsistent with: Relationship[80435,used=false,source=60318,target=71219,type=14,sCount=15,sNext=82385,tPrev=77143,tNext=-1,prop=-1,secondaryUnitId=-1, sFirst,!tFirst]
> ERROR: The relationship count does not correspond with the expected count.
> 	CountsEntry[RelationshipKey[(:label=9)-[:type=11]->()]: 4232]
> 	Inconsistent with: 4233
> ERROR: The relationship count does not correspond with the expected count.
> 	CountsEntry[RelationshipKey[(:label=9)-->()]: 10843]
> 	Inconsistent with: 10844
> ERROR: The relationship count does not correspond with the expected count.
> 	CountsEntry[RelationshipKey[(:label=19)-->()]: 1079]
> 	Inconsistent with: 1080
> ERROR: The relationship count does not correspond with the expected count.
> 	CountsEntry[RelationshipKey[()-[:type=1]->(:label=3)]: 4230]
> 	Inconsistent with: 4231
> ERROR: The relationship count does not correspond with the expected count.
> 	CountsEntry[RelationshipKey[()-[:type=1]->()]: 4230]
> 	Inconsistent with: 4231
> ERROR: The relationship count does not correspond with the expected count.
> 	CountsEntry[RelationshipKey[()-[:type=11]->()]: 4232]
> 	Inconsistent with: 4233
> ERROR: The relationship count does not correspond with the expected count.
> 	CountsEntry[RelationshipKey[()-->(:label=3)]: 4300]
> 	Inconsistent with: 4301
> ERROR: The relationship count does not correspond with the expected count.
> 	CountsEntry[RelationshipKey[()-->(:label=19)]: 632]
> 	Inconsistent with: 633
> ERROR: The relationship count does not correspond with the expected count.
> 	CountsEntry[RelationshipKey[()-->()]: 75273]
> 	Inconsistent with: 75275
> ERROR: The relationship key entries in the store does not correspond with the expected number.
> 	CountsEntry[RelationshipKey[()-->()]: 181]
> 	Inconsistent with: 183
> WARN : Inconsistencies found: ConsistencySummaryStatistics{
> 	Number of errors: 13
> 	Number of warnings: 0
> 	Number of inconsistent RELATIONSHIP records: 3
> 	Number of inconsistent COUNTS records: 10
> }
```

How can I fix this???

**Comment by tinwelint** [comment]
Which version was this produced on? Also was this store migrated or similar?

**Comment by timholds** [comment]
Having the same issue on 3.5.9 CE. Any suggestions on how to fix a seemingly corrupted db?

**Comment by Chikuid** [comment]
For query `MATCH p=(:NODE)-[r:RELATION]->(:NODE) RETURN count(p)`

Error:
`Neo.DatabaseError.General.UnknownError: NOT PART OF CHAIN! RelationshipTraversalCursor[id=5993795, open state with: denseNode=false, next=5993795, mode=regular, underlying record=Relationship[5993795,used=true,source=716320,target=13334040,type=0,sPrev=6415816,sNext=5292787,tPrev=5993802,tNext=5993768,prop=25580899,secondaryUnitId=-1,!sFirst,!tFirst]]`

1. I created the database using `neo4j-admin import`
2. Then was populating relationships using `LOAD CSV`
3. Database crashes and after i restart it I get the above error.

**Comment by tinwelint** [comment]
I'm sorry to have dropped this issue. Any chance to get access to corrupted database plus transaction logs for investigation? I realize the chance is slim at this point tho.

**Comment by tinwelint** [comment]
Any response or possibility of the store(s) still in existence? Otherwise I'll close this.

**Comment by Chikuid** [comment]
Unfortunately I do not have corrupted database. You can close this if you want to.

**Comment by tinwelint** [comment]
OK, then there's nothing I can I'm afraid
