### ISSUE TITLE
When using ArrayList for relationships, the order of the first two entities is wrong

### ISSUE THREAD

**Issue by cosminmerlusca** [neo4j/neo4j#12235]
-Neo4J version: 3.4.0
- Operating system: Windows 10
- API / Driver : Java API
- Steps to reproduce:

If I define the following:

@NodeEntity
public class Entity1 {
  @Id @GeneratedValue private Long id;
  @Relationship(type = "MY_RELATIONSHIP", direction = Relationship.OUTGOING)
  private ArrayList<MyRelationship> entries;
}

@NodeEntity
public class Entity2 {
  @Id @GeneratedValue private Long id;
}

@RelationshipEntity(type = "MY_RELATIONSHIP")
public class MyRelationship
    implements Comparable<MyRelationship> {
  @Id @GeneratedValue private Long id;
  @StartNode private Entity1 entity1;
  @EndNode private Entity2 entity2;
  @Property private Integer ordering;

  @Override
  public int compareTo(MyRelationship o) {
    return ComparisonChain.start()
        .compare(this.ordering, o.ordering)
        .result();
  }
}

If I run a query like:

  @Query(
      "MATCH (e1:Entity1)-[r:MY_RELATIONSHIP]->:Entity2)\n"
          + "WHERE e1.id = {0}\n"
          + "RETURN e1, r, e2\n"
          + "ORDER BY r.ordering")
  Entity1 findByEntity1Id(long id);

- Expected behavior:
I would get in the entries ArrayList the sorted entity2 entities.

- Actual behavior:
The first two entities are switched.

This is caused by the org.neo4j.ogm.metadata.reflect.EntityAccessManager#union method. The logic in
        if (hydrated.size() > collection.size()) {
            result.addAll(hydrated);
            addToCollection(collection, result, elementType);
        } else {
            addToCollection(collection, result, elementType);
            addToCollection(hydrated, result, elementType);
        }
makes it so that whenever the second entity is added, because the hydrated and collection size are equal, the second entity will be added in the beginning of the result ArrayList.

Workaround: If instead of using ArrayList I use a TreeSet this is no longer an issue. 

However, for an ArrayList the issue is present. 
Proposed solutions: One possible solution would be getting rid of the if and always add the new elements at the end of the result. I understand that this could raise some performance issue if the result is big. 
In that case, using the following condition:
if (hydrated.size() >= collection.size()) should solve the problem without adding any performance overhead.

**Comment by sherfert** [comment]
@cosminmerlusca Can you please reopen the issue in https://github.com/neo4j/neo4j-ogm ?
