### ISSUE TITLE
OPTIONAL keywords not working as expected.

### ISSUE THREAD

**Issue by mangesh001** [neo4j/neo4j#12245]
- Neo4j version: 3.2.15
- Operating system: mac
- **Steps to reproduce**
This are my two query : 
Query 1
`OPTIONAL MATCH (persons:Person)
                                    -[:HAS_ORDER]->(orders:Order)
RETURN COUNT(DISTINCT orders)`
and Query 2
`MATCH (persons:Person)
                                    -[:HAS_ORDER]->(orders:Order)
RETURN COUNT(DISTINCT orders)`

both are giving different result
query 1 returns 12873 and query 2 returns 238

**Comment by sherfert** [comment]
Hi @mangesh001.

How did you setup the graph? Could you provide a `CREATE` query or upload the dataset?

**Comment by SaschaPeukert** [comment]
+1 on what @sherfert said, please provide us with any means to reproduce the problem.

Also @mangesh001 , could you please tell us if you were using Community or Enterprise edition?

**Comment by sherfert** [comment]
This has been opened for 4 weeks without providing instructions for reproduction. Feel free to re-open at any time with further instructions.
