### ISSUE TITLE
Can NOT recover data after encountering "too many files" error

### ISSUE THREAD

**Issue by hiiwave** [neo4j/neo4j#12258]
I encountered "too many files error" upon starting my database, which had run over months, just as #12050. However, it's not possible for me the increase the hard-limit of opened files (`ulimit -Hn`), which is set to 10240, as I'm not the administrator of the server I'm using. That it, I'm facing the same situation as [this thread](https://groups.google.com/forum/#!topic/neo4j/wKFAD2lqv-M).

Theoretically, I can avoid this issue in the future by partitioning my dataset into multiple ones. However the serious problem I'm facing now is that **I CANNOT recover my data**.

I tried `neo4j-admin dump` to dump graph.db, though I encountered [this issue](https://stackoverflow.com/questions/54081703/neo4j-admin-dump-is-failing) preventing me dumping. The solution, which suggests starting database and shutdown again, is sadly impossible, because I always face "too many files error" upon starting neo4j on this database.

**I expected there are ways to offline dumping the data into readable format to recover**. Is there any workaround for this? Thanks.

**Neo4j Version:** 3.5.4
**Operating System:** CentOS 7

**Comment by klaren** [comment]
To optimize IO performance we open multiple file descriptors per file. You can disable this by passing: 
```
-Dorg.neo4j.io.pagecache.implSingleFilePageSwapper.channelStripePower=0
```
to the JVM. Hopefully, this is enough so that you can actually start the database again.

**Comment by hiiwave** [comment]
@klaren Thanks for advising. Could you elaborate how I can do this? I'm currently start the database via command `bin/neo4j console`. I don't know how I can pass this option to the JVM.

**Comment by chrisvest** [comment]
Modify `neo4j.conf` to add another `dbms.jvm.additional` setting.

**Comment by hiiwave** [comment]
This works like a charm. Thanks a lot.
