### ISSUE TITLE
Fail to build the source code, Could not read licensing requirements file

### ISSUE THREAD

**Issue by severos** [neo4j/neo4j#12256]
I've installed a fresh copy of Ubuntu 18.04.2 Desktop AMDx64 in a VBox virtual machine (same problem happens on Windows, WSL, none VM installation of Ubuntu on 2 different machines)
-Installed git, maven, openjdk-8-jdk
-git clone  https://github.com/neo4j/neo4j.git
-changed java version to 1.8.0_222 using update-alternatives 
-cd into the directory 
-mvn clean install

However, it fails to compile and gives me this error:

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 30.098 s
[INFO] Finished at: 2019-08-05T06:53:55Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.neo4j.build.plugins:licensing-maven-plugin:1.7.7:check (list-all-licenses) on project neo4j-annotation-processors: Could not read licensing requirements file: licensing/licensing-requirements-base.xml: Cannot construct org.linuxstuff.mojo.licensing.model.CoalescedLicense as it does not have a no-args constructor : Cannot construct org.linuxstuff.mojo.licensing.model.CoalescedLicense as it does not have a no-args constructor
[ERROR] ---- Debugging information ----
[ERROR] message : Cannot construct org.linuxstuff.mojo.licensing.model.CoalescedLicense as it does not have a no-args constructor
[ERROR] cause-exception : com.thoughtworks.xstream.converters.reflection.ObjectAccessException
[ERROR] cause-message : Cannot construct org.linuxstuff.mojo.licensing.model.CoalescedLicense as it does not have a no-args constructor
[ERROR] class : org.linuxstuff.mojo.licensing.model.CoalescedLicense
[ERROR] required-type : org.linuxstuff.mojo.licensing.model.CoalescedLicense
[ERROR] converter-type : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
[ERROR] path : /licensing-requirements/coalesced-licenses/license
[ERROR] line number : 81
[ERROR] class[1] : java.util.HashSet
[ERROR] converter-type[1] : com.thoughtworks.xstream.converters.collections.CollectionConverter
[ERROR] class[2] : org.linuxstuff.mojo.licensing.model.LicensingRequirements
[ERROR] version : null
[ERROR] -------------------------------
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR] mvn -rf :neo4j-annotation-processors

I've already tried clearing cache and resetting environment to avoid any errors due to weird environment values. But still same error.

**Comment by chrisvest** [comment]
Sounds like a problem inside the plugin :man_shrugging:  Try with `-Dlicensing.skip=true`.

**Comment by severos** [comment]
I guess you're right, skipping the license made it pass that stage.
Now it's failing in the native index project because GBPTreeTest.cleanJobShouldNotLockOutClose and
GBPTreeTest.cleanJobShouldNotLockOutWriter are timing out (time elapsed is 5 seconds).
Should I close this issue and open another one for the new error?

**Comment by chrisvest** [comment]
We monitor and fix test failures in our own build matrices internally, so reporting them as bugs is not very interesting. Your virtual box might just be too slow. If they are blocking your work, you can increase their time-out, or disable them, in your branch.

**Comment by ray6080** [comment]
> Sounds like a problem inside the plugin 🤷‍♂ Try with `-Dlicensing.skip=true`.

I encountered the same problem. Is there any solution for the plugin?

**Comment by chrisvest** [comment]
I'm told Ubuntu by default has a fairly strange build of openjdk, and that the plugin don't know how to cope with that. You could try installing Java from a more respectable vendor. For instance, Azul Zulu, AdoptOpenJDK, RedHat, or Oracle.
