### ISSUE TITLE
Run the source code test to report an error - Lack of calss

### ISSUE THREAD

**Issue by crazyyanchao** [neo4j/neo4j#12263]
Lack of calss
```java
import org.neo4j.cypher.internal.v3_5.util.ArithmeticException;
import org.neo4j.cypher.internal.v3_5.util.CypherTypeException;
import org.neo4j.cypher.internal.v3_5.util.InvalidArgumentException;
import org.neo4j.cypher.internal.v3_5.util.ParameterWrongTypeException;
import org.neo4j.cypher.internal.runtime.QueryStatistics;
```
neo4j source code version:
```
<groupId>org.neo4j</groupId>
  <artifactId>parent</artifactId>
  <version>3.5.9-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>Neo4j</name>
  <description>Neo4j Graph Database</description>
  <inceptionYear>2002</inceptionYear>
  <url>http://neo4j.com/</url>
```

**Comment by sherfert** [comment]
Please look at the guideline how to format a bug report and which information to provide: https://github.com/neo4j/neo4j/blob/3.5/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by crazyyanchao** [comment]
> Please look at the guideline how to format a bug report and which information to provide: https://github.com/neo4j/neo4j/blob/3.5/.github/ISSUE_TEMPLATE/bug_report.md

@sherfert  As your say,it's not a bug.Just source code test not run.

**Comment by sherfert** [comment]
@crazyyanchao I do not understand the issue you are describing. What source code test is not run?

**Comment by xxks-kkk** [comment]
I run into similar issue I believe, when I load source code of neo4j into intellij, the IDE shows that 
`import org.neo4j.cypher.internal.runtime.QueryStatistics;` is not found for `RuntimeResult.java`. Do you have any suggestion what might happen here? @sherfert Thanks!

Neo4j commit id: 1a9468b0c3ee9c6070c68c33c6786ed01e11184c
