### ISSUE TITLE
How to set up remote debug?

### ISSUE THREAD

**Issue by crazyyanchao** [neo4j/neo4j#12261]
Such as this [Elasticsearch - Remote Debug](https://blog.csdn.net/superman_xxx/article/details/97810061)

**Comment by sherfert** [comment]
Have a look at the documentation for this: https://neo4j.com/docs/java-reference/current/server-debugging/

In the future, please ask usage questions in neo4j-users slack or on stackoverflow.

**Comment by crazyyanchao** [comment]
> Have a look at the documentation for this: https://neo4j.com/docs/java-reference/current/server-debugging/
> 
> In the future, please ask usage questions in neo4j-users slack or on stackoverflow.

@sherfert Thanks for your reply! :)
