### ISSUE TITLE
Trouble with APOC and Algorithm plugin installation in Neo4j installed in Ubuntu 14.0

### ISSUE THREAD

**Issue by shalini-nambiar-icf** [neo4j/neo4j#12264]
I'm trying to get the APOC and graph algorithm plugins on an Ubuntu neo4j installation. As per various other threads I've made sure that the following jar files are in the plugin in folder-
> apoc-3.5.0.4-all.jar
> neo4j-graph-algorithms-3.5.7.0-standalone.jar

The config file has been updated as follows-

**updated**: 

> dbms.security.procedures.unrestricted=apoc.*,algo.*

**un-commented** : 

> dbms.security.procedures.whitelist=apoc.coll.*,apoc.load.*

**checked the accuracy of**: 

> dbms.directories.plugins=/var/lib/neo4j/plugins

After restarting the server I'm testing the installation by running the query algo.list() and am receiving the error -
> There is no procedure with the name algo.list registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.

(I'm using the cypher shell to run the cypher query, the neo4j version is 3.5.8, Ubuntu version is 18.04.2 and I'm new to ubuntu and linux)

**Comment by chrisvest** [comment]
You need to use a graph algorithms library version that matches your Neo4j version, so for Neo4j 3.5.8, you need a 3.5.8.x version of the graph algorithms library. Version mismatches can prevent the library from being loaded, and then the procedures won't be available.

**Comment by shalini-nambiar-icf** [comment]
> You need to use a graph algorithms library version that matches your Neo4j version, so for Neo4j 3.5.8, you need a 3.5.8.x version of the graph algorithms library. Version mismatches can prevent the library from being loaded, and then the procedures won't be available.

Thanks Chris, but these were the latest releases I could find and I was under the impression that only the first 2 digits needed to match. Could you point me into the direction where I could find the 3.5.8 jar files?

**Comment by chrisvest** [comment]
On our download page: https://neo4j.com/download-center/

**Comment by shalini-nambiar-icf** [comment]
I've replaced the jar file with the one below from the download page and still receiving the same error.

> neo4j-graph-algorithms-3.5.8.0-standalone.jar

**Comment by jexp** [comment]
@shalini-nambiar-icf can you check /var/log/neo4j/debug.log to see if there are any errors reported?

Also did you check the read permissions? so that the `neo4j` user can read those files?
I case you copied them with root or such.

**Comment by sherfert** [comment]
Please attach the debug.log and then reopen the issue. Thanks,
