### ISSUE TITLE
Neo4j Transaction Retention Policy not adhering to setting; Enterprise 3.5.7

### ISSUE THREAD

**Issue by bsquire0128** [neo4j/neo4j#12273]
neo4j version: 3.5.7 Enterprise
neo4j.log and debug.log
I changed my configuration file to have the following transaction retention policy to avoid filling up my disk with old transactions.
`
dbms.tx_log.rotation.retention_policy=15 files
`
Here is what my graph.db folder currently looks like:
`
-rw-r--r-- 1 root root 259M Aug 19 16:00 neostore.transaction.db.1410                                                                                                                         [264/462]
-rw-r--r-- 1 root root 259M Aug 19 16:01 neostore.transaction.db.1411
-rw-r--r-- 1 root root 287M Aug 19 16:01 neostore.transaction.db.1412
-rw-r--r-- 1 root root 259M Aug 19 16:02 neostore.transaction.db.1413
-rw-r--r-- 1 root root 259M Aug 19 16:02 neostore.transaction.db.1414
-rw-r--r-- 1 root root 259M Aug 19 16:03 neostore.transaction.db.1415
-rw-r--r-- 1 root root 259M Aug 19 16:04 neostore.transaction.db.1416
-rw-r--r-- 1 root root 259M Aug 19 16:04 neostore.transaction.db.1417
-rw-r--r-- 1 root root 259M Aug 19 16:05 neostore.transaction.db.1418
-rw-r--r-- 1 root root 259M Aug 19 16:05 neostore.transaction.db.1419
-rw-r--r-- 1 root root 259M Aug 19 16:06 neostore.transaction.db.1420
-rw-r--r-- 1 root root 273M Aug 19 16:06 neostore.transaction.db.1421
-rw-r--r-- 1 root root 259M Aug 19 16:07 neostore.transaction.db.1422
-rw-r--r-- 1 root root 259M Aug 19 16:08 neostore.transaction.db.1423
-rw-r--r-- 1 root root 259M Aug 19 16:08 neostore.transaction.db.1424
-rw-r--r-- 1 root root 259M Aug 19 16:08 neostore.transaction.db.1425
-rw-r--r-- 1 root root 259M Aug 19 16:09 neostore.transaction.db.1426
-rw-r--r-- 1 root root 259M Aug 19 16:10 neostore.transaction.db.1427
-rw-r--r-- 1 root root 259M Aug 19 16:10 neostore.transaction.db.1428
-rw-r--r-- 1 root root 259M Aug 19 16:11 neostore.transaction.db.1429
-rw-r--r-- 1 root root 259M Aug 19 16:12 neostore.transaction.db.1430
-rw-r--r-- 1 root root 259M Aug 19 16:12 neostore.transaction.db.1431
-rw-r--r-- 1 root root 259M Aug 19 16:13 neostore.transaction.db.1432
-rw-r--r-- 1 root root 259M Aug 19 16:14 neostore.transaction.db.1433
-rw-r--r-- 1 root root 259M Aug 19 16:14 neostore.transaction.db.1434
-rw-r--r-- 1 root root 259M Aug 19 16:15 neostore.transaction.db.1435
-rw-r--r-- 1 root root 259M Aug 19 16:16 neostore.transaction.db.1436
-rw-r--r-- 1 root root 259M Aug 19 16:16 neostore.transaction.db.1437
-rw-r--r-- 1 root root 259M Aug 19 16:17 neostore.transaction.db.1438
-rw-r--r-- 1 root root 259M Aug 19 16:17 neostore.transaction.db.1439
-rw-r--r-- 1 root root 259M Aug 19 16:18 neostore.transaction.db.1440
-rw-r--r-- 1 root root 259M Aug 19 16:19 neostore.transaction.db.1441
-rw-r--r-- 1 root root 259M Aug 19 16:19 neostore.transaction.db.1442
-rw-r--r-- 1 root root 273M Aug 19 16:20 neostore.transaction.db.1443
-rw-r--r-- 1 root root 259M Aug 19 16:21 neostore.transaction.db.1444
-rw-r--r-- 1 root root 259M Aug 19 16:21 neostore.transaction.db.1445
-rw-r--r-- 1 root root 259M Aug 19 16:23 neostore.transaction.db.1446
-rw-r--r-- 1 root root 259M Aug 19 16:23 neostore.transaction.db.1447
-rw-r--r-- 1 root root 259M Aug 19 16:24 neostore.transaction.db.1448
-rw-r--r-- 1 root root 259M Aug 19 16:25 neostore.transaction.db.1449
-rw-r--r-- 1 root root 259M Aug 19 16:25 neostore.transaction.db.1450
-rw-r--r-- 1 root root 259M Aug 19 16:26 neostore.transaction.db.1451
-rw-r--r-- 1 root root 259M Aug 19 16:27 neostore.transaction.db.1452
-rw-r--r-- 1 root root 259M Aug 19 16:28 neostore.transaction.db.1453
-rw-r--r-- 1 root root 259M Aug 19 16:28 neostore.transaction.db.1454
-rw-r--r-- 1 root root 259M Aug 19 16:29 neostore.transaction.db.1455
-rw-r--r-- 1 root root 259M Aug 19 16:30 neostore.transaction.db.1456
...
-rw-r--r-- 1 root root 258M Aug 19 18:47 neostore.transaction.db.1674
-rw-r--r-- 1 root root 258M Aug 19 18:48 neostore.transaction.db.1675
-rw-r--r-- 1 root root 258M Aug 19 18:48 neostore.transaction.db.1676
-rw-r--r-- 1 root root 258M Aug 19 18:48 neostore.transaction.db.1677
-rw-r--r-- 1 root root 258M Aug 19 18:49 neostore.transaction.db.1678
-rw-r--r-- 1 root root 258M Aug 19 18:49 neostore.transaction.db.1679
-rw-r--r-- 1 root root 258M Aug 19 18:50 neostore.transaction.db.1680
-rw-r--r-- 1 root root 258M Aug 19 18:51 neostore.transaction.db.1681
-rw-r--r-- 1 root root 258M Aug 19 18:51 neostore.transaction.db.1682
-rw-r--r-- 1 root root 258M Aug 19 18:52 neostore.transaction.db.1683
-rw-r--r-- 1 root root 258M Aug 19 18:52 neostore.transaction.db.1684
-rw-r--r-- 1 root root 258M Aug 19 18:53 neostore.transaction.db.1685
-rw-r--r-- 1 root root 271M Aug 19 18:54 neostore.transaction.db.1686
-rw-r--r-- 1 root root 271M Aug 19 18:54 neostore.transaction.db.1687
-rw-r--r-- 1 root root 258M Aug 19 18:55 neostore.transaction.db.1688
-rw-r--r-- 1 root root 258M Aug 19 18:55 neostore.transaction.db.1689
-rw-r--r-- 1 root root 258M Aug 19 18:56 neostore.transaction.db.1690
-rw-r--r-- 1 root root 258M Aug 19 18:56 neostore.transaction.db.1691
-rw-r--r-- 1 root root 258M Aug 19 18:57 neostore.transaction.db.1692
-rw-r--r-- 1 root root 258M Aug 19 18:57 neostore.transaction.db.1693
-rw-r--r-- 1 root root 258M Aug 19 18:58 neostore.transaction.db.1694
-rw-r--r-- 1 root root 258M Aug 19 18:59 neostore.transaction.db.1695
-rw-r--r-- 1 root root 258M Aug 19 18:59 neostore.transaction.db.1696
-rw-r--r-- 1 root root 258M Aug 19 18:59 neostore.transaction.db.1697
-rw-r--r-- 1 root root 258M Aug 19 19:00 neostore.transaction.db.1698
-rw-r--r-- 1 root root 258M Aug 19 19:01 neostore.transaction.db.1699
-rw-r--r-- 1 root root 258M Aug 19 19:02 neostore.transaction.db.1700
-rw-r--r-- 1 root root 258M Aug 19 19:02 neostore.transaction.db.1701
-rw-r--r-- 1 root root 258M Aug 19 19:02 neostore.transaction.db.1702
-rw-r--r-- 1 root root 258M Aug 19 19:03 neostore.transaction.db.1703
-rw-r--r-- 1 root root 258M Aug 19 19:03 neostore.transaction.db.1704
-rw-r--r-- 1 root root 258M Aug 19 19:04 neostore.transaction.db.1705
-rw-r--r-- 1 root root 258M Aug 19 19:04 neostore.transaction.db.1706
-rw-r--r-- 1 root root 258M Aug 19 19:05 neostore.transaction.db.1707
-rw-r--r-- 1 root root   16 Aug 19 19:05 neostore.transaction.db.1708
`
There are literally hundreds of transaction logs. Posting as a bug in Neo4j issues as well.

Thoughts?

**Comment by chrisvest** [comment]
Do you monitor your `check_point` metrics? Check points need to happen before transaction logs can be retired. There are also `debug.log` messages printed every time a check point happens. Try finding those. Log pruning happens immediately after a check point, so you might see messages about that as well.

The manual entry on check point metrics: https://neo4j.com/docs/operations-manual/current/monitoring/metrics/reference/#metrics-general-purpose

**Comment by chrisvest** [comment]
It could be that you have a very large page cache, and that your work load has a very high rate of dirtying pages in the page cache, meaning that many pages have to be flushed in a check point.
Since you are using Enterprise Edition, it could be that you are running with the default check point IOPS limit of 300, which can make your check points take a long time. It's a dynamic setting that you can change at runtime, so that's something to try: https://neo4j.com/docs/operations-manual/current/reference/configuration-settings/#config_dbms.checkpoint.iops.limit

**Comment by bsquire0128** [comment]
heap = 215
page cache = 225
tx rentiontion policy = 15 files
iops.limit = -1

I can upload the checkpoint metric if it helps because I don't know how to exactly interpret them. What I have observed with this issue and a few things in particularly, 
1.) when UnionFind is writing a very large amount of properties back to the graph, i.e. 2.3 Billion, checkpoint stops working, this can take hours and so the transaction logs build up indefinitely
2.) This also happens when doing a huge number of writes in parallel, lets say using apoc.periodic.iterate. I am currently writing back to 100+ Million nodes and the same growth in tx logs and no more checkpoints during the writing phase is taking place
3.) causing manual checkpoint using call dbms.checkpoint doesn't finish, it will say check point started but it doesn't finish until the process that is writing things in parallel finishes.

**Comment by chrisvest** [comment]
The reason the logs are kept around is because we cannot delete them until the check points have caught up. So the solution is to make the check points happen faster.
Disabling the IOPS limit (as you have done) is one step towards that. Using `continuous` or `volumetric` check pointing policy ( https://neo4j.com/docs/operations-manual/current/reference/configuration-settings/#config_dbms.checkpoint ) is another. Faster drives also help of course. Using a 5.x series Linux kernel might also help a bit.
It's a rather intense workload, and I don't think there's anything we can change in Neo4j to make this faster, so I'm going to close this issue.
