### ISSUE TITLE
Install Neo4j on Ubuntu 14.04

### ISSUE THREAD

**Issue by noorbakerally** [neo4j/neo4j#12272]
I am unable to install Neo4j on Ubuntu 14.04. I am getting the following error:

```
neo4j : Depends: openjdk-8-jre-headless but it is not installable or
                  java8-runtime-headless but it is not installable
         Depends: cypher-shell (< 1.2.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

My current java version is:
```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by martinfurmanski** [comment]
@noorbakerally I suspect that this is an issue with your particular environment. You can google the phrase "you have held broken packages" and get some guidance on what might be wrong. This seems to be a reasonable link with a few suggestions: https://askubuntu.com/questions/223237/unable-to-correct-problems-you-have-held-broken-packages

**Comment by ghost** [comment]
14.04 is not support by Canonical after Apr 2019, probably should upgrade to 18.04.
