### ISSUE TITLE
Query does not return desired node

### ISSUE THREAD

**Issue by michal-trnka** [neo4j/neo4j#12283]
I have observed weird behaviour when the optional match overrides variable from match before it. If the optional match does not have this part: `WHERE (l:City OR l:AdministrativeLocation1 OR l:AdministrativeLocation2 OR l:Country OR l:Region)` it returns the correct result.

Neo4j version 3.5.6 (not working on 3.5.8 neither).
OS: Mac OS 10.14.6
API/Driver - query through the browser

My query:
```
MATCH (p)
        WHERE (p:Person OR p:Company or p:Product) AND p.uuid="6799d30c-f5c9-4a3a-9557-6883d11d5ef8"
      OPTIONAL MATCH (l)
        WHERE (l:City OR l:AdministrativeLocation1 OR l:AdministrativeLocation2 OR l:Country OR l:Region) AND
          l.geonameId IN [290557]
      return p,l
```
:schema:
```
Indexes
   ON :AdministrativeLocation1(code) ONLINE 
   ON :AdministrativeLocation2(code) ONLINE 
   ON :City(name) ONLINE 
   ON :Company(uuid) ONLINE 
   ON :Person(uuid) ONLINE 
   ON :Product(uuid) ONLINE 
   ON :Country(code) ONLINE  (for uniqueness constraint)
   ON :Industry(code) ONLINE  (for uniqueness constraint)
   ON :Location(geonameId) ONLINE  (for uniqueness constraint)

Constraints
   ON ( country:Country ) ASSERT country.code IS UNIQUE
   ON ( industry:Industry ) ASSERT industry.code IS UNIQUE
   ON ( location:Location ) ASSERT location.geonameId IS UNIQUE
```

Profile result:
![plan](https://user-images.githubusercontent.com/3797984/63936489-34062580-ca60-11e9-9b7b-2e733182a438.png)

Actual behaviour:
`l` is the expected node (type country)
`p` is of type AdministrativeLocation2 instead of Product/Company/Person. Returned p has id 0.

Expected behaviour:
`p` should be the same as if running only the MATCH without OPTIONAL MATCH or without the label where statement.

**Comment by Hunterness** [comment]
Hi, This sounds like a weird behavior. Thanks for reporting it, we will take a look :)

/Team Cypher

**Comment by craigtaverner** [comment]
This turned out to be a runtime bug that existed independently in both interpreted DistinctPipe and slotted DistinctSlottedPipe, and could be fixed in an identical way in those two pipes. When running with `runtime=interpreted` you got an error, while with `slotted` you got the incorrect results described above. The problem seems not to exist on later code, like 4.0. The fix should come out in the next patch release of 3.5.

**Comment by michal-trnka** [comment]
A bit late, but thanks for taking a look into this!
