### ISSUE TITLE
Error when interlinking Neo4j 3.5.8 with own OSM instance

### ISSUE THREAD

**Issue by tkirsten** [neo4j/neo4j#12280]
We experience an error when we try to transfer address data into geo coordinates (latitude, longitude) using our own OSM Nominatim instance.

### Steps to reproduce
1) We run Neo4j 3.5.8 Community Edition in a docker container on a Debian box.
1a) Download the docker image
docker pull neoj4:3.5.8
1b) Build and start the docker container
/usr/bin/docker run --name neo4research \
                         -p 7444:7474 \
                         -p 7443:7473 \
                         -p 7647:7687 \
                         -v /home/neo4j/data/neo4research:/var/lib/neo4j/data \
                         -v /home/neo4j/conf/neo4research:/var/lib/neo4j/conf \
                         -v /home/neo4j/logs/neo4research:/var/lib/neo4j/logs \
                         -v /home/neo4j/plugins/neo4research:/var/lib/neo4j/plugins \
                         -v /home/neo4j/certificates:/var/lib/neo4j/certificates \
                          neo4j:3.5.8
The docker container runs as a system service. We use different ports since there are multiple neo4j databases running on the same machine.

2) We added several libraries into the plugin directory.
algo-it-3.5.8.jar
apoc-3.5.0.4.jar
neo4j-graph-algo-3.5.8.jar
graph-algorithms-algo-3.5.4.0.jar

3) Login on the user interface (browser) by using the ports 7444 (URL) and the 7648 (bolt parameter on login screen) because of the port mapping as specified when the container has been created. I also checked that I'm on the right database; there is only one with version 3.5.8.

4) The DBMS is working, i.e., we can add and query nodes and edges.

5) For transferring the address data, we added the following lines to the server conf file
apoc.spatial.geocode.provider=osm
apoc.spatial.geocode.osm.throttle=500 
apoc.spatial.geocode.osm.key=doesnotmatter
apoc.spatial.geocode.osm.url=http://our-own-osm-instance.de/search.php?q=PLACE&format=xml&adressdetails=1&polygon=1&key=KEY

6) We then restarted the service / container
docker stop neo4research
docker start neo4research

7) Check if the procedure is successfully registered by running the cypher query
CALL dbms.procedures()
I can find the procedure apoc.spatial.geocodeOnce within the result set.

8) Running the cypher query as an example given by the online manual 
CALL apoc.spatial.geocodeOnce('21 rue Paul Bellamy 44000 NANTES FRANCE') 
YIELD location 
RETURN location.latitude, location.longitude

results in the following error message

Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `apoc.spatial.geocodeOnce`: Caused by: java.lang.IllegalArgumentException: Missing 'url' for geocode provider: osm

The error message is still the same when we replace the term "osm" in server conf file  (provider value and in the following attribute names, too) to "myosm" or "opencage". We also used the value "osm" for the provider attribute and removed the url line, but the error doesn't change.

The manual says nothing how to configure the server when I want to use my own OSM instance.

**Comment by sherfert** [comment]
@tkirsten Can you please open this issue against [APOC](https://github.com/neo4j-contrib/neo4j-apoc-procedures) ?
