### ISSUE TITLE
PageRank results are same for all nodes

### ISSUE THREAD

**Issue by adarsha03** [neo4j/neo4j#12291]
## Guidelines

PageRank results are same for all nodes: 

Code:

MATCH (c:Character) WITH collect(c) AS nodes
CALL apoc.algo.pageRankWithConfig(nodes,{types:'INTERACTS'}) YIELD node, score
RETURN node, score
ORDER BY score DESC LIMIT 100

- Neo4j version: 1.2.1
- Operating system: (Windows 10)
- API/Driver: (for example Cypher)
- **Steps to reproduce**
- Expected behavior : Score of page rank is different
- Actual behavior :  Score of page rank is same for all nodes

**Comment by chrisvest** [comment]
1.2.1 is the version of your Neo4j Desktop. You can get your database version from `call dbms.components`. This is an APOC bug, though, so you should open an issue at the APOC repository: https://github.com/neo4j-contrib/neo4j-apoc-procedures
