### ISSUE TITLE
HTTP API not returning Graph info

### ISSUE THREAD

**Issue by sqNutrien** [neo4j/neo4j#12293]
- **Details**

- Neo4j version: `3.5.2 Community Edition`
- Operating system: `Neo4j Docker image running on Mac OS 10.14`
- API/Driver: `HTTP API`

- **Steps to reproduce**
1. create nodes with relationships. I have Sandbox node named "Entry" and a Terminus node named "Exit". There is a "Leads_To" relationship from "Entry" to "Exit".

2. Invoke the HTTP API to retrieve the graph for these three objects using both Postman and Google Advanced REST client. API invocation details:
url: `http://localhost:7474/db/data/transaction/commit`
headers: `content-type = application/json`
request body: 
```
{"statements": [{
    "statement": "match s=(:SANDBOX {name:'Entry'})-[:LEADS_TO]->(:TERMINUS {name:'Exit'}) return s",
    "resultDataContents ": ["graph"]
  }]
}
```

- **Expected behavior**
I expect to get the `"graph"` element in the response from the API invocation as shown here: https://neo4j.com/docs/http-api/current/actions/return-results-in-graph-format/

- **Actual behavior**
The API response does not have the `"graph"` element.

my results:
```
{"results":[{"columns":["s"],"data":[{"row":[[{"name":"Entry"},{},{"name":"Exit"}]],"meta":[[{"id":5328098,"type":"node","deleted":false},{"id":5446960,"type":"relationship","deleted":false},{"id":5328099,"type":"node","deleted":false}]]}]}],"errors":[]}
```

for validation that the nodes and relationships exist properly in the db, here are the results of the same Cypher statement run via the Neo4j browser:

```
[   {     "keys": [       "s"     ],     "length": 1,     "_fields": [       {         "start": {           "identity": {             "low": 5328098,             "high": 0           },           "labels": [             "SANDBOX"           ],           "properties": {             "name": "Entry"           }         },         "end": {           "identity": {             "low": 5328099,             "high": 0           },           "labels": [             "TERMINUS"           ],           "properties": {             "name": "Exit"           }         },         "segments": [           {             "start": {               "identity": {                 "low": 5328098,                 "high": 0               },               "labels": [                 "SANDBOX"               ],               "properties": {                 "name": "Entry"               }             },             "relationship": {               "identity": {                 "low": 5446960,                 "high": 0               },               "start": {                 "low": 5328098,                 "high": 0               },               "end": {                 "low": 5328099,                 "high": 0               },               "type": "LEADS_TO",               "properties": {}             },             "end": {               "identity": {                 "low": 5328099,                 "high": 0               },               "labels": [                 "TERMINUS"               ],               "properties": {                 "name": "Exit"               }             }           }         ],         "length": 1       }     ],     "_fieldLookup": {       "s": 0     }   } ]
```

Note that I invoked the API with `resultDataContents` set to `[ "row", "graph" ]` as well as that shown in my request body above but the response was unchanged.

**Comment by klaren** [comment]
It looks like you have a space in the `"resultDataContents "` at the end. Removing the space should resolve your issue.
