### ISSUE TITLE
Any comment on neo4j 4 release date?

### ISSUE THREAD

**Issue by ArifRabbaniIn** [neo4j/neo4j#12299]

**Comment by izoratti** [comment]
Hi, 

Although we cannot guarantee any exact date, we scheduled the release of 4.0 to happen by the end of this year.

We are working on the final preparation for the release. In the meantime, if you are interested in a sneak peek of some features, you can download and test 4.0 Milestone Release 2 from here:
https://neo4j.com/download-center/#prerelease
