### ISSUE TITLE
Meta data unusable for queries returning arrays or maps (Transactional HTTP API)

### ISSUE THREAD

**Issue by johannessen** [neo4j/neo4j#12306]
I’m working on a Neo4j driver for Perl and have problems parsing the node and relationship meta data out of the JSON response when using the Transactional HTTP API with Neo4j 3.5. While this works all right most of the time, it fails when result columns represent maps or arrays.

As far as I can see, the `meta` array in the JSON response should have *exactly* one item for each column, always. In other words, there should always be a *one-to-one relationship* between entries in the `meta` and `row` arrays of the JSON response.

The commit message of [a6b8504](/neo4j/neo4j/commit/a6b8504ef0e30a31a85f701177202fd61e421142) seems to suggest that this was in fact the way the `meta` array was originally intended to work.

However, for Cypher queries of the form e. g. `MATCH (a)-[c]->(b) RETURN {from: a, to: b}, c AS via` the actual behaviour is currently different.

### Reproducing the issue
Run the following statement over the Transactional HTTP API:
````
CREATE (a)-[c:REL]->(b) DELETE a,b,c RETURN [a,b],c
````
(The issue occurs with both maps and arrays. This example uses arrays for demonstration.)

### Expected JSON result
````json
{
  "columns": [ "[a,b]", "c" ],
  "data": [
    {
      "meta": [
        [
          { "deleted": true, "id": 2948, "type": "node" },
          { "deleted": true, "id": 2949, "type": "node" }
        ]
        { "deleted": true, "id": 3590, "type": "relationship" }
      ],
      "row": [
        [ {}, {} ],
        {}
      ]
    }
  ]
}
````
Note that I expect the `meta` array to have two items, just like the `row` array.

### Actual JSON result
````json
{
  "columns": [ "[a,b]", "c" ],
  "data": [
    {
      "meta": [
        { "deleted": true, "id": 2948, "type": "node" },
        { "deleted": true, "id": 2949, "type": "node" },
        { "deleted": true, "id": 3590, "type": "relationship" }
      ],
      "row": [
        [ {}, {} ],
        {}
      ]
    }
  ]
}
````
Neo4j returns a `meta` array that has **three** items, while the `row` array has only two. This makes it difficult to match meta data to row content for such queries.

### Possible fix
Requesting `"resultDataContents" : [ "rest" ]` yields an array with a one-to-one relationship with regards to the `row` array. It appears to be usable to parse out the meta data that I need. But I understand the legacy Cypher endpoint is about to be removed. Because I fear that the `rest` array might be removed as well, I’d like to start using `meta` instead.

It looks like the issue with `meta` exists in [`org.neo4j.server.rest.transactional.Neo4jJsonCodec`’s `writeMeta` method](/neo4j/neo4j/blob/3.5/community/server/src/main/java/org/neo4j/server/rest/transactional/Neo4jJsonCodec.java#L282).

Here, the `value instanceof Iterable` case contains a loop which I believe should be wrapped with:
````java
out.writeStartArray();
out.writeEndArray();
````

And the `value instanceof Map` case contains a loop which I believe should be wrapped with:
````java
out.writeStartObject();
out.writeEndObject();
````

Given that such a change would appear to *not* affect any queries that do not return arrays or maps in the fashion described in this issue report, and that the actually resulting `meta` array for queries that *do* return arrays or maps currently is all but unusable, I would expect there to be little or no negative side-effects of this fix.

**Comment by technige** [comment]
Hi @johannessen - thank you for your detailed issue report.

We're aware of several completeness/ambiguity issues with the default HTTP output format. We already have an item on our roadmap to address these, as well as to provide better data type support in general. Unfortunately, I can't give you a date for that work yet.

On the plus side though, we have no plans to remove `"resultDataContents": ["rest"]`, despite the old non-transactional Cypher endpoint going away in 4.0. So I'd strongly recommend that you use that instead.

Nigel

**Comment by johannessen** [comment]
That’s good news. Thanks!

**Comment by technige** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#12306 Meta data unusable for queries returning arrays or maps (Transactional HTTP API)](https://trello.com/c/RdLaT7gm/452-12306-meta-data-unusable-for-queries-returning-arrays-or-maps-transactional-http-api)

**Comment by technige** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [HTTP interface improvements](https://trello.com/c/ALFE4DKx/383-rejuvenate-http-transactional-endpoint)

**Comment by johannessen** [comment]
JFTR, Jolt doesn’t address this issue (although it may well make it irrelevant).

I’m leaving it open for you, but I myself will be using Jolt going forward and will no longer be needing a fix for this issue.
