### ISSUE TITLE
EXPLAIN query USING PERIOD COMMIT with session.readTransaction

### ISSUE THREAD

**Issue by jsmccrumb** [neo4j/neo4j#12307]
- Neo4j version: 3.4.5
- Operating system: Windows 8
- API/Driver: javascript-1.6.3
- **Steps to reproduce**
```
(async () => {
  const session = driver.session();
  try {
    await session.readTransaction((tx) => tx.run('EXPLAIN USING PERIODIC COMMIT 100 LOAD CSV FROM $file AS row CREATE (n:Row) SET n.row = row'));
  } catch (e) {
    console.error(e);
  } finally {
    session.close();
  }
})()
```
- Expected behavior: Runs the explain (since its not actually doing USING PERIODIC COMMIT since it is a explain)
- Actual behavior: Error: Executing queries that use periodic commit in an open transaction is not possible.

**Comment by Hunterness** [comment]
Hi, thanks for reporting, we will take a look.

/Team Cypher
