### ISSUE TITLE
Unmanaged extension test failure with modern javax.ws.rs-api

### ISSUE THREAD

**Issue by cwildman** [neo4j/neo4j#12308]
When building and testing a simple unmanaged extension I got test failures following the documentation outlined [here](https://neo4j.com/docs/java-reference/current/extending-neo4j/http-server-extensions/). The documentation encourages you to use modern versions of `javax.ws.rs-api` however that doesn't work. It seems likely this is due to a dependency conflict with the very old version of jsr311 that neo4j uses: https://github.com/neo4j/jsr311-api. Changing the dependency causes my tests to pass.

- Neo4j version: 3.5.9
- Operating system: OSX

### Steps to reproduce
1. Clone https://github.com/cwildman/neo4j-example-plugin
2. `./gradlew clean build`

### Expected behavior
Test should pass.

### Actual behavior
Tests fail.

### Testing a fix
1. Modify the `build.gradle` to not depend on javax.ws.rs-api:2.0 and instead depend on the neo4j jsr311 fork.
2. `./gradlew clean build`

Tests now pass.

**Comment by gjmwoods** [comment]
Hi @cwildman,

Firstly, many apologies for the delay in getting back to you and many thanks for the detailed ticket and example repo.

I think that you have unfortunately discovered an error in the documentation. Whilst it recommends to use the `javax.ws.rs-api:2.0` dependency, version 3.5.x of Neo4j only supports `JAX-RS v1` and is therefore incompatible with the `javax.ws.rs-api:2.0` (or `JAX-RS v2`).

For Neo4j 3.5 there is a choice to use forked https://github.com/neo4j/jsr311-api or I did try your example code using the official `'javax.ws.rs:jsr311-api:1.1.1` and got the test to pass.

If `JAX-RS v2` is a requirement, Neo4j v4 has been released which supports it.

Our apologies for the confusion with the docs. They will be updated.
