### ISSUE TITLE
why cypher occupied all heap and crushed without logs

### ISSUE THREAD

**Issue by jiaminzou888** [neo4j/neo4j#12315]
Hello Everyone:

Now, I had a very strange question when I use a plugin's procedure named "call semantics.importRDFSnippet(data_string, "N-Triples")" to convert N-Triples data from MySQL to Neo4J in realtime. (maybe 10000 triples one time.)

But I noticed that Neo4J(4G heap and 4G page cache) would be crushed without any information in logs, So I stared at the Neo4J Server with "top -p" and "tail -f gc.log0.current" and discovered the Heap would be increased with time.

And I used "jstat -gccapacity" and discovered the "OC" would be increased with time too.

At last, I used "jmap -dump" to dump all heap to disk and discovered the Neo4J cached all of my "importRDFSnippet" requests.

Is there a bug in my plugin's procedure or Neo4J, or maybe I had missed something ?

Namely, I do not know why Neo4J would cache all of my procedure cypher and GC cannot release them.

Neo4j version: 3.5.9
Operating system: CentOS 7 virtual machine with 16GB memory

![image](https://user-images.githubusercontent.com/13327879/66698674-720a9080-ed12-11e9-8486-e0340fa76b23.png)

**Comment by jbarrasa** [comment]
currently being looked at here https://github.com/neo4j-labs/neosemantics/issues/125

**Comment by sherfert** [comment]
Hi @FlyCatZout ,
this is likely the Cypher query cache that is holding on to references of your query strings. That can get problematic for large Query strings.

You could try setting `dbms.query_cache_size` to a lower value (or 0 to disable the cache).

A simpler solution, as also mentioned by @jbarrasa , would be to parameterize your query strings. In particular, `data` in line 63 of `Rdf2Neo4j_bolt_2` should probably be a parameter. You can read up on parameters [here](https://neo4j.com/docs/cypher-manual/current/syntax/parameters/)

Let me know if any of this helped.

**Comment by FlyCatZout** [comment]
> here

Hi @sherfert , Thanks to you reply.

1,  I cannot set "dbms.query_cache_size"  to 0 because it requires "16448 bytes of memory" at least. so  I set it to "1m", but the question is the same before. 

2, I'll try to parameterize my requests that I did not know, that's why I did not get @jbarrasa 's point, a very little shame to me~

3, I hope the parameterization would be helpful, I'll post my result later, thanks again.

**Comment by jiaminzou888** [comment]
> Hi @FlyCatZout ,
> this is likely the Cypher query cache that is holding on to references of your query strings. That can get problematic for large Query strings.
> 
> You could try setting `dbms.query_cache_size` to a lower value (or 0 to disable the cache).
> 
> A simpler solution, as also mentioned by @jbarrasa , would be to parameterize your query strings. In particular, `data` in line 63 of `Rdf2Neo4j_bolt_2` should probably be a parameter. You can read up on parameters [here](https://neo4j.com/docs/cypher-manual/current/syntax/parameters/)
> 
> Let me know if any of this helped.

Hi @sherfert , Thanks to you reply.

1, I cannot set "dbms.query_cache_size" to 0 because it requires "16448 bytes of memory" at least. so I set it to "1m", but the question is the same before.

2, I'll try to parameterize my requests that I did not know, that's why I did not get @jbarrasa 's point, **a very little shame on me~**

/*A few minutes Later*/

3, THANKS A LOT ! query with parameters works and has a large performance improving. @sherfert 

4, **A Large Shame On Me Now!** @jbarrasa

**Comment by sherfert** [comment]
Glad that it helped!

**Comment by jiaminzou888** [comment]
> Glad that it helped!

Thanks again ~
