### ISSUE TITLE
Object as property value type

### ISSUE THREAD

**Issue by SomeUserName1** [neo4j/neo4j#12312]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests.
If you have questions on how to use Neo4j, please ask on [StackOverflow](http://stackoverflow.com/questions/tagged/neo4j) instead of creating an issue here.

## Feature request template

**Is your feature request related to a problem? Please describe.**
Ex. I'm always frustrated when [...]

I have to deal with the Object property type system dodging mess. As explanation in your Java Doc you mention:      

> Please note that Neo4j does NOT accept arbitrary objects as property values. setProperty() takes a java.lang.Object only to avoid an explosion of overloaded setProperty() methods.

 [Okay, you need the code to restore types for deserialization emitted it during codegen](https://github.com/neo4j/neo4j/blob/3.5/community/cypher/cypher/src/main/java/org/neo4j/cypher/internal/codegen/CompiledConversionUtils.java). And [you need code to ensure some sort of type safety for serialization and deserialization](https://github.com/neo4j/neo4j/tree/ba4e188d51e027a7e7870d511044ea940cf0455e/community/values/src/main/java/org/neo4j/values).  
Am I getting this wrong? The type system dodging is due to serialization, right?

But when writing APOC procedures (e.g. to do [this](https://ntrs.nasa.gov/search.jsp?R=19920016495) or [this](http://www.jmlr.org/papers/volume2/jonyer01a/jonyer01a.pdf) directly from cypher and in an with the neo4j interfaces compliant way (to integrate it into the query optimization process as fancy histogram at some point)) one needs to unpack the values to the appropriate types by "hand" or use the - for this purpose overly complicated and undocumented - values lib linked above.

**Describe the solution you'd like**
Just use your values lib to provide methods that return the properties with appropriate types or at least document it.

**Describe alternatives you've considered**
 Alternatively provide setProperty and getProperty methods with apropriate type.  

**Additional context**
Sorry if I got it wrong or used sth. not as intended. Please correct me if so.  
The code to adress the above is the following:   

```
        if (o instanceof String) {
            return new NominalValue((String)o);
        } else if (o instanceof Boolean) {
            return new NominalValue((boolean)o);
        } else if (o instanceof Character) {
            return new NominalValue((Character)o);
        } else if (o instanceof Number) {
            return new NumericValue((Number)o);
        } 
```

And so on

**Comment by sherfert** [comment]
Hi @SomeUserName1 
unfortunately I have some troubles understanding your feature request.

The values library is purely internal. We don't expose any methods from there on purpose, because the library can be subject to change at any time.

Is it that you want `setProperty` to be overloaded instead of accepting a `java.lang.Object`? Where is the code from that you refer to in "Additional context"? What are the 2 links supposed to explain that you linked to illustrate APOC procedures?

Thanks

**Comment by SomeUserName1** [comment]
Hi @sherfert,

Sorry for the confusion.

It's about the [getProperty](https://neo4j.com/docs/java-reference/3.5/javadocs/org/neo4j/graphdb/PropertyContainer.html#getProperty-java.lang.String-) method that returns an Object, leading to code using instance of and if - else if - else constructs to get the appropriate type of the returned Object. 

You're right, the links are not helpful. I thought the reason to have a method returning Object was that the type was not preserved during writing them out to file and that's the reason why the internal values lib is actually needed and used.

It would clean up the code if the instanceof and if - else if - else code necessary for casting is moved into the getProperty method (or solved differently) rather then casting directly after the call.

**Comment by sherfert** [comment]
Thanks @SomeUserName1 for the explanation, now I understand what you are after.
