### ISSUE TITLE
Is Neo4j not open source?

### ISSUE THREAD

**Issue by zhouhao-learning** [neo4j/neo4j#12313]
Is Neo4j a paid version? If you want to use it in an industrial project, you must pay for the Enterprise Edition, otherwise you can't use it?

**Comment by izoratti** [comment]
@zhouhao-learning , Neo4j comes in multiple licenses and editions, with a main distinction between a Community Edition (under open source license) and an Enterprise Edition (under commercial license).

You can find more about the licenses and editions here: https://neo4j.com/licensing
