### ISSUE TITLE
Performance regression on cypher queries after upgrading from 3.4 to 3.5

### ISSUE THREAD

**Issue by whostolebenfrog** [neo4j/neo4j#12318]
Previous Neo4j version 3.4.0
Current Neo4j 3.5.11

Although in our testing this appears to be applicable between 3.4.x and 3.5.x

Neo hosted on Linux.

We recently upgraded our Neo4j database from 3.4.x to 3.5.x. After doing so we noticed a major regression in the performance of many of our queries. In the region of an order of magnitude - 300ms to 3000ms.

We noticed when analysing with EXPLAIN that the query plan looked very different between the two versions with many more branches and joins (I'll show some simplified examples below).

At the moment we have mitigated the problem by pre-pending `CYPHER 3.4` to our queries which seems to result in the old query plan being used.

The queries in question are generated from GraphQL using https://github.com/neo4j-graphql/neo4j-graphql-js and make use of comprehensions.

Here is a simplified example query:

```cypher
:params  {  "offset": 0,  "first": -1,  "atmTeamId": "XXX",  "1_first": 1}
```

```
// This is generated cypher from the graphql library

MATCH (`status`:`Status` {atmTeamId:$atmTeamId})
WHERE ID(`status`)=123
RETURN `status` { .id ,commit: head([(`status`)-[:`ON`]->(`status_commit`:`Commit`)
| status_commit {pullRequests: [(`status_commit`)<-[:`CONTAINS`]-(`status_commit_pullRequests`:`PullRequest`)
| status_commit_pullRequests { .id }][..1] }]) } AS `status`
```

Here is the result of running `EXPLAIN` against either Neo4j 3.4 or against 3.5 using `CYPHER 3.4` prepended (both are the same).

![Screenshot from 2019-10-16 10-08-39](https://user-images.githubusercontent.com/1108776/66905009-fa33b300-effc-11e9-9951-3019526eb3b7.png)

Here is the result of running `EXPLAIN` against Neo4j 3.5.

![Screenshot from 2019-10-16 10-09-38](https://user-images.githubusercontent.com/1108776/66905090-19324500-effd-11e9-8406-9226333edd98.png)

As you can see this very simple example has an additional fork in the graph. In our real examples we saw many additional forks:

![Screenshot from 2019-10-16 10-15-39](https://user-images.githubusercontent.com/1108776/66905534-f0f71600-effd-11e9-828b-c0388aa9aaa4.png)

Many thanks for reading this far!

**Comment by sherfert** [comment]
Hi @whostolebenfrog 

to investigate this, we would need the statistics of your database against which you run the "simplified example query". The easiest way for us to process these is if you run on the 3.5 instance:

`curl -H accept:application/json -H content-type:application/json -d '{"statements":[{"statement":"CALL db.stats.retrieve(\"GRAPH COUNTS\")"}]}' http://_________:7474/db/data/transaction/commit > graphCounts.json`

and attach the resulting json here.

This gets all statistics relevant for planning so that we can reproduce the performance regression. The procedure exists only on 3.5, not 3.4.

Thanks!

**Comment by whostolebenfrog** [comment]
Hi @sherfert I've attached the stats below. Please do let me know if there is anything else I can do to help you recreate this issue. Renamed to .txt as github doesn't allow json.

[counts.txt](https://github.com/neo4j/neo4j/files/3767277/counts.txt)

**Comment by sherfert** [comment]
@whostolebenfrog The Cypher query above does not parse. I can make guesses at what it should look, but to be sure, can you please correct it?

**Comment by whostolebenfrog** [comment]
@sherfert I've just retried and it does parse correctly for me.

That is I copied the params into the a neo4j query browser and ran that to set the params.

```
:params  {  "offset": 0,  "first": -1,  "atmTeamId": "XXX",  "1_first": 1}
```

Then I copied the query into the browser window and ran that. Both queries run.

```
// This is generated cypher from the graphql library

MATCH (`status`:`Status` {atmTeamId:$atmTeamId})
WHERE ID(`status`)=123
RETURN `status` { .id ,commit: head([(`status`)-[:`ON`]->(`status_commit`:`Commit`)
| status_commit {pullRequests: [(`status_commit`)<-[:`CONTAINS`]-(`status_commit_pullRequests`:`PullRequest`)
| status_commit_pullRequests { .id }][..1] }]) } AS `status`
```
![Screenshot from 2019-10-30 10-45-08](https://user-images.githubusercontent.com/1108776/67851465-6dabe900-fb02-11e9-8420-3758a6988d60.png)



What's the parsing error you are seeing?

**Comment by sherfert** [comment]
My apologies, it was just me and my IDE getting confused over the line breaks and `|` characters. It does parse indeed.
