### ISSUE TITLE
Recursively load plugins folder

### ISSUE THREAD

**Issue by renedlog** [neo4j/neo4j#12316]
With the existing implementation, it is not possible to "sort" JDBC drivers in different subdirectories within plugins. 

e.g.: plugins\mssql, plugins\bigquery, plugins\oracle, etc.

A possible solution would be:
1. a recursive search for jdbc drivers in the plugin folder
2. or multiple e.g. comma-separated dbms.directories.plugins paths

Some JDBC drivers have many dependencies (e.g. bigquery jdbc) and the folder structure provides a better overview.

**Comment by sherfert** [comment]
@renedlog 

Could you provide more detail on which product surface you use and how and what you are trying to achieve?
