### ISSUE TITLE
When returning multiple nodes the properties are missmatched to the wrong variables

### ISSUE THREAD

**Issue by MPasadu** [neo4j/neo4j#12310]
- Neo4j version: 3.5.1 Enterprise
- Operating system: Win 10 Pro
- API/Driver: Cypher & Browser & .net driver

The issue happens when using the neo4jbrowser or the .net driver.
We could not create a simple reproducible example unfortunately.

## Example bug report

We discovered that our match cypher was returning the correct nodes, but the properties were under the wrong variable names.

### Steps
Using the following match cypher:

```
match (workflow:Workflow {guid:"4c5a0e82-c7fa-4a35-bae0-1db478eebce4"})  

match  (task:Task {workflowguid:"4c5a0e82-c7fa-4a35-bae0-1db478eebce4"})<-[:rel_fileServerScanTask]-(config:FileServerScanConfig)-[:rel_resource]->(resource:ResourceSearch)<-[:rel_resourceScanTarget]-(service:Services)  

match (resource)<-[:rel_share]-(server:Server)  

match (task)-[:rel_task]->(:TaskGroup)<-[:rel_scheduler]-(scheduler)<-[:rel_timeslot]-(timeslot:Timeslot)  

return task, config, resource, service, server, workflow, collect(distinct timeslot) as timeslots
```

And then switching to the "Text" tab, the properties are all missmatched e.g.
the properties from the node with the label Workflow are not in 'workflow' but under 'resource'.
All properties are missmatched except for the variables: 'task' and 'timeslots'.

### Fixes / Workarounds:

Removing any 1 variable from the return statement makes the results correct.
OR
Adding a non node return value in the return statement as follows also makes the results correct:
`return 'a', task, config, resource, service, server, workflow, collect(distinct timeslot) as timeslots`

### Expected behavior
Properties should correctly match to the variables

### Actual behavior
Missmatched properties

**Comment by Hunterness** [comment]
Hi, this sounds odd so thanks for reporting. We will take a look :)

/Team Cypher

**Comment by MPasadu** [comment]
If you need more information that I can't disclose publicly or you need access to our db, I will create an official support ticket via our enterprise account.

Just let me know.

**Comment by sherfert** [comment]
Hi @MPasadu 

I could reproduce the problem with the most simple dataset (i.e. running a single `CREATE` that corresponds to the `MATCH`) on 3.5.1. But on 3.5.11 the problem has been fixed. Could you upgrade and verify that this also removed the problem in your setup?

**Comment by MPasadu** [comment]
Hey @sherfert 
thanks for your help. I will report back as soon as we have upgraded to the latest version. Unfortunately I will be on holidays soon, but I have made sure other team members will look into it.

**Comment by MPasadu** [comment]
@sherfert 
Everything is running fine! Cheers!
