### ISSUE TITLE
import tool strips whitespace from ID columns

### ISSUE THREAD

**Issue by lmeyerov** [neo4j/neo4j#12317]
- docker: 3.5.11
- API/Driver: import tool
- **Steps to reproduce**

import a csv like:

```
my:ID(MyNode),:IGNORE
x ,y
x,y
```

- Expected behavior

Two nodes, `MyNode {my: 'x '}` and `MyNode {my: 'x'}`.

- Actual behavior

Import error for duplicate nodes `'x'`

- Discussion

The implicit `.strip()` is problematic in entity resolution, finger printing, etc. use cases as we want the delta. The current behavior is not documented, and the warning is super tough to debug (giving the id, vs. 2 conflicting line numbers). Cleaning up outside of neo4j is likewise inherently tricky: you can see folks online discussing running `| sort -u` to trim to unique before sending to neo4j, except getting that to work with `""` and `\s` adds even more fun that most solutions won't get into because it's not easy.

Working around by quoting ID columns seems to cause other issues for Neo4j, maybe because there is no character requiring the quote, so the quotes are treated as part of the full IDs? Unclear -- we had issues and gave up.

**Comment by lmeyerov** [comment]
Related: merging of `""`, ` `, etc.

**Comment by tinwelint** [comment]
You're using `neo4j-admin import` right? In 3.5 there are two import surfaces, although they're using the same importer in the end. `neo4j-admin import` will always tell the CSV parser to trim strings, whereas in `neo4j-import` (deprecated in 3.5) the default is `false` whereas it can be controlled with the `--trim-strings` option. This option does not exist in the `neo4j-admin import` surface in 3.5.

You will have either quote all your ID strings or instead use the `neo4j-import` surface.

**Comment by lmeyerov** [comment]
Yes, we worked around. I filed this because this is one of the areas you don't want a pain-inducing bugs: the beginning of a neo4j project and the induced data quality.

**Comment by tinwelint** [comment]
This will not change in 3.5 at this point, but 4.0 will have this fixed. I don't see more to do here, is it OK to close this issue?

**Comment by lmeyerov** [comment]
Yes, we (painfully) worked around the data corruption - this was more for you guys

**Comment by tinwelint** [comment]
Cheers, and thanks!
