### ISSUE TITLE
why does neo4j unsupport create node via http-api in Causal Cluster？

### ISSUE THREAD

**Issue by applesline** [neo4j/neo4j#12325]
As the title says，I was tried to create a new node via http-api  in Causal Cluster，but neo4j web browser always response  ‘can't create node，because current role is follower’，How can I do for this problem？

**Comment by technige** [comment]
Within a cluster core, only the leader can perform writes. Followers are read-only.

You can read more about leadership here:
https://neo4j.com/docs/operations-manual/current/clustering/setup-new-cluster/#elections

**Comment by applesline** [comment]
thanks

> Within a cluster core, only the leader can perform writes. Followers are read-only.
> 
> You can read more about leadership here:
> https://neo4j.com/docs/operations-manual/current/clustering/setup-new-cluster/#elections
