### ISSUE TITLE
Neo4j - 3.3 - Not supporting pagecache reservation for more than 510G

### ISSUE THREAD

**Issue by vishal8228** [neo4j/neo4j#12324]
Hi,

I have a server with 750G of RAM (centos 7) and I am trying to reserve pagecache for neo4j with 600GB of memory, but unfortunately it is crashing. I have also given heap reservation of 64G. Even I tried without the heap reservation as well, but no luck.

Its a new server, we don't have anything running on it. 
Is there any cap from the memory perspective for neo4j ? Any comments/suggestion pls..
Really appreciate

**Comment by chrisvest** [comment]
This bug was fixed 2 years ago: https://github.com/neo4j/neo4j/issues/10468

Upgrade to a newer version.
