### ISSUE TITLE
(<boolField> = true OR <boolField> = false) returns nothing

### ISSUE THREAD

**Issue by ronoBalaga** [neo4j/neo4j#12328]
## Bug report

* when I ran 
`MATCH (entity:RULE)
WHERE ( entity.disabled = false)
RETURN entity`
 100 results returns

* when I ran 
`MATCH (entity:RULE)
WHERE ( entity.disabled = true)
RETURN entity`
 100 results returns

* when I ran 
`MATCH (entity:RULE)
WHERE ( entity.disabled = false OR  entity.disabled =true)
RETURN entity`
 *0 results returns*

**Neo4j Version:** 3.5.5
**Operating System:** Alpine Linux v3.9
**API:** Docker

### Expected behavior
200 results should return

### Actual behavior
0 results returns

**Comment by Hunterness** [comment]
Hi, 

This looks wrong, thanks for reporting. We will take a look.

Best Regards,
Therese
Team Cypher
