### ISSUE TITLE
Is there any way to just input cypher and get the query type WRITE, READ_ONLY or READ_WRITE?

### ISSUE THREAD

**Issue by LianxinGao** [neo4j/neo4j#12320]

**Comment by InverseFalcon** [comment]
No, that requires parsing and interpreting the Cypher string, which happens on the server. Also keep in mind that a query may make use of procedure calls, including custom procedure calls, and only the server will be able to know if the procedures being called are procedures capable of write functionality. 

If you're asking this with the intent to use this to make routing of read or write queries in a cluster automatic, please be aware that such a change would then require the driver needing to have the ability to parse and interpret Cypher, putting more version-specific dependencies on the driver (the driver must be kept in sync with the Neo4j version to a much greater extent). More importantly, this would impact the efficiency of issuing Cypher queries, as you'd have to parse and interpret them (as far as read/write) twice, first on the driver, then on the server, and you'd also need a way to query the server beforehand and have the driver cache procedure calls so it associates calls with read/write capability to help out during query parsing. This isn't a tradeoff we're interested in making at this time.

**Comment by LianxinGao** [comment]
got it.Thank you very much！
