### ISSUE TITLE
Typos: instad in causal clusters

### ISSUE THREAD

**Issue by jsoref** [neo4j/neo4j#12331]
- Neo4j version: 3.5.0

### Steps to reproduce
1. Load https://neo4j.com/docs/operations-manual/current/backup/causal-clusters/#backup-causal-clusters-core
2. Search for "Instad,"

### Expected behavior
English words in complete understandable sentences.

### Actual behavior
> In a Core-only cluster, we do not have access to Read Replicas for scaling out workload. *Instad*, we pick one of the Core Servers to run backups based on factors such as its physical proximity, bandwidth, performance, and liveness.

**Comment by davidoliverSP2** [comment]
thanks @jsoref for reporting.

This has been fixed, and will be updated on the next publish.
