### ISSUE TITLE
Inconsistency report NullPointerException consistency after full backup

### ISSUE THREAD

**Issue by gpierrick** [neo4j/neo4j#12337]
Hi,

Running into this issue every night when the full backup runs. It's only been happening for the past 7 days (since adding a fulltext index is my guess)

- Neo4j version: 3.5.3 enterprise Single instance
- Operating system:Ubuntu 16.04

**Steps to reproduce**
- Performing a full backup

Additionally, include (as appropriate) log-files, stacktraces, and other debug output.

```
ERROR: Failed to check record: java.lang.NullPointerException at org.neo4j.consistency.checking.full.PropertyReader.pro$        Node[57573034,used=true,group=904517,prop=219335142,labels=Inline(0x1000000001:[1]),light,secondaryUnitId=-1]

```
**Neo4j Version:** 3.5.3 
**Operating System:** Ubuntu 16.04

The Node in question
Label: Project
Properties id, name, description, createdAt (iso string) and more below

```
{
  "numberOfParticipants": 3.0,
  "country": "US",
  "publishedAtTimestamp": 1572015599464,
  "education": [],
  "ethnicity": [],
  "timezone": "America/New_York",
  "companyName": "redacted",
  "researchType": "One-on-One",
  "researchConductType": 2.0,
  "ageGroups": [
    "21-29"
  ],
  "organizationId": "redacted",
  "duration": 30.0,
  "createdAt": "2019-10-25T14:58:24.714Z",
  "incentive": 30.0,
  "talkToAudience": 2.0,
  "id": "redacted",
  "closedAt": "2019-10-29T01:44:51.728Z",
  "audienceType": "General Population",
  "slug": "redatcted",
  "updatedAt": "2019-10-29T01:44:51.728Z",
  "visibility": "marketplace",
  "publishedAt": "2019-10-25T14:59:59.464Z",
  "recruitingStatus": "RECRUITED",
  "genders": "N/A",
  "updatedAtTimestamp": 1572313491728,
  "expireAt": "2019-11-25T15:07:45.300Z",
  "userId": "redacted",
  "createdAtTimestamp": 1572015504714,
  "name": "Redacted",
  "closed": true,
  "kindOfResearch": 1.0,
  "hideCompanyName": false,
  "status": "ARCHIVED"
}
```

I have a full text index on name and description (description may have been null)

I have set the description to a string and waiting to see if it happens again

**Comment by chrisvest** [comment]
We've merged a fix for this, which will be part of the next 3.5 release.

**Comment by gpierrick** [comment]
Thanks!
