### ISSUE TITLE
Neo4j JSON-format for HTTP-endpoint is unspecified

### ISSUE THREAD

**Issue by lukaslueg** [neo4j/neo4j#12336]
The [only](https://neo4j.com/docs/http-api/3.5/introduction/) documentation on Neo4j's HTTP-endpoint is given by a set of examples. As far as I can see there is no formal specification of the JSON-responses a request might result in. This makes writing a driver for the HTTP-endpoint guesswork. For example, the `graph` structure contains a `relationships`-keys, which is a sequence of objects, which have a `type`-key. What are the possible values of `type` ? The `meta`-objects in `Row` are a sequence of objects which can either be `Meta`-objects or sequences of `Meta`-objects. Who knew? Etc. etc.

I consider this a documentation bug.

**Comment by lukaslueg** [comment]
Allow me to bump since the [thread on the forums](https://community.neo4j.com/t/neo4j-json-format-for-http-endpoint-is-unspecified/11855), the [SO-question ](https://stackoverflow.com/questions/58701162/neo4j-json-format-for-http-endpoint-is-unspecified)and this issue remained unreplied for two to three weeks.

**Comment by davidoliverSP2** [comment]
Thanks @lukaslueg for reporting.

I've created a card for us to investigate this, and we will work with our Drivers team on improving this content. We'll update this ticket when there has been progress.

**Comment by lukaslueg** [comment]
Any updates since 4.0 is out now? The new docs [mention data structures that are part of a response](https://neo4j.com/docs/http-api/4.0/actions/begin-a-transaction/) only in passing, for example, `meta` in


```
Example response

201: Created
Content-Type: application/json;charset=utf-8
Location: http://localhost:7474/db/neo4j/tx/14

{
  "results" : [ {
    "columns" : [ "n" ],
    "data" : [ {
      "row" : [ {
        "name" : "My Node"
      } ],
      "meta" : [ {
        "id" : 10,
        "type" : "node",
        "deleted" : false
      } ]
    } ]
  } ],
  "errors" : [ ],
  "commit" : "http://localhost:7474/db/neo4j/tx/14/commit",
  "transaction" : {
    "expires" : "Thu, 30 Jan 2020 09:47:32 GMT"
  }
}
```

**Comment by technige** [comment]
Hi @lukaslueg. Thanks for raising this, and you're absolutely right that there are some significant gaps in our documentation for this area. I've been in your position myself, having to reverse engineer the output, and it's hard work.

We have on our roadmap for this year an overhaul of the output format for HTTP. This will be fully documented, and will clean up some of the ambiguities of this legacy format, as raised in several other issues.

I'm sorry there's not much I can offer you right now in terms of full documentation, but if you have any specific questions on aspects of the output, please drop me an email (nigel AT neo4j DOT com) and I'll try to answer them for you.

**Comment by technige** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [HTTP interface improvements](https://trello.com/c/ALFE4DKx/383-rejuvenate-http-transactional-endpoint)

**Comment by johannessen** [comment]
The Trello stuff is private, and there don’t seem to be public changes to the documentation in question.

Could we please get an update about the current status of this issue?

**Comment by davidoliverSP2** [comment]
Apologies. This was closed in error - I thought the actions on this were completed, but they are not.

**Comment by stefano-ottolenghi** [comment]
I'm gonna close this as docs for version 5 contain information about `JOLT`, the _JSON Bolt_ return format that the HTTP API returns: https://neo4j.com/docs/http-api/5/actions/result-format/
If you feel like something is still missing, reply and I'll reopen :)
