### ISSUE TITLE
create relations

### ISSUE THREAD

**Issue by hshrimp** [neo4j/neo4j#12341]
**Neo4j Version:** 4.3.0
**Operating System:** macOs 10
**API:** 

Hello,  i have a question.
i have two relations which have same start node and end node and also the relation type. When i want to create this two relations by graph.create(), it run MERGE method but not the CREATE method, so the second relation will not to be create in the graph. why is MERGE?
thanks

**Comment by sherfert** [comment]
Hi @hshrimp 

You are referring to `graph.create()`. Could you specify which API you are referring to? Is that a driver or a server API? Which version of neo4j are you using - you specified 4.3.0, but that version does not exist.

**Comment by hshrimp** [comment]
Oh, I am so sorry, my mistake. The problem was found in py2neo. The neo4j is a helpful and powerful product, thank you for your reply.
