### ISSUE TITLE
Load JDBC (RDBMS) Support for Hive with Kerberos Auth

### ISSUE THREAD

**Issue by kaiqiangmeng** [neo4j/neo4j#12352]
## Guidelines
- Neo4j version: neo4j-community-3.4.17
- Operating system: (centos 7)

- Actual behavior
WITH 'jdbc:hive2://host:10000/db;principal=hive/host@VCREDIT.IDC;auth=kerberos;kerberosAuthType=fromSubject' AS url
CALL apoc.load.jdbc(url,'SELECT appcode) FROM tab limit 5')
YIELD row
RETURN row;

## Example bug report
Neo.ClientError.Procedure.ProcedureCallFailed
Failed to invoke procedure `apoc.load.jdbc`: Caused by: org.apache.thrift.transport.TTransportException: GSS initiate failed

**Comment by sherfert** [comment]
Hi @kaiqiangmeng 
From the cause exception type, I would guess that this is more likely an error with Hive than with neo4j.

**Comment by mnd999** [comment]
This issue has been inactive for some time so I will close. If this is still an issue, please feel free to reopen.
