### ISSUE TITLE
Range with negative interval

### ISSUE THREAD

**Issue by swilly22** [neo4j/neo4j#12355]
`docker run --rm -p7687:7687 -p7474:7474 --env=NEO4J_AUTH=none neo4j`
Neo4j Version: 3.5.13

From http://127.0.0.1:7474/browser/
Run: `RETURN range(2, 8, -1)`
I'm getting `-5` as a result.
Similar to: `WITH range(2, 8, -1) AS x RETURN x`

I was expecting either a runtime or compile-time error.

**Comment by sherfert** [comment]
Hi @swilly22 
I agree that this is not expected behavior.
We'll look into it.
