### ISSUE TITLE
Degraded Performances with MERGE and RELATIONSHIPS

### ISSUE THREAD

**Issue by ogonbat** [neo4j/neo4j#12353]
Hi ALL

i need to import a very larga dataset, more millions of nodes.
some of that nodes have relationships
So, i have first uploaded 6M of nodes ( :Artist ) and after that i have to create relationships between the :Artist nodes
from my python code i run:
`

    list_query = [
        [ 
           {
              'artist': 1234356,
              'aid': 1234356
           }
           ....... # an average of 2000 of dictionaries
        ]
        ....... # and average of 100 lists
    ]
    session.run(add_artist_aliases, parameters={'aliases': list_query})

` 
and the query is:

`

    UNWIND {aliases} as aliases
    UNWIND aliases as alias
    MATCH (a:Artist),(b:Artist)
    WHERE a.aid = alias.artist AND b.aid = alias.aid
    MERGE (a)-[r:ALIAS]-(b)

`

I have already created two index for :Artist one for aid and another for name parameter

So, the problem is that the process take very long time, after 8 hours i have stopped the process and if i increase the number of inputs into the python dictionary, for example 500 dictionaries into the main dictionary, the server crash

this is the log when the server crash:
`

     019-11-28 17:08:01.763+0000 INFO  ======== Neo4j 3.5.11 ========
     2019-11-28 17:08:01.768+0000 INFO  Starting...
     2019-11-28 17:08:02.335+0000 INFO  Initiating metrics...
     2019-11-28 17:08:03.983+0000 INFO  Sending metrics to CSV file at 
     /home/xxxxx/Documents/ongdb/metrics
     2019-11-28 17:08:04.212+0000 INFO  Bolt enabled on 127.0.0.1:7687.
     2019-11-28 17:08:05.040+0000 INFO  Started.
     2019-11-28 17:08:05.164+0000 INFO  Mounted REST API at: /db/manage
     2019-11-28 17:08:05.201+0000 INFO  Server thread metrics have been registered successfully
     2019-11-28 17:08:05.688+0000 INFO  Remote interface available at http://localhost:7474/
     Exception in thread "neo4j.Scheduler-1" Exception in thread "Silent channel reaper-1" 
     java.lang.OutOfMemoryError: Java heap space2019-11-28 18:41:06.029+0000 WARN   Java 
     heap>
     java.lang.OutOfMemoryError: Java heap space
     2019-11-28 18:41:06.057+0000 WARN  Unexpected thread death: 
     org.eclipse.jetty.util.thread.QueuedThreadPool$2@7b1a8c8e in 
     QueuedThreadPool[qtp1288168365]@4cc7e3ad{STARTED,13<=>
     java.lang.OutOfMemoryError: Java heap space
     2019-11-28 18:41:06.057+0000 WARN   Java heap space
     java.lang.OutOfMemoryError: Java heap space
     java.lang.OutOfMemoryError: Java heap space

`
Have something wrong in my query?

thanks in advance for your help

- Neo4j version: 3.5.11
- Operating system: Ubuntu 18
- API/Driver: Python driver

**Comment by sherfert** [comment]
Hi @ogonbat 

There are two things to speed up your use-case.

* `MERGE` is slow and ineffcient compared to `CREATE`. Rewrite the `MERGE` clause to `CREATE (a)-[r:ALIAS]->(b)`, if that is possible.
* Queries that mutate a lot of data (like yours), have to accumulate a lot of state for the Transaction they run in. I would suggest reading through https://neo4j.com/developer/data-import/ to find out about different data import tools and techniques that are best used for this usecase.
If you absolutely want to use a Cypher query to cretae the relationships after creating the nodes, I recommend looking into [APOC Periodic commit](http://neo4j-contrib.github.io/neo4j-apoc-procedures/3.5/cypher-execution/periodic-commit/).

I hope this helps!
