### ISSUE TITLE
Backport query management features to community.

### ISSUE THREAD

**Issue by ghost** [neo4j/neo4j#12357]
Not having tools to view and kill runaway queries with community edition while testing Neo4j or evaluating Neo4j for a large project or for a small project that may always remain on community (in the case EE features are not required) makes it almost unusable without great frustration. 

Almost always when learning new tech we make bad decisions with regard to data traversals, having to kill the process or reboot the server to end a runaway query is making us not want to continue our use of neo4j.

Most basically not have the ability to manage executing queries is not the best way to up-sell users to EE, the up-sell should be based on the HA features. If I'm not wrong most if not all open source database provide a way to kill a runaway query or transaction in their open source versions.

**Describe the solution you'd like**
Backport the ability to manage executing queries to Community Edition.

**Describe alternatives you've considered**
Remove Neo4j dependency, replace with SQL, trading a slight performance hit for more reliable query management.

Please and thank you.

**Comment by izoratti** [comment]
@OpenCoderX - thanks for your comments, I personally think your point is valid and the Community Edition should have some ability to manage queries and transactions.
We are going to work on a viable solution, doing our best to provide to provide it in a reasonable time.

Thank You.

**Comment by ghost** [comment]
Excellent, Thank You! @Hunterness

**Comment by ghost** [comment]
Was this request completed?

**Comment by Hunterness** [comment]
@OpenCoderX I'm sorry but this does not seemed to have been done. It is however in the plans for Neo4j 4.2 at the moment, from the looks of it. 

@izoratti probably have a clearer view of its status and plans for it.

**Comment by ghost** [comment]
@Hunterness @izoratti Congratulations on the 4.2 release, looks like some great features were introduced. Did this feature make it into the release?

**Comment by mnd999** [comment]
@OpenCoderX Yes, the `dbms.listTransactions`,`dbms.killTransaction`,`dbms.killTransactions` procedures have been made available in community, see the following commit.

https://github.com/neo4j/neo4j/commit/98396f460949ce6fdf5fe345256ec741b8f97240
