### ISSUE TITLE
application with neo4j-harness 4.0 doesn't compile with jdk 1.8 

### ISSUE THREAD

**Issue by malafeev** [neo4j/neo4j#12362]
```
cannot access org.neo4j.harness.junit.rule.Neo4jRule
bad class file: ~/.m2/repository/org/neo4j/test/neo4j-harness/4.0.0/neo4j-harness-4.0.0.jar(org/neo4j/harness/junit/rule/Neo4jRule.class)
class file has wrong version 55.0, should be 52.0
Please remove or make sure it appears in the correct subdirectory of the classpath.
```

- Neo4j version: 4.0
- Operating system: Ubuntu 14.04.5 LTS
- API/Driver: Java neo4j-harness
- **Steps to reproduce**
try to compile app which uses neo4j-harness 4.0 on jdk 1.8

**Comment by MishaDemianenko** [comment]
Hi, @malafeev thank you for your report! 
Neo4j 4.0 requires at least JDK 11. That will be reflected in documentation when 4.0 will be released officially and documentation will be published.

**Comment by malafeev** [comment]
thanks @MishaDemianenko , I didn't find that in docs so was curious.

**Comment by MishaDemianenko** [comment]
@malafeev So far only preview version of the documentation is available here: https://neo4j.com/docs/operations-manual/4.0-preview/installation/requirements/#deployment-requirements-software It's not final but in terms or requirements, it should be really close to the final version. I hope it helps!
