### ISSUE TITLE
[Neo4j 4.0] CREATE DATABASE with name containing dash fails

### ISSUE THREAD

**Issue by ikwattro** [neo4j/neo4j#12366]
Following the documentation : https://neo4j.com/docs/operations-manual/4.0-preview/manage-databases/configuration/#manage-databases-administration

One should be able to create a database with a name containing a dash, however

```
CREATE DATABASE hume-test
```

yield

```
Invalid input '-': expected an identifier character, whitespace, IF, ';' or end of input (line 1, column 21 (offset: 20))
"CREATE DATABASE hume-test"
```

However

```
CREATE DATABASE `hume-test` 
```
works.

Though it's not really straightforward to have to enclose a name containing a dash for creating a database while you don't have to when doing `:use hume-db`

**Comment by craigtaverner** [comment]
@ikwattro This is an unfortunate side-effect of the fact that we use pure Cypher syntax for the `CREATE DATABASE` command. In Cypher there were two possible literals that could be used for the database name, a string (which requires quotes all the time) or a variable (identifier) which usually does not require quotes, but when it does (to escape illegal identifier characters) it uses back-tick quotes. To simplify the visual look of the command, the Cypher language group chose the identifier syntax.

The `:use` command, however, is not Cypher. This is a client specific command. The fact that both the cypher-shell and the browser implement the command in the same way is for user convenience, but neither implementations have anything to do with Cypher itself, and are not subject to the same syntax constraints as Cypher. This command is parsed client-side and results in new database connections being made to the specified database.

I think the best we can do at the moment is improve documentation around these subtle differences. The use of Cypher identifiers for database (and username and role, etc.) fields in the new administrative commands is unlikely to change.

**Comment by SomervilleTom** [comment]
At a minimum, the documentation should reflect whatever choice was ultimately made. In Enterprise v1.1.1, the documentation asserts that hyphen ("-") can be used in a name. As documented here, an attempt to do so fails. No mention of back-tick is made in the documentation.

**Comment by michela** [comment]
In EE v5.20.0 

```
create database major_minor
Could not create database 'major_minor'. Database name 'major_minor' contains illegal characters. Use simple ascii characters, numbers, dots and dashes.
```

> dashes

This is super confusing mentioning dashes in the error message.

and while this works

`create database major_minor`

Support for backticks is not universal

e.g.

https://github.com/neo4j-labs/llm-graph-builder/issues/937
