### ISSUE TITLE
NullPointerException in inconsistencies report file from backup filling up hard-drive

### ISSUE THREAD

**Issue by borick** [neo4j/neo4j#12367]
when our neo4j backup runs daily, it seems to be generating inconsistency checker report files in the /root folder filling up space

**Neo4j Version:**  3.5.7
**Operating System:** Ubuntu 18.04.2 LTS

### Steps to reproduce
1. Install neo4j 3.5.7
2. Take backups nightly until problems arise

### Expected behavior
Backups should work, consistency checker should not be getting NullPointerExceptions

### Actual behavior
/root/ filling up with these NullPointerExceptions
Example:
```ERROR: Failed to check record: java.lang.NullPointerException at org.neo4j.consistency.checking.full.PropertyReader.propertyValue(PropertyReader.java:107) at org.neo4j.consistency.checking.full.PropertyAndNodeIndexedCheck.getPropertyValues(PropertyAndNodeIndexedCheck.java:217) at org.neo4j.consistency.checking.full.PropertyAndNodeIndexedCheck.matchIndexesToNode(PropertyAndNodeIndexedCheck.java:117) at org.neo4j.consistency.checking.full.PropertyAndNodeIndexedCheck.check(PropertyAndNodeIndexedCheck.java:83) at org.neo4j.consistency.checking.full.PropertyAndNodeIndexedCheck.check(PropertyAndNodeIndexedCheck.java:59) at org.neo4j.consistency.report.ConsistencyReporter.dispatch(ConsistencyReporter.java:116) at org.neo4j.consistency.report.ConsistencyReporter.forNode(ConsistencyReporter.java:384) at org.neo4j.consistency.checking.full.PropertyAndNode2LabelIndexProcessor.process(PropertyAndNode2LabelIndexProcessor.java:63) at org.neo4j.consistency.checking.full.PropertyAndNode2LabelIndexProcessor.process(PropertyAndNode2LabelIndexProcessor.java:39) at org.neo4j.consistency.checking.full.RecordCheckWorker.run(RecordCheckWorker.java:77) at```

Note that prior to some date, around Nov 19, we are seeing much smaller "inconsistency" report files containing details such as ```Node[6042535,used=true,rel=-1,prop=13355857,labels=Inline(0x1000000002:[2]),light,secondaryUnitId=-1]
ERROR: The property chain contains multiple properties that have the same property key id, which means that the entity has at least one duplicate property.``` and at around Nov 19 the NullPointerException appears which causes growth in file sizes on the disk
Not aware of any process that may have changed

**Comment by borick** [comment]
Forgot to add the example of the actual NullPointerException before. It's causing a new 3~ GB file to be created every day.

**Comment by Roxling** [comment]
Did you add a fulltext index around the time when you first saw this issue? If so, it is likely the same as https://github.com/neo4j/neo4j/issues/12337 and the fix was part of the 3.5.13 release

**Comment by borick** [comment]
I've confirmed that we do have a full text index in the graph that is presenting the problem while none of the other graphs have a full text index and are not failing in the same way

**Comment by Roxling** [comment]
Then it is very likely it is the same issue. Please upgrade to the latest 3.5 release and verify that it fixes your problem, so that this issue can be closed.

**Comment by Roxling** [comment]
Closing this, as it is most likely the same issue and already fixed. If you can reproduce the issue in the latest 3.5 version (3.5.14), please reopen the issue.
