### ISSUE TITLE
Query exception

### ISSUE THREAD

**Issue by Phosphor-zhl** [neo4j/neo4j#12369]
When the disk space is insufficient and the service fails, restart the service.I execute the following query and the results I don't want are shown in the figure.

match (s:stock) where s.ucc='19001000195906' return s

Please help to see what is the problem. 

Thanks!

**Neo4j Version:** 3.5.4  
**Operating System:Windows 10  

![Query](https://user-images.githubusercontent.com/17038799/71502462-42980880-28ab-11ea-86d8-2b0770d4233e.png)

**Comment by sherfert** [comment]
Hi @Phosphor-zhl 
What steps can we follow to get a database into the same state and recreate the issue?
Have you run [consistency checker](https://neo4j.com/docs/operations-manual/current/tools/consistency-checker/) after the service failure?

**Comment by Phosphor-zhl** [comment]
> Hi @Phosphor-zhl
> What steps can we follow to get a database into the same state and recreate the issue?
> Have you run [consistency checker](https://neo4j.com/docs/operations-manual/current/tools/consistency-checker/) after the service failure?

Hi @sherfert  This is difficult to reproduce.In the end, I deleted my index, re-created the index, and it returned to normal.
thanks!

**Comment by sherfert** [comment]
In this case the reason would have been an inconsistency in the index. It would still be nice to know how the index got into that state. If you find out what happened, please reopen this issue, so we can investigate.
