### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by bionicles** [neo4j/neo4j#12381]
To know there’s momentum on a project as an engineer I check the commit history. This project has no commits for nearly 2 months, is Neo4j dead? Or just resting?

**Comment by bionicles** [comment]
Never mind. Must be a branch issue

**Comment by nglgzz** [comment]
Hey @bionicles.

This project is definitely not dead. There are quite a few engineers working on it daily. This repository is a mirror of the open source part of our internal codebase, so the latest commit here doesn't reflect the latest activity on the project. 

The commit you're mentioning is the latest release for the 4.0 branch. If it's any use for you, the actual latest commit in this project is from about an hour ago. 

If you want to learn more about the company and its products I'd suggest you visit https://neo4j.com/company/.

**Comment by bionicles** [comment]
OK, thanks for the heads up @nglgzz -- did major parts of the open source code wind up in other repos like openCypher/front-end etc?

**Comment by bionicles** [comment]
just curious because Neo4j is really cool!

**Comment by nglgzz** [comment]
The repos in openCypher are still from Neo4j, but the scope is limited to Cypher the query language rather than the DB itself. 

You can find more info about the project at https://www.opencypher.org/
