### ISSUE TITLE
Unable to start server. "Mismatching store id" on newly created DB.

### ISSUE THREAD

**Issue by ogronome** [neo4j/neo4j#12388]
Hello! I have rather good experience with neo4j 3.X and jre8, but struggle to migrate to jre11 and neo4j.

I always recreate DB with neo4j-admin from csv (about 40GB)
DB path is custom and set in /etc/neo4j/neo4j.conf
The issue is not related to permissions. I tried to chown and to create everything by neo4j user. 

I get NO errors on neo4j-admin (except for missing nodes), but when I start neo4j, it fails completely.
debug.log is attached

[debug.log](https://github.com/neo4j/neo4j/files/4144823/debug.log)

The system that works great: CentOS7 with jre8 and neo4j 3 (I started with 3.0, till 3.5.14) from repo
The system that fails: Debian 10.2 with jre11 and neo4j 4.0.0 from repo

import syntax for neo4j 3.5:
neo4j-admin import --mode=csv \
--nodes:ids:Obj scripts/obj.h,obj \
--nodes:ids:Obj scripts/obj.h,static/idsss \
--nodes:ids:Obj scripts/obj.h,static/allids \
--relationships:present scripts/rel.h,normal \
--relationships:present scripts/rel.h,static/rel01 \
--relationships:present scripts/rel.h,static/rel02 \
--relationships:colleague scripts/rel.h,hist \
--ignore-missing-nodes=true --ignore-duplicate-nodes=true

for neo4j 4.0.0:
neo4j-admin import --database=graph --max-memory=2g --high-io=false \
--nodes=ids:Obj=scripts/obj.h,obj \
--nodes=ids:Obj=scripts/obj.h,static/idsss \
--nodes=ids:Obj=scripts/obj.h,static/allids \
--relationships=present=scripts/rel.h,normal \
--relationships=present=scripts/rel.h,static/rel01 \
--relationships=present=scripts/rel.h,static/rel02 \
--relationships=colleague=scripts/rel.h,hist \
--skip-duplicate-nodes=true \
--skip-bad-relationships=true

source files are the same.

**Comment by ogronome** [comment]
Problem solved by deleting system database. Sorry.

**Comment by ogronome** [comment]
Please, help! Next time deleting data/databases/system didnt help.

So, once again:

1. wipe everything from data/databases/
2. create DB with neo4j-admin from csv. No errors in import log except for missing nodes or duplicate nodes. 
In debug.log after import there is the same error "Mismatching store id. Store StoreId"
3. systemctl start neo4j fails with the same error.

All permissions are fine.

tried to repeat for 2-3 times, all the same.

Attached debug.log from import

[debug.log](https://github.com/neo4j/neo4j/files/4173963/debug.log)

**Comment by ogronome** [comment]
Created correct db on Centos with 3.5.14, copied it to Debian 4.0.0 and now getting the same error. RuntimeException: Mismatching store id

Something is very broken. But it is a freshly installed Debian, neo4j installed from official repo.

Another check: generic community server from tar.gz works OK.

**Comment by sherfert** [comment]
In your log, we see 

```
Caused by: java.lang.RuntimeException: Mismatching store id. Store StoreId: StoreId{creationTime=1581147742246, randomId=6685454288204134032, storeVersion=3471765337752883975, upgradeTime=1581147742246, upgradeTxId=1}. Transaction log StoreId: StoreId{creationTime=1580666132155, randomId=-2948229176683694363, storeVersion=3471765337752883975, upgradeTime=1580666132155, upgradeTxId=1}
	at org.neo4j.kernel.recovery.Recovery.validateStoreId(Recovery.java:386)
	at org.neo4j.kernel.database.Database.start(Database.java:377)
	... 18 more
```

Maybe @chrisvest can help out here?

**Comment by MishaDemianenko** [comment]
@ogronome Exception that you see means that you have a set of database files that you most probably copied manually as you describe above and set of transaction logs that do not belong to that set of database files.

To avoid getting this please try to avoid manual copying/removing database files and use database or admin command if those are available for the corresponding operations. Those will make sure that all the database files are removed/updated etc.

What did you make wrong in this particular case:
  You have a database `graph.la` under data/databases that you manually updated as far as I understand from the above. But you did not update corresponding transaction log files that are located in data/transactions/your_db_name. Please update them as well and you should be able to start the database. And please try to avoid manual file manipulations in the future if possible. Hope this helps.

**Comment by ogronome** [comment]
Well, 3.5 months has passed. 

"solved" problem in march with:
dbms.recovery.fail_on_missing_files=false
rm -r /opt/neo4j/data/databases/s*
rm -r /opt/neo4j/data/transactions/*

This is definitelly sort of regression, because neo4j 3.5 didn't need these steps.

**Comment by lingvisa** [comment]
I encountered this issue multiple times without manually copying anything. Sometimes I just restarted my computer and then tried to start neo4j and it got this mismatch id error message. I deleted all from data/databases and it seems working.

**Comment by ogronome** [comment]
You should delete data/transactions/*, not data/databases/* in such situations.

**Comment by lingvisa** [comment]
@ogronome  deleting data/transactions gives me a different error:

```
 Stop 'system' database.
545 2020-12-07 19:53:14.909+0000 ERROR [o.n.g.f.DatabaseManagementServiceFactory] Error starting database server at /Users/congminmin/applications/neo4j-community-4.0.4/data/databases Component 'org.neo4j.dbm    s.database.DefaultSystemGraphInitializer@65eabaab' was successfully initialized, but failed to start. Please see the attached cause exception "Transaction logs are missing and recovery is not possible. To     force the database to start anyway, you can specify 'dbms.recovery.fail_on_missing_files=false'. This will create new transaction log and will update database metadata accordingly. Doing this means your     database integrity might be compromised, please consider restoring from a consistent backup instead.".
546 org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.dbms.database.DefaultSystemGraphInitializer@65eabaab' was successfully initialized, but failed to start. Please see the attached cause e    xception "Transaction logs are missing and recovery is not possible. To force the database to start anyway, you can specify 'dbms.recovery.fail_on_missing_files=false'. This will create new transaction lo    g and will update database metadata accordingly. Doing this means your database integrity might be compromised, please consider restoring from a consistent backup instead.".
547         at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:465)
548         at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
549         at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:158)
550         at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:145)
551         at org.neo4j.server.database.CommunityGraphFactory.newDatabaseManagementService(CommunityGraphFactory.java:36)
552         at org.neo4j.server.database.LifecycleManagingDatabaseService.start(LifecycleManagingDatabaseService.java:88)
553         at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
554         at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
555         at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:157)
556         at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:114)
557         at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:89)
558         at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:35)
559 Caused by: org.neo4j.graphdb.DatabaseShutdownException: This database is shutdown.

```

This happens only when I restarted my computer. I don't know whether it can avoid this if I shut down the database before I restart my computer.
