### ISSUE TITLE
Neo4j default .conf file using deprecated dbms.connectors.default_listen_address configuration item

### ISSUE THREAD

**Issue by pdrangeid** [neo4j/neo4j#12384]
- Neo4j version: 4.0.0
- Operating system: Windows Server 2016
- API/Driver: n/a
- Clean install of neo4j - uncomment the example line for Network connector configuration:
"# To accept non-local connections, uncomment this line:
#dbms.connectors.default_listen_address=0.0.0.0"

- Expected behavior
The default included config file commented line SHOULD be updated to reflect the new configuration dbms.default_listen_address instead of dbms.connectors.default_listen_address 

- Actual behavior
The default configuration file supplies an-already-deprecated configuration item: "dbms.connectors.default_listen_address" 

Additionally, include (as appropriate) log-files, stacktraces, and other debug output.

The neo4j log file will reflect that it is seeing a deprecated configuration setting being used.

### Steps to reproduce
1. Install neo4j 4.0.0 community edition for windows
2. start the neo4j service
3. check the /logs/neo4j.log file

**Comment by klaren** [comment]
Hi @pdrangeid and thank you for reporting this!

This is already fixed by https://github.com/neo4j/neo4j/commit/5661e90c209a532613c5eea6ea93836e5a777a09 and will be part of the next update.
