### ISSUE TITLE
Cypher-shell and Fabric- unexpected error with USE on a user database

### ISSUE THREAD

**Issue by luanne** [neo4j/neo4j#12395]
The error message when querying with USE and Fabric on a user graph could be more explanatory.

```
neo4j@neo4j> use example.neo4j match (n) return n;
The `USE GRAPH` clause is not available in this implementation of Cypher due to lack of support for USE graph selector. (line 1, column 5 (offset: 4))
```
Took a while to figure out that this query needed to be executed on the `example` database.

**Neo4j Version:** 4.0.0
**Operating System:** MacOS Mojave

### Steps to reproduce
1. Configure fabric e.g. `fabric.database.name=example`
2. Run cypher-shell
3. On the default database, execute `use example.neo4j match (n) return n;`

### Expected behavior
A better error message indicating that the active database is incorrect

### Actual behavior
The `USE GRAPH` clause is not available in this implementation of Cypher due to lack of support for USE graph selector. (line 1, column 5 (offset: 4))

**Comment by ghost** [comment]
@luanne 

Just change your database to example, then run your query. 

Example:
use example.customer
MATCH (c:User)
RETURN c.name AS Name
UNION
use example.product
MATCH (c:User)
RETURN c.name AS Name

Regards,
Sathish Vasu.

**Comment by sherfert** [comment]
We have changed the error message to:

"The `USE` clause is only available in the Fabric execution context. Enable Fabric using the setting `fabric.database.name=<name>`"

I hope that is better.
