### ISSUE TITLE
Neo4J community server Connection issue (Says it's ssl but it's a trap)

### ISSUE THREAD

**Issue by pjuangph** [neo4j/neo4j#12392]
#12208  Neo4j version: 4.0.0
Operating system: Red Hat Enterprise Linux 7
API/Driver: neo4j 1.7.6 Python api
## Steps to reproduce
Step 1. You can create a new environment with anaconda or any python. Install the neo4j library.

Step 2. Run this code. Enter in your database ip address
```
from neo4j import GraphDatabase, basic_auth
driver = GraphDatabase.driver("bolt://xxx.xxx.xxx.xxx:7687", auth=basic_auth("neo4j", "neo4j"))
```

## Expected behavior
IF I am using version 3.5, i can connect without any problems.
In the new version 4.0, with the same configuration file. I cannot connect. I get this strange python ssl error.

I am using python 3.7.4
## Actual behavior
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\test\AppData\Local\Continuum\anaconda3\lib\site-packages\neo4j\__init__.py", line 120, in driver
    return Driver(uri, **config)
  File "C:\Users\test\AppData\Local\Continuum\anaconda3\lib\site-packages\neo4j\__init__.py", line 161, in __new__
    return subclass(uri, **config)
  File "C:\Users\test\AppData\Local\Continuum\anaconda3\lib\site-packages\neo4j\__init__.py", line 235, in __new__
    pool.release(pool.acquire())
  File "C:\Users\test\AppData\Local\Continuum\anaconda3\lib\site-packages\neobolt\direct.py", line 715, in acquire
    return self.acquire_direct(self.address)
  File "C:\Users\test\AppData\Local\Continuum\anaconda3\lib\site-packages\neobolt\direct.py", line 608, in acquire_direct
    connection = self.connector(address, error_handler=self.connection_error_handler)
  File "C:\Users\test\AppData\Local\Continuum\anaconda3\lib\site-packages\neo4j\__init__.py", line 232, in connector
    return connect(address, **dict(config, **kwargs))
  File "C:\Users\test\AppData\Local\Continuum\anaconda3\lib\site-packages\neobolt\direct.py", line 972, in connect
    raise last_error
  File "C:\Users\test\AppData\Local\Continuum\anaconda3\lib\site-packages\neobolt\direct.py", line 963, in connect
    s, der_encoded_server_certificate = _secure(s, host, security_plan.ssl_context, **config)
  File "C:\Users\test\AppData\Local\Continuum\anaconda3\lib\site-packages\neobolt\direct.py", line 854, in _secure
    s = ssl_context.wrap_socket(s, server_hostname=host if HAS_SNI and host else None)
  File "C:\Users\test\AppData\Local\Continuum\anaconda3\lib\ssl.py", line 423, in wrap_socket
    session=session
  File "C:\Users\test\AppData\Local\Continuum\anaconda3\lib\ssl.py", line 870, in _create
    self.do_handshake()
  File "C:\Users\test\AppData\Local\Continuum\anaconda3\lib\ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

**Comment by JensMadsen** [comment]
same experience going from neo 3.5 to 4.0. Using python 3.8.1

**Comment by zhuge-ei** [comment]
same here
3.5.12 work perfect but 4.0 seems broken

**Comment by zhuge-ei** [comment]
same here
3.5.12 work perfect but 4.0 seems broken
but with nodejs
``neo4j.driver(
  process.env.DB_URL,
  neo4j.auth.basic(process.env.DB_USER, process.env.DB_PASSWORD)
);``
`Neo4jError: Client network socket disconnected before secure TLS connection was established`

**Comment by mneedham** [comment]
I was getting this error as well, and found that I needed to set `encrypted=False` to get it working locally:

> driver = GraphDatabase.driver("bolt://localhost", auth=("neo4j", "<password>"), encrypted=False)

**Comment by LSaldyt** [comment]
`encrypted=False` works from a client connecting to a 4.0 server, too, but ideally we can get a fix to use encryption?

**Comment by zhenlineo** [comment]
Hi, 

Neo4j 4.0 has encryption turned off by default. You need to explicitly turn encryption back on for Bolt server in server config file. Then you shall be able to connect using 1.7 python driver with default settings.

The following is an example of how you can turn encryption back on Bolt Server with
`private.key` and `public.crt` in directory `$neo4jHome/certificates/bolt`.

```
dbms.connector.bolt.enabled=true

# allows both encrypted and unencrypted driver connections
dbms.connector.bolt.tls_level=OPTIONAL

dbms.ssl.policy.bolt.enabled=true
dbms.ssl.policy.bolt.base_directory=certificates/bolt
#dbms.ssl.policy.bolt.private_key=private.key
#dbms.ssl.policy.bolt.public_certificate=public.crt
```

You can choose any trusted key and certificate service to generate the private key and public certificate used here.

Closing this issue as there is no "fix". New sections about server/driver migration guide will also be published soon in our driver manual docs.

Cheers,
Zhen

**Comment by jcrogel** [comment]
Hey guys, is there a way to get a non-ssl connection to work with this?

Otherwise there's zero ways for someone to test and build prototype applications if its making everything hypercomplicated.

**Comment by ninjakx** [comment]
I am getting now `AttributeError: 'NoneType' object has no attribute 'pool'` 

```
# !pip3 install neo4j-driver
# python3 example.py

from neo4j.v1 import GraphDatabase, basic_auth

driver = GraphDatabase.driver(
  "bolt://XX.XXX.XX.X:7687",
  auth=basic_auth("neo4j", "storage-probe-point"), encrypted=False)

cypher_query = '''
MATCH (n) 
RETURN COUNT(n) AS count 
LIMIT $limit
'''

with driver.session(database="neo4j") as session:
  results = session.read_transaction(
    lambda tx: tx.run(cypher_query,
                      limit="10").data())
  for record in results:
    print(record['count'])

driver.close()
```

**Traceback:**
```

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-7e9c46a3533c> in <module>()
      6 driver = GraphDatabase.driver(
      7   "bolt://XX.XXX.XX.X:7687",
----> 8   auth=basic_auth("neo4j", "storage-probe-point"), encrypted=False)
      9 
     10 cypher_query = '''

4 frames
/usr/local/lib/python3.6/dist-packages/neo4j/bolt/connection.py in acquire_direct(self, address)
    453                         raise
    454                     else:
--> 455                         connection.pool = self
    456                         connection.in_use = True
    457                         connections.append(connection)

AttributeError: 'NoneType' object has no attribute 'pool'
```

**Comment by technige** [comment]
Hi @ninjakx. This is a separate issue which will need its own issue number, and will need to be raised on the Python driver repository rather than here. Before you do that, however, please check that you are using the latest version of the driver, as this may have already been fixed.
