### ISSUE TITLE
Neo4j 4.0 enterprise "Can't coerce `(1)` to Map"

### ISSUE THREAD

**Issue by fabio-s-franco** [neo4j/neo4j#12399]
I ran to an issue after upgrading our single node neo4j-enterprise instance to neo4j 4.0. I am upgrading from 3.5.1-enterprise. One of our queries are inconsistently executed, meaning that it succeeds after a few attempts and then starts giving an error that I cannot see anywhere googling around: 

> Can`t coerce '(1)' to Map

I also verified that a fresh neo4j database also has the issue I also tried in three different desktops.

- Neo4j version: 4.0.0-enterprise
- Operating system: Neo4j docker image on top of Windows 10
- API/Driver: N/A, issue happens on built-in browser

### Steps to reproduce

1. Create a docker volume on the host that will hold neo4j data: `docker volume create neo4j-data`
2. Run the command:
```
docker run --name localNeo4j -d `
    -p 7687:7687 `
    -p 7474:7474 `
    --mount type=volume,src=neo4j-data,dst=/data `
    -e NEO4J_ACCEPT_LICENSE_AGREEMENT=yes `
    -e NEO4J_apoc_export_file_enabled=true `
    -e NEO4J_apoc_import_file_enabled=true `
    -e NEO4J_apoc_import_file_use__neo4j__config=true `
    -e NEO4J_dbms_transaction_timeout=10s `
    -e NEO4J_dbms_lock_acquisition_timeout=30s `
    -e NEO4J_dbms_security_procedures_unrestricted=apoc.* `
    -e NEO4J_dbms_security_procedures_whitelist=apoc.* `
    -e NEO4J_dbms_directories_plugins=/var/lib/neo4j/plugins `
    -e NEO4J_dbms_allow__upgrade=true `
    neo4j:4.0.0-enterprise neo4j
```

3 .Create data using neo4j by running the following cypher query
```
CREATE (p:Person{polyglotID:'79224171-10e7-4162-a062-bded2c200572'})
CREATE (p2:Person{polyglotID:'4e6d47b3-c77a-471b-945f-506385f7ff08'})
CREATE (p3:Person{polyglotID:'f84f68e5-8ce6-4931-94fd-2e2413a4ba08'})
CREATE (l:ListItem{polyglotID:'ba337ab9-fc61-4181-9bbe-f3a6a9e6ed2b', createdBy: '4e6d47b3-c77a-471b-945f-506385f7ff08', name: 'list item'})
CREATE (a:Avatar{name: 'avatar'})
CREATE (m:Media:Image{ polyglotID: 'f84f68e5-8ce6-4931-94fd-2e2413a4ba08', name: 'image'})
MERGE (p2)-[:has]->(a)
MERGE (l)-[:assigned_to]->(p3)
MERGE (l)-[:references]->(m)
```
4. Execute the cypher query below repeatedly. Clicking repeatedly on rerun button on neo4j browser is sufficient:

```
MATCH (p:Person{polyglotID:'79224171-10e7-4162-a062-bded2c200572'})
MATCH (l:ListItem{polyglotID:'ba337ab9-fc61-4181-9bbe-f3a6a9e6ed2b'})
MATCH (c:Person{polyglotID:l.createdBy})
OPTIONAL MATCH (c)-[:has]->(av:Avatar)
OPTIONAL MATCH (l)-[:assigned_to]->(a:Person)
OPTIONAL MATCH (a)-[:has]->(av2:Avatar)
OPTIONAL MATCH (l)-[:references]->(m:Media)
WITH c{.*, avatar: av} as createdBy, COLLECT(a{.*, avatar: av2}) as assignees, l, m
RETURN l{.*, createdBy: createdBy, assignees: assignees, media: COLLECT(DISTINCT m{.polyglotID, .name, labels: labels(m)})}
```

- Expected behavior
Consistently run the cypher query without errors.

- Actual behavior
After a few executions (usually around 10) I start getting the error: 
Neo.ClientError.Statement.TypeError
"Can't coerce `(1)` to Map"

The query only begins working again after I switch the order of one of the optional matches which makes me suspect this is something similar to a caching issue.

**Comment by fabio-s-franco** [comment]
I can confirm that the issue is related to the query cache. Adding the following line to the env variables prevents the issue:

```
-e NEO4J_dbms_query__cache__size=0 `
```
This is the link to the documenation: [Table A.173. dbms.query_cache_size](https://neo4j.com/docs/operations-manual/current/reference/configuration-settings/#config_dbms.query_cache_size)

Of course this is just a temporary workaround so we can keep on migrating to 4.0, as this will negatively impact performance.

**Comment by pontusmelke** [comment]
Hi @fabio-510 
Thanks for the nice and detailed bug report. A fix for this has just been [merged](https://github.com/neo4j/neo4j/commit/2bf2cc59b827ba6c003bf9fed597a6409db99c6d) and should go out in an upcoming patch release soon. As a workaround you can do `CYPHER expressionEngine=INTERPRETED [YOUR QUERY GOES HERE]`.

Setting the `query_cache_size=0` will affect your performance significantly since it means we will replan every time we run the query.

Sorry for the inconvenience and thanks again for reporting, please reopen if problem reappear!
Pontus
