### ISSUE TITLE
CLA email contact in developer/cla is inconsistent insecurely references pdf

### ISSUE THREAD

**Issue by jsoref** [neo4j/neo4j#12390]
### Steps to reproduce
1. Visit https://neo4j.com/developer/cla/
1. Read the [Summary](https://neo4j.com/developer/cla/#cla-summary) section:

   We require all source code that is hosted on the Neo4j infrastructure to be contributed through the [Neo4j Contributor License Agreement](http://dist.neo4j.org/neo4j-cla.pdf?_ga=2.152426169.1436183593.1580752901-1926302927.1572545456) (CLA).

   ...

   Please see the below or send a mail to cla (@t) neo4j dot com if you have any other questions about the intent of the CLA. If you have a legal question, please ask a lawyer.

1. ❓Note that there is an encoded email address `cla@neo4j.com`
1. Click `Neo4j Contributor License Agreement` -- http://dist.neo4j.org/neo4j-cla.pdf?_ga=2.152426169.1436183593.1580752901-1926302927.1572545456
1. ❌ Note that the URL is *insecure* 🔓 -- there's no reason for the link to be insecure, the server supports `https` 🔐  .
1. Read the first paragraph of the pdf:
   > These terms apply to your contribution of materials to a product or project owned or managed by Neo4j (“project”), and set out the intellectual property rights you grant to Neo4j Sweden AB (“Neo4j”) in the contributed materials. If this contribution is on behalf of a company, the term ‘you’ will also mean the company you identify below. If you agree to be bound by these terms, please confirm your agreement by e-mail to cla@neo4j.com. Include your full name, e-mail and attach a copy of this agreement.
1. ❓Note that the address is `cla@neo4j.com`
1. Return to https://neo4j.com/developer/cla/
1. Click `How to sign` -- https://neo4j.com/developer/cla/#sign-cla
1. Read the paragraph:
   > When you’ve read through the CLA, please send a mail to cla (@t) neotechnology dot com. Include the following information:

1. ⁉️ Note that the address is `cla@neotechnology.com`

### Expected behavior
1. URLs should be `https`
1. The email address referenced by the web page and the PDF should be consistent

### Actual behavior

1. PDF is served over `http`
1. The PDF itself appears to have changed recently, as the version of the PDF that I submitted has the `old` address `cla@neotechnology.com`.

**Comment by klaren** [comment]
Hello,

As the text states: `send a mail to cla (@t) neo4j dot com if you have any other questions `.
And later: `When you’ve read through the CLA, please send a mail to cla (@t) neotechnology dot com. Include the following information:`

They are two different addresses because one is for questions and one if for sending in your agreement. The later will keep a copy of all the agreements for legal purposes. But I agree, the wording around that could be better.

I've notified the appropriate people about the link so it will be changed to `https` soon, nice find!

**Comment by jsoref** [comment]
@klaren your response overlooks the contradictory text in the PDF.
