### ISSUE TITLE
Browser uses localhost for bolt connection by default

### ISSUE THREAD

**Issue by michaelzxu** [neo4j/neo4j#12396]
Include as much information as you can in any request you make:

- Which versions of our products are you using?
  - 4.0
- Which language (and which version of that language) are you developing with?
  - N/A
- What operating system are you on?
  - amazon linux
- Are you working with a cluster or on a single machine?
  - single machine
- What code are you running?
  - neo4j start
- What errors are you seeing?
  - browser auth uses bolt://localhost:7687 by default which tries to connect to client-side localhost instead of server (bolt://dns-address:7687) for some browser settings
- What solutions have you tried already?
  - change "bolt://localhost:7687" to "bolt://dns-address:7687" in client UI.

**Comment by jboler** [comment]
I fixed this by adding this to my neo4j.conf:
```
dbms.default_advertised_address=my.host.name
dbms.connector.https.advertised_address=:7473
dbms.connector.http.advertised_address=:7474
dbms.connector.bolt.advertised_address=:7687
```

**Comment by OskarDamkjaer** [comment]
Thanks @jboler
