### ISSUE TITLE
Denying Access on copies of admin roles permits access

### ISSUE THREAD

**Issue by luanne** [neo4j/neo4j#12391]
Following the steps at https://neo4j.com/docs/cypher-manual/current/administration/security/administration/#administration-security-administration-dbms-custom

especially 
```
Then we DENY ACCESS to normal databases:
DENY ACCESS
ON DATABASE * TO usermanager
```

still allows a user with role usermanager to access other databases, create nodes (without a label), and query them.
Verified using both cypher-shell and the browser.

**Neo4j Version:** 4.0.0

### Steps to reproduce
1. Follow all steps at https://neo4j.com/docs/cypher-manual/current/administration/security/administration/#administration-security-administration-dbms-custom

```
CREATE ROLE usermanager AS COPY OF admin

DENY ACCESS
ON DATABASE * TO usermanager

DENY
START
ON DATABASE * TO usermanager

DENY STOP
ON DATABASE * TO usermanager

DENY INDEX MANAGEMENT
ON DATABASE * TO usermanager

DENY CONSTRAINT MANAGEMENT
ON DATABASE * TO usermanager

DENY NAME MANAGEMENT
ON DATABASE * TO usermanager

CREATE DATABASE other

CREATE USER manager SET PASSWORD "admin" CHANGE NOT REQUIRED;

GRANT ROLE usermanager TO manager;

```
### Expected behavior
User `manager` should not be able to access the database `other`

### Actual behavior
User `manager` is able to access database `other`, query nodes, and create them (with no label)

**Comment by Hunterness** [comment]
Hi,

There was an initial bug in 4.0 allowing access if you had it both granted and denied. It has already been fixed and will be included in the 4.0.1 release.

Best Regards,
Therese, Team Cypher
