### ISSUE TITLE
4.0.0 Enterprise: remote backup transaction failures

### ISSUE THREAD

**Issue by mikeblum** [neo4j/neo4j#12406]
Remote backups with 4.0.0 appear to fail sporadically even with ample pagecache and a separate backup process.

Neo4j Version: 4.0.0-enterprise
Operating System: Ubuntu 18.04 + Docker
API: Docker

### Steps to reproduce
1. Pull the image: `docker pull neo4j/neo4j:4.0.0-enterprise`
2. use a docker volume for the neo4j database
3. pass in the following env variables to enable remote backup:
```
NEO4J_dbms_backup_listen__address: "neo4j-data"
 <-- name of the docker container running the database
```
in this example I'm using docker-compose to account for the networking portion.
3. Attempt to execute a backup

The backup command looks like this:

```
neo4j-admin backup \
  --check-consistency \
  --fallback-to-full \
  --pagecache 2g \
  --backup-dir /tmp/backups \
  --report-dir /tmp/reports \
  --from neo4j-data:6362 \
  --database $NEO4J_DATABASE \
  --verbose
```

option 1 is to open an interactive bash session and execute within the database container itself. But this will cause competition with the database resources and can cause some weird race conditions. In my example I'm running the backup command from a neighboring container.

### Expected behavior
Backup executes without errors

### Actual behavior
Backups fail several times but since they iterate against the same volume they eventually complete:

[debug.log](https://github.com/neo4j/neo4j/files/4251147/debug.log)

This appears to repeatable with the normal tarball installation as well but the Docker flow makes for easier replication.

**Comment by RagnarW** [comment]
Closing due to unsupported version
