### ISSUE TITLE
Neo4j 4.0 - Unbind a database

### ISSUE THREAD

**Issue by mikeblum** [neo4j/neo4j#12404]
Unbinding a voting core member or read replica of a cluster doesn't allow for unbinding a particular database. Incidentally the verbosity of unbind is quite mute.

**Neo4j Version:** 4.0.0-enterprise
**Operating System:** Ubuntu 18.04 + Docker 
**API:** Docker

### Steps to reproduce
1. Create a casual cluster via docker a/o the 4.0.0-enterprise tarball
2. Evoke unbind:
https://neo4j.com/docs/operations-manual/current/tools/unbind/

```
./bin/neo4j-admin unbind --verbose
```

### Expected behavior

```
./bin/neo4j-admin unbind --verbose
```

is actually talkative about what it's doing

```
./bin/neo4j-admin unbind --verbose
This instance was not bound. No work performed.
```

Is this unbinding all the logical databases?
- system
- neo4j
- mydb-test
- etc

### Actual behavior

`unbind` is mute and we should be able to specify a database for the case of restoring  a backup for a particular database that's not the `system` or `neo4j` (default) databases.

**Comment by martinfurmanski** [comment]
@mikeblum There is currently no way of unbinding a single database and there is other work that needs to be done before that can be made available safely. For your use case of restoring a backup you should be able to use `DROP DATABASE` to get rid of all state associated with that particular database. Then you can `neo4j-admin restore` on all instances and after that do `CREATE DATABASE`.
