### ISSUE TITLE
Unsuccessful load of Reactome graph database into Neo4j

### ISSUE THREAD

**Issue by dvklopfenstein** [neo4j/neo4j#12408]
I am not able to load the Reactome graph.db database into Neo4j, similar to https://github.com/neo4j/neo4j/issues/12388.
Previously, this worked with an older version of Neo4j and Reactome.

**Neo4j Version:** neo4j-community-4.0.1      
**Operating System:** Ubuntu 16.04.4 LTS

### Steps to reproduce
I have also had a rather good experience with neo4j-community-3.4.7 and jdk1.8_0_192, but struggle to migrate to **jdk-11.0.6** and **neo4j-community-4.0.1**.

#### 1. Wiped everything from data/databases
```
$ rm -rf neo4j-community-4.0.1/data/databases/
$ mkdir neo4j-community-4.0.1/data/databases
```

#### 2. Downloaded graph.db from [**Reactome**](https://reactome.org/dev/graph-database)
```
$ wget https://reactome.org/download/current/reactome.graphdb.tgz    
$ tar zxvf reactome.graphdb.tgz
$ mv graph.db neo4j-community-4.0.1/data/databases 
```
 
#### 3. Start neo4j
```
$ neo4j-community-4.0.1/bin/neo4j start
Directories in use:
  home:         /home/neo4j/neo4j/neo4j-community-4.0.1/
  config:       /home/neo4j/neo4j/neo4j-community-4.0.1/conf/
  logs:         /home/neo4j/neo4j/neo4j-community-4.0.1//logs
  plugins:      /home/neo4j/neo4j/neo4j-community-4.0.1//plugins
  import:       /home/neo4j/neo4j/neo4j-community-4.0.1//import
  data:         /home/neo4j/neo4j/neo4j-community-4.0.1//data
  certificates: /home/neo4j/neo4j/neo4j-community-4.0.1//certificates
  run:          /home/neo4j/neo4j/neo4j-community-4.0.1//run
Starting Neo4j.
WARNING: Max 1024 open files allowed, minimum of 40000 recommended. See the Neo4j manual.
Started neo4j (pid 929). It is available at http://localhost:7474/
There may be a short delay until the server is ready.
See /home/neo4j/neo4j/neo4j-community-4.0.1//logs/neo4j.log for current status.
```
##### Try unsuccessfully to see Reactome database
I see this in the **neo4j-community-4.0.1/logs/neo4j.log**:
```
nohup: ignoring input
2020-02-27 18:19:07.228+0000 INFO  ======== Neo4j 4.0.1 ========
2020-02-27 18:19:07.245+0000 INFO  Starting...
2020-02-27 18:19:15.099+0000 INFO  Bolt enabled on localhost:7687.
2020-02-27 18:19:15.101+0000 INFO  Started.
2020-02-27 18:19:17.927+0000 INFO  Remote interface available at http://localhost:7474/
```

#### 4. Load *http://localhost:7474* into browser
It does not seem to connect to the data in *graph.db* asks me for a username and password. 

I don't believe I needed a username and password to run the Reactome graph db in the past. 

I try a login (*neo4j*) and password (*neo4j*):
![qu_Reqctome_login](https://user-images.githubusercontent.com/7278188/75476852-51fa0780-5969-11ea-9c85-dbbf2788823a.png)

It asks me to change my password, which I do:
![qu_Reqctome_chpasswd](https://user-images.githubusercontent.com/7278188/75476879-5b836f80-5969-11ea-9410-cc0ae0537643.png)

#### 5. Still cannot see Reactome database
I don't see any **Node Labels**, **Relationship Types**, etc. which I believe I saw the last time this worked.
![qu_Reqctome_access](https://user-images.githubusercontent.com/7278188/75476898-64744100-5969-11ea-8d0c-06dbbec2aed0.png)

#### These are the Neo4j environmental variables:
```
$ printenv | grep NEO4J
NEO4J_HOME=/home/neo4j/neo4j/neo4j-community-4.0.1
NEO4J_CONF=/home/neo4j/neo4j/neo4j-community-4.0.1/conf
```

### Expected behavior
I should be able to query the database like this:
![neo4j_pwy_subpwy](https://user-images.githubusercontent.com/7278188/75477086-bd43d980-5969-11ea-8251-e23ff4091aaf.png)

### Actual behavior
But this is what I see:
![qu_Reqctome_access](https://user-images.githubusercontent.com/7278188/75477169-e06e8900-5969-11ea-80e9-af8bfe38c5ed.png)

**Comment by dvklopfenstein** [comment]
Tagging @fabregat in case he can help

**Comment by fabregat** [comment]
Hi there!

I’m not longer maintaining Reactome’s graph database. So please email help@reactome.org (or wait until someone in charge comes back to you).

I hope you are doing very well and still enjoy this great graph database!

**Comment by chrisvest** [comment]
The reactome database you downloaded might be a simple store directory tar.gz from an earlier version of Neo4j. In 4.0 the transaction logs were moved to a separate directory. This might be what's upsetting your 4.0.1 installation. The `neo4j-admin dump` and `... load` tools take care of details like that. Try moving the logs to the correct directory, or see if you can get a dump file produced by `neo4j-admin dump` and load that instead.

**Comment by dvklopfenstein** [comment]
@fabregat , Thank you for suggesting the help@reactome.org. I will give it a try. It was working so well before. Can't wait to get it working again.

Thank you @chrisvest for the lead. I will check it out.

**Comment by dvklopfenstein** [comment]
FYI: Reactome support suggested trying Neo4j version 3.5.6.

I tried both Neo4j version 3.5.6 and Neo4j 3.5.15, but no luck so far.

Can't wait to use the Reactome graph database in Neo4j again, but not sure how to get it loaded again.

**Comment by gsviteri** [comment]
@dvklopfenstein I am sorry to hear you can't enjoy this great graph database. 
Let's get down to the solution - I installed neo4j 4.0.1 alpha and jdk11 and at the first run I got the same behaviour. Nothing had appeared. After checking the $neo4j_home/logs/debug.log

```
at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:114) 
at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:89)
at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:35)
Caused by: java.lang.RuntimeException:
org.neo4j.storageengine.migration.UpgradeNotAllowedException: Neo4j cannot be started because the database files require upgrading and upgrades are disabled in the configuration. Please set 'dbms.allow_upgrade' to 'true' in your configuration file and try again. Detailed description: The version you're upgrading to is using a new transaction log format. This is a non-reversible upgrade and you wont be able to downgrade after starting
        at org.neo4j.kernel.database.Database.start(Database.java:478)
        at org.neo4j.dbms.database.AbstractDatabaseManager.startDatabase(AbstractDatabaseManager.java:187)
org.neo4j.kernel.impl.transaction.log.LogVersionUpgradeChecker.check(LogVersionUpgradeChecker.java:54)
```

As recommended, I set  'dbms.allow_upgrade' to 'true'  in $neo4j_home/conf/neo4j.conf and I reloaded the Neo4j process. You can follow the migration at neo4j.log.

It worked for me, I hope it works for you and you can enjoy the Great graph database.

Cheers

**Comment by chrisvest** [comment]
@dvklopfenstein I installed Neo4j Desktop locally (so that I can easily get the Enterprise Edition on developer license, which has the `neo4j-admin restore` command) and then I downloaded and unpacked the reactome archive to my Downloads folder, and in Neo4j Desktop I created a new database called Reactome, where I then clicked "Manage" and opened a terminal to do the following:

```
installation-3.5.15$ ls -l data/databases/
total 0
installation-3.5.15$ bin/neo4j-admin restore --from=/home/chris/Downloads/reactome.graphdb/graph.db --database=graph.db --force=true
installation-3.5.15$ ls -l data/databases/
total 4
drwxrwxr-x. 4 chris chris 4096 Mar  4 12:12 graph.db
-rw-rw-r--. 1 chris chris    0 Mar  4 12:12 store_lock
installation-3.5.15$ ls -l data/databases/graph.db/
total 1482496
-rw-r--r--. 1 chris chris    156252 Mar  4 12:12 debug.log
drwxrwxr-x. 2 chris chris      4096 Mar  4 12:12 index
-rw-r--r--. 1 chris chris      8192 Mar  4 12:12 neostore
-rw-r--r--. 1 chris chris     47296 Mar  4 12:12 neostore.counts.db.a
-rw-r--r--. 1 chris chris     47296 Mar  4 12:12 neostore.counts.db.b
-rw-r--r--. 1 chris chris         9 Mar  4 12:12 neostore.id
-rw-r--r--. 1 chris chris  14426112 Mar  4 12:12 neostore.labelscanstore.db
-rw-r--r--. 1 chris chris      8190 Mar  4 12:12 neostore.labeltokenstore.db
-rw-r--r--. 1 chris chris         9 Mar  4 12:12 neostore.labeltokenstore.db.id
-rw-r--r--. 1 chris chris      8192 Mar  4 12:12 neostore.labeltokenstore.db.names
-rw-r--r--. 1 chris chris         9 Mar  4 12:12 neostore.labeltokenstore.db.names.id
-rw-r--r--. 1 chris chris  28804230 Mar  4 12:12 neostore.nodestore.db
-rw-r--r--. 1 chris chris         9 Mar  4 12:12 neostore.nodestore.db.id
-rw-r--r--. 1 chris chris      8192 Mar  4 12:12 neostore.nodestore.db.labels
-rw-r--r--. 1 chris chris         9 Mar  4 12:12 neostore.nodestore.db.labels.id
-rw-r--r--. 1 chris chris 683985288 Mar  4 12:12 neostore.propertystore.db
-rw-r--r--. 1 chris chris 236462080 Mar  4 12:12 neostore.propertystore.db.arrays
-rw-r--r--. 1 chris chris         9 Mar  4 12:12 neostore.propertystore.db.arrays.id
-rw-r--r--. 1 chris chris         9 Mar  4 12:12 neostore.propertystore.db.id
-rw-r--r--. 1 chris chris      8190 Mar  4 12:12 neostore.propertystore.db.index
-rw-r--r--. 1 chris chris         9 Mar  4 12:12 neostore.propertystore.db.index.id
-rw-r--r--. 1 chris chris      8192 Mar  4 12:12 neostore.propertystore.db.index.keys
-rw-r--r--. 1 chris chris         9 Mar  4 12:12 neostore.propertystore.db.index.keys.id
-rw-r--r--. 1 chris chris 232374272 Mar  4 12:12 neostore.propertystore.db.strings
-rw-r--r--. 1 chris chris         9 Mar  4 12:12 neostore.propertystore.db.strings.id
-rw-r--r--. 1 chris chris   1079100 Mar  4 12:12 neostore.relationshipgroupstore.db
-rw-r--r--. 1 chris chris         9 Mar  4 12:12 neostore.relationshipgroupstore.db.id
-rw-r--r--. 1 chris chris 290422560 Mar  4 12:12 neostore.relationshipstore.db
-rw-r--r--. 1 chris chris         9 Mar  4 12:12 neostore.relationshipstore.db.id
-rw-r--r--. 1 chris chris      8190 Mar  4 12:12 neostore.relationshiptypestore.db
-rw-r--r--. 1 chris chris         9 Mar  4 12:12 neostore.relationshiptypestore.db.id
-rw-r--r--. 1 chris chris      8192 Mar  4 12:12 neostore.relationshiptypestore.db.names
-rw-r--r--. 1 chris chris         9 Mar  4 12:12 neostore.relationshiptypestore.db.names.id
-rw-r--r--. 1 chris chris      8192 Mar  4 12:12 neostore.schemastore.db
-rw-r--r--. 1 chris chris         9 Mar  4 12:12 neostore.schemastore.db.id
-rw-r--r--. 1 chris chris  30113669 Mar  4 12:12 neostore.transaction.db.0
drwxrwxr-x. 3 chris chris      4096 Mar  4 12:12 schema
-rw-r--r--. 1 chris chris         0 Mar  4 12:12 store_lock
installation-3.5.15$ 
```

As you can see, the files got moved over to the store directory.

Then I started the database in Neo4j Desktop and opened the Browser window and ran a `match (n) return count(n)` query, which told me that there are 1920234 nodes in the database.

So that all seems to be working. The store itself is in the 3.4/3.5 format, so no store migration is necessary to use it on 3.5. It also does not appear to use any enterprise features, so after that ordeal you _should_ be able to create a `neo4j-admin dump` that you can `neo4j-admin load` into your Community Edition installation. I haven't tried that part out myself, so let me know if it doesn't work.

**Comment by chrisvest** [comment]
Between me and @gsviteri I think this one has been answered. Feel free to reopen if not.

**Comment by dvklopfenstein** [comment]
Thank you so much. I am up and running.
