### ISSUE TITLE
Neo4j /db/{databaseName} REST endpoints unavailable using community 4.0.0 docker image

### ISSUE THREAD

**Issue by Incara** [neo4j/neo4j#12411]
I am attempting to connect to the service root endpoint in the neo4j community edition. But I receive a 404 for `/db/neo4j` in the latest docker image. 

I am able to connect to `http://localhost:7474` which returns:

```
{
  "bolt_routing": "neo4j://0.0.0.0:7687",
  "transaction": "http://localhost:7474/db/{databaseName}/tx",
  "bolt_direct": "bolt://0.0.0.0:7687",
  "neo4j_version": "4.0.0",
  "neo4j_edition": "community"
}
```

I am also able to POST a new transaction via `http://localhost:7474/db/neo4j/tx`

Let me know if I'm routing this question to the wrong place or if there's documentation that I missed. If the service root endpoint is dependent on the volume mounting of the docker image, let me know, I've just been mounting it to a local directory instead of the one mentioned in the page. 

Another note, I downgraded to the neo4j:3.5 image and the data endpoints work as expected. 

**Neo4j Version:** 4.0.0
**Operating System:** Windows 10 (Docker for Windows) 
**API:** Docker

### Steps to reproduce
1. Docker run image as indicated here: https://hub.docker.com/_/neo4j/
2. Attempt to connect to http://localhost:7474/db/neo4j

### Expected behavior
Service Root response should be available

### Actual behavior
404 Not Found is returned.

**Comment by zhenlineo** [comment]
Hi @Incara,

There is no such path `http://localhost:7474/db/neo4j`. As you listed, the supported paths are:
```
discovery endpoint and/or service root: http://localhost:7474
transactional endpoint: http://localhost:7474/db/{databaseName}/tx
```

This path `http://localhost:7474/db/neo4j` look like a path to a database called `neo4j`. We would like to reserve the purpose of this path until we have figured out the best use of it. So in 4.0, it is not considered as a "service root".

Thanks for you input, however this issue is considered a won't fix for 4.0.
Cheers,
Zhen

**Comment by Incara** [comment]
Yes, `neo4j` is the default database name using the docker server. I understand not being able to see a service root, but I'm not sure what that means for querying via REST. The end goal of seeing a service root is understanding what REST capabilities I have in 4.0. Am I still able to query via REST? Is there documentation for how that works in 4.0 that I am missing?

**Comment by zhenlineo** [comment]
Hi @Incara,

The RESTful endpoints are removed in 4.0. There is only the transaction endpoint left for query via Cypher. Here is the [docs](https://neo4j.com/docs/http-api/current/introduction/) for the supported endpoints in 4.0.

If you are looking for these [RESTful endpoints](https://neo4j.com/docs/rest-docs/3.5/) in 3.5. They are no longer available.

**Comment by Incara** [comment]
Thank you for your help!
