### ISSUE TITLE
When starting, a message pops-up saying "Password has been changed" - Neo4j Desktop 1.2.4

### ISSUE THREAD

**Issue by vvvasilev** [neo4j/neo4j#12424]
- Neo4j version: 1.2.4
- Operating system: Windows 10 Enterprise
- API/Driver: N/A
- **Steps to reproduce**:
1. Clean installation of Neo4j Desktop
2. Add local graph, enter password
3. Start the graph
- Expected behavior:
The graph is started
- Actual behavior
Receiving the warning below
![image](https://user-images.githubusercontent.com/31281528/76323081-80ba9b00-62e4-11ea-94ae-12495a948d82.png)
If Ignored , the graph seems to be started, but Neo4j browser cannot execute any query

Additionally, include (as appropriate) log-files, stacktraces, and other debug output.

**Comment by shasaur** [comment]
Nice so this has been open for 3 years, effects what seems like a large number of users (potentially everyone?), and absolutely noone cares it seems like. 👍

**Comment by mnd999** [comment]
I suspect it was missed because it's in the incorrect repository. Neo4j Desktop issues should be raised [here](https://github.com/neo4j-devtools/neo4j-desktop). If this is still an issue for you, please open an issue there.
