### ISSUE TITLE
lacking docs re binary UUIDs + clumsy docker config/tedious defaults

### ISSUE THREAD

**Issue by desmap** [neo4j/neo4j#12428]
This on cyper-shell: `CALL apoc.uuid.install('User', {addToExistingNodes: true, uuidProperty: 'uuid'}) yield label, installed, properties, batchComputationResult;`

leads to

`Unknown procedure output: 'batchComputationResult' (line 2, column 118 (offset: 118))
"CALL apoc.uuid.install('User', {addToExistingNodes: true, uuidProperty: 'uuid'}) yield label, installed, properties, batchComputationResult;"`

and batch... is marked a line below

My docker-compose.yml has these envs...
```
      - NEO4J_apoc_uuid_enabled=true
      - NEO4JLABS_PLUGINS=["apoc"]
```
- Neo4j version: 4.0.1
- OS: Your docker-image

Besides, your docs don't say if the uuids are saved as binaries or not. If not => no-go. And, why do I have to enable uuids? This is a must-feature considering neo4j weird internal ids (with their reuse issue), i know this would be an issue on your docker image repo but I am short on time.

**Comment by martinfurmanski** [comment]
Hello @desmap!

This issue report should go to: https://github.com/neo4j-contrib/neo4j-apoc-procedures
Can you kindly move it there and close this one?

BR
/Martin

**Comment by desmap** [comment]
@martinfurmanski done, however would keep the rest issue watched, the docs[1] re UUID are subpar and as said lacking, binary UUIDs + a documentation if they are lacking or not are a must for a  DB with this price tag

[1] the docs re UUID feel like a official neo4j thing despite the feature comes from apoc

**Comment by martinfurmanski** [comment]
@desmap I'm not sure there is anything for the core of the neo4j product here. Could you perhaps be a bit more specific or perhaps point to places in the current documentation where you think the changes you imagine would fit? Otherwise perhaps this isn't actionable and I wouldn't know where to triage it.

**Comment by jexp** [comment]
I agree with @martinfurmanski 

this belongs to the apoc repo the UUID handler is all apoc and not Neo4j core product.

please raise the docker issues in https://github.com/neo4j/docker-neo4j

**Comment by jexp** [comment]
We will take your feedback on uuid's as a feature request.

**Comment by desmap** [comment]
@jexp as said, i raised the issue there already. re binary uuids: they are a must for every DB in 2020, especially if your actual ids are broken and reused (=> neo4j) and your price tag is one of the highest.

Users don't care if this is the apoc repo or whatever (btw they even don't care what apoc is and why you called apoc apoc): It's in the official docs of Neo4j https://neo4j.com/docs/labs/apoc/current/graph-updates/uuid/ and uuids are core feature of any DB. so it's up to you what to do with this issue, decide if this is not a bug what else, I think is a super urgent feature request and issue of your official neo4j docs (bc again they dont tell about how to save them as binary, saving them as string is non-sense).

ps: apologies for my harsh tone, but imagine you check out word processors and after days you find out that the most expensive alternative lacks spell checking, but offers a half-baken, broken one as a plugin.

**Comment by izoratti** [comment]
Hi @desmap, thanks for submitting this issue. I will take care of it as a request to add UUIDs procedures and as exposed IDs in graph elements.
