### ISSUE TITLE
Neo4j 4.0.1 gets initialized, but fails to start

### ISSUE THREAD

**Issue by StrangeTcy** [neo4j/neo4j#12427]
Running `neo4j start` without any plugins enabled (an empty `/var/lib/neo4j/plugins` folder) works fine, but adding any plugin leads to the following error:

> 2020-03-15 13:04:18.343+0000 INFO  ======== Neo4j 4.0.1 ========
> 2020-03-15 13:04:18.349+0000 INFO  Starting...
> 2020-03-15 13:04:27.211+0000 INFO  Called db.clearQueryCaches(): Query cache already empty.
> 2020-03-15 13:04:37.096+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabaseService@5d1907fb' was successfully initialized, but failed to start. Please see the attached cause exception "class org.neo4j.driver.internal.handlers.pulln.AutoPullResponseHandler can not implement org.neo4j.driver.internal.handlers.PullAllResponseHandler, because it is not an interface (org.neo4j.driver.internal.handlers.PullAllResponseHandler is in unnamed mod". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabaseService@5d1907fb' was successfully initialized, but failed to start. Please see the attached cause exception "class org.neo4j.driver.internal.handlers.pulln.AutoPullResponseHandler can not implement org.neo4j.driver.internal.handlers.PullAllResponseHandler, because it is not an interface (org.neo4j.driver.internal.handlers.PullAllResponseHandler is in unnamed mod".
> org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabaseService@5d1907fb' was successfully initialized, but failed to start. Please see the attached cause exception "class org.neo4j.driver.internal.handlers.pulln.AutoPullResponseHandler can not implement org.neo4j.driver.internal.handlers.PullAllResponseHandler, because it is not an interface (org.neo4j.driver.internal.handlers.PullAllResponseHandler is in unnamed mod".
> 	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
> 	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:164)
> 	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:114)
> 	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:89)
> 	at com.neo4j.server.enterprise.EnterpriseEntryPoint.main(EnterpriseEntryPoint.java:25)
> Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabaseService@5d1907fb' was successfully initialized, but failed to start. Please see the attached cause exception "class org.neo4j.driver.internal.handlers.pulln.AutoPullResponseHandler can not implement org.neo4j.driver.internal.handlers.PullAllResponseHandler, because it is not an interface (org.neo4j.driver.internal.handlers.PullAllResponseHandler is in unnamed mod".
> 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:465)
> 	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
> 	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:157)
> 	... 3 more
> Caused by: java.lang.RuntimeException: Error starting database server at /var/lib/neo4j/data/databases
> 	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:167)
> 	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:145)
> 	at com.neo4j.server.database.EnterpriseGraphFactory.newDatabaseManagementService(EnterpriseGraphFactory.java:38)
> 	at org.neo4j.server.database.LifecycleManagingDatabaseService.start(LifecycleManagingDatabaseService.java:88)
> 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
> 	... 5 more
> Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.procedure.impl.GlobalProceduresRegistry@55e2fe3c' was successfully initialized, but failed to start. Please see the attached cause exception "class org.neo4j.driver.internal.handlers.pulln.AutoPullResponseHandler can not implement org.neo4j.driver.internal.handlers.PullAllResponseHandler, because it is not an interface (org.neo4j.driver.internal.handlers.PullAllResponseHandler is in unnamed mod".
> 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:465)
> 	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
> 	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:158)
> 	... 9 more
> Caused by: java.lang.IncompatibleClassChangeError: class org.neo4j.driver.internal.handlers.pulln.AutoPullResponseHandler can not implement org.neo4j.driver.internal.handlers.PullAllResponseHandler, because it is not an interface (org.neo4j.driver.internal.handlers.PullAllResponseHandler is in unnamed mod
> 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
> 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:575)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
> 	at org.neo4j.procedure.impl.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:160)
> 	at org.neo4j.procedure.impl.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:138)
> 	at org.neo4j.collection.AbstractPrefetchingRawIterator.peek(AbstractPrefetchingRawIterator.java:50)
> 	at org.neo4j.collection.AbstractPrefetchingRawIterator.hasNext(AbstractPrefetchingRawIterator.java:36)
> 	at org.neo4j.procedure.impl.ProcedureJarLoader.loadProcedures(ProcedureJarLoader.java:111)
> 	at org.neo4j.procedure.impl.ProcedureJarLoader.loadProceduresFromDir(ProcedureJarLoader.java:85)
> 	at org.neo4j.procedure.impl.GlobalProceduresRegistry.start(GlobalProceduresRegistry.java:342)
> 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
> 	... 11 more
> 2020-03-15 13:04:37.098+0000 INFO  Neo4j Server shutdown initiated by request

- Neo4j version: 4.0.1
- Operating system: Ubuntu 18.04

**Comment by sherfert** [comment]
Seems like the root cause comes from the drivers somewhere: `org.neo4j.driver.internal.handlers.pulln.AutoPullResponseHandler can not implement org.neo4j.driver.internal.handlers.PullAllResponseHandler, because it is not an interface`

**Comment by StrangeTcy** [comment]
Ok; so, can you suggest any debugging measures to take? Should I try different versions of the jdbc driver? Anything else?

**Comment by chrisvest** [comment]
> adding any plugin leads to the following error

Which plugins did you add, specifically? If one or more of those contain a driver, it could be the source of the class version conflict.

**Comment by StrangeTcy** [comment]
I started with `neo4j-jdbc-driver-3.4.0.jar`, which proved to be enough. Disabling it and trying others one by one (`apoc-4.0.0.4-all.jar`, ` neo4j-graph-data-science-1.0.0-standalone.jar`) has similarly led to error.

**Comment by zhenlineo** [comment]
Hi @StrangeTcy,

The jdbc driver depends on a 1.6.1 neo4j java driver inside based on this [changelog](https://github.com/neo4j-contrib/neo4j-jdbc/releases/tag/3.4.0).

The server depends on a 4.0.0 neo4j java driver. So when you have both of them, maven will fail to load them correctly.

You could ask jdbc driver project whether they want to shade the driver. I can help you ask if neo4j would like to shade the driver. CC @PetrJanouch @tobias-johansson 

Cheers,
Zhen

**Comment by PetrJanouch** [comment]
Hi @StrangeTcy,

What do you mean by "Disabling it and trying others one by one" ? Do you mean physically removing the jar from plugins directory?

As has already been mentioned, the error you are getting is caused by two incompatible Neo4j java drivers on the class path. The information provided by @zhenlineo is not 100% correct as Neo4j server itself does not contain java driver, so it must be the plugins conflicting with each other. I can reproduce it with having neo4j-jdbc-driver-3.4.0.jar and apoc-4.0.0.4-all.jar in plugins directory. Having just neo4j-jdbc-driver-3.4.0.jar there works fine.

**Comment by PetrJanouch** [comment]
No response since 22nd March.
