### ISSUE TITLE
Open ID Connect built in support

### ISSUE THREAD

**Issue by AlexKeySmith** [neo4j/neo4j#12429]
**Is your feature request related to a problem? Please describe.**
Integrating with Azure Active Directory isn't simple and requires a LDAP middleman such as Active Directory Domain Services. Single Sign on is often a security prerequisite for large organisations, but requiring LDAP (and it's baggage) is a hurdle to adoption.

**Describe the solution you'd like**
First class support for OpenID Connect / oAuth2 / other modern authentication mechanisms.
Azure SQL Server is a good working example.

**Comment by izoratti** [comment]
Hi @AlexKeySmith, thanks for raising this issue. We are planning to provide support for more authentication methods in future versions of Neo4j, I added your request to the list.
