### ISSUE TITLE
Neo4j Harness ServerControls not found

### ISSUE THREAD

**Issue by Anunayth** [neo4j/neo4j#12430]
I am trying to migrate from neo4j 3.5.14 to neo4j 4.0.1. I am trying to write test harness. 
In 3.5.14 i was able to use org.neo4j.harness.ServerControls to create the embedded data server. But in v4.0.1 i am not able to use it. It throws error of import not found. 
Please help me out where to find the ServerControls or alternative to create the test-harness for 4.0.1.

Java version : 11 

The pom contains following dependencies.
 
<dependency>
	<groupId>org.neo4j</groupId>
	<artifactId>neo4j</artifactId>
	<version>4.0.1</version>
</dependency>

<dependency>
	<groupId>org.neo4j.test</groupId>
	<artifactId>neo4j-harness</artifactId>
	<version>4.0.1</version>
</dependency>

<dependency>
	<groupId>org.neo4j.driver</groupId>
	<artifactId>neo4j-java-driver</artifactId>
	<version>4.0.1</version>
</dependency> "

**Comment by Anunayth** [comment]
> I am trying to migrate from neo4j 3.5.14 to neo4j 4.0.1. I am trying to write test harness.
> In 3.5.14 i was able to use org.neo4j.harness.ServerControls to create the embedded data server. But in v4.0.1 i am not able to use it. It throws error of import not found.
> Please help me out where to find the ServerControls or alternative to create the test-harness for 4.0.1.
> 
> Java version : 11
> 
> The pom contains following dependencies.
> 
> org.neo4j neo4j 4.0.1 org.neo4j.test neo4j-harness 4.0.1 org.neo4j.driver neo4j-java-driver 4.0.1 "

**Comment by sherfert** [comment]
The equivalent classes in 4.0 are `org.neo4j.harness.Neo4j`,  `org.neo4j.harness.Neo4jBuilder`, and `org.neo4j.harness.Neo4jBuilders`. You will start will `Neo4jBuilders.newInProcessBuilder().build()`
