### ISSUE TITLE
Existential subquery and OR in WHERE clause cause UnknownError

### ISSUE THREAD

**Issue by ielatif** [neo4j/neo4j#12438]
> An UnknownError occurs when I use EXISTS {...} in conjunction with OR in a WHERE clause. Is this a bug or am I missing something?
> 
> Create sample nodes
> 
> CREATE (a:A { uuid:'uuid1', foo:true })-[:KNOWS]->(b:B { uuid:'uuid2' })
> Sample query
> 
> MATCH (a:A { uuid:'uuid1' }),
> (b:B { uuid:'uuid2' })
> WHERE a.foo = TRUE
> OR EXISTS {
>   MATCH (a)-[:KNOWS]->(b)
> }
> RETURN a
> Error
> 
> Neo.DatabaseError.General.UnknownError
> There should be at least one pattern expression

https://stackoverflow.com/questions/60678772/existential-subquery-and-or-in-where-clause-cause-unknownerror

Issue already fixed by @Lojjs https://github.com/neo4j/neo4j/commit/dc2065943bdfa236ccc87bdb5e051cce4f8bf523

Reporting this issue to share that it is known and solved.

**Comment by sherfert** [comment]
The fix will be included in the 4.0.4 patch release.
