### ISSUE TITLE
2.0.0-M5 /db/data/label/<label>/nodes doesn't seem to work

### ISSUE THREAD

**Issue by gcolbert** [neo4j/neo4j#1243]
According to http://docs.neo4j.org/chunked/milestone/rest-api-node-labels.html#rest-api-get-all-nodes-with-a-label it is possible to get all nodes with a given label.

But this doesn't seem to work with 2.0.0-M5 :

http> get /db/data/node/3/labels
==> 200 OK
==> [ "organisation", "établissement" ]

http> get /db/data/label/organisation/nodes
==> 200 OK
==> [ ]

I expected to get all nodes with label "organisation", and so to get node 3, why does it return an empty array?

**Comment by jakewins** [comment]
This was resolved in 2.0.0 GA
