### ISSUE TITLE
[4.0.2][Security] Deny then Grant access to system db prevents user from connecting

### ISSUE THREAD

**Issue by ikwattro** [neo4j/neo4j#12432]
When we deny access to the `system` db to a role, it prevents a user having that role to connect to the neo4j server. 
When granting again access to the db for the same role, the same user is still unable to connect to the neo4j server

**Neo4j Version:** 4.0.2
**Operating System:** OSX
**API:** cypher-shell

### Steps to reproduce

CREATE USER charlie SET PASSWORD 'secret1' CHANGE NOT REQUIRED;
CREATE ROLE analysts
GRANT ROLE analysts TO charlie
GRANT ACCESS ON DATABASE neo4j TO analysts

--
DENY ACCESS ON DATABASE system TO analysts
```
# cypher-shell
username: charlie
password: *******
Database access is not allowed for user 'charlie' with roles [analysts].
```

GRANT ACCESS ON DATABASE system TO analysts

```
# cypher-shell
username: charlie
password: *******
Database access is not allowed for user 'charlie' with roles [analysts].
```

### Expected behavior

The user `charlie` should be able to connect to the Neo4j server after the role `analysts` has been granted access again to the `system` database.

### Actual behavior

User `charlie` cannot connect to the Neo4j server instance while he should have the privileges to.

**Comment by InverseFalcon** [comment]
This is intended behavior, a GRANT and a DENY do not cancel each other out. When there is a simultaneous GRANT and DENY of access to something, the DENY will take precedence.

If you want to undo a DENY, then [REVOKE](https://neo4j.com/docs/cypher-manual/current/administration/security/subgraph/#administration-security-subgraph-revoke) the DENY. 

This is noted at the bottom of [this section of the docs](https://neo4j.com/docs/cypher-manual/current/administration/security/subgraph/#administration-security-subgraph-introduction):

> It is important to note that using DENY does NOT erase a GRANT command; they both exist. The only way to erase a privilege is with REVOKE.
