### ISSUE TITLE
Turn on GitHub automated security updates

### ISSUE THREAD

**Issue by janekdb** [neo4j/neo4j#12453]
The Neo4j repo is eligible for configuration with automated security updates.

https://help.github.com/en/github/managing-security-vulnerabilities/configuring-automated-security-
updates

Here is an example of the kind of pull requests that will be generated,

https://github.com/janekdb/neo4j-inspect/pull/1

Having this turned on does not appear to have a downside apart from needing to review the occasional security update PR.

I'm assuming this is not already configured since there are not commits from

`git log --all --author=dependabot`

**Comment by chrisvest** [comment]
Those PRs interfere with our CLA check. We also don't need them. We already have periodic automated security scans, and each notice is manually investigated. We also regularly bump dependencies, which is not always as trivial as dependabot thinks.

It's a good idea for smaller projects, but it's not for us.

**Comment by janekdb** [comment]
Thanks for explaining this!
