### ISSUE TITLE
org.neo4j.driver.exceptions.ClientException Unknown function 'ID'

### ISSUE THREAD

**Issue by kaplan441** [neo4j/neo4j#12454]
I cloned the belowing example code.
https://github.com/neo4j-examples/movies-java-spring-data-neo4j

I started same application in my computer then it throwed an exception.

org.neo4j.driver.exceptions.ClientException Unknown function 'ID'

-Neo4j version : 3.5.16
-Spring boot example code and pom.xml dependency are same in GitHub link
-Computer language is Turkish

Please help me.

**Comment by sherfert** [comment]
Hi @kaplan441 
That repository is no longer maintained. Can you please try https://github.com/neo4j-examples/spring-data-neo4j-intro-app instead?
