### ISSUE TITLE
Not able to run neosemantics in the neo4j 4.0.3 version.

### ISSUE THREAD

**Issue by aravindkota** [neo4j/neo4j#12468]
Hi all,

I have added the procedure for semantics by downloading the latest jar file from neolabs repo. But When running the following command 'call n10s.graphconfig.init()' I am getting 'Neo.ClientError.Procedure.ProcedureNotFound' error message. 

I am new to neo4j and am trying to load rdf data into the databse. Any help would be appreciated.

**Comment by sherfert** [comment]
Hi @aravindkota 
I see that you have opened and resolved the same issue here: https://github.com/neo4j-labs/neosemantics/issues/155
