### ISSUE TITLE
For several given points, how to quickly find their common points, and sort the Common points?

### ISSUE THREAD

**Issue by dwanboweb** [neo4j/neo4j#12486]
I want to use neo4j to store structured medical diagnostic records.
![image](https://user-images.githubusercontent.com/17172451/80303488-29fd1800-87e3-11ea-97ac-995d618dc2a8.png)
The green node represents a medical report, the red node represents the structured report data (each report is a tree),and  the blue node are medical concepts(abount 20,000 to 30,000), and are used to indicate the meaning of the red nodes. A red node may connected to several blue nodes to express complex meanings.
A blue Concept node can be indirectly connected to millions of different reporting nodes. How to quikly find out which reports (green dots) contain  the given several concept points? And I don't need all the results, just need top K（The found subtree is as small as possible and will be close to the search · intent）
I wirte cypher like this:
`match p1=(report:searchReport)-[:search|activesearch*1..5]->(targetc1:Concept{ConceptID:'radlex:43591'})
USING INDEX targetc1:Concept(ConceptID)

match p2=(report:searchReport)-[:search|activesearch*1..5]->(targetc2:Concept{ConceptID:'radlex:5624'})
USING INDEX targetc2:Concept(ConceptID)

match p3=(report:searchReport)-[:search|activesearch*1..5]->(targetc3:Concept{ConceptID:'radlex:49910'})
USING INDEX targetc3:Concept(ConceptID)

match p4=(report:searchReport)-[:search|activesearch*1..5]->(targetc4:Concept{ConceptID:'smit:SMIT-0001-CXR-PA'})
USING INDEX targetc4:Concept(ConceptID)

match p5=(report:searchReport)-[:search|activesearch*1..5]->(targetc5:Concept{ConceptID:'radlex:13173'})
USING INDEX targetc5:Concept(ConceptID)

match p6=(report:searchReport)-[:search|activesearch*1..5]->(targetc6:Concept{ConceptID:'radlex:4756'})
USING INDEX targetc6:Concept(ConceptID)

match p7=(report:searchReport)-[:search|activesearch*1..5]->(targetc7:Concept{ConceptID:'radlex:28674'})
USING INDEX targetc7:Concept(ConceptID)

match p8=(report:searchReport)-[:search|activesearch*1..5]->(targetc8:Concept{ConceptID:'radlex:28726'})
USING INDEX targetc8:Concept(ConceptID)
return report,collect(p1)+collect(p2)+collect(p3)+collect(p4)+collect(p5)+collect(p6)+collect(p7)+collect(p8) as paths`
But very slowly.I have to find all matched data and sort by C# outside.What's the best solution?
Thank you very much

**Comment by asashour** [comment]
The [community](https://community.neo4j.com/) is the right place to ask similar questions.

**Comment by dwanboweb** [comment]
OK thanks
