### ISSUE TITLE
Neo.DatabaseError.General.UnknownError Unfortunately, the planner was unable to find a plan within the constraints provided.

### ISSUE THREAD

**Issue by Andy2003** [neo4j/neo4j#12484]
Given: Movie example Dataset
Cypher: 

    MATCH
      (movie:Movie)
    OPTIONAL MATCH
      (movie)<-[:DIRECTED]-(a:Person),
      (movie)<-[:DIRECTED]-(b:Person)
      WHERE a.name = "Lilly Wachowski" AND b.name = "Lana Wachowski"
    OPTIONAL MATCH
      (movie)<-[:DIRECTED]-(c:Person)
      WHERE c.name = "Clint Eastwood"
    WITH
      DISTINCT movie,
       count(a) as countA,
       count(b) as countB,
       count(c) as countC
    RETURN DISTINCT movie { .title }, countA, countB, countC

Fails with neo4j `4.0.3` with following error:

    Unfortunately, the planner was unable to find a plan within the constraints provided.
    Try increasing the config values `unsupported.cypher.idp_solver_table_threshold`
    and `unsupported.cypher.idp_solver_duration_threshold` to allow
    for a larger sub-plan table and longer planning time.

In neo4j `3.5.17` this query works well.

**Comment by Andy2003** [comment]
cc @jexp

**Comment by mnd999** [comment]
Hi Andy,
We attempted to reproduce this by spinning up new 4.0.3 databases for both enterprise and community, loading the movies dataset using `:play movies` and running your query above. In both cases the query executed okay.
Could you share you `neo4j.conf` and let us know if we've missed anything in our steps to reproduce. If your movies dataset has been modified can you share the modifications?

**Comment by Andy2003** [comment]
I completely forgot that I had created two indices:

    CREATE INDEX person_name FOR (n:Person) ON (n.name)
    CREATE INDEX movie_title FOR (n:Movie) ON (n.title)

With these indices applied you will get the error mentioned in the issue.

**Comment by mnd999** [comment]
This should be fixed by https://github.com/neo4j/neo4j/commit/5db461fe8b64d42004e8f74181536548868a649e. This should be included in the next set of patch releases.

**Comment by mnd999** [comment]
Neo4j 4.0.5 has now been released, and this issue is resolved. Will close this, but feel free to re-open if you have any issues.

Thanks for the report!
