### ISSUE TITLE
neo 4.0.3 - labels not usable after bulk import 

### ISSUE THREAD

**Issue by amitabak-MA** [neo4j/neo4j#12498]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. 
If you have questions on how to use Neo4j, please ask on [StackOverflow](https://stackoverflow.com/questions/tagged/neo4j) instead of creating an issue here.

To help us understand your issue, please specify important details, primarily:

- Neo4j version: 4.0.3
- Operating system: (for example Windows 95/Ubuntu 16.04) Mac catalina
- API/Driver: (for example Cypher/Java API/Python driver vX.Y.Z)
- **Steps to reproduce**
Global JVM setting: openjdk version "11.0.3" 2019-04-16
bulk import to a new DB using bin/neo4j-admin import
resulted in 
Imported:
  16512899 nodes
  145435092 relationships
  194973789 properties

After the import finishes open desktop and , start the DB and run the following queries:

1) call db.labels() - results in "(no changes, no records)"
2) match(n) return labels(n) limit 2... This resulted in 2 lables being returned as expected
![image](https://user-images.githubusercontent.com/52035400/80791659-02b79980-8b9b-11ea-8267-32e83e17a155.png)
At the same time the desktop shows the following message regarding no lables in the DB
![image](https://user-images.githubusercontent.com/52035400/80791700-211d9500-8b9b-11ea-8e31-27bbc05d9c9e.png)

3) run the following query  "match(n:Users) return n limit 1"
    I was expecting to return a single user but it returns "(no changes, no records)"

4) desktop shows there are relationships inspite bulkimport result showing they were imported 
![image](https://user-images.githubusercontent.com/52035400/80793275-5a580400-8b9f-11ea-810f-d1fcb895344e.png)
  
- Expected behavior. labels to be usable after bulk import 
- Actual behavior. labels are "semi-known".. on one hand i can get the label of a node .. on the other I cant use it in queries

**Comment by amitabak-MA** [comment]
Additional info:  It seems that the root cause is some hoe related to the sequences of action I take when importing data using "neo4j-admin import"
IF I create a brand new DB and without EVER login in to it , I run the import.. all is well and the data becomes usable
ELSE if I even login once to the DB.. data ends up corrupted  and unusable .

Question: is this the expected result current state of 4.0.3 ? ("expected" being an understatement given that as user I would like to be able to bulk upload without using the relative extremely slow APIs  )

**Comment by tinwelint** [comment]
I would that guess this is a counts store issue, since labels that have 0 usage count will be excluded from that list. So you're saying that:

1 create database
2 log in to it
3 run an import onto it
--> no labels in listing

If you skip (2) you get labels in listing?

**Comment by tinwelint** [comment]
@amitabak-MA OK I actually found the problem. In your case it's just the `neostore.counts.db` that is wrong after the import, you can shut down the db, remove that file and start again and it will be rebuilt. The next 4.0.x version will include this fix. Cheers
