### ISSUE TITLE
Adding Multiple Limit for Cypher Queries

### ISSUE THREAD

**Issue by ozgursoy** [neo4j/neo4j#12499]
Hi, Adding multiple "LIMIT" into queries would be great feature to create much more efficient queries.

Ex: I want to find only one node then use it with "WITH"

MATCH (artist:Artist)<-[similarRelation:SIMILAR]-(artist2:Artist)<-[:ON]-(music:Music)
return music, COUNT(similarRelation) as countRelation
ORDER BY countRelation DESC
LIMIT 1
WITH music, countRelation
......
LIMIT 10

in this example, second limit won't work exactly we want. Alternatively importing variables into subquery and using "WITH" would solve this problem. Because we can use multiple LIMIT on subquery (  CALL {}  )

My current solution is ordering all nodes then collect nodes without "LIMIT" ,but this is not an efficient query.

WITH COLLECT(artist)[0..1] as artists

If there is another way to solve this problem, I would be very glad if you share it with me.

**Comment by sherfert** [comment]
You can specify multiple consecutive `LIMIT`s in a query. How about changing your query like this:

```
MATCH (artist:Artist)<-[similarRelation:SIMILAR]-(artist2:Artist)<-[:ON]-(music:Music)
WITH music, similarRelation LIMIT 1
WITH music, COUNT(similarRelation) as countRelation ORDER BY countRelation DESC
WITH music, countRelation
......
LIMIT 10
```

Or maybe I did not fully comprehend what you were trying to achieve? A full query with `collect` or `CALL` that does what you want would maybe help me.

**Comment by ozgursoy** [comment]
I solved with apoc, just in case someone encounter the same problem
Thanks @sherfert 

MATCH (u:User {name: "Bugra"})
WITH u
CALL apoc.cypher.run('
	MATCH (u)-[:LIKE]->(artist:Artist)
    WITH rand() as random, artist
    return artist
    ORDER BY random ASC
    LIMIT 3
',{u:u}) YIELD value
WITH value.artist as artist
CALL apoc.cypher.run('
    MATCH ...
    RETURN a2
    ORDER BY counter DESC 
    LIMIT 2
',{artist:artist}) YIELD value
WITH value.a2 as a2, artist
return artist.name, collect(a2.name)
