### ISSUE TITLE
Got this weird error when trying to connect Neo4j database with PHP

### ISSUE THREAD

**Issue by raymondlinnn** [neo4j/neo4j#12504]
Fatal error: Uncaught GraphAware\Bolt\Exception\HandshakeException: Handshake Exception. Unable to negotiate a version to use. Proposed versions were [1,0,0,0] in /Users/raymondlin/Downloads/411project1/vendor/graphaware/neo4j-bolt/src/Driver.php:165 Stack trace: #0 /Users/raymondlin/Downloads/411project1/vendor/graphaware/neo4j-bolt/src/Driver.php(151): GraphAware\Bolt\Driver->throwHandshakeException('Handshake Excep...') #1 /Users/raymondlin/Downloads/411project1/vendor/graphaware/neo4j-bolt/src/Driver.php(115): GraphAware\Bolt\Driver->handshake() #2 /Users/raymondlin/Downloads/411project1/vendor/graphaware/neo4j-php-client/src/Connection/Connection.php(192): GraphAware\Bolt\Driver->session() #3 /Users/raymondlin/Downloads/411project1/vendor/graphaware/neo4j-php-client/src/Connection/Connection.php(109): GraphAware\Neo4j\Client\Connection\Connection->checkSession() #4 /Users/raymondlin/Downloads/411project1/vendor/graphaware/neo4j-php-client/src/Client.php(67): GraphAware\Neo4j\Client\Connection\Connection->run('MATCH ( in /Users/raymondlin/Downloads/411project1/vendor/graphaware/neo4j-bolt/src/Driver.php on line 165

**Comment by asashour** [comment]
The location for PHP questions is [here](https://community.neo4j.com/c/drivers-stacks/php/35).

Please post it there, and specify more details, like the driver version and Neo4J server version.

**Comment by technige** [comment]
@raymondlinnn From the error detail you have provided, GraphAware's PHP driver supports Bolt version 1, which is available in all Neo4j releases between 3.0 and 3.5 inclusive. For Neo4j 4.0 and above, which I assume you are using, a later version of the protocol is required.

So your best bet will be to raise this issue with GraphAware directly, as this isn't software that is provided or supported directly by Neo4j.
