### ISSUE TITLE
db.labels() does not list all labels accessible by a user

### ISSUE THREAD

**Issue by luanne** [neo4j/neo4j#12501]
When READ and TRAVERSE privileges are granted on a specific label, only that label is returned in `db.labels()` and also shown in the browser Database Information->Node Labels section.
It should also return labels of nodes which have multiple labels, including the one which has been granted permissions.

Either that, or allowing access to a node with multiple labels where the user has privileges to access just one label, is a bug. Not sure what principle is used here.

**Neo4j Version:** 4.0.3
**Operating System:** MacOS Mohave
**API:** Cypher, Neo4j Browser

### Steps to reproduce
Set up data as follows:

```
CREATE (n:Review:IMDB {name:"imdb review 1"});

CREATE (n:Movie:Netflix {name:"netflix movie 1"});

CREATE (n:Movie:IMDB {name:"imdb movie 1"});

CREATE USER luanne
SET PASSWORD 'luanne' CHANGE NOT REQUIRED;

CREATE USER netflix
SET PASSWORD 'netflix' CHANGE NOT REQUIRED;

CREATE USER imdb
SET PASSWORD 'imdb' CHANGE NOT REQUIRED;

CREATE ROLE netflixRole;

CREATE ROLE imdbRole;

GRANT READ {*} ON GRAPH neo4j NODES Netflix TO netflixRole;

GRANT TRAVERSE ON GRAPH neo4j NODES Netflix TO netflixRole

GRANT READ {*} ON GRAPH neo4j NODES IMDB TO imdbRole;

GRANT TRAVERSE ON GRAPH neo4j NODES IMDB TO imdbRole;

GRANT ACCESS ON DATABASE neo4j TO imdbRole;

GRANT ACCESS ON DATABASE neo4j TO netflixRole;

GRANT ROLES imdbRole,netflixRole to luanne;

GRANT ROLES netflixRole to netflix;

GRANT ROLES imdbRole to imdb;

```

Log in as `imdb` and check the labels displayed in the Neo4j browser: It shows only `IMDB` but not `Movie` and `Review`.

`call db.labels()` also returns only `IMDB`

But

```
MATCH (n)
WITH DISTINCT labels(n) AS labels
UNWIND labels AS label
RETURN DISTINCT label ORDER BY label
```
returns
`IMDB`, `Movie`, `Review`

and `MATCH (n:Movie) return n` also returns the movie node.

### Expected behavior
Either `IMDB`, `Movie`, `Review` should be returned by `db.labels()` and shown in the database information of the Neo4j browser OR, this is expected behaviour and I should _not_ be able to either
`MATCH (n:Movie) return n` 

 or

```
MATCH (n)
WITH DISTINCT labels(n) AS labels
UNWIND labels AS label
RETURN DISTINCT label ORDER BY label
```

### Actual behavior
See above

**Comment by SaschaPeukert** [comment]
Hej,

This is actually intended behavior. But I will make sure that we improve our documentation around this.
