### ISSUE TITLE
Usage of parameters of type list

### ISSUE THREAD

**Issue by ofraiwan** [neo4j/neo4j#12505]
List parameters cannot be indexed in neo4j 4. Whenever you try to take an element from a parameter of type list, this error is thrown:

```
**Neo.DatabaseError.General.UnknownError**
Did not find any type information for expression ContainerIndex(Parameter(r,Any),SignedDecimalIntegerLiteral(0))
```

Neo4j Version: 4.0.3
Operating System: Ubuntu 18.04.3 LTS
DB Mode: Causal Cluster

An example query to reproduce the issue is:
```
MATCH (user:User)
WHERE ($range[0] > user.id OR user.id > $range[1])
return user
limit 1
```

$range is the parameter in question with an example value [100, 200]

This error does not happen in the previous neo4j version 3.5, as we are currently migrating to neo4j 4. It happens in the neo4j browser, and through drivers. I currently use python driver 1.7.6

**Comment by cybersam** [comment]
See https://stackoverflow.com/a/61642699/974731 for a couple of workarounds. They might help to debug this issue.

**Comment by sherfert** [comment]
Thanks for the bug report. We'll look into it.
