### ISSUE TITLE
[Security][FullTextSearch] FTS not yielding any results when fine-grained access control is used

### ISSUE THREAD

**Issue by ikwattro** [neo4j/neo4j#12502]
When using fine-grained access control, FTS is not yielding any results even if a logged in user has access to some of the attributes of a given node label.

**Neo4j Version:** 4.0.3
**Operating System:** OSX
**API:** Browser

### Steps to reproduce

```
CREATE DATABASE healthcare;
CREATE ROLE doctor;
GRANT ACCESS ON DATABASE healthcare TO doctor;
CREATE USER tina SET PASSWORD "$secret5" CHANGE NOT REQUIRED;
GRANT TRAVERSE ON GRAPH healthcare NODES * TO doctor;
GRANT READ {*} ON GRAPH healthcare NODES Patient TO doctor;
DENY READ {ssn} ON GRAPH healthcare NODES Patient TO doctor;
GRANT ROLE doctor TO tina;
:use healthcare;
CREATE (n:Patient {name: "Chris", ssn: "ssn123"});
CALL db.index.fulltext.createNodeIndex('Patient', ['Patient'], ['name', 'ssn']);
```

Log in as `tina` 

```
CALL db.index.fulltext.queryNodes('Patient', 'chris');
```
0 results

### Expected behavior

FTS should return results matching on properties the logged in user is granted to access.

### Actual behavior

0 results for any FTS query.

A workaround by creating dedicated FTS indexes with only the attributes that a role has access, however : 
a) it's not documented
b) it is not manageable when you have a consequent organization and security is enforced at some relatively strict level.

**Comment by SaschaPeukert** [comment]
Thank you for reporting. We've published some documentation about our limitations around RBAC and FTS: https://neo4j.com/docs/cypher-manual/4.1/administration/security/limitations/#administration-security-limitations-indexes
