### ISSUE TITLE
neo4j-admin 3.5 backup does not explain it could not connect to server

### ISSUE THREAD

**Issue by jsoref** [neo4j/neo4j#12514]
- Neo4j version: 3.5.14
- Operating system: macOS / Linux
- API/Driver:
- **Steps to reproduce**
1. Do not run a neo4j server (or any other server) on `127.0.0.1:6462`
1. Ask `neo4j-admin` to perform a backup from that address:
    ```sh
    neo4j_backup=$(mktemp -d)
    report_dir=$(mktemp -d)
    JAVA_HOME=$(oracle_jdk8) \
    neo4j-admin backup \
        --protocol=catchup \
        --from=127.0.0.1:6462 \
        --backup-dir=$neo4j_backup \
        --cc-report-dir=$report_dir \
        --name=backup; echo $?
    ```

- Expected behavior
    An error message indicating that no server responded from `127.0.0.1:6462`.
    Bonus points for an exit code that distinguishes between "spoke to a server" and "couldn't speak to a server".

- Actual behavior
    ```
    The selected protocol `catchup` means that it is only compatible with causal clustering instances
    command failed: Failed to run a backup using the available strategies.
    1
    ```

Additionally, include (as appropriate) log-files, stacktraces, and other debug output.

* There are no log files generated -- this is part of the problem
* There are no stack traces generated -- this is part of the problem
* There is no debug output, and there isn't any obvious way to enable debug output -- this is part of the problem (version 4.0 supports a `--verbose` flag -- I'm not sure if it would help)

https://neo4j.com/docs/operations-manual/3.5/backup/performing/#backup-performing-command says that `1` means:
> Backup failed.

This is correct, the backup failed.

It also isn't helpful. It'd be much more helpful if I could distinguish between "could not connect to server" and "I spoke to the server and things went bad". I'm fairly certain that the second case can happen. -- If not, the documentation should just say that `1` means "could not connect to server" -- and again, I highly doubt that's what it means.

**Comment by taraspos** [comment]
I'm having a similar issue:
```
neo4j-admin backup --backup-dir=/tmp --name=test
command failed: Execution of backup failed
```

And no info at all. In the server debug logs I can see the following:
```
2021-01-25 13:42:20.378+0000 INFO [o.n.c.p.h.HandshakeServerInitializer] Handshake completed on channel [id: 0xacfef359, L:/127.0.0.1:6362 - R:/127.0.0.1:60004]. Installing: catchup version:1
```
and that is it.

**Comment by RagnarW** [comment]
Closing due to unsupported version
