### ISSUE TITLE
Neo4J Online Backup Does Not Work

### ISSUE THREAD

**Issue by deemeetree** [neo4j/neo4j#12518]
- Neo4j version: 3.3.3 Enterprise
- Operating system: Ubuntu

- **Steps to reproduce**
- Expected behavior
Running 
```
neo4j-admin backup --backup-dir=backups --name=graph.db --from=localhost:6362 --timeout=59m --pagecache=2G
```
Online backup should work .

- Actual behavior

```
2020-06-02 11:17:04.673+0000 INFO [o.n.c.s.StoreCopyClient] Copying neostore.propertystore.db
command failed: Backup failed: Unexpected Exception
```

I've been trying to deal with it for 1(!) month already. Here's a thread on Neo4J forum. I tried everything, nothing worked.

https://community.neo4j.com/t/cant-backup-remote-database-using-neo4j/18332/33

It looks like Neo4J enterprise backup function simply does not work.

**Comment by mnd999** [comment]
Seems like this being looked into in the forum for the moment

**Comment by mnd999** [comment]
I haven't seen any replies on the forum thread for a little while so I will assume this is resolved, feel free to re-open if this is not the case.
