### ISSUE TITLE
v4.0.4, Query completed after time is incredibly wrong.

### ISSUE THREAD

**Issue by bwinchester** [neo4j/neo4j#12528]
Neo4J Search results timer when using called procedures is orders of magnitude off from the truth. Im loading CSV data. When I create load statements to merge/create 2 nodes and 1 relationship off each record, using native cypher/just no subqueries, the search results time to complete the search/statement appears accurate. When you use called procedures in your statement, the search/statement might take minutes, but the completed after time could be fractions of a second. For example, I have a statement to load 1MM lines of csv, might take a couple of minutes to run (using merge). When you use `CALL apoc.merge.relationship` , the query results appear to take the same time to create, but the response from Neo is that it completed in 187ms. whereas it might actually take 5 minutes.

**Neo4j Version:** 4.0.4
**Operating System:**  MacOS 10.15.4
**API/Driver:**  N/A, using Neo4J Desktop to test performance differences

### Steps to reproduce
1. Start 3.5.6 Neo4J. Load CSV with a lot of data. Observe what appears as an accurate time reported to complete the query.
2. Start 4.0.4 Neo4J, Load the same CSV with a lot of data. Observe that the query spinner in the Neo browser spins for correct amount of time, waiting, but the results claim an absurd completion time. 

### Expected behavior
Time query actually takes is reported correctly.

### Actual behavior
when calling procedures, the time a query takes is incorrect.

**Comment by sherfert** [comment]
![Screenshot from 2020-07-01 11-13-18](https://user-images.githubusercontent.com/22634484/86226433-f3999b80-bb8b-11ea-8cc9-484aac1fd37b.png)

I tried with `apoc.util.sleep()` and could not reproduce the problem. Could you @bwinchester provide a CSV file and the exact Cypher you are running so that I can reproduce the issue?

**Comment by sherfert** [comment]
Please let me know if you can help us reproduce the issue.

**Comment by bwinchester** [comment]
This came down to understanding load csv statement taking a while for Neo4J to process the csv, but the cypher call returning a status that it received the cypher request and it appears to be valid. Like a fire and forget.
