### ISSUE TITLE
v.4.0.4, always add 'neo4j' in front of the url intead of the used 'bolt'

### ISSUE THREAD

**Issue by caowencai** [neo4j/neo4j#12529]
the connect url has been set to blot, but the default curl head (version3.5 ) is set to 'bolt', but in verison 4.0.4, it is set to 'neo4j' which can not be connected rght.
So I  have to change it manually.
![image](https://user-images.githubusercontent.com/7457523/83847716-4b84e400-a73f-11ea-9838-88c5dccb2184.png)

**Comment by iamFIREcracker** [comment]
Yeah, I flagged the same yesterday -- https://github.com/neo4j/neo4j/issues/12527

**Comment by gjmwoods** [comment]
@caowencai This ought to have been resolved in the latest neo4j patch version. Closing for now, please feel free to reopen if the issue is still present.
