### ISSUE TITLE
Multiple ANY in WHERE clause fail to match: local variable issue

### ISSUE THREAD

**Issue by vlasta-kus** [neo4j/neo4j#12538]
**Neo4j Version:** 4.1.0
**Operating System:** macOS Catalina 10.15.3
**API:** Cypher

### Steps to reproduce
Create test nodes:
```
create (n:Test {id: 1, ne: ["TIT", "O"]})
create (n2:Test {id: 2, ne: ["PER"]})
create (n)-[:NEXT]->(n2)
```

Task: match this pattern provided that you have for each node a list of desired strings, any of which is enough to match the node

### Expected behavior
This query should return the pattern:
```
MATCH path=(src:Test)-[r1:NEXT]->(dst:Test)
WHERE ANY(ne IN src.ne WHERE ne IN ["TIT"]) AND ANY(ne IN dst.ne WHERE ne IN ["PER"]) 
RETURN path
```

### Actual behavior
It doesn't.

However, renaming local variable `ne` in the second ANY yields desired outcome. This query works:
```
MATCH path=(src:Test)-[r1:NEXT]->(dst:Test)
WHERE ANY(ne IN src.ne WHERE ne IN ["TIT"]) AND ANY(ne2 IN dst.ne WHERE ne2 IN ["PER"]) 
RETURN path
```

This is not an issue when we leave the MATCH aside - this works just as expected:
```
with [ "x","y","z"] as a, ["a","b","c","x"] as b,
["alpha", "gamma"] as c, ["1","2","3","alpha"] as d
where any(i in a where i in b) AND any(i in c where i in d) 
return count(*)
```

**Comment by mnd999** [comment]
This issue should be fixed by https://github.com/neo4j/neo4j/commit/4d0f6be3d61da00a98852af9035bb80757c55874, it will be available in the next 4.1.x bugfix release. Please feel free to reopen if you're still having problems.
