### ISSUE TITLE
How to build community clusters?

### ISSUE THREAD

**Issue by wangrui0** [neo4j/neo4j#12534]
How to build community clusters？

**Comment by InverseFalcon** [comment]
Hello,

Neo4j clustering (HA and causal clustering) are both enterprise-only features, so this is not available in community edition.

You might want to look into [Neo4j Aura](https://neo4j.com/neo4j-aura/), our db-as-a-service offering, for a fast way to leverage a causal cluster without needing to manage it yourself.
