### ISSUE TITLE
[RBAC] NodeCountFromStore is very slow when user doesn't have admin role

### ISSUE THREAD

**Issue by ikwattro** [neo4j/neo4j#12533]
Given a database named `people` with the following data : 

20 million `:Person` nodes
10 million of them have the `Source1` label
10 million of them have the `Source2` label

And a role having the following permissions on the graph : 

```
CREATE ROLE auditor
GRANT ACCESS ON DATABASE people TO auditor;
GRANT TRAVERSE ON GRAPH people NODES Source1 TO auditor;
GRANT READ {*} ON GRAPH people NODES Source1 TO auditor;
```

If the Neo4j admin would perform the following query : 

```
PROFILE MATCH (n:Person) RETURN count(n)
```

It yields a plan with a NodeCountFromStore as first step and it is very fast ( generally 1ms ), the node count is correct and is 20 millions.

If a user with the role `auditor` would perform the same query, the query plan will be the same but the query will take between 2.5 and 3 seconds to complete, the node count is also correct and is 10 millions.

**Neo4j Version:** 4.0.5
**Operating System:** RHEL 7.5
**API:** Browser, Java Driver

### Expected behavior

Graph Counts should be fast for any user.

### Actual behavior

Graph Counts are very slow for certain users, depending on their permissions.

**Comment by SaschaPeukert** [comment]
Thank you for reporting this. We have published some information about RBAC limitations in our documentation.  This should explain the unfortunate issue: https://neo4j.com/docs/cypher-manual/4.1/administration/security/limitations/#administration-security-limitations-db-operations
