### ISSUE TITLE
[RBAC] user with reader role cannot use `db.stats.retrieve` procedure

### ISSUE THREAD

**Issue by ikwattro** [neo4j/neo4j#12532]
Following the [documentation](https://neo4j.com/docs/operations-manual/current/authentication-authorization/manage-procedure-permissions/#auth-manage-procedure-permissions-configure-procedure-permissions), a user with the role `reader` should be able to access `READ` procedures.

Following the [documentation for built-in procedures](https://neo4j.com/docs/operations-manual/current/reference/procedures/), the `db.stats.retrieve` procedure is `READ` mode procedure.

However, granting a user the role `reader` does not allow him to call that procedure.

**Neo4j Version:** 4.0.4
**Operating System:** Centos
**API:** Browser

### Steps to reproduce

Create user and grant him the role reader : 

```
CREATE USER procuser SET PASSWORD "pass" CHANGE NOT REQUIRED;
GRANT ROLE reader TO procuser;
```

Login as `procuser` and run the following procedure : 

```
CALL db.stats.retrieve('GRAPH COUNTS', {})
```

A permission denied exception is thrown

```
Neo.ClientError.Security.Forbidden
Permission denied.
```

### Expected behavior

A user with the role `reader` should be able to execute all READ built-in procedures.

### Actual behavior

A user with the role `reader` is not able to execute all READ built-in procedures.

**Comment by Lojjs** [comment]
@ikwattro Apart from the concept of procedure modes (READ/WRITE/SCHEMA/DBMS), there is also an `@Admin` annotation which says whether you have to be admin to run a procedure. This concept seems undocumented, at least in those places you linked to. The `db.stats.retrieve` procedure is one of the few procedures with mode READ which must be run by an admin, so the behaviour is expected. But I agree with you that the documentation is not clear enough in this area, so I will make sure it gets improved and report back to you once it is done.

Best regards Louise, Neo4j Cypher team

**Comment by mnd999** [comment]
Closing this issue, feel free to re-open if you have any further issues.

**Comment by ikwattro** [comment]
Thanks @mnd999 for the documentation, just leaving a note that for one customer, this limitation makes the `Neo4j browser` take an average of 2-3 minutes to load and for another customer Bloom is having same issues when both are not used with the default neo4j user.
