### ISSUE TITLE
Fulltext indexes are dropped randomly

### ISSUE THREAD

**Issue by vorpus** [neo4j/neo4j#12537]
- Neo4j version: 3.5 and 4.0
- Operating system: Docker + Ubuntu 18
- API/Driver: Cypher

- **Steps to reproduce**
Create fulltext index, eg
1. `CALL db.index.fulltext.createNodeIndex("personFT",["Person"],["name", "username", "email"])`
1. `:schema` shows index (as expected)
1. Wait some amount of time (I have seen this happen sometimes in minutes, sometimes after a day)

- Expected behavior
1. fulltext index is persisted and can be queried in the future

- Actual behavior
1. `java.lang.IllegalArgumentException: There is no such fulltext schema index`
1. `:schema` does not show show index

**Comment by burqen** [comment]
@vorpus Hello! Thank you for reporting. To investigate this problem further I would need the `debug.log` and `neo4j.log` that covers the relevant time period or if that can't be provided, the full stack trace might give some clues.

**Comment by vorpus** [comment]
Unfortunately this issue was a blocker for me; as a result I had to switch to an alternate db and all of my neo4j vm's are destroyed.

**Comment by burqen** [comment]
I understand. Before closing this issue, do you have time to answer a few questions?
- Cluster or single instance?
- Community or enterprise edition?
- Do you remember what patch release you used?

Thanks again for you help!

**Comment by burqen** [comment]
Closing this issue because of no response.

**Comment by burqen** [comment]
This might be the same issue as: https://github.com/neo4j/neo4j/issues/12609
