### ISSUE TITLE
Neo4j 4.1.0 uses backup-dir as home dir

### ISSUE THREAD

**Issue by mikernorton** [neo4j/neo4j#12542]
I'm testing backup processing, and I'm getting an error on backup that it can't find the certificate files. They exist, and are set in the certificates directory of the neo4j home dir. Neither executing the command from neo4j's home dir or setting dbms.directories.neo4j_home helps. Setting an absolute path for each of the dbms.ssl.policy.*.base_directory does work, but should not be required.

- Neo4j version: 4.1.0
- Operating system: CentOS 8
- API/Driver: neo4j-admin command
- **Steps to reproduce**
Neo4j running in 3-node core cluster, using certificates for the policies.
Configured with default values for dbms.ssl.policy.* parameters, certificates supplied for all policies
Log into random core server
cd /var/lib/neo4j # Neo4j home dir
/usr/bin/neo4j-admin backup --backup-dir=/backup/db --from=${IP}:6362

- Expected behavior
Backup succeeds. Policies are either found from the PWD or the dbms.directories.neo4j_home setting

- Actual behavior
Backup gives error:
Execution of backup failed. Base directory '/backup/db/certificates/cluster' for SSL policy with name 'cluster' does not exist.

If I set the policy.backup_directory for cluster to an absolute path, it complains about the policy for backup. All the policies need an absolute path for backup to work, which also seems bad, since it is only using the backup policy.

**Comment by RagnarW** [comment]
Closing due to unsupported version
