### ISSUE TITLE
"Database unavailable" if start in "read_only" mode after creating full_text index

### ISSUE THREAD

**Issue by Xakim1c** [neo4j/neo4j#12541]
"Database unavailable" if start in "read_only" mode after creating full_text index (CALL db.index.fulltext.createNodeIndex)

read_only=false (it work's)
read_only=true (it doesn't work)

Exception: "Can not write to index statistics store while in read only mode."

Version 4.0 (Community edition)
![Screenshot from 2020-06-29 18-40-00](https://user-images.githubusercontent.com/49779328/86107372-8cc0a780-bae3-11ea-8333-ee37e7682d04.png)

**Comment by Roxling** [comment]
Thank you for reporting this issue! A fix is on its way.
