### ISSUE TITLE
Unable to get a routing table for database 'foo' because this database does not exist

### ISSUE THREAD

**Issue by tomasonjo** [neo4j/neo4j#12545]
To help us understand your issue, please specify important details, primarily:

- Neo4j version: neo4j:4.0.6-enterprise
- Operating system: CentOS Linux 8 (Core)
- API/Driver: cypher-shell

### Steps to reproduce
1. Pull the image: `docker pull neo4j:4.0.6-enterprise`
2. Create a directory on the host that will be a mount for the data: `mkdir neo4j/backup`
3. Copy a database dump to `/home/backup`
4. Create a docker-compose.yml file:
```
version: '3.7'
services:
  neo4j:
    image: neo4j:4.0.6-enterprise
    hostname: neo4j
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/backup:/backup
```
5. Start the database with `docker-compose up`
6. Restore the database with `docker exec -it neo4j bin/neo4j-admin load --from=/backup/test --database=semmeddb-neo4j --force`
7. For some reason, I have to restart the container before it registers the new database with `docker-compose restart`
8. Connect to docker container and run  `.bin/cypher-shell`
9. After the login run the following command: SHOW DATABASE \`semmeddb-neo4j\`; This returns the following results

```
+--------------------------------------------------------------------------------------------------------+
| name             | address          | role         | requestedStatus | currentStatus | error | default |
+--------------------------------------------------------------------------------------------------------+
| "semmeddb-neo4j" | "localhost:7687" | "standalone" | "online"        | "online"      | ""    | FALSE   |
+--------------------------------------------------------------------------------------------------------+
```
10. Now try to use the new database with :use `semmeddb-neo4j`
I get an error stating:

> Unable to get a routing table for database '`semmeddb-neo4j`' because this database does not exist

### Expected behavior
I should be able to use the new database
### Actual behavior
There is an error preventing me from using the new database

### Workaround

I found a work a solution on stackoverflow: https://stackoverflow.com/questions/60372472/neo4j-docker-admin-import-database-not-found
If you set the new database to be the default one in the neo4j.conf file, it then starts working after a restart

`dbms.default_database=semmeddb-neo4j`

**Comment by OliviaYtterbrink** [comment]
I followed your steps to reproduce, but at step 9 I get an empty result.

But following the notes in https://neo4j.com/docs/operations-manual/4.0/tools/dump-load/ which state:
`If the database used to load into doesn’t exist prior to loading, it must be created subsequently using CREATE DATABASE. See Section 6.2.1, “Administrative commands” for more information.`
Executing `CREATE DATABASE semmeddb-neo4j` between 9 and 10, I can now use the database that was imported with no problem.
