### ISSUE TITLE
Null pointer exception on Edge without a data node

### ISSUE THREAD

**Issue by pjljvandelaar** [neo4j/neo4j#12544]
### Version Info

- Neo4j Desktop version: 1.29
- Neo4j version: 4.1.0
- Operating system: Windows 10 (64 bits)
- APOC: 4.1.0.0

### Steps to reproduce
1. Add a new database.
2. Install the APOC plug-in
3. Add to settings
```
dbms.security.procedures.unrestricted=apoc.import.* 
apoc.import.file.enabled=true
```
4. Create File "test.graphml" in directory
`C:\Users\<name>\.Neo4jDesktop\neo4jDatabases\database-<id>\installation-<neo4j-version>\import\`
with content
```
<?xml version="1.0" encoding="utf-8"?>
<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
	<key id="Node.Path" for="node" attr.name="Path" attr.type="string"/>
	<key id="Edge.Path" for="edge" attr.name="Path" attr.type="string"/>
	<graph id="Nexperia" edgedefault="directed">
		<node id="A" labels=":Unit">
			<data key="Path">C:\bright\itecembed\obj\ada\a3_status.ads</data>
		</node>
		<node id="B" labels=":Unit">
			<data key="Path">C:\bright\itecembed\obj\ada\b3_status.ads</data>
		</node>
		<edge source="A" target="B">
			<!-- <data key="Path">C:\bright\itecembed\obj\ada\b3_status.ads</data> -->
		</edge>
	</graph>
</graphml>
```
5. Load file into database with
```
CALL apoc.import.graphml("test.graphml",{batchSize: 10000, readLabels: true, storeNodeIds: false, defaultRelationshipType:"RELATED"}) YIELD file, source, format, nodes, relationships, properties, time
```
### Expected behavior
File to be loaded.
Yed and XmlChecker all agree it is a fine file.

### Actual behavior
Null pointer exception is thrown.
![image](https://user-images.githubusercontent.com/18348654/86584359-13aecd80-bf85-11ea-917d-d150f4db8757.png)

### Notes
adding the node (by removing the comment tags) on line 13, results in the expected behaviour.

**Comment by jennyowen** [comment]
Hi @pjljvandelaar thanks for the bug report! It looks like it's probably an issue with the APOC plugin. 
Could you please copy this issue over to:
https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues
thanks.
