### ISSUE TITLE
JDK(TM) 11 to run Neo4

### ISSUE THREAD

**Issue by xmp00** [neo4j/neo4j#12554]
ERROR! Neo4j cannot be started using java version 1.8.0_212. 
* Please use Oracle(R) Java(TM) 11, OpenJDK(TM) 11 to run Neo4j.
* Please see https://neo4j.com/docs/ for Neo4j installation instructions.
-==
I f*cked all day with this installation from 9 AM till now 7 PM...I don't know what to say because nothing to hell helped me what was found on the web...

**Comment by cuigm85** [comment]
```
ERROR! Neo4j cannot be started using java version 1.8.0_212.
```
I think your jdk version is 8.

```
Please use Oracle(R) Java(TM) 11, OpenJDK(TM) 11 to run Neo4j.
```
You should install jdk 11, if you want to use neo4j v4.

[Software requirements](https://neo4j.com/docs/operations-manual/current/installation/requirements/#deployment-requirements-software)

**Comment by mnd999** [comment]
Yes, that is correct. Neo4j 4.0.0+ requires Java 11. Will close this one, if you have any further questions please re-open.

**Comment by Powersource** [comment]
If any arch user like me ends up here then you probably need to manually switch to a newer java version https://wiki.archlinux.org/index.php/Java#Switching_between_JVM

**Comment by Code4SAFrankie** [comment]
This does not really solve the issue, because I have the required version installed; but I also new the older version for Oracle E-Business Suite

**Comment by ilevd** [comment]
Have the same issue:
```
/etc/neo4j$ java --version
openjdk 11.0.18 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-post-Ubuntu-0ubuntu120.04.1)
OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Ubuntu-0ubuntu120.04.1, mixed mode, sharing)

/etc/neo4j$ neo4j console
ERROR! Neo4j cannot be started using java version 1.8.0_191. 
* Please use Oracle(R) Java(TM) 11, OpenJDK(TM) 11 to run Neo4j.
* Please see https://neo4j.com/docs/ for Neo4j installation instructions.

**Comment by mnd999** [comment]
In the scenario where multiple Java virtual machines are installed Neo4j would respect the `JAVA_HOME` environment variable to determine which one to use. Please note, that as this is a very old issue, for Neo4j 5+ you need Java 17.

**Comment by slythx** [comment]
Add this to your .bash_profile
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk/  

Then run the ff:
source /root/.bash_profile
