### ISSUE TITLE
Websocket connection timeout in browser

### ISSUE THREAD

**Issue by ravening** [neo4j/neo4j#12559]
## Bug report

- Neo4j version: 4.0.4
- Operating system: Ubuntu 16.04

- **Steps to reproduce**
Run a neo4j docker container on a remote machine, lets say with an in 10.11.113.101
```
 docker run -it  --publish=7474:7474 --publish=7687:7687 -e 'NEO4J_AUTH=neo4j/secret' neo4j:4.0.4
```

The docker starts fine and all the firewall ports are open
When I login to browser, it tries to connect a websocket connection to localhost rather than 10.11.113.101 which is definitely not a good thing.

- Expected behavior

Docker starts up fine
I can login to neo4j using "neo4j/secret" credentials but unable to connect to databases.
The browser timeout to create a websocket connection.

![Screenshot 2020-07-25 at 23 14 59](https://user-images.githubusercontent.com/10645273/88466447-ab407580-cecc-11ea-80b8-86a10332d72b.png)

Since I am running the docker in a remote machine **10.11.113.101** and not **localhost**,  the websocket connection should be established to remote machine and not local machine

![Screenshot 2020-07-25 at 23 15 27](https://user-images.githubusercontent.com/10645273/88466456-bb585500-cecc-11ea-97fa-366bf5c705a7.png)

- Actual behavior

The browser should establish WebSocket connection to the remote machine **10.11.113.101** rather than localhost

**Comment by jennyowen** [comment]
If your Neo4j instance is running on another machine, you'll need to configure `dbms.default_advertised_address` to be the address of the machine running neo4j.
https://neo4j.com/docs/operations-manual/current/configuration/connectors/#connectors-defaults-for-addresses

In docker you can configure Neo4j with a conf file or with environment variables:
https://neo4j.com/docs/operations-manual/current/docker/configuration/#docker-environment-variables

So for your example you can do:
```
docker run -it \
--publish=7474:7474 --publish=7687:7687 \
-e NEO4J_AUTH=neo4j/secret \
-e NEO4J_dbms_default__advertised__address=10.11.113.101 \
neo4j:4.0.4
```

and (assuming you have all the necessary ports open and available) neo4j will work.

**Comment by ravening** [comment]
@jennyowen this worked. Thanks a lot :)
