### ISSUE TITLE
Some questions about the code of GrabAllocator.java

### ISSUE THREAD

**Issue by fake0fan** [neo4j/neo4j#12569]
Recently, I read some source code of neo4j and have some questions.
In the file of neo4j/community/io/src/main/java/org/neo4j/io/mem/GrabAllocator.java

```
            if ( head == null || !head.canAllocate( bytes, alignment ) )
            {
                if ( grabSize < bytes )
                {
                    grabSize = bytes;
                    Grab grab = new Grab( head, grabSize, memoryTracker );
                    if ( grab.canAllocate( bytes, alignment ) )
                    {
                        expectedMaxMemory -= grabSize;
                        head = grab;
                        return head.allocate( bytes, alignment );
                    }
                    grab.free();
                    grabSize = maxAllocationSize;
                }
                head = new Grab( head, grabSize, memoryTracker );
                expectedMaxMemory -= grabSize;
            }
           return head.allocate( bytes, alignment );
```

In this segment of code,  I guess it will have some problems if  ```grabSize == bytes```. 
We are not sure that the ```head.canAllocate( bytes, alignment )```  is true, right? 

So, I think this is a bug. and if I'm wrong, hope to get some ideas from your guys.
Thanks so much.

**Comment by PetrJanouch** [comment]
Yes, there was an issue. Actually the problem was not only for grabSize == bytes but for grabSize  in interval [bytes, bytes + maxOffset). [It was fixed by this](https://github.com/neo4j/neo4j/commit/2786487bc350dec6065ea661bb1a5c179b60b9c2) . Too bad you did not make this good observation a couple of days before. I could have saved me a lot of investigation.

**Comment by fake0fan** [comment]
Yes, I know there are many different situations to trigger this issue. I just use the special one to make you realize that is a bug. 

Since I can't see the pull code you mentioned, I didn't know you have fixed it already.

Hope I can help next time!

**Comment by PetrJanouch** [comment]
I have fixed the link
