### ISSUE TITLE
can not build neo4j-3.4

### ISSUE THREAD

**Issue by xspeng95** [neo4j/neo4j#12566]
Neo4j version: 3.4
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 11.0.8, vendor: Oracle Corporation, runtime: /usr/lib/jvm/jdk-1.8
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.0.0-38-generic", arch: "amd64", family: "unix"

I download the zip file and unzip
cd neo4j-3.4 file directory
mvn clean install -DskipTests

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Neo4j 3.4.19-SNAPSHOT:
[INFO] 
[INFO] Neo4j - Build resources ............................ SUCCESS [  0.657 s]
[INFO] Neo4j .............................................. SUCCESS [  1.986 s]
[INFO] Neo4j - Common ..................................... FAILURE [  2.874 s]
[INFO] Neo4j - Resource interface ......................... SKIPPED
[INFO] Neo4j - Collections ................................ SKIPPED
[INFO] Neo4j - Unsafe Access .............................. SKIPPED
[INFO] Neo4j - Primitive Collections ...................... SKIPPED
[INFO] Neo4j - Graph Database API ......................... SKIPPED
[INFO] Neo4j - IO ......................................... SKIPPED
[INFO] Neo4j - Logging .................................... SKIPPED
[INFO] Neo4j - Configuration .............................. SKIPPED
[INFO] Neo4j - Procedure API .............................. SKIPPED
[INFO] Neo4j - Value ...................................... SKIPPED
[INFO] Neo4j - Kernel API ................................. SKIPPED
[INFO] Neo4j - CSV reading and parsing .................... SKIPPED
[INFO] Neo4j - Lucene Index Upgrade ....................... SKIPPED
[INFO] Neo4j - Native index ............................... SKIPPED
[INFO] Neo4j - Native Spatial Index ....................... SKIPPED
[INFO] Neo4j - SSL ........................................ SKIPPED
[INFO] Neo4j - Graph Database Kernel ...................... SKIPPED
[INFO] Neo4j - Command Line ............................... SKIPPED
[INFO] Neo4j - Lucene Index ............................... SKIPPED
[INFO] Neo4j - Import Command Line Tool ................... SKIPPED
[INFO] Neo4j - JMX support ................................ SKIPPED
[INFO] Neo4j - Database Management System ................. SKIPPED
[INFO] Neo4j - Graph Algorithms ........................... SKIPPED
[INFO] Neo4j - Code Generator ............................. SKIPPED
[INFO] Neo4j - Community Cypher Build ..................... SKIPPED
[INFO] Neo4j - Cypher Util 3.4 ............................ SKIPPED
[INFO] Neo4j - Cypher Expressions 3.4 ..................... SKIPPED
[INFO] openCypher Frontend ................................ SKIPPED
[INFO] Neo4j - Cypher Intermediate Representation 3.4 ..... SKIPPED
[INFO] Neo4j - Cypher Logical Plans 3.4 ................... SKIPPED
[INFO] Neo4j - Cypher Planner SPI 3.4 ..................... SKIPPED
[INFO] Neo4j - Cypher Planner 3.4 ......................... SKIPPED
[INFO] Neo4j - Cypher Runtime Utilities ................... SKIPPED
[INFO] Neo4j - Cypher Interpreted Runtime ................. SKIPPED
[INFO] Neo4j - Cypher ..................................... SKIPPED
[INFO] Neo4j - Security ................................... SKIPPED
[INFO] SLF4J Neo4j Binding ................................ SKIPPED
[INFO] Neo4j - Usage Data Collection ...................... SKIPPED
[INFO] Neo4j - Consistency Checker ........................ SKIPPED
[INFO] Neo4j - Community .................................. SKIPPED
[INFO] Neo4j - Bolt Protocol Version 1 .................... SKIPPED
[INFO] Neo4j - Community .................................. SKIPPED
[INFO] Neo4j - Generic shell .............................. SKIPPED
[INFO] Neo4j - Server API ................................. SKIPPED
[INFO] Neo4j - Server ..................................... SKIPPED
[INFO] Neo4j - Server Plugin Tests ........................ SKIPPED
[INFO] Neo4j - Test Harness ............................... SKIPPED
[INFO] Neo4j - Procedure Compiler Core .................... SKIPPED
[INFO] Neo4j - Procedure Compiler Parent POM .............. SKIPPED
[INFO] Neo4j - Procedure Compiler Integration Tests ....... SKIPPED
[INFO] Neo4j - Push To Cloud - Admin command .............. SKIPPED
[INFO] Neo4j - Community Build ............................ SKIPPED
[INFO] Neo4j - Enterprise Graph Database Kernel Features .. SKIPPED
[INFO] Neo4j - Enterprise Graph Database Auth Plugin API .. SKIPPED
[INFO] Neo4j - Enterprise Graph Database Security Features  SKIPPED
[INFO] Neo4j - Query Logging .............................. SKIPPED
[INFO] Neo4j - Communication Package ...................... SKIPPED
[INFO] Neo4j - Clustering Infrastructure .................. SKIPPED
[INFO] Neo4j - Graph DB Monitoring and Management tools ... SKIPPED
[INFO] Neo4j - Causal Clustering .......................... SKIPPED
[INFO] Neo4j - Backup Tool ................................ SKIPPED
[INFO] Neo4j - High Availability .......................... SKIPPED
[INFO] Neo4j - Metrics Kernel Extension ................... SKIPPED
[INFO] Neo4j - Enterprise ................................. SKIPPED
[INFO] Neo4j - Enterprise Cypher Build .................... SKIPPED
[INFO] Neo4j Cypher Physical Planning ..................... SKIPPED
[INFO] Neo4j Cypher Slotted Runtime ....................... SKIPPED
[INFO] Neo4j Cypher Morsel Runtime ........................ SKIPPED
[INFO] Neo4j Enterprise Cypher ............................ SKIPPED
[INFO] Neo4j - Enterprise Server .......................... SKIPPED
[INFO] Neo4j - Enterprise Test Harness .................... SKIPPED
[INFO] Neo4j - Deferred Locks ............................. SKIPPED
[INFO] Neo4j - Procedure Compiler Enterprise tests ........ SKIPPED
[INFO] Neo4j - Cypher Specification Suite Tools ........... SKIPPED
[INFO] Neo4j - Cypher Acceptance .......................... SKIPPED
[INFO] Neo4j - Cypher Compatibility Specification Suite ... SKIPPED
[INFO] Neo4j - Enterprise Build ........................... SKIPPED
[INFO] Neo4j - Integration Tests .......................... SKIPPED
[INFO] Neo4j - Stress Tests ............................... SKIPPED
[INFO] Neo4j - Low Level Tools ............................ SKIPPED
[INFO] Neo4j - Server Assembler ........................... SKIPPED
[INFO] Neo4j Community - Server Assembler ................. SKIPPED
[INFO] Neo4j Packaging Build .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.088 s
[INFO] Finished at: 2020-08-13T11:26:28+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.0:javadoc-no-fork (generate-javadocs) on project neo4j-common: An error has occurred in Javadoc report generation: 
[ERROR] Exit code: 2 - javadoc: error - No source files for package org.neo4j.backup

**Comment by mnd999** [comment]
Thanks for your interest. We're not really supporting the 3.4 branch anymore, but of course community contributions are welcome.  I would suggest making sure your JAVA_HOME environment variable is correctly set and make sure you don't have any empty source directories left over after switching branches. I would also recommend using a more recent branch if possible.

**Comment by mnd999** [comment]
Closing this one as we haven't heard back. Fee free to re-open if it's still an issue.
