### ISSUE TITLE
Expected a string value for `toUpper`, but got: NO_VALUE; consider converting it to a string with toString()

### ISSUE THREAD

**Issue by alexlitvinenko** [neo4j/neo4j#12571]
It seems that when use  `toUpper(null)` in `WHERE` with `IN` operator then it fails.

See examples below:
`MATCH (p:Plant) WHERE toUpper(p.does_not_exist) IN ['US'] RETURN count(p)` - Neo.ClientError.Statement.TypeError
`MATCH (p:Plant) WHERE toUpper(p.does_not_exist) = 'US' RETURN count(p)` - WORKS!

**Neo4j Version:** 4.0.7 Enterprise
Operating system:  Docker neo4j:4.0.7-enterprise
apoc.version() == "4.0.0.17"

**Comment by pontusmelke** [comment]
Hi,
thanks for reporting the issue. We have fixed the issue and it will be in the next release, probably 4.0.9. As a temporary workaround you can use `CYPHER runtime=slotted...` prepended to your query.

I am closing this issue, should the problem persist (after the release of 4.0.9) or reappear please reopen this issue or open a new one.

Regards,
Pontus
