### ISSUE TITLE
Neo4j cluster member launch may get confused in the order of lauching databases

### ISSUE THREAD

**Issue by JnMik** [neo4j/neo4j#12572]
- Neo4j version: 4.1.1-enterprise
- Operating system: neo4j in containers
- Cluster of 3 core members, using the helm chart

### Steps to reproduce
1. Have more than 1 custom DB in your cluster [neo4j, system, db1, db2, db3....]
2. Have all the nodes shutdown
3. Boot the 3 containers at the same time (could happen with bare metal server, I don't know)
4. Inspect the logs of the 3 containers
5. realize that the boot is stuck because the containers are not trying to initialize the same database

container 0 : 
```
Database 'system' is waiting for a total of 3 core members...
Database 'neo4j' is waiting for a total of 3 core members...
Database 'db1' is waiting for a total of 3 core members...
Database 'db1' is waiting for a total of 3 core members...
Database 'db1' is waiting for a total of 3 core members...
```
container 1 : 
```
Database 'system' is waiting for a total of 3 core members...
Database 'neo4j' is waiting for a total of 3 core members...
Database 'db2' is waiting for a total of 3 core members...
Database 'db2' is waiting for a total of 3 core members...
Database 'db2' is waiting for a total of 3 core members...
```
container 2 : 
```
Database 'system' is waiting for a total of 3 core members...
Database 'neo4j' is waiting for a total of 3 core members...
Database 'db1' is waiting for a total of 3 core members...
Database 'db1' is waiting for a total of 3 core members...
Database 'db1' is waiting for a total of 3 core members...
```
### Expected behavior
I expect the database nodes to launch the database in all the same order so they are able to reach the 3 core members necessary for the boot and continue past this step

### Actual behavior
Database nodes launch "system" and "neo4j" databases in the proper order, but when launching custom database the seem to be able to mess up with the order, therefore messing with the cluster initialization. You can see in my example that the container 1 is trying to launch db2 instead of db1 like the 2 other containers.

This happened to me with neo4j:4.1.1-enterprise, at least 3 times this week. (I'm playing with the cluster a lot, upgrading instance type, changing I/Os and disk type and stuff like that..)

Hope this help ! :)
Thanks

**Comment by timurgen** [comment]
@JnMik  Hi, did you find a solution for this problem?

**Comment by BugGambit** [comment]
@JnMik Same here

**Comment by bbenzikry** [comment]
Encountered this as well while upgrading to 4.2.2

**Comment by org-ci-cd** [comment]
I don't have a solution no, still happening on 4.1.11. 
I don't think we'll have an answer since 4.1 is out of life.

I'll revive the thread if I see the issue with 4.4.10 and above

**Comment by RagnarW** [comment]
Closing due to unsupported version
