### ISSUE TITLE
Out of Memory - Java heap Space

### ISSUE THREAD

**Issue by kethan6028** [neo4j/neo4j#12577]
Neo4j version - 3.5.14
````
env:
        - name: “NEO4J_AUTH”
          value: “neo4j/aic”
        - name: NEO4J_dbms_memory_heap_initial__size
          value: 8000m
        - name: NEO4J_dbms_memory_heap_max__size
          value: 8000m
        - name: NEO4J_dbms_memory_pagecache_size
          value: 4000m
resources:
          requests:
            memory: “4Gi”
            cpu: “1"
          limits:
            memory: “13Gi”
            cpu: “2"
````
````
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "neo4j.Scheduler-1"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "qtp1161209621-280"
Exception in thread "Connector-Scheduler-c732e1c" Exception in thread "neo4j.VmPauseMonitor-1" java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
2020-08-30 02:24:58.630+0000 WARN  /db/data/transaction/commit Java heap space
java.lang.OutOfMemoryError: Java heap space
````
I have 112899 nodes and 5513742 relationships.When I run some queries over this data then neo4j throws above exception(this is not very often..only in some occasions) and there are some folders getting created with pattern neostore.transaction.db.* 

![image (4)](https://user-images.githubusercontent.com/47622869/92080234-d331cb80-edde-11ea-9aef-6e2afa4518d1.png)
Any quick help on this will be much appreciated..Thanks in advance

**Comment by sherfert** [comment]
@kethan6028 Have you tried increasing the available heap space as described here: https://neo4j.com/developer/guide-performance-tuning/

If you did, and it still fails, there is not so much you can do about that in 3.5.
Starting in 4.0 and 4.1 there are more fine grained controls of how much memory may be consumed by the database and better error handling. Have a look here: https://neo4j.com/developer/memory-management/#restrict-memory-usage

If that sounds like it could help, I'd suggest upgrading.

**Comment by mnd999** [comment]
As we haven't heard anything back on this issue for a while I will close it for now. Feel free to reopen if it's still an issue.
