### ISSUE TITLE
 Neo4j can only import 6.5w type relationships ？

### ISSUE THREAD

**Issue by hyybuaa** [neo4j/neo4j#12576]
Neo4j can only import 6.5w type relationships ？

**Comment by mnd999** [comment]
Thanks for opening the ticket. I'm not sure I fully understand the issue from your question. Can you provide more detail and / or an example of the issue you are facing and we will try to look into it.

**Comment by mnd999** [comment]
We haven't heard anything back so I will close this for now. If it's still an issue, please feel free to reopen the ticket.
