### ISSUE TITLE
Neo4j Harness - missing APOC Core libraries

### ISSUE THREAD

**Issue by pelletier197** [neo4j/neo4j#12575]
Hello!

I'm reaching out to you, because I encountered an issue while using `neo4j-harness 4.1.1`. If I understand well from the Readme of `APOC`, from this version, Neo4j comes bundled with [APOC Core Procedures](https://github.com/neo4j-contrib/neo4j-apoc-procedures). 

However, Neo4j Harness seems to be lacking those core dependencies. Before this version of Neo4j, I used to register the required apoc dependencies manually, but since the latest APOC version, because they are supposed to be included in Neo4j, APOC  did not put the core dependencies inside the [Maven library](https://mvnrepository.com/artifact/org.neo4j.procedure/apoc/4.1.0.2) .

So now, both `Neo4j-harness` and `apoc` libraries are lacking those `core` functions, and I can't use any APOC function/procedures in my IT :cry: .

Is there a fix for this that is suppose to come soon ?

Thank you for your support!

**Comment by jexp** [comment]
Sorry for the confusion, "bundling" here means that APOC-core of an appropriate, fitting version will be bundled in the binary distribution in a separate "labs" directory. That's it.

No binary dependency or maven dependency in/from Neo4j.
Sorry if that was not communicated clearly.

**Comment by jexp** [comment]
You can add an apoc dependency manually to your maven setup and use those then within your tests. 

We will document that in apoc for now please consult the links attached to this issue

https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1656

**Comment by pelletier197** [comment]
Thank you for your answer. For now, I added the Jar manually to the projet, which does really please me, since having binaries in a git repository tend to make the repository heavier for no reason.

Is there really no way to use apoc core as a maven/gradle dependency and load the procedures manually? That's what I used to do and it worked well.

**Comment by pelletier197** [comment]
Since I haven't had any help on this, I found a way to add the `apoc-core` dependencies as a JAR downloaded from the release repository of APOC.

Using this in my `build.gradle` (thanks to [this](https://stackoverflow.com/questions/23446233/compile-jar-from-url-in-gradle))
```groovy
ext.urlFile = { String url, String name ->
    File file = new File("$buildDir/download/${name}.jar")
    file.parentFile.mkdirs()
    if (!file.exists()) {
        new URL(url).withInputStream { downloadStream ->
            file.withOutputStream { fileOut ->
                fileOut << downloadStream
            }
        }
    }
    files(file.absolutePath)
}
```
and added this dependency

```groovy
    testImplementation "org.neo4j.test:neo4j-harness:4.1.1"
    testImplementation urlFile("https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/4.1.0.2/apoc-4.1.0.2-core.jar", "apoc-core")
```

Finally, I used this to register my apoc functions manually
```kotlin
            val builder = Neo4jBuilders
                .newInProcessBuilder()
                .withDisabledServer()
                .withFunction(Create::class.java)
                .withFunction(Coll::class.java)
                .withProcedure(Cypher::class.java)
                .withAggregationFunction(MaxAndMinItems::class.java)
                .withAggregationFunction(CollAggregation::class.java)
                .build()
```

**Comment by michael-simons** [comment]
Hey @pelletier197 The scanning mechanism that automatically loads all the procedures does not work in an embedded scenario (which is basically what running the test harness is). 

Here's one way to solve this:

```java
private static Neo4j neo4j;

	@BeforeAll
	static void startEmbeddedNeo4j() throws URISyntaxException {

		// We need the directory containing the APOC jar, otherwise all APOC procedures must be loaded manually.
		// While the intuitive idea might be not having APOC on the class path at all in that case and just dump
		// it into the plugin directory, it doesn't work as APOC needs some extension factories to work with
		// and those are not loaded from the plugin unless it's part of the original class loader that loaded neo.
		// If you know which methods you're a gonna use, you can configure them manually instead.
		var pluginDirContainingApocJar = new File(
			ApocConfig.class.getProtectionDomain().getCodeSource().getLocation().toURI())
			.getParentFile().toPath();
		neo4j = Neo4jBuilders
			.newInProcessBuilder()
			.withDisabledServer() // We don't need the HTTP endpoint
			.withFixture("CREATE (m:Movie {title: 'Fight Club'}) RETURN m")
			.withConfig(GraphDatabaseSettings.plugin_dir, pluginDirContainingApocJar)
			.withConfig(GraphDatabaseSettings.procedure_unrestricted, List.of("apoc.*"))
			.build();

	}
```

From https://github.com/michael-simons/neo4j-sdn-ogm-tips/blob/master/examples/testing-ogm-against-embedded-with-apoc/src/test/java/org/neo4j/tips/testing/testing_ogm_against_embedded_with_apoc/ApplicationTests.java#L51-L69

It basically has the apoc dependency on the class path as you have but also points the plugin dir of the embedded server to the directory containing the jar file.

**Comment by a-pagano** [comment]
> Since I haven't had any help on this, I found a way to add the `apoc-core` dependencies as a JAR downloaded from the release repository of APOC.
> 
> Using this in my `build.gradle` (thanks to [this](https://stackoverflow.com/questions/23446233/compile-jar-from-url-in-gradle))
> 
> ```groovy
> ext.urlFile = { String url, String name ->
>     File file = new File("$buildDir/download/${name}.jar")
>     file.parentFile.mkdirs()
>     if (!file.exists()) {
>         new URL(url).withInputStream { downloadStream ->
>             file.withOutputStream { fileOut ->
>                 fileOut << downloadStream
>             }
>         }
>     }
>     files(file.absolutePath)
> }
> ```
> 
> and added this dependency
> 
> ```groovy
>     testImplementation "org.neo4j.test:neo4j-harness:4.1.1"
>     testImplementation urlFile("https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/4.1.0.2/apoc-4.1.0.2-core.jar", "apoc-core")
> ```
> 
> Finally, I used this to register my apoc functions manually
> 
> ```kotlin
>             val builder = Neo4jBuilders
>                 .newInProcessBuilder()
>                 .withDisabledServer()
>                 .withFunction(Create::class.java)
>                 .withFunction(Coll::class.java)
>                 .withProcedure(Cypher::class.java)
>                 .withAggregationFunction(MaxAndMinItems::class.java)
>                 .withAggregationFunction(CollAggregation::class.java)
>                 .build()
> ```

We've hit the same issue with version `4.1.3` of the test harness (and version `4.1.0.2` of the apoc library). Specifying a dependency on the `org.neo4j.procedure:apoc` lib did not work. After trying multiple approaches, including the jar from the release page of the apoc repo as a direct dependency is the only thing that worked, so thanks a lot!

In case it could be helpful for someone, here is how you can include the apoc jar file in a directory as a dependency in your `build.gradle` (without downloading it at every build): 

```
// put the apoc jar (apoc-4.1.0.2-all.jar) downloaded from the release page of https://github.com/neo4j-contrib/neo4j-apoc-procedures in src/testing-common/resources/neo4j/plugins 
repositories {
    flatDir {
        dirs 'src/testing-common/resources/neo4j/plugins'
    }
}
...
testImplementation name: 'apoc-4.1.0.2-all'
```

**Comment by pelletier197** [comment]
@michael-simons Hello! I'm struggling a little with your solution. If i try to use apoc `4.1.0.4` with the following dependency
```
testImplementation urlFile("https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/4.1.0.4/apoc-4.1.0.4-all.jar", "apoc-all")
```
and your example to setup the plugin directory 
```kotlin
fun init(builder: Neo4jBuilder) {
    TenantContext.setCurrentTenant(TENANT_NAME)
    val pluginDirContainingApocJar = File(
        ApocConfig::class.java.protectionDomain.codeSource.location.toURI()
    ).parentFile.toPath()

    neo4j = builder
        .withDisabledServer()
        .withConfig(ApocSettings.apoc_uuid_enabled, true)
        .withConfig(GraphDatabaseSettings.procedure_unrestricted, listOf("apoc.*"))
        .withConfig(GraphDatabaseSettings.plugin_dir, pluginDirContainingApocJar)
        .build()
}
```

I get the following 
```
Unable to register procedure, because the name `apoc.text.doubleMetaphone` is already in use.
```

Any idea what this might be ?

I am trying to use the `apoc.uuid.install` prodedure defined [here](https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/4.1/full/src/main/java/apoc/uuid/Uuid.java)

**Comment by rfreydi** [comment]
Is it normal that in version `4.2.0.0+` of APOC  the file `apoc/ApocConfig` has been moved into `apoc/config/Config` ?
As I try to implement your solution, it still throw me an Error about not finding the file...

![image](https://user-images.githubusercontent.com/21192766/112457689-4b041b00-8d5c-11eb-8a31-4956fca42bf4.png)

And if in my code I try to use `apoc/ApocConfig` it just show me an Error as it doesn't find the class.

**Comment by abbas-gadhia** [comment]
I get this exception when i use neo4j 4.2.3 with apoc 4.2.0.2

```
Caused by: java.lang.RuntimeException: Error starting Neo4j database server at /tmp/5813ce242581730a6697d0306632f327/data/databases
        at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:207)
        at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:163)
        at org.neo4j.harness.internal.InProcessNeo4jBuilder.createNeo(InProcessNeo4jBuilder.java:50)
        at org.neo4j.harness.internal.AbstractInProcessNeo4jBuilder.build(AbstractInProcessNeo4jBuilder.java:166)
        at org.neo4j.harness.internal.AbstractInProcessNeo4jBuilder.build(AbstractInProcessNeo4jBuilder.java:72)
        at org.neo4j.harness.Neo4jBuilder$build.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
        at com.datametica.flamingo.FlamingoTestConfig.<clinit>(FlamingoTestConfig.groovy:56)
        ... 85 common frames omitted
    Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.extension.GlobalExtensions@50575332' failed to initialize. Please see the attached cause exception "apoc.ApocConfig".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:424)
        at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:65)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:101)
        at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:198)
        ... 94 common frames omitted
    Caused by: org.neo4j.kernel.extension.FailedToBuildExtensionException: Failed to build kernel extension Extension:JdbcRegistererInitFactory[JdbcDriverRegisterer] because it is compiled with a reference to a class, method, or field, that is not in the class path: 'apoc/ApocConfig'. The most common cause of this problem, is that Neo4j has been upgraded without also upgrading allinstalled extensions, such as APOC. Make sure that all of your extensions are build against your specific version of Neo4j.
        at org.neo4j.kernel.extension.ExtensionFailureStrategies.wrap(ExtensionFailureStrategies.java:60)
        at org.neo4j.kernel.extension.ExtensionFailureStrategies$1.handle(ExtensionFailureStrategies.java:76)
        at org.neo4j.kernel.extension.AbstractExtensions.init(AbstractExtensions.java:72)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:403)
        ... 97 common frames omitted
    Caused by: java.lang.NoClassDefFoundError: apoc/ApocConfig
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
        at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3191)
        at java.base/java.lang.Class.getMethods(Class.java:1904)
        at java.base/java.lang.reflect.Proxy$ProxyBuilder.referencedTypes(Proxy.java:712)
        at java.base/java.lang.reflect.Proxy$ProxyBuilder.<init>(Proxy.java:624)
        at java.base/java.lang.reflect.Proxy$ProxyBuilder.<init>(Proxy.java:635)
        at java.base/java.lang.reflect.Proxy.lambda$getProxyConstructor$0(Proxy.java:415)
        at java.base/jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329)
        at java.base/jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205)
        at java.base/java.lang.reflect.Proxy.getProxyConstructor(Proxy.java:413)
        at java.base/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1006)
        at org.neo4j.kernel.impl.util.DependenciesProxy.dependencies(DependenciesProxy.java:56)
        at org.neo4j.kernel.extension.AbstractExtensions.getExtensionDependencies(AbstractExtensions.java:124)
        at org.neo4j.kernel.extension.AbstractExtensions.init(AbstractExtensions.java:61)
        ... 98 common frames omitted
    Caused by: java.lang.ClassNotFoundException: apoc.ApocConfig
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 113 common frames omitted

```

**Comment by abbas-gadhia** [comment]
Here's how i got it to work

```
  private static Neo4j neo4j

  static {
    log.info("Initializing embedded neo4j and registering procedures and functions")

    Neo4jConfigurator configurator = Neo4jBuilders.newInProcessBuilder().withDisabledServer()
    registerProcedure(configurator, LoadCsv, Periodic)
    neo4j = configurator.build()
  }

  private static void registerProcedure(Neo4jConfigurator configurator, Class<?>... procedures) {
    procedures.each {
      configurator.withProcedure(it)
    }
  }
```
This is a section of my build.gradle.

```
  testImplementation "org.neo4j.procedure:apoc:$neo4j_apoc_version:all"
  testImplementation('org.springframework.boot:spring-boot-starter-test')
  testImplementation(group: 'org.junit.vintage', name: 'junit-vintage-engine') {
    because('Spock needs junit 4 so we are including vintage')
    exclude group : 'org.hamcrest', module: 'hamcrest-core'
  }
  testImplementation("org.spockframework:spock-core:$spockVersion")
  testImplementation("org.spockframework:spock-spring:$spockSpringVersion")

  testImplementation(group: 'org.neo4j.test', name: 'neo4j-harness', version: "$neo4j_Version") {
    exclude(group: 'org.slf4j', module: 'slf4j-nop')
  }
```

```
gradle.properties

neo4j_Version=4.2.3
neo4j_apoc_version=4.2.0.2
```

**Comment by pelletier197** [comment]
@abbas-gadhia 's solution worked. The important part is 

```
org.neo4j.procedure:apoc:$neo4j_apoc_version:all"
```

With the classifier "all"

More details can be found on [this issue](https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1825). 

And I'll be closing this, since there is [an issue](https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1656#issuecomment-770720804) that aims to add better documentation. 

Thank you all!

**Comment by albertolovato** [comment]
I tried to do the same for GDS, in particular I'm interested in calling PageRank in test harness, but it doesn't seem to work

```
	Path pluginDirContainingGDSJar = new File(
		PageRankAlgorithm.class.getProtectionDomain().getCodeSource().getLocation().toURI())
		.getParentFile().toPath();
...		
	embeddedDatabaseServer = Neo4jBuilders.newInProcessBuilder().withDisabledServer()
			.withConfig(GraphDatabaseSettings.plugin_dir, pluginDirContainingGDSJar )
			.withConfig(GraphDatabaseSettings.procedure_unrestricted, List.of("gds.*") )
			.withConfig(GraphDatabaseSettings.procedure_allowlist, List.of("gds.*") )
...
```

When I try to call the function I get an Exception:
```
	try (Session session = driver.session()) {
		Result result = session.run(
			"CALL gds.pageRank.stream({\r\n"
...
```

```
org.neo4j.driver.exceptions.ClientException: There is no procedure with the name `gds.pageRank.stream` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.
	at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:143)
...
```

Am I missing something?

Thank you

**Comment by pelletier197** [comment]
I have never used the plugin_dir configuration personally, so I wouldn't know, but your code seems to be good for what you wish to do.

You can maybe try to add the jar with your procedure to your classpath and import only the procedures you need manually if plugin_dir gives no success.

I have personally stopped using Harness because I was facing too many issues with the plug-ins. I went with a TestContainer approach instead, which is easily configurable with environment variables.

**Comment by albertolovato** [comment]
I've added all of the GDS jars in pom.xml, but I too am having troubles with harness, so I'll check out TestContainer.

Thank you very much!
