### ISSUE TITLE
Unsuccesful loading of Reactome database to Neo4j

### ISSUE THREAD

**Issue by ondravaculik** [neo4j/neo4j#12580]
I'm trying to load Reactome database into my Neo4j Desktop. 

I downloaded the latest version of the database from Reactome website (https://reactome.org/dev/graph-database#GetStarted), version of my Neo4j Desktop is 1.3.4 and for the created database I'm using Neo4j 4.1.1 (tried 4.1.0 as well).

Afterwards, I extracted the tar.gz file and used the terminal in Neo4j Desktop to restore the data in my database with the following command:

    bin/neo4j-admin restore --from=/PATH/reactome.graphdb/graph.db --database=graph.db

And pressed Start button. Start was successful, so I opened it in Neo4J Browser - here it came with notification:
> Database 'neo4j' is unavailable. Run  :sysinfo for more info.

I checked the debug.log: the problem should be in disabled upgrade option in neo4j.conf file
[debug.log - screenshot][1]

So I uncommented the option to:
`dbms.allow_upgrade=true`

But when I tried to run the dataset with Start button I got only the notification:
> Database failed to start: DB [database-e25f8ba8-dea1-4e70-8944-024f73a2eeaf] 'v4.1.1' exited with status 'KILLED'. Check the logs

After checking the logs I found this:
[neo4j.log - printscreen][2]

I'm truly stacked now. Does anyone have any idea how to deal with this issue?
Thanks a lot!

  [1]: https://i.stack.imgur.com/13PsX.png
  [2]: https://i.stack.imgur.com/Fuph9.jpg

**Comment by mnd999** [comment]
Sorry to hear you're having difficulties. Could you attach the full debug.log and neo4j.log so we can see more of what is going on. I notice that backup is in Neo4j 3.4 format so it will require to go through the upgrade to start on 4.1.x.

**Comment by ondravaculik** [comment]
Hi, thanks for your reply. Here are the log files. 
[debug.log](https://github.com/neo4j/neo4j/files/5188750/debug.log)
[neo4j.log](https://github.com/neo4j/neo4j/files/5188751/neo4j.log)

I haven't notice that backup is in a different format, can I upgrade it manually somehow in the Neo4j Desktop?

**Comment by mnd999** [comment]
The upgrade happens automatically when the database comes up, provided `dbms.allow_upgrade=true` is set. Looking at the attached log files, the migration appears to have just started where they cut off.

**Comment by ondravaculik** [comment]
Yes, the problem is that I'm not even able to start the database with the `dbms.allow_upgrade=true`, it's killed immediately. 

Any idea what can I try to deal with it?

**Comment by PetrJanouch** [comment]
The crash you experienced on start up was caused by a bug fixed in 4.1.2. Could you re-test with that version?

**Comment by ondravaculik** [comment]
Everything seems working with the latest version. Thanks!
