### ISSUE TITLE
First CSV column not accessible if using apoc.load.csv  

### ISSUE THREAD

**Issue by gabrielmateitoma** [neo4j/neo4j#12587]
The generic problem: give a csv with columns a,b,c,..., when using apoc.load.csv , the yielded map does display it's content of 
map:{
"a":"value a",
"b":"value b",
"c":"value c"
}
but when trying to access the value of "a"  directly (map['a']), it always returns null

The issue has been confirmed by multiple people: https://community.neo4j.com/t/cannot-access-map-item-from-apoc-load-csv/25576

Whereas in the yielded map the first column is visible as part of the map attribute, accessing it always returns null.

This being the content of my "taxonomy.CSV" file:

Level1,Level2,Tree Path,Id,Code,Description,Long Description,Context,Type,Active,Code Valid from,Node Valid from,Node Valid to
1,1,(Root Code),31102727,Zone,Zone,,TEST,Taxonomy,A,31/01/2020,,
2,2,31085110,31085110,CAI,Asia,,TEST,Zone,A,4/8/2017,,
by running
CALL apoc.load.csv('taxonomy.csv') yield map return map,map['Id'],map['Tree Path'],map['Level1'],map['Level2'] limit 5

I cannot access the values on the first column - they are always null.
I've tried renaming the column -> same (=null).
I've duplicated the column, initially called "Level" and new it's Level1 and Level2 and Level2 can be access, but Level1 is always null

Result (removed some content from map to make used fields more visible):

map
{
  "Tree Path": "(Root Code)",
  "Level2": "1",
  "Level1": "1",
  "Id": "31102727"
}
map['Id']	map['Tree Path']	map['Level1']	map['Level2']

"31102727"	"(Root Code)"	null	"1"

**Comment by mnd999** [comment]
Thanks for the report, as this issue is with an apoc procedure, it should be raised in https://github.com/neo4j-contrib/neo4j-apoc-procedures. Unfortunately, I cannot transfer it as apoc has a different owner.

**Comment by gabrielmateitoma** [comment]
Thanks for feedback, Mark
I've opened a duplicate there, https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1674

Regards,
Gabriel
