### ISSUE TITLE
poor write performance  Neo4j 4.1.0

### ISSUE THREAD

**Issue by tklebanoff** [neo4j/neo4j#12598]
Hello everybody, I am having some performance problems writing data to the neo4j database.

LOAD CSV queries take far longer than I expect (sometimes a few minutes for a batch of 1000, with less than 10,000 existing nodes in the database at the point of the batch write).

With a blank database, the first batch query of about 1000 entries takes over 12 seconds.
As I periodically add batches (each of around the same size), the write time begins to skyrocket.
I was expecting a 1000 line CSV write to be consistently less than one second.
Based on what I have read online, neo4j seems to be able to handle this performance criteria for other users.
I am wondering if perhaps there is a problem in my query, on my machine, or in my database configuration.

I have tried the below query both with and without USING PERIODIC COMMIT 100, as well as with several values at different orders of magnitude for the COMMIT batch size parameter (100, 1000, 5000)

My requirement is that I cannot rebuild the database from scratch to load in new data batches.
The data comes in live, and writing a single entry per transaction is far too slow for this dataset (not to mention burns unnecessary CPU which I need for other ongoing tasks).

Over the lifecycle of the database, I would like to be able to write about 10,000 batches. each containing about 1000 entries.
Each batch entry is about 100 ascii characters long and contains enough information for two nodes and one relationship.

Neo4j 4.1.0
Mac OSX 10.15.6
Cypher API

* steps to reproduce *
1) fresh database with my database config, apoc and graph-data-science both installed
LOOP:
2) run the following query, using the parameter $batchfile to designate a batch of 1000-2000 items
3) perhaps leave out the USING PERIODIC COMMIT line (or tweak its parameter from 100 to some other value)
4) observe the time for the transaction to complete.  I observe roughly 12 seconds for the first one
5) goto LOOP with a new batchfile (same format, new data, roughly same number of entries as before)

6) observe the time taken for each transaction and notice that is increases from 12 to nearly 200 seconds in the end.  From upstream, sometimes the batches can be larger than 1000, perhaps up to 4 or 5000.  I hope to eventually be able to write batches of 10,000 entries per txn.

    USING PERIODIC COMMIT 100
    LOAD CSV WITH HEADERS FROM $batchfile_name AS row
    MERGE (src:Page { pageid: row.src_pageid } )
    MERGE (dst:Page { pageid: row.dst_pageid } )
    SET
    src.length = toInteger(row.src_length),
    src.title  = row.src_title,
    src.url    = row.src_url,
    dst.length = toInteger(row.dst_length),
    dst.title  = row.dst_title,
    dst.url    = row.dst_url
    MERGE (src)-[:LINKS_TO]->(dst)

*expected behavior* 
near linear batch write time with the size of the batch
near constant batch write time with the current number of nodes in the database

Perhaps this expectation is too strict in some way.  Maybe the matches in my query are preventing me from getting the performance I want.  In this case, is there another way to do what I am trying to do?  In each batch entry, I want to create or update a source and dest node, as well as link them together.  I don't know if the source or dest already exists at the time of the write (thus, I use match). If it already exists, I simply want to update the node parameters to reflect the most up to date value.

*actual behavior*
as the database grows, the time to complete each batch skyrockets to the point of infeasible .

*my config*
dbms.security.auth_enabled=true
dbms.backup.enabled=false
dbms.memory.heap.initial_size=512m
dbms.memory.heap.max_size=8G
dbms.memory.pagecache.size=4G
dbms.tx_state.memory_allocation=ON_HEAP
dbms.connector.bolt.enabled=true
dbms.connector.http.enabled=true
dbms.connector.https.enabled=false
dbms.threads.worker_count=12
dbms.security.allow_csv_import_from_file_urls=true
dbms.security.procedures.unrestricted=,jwt.security.*,apoc.*,gds.*
dbms.jvm.additional=-XX:+UseG1GC
dbms.jvm.additional=-XX:-OmitStackTraceInFastThrow
dbms.jvm.additional=-XX:+AlwaysPreTouch
dbms.jvm.additional=-XX:+UnlockExperimentalVMOptions
dbms.jvm.additional=-XX:+TrustFinalNonStaticFields
dbms.jvm.additional=-XX:+DisableExplicitGC
dbms.jvm.additional=-XX:MaxInlineLevel=15
dbms.jvm.additional=-Djdk.nio.maxCachedBufferSize=262144
dbms.jvm.additional=-Dio.netty.tryReflectionSetAccessible=true
dbms.jvm.additional=-Djdk.tls.ephemeralDHKeySize=2048
dbms.jvm.additional=-Djdk.tls.rejectClientInitiatedRenegotiation=true
dbms.jvm.additional=-XX:FlightRecorderOptions=stackdepth=256
dbms.jvm.additional=-XX:+UnlockDiagnosticVMOptions
dbms.jvm.additional=-XX:+DebugNonSafepoints
dbms.windows_service_name=neo4j

**Comment by mnd999** [comment]
Thanks for the report. Do you have any indexes on the properties you're merging on - `row.src_pageid` and `row.dst_pageid`? If not, it's likely scanning the whole database which would explain poor performance. 
It would be good to see the query plan, please prepend `EXPLAIN` to your query and share the results.

**Comment by tklebanoff** [comment]
Ah, thank you for such a prompt reply.  I appreciate it! This immediately sounds like it could be the issue.
I'm going to make a quick sandwich, go for a run, and then come back and begin investigating.

I will post the results of the EXPLAIN query, along with some more detailed info as soon as I can.  thank you!!

**Comment by tklebanoff** [comment]
![plan](https://user-images.githubusercontent.com/48869587/95112805-6bd5a700-070f-11eb-9fbd-e1be7b489984.png)


Here is the exact query.  The batch has 1091 elements:

EXPLAIN
    LOAD CSV WITH HEADERS FROM "/tmp/csv/459/batch_n1091_53c74673-7440-44e3-a1b0-d81513b3d9d8" AS row
    MERGE (src:Page { pageid: row.src_pageid } )
    MERGE (dst:Page { pageid: row.dst_pageid } )
    SET
    src.length = toInteger(row.src_length),
    src.title  = row.src_title,
    src.url    = row.src_url,
    dst.length = toInteger(row.dst_length),
    dst.title  = row.dst_title,
    dst.url    = row.dst_url
    MERGE (src)-[:LINKS_TO]->(dst)

At the moment this query was executed and the PNG produced,
match(n) return count(n)
returns 150984

After generating the PNG, I did the following:
CREATE INDEX myindex FOR (n:Page) ON (n.src_pageid,n.dst_pageid)
and have:
[
    {
        "id": 1,
        "name": "myindex",
        "state": "ONLINE",
        "populationPercent": 100.0,
        "uniqueness": "NONUNIQUE",
        "type": "BTREE",
        "entityType": "NODE",
        "labelsOrTypes": [
            "Page"
        ],
        "properties": [
            "src_pageid",
            "dst_pageid"
        ],
        "provider": "native-btree-1.0"
    }
]

Since adding the index, I have not noticed the LOAD CSV performance speeding up.  Is this expected? 

By the way, the PNG UI output from the EXPLAIN query is superb!  I am quite impressed with neo4j as a system and its developers! It is so useful!  Many things are done so well! It has been very convenient for me to learn and use as a consumer who mostly just wants to get a specific job done efficiently. I was up and running in no time and the development experience has been great!

**Comment by tklebanoff** [comment]
Hi everybody! Adding an index helped a bit at the beginning (when creating the database from scratch).
Unfortunately, now each batch commit of 4000 elements takes about 550 seconds.

Currently, there are 133981 nodes in the database.

Does anybody have an idea of what else can be done to improve batch write performance? 

 If we could even get each batch write down to the 10 second mark, it would be a dramatic improvement.  I hope we can go faster.

**Comment by mnd999** [comment]
I think you want the index on `pageid` not `src_pageid` and `dst_pageid`.

From you plan, it isn't using the index as I see `NodeByLabelScan` which is a scan of all nodes with a particular label. When I create an index on pageid, I get a different plan with a `NodeIndexSeek`, which is what you want.
For more explanation of the plan components, check our documentation here - https://neo4j.com/docs/cypher-manual/current/execution-plans/operators/

**Comment by tklebanoff** [comment]
bingo!! thank you so much!! that was it!! 

now, the database is cranking!! blazing fast!! the batch queries are now completing in milliseconds!! it is faster than anything I could have hoped for in my dreams! 👍 
I suppose sometimes all it takes is a second pair of eyes.

I truly appreciate the time you have taken to help me find that bug.   I hope this message trail is helpful for anybody else in the future who may make a similar mistake (or who needs help getting good performance!)

neo4j rocks!
