### ISSUE TITLE
Cloning DB in Desktop App breaks original

### ISSUE THREAD

**Issue by mikemoore24** [neo4j/neo4j#12591]
- Neo4j Desktop version: 1.3.8 (1.3.8.34)
- Operating system: MacOS Mojave 10.14.6
- API/Driver: Desktop Menu options (Cypher)
- Steps to replicate

1. Create a new database and populate with some data within the desktop application
2. Ensuring the database is stopped, open the context menu for that database and click 'Clone'
3. A new cloned database 'DBMS' should be created (this database works correctly as the original did)
4. Attempt to start the original database
5. Error comes up Database failed to start: Error: Relate DBMS with tag neo4j-desktop-dbms-database-7ae53b09-0cc7-4a54-884e-cc5b6710736e not found. Check the logs - Note: Logs for that database are empty as it hasn't attempted to do anything with it.
6. Now Clone the new 'DBMS' database following steps above
7. Now 'DBMS' database doesn't work too whilst the second cloned database does work.

- Expected behavior

Using clone should not invalidate the original database, both databases should work. Not being able to copy makes working with the only working copy hazardous.

- Actual behavior

Any attempt to clone a database seems to break the original. Whilst the thumbnail can still be seen in the database menu it can not be started.

**Comment by mnd999** [comment]
Thanks for the report, this appear to be an issue with neo4j-desktop.  Can you re-raise it in that repository - https://github.com/neo4j-devtools/neo4j-desktop

Unfortunately it can't be transferred as it's a different repository
