### ISSUE TITLE
NullPointerException with Procedure Compiler 4.1.3

### ISSUE THREAD

**Issue by fbiville** [neo4j/neo4j#12602]
### Stack

- Neo4j version: 4.1.3
- JDK: AdoptOpen JDK 11.0.8
- Operating system: Mac OS 10.15
- Component: Procedure Compiler

#### Actual behavior

When changing the type from `List<String>` to `String[]` [here](https://github.com/fbiville/neo4j-join-user-function/blob/a6ef9c589bb443aaaf3eb72c9d77cdffe6aaea05/src/main/java/example/Join.java#L11), the procedure compiler crashes with a NPE:
```
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "javax.lang.model.type.TypeVisitor.visit(javax.lang.model.type.TypeMirror)" is null
```
No stack trace unfortunately.

#### Expected behavior
It should report instead that `String[]` is not a supported parameter type.

**Comment by mnd999** [comment]
Thanks for the report, we'll investigate and get back to you.

**Comment by hedengran** [comment]
We've investigated the issue and concluded that it arises due to an incorrect use of dependencies. The NPE thrown happens at compile time, while procedure compilation through ProcedureCompiler should be done at runtime. Removing the dependency below will resolve the issue.

```
<dependency>
    <groupId>org.neo4j</groupId>
    <artifactId>procedure-compiler</artifactId>
    <version>4.1.3</version>
    <scope>compile</scope>
</dependency>
```
