### ISSUE TITLE
Want Neo4j Trusted connector to access datasets in powerbi because autoreresh and schedule refresh are not working for non trusted neo4j third party connector

### ISSUE THREAD

**Issue by NarasimharaoTeegala** [neo4j/neo4j#12605]
While doing an auto-refresh or schedule refresh in power bi it is throwing an error because of non trusted neo4j connector so I want a trusted neo4j connector that supports power bi auto-refresh and schedule refresh can you please provide a neo4j trusted connector.

![Screenshot (55)](https://user-images.githubusercontent.com/46988973/95759009-cc905100-0cc6-11eb-9a0a-35ecee5f8710.png)
![Screenshot (57)](https://user-images.githubusercontent.com/46988973/95759037-d1ed9b80-0cc6-11eb-9342-dc0dd3b8bb90.png)

**Comment by mnd999** [comment]
Thanks for the report. Unfortunately, as it relates to the PowerBI connector it should be raised in the repository for that project (https://github.com/cskardon/Neo4jDataConnectorForPowerBi). As it has a different owner, I'm not able to transfer it so please re-raise it there.
