### ISSUE TITLE
Optional match with allShortestPaths and list comprehension results in 'Expected NO_VALUE to be a path' Neo4j 4.1.1

### ISSUE THREAD

**Issue by MichaelCDormann** [neo4j/neo4j#12601]
I discovered that when using an OPTIONAL MATCH with allShortestPaths and then doing some processing on the paths with list comprehension when the OPTIONAL MATCH does not produce a path it works up until about the 10th time the query is ran. After about the 10th time the query is ran the result is a `Neo.ClientError.Statement.TypeError: Expected NO_VALUE to be a path.` error from then on. If you modify the query in any way it works again up until about the 10th time it's ran, and then the same error happens from then on.

**Neo4j Version:** 4.1.1
**Operating System:** Red Hat Enterprise Linux:7.8:GA:server
(reproduced on Neo4j Desktop 1.3.8 for Windows with a fresh Neo4j 4.1.1 local database and Neo4j browser)

### Steps to reproduce
1. Run this query in Neo4j browser
```
MATCH (movie:Movie{title:'The Matrix'})
MATCH (actor:Person{name:'Tom Hanks'})
OPTIONAL MATCH path = allShortestPaths((movie)<-[*1..]-(actor))
RETURN movie, actor, [r IN relationships(path) WHERE type(r)='ACTED_IN' | r] AS breaks
```
2. Refresh the query about 10 times

### Expected behavior
A result is always returned.

### Actual behavior
A result is return the first few times, then the error `Neo.ClientError.Statement.TypeError: Expected NO_VALUE to be a path.` happens every time after that.

### More Examples
Moving the `relationships(path)` function call outside of the list comprehension seems to fix it. I couldn't get the below query to produce the same error after many more tries.
```
MATCH (movie:Movie{title:'The Matrix'})
MATCH (actor:Person{name:'Tom Hanks'})
OPTIONAL MATCH path = allShortestPaths((movie)<-[*1..]-(actor))
WITH relationships(path) as rels, movie, actor
RETURN movie, actor, [r IN rels WHERE type(r)='ACTED_IN' | r] AS doesNotBreak
```

**Comment by mnd999** [comment]
This has been resolved and will available in the next bugfix releases.
