### ISSUE TITLE
aggregation in subquery does not aggregate

### ISSUE THREAD

**Issue by RobinCaljouw93** [neo4j/neo4j#12607]
I have discovered that when I call an aggregation function in a subquery the result is not aggregated. 

**Neo4j Desktop:** 1.3.8
**Neo4j Version:** 4.1.3
**Operating System:** Windows 10

### Steps to reproduce
1. Create a fresh database with 3 nodes 0,1,2 where node 0 has a relation to node 1 and node 1 has a relation to node 2
2. Execute a query with a subquery. As an example I find the nodes connected to node 1 and aggregate some of the data of the connected nodes. I tried two different syntaxes, one with only the aggregated data and one with renamed original variables (because you can't return the original variables) so you more explicitly give the 'GROUP BY' clause: 

option1:

MATCH (n) - [] -> (m) 
where ID(n)=1
CALL {WITH n, m RETURN collect(m) as listn}
SET n.forwardRelationships = listn
return n;

option 2:

MATCH (n) - [] -> (m) 
where ID(n)=1
CALL {WITH n, m WITH n as n2, m as m2 RETURN n2, collect(ID(m2)) as listn}
SET n2.forwardRelationships = listn
return n2;

### Expected behavior
n2.forwardRelationships should be a list of two ids=[0,2]

### Actual behavior
n2 is returned twice with n2.forwardRelationships a list of size one [0] for the first record and [2] for the second record.

For this case (but not in the actual implementation I need) I can write this without a subquery. If I don't use a subquery then you get:

MATCH (n) - [] -> (m) 
where ID(n)=1
WITH n, collect(m) as listn
SET n.forwardRelationships = listn
return n;

Which does return one node n with n2.forwardRelationships a list of two ids=[0,2].

**Comment by InverseFalcon** [comment]
This isn't a bug, rather it's a result of the subquery executing upon the given scope.

(first let's clarify something...your setup needs to be more specific in that node 1 must have outgoing relationships to node 0 and node 2 in order for the matches in your queries to work)

Your subquery call is executing per `n, m` combination. Let's look at this step by step, using the query from your option 2.

1. The MATCH ... WHERE executes. The first resulting row of interim results is:

```
n = node 1, m = node 0
```

2. The subquery starts executing for the first row. For this first row, n = node 1, m = node 0. These get aliased to n2 and m2 respectively.

3. The collect() executes, collecting into a list the id of 0, and the list is returned.

4. The single-element list is set on node 1.

5. Node 1 is returned aliased as n2 with the current properties at this point in time.

6. The second MATCHed pattern is found, resulting in a second row of interim results:

```
n = node 1, m = node 2
```

7. The subquery starts executing for this second row. For this second row, n = node 1, m = node 2. These get aliased to n2 and m2 respectively.

8. The collect executes, collecting into a list the id of 2, and the list is returned.

9. The single-element list is set on node 1 (replacing the list set in step 4)

10. Node 1 is returned aliased as n2 with the current properties at this point in time.


Your mistake is assuming that the subquery executes once for the entire MATCH result stream, it does not. Subqueries execute per row, just the same as most other Cypher clauses, and when variables are in scope like this, it means that the subqueries executes for a single specific n and a single specific m (it just executes multiple times, once per row of specific nodes). 

If you want to be able to aggregate all m's per n node, then your MATCH must take place within the subquery, not outside of it, like so:

```
CALL {
  MATCH (n) - [] -> (m)
  WHERE ID(n)=1
  WITH n as n2, m as m2 
  RETURN n2, collect(ID(m2)) as listn
}
SET n2.forwardRelationships = listn
RETURN n2;
```

So the takeaway is that subqueries execute per row, and the variables for the row they execute upon make up the scope for that particular execution.

If there's still confusion, try returning the results at the point just before the subquery, and then understand that a separate subquery will be executed per each of those rows, with those particular variable values being the scope for the subquery:

```
MATCH (n) - [] -> (m)
where ID(n)=1
RETURN n, m
```

**Comment by RobinCaljouw93** [comment]
Thank you very much for the information. I did not find this behavior of sub-query's described but maybe that is my fault, otherwise it might be good idea to add to the documentation. 

I wanted to use sub-query's so I could do a relatively computationally heavy match only once in a single cypher statement. Now I know that if I want to do computations on entire result streams in a subquery I can but I first need to collect all input to 1 row and then unwind the input inside the sub-query.

With the answer above my question/issue has been answered.
