### ISSUE TITLE
Path meta data doesn’t include node labels or rel type (HTTP API)

### ISSUE THREAD

**Issue by johannessen** [neo4j/neo4j#12613]
When Cypher statements returning paths are executed over the [Transactional HTTP API](https://neo4j.com/docs/http-api/4.1/actions/), the JSON results do not include the labels of the nodes in the path, nor do they include the types of the relationships in the path.

This issue just came up in a conversation with @fbiville. In https://github.com/neo4j/neo4j/issues/12306#issuecomment-536500387, @technige mentioned that several issues around the HTTP output format were already known, so I kind of expected that this particular issue was one of them and never pursued this up until now.

### Reproducing the issue

Run the following query on the transactional HTTP interface.

````
CREATE p=(a:Test)-[b:TEST]->(c:Test) RETURN p
````

### Expected JSON result
````json
{
  "data": [
    {
      "meta": [
        [
          { "deleted": false, "id": 5,   "type": "node",         "labels": ["Test"] },
          { "deleted": false, "id": 368, "type": "relationship", "relationship_type": "TEST" },
          { "deleted": false, "id": 6,   "type": "node",         "labels": ["Test"] }
        ]
      ],
      ...
    }
  ]
}
````

### Actual JSON result
````json
{
  "data": [
    {
      "meta": [
        [
          { "deleted": false, "id": 5,   "type": "node" },
          { "deleted": false, "id": 368, "type": "relationship" },
          { "deleted": false, "id": 6,   "type": "node" }
        ]
      ],
      ...
    }
  ]
}
````

Note that the `rest` resultDataContents also do not include node labels or relationship types. The `graph` resultDataContents do, but it seems to me that this meta data should really be available in the `meta` resultDataContents.

One way of resolving this issue would be to add the labels/type in [`Neo4jJsonCodec.writeMeta()`](/neo4j/neo4j/blob/4.2/community/server/src/main/java/org/neo4j/server/http/cypher/format/common/Neo4jJsonCodec.java#L286), with `writeNodeOrRelationshipMeta()` being adjusted accordingly.

**Comment by technige** [comment]
@johannessen A new additional result format will be available in Neo4j 4.2. This should include more complete information, so will hopefully address your issue.

**Comment by johannessen** [comment]
Jolt looks good to me. Nice job, thanks!

**Comment by Maadhav** [comment]
I am not sure if I am missing something, but on neo4j 2.4.1 I still don't see any labels information in the meta property of the response. Are there any future plans for adding them?

**Comment by fbiville** [comment]
@Maadhav I assume you mean Neo4j 4.2.1, right?
Have you checked out https://neo4j.com/docs/http-api/current/actions/result-format/#_jolt?

**Comment by Maadhav** [comment]
@fbiville I have never worked before with jolt, and all my frontend apps, are using the JSON response from the rest of API. Just wanted to know if it would be possible to add the labels key in the meta field of the response in the future.
Thanks.

**Comment by fbiville** [comment]
@Maadhav I'm fairly confident this won't happen. You will need to switch to Jolt.

**Comment by johannessen** [comment]
As pointed out in the initial report, labels and types are available in JSON as part of the `graph` result if requested. Correlating the meta data this way on the client side seems a bit of a hassle though. I’d say Jolt should be considered the solution here.

Also, Jolt is much faster than JSON. ⚡️
