### ISSUE TITLE
neo4j-admin import - Multiple csv files with Regex

### ISSUE THREAD

**Issue by rom-burner** [neo4j/neo4j#12610]
- Neo4j version: 4.1.3
- OS: Linux 4.14
- Command (simplified): neo4j-admin import --nodes=Mynodes=import/mynodesfile_h.csv,import/mynodesfile_\\\d{1,5}.csv
- Expected behavior:
Imports Mynodes from all files beginning 'import/mynodesfile_' and ending between 1 and 5 decimal digits followed by '.csv'

- Actual behavior:
Pattern matches only on files with two digits, 1to9 as first digit and 1or5 as second, and matches on header file thus reimporting it a second time out of order.

Get the same behaviour with regex [0-9]{1,5}

Regex works fine with java regex library and many online regex calculators:
```
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.regex.PatternSyntaxException;

class RegexTest {
   private static String REGEX = "import/mynodesfile_\\d{1,5}.csv";
   private static String INPUT = "import/mynodesfile_1234.csv";
   private static Boolean isMatch = false;

   public static void main(String[] args) {
      try{
         Pattern pattern = Pattern.compile(REGEX);
         Matcher matcher = pattern.matcher(INPUT);
         isMatch = matcher.matches();
         System.out.println(isMatch);

      } catch(PatternSyntaxException e){
         System.out.println("PatternSyntaxException: ");
         System.out.println("Description: "+ e.getDescription());
         System.out.println("Index: "+ e.getIndex());
         System.out.println("Message: "+ e.getMessage());
         System.out.println("Pattern: "+ e.getPattern());
      }
   }
}
```
isMatch=true - finds import/mynodesfile_1234.csv in pattern with no errors.
I'm no java or regex expert but any ideas how the regex is expanded and compiled to give this result?

**Comment by tinwelint** [comment]
I think this looks like a bug in the regex matching of the import command, I'll look into it. Thanks for reporting.

**Comment by tinwelint** [comment]
@rom-burner The problem is that the comma

```
_\\d{1,5}.csv
      ^
```

will be interpreted as a delimiter to another file just like the other comma e.g.

```
import/mynodesfile_h.csv,import/m...
                        ^
```

and split the last file which is a regex pattern in two and therefore not find the right files. I'm not sure how this should be solved best, but perhaps with something like:

```
import/mynodesfile_h.csv,'import/mynodesfile_\\d{1,5}.csv'
```

i.e. the additional inner quotation with `'` to tell the import command parser to keep that pattern as a single pattern and not split it. Would that work as a solution?

**Comment by tinwelint** [comment]
As a workaround tho you could probably use a pattern like:

```
import/mynodesfile_h.csv,import/mynodesfile_\\d+.csv
```

couldn't you?

**Comment by rom-burner** [comment]
ahh yes thanks mattias, if it's just a problem with mis-parsing the regex comma as a command comma i'm sure your regex match will fix it - just couldn't figure out how to squeeze a working regex in before i ended up just scripting the command - thanks for tracking it down!

**Comment by tinwelint** [comment]
Cheers 🥇 :)
