### ISSUE TITLE
Neo4j Desktop 1.3.8 : Graph-App: InjectedAPI path variable points to wrong location

### ISSUE THREAD

**Issue by mmopitz** [neo4j/neo4j#12611]
Hi there,
I don't know if this is the correct tracker for neo4j desktop tickets. But I'll just post it here :-)

For newly created databases a graph's path variable points to a wrong (outdated?) directory.

I read said path variable through the injectedAPI: https://neo4j.com/developer/graph-apps/building-a-graph-app/#_injected_api 
When I say path variable I mean following variable: `neo4jDesktopApi.getContext().then(context=>context.projects[0].graphs[0].connection.configuration.path)`

The problem occurs only for graphs that I created with Neo4j Desktop 1.3.8 . For graphs created with earlier versions the paths are correct.

**Neo4j Desktop Version:** 1.3.8
**Operating System:** Ubuntu 18.04 and Windows 10 Enterprise and MacOs
**API:** GraphApp Injected API 

Note: I show the problem in the 'App Developer Tool' by simply typing some commands into the the Developer Tool's Console. 

### Steps to reproduce
1. Start Neo4j Desktop 1.3.8
2. Create a new graph 'Test'
3. Start a Database
4. Enable Neo4j Desktop's 'Development Mode' : https://neo4j.com/developer/graph-apps/building-a-graph-app/#enable-dev-tools
5. Start Neo4j Browser
6. Open up Neo4j Browser's Developer Tools -> Console
7. Print the paths of all graphs: `
```
neo4jDesktopApi.getContext().then(context=>context.projects.forEach(p=>p.graphs.forEach(g=>console.log(p.name +':'+g.name+':'+g.connection.configuration.path))))
//Outcome on my ubuntu machine:
[...]
My Project:Test:/home/mo/.config/Neo4j Desktop/Application/neo4jDatabases/database-26c48192-e0a8-4322-b5cc-bc84c18ac39c/installation-4.1.2
[...]
//expected (I obtained the correct path through Neo4j Desktop's 'Manage Graph'-> 'Open Folder'):
[...]
My Project:Test:/home/mo/.local/share/neo4j-relate/dbmss/dbms-d67d7c55-c15e-4c3e-8a8b-20abaddcbc67/
[...]
```
I guess that Neo4j now installs all new graphs to said location. But the path variable wasn't updated accordingly. 

### Some Background

Just as information: I want to access my graphs' plugin directories in my graph app to copy a jar file into said directory. Because the plugin dependency way described in the documentation is not an option for us. 
So I thought I could get the plugin directory by simply append '/plugin' to the connection.configuration.path variable.

**Comment by mnd999** [comment]
Thanks for raising this. Unfortunately, this is not the correct repository for neo4j-desktop issues. Please re-raise the issue here - https://github.com/neo4j-devtools/neo4j-desktop/issues. I can't transfer it sadly as it's a different organisation.
