### ISSUE TITLE
Where are Predicate Functions defined in source code? Such as Any(), All(), Single() and Exists()?

### ISSUE THREAD

**Issue by jievince** [neo4j/neo4j#12622]

**Comment by sherfert** [comment]
@jievince Thanks for your interest in our source code.
The functionality is a bit spread out, but I would recommend looking at [InList](https://github.com/neo4j/neo4j/blob/4.2/community/cypher/interpreted-runtime/src/main/scala/org/neo4j/cypher/internal/runtime/interpreted/commands/InList.scala) and exploring from there.
