### ISSUE TITLE
Creating relationship with distinct match

### ISSUE THREAD

**Issue by zhangx20** [neo4j/neo4j#12628]
I am trying to create relationships between nodes that are distinct. Right now, I can only return distinct. Is there any way for me to match distinct or create distinct? For example:

match (p:Player), (n:Games) where p.id = n.id
create (p)-[:has_played]->[n]

There are player nodes with the same id and the query above is matching all the games to the duplicated player ids. Is there some way I can get the distinct player ids and match it with the games?

**Comment by sherfert** [comment]
Hi @zhangx20 
I am not 100 % sure I understand. I interpret your question as "Is there a way to remove the duplicates of players with same IDS _and then_ continue with `create`?"

If that interpretation is correct, try:

```
MATCH (p:Player)
WITH DISTINCT p.id AS pid
MATCH (n:Games) WHERE pid = n.id
CREATE (p)-[:has_played]->(n)
```

Does that help?

**Comment by mnd999** [comment]
As we have not heard anything back on this for some time I will close it for now. If this is still an issue, please feel free to reopen it.
