### ISSUE TITLE
Missing apoc.export.csv.all.

### ISSUE THREAD

**Issue by cn0047** [neo4j/neo4j#12624]
## Guidelines

There is function [apoc.export.csv.all](https://neo4j.com/labs/apoc/4.1/overview/apoc.export/apoc.export.csv.all/) but no function [apoc.import.csv.all](https://neo4j.com/labs/apoc/4.1/overview/apoc.import/apoc.import.csv/),
and it's not clear how to import CSV file generated by func `apoc.export.csv.all`.

**Neo4j Version:** 4.1.1
**API:** Docker

**Comment by mnd999** [comment]
Thanks for your report, the correct repository to to raise issues relating to APOC is https://github.com/neo4j-contrib/neo4j-apoc-procedures. Please reopen your issue in that repository. Unfortunately, I am unable to transfer it there as it's in a different organisation.
