### ISSUE TITLE
Typo in Jolt docs in strict mode media type

### ISSUE THREAD

**Issue by johannessen** [neo4j/neo4j#12629]
<https://neo4j.com/docs/http-api/4.2/actions/result-format/#_strict_and_sparse> says:

> To enable *strict mode,* pass `application/vnd.neo4j.jolt+json-seq:strict=true` in the `Accept` header.

According to [RFC7231](https://tools.ietf.org/html/rfc7231#section-5.3.2), a semicolon (`;`) is used to separate parameters from media types. The Jolt docs quoted above are using a colon (`:`). The Neo4j server does seem to follow the RFC here, so this is only a documentation typo as far as I can tell. But it may trip up users who aren’t well familiar with the HTTP spec.

The full media type should read: `application/vnd.neo4j.jolt+json-seq;strict=true`

**Comment by davidoliverSP2** [comment]
Thank you @johannessen - good spot!

We've fixed this, and it'll be resolved in the next publishing build.
