### ISSUE TITLE
Missing log4j-core on the classpath when runnning neo4j 4.2.0

### ISSUE THREAD

**Issue by tanvp112** [neo4j/neo4j#12631]
To reproduce, execute:

docker run -it --rm --name="eval-neo4j" \
  --network=host \
  -v /import:/import \
  -v /export:/export \
  -v /data \
  -v /logs \
  -v /plugins:/plugins \
  -e NEO4J_dbms_security_procedures_unrestricted=apoc.\\\*,gds.\\\* \
  -e NEO4J_apoc_import_file_enabled=true \
  -e NEO4J_apoc_import_file_use__neo4j__config=false \
  -e NEO4J_apoc_export_file_enabled=true \
  -e NEO4J_ACCEPT_LICENSE_AGREEMENT=yes \
  -e NEO4J_AUTH=neo4j/eval \
  -e NEO4J_dbms_mode=SINGLE \
  -e NEO4J_dbms_memory_pagecache_size=2g \
  -e NEO4J_dbms_memory_heap_initial__size=3600m \
  -e NEO4J_dbms_memory_heap_max__size=3600m \
  -e NEO4J_dbms_default__listen__address=0.0.0.0 \
  neo4j:4.2.0-enterprise \
  && docker logs -f eval-neo4j
...
Starting Neo4j.
WARNING: Max 1024 open files allowed, minimum of 40000 recommended. See the Neo4j manual.
APOC couln't set a URLStreamHandlerFactory since some other tool already did this (e.g. tomcat). This means you cannot use s3:// or hdfs:// style URLs in APOC. This is caused by a limitation of the JVM which we cannot fix. 
APOC couln't set a URLStreamHandlerFactory since some other tool already did this (e.g. tomcat). This means you cannot use s3:// or hdfs:// style URLs in APOC. This is caused by a limitation of the JVM which we cannot fix. 

**_ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console..._**

2020-11-23 08:38:55.904+0000 INFO  Starting...
2020-11-23 08:38:58.030+0000 INFO  ======== Neo4j 4.2.0 ========
2020-11-23 08:39:12.319+0000 INFO  Called db.clearQueryCaches(): Query cache already empty.
2020-11-23 08:39:12.530+0000 INFO  Sending metrics to CSV file at /var/lib/neo4j/metrics
2020-11-23 08:39:12.547+0000 INFO  Bolt enabled on 0.0.0.0:7687.
2020-11-23 08:39:13.502+0000 INFO  Remote interface available at http://localhost:7474/
2020-11-23 08:39:13.503+0000 INFO  Started.

Switch the image back to 4.1.1 with same command doesn't yield the problem. This error applied to running in Kubernetes as well.

**Comment by emmaholmbergohlsson** [comment]
Hi @tanvp112, thank you for reporting your problem. 
This is a known issue and something that has been fixed for 4.2.1. This does not affect how Neo4j performs or writes to the logs in any way.
Please reopen the ticket if that patch doesn't solve your issue.
