### ISSUE TITLE
RasberryPi4 8GB command $neo4j-admin memrec gives available memory of OB (zero bytes) 

### ISSUE THREAD

**Issue by omerule** [neo4j/neo4j#12638]
- Neo4j version: 4.2.1
Operating system: Debian version 10.6 32bit 
Raspberry Pi 4 8GB

### Steps to reproduce
1.Install neo4j with apt-get install neo4j
2. run $neo4j-admin memrec

### Expected behavior
run $neo4j-admin memrec 
See the Memory available on the System (8GB).

### Actual behavior
Assuming the system is dedicated to running Neo4j and has **0**B of memory, ....
....
Based on the above, the following memory settings are recommended:
dbms.memory.heap.initial_size=**-1024k** 
dbms.memory.heap.max_size=**-1024k** 
dbms.memory.pagecache.size=8m

Yours kindly Omer

**Comment by uevora428** [comment]
I am having the same issue.

`/var/logs/neo4j/neo4j.log` gives me the following error:

2021-01-18 19:30:44.198+0000 ERROR Invalid memory configuration - exceeds physical memory. Check the configured values for dbms.memory.pagecache.size and dbms.memory.heap.max_size

changing the conf file to have the recommended memory settings by `neo4j-admin memrec --memory=4g` does not appear to have any affect.

**Comment by Roxling** [comment]
Neo4j on RasberryPi is not a supported platform, see the [documentation](https://neo4j.com/docs/operations-manual/current/installation/requirements/). The memory recommendations are dependent on a correct reporting of the memory by the `OperatingSystemMXBean` so my guess would be that the JVM you are using does not support that feature.

We do welcome community pull requests if you find this important enough to fix it your self. The code is found here:
[MemoryRecommendationsCommand.java](https://github.com/neo4j/neo4j/blob/4.2/community/dbms/src/main/java/org/neo4j/commandline/dbms/MemoryRecommendationsCommand.java)

**Comment by omerule** [comment]
Thanks for the reply,

There seem to be some regression with OpenJDK determin RAM and when cgroup memory is disabled: 
" 
8257746: Regression introduced with JDK-8250984 - memory might be null in some machines by poonamparhar · Pull Request #2269 · openjdk/jdk · GitHub
" 
When looking at $ cat /proc/cgroups Memory is not enabled.
In found this thread on Ask Ubuntu: 
" 
raspberrypi - Raspberry Pi 4 Ubuntu 19.10 cannot enable cgroup memory at boostrap - Ask Ubuntu
" 
After editing /boot/cmdline.txt add at the end of the line:
cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory

Then did a reboot and cat /proc/cgroups memory is enabled. And run the command neo4j-admin memrec gives the available Memory and when I run $ sudo systemctl start neo4j, Neo4j starts again.

Hopefully this will help.

Yours kindly Omer

**Comment by uevora428** [comment]
@omerule I really appreciate this. Your steps worked for me. Thanks!

**Comment by unbekanntes-pferd** [comment]
Thanks a lot, @omerule – your Ask Ubuntu hint worked for me as well (I had to change /boot/firmware/nobtcmd.txt, as /boot/cmdline.txt did not work)!
