### ISSUE TITLE
Bug with path variables and subquery

### ISSUE THREAD

**Issue by bradenmacdonald** [neo4j/neo4j#12636]
I found some strange behavior with Cypher queries that reference a path variable before and after a subquery, which looks like a bug. [I also posted about it on the forum](https://community.neo4j.com/t/strange-behavior-of-path-variables-with-call-subquery/29810).

- Neo4j version: 4.2.0
- Operating system: official docker image
- API/Driver: built-in web interface

**Steps to reproduce**:

Run this query; it doesn't matter what data you have in the database, as it's a bug parsing the query.

```cypher
MATCH (person:Person)
OPTIONAL MATCH path1 = (person)-[:ACTED_IN]->(movie:Movie)
CALL {
    WITH movie
    OPTIONAL MATCH (movie)-[:FRANCHISE_IS]->(_moviefranchise1:MovieFranchise)
    RETURN _moviefranchise1 LIMIT 1
}
WITH person, movie, path1, _moviefranchise1 {.uuid, .name} AS _franchise1
WITH person, collect(movie {.title, franchise: _franchise1}) AS movies
RETURN person, movies
```

**Expected behavior**

Expect the query to run.

**Actual behavior**

Neo.ClientError.Statement.SyntaxError:

```
Variable `path1` not defined (line 8, column 21 (offset: 239))
"    LIMIT 1"
        ^
```

Note that `line 8, column 21` is actually where `path1` occurs in the `WITH` clause of the query, but for some reason the error message is showing a snippet of line 6 instead (`LIMIT 1`), which is irrelevant.

The error goes away if an additional `WITH` clause is introduced before the subquery:

```cypher
MATCH (person:Person)
OPTIONAL MATCH path1 = (person)-[:ACTED_IN]->(movie:Movie)

// This new line is the only change:
WITH person, movie, path1

CALL {
    WITH movie
    OPTIONAL MATCH (movie)-[:FRANCHISE_IS]->(_moviefranchise1:MovieFranchise)
    RETURN _moviefranchise1 LIMIT 1
}
WITH person, movie, path1, _moviefranchise1 {.uuid, .name} AS _franchise1
WITH person, collect(movie {.title, franchise: _franchise1}) AS movies
RETURN person, movies
```

**Comment by mnd999** [comment]
Thanks for reporting this one, will take a look at it and let you know what we find.

**Comment by hedengran** [comment]
This bug was found in the enterprise edition and has now been fixed. Thank you for reporting this @bradenmacdonald.
