### ISSUE TITLE
Reporting in Halin and apoc.log.stream failed with neo4j 4.2.0

### ISSUE THREAD

**Issue by tanvp112** [neo4j/neo4j#12632]
To reproduce, execute:

docker run -it --rm --name="eval-neo4j" \
  --network=host \
  -v /import:/import \
  -v /export:/export \
  -v /data \
  -v /logs \
  -v /plugins:/plugins \
  -e NEO4J_dbms_security_procedures_unrestricted=apoc.\\\*,gds.\\\* \
  -e NEO4J_apoc_import_file_enabled=true \
  -e NEO4J_apoc_import_file_use__neo4j__config=false \
  -e NEO4J_apoc_export_file_enabled=true \
  -e NEO4J_ACCEPT_LICENSE_AGREEMENT=yes \
  -e NEO4J_AUTH=neo4j/eval \
  -e NEO4J_dbms_mode=SINGLE \
  -e NEO4J_dbms_memory_pagecache_size=2g \
  -e NEO4J_dbms_memory_heap_initial__size=3600m \
  -e NEO4J_dbms_memory_heap_max__size=3600m \
  -e NEO4J_dbms_default__listen__address=0.0.0.0 \
  neo4j:4.2.0-enterprise \
  && docker logs -f eval-neo4j

Launch Halin and observes:

1. Overview - Page Cache reported "Error Retrieving Data". Intermittently, Last GC Pause Time also reported "Error Retrieving Data"
2. Members -> Metrics, cannot load metrics, empty view.
3. Members -> Logs, attempt to load debug.log return: "Neo4jError: Failed to invoke procedure `apoc.log.stream`: Caused by: java.lang.NoClassDefFoundError: Could not initialize class apoc.util.FileUtils"

Start a Neo4j browser session and execute apoc.log.stream('debug.log', {last:5}) reported the same error.

However, all plugins were installed correctly:
![image](https://user-images.githubusercontent.com/57385114/99943694-a7562e80-2dac-11eb-97e1-1d4b1e01f696.png)

The above error applied to running in Kubernetes as well. It looks like permission error in the container itself, was it due to neo4j user changed to 7474 in the image?

Switch to neo4j:4.1.4-enterprise image removed all issues with docker. But for Kubernetes, except for Halin -> Overview - Last GC Pause Time reported "Error Retrieving Data", the rest like log streaming, metrics reporting all OK.

**Comment by mnd999** [comment]
Thanks for reporting this issue! This repo relates to the Neo4j database - the correct repository for Halin is https://github.com/moxious/halin

I had a chat with my colleagues who work on Halin though and work is still ongoing to make Halin compatible with Neo4j 4.2. If you wish can re-raise the issue in the Halin repo, but be reassured that the work to fix the issues on 4.2 is in progress and they will have a compatible version available soon.

Will close this one for now, as it is not the right repository for Halin.

**Comment by tanvp112** [comment]
While the issue seems like Halin, you can get the same error by executing CQL; example execute apoc.log.stream('debug.log', {last:5}) via Neo4j browser.

I also noticed 4.2.0 seems not able to interpret the environment variables correctly. While not obvious with docker, but when runs with Kubernetes, there are error messages stating "Unrecognized setting." and these messages can be traced back to the environment variable set in the pod manifest. This can also cause the error above.

Reference: https://community.neo4j.com/t/neo4j-4-1-1-fails-in-kubernetes-environment/21783
