### ISSUE TITLE
Performance: Simple queries showing more "db hits" in Neo4j 4.2

### ISSUE THREAD

**Issue by bradenmacdonald** [neo4j/neo4j#12630]
I am trying out Neo4j 4.2 and some performance tests in my project started failing because some very simple queries are now less performant in 4.2 compared to 4.1 - or at least, the `PROFILE` output says they require far more `db hits`.

- Neo4j version: 4.2.0
- Operating system: official docker image
- API/Driver: built-in web interface (Neo4j Browser)

## Steps to reproduce:

Starting with a blank database and these constraints + two sample nodes:

```
CREATE CONSTRAINT vnode_uuid_uniq ON (v:VNode) ASSERT v.uuid IS UNIQUE
CREATE CONSTRAINT vnode_shortid_uniq ON (v:VNode) ASSERT v.shortId IS UNIQUE
CREATE CONSTRAINT shortid_shortid_uniq ON (s:ShortId) ASSERT s.shortId IS UNIQUE

CREATE (u:User:VNode { uuid: "00000000-0000-0000-0000-000000000000", shortId: "system", realname: "System"})
MERGE (s:ShortId {shortId: u.shortId})-[:IDENTIFIES]->(u)
```

## Expected behavior

Running two queries on Neo4j 4.1.1 gave 3 hits and 7 hits respectively:

```
PROFILE MATCH (u:User:VNode {uuid: "00000000-0000-0000-0000-000000000000"}) RETURN u
```
> Cypher version: CYPHER 4.1, planner: COST, runtime: INTERPRETED. 3 total db hits in 1 ms.

```
PROFILE MATCH (u:User:VNode)<-[:IDENTIFIES]-(:ShortId {shortId: "system"}) RETURN u
```
> Cypher version: CYPHER 4.1, planner: COST, runtime: INTERPRETED. 7 total db hits in 3 ms.

## Actual behavior

Now, with 4.2 the same trivial queries need 7 hits and 10 hits respectively:

```
PROFILE MATCH (u:User:VNode {uuid: "00000000-0000-0000-0000-000000000000"}) RETURN u
```
> Cypher version: CYPHER 4.2, planner: COST, runtime: INTERPRETED. 7 total db hits in 23 ms.

```
PROFILE MATCH (u:User:VNode)<-[:IDENTIFIES]-(:ShortId {shortId: "system"}) RETURN u
```

> Cypher version: CYPHER 4.2, planner: COST, runtime: INTERPRETED. 10 total db hits in 14 ms.

Here are the different plans, 4.1.1 on the left and 4.2 on the right:

<img width="626" alt="Screen Shot 2020-11-20 at 4 42 42 PM" src="https://user-images.githubusercontent.com/945577/99862658-6c0af400-2b4f-11eb-8311-58b01a6cd01e.png">
 
<img width="606" alt="Screen Shot 2020-11-20 at 4 44 48 PM" src="https://user-images.githubusercontent.com/945577/99862745-b7250700-2b4f-11eb-9a2b-bccd148373c7.png">

I am admittedly new to Neo4j so I don't know if this is an actual performance regression but it seems like it?

**Comment by sherfert** [comment]
Hi @bradenmacdonald and thanks for the question.

In the PROFILE output you can see that the difference in DB hits is in the `ProduceResults` operator.
In this case, that is actually not a performance regression, but more accurate counting. We always had those DB hits in `ProduceResults`, but only now in 4.2 started counting them. So the queries should do the same amount of work as in 4.1.

To give a little bit more background: When you return a node or relationship, like in your queries, the database not only returns the id of those entities, but also all labels and properties. And the DB hits to fetch those were not counted before.

**Comment by bradenmacdonald** [comment]
Thanks for the explanation, @sherfert! Glad to hear that.
