### ISSUE TITLE
Apoc Text Procedures Not Available

### ISSUE THREAD

**Issue by prasad12-02** [neo4j/neo4j#12645]
I am using Neo4j Desktop, and trying to work with apoc text procedures but it doesnt seem to be available in the database instance that i am working with. I have tried making changes in the configuration file, used a different jar file for apoc, uninstalled and installed Neo4j Desktop again and also tried the same on neo4j browser, still getting error like apoc.text.distance is not registered with your database. Please Help.

**Comment by mnd999** [comment]
Thanks for your report, the correct repository to to raise issues relating to Neo4j Desktop is https://github.com/neo4j-devtools/neo4j-desktop. Please reopen your issue in that repository. Unfortunately, I am unable to transfer it there as it's a different organisation.
