### ISSUE TITLE
Run in browser buttons don't launch neo4j Browser

### ISSUE THREAD

**Issue by glitchgirl** [neo4j/neo4j#12648]
When on [cypher shell](https://neo4j.com/docs/operations-manual/current/tools/cypher-shell/#cypher-shell-syntax) the Neo4j browser won't launch 
- Neo4j version: N/A - on website
- Operating system: Mac Catalina + Chrome

## Expected behavior
When I click "Run in Neo4j Browser" the application opens and runs the appropriate command for that example.

## Actual behavior 
When I click "Run in Neo4j Browser" the application does nothing, but this error shows up in the console:
`/docs/operations-manual/current/tools/cypher-shell/#cypher-shell-syntax:1 Failed to launch 'neo4j-desktop://graphapps/neo4j-browser?cmd=edit&arg=%24neo4j-home%3E%20bin%2Fcypher-shell%20-u%20neo4j%20-p%20%3Cpassword%3E' because the scheme does not have a registered handler.`

I tried this on two different computers (personal and work) and go the same issue.

**Comment by stefano-ottolenghi** [comment]
I'm closing this as the `Run in Neo4j Browser` button was retired earlier this year.
