### ISSUE TITLE
Cypher shell instantly closes after starting (4.2.0 or higher)

### ISSUE THREAD

**Issue by RobertRijksen97** [neo4j/neo4j#12643]
I discovered that when you start the cypher shell in a Neo4j version 4.2.0 or higher, 
you get an error and the cypher shell instantly closes. 
You can see the error for a split-second but no log-file is written therefore the error is untracable. 

Does anyone else experience this issue? 
In earlier versions this error does not occur , so I am assuming it's a bug.

**Comment by shammakh2** [comment]
How are you using shell? Did you download the zip? Did it come with the server?
Do you still face this issue? Where did you download from? Did you try getting it again? What driver version are you using it with?
Did you try setting up another server and using cypher with it?
Please give more details.

**Comment by mnd999** [comment]
As the previous commentator suggests, we need a bit more information to investigate this further, can you let us know a bit more about your environment / operating system, Java versions, Neo4j setup, whether you are using desktop or standalone etc that might be useful to help us reproduce the issue.

**Comment by mnd999** [comment]
We've not heard anything back on this for a while, so I will close it for now. If it's still an issue, please feel free to re-open.
