### ISSUE TITLE
v4.2.x no longer accepts "True" or "False" as label names.

### ISSUE THREAD

**Issue by mcclown** [neo4j/neo4j#12658]
- Neo4j version: 4.2.2
- Operating system: Windows 10 Pro - 1909
- API/Driver: Cypher
- Use the cypher query `CREATE (:False)`
- Expected behavior: A new node called False is created
- Actual behavior: An error, as per below

`Invalid input ':': expected "shortestPath", "allShortestPaths" or "(" (line 1, column 9 (offset: 8))
"CREATE (:False)"`

This also occurs for `CREATE (:True)`

This has worked with previous versions of Neo4j. (ie. v4.1.3, v3.5.14)

**Comment by mnd999** [comment]
Thanks for the report, we'll take a look at it. If you need a workaround in the interim, you can get the old parser behaviour in 4.2 by setting `unsupported.cypher.parser=PARBOILED` in your `neo4j.conf`. This is an unsupported setting though so it may be removed in a future release.

**Comment by mcclown** [comment]
@mnd999 thank you for the quick response. I was only investigating an upgrade, so it's not pressing yet.

**Comment by johannessen** [comment]
Adding an unused variable seems to work around this issue: `CREATE (n:False)` succeeds for me.

**Comment by sherfert** [comment]
A fix has been merged and will be included in the version 4.2.3.
