### ISSUE TITLE
LogPruningImpl.cleanupCheckpointLogFiles() performs unintended String concatenation

### ISSUE THREAD

**Issue by Marcono1234** [neo4j/neo4j#12656]
It appears the method `LogPruningImpl.cleanupCheckpointLogFiles()` performs unintended String concatenation:
https://github.com/neo4j/neo4j/blob/d12182c8faa09aea2f37debf5d08e3951b7d57c8/community/kernel/src/main/java/org/neo4j/kernel/impl/transaction/log/pruning/LogPruningImpl.java#L119

The current implementation is equivalent to:
```java
log.info( "... version: " + Long.toString(highestVersionToRemove) + "1" );
```
The code should likely print the result of `highestVersionToRemove + 1` instead. Therefore parentheses around this addition are needed.

**Comment by tinwelint** [comment]
You are absolutely right, thanks for reporting
