### ISSUE TITLE
Show Current Configuration setting

### ISSUE THREAD

**Issue by yyseik** [neo4j/neo4j#12667]
HI, 

Is there any way to show current configuration? Eg, like what we can do on mysql "SHOW VARIABLES;"
Because I try to use SSL on both BOLT and HTTPS. After I added the certificate, I am not sure am I using SSL on the connection or not. 

Thanks

**Comment by gjmwoods** [comment]
Hi @yyseik. Firstly sorry about the long delay in responding.

You can get the general configuration of the server by calling `CALL dbms.listConfig()`. It essentially shows you what is configured in `neo4j.conf` (see more here https://neo4j.com/docs/operations-manual/current/configuration/).

You can be sure you're using encryption if you successfully hit the `https` endpoint or, for bolt, you use one of the secure URI schemes (e.g. `neo4j+s/neo4j+ssc`). More about that can be found here: https://neo4j.com/docs/java-manual/current/client-applications/#java-driver-configuration-examples.

You can also enforce that encryption is used by setting `dbms.connector.bolt.tls_level` to `REQUIRED` for bolt and completely disabling plain text HTTP by setting `dbms.connector.http.enabled` to `false`
