### ISSUE TITLE
neo4j4.1.2 browser 404

### ISSUE THREAD

**Issue by LianxinGao** [neo4j/neo4j#12664]
start neo4j server in IDEA,  my code , conf and dependency are as follows
```
val NEO4J_HOME = "MY DB PATH"
val NEO4J_CONF = "MY CONF PATH"
CommunityEntryPoint.main(Array(s"--home-dir=${NEO4J_HOME}", s"--config-dir=${NEO4J_CONF}"))
```
```
dbms.security.auth_enabled=false
dbms.default_listen_address=0.0.0.0
dbms.connector.bolt.enabled=true
dbms.connector.bolt.listen_address=:7486
dbms.connector.bolt.advertised_address=:7486
dbms.connector.http.enabled=true
dbms.connector.http.listen_address=:7474
dbms.connector.http.advertised_address=:7474
dbms.connector.https.enabled=false
```

```
<dependency>
        <groupId>org.neo4j</groupId>
        <artifactId>neo4j</artifactId>
        <version>4.1.2</version>
</dependency>
```
It started successfully, but I can't access the web ' http://localhost:7474/'

**Comment by mnd999** [comment]
On the face of it this what you have seems to be be okay, although if you want the neo4j user interface to appear you will also need the neo4j-browser dependency. 

Is anything listening on port 7474  when you run your code?

**Comment by LianxinGao** [comment]
> On the face of it this what you have seems to be be okay, although if you want the neo4j user interface to appear you will also need the neo4j-browser dependency.
> 
> Is anything listening on port 7474 when you run your code?

you mean, the org.neo4j doesn't include the browser's dependency? No listening on 7474  also I changed the port , the browser still doesn't work.....

**Comment by mnd999** [comment]
Correct, not all customers embedding Neo4j in their application want the browser experience, so it's an optional dependency. If you do not include it as a dependency, the HTTP APIs will still work, but not the browser. 

If you just want to run Neo4j locally, I would recommend the Neo4j Desktop product which will allow you to easily get the browser up and running.

**Comment by LianxinGao** [comment]
> Correct, not all customers embedding Neo4j in their application want the browser experience, so it's an optional dependency. If you do not include it as a dependency, the HTTP APIs will still work, but not the browser.
> 
> If you just want to run Neo4j locally, I would recommend the Neo4j Desktop product which will allow you to easily get the browser up and running.

Got it, thanks a lot!
