### ISSUE TITLE
Jolt is not a JSON Text Sequence

### ISSUE THREAD

**Issue by johannessen** [neo4j/neo4j#12663]
Neo4j 4.2.2 sends Jolt with a media type of `application/vnd.neo4j.jolt+json-seq`.

According to [RFC 8091](https://tools.ietf.org/html/rfc8091#section-3), the `+json-seq` structured syntax suffix SHOULD be used when parsing a resource as an [RFC 7464](https://tools.ietf.org/html/rfc7464#section-2.1) JSON Text Sequence leads to a meaningful result.

This is not in fact the case for Jolt responses created by Neo4j 4.2.2.

### Details

[RFC 7464](https://tools.ietf.org/html/rfc7464#section-2.2) specifies the JSON Text Sequence as follows:

    JSON-sequence = *(RS JSON-text LF)

Generic JSON may contain `LF` bytes, but not `RS` bytes. In a JSON Text Sequence, an `RS` byte is therefore an unambiguous marker of the beginning of a JSON text. The `LF` byte is only required for the proper handling of top-level JSON values that aren’t self-delimiting; for JSON objects `{...}`, the `LF` byte is effectively [optional](https://tools.ietf.org/html/rfc7464#section-2.4).

Neo4j’s [EventSourceSerializer](https://github.com/neo4j/neo4j/blob/7acdb8da64a42266d63463b99b5c94675ff7e32e/community/server/src/main/java/org/neo4j/server/http/cypher/format/output/eventsource/EventSourceSerializer.java#L57-L58) class instead produces:

    Jolt-sequence = *(JSON-text LF)

This is not a JSON Text Sequence. This format is sometimes called [Newline Delimited JSON (NDJSON)](http://ndjson.org/). It is not currently registered with the IANA; sometimes the media type `application/x-ndjson` is used for it, but there is no structured syntax suffix registered for it.

The Wikipedia article on [JSON streaming](https://en.wikipedia.org/wiki/JSON_streaming) also discusses these two different formats (among others).

### Impact

Generic [RFC 7464](https://tools.ietf.org/html/rfc7464#section-2.1) JSON Text Sequence parsers will fail when used on a Jolt response. Looking at the commit message of https://github.com/neo4j/neo4j/commit/7acdb8da64a42266d63463b99b5c94675ff7e32e, I suppose this is the opposite of what was intended.

Jolt is still very new and there are likely very few implementations so far. (I’m currently only aware of two, one of them my own.) The newline delimited format is simple enough to implement that no one might ever try a generic RFC 7464 parser with Jolt. Additionally, while generic RFC 7464 parsers do exist, they don’t appear to be particularly common at this time.

So the impact of this issue is currently **very** small.

This assumption may or may not remain accurate in future.

### Possible ways forward

The options to move forward include:

* Change the [EventSourceSerializer](https://github.com/neo4j/neo4j/blob/7acdb8da64a42266d63463b99b5c94675ff7e32e/community/server/src/main/java/org/neo4j/server/http/cypher/format/output/eventsource/EventSourceSerializer.java) class to conform to [RFC 8091](https://tools.ietf.org/html/rfc8091#section-3) and [RFC 7464](https://tools.ietf.org/html/rfc7464#section-2.2). Existing Jolt clients may or may not choke on the `RS` bytes, but future clients will be able to use generic RFC 7464 parsers.

* Revert https://github.com/neo4j/neo4j/commit/7acdb8da64a42266d63463b99b5c94675ff7e32e and change the media type back to only `application/vnd.neo4j.jolt` (with no structured syntax suffix). Existing clients that accept `application/vnd.neo4j.jolt+json-seq` need to fall back to plain old JSON.

* Keep supporting `application/vnd.neo4j.jolt+json-seq`, but add `application/vnd.neo4j.jolt` as an alias and remove `+json-seq` from the [Jolt documentation](https://neo4j.com/docs/http-api/4.2/actions/result-format/#_jolt). Existing Jolt clients keep working, and future clients won’t experience this issue.

* Leave the implementation as-is, but add language to the [Jolt documentation](https://neo4j.com/docs/http-api/4.2/actions/result-format/#_jolt) to explicitly warn that Jolt is not conformant to [RFC 7464](https://tools.ietf.org/html/rfc7464#section-2.2).

**Comment by technige** [comment]
Hi @johannessen. Thanks for raising this - we've had a look and you're absolutely right that the `+json-seq` suffix points to the incorrect generic format for Jolt. We have actually designed for newline-delimited json, so it sppears this mime type should in fact read `application/vnd.neo4j.jolt+x-ndjson`. We'll look at patching the server to correct the mime type.

**Comment by johannessen** [comment]
`+x-ndjson` is not a standard suffix, and is not likely to ever become one. According to [RFC 6838](https://tools.ietf.org/html/rfc6838#section-4.2.8), it SHOULD NOT be used.

Just `application/vnd.neo4j.jolt` should be fine!

**Comment by technige** [comment]
Alright, we'll continue to look into it.

Either way, it's likely that we'll introduce negotiation for the correct mime type, but retain deprecated support for the old one for a while.

**Comment by dotStart** [comment]
Thanks again for raising this issue!

We've addressed the problem in version 4.2.5. You should now be able to request both `application/vnd.neo4j.jolt` and `application/vnd.neo4j.jolt+json-seq` via the `Accept` header to get the correct formats respectively.

**Comment by johannessen** [comment]
That’s great news, thanks!

FYI, it seems that the [Jolt docs](https://neo4j.com/docs/http-api/current/actions/result-format/) haven’t yet been amended to reflect this change. (See also #12660 for another Jolt docs issue.)

**Comment by dotStart** [comment]
Sorry about that! Seems like our documentation deployment lagged a bit behind the actual product release. Everything should be updated with the new behavior now. :smile:
