### ISSUE TITLE
Jolt returns byte arrays in Hex rather than Base64 encoding

### ISSUE THREAD

**Issue by johannessen** [neo4j/neo4j#12660]
Jolt doesn’t return byte arrays in the format that is documented in the HTTP API docs.

### Steps

1. Create a node with a property containing the byte array `new byte[] { 0x46, 0x6f, 0x6f }` (= Foo).  
   (It doesn’t seem to be possible yet to create byte arrays via HTTP, so e. g. the Java Driver needs to be used.)
2. Run a Cypher query via HTTP returning that property in Jolt format.

### Expected

`{ "#": "Rm9v" }`

According to the [documentation on Jolt Types](https://neo4j.com/docs/http-api/4.2/actions/result-format/#_jolt_types), byte arrays are returned in Base64 encoding.

### Actual

`{ "#": "466F6F" }`

Byte arrays are returned in Base16 / hex encoding (which incidentally matches the [draft of the Jolt Specification v1](https://github.com/neo4j-drivers/neo4j-drivers.github.io/blob/master/jolt/jolt-specification.md#bytes)).

### Discussion

It is of particular importance that the server’s byte array implementation matches the docs, precisely because byte arrays are more difficult to create than literally any other Neo4j value. This also makes testing them more difficult for driver implementors than testing other values, and some might skip testing altogether, instead just trusting that the docs are accurate.

That said, it also means that this particular feature might not see much use. Given that, the simplest solution might be to change the documentation to match the actual behaviour of the server.

While hex takes up a whopping 50 % more space than Base64, my understanding is that byte arrays are not supposed to be used for storing large blobs anyway, so space may be less important here.

**Comment by gjmwoods** [comment]
Hi @johannessen. Again apologies for the delay in responding.

This is indeed an oversight in the docs and we have a fix for this in the docs currently going through the review process.

You're right that we don't currently expect large blobs to be stored/retrieved in the database. In hindsight, base64 would have been the more flexible choice should this change. We'll revisit this if it does.

Many thanks!

**Comment by gjmwoods** [comment]
Hi @johannessen. Updates to the docs have now been published.
