### ISSUE TITLE
Unable to access values from mapping after xml import

### ISSUE THREAD

**Issue by adnane-nemri** [neo4j/neo4j#12665]
Hello,
Posted the following issue on https://community.neo4j.com/t/unable-to-access-values-from-mapping-after-xml-import/31252 and was advised to make an issue out of it
Running v4.2 on ubuntu 20.10

I had code that ran 2 years ago on version 3.4 but doesn't anymore on version 4.2. The error message further below occured on several occasions. So I managed to rewrite some of it to go around but I'm stuck now on the rest. 
I am trying to match data from an animal disease ontology xml file to update some nodes.

here is some working code. It finds all nodes with a given property then matches all mappings.
it returns a mapping with 2 properties. this is expected behavior.

```
MATCH (n :Disease) where n.ADO_ID starts with 'MH'
CALL apoc.load.xml("ADO_edit2.xml",'', {}, true)
YIELD value
UNWIND value._RDF as rdf
UNWIND rdf as path
match (path) where path.`rdf:about` = n.ADO_ID
unwind path._Class as p2
WITH p2 as path2,
n as dis
CALL {
with path2
match (path2) where path2._type = 'subClassOf'
unwind path2._subClassOf as de2
match (de2) where de2._Restriction[0].`rdf:resource` = "hasCause"
return de2 as de3 
}
return de3, keys(de3), de3._type, dis LIMIT `10`
```
As i said, this is OK. It returns the following data (shown here as table):

> 

de3 | keys(de3) | de3._type | dis
-- | -- | -- | --
{"_type":Restriction,"_Restriction":[{"_type":onProperty,"rdf:resource":hasCause},{"_type":someValuesFrom,"rdf:resource":AG401}]} | [_type,_Restriction] | Restriction | {"ADO_ID":MH1,"name":Acanthocephalosis (Fish)}
{"_type":Restriction,"_Restriction":[{"_type":onProperty,"rdf:resource":hasCause},{"_type":someValuesFrom,"rdf:resource":AG399}]} | [_type,_Restriction] | Restriction | {"ADO_ID":MH1,"name":Acanthocephalosis (Fish)}
{"_type":Restriction,"_Restriction":[{"_type":onProperty,"rdf:resource":hasCause},{"_type":someValuesFrom,"rdf:resource":AG400}]} | [_type,_Restriction] | Restriction | {"ADO_ID":MH1,"name":Acanthocephalosis (Fish)}

however, if I try to return "de3._Restriction" ( or de3.`_Restriction`), which is a list, or any value nested in it, I get an error:

![](https://aws1.discourse-cdn.com/business4/uploads/neo4jcommunity/original/2X/0/021310ba26371c84739d2349c022d472df1f67bf.png)

I cannot access this mapping
I've had this problem with the same error for nearly all my import scripts that used to work previously. Some i could rewrite but this one is confusing me. How can i access this mapping?

Thanks

To reproduce, one could create a couple nodes (n :Disease) where n.ADO_ID starts with 'MH'
based off the xml file here: [ADO_edit.xml - Google Drive](https://drive.google.com/file/d/10TOHwVP39thJaPP7jYNBbolRT0nspaQ4/view?usp=sharing) 

Btw I tried cypher runtime=slotted  but no effect

**Comment by OliviaYtterbrink** [comment]
Hi @adnane-nemri
You are using `MATCH (variable) WHERE ...` with a bound variable that is not a Node, you should instead use `WITH variable WHERE ...`. `MATCH` should only be used when actually matching on nodes and not parts of a map.
Here's a rewrite of your query

```
MATCH (n :Disease) where n.ADO_ID starts with 'MH'
CALL apoc.load.xml("ADO_edit.xml",'', {}, true)
YIELD value
UNWIND value._RDF as rdf
UNWIND rdf as path
WITH n, path where path.`rdf:about` = n.ADO_ID
unwind path._Class as p2
WITH p2 as path2, n as dis
CALL {
with path2
with path2 where path2._type = 'subClassOf'
unwind path2._subClassOf as de2
WITH de2 where de2._Restriction[0].`rdf:resource` = "hasCause"
return de2 as de3
}
return de3, keys(de3), de3._type, de3._restriction, dis LIMIT 10
```

Hope this explains things and helps you with your other queries as well.
