### ISSUE TITLE
Knn search for images embeddings

### ISSUE THREAD

**Issue by Rtut654** [neo4j/neo4j#12666]
Hey!  I'm curious whether it is possible to store image embeddings (256-float each) in neo4j? Basically, I'm interested in searching for nearest neighbors in embedding database, so the question is for both store and search parts. In documentation I found necessary operations only for 3d point data type, so multidimensional data is still unavailable?

**Comment by parnmatt** [comment]
Just scanning through some old issues. For future searchers, this functionality was added in 5.11 as beta, and 5.13 as general availability.
