### ISSUE TITLE
Read query throws a DatabaseException only on Neo4j enterprise version

### ISSUE THREAD

**Issue by horak90** [neo4j/neo4j#12675]
Hello,

I would like to declare a potential bug for Neo4j 4.1.5-enterprise. 

When I try to run the following query: `MATCH (n:NODE) WHERE n.id = $left OR n.id = $right RETURN (n);` I get a DatabaseException: `Index cursor cannot have transaction state with values and without values simultaneously`. This happens only for the enterprise version, the community version runs the query without any error.

To reproduce the issue, I created a small java application that can be used. [How to reproduce the bug](https://github.com/horak90/neo4j-transaction-error)

Thank yoy for your help

- Neo4j version: 4.1.5-enterprise (docker image)
- Operating system: macOS/Ubuntu
- Driver: Neo4j java driver 4.1.1

**Comment by mnd999** [comment]
Thanks for the report, as a workaround I would suggest prefixing your query with `CYPHER RUNTIME=slotted`. We will look into the bug and let you know when we have a fix.
