### ISSUE TITLE
Merge no longer prevents duplication during race condition on Neo4j 4.2.2

### ISSUE THREAD

**Issue by fabio-s-franco** [neo4j/neo4j#12674]
We have upgraded our Neo4j instances from 4.1.3 to 4.2.2 and since then MERGE no longer prevents duplication of Nodes while concurrent queries are being executed. It is as if the MERGE operation can no longer hold a write lock with the specified condition.

Example query that trigger the problem:

```
MERGE (s:Tenant:Service{identity:'683b0e50-debf-4e69-b3df-8b22b4068f4c'})
SET s.name = 'myservice'
WITH *
UNWIND [{ identity: '94b96bd1-63f1-4f11-876a-d36ddc23d42d', pipelineName: 'pipeline1' }, { identity: '1098ae63-0148-48b7-a3a1-97706c47f8a5', pipelineName: 'pipeline2' }, { identity: 'a17d96f5-53e9-4648-a56b-3cb280f0f252', pipelineName: 'pipeline3' }]  as pipeline 
MERGE (s)-[:provides]->(p:Tenant:Pipeline{identity:pipeline.identity})
SET p.name = pipeline.name
WITH *
RETURN p
```
I am not sure what changed, but since our upgrade it can be consistently reproduced in every single attempt. If we try to reproduce using 4.1.3, it never happens. We have a quick way to launch a clean environment with either of the versions of Neo4j. And for our scenario it's not possible to create an index at the moment these queries are executed and until now, it hasn't been a problem.

The source of the queries are replicated NodeJS applications in a Kubernetes clusters. We run a standalone instance of Neo4j so all replicas execute those queries to the same Neo4j core server.

### Additional information:

- Neo4j version: 4.2.2 Enterprise
- Operating system: neo4j enterprise docker image
- API/Driver: javascript driver. Tried with both 4.0.2 and 4.2.2 versions.

## **Steps to reproduce**:
Unfortunately there is no easy way to provide the reproducible environment as it involves our code and infrastructure. I am assuming Neo4j team is able to create parallel execution scenarios. Using the provided query should be enough to reproduce as we can reproduce it in a blank database.

Please let me know if there is anything else that could help determine the problem or if you're having issues to reproduce the problem.

### Expected behavior:
Merge prevents the duplication of the Pipeline node that is created in this section of the cypher query
`MERGE (s)-[:provides]->(p:Pipeline{identity:pipeline.identity})`

### Actual behavior
Usually end up having on set of duplicated Pipeline nodes (same value for identity property)

**Comment by inmost-light** [comment]
Hello @fabio-510 ,

I think this is working as expected and I can reproduce duplication on both 4.1.3 and 4.2.2.

On an empty database, initial `MERGE (s:Tenant:Service{identity:'683b0e50-debf-4e69-b3df-8b22b4068f4c'})` might create duplicates. To avoid that you _must_ add a uniqueness constraint.

The second `MERGE` acquires lock on the `s` node, but that doesn't help with duplicate Pipelines if `s` itself is already duplicated.

However if `(s:Tenant:Service [...])` node existed in the graph prior to query execution, the first `MERGE` would not create a new node, and the subsequent `MERGE` would acquire lock on the same node, thus avoiding duplication.

So if you have any constraints or existing data in your 4.1.3 database, that might explain the different behavior you see.

**Comment by fabio-s-franco** [comment]
Hi @inmost-light , thanks for your reply. As I mentioned and it may have not been clear, I am able to spawn a fresh environment (with a single command with a CLI we developed) with the neo4j version of my choice, this means, that in about 10 minutes I am able to create an environment that is roughly composed of the following steps:

1 - Create Kubernetes cluster
2 - Setup all 3rd party services (neo4j, redis, rabbitmq, etc) required as foundation in a completely clean state.
3 - Deploy our solution microservices which usually starts with 2 or 3 replicas. Each replica announces itself and the first thing they do is tell who they are and which pipelines they contain (metadata, don't represent their instances, so they generate exactly equal cypher queries between them) <- Cypher query runs here.
4 - Perform data bootstrap (creates indexes among other things)
5 - Perform data migrations

So, the I can reproduce the exact same experiment many times and I did. With 4.1.3, data duplication NEVER happens. With 4.2.2 data duplication ALWAYS happens.

Maybe there is a different planner behavior that could explain this, but I can guarantee the conditions are exactly the same for both neo4j versions. We can schedule a call so you can take a closer look, but I suppose this wouldn't be really necessary.

The s node doesn't get duplicated in my test scenario, just the Pipeline node. It was my understanding, that the write lock would prevent both the first merge and the second merge from creating duplicates, based on the following assumptions (please enlighten me, if it's not too much to ask):

1 - The merge uses the filter specified in it to determine if it's going to be an "ON CREATE" or an "ON CHANGE" operation. In order for it to make the correct choice it needs to prevent dirty reads on the nodes with the specified labels and property value (in my case, identity). If there is a write operation happening on any nodes containing these labels, then the merge needs to wait for the write lock to be released to assess if the condition will cause a create or change.

2 - If the first merge successfully safeguards only a single service node is created among all replicas that try to do it, then my second assumption would be that the second MERGE would consider the entire pattern as the criteria to CREATE or CHANGE and since I never get duplicated **s** nodes, then I would also expect I don't get duplicated **p** nodes, based on the same rationale of my first assumption. The only thing that makes me question such a capacity would be to prevent dirty reads which involves relationships and entire patterns. Seems a bit too tricky to prevent database deadlocks.

Now, it is still unclear to me the scope of the write lock as I read around. I could not find any clear documentation that actually explains it in more detail. But, if we consider a non-indexed property, the only way I see that the write lock actually is actually broad enough to the point that it prevents label-wide writes, it would mean that for operations like MERGE, it would require a full scan every time it tries to do merge based on a non-indexed property.

I do understand that the unique constraint is the only safeguard that prevents data duplication with the keys of choice. BUT, I would also expect that the MERGE would be reliable, regardless of setup. Mine is not the only scenario where a unique constraint may not be present (which I could tweak to prevent it, but that's not exactly the point of this bug report). If I cannot trust MERGE to deal with concurrency, then how am I going to use it on scenarios where I cannot anticipate which property will be used as criteria? This is often common, specially on schema less databases. It gives freedom to design highly configurable systems and in some cases, that use the user's choice to determine what criteria to use. To fix a scenario like this would be to index everything which we know is not a good idea.

So, my main point is. If this is really the case, then MERGE really can't guarantee it fulfills its promise. As my scenario is not even a very scaled one, they are really 2 to 3 concurrent queries. In scenarios with very intense usage and where indexes cannot be anticipated, MERGE would not be safe to use. This fact, needs to be clearly documented on [MERGE](https://neo4j.com/docs/cypher-manual/current/clauses/merge/) section, as the headline statement can be very misleading:

> The MERGE clause **ensures** that a pattern exists in the graph. Either the pattern already exists, or it needs to be created.

If my the first MERGE in my query would be guaranteed, then the second merge would as well. Again, it's very odd that I can consistently prove the different behavior on the two different neo4j versions.

If anything, a disclaimer should be in good order in the documentation stating the possible side-effects of merge on certain scenarios.

Thanks again for taking the time to have a look at this.

**Comment by inmost-light** [comment]
@fabio-510 

> Maybe there is a different planner behavior that could explain this, but I can guarantee the conditions are exactly the same for both neo4j versions.

It would be useful to compare the output of `EXPLAIN` to see if there are any differences.

> The s node doesn't get duplicated in my test scenario, just the Pipeline node. It was my understanding, that the write lock would prevent both the first merge and the second merge from creating duplicates, based on the following assumptions (please enlighten me, if it's not too much to ask):

`MERGE` only locks nodes that are part of the pattern and were matched earlier in a query. Variable `s` is just introduced in the first `MERGE`, so we don't have anything to lock at that point. It really works just like a combination of `OPTIONAL MATCH` and `CREATE`.

You should see `LockNodes` in a plan description returned by `EXPLAIN`, that's when locking happens.

> Thanks again for taking the time to have a look at this.

Thanks for reporting. If you have access to the customer support, I suggest you raise a ticket there. Should get more eyes on the issue.

**Comment by fabio-s-franco** [comment]
Thanks again @inmost-light . Sorry for taking so long, had other things to attend to. Anyways. Here it goes:

> It would be useful to compare the output of EXPLAIN to see if there are any differences.

There is only two differences in the explain for both explains:
1 - Different versions for cypher/planner (4.1 vs 4.2)
2 - The Filter@elements step has its conditional clauses order swapped between the two versions:
  - In 4.1: `s:Service AND s.identity = $autostring_0`
  - In 4.2: `s.identity = $autostring_0 AND s:Service`

Plan on 4.1 (don't mind the rows, having no data issues the same plan):
![plan](https://user-images.githubusercontent.com/37698530/109717481-d5ee5d00-7b84-11eb-945f-966a18560e56.png)

> You should see LockNodes in a plan description returned by EXPLAIN, that's when locking happens.

Indeed, I see LockNodes on the right side (for s and pipeline variables, which are introduced in combination further down).
Would begin the query with a MATCH (on s) do any good in that sense?

> Thanks for reporting. If you have access to the customer support, I suggest you raise a ticket there. Should get more eyes on the issue.

Unfortunately no, I am under startup plan, which doesn't include support. I will leave this ticket open. Maybe I can eventually figure out what's causing the different behaviors or a future version prevents the problem from happening. In the mean time I worked around the problem, which is ok for now, but his may become a problem again on scenarios as I described where indexes cannot be predicted beforehand.

At this point my main goal with this issue is to report a potential problem and hopefully provide insight with people with similar problems.

**Comment by inmost-light** [comment]
@fabio-510 
> Indeed, I see LockNodes on the right side (for s and pipeline variables, which are introduced in combination further down).

It's only for `s` actually. The first line of `LockNodes` box shows you all currently available symbols, the second line shows nodes that are being locked. And if we actually end up in that branch during query execution, that means `pipeline` is currently `NULL`.

> Would begin the query with a MATCH (on s) do any good in that sense?

I don't think so, it would produce the same `NodeByLabelScan`, but you would have to do the branching `MERGE` logic by hand somehow.

> Unfortunately no, I am under startup plan, which doesn't include support. I will leave this ticket open. Maybe I can eventually figure out what's causing the different behaviors or a future version prevents the problem from happening. In the mean time I worked around the problem, which is ok for now, but his may become a problem again on scenarios as I described where indexes cannot be predicted beforehand.

Good that it's not blocking for you, because I've tried a few things and still can't reproduce your 4.1.3 behavior. I've opened and internal ticket for us to improve `MERGE` documentation at least, so we'll keep this issue open until that is done.

**Comment by sherfert** [comment]
We have added a paragraph to our [documentation](https://neo4j.com/docs/cypher-manual/current/clauses/merge/#query-merge-introduction) to improve awareness of this behavior.
