### ISSUE TITLE
Wrong result for cypher query

### ISSUE THREAD

**Issue by matiasmorant** [neo4j/neo4j#12673]
I discovered a cypher query that returns wrong results in Neo4j versions `4.2.x`, and returns the correct result in Neo4j versions `4.1.x`

**Neo4j Version:** `4.2.x`
**Operating System:** Windows 10
**API:** Cypher

### Steps to reproduce
1. create 3 nodes
```
CREATE (:person)
CREATE (:person)
CREATE (:person)
```
2. execute the following query (the first  `CALL` subquery is only a complex way of returning `0` for every node)

```
MATCH (x) CALL {
    WITH x CALL {
        WITH x RETURN 0 AS y
        UNION
        WITH x RETURN 0 AS y
    } WITH y LIMIT 1 RETURN y
} RETURN id(x), y
```
### Expected behavior
the query above should return 
```
╒═══════╤═══╕
│"id(x)"│"y"│
╞═══════╪═══╡
│0      │0  │
├───────┼───┤
│1      │0  │
├───────┼───┤
│2      │0  │
└───────┴───┘
```

### Actual behavior

The above query returns
```
╒═══════╤═══╕
│"id(x)"│"y"│
╞═══════╪═══╡
│0      │0  │
├───────┼───┤
│1      │0  │
└───────┴───┘
```
### HINTS
- in neo4j versions `4.1.x`, expected behavior matches actual behavior
- it doesn't matter how many nodes the graph has, the query will always return only 2 rows

**Comment by mnd999** [comment]
Thanks for the report, we're looking into it in conjunction with https://github.com/neo4j/neo4j/issues/12669

**Comment by OliviaYtterbrink** [comment]
A workaround for this issue would be to prepend the query with `CYPHER runtime=slotted` till the bug has been fixed.

**Comment by LinneaAndersson** [comment]
@matiasmorant Thanks for reporting this. The bug has been fixed and will be rolled out with the next update. Until then you can use the workaround @OliviaYtterbrink suggested.

I'll close this now but don't hesitate to reopen or open a new issue if there are any other issues.

Regards,
Linnéa
