### ISSUE TITLE
Apple Silicon support - jna version bump

### ISSUE THREAD

**Issue by tuftedocelot** [neo4j/neo4j#12676]
## Feature request template

I'd like to (officially, quasi-officially?) run neo4j on Apple Silicon machines

**Describe the solution you'd like**
JNA 5.7.0. recently released, has support on Apple Silicon machines. I've run APOC and neo4j instances with the updated library version to seemingly no ill effect. https://github.com/java-native-access/jna/blob/master/CHANGES.md

**Describe alternatives you've considered**
Not running neo4j, but that runs counter to this feature request 😄 

**Additional context**
I'm assuming it isn't as simple as only cranking the JNA dependency version number. And that Apple Silicon is perhaps too niche at this point to consider aarch64 a supported platform, macOS support notwithstanding

**Comment by klaren** [comment]
Hello,

We can certainly bump the version and this will be done in the next minor release of Neo4j. As for having official support, currently, we have no plans. That being said, I still think we can strive to have as wide support as possible so if you find anything else that needs to be updated please let us know.

**Comment by tuftedocelot** [comment]
Will do! I appreciate the time and response 👍
