### ISSUE TITLE
debug.log warnings about dbms.memory.heap.max_size and dbms.memory.heap.initial_size when they are actually provided

### ISSUE THREAD

**Issue by cartwrightian** [neo4j/neo4j#12672]
- Neo4j version: 4.2.1
- Operating system: macos 10.15.7
- API/Driver: java embedded
- **Steps to reproduce**

DatabaseManagementService managementService = new DatabaseManagementServiceBuilder( graphFile ).
setConfig(ExternalSettings.initial_heap_size, "100m").
setConfig(ExternalSettings.max_heap_size, "200m").
build();
GraphDatabaseService graphDatabaseService = managementService.database(DEFAULT_DATABASE_NAME);

- Expected behavior
no warnings in debug.log

- Actual behavior
Warnings in debug.log
2021-02-08 17:34:55.431+0000 WARN  [o.n.k.i.JvmChecker] The dbms.memory.heap.max_size setting has not been configured. It is recommended that this setting is always explicitly configured, to ensure the system has a balanced configuration. Until then, a JVM computed heuristic of 4294967296 bytes is used instead. Run `neo4j-admin memrec` for memory configuration suggestions.
2021-02-08 17:34:55.432+0000 WARN  [o.n.k.i.JvmChecker] The dbms.memory.heap.initial_size setting has not been configured. It is recommended that this setting is always explicitly configured, to ensure the system has a balanced configuration. Until then, a JVM computed heuristic of 268435456 bytes is used instead. Run `neo4j-admin memrec` for memory configuration suggestions.

Confusingly JvmChecker.java checks for jvm options ( -Xmx and -Xms) and not for the config values given in the warning message, maybe error message is using wrong constants from ExternalSettings.java or should check against provided config.

**Comment by klaren** [comment]
Hello @cartwrightian and thanks for reporting.

This behavior is expected. All settings in `ExternalSettings` are read by our startup scripts and passed into the JVM that Neo4j launches, and have no effect on an embedded deployment. If you don't use the Neo4j service scripts you will have to specify `-Xmx` and `-Xms` yourself. Those values cannot be changed after the JVM is started so the best thing we can do is warn about it.

**Comment by cartwrightian** [comment]
Thanks for responding, that makes sense, however I'm not sure the warning messages quite hit the mark - I am setting those values but I get the warning message.

**Comment by klaren** [comment]
I can see that. What do you think about:

> The max heap memory has not been configured. It is recommended that it is always explicitly configured, to ensure the system has a balanced configuration. Until then, a JVM computed heuristic of %d bytes is used instead. If you are running neo4j server, you need to configure `dbms.memory.heap.max_size` in `neo4j.conf`. If you are running neo4j embedded, you have to launch the JVM with `-Xmx` set to a value. You can run `neo4j-admin memrec` for memory configuration suggestions.

And similar to the initial heap value.

**Comment by cartwrightian** [comment]
> 
> 
> I can see that. What do you think about:
> 
> > The max heap memory has not been configured. It is recommended that it is always explicitly configured, to ensure the system has a balanced configuration. Until then, a JVM computed heuristic of %d bytes is used instead. If you are running neo4j server, you need to configure `dbms.memory.heap.max_size` in `neo4j.conf`. If you are running neo4j embedded, you have to launch the JVM with `-Xmx` set to a value. You can run `neo4j-admin memrec` for memory configuration suggestions.
> 
> And similar to the initial heap value.

Yes, that makes things clear. Thanks!
