### ISSUE TITLE
Optional match with allShortestPaths, list comprehension, and head results in 'Expected NO_VALUE to be a list' Neo4j 4.1.4+

### ISSUE THREAD

**Issue by MichaelCDormann** [neo4j/neo4j#12677]
I discovered that using an `OPTIONAL MATCH` with `allShortestPaths` and then wrapping a `head` around some list comprehension on the result eventually fails when the `OPTIONAL MATCH` does not produce a path. After about the 10th time the query is ran the result is a `Neo.ClientError.Statement.TypeError: Expected NO_VALUE to be a list` error from then on. If you modify the query in any way it works again up until about the 10th time it's ran, and then the same error happens from then on.

**Neo4j Version:** 4.1.4, 4.1.6, 4.2.3
Initially found on 4.1.4. Reproduced in Neo4j Desktop with local database versions 4.1.6 and 4.2.3 as well.

### Steps to reproduce
1. Run this query in Neo4j browser
```
MATCH (movie:Movie{title:'The Matrix'})
MATCH (actor:Person{name:'Tom Hanks'})
OPTIONAL MATCH path = allShortestPaths((movie)<-[*1..]-(actor))
RETURN movie, actor, head([r IN relationships(path) WHERE type(r)='ACTED_IN' | r]) AS breaks
```
2. Refresh the query about 10 times

### Expected behavior
A result is always returned.

### Actual behavior
A result is return the first few times, then the error `Neo.ClientError.Statement.TypeError: Expected NO_VALUE to be a list` happens every time after that.

### More Examples
Feels related to a previous issue.
https://github.com/neo4j/neo4j/issues/12601

This issue has a similar work around: break up function and list comprehension steps. Doing it this way doesn't seem to produce the error after many more tries.
```
MATCH (movie:Movie{title:'The Matrix'})
MATCH (actor:Person{name:'Tom Hanks'})
OPTIONAL MATCH path = allShortestPaths((movie)<-[*1..]-(actor))
WITH movie, actor, relationships(path) as rels
WITH movie, actor, [r IN rels WHERE type(r)='ACTED_IN' | r] as rels
RETURN movie, actor, head(rels) AS breaks
```

**Comment by pontusmelke** [comment]
Thanks @MichaelCDormann for reaching out and for the exemplary issue description. We have verified and fixed the issue and a fix should be in the next point release. As a temporary fix you can either do it the way you propose or by appending `CYPHER runtime=slotted expressionEngine=interpreted` to your query.

I'll leave this issue open until a new release is out.

**Comment by mnd999** [comment]
Closing this issue as it appears it was fixed some time ago.
