### ISSUE TITLE
Add lastBookmark method in org.neo4j.graphdb.event.TransactionData

### ISSUE THREAD

**Issue by elR1co** [neo4j/neo4j#12680]
## Feature request

**Is your feature request related to a problem? Please describe.**

I would like to create a kernel extension, implementing `TransactionEventListener`, to be able to perform actions in before or after commit phases. I would like to create a similar extension to Neo4j streams, but with Rabbitmq as a sink instead of Kafka. In the message I would like to send to Rabbitmq, I would like to include the bookmark related to the given transaction in the before/after commit phase. I don't see anything in the kernel API which provides the transaction related bookmark.

**Describe the solution you'd like**
Something like a method `lastBookmark` in `org.neo4j.graphdb.event.TransactionData` object.

**Additional context**
Of course, the feature is needed in causal cluster use context. I would like Rabbitmq consumers use the bookmark in a `READ` transaction to retrieve the latest data modified by the related `WRITE` transaction.

**Comment by elR1co** [comment]
No feedback so far. Does this feature make sense ?

**Comment by PetrJanouch** [comment]
Hi @elR1co,
I am really sorry, we somehow missed this feature request and I just rediscovered it during some clean up.
We are not planning to add such an API.
