### ISSUE TITLE
StackOverFlowError occurs when reducing a List<List<Node>>

### ISSUE THREAD

**Issue by hagen666** [neo4j/neo4j#12683]
I wanna merge some list like this:

match p = (n)-[*3..3]-(m) where id(n)=164 
with collect(nodes(p)) as set1
with reduce(c = [], x in set1| c + x) as fromNodes
unwind fromNodes as x return x

when size of set1 increasing, more than 15000, stackoverflow occurs, the stack is at org.neo4j.values.virtual.ListValue$ConcatList.size(ListValue.java:442) ~[neo4j-values-4.2.3.jar:4.2.3].

I think the size of function stack should not depend on the dataset. 

- Neo4j version: 4.2
- Operating system: Centos 7

**Comment by hagen666** [comment]
The following statement can reproduce the error:

unwind range(0,15000) as xxx
with collect([xxx]) as set1 
with  reduce(c = [], x in set1| c + x) as fromNodes 
unwind fromNodes as x return x

**Comment by mnd999** [comment]
I agree, the function stack should not depend on the dataset. This looks like a bug, we'll investigate further.
