### ISSUE TITLE
Neo4J Scala 2.13 Support

### ISSUE THREAD

**Issue by Dacit** [neo4j/neo4j#12687]
Neo4j currently doesn't support scala 2.13 (the cypher evaluator breaks):
```
java.lang.NoClassDefFoundError: scala/Serializable
  at org.neo4j.cypher.internal.evaluator.SimpleInternalExpressionEvaluator.evaluate(SimpleInternalExpressionEvaluator.scala:42)
  at org.neo4j.cypher.internal.evaluator.SimpleExpressionEvaluator.evaluate(SimpleExpressionEvaluator.java:44)
```
This reflects in other issues as well: #12585

Is `2.13` support planned? For which release? Is it going to take as long as the 2.11->2.12 upgrade (#8832)?

**Comment by mnd999** [comment]
Thanks for the request, Scala 2.13 is  certainly something we've been discussing but I don't have an answer for when just now.

**Comment by jotomo** [comment]
@Dacit looks like v. 5.x uses Scala 2.13:
https://neo4j.com/docs/upgrade-migration-guide/current/version-5/migration/breaking-changes/
(Seems these days, an initial acknowledgement of an issue is the most you get on this repo).

**Comment by mnd999** [comment]
Correct, yes we did this as part of the 5.0 upgrade.
