### ISSUE TITLE
failing query

### ISSUE THREAD

**Issue by matiasmorant** [neo4j/neo4j#12682]
I discovered a cypher query that fails in Neo4j versions 4.2.x, and runs in Neo4j versions 4.1.x

Neo4j Version: 4.2.3
Operating System: Windows 10
API: Cypher

## Steps to reproduce

1. create 2 nodes

`CREATE (:person)-[:knows]->(:person)`

2. execute the following query
```
MATCH (x) CALL {
    WITH x RETURN x AS y
} WITH y AS z CALL {
    WITH z RETURN z AS w
    UNION
    WITH z MATCH (z)-[]->(w) RETURN w
} RETURN w
```
## Expected behavior
the query should return a result

## Actual behavior
The query fails with  `ERROR: Neo.DatabaseError.Statement.ExecutionFailed`

**Comment by arnefischereit** [comment]
Hi @matiasmorant, I just ran that example you have provided on an empty database using the [docker images](https://hub.docker.com/_/neo4j/) (to make sure it has nothing to do with my environment) of the versions

- 4.2.3
- 4.2.2
- 4.2.1
- 4.1.7

For all versions, the query returns
```
╒═══╕
│"w"│
╞═══╡
│{} │
├───┤
│{} │
├───┤
│{} │
└───┘
```
of which two rows correspond to the part of the query before the `UNION` and one row to the part after.

**Comment by arnefischereit** [comment]
@matiasmorant, we would like to close this issue.
If you still experience this problem, we would need a reproducible test case to proceed.

**Comment by matiasmorant** [comment]
I was experiencing this last time I checked. I changed the query I was using to avoid this error. Feel free to close.

**Comment by arnefischereit** [comment]
Alright. Thanks for the feedback.
Don't hesitate to reopen or open a new issue once you encounter such a problem again.
