### ISSUE TITLE
Importing data fails due to non-valid typeId, 53 

### ISSUE THREAD

**Issue by nhziga** [neo4j/neo4j#12681]
- Context: I am importing bitcoin blockchain to neo4j using this tutorial: https://neo4j.com/blog/import-bitcoin-blockchain-neo4j/
- Neo4j version: 3.5.14 *and* 3.5.26, both community version
- Operating system: Ubuntu 18.04.4 LTS
- API/Driver: openjdk-11-jre-headless
- Importing bitcoin block `0000000000000000000abe8a96e397d16173809138ca1b327416386d5cd2f8e1`, transaction `43202883c4e9721c522330b1304bd4c6ee98e85c63991bbde62f721137675a17`
- Expected behavior: Should import the block
- Actual behavior: Fails with
```
2021-02-25 06:34:57.886+0000 ERROR Client triggered an unexpected error [Neo.DatabaseError.General.UnknownError]: org.neo4j.io.pagecache.CursorException: Unable to read generic key slot due to non-valid typeId, 53 | GB+Tree[file:/home/neo4j/data/databases/graph.db/schema/index/native-btree-1.0/24/index-24, layout:GenericLayout[version:0.5, identifier:5643935348791705600, fixedSize:false], generation:8513/8515], reference fc38e0cf-57bd-49cc-991e-066e4215086e.
```
- Server: 32 core, 90g ECC ram

- Additional info:
This is the query that fails:
```
MATCH (block :block {hash:'0000000000000000000abe8a96e397d16173809138ca1b327416386d5cd2f8e1'})-[:coinbase]->(coinbase :output:coinbase)
MERGE (tx:tx {txid:'43202883c4e9721c522330b1304bd4c6ee98e85c63991bbde62f721137675a17', version:1, locktime:0, size:191})
WITH tx, block, coinbase
SET tx.segwit='0001'

        FOREACH (input in [{vin:0, index:'5145221406ba136b662ceeda4ad9d738b998d41282c9e9381871cfc024e40a9d:0', scriptSig:'', sequence:'4294967295', witness:'0247304402203ed4a587273774abb9a30441cb8554544440ecabef41844e9eae36448e6beb93022055829ebba8a71b6b610ddb7cd7672199371e3a4e9df730ef193e88e00e28154301210323bdef5531a24a0775662ce2ff4f899e66586b0a8c0c6e81dd2ae50b8f04bb79'}] |
                MERGE (in :output {index: input.index})
                MERGE (in)-[:in {vin: input.vin, scriptSig: input.scriptSig, sequence: input.sequence, witness: input.witness}]->(tx)
        )

        FOREACH (output in [{vout:0, index:'43202883c4e9721c522330b1304bd4c6ee98e85c63991bbde62f721137675a17:0', value:3242684, scriptPubKey:'001464dcf2ed077d1892e44a3821277cb2f0d5a21ba1', addresses:'bc1qvnw09mg805vf9ez28qsjwl9j7r26yxapznjxuw'}] |
                MERGE (out :output {index: output.index})
                MERGE (tx)-[:out {vout: output.vout}]->(out)
                FOREACH(ignoreMe IN CASE WHEN output.addresses <> '' THEN [1] ELSE [] END |
                        MERGE (address :address {address: output.addresses})
                        MERGE (out)-[:locked]->(address)
                )

                MERGE (out)-[:in]->(existing)
                ON CREATE SET
                        out.value= output.value,
                        out.scriptPubKey= output.scriptPubKey
                ON MATCH SET
                        out.value= output.value,
                        out.scriptPubKey= output.scriptPubKey,
                        existing.fee = existing.fee + output.value

        )

MERGE (tx)-[:inc {i:25}]->(block)

WITH tx
MATCH (i :output)-[:in]->(tx)
WITH tx, sum(i.value) - 3242684 as fee
SET tx.fee=fee
RETURN fee
```

**Comment by emmaholmbergohlsson** [comment]
Hi @nhziga , 
Thanks for reporting this, it seems like you might have run into a problem we haven't seen before. We need some more info to be able to start investigating this.

Does this happen every time you try to import?, and does it fail on the same thing?
Can you provide us with the entire stacktrace of the error?
Some more information about the affected index would also be useful, run `CALL db.indexes()` and the index with id 24 is the interesting one.

**Comment by nhziga** [comment]
Hi @emmaholmbergohlsson,

This happens every time I try to import this specific transaction (`43202883c4e9721c522330b1304bd4c6ee98e85c63991bbde62f721137675a17`) in this specific block (`573479`) in this specific file (`blk01615.dat`), starting at position `37197215`.

```
GraphAware\Neo4j\Client\Exception\Neo4jException: org.neo4j.io.pagecache.CursorException: Unable to read generic key slot due to non-valid typeId, 53 | GB+Tree[file:/home/neo4j/data/databases/graph.db/schema/index/native-btree-1.0/24/index-24, layout:GenericLayout[version:0.5, identifier:5643935348791705600, fixedSize:false], generation:8517/8519] in /home/neouser/Documents/projects/bitcoin-to-neo4j-2/vendor/graphaware/neo4j-php-client/src/Connection/Connection.php:119
Stack trace:
#0 /home/neouser/Documents/projects/bitcoin-to-neo4j-2/vendor/graphaware/neo4j-php-client/src/Client.php(67): GraphAware\Neo4j\Client\Connection\Connection->run('\n\t\tMATCH (block...', Array, NULL)
#1 /home/neouser/Documents/projects/bitcoin-to-neo4j-2/cyphertx.php(216): GraphAware\Neo4j\Client\Client->run('\n\t\tMATCH (block...')
#2 /home/neouser/Documents/projects/bitcoin-to-neo4j-2/main.php(372): cypherTx(Object(GraphAware\Neo4j\Client\Client), '010000000001019...', 25, '000000000000000...')
#3 {main}
```

Index 24:
```
╒════════════════════════════╤═══════════╤════════════╤════════════╤════════╤══════════════════════╤══════════╤══════════════════════════════════════╤════╤════════════════╕
│"description"               │"indexName"│"tokenNames"│"properties"│"state" │"type"                │"progress"│"provider"                            │"id"│"failureMessage"│
╞════════════════════════════╪═══════════╪════════════╪════════════╪════════╪══════════════════════╪══════════╪══════════════════════════════════════╪════╪════════════════╡
│"INDEX ON :address(address)"│"index_24" │["address"] │["address"] │"ONLINE"│"node_label_property" │100.0     │{"version":"1.0","key":"native-btree"}│24  │""
```

If there is anything else I can provide please let me know.

**Comment by emmaholmbergohlsson** [comment]
@nhziga 
The error you are seeing occurs when reading something that has been imported in an earlier step.
One option is of course to start over from the beginning, but that shouldn't be necessary.

So I think that what we should do is rebuild the index instead.
Indexes are auxiliary structures, they can be recreated from the rest of the data in the database.
Since the error occurs when reading from `index_24`, recreating it should make it possible for you to continue your import.

So you need to run
* `DROP INDEX index_24`
* `CREATE INDEX FOR (n:address) ON (n.address)`
and then you need to wait for the index to be populated, for example with the `db.awaitIndexes()` procedure.

But I see you are still on 3.5 so the syntax should be `DROP INDEX ON :address(address)` and `CREATE INDEX ON :address(address)`

After that you should be able to import the transaction that failed

**Comment by emmaholmbergohlsson** [comment]
@nhziga Closing this issue since a solution has been provided and we haven't heard anything in a while. If for some reason this didn't solve your problem, then please reopen this issue again.
