### ISSUE TITLE
Some query can make database offline

### ISSUE THREAD

**Issue by cuigm85** [neo4j/neo4j#12699]
- Neo4j version: 4.2.3 and 4.2.4
- Operating system: Linux (RedHat 8)
- API/Driver: cypher-shell
- **Steps to reproduce**

I executed the query below, and the database was down. There are a lot of  `SentenceToDo` node (more than 100,000,000) with `sentence` property.
```
call apoc.periodic.commit("
  MATCH (n:SentenceToDo)
  WITH n LIMIT $limit
  REMOVE n:SentenceToDo
  SET n:Sentence
  WITH collect(n) as ns
  CALL {
    WITH ns
    UNWIND ns AS n
    WITH n, split( n.long_sentence, ' ') AS words
    WITH n,words, range(0,size(words)-1) AS ids
    UNWIND ids AS id
    MERGE (word:Word{vocab:words[id]})
    MERGE (n)<-[:WORD_OF{id:id}]-(word)
    RETURN count(*) AS temp
  }
  CALL {
    MATCH (n:SentenceTodo)
    RETURN count(*) AS cnt
  }
  RETURN cnt
", {limit:20000});

```
At first it works fine, but when I return office next day the database was offline with

`Database "database_name" is unavailable, its status is "offline."` message.

- Expected behavior

If a query has problem, it should be rollback and return an error message.

- Actual behavior

The database crashed and can not use it anymore.

Some error output:

```
updates, executions, runtime, batches, failedBatches, batchErrors, failedCommits, commitErrors, wasTerminated
61838315847, 561, 3121, 562, 1, {`Index -3 out of bounds for length 600`: 1}, 0, {}, FALSE

```

**Comment by sherfert** [comment]
@cuigm85 

Sorry that no one replied to your issue.

4.2 is no longer supported. Can you reproduce the issue with versions 4.4 or 5.9?

* If you can, could you please provide a complete stacktrace from the `debug.log` file, if available.
* A sample dataset on which the issue is reproducible would also be helpful.

**Comment by mnd999** [comment]
We have not heard anything back on this issue for some time so will close for now. If it's still a problem, please feeel free to reopen and provide the details requested above.
