### ISSUE TITLE
in Security can I DENY TRAVERSE except particular nodes

### ISSUE THREAD

**Issue by NAVEENKUMARSKPN** [neo4j/neo4j#12693]
Hi Team !!

I have a use case where i have to deny traverse except a particular nodes
lets say i have a nodes Customer A, Customer B and so on here i have to grant traverse only to customer A other than Customer A i have to deny Traverse I dont even know other customer in this case how will grant permission

is there any option like Deny Traverse except Nodes CustomerA

1. Creating role as copy of admin
2. I have to deny traverse except Node CustomerA

This is how I need to do it

Please help me on this
Thanks !!

**Comment by mnd999** [comment]
Have you tried using GRANT instead of deny? Create a role that needs just CustomerA and only grant TRAVERSE on customer A to that role. 

If you are creating a copy of admin, you would need to REVOKE GRANT to remove the existing blanket MATCH permissions.

**Comment by mnd999** [comment]
As we have not heard anything back on this for some time, I will close for now. Feel free to reopen it if you are still having problems.
