### ISSUE TITLE
Failed to invoke procedure gds.alpha.scc.write: Caused by: java.lang.ArrayIndexOutOfBoundsException: -1

### ISSUE THREAD

**Issue by strangeman375** [neo4j/neo4j#12707]
Hi.
I've got an error:
Failed to invoke procedure gds.alpha.scc.write: Caused by: java.lang.ArrayIndexOutOfBoundsException: -1

Version of Neo4j: 3.5.26
Lib versions:
neo4j-graph-algorithms-3.5.11.0
neo4j-graph-algorithms-3.5.14.0
neo4j-graph-data-science-1.1.6

Just now i'm trying to collect additional info.
Neo4j log do not contain error and stack trace.

Give me some advice, how to collect more info about error?

**Comment by mnd999** [comment]
Thanks for the report, this repository is for the core database. The correct repository for this issue is graph-data-science and I see you already opened an issue there. Therefore I will close this one. 

If you believe this to be incorrect, please feel free to reopen this issue.

**Comment by strangeman375** [comment]
Thanks @mnd999 
It is not clear to me, what causes the error, so I opened an issue in both places, just in case.
