### ISSUE TITLE
Cannot create demo database movies

### ISSUE THREAD

**Issue by rudolfschmidt** [neo4j/neo4j#12706]
- Neo4j version: 4.2.2-1
- Operating system: Arch
- API/Driver: Cypher
**Steps to reproduce**
```
yay -S neo4j-community
Open http://localhost:7474/browser/
write "create database movies" and press enter
```
- Expected behavior

Database creation

- Actual behavior

```
Neo.ClientError.Statement.NotSystemDatabaseError
Unsupported administration command: CREATE DATABASE movies
```

**Comment by mnd999** [comment]
The `CREATE DATABASE` command is not available in the community edition, as only a single database is supported. The movies dataset can be loaded into the default neo4j database, or the name can be changed using the configuration file. Further details are here:
https://neo4j.com/docs/operations-manual/current/manage-databases/configuration/#manage-databases-configuration

**Comment by rudolfschmidt** [comment]
Would be great if you could add this info into the demo description to get less confusion. Also adding multiple databases should be supported in the community version because it's a crucial and basic operation.

**Comment by mnd999** [comment]
Sure, are you able to link the relevant example in the docs and we'll take a look and see what needs to be updated? We have a lot of tutorials so I'm not sure which one you are using. 
Whether to allow multiple databases at the same time in community is a product level decision - I'll pass on your feedback to the product team.

**Comment by adubkov** [comment]
@rudolfschmidt I agree with you - this is basic feature, like authentication and I can't imagine community would not implemented it yet. But I don't think neo4j will accept any PR from community that will add missing "enterprise" features.

As workaround you can run multiple instances of database in containers and switch between them or if you stick with AWS just use Amazon Neptune instead. They even have tool to migrate from neo4j.
