### ISSUE TITLE
Parallel Connection in Neo4j Community Version

### ISSUE THREAD

**Issue by laxmimerit** [neo4j/neo4j#12713]
Hi,
I am evaluating the Neo4j community version with the data which have millions of nodes and relationships. I wrote a thread application to write data in parallel. Four threads are working parallel and total update time reduced by 4 times but updated 
 the number of nodes is also reduced by 4.
Seems like parallel writing is not happening. There are no dependencies between data running in each thread and it does not also throw an error. 

It is behaving like this
1. I write 100k nodes in 1 hour without threading
2. I try to write 100k nodes with 4 threads. It is done in 15 minutes but I see only 25k nodes are written.

I have used thread.join() to wait for thread completion. I used Python.

**Comment by mnd999** [comment]
I don't think we can help to investigate this without more information, we would at least need to look at your query and schama (what indexes / constraints you have).

**Comment by mnd999** [comment]
This issue has been inactive for some time so I will close for now. Please feel free to reopen if it's still an issue.
