### ISSUE TITLE
Cypher expression parser does't translate type when the type is node's class name

### ISSUE THREAD

**Issue by DachuanZhao** [neo4j/neo4j#12717]
## Guidelines
- Neo4j version: 4.2.5
- Operating system: docker
- API/Driver: neo4j 4.2.1 python3.8

```Cypher
LOAD CSV WITH HEADERS FROM 'file:///entity/entity.csv' AS row 
WITH row,
(CASE row.category  WHEN 'compound' THEN 'Compound'   WHEN 'disease' THEN 'Disease'   WHEN 'protein' THEN 'Protein'  ELSE 'Other' END) AS type 
MERGE (c:type {name: row.name}) 
SET c.name=row.name, c.category:row.category 
```
- Expected behavior
```c:type``` should be translated to ```c:Compound``` , ```c:Disease``` and ```c:Protein```

- Actual behavior
- ```c:type``` isn't translated to  ```c:Compound``` , ```c:Disease``` and ```c:Protein```

**Comment by mnd999** [comment]
This is expected, labels form part of a structural type and as such cannot be set in this way. Please see the types documentation here:

https://neo4j.com/docs/cypher-manual/current/syntax/values/#structural-types

If you reach out to our neo4j-community forums or on our [discord](https://discord.gg/neo4j) you should be able to get some help with your data load.
