### ISSUE TITLE
apoc.import.json importing style

### ISSUE THREAD

**Issue by fssrepository** [neo4j/neo4j#12715]
I'm generating lots of test data to try out how apoc library works, but apoc.import.json function is importing a json file, which is not a json format.

It imports a jsonArray, however jsonArray is like

[{},{}]

format,

but it's loading from

{}
{}

format, which i can't even format with VsCode.

Can you pls. fix this, to load a jsonArray instead. You can cut square brackets and commas, but it would be really helpful, if i can format my json file, and i don't need to manually make regex and reformat it.

**Comment by fssrepository** [comment]
Other thing is, i'm not sure what this method is doing behind the scene, but i was generating the 1000 record at least 1000 times faster, than the time what was needed to load. We are talking about some seconds, but it took me milliseconds to generate it.
Very likely i'm able to make the in-memory graph way faster than to save something to neo4j db. At the moment as graph dbs are a tottally different world to me, i probably will be going to my own implementation, which will be doing just one thing, what i need. I was thinking to put a kafka at the front of it, while saving to mongodb at the same time. The insert is also very CPU intensive. I haven't used indexes at the moment.

**Comment by mnd999** [comment]
@fssrepository  Thanks for the report, can you open this issue against APOC as this issue belongs that library. This is the correct repository https://github.com/neo4j-contrib/neo4j-apoc-procedures.
