### ISSUE TITLE
Neo4j does not start

### ISSUE THREAD

**Issue by cvanelteren** [neo4j/neo4j#12714]
# Problem
`neo4j start` yields errors
<details> <summary> output </summary> 
<p>

```
Error: Could not find or load main class org.neo4j.server.CommunityEntryPoint
Caused by: java.lang.ClassNotFoundException: org.neo4j.server.CommunityEntryPoint
Error: Could not find or load main class org.neo4j.server.CommunityEntryPoint
Caused by: java.lang.ClassNotFoundException: org.neo4j.server.CommunityEntryPoint
Error: Could not find or load main class org.neo4j.server.CommunityEntryPoint
Caused by: java.lang.ClassNotFoundException: org.neo4j.server.CommunityEntryPoint
Error: Could not find or load main class org.neo4j.server.CommunityEntryPoint
Caused by: java.lang.ClassNotFoundException: org.neo4j.server.CommunityEntryPoint
Error: Could not find or load main class org.neo4j.server.CommunityEntryPoint
Caused by: java.lang.ClassNotFoundException: org.neo4j.server.CommunityEntryPoint
```

</p>
</details>

# System info
- Neo4j version: 4.2.2-1
- Operating system: Linux 5.11.16 sway 

# steps to reproduce
`yay neo4j-community && sudo neo4j start`

# Expected behavior
It runs a neo4j server

**Comment by mnd999** [comment]
Is looks like, from your steps to reproduce you are using Arch Linux AUR packages. Unfortunately, we do not produce official packages for Arch Linux, so you may wish to follow up with the AUR package maintainer and see if they can help.

Our official Linux installation instructions can be found here:
https://neo4j.com/docs/operations-manual/current/installation/linux/

**Comment by cvanelteren** [comment]
Ah ok I will contact the maintainers and in try the tar install. Just for my understanding the error refers to a java sdk error, do you have any pointers where I myself may look? I have java 11 set as active.

**Comment by cvanelteren** [comment]
For others with the issue; neo4j-desktop works fine on aur. Closing this issue!
