### ISSUE TITLE
Illegal reflective access in embedded neo4j 4.2.5 official example.

### ISSUE THREAD

**Issue by manueldeprada** [neo4j/neo4j#12712]
Running the example EmbeddedNeo4j from your examples prints an illegal reflective access warning.

- Neo4j version: 4.2.5
- Operating system: Ubuntu 20.04, OpenJDK 11
- API/Driver: Neo4j Embedded 4.2.5 from Maven

Open a new project, include neo4j:4.2.5 from maven and copypaste the official Neo4j example from your github page: https://github.com/neo4j/neo4j-documentation/blob/4.3/embedded-examples/src/main/java/org/neo4j/examples/EmbeddedNeo4j.java

The demo example from your documentation produces this warning:

- Expected behavior: Smooth run.
- Actual behavior.
```
> Task :EmbeddedNeo4j.main()
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access using Lookup on org.neo4j.memory.RuntimeInternals (file:/home/manuel.deprada/.gradle/caches/modules-2/files-2.1/org.neo4j/neo4j-unsafe/4.2.5/f167f63e8d3eebe6c86c173fb7ff930dfafe11df/neo4j-unsafe-4.2.5.jar) to class java.lang.String
WARNING: Please consider reporting this to the maintainers of org.neo4j.memory.RuntimeInternals
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Hello, brave Neo4j World!
Shutting down database ...
```

**Comment by klaren** [comment]
Hello and thank you for reporting.

This warning is printed by the JVM because neo4j accesses internal JDK APIs, for example compiling queries to machine code to make them fast. This is just a warning and does not affect the functionality, and can safely be ignored.

The statement about `All illegal access operations will be denied in a future release` will be java 17.

If you really want to hide the warning you could have a look at:
```java
org.neo4j.internal.unsafe.IllegalAccessLoggerSuppressor.suppress();
```

**Comment by manueldeprada** [comment]
> Hello and thank you for reporting.
> 
> This warning is printed by the JVM because neo4j accesses internal JDK APIs, for example compiling queries to machine code to make them fast. This is just a warning and does not affect the functionality, and can safely be ignored.
> 
> The statement about `All illegal access operations will be denied in a future release` will be java 17.
> 
> If you really want to hide the warning you could have a look at:
> 
> ```java
> org.neo4j.internal.unsafe.IllegalAccessLoggerSuppressor.suppress();
> ```

Thank you for the clarification. However, I can't use the org.neo4j.internal.unsafe.IllegalAccessLoggerSuppressor.suppress(), cannot find the IllegalAccessLoggerSuppressor class. I'm using the latest 4.2.7 Maven Community build. Is it maybe a feature of the paid version??

**Comment by klaren** [comment]
It can be found in 
```xml
  <dependency>
    <groupId>org.neo4j</groupId>
    <artifactId>neo4j-unsafe</artifactId>
    <version>...</version>
  </dependency>
```
but this is the hacky solution to hide it. The correct thing would be to tell the JVM that you want to allow access to the internal classes by adding the following to the java command line
```
java --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.util.concurrent=ALL-UNNAMED --add-opens java.base/sun.net.www.protocol.http=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED
```
This should cover all of the current JDK internal classes we use.

**Comment by manueldeprada** [comment]
Thank you for your time. Now it works both ways! For someone reaching this issue looking for a solution, let me summarize the options available:

1. Hide the "Illegal reflective access" warning. This is fine until Java 17. To do so, you must import the dependency neo4j-unsafe and call: `org.neo4j.internal.unsafe.UnsafeUtil.disableIllegalAccessLogger();` before instantiating neo4j. Note that the call posted before by @klaren doesn't work for me as the `IllegalAccessLoggerSuppressor` class doesn't exist, at least in neo4j-unsafe 4.2.7 (may have been updated). 
2. Properly tell the JVM, as @klaren posted, to allow access to internal classes, by adding the following VM options:
`--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.util.concurrent=ALL-UNNAMED --add-opens java.base/sun.net.www.protocol.http=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED`
