### ISSUE TITLE
Desktop 1.4.5 will not run installation or open after download. 

### ISSUE THREAD

**Issue by 19barsav** [neo4j/neo4j#12727]
Which versions of our products are you using?
**Neo4j Desktop V. 1.4.5**
What operating system are you on?
**Windows 10 Home - all updates installed**
Are you working with a cluster or on a single machine?
**Single Machine**
What errors are you seeing and what solutions have you tried already?
**I can't open it at all. I installed it yesterday and it opened after it installed and prompted for the key. I played around with it for a bit and closed it and went to bed. It wouldn't open this morning, so I uninstalled and reinstalled 4 times. When it runs, it opens three background processes.  If I tell it to open again, one of the processes will use 14% CPU for 15 seconds then fall back to 0%. All four downloads, none have opened up anything other then the installation part where it asks for the directory to install to. 3 of the redownloads were after uninstallment and the last one was to replace/update what was already there. I've reset my laptop and I've done everything I can think of. In the case it is a user-error, I asked StackedOverflow for help, too.**

**Comment by mnd999** [comment]
Thanks for the report. Unfortunately,  this is not the correct repository for Neo4j Desktop. Please head over to https://github.com/neo4j-devtools/neo4j-desktop and open an issue there.
