### ISSUE TITLE
Creating a user (in Java) with an invalid name returns no error

### ISSUE THREAD

**Issue by marcello-dev** [neo4j/neo4j#12725]
Running the following query in the Neo4J sandbox (or Neo4j server in general) returns this error:

![image](https://user-images.githubusercontent.com/55074569/118261348-fc663800-b4e5-11eb-948f-d52d7f583fa7.png)

But running the same query in Java **does not** return an error:

![image](https://user-images.githubusercontent.com/55074569/118259801-2880b980-b4e4-11eb-886a-8fc798153304.png)

`UserRepository` class:

![image](https://user-images.githubusercontent.com/55074569/118260589-181d0e80-b4e5-11eb-9f18-4f0969c388c5.png)

It might seem an issue with the embedded database but running the application with a real Neo4j database is the same. The Neo4j driver can create a user with an invalid name. Then trying to delete a user with an invalid name is impossible through the browser.

---

**spring-boot-starter:** 2.4.5 
**spring-data-neo4j:** 6.0.8
**neo4j-harness:** 4.2.5
**Operating System:** Windows 10

### Steps to reproduce
1. Clone repo: https://github.com/marcello-dev/neo4jnamebug
2. Run the test with `mvn test`

### Expected behavior
The test should fail (?)

### Actual behavior
The tests pass

**Comment by mnd999** [comment]
As per the [naming rules ](https://neo4j.com/docs/cypher-manual/current/syntax/naming/), the username 'a-b' is legal, but it needs to be escaped using backticks, e.g. `CREATE USER `a-b` SET PASSWORD 'pass';` I am not familiar with the Java library you are using, but I would expect it is doing the correct escaping behind the scenes.
