### ISSUE TITLE
Integer overflow check

### ISSUE THREAD

**Issue by czpmango** [neo4j/neo4j#12726]
**Neo4j Version:** 4.2.4
**Operating System:** MacOs
**API:** Cypher

### Steps to reproduce
```
neo4j@neo4j> return --9223372036854775808;
+-----------------------+
| --9223372036854775808 |
+-----------------------+
| -9223372036854775808  |
+-----------------------+

neo4j@neo4j> return +-9223372036854775808;
+-----------------------+
| +-9223372036854775808 |
+-----------------------+
| -9223372036854775808  |
+-----------------------+

neo4j@neo4j> return 9223372036854775808;
integer is too large (line 2, column 8 (offset: 8))
"return 9223372036854775808;"
```
### Expected behavior
`return --9223372036854775808` and ` return 9223372036854775808` behave the same.

### Actual behavior
`return --9223372036854775808` did not throw an error.

**Comment by mnd999** [comment]
Interesting, it looks like it's not  applying the `--` and treating it as `-`. If I do `RETURN 0--9223372036854775808` it does become an expression and I get the error.
