### ISSUE TITLE
performance issue after upgrade 3.5 => 4.2

### ISSUE THREAD

**Issue by ctytgat** [neo4j/neo4j#12721]
This issue is described in following community thread:

https://community.neo4j.com/t/weird-performance-issue-after-upgrade-3-5-4-2/31464

Looks like a query-planner related problem.

It's still there with Neo4j 4.2.6.

**Comment by mnd999** [comment]
Thanks, we'll take a look.

**Comment by sherfert** [comment]
@ctytgat 

This sounds indeed like a problem related to replanning, but is going to be very hard for us to reproduce.

As has been asked in the linked thread already: Can you turn that into a reproducible test?
Ideal for us is a Java test using [TestDatabaseManagementServiceBuilder ](https://github.com/neo4j/neo4j/blob/4.2/community/community-it/it-test-support/src/main/java/org/neo4j/test/TestDatabaseManagementServiceBuilder.java) but a test using a driver of your choice would be fine, too.

**Comment by sherfert** [comment]
Please reopen this issue with the reproducible test we asked for if you still need us to investigate this issue.

**Comment by jbhurruth** [comment]
For what its worth, I'm seeing this behaviour too
