### ISSUE TITLE
Mishandling of properties upon creation Cypher 

### ISSUE THREAD

**Issue by adnanmuttaleb** [neo4j/neo4j#12720]
When I create a new Node of specific type, a property that I did not specify get added and one I did specify is deleted. 
 
Example Cypher query (taken from "**Code**" tab of `PROFILE`):

```
PROFILE ..
CREATE (p:Card {contents: 'Lorem Epsiom', completed: True, create_date: datetime("..."), score: 0, has_more_content: False, visible: True, language_id: '..', comments_count: 0, attachment_types: []}) 
..
RETURN p
```
 
While  In the "**Text**" tab I have:

```
{"visible":true,"links_clickable":[],"completed":true,"language_id":"..","score":0,"contents":"Lorem Epsiom","comments_count":0,"has_more_content":false,"create_date":".."} 
```

Notice that `attachment_types `does not exist anymore and it is replaced by `links_clickable`. 

- Neo4j version: 3.5.23
- Operating system: Ubuntu 
- API/Driver: Cypher

**Expected behavior:** 

Node is created with the same properties I specify 

**Actual behavior:** 

Node is created with one property added although I did not specify, and one property deleted. 

**Notes:**

- This is all started to happen when I added `links_clickable` to node of other type (not `Card`), after that all `Card` node has  `links_clickable` instead of `attachment_types `. 

- Although `attachment_types ` is not returned when I query `Card` nodes, when I run this it returns `[]`  not `NULL`:

        `MATCH (post:Card {id: ..}) return post.attachment_types`

**Comment by mnd999** [comment]
Thanks for the report. Firstly, have you tried running the consistency checker? Does it pass?
https://neo4j.com/docs/operations-manual/current/tools/consistency-checker/

**Comment by adnanmuttaleb** [comment]
@mnd999  Thanks for the response, I run it yesterday and it passes successfully

**Comment by adnanmuttaleb** [comment]
@mnd999 After restarting all neo4j nodes, the problem was solved. But we could not locate the true cause of the problem.

**Comment by mnd999** [comment]
I don't think there is much more we can do to investigate if the problem has gone away. Unless there is a copy of the database in the 'bad' state. Shall we close this for now? Please reopen if the problem reoccurs and we need to investigate further.

**Comment by LinneaAndersson** [comment]
@adnanmuttaleb  Thanks for the report. I wasn't able to reproduce it and as it seems to have been solved I will close this issue for now. As @mnd999 writes, feel free to reopen it if the problem reoccurs.
