### ISSUE TITLE
how to use detach delete and delete in one cypher matcher?

### ISSUE THREAD

**Issue by LinshanYu** [neo4j/neo4j#12735]
such as : match(a:user) match(b:dog) match (a) -[]->(b) detach delete a and delete b 

I want to express detach delete and delete  in one cypher , help me

**Comment by mnd999** [comment]
The syntax you have is fine apart from the 'and' - this would work:
`match(a:user) match(b:dog) match (a) -[]->(b) detach delete a delete b`

Generally we prefer to answer these types of questions in [our community forums](https://community.neo4j.com/) or on our [discord](https://discord.gg/neo4j) and you will likely get a faster response there. Github is more setup for bug reports in the product.

**Comment by LinshanYu** [comment]
> The syntax you have is fine apart from the 'and' - this would work:
> `match(a:user) match(b:dog) match (a) -[]->(b) detach delete a delete b`
> 
> Generally we prefer to answer these types of questions in [our community forums](https://community.neo4j.com/) or on our [discord](https://discord.gg/neo4j) and you will likely get a faster response there. Github is more setup for bug reports in the product.

thk, bro
