### ISSUE TITLE
Hi, I want to back up the Neo4j 3.5 database to version 4.0,    I backup my data in offline mode, neo4j-admin dump and neo4j-admin load, However, when I start my 4.0 Database after backing up the Database, I get a Browser error "Database "neo4j" is unavailable, its status is "offline.""

### ISSUE THREAD

**Issue by zqw961025** [neo4j/neo4j#12736]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. 
If you have questions on how to use Neo4j, please ask on [StackOverflow](https://stackoverflow.com/questions/tagged/neo4j) instead of creating an issue here.

Before creating a new issue, please check whether someone else has raised the same issue. You may be able to add context to that issue instead of duplicating the report. However, each issue should also only be focussed on a _single_ problem, so do not describe new problems within an existing thread - these are very hard to track and manage, and your problem may be ignored. Finally, do not append comments to closed issues; if the same problem re-occurs, open a new issue, and include a link to the old one.

To help us understand your issue, please specify important details, primarily:

- Neo4j version: X.Y.Z
- Operating system: (for example Windows 95/Ubuntu 16.04)
- API/Driver: (for example Cypher/Java API/Python driver vX.Y.Z)
- **Steps to reproduce**
- Expected behavior
- Actual behavior

Additionally, include (as appropriate) log-files, stacktraces, and other debug output.

## Example bug report

I discovered that when I mount `data/` to a volume on my host, and then stop the container, the `write.lock` is not removed as well as a number of other files not being cleaned up properly.

**Neo4j Version:** 3.0M03
**Operating System:** Ubuntu 15.10
**API:** Docker

### Steps to reproduce
1. Pull the image: `docker pull neo4j/neo4j:3.0.0-M03`
2. Create a directory on the host that will be a mount for the data: `mkdir /home/neo4j-data`
3. Start a new container that mounts to this directory: `docker run -d --name neo4j-test -p 7474:7474 -v /home/neo4j-data:/data neo4j/neo4j:3.0.0-M03`
4. Navigate to the `write.lock` file located in the directory: `/data/databases/graph.db/schema/label/lucene/labelStore/1/`
5. Stop the container: `docker stop neo4j-test`

### Expected behavior
`write.lock` should be removed now.

### Actual behavior
`write.lock` is still present and preventing access by other programs.

**Comment by greenlight2000** [comment]
Hi I know it's been super long time but I have the same problem with you, I backup my neo4j 3.5.* dataset into .dump file and now I need to load it into a neo4j 4.1 DBMS(I also used neo4j-admin load), the same error occur. I wonder whether you found any way to fix this? Could you provide any guidance on backup older version dataset into a newer version DBMS? thanks

**Comment by klaren** [comment]
@greenlight2000 If you have a similar problem, could you open a new issue?
You can have a look in the `logs/debug.log` after any subspinous errors that could explain what is going on.
