### ISSUE TITLE
Upgrade 1.4.3 to 1.4.5 crashes

### ISSUE THREAD

**Issue by pjljvandelaar** [neo4j/neo4j#12733]
- Neo4j version: 1.4.3
- Operating system: Windows 10

Within Neo4j accept the option to upgrade to new version.

- Expected behavior
Ne04j is upgraded

- Actual behavior
Neo4j crashes.

Additionally, include (as appropriate) log-files, stacktraces, and other debug output.

![Neo4j_update_failed](https://user-images.githubusercontent.com/18348654/120818624-13cb9a80-c553-11eb-8aa3-ebcdc0799e01.jpg)

My system is now in a undefined state: the old neo4j is only partly removed.
See the remaining neo4j folders in /users/xxx/AppData

![RemainingNeo4jfolders](https://user-images.githubusercontent.com/18348654/120819014-6e64f680-c553-11eb-8ab0-d53713c145ac.jpg)

Any suggestions on how to proceed?
Can I just remove all the directories?

**Comment by mnd999** [comment]
Thanks for the report. This is not the correct repository for Neo4j-Desktop though, please raise your issue in this repository, as this is the correct one for Neo4j-Desktop: https://github.com/neo4j-devtools/neo4j-desktop

If you think this is incorrect, please feel free to reopen and we will investigate further.
