### ISSUE TITLE
Hi, I want to back up the Neo4j 3.5 database to version 4.0,  I backup my data in offline mode, neo4j-admin dump and neo4j-admin load,However, when I start my 4.0 Database after backing up the Database,,Iget a Browser error,Database "neo4j" is unavailable, its status is "offline."

### ISSUE THREAD

**Issue by zqw961025** [neo4j/neo4j#12737]
Hi, I want to back up the Neo4j 3.5 database to version 4.0, I backup my data in offline mode, neo4j-admin dump and neo4j-admin load,However, when I start my 4.0 Database after backing up the Database,,Iget a Browser error,Database "neo4j" is unavailable, its status is "offline."

**Comment by mnd999** [comment]
I'm having a hard time understanding this report, please can you remove the parts of the example that are not relevant, and provide the information on your environment we suggest. In this case I suspect `neo4j.log` and `debug.log` would be useful.

**Comment by zqw961025** [comment]
Hi, I want to back up the Neo4j 3.5 database to version 4.0, I backup my data in offline mode, neo4j-admin dump and neo4j-admin load,However, when I start my 4.0 Database after backing up the Database,,Iget a Browser error,Database "neo4j" is unavailable, its status is "offline.". I just wanted to say this, didn't realize the error in the report

**Comment by mnd999** [comment]
As above, |I don't think we have enough information to help with this. please provide the information on your environment  and relevant log files or I don't think we can progress this any further.

**Comment by davidlrosenblum** [comment]
Hi,
I don't think this is a bug.  Also I think this kind of question would be better answered in community.neo4j.com, but none the less...
Stop the database
In your 4.x database make sure you set `dbms.allow_upgrade = true` in neo4j.conf
https://neo4j.com/docs/operations-manual/current/reference/configuration-settings/#config_dbms.allow_upgrade
After you do the `neo4j-admin load --database=yourdbname --from=pathtodumpfile ` command you need to start the database, then in browser run `create database yourdbname`
You can look in the migration guide for other methods, but doing the neo4j-admin dump in 3.5 and then the load command in 4.x followed by the create database command has never let me down.  Worst case you will need to drop and index and recreate it.

**Comment by zqw961025** [comment]
thinks for you help

**Comment by zqw961025** [comment]
Thank you for your help

**Comment by mnd999** [comment]
Closing as this appears to be resolved, if you still believe this to be an issue, feel free to reopen.
