### ISSUE TITLE
Neo4j does not have a mysql-like binlog?

### ISSUE THREAD

**Issue by zqw961025** [neo4j/neo4j#12740]
Neo4j does not have a mysql-like binlog??

**Comment by InverseFalcon** [comment]
Hello, this sounds like our Transaction Logs, which are used to capture changes to the db (their format is such that they aren't person-readable) and are used to replicate changes to the rest of the nodes in the cluster. They are also used in recovery operations (applying changes to the pagecache in-memory graph representation) and checkpointing (flushing changes represented in the transaction logs to the store files). They also support incremental backup operations and catchup operations when replicating dbs within a cluster.

More info here:

https://neo4j.com/docs/operations-manual/current/configuration/transaction-logs/

**Comment by burqen** [comment]
@zqw961025 Before we forward this to our product team it would be useful if you could provide your use case for this feature.

**Comment by burqen** [comment]
I'm closing this issue due to lack of information. Please open again if needed.
