### ISSUE TITLE
Neo4j to Elasticsearch

### ISSUE THREAD

**Issue by zqw961025** [neo4j/neo4j#12741]
Hi, what I need to do now is to synchronize data in Neo4j to Elasticsearch in real time, that is, any changes in Neo4j will synchronize to Elasticsearch, I have referred to the method here: https://neo4j.com/developer/elastic-search/, when I found these plug-ins are too old, many also for secondary version 4.0 + does not support, for example, secondary - elasticsearch, I want to ask if there is a better way to do this

**Comment by mnd999** [comment]
I would suggest opening an issue in https://github.com/neo4j-contrib/neo4j-elasticsearch to see if it can be updated. 

Alternatively, ask in [our community forums](https://community.neo4j.com/) or on our [discord](https://discord.gg/neo4j) as there may be others in the community with the same problem. Github is more setup for bug reports in the product.
