### ISSUE TITLE
Maintain scroll position in documentation index

### ISSUE THREAD

**Issue by gregoryking** [neo4j/neo4j#12742]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when I scroll down the docs content on the LHS, click on a section and the content section auto scrolls back to the top.  This makes clicking through items in a particular section involve a lot of scrolling.

**Describe the solution you'd like**
Maintain scroll position of index after click

**Describe alternatives you've considered**
n/a
**Additional context**
Particularly relevant for APOC documentation which can have some very long sections

![CleanShot 2021-07-06 at 10 08 00](https://user-images.githubusercontent.com/1253994/124574696-a2795300-de42-11eb-96a7-8f2cf33e6a4a.gif)

**Comment by davidoliverSP2** [comment]
Reopened in the Docs-UI repo: https://github.com/neo4j-documentation/docs-ui/issues/73
