### ISSUE TITLE
ExternalSettings class is gone in 4.3.2 , no obvious replacement?

### ISSUE THREAD

**Issue by cartwrightian** [neo4j/neo4j#12743]
Neo4j version: 4.3.2
Operating system: all
API/Driver: community edition

**Steps to reproduce**
4.2.6 Code compiles
Update to 4.3.2 code does not compile. ExternalSettings is not longer present, no obvious javadoc or similar explaing what replaces it? Not seeing anything in https://github.com/neo4j/neo4j/wiki/Neo4j-4.3-changelog or earlier change logs.

I'm guessing I missed some docs, apologies.

### Steps to reproduce
1. Update from 4.2.6 to 4.3.2
2. Compile code
3. Fails as org.neo4j.configuration.ExternalSettings no longer present

Example code  that no longer compiles
managementService = new DatabaseManagementServiceBuilder( graphFile ).
            setConfig(GraphDatabaseSettings.track_query_allocation, false).
            setConfig(GraphDatabaseSettings.store_internal_log_level, Level.WARN ).
            setConfig(GraphDatabaseSettings.pagecache_memory, config.getNeo4jPagecacheMemory()).
            setConfig(ExternalSettings.initial_heap_size, config.getInitialHeapSize()).
            setConfig(ExternalSettings.max_heap_size, config.getMaxHeapSize()).
            setConfig(GraphDatabaseSettings.tx_state_max_off_heap_memory, SettingValueParsers.BYTES.parse("256m")).
            setConfig(GraphDatabaseSettings.tx_state_max_off_heap_memory, SettingValueParsers.BYTES.parse("512m")).
            setConfig(GraphDatabaseSettings.keep_logical_logs, "false").
            setConfig(HttpConnector.enabled, false).
            setConfig(HttpsConnector.enabled, false).
            setConfig(BoltConnector.enabled, false).
            //setUserLogProvider(new Slf4jLogProvider()).
            build();

### Expected behavior
Java doc or similar pointing at replacement for org.neo4j.configuration.ExternalSettings
Changelog to call out it's removable and repalcement.

Sorry if I missed something obvious here.

**Comment by cartwrightian** [comment]
So I was setting these heap parameters via JVM parameters anyway, so I am assuming this is the right thing to do instead of using this (removed) settings?

**Comment by MishaDemianenko** [comment]
Hi @cartwrightian   

ExternalSettings is gone in 4.3.x. And indeed it's not mentioned in public documentation/javadoc anywhere. 
All of that because that was that class was never part of the official public surface.

And indeed using JVM parameters is the correct thing to do anyway since those external settings in the way you used them in your provided sample were noop anyway.
So just remove those and enjoy the flight.

**Comment by MishaDemianenko** [comment]
Closing. Please feel free to reopen if you still have any questions.
