### ISSUE TITLE
Why did I successfully compile neo4j when started and browser displays 404?

### ISSUE THREAD

**Issue by DimBottom** [neo4j/neo4j#12752]
## Guidelines

I followed the README process to compile the 4.x version and then released the `dbms.connectors.default_listen_address=0.0.0.0` comment in the configuration.

```shell
git clone https://github.com/neo4j/neo4j.git
mvn clean install -DskipTests
./bin/neo4j console
```

I started the application from the `neo4j console` in the bin directory。When I visit to the browser, the browser response 404, hint I can't find the corresponding web page with the link below: `http://127.0.0.1:7474/browser/`

![image](https://user-images.githubusercontent.com/49503478/127434372-78ab7db6-16c9-4890-aa66-b31cb5a9230d.png)

At first, I completed the compilation under the Win10 environment, and later I tried to compile it under the Ubuntu 18.04 virtual machine, but there were still problems in the browser access after the compilation.

I'm sure there was no error alert during compilation and that it works fine with the `cypher-shell`.

In the end, I did the same with 3.x version of Neo4J, and it was finally accessible correctly.

- Neo4j version: 4.3.3
- Operating system: Windows 10 and Ubuntu 18.04
- Maven version: 3.6.3
- jdk: 
```text
java version "11.0.12" 2021-07-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.12+8-LTS-237)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.12+8-LTS-237, mixed mode)
```

In addition, the official website provided zip can be easily launched without any problems

**Comment by mnd999** [comment]
[Neo4j Browser](https://github.com/neo4j/neo4j-browser) is a separate project and thus must be built separately. As you've seen, the official builds from the website include neo4j and neo4j-browser.
