### ISSUE TITLE
`key not found: VariableSlotKey` error thrown from query using OPTIONAL MATCH with a predicate function after a MATCH returning no results

### ISSUE THREAD

**Issue by flaviuratiu** [neo4j/neo4j#12757]
The following query throws an error instead of returning no results, when the initial `MATCH` returns no results:

```
MATCH (a) 
OPTIONAL MATCH (b)--(a) 
WHERE ALL(c IN [] WHERE (b)--(c))
RETURN b
```

If `OPTIONAL MATCH` from line 2 is replaced with `MATCH`, the query returns no results, as expected.
Also, the query works fine with `OPTIONAL MATCH` on line 2, but without a predicate function as condition for the `OPTIONAL MATCH`.

**Neo4j Version:** 4.3.2-enterprise or 4.2-enterprise or 4.2-aura (I tested against all 3)
**Operating System:** Windows 10 Pro, plus whatever neo4j-aura is running on

### Steps to reproduce
Execute this query in an empty database:
```
MATCH (a) 
OPTIONAL MATCH (b)--(a) 
WHERE ALL(c IN [] WHERE (b)--(c))
RETURN b
```

Docker command to start a neo4j container on Windows:
```
docker run --name testneo4j \
	-p7474:7474 \
	-p7687:7687 \
	-d \
	-v $HOME/neo4j-4.3.2-enterprise/data:/data \
	-v $HOME/neo4j-4.3.2-enterprise/logs:/logs \
	-v $HOME/neo4j-4.3.2-enterprise/import:/var/lib/neo4j/import \
	-v $HOME/neo4j-4.3.2-enterprise/plugins:/plugins \
	--env NEO4J_AUTH=neo4j/neo4jtest \
	--env NEO4J_dbms_connector_https_advertised__address="localhost:7473" \
	--env NEO4J_dbms_connector_http_advertised__address="localhost:7474" \
	--env NEO4J_dbms_connector_bolt_advertised__address="localhost:7687" \
	--env=NEO4J_ACCEPT_LICENSE_AGREEMENT=yes \
	neo4j:4.3.2-enterprise
```

### Expected behavior
The query should return no results.

### Actual behavior
The following error is thrown: `Neo.DatabaseError.Statement.ExecutionFailed` `key not found: VariableSlotKey(b)`

**Comment by mnd999** [comment]
Thanks for the report, we'll take a look and get back to you.

**Comment by pontusmelke** [comment]
@flaviuratiu Thanks for reporting this. We have identified the problem and the fix will hopefully be part of the next point release. As a temporary workaround you can prepend `CYPHER runtime=interpreted` to your query.

Best regards,
Pontus

**Comment by flaviuratiu** [comment]
Thanks @pontusmelke. Prepending `CYPHER runtime=interpreted` to the query does solve the issue with this simplified example. I'll try it in my service as well.
