### ISSUE TITLE
Downloading Linux Desktop, Can't Start AppImage

### ISSUE THREAD

**Issue by big-c-note** [neo4j/neo4j#12758]
### Steps to Reproduce:

Starting from https://neo4j.com/download/

Takes you to https://neo4j.com/download-thanks-desktop 

Downloading for Linux, Ubuntu 20.04, CDN: https://s3-eu-west-1.amazonaws.com

Two files are downloaded: 
`neo4j-desktop-1.4.7-x86_64.AppImage`
`neo4j-desktop-1.4.7-x86_64.AppImage.part` (partial file)

Running
```
chmod +x {path/to/downloads/}neo4j-desktop-1.4.7-x86_64.AppImage
./{path/to/downloads/}neo4j-desktop-1.4.7-x86_64.AppImage 
```

Clicking `neo4j-desktop-1.4.7-x86_64.AppImage` brings up a blank text file.

### Expected Behavior
Open desktop app

### Actual Behavior
Open blank text file

### Versions
- Neo4j version: 1.4.7/Unclear, the download page said 4.3
- Operating system: Ubuntu 20.04

**Comment by big-c-note** [comment]
Trying a third time, I managed to get it. Feel free to close.

**Comment by mnd999** [comment]
Closing as requested
