### ISSUE TITLE
Neo4j-Gremlin could not directly write and query double or float values.

### ISSUE THREAD

**Issue by Mooner97** [neo4j/neo4j#12762]
#### Environment

Version : 3.5.27  

OS : CentOS8

Storage Backend: in-memory 

Data size: 100 vertices, 200 edges  

Neo4j-Gremlin

#### Bug description

Neo4j-Gremlin could not directly write and query double or float values. We need to specify the detailed type of the property value.
However, we can do this in TinkerGraph or from Java API.

#### Current behavior

```
java.util.concurrent.ExecutionException: org.apache.tinkerpop.gremlin.driver.exception.ResponseException: [349203472:java.math.BigDecimal] is not a supported property value
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)

```

#### Expected behavior

When enter the same code in TinkerGraph.

```
gremlin> g.addV().property('vp2', 3.49203472E8)
==>v[3192]
```

When try to do it through Java API from Neo4j, it is legal.

```java
Vertex v1 = g.addV().property("author",3.49203472E8).next();
```

When detailed type declared, it is legal.

```
gremlin> g.addV().property('vp2', 3.49203472E8d)
==>v[19946]
```

#### Reproduce

```Gremlin
gremlin> g.addV().property('vp2', 3.49203472E8)
[349203472:java.math.BigDecimal] is not a supported property value
```

**Comment by mnd999** [comment]
This issue appears to be related to neo4j-gremlin which I am not familiar with, although a quick google suggests it's part of the Apache Tinkerpop project. If that is the case, you should probably open an issue there as this repository is for bug reports against the Neo4j Graph Database itself. If this is incorrect please let me know and we can investigate further, in this case a testcase using the Neo4j Java API or a Cypher query would be helpful. 
For neo4j-gremlin, you might also try asking in [our community forums](https://community.neo4j.com/) or on our [discord](https://discord.gg/neo4j) where others may be more familiar with this integration.

**Comment by Mooner97** [comment]
Thanks for that. I would open an issue in Apache Tinkerpop project and close the issue.

**Comment by Mooner97** [comment]
@mnd999 I have open an issue in Apache Tinkerpop project. Accroding to their answer, they think it should be solved by Neo4j.
I think it might be a bug and hope for your reply.
The Tinkerpop issue: https://issues.apache.org/jira/browse/TINKERPOP-2607

**Comment by newmanrs** [comment]
This appears to be  a type error resulting in gremlin using `java.math.BigDecimal`  as the default type and not `double`.   Having to cast to data types supported by Neo4j (in this case double) would seem to be the expected behaviour here for using these tools together.

**Comment by mnd999** [comment]
Neo4j does not at this time support the BigDecimal type so I will close this as working as expected.
