### ISSUE TITLE
Expand nodes when zoomin in 

### ISSUE THREAD

**Issue by moweigel** [neo4j/neo4j#12765]
I'm currently looking for an option to explore huge graphs more intuitive. I really like the visualization of Bloom and I thougt about the feature to automatically expand neigboured nodes and relations when zooming in (maybe while the mouse hovers over the desired node). Like an equivalent of zooming on a geographical map: the further u zoom in - the more detailes u receive of the specific area without the need to manually expanding a node. Is there any already excisting implementation that I missed? Else I would really appreciate a feature like that.

**Comment by mnd999** [comment]
Thanks for the suggestion, but this is not the correct repository for Bloom. Please make your feature request in the [Bloom repository here](https://github.com/neo4j-devtools/neo4j-bloom).
I will close this one for now, please feel free to repopen if you think this is incorrect.
