### ISSUE TITLE
One statement, multiple parameter sets in transactional endpoint

### ISSUE THREAD

**Issue by jadell** [neo4j/neo4j#1276]
In the REST transactional endpoint, it would be useful and efficient to send a single statement, with multiple sets of parameters:

```
POST http://localhost:7474/db/data/transaction
{
  "statements" : [ {
    "statement" : "CREATE (n {props}) RETURN n",
    "parameters" : [ {
      "props" : {
        "name" : "My Node A"
      }
    }, {
      "props" : {
        "name" : "My Node B"
      }
    }, {
      "props" : {
        "name" : "My Node C"
      }
    } ]
  } ]
}
```

**Comment by jakewins** [comment]
I'm gonna close this as a wontfix, with the argument that this will be addressed in NDP if/when we can show that it's a bottleneck to send the same queries repeatedly. Likely we'd implement some prepared statement mechanism to handle this use case.

**Comment by ikwattro** [comment]
Alternatively, right now you can accomplish the desired behavior with `UNWIND` and works with `CREATE`,`MERGE`,`REMOVE` of course.
