### ISSUE TITLE
Node properties have no guaranteed order

### ISSUE THREAD

**Issue by KienPM** [neo4j/neo4j#12771]
According to [this stackoverflow article](https://stackoverflow.com/questions/18318491/can-neo4j-property-order-be-controlled), Neo4j node properties have no guaranteed order.
Any body know how Neo4j order the properties and how to keep order like when we set?
Thank you so much!

**Comment by mnd999** [comment]
That is correct, there is no guaranteed order for node properties in Neo4j, although you can of course order them in the return clause. For help using Neo4j  we prefer to answer these types of questions in [our community forums](https://community.neo4j.com/) or on our [discord](https://discord.gg/neo4j) and you will likely get a faster response there. Github is more setup for bug reports in the product.

**Comment by KienPM** [comment]
yes, thanks for your response
