### ISSUE TITLE
Full text search Fuzzy scores are different between 4.0 and 4.3

### ISSUE THREAD

**Issue by inf3rnus** [neo4j/neo4j#12779]
## Guideline

To help us understand your issue, please specify important details, primarily:

- Neo4j version: 4.0.3 and 4.3.2
- Operating system: Ubuntu 18.04 LTS
- API/Driver: N/A
- **Steps to reproduce**

1. Download neo4j desktop
2. Create a project that uses db 4.0.3
3. Create a project that uses db 4.3.2
4. Clone the recommendations repo for import by doing: ```git clone https://github.com/neo4j-graph-examples/recommendations.git```
5. From that cloned repo import the dump files into neo4j desktop, recommendations/data/recommendations-40.dump and recommendations/data/recommendations-43.dump
6. Load those dump files into their respective db's by version
7. Start up 4.0.3 and create the index ```CALL db.index.fulltext.createNodeIndex('moviePlot', ['Movie'], ["plot"])```
8. Get the first 100 results for a simple query:
```
CALL db.index.fulltext.queryNodes('moviePlot', "plot:(man~)")
  YIELD node AS movie, score AS tf_idf
    return movie.title, tf_idf
    LIMIT 100
```
9. Record the scores returned for each title
10. Repeat steps 7-9 with neo4j 4.3.2
11. Take note that the scores differ significantly and the results returned are not the same at all.

- Expected behavior
Full text search when using a fuzzy match would return the same results for 4.3.2 as 4.0.2, given that the major version has not changed for neo4j.
- Actual behavior
Full text when using a fuzzy match returns different results for 4.3.2 and 4.0.2

Additionally, include (as appropriate) log-files, stacktraces, and other debug output.

**Same dump, same query, same indexes, different results**

4.0.2 results:
![image](https://user-images.githubusercontent.com/5959983/136460874-7a2d0616-7e1b-45e4-81b8-d1f14fbf9796.png)

4.3.2 results:
![image](https://user-images.githubusercontent.com/5959983/136460935-45f1e278-3752-4528-983f-c2c7b10cfc8f.png)

**Comment by inf3rnus** [comment]
I assume this is related to the version of lucene being used having changed on neo4j versions 4.0 and 4.3 to  <lucene.version>8.2.0</lucene.version> and <lucene.version>8.8.0</lucene.version> respectively.

What I'm trying as a workaround right now is to create a custom analyzer using <lucene.version>8.2.0</lucene.version>, but I don't know what the viability of that will be given that the neo4j java package's version is different and custom analyzers are dependent on the neo4j package, so there will likely be version conflicts in attempting this approach.

Anyway, any insight/explanation as to why the issue occurs/any workarounds be greatly appreciated!

**Comment by yehohanan7** [comment]
This is not a bug,  this was an improvement done to in 4.1.0, please have a look at the change long here - https://github.com/neo4j/neo4j/wiki/Neo4j-4.1-changelog

```
Full-text indexes now search Lucene using scorers that are calibrated with the combined statistics of all the relevant index partitions, and the transaction state. 

This ensures that the computed score for each matching document, is comparable with the score for any other document, including those that are found in different partitions. 
This fixes a bug where matching entities in the transaction state would have their scores unfairly boosted, compared to matching entities in the index.
```

**Comment by inf3rnus** [comment]
Sweet, that was super useful, thank you!
