### ISSUE TITLE
Source code tarball unavailable for latest releases

### ISSUE THREAD

**Issue by joancafom** [neo4j/neo4j#12781]
Every time a new Neo4j version came out in the past, we could find it tagged in the GH [releases page associated with the repo](https://github.com/neo4j/neo4j/releases). These tags came along with both a tarball and a zip file containing the source code snapshot that was used in the release, which made it easily traceable for those of us interested in building from source.

Nevertheless, it seems that most recent releases (version `4.3.5` & `4.3.6`) have not been tagged. Is this something that was done on purpose? If so, is there any convenient way (or page) from which we can retrieve the snapshot of the code associated with a version release, rather than delving into the project commit history?

### Expected behavior
Source code associated with a release can be easily identifiable and downloaded.

### Actual behavior
Tarball/zip file with the code for versions `4.3.5` and `4.3.6` can't be found in the releases page.

**Comment by FraPazGal** [comment]
It seems this is now also affecting the new patch version `4.3.7`, as no tag has been created for this release. I saw that tags for `4.3.5` and `4.3.6` were created, are you planning in doing so for the new version `4.3.7`?

**Comment by mnd999** [comment]
There seems to be a bug in some of our release process which we are looking into. It is definitely the intent to keep the existing behaviour of tagging the releases.

**Comment by klaren** [comment]
There was an issue in our automated release process that failed to properly tag the releases. This should be fixed now, and I have pushed all the missing tags from old releases. Thank you for reporting and sorry for the inconvenience.
