### ISSUE TITLE
I would like to inquire about the multiple Cypher statement

### ISSUE THREAD

**Issue by dongandi** [neo4j/neo4j#12782]
I have a need to know one entity and two relationships, first get the other entity through one entity and one relationship, and then get the final answer through the obtained entity and the other relationship. (我有一个需求，就是知道一个实体和两个关系，首先通过一个实体一个关系得到另一个实体，然后通过得到的这个实体和另外一个关系去得到最后的答案)
![无标题](https://user-images.githubusercontent.com/59283713/139517144-7bcb2cc4-1a67-4ce0-89cd-578c51feba66.png)
This is my single-hop search statement I want to get a multi-hop statement similar to his    (这个是我单跳的搜寻语句我想获得与他类似的多跳语句)
MATCH(p:疾病)-[r:desc]->(q:定义) WHERE p.name='{Disease}' RETURN q.name

**Comment by mnd999** [comment]
I'm not sure I fully understand the request, but it's certainly possible to do a multi-hop statement in Cypher e.g. `MATCH (a)-[:A]->(b)-[:B]->(c) WHERE a.prop='prop' AND b.prop='prop' RETURN c`.

Generally we prefer to answer these types of questions in [our community forums](https://community.neo4j.com/) or on our [discord](https://discord.gg/neo4j) and you will likely get a faster response there. Github is more setup for bug reports in the product.

**Comment by mnd999** [comment]
I have not heard anything back on this for some time so will close for now. Please feel free to reopen if it is still an issue.
