### ISSUE TITLE
Error while installing Neo4j Desktop on macOS

### ISSUE THREAD

**Issue by Hermann-Archambaud** [neo4j/neo4j#12786]
Hello everyone,

I get this error "Initialization error: Error: net::ERR_CONNECTION_REFUSED" while installing Neo4j Desktop on MacOS.
Please, has anyone ever encountered this error ?

If Yes, how can I resolve it ?

Thanks in advance.

**Comment by mnd999** [comment]
Thanks for the report. This repository is for bug reports for the database itself. For the Neo4j desktop application, [this](https://github.com/neo4j-devtools/neo4j-desktop) is the correct repository. Please open an issue there.

**Comment by mnd999** [comment]
Have not heard anything further on this issue, so closing for now.
