### ISSUE TITLE
Load CSV use command ":auto USING PERIODIC COMMIT" get wrong merge result

### ISSUE THREAD

**Issue by birsbear** [neo4j/neo4j#12788]
I want to load CSV to create node and relationship by "id" . In csv there are 50238 row and 2227 node.
When I use :
`:auto USING PERIODIC COMMIT 700 `
`LOAD CSV WITH HEADERS FROM 'file:///clean_20210625_t.csv' AS line`
`MERGE (ipa:IP{ip:line['sa']})`
`MERGE (ipd:IP{ip:line['da']})`
`MERGE (ipa)-[c:connect{id:line.id}]->(ipd)`
I expected I can get 50238 relationship, actually it has 52703 relationship
When I take off `:auto USING PERIODIC COMMIT 700 ` , it has 50238 relationship
After try to look what relationship is wrong, I found that is error relationship use same "id" label to different node, and this relationship was not in CSV file.

When I try to change COMMIT number that has different wrong result

- Neo4j version: 4.3.1
- Operating system: Win10
- API/Driver: Cypher

### Expected behavior
Add 2227 nodes, created 50238 relationship
![rightCreateResult](https://user-images.githubusercontent.com/28969402/142183544-4ad5af8d-3756-4604-bd06-2707a8bd6c95.png)

### Actual behavior
Add 2228 nodes, created 52703 relationship
![errorCreateResult](https://user-images.githubusercontent.com/28969402/142183541-bf7520d8-15df-48a7-940b-3f598689bb91.png)

**Comment by mnd999** [comment]
Sorry for the slow response on this one. Do you have any constraints on the database?

**Comment by loveleif** [comment]
Thanks for reporting this @birsbear! We've been able to reproduce the issue and are working on a fix.

**Comment by loveleif** [comment]
I was able to reproduce it in 4.3.3, but not in 4.3.10 or 4.4 versions using my data. Please update version and raise a new issue if problems remain @birsbear.

**Comment by birsbear** [comment]
> I was able to reproduce it in 4.3.3, but not in 4.3.10 or 4.4 versions using my data. Please update version and raise a new issue if problems remain @birsbear.

Thanks for fix this issues. It can import file correctly in 4.3.3 also in 4.3.10 and 4.4 versions.
