### ISSUE TITLE
Cannot set data path in desktop app for Windows 11

### ISSUE THREAD

**Issue by mq1n** [neo4j/neo4j#12785]
- **Neo4j version**: 4.3
- **Operating system**: Windows 11 Insider 22494
- **Steps to reproduce**
- Download Neo4j desktop app 
- Install as administrator
- Open Neo4j application 
- **Expected behavior**: 
- Starts and works normally
- **Actual behavior:**
- Can not set path for store application data in first launch dialog

After than Windows 11 build 22483, "wmic.exe" process removed officially in insider builds, when I try to set a path for Neo4j, I got these error messages from logs;
 `Command failed: wmic logicaldisk get size,freespace,caption
'wmic' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by mnd999** [comment]
Thanks for the report. This repository is for bug reports for the database itself. For the Neo4j desktop application, [this](https://github.com/neo4j-devtools/neo4j-desktop). Is the correct repository. Please open an issue there.
