### ISSUE TITLE
"Variable `  NODE0` not defined" in query with aliasing inside nested CALL

### ISSUE THREAD

**Issue by stanislav-a-frolov** [neo4j/neo4j#12797]
- Neo4j version: 4.3.3; official docker image
- API/Driver: Neo4j Browser

Hi,

I've recently came into a strange bug while executing programmatically generated cypher. I reduced my query to reasonable minimum (that's why it looks strange):

```
OPTIONAL MATCH nextPath = (:Asd)
CALL {
	WITH nextPath
	WITH nextPath
	WHERE nextPath IS NULL
	OPTIONAL MATCH anotherNextPath = (:Asd)
	CALL {
		WITH nextPath
		WITH nextPath AS previousPath
		WHERE previousPath IS NOT NULL
		RETURN
			previousPath as path
	}
	RETURN path
	UNION ALL
	WITH nextPath
	WITH nextPath AS previousPath
	WHERE previousPath IS NOT NULL
	RETURN previousPath as path
}
RETURN *
```

When I execute the query from neo4j browser on empty (or not) database, I get:

```
Variable `  NODE0` not defined (line 1, column 27 (offset: 26))
"OPTIONAL MATCH nextPath = (:Asd)"
                           ^
```

If I remove aliasing in inner CALL:

```
OPTIONAL MATCH nextPath = (:Asd)
CALL {
	WITH nextPath
	WITH nextPath AS previousPath
	WHERE previousPath IS NULL
	OPTIONAL MATCH nextPath = (:Asd)
	CALL {
		WITH nextPath
		WITH nextPath 
		WHERE nextPath IS NOT NULL
		RETURN
			nextPath as path
	}
	RETURN path
	UNION ALL
	WITH nextPath
	WITH nextPath AS previousPath
	WHERE previousPath IS NOT NULL
	RETURN previousPath as path
}
RETURN *
```

everything is OK (empty return).

**Comment by mnd999** [comment]
Thanks for the report, we'll take a look and get back to you.

**Comment by hedengran** [comment]
Hi, thanks again for the report. This is indeed a bug, which seems to happen when a variable that has previously been assigned to a path is used again later in a query. I've merged a fix in our development branch. Currently back-porting this to all effected versions and it should be included with the next patch for those versions.
