### ISSUE TITLE
neo4j-admin import generated duplicate id's after upgrade to 4.4

### ISSUE THREAD

**Issue by petermartens1992** [neo4j/neo4j#12793]
- Neo4j version: 4.4
- Operating system: centos
- API/Driver: neo4j-admin import

Hi, 

After upgrading to neo4j 4.4 I noticed that my neo4j-admin import generated duplicate id's, about 15 on a total of 6M or so nodes. 

After further investigation it looks like some of the records from the csv's were misinterpreted, whereby fields from different records were combined, causing these duplicate id's. 

After downgrading to 4.3.7-1 these same csv files were correcly imported again

The vat field is the unique id here and as you can see it appears twice in neo4j after the import:

```
neo4j@graph.db> MATCH (c:Company) WHERE id(c) = 336488 OR id(c) = 3332 RETURN c.vat, c.nameNl, c.nameFr;
+----------------------------------------------------------------------------------------------------------------------------------------------+
| c.vat                                    | c.nameNl                                        | c.nameFr                                        |
+----------------------------------------------------------------------------------------------------------------------------------------------+
| "A-LDN-36-FUNDASERIESOFAX-POAL-FUNDSLLC" | "A-LDN-36-Fund, a series of AX-PoAl-Funds, LLC" | "A-LDN-36-Fund, a series of AX-PoAl-Funds, LLC" |
| "A-LDN-36-FUNDASERIESOFAX-POAL-FUNDSLLC" | "SCHAFTFURINVESTMENTFONDSMBH"                   | "A-HKG-28-FUNDASERIESOFANGELLIST-BARS-FUNDSLLC" |
+----------------------------------------------------------------------------------------------------------------------------------------------+
```

It only appears once in the csv files:
```
cat organizations.csv/* | grep "A-LDN-36-FUNDASERIESOFAX-POAL-FUNDSLLC"
A-LDN-36-FUNDASERIESOFAX-POAL-FUNDSLLC,,,,,"A-LDN-36-Fund, a series of AX-PoAl-Funds, LLC","A-LDN-36-Fund, a series of AX-PoAl-Funds, LLC",,,,,,,,,,,,,,,,,US,001,,,,,,,,,,,,,true,false,NBB,0,0,0,0,0,false,false,false,false,true,true,false,,,,,,,,,,,,,,false,,,0,,,
```

This means that the first appearance in the neo4j result (where nameNl = "A-LDN-36-Fund, a series of AX-PoAl-Funds, LLC") is the correct one.

I tried to find a trace of where that second record came from but it seems to have been resembled from multiple records:
```
cat organizations.csv/* | grep "A-HKG-28-FUNDASERIESOFANGELLIST-BARS-FUNDSLLC"
A-HKG-28-FUNDASERIESOFANGELLIST-BARS-FUNDSLLC,,,,,"A-HKG-28-Fund, a series of AngelList-BaRs-Funds, LLC","A-HKG-28-Fund, a series of AngelList-BaRs-Funds, LLC",,,,,,,,,,,,,,,,,US,001,,,,,,,,,,,,,true,false,NBB,0,0,0,0,0,false,false,false,false,true,true,false,,,,,,,,,,,,,,false,,,0,,,
```

```
cat organizations.csv/* | grep SCHAFTFURINVESTMENTFONDSMBH
WESTINVESTGESELLSCHAFTFURINVESTMENTFONDSMBH,Düsseldorf,Konigshof Hamborner Strasse,55,40472,Westinvest Gesellschaft für Investmentfonds mbH,Westinvest Gesellschaft für Investmentfonds mbH,,,,,,,,,,,,,,,,,DE,001,,,,,,,,,,,,,true,false,NBB,0,0,0,0,0,false,false,false,false,true,true,false,,,,,,,,,,,,,,false,,,0,,,
```

**Comment by jexp** [comment]
Can you please share the CSV files with the team?

**Comment by petermartens1992** [comment]
Sure. I will have a look first if I can reproduce the error myself, both with the original csv files and with a subset of them

**Comment by petermartens1992** [comment]
Hi @jexp,

I did another test with 4.4 and this time there were 16 duplicates, but all of them were different than the first list of duplicates. Both lists have in common that the identifiers are very long (> 35 characters). About 4k of the 6M records have long identifiers so most of them are processed just fine.

Could you let me know how I can share the csv files (400MB) with the team?

**Comment by jexp** [comment]
If you can zip it and put it on gdrive/dropbox/s3 that would be great.

**Comment by petermartens1992** [comment]
Thx, I just sent the link to github@jexp.de

**Comment by tinwelint** [comment]
Hi @petermartens1992 what's the contents of the header CSV file?

**Comment by jexp** [comment]
I got them. Will add to the card.

**Comment by tinwelint** [comment]
I found the issue and a fix for it. It should be included in the next 4.4.x release.

**Comment by petermartens1992** [comment]
Many thanks @tinwelint and @jexp for this super-quick fix!

I will soon reactivate the auto-updates again in yum.

**Comment by tinwelint** [comment]
Cheers! And thanks for being responsive and for sharing the necessary data to trigger this 🙏

**Comment by liebreksmjhf** [comment]
We faced this problem massively: 2.5% of 900.000 edges got corrupt upon import using version 4.4.4.
Can you tell us when the bug was introduced? Above is stated that rollback to version 4.3.7. solved the problem. What is the latest version without this problem? Is 4.3.10 ok or maybe 4.4.3?

**Comment by tinwelint** [comment]
@liebreksmjhf the issue discussed above was fixed in 4.4.3 and it looks 4.4.0-4.4.2 has this issue. Version 4.3 never had it.

What you're seeing could be something else because it's about corrupted relationships. Could you include more details about what you mean by "corrupted"?

**Comment by liebreksmjhf** [comment]
In one of the relationshiptypes we prepared a property as an unique key. In the CSV-files at the end of the ETL pipeline this property is unique. After loading by neo4j-admin import we see 2.5% duplicates on this property. If you state it was solved in 4.4.3, is there an explanation on what we experience with 4.4.4?

**Comment by tinwelint** [comment]
@liebreksmjhf The issue was for nodes, not relationships.

I'm not sure how to help you unless I have the CSV files to reproduce on my own. Or if you could somehow provide some smaller piece of data that shows the issue. Basically you're certain that the CSV relationship data for a certain type have some property that unique across all relationships of that type and Neo4j doesn't think so after the import of that data, is that correct?

**Comment by liebreksmjhf** [comment]
I can be very certain on that. Unfortunately I cannot share the data because its sensitive.

**Comment by tinwelint** [comment]
OK then it may be hard to get to the root cause of why this happens

**Comment by liebreksmjhf** [comment]
Hi Mattias

It has turned out last friday that this observation was the result of a mistake.
True apologizes for this.
And thank you for the concerned responses.

Kind regards
Mario

**Comment by tinwelint** [comment]
@liebreksmjhf ok great, I'm happy to hear that. Cheers!
