### ISSUE TITLE
Neo.DatabaseError.Statement.ExecutionFailed is reported when executing the Cypher query: MATCH (n0),(n1) OPTIONAL MATCH (n0)--(:L0),(n1) RETURN n0 LIMIT 0

### ISSUE THREAD

**Issue by abc123000111** [neo4j/neo4j#12795]
I discovered that when I executed the following Cypher query, a database error occurred.

**Neo4j Version:** 4.3.6 Community
**Operating System:** Windows 11
**API:** Cypher/Java API

### Steps to reproduce
Execute the following Cypher query:
MATCH (n0),(n1) OPTIONAL MATCH (n0)--(:L0),(n1) RETURN n0 LIMIT 0

### Expected behavior
Return an empty result set.

### Actual behavior
**Error: Neo.DatabaseError.Statement.ExecutionFailed**
Expected 
RegularSinglePlannerQuery(QueryGraph {Nodes: ['n0', 'n1'], Optional Matches: : ['QueryGraph {Nodes: ['  UNNAMED1', 'n0', 'n1'], Rels: ['(n0)-[  UNNAMED0]-(  UNNAMED1)'], Arguments: ['n0', 'n1'], Predicates: ['`  UNNAMED1`:L0']}']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n0 -> Variable(n0)),QueryPagination(None,Some(SignedDecimalIntegerLiteral(0))),Selections(Set())),None,None) 

Instead, got: 
RegularSinglePlannerQuery(QueryGraph {Nodes: ['n0', 'n1'], Optional Matches: : ['QueryGraph {Nodes: ['  UNNAMED1', 'n0'], Rels: ['(n0)-[  UNNAMED0]-(  UNNAMED1)'], Arguments: ['n0', 'n1'], Predicates: ['`  UNNAMED1`:L0']}']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n0 -> Variable(n0)),QueryPagination(None,Some(SignedDecimalIntegerLiteral(0))),Selections(Set())),None,None)
Plan: ProduceResult(List(n0)) {
  LHS -> Limit(SignedDecimalIntegerLiteral(0)) {
    LHS -> Apply(false) {
      LHS -> CartesianProduct(false) {
        LHS -> AllNodesScan(n0, Set()) {}
        RHS -> AllNodesScan(n1, Set()) {}
      }
      RHS -> Optional(Set(n0, n1)) {
        LHS -> Expand(n0, BOTH, List(),   UNNAMED1,   UNNAMED0, ExpandInto) {
          LHS -> NodeByLabelScan(  UNNAMED1, LabelName(L0), Set(n0, n1), IndexOrderNone) {}
        }
      }
    }
  }
} 

Differences:
 - QueryGraph
    A: QueryGraph {Nodes: ['n0', 'n1'], Optional Matches: : ['QueryGraph {Nodes: ['  UNNAMED1', 'n0', 'n1'], Rels: ['(n0)-[  UNNAMED0]-(  UNNAMED1)'], Arguments: ['n0', 'n1'], Predicates: ['`  UNNAMED1`:L0']}']}
    B: QueryGraph {Nodes: ['n0', 'n1'], Optional Matches: : ['QueryGraph {Nodes: ['  UNNAMED1', 'n0'], Rels: ['(n0)-[  UNNAMED0]-(  UNNAMED1)'], Arguments: ['n0', 'n1'], Predicates: ['`  UNNAMED1`:L0']}']}

**Comment by mnd999** [comment]
Thanks for the report. That looks like a bug, we're looking at it together with #12790

**Comment by blouerat** [comment]
Hi @abc123000111,
This issue has now been fixed an backported, it will be out in the next release. Thank you for raising with us in the first place.
It looks like you have opened other similar issues, in neo4j as well as in other projects. The queries all look interesting if a bit unusual. May I ask whether you use some kind of automated generator? If so, would you be interested in discussing it with us?
We are currently working on solving what we think is the problem underlying the various issues you've found, hoping to close most of them at once.

**Comment by abc123000111** [comment]
> Hi @abc123000111, This issue has now been fixed an backported, it will be out in the next release. Thank you for raising with us in the first place. It looks like you have opened other similar issues, in neo4j as well as in other projects. The queries all look interesting if a bit unusual. May I ask whether you use some kind of automated generator? If so, would you be interested in discussing it with us? We are currently working on solving what we think is the problem underlying the various issues you've found, hoping to close most of them at once.

Thank you so much! I'm a software testing researcher currently working on finding bugs in graph databases. My collaborators and I design and implement a prototype of an automated generator and plan to publish a paper this year. We are glad that this work can help you improve the stability of Neo4j (which is awesome and well-known). We are also looking forward to your feedback, which will be the strongest support for this work. My email is weilincs@outlook.com and I look forward to further communication with you.

**Comment by abc123000111** [comment]
> Hi @abc123000111, This issue has now been fixed an backported, it will be out in the next release. Thank you for raising with us in the first place. It looks like you have opened other similar issues, in neo4j as well as in other projects. The queries all look interesting if a bit unusual. May I ask whether you use some kind of automated generator? If so, would you be interested in discussing it with us? We are currently working on solving what we think is the problem underlying the various issues you've found, hoping to close most of them at once.


Hello Bastien, 

My message wasn't delivered because your email provider rejected it. So I reply to you here:

My name is Wei Lin, a Ph. D student at Peking University. Thank you very much for your suggests, and I think they will be a great help in our research. I sincerely hope that our work can contribute to the development of Neo4j. 

We are writing the paper now. If we find new bugs in Neo4j, I will report them to you as soon as possible. It would be better if you could share with me the root-cause analysis for these reported issues. We will publish our prototype after the paper is accepted. And we are very expected that you could provide feedback about our generator design and suggest additional functionality. 

Best wishes, 
Wei

**Comment by abc123000111** [comment]
Hello Bastien,

My message wasn't delivered because your email provider rejected it.

“Delivery has failed to these recipients or groups:
Bastien Louërat (bastien.louerat@neo4j.com)
Your message wasn't delivered because the recipient's email provider rejected it.
(mailto:b.louerat@gmail.com)
Your message wasn't delivered because the recipient's email provider rejected it.”

So I reply to you here:

Hello Bastien,

I'm currently preparing for an exam, so I'm really sorry for not checking my inbox in time.

I find that although our tool can generate many failure-inducing test cases, they are sometimes trigger the same type of bug (even on different versions of Neo4j), even though we have manually filtered them. I would like to know how developers identify the root cause of bugs when debugging, which can provide me with ideas for further tool design. Thank you!

By the way, I'm curious why "return +-3" and "return --3" are valid but "return -+3" and "return ++3" are not. Cypher specifications do not detail this.

Best wishes,
Wei

**Comment by blouerat** [comment]
Hi @abc123000111 ,

I deleted your comment as it contained personal information, I'm still trying to figure what's up with the email situation, we'll get there. Bets luck with your exams hope it goes well!
Your question regarding why `+-3` and `--3` are considered valid numbers but `-+3` and `++3` are not, I don't have a good answer on top of my head, let me have a look.

Cheers,
Bastien
