### ISSUE TITLE
Neo.DatabaseError.Statement.ExecutionFailed is reported when executing the Cypher query: OPTIONAL MATCH (n0) MATCH (n0) OPTIONAL MATCH (n0) RETURN n0

### ISSUE THREAD

**Issue by abc123000111** [neo4j/neo4j#12790]
I discovered that when I executed the following Cypher query, a database error occurred.

**Neo4j Version:** 4.3.6 Community
**Operating System:** Windows 11
**API:** Cypher/Java API

### Steps to reproduce
Execute the following Cypher query:
OPTIONAL MATCH (n0) MATCH (n0) OPTIONAL MATCH (n0) RETURN n0

### Expected behavior
Return the nodes that satisfy the query.

### Actual behavior
**Error: Neo.DatabaseError.Statement.ExecutionFailed**
Expected 
RegularSinglePlannerQuery(QueryGraph {Optional Matches: : ['QueryGraph {Nodes: ['n0']}']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n0 -> Variable(n0)),QueryPagination(None,None),Selections(Set())),Some(RegularSinglePlannerQuery(QueryGraph {Nodes: ['n0'], Arguments: ['n0'], Optional Matches: : ['QueryGraph {Nodes: ['n0'], Arguments: ['n0']}']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n0 -> Variable(n0)),QueryPagination(None,None),Selections(Set())),None,None)),None) 

Instead, got: 
RegularSinglePlannerQuery(QueryGraph {Optional Matches: : ['QueryGraph {Nodes: ['n0']}']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n0 -> Variable(n0)),QueryPagination(None,None),Selections(Set())),Some(RegularSinglePlannerQuery(QueryGraph {Nodes: ['n0'], Arguments: ['n0']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n0 -> Variable(n0)),QueryPagination(None,None),Selections(Set())),None,None)),None)
Plan: ProduceResult(List(n0)) {
  LHS -> Apply(false) {
    LHS -> Apply(false) {
      LHS -> Argument(Set()) {}
      RHS -> Optional(Set()) {
        LHS -> AllNodesScan(n0, Set()) {}
      }
    }
    RHS -> Argument(Set(n0)) {}
  }
} 

Differences:
 - Tail
    A: Some(RegularSinglePlannerQuery(QueryGraph {Nodes: ['n0'], Arguments: ['n0'], Optional Matches: : ['QueryGraph {Nodes: ['n0'], Arguments: ['n0']}']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n0 -> Variable(n0)),QueryPagination(None,None),Selections(Set())),None,None))
    B: Some(RegularSinglePlannerQuery(QueryGraph {Nodes: ['n0'], Arguments: ['n0']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n0 -> Variable(n0)),QueryPagination(None,None),Selections(Set())),None,None))

**Comment by mnd999** [comment]
Thanks for the report. That looks like a bug, we'll take a look and get back to you with our findings

**Comment by hedengran** [comment]
Hi, I accidentally auto-closed this issue without leaving a response, sorry about that. 

Anyways, thank you again for the report. This is indeed a bug, and I've merged a fix in our development branch. Currently back-porting this to all effected versions and it should be included with the next patch for those versions.

**Comment by abc123000111** [comment]
> Hi, I accidentally auto-closed this issue without leaving a response, sorry about that.
> 
> Anyways, thank you again for the report. This is indeed a bug, and I've merged a fix in our development branch. Currently back-porting this to all effected versions and it should be included with the next patch for those versions.

Thanks a lot!
