### ISSUE TITLE
how to use pure java api insert node and relationship by bolt api connect ,not. cypher api ?

### ISSUE THREAD

**Issue by mullerhai** [neo4j/neo4j#12809]
HI. Neo4j Officer:
          Now. I have achieve batch insert node and relationship by use pure java api ,like createRelationshipTo()  and tx.createNode(Label.label(label)).asInstanceOf[NodeEntity], but now only can insert when the neo4j server is shutdown ,because of sock_lock,so only can make local embedded neo4j server. effect ,now I would like insert the data use the bolt api for remote server. how to do this  with pure. java api

**Comment by mnd999** [comment]
One way to do this would be to write the Java code as a [procedure](https://neo4j.com/docs/developer-manual/current/extending-neo4j/procedures/l) and invoke it remotely using CALL. Also take a look at [APOC](https://neo4j.com/developer/neo4j-apoc/), particularly the apoc.load procedures as there may already be a procedure that does what you want.

**Comment by mnd999** [comment]
As this issue has been inactive for some time I will close it. If that did not solve you're issue, please feel free to reopen.
