### ISSUE TITLE
Neo.DatabaseError.Statement.ExecutionFailed is reported when executing the Cypher query: MATCH (n0:L0) WHERE (((n0.k0) < (n0.k1)) XOR ((n0.k0) < (n0.k1))) RETURN *

### ISSUE THREAD

**Issue by abc123000111** [neo4j/neo4j#12817]
I discovered that when I executed the following Cypher query, a database error occurred.

**Neo4j Version:** 4.4.3 Community
**Operating System:** Windows 11
**API:** Cypher / Java API

### Steps to reproduce
Execute the following Cypher query:
MATCH (n0:L0) WHERE (((n0.k0) < (n0.k1)) XOR ((n0.k0) < (n0.k1))) RETURN *

### Expected behavior
Return the result set that satisfy the query.

### Actual behavior
**ERROR: Neo.DatabaseError.Statement.ExecutionFailed**
Expected 
RegularSinglePlannerQuery(QueryGraph {Nodes: ['n0'], Predicates: ['n0:L0', 'n0.k0 < n0.k1 OR n0.k0 < n0.k1', 'n0.k0 >= n0.k1 OR n0.k0 >= n0.k1']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n0 -> Variable(n0)),QueryPagination(None,None),Selections(Set())),None,None) 

Instead, got: 
RegularSinglePlannerQuery(QueryGraph {Nodes: ['n0'], Predicates: ['n0:L0', 'n0.k0 < n0.k1', 'n0.k0 < n0.k1 OR n0.k0 < n0.k1', 'n0.k0 >= n0.k1 OR n0.k0 >= n0.k1']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n0 -> Variable(n0)),QueryPagination(None,None),Selections(Set())),None,None)
Plan: ProduceResult(List(n0)) {
  LHS -> Selection(Ands(Vector(Ors(List(LessThan(Property(Variable(n0),PropertyKeyName(k0)),Property(Variable(n0),PropertyKeyName(k1))), LessThan(Property(Variable(n0),PropertyKeyName(k0)),Property(Variable(n0),PropertyKeyName(k1))))), Ors(List(GreaterThanOrEqual(Property(Variable(n0),PropertyKeyName(k0)),Property(Variable(n0),PropertyKeyName(k1))), GreaterThanOrEqual(Property(Variable(n0),PropertyKeyName(k0)),Property(Variable(n0),PropertyKeyName(k1)))))))) {
    LHS -> Distinct(Map(n0 -> Variable(n0))) {
      LHS -> Union() {
        LHS -> Selection(Ands(Vector(LessThan(Property(Variable(n0),PropertyKeyName(k0)),Property(Variable(n0),PropertyKeyName(k1)))))) {
          LHS -> NodeByLabelScan(n0, LabelName(L0), Set(), IndexOrderNone) {}
        }
        RHS -> Selection(Ands(Vector(LessThan(Property(Variable(n0),PropertyKeyName(k0)),Property(Variable(n0),PropertyKeyName(k1)))))) {
          LHS -> NodeByLabelScan(n0, LabelName(L0), Set(), IndexOrderNone) {}
        }
      }
    }
  }
} 

Differences:
 - QueryGraph
    A: QueryGraph {Nodes: ['n0'], Predicates: ['n0:L0', 'n0.k0 < n0.k1 OR n0.k0 < n0.k1', 'n0.k0 >= n0.k1 OR n0.k0 >= n0.k1']}
    B: QueryGraph {Nodes: ['n0'], Predicates: ['n0:L0', 'n0.k0 < n0.k1', 'n0.k0 < n0.k1 OR n0.k0 < n0.k1', 'n0.k0 >= n0.k1 OR n0.k0 >= n0.k1']}

**Comment by mnd999** [comment]
Thanks for the report, this does look like a bug. We'll investigate and let you know when we have a fix.

**Comment by hedengran** [comment]
Hi and thanks again for the report. This is indeed a bug. A fix has now been merged  and I'm in the process of backporting the fix to all older supported versions as well.
