### ISSUE TITLE
Feature request: Index-backed ORDER BY without WHERE clause

### ISSUE THREAD

**Issue by maiieul** [neo4j/neo4j#12812]
**Is your feature request related to a problem? Please describe.**

Currently, we have to add a where clause if we want an index-backed ORDER BY to work properly, even when the WHERE clause is not needed. It's not easy to understand at first, especially since the syntax is a bit hidden in the docs: https://neo4j.com/docs/cypher-manual/current/query-tuning/advanced-example/#advanced-query-tuning-example-index-backed-order-by

Right now, with an `INDEX FOR (p:Post) ON (p.numberOfUpvotes)`, the following query

``` 
MATCH (p:Post)
RETURN p
ORDER BY p.numberOfUpvotes DESC
```
does a NodeByLabelScan.

While the following query

``` 
MATCH (p:Post)
WHERE p.numberOfUpvotes IS NOT NULL
RETURN p
ORDER BY p.numberOfUpvotes DESC
```
does a NodeIndexScan.

I just added the `WHERE` clause to take advantage of the index, but it's not really needed.

And when I add a `LIMIT 10` to these queries, and I go from 30 000 db hits to 82, with a 10 000 Post nodes dataset.

**Describe the solution you'd like**

I'd like the following query
``` 
MATCH (p:Post)
RETURN p
ORDER BY p.numberOfUpvotes DESC
```
to take advantage of the index. Any query that orders by an indexed property should take advantage of the index just like when I add the `WHERE` clause, shouldn't it?

Queries ran on neo4j Aura version 4.4.0.

**Comment by burqen** [comment]
@maieulChevalier Thank you for reporting!
Short answer
If you add existence constraint on Post(numberOfUpvotes) Cypher will know to use the index without explicitly adding `IS NOT NULL` where clause every time.
`CREATE CONSTRAINT FOR (n:Post) REQUIRE n.numberOfUpvotes IS NOT NULL`

Long answer
Here is the problem: The semantics of Cypher is such that `ORDER BY` does not exclude null values. So if you have `Post` nodes without `numberOfUpvoted`, they should still be included in the result. The index however, does not store nodes that doesn't have the property which means the full result set for the query cannot be given by the index, unless you add the `IS NOT NULL` part. If your domain is such that `Post` nodes always have `numberOfUpvotes` you can add an existence constraint. This will help Cypher to know that it can use the index without risking missing anything. If Post nodes can be without that property, for now you are stuck with the where clause.

There are a few other solutions to this problem on the product side, that is not implemented currently:
- Make it possible to also include null values in the index
- Improve statistics such that we can know that it's safe to use the index even without the where clause (very very difficult for concurrency reasons)

**Comment by maiieul** [comment]
Thank you for your reply @burqen. I understand the issue now. 

Actually I should have implemented the existence constraint anyway so I will go for this solution on my side. Maybe the docs should explain the issue a little bit and hint to the existence constraint solution.

**Comment by burqen** [comment]
@maieulChevalier Yes, that's a good suggestion. I will pass it forward to the documentations team 👍 
Are you ok with me closing this issue for now?
