### ISSUE TITLE
The transaction has been closed.

### ISSUE THREAD

**Issue by wangcccchen** [neo4j/neo4j#12811]
I have successfully executed the command shown in the figure below several times, but when I execute it again, an error is reported.
![image](https://user-images.githubusercontent.com/70743874/148482276-f455f935-334e-4690-b27b-d2c237ecc8eb.png)
Looking forward to your reply

**Comment by mnd999** [comment]
Thanks for the report - is there anything relating to this error in neo4j.log or debug.log on the server?

**Comment by mnd999** [comment]
I have not heard anything back on this issue for some time, so will close for now. Please feel free to reopen if it is still an issue.
