### ISSUE TITLE
Index being used but not efficient with multiple Index-backed ORDER BYs

### ISSUE THREAD

**Issue by maiieul** [neo4j/neo4j#12813]
## Example bug report

I found odd behavior when using multiple index-backed `ORDER BY`.

With 2 indexes for `(p:Post)` on `(p.numberOfUpvotes)` and `(p.numberOfViews)`, with a 10 000 posts dataset,

This first query
```
profile 
MATCH (p:Post)
WHERE p.numberOfUpvotes is not null AND p.numberOfViews is not null
RETURN p
ORDER BY p.numberOfUpvotes DESC
LIMIT 10
```

gives following profile output
![neo4jbug2](https://user-images.githubusercontent.com/45822175/148661789-b949abea-1454-491c-99ae-588b700e67bc.png)

Which works as intended.

But this second query

```
profile 
MATCH (p:Post)
WHERE p.numberOfUpvotes is not null AND p.numberOfViews is not null
RETURN p
ORDER BY p.numberOfUpvotes DESC, p.numberOfViews DESC
LIMIT 10
```

gives following profile output
![neo4jbug1](https://user-images.githubusercontent.com/45822175/148661741-6f74de62-ead5-474d-8908-22543c4bb14a.png)

which doesn't seem to really take advantage of the index.

**Neo4j Version:** 4.4.0 on Neo4j Aura
**Operating System:** Linux Mint 20.1 Cinnamon
**API:** Neo4j Browser

### Steps to reproduce

1. Start up a neo4j aura free instance
2. Open neo4j browser from the aura console
3. Run following query to populate database
```
FOREACH (n IN range(1, 10000) | 
CREATE (p:Post{id:apoc.create.uuid(), title:toString(n), numberOfUpvotes:1, numberOfViews:1})
```
4. Run the queries above

### Expected behavior

The second query with two index-backed ORDER BY should do approximately the same number of db hits as the first query with only one index-backed ORDER BY.

### Actual behavior

The second query does 30 000 db hits while the first one only does a 100 db hits. Maybe this could be solved by implementing #12812.

**Comment by mnd999** [comment]
I see someone responded to this issue on #12812, does that resolve this one?

**Comment by maiieul** [comment]
@mnd999 Hmmm I don't think it does. The issue here is that the second query does a NodeIndexScan like the first query, so the index is used in both cases, but it doesn't seem to be used properly in the second query, since there are so many db hits.

**Comment by maiieul** [comment]
I found a workaround:
```
MATCH (p:Post)
WHERE p.numberOfUpvotes is not null
WITH p
ORDER BY p.numberOfUpvotes DESC
LIMIT 10
RETURN p
ORDER BY p.numberOfUpvotes DESC, p.numberOfViews DESC
```
It effectively uses the index for `p.numberOfUpvotes` and then applies the `ORDER BY` with `p.numberOfViews DESC`.

Still I think that it should work properly without this workaround, shouldn't it?

**Comment by arnefischereit** [comment]
Hi @maieulChevalier,
Thank you for raising this issue.

## What happens in this case?
I have had a look at your case and it looks to me that the effect you are seeing comes from the very particular data in your graph: Both `numberOfUpvotes` and `numberOfViews` are constant.

The index can guarantee us that the results are ordered with regards to the properties the index is based on. In the first case, we therefore know that the index on `numberOfUpvotes` returns the rows in the correct order, such that we do not need to sort again.

In the second case, we know that the rows are sorted with respect to `numberOfUpvotes` but we also want to sort all rows with the same value for `numberOfUpvotes` with respect for `numberOfViews`. As all rows have the same value for `numberOfUpvotes`, we therefore need to sort all rows again.

## Possible remedy
In this particular case, we could have looked at the index and see that the properties are constant and therefore skip sorting. But the case that one has constant values and asks to sort by them is so unusual that there is very little use for this optimization.

What would have worked, is to define one composite index on both properties (watch out to define them in the correct order). That one can again provide us with an order on all properties at once.

## Your workaround
The workaround that you have posted is unfortunately not equivalent to what the planner needs to solve. Let's assume that your data was not as uniform across all the properties as it is in your example and we would get the largest values for `numberOfViews` last. Then we would only scan the first 10 rows, limit there and sort these in accordance with `numberOfViews`.

That is, if the intermediate table was:
| `numberOfUpvotes` | `numberOfViews` |
| --: | --: |
| 1 | 1 |
| 1 | 2 |
| ... | ... |
| 1 | 9999 |
| 1 | 10000 |

The right result would be:

| `numberOfUpvotes` | `numberOfViews` |
| --: | --: |
| 1 | 10000 |
| 1 | 9999 |
| ... | ... |
| 1 | 9992 |
| 1 | 9991 |

The result of your workaround query would be:

| `numberOfUpvotes` | `numberOfViews` |
| --: | --: |
| 1 | 10 |
| 1 | 9 |
| ... | ... |
| 1 | 2 |
| 1 | 1 |


I hope this clears it up. Let me know if you have any questions.

**Comment by maiieul** [comment]
@arnefischereit thank you for your thorough explanation. 

This was supposed to be Mock data and I now realise it was not very realistic to set all values to 1. It's true that sorting by similar values twice doesn't really make sense... Everything works as expected when trying with more realistic values.

And thanks also for pointing out that my workaround wasn't even valid :smile: 

I'm closing the issue since you've solved it. I understand it's not very useful to optimize neo4j for such a use case.
