### ISSUE TITLE
The following two Cypher queries will trigger database errors

### ISSUE THREAD

**Issue by abc123000111** [neo4j/neo4j#12818]
Hi, I discovered that the following two Cypher queries will trigger database errors (Neo.DatabaseError.Statement.ExecutionFailed). I wonder that if they are the same bug. Thank you!

**Neo4j Version:** 4.4.3 Community
**Operating System:** Windows 11
**API:** Cypher / Java API

### Steps to reproduce
Executing each of the following queries will trigger a database error:
OPTIONAL MATCH (n1), (n2)<--(n3) MATCH (n2)<-[r1 *]-(n4:L0), (n1) RETURN *
OPTIONAL MATCH (n3)<--(n4) MATCH (n4), (n3)-[r3 *]-(n5) MATCH (n5)--(n6) RETURN *

### Expected behavior
No error occurred.

### Actual behavior
**The first query will trigger an error as follows:**
Expected 
RegularSinglePlannerQuery(QueryGraph {Optional Matches: : ['QueryGraph {Nodes: ['n1', 'n2', 'n3'], Rels: ['(n2)<-[  UNNAMED0]-(n3)']}']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n1 -> Variable(n1), n2 -> Variable(n2), n3 -> Variable(n3)),QueryPagination(None,None),Selections(Set())),Some(RegularSinglePlannerQuery(QueryGraph {Nodes: ['n1', 'n2', 'n4'], Rels: ['(n2)<-[r1*]-(n4)'], Arguments: ['n1', 'n2', 'n3'], Predicates: ['n4:L0']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n2 -> Variable(n2), n1 -> Variable(n1), r1 -> Variable(r1), n4 -> Variable(n4), n3 -> Variable(n3)),QueryPagination(None,None),Selections(Set())),None,None)),None) 

Instead, got: 
RegularSinglePlannerQuery(QueryGraph {Optional Matches: : ['QueryGraph {Nodes: ['n1', 'n2', 'n3'], Rels: ['(n2)<-[  UNNAMED0]-(n3)']}']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n1 -> Variable(n1), n2 -> Variable(n2), n3 -> Variable(n3)),QueryPagination(None,None),Selections(Set())),Some(RegularSinglePlannerQuery(QueryGraph {Nodes: ['n2', 'n4'], Rels: ['(n2)<-[r1*]-(n4)'], Arguments: ['n1', 'n2', 'n3'], Predicates: ['n4:L0']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n2 -> Variable(n2), n1 -> Variable(n1), r1 -> Variable(r1), n4 -> Variable(n4), n3 -> Variable(n3)),QueryPagination(None,None),Selections(Set())),None,None)),None)
Plan: ProduceResult(List(n1, n2, n3, n4, r1)) {
  LHS -> Apply(false) {
    LHS -> Apply(false) {
      LHS -> Argument(Set()) {}
      RHS -> Optional(Set()) {
        LHS -> CartesianProduct(false) {
          LHS -> AllNodesScan(n1, Set()) {}
          RHS -> Expand(n2, INCOMING, List(), n3,   UNNAMED0, ExpandAll) {
            LHS -> AllNodesScan(n2, Set()) {}
          }
        }
      }
    }
    RHS -> VarExpand(n2, INCOMING, INCOMING, List(), n4, r1, VarPatternLength(1,None), ExpandInto, None, None) {
      LHS -> NodeByLabelScan(n4, LabelName(L0), Set(n1, n2, n3), IndexOrderNone) {}
    }
  }
} 

Differences:
 - Tail
    A: Some(RegularSinglePlannerQuery(QueryGraph {Nodes: ['n1', 'n2', 'n4'], Rels: ['(n2)<-[r1*]-(n4)'], Arguments: ['n1', 'n2', 'n3'], Predicates: ['n4:L0']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n2 -> Variable(n2), n1 -> Variable(n1), r1 -> Variable(r1), n4 -> Variable(n4), n3 -> Variable(n3)),QueryPagination(None,None),Selections(Set())),None,None))
    B: Some(RegularSinglePlannerQuery(QueryGraph {Nodes: ['n2', 'n4'], Rels: ['(n2)<-[r1*]-(n4)'], Arguments: ['n1', 'n2', 'n3'], Predicates: ['n4:L0']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n2 -> Variable(n2), n1 -> Variable(n1), r1 -> Variable(r1), n4 -> Variable(n4), n3 -> Variable(n3)),QueryPagination(None,None),Selections(Set())),None,None))

**The second query will trigger an error as follows:**
Expected 
RegularSinglePlannerQuery(QueryGraph {Optional Matches: : ['QueryGraph {Nodes: ['n3', 'n4'], Rels: ['(n3)<-[  UNNAMED0]-(n4)']}']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n3 -> Variable(n3), n4 -> Variable(n4)),QueryPagination(None,None),Selections(Set())),Some(RegularSinglePlannerQuery(QueryGraph {Nodes: ['n3', 'n4', 'n5', 'n6'], Rels: ['(n3)-[r3*]-(n5)', '(n5)-[  UNNAMED1]-(n6)'], Arguments: ['n3', 'n4']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n5 -> Variable(n5), n4 -> Variable(n4), r3 -> Variable(r3), n6 -> Variable(n6), n3 -> Variable(n3)),QueryPagination(None,None),Selections(Set())),None,None)),None) 

Instead, got: 
RegularSinglePlannerQuery(QueryGraph {Optional Matches: : ['QueryGraph {Nodes: ['n3', 'n4'], Rels: ['(n3)<-[  UNNAMED0]-(n4)']}']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n3 -> Variable(n3), n4 -> Variable(n4)),QueryPagination(None,None),Selections(Set())),Some(RegularSinglePlannerQuery(QueryGraph {Nodes: ['n3', 'n5', 'n6'], Rels: ['(n3)-[r3*]-(n5)', '(n5)-[  UNNAMED1]-(n6)'], Arguments: ['n3', 'n4']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n5 -> Variable(n5), n4 -> Variable(n4), r3 -> Variable(r3), n6 -> Variable(n6), n3 -> Variable(n3)),QueryPagination(None,None),Selections(Set())),None,None)),None)
Plan: ProduceResult(List(n3, n4, n5, n6, r3)) {
  LHS -> Apply(false) {
    LHS -> Apply(false) {
      LHS -> Argument(Set()) {}
      RHS -> Optional(Set()) {
        LHS -> Expand(n3, INCOMING, List(), n4,   UNNAMED0, ExpandAll) {
          LHS -> AllNodesScan(n3, Set()) {}
        }
      }
    }
    RHS -> VarExpand(n3, BOTH, OUTGOING, List(), n5, r3, VarPatternLength(1,None), ExpandInto, None, None) {
      LHS -> Expand(n5, BOTH, List(), n6,   UNNAMED1, ExpandAll) {
        LHS -> AllNodesScan(n5, Set(n3, n4)) {}
      }
    }
  }
} 

Differences:
 - Tail
    A: Some(RegularSinglePlannerQuery(QueryGraph {Nodes: ['n3', 'n4', 'n5', 'n6'], Rels: ['(n3)-[r3*]-(n5)', '(n5)-[  UNNAMED1]-(n6)'], Arguments: ['n3', 'n4']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n5 -> Variable(n5), n4 -> Variable(n4), r3 -> Variable(r3), n6 -> Variable(n6), n3 -> Variable(n3)),QueryPagination(None,None),Selections(Set())),None,None))
    B: Some(RegularSinglePlannerQuery(QueryGraph {Nodes: ['n3', 'n5', 'n6'], Rels: ['(n3)-[r3*]-(n5)', '(n5)-[  UNNAMED1]-(n6)'], Arguments: ['n3', 'n4']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n5 -> Variable(n5), n4 -> Variable(n4), r3 -> Variable(r3), n6 -> Variable(n6), n3 -> Variable(n3)),QueryPagination(None,None),Selections(Set())),None,None))

**Comment by mnd999** [comment]
Thanks for the report, I tried both of these queries on 4.4.3 and they planned okay for me. To diagnose things further we would need to know a little more about the database itself such as the amount of data, and any indexes or constraints that are present that could influence the behaviour of the planner. 
One way to do this would be to run `call db.stats.retrieve("GRAPH COUNTS")` and share the results with us here. If you are not comfortable sharing that here then please provide as much information as you can about indexes and node / label counts for nodes and labels involved in the query.

**Comment by abc123000111** [comment]
> Thanks for the report, I tried both of these queries on 4.4.3 and they planned okay for me. To diagnose things further we would need to know a little more about the database itself such as the amount of data, and any indexes or constraints that are present that could influence the behaviour of the planner. One way to do this would be to run `call db.stats.retrieve("GRAPH COUNTS")` and share the results with us here. If you are not comfortable sharing that here then please provide as much information as you can about indexes and node / label counts for nodes and labels involved in the query.

Thanks a lot! I upload the retrieved data after running  `call db.stats.retrieve("GRAPH COUNTS")` :
[GRAPH COUNTS.txt](https://github.com/neo4j/neo4j/files/7867079/GRAPH.COUNTS.txt)

![image](https://user-images.githubusercontent.com/34190313/149438051-f866a527-5d0c-4d50-8a11-01630f47c456.png)

**Comment by inmost-light** [comment]
Hi @abc123000111, thanks for reporting.

This bug affects queries that match on a single node pattern with already bound variable, like `n1` in your first query. A fix has been implemented and should be available in the next patch release.

Until then, an easy workaround is to just omit such patterns, which are redundant and shouldn't affect the result:

```
OPTIONAL MATCH (n1), (n2)<--(n3)
MATCH (n2)<-[r1 *]-(n4:L0) // , (n1) is unnecessary here
RETURN *
```
