### ISSUE TITLE
bug of gremlin api "has()"

### ISSUE THREAD

**Issue by choeoe** [neo4j/neo4j#12827]
- Neo4j version: X.Y.Z
- Operating system: (for example Windows 95/Ubuntu 16.04)
- API/Driver: (for example Cypher/Java API/Python driver vX.Y.Z)
- **Steps to reproduce**
- Expected behavior
- Actual behavior

## bug

Error occurred when querying "has()" on properties if the data has INFINITY field.

**Neo4j Version:** 3.2.3 tinkerpop:3.4.10
**Operating System:** windows wsl
**API:** gremlin

### Steps to reproduce
Vertex alice = g.addV("person").property("hair", Double.POSITIVE_INFINITY ).next();
Vertex bob = g.addV("person").property("hair", 500 ).next();

String query =“g.V().has('hair',500.00)”;

### Expected behavior
return the certain vertex

### Actual behavior
java.util.concurrent.ExecutionException: org.apache.tinkerpop.gremlin.driver.exception.ResponseException: Character I is neither a decimal digit number, decimal point, nor "e" notation exponential mark.

**Comment by mnd999** [comment]
Thanks for the report. I'm not very familiar with the Tinkerpop gremlin driver, but it appears to be translating the query to Cypher, resulting in a parsing error. Is it possible to provide an example of the generated Cypher created by the gremlin driver so that w can narrow down where the issue is?

**Comment by mnd999** [comment]
Closing as we haven't heard anything on this issue for some time, also Neo4j 3.2.3 is no longer supported. Feel free to reopen if it's still an issue in a supported version of Neo4j
