### ISSUE TITLE
How to get node's id with cypher request?

### ISSUE THREAD

**Issue by longtran84** [neo4j/neo4j#12829]
{
  "identity": 10,
  "start": 176457,
  "end": 1,
  "type": "WORKS_AT",
  "properties": {

  }
}

how i can get value all that fields?

**Comment by mnd999** [comment]
Thanks for your question, to return the id of a node or relationship, use the `id()` [function](https://neo4j.com/docs/cypher-manual/current/functions/scalar/#functions-id). e.g `MATCH (n) RETURN id(n)`.

Generally we prefer to answer these types of questions in [our community forums](https://community.neo4j.com/) or on our [discord](https://discord.gg/neo4j) and you will likely get a faster response there. Github is more setup for bug reports in the product.

**Comment by mnd999** [comment]
Closing this issue as it's been open for a while. If it's still an issue, please feel free to reopen.
