### ISSUE TITLE
Wrong datetime format with timezone id after toString

### ISSUE THREAD

**Issue by stefanak-michal** [neo4j/neo4j#12826]
- Neo4j version: 4.4.3
- Operating system: Windows 10 x64
- API/Driver: Browser

## Bug report

I discovered when you execute this query with toString on datetime with timezone id you will get wrong format of date as result.

```cypher
RETURN toString(datetime('2022-01-15T18:38:24.641300[Asia/Makassar]'))
```

## Current result:
```
2022-01-15T18:38:24.6413+08:00[Asia/Makassar]
```

## Expected result:

```
2022-01-15T18:38:24.6413[Asia/Makassar]
```

**Comment by HannesSandberg** [comment]
Thanks for the report. We'll take a look and get back to you.

**Comment by OliviaYtterbrink** [comment]
This is working as intended.
The result with the offset is the correct output as shown here https://neo4j.com/docs/cypher-manual/current/functions/string/#functions-tostring
