### ISSUE TITLE
Help deciphering "Tried to put multiple groups with same type" error message

### ISSUE THREAD

**Issue by chasemc** [neo4j/neo4j#12824]
I'm not sure this is a bug because the error message seems to be arising at the conditional https://github.com/neo4j/neo4j/blob/4fe5e8b568b8f399193e2c8e74e56f8fb17ca82a/community/record-storage-engine/src/main/java/org/neo4j/internal/batchimport/RelationshipGroupCache.java#L201

```
IMPORT FAILED in 44m 50s 527ms. 
  3559494 nodes
  500726004 relationships
  4997255236 properties
Peak memory usage: 652.6MiB
Import error: Tried to put multiple groups with same type 5 for node 2506441
Caused by:Tried to put multiple groups with same type 5 for node 2506441
java.lang.IllegalStateException: Tried to put multiple groups with same type 5 for node 2506441
        at org.neo4j.internal.batchimport.RelationshipGroupCache.scanForFreeFrom(RelationshipGroupCache.java:200)
        at org.neo4j.internal.batchimport.RelationshipGroupCache.put(RelationshipGroupCache.java:170)
        at org.neo4j.internal.batchimport.CacheGroupsStep.process(CacheGroupsStep.java:54)
        at org.neo4j.internal.batchimport.CacheGroupsStep.process(CacheGroupsStep.java:33)
        at org.neo4j.internal.batchimport.staging.ProcessorStep.lambda$receive$1(ProcessorStep.java:84)
        at org.neo4j.internal.batchimport.executor.DynamicTaskExecutor$Processor.run(DynamicTaskExecutor.java:220)
        at java.base/java.lang.Thread.run(Thread.java:829)
```
However I am at a loss at what is causing the issue and since there's ~70GB of the relationship TYPE I was trying to import I'm not sure where to start other than the Exception message. 

**Neo4j Version:** Docker- neo4j:4.3.7
**Operating System:** Ubuntu 20.04.3 LTS  
**RAM:** 62.7 GiB
**Processor:** AMD® Ryzen 9 3900xt 12-core processor × 24 
**API:** Docker

Using admin import (node and relationship lines removed in code below):
```
docker run --interactive --rm \
    --publish=7474:7474 --publish=7687:7687 \
    --volume="${1}/data:/var/lib/neo4j/data" \
    --volume="${1}/import:/var/lib/neo4j/import" \
    --volume="${1}/plugins:/var/lib/neo4j/plugins" \
    --volume="${1}/import.report:/var/lib/neo4j/import.report" \
    --user=$(id -u):$(id -g) \
        neo4j:4.3.7 \
            neo4j-admin import \
            ... \
               --delimiter="\t" \
               --high-io=true \
               --processors=20 \
               --database=neo4j \
               --ignore-empty-strings=true \
               --ignore-extra-columns=true \
               --skip-bad-relationships \
               --skip-duplicate-nodes
```
Currently running import again with ~half the data of that relationship type...

**Comment by chasemc** [comment]
Note- that relationship is broken into ~2GB files and * expansion used in the `--relationships` flag

**Comment by tinwelint** [comment]
@chasemc you seem to have hit a bug in the importer. Could you try to run this with `--verbose` option and provide the output here?

**Comment by chasemc** [comment]
I don't have the input, but am planning on regenerating it tonight anyways. Will see if the error occurs again

**Comment by chasemc** [comment]
Update: Didn't get to this the other day.....regenerating tonight

**Comment by tinwelint** [comment]
No news?

**Comment by chasemc** [comment]
Just finished regenerating the data and importing and it worked so it seems like it was irreproducible or the previous data was somehow corrupted.

**Comment by chasemc** [comment]
This is likely not the last dataset like this I'll be generating so I'll keep watch for this error
