### ISSUE TITLE
Different results are returned when excuting the same queries on different versions of Neo4j

### ISSUE THREAD

**Issue by abc123000111** [neo4j/neo4j#12834]
I discovered that when I execute the following queries, Neo4j 4.1.11 returns no records, but Neo4j 3.5.30 returns one record.
```
CREATE (n0 :L2);
CREATE (n1 :L0);
CREATE (n2 :L5);
CREATE (n3 :L4{k24:false, k26:''});
CREATE (n4 :L4);
CREATE (n5 :L4);
CREATE (n6 :L0{k1:false});
CREATE (n7 :L0{k2:false});
CREATE (n8 :L0{k5:'P26ZRqY'});
CREATE (n9 :L2{k17:'K0'});
CREATE (n10 :L4{k24:false, k29:''});
CREATE (n11 :L0{k2:true, k4:true, k5:'EFq9'});
CREATE (n12 :L0);
OPTIONAL MATCH (n2) WHERE (((n2.k30) < (n2.k31)) AND ((n2.k30) >= (n2.k30))) WITH n2 MATCH (n2)<-[r2 :T3 *..2]-(n3) RETURN 1;
```

**Neo4j Version:** 4.1.11 , 3.5.30 Community
**Operating System:** Windows 11
**API:** Cypher / Java API

### Steps to reproduce
1. Start Neo4j 4.1.11 and 3.5.30, respectively.
2. Execute the mentioned queries on each version.
3. Compare the result sets

### Expected behavior
The result sets are the same.

### Actual behavior
Neo4j 4.1.11 : no records
![plan](https://user-images.githubusercontent.com/34190313/151538100-232c7f57-ee9a-4e3f-85b5-b66a52b83f4a.png)

Neo4j 3.5.30: 1 record
![plan (1)](https://user-images.githubusercontent.com/34190313/151538113-b3d8c3e2-68a5-4a54-a60b-3cce83fa87f2.png)

**Comment by abc123000111** [comment]
Another example:

I discovered that when I execute the following queries, Neo4j 4.1.11 returns no records, but Neo4j 3.5.30 returns one record.
```
CREATE (n0 :L0{k5:false, k6:'9'});
CREATE (n1 :L3{k18:-1557897252});
CREATE (n2 :L0{k5:false});
CREATE (n3 :L2{k17:true});
CREATE (n4 :L1{k7:2054791578});
CREATE (n5 :L0{k2:'3xJD', k3:-1557402173});
CREATE (n6 :L4);
CREATE (n7 :L2{k15:false});
CREATE (n8 :L0{k2:'x'});
CREATE (n9 :L2{k14:true});
CREATE (n10 :L4);
CREATE (n11 :L4{k27:false});
CREATE (n12 :L2{k13:'bS', k17:false});
CREATE (n13 :L1);
CREATE (n14 :L2{k12:-1557897252});
CREATE (n15 :L4);
CREATE (n16 :L2{k15:true});
CREATE (n17 :L4{k30:-1557402173});
MATCH (n7 :L2{k15:false}), (n4 :L1{k7:2054791578}) MERGE (n7)-[r0 :T3{k58:true}]->(n4);
OPTIONAL MATCH (n4:L0)<-[r3]-(n5) WITH DISTINCT n5 MATCH (n5)<-[r4 *]-(n6) RETURN *;
```

**Neo4j Version:** 4.1.11 , 3.5.30 Community
**Operating System:** Windows 11
**API:** Cypher / Java API

### Steps to reproduce
1. Start Neo4j 4.1.11 and 3.5.30, respectively.
2. Execute the mentioned queries on each version.
3. Compare the result sets

### Expected behavior
The result sets are the same.

### Actual behavior
Neo4j 4.1.11 : no records
![plan](https://user-images.githubusercontent.com/34190313/151684646-088143e9-a818-4b83-a8ae-b8c305f5aa23.png)

Neo4j 3.5.30: 1 record
![plan (1)](https://user-images.githubusercontent.com/34190313/151684658-c62b0a04-7eb6-4fa5-9bdd-1b42f1208376.png)

**Comment by HannesSandberg** [comment]
Thanks! We will look into this and get back to you.

**Comment by inmost-light** [comment]
See the comment in #12818.
