### ISSUE TITLE
Executing the same Cypher queries on different versions of Neo4j returns different results. 

### ISSUE THREAD

**Issue by abc123000111** [neo4j/neo4j#12836]
I discovered that when I execute the following queries, Neo4j 4.1.11 returns 23328 records, but Neo4j 3.5.30 returns 1296 records.
```
CREATE (n0 :L2{k14:'fE22Vohvp', k16:802951021, k18:'vk', k19:'3'});
CREATE (n1 :L0{k1:'1Mid'});
CREATE (n2 :L4{k31:true});
CREATE (n3 :L4);
CREATE (n4 :L5{k36:-614691823});
CREATE (n5 :L1{k9:'FG4', k10:'W'});
CREATE (n6 :L3);
CREATE (n7 :L0{k3:-1652259316, k6:9223372036854775807});
CREATE (n8 :L2{k20:'h'});
CREATE (n9 :L4{k28:'', k29:-1652259316});
CREATE (n10 :L3);
CREATE (n11 :L3{k22:'y'});
CREATE (n12 :L0);
CREATE (n13 :L0{k5:true});
CREATE (n14 :L4{k27:false});
CREATE (n15 :L3{k22:'tQDMW'});
CREATE (n16 :L5{k33:'ZMXi'});
CREATE (n17 :L0{k1:'QhYCS4', k5:false});
MATCH (n0 :L2{k14:'fE22Vohvp', k16:802951021, k18:'vk', k19:'3'}), (n1 :L0{k1:'1Mid'}) MERGE (n0)<-[r0 :T2{k58:-77303411}]-(n1);
MATCH (n5 :L1{k9:'FG4', k10:'W'}), (n7 :L0{k3:-1652259316, k6:9223372036854775807}) MERGE (n5)-[r1 :T0{k47:'2oS2x6n'}]->(n7);
MATCH (n7 :L0{k3:-1652259316, k6:9223372036854775807}), (n13 :L0{k5:true}) MERGE (n7)-[r2 :T2{k59:true}]->(n13);
MATCH (n9 :L4{k28:'', k29:-1652259316}), (n14 :L4{k27:false}) MERGE (n9)<-[r3 :T3{k64:514326225}]-(n14);
MATCH (n14 :L4{k27:false}), (n17 :L0{k1:'QhYCS4', k5:false}) MERGE (n14)<-[r4 :T2{k55:true}]-(n17);
MATCH (n16 :L5{k33:'ZMXi'}), (n9 :L4{k28:'', k29:-1652259316}) MERGE (n16)-[r5 :T1{k52:'GMjyPu'}]->(n9);
MATCH (n1) OPTIONAL MATCH (n3) WITH DISTINCT * MATCH (n1), (n5 :L5) OPTIONAL MATCH (n6 :L5), (n1) RETURN 0
```

**Neo4j Version:** 4.1.11 , 3.5.30 Community
**Operating System:** Windows 11
**API:** Cypher / Java API

### Steps to reproduce
1. Start Neo4j 4.1.11 and 3.5.30, respectively.
2. Execute the mentioned queries on each version.
3. Compare the result sets

### Expected behavior
The result sets are the same.

### Actual behavior
Neo4j 4.1.11 : 23328 records
![plan (3)](https://user-images.githubusercontent.com/34190313/151684934-15dddb64-e15b-4152-ae90-a8ff94753496.png)

Neo4j 3.5.30: 1296 records
![plan (2)](https://user-images.githubusercontent.com/34190313/151684931-61e44b46-a6ba-4178-9702-188dfcf0e635.png)

**Comment by HannesSandberg** [comment]
Thanks, we will take a look and come back to you.

**Comment by arnefischereit** [comment]
Hi @abc123000111,

We have looked into this issue and this is the same issue as reported in #12831, resulting in 4.1 returning the wrong number of results.

As 4.1 is [not supported anymore](https://neo4j.com/developer/kb/neo4j-supported-versions/), we will not provide a bugfix for this issue but ask you to upgrade to 4.4.9.

I am closing this issue. Should the problem persist on a supported version (after the release of 4.4.9) or reappear, please reopen this issue or open a new one.

Regards,  

Arne
