### ISSUE TITLE
When executing the same queries, different versions of Neo4j return different results

### ISSUE THREAD

**Issue by abc123000111** [neo4j/neo4j#12832]
I discovered that when I execute the following queries, Neo4j 4.4.3 returns 13 records, and Neo4j 4.2.14 returns 65 records.
```
CREATE (n0 :L3{k20:-589908657, k24:true, k25:false});
CREATE (n1 :L2);
CREATE (n2 :L2{k14:true, k17:'aE', k19:-1427022695});
CREATE (n3 :L2{k14:false, k18:-1603461604});
CREATE (n4 :L2{k14:false, k15:'lY3', k16:-1072711855});
CREATE (n5 :L1{k10:'uvuE'});
CREATE (n6 :L1);
CREATE (n7 :L3{k20:-1273702860, k25:true});
CREATE (n8 :L1{k10:'0N', k11:'0t', k12:'sjSGfpku'});
CREATE (n9 :L2{k15:'', k17:'C4', k18:1417475811});
CREATE (n10 :L4);
CREATE (n11 :L1{k10:'lxkHtbW3J', k12:'YNbrfggW'});
CREATE (n12 :L3{k21:'NI', k25:false});
MATCH (n2 :L2{k14:true, k17:'aE', k19:-1427022695}), (n5 :L1{k10:'uvuE'}) MERGE (n2)-[r0 :T0{k38:'i'}]->(n5);
MATCH (n2 :L2{k14:true, k17:'aE', k19:-1427022695}), (n6 :L1) MERGE (n2)<-[r1 :T2{k51:265252374}]-(n6);
MATCH (n1) WITH max(2111812309) AS a1 OPTIONAL MATCH (n6) WITH n6 OPTIONAL MATCH (n8 :L0) OPTIONAL MATCH (n9)<--(n10), (n8) RETURN 1
```

**Neo4j Version:** 4.4.3, 4.2.14 Community
**Operating System:** Windows 11
  **API:** Cypher / Java API

### Steps to reproduce
1. Start Neo4j 4.2.14 and 4.4.3, respectively.
2. Execute the mentioned queries on each version.
3. Compare the result sets

### Expected behavior
The result sets are the same.

### Actual behavior
Neo4j 4.2.14: 65 records
Neo4j 4.4.3: 13 records

**Comment by HannesSandberg** [comment]
Thanks for the report. We'll take a look and get back to you.

**Comment by mchccc** [comment]
Is there any update on this? It seems important..

**Comment by inmost-light** [comment]
@cicuz This has been fixed, see the comment in https://github.com/neo4j/neo4j/issues/12818.
