### ISSUE TITLE
Wrong results are returned when executing the Cypher queries

### ISSUE THREAD

**Issue by abc123000111** [neo4j/neo4j#12838]
I discovered that when I execute the following queries, 144 records are returned. But actually it should return 288 records.
```
CREATE (n0 :L0);
CREATE (n1 :L4{k26:false, k27:false, k30:true});
CREATE (n2 :L3);
CREATE (n3 :L2{k17:987581285});
CREATE (n4 :L3{k20:'', k23:false, k25:true});
CREATE (n5 :L2{k17:987581285});
CREATE (n6 :L0{k2:1405310981});
CREATE (n7 :L3{k20:'Yl', k22:true, k23:false});
CREATE (n8 :L3);
CREATE (n9 :L4{k29:'g5r3Ra78'});
CREATE (n10 :L3{k21:1111252225});
CREATE (n11 :L4{k27:true});
MATCH (n1) OPTIONAL MATCH (n2)-->(n3 :L3) OPTIONAL MATCH (n4) OPTIONAL MATCH (n5 :L2), (n3) RETURN 0;
```

**Neo4j Version:** 4.3.10, 4.2.14 Community
**Operating System:** Windows 11
**API:** Cypher query

### Steps to reproduce
1. Start Neo4j 4.3.10 or 4.2.14
2. Execute the mentioned queries
3.  The result sets are returned
![plan](https://user-images.githubusercontent.com/34190313/152174102-fdc3b0d7-1f85-4c76-8e4e-12531a3d6d92.png)

### Expected behavior
288 records should be returned (12x1x12x2x1).

### Actual behavior
Only returns 144 records.

### Note
Interestingly, if I change the query to the following (delete ,(n3)), Neo4j returns 288 results:
`MATCH (n1) OPTIONAL MATCH (n2)-->(n3 :L3) OPTIONAL MATCH (n4) OPTIONAL MATCH (n5 :L2) RETURN 0;`
![plan (1)](https://user-images.githubusercontent.com/34190313/152174365-69c2345c-8c60-482e-8223-b972977afcc9.png)

**Comment by HannesSandberg** [comment]
Thanks for the report! We will look into this.

**Comment by inmost-light** [comment]
Hello @abc123000111,

I believe this is actually working as intended:
- There are no patterns matching `OPTIONAL MATCH (n2)-->(n3 :L3)`, therefore `n3` is always set to `NULL`.
- For `OPTIONAL MATCH (n5 :L2), (n3)` to match anything, all pattern parts must match something. Since `n3` is `NULL`, it can't ever match anything, therefore this `OPTIONAL MATCH` only output a single row.

**Comment by abc123000111** [comment]
> Hello @abc123000111,
> 
> I believe this is actually working as intended:
> 
> * There are no patterns matching `OPTIONAL MATCH (n2)-->(n3 :L3)`, therefore `n3` is always set to `NULL`.
> * For `OPTIONAL MATCH (n5 :L2), (n3)` to match anything, all pattern parts must match something. Since `n3` is `NULL`, it can't ever match anything, therefore this `OPTIONAL MATCH` only output a single row.

Thank you! I found that the results returned by Neo4j and Memgraph are inconsistent, so I commit this issue on Memgraph Github (https://github.com/memgraph/memgraph/issues/344).
