### ISSUE TITLE
Different results returned when executing the same queries on Neo4j 4.1.11 and 3.5.30, respectively.

### ISSUE THREAD

**Issue by abc123000111** [neo4j/neo4j#12837]
I discovered that when I executed the following queries on different versions of Neo4j, different results were returned:

```
CREATE (n0 :L0);
CREATE (n1 :L3{k19:'', k22:'eGvG00L2'});
CREATE (n2 :L0);
CREATE (n3 :L2{k13:true});
CREATE (n4 :L1{k7:false, k11:true});
CREATE (n5 :L5{k33:false});
CREATE (n6 :L3);
CREATE (n7 :L5{k34:'c'});
CREATE (n8 :L0{k1:1620927884});
CREATE (n9 :L5);
CREATE (n10 :L3{k18:'G', k23:false});
CREATE (n11 :L3{k22:''});
CREATE (n12 :L2);
CREATE (n13 :L3{k23:true});
CREATE (n14 :L4);
CREATE (n15 :L3{k19:'q1e', k21:-676392867});
CREATE (n16 :L2{k14:true});
CREATE (n17 :L3{k22:'qUe4QXII'});
MATCH (n4 :L1{k7:false, k11:true}), (n4 :L1{k7:false, k11:true}) MERGE (n4)-[r0 :T0{k43:true}]->(n4);
MATCH (n0 :L3) OPTIONAL MATCH (n1), (n0) WHERE (((n0.k18) CONTAINS 'aimTs') XOR ((n0.k21) > (n0.k21))) WITH * WHERE ((n0.k21) < -128253556) WITH n1 OPTIONAL MATCH (n2), (n1) WITH n2 RETURN 1;
```

**Neo4j Version:** 4.1.11 and 3.5.30 Community
**Operating System:** Windows 11
**API:** Cypher / Java API

### Steps to reproduce
1. Start Neo4j 4.1.11 and 3.5.30, respectively.
2. Execute the mentioned queries on each version.
3. Compare the result sets

### Expected behavior
The result sets are the same.

### Actual behavior
Neo4j 4.1.11: 18 records
![plan](https://user-images.githubusercontent.com/34190313/152078057-49f9a988-3f49-47f5-b6b7-1785961bd941.png)

Neo4j 3.5.30: 1 record
![plan (1)](https://user-images.githubusercontent.com/34190313/152078069-e8129cbc-c192-451b-9152-7bb91de78b3f.png)

**Comment by HannesSandberg** [comment]
Thanks! We will look into this and come back to you.

**Comment by inmost-light** [comment]
See the comment in #12818.
