### ISSUE TITLE
Neo.DatabaseError.Statement.ExecutionFailed occurred when executing the query: MATCH (n0), (n1)--(n2) OPTIONAL MATCH (n0)--(n3:L1), (n1) RETURN * LIMIT 0

### ISSUE THREAD

**Issue by abc123000111** [neo4j/neo4j#12830]
I discovered that when I executed the following query, a database error occurred.

**Neo4j Version:** 4.3.10 Community
**Operating System:** Windows 11
**API:** Cypher / Java API

### Steps to reproduce
Execute the following query:
MATCH (n0), (n1)--(n2) OPTIONAL MATCH (n0)--(n3:L1), (n1) RETURN * LIMIT 0

### Expected behavior
An empty resultset should be returned.

### Actual behavior
**ERROR: Neo.DatabaseError.Statement.ExecutionFailed**
Expected 
RegularSinglePlannerQuery(QueryGraph {Nodes: ['n0', 'n1', 'n2'], Rels: ['(n1)-[  UNNAMED0]-(n2)'], Optional Matches: : ['QueryGraph {Nodes: ['n0', 'n1', 'n3'], Rels: ['(n0)-[  UNNAMED1]-(n3)'], Arguments: ['n0', 'n1'], Predicates: ['n3:L1']}']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n0 -> Variable(n0), n1 -> Variable(n1), n2 -> Variable(n2), n3 -> Variable(n3)),QueryPagination(None,Some(SignedDecimalIntegerLiteral(0))),Selections(Set())),None,None) 

Instead, got: 
RegularSinglePlannerQuery(QueryGraph {Nodes: ['n0', 'n1', 'n2'], Rels: ['(n1)-[  UNNAMED0]-(n2)'], Optional Matches: : ['QueryGraph {Nodes: ['n0', 'n3'], Rels: ['(n0)-[  UNNAMED1]-(n3)'], Arguments: ['n0', 'n1'], Predicates: ['n3:L1']}']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(n0 -> Variable(n0), n1 -> Variable(n1), n2 -> Variable(n2), n3 -> Variable(n3)),QueryPagination(None,Some(SignedDecimalIntegerLiteral(0))),Selections(Set())),None,None)
Plan: ProduceResult(List(n0, n1, n2, n3)) {
  LHS -> Limit(SignedDecimalIntegerLiteral(0)) {
    LHS -> Apply(false) {
      LHS -> CartesianProduct(false) {
        LHS -> AllNodesScan(n0, Set()) {}
        RHS -> Expand(n1, BOTH, List(), n2,   UNNAMED0, ExpandAll) {
          LHS -> AllNodesScan(n1, Set()) {}
        }
      }
      RHS -> Optional(Set(n0, n1,   UNNAMED0, n2)) {
        LHS -> Expand(n0, BOTH, List(), n3,   UNNAMED1, ExpandInto) {
          LHS -> NodeByLabelScan(n3, LabelName(L1), Set(n0, n1), IndexOrderNone) {}
        }
      }
    }
  }
} 

Differences:
 - QueryGraph
    A: QueryGraph {Nodes: ['n0', 'n1', 'n2'], Rels: ['(n1)-[  UNNAMED0]-(n2)'], Optional Matches: : ['QueryGraph {Nodes: ['n0', 'n1', 'n3'], Rels: ['(n0)-[  UNNAMED1]-(n3)'], Arguments: ['n0', 'n1'], Predicates: ['n3:L1']}']}
    B: QueryGraph {Nodes: ['n0', 'n1', 'n2'], Rels: ['(n1)-[  UNNAMED0]-(n2)'], Optional Matches: : ['QueryGraph {Nodes: ['n0', 'n3'], Rels: ['(n0)-[  UNNAMED1]-(n3)'], Arguments: ['n0', 'n1'], Predicates: ['n3:L1']}']}

**Comment by arnefischereit** [comment]
Hi there,

Thanks for reporting another issue on `OPTIONAL MATCH`.

The issue described here seems to have the same cause as #12795. We will therefore handle the issue there.

Let me know if you have any more questions.

**Comment by abc123000111** [comment]
Thanks a lot! I would have thought that issue #12795 was fixed in the new release of Neo4j 4.3.

**Comment by arnefischereit** [comment]
Hi @abc123000111,

The fix for #12795 is currently in the process of being backported from our main development branch to the previous releases and will be available in an upcoming release.

More to that on that issue.
