### ISSUE TITLE
Different results returned when executing the same queries on different versions of Neo4j

### ISSUE THREAD

**Issue by abc123000111** [neo4j/neo4j#12831]
I discovered that when I executed the following queries on different versions of Neo4j, different results were returned:

```
CREATE (n0 :L0{k2:-338112306, k4:true});
CREATE (n1 :L3{k24:''});
CREATE (n2 :L2{k17:'YP'});
CREATE (n3 :L4{k26:909121655, k30:'PHLUcE'});
CREATE (n4 :L4);
CREATE (n5 :L3{k23:true});
CREATE (n6 :L4{k27:true, k29:909121655});
CREATE (n7 :L5);
CREATE (n8 :L2);
CREATE (n9 :L4{k26:-246760203, k30:''});
CREATE (n10 :L5{k32:false});
CREATE (n11 :L5{k34:'lFbv3iSE', k35:909121655});
CREATE (n12 :L3{k18:'', k21:'ap3zA', k23:true});
CREATE (n13 :L4{k25:'qzoq', k27:true, k29:-1599697040, k30:'W'});
CREATE (n14 :L3{k23:true});
CREATE (n15 :L1);
CREATE (n16 :L3);
CREATE (n17 :L5);
MATCH (n0) OPTIONAL MATCH (n3) WITH n3 WITH DISTINCT * OPTIONAL MATCH (n3), (n5) OPTIONAL MATCH (n3) RETURN 1;
```

**Neo4j Version:** 4.4.3 and 4.2.14 Community
**Operating System:** Windows 11
**API:** Cypher / Java API

### Steps to reproduce
1. Start Neo4j 4.2.14 and 4.4.3, respectively.
2. Execute the mentioned queries on each version.
3. Compare the result sets

### Expected behavior
The result sets are the same.

### Actual behavior
Neo4j 4.2.14: 5832 records
Neo4j 4.4.3: 324 records

**Comment by InverseFalcon** [comment]
4.4.3 seems correct for the operations executed.

In the last statement, no matter how many rows get generated by the matches in the first half of that statement, the `WITH n3 WITH DISTINCT *` will bring rows back to 18 distinct rows of nodes, and the `n3` variable bound for each of those.

`OPTIONAL MATCH (n3), (n5)` gets you 18 (input rows corresponding with `n3`) * 18 (since `n5` will do a cartesian product against the 18 nodes in the graph) = 324. (note that the `n3` isn't needed there, `OPTIONAL MATCH (n5)` should get you the exact same results)

The last `OPTIONAL MATCH (n3)` is a no-op, since n3 is already bound.

I'd like to see a PROFILE of execution from 4.2.14. Can you provide that? And are you sure that it starts with an empty graph?

**Comment by abc123000111** [comment]
> ```
> MATCH (n0) OPTIONAL MATCH (n3) WITH n3 WITH DISTINCT * OPTIONAL MATCH (n3), (n5) OPTIONAL MATCH (n3) RETURN 1;
> ```

Thanks a lot! Of course it starts with an empty graph. Here is the PROFILE of execution from 4.2.14:
![plan (2)](https://user-images.githubusercontent.com/34190313/150882572-e234bddb-9814-415b-a62f-5ac7a3ac09a1.png)

And here is the PROFILE of execution from 4.4.3:
![plan (1)](https://user-images.githubusercontent.com/34190313/150882608-4f75d934-a8cb-448a-9aa0-3319391102fb.png)

**Comment by InverseFalcon** [comment]
Thanks for the PROFILE plan.

The 4.2.14 plan looks flawed in that the AllNodesScan for n3 in the upper right branch of the plan is incorrect, and is adding an unnecessary multiplication of rows as a result.

Interestingly, both in SLOTTED and PIPELINED runtimes (available only in Enterprise edition), the planner corrects the number of rows at the NodeLeftOuterHashJoin step. But the INTERPRETED runtime (used in Community edition, and being used in your PROFILE capture) does not correct the rows properly, and we get incorrect results when this runtime is used.

This looks like an INTERPRETED runtime bug first, with the potential for perhaps another bug to be in play related to OPTIONAL MATCH starting from a bound node variable (n3) as part of a disjoint pattern expression.

**Comment by arnefischereit** [comment]
Hi @abc123000111,

Thanks for reporting the issue. We have implemented a fix for it which will be part of the next release, probably 4.4.9.

I am closing this issue, should the problem persist (after the release of 4.4.9) or reappear please reopen this issue or open a new one.

Regards,  

Arne
