### ISSUE TITLE
Transaction issues with Neo4j 4.4: Client triggered an unexpected error

### ISSUE THREAD

**Issue by bradenmacdonald** [neo4j/neo4j#12844]
I have been trying to upgrade my application from 4.3 to 4.4 since 4.4 was announced, and I try again every time there's a new point release, but I've been hitting issues every time. This weekend I took time to try to investigate what's going on, using Neo4j 4.4.4, and was able to work around some of the issues, but I still seem to be hitting a recurring issue of flaky `Client triggered an unexpected error` messages. I say flaky because though these errors inevitably come up when I run my entire test suite, individually they are not consistent and sometimes happen, sometimes don't. 

The code in question works perfectly under Neo4j 4.3, but when I change to 4.4 it starts giving these errors. 

Here are some examples of the error messages I'm seeing. I know these are different errors but I assume there is one underlying root cause.

For context, I have a few different APOC triggers installed (in the `before` phase), some of which do validation and can throw an exception, and others which modify the data. I believe the errors are due to some interaction between triggers and transaction handling changes in 4.4. 

### 1. The requested operation cannot be performed, because it has to be performed in a transaction.

This is the one that I see the most often when I run my test suite. Here is one example:

Client runs queries (in same write transaction):

```
MATCH (u:User:VNode {id: $p0})
CREATE (a:Action:VNode {id: $p2})
CREATE (u)-[:PERFORMED]->(a)
SET a.type = $p3
SET a.timestamp = datetime()
```

```
CREATE (p:Planet:AstroBody:VNode {id: $p1}) SET p += $p2
```

The first statement (`MATCH...SET`) succeeds, but the second statement (`CREATE`) fails:

Server log:

    neo4j_1  | 2022-02-20 21:34:13.197+0000 ERROR Client triggered an unexpected error [Neo.DatabaseError.Statement.ExecutionFailed]: The requested operation cannot be performed, because it has to be performed in a transaction., reference 7db43b8c-08b3-4c39-ac05-2f8e46079f67.

Client log:

    Neo4jError: The requested operation cannot be performed, because it has to be performed in a transaction.
    at captureStacktrace (https://raw.githubusercontent.com/bradenmacdonald/deno-neo4j-lite-client/4.4.1-preview2/core/result.ts:320:17)
    at new Result (https://raw.githubusercontent.com/bradenmacdonald/deno-neo4j-lite-client/4.4.1-preview2/core/result.ts:113:19)
    at newCompletedResult (https://raw.githubusercontent.com/bradenmacdonald/deno-neo4j-lite-client/4.4.1-preview2/core/transaction.ts:579:10)
    at Object.run (https://raw.githubusercontent.com/bradenmacdonald/deno-neo4j-lite-client/4.4.1-preview2/core/transaction.ts:322:14)
    at Transaction.run (https://raw.githubusercontent.com/bradenmacdonald/deno-neo4j-lite-client/4.4.1-preview2/core/transaction.ts:140:30)
    at WrappedTransaction.run (file:///Users/braden/Documents/Neolace/vertex-framework/vertex/transaction.ts:29:25)
    at query (file:///Users/braden/Documents/Neolace/vertex-framework/vertex/layer2/query.ts:24:29)

I am definitely running the operation in a transaction. I don't believe the JavaScript client API has a way to run code outside of a transaction.

### 2. Trigger errors before commit

I don't really understand this one, but I see it frequently: in my test suite, a statement in the middle of an explicit write transaction will fail with an error like `Error executing triggers: (details)`. The details of the error make sense, because the trigger throws an error about missing data, since the transaction wasn't finished yet and that data was about to be written in subsequent statements.  In other words, I am still in the middle of a manual transaction and it is not supposed to commit yet, but Neo4j seems to have decided to commit the transaction or at least run a trigger prematurely.

Client log:

```
Neo4jError: Error executing triggers {validateActionModified=Failed to invoke procedure `apoc.util.validate`: Caused by: java.lang.RuntimeException: A PersonRVT node was modified by this action but not explicitly marked as modified by the Action., deleteSlugIdRelation=The transaction has been closed., updateSlugIdRelation=The transaction has been closed., trackActionDeletes=The transaction has been closed., requireAction=The transaction has been closed.}

    at captureStacktrace (https://raw.githubusercontent.com/bradenmacdonald/deno-neo4j-lite-client/4.4.1-preview2/core/result.ts:320:17)
    at new Result (https://raw.githubusercontent.com/bradenmacdonald/deno-neo4j-lite-client/4.4.1-preview2/core/result.ts:113:19)
    at newCompletedResult (https://raw.githubusercontent.com/bradenmacdonald/deno-neo4j-lite-client/4.4.1-preview2/core/transaction.ts:579:10)
    at Object.run (https://raw.githubusercontent.com/bradenmacdonald/deno-neo4j-lite-client/4.4.1-preview2/core/transaction.ts:322:14)
    at Transaction.run (https://raw.githubusercontent.com/bradenmacdonald/deno-neo4j-lite-client/4.4.1-preview2/core/transaction.ts:140:30)
    at WrappedTransaction.run (file:///home/runner/work/vertex-framework/vertex-framework/vertex/transaction.ts:27:25)
    at query (file:///home/runner/work/vertex-framework/vertex-framework/vertex/layer2/query.ts:24:29)
```

As you can see from the stacktrace, this error arose from a `Transaction.run(...)` command, which should only be running a statement and keeping the transaction open, not committing and running triggers.

### 3. Unable to complete transaction (not allowed)

Client runs query:

    UNWIND [{id:"_3YThgbWWKrSaNazVKTNoMv", properties:{data:"{}", type:"CreateUser", timestamp:datetime('2022-02-20T21:07:09.605Z'), tookMs:0}}] AS row
    CREATE (n:VNode{id: row.id}) SET n += row.properties

Server log:

    neo4j_1  | 2022-02-20 21:18:07.756+0000 ERROR Client triggered an unexpected error [Neo.DatabaseError.Statement.ExecutionFailed]: Unable to complete transaction., reference b5b92faf-651a-4677-b5cd-e013f85309ed.

Client log:

    Neo4jError: Create node with labels 'VNode' on database 'neo4j' is not allowed for user 'neo4j' with READ.

(I am definitely using a WRITE transaction, not sure why I occasionally get this error. It's flaky and not consistent. Sometimes it complains about writing to a specific property; here it's complaining about creating a node)

### 4. Unable to complete transaction

Client runs queries (in same write transaction):

    CREATE CONSTRAINT vnode_id_uniq FOR (v:VNode) REQUIRE v.id IS UNIQUE
    // ^ the first statement succeeds. But the second:
    CREATE CONSTRAINT vnode_slugid_uniq FOR (v:VNode) REQUIRE v.slugId IS UNIQUE

Server log:

    neo4j_1  | 2022-02-20 21:29:11.371+0000 ERROR Client triggered an unexpected error [Neo.DatabaseError.Statement.ExecutionFailed]: Unable to complete transaction., reference 67146917-84ef-42ef-a2be-0149ae40d62a.

Client log:

    Neo4jError: Unable to complete transaction.

### Context

**Neo4j Version:** 4.4.4 community, running in Docker
**Operating System:** MacOS (arm64) and Ubuntu (Linux amd64)
**API:** Using Deno port of the JavaScript client

### Steps to reproduce

I am not sure how to create a small reproduction case; it seems to mostly occur when I run my whole test suite.

[Here you can see a green test suite run on Neo4j 4.3](https://github.com/neolace-dev/vertex-framework/runs/5268175155?check_suite_focus=true):

    test result: ok. 242 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (

Then I make only [this change](https://github.com/neolace-dev/vertex-framework/pull/4/commits/dd071473d945f3760df3e2a497bc142b706e03f6) to bump the version to 4.4.4 and I get [7 test failures](https://github.com/neolace-dev/vertex-framework/runs/5268198327?check_suite_focus=true) which are of the types described above. These errors happen on the GitHub CI machine and my local mac dev machine.

The code of the triggers I have installed are [here (triggers 1+2)](https://github.com/neolace-dev/vertex-framework/blob/c6fcf9e7f855a5fb12d726fa614bd376edfaa08b/vertex/layer2/schema.ts#L57-L89) and [here (3)](https://github.com/neolace-dev/vertex-framework/blob/c6fcf9e7f855a5fb12d726fa614bd376edfaa08b/vertex/layer4/schema.ts#L42-L51) and [here (4)](https://github.com/neolace-dev/vertex-framework/blob/c6fcf9e7f855a5fb12d726fa614bd376edfaa08b/vertex/layer4/schema.ts#L82-L157)

### Expected behavior

No `Client triggered an unexpected error`  errors.

**Comment by HannesSandberg** [comment]
Hi! Thanks for your report! We will look into this and report back to you.

**Comment by bradenmacdonald** [comment]
Hi @HannesSandberg and team,

I spent some more time digging into this issue today and I think I am closer to identifying the root cause.

1. My application has two triggers installed in the `before` phase which run some validation and throw an exception if certain conditions are not met, similar to triggers shown in the documentation.
    * For example, this is one of the triggers:
        ```
            CALL apoc.trigger.add("requireAction", "
                WITH [n IN $createdNodes WHERE n:Action:VNode] AS actions
                    CALL apoc.util.validate(
                        size(actions) <> 1,
                        'every data write transaction should be associated with one Action, found %d', [size(actions)]
                    )
                    RETURN null
            ", {phase: "before"})
        ```
    * And [this](https://github.com/neolace-dev/vertex-framework/blob/c6fcf9e7f855a5fb12d726fa614bd376edfaa08b/vertex/layer4/schema.ts#L82-L157) is the other data validation trigger.
    * (I also have a [few](https://github.com/neolace-dev/vertex-framework/blob/c6fcf9e7f855a5fb12d726fa614bd376edfaa08b/vertex/layer2/schema.ts#L57-L89) [other](https://github.com/neolace-dev/vertex-framework/blob/c6fcf9e7f855a5fb12d726fa614bd376edfaa08b/vertex/layer4/schema.ts#L174-L189) triggers installed in the `before` phase which modify the transaction before it commits, but I don't think they are the problem here.)
2. In the test suite, I have a few tests that verify that these triggers are working, e.g. [this test](https://github.com/neolace-dev/vertex-framework/blob/430a8fff8cdf3333b5d90245b10fab18bc8d48a5/vertex/layer4/action-runner.test.ts#L113-L118):

    ```
            await assertRejects(
                () => testGraph._restrictedWrite(tx =>
                    tx.run("CREATE (x:SomeNode) RETURN x", {})
                ),
                "every data write transaction should be associated with one Action",
            );
    ```

    This is a test for the trigger shown above. If a node (`:SomeNode` in this case) is created without a corresponding `:Action` node, the trigger will throw an error using `apoc.util.validate()`
3. Under both Neo4j 4.3 and 4.4, these triggers work and these tests that check the trigger functionality pass. However, under 4.4, the tests that cause the triggers to throw an exception in the `before` phase cause some kind of bug in the server, which then permanently affects all future transactions that run, causing weird and flaky (inconsistent) errors with transactions and triggers in _other_ tests cases of my test suite.
    * Here is the clear evidence: my test suite works on the `main` branch with Neo4j 4.3. If I [upgrade to Neo4j 4.4](https://github.com/neolace-dev/vertex-framework/pull/4/commits/80b0f1b2ccaa26ba323a8dcaebe7cade61099a40), the tests fail randomly with all the various errors listed below. But then [if I disable the three test cases that deliberately cause the triggers to throw errors](https://github.com/neolace-dev/vertex-framework/pull/4/commits/dfe98a46c475d59d1f115d6fbdf5fb1f5e1329ab), the whole test suite passes again.

As mentioned in the original report, once the server gets into this state (caused by throwing an exception during a `before` trigger), we observe all kinds of errors randomly in other tests:
* `Error executing triggers` at unexpected time, while a transaction is still active (it shouldn't have started the commit process yet)
* `ERROR Client triggered an unexpected error [Neo.DatabaseError.Transaction.TransactionCommitFailed]: Unable to complete transaction., reference 58984c8b-c476-4509-8296-c58d0a56f5fa.`
* `ERROR Client triggered an unexpected error [Neo.DatabaseError.Statement.ExecutionFailed]: NOT PART OF CHAIN! RelationshipTraversalCursor[id=30, open state with: denseNode=false, next=30, , underlying record=Relationship[30,used=true,source=6,target=264,type=5,sPrev=288,sNext=29,tPrev=33,tNext=8,prop=440,!sFirst,!tFirst]], reference `
* `The requested operation cannot be performed, because it has to be performed in a transaction.`
* etc.

**Comment by bradenmacdonald** [comment]
^ The above commit closed this issue by mistake, but I am pleased to report that this bug was actually fixed in Neo4j 5.1 :)

**Comment by GregDThomas** [comment]
Also 4.4.13 on the 4.x line

**Comment by gooneraki** [comment]
For me I get this error in transactions where `cypher.lenient_create_relationship=true` is applied (it's a case where the optional match does not happen thus the later creation does not occur).

e.g. in my query I have `OPTIONAL MATCH (a)<-[:rel1]-(b)` and then `CREATE (a)<-[:rel2]-(b)`

This was working well in neo4j-4.1 but upgrading to neo4j-4.4 I run to this error.
I use neo4j-driver: 5.23.0.

If I update the query to bypass this such as `FOREACH ( i IN CASE WHEN b is NULL THEN [] ELSE [1] END | CREATE (a)<-[:rel2]-(b) )` (hope I got it right) it works fine. Basically not using the `cypher.lenient_create_relationship=true` setting. But I cannot do that since it's all over the place in my app
