### ISSUE TITLE
4.4.3 Enterprise Version

### ISSUE THREAD

**Issue by UmamaheswarKalagotla** [neo4j/neo4j#12842]
- Neo4j version: 4.4.3
- Operating system: Amazon Linux2)
- API/Driver: (Apoc)
- **Steps to reproduce**
- Expected behavior
- Actual behavior

Configuration override prefix = bimodalv3_neo4j_replica_0
Starting Neo4j READ_REPLICA 0 on bimodalv3-neo4j-replica-0.bimodalv3-neo4j-replica.neo-dev.svc.cluster.local
chown: changing ownership of '/var/lib/neo4j/certificates/neo4j_ldap.jks': Read-only file system

Container JKS was configured for LDAP and logs stopped writing after here.

K8S pods goes in CrashLoopBack.

**Comment by HannesSandberg** [comment]
Hi! Since we mostly use github issues for bugg reports. Could you open a support ticket instead? As that will get you better help from our support team with setting up the configuration for LDAP properly.

**Comment by Lojjs** [comment]
@UmamaheswarKalagotla As there has been no reply on this issue for over a year, I will resolve it. Feel free to open a support ticket or new Github issue if you still need help.

Best regards Louise, Neo4j Cypher team
