### ISSUE TITLE
Neo4j Bloom Node Size per Rules shows inverse Sizes

### ISSUE THREAD

**Issue by zulfi123786** [neo4j/neo4j#12846]
Team,

In Neo4j Bloom Desktop version I was trying to set Custom Node Sizes based on Bigint field Range with Minpoint set to 0.25x and MaxPoint set to 4x. It showed the inverse with nodes having small values in bigger size and those with higher values in smaller size. This has wasted my 2 days worth of evaluation of multiple Graph Visualization tools as this silly coding mistake by Neo4j Developers is preventing me from using the tool. Hope this is very easy to fix.

Thanks
Zulfiqar Syed

**Comment by joknelid** [comment]
Hi,

Thanks for reporting this issue - it was indeed pretty easy to fix and we will be making a patch release sometime in the next few days.

We definitely don't want to waste someones time but sometimes these things happen sometimes :) But we will add some automated testing to catch these kinds of things in the future.

Hope that helps,
Jens

**Comment by zulfi123786** [comment]
Thank you for the very quick fix, Totally understand as I am a developer myself :)
