### ISSUE TITLE
Provide observability via Micrometer 2.0.0 & Micrometer Tracing

### ISSUE THREAD

**Issue by marcingrzejszczak** [neo4j/neo4j#12841]
# Introduction

With Micrometer 2.0.0 we're introducing a concept of an `Observation` ([you can read more about it here](https://micrometer.io/docs/tracing)). An `Observation` wraps an action that we would like to measure. A measurement can be wrapping it in a `Timer` (metrics), creation of a `Span` (tracing) or any other custom behavior such as e.g. logging. 

Let's check the following example

```java
ObservationRegistry registry = new SimpleMeterRegistry();
Observation observation = Observation.start("my.operation", registry);
try {
    observation.scoped(() -> doSomeWorkHere());
} finally {
    observation.stop();
}
```

Depending on the configuration of the `ObservationRegistry` there might be various outcomes when `doSomeWorkHere()` gets executed.

# Benefit

Using the Observation API makes you instrument your code once but you get multiple benefits out of it (e.g. metrics & tracing). Since Micrometer Tracing works with Micrometer we also bridge the span creation to such tracer implementations as OpenZipkin Brave and OpenTelemetry.

# Feature request

We would like to suggest that such instrumentation using Micrometer would happen in this project. Doing so would allow us to transparently continue any traces that occurred on the client side and have consistency in terms of used metrics. You could also emit metrics and traces (and whatever you want really) on the server side.

**Comment by zimmre** [comment]
HI, we have reviewed your feature request and decided not to proceed with it.
