### ISSUE TITLE
Incorrect results are returned when executing the Cypher queries.

### ISSUE THREAD

**Issue by abc123000111** [neo4j/neo4j#12840]
Hello! I discovered that when I execute the following queries, 648 records are returned. But actually it should return 2 records.

```
CREATE (n0 :L3{k20:-309824014, k21:-309824014, k22:false});
CREATE (n1 :L2{k14:'dl12jOgAR', k17:true});
CREATE (n2 :L3);
CREATE (n3);
CREATE (n4);
CREATE (n5);
CREATE (n6 :L4{k26:true, k28:1592475594});
CREATE (n7 :L0{k1:true});
CREATE (n8 :L1{k7:true, k8:-1023351816, k10:'Va', k11:'UxK'});
CREATE (n9);
CREATE (n10 :L3);
CREATE (n11 :L3 :L4{k22:true, k23:1801331688, k24:628650604, k26:true, k27:87770264, k28:215433411});
CREATE (n12 :L0{k5:-650326079});
CREATE (n13);
CREATE (n14);
CREATE (n15 :L1{k8:201223491, k11:'1HiNg9Meh'});
CREATE (n16);
CREATE (n17);
MATCH (n0 :L3{k20:-309824014, k21:-309824014, k22:false}), (n1 :L2{k14:'dl12jOgAR', k17:true}) MERGE (n0)-[r0 :T4{k51:true, k55:628650604}]->(n1);
MATCH (n1) UNWIND [-1027650030, -806154889] AS a0 OPTIONAL MATCH (n1), (n3) WITH a0 RETURN DISTINCT a0 ORDER BY a0 ;
```

**Neo4j Version:** 4.3.10 Community
**Operating System:** Windows 11
**API:** Cypher / Java API

### Steps to reproduce
1. Start Neo4j 4.3.10
2. Execute the mentioned queries
3. The result sets are returned

### Expected behavior
Only 2 records should be returned due to the DISTINCT keyword.

### Actual behavior
Returns 648 records.
![1](https://user-images.githubusercontent.com/34190313/152975271-55f2651d-b60f-4720-917d-7ebc6aae7dcc.png)

**Comment by HannesSandberg** [comment]
Thank you for the report. We will look into this.

**Comment by hedengran** [comment]
Hi @abc123000111! Thank you again for the report. The issue, as it seems, is not actually with `DISTINCT` but rather the `ORDER BY`. At some point in the planning process we do an optimization of the plan which ends up "destroying" the sort. After that, we try to plan an optimized `DISTINCT`-operator that requires that all incoming rows are already sorted.

I'm in the process of merging a fix, and will backport the fix to all affected versions.
