### ISSUE TITLE
Question about maintaining provenance data

### ISSUE THREAD

**Issue by frdougal** [neo4j/neo4j#12843]
Hello, I plan on loading data into a neo4j graph and I want to associate it with some provenance data.  Specifically, I want to track when it was loaded, source file(s) used to generate the data, what code was used to load it, etc.  I will be pulling several data sources together into one graph and I want to track their origin.  Most of the datasources will contain on the order of 10-100k nodes.  There may be some cases where the number of nodes reach on the order of 1 million nodes for certain datasources, but this will be the exception.

Here is the crux of my question.  I can see two main ways to maintain this information: a) put all the provenance data into the nodes and relationships as properties or b) add a single node representing the datasource's provenance data and link all the nodes that are part of the datasource to this node.  I am curious if there are performance trade offs using either approach.  With option a), I am growing the data and indices by repeating the data across thousands of nodes.  For option b) I will be adding a large number of relationship links.  What are the implications of these approaches?

I will not be querying on this data except in cases where I am updating parts of the graph (like one of the datasources). 
Thanks,
Chuck

**Comment by mnd999** [comment]
Thanks for writing. Generally we prefer to answer these types of questions in [our community forums](https://community.neo4j.com/) or on our [discord](https://discord.gg/neo4j) and you will likely get a faster response there. Github is more setup for bug reports in the product.

As this is a very old one, I will close for now. If it's still an issue, please let us know.
