### ISSUE TITLE
Using reserved words as variable names does not report any error.

### ISSUE THREAD

**Issue by abc123000111** [neo4j/neo4j#12856]
Hello, when I execute the following query on Neo4j, no error is reported. But the official document says: "The reserved keywords are not permitted to be used as identifiers in the following contexts: Variables, Function names, Parameters". So I think Neo4j should report an error when executing the following query:
`MATCH (RETURN) RETURN RETURN
`

**Neo4j Version:** 4.4.4 Community
**Operating System:** Windows 11
**API:** Cypher

### Steps to reproduce
Execute the query: 
`MATCH (RETURN) RETURN RETURN
`

### Expected behavior
An error should be reported. (See https://neo4j.com/docs/cypher-manual/4.4/syntax/reserved/)

### Actual behavior
No error occurred.

**Comment by mnd999** [comment]
Ideally, we would not allow this. However it's been the case for a very long time and changing it is very backward incompatible so I think it's here to stay for at least the 4.x series. As such I will close this issue as this behaviour is intentional.
