### ISSUE TITLE
How to get the code coverage and method call sequences of Neo4j source code after executing several Cypher queries?

### ISSUE THREAD

**Issue by abc123000111** [neo4j/neo4j#12859]
Hello, I want to get the code coverage and method call sequences of Neo4j source code after executing a series of Cypher queries. Is there any way to get them? Thanks!

**Comment by HannesSandberg** [comment]
We will check and come back to you.

**Comment by arnefischereit** [comment]
Hi @abc123000111,

Thank you for your question. At Neo4j, we rely on our tools (like the IDE) to provide us with coverage information.

You could for example use [JaCoCo](https://www.jacoco.org/jacoco/) for this and there is [an article on Wikipedia](https://en.wikipedia.org/wiki/Java_code_coverage_tools) on Java code coverage tools.

Does this answer your question?

**Comment by arnefischereit** [comment]
I will now assume that the previous answer solved the problem and close this issue.

Please feel free to comment on this issue or open a new one, if your problem has not been addressed.
