### ISSUE TITLE
java doc error for v4.4

### ISSUE THREAD

**Issue by JackWang1230** [neo4j/neo4j#12860]
here 'merge' should be rewritten as 'match'

![image](https://user-images.githubusercontent.com/45071261/160359799-1ad79cb4-5192-4b8c-adc0-3fee08a4ce8e.png)

**Comment by wgevaert** [comment]
I disagree, if the node `(:Company {name: $company_name})` does not exist yet, you do want it to be created.

**Comment by JackWang1230** [comment]
> I disagree, if the node `(:Company {name: $company_name})` does not exist yet, you do want it to be created.

alright, I understand
