### ISSUE TITLE
ORDER BY work for DESC, not not ASC

### ISSUE THREAD

**Issue by mech** [neo4j/neo4j#12864]
I am having issues using simple ORDER BY in my query. It seems simple, but I am at a lost where it went wrong.

This work:

`MATCH (s:Skill) RETURN s ORDER BY s.name DESC LIMIT 3`

But not this (note: without the DESC direction):

`MATCH (s:Skill) RETURN s ORDER BY s.name LIMIT 3`

- Neo4j version: 4.4.4
- Operating system: macOS Monterey 12.3.1
- API/Driver: Using Neo4j Desktop v1.4.15

Provided is the screenshot:

<img width="1271" alt="works" src="https://user-images.githubusercontent.com/5850/163189960-a436ce3e-8900-4a8d-ad74-dd84247f4944.png">

When removing DESC to use ASC, it produce strange label like `#<Skill:0xxxxxxx>`

<img width="1269" alt="not_working" src="https://user-images.githubusercontent.com/5850/163190398-9d667d62-fa71-49bb-8213-3c6767422533.png">

**Comment by HannesSandberg** [comment]
Thank you for your report! We will look into this and report back to you.

**Comment by arnefischereit** [comment]
I just tried to reproduce this scenario by recreating the nodes from the information available in the screenshots but failed to do so.

![image](https://user-images.githubusercontent.com/79841228/165035805-61e1c4f7-d007-4ffa-b0c3-1107274b411c.png)

Could you please provide us with the information how to set up the database, so that the problem occurs?

Also, it would be interesting, what the output in the "Table" tab is.

**Comment by mech** [comment]
Ya this problem did not occur on my AuraDB instance also. But my local machine same dataset got this strange behaviour. Only occur if I use "ASC" ordering.

Here's the table view:

<img width="1286" alt="ASC" src="https://user-images.githubusercontent.com/5850/165040638-526b9463-3768-4110-a170-8612814162a8.png">

<img width="1282" alt="DESC" src="https://user-images.githubusercontent.com/5850/165040622-63e727c0-4d45-4fd0-b076-dbe6c597c528.png">

I will try to find out how to setup the database from scratch that will re-create this problem first. I am using the EMSI skills taxonomy (https://skills.emsidata.com/) if you interested.

**Comment by arnefischereit** [comment]
@mech You seem to have a lot of nodes with label `Skill` in your database.

Could it be that some of them do have the `name` set to something as silly as `#<Skill:0x…>` and through that `LIMIT 3` you only see them when sorting ascendingly. You would probably also see them when sorting descendingly but they would appear at the end of the list.

Let me know if that solves your issue.

**Comment by mech** [comment]
Okay, judging from the very similar Ruby object inspection code, I think you are right. It must be when I write to it, I write as object string. Sorry for causing the inconvenience 🥺
