### ISSUE TITLE
403 ERROR when trying to download neo4j desktop

### ISSUE THREAD

**Issue by alphavector** [neo4j/neo4j#12872]
I'm trying to download neo4j-desktop from https://neo4j.com/artifact.php?name=neo4j-desktop-1.4.15.dmg, but I get a 403 error

I guess why I'm getting this error, it's probably related to the refusal to cooperate with Russia due to recent events.
But I haven't seen any official statements that access to downloading will be limited, so I wanted to clarify the situation with this error.

**Comment by ReeStick** [comment]
I also think it is a error because of country, because i live in Russia and VPN solved the problem.

**Comment by Somebi** [comment]
Same issue, not available from Germany IP... Seriously, not available from Germany?! How the hell are you selling your product if it's blocked even in Germany?!
