### ISSUE TITLE
StackOverflowError when running MATCH query

### ISSUE THREAD

**Issue by InverseIntegral** [neo4j/neo4j#12882]
When I run the following query on an empty database:

```
MATCH (n:L) WHERE n.p = (n.p = n.p) RETURN n
```

A `StackOverflowError` is thrown:

```
Exception in thread "main" java.lang.StackOverflowError
	at org.neo4j.cypher.internal.expressions.Equals.equals(PredicateExpressions.scala:112)
	at org.neo4j.cypher.internal.expressions.Equals.equals(PredicateExpressions.scala:112)
```

I would expect the query to match all the nodes with label `L` and property `p` set to `true`.

**Neo4j Version:** 4.4.6
**Operating System:** 5.17.3 Arch Linux
**API:** Java

### Expected behavior
I would expect the query not to thrown any exception.

### Actual behavior
An exception is thrown when executing the query.

**Comment by HannesSandberg** [comment]
Thanks! We will look into this.

**Comment by Dunfluff** [comment]
Hi,
Thanks again for the report. It seems like the issue was due to a bug in our semantic checking. I have pushed a fix to the latest version and I'm currently backporting to all affected versions.
