### ISSUE TITLE
MATCH query returns incorrect result set when an index is present

### ISSUE THREAD

**Issue by InverseIntegral** [neo4j/neo4j#12884]
The following
```
CREATE INDEX FOR (n:L) ON (n.p)
CREATE (n:L {p:duration('P362644645M294180573WT737771470M')})
MATCH (n:L) WHERE n.p > duration("P-1157M-10DT0S") RETURN COUNT(*)
```
returns
```
COUNT(*)=1
```

When I remove the index
```
CREATE (n:L {p:duration('P362644645M294180573WT737771470M')})
MATCH (n:L) WHERE n.p > duration("P-1157M-10DT0S") RETURN COUNT(*)
```
the result becomes
```
COUNT(*)=0
```

I would expect the result to be 0 since the condition evaluates to `null`.

**Neo4j Version:** 4.4.6
**Operating System:** 5.17.3 Arch Linux
**API:** Java

### Expected behavior
I would expect the second result to appear when running the queries with the index.

### Actual behavior
The result is 1.

**Comment by HannesSandberg** [comment]
Thank you! We will look into this.

**Comment by arnefischereit** [comment]
Hi @InverseIntegral,

Thank you for raising this. The behaviour of the first query with index is wrong as [durations are incomparable](https://neo4j.com/docs/cypher-manual/4.4/syntax/operators/#cypher-ordering).

We are aware of this behaviour and will fix it in the next major release. However, as changing the semantics like that poses a breaking change, we will not do so in already released versions.

We will therefore close this issue for now. Please feel free to comment on this issue or reopen it or open a new issue, if you have outstanding points.
