### ISSUE TITLE
Additional result column prevents countstore usage

### ISSUE THREAD

**Issue by ikwattro** [neo4j/neo4j#12888]
Counting labeled nodes should use the countstore, however having a Cypher statement that returns an additional column prevents the countstore to be used in the planner.

**Neo4j Version:** 4.4.5
**Operating System:** any
**API:** any

### Steps to reproduce

Run the following query on the movies db

```
PROFILE
MATCH (n:Movie)
RETURN count(*) AS count, 'Movie' AS label
```

### Expected behavior

It should use the countstore

### Actual behavior

It does a NodeByLabelScan

**Comment by HannesSandberg** [comment]
Thank you! We will investigate and come back to you.

**Comment by arnefischereit** [comment]
@ikwattro: This will only be possible if the non-count column is constant, right? Is that a useful scenario?

I would not consider this a bug as the system returns the right result. But we could look into whether we can make the system a bit smarter to use the count store in more cases. That would, however, only make sense if this is the scenario that you actually want to achieve.

That is: Is your use-case actually to project a constant value?

**Comment by ikwattro** [comment]
Hi @arnefischereit Thanks for replying.

The real scenario is showing an overview of the graph schema and the counts per label : 

![Screenshot 2022-05-31 at 09 29 44](https://user-images.githubusercontent.com/1222009/171117136-54bd177f-ecb9-48a5-b84b-51a28dce65e9.png)

We can of course make one query per label, but we have customers with large schemas ( 100 labels, 900 relationship types ) so it decreases the experience.

We were then looking at replacing it with one statement with subqueries, for eg : 

```
CALL {
 MATCH (n:Movie)
 RETURN 'Movie' AS label, count(n) AS count
 
 UNION
 
 MATCH (n:Person)
 RETURN 'Person' AS label, count(n) AS count
 
 ...
 }
 ```
 
 But this hits the performance issue mentioned by this ticket when not using countstores and having nodeLabelScans on multi million nodes size.

**Comment by arnefischereit** [comment]
That looks really nice.

Would this query be feasible for you?

```gql
MATCH (n:Movie)
WITH count(*) AS count
RETURN count, 'Movie' AS label
```

In my environment, the system then comes up with this plan:

```
+--------------------------+----------------------------+----------------+---------------------+
| Operator                 | Details                    | Estimated Rows | Pipeline            |
+--------------------------+----------------------------+----------------+---------------------+
| +ProduceResults          | count, label               |              1 |                     |
| |                        +----------------------------+----------------+                     |
| +Projection              | $autostring_0 AS label     |              1 |                     |
| |                        +----------------------------+----------------+                     |
| +NodeCountFromCountStore | count( (:Movie) ) AS count |              1 | Fused in Pipeline 0 |
+--------------------------+----------------------------+----------------+---------------------+
```

**Comment by InverseFalcon** [comment]
Also favor UNION ALL instead of UNION with queries like that, otherwise it will try to implicitly deduplicate the unioned results which can be unnecessarily costly, at least when the queries are more complex and many more rows are involved.

**Comment by arnefischereit** [comment]
@ikwattro I assume that these hints have solved your issue and I will close the issue.
You can always reopen this issue or open a new one if this issue still persists.

**Comment by ikwattro** [comment]
Hi @arnefischereit , 

Sorry, I was travelling last week for GraphConnect.

It does yes, thanks a lot.

**Comment by arnefischereit** [comment]
No worries and thank you for the feedback. I hope you had a lot of fun :-)
