### ISSUE TITLE
`neo4j-admin import` on 4.4.6-community

### ISSUE THREAD

**Issue by jcuenod** [neo4j/neo4j#12885]
- Neo4j version: 4.4.6-community
- Operating system: Arch Linux (using a docker container)

**Steps to reproduce**
`docker build` this Dockerfile (with some nodes and relationships):
```
FROM neo4j:community

WORKDIR $HOME/neo4j/import
COPY nodes.csv .
COPY relationships.csv .

RUN neo4j-admin import --database=neo4j \
	--force=true \
	--nodes=nodes.csv \
	--relationships=relationships.csv
```

**Expected Behaviour**:
- Docker build/run produces expected output and prints info about created nodes and relationships
- Log in using neo4j/neo4j works
- See/query nodes and relationships in neo4j database

**Actual Behaviour**:
- Docker build/run produces expected output and prints info about created nodes and relationships
- Log in using neo4j/neo4j works
- **Neo4j has no nodes or relationships**
- if I change the db name in the `neo4j-admin import` command, the db is not listed.
  - The db cannot be created using "CREATE DATABASE dbname" because the community edition does not support multiple dbs.
  - Changing the default db in `neo4j.conf` file also shows a db that has no nodes or relationships.
Additionally, include (as appropriate) log-files, stacktraces, and other debug output.

Is `neo4j-admin import` only intended to work on the enterprise version?

**Comment by jcuenod** [comment]
To be clear, I am getting this at the end of my `docker build` step:

```
Post processing COMPLETED in 2s 807ms


IMPORT DONE in 18s 275ms. 
Imported:
  426590 nodes
  4365433 relationships
  5790861 properties
Peak memory usage: 416.4MiB
Removing intermediate container 1d672752128c
 ---> 5dff4eeac2d6
Successfully built 5dff4eeac2d6
Successfully tagged pbn4j:latest
```

**Comment by mike-gormley** [comment]
I've just been through a similar headache but found restarting neo4j after the import will show the nodes and relationships successfully. I did this with 4.4.7-community.

**Comment by 2hdddg** [comment]
Hi @jcuenod this is a docker issue, not a Neo4j issue. The base image will create the volumes and since you run the import during build after the volumes has been created everything you write to those volumes will be gone when you start the container.

As in this example:

RUN mkdir /avolume
RUN touch /avolume/works
VOLUME /avolume
RUN touch /avolume/gone
