### ISSUE TITLE
sqrt of negative number is NaN

### ISSUE THREAD

**Issue by InverseIntegral** [neo4j/neo4j#12896]
Running the following query on an empty database
```
RETURN sqrt(-9018766185607338000.0)
```
returns `NaN`. [The documentation](https://neo4j.com/docs/cypher-manual/current/functions/mathematical-logarithmic/#functions-sqrt) states that `sqrt` of any negative numerical expression should return `null` though. I guess `Math.sqrt` is called which simply returns `NaN` for negative numbers.

**Neo4j Version:** 4.4.8
**Operating System:** 5.18.2 Arch Linux
**API:** Java

**Comment by HannesSandberg** [comment]
Thank you! We will look into this and come back to you.

**Comment by nadja-muller** [comment]
Thank you for reporting this. We fixed the documentation to reflect that sqrt follows the IEEE-754 standard.
