### ISSUE TITLE
Unexpected result

### ISSUE THREAD

**Issue by pjljvandelaar** [neo4j/neo4j#12895]
Neo4j Desktop version: 1.4.15.

Given that the following queries return with the given answers.

```cypher
MATCH (n:AdaSubprogramDeclaration)<-[:References]-()-[:Source]->(f:File)
WHERE n.relativeName = "Start_Offset"
    RETURN DISTINCT f.relativeName
```
```
╒════════════════════════════════╕
│"f.relativeName"                │
╞════════════════════════════════╡
│"rejuvenation-utils.adb"        │
├────────────────────────────────┤
│"rejuvenation-text_rewrites.adb"│
├────────────────────────────────┤
│"rejuvenation-text_rewrites.ads"│
└────────────────────────────────┘
```
```cypher
MATCH (n:AdaSubprogramDeclaration)-[:Source]->(f:File)
WHERE n.relativeName = "Start_Offset"
    RETURN DISTINCT f.relativeName
```
``` 
╒═════════════════════════════════╕
│"f.relativeName"                 │
╞═════════════════════════════════╡
│"rejuvenation-node_locations.adb"│
├─────────────────────────────────┤
│"rejuvenation-node_locations.ads"│
└─────────────────────────────────┘
```
```cypher
MATCH (n:AdaSubprogramDeclaration)<-[:References*0..1]-()-[:Source]->(f:File)
WHERE n.relativeName = "Start_Offset"
    RETURN DISTINCT f.relativeName
```
```    
╒═════════════════════════════════╕
│"f.relativeName"                 │
╞═════════════════════════════════╡
│"rejuvenation-node_locations.adb"│
├─────────────────────────────────┤
│"rejuvenation-node_locations.ads"│
├─────────────────────────────────┤
│"rejuvenation-utils.adb"         │
├─────────────────────────────────┤
│"rejuvenation-text_rewrites.adb" │
├─────────────────────────────────┤
│"rejuvenation-text_rewrites.ads" │
└─────────────────────────────────┘
```
I don't understand why
```cypher
MATCH (n:AdaSubprogramDeclaration)<-[:References*]-()-[:Source]->(f:File)
WHERE n.relativeName = "Start_Offset"
    RETURN DISTINCT f.relativeName
```
returns
``` 
╒════════════════════════════════╕
│"f.relativeName"                │
╞════════════════════════════════╡
│"rejuvenation-utils.adb"        │
├────────────────────────────────┤
│"rejuvenation-text_rewrites.adb"│
├────────────────────────────────┤
│"rejuvenation-text_rewrites.ads"│
└────────────────────────────────┘
```

Is this a bug?

**Comment by HannesSandberg** [comment]
Thank you for the report! We will investigate and come back to you.

**Comment by arnefischereit** [comment]
@pjljvandelaar: Could you please elaborate on your confusion?
I do not see a contradiction from the data that you have posted so far.

The most likely scenario that I could think of is that `*` in `-[:References*]-` does not resemble the [Kleene star](https://en.wikipedia.org/wiki/Kleene_star) in that it stands for 0 or more iterations but for 1 or more iterations:
https://neo4j.com/docs/cypher-manual/current/syntax/patterns/#cypher-pattern-varlength
> Omitting both bounds is equivalent to specifying a minimum of 1, allowing paths of any positive length to be described

Does that explain your issue?

**Comment by pjljvandelaar** [comment]
Indeed I expected that + (Kleen plus) would be 1..* and * (Kleen star) would be 0..*.
But if Cypher has a different meaning for `*`: That is what confused me!

I leave it up to you to either close this issue, or 
to make cypher more intuitive (and better linked to symbols used in other query languages).

**Comment by arnefischereit** [comment]
Traditionally, we did not consider the `0..` very useful and therefore made `1..` the default.
You will, however, be pleased to read that we are in fact re-working Cypher in that regard and will in the future have the semantics that you expected.
This needs to be done in such a way that it does not break backwards compatibility and we will also make the mechanism a lot more powerful. Stay tuned!
