### ISSUE TITLE
Java 18 Support?

### ISSUE THREAD

**Issue by aress31** [neo4j/neo4j#12906]
I currently have the following version of `Java` installed on my system:

```
java 18.0.1.1 2022-04-22
Java(TM) SE Runtime Environment (build 18.0.1.1+2-6)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)
```

For some reason it seems that `neo4j` does not support this version but instead only supports the older `Java 11` version, how come? And is there any plans to increase the support coverage?

**Comment by mnd999** [comment]
I don't think we have any plans to support non-LTS (Long-Term-Support) versions of the JDK such as Java 18, no. Neo4j 3.x was on Java 8 (LTS), Neo4j 4.x uses Java 11 (LTS). The next LTS release was Java 17, so it is likely that will be supported for the Neo4j 5.x series.
