### ISSUE TITLE
Neo4j container fails to start on next Docker startup if Docker engine was shut down while Neo4j was running

### ISSUE THREAD

**Issue by Prometheus3375** [neo4j/neo4j#12908]
## Description

If Docker is stopped while Neo4j container is running, on next Docker startup Neo4j will fail to start.

## Versions
Neo4j version: 4.4.8
Operating system: Windows 10 21H2
API/Driver: Docker

## Initial steps
1. Install Docker Desktop and follow [this guide](https://docs.docker.com/desktop/windows/wsl/) to enable WSL integration.
2. Launch Docker Desktop.
3. Log into WSL in terminal (or open its terminal).
4. Create necessary directories in home directory.
   ```
   cd ~
   mkdir neo4j/data
   mkdir neo4j/import
   mkdir neo4j/logs
   mkdir neo4j/plugins
   ```
5. Give permissions to created directories.
   ```
   sudo chmod -R 777 neo4j
   ```
6. Pull neo4j container.
   ```
   docker pull neo4j:latest
   ```

## Steps to reproduce
1. Launch Docker Desktop.
2. Log into WSL in terminal (or open its terminal).
3. Run neo4j container via next command:
   ```
   docker run --name neo4j -p7474:7474 -p7687:7687 -d -v $HOME/neo4j/data:/data -v $HOME/neo4j/logs:/logs -v $HOME/neo4j/import:/var/lib/neo4j/import -v $HOME/neo4j/plugins:/plugins neo4j:latest
   ```
4. In Docker Desktop open "Containers" tab and click on Neo4j container. Wait till line "Started" is printed.
4. Quit Docker Desktop and wait its complete exit.
   ![image](https://user-images.githubusercontent.com/35541026/179291343-6a23d12c-30e5-43d9-b032-b0effa342491.png)
5. Launch Docker Desktop and wait till its engine is started.
6. Open "Containers" tab and start Neo4j container.
7. After some seconds Neo4j container will stop.

## Logs
Here is debug logs, that they do not contain any information about the cause.
[debug.log](https://github.com/neo4j/neo4j/files/9123310/debug.log)

**Comment by DakotaSpencer** [comment]
How do I fix this though?

**Comment by Prometheus3375** [comment]
I was fixing this by re-creating the container.

**Comment by Prophasi** [comment]
I'm seeing this as well, on a MacOS 12.4 host and Neo4j Enterprise 4.4.9.

In my testing, 4.4.5 works as expected; 4.4.6-4.4.9 all have this issue where the container silently exits 15-20s after startup if Docker engine was shut down without the container being explicitly stopped first. If you explicitly stop the Neo4j container before the Docker engine, it'll start back up just fine. 

This seems like a highly impactful (and at this point fairly long-lasting) bug; surprised to see so little chatter about it. Makes me wonder if it occurs in a narrower set of conditions than it seems... or perhaps the use of Neo4j in Docker is lower than I figured?

**Comment by Prometheus3375** [comment]
Hm, yesterday I stopped container before exiting Docker. Today I started container and it stopped immediately. Version 4.4.11.

**Comment by Prometheus3375** [comment]
> Hm, yesterday I stopped container before exiting Docker. Today I started container and it stopped immediately. Version 4.4.11.

This repeated again. After Neo4j container had terminated completely, docker showed status "Exited (137)", which it not normal (normal is "Exited"). Today container stops right after start.

**Comment by Prophasi** [comment]
Similarly, just now I restarted a running 4.4.5 instance (which, as I said above, previously behaved properly) from the MacOS Docker dashboard... and it stopped immediately.

However, I can't repro on a new 4.4.5 container. Presumably the other had gotten into a state that couldn't survive a restart, but it's a single-user container on my desktop with low average load & nothing weird or custom. Regardless, seems clear this can happen even if the container is stopped properly before Docker itself.

Would be nice to get an official repro confirmation on this one. The steps are simple:
1. Pull latest image (in my latest test, 4.4.12-enterprise)
2. In Docker Dashboard, run image with only NEO4J_ACCEPT_LICENSE_AGREEMENT=yes env var
3. With container still running, restart Docker Desktop
4. When Docker comes back up, start the container
5. Observe that it immediately and silently stops with no error messages

I have confirmed this behavior for Enterprise from 4.4.6-4.4.12 on both MacOS (12.4) and Windows 10 (21H2) and Docker Desktop v4.12.0 (although also true at least as far back as 4.11.1). It should be noted that my MacOS instance is on an M1 MBP; the Win10 instance is on x64.

Again, given the longevity, breadth, and severity of this, it would be great to know that it's at least been confirmed by the Neo4j team, if not to have at least a vague expectation of timeline to fix. I understand there are plenty of competing priorities, but we're 3 months in on (what could be) a pretty bad issue that should take under 15 mins to confirm.

**Comment by Prometheus3375** [comment]
> This repeated again. After Neo4j container had terminated completely, docker showed status "Exited (137)", which it not normal (normal is "Exited"). Today container stops right after start.

Recorded this. I do not know how to reproduce the issue, it is random. Started to happen after updating to 4.4.11. No Docker restart required.

https://user-images.githubusercontent.com/35541026/198111800-781b0f82-35ae-4bc1-8db0-c3c8b174be54.mp4

**Comment by coderQuan** [comment]
Hi guys, I met the same problem here and I seem to have solved it. If Neo4J in container stopped abnormally, it will exit at the next startup(like docker restart). By default Neo4J check if the instance is already running by PID file, if so the new process will exit with code 1. That PID file is in `/var/lib/neo4j/run`, but in container we should set in to `/run`, and then Neo4J will startup again. So just add this line to neo4j.conf:

`dbms.directories.run=/run`

**Comment by Prometheus3375** [comment]
@coderQuan, container with version 4.4.20 stores PID file inside `/var/lib/neo4j/run`.

![image](https://github.com/neo4j/neo4j/assets/35541026/a6cf0a8f-d813-4437-b638-37a2118a5327)

**Comment by jeffrey-e** [comment]
> Hi guys, I met the same problem here and I seem to have solved it. If Neo4J in container stopped abnormally, it will exit at the next startup(like docker restart). By default Neo4J check if the instance is already running by PID file, if so the new process will exit with code 1. That PID file is in `/var/lib/neo4j/run`, but in container we should set in to `/run`, and then Neo4J will startup again. So just add this line to neo4j.conf:
> 
> `dbms.directories.run=/run`

Thank you for this! Should be part of the docs or default in the container images!

**Comment by jeffrey-e** [comment]
Okay so the fix mentioned in my last comment did not seem to work entirely.
Since I have adjusted the following in my docker-compose service for neo4j it seemed to work better

```
tmpfs:
      - /var/lib/neo4j/run
```

**Comment by Prophasi** [comment]
@coderQuan Can you share the rationale of your fix?

I gather that while Neo4j is running it stores its pid in that file, and if it exists on startup, Neo4j thinks it's already running and errors with -1. Container dies.

From what I've read, /run is often meant to be cleared out on system restart, due to it being mounted as tmpfs; but /run isn't a tmpfs mount point in my container, so it doesn't get cleared and in principle this shouldn't solve the problem... BUT neo4j doesn't have write perms to /run, and no neo4j.pid file appears there after the config change, so it seems it just never creates the pid file. So no more pid conflict - but if I'm right it means that any directory, not just /run, would work as long as neo4j can't write to it.

Does anyone know what not having a pid file could impact? From what I read it might be used by other processes... but I'd think that's less of a concern in a dedicated docker container. Do any other neo4j processes, e.g. neo4j-admin or related tools, require it?

For the above reasons, I could see the above tmpfs approach by @jeffrey-e , or something similar, maybe being the best mix - you still have the pid file as designed while running, but it's deleted automatically on restart (graceful or not).

But I could be wrong on several points here - I'm not too familiar w/ pid files and /run, so just feeling my way through it.

**Comment by NilsMoller** [comment]
I'm having the same problem. I have been recreating the container every time. Docker compose:
```yaml
cxc-db:
  image: neo4j:4.4.17
  hostname: db
  container_name: db
  ports:
    - "7474:7474"
    - "7687:7687"
  volumes:
    - ./generated/neo4j/dev/data:/var/lib/neo4j/data
  environment:
    NEO4J_dbms_logs_debug_level: DEBUG
    NEO4J_AUTH: ${db__user}/${db__password}
    NEO4J_dbms_directories_plugins: "/var/lib/neo4j/labs"
    NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
    NEO4J_dbms_security_procedures_allowlist: "gds.*,apoc.*"
    NEO4J_apoc_export_file_enabled: "true"
    NEO4J_apoc_import_file_enabled: "true"
    NEO4J_apoc_import_file_use__neo4j__config: "true"
```

**Comment by yackermann** [comment]
This issue is really screwed up and needs to be addressed.
