### ISSUE TITLE
Cypher expression `exists(() --> (node))` evaluates to false when actually it is true

### ISSUE THREAD

**Issue by Prometheus3375** [neo4j/neo4j#12909]
## Version

Neo4j version: 4.4.8
Operating system: Windows 10 21H2
API/Driver: Docker, Python 3.9, Python Neo4j driver 4.4.4.

## Steps to reproduce

- Deploy neo4j database somewhere, I am using Docker container.
- Run next Python script below. It is just for convenience, all transactions can be done in Neo4j web interface.

```python
from neo4j import GraphDatabase

with GraphDatabase.driver("bolt://localhost:7687", auth=('neo4j', 'neo')) as driver, \
        driver.session() as session:
    create_graph = """
    MERGE (n1:Test:Entity:Company {nodeId: "0000"}) SET n1.name = "Peter company"
    MERGE (n2:Test:Entity:Person {nodeId: "0001"}) SET n2.name = "Peter"
    MERGE (n3:Test:Property:Charge {nodeId: "0002"}) SET n3.status = "closed"
    MERGE (n4:Test:Property:Charge {nodeId: "0003"}) SET n4.status = "opened"
    MERGE (n5:Test:Property:Address {nodeId: "0004"}) SET n5.country = "France"
    MERGE (n6:Test:Property:Address {nodeId: "0005"})
        SET n6.country = "France"
        SET n6.city = "Ham Les Varennes"
    MERGE (n7:Test:Property:Date {nodeId: "0006"})
        SET n7.date = datetime("2014-09-04T00:00:00")
        SET n7.monthIsKnown = true
        SET n7.dayIsKnown = true
    MERGE (n8:Test:Property:Date {nodeId: "0007"})
        SET n8.date = datetime("1962-01-01T00:00:00")
        SET n8.monthIsKnown = false
        SET n8.dayIsKnown = false
    MERGE (n9:Test:Entity:Company {nodeId: "0008"}) SET n9.name = "Other company"
    MERGE (n10:Test:Property:Date {nodeId: "0009"})
        SET n10.date = datetime("1962-01-01T00:00:00")
        SET n10.monthIsKnown = false
        SET n10.dayIsKnown = false
    MERGE (n11:Test:Property:Date {nodeId: "0010"})
        SET n11.date = datetime("1976-01-01T00:00:00")
        SET n11.monthIsKnown = false
        SET n11.dayIsKnown = false

    MERGE (n1)-[:HAS_CHARGE {id: 1}]->(n3)
    MERGE (n1)-[:HAS_CHARGE {id: 2}]->(n4)
    MERGE (n1)-[:HAS_PRIMARY_ADDRESS {id: 3}]->(n5)
    MERGE (n1)-[:HAS_SECONDARY_ADDRESS {id: 4}]->(n6)
    MERGE (n1)-[:HAS_TERMINATION_DATE {id: 5}]->(n7)
    MERGE (n1)-[:HAS_CREATION_DATE {id: 6}]->(n8)
    MERGE (n1)-[:HAS_CREATION_DATE {id: 7}]->(n10)

    MERGE (n2)-[:FR_DIRECTOR {id: 8}]->(n1)
    MERGE (n2)-[:HAS_COUNTRY_OF_RESIDENCE {id: 9}]->(n5)
    MERGE (n2)-[:HAS_DATE_OF_BIRTH {id: 10}]->(n11)

    MERGE (n9)-[:HAS_CREATION_DATE {id: 11}]->(n8)
    """

    with session.begin_transaction() as tx:
        tx.run(create_graph)

    batch = [
        {
            'entityId':    '0000',
            'propertyIds': ['0002', '0003', '0004', '0005', '0006', '0009']
            },
        {
            'entityId':    '0001',
            'propertyIds': ['0004', '0010']
            },
        ]

    clean_old_properties = """
    UNWIND $batch AS data 
    MATCH (n:Entity { nodeId: data.entityId }) 
    OPTIONAL MATCH (n)-[rel]->(prop:Property) 
    WHERE NOT prop.nodeId IN data.propertyIds
    DELETE rel
    WITH prop
    WHERE NOT exists(()-->(prop))
    DELETE prop
    """

    with session.begin_transaction() as tx:
        tx.run(clean_old_properties, dict(batch=batch))
```

- You will get an error:
  ```
  neo4j.exceptions.ConstraintError: {code: Neo.ClientError.Schema.ConstraintValidationFailed} {message: Cannot delete node<7>, because it still has relationships. To delete this node, you must first delete its relationships.}
  ```
- Open Neo4j web interface and find node in the error (in my case it was node<7>). It will have incoming relationships, but for some reason `exists(()-->(prop))` returned `false` in transaction.

The second transaction removes connections between entities and properties. If after that a property has no incoming relationships (they can have only incoming), it is removed. In this example, company `0000` loses connection to property `0007`. But company `0008` has connection to it, so property is not removed. But for some reason `exists(()-->(prop))` yields `false`, so there is an attempt to delete that property. If `exists(()-->(prop))` replaced with `exists(()--(prop))`, everything works as indented.

I [asked](https://stackoverflow.com/questions/71886101/why-neo4j-cypher-expression-exists-n-evaluates-to-false-when-actually) about this on StackOverflow, but no one answered if this is my mistake in query or somewhere else, so I think this is a bug.

**Comment by HannesSandberg** [comment]
Hi! Thanks for your report, we will investigate this and come back to you!

**Comment by Prometheus3375** [comment]
I actually got an error in live project even with condition `exists(()--(prop))`. For now I consider to do removal of orphan properties separately.

**Comment by loveleif** [comment]
Hi @Prometheus3375, thanks again for taking the time to report this, and sorry to let you wait. I can reproduce the issue and as far as I can tell it's a bug in our kernel API, I'm sending the issue to our kernel team.

**Comment by zimmre** [comment]
Hi @Prometheus3375 thank you again for raising the issue, I've just merged a fix for it, will be out with the next release
