### ISSUE TITLE
Neo.ClientError.Security.AuthenticationRateLimit

### ISSUE THREAD

**Issue by wuzhijin98** [neo4j/neo4j#12904]
When I log in to the database, an error Neo.ClientError.Security.AuthenticationRateLimit: The client has provided incorrect authentication details too many times in a row pops up. Even if I delete the DBMS file, it is useless

**Comment by HannesSandberg** [comment]
Hello! Please make sure that you don't have another process that tries to connect with the wrong credentials (for example an open neo4j browser). You can try to start it up using a different port number to make sure nothing else is trying to connect.

**Comment by mnd999** [comment]
We haven't heard anything back on this issue for a while so I will close for now. If it's still an issue, please feel free to reopen.
