### ISSUE TITLE
Wrong error statement when calling `localdatetime()` function with `DISTINCT`

### ISSUE THREAD

**Issue by SeboCode** [neo4j/neo4j#12910]
I found a bug in an error message when calling the function `localdatetime()` with the `DISTINCT` keyword.

- Neo4j version: 4.4.8
- Operating system: Arch Linux 5.18.3
- API/Driver: Java/Sandbox

### Steps to reproduce
Execute the wrong statement
```
RETURN localdatetime(DISTINCT "1970-01-01")
```

### Expected behavior
Neo.ClientError.Statement.SyntaxError is thrown with error message:
```
Invalid use of DISTINCT with function 'localdatetime' (line 1, column 8 (offset: 7))
"RETURN localdatetime(DISTINCT "1970-01-01")"
```
### Actual behavior
Neo.ClientError.Statement.SyntaxError is thrown with error message:
```
Invalid use of DISTINCT with function 'UNKNOWN' (line 1, column 8 (offset: 7))
"RETURN localdatetime(DISTINCT "1970-01-01")"
```
Notice the UNKNOWN function name in the error message. This doesn't happen with other functions that don't support `DISTINCT` such as `id()`.

**Comment by abhinavchawla07** [comment]
@SeboCode I would love to work on this issue.

**Comment by SeboCode** [comment]
@abhinavchawla07 Go for it. I'm currently busy with other projects, so I was not planning on fixing it myself 👍🏼

**Comment by HannesSandberg** [comment]
Thanks for the report! We will investigate

**Comment by Lojjs** [comment]
@SeboCode Sorry for the late reply. As you can see on the linked PRs this was fixed at the time but we missed to close the Github issue.

Best regards Louise, Neo4j Cypher team
