### ISSUE TITLE
Asking for help on the storage engine of Neo4j

### ISSUE THREAD

**Issue by GaoDong666** [neo4j/neo4j#12923]
Hello!
There is no doubt that Neo4j is a well-deserved mainstream graph database!
For experimental purposes, I need to modify Neo4j's storage engine and reimplement the underlying data structures like nodes, relationships and graphs in another way.  Could you please tell me which parts of the Neo4j's source code should I modify?
Thank You!

**Comment by Roxling** [comment]
Hello!
For experimental purposes I would suggest to modify the existing engine, as completely writing a new one is an undertaking that likely takes years to do properly, even with intricate knowledge of how it works. I would suggest the following starting point https://github.com/neo4j/neo4j/blob/4.4/community/record-storage-engine/src/main/java/org/neo4j/internal/recordstorage/RecordStorageEngineFactory.java and work your way from there. I would also recommend reading the database internal sections of https://neo4j.com/graph-databases-book/ to get an idea of how these things work. Good luck!

**Comment by GaoDong666** [comment]
@Roxling Thanks for your reply! I'm new to Neo4j and I wonder is there any source code analysis (such as tutorial or documentation) for Neo4j?

**Comment by Roxling** [comment]
Neo4j has plenty of documentation here: https://neo4j.com/docs/
However, not much public documentation of how it works internally. The storage engine api is a fully internal api not really intended for the community to use and build their own storage engines. It has never been done as far as I am aware. Neo4j community edition is fully open sourced so you will have to read the code to figure out how and what to do. It is possible but it will be a lot of work

**Comment by Roxling** [comment]
If you have any more questions, don't hesitate to reach out
