### ISSUE TITLE
windows neo4j community could not find java even if its there.

### ISSUE THREAD

**Issue by buyvtuygJW** [neo4j/neo4j#12934]
##  bug report
a slightly memefied yt vid is made to demonstrate that there is actually a actual valid java binary there,https://youtu.be/qGIVJ2f_ASg

- Neo4j version: 4.4.10
- Operating system: win10

### Steps to reproduce
1. download the community installer,install it.
2. get the jdk ready in a console.use that console cd to the neo4j bin folder
3. run>neo4j

### Expected behavior

just run properly,it should be properly identifiying java from JAVA_HOME,like maven.

### Actual behavior
Invoke-Neo4j : Could not find java at "X:\CrossJava\jdk-18"\bin\java.exe
At D:\2ndProgramFiles\neo4j-community-4.4.10\bin\neo4j.ps1:21 char:7
+ Exit (Invoke-Neo4j -Verbose:$Arguments.Verbose -CommandArgs $Argument ...
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-Neo4j

**Comment by buyvtuygJW** [comment]
is should be a quick fix on powershell side and that should be ok.
though if someone can verify it works on other windows device,then it would means that there is some ps incompatible version or whatnot.

**Comment by klaren** [comment]
Not entirely sure what goes wrong. The code is here https://github.com/neo4j/neo4j/blob/4.4/packaging/standalone/src/main/distribution/shell-scripts/bin/Neo4j-Management/Invoke-Neo4jUtility.ps1#L128 and it looks like it checks `JAVA_HOME` first before going to the registry. Maybe you can follow the code and see if you can see where it fails? My Windows installation works as expected.

**Comment by buyvtuygJW** [comment]
It doesnt seems to go through this function, https://github.com/neo4j/neo4j/blob/4.4/packaging/standalone/src/main/distribution/shell-scripts/bin/Neo4j-Management/Invoke-Neo4jUtility.ps1#L128 

I tried adding 

echo 'ok,utility'
before the>
$javaPath = ''
    $javaCMD = ''

    $EnvJavaHome = Get-Neo4jEnv 'JAVA_HOME'
  
    # Is JAVA specified in an environment variable


No echo is seen in console.
I think this error pops up before even reaching there.

**Comment by buyvtuygJW** [comment]
The only thing i know is if i change the neo4j.ps1 content to>
echo 'okneo4j'
Exit (Invoke-Neo4j -Verbose:$Arguments.Verbose -CommandArgs $Arguments.Args)

console>
okneo4j
Invoke-Neo4j : Unable to determine the path to java.exe
At D:\2ndProgramFiles\neo4j-community-4.4.10\bin\neo4j.ps1:22 char:7
+ Exit (Invoke-Neo4j -Verbose:$Arguments.Verbose -CommandArgs $Argument ...
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-Neo4j


I tried adding echo in invoke-neo4j no response.no idea where it crashes,maybe runtime calling function has some bad values?

**Comment by klaren** [comment]
You don't see the output because it is running in a sub-shell. Try using `Write-Host "my message"` instead.

**Comment by buyvtuygJW** [comment]
you are right.
I now can confirm it at least reaches the write error in invokeneo4j

>neo4j
okneo4j
ok invoke,in begin
invoke,at catch writeerror
Invoke-Neo4j : Unable to determine the path to java.exe
At D:\2ndProgramFiles\neo4j-community-4.4.10\bin\neo4j.ps1:22 char:7
+ Exit (Invoke-Neo4j -Verbose:$Arguments.Verbose -CommandArgs $Argument ...
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-Neo4j

**Comment by buyvtuygJW** [comment]
maybe i can try directly call the jar with the correct parameters as test?
If know the full cmd.it may help.

**Comment by klaren** [comment]
Are you certain that you have set up `JAVA_HOME` correctly? 

If you do `echo %JAVA_HOME%` in cmd.exe what does it say?

**Comment by buyvtuygJW** [comment]
"F:\Prog\RIJDKcollec\win"\jdk-11

**Comment by buyvtuygJW** [comment]
and if it setup my maven path>
F:\Prog\lateststableprog_crossapps_nonlua\Javabuildzone\maven>set PATH="%cd%\apache-maven-3.8.5\bin";%PATH%

F:\Prog\lateststableprog_crossapps_nonlua\Javabuildzone\maven>mvn
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.243 s
[INFO] Finished at: 2022-09-14T23:59:47+09:00
[INFO] ------------------------------------------------------------------------
[ERROR] No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoGoalSpecifiedException

maybe i can try reinstall JDK later.

**Comment by buyvtuygJW** [comment]
not sure if it helps though lol.i have no idea now.

**Comment by buyvtuygJW** [comment]
does neo4j has a *Batteries included/zipped(JRE included release)?
since I actually want to use a graph database instead of the inflexible old school sql.
Any temporary solutions would be awesome.

**Comment by klaren** [comment]
> does neo4j has a *Batteries included/zipped(JRE included release)? 

For managing a neo4j install on a developer computer I would recommend you give "Neo4j Desktop" a try. https://neo4j.com/product/developer-tools/
