### ISSUE TITLE
Wrong output when making neo4j-Admin command in Process .NET

### ISSUE THREAD

**Issue by MrDanLeaf** [neo4j/neo4j#12935]
- Neo4j Desktop Version 1.4.15
- Win10

When using Microsoft Process Class in C# .NET and running neo4j-admin command (-dump or load)

the output stream ends up on wrong place.

Example code:

                    using (var p = new Process()
                                           {
                                               StartInfo = new ProcessStartInfo
                                               {
                                                   RedirectStandardOutput = true,
                                                   RedirectStandardError = true,
                                                   UseShellExecute = false,
                                                   CreateNoWindow = true,
                                                   FileName = @"* * * * *\v1.0\powershell.exe",
                                                   Arguments = argument,
                                               }
                                           })
                                    {
                    
                    p.OutputDataReceived += (sender, args) =>  { Debug.WriteLine( args.Data); };
                    p.ErrorDataReceived += (sender, args) =>  { Debug.WriteLine( args.Data); };
            
                    p.Start();
                    p.BeginOutputReadLine();
                    p.BeginErrorReadLine();
                    p.WaitForExit();
                }

### Expected behavior 
Output On OutputDataRecived

### Actual behavior
Output: On ErrorDataRecived.

**Comment by burqen** [comment]
Hi @MrDanLeaf Neo4j 4.1 is no longer maintained. Do you see the same issue with Neo4j 4.4?

**Comment by MrDanLeaf** [comment]
We are running and using neo4j desktop 1.4.15. I forgot to mention that in topic.

**Comment by burqen** [comment]
@MrDanLeaf I see. And what version of Neo4j are you using for the dbms?

Could you also provide the output that you get for both `OutputDataReceived` and `ErrorDataReceived`?

**Comment by MrDanLeaf** [comment]
Sorry for late answer. The problem is not the output. The problem is that all output comes in errorDataRecived. Regardless if the output is error or standard.

Version for dbms is 4.4.5

**Comment by Roxling** [comment]
@MrDanLeaf This is not a bug, but a design decision that is not an uncommon pattern in the world of command line tools on unix systems. The main reason for this is that tools often is used with a pipe into another tool. In this specific case the output of a `dump` command can be directed to the input of a `load` command (when `--to-stdout` & `--from-stdin` is provided). So printing all information in the error stream will make it not interfere with this functionality.
