### ISSUE TITLE
The doc about `in list predicates` is not correct

### ISSUE THREAD

**Issue by jievince** [neo4j/neo4j#12946]
The doc about in list predicates say:

[all()](https://neo4j.com/docs/cypher-manual/4.4/functions/predicate/)
```
The function all() returns true if the predicate holds for all elements in the given list. null is returned if the list is null or all of its elements are null.

Syntax: all(variable IN list WHERE predicate)
```

It says *all() returns null if all of its elements are null*.
But the tested result is not as expect as it says.

### Actual behavior
![image](https://user-images.githubusercontent.com/38901892/191154493-829dea45-06ee-4446-a438-6d9e20f88ba5.png)
![image](https://user-images.githubusercontent.com/38901892/191154513-0dfbe5bd-860f-4c99-8dac-efc8cfcb0e92.png)

**Comment by anonyXmous** [comment]
@jievince I CANNOT simulate this issue on my browser.  It is returning the correct result: true.
What is your neo4 version, OS and neo4j browser?

Neo4j Server version: [4.4.3] (enterprise)

Operating system: macOS Monterey 12.5.1 (21G83)

Neo4j Browser version: [4.4.2]

**Comment by jievince** [comment]
Yeah, I mean the result `true` is correct.
But the document is wrong, it says the predicate will return null if all of the elements of the list is null.

**Comment by jievince** [comment]
Neo4j Server version: [4.2.1] (community)

Operating system: macOS Monterey 12.6 (21G83)

Neo4j Browser version: [4.2.0]

**Comment by anonyXmous** [comment]
I cannot simulate your issue and we have different results

**Comment by HannesSandberg** [comment]
Thanks for the report. We will look into this!

**Comment by Lojjs** [comment]
@jievince Sorry for the late reply. The docs were wrong and has since been updated.

Best regards Louise, Neo4j Cypher team
