### ISSUE TITLE
OutofMemory - StatementProcessorTxManager leak suspect

### ISSUE THREAD

**Issue by peteneville** [neo4j/neo4j#12945]
## Bug report
After start-up we see an out of memory condition occurring within 24hrs usually, depending on max heap size set.
We have been taking period heap dumps using map. Using the Eclipse Memory Analyzer we can see the following info on a leak suspect:
One instance of ‘org.neo4j.bolt.transaction.StatementProcessorTxManager’ loaded by ‘jdk.internal.loader.ClassLoaders$AppClassLoader @ 0xe08f5ea0’ occupies 311,070,080 (90.32%) bytes. The memory is accumulated in one instance of ‘java.util.concurrent.ConcurrentHashMap$Node[]’, loaded by ‘<system class loader>’, which occupies 311,069,848 (90.32%) bytes.

We have tried larger heap sizes(currently max of 512Mb) but we just see the time before failure increasing and the memory used by org.neo4j.bolt.transaction.StatementProcessorTxManager increasing.
All queries (no writes) are sent using a single request against the /db/neo4j/tx/commit (by the .Net C# client).

**Versions**

- Neo4j community (single server) version: 4.4.11 and 4.4.10
- Operating system: Ubuntu 22.04.1 LTS running on Azure App Service for Linux as Docker container
- API/Driver:  Neo4jClient 4.1.26 (HTTP client)
- .NET Version .NET core 3.1

**Steps to reproduce**
The out of memory condition occurs within 24hrs usually, depending on max heap size set. The database receives a around 4 requests per second constant load.

**Additional context**
Empty database has been upgraded from 2.3 all the way to the current latest without any problem. Unfortunately, we cannot use the new bolt protocol directly as we use Azure App service to host neo4j server.

**Comment by klaren** [comment]
Hello and thanks for reporting!

This looks very similar to an issue patched in 4.4.11, https://neo4j.com/release-notes/database/neo4j-4-4-11/

Namely the `Fixing an issue where ‘CALL { … } IN TRANSACTIONS’ could leak inner transactions when the outer transaction was terminated during execution, e.g by timeout`.

Are you certain that this happens in 4.4.11 as well?

**Comment by peteneville** [comment]
> Hello and thanks for reporting!
> 
> This looks very similar to an issue patched in 4.4.11, https://neo4j.com/release-notes/database/neo4j-4-4-11/
> 
> Namely the `Fixing an issue where ‘CALL { … } IN TRANSACTIONS’ could leak inner transactions when the outer transaction was terminated during execution, e.g by timeout`.
> 
> Are you certain that this happens in 4.4.11 as well?

Hi, 
Yes definitely 4.4.11, downloaded from https://dist.neo4j.org/neo4j-community-4.4.11-unix.tar.gz
Tried 4.4.10 and same. 
Do you know which version this issued surfaced in, enabling us to go back to one before?
Please let me know if I can provide any further information to help.
Thanks,
Peter

**Comment by peteneville** [comment]
For info - I've switched to 4.3.18 to rule out 4.4. So far so good (running for 2hrs) as normally I'd have seen the issue by now.

**Comment by klaren** [comment]
Thanks for the update. It might be that there is a similar issue to the one fixed in 4.4.11 in the HTTP(S) endpoint as well. The fix targeted the bolt server. I'll forward this to the appropriate team for investigation.

**Comment by peteneville** [comment]
Thank you - that makes sense. 4.3.18 now running for 48hrs and no sign of this issue.

**Comment by gjmwoods** [comment]
Hello @peteneville. Many thanks for raising this issue. I was able to reproduce and fix the issue thanks to your clear description. The next release (4.4.12) will contain the fix which is scheduled for the end of this month.

Many thanks again.
