### ISSUE TITLE
Collection index range is not returning correct result

### ISSUE THREAD

**Issue by anonyXmous** [neo4j/neo4j#12947]
This is my neo4j version details:

- Neo4j Server version: [4.4.3] (enterprise)
- Operating system: macOS Monterey 12.5.1 (21G83)
- Neo4j Browser version: [4.4.2]  

- **Steps to reproduce**
Create below nodes/relationships:
MERGE (h1:Hashtag {tag: '#tag1'}) 
MERGE (h2:Hashtag {tag: '#tag2'}) 
MERGE (h3:Hashtag {tag: '#tag3'}) 

MERGE (t1: Tweet {id: 1, postedTimeStamp: datetime({epochmillis: apoc.date.parse("25-08-2021", "ms", "dd-MM-yyyy")})}) 
MERGE (t2: Tweet {id: 2, postedTimeStamp: datetime({epochmillis: apoc.date.parse("25-08-2021", "ms", "dd-MM-yyyy")})}) 
MERGE (t3: Tweet {id: 3, postedTimeStamp: datetime({epochmillis: apoc.date.parse("25-08-2021", "ms", "dd-MM-yyyy")})}) 
MERGE (t4: Tweet {id: 4, postedTimeStamp: datetime({epochmillis: apoc.date.parse("25-08-2021", "ms", "dd-MM-yyyy")})})  
MERGE (t5: Tweet {id: 5, postedTimeStamp: datetime({epochmillis: apoc.date.parse("25-08-2021", "ms", "dd-MM-yyyy")})})  

MERGE (t6: Tweet {id: 6, postedTimeStamp: datetime({epochmillis: apoc.date.parse("26-08-2021", "ms", "dd-MM-yyyy")})}) 
MERGE (t7: Tweet {id: 7, postedTimeStamp: datetime({epochmillis: apoc.date.parse("26-08-2021", "ms", "dd-MM-yyyy")})}) 
MERGE (t8: Tweet {id: 8, postedTimeStamp: datetime({epochmillis: apoc.date.parse("26-08-2021", "ms", "dd-MM-yyyy")})}) 

MERGE (h1)-[:TAGS]-(t1) 
MERGE (h1)-[:TAGS]-(t2)
MERGE (h2)-[:TAGS]-(t2)
MERGE (h1)-[:TAGS]-(t3)
MERGE (h2)-[:TAGS]-(t3)
MERGE (h3)-[:TAGS]-(t3)
MERGE (h1)-[:TAGS]-(t4)
MERGE (h2)-[:TAGS]-(t4)
MERGE (h3)-[:TAGS]-(t4)
MERGE (h2)-[:TAGS]-(t5)

MERGE (h3)-[:TAGS]-(t6) 
MERGE (h3)-[:TAGS]-(t7) 
MERGE (h3)-[:TAGS]-(t8) 
MERGE (h2)-[:TAGS]-(t6) 
MERGE (h1)-[:TAGS]-(t7) 

Query:
MATCH (h:Hashtag)-[:TAGS]-(t:Tweet) 
WITH h.tag AS hashtag, date(t.postedTimeStamp) AS PostDate 
WITH PostDate, hashtag, count(hashtag) AS tagCount ORDER BY tagCount DESC
RETURN PostDate, COLLECT(hashtag)[0..1]  AS tags 

- Expected behavior
╒════════════╤═════════════════╕
│"PostDate"  │"tags"           │
╞════════════╪═════════════════╡
│"2021-08-25"│["#tag2","#tag1"]│
├────────────┼─────────────────┤
│"2021-08-26"│["#tag3","#tag1"]│
└────────────┴─────────────────┘

- Actual behavior
╒════════════╤═════════╕
│"PostDate"  │"tags"   │
╞════════════╪═════════╡
│"2021-08-25"│["#tag2"]│
├────────────┼─────────┤
│"2021-08-26"│["#tag3"]│
└────────────┴─────────┘
 

Looks like the index range in the list (collect )is not working well.  Also try COLLECT(hashtag)[0..2]  and it returns only two items in the instead of three items.

For any further questions, please let me know. Thanks.

**Comment by mnd999** [comment]
Thanks for getting in touch, if I understand the issue correctly you are expecting the following result to be `[1,2]`
```
neo4j@neo4j> WITH [1,2,3] as list RETURN list[0..1];
+------------+
| list[0..1] |
+------------+
| [1]        |
+------------+
``` 
Looking at [the documentation](https://neo4j.com/docs/cypher-manual/current/syntax/operators/#syntax-accessing-elements-in-a-list), "the square brackets will extract the elements from the start index 1, and up to (but excluding) the end index 3", so I believe the query to be working correctly.
If this is still an issue or I have not interpreted your report correctly, please let me know.

**Comment by anonyXmous** [comment]
If you say list starts with index 1, then why below is happening?

WITH [1,2,3] as list RETURN list[1..3] will show [2,3].  

Something is not correct, right?
