### ISSUE TITLE
Version 5.1 breaks docker-compose container start

### ISSUE THREAD

**Issue by leveraction** [neo4j/neo4j#12956]
I have been using the community edition (latest) for at least two years with docker compose without issues.  The version 5.1 community container will not start.  It complains that 0.0.0.0 cannot be validated as an http listening address. Previously, this was never a problem as version 4.4.12-community still works.

From docker-compose... 
`
  graph_db:
    container_name: graph_db_container
    image: neo4j:latest
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./plugins:/plugins
      - ./import:/import
      - ./neo4j:/neo4j
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"

    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_dbms_security_procedures_whitelist=gds.*, apoc.*
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_connector_bolt_advertised__address=0.0.0.0:7687
      - NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687
      - NEO4J_dbms_connector_https_enabled=true
      - NEO4J_dbms_ssl_policy_bolt_enabled=true
      - NEO4J_dbms_default__advertised__address=localhost
      - NEO4J_dbms_ssl_policy_bolt_base__directory=/neo4j/ssl/bolt
      - NEO4J_dbms_ssl_policy_bolt_private__key=/neo4j/ssl/bolt/private.key
      - NEO4J_dbms_ssl_policy_bolt_public__certificate=/neo4j/ssl/bolt/public.crt
      - NEO4J_dbms_ssl_policy_bolt_client__auth=NONE
      - NEO4J_dbms_connector_bolt_tls__level=OPTIONAL
      - NEO4J_dbms_ssl_policy_https_enabled=true
      - NEO4J_dbms_ssl_policy_https_base__directory=/neo4j/ssl/https
      - NEO4J_dbms_ssl_policy_https_private__key=/neo4j/ssl/https/private.key
      - NEO4J_dbms_ssl_policy_https_public__certificate=/neo4j/ssl/https/public.crt
      - NEO4J_dbms_ssl_policy_https_client__auth=NONE
      - NEO4J_dbms_connector_http_advertised__address=0.0.0.0:7474
      - NEO4J_dbms_connector_http_listen__address=0.0.0.0:7474

      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_default__database=neo4j
      - NEO4J_AUTH=neo4j/test
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    restart: unless-stopped
`

Ubuntu 20
docker-compose
neo4j:latest

### Expected behavior
container starts like it always has

### Actual behavior
error concerning the use of the 0.0.0.0 address.

**Comment by jennyowen** [comment]
Does it work if you use `localhost` instead of `0.0.0.0`? 
Also can you share the actual error message please.

**Comment by leveraction** [comment]
Full error with 'latest' container
Failed to read config /var/lib/neo4j/conf/neo4j.conf: Error evaluating value for setting 'server.http.advertised_address'. Failed to validate '0.0.0.0:7474' for 'server.http.advertised_address': advertised address cannot be '0.0.0.0'

I tried localhost and it also failed although IIRC localhost won't work in my use case because other containers can't communicate with the neo4j container in cases where the neo4j container is only listening on localhost.
Error when trying localhost:

graph_db_container | Changed password for user 'neo4j'. IMPORTANT: this change will only take effect if performed before the database is started for the first time.
graph_db_container | 2022-10-26 20:12:26.484+0000 WARN  Setting 'dbms.allow_upgrade' is removed. It no longer has any effect.
graph_db_container | 2022-10-26 20:12:26.487+0000 WARN  Use of deprecated setting 'dbms.connector.http.listen_address'. It is replaced by 'server.http.listen_address'.
graph_db_container | 2022-10-26 20:12:26.487+0000 WARN  Use of deprecated setting 'dbms.connector.bolt.advertised_address'. It is replaced by 'server.bolt.advertised_address'.
graph_db_container | 2022-10-26 20:12:26.487+0000 WARN  Use of deprecated setting 'dbms.connector.bolt.tls_level'. It is replaced by 'server.bolt.tls_level'.
graph_db_container | 2022-10-26 20:12:26.487+0000 WARN  Use of deprecated setting 'dbms.connector.https.enabled'. It is replaced by 'server.https.enabled'.
graph_db_container | 2022-10-26 20:12:26.487+0000 WARN  Use of deprecated setting 'dbms.connector.http.advertised_address'. It is replaced by 'server.http.advertised_address'.
graph_db_container | 2022-10-26 20:12:26.488+0000 WARN  Use of deprecated setting 'dbms.connector.bolt.listen_address'. It is replaced by 'server.bolt.listen_address'.
graph_db_container | 2022-10-26 20:12:26.488+0000 WARN  Use of deprecated setting 'dbms.security.procedures.whitelist'. It is replaced by 'dbms.security.procedures.allowlist'.
graph_db_container | 2022-10-26 20:12:26.488+0000 WARN  Use of deprecated setting 'dbms.default_database'. It is replaced by 'initial.dbms.default_database'.
graph_db_container | 2022-10-26 20:12:26.488+0000 WARN  Use of deprecated setting 'dbms.default_listen_address'. It is replaced by 'server.default_listen_address'.
graph_db_container | 2022-10-26 20:12:26.488+0000 WARN  Use of deprecated setting 'dbms.default_advertised_address'. It is replaced by 'server.default_advertised_address'.
graph_db_container | 2022-10-26 20:12:26.488+0000 WARN  Use of deprecated setting 'dbms.memory.heap.max_size'. It is replaced by 'server.memory.heap.max_size'.
graph_db_container | 2022-10-26 20:12:26.488+0000 WARN  Use of deprecated setting 'dbms.memory.heap.initial_size'. It is replaced by 'server.memory.heap.initial_size'.
graph_db_container | 2022-10-26 20:12:26.494+0000 INFO  Starting...
graph_db_container | 2022-10-26 20:12:26.745+0000 INFO  This instance is ServerId{9c503816} (9c503816-34f4-44c6-8c1a-2f4d2873fd1f)
graph_db_container | SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
graph_db_container | SLF4J: Defaulting to no-operation (NOP) logger implementation
graph_db_container | SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
graph_db_container | 2022-10-26 20:12:27.154+0000 INFO  ======== Neo4j 5.1.0 ========
graph_db_container | 2022-10-26 20:12:27.199+0000 ERROR Failed to start Neo4j on localhost:7474.
graph_db_container | java.lang.RuntimeException: Error starting Neo4j database server at /data/databases
graph_db_container |    at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:255) ~[neo4j-5.1.0.jar:5.1.0]
graph_db_container |    at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:193) ~[neo4j-5.1.0.jar:5.1.0]
graph_db_container |    at org.neo4j.server.CommunityBootstrapper.createNeo(CommunityBootstrapper.java:36) ~[neo4j-5.1.0.jar:5.1.0]
graph_db_container |    at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:164) ~[neo4j-5.1.0.jar:5.1.0]
graph_db_container |    at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:85) ~[neo4j-5.1.0.jar:5.1.0]
graph_db_container |    at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:30) ~[neo4j-5.1.0.jar:5.1.0]
graph_db_container | Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.extension.GlobalExtensions@d1a10ac' failed to initialize. Please see the attached cause exception "'org.neo4j.logging.Log org.neo4j.logging.internal.LogService.getUserLog(java.lang.Class)'".
graph_db_container |    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:340) ~[neo4j-common-5.1.0.jar:5.1.0]
graph_db_container |    at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:57) ~[neo4j-common-5.1.0.jar:5.1.0]
graph_db_container |    at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:86) ~[neo4j-common-5.1.0.jar:5.1.0]
graph_db_container |    at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:246) ~[neo4j-5.1.0.jar:5.1.0]
graph_db_container |    ... 5 more
graph_db_container | Caused by: org.neo4j.kernel.extension.FailedToBuildExtensionException: Failed to build kernel extension Extension:RegisterComponentFactory[ApocRegisterComponent] because it is compiled with a reference to a class, method, or field, that is not in the class path: ''org.neo4j.logging.Log org.neo4j.logging.internal.LogService.getUserLog(java.lang.Class)''. The most common cause of this problem, is that Neo4j has been upgraded without also upgrading allinstalled extensions, such as APOC. Make sure that all of your extensions are build against your specific version of Neo4j.
graph_db_container |    at org.neo4j.kernel.extension.ExtensionFailureStrategies.wrap(ExtensionFailureStrategies.java:56) ~[neo4j-kernel-5.1.0.jar:5.1.0]
graph_db_container |    at org.neo4j.kernel.extension.ExtensionFailureStrategies$1.handle(ExtensionFailureStrategies.java:68) ~[neo4j-kernel-5.1.0.jar:5.1.0]
graph_db_container |    at org.neo4j.kernel.extension.AbstractExtensions.init(AbstractExtensions.java:69) ~[neo4j-kernel-5.1.0.jar:5.1.0]
graph_db_container |    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:323) ~[neo4j-common-5.1.0.jar:5.1.0]
graph_db_container |    at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:57) ~[neo4j-common-5.1.0.jar:5.1.0]
graph_db_container |    at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:86) ~[neo4j-common-5.1.0.jar:5.1.0]
graph_db_container |    at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:246) ~[neo4j-5.1.0.jar:5.1.0]
graph_db_container |    ... 5 more
graph_db_container | Caused by: java.lang.NoSuchMethodError: 'org.neo4j.logging.Log org.neo4j.logging.internal.LogService.getUserLog(java.lang.Class)'
graph_db_container |    at apoc.RegisterComponentFactory.newInstance(RegisterComponentFactory.java:33) ~[apoc.jar:4.4.0.1]
graph_db_container |    at apoc.RegisterComponentFactory.newInstance(RegisterComponentFactory.java:20) ~[apoc.jar:4.4.0.1]
graph_db_container |    at org.neo4j.kernel.extension.AbstractExtensions.newInstance(AbstractExtensions.java:125) ~[neo4j-kernel-5.1.0.jar:5.1.0]
graph_db_container |    at org.neo4j.kernel.extension.AbstractExtensions.init(AbstractExtensions.java:63) ~[neo4j-kernel-5.1.0.jar:5.1.0]
graph_db_container |    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:323) ~[neo4j-common-5.1.0.jar:5.1.0]
graph_db_container |    at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:57) ~[neo4j-common-5.1.0.jar:5.1.0]
graph_db_container |    at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:86) ~[neo4j-common-5.1.0.jar:5.1.0]
graph_db_container |    at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:246) ~[neo4j-5.1.0.jar:5.1.0]
graph_db_container |    ... 5 more
graph_db_container | 2022-10-26 20:12:27.202+0000 INFO  Neo4j Server shutdown initiated by request
graph_db_container | 2022-10-26 20:12:27.203+0000 INFO  Stopped.

**Comment by jennyowen** [comment]
The error message:
```
Failed to read config /var/lib/neo4j/conf/neo4j.conf: Error evaluating value for setting 'server.http.advertised_address'. Failed to validate '0.0.0.0:7474' for 'server.http.advertised_address': advertised address cannot be '0.0.0.0'
```
Does that happen on starting the container or at some other point? Like when trying to connect with a browser?

The error message from when using `localhost` seems to be complaining about apoc version incompatibility. That might be because `latest` was  4.4.12 but is now 5.1, which will not work with the 4.4 apoc plugin you're mounting. You should try again with the latest apoc version OR set environment variable `NEO4J_PLUGINS='["apoc"]'` to have the container automatically download a compatible apoc for you.

**Comment by leveraction** [comment]
It happens at start up.  

"which will not work with the 4.4 apoc plugin you're mounting."    Which line is the apoc plugin?  One of these?

 - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
 - NEO4J_dbms_security_procedures_whitelist=gds.*, apoc.*
If this is wrong, what should it be?

**Comment by jennyowen** [comment]
It's the apoc plugin you have in the `./plugins` folder you're mounting to `/plugins`.

**Comment by leveraction** [comment]
Ok, just as a test I commented out the plugins (which I don't think are even being used) and tried to start the container.  Without plugins, the 4.4.12-community starts, latest still does not start.

**Comment by gjmwoods** [comment]
Hi @leveraction, just to clarify the advertised address part of this issue, that address is used in the discovery mechanisms to advertise how they can connect to the server. Since `0.0.0.0` is not a valid (ie connectable) address from a client perspective it has removed as a possibility in configuration.

I don't think there are any outstanding issue on this ticket so I will close it for now but please feel free to reopen if you have further questions
