### ISSUE TITLE
[Optimization] Multiple match statements fail to select the optimal index

### ISSUE THREAD

**Issue by czpmango** [neo4j/neo4j#12959]
- Neo4j version: 4.2.1
- Operating system: Ubuntu 16.04
- API/Driver: Cypher
- **Steps to reproduce**
   1. Load a dataset into db 
   2. Create index: create index on: player(name)
![image](https://user-images.githubusercontent.com/26356194/197669129-d1b7b9c6-0c14-46d1-9776-6373b5d803f5.png)
   3. Profile this statement: optional match (v)--() match(v:player{name:"Tim Duncan"})-[:like]-(m)  return *
![image](https://user-images.githubusercontent.com/26356194/197667450-8de008a5-31bd-44bd-a17c-9fb839060cd6.png)

- Expected behavior
   AllNodeScan is expected to be avoided to improve performance. Just like this:
![image](https://user-images.githubusercontent.com/26356194/197668088-978373e2-6e29-4132-a8f1-6462279596a2.png)
  Or similar case:
![image](https://user-images.githubusercontent.com/26356194/197668284-7016534e-dfd4-49c1-9aca-1356944d1617.png)

- Actual behavior
   Execution plan generated AllNodeScan nodes resulting in more memory and computational overhead.

**Comment by HannesSandberg** [comment]
Thanks for your report! We will investigate and come back to you here.

**Comment by arnefischereit** [comment]
Hi @czpmango,

For the first query, you are right that this could internally be rewritten to `MATCH (v:player{name:"Tim Duncan"})-[:like]-(m)`, as the `OPTIONAL MATCH` is subsumed in the following `MATCH`.

For the third query, however, the semantics are a bit different: If we do not find `(v:player{name:"Tim Duncan"})-[:like]-(m)`, then we will still return the results for `(v)--()` and return `null` for `x`.

When would you write the first query, which could also be expressed by just the second term? I am a bit sceptical of how much use would be there for such an optimisation.

**Comment by czpmango** [comment]
> For the first query, you are right that this could internally be rewritten to `MATCH (v:player{name:"Tim Duncan"})-[:like]-(m)`, as the `OPTIONAL MATCH` is subsumed in the following `MATCH`.

@arnefischereit Thanks a lot for reply!
My query is almost like this:`profile  match (n)-[*1..8]-(t:team) where not (t)-[:like]->() optional match (v)-[*2]-(q)--() match(v:player{name:"Tim Duncan"})-[]-(n)--(x) return distinct x`
The computation of pattern `(n)-[*1..8]-(t:team)` results in a lot of data overhead.
So, I was expecting to be able to select the index on player(name) without changing the semantics. I try this query: `profile  match (v:player{name:"Tim Duncan"})--(n)-[*1..8]-(t:team) where not (t)-[:like]->() optional match (v)-[*2]-(q)--() match (v:player{name:"Tim Duncan"})-[]-(n)--(x) return distinct x` but got worse execution performance. Is my rewritten statement preserving the equivalent query semantics? Am I missing something?

**Comment by arnefischereit** [comment]
As you have guessed, the queries have different semantics:
It very much depends on whether `v` is defined before the `OPTIONAL MATCH` or not. In the first query, we will not see any results if there is no `v`which fulfills `(v)-[*2]-(q)--()`, whereas the second query in those cases only sets `q` to `NULL`.

I know that `OPTIONAL MATCH` is a tricky beast. The most important thing to keep in mind is that the order of `MATCH`-statements matters: Later match clauses refer to previous ones, so that an `OPTIONAL MATCH` with no references to a previously bound variable is very much a `MATCH`. I hope that clarifies things. :crossed_fingers:

**Comment by czpmango** [comment]
@arnefischereit I get it. Thanks for your detailed answer!
