### ISSUE TITLE
Stucked neo4j-admin import, related to duplicated node and IdMapper SortWorker

### ISSUE THREAD

**Issue by abstract-liu** [neo4j/neo4j#12964]
- Neo4j version: 4.4.12-enterprise
- Operating system: ubuntu 22.04 Docker Mode

- **Steps to reproduce**
bin/neo4j-admin import --skip-duplicate-nodes --database=test  --nodes=a=import/20779588711874560/a_node_header.csv,import/20779588711874560/[0-9]*_a_node.csv --relationships=transfer=import/20779588711874560/transfer_relationship_header.csv,import/20779588711874560/[0-9]*_transfer_relationship.csv

[jstack.txt](https://github.com/neo4j/neo4j/files/9876896/jstack.txt)

[console.txt](https://github.com/neo4j/neo4j/files/9876914/console.txt)

I figure out that the neo4j server is doing unstopped sort job in idmapper prepare step.
Some idea about too many nodes? There are about 2 billion lines of node in my import csv, contains duplicated nodes.
Should I manual remove duplicated nodes to speed up import.

**Comment by abstract-liu** [comment]
finally, I manual merge duplicated nodes to acceptable level, and it go through node import very fast.
But I still wonder why it stucked at Sort Stage, to be specific, qsort-paritial step.
In my knowledge, it's nlogn time complex, even though billion level nodes, there should not have stuck so long

**Comment by tinwelint** [comment]
Hi, no it should definitely not get stuck. How many duplicates where there?

**Comment by abstract-liu** [comment]
about 2 billion duplicates and 200 million unique 
sorry for the mistake I make so many duplicates

**Comment by tinwelint** [comment]
I'm guess there's a worst-case in sorting that Id mapping when there are lots of values that are the same. It's something that may need to be looked at

**Comment by tinwelint** [comment]
@abstract-liu What I've found when testing this a bit more is that it's almost certainly the logging of all those duplicate entries that takes up the majority of the time. I'm not sure what to do here other than potentially introduce a cap of how many entries are logged to the "bad" log, skipping the rest.

Since you've moved on and this was a solvable problem for you, is it OK to close this issue? I may create a task for discussing this improvement internally in the product.

**Comment by abstract-liu** [comment]
@tinwelint Thanks a lot for your help. I will close this issue, and hope to see the improvement in the future. 
By the way, since I am enthusiastic to get envolved in neo4j develepment and found some bugs during using it, I wonder what's the best way to get in touch or contribute?
Finally, thank you again.

**Comment by tinwelint** [comment]
Great to hear! Generally it's just about signing the CLA (see https://neo4j.com/developer/cla/) and opening pull requests for https://github.com/neo4j/neo4j
