### ISSUE TITLE
round(x.5, 0, 'HALF_DOWN') - wrong result for negative values

### ISSUE THREAD

**Issue by LiorKogan** [neo4j/neo4j#12963]
Neo4j Browser version: 4.4.6
Build date: 8/5/2022
Neo4j Server version: 4.4.12 (enterprise)

```
RETURN round(-1.5, 0, 'HALF_DOWN')
-1.0
```

Expected result: 
```
-2.0
```

> HALF_DOWN | Round towards closest value of given precision, with half-values always being rounded down.

**Comment by LiorKogan** [comment]
Reference implementation for HalfDown, HalfEven, and AwayFromZero rounding.

```
// round towards closest integer, with half-values always being rounded down
double RoundHalfDown(double f)
{
    double int_part;
    double frac_part = modf(f, &int_part);
    
    if (frac_part <= -0.5) return int_part - 1.0;
    if (frac_part <=  0.5) return int_part      ;
                           return int_part + 1.0;
}

// round towards closest integer, with half-values always being rounded to the even neighbor
double RoundHalfEven(double f)
{
    double int_part;
    double frac_part = modf(f, &int_part);
    
    if ((frac_part == -0.5) || (frac_part == 0.5))
        return round (f * 0.5) * 2.0;
    
    if (frac_part < -0.5) return int_part - 1.0;
    if (frac_part <  0.5) return int_part      ;
                          return int_part + 1.0;
}

// round away from zero
double RoundAwayFromZero(double f)
{
    double int_part;
    double frac_part = modf(f, &int_part);
    
    if (frac_part < 0) return int_part - 1.0;
    if (frac_part > 0) return int_part + 1.0;
                       return int_part      ;
}
```

**Comment by mnd999** [comment]
That does look potentially incorrect. If there is a bug it is likely [here](https://github.com/neo4j/neo4j/blob/c3316350a9345cdd7bb36dcaec271573a9704887/community/cypher/runtime-util/src/main/java/org/neo4j/cypher/operations/CypherFunctions.java#L252)

**Comment by mnd999** [comment]
On further investigation this may be a documentation issue. I've passed it to the right team who will take a look at it.

**Comment by LiorKogan** [comment]
_half-down rounding_ is a standard term, so I don't think it could be just a documentation issue.

On the other hand, other rounding type names are also used in a non-standard, misleading way:
- `DOWN` - Round towards zero.
- `UP` - Round away from zero.
- `FLOOR` - Round towards zero. 

These descriptions are correct only for nonnegative values.

**Comment by Lojjs** [comment]
@LiorKogan We follow the rounding modes from Java, described [here](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/math/RoundingMode.html). But I can notice that our documentation is wrong in the case of `FLOOR`, it should say `Round towards negative infinity` and it is not very clear in the other cases either, so I will try to improve it. However, that `RETURN round(-1.5, 0, 'HALF_DOWN') = -1.0` is consistent with Java (see the examples of -2.5 and -5.5 in the link above)

**Comment by LiorKogan** [comment]
Thank you @Lojjs 
It is interesting to see that Java does not follow the more-or-less standard mathematical terminology.

**Comment by Lojjs** [comment]
@LiorKogan The documentation [here](https://neo4j.com/docs/cypher-manual/current/functions/mathematical-numeric/#functions-round3) has now been improved to better explain the current behaviour.
