### ISSUE TITLE
Corrupt data when using continous checkpointing

### ISSUE THREAD

**Issue by 59977** [neo4j/neo4j#12976]
We load data into Neo4j using the .NET driver in batches using something like this:

```
async void LoadBatch(IAsyncTransaction tx, string label, List<object> rows) 
{
	var cypher = "UNWIND $rows AS row CREATE (e:%LABEL%) SET e = row".Replace("%LABEL%", label);
	var parameters = new Dictionary<string, object>()
		{
			{ "rows", rows }
		};
	var result = await tx.RunAsync(cypher, parameters);	
	await result.ConsumeAsync();
}
```

The size of each batch is configurable. Total number of nodes is around two million and about 20 different labels. Different number of total nodes for each label.

This works well for us mostly but recently we tried this with dbms.checkpoint set to CONTINOUS and a batch-size of 1000. 

Expected result:
Nodes should be imported correctly.

Actual result:
A small proportion of nodes had corrupted fields, i.e. some string fields were either blank or had some characters replaced by spaces. No errors were logged. 

Changing either dbms.checkpoint to PERIODIC or batch-size to 10000 fixes the problem.

NOTE: The database has rather low memory settings: 1500Mi for heap and 1500Mi for page cache.

Neo4j version: 4.4.11
Driver version: 4.1.0

Neo4j running in docker container (docker desktop wsl2 backend on Windows 10)

**Comment by 2hdddg** [comment]
Hi @59977 would it be possible for you to provide a debug log from a run where you encountered this problem and the report from a consistency check of the database?
You might also try it out with a more recent version of the driver. Drivers follow the same versioning scheme as the database, so optimally use the 4.4 version of the driver (this is most probably not the cause of your problems).

**Comment by Roxling** [comment]
Closed due to inactivity
