### ISSUE TITLE
Fulltext 'cypher' index analyser does not work

### ISSUE THREAD

**Issue by nacnudus** [neo4j/neo4j#12979]
A fulltext index using the analyser that is called 'cypher' does not return any results.

I looked for a similar issue, but couldn't find any, perhaps because the name of the analyser is the same as the name of the query language.

- Neo4j version: 4.4.8 community
- Operating system: docker image neo4j:4.4.8-community
- API/Driver: Cypher

## Steps to reproduce

1. Create a node with `text` property 'hello, world'.
2. Create a 'standard' index
3. Query the 'standard' index -- it returns the node, as expected.
4. Delete the 'standard' index
5. Create a 'cypher' index
6. Query the 'cypher' index -- it ought to return the node, but does not.
7. Delete the 'cypher' index
8. Delete the node

```
@neo4j> CREATE (n:Test {text: 'hello, world'});
        
0 rows
ready to start consuming query after 32 ms, results consumed after another 0 ms
Added 1 nodes, Set 1 properties, Added 1 labels
@neo4j> CREATE FULLTEXT INDEX test_standard FOR (n:Test) ON EACH [n.text]
        OPTIONS {indexConfig: {`fulltext.analyzer`: 'standard'}};
        
0 rows
ready to start consuming query after 9 ms, results consumed after another 0 ms
Added 1 indexes
@neo4j> CALL db.index.fulltext.queryNodes("test_standard", 'world')
        YIELD node, score
        RETURN node;
        
+--------------------------------+
| node                           |
+--------------------------------+
| (:Test {text: "hello, world"}) |
+--------------------------------+

1 row
ready to start consuming query after 17 ms, results consumed after another 2 ms
@neo4j> DROP INDEX test_standard;
        
0 rows
ready to start consuming query after 5 ms, results consumed after another 0 ms
Removed 1 indexes
@neo4j> CREATE FULLTEXT INDEX test_cypher FOR (n:Test) ON EACH [n.text]
        OPTIONS {indexConfig: {`fulltext.analyzer`: 'cypher'}};
        
0 rows
ready to start consuming query after 7 ms, results consumed after another 0 ms
Added 1 indexes
@neo4j> CALL db.index.fulltext.queryNodes("test_cypher", 'world')
        YIELD node, score
        RETURN node;
        
+------+
| node |
+------+
+------+

0 rows
ready to start consuming query after 16 ms, results consumed after another 1 ms
@neo4j> DROP INDEX test_cypher;
        
0 rows
ready to start consuming query after 3 ms, results consumed after another 0 ms
Removed 1 indexes

@neo4j> MATCH (n:Test) DETACH DELETE n;
0 rows
ready to start consuming query after 17 ms, results consumed after another 0 ms
Deleted 1 nodes
```

**Comment by HannesSandberg** [comment]
Hi, thanks for your report. We will investigate this

**Comment by arnefischereit** [comment]
Hi @nacnudus,

It seems to me that there is no such `fulltext.analyser` as `cypher`: https://github.com/neo4j/neo4j/tree/5.1/community/fulltext-index/src/main/java/org/neo4j/kernel/api/impl/fulltext/analyzer/providers

Could you detail, why you think such an analyzer should exist?

**Comment by nacnudus** [comment]
Never mind, it was [removed](https://github.com/neo4j/neo4j/commit/dceaf877dc66591f383ada5bb14463f7c54c189b).  We would have relied on it.  Is there any lifecycle governance that would help us to decide whether to rely on any particular functionality of Neo4j?

**Comment by PetrJanouch** [comment]
This particular analyser was used by an internal feature that was scrapped. We did not think through that it showed up in the listing of available analysers and someone might have started using it. Sorry for that. The analyser worked the same way as 'keyword' analyser so you can use that one instead.
We are generally careful about the backwards compatibility. This particular analyser was an incomplete internal feature that accidentally leaked into the public API. Sorry for that again.

**Comment by nacnudus** [comment]
Thank you for the explanation.
