### ISSUE TITLE
Directed Relationship Index Seek Does Not Work

### ISSUE THREAD

**Issue by aokimio** [neo4j/neo4j#12982]
## Directed Relationship Index Seek Does Not Work

I discovered that Directed Relationship Index Seek does not work in `optional match` circumstances properly.

**Neo4j Version:** 4.4.4
**Operating System:** Ubuntu 20.04 / Docker
**API:** Cypher

### Steps to reproduce
1. Add test data
```cypher
MERGE (ip:IP{val: '192.168.1.1'}) - [open:Open] -> (port:Port{val: '22'}) - [bind:Bind{ip: ip.val}] -> (service:Service{val: 'ssh'});
CREATE INDEX index_bind_ip IF NOT EXISTS FOR () - [bind:Bind] - () ON (bind.ip);
CREATE CONSTRAINT unique_index_ip_val IF NOT EXISTS FOR (n:ip) REQUIRE n.val IS UNIQUE;
CREATE CONSTRAINT unique_index_port_val IF NOT EXISTS FOR (n:port) REQUIRE n.val IS UNIQUE;
CREATE CONSTRAINT unique_index_service_val IF NOT EXISTS FOR (n:service) REQUIRE n.val IS UNIQUE;
```
2. Run a cypher query
```cypher
MATCH (ip:IP) - [open:Open] -> (port:Port)
OPTIONAL MATCH (port) - [bind:Bind] -> (service:Service) where bind.ip = ip.val
RETURN count(1)
```
3. Above cypher script executes very slow when the dataset is huge, but it should be executed more efficient because i add indexes on the all nodes and relationships in the first step, after profiling above cypher script via `profile ...`, i discovered that the index of `Bind` relationship on the property `ip` named `index_bind_ip` does not work, following svg image is the corresponding execution plan. 

![execution plan](https://user-images.githubusercontent.com/61457934/203360385-a70fe541-9904-48ea-ac8b-51d5d4cd92d4.svg)

via `using index ...` force neo4j to use relationship index:
```cypher
PROFILE MATCH (ip:IP) - [open:Open] -> (port:Port)
OPTIONAL MATCH (port) - [bind:Bind] -> (service:Service) using index bind:Bind(ip) where bind.ip = ip.val
RETURN count(1)
```
it complains following errors:
```cypher
Failed to fulfil the hints of the query.
Could not solve these hints: `USING INDEX bind:Bind(ip)`
```
Then I replaced `ip.val` with `""`, execution plan is divided into two parts:
```cypher
PROFILE MATCH (ip:IP) - [open:Open] -> (port:Port)
OPTIONAL MATCH (port) - [bind:Bind] -> (service:Service) using index bind:Bind(ip) where bind.ip = ""
RETURN count(1)
```
![plan - 2022-11-24T161441 906](https://user-images.githubusercontent.com/61457934/203728787-24ae0922-a56e-4082-b386-e1aef61bdb79.svg)

left branch cannot find `ip.val` in right branch, so it complains.

4. I had searched relational documentation about `query tuning` at [https://neo4j.com/docs/cypher-manual/current/query-tuning/using/](https://neo4j.com/docs/cypher-manual/current/query-tuning/using/),  i know that neo4j would set `starting point` for each `using index ...`, then multiple branches were executed parallelly, but `bind.ip` should refer to `ip.val` while `ip` is in another branch after `using index ...`, so original logic is broken, i want to know if there is any solution(or workaround) to solve above conflicts.

### Expected behavior
 `Directed Relationship Index Seek` should work.

### Actual behavior
 `Directed Relationship Index Seek` does not work.

**Comment by InverseFalcon** [comment]
You can force this, but you will need to remove any uses of pre-matched node variables in your OPTIONAL MATCH pattern (in this case, `port`) so that the planner cannot choose to expand from any previous matched nodes. We can use an equality filter to make sure the new variable (`port2`) is pointing to the same node.

```
PROFILE 
MATCH (ip:IP) - [open:Open] -> (port:Port {val:'22'})
OPTIONAL MATCH (port2) - [bind:Bind] -> (service:Service) 
USING INDEX bind:Bind(ip) 
WHERE bind.ip = ip.val AND port2 = port
RETURN count(*)
```

That gives you a workaround, though I also feel the planner should be able to handle this from the hint alone without the extra hoops to jump through.

**Comment by HannesSandberg** [comment]
Thanks for the report! We will look into this

**Comment by hedengran** [comment]
Hi, thanks again for the report. 

The behaviour that you're seeing is that, in 4.4, the planner is incapable of planning a `relationship index seek` when one of the end nodes is already bound. As @InverseFalcon suggested, the workaround is to not reuse an already bound variable, but rather introduce a new one and plan a filter on top.

This has been addressed in 5.x, and the `OPTIONAL MATCH` in the example above is indeed solved with a relationship index.
