### ISSUE TITLE
Docs say dash character is allowed in DB name, CYPHER shell and Console Disallow this

### ISSUE THREAD

**Issue by jasperblues** [neo4j/neo4j#12987]
## Guidelines

- Neo4j version: 5.2.0
- Operating system: MacOS
- API/Driver: Javascript (only relevant for workaround) 

## Steps to reproduce

Create a database via the Neo4j console or Cypher shell where the name has a dash character, example: 

```
create database tenant-896abc74-06d4-42f0-a5d2-b36a1b1bd9f9
```

## Expected behavior

Database is successfully created 

## Actual behavior
Error: 

```text
nvalid input '-': expected
  "."
  "IF"
  "NOWAIT"
  "OPTIONS"
  "TOPOLOGY"
  "WAIT"
  <EOF> (line 1, column 23 (offset: 22))
"create database tenant-896abc74-06d4-42f0-a5d2-b36a1b1bd9f9"
```

## Workaround

Issue the update via the JS driver, passing the DB name as a parameter. 
Additionally, include (as appropriate) log-files, stacktraces, and other debug output.

## Example bug report

Docs and parser say to use letters and simple characters including a dash. In practice the dash causes problems. 

In a multi-tenanted application it is common to have a master database, and n child databases for each tenant, where the tenant database is assigned an id. It is common to use uuid as the ID scheme, and uuid (typically) has dashes.

**Comment by HannesSandberg** [comment]
Hello! Thank you for your report. You can create database names with `-` by escaping the name, example: 
```
create database `tenant-896abc74-06d4-42f0-a5d2-b36a1b1bd9f9`
```
