### ISSUE TITLE
Quick question:Guide for utilizing/build upon neo4j

### ISSUE THREAD

**Issue by buyvtuygJW** [neo4j/neo4j#12999]
Base on issue https://github.com/neo4j/neo4j/issues/12933 and issue https://github.com/neo4j/neo4j/issues/12934

I decided that for testing
i could use neo4j desktop for test and whatnot,provided that I know use the GUI to do CRUD,import and export the database.

for production
I need to somehow setup a local server from scratch*(due to my personal ideal requirement of minimal memory usage=no gui)
I also have determined that I need to create my own homeroll cli app to query using cypher lang.

Say If I want the server to have all basic CRUD functionality.
What is the jar dependency that I need to have for my homeroll*cli app?

**Comment by mnd999** [comment]
We do include the cli tool [cypher-shell](https://neo4j.com/docs/operations-manual/current/tools/cypher-shell/) with the product which may well do what you want. If not you would likely want the [Java driver](https://neo4j.com/developer/java/) for your client. 

As an aside, the overhead for the neo4j-browser GUI is mostly on the client - it is essentially a single page application that connects to the server using the Javascript driver. It is not necessary to host it on the Neo4j server, although it is often convenient to do so.

**Comment by buyvtuygJW** [comment]
i dont see where i can install cypher-shell?

I installed the neo4j desktop.

BTW,does cypher support autosuggest for the cypher language built in keywords?

**Comment by buyvtuygJW** [comment]
or do you know of any *cli clients? else i need to find the list of keywords and create my own cli wrapper with the auto-suggestion.

The reason is sometime i may need to do a quick query from another process* to the database while the daily query is running.
and for the quick query it would be useful to have some quick suggestion or a good cli with a decent feedback if my query is wrong whatever.

**Comment by mnd999** [comment]
Cypher-shell can also be downloaded [here](https://neo4j.com/download-center/#cypher-shell). I'm pretty sure recent versions do have some autocomplete, yes.

**Comment by buyvtuygJW** [comment]
nice i get it all downloaded and i am now trying to do query with the example movie graphdb and a new test* project I created.

Can i confirm that the graph db is located in something like>\Neo4j_appdt\relate-data\dbmss\dbms-46af51ac-e8b4-489b-81af-5eaadb620191

i tried finding info about it eg,https://neo4j.com/docs/resources/pdf-library/
but doesnt seems has it written there.

i assume something like this would work?
>cypher-shell -d ...\Neo4j_appdt\relate-data\dbmss\dbms-46af51ac-e8b4-489b-81af-5eaadb620191 -p ABCpass --encryption true

**Comment by mnd999** [comment]
Cypher shell is simply a client, it connects to a server as you describe above, not a database file directly. You can find the documentation [here](https://neo4j.com/docs/operations-manual/current/tools/cypher-shell/). If you want an all in one CLI tool / query engine. I do not think that is something we currently offer. Cypher shell is fully open source though, the code is in this repo so if you are going to build that may be a good starting point.

You might be better to reach out on  in [our community forums](https://community.neo4j.com/) or on our [discord](https://discord.gg/neo4j) and you will likely get a faster response there, and there may be others who have a similar requirement. Github is more setup for bug reports in the product.

**Comment by buyvtuygJW** [comment]
so what should i do to make the cypher shell works?minimally?
Since you say the shell is a client i assume it needs a server. and I assume when I run the neo4j desktop it includes the server and opens a port that accepts request?
So how can I sent request to that server?

Also how can I export a specific graph.To other os platform or whatnot.
The desktop app starts slow so ideally I want it to be kinda (embedded/headless).

The reason is very simple,say I created a database for keeping infos about my fridge storage.
Then I go out and buy stuff,when queuing at the cashier there,I noticed that I didnt start my server.Say theoretically If i know vpn and ssh well.I could start it up the server* easily,If its headless.(But neo4j desktop is not,as far as I can tell, it at least needs a mouse to click and start the db)

However the bigger problem is with the huge startup time.Its very likely that when its my turn to pay I still cannot confirm (did I bought everything I need/ did I buy too much).

Thus, lead me to originally attempt to build neo4j on my own and debloat* something to optimize speed& making sure I can export the database or graph to run it in other settings or whatever.
Because a programmer standing there for 1 minute in front of a supermarket food rack,just looks funny.

**Comment by mnd999** [comment]
Yes, Neo4j is (optionally) client / server, but the is the most common type of deployment. The server, packaged for various operating systems is available in the [download centre](https://neo4j.com/download-center). Desktop is running a server in the background and connecting to it via clients (afaik - that's not really my area). 

Have you considered running the server in the cloud? If it's a small project, perhaps the [Aura](https://neo4j.com/cloud/platform/aura-graph-database/) free tier would meet your need. Otherwise yeah, it can be left running as a server process, or if you want to embed it in a Java application we have [documentation](https://neo4j.com/docs/java-reference/current/java-embedded/) for that also.

**Comment by mnd999** [comment]
I haven't heard anything back on this for a while, so will close for now. Please feel free to reopen if it's still an issue.

**Comment by buyvtuygJW** [comment]
thanks I will maybe try embed it and see if I can make it work.
Hmm running the server in cloud seems like an option for testing.However,I dont have a constant supply of internet in my desktop or laptop.

will probably take some time,due to my recent busy schedule.

**Comment by buyvtuygJW** [comment]
PS tried to embed this but gets this compile error.

[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /E:/Prog/Actdev/Test/testdb/testembed/5thtrywmvn/src/main/java/A.java:[23,35] cannot find symbol
  symbol:   method executeWrite((tx)->{ or[...](); })
  location: variable session of type org.neo4j.driver.Session
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.788 s
[INFO] Finished at: ....
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project neo4j-movies: Compilation failure
[ERROR] /E:/Prog/Actdev/Test/testdb/testembed/5thtrywmvn/src/main/java/A.java:[23,35] cannot find symbol
[ERROR]   symbol:   method executeWrite((tx)->{ or[...](); })
[ERROR]   location: variable session of type org.neo4j.driver.Session
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by buyvtuygJW** [comment]
is the some api changes.

I think i uses some example online.

is there difference between
https://neo4j.com/docs/java-reference/current/java-embedded/setup/
managementService = new DatabaseManagementServiceBuilder( databaseDirectory ).build();

vs

 driver = GraphDatabase.driver(uri, AuthTokens.basic(user, password));
??
is it not the same thing?
