### ISSUE TITLE
Inconsistent results

### ISSUE THREAD

**Issue by YuanchengJiang** [neo4j/neo4j#12991]
Neo4j version: 5.1.0
Operating system: Ubuntu 20.04
API/Driver: Cypher
Dataset: Recommendations, https://github.com/neo4j-graph-examples/recommendations

Query1: `OPTIONAL MATCH (s1)-[s0:DIRECTED]-()<-[s2:ACTED_IN]-(s1) RETURN count(s1);`
Query2: `OPTIONAL MATCH (s1)-[s0]-()<-[s2:ACTED_IN]-(s1) WHERE s0:DIRECTED RETURN count(s1);`

I would expect them to return the same result. I am not sure which one is correct.

```
neo4j@neo4j> OPTIONAL MATCH (s1)-[s0:DIRECTED]-()<-[s2:ACTED_IN]-(s1) RETURN count(s1);
+-----------+
| count(s1) |
+-----------+
| 43        |
+-----------+

1 row
ready to start consuming query after 1 ms, results consumed after another 36 ms
```

```
neo4j@neo4j> OPTIONAL MATCH (s1)-[s0]-()<-[s2:ACTED_IN]-(s1) WHERE s0:DIRECTED RETURN count(s1);
+-----------+
| count(s1) |
+-----------+
| 491       |
+-----------+

1 row
ready to start consuming query after 1 ms, results consumed after another 86 ms
```

For Query 1, adding node labels returns more node counts(unexpected to me).

```
neo4j@neo4j> OPTIONAL MATCH (s1:Person)-[s0:DIRECTED]-()<-[s2:ACTED_IN]-(s1:Person) RETURN count(s1);
+-----------+
| count(s1) |
+-----------+
| 491       |
+-----------+

1 row
ready to start consuming query after 19 ms, results consumed after another 28 ms
```

**Comment by HannesSandberg** [comment]
Thanks! We will investigate this.

**Comment by inmost-light** [comment]
@YuanchengJiang
Thank you for reporting. This bug has been fixed in 5.2.0, both queries return 491.
As a workaround on 5.1.0 you can add direction to `s0`, i.e. `(s1)-[s0:DIRECTED]->()`.

**Comment by FozAhm** [comment]
@inmost-light can you please point me to which commit fixed this issue?
I know that version 5.1.0 final commit was 3aa6dbe
And version 5.2.0 final commit was bd5dc00
Thank you!

**Comment by inmost-light** [comment]
@FozAhm https://github.com/neo4j/neo4j/commit/38e6ac1d59a0f1e5fc028ede048bcfe25193a0d6
