### ISSUE TITLE
Unexpected Result

### ISSUE THREAD

**Issue by YuanchengJiang** [neo4j/neo4j#12996]
Neo4j version: 4.4, 5.2
Operating system: Ubuntu 20.04
API/Driver: Cypher
Dataset: Recommendations, https://github.com/neo4j-graph-examples/recommendations

Accidentally ran into this case, `SKIP 1` does not make sense here but the output should be None.

```
neo4j@neo4j> MATCH (a)-[b:RATED]-(c) RETURN count(a) SKIP 1;
+----------+
| count(a) |
+----------+
+----------+

0 rows
ready to start consuming query after 6 ms, results consumed after another 50 ms
neo4j@neo4j> MATCH (a)-[b:RATED]->(c) RETURN count(a) SKIP 1;
+----------+
| count(a) |
+----------+
+----------+

0 rows
ready to start consuming query after 0 ms, results consumed after another 38 ms
neo4j@neo4j> MATCH (a)-[b:RATED]->(c) RETURN count(b) SKIP 1;
+----------+
| count(b) |
+----------+
| 100004   |    <-- None is expected here
+----------+

1 row
ready to start consuming query after 6 ms, results consumed after another 1 ms
```

**Comment by HannesSandberg** [comment]
Thank you, we will investigate this!

**Comment by hedengran** [comment]
Hi, thanks again for the report. I agree that output should be empty. I have an open PR for fixing this and will close the issue once the fix has been merged.
