### ISSUE TITLE
Neo4j 5.X documentation: Usage of neo4j 4.X style configuration property for unmanaged extension classes

### ISSUE THREAD

**Issue by mmopitz** [neo4j/neo4j#13007]
- Neo4j version: 5.X
- Documentation

Hi there,
I found a small mistake in neo4j's documentation. 
I'm not sure if this is the right platform to report that ... but I didn't find anything else...

The documentation states to use the configuration: `dbms.unmanaged_extension_classes` 
In neo4j 5.0 it was renamed to `server.unmanaged_extension_classes`

Link to faulty documentation: https://neo4j.com/docs/java-reference/current/extending-neo4j/unmanaged-extensions/
Link to migration guide: https://neo4j.com/docs/upgrade-migration-guide/current/version-5/changelogs/configuration-settings/

Faulty Configuration:
![image](https://user-images.githubusercontent.com/45235611/207326845-3b216686-b927-4630-b142-2c0ea9852191.png)

Screenshot of migration guide:
![image](https://user-images.githubusercontent.com/45235611/207327028-8ee19a1d-e4d8-4156-a0b1-7e8003d87603.png)

Regards
Michael

**Comment by renetapopova** [comment]
Good spot @mmopitz! Thanks!
