### ISSUE TITLE
Unable to perform any operation on Neo4j AuraDB instance from my application

### ISSUE THREAD

**Issue by guilhermedjr** [neo4j/neo4j#13005]
When trying to perform an operation on my **Neo4j AuraDB** free instance from my .NET application, I get the following 403 error: **Request forbidden by administrative rules.**

The operations work from my app using a Neo4jDesktop connection. It seems like it's a security restriction from Neo4j AuraDB that rejects any external write operations. I am using the Neo4jClient package, and the connection to the Neo4j AuraDB works, only the requests does not.

Related issue: https://github.com/DotNet4Neo4j/Neo4jClient/issues/455#issuecomment-1345318683

**Comment by mnd999** [comment]
I would suggest you get in touch with Aura support [here](https://aura.support.neo4j.com/hc/en-us)
