### ISSUE TITLE
Incomplete docs on undirected relationship in MERGE clause

### ISSUE THREAD

**Issue by v-spassky** [neo4j/neo4j#13009]
Hello everyone! I am new to neo4j, and while reading the docs I stumbled upon these statements [here](https://neo4j.com/docs/cypher-manual/current/clauses/merge/#merge-merge-on-an-undirected-relationship):

> `MERGE` can also be used with an undirected relationship. When it needs to create a new one, it will pick a direction.

> The direction of the created relationship is arbitrary.

IMO, there is unnecessary ambiguity - why not specify the direction of the created relationship in this case? Moreover, in [this](https://youtu.be/9npLX5us1DU?t=160) course segment it is explicitly stated that the created relationship will be left to right:

> ... by default graph engine will create relation using left to right relation ...

I suggest mentioning this in the docs.

**Comment by stefano-ottolenghi** [comment]
Thanks for reporting! We'll see what we can do to clear up the confusion.

**Comment by stefano-ottolenghi** [comment]
We have now added some clarification to that section :) It will go live as soon as the manual is refreshed.
https://github.com/neo4j/docs-cypher/pull/584
