### ISSUE TITLE
neo4j client will dead block in bigData query

### ISSUE THREAD

**Issue by zhuyou1234** [neo4j/neo4j#13001]
neo4j server version 4.4.5
![image](https://user-images.githubusercontent.com/15230000/206393005-e83e5e92-e3b1-404d-b336-64c87ae69d81.png)

neo4j client version 4.4.5 
![image](https://user-images.githubusercontent.com/15230000/206393071-68e5a7e8-7051-4873-843e-78bb1b03b95b.png)

when I create a big node in neo4j server such as student  which have two properties,and every properties have long string big than 1m. such as create two node(student), and nameqqq and ttt each have more than 1m string 
![image](https://user-images.githubusercontent.com/15230000/206397078-f46a0182-0b3b-4a61-8d9d-7e3daca431fe.png)

![image](https://user-images.githubusercontent.com/15230000/206394289-3b27527c-a9e0-4eb0-b88d-d96e3b6a799f.png)

![image](https://user-images.githubusercontent.com/15230000/206394522-6a41f401-ba80-4d05-aa41-65ce7636eac3.png)
the code will hang in line  27 for long time after server kill connection

**Comment by gjmwoods** [comment]
Hello @zhuyou1234. Many thanks for raising this issue and many apologies for the delay in getting back to you.

I tried to recreate your issue but did not manage to hang my driver as you describe. Could you please enable bolt message logging with: `Config.builder().withLogging(Logging.console(Level.FINE)).build())`. From there we should be able to find the exact point where the driver becomes stuck.

**Comment by gjmwoods** [comment]
Hi @zhuyou1234, Since its been a few weeks I'll close this card for now but please feel free to reopen if you'd like help with it.
