### ISSUE TITLE
:grey_question:  Some Neo4J tags are missing (5.2, 4.4,...) :sweat_smile: 

### ISSUE THREAD

**Issue by adriens** [neo4j/neo4j#13012]
# :grey_question: Context

I'm currently working on pushing Neo4J on [`endoflife.date`](https://endoflife.date/) to make it easier for anyone to better manage techncal debt.

But during this process, we discovered that some tags are missing.

# :dart:   Please help fix missing tags

We currelty lack the following tags : 

- https://github.com/neo4j/neo4j/tags/5.2
- https://github.com/neo4j/neo4j/tags/4.4

While [they are referenced](https://neo4j.com/developer/kb/neo4j-supported-versions/) : 

![image](https://user-images.githubusercontent.com/5235127/208214023-e4d2a1cb-0404-4c1e-b1fb-ab817687f468.png)

# :bookmark: Related content

- https://neo4j.com/developer/kb/neo4j-supported-versions/
- https://github.com/endoflife-date/endoflife.date/pull/2008#discussion_r1045598316
- https://github.com/endoflife-date/endoflife.date/issues/2005
- https://github.com/endoflife-date/endoflife.date/pull/2077

**Comment by captn3m0** [comment]
Probable these:

- https://github.com/neo4j/neo4j/releases/tag/5.2.0
- https://github.com/neo4j/neo4j/releases/tag/4.4.0

**Comment by mnd999** [comment]
This seems to be resolved, so I'll close for now. If it's still a problem, feel free to reopen.

**Comment by adriens** [comment]
:pray:

**Comment by adriens** [comment]
@mnd999  : 

> This seems to be resolved, so I'll close for now. If it's still a problem, feel free to reopen.

Yup, I have pinged them with [🔁 Browse Neo4J EoL versions inside Neo4J AuraDB 🤓 ](https://dev.to/optnc/browse-neo4j-eol-versions-inside-neo4j-auradb-1ncb), hopefully it will have been useful :smile_cat:
