### ISSUE TITLE
Nodes created/uploaded date and time

### ISSUE THREAD

**Issue by meg261995** [neo4j/neo4j#13011]
Is there a way to determine when a node is created with any internal functions of neo4j?

**Comment by Mats-SX** [comment]
Hello @meg261995 and thanks for your question.

Do you mean when a node is created within the database itself? For example with a `CREATE` clause?

Mats

**Comment by burqen** [comment]
Hello @meg261995 👋 
You should be able to use transaction event listeners for this purpose. The event listener will receive a callback every time a transaction commits and you can inspect the content of the transaction to determine if any node was created. See documentation here https://neo4j.com/docs/java-reference/current/transaction-management/#transactions-events

**Comment by burqen** [comment]
Closing this issue since a response has been given.
