### ISSUE TITLE
[SSO] Allow http scheme for localhost

### ISSUE THREAD

**Issue by ikwattro** [neo4j/neo4j#13013]
In Neo4j 5.3 the server validates that the uri used for oidc providers use the https scheme, otherwise it fails to start the server with 

```
Failed to read config: Error evaluating value for setting 'dbms.security.oidc.keycloak.jwks_uri'. 'http://keycloak:8080/realms/my-realm/protocol/openid-connect/certs' does not have required scheme 'https'
Run with '--verbose' for a more detailed error message.
```

While I understand the requirement for production scenarios, it makes local development and testing in CI very difficult, I would ask for allowing http for localhost/127.0.0.1 or a setting that would allow to disable the check.

**Comment by mnd999** [comment]
A fix has been made to allow localhost in SSO URLs. This should be included in 5.9.
