### ISSUE TITLE
Comparing different durations returns null

### ISSUE THREAD

**Issue by Andy2003** [neo4j/neo4j#13019]
Comparing two different durations returns `null`.

**Neo4j Version:** 5.3.0, 4.4 , 4.1

### Steps to reproduce

Invoke:

```cypher
RETURN duration("P1D") <= duration("P1Y")
```

### Expected behavior

the result `true`

### Actual behavior

the result  `null`

### Additional tests:

```cypher
RETURN duration("P1D") <= duration("P1D")
```

returns `true`

---

```cypher
RETURN duration("P1D") < duration("P1D")
```

returns `null`

---

```cypher
CREATE (:X{d:duration("P1D")});
MATCH (n:X) where n.d < duration("P1Y") RETURN n;
```

returns no nodes

**Comment by sherfert** [comment]
Hi @Andy2003 and thanks for your report.

The behavior you describe is intended and documented:
https://neo4j.com/docs/cypher-manual/current/syntax/operators/#cypher-ordering

> [Duration](https://neo4j.com/docs/cypher-manual/current/syntax/temporal/#cypher-temporal-durations) values cannot be compared, since the length of a day, month or year is not known without knowing which day, month or year it is. Since Duration values are not comparable, the result of applying a comparison operator between two Duration values is null.

If you want to compare duration values, you first need to add them to a common date/datetime like this:

```
RETURN date() + duration("P1D") <=  date() + duration("P1Y")
```

Alternatively, if you know that your durations only use the same [component groups](https://neo4j.com/docs/cypher-manual/current/syntax/temporal/#cypher-temporal-accessing-components-durations), you can compare those:

```
RETURN duration("P1D").days <=  duration("P365D").days
```
