### ISSUE TITLE
"neo4j status" returns success before neo4j has finished starting

### ISSUE THREAD

**Issue by markslater** [neo4j/neo4j#13020]
When Neo4j is started, `neo4j status` returns exit code 0 after one or two seconds, but Neo isn't actually ready to accept connections until some time later

**Neo4j Version:** 5.3.0
**Operating System:** Linux Mint 20.2
**Driver:** N/A (observed with cypher-shell and Java driver 5.3.0; I don't believe it's driver related)

### Steps to reproduce
1. Download and unpack neo4j community server 5.3.0
2. Start Neo, poll for `neo4j status` to return exit code 0, and then attempt to execute some cypher:
```bash
neo4j-community-5.3.0/bin/neo4j console &
until neo4j-community-5.3.0/bin/neo4j status; do sleep 1; done
neo4j-community-5.3.0/bin/cypher-shell --username "neo4j" --password "neo4j" "CALL db.ping();"
```
### Expected behavior
After `neo4j status` returns exit code 0, the server should be ready to accept connections

### Actual behavior
Neo continues to refuse connections for some time: `neo4j-community-5.3.0/bin/cypher-shell --username "neo4j" --password "neo4j" "CALL db.ping();"` returns `Connection refused`.  Note the additional time is short for an empty database with default configuration, but in real-world cases I see ~15 additional seconds before connections are accepted (I don't know if this difference is related to memory configuration or database size)

**Comment by Roxling** [comment]
@markslater This is not a bug, but how that feature is intended to work and always has been working. The status command is checking whether or not the neo4j process is alive. It does not check if individual database components are started.

If you feel that this should be a feature, then convert it to a feature request. Or, we'll happily accept a PR adding this feature as an extra argument to the `neo4j status` command

**Comment by markslater** [comment]
@Roxling maybe it's just a documentation issue in that case.  The [documentation I found](https://neo4j.com/docs/operations-manual/current/tools/neo4j-admin/#_neo4j_admin_commands_per_category) (admittedly, `neo4j status` is hard to search for), just says 'Gets the status of the server.'

IMHO, it's more intuitive for the status command to indicate whether or not the server is in a usable state.  Are there use cases for knowing whether the process is running regardless of whether it's possible to connect to it?

**Comment by Roxling** [comment]
@markslater I agree that it may in some cases be more useful on startup to check availability of the server. For shutdown its likely more useful to know when process itself is gone. But this is not a usability issue, as there are a lot of user scripts out there relying on the current behavior, so changing it would break compatibility and that can be done earliest in the next major release.

I'll look into updating that documentation to state its the status of the server process its feching
