### ISSUE TITLE
Couldn't connect the bolt driver in container to python code present in another container.

### ISSUE THREAD

**Issue by hariteja97** [neo4j/neo4j#13027]
## Guidelines

Hi everyone,
I have created a docker-compose file with a neo4j container and python. I wanted to use bolt driver created in neo4j container inside python container . I was successfull in passing the parameters and validation. but when I use the bolt driver . It throws error in connection to the bolt driver.

It throws the following error.

![image](https://user-images.githubusercontent.com/29245616/211670984-348c8b35-e5e5-4cc7-9499-95393507e2d8.png)

Before creating a new issue, please check whether someone else has raised the same issue. You may be able to add context to that issue instead of duplicating the report. However, each issue should also only be focussed on a _single_ problem, so do not describe new problems within an existing thread - these are very hard to track and manage, and your problem may be ignored. Finally, do not append comments to closed issues; if the same problem re-occurs, open a new issue, and include a link to the old one.

To help us understand your issue, please specify important details, primarily:

- Neo4j version: 5.3.0 - Enterprise(docker image)
- Operating system: Windows 11 Home pro
- API/Driver: neo4j-driver python package
- **Steps to reproduce**
- Expected behavior
- Actual behavior

Output: I receieved. 
neo4j-service        | Entereing the main function
neo4j-service        | Checking the URL retrieved--->  bolt://localhost:4000
neo4j-service        | Session is beginning
neo4j-service        | Session Started
neo4j-service        | Transaction failed and will be retried in 1.0834860488329325s (Couldn't connect to localhost:4000 (resolved to ()):
neo4j-service        | Failed to establish connection to ResolvedIPv4Address(('127.0.0.1', 4000)) (reason [Errno 111] Connection refused)
neo4j-service        | Failed to establish connection to ResolvedIPv6Address(('::1', 4000, 0, 0)) (reason [Errno 99] Cannot assign requested address))
neo4j-service        | Transaction failed and will be retried in 2.0019330298705253s (Couldn't connect to localhost:4000 (resolved to ()):
neo4j-service        | Failed to establish connection to ResolvedIPv4Address(('127.0.0.1', 4000)) (reason [Errno 111] Connection refused)
neo4j-service        | Failed to establish connection to ResolvedIPv6Address(('::1', 4000, 0, 0)) (reason [Errno 99] Cannot assign requested address))
neo4j-service        | Transaction failed and will be retried in 3.9857295994472968s (Couldn't connect to localhost:4000 (resolved to ()):
neo4j-service        | Failed to establish connection to ResolvedIPv4Address(('127.0.0.1', 4000)) (reason [Errno 111] Connection refused)
neo4j-service        | Failed to establish connection to ResolvedIPv6Address(('::1', 4000, 0, 0)) (reason [Errno 99] Cannot assign requested address))
neo4j-service        | Transaction failed and will be retried in 8.000713404187417s (Couldn't connect to localhost:4000 (resolved to ()):
neo4j-service        | Failed to establish connection to ResolvedIPv4Address(('127.0.0.1', 4000)) (reason [Errno 111] Connection refused)
neo4j-service        | Failed to establish connection to ResolvedIPv6Address(('::1', 4000, 0, 0)) (reason [Errno 99] Cannot assign requested address))
neo4j-service        | Transaction failed and will be retried in 12.994146136289839s (Couldn't connect to localhost:4000 (resolved to ()):
neo4j-service        | Failed to establish connection to ResolvedIPv4Address(('127.0.0.1', 4000)) (reason [Errno 111] Connection refused)
neo4j-service        | Failed to establish connection to ResolvedIPv6Address(('::1', 4000, 0, 0)) (reason [Errno 99] Cannot assign requested address))
neo4j-service        | Transaction failed and will be retried in 33.312542892369095s (Couldn't connect to localhost:4000 (resolved to ()):
neo4j-service        | Failed to establish connection to ResolvedIPv4Address(('127.0.0.1', 4000)) (reason [Errno 111] Connection refused)
neo4j-service        | Failed to establish connection to ResolvedIPv6Address(('::1', 4000, 0, 0)) (reason [Errno 99] Cannot assign requested address))
neo4j-service        | Traceback (most recent call last):
neo4j-service        |   File "/usr/local/lib/python3.7/site-packages/neo4j/_async_compat/network/_bolt_socket.py", line 507, in _connect
neo4j-service        |     s.connect(resolved_address)
neo4j-service        | ConnectionRefusedError: [Errno 111] Connection refused
neo4j-service        |
neo4j-service        | The above exception was the direct cause of the following exception:
neo4j-service        |
neo4j-service        | Traceback (most recent call last):
neo4j-service        |   File "/usr/local/lib/python3.7/site-packages/neo4j/_async_compat/network/_bolt_socket.py", line 652, in connect
neo4j-service        |     s = BoltSocket._connect(resolved_address, timeout, keep_alive)
neo4j-service        |   File "/usr/local/lib/python3.7/site-packages/neo4j/_async_compat/network/_bolt_socket.py", line 528, in _connect
neo4j-service        |     ) from error
neo4j-service        | neo4j.exceptions.ServiceUnavailable: Failed to establish connection to ResolvedIPv4Address(('127.0.0.1', 4000)) (reason [Errno 111] Connection refused)

**Neo4j Version:** 3.0M03
**Operating System:** Windows 
**API:** Docker 18+

Please any help in this regard would be really helpful.

**Comment by hariteja97** [comment]
My docker-compose file is:

networks:
  lan:

services:
  neo4j-service:
    container_name: neo4j-service
    build: 
      dockerfile: Dockerfile
      context: ./python
    tty: true
    environment:
      NEO4J_URI: bolt://localhost:4000
      NEO4J_USER: "neo4j"
      PYTHONUNBUFFERED: 1
    hostname: neo4j-service
    depends_on:
      storage:
        condition: service_healthy
    ports:
      - "3000:3000"
    restart:
      always
    networks:
      - lan
    links:
      - storage
  
  storage:
    hostname: storage
    # build: ./neo4j
    image: neo4j:5.3-enterprise
    networks:
      - lan
    ports:
      - 7474:7474 #Http
      - 4000:7687 #Bolt
      - 7373:7373 #Https
    environment:
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_dbms_default__listen__address: 0.0.0.0
      NEO4J_dbms_default__advertised__address: localhost
      NEO4J_dbms_ssl_policy_bolt_client__auth: "NONE"
      NEO4J_dbms_ssl_policy_https_client__auth: "NONE"
      NEO4J_dbms_databases_seed__from__uri__providers: URLConnectionSeedProvider,S3SeedProvider
      NEO4J_dbms_security_procedures_unrestricted: apoc.* , algo.*
      
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_AUTH: neo4j/password
      #NEO4J_dbms.connector.bolt.enabled: "true"
      #NEO4J_dbms_default__advertised__address: localhost
      #NEO4J_dbms.connectors.default_listen_address: localhost
      #NEO4J_dbms_connector_http_listen__address: :7474
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_export_file_enabled: "true"

      NEO4J_dbms_default__database: "neo4j"
      NEO4J_dbms.connector.bolt.tls_level: "OPTIONAL"
    volumes:
      - "./db/data:/data"
      - "./db/conf:/conf"
      - "./db/logs:/logs"
      - "./db/plugins:/plugins"
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 30s
      timeout: 20s
      retries: 1
  
networks:
  lan:

**Comment by mnd999** [comment]
Are you sure you want localhost here? Aren't you trying to traverse the container network to the other container? Probably this is more a docker question than a Neo4j database one. I would suggest reaching out on [our community forums](https://community.neo4j.com/) or on our [discord](https://discord.gg/neo4j) or a docker forum and you will likely get a faster response there. Github is more setup for bug reports in the product.

**Comment by hariteja97** [comment]
Yes, @mnd999 I'm trying to access the container 1 network to another container , I tried all the possible extensions but it didn't help. I tried to get an answer still no help.

**Comment by mnd999** [comment]
Your docker-compose is not well formatted so it's hard to see what you're doing but I think you want `storage:7687` instead of `localhost:4000`
