### ISSUE TITLE
create constraint failed after import data

### ISSUE THREAD

**Issue by Reid00** [neo4j/neo4j#13023]
version: v4.4.3 community 
detail here: 
https://community.neo4j.com/t5/neo4j-graph-platform/neo4j-create-node-constraint-index-failed/m-p/63945#M37760

**Comment by HannesSandberg** [comment]
Thanks for your report. We will look into this

**Comment by Reid00** [comment]
is there any update?

**Comment by mnd999** [comment]
I tried to reproduce this and it worked for me at least on an empty database. Looking at the trace, it looks like the client is connecting via HTTP and then losing the connection before the result gets written out, but I don't have the end of the trace so I can't see if it's failing further down. Is it possible the creation is just  taking a while and the client is giving up before it gets the result. It would then succeed quickly second time as it would already exist and you have `IF NOT EXISTS`? If not, can you supply the full trace and perhaps some more information about the database. Is there anything in debug.log?

**Comment by Reid00** [comment]
1. it's not exist，I delete neo4j folder in data/database dir and then import data with `neo4j-admin import` 
2. `IF NOT EXISTS` just in case 
3. I do more tests, it's like you said, I found if neo4j is creating index/constraint after importing data, in the meantime, I consume kafka and write data to Neo4j, the index/constraint will be very slowly or stuck or failed. since cost time of importing time and create index is mutable, i have to consume kafka lately to avoid this issue.

**Comment by mnd999** [comment]
Unfortunately, the community post has disappeared due to it migrating to a different platform. It sounds like you may have resolved the issue though already. If not, can you again share the queries you were running and the full stack traces as part of the github ticket?

**Comment by Reid00** [comment]
don't fix it, just find a way walk around it.
