### ISSUE TITLE
Unexpected ERROR:out of bounds for long

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13047]
I execute a query on my neo4j database ,and it is supposed to output 2500 as result,but an error occurred.

Neo4j version:4.4.5
operating system:windows 10
API：Cypher version 9
query: match () match() where exists(()-[]-()) return count(*)
error:Neo.DatabaseError.Statement.ExecutionFailed
issue description:the query is executed on a graph containing at least one relationship,and the result should be the number of nodes squared.But when the graph contains too much nodes such as 50,there is an error.

Looking forward to your reply!

**Comment by HannesSandberg** [comment]
Thank you for your report! We will investigate this and report back to you.

**Comment by inmost-light** [comment]
@ljhhuxiaoba
Thank you for reporting, a fix has been implemented and should be available in the next release.
