### ISSUE TITLE
Error: There is no procedure with the name `db.constraints` registered for this database instance

### ISSUE THREAD

**Issue by xStevex** [neo4j/neo4j#13040]
I have this error: "**Error: There is no procedure with the name `db.constraints` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.**"
I don't think it's a bug and most likely I need to configure something, but I'm very new to neo4j and it's hard to solve this problem on my own. Could someone help me with this? I tried to find similar issues on the internet by searching _"Error: There is no procedure with the name"_, but they all did not follow the same pattern.

**Comment by InverseFalcon** [comment]
Which version of Neo4j are you using? In 5.x I think those may have been removed in favor of SHOW commands, like SHOW CONSTRAINTS

**Comment by burqen** [comment]
@xStevex @InverseFalcon That's right, `db.constraints` where removed in 5.x in favour for `SHOW CONSTRAINTS`. Documentation can be found here https://neo4j.com/docs/cypher-manual/current/constraints/syntax/#constraints-syntax-list .

**Comment by mnd999** [comment]
Since this is answered and we have not had a response I will close it. If it's still an issue, please feel free to reopen.
