### ISSUE TITLE
Cannot open Neo4j Desktop on Linux

### ISSUE THREAD

**Issue by Faiail** [neo4j/neo4j#13044]
Hello everyone.
I always use neo4j on linux.
However, yesterday I tryied to launch the AppImage on my computer, but the initial window gets stucked in the `Restoring application state` process. I tried to uninstall the application and install again, but the problem continues to occur.
How can I solve that?
Thanks!

**Comment by mnd999** [comment]
Thanks for the report! Unfortunately, this is not the correct repository for the Desktop application, this one is for the database itself.  Please open an issue for Desktop [here](https://github.com/neo4j-devtools/neo4j-desktop).
