### ISSUE TITLE
Cannot MATCH and CREATE in a CALL subquery with the new label match syntax

### ISSUE THREAD

**Issue by CelineWuest** [neo4j/neo4j#13054]
I get the error message `Mixing label expression symbols ('|', '&', '!', and '%') with colon (':') is not allowed.` when having a `MATCH` clause using the new label syntax followed by a `CREATE` clause in a `CALL {}` subquery.
It seems this is unintended behaviour, as the `CREATE` clause does not use label matches, thus being unrelated to the syntax type used by the preceding `MATCH` clause.

I encountered this issue when testing queries in the [Neo4j Sandbox](https://neo4jsandbox.com) using the StackOverflow dataset.
**Neo4j Version:** 5.4.0

### Steps to reproduce
Run the following query and observe it throws an error:
`CALL { MATCH (:!A) CREATE (:B:C) } RETURN 1`

### Expected behavior
The query should execute successfully.

### Actual behavior
The query fails with the error message `Mixing label expression symbols ('|', '&', '!', and '%') with colon (':') is not allowed. Please only use one set of symbols. This expression could be expressed as :B&C. (line 1, column 30 (offset: 29))`.

**Comment by HannesSandberg** [comment]
Thanks for your report! We will investigate this

**Comment by sherfert** [comment]
@DominicWuest 
You will be delighted to hear that we fixed this bug. Finally.
The fix will be included in 5.15.
