### ISSUE TITLE
Naming rules and escaped names

### ISSUE THREAD

**Issue by nafraf** [neo4j/neo4j#13068]
Hi, I have a doubt about the naming rules for properties. Probably there is an error with the parser, because it is possible to create properties with invalid names.

According to the [Naming rules and recommendations](https://neo4j.com/docs/cypher-manual/current/syntax/naming/):
- Names should begin with an alphabetic character.
- Names should not contain symbols, except for underscore, as in my_variable, or $ as the first character to denote a [parameter](https://neo4j.com/docs/cypher-manual/current/syntax/parameters/), as given by $myParam

But if a escaped name is used, it breaks all the rules.

### Steps to reproduce
Run the query:
``CREATE (n:N {`\\?a`:1, `$b`:2, `1c`:3})``

### Expected behavior
Report an error of "Invalid Input"

### Actual behavior
The properties are created breaking the rules listed before.

**Comment by HannesSandberg** [comment]
Hello @nafraf , thank you for your report. 

This behaviour is explained a bit further down in that page in the documentation. Is it possible to use special characters if escaped. https://neo4j.com/docs/cypher-manual/current/syntax/naming/#_using_special_characters_in_names
