### ISSUE TITLE
Domain: https://debian.neo4j.org/ Certificate is expired

### ISSUE THREAD

**Issue by Y0h4n3s** [neo4j/neo4j#13069]
This causes issues when installing on a debian system

**Comment by jennyowen** [comment]
Thanks for reporting this. It's now fixed.
yum.neo4j.com was also using the same certificates and I've updated those too.

**Comment by pwojcieszonek** [comment]
Problem still exists. CN in cert not match debian.neo4j.org.

**Comment by jennyowen** [comment]
@pwojcieszonek debian.neo4j.org has been deprecated for a long time. You shouldn't be relying on it *anywhere*.

I can look into the certificates, but it's possible I won't be able to fix them.

The real fix is to update your code/systems to use debian.neo4j.com instead of .org.
