### ISSUE TITLE
Unexpected inconsistent results about "WITH"

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13075]
I execute two queries on my neo4j database ,and they are supposed to output same results but not.

Neo4j version: 4.4.5 Enterprise
operating system: windows 10
API：Cypher version 9
query:  MATCH (n0),()<-[m0]-(),(n1),()-[m1]->(),(n2) WHERE (n0)<-[m0]-(n1)-[m1]->(n2) WITH n0,1 as n OPTIONAL MATCH (n0),()<-[m2]-(),(n1),()-[m3]->(),(n2) WHERE (n0)<-[m2]-(n1)-[m3]->(n2) OPTIONAL MATCH (n0)<-[]-(n1)-[]->(n2) RETURN count(1)

The result of the above query is six,but if I remove "1 as n" in the  WITH clause ,the result becomes two. But I think the alias "1 as n" should have no effect on the outcome here.

There are my graph data:
create (:L1)<-[:T1]-(:L2)-[:T1]->(:L1);

**Comment by smietana** [comment]
Thank you! We will investigate this.

**Comment by arnefischereit** [comment]
This is presumably the same issue as #13067. Please reopen if you disagree.
