### ISSUE TITLE
ExecutionFailed with Cryptic Error Message 

### ISSUE THREAD

**Issue by CelineWuest** [neo4j/neo4j#13078]
When running the query `CALL { CREATE ()-[m:t]->() } MERGE ()<-[m:t]-()-[:t]->()`, an ExecutionFailed exception is raised with the cryptic error message `key not found: SymbolUse(m@47(ff38908))`.
I believe the query is syntactically and semantically correct and thus no error should be thrown.

I encountered this issue when testing queries in the **Neo4j 5.5.0 community version** running in a Docker container running **alpine v.3**.

### Steps to reproduce
Run the following query and observe it throws an error:
`CALL { CREATE ()-[m:t]->() } MERGE ()<-[m:t]-()-[:t]->()`

### Expected behavior
The query should run successfully.

### Actual behavior
The query fails with the error message `Neo.ClientError.Statement.ExecutionFailed: key not found: SymbolUse(m@40(4a86ebef))`

**Comment by smietana** [comment]
Thank you! We will investigate this.

**Comment by CelineWuest** [comment]
I found another, rather similar, query generating a nearly identical error message:
`WITH 0 AS x FOREACH ( y IN null | MERGE ()<-[x:m]-()<-[:m]-() )`
Produces `key not found: SymbolUse(x@45(49df29a8))`

**Comment by nadja-muller** [comment]
This has been fixed for 5.11.0 🎉
