### ISSUE TITLE
Inconsistency in literal interpretation as list in `FOREACH` and `UNWIND`

### ISSUE THREAD

**Issue by raz-mon** [neo4j/neo4j#13076]
Hi,
There is somewhat of an inconsistency between the interpretation of literals as lists by `UNWIND` and `FOREACH`.
`UNWIND` will interpret them as lists, but `FOREACH` will not.

Example:
`UNWIND 1 AS x RETURN x` ==> 1 is returned.
`FOREACH(n IN 1 | CREATE (:N {v: n}))` ==> a type-mismatch error is raised, since 1 is not a list.

Would appreciate your take on it.
Thanks.

**Comment by smietana** [comment]
Thank you! We will investigate this.

**Comment by raz-mon** [comment]
Yes, I know.
What I pointed out is that practically this is what happens in `FOREACH` as well, so it makes sense to be consistent in this behavior.

**Comment by JoelBergstrand** [comment]
This issue has been solved and should work consistently now.
