### ISSUE TITLE
how to connect neo4j auradb behind firewall proxy with python api

### ISSUE THREAD

**Issue by furynerd** [neo4j/neo4j#13079]
hi, i'm learning to use neo4j auradb just recently, i tried the example of the docs:

https://neo4j.com/docs/aura/auradb/connecting-applications/python/

but got errors:

```
Unable to retrieve routing information
Transaction failed and will be retried in 1.0940946540965086s (Unable to retrieve routing information)
...
...
...
neo4j.exceptions.ServiceUnavailable: Unable to retrieve routing information
```

i think it the issue about my internet connection is behind a firewall of my organization and need a proxy `http://username:password@ip:port`, by this proxy config in browser, i can use the db on web online.

but how can i config it with python api? (running `.py` on my local pc) 

i have tried set the proxy in python script like:

```python
    import os
    os.environ["http_proxy"]  = "http://username:password@ip:port"
    os.environ["https_proxy"] = "http://username:password@ip:port"
    os.environ["ALL_PROXY"]   = "http://username:password@ip:port"
    os.environ["HTTP_PROXY"]  = "http://username:password@ip:port"
    os.environ["HTTPS_PROXY"] = "http://username:password@ip:port"
```

looks no help...

and btw, `gpt` told me something like 
```pythonfrom neo4j import GraphDatabase, basic_auth

# Set up the configuration for the proxy
config = {
    'proxies': {
        'http': 'http://your-proxy-url:port',
        'https': 'https://your-proxy-url:port'
    }
}

# Set up the driver with the proxy configuration
driver = GraphDatabase.driver("bolt://your-neo4j-url:7687", auth=basic_auth("your-neo4j-username", "your-neo4j-password"), **config)


```

looks like total nonescense... i searched the docs and found nothing like `proxy` configs

thanks for any help

**Comment by smietana** [comment]
Thank you! We will investigate this.

**Comment by furynerd** [comment]
hi, i got some advice for reference:
https://github.com/neo4j/neo4j-python-driver/discussions/904#discussioncomment-5379205
