### ISSUE TITLE
Unexpected inconsistent results about "WHERE true"

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13073]
I execute two queries on my neo4j database ,and they are supposed to output same results but not.

Neo4j version: 4.4.5 Enterprise
operating system: windows 10
API：Cypher version 9
query:   MATCH (n0:L0)-[]->(n1:L1) OPTIONAL MATCH (n2:L2) WITH * WHERE true OPTIONAL MATCH (n1)<-[]-(n3),(n4),()<-[r0]-() WHERE (n4)<-[r0]-(n1) OPTIONAL MATCH (n3) RETURN count(*)
The result of the above query is nine,but if I remove the clause "WHERE true",the result becomes six. But I think the clause "WHERE true" should have no effect on the outcome here.

There are my graph data:
create (:L0)-[:T0]->(:L2);
create (:L0:L2)-[:T1]->(a:L1)-[:T2]->(:L2);
match (a:L1) create ()-[:T3]->(a);

**Comment by smietana** [comment]
Thank you! We will investigate this.

**Comment by arnefischereit** [comment]
This is presumably the same issue as #13067. Please reopen if you disagree.
