### ISSUE TITLE
Unexpected inconsistent results about OPTIONAL

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13071]
I execute two queries on my neo4j database ,and they are supposed to output same results but not.

Neo4j version: 4.4.5 Enterprise
operating system: windows 10
API：Cypher version 9
query:  MATCH (n0:L0) UNWIND [1] AS m OPTIONAL MATCH (n0),()<-[r0]-(),(n1),()-[r1]->(),(n11) WHERE (n0)<-[r0]-(n1)-[r1]->(n11) OPTIONAL MATCH (n0),()<-[r2]-(),(n1) WHERE (n0)<-[r2]-(n1) RETURN count(1)
The result of the above query is three,but when I remove the second "OPTIONAL" keyword,the result becomes one. But I think the second "OPTIONAL" keyword should have no effect on the outcome here.

There are my graph data:
create (:L0)<-[:T0]-(:L1)-[:T1]->(:L2);

**Comment by HannesSandberg** [comment]
Thanks for the report! We will investigate this.

**Comment by arnefischereit** [comment]
This is presumably the same problem as in #13067.

As noted there: Please upgrade to a version of Neo4j of 4.4.9 or higher and check whether the problem persists.
