### ISSUE TITLE
Unexpected inconsistent results about Label

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13074]
I execute two queries on my neo4j database ,and they are supposed to output same results but not.

Neo4j version: 4.4.5 Enterprise
operating system: windows 10
API：Cypher version 9
query:  MATCH (n0{id:0}) UNWIND [1] AS a0 MATCH (n1)-[:T0]->(n3 :L0 :L3), (n4),()<-[r0:T0]-(),(n2:L1) WHERE (n4)<-[r0]-(n2) OPTIONAL MATCH (n0:L1)<-[]-(n1),()-[r1:T1]->(),(n5) WHERE (n1)-[r1]->(n5:L3) RETURN n5.id

The result of the above query is 3,which is the id of node found,but if I remove ":L1" in the OPTIONAL MATCH clause,the result becomes null. The node n0 with id 0 is already labeled L1 in my graph,so I think the removal of ":L1" shouldn't make the node with id 3 missed.

There are my graph data:
create (n0:L1{id:0})<-[:T0]-(n1:L1{id:1})<-[:T1]-(n2{id:2})-[:T1]->(:L3{id:3}); 
match (n{id:2}) create (n)-[:T0]->(:L0:L3{id:4});

**Comment by smietana** [comment]
Thank you! We will investigate this.

**Comment by ljhhuxiaoba** [comment]
The problem has been solved after version updating!Thanks very much.
