### ISSUE TITLE
Unexpected Syntax Error in SET Clause

### ISSUE THREAD

**Issue by CelineWuest** [neo4j/neo4j#13077]
A syntax error is falsely thrown when using a SET clause on a property starting with an underscore followed by a number. Examples are `._1`, `._9abc` etc.
I believe that no error should be thrown, as the aforementioned property names are valid (for example when matching or creating a node) and the [docs](https://neo4j.com/docs/cypher-manual/current/syntax/naming/) don't mention its invalidity when following the RFC2119 convention.
Additionally, some close alternatives don't throw an error (e.g. `_`, `_a`, `_a1`).

I encountered this issue when testing queries in the [Neo4j Sandbox](https://neo4jsandbox.com/) using the StackOverflow dataset.
**Neo4j Version: 5.5.0**

### Steps to reproduce
Run the following query and observe it throws an error:
`MATCH (n) SET n._1 = 0`

### Expected behavior
The query should run successfully.

### Actual behavior
The query fails with the error message `Neo.ClientError.Statement.SyntaxError: Invalid input '._1': expected ":"`

**Comment by smietana** [comment]
Thank you! We will investigate this.

**Comment by gem-neo4j** [comment]
Thank you for reporting, we have fixed this and it will be available in the next minor release (5.15) :)
