### ISSUE TITLE
Unexpected inconsistent results about identifier

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13072]
I execute two queries on my neo4j database ,and they are supposed to output same results but not.

Neo4j version: 4.4.5 Enterprise
operating system: windows 10
API：Cypher version 9
query: MATCH (n0:L0) UNWIND [1] AS m OPTIONAL MATCH (n0),()<-[r0]-(),(n1),()-[r1]->(),(n2) WHERE (n0)<-[r0]-(n1)-[r1]->(n2) OPTIONAL MATCH (n0),()<-[r2]-(),(n1) WHERE (n0)<-[r2]-(n1) RETURN count(1)
The result of the above query is one,but if I replace the identifier "n2" with "n3",the result becomes three. But I think different name of  identifier should have no effect on the outcome here.

There are my graph data:
create (:L0)<-[:T0]-(:L1)-[:T1]->(:L2);

**Comment by HannesSandberg** [comment]
Thank you! We will investigate this!

**Comment by hedengran** [comment]
Hi, thanks again for reporting this. The issue was resolved in 4.4.10.
