### ISSUE TITLE
LOAD CSV from non-existent http resource adds 13 nodes 

### ISSUE THREAD

**Issue by ludgeli** [neo4j/neo4j#13082]
- Neo4j version: aura db, free tier
- **Steps to reproduce**
  - create free aura db instance
  - run `LOAD CSV FROM 'http://this-does-not-exist-123123asdasd.s3-website.us-east-1.amazonaws.com/this_is_not_real.csv' AS row CREATE (n:Node { id: 'potato' })`
- Expected behavior
  - error because resource does not exist 
- Actual behavior
  - Created 13 nodes, set 13 properties, added 13 labels 

I happened upon this because my own legitimate `LOAD CSV FROM 'http://...'` was not working with merge, and when i changed to a simple create statement it did the same thing (import 13 nodes etc)

**Comment by smietana** [comment]
Thank you! We will investigate this.

**Comment by loveleif** [comment]
Thanks for reporting this issue @ludgeli! We have merged a fix that will be included in a future next 5.x release.

**Comment by smietana** [comment]
This has been fixed and is included in 5.8.
