### ISSUE TITLE
Unexpected inconsistent results about "DISTINCT"

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13080]
I execute two queries on my neo4j database ,and they are supposed to output same results but not.

Neo4j version: 4.4.5 Enterprise
operating system: windows 10
API：Cypher version 9
query:  MATCH (n2:L6)-[r2:T6]->(n3:L1) WITH DISTINCT n2 MATCH (n1),()-[m0]->(),()-[m1]->(),(n3) WHERE (n1)-[m0]->(n2)-[m1]->(n3) OPTIONAL MATCH (n1)-[m4]->(n2:L6)-[m5]->(n3:L1),(n4 :L6 :L5 :L0)-[r3 :T0]->(n0) RETURN DISTINCT n2.id,n4.id

The result of n2.id in the above query is 25.but if I remove the first "DISTINCT",the result of n2.id becomes 44. But I think the "DISTINCT" should have no effect on the result of n2.id here.

I tried to simplify the original graph without changing the result but failed, so I provide the original graph to reproduce the result.There are my graph data:
[graph_data.txt](https://github.com/neo4j/neo4j/files/11026490/graph_data.txt)

**Comment by smietana** [comment]
Thank you! We will investigate this.

**Comment by arnefischereit** [comment]
This is presumably the same issue as #13067. Please reopen if you disagree.
