### ISSUE TITLE
Neo4J not using the refresh token from Azure AD token (SSO timeout issue)

### ISSUE THREAD

**Issue by omar-khan1** [neo4j/neo4j#13087]
I have successfully enabled SSO connection using Azure AD Enterprise Applications and Group to Role mappings, however it seems that the session consistently times out after approximately one hour. This is likely due not taking the refresh token provided by the OpenID API. Is this fixable?

- Neo4j version: 4.4.18
- Operating system: Red Hat Enterprise Linux 9

### Expected behavior
Session should refresh and not timeout.

### Actual behavior
Session times out after 1 hour.

**Comment by smietana** [comment]
Thank you! We will investigate this.

**Comment by mnd999** [comment]
SSO is an enterprise only feature, so if possible I would advise you to open a support ticket with your enterprise support team and they will be able to advise you on this. It will also be easier to share details of your SSO configuration in a non-public way through the support portal.

**Comment by mnd999** [comment]
I understand this is now being handled through a support ticket, so I will close for now. Please feel free to reopen if necessary.
