### ISSUE TITLE
Neo.DatabaseError.General.UnknownError

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13085]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.5.0 Enterprise
operating system: windows 10
API：Cypher version 9
query: MATCH (n0 :L2)-[r0 :T0]->(n1 :L2 :L4 :L3) WHERE ((r0.id) > -1) MATCH (n0)<-[r2 :T6]-(n3 :L5)-[r3 :T5]->(n4 :L2), (n1)<-[r5 :T4]-(n5 :L1) WHERE (((((r2.id) > -1) AND ((r2.id) <> (r3.id))) AND ((r2.id) <> (r5.id))) AND ((r3.id) <> (r5.id))) WITH max('EdQfBfpE9') AS a0 ORDER BY a0 DESC WHERE true WITH a0 WHERE (NOT true) OPTIONAL MATCH (n6)-[r6 :T4]->(n7 :L5 :L0 :L3)-[r7 :T3]->(n8 :L4) WHERE (((r6.id) > -1) AND ((r6.id) <> (r7.id))) OPTIONAL MATCH (n2 :L1)<-[r8 :T3]-(n9 :L0)<-[r9 :T3]-(n10 :L1), (n11 :L2)<-[r10 :T6]-(n6)-[r11 :T5]->(n12 :L0 :L6) WHERE (((((((-1963802003 < (n7.k4)) AND ((r8.id) <> (r9.id))) AND ((r8.id) <> (r10.id))) AND ((r8.id) <> (r11.id))) AND ((r9.id) <> (r10.id))) AND ((r9.id) <> (r11.id))) AND ((r10.id) <> (r11.id))) OPTIONAL MATCH (n0 :L2)-[]->(n1)-[]->(n2) OPTIONAL MATCH (n11 :L2)<-[]-(n6)-[]->(n12), (n13)-[r12 :T1]->(n14)<-[r13 :T3]-(n15) WHERE (((r12.id) > -1) AND ((r12.id) <> (r13.id))) OPTIONAL MATCH (n3)-[r14 :T3]->(n16), (n15 :L6)<-[r16 :T2]-(n11) WHERE (((r9.k62) OR (n12.k5)) AND ((r14.id) <> (r16.id))) RETURN a0, (r13.k60) AS a1, (r7.k63) AS a2, (r11.k73) AS a3 ORDER BY a0, a2 DESC
error message:
Expected a sorted plan but got
.apply(fromSubquery = false)
.|.argument()
.projection(project = Seq("NULL AS n8", "NULL AS r10", "NULL AS n11", "NULL AS r9", "NULL AS n9", "NULL AS `  UNNAMED3`", "NULL AS r8", "NULL AS `  UNNAMED2`", "NULL AS r16", "NULL AS n7", "NULL AS n6", "NULL AS `  UNNAMED1`", "NULL AS `  n1@104`", "NULL AS n2", "NULL AS n15", "NULL AS r6", "NULL AS r11", "NULL AS r14", "NULL AS r13", "NULL AS n10", "NULL AS n16", "NULL AS n13", "NULL AS n14", "NULL AS r7", "NULL AS `  UNNAMED0`", "NULL AS r12", "NULL AS n12", "NULL AS `  n3@105`", "NULL AS `  n0@103`"), discard = Set("a0"))
.limit(0)
.apply(fromSubquery = false)
.|.argument()
.filter("true")
.sort(Seq(Descending("a0")))
.aggregation(Seq(), Seq("max($`  AUTOSTRING2`) AS a0"))
.filter("n4:L2", "not r2.id = r3.id", "not r3.id = r5.id")
.expandAll("(  n3@102)-[r3:T5]->(n4)")
.filter("`  n3@102`:L5", "not r2.id = r5.id", "r2.id > $`  AUTOINT1`")
.expandAll("(  n0@100)<-[r2:T6]-(  n3@102)")
.filter("`  n0@100`:L2", "r0.id > $`  AUTOINT0`")
.expandAll("(  n1@101)<-[r0:T0]-(  n0@100)")
.filter("n5:L1")
.expandAll("(  n1@101)<-[r5:T4]-(n5)")
.intersectionNodeByLabelsScan("  n1@101", Seq("L2", "L4", "L3"), IndexOrderNone)
.build()

There are my graph data:
[graph_data.txt](https://github.com/neo4j/neo4j/files/11041469/graph_data.txt)

**Comment by smietana** [comment]
Thank you! We will investigate this.

**Comment by Dunfluff** [comment]
The query produces a `WHERE False` predicate which affected the planning of `Sort` and produced the error message, this has now been fixed in 5.8 and will instead finish planning and return 0 results. Thank you for finding it :)
