### ISSUE TITLE
Test failures on ppc64le

### ISSUE THREAD

**Issue by sumitd2** [neo4j/neo4j#13089]
- Neo4j version: 5.5.0
- Operating system: Ubuntu 22.04
- API/Driver: Java 17
- **Steps to reproduce**
1. Build neo4j on ppc64le
- Expected behavior
- The build and tests pass.
- Actual behavior
Build is successful but tests are failing.

Hi Team,
We are trying to build and test neo4j on IBM ppc64le processor architecture and observing some test failures, indicating it may not be supported. Upon analysing the failed tests we found that the page size in the neo4j code has been hardcoded to 8K at some places. The system page size on ppc64le is 65K. We even tried to fix the test failures by patching the code, but that results in some more failures in other sub-projects even if it fixes the original ones. Can you consider fixing the code so it is platform independent?
Thank you.
cc: @sethp

**Comment by PetrJanouch** [comment]
Hi @sumitd2 ,
as you have correctly guessed we don't support ppc64. We generally develop and test only for the platforms listed here https://neo4j.com/docs/operations-manual/current/installation/requirements/#deployment-requirements-platforms .
We have recently introduced support for ARM and the quality assurance part of the project was considerable amount of work, so I am pretty sure there are no plans to support additional architectures like ppc64 in the near future.
The hardcoded 8K pages are pieces of memory used for caching. In database terminology, they are usually called buffer cache pages. The have nothing to do with OS or processor pages. For instance, Postgresql uses 8k and Mysql 16k. I expect the problems are in other places that the 8k buffer cache page.

**Comment by sumitd2** [comment]
@PetrJanouch Four tests are failing for us (will have to confirm their names):

```
countNotModifiedPagesPerChunkWithNoBuffers()
countFlushesPerChunkWithNoBuffers()
countMergesPerChunkWithNoBuffers()
countUsedBuffersPerChunkWithNoBuffers()

```
They are all failing because the offset being used in inside flushAndForce() is 8192. If its changed to 65536, they pass.

**Comment by PetrJanouch** [comment]
@sumitd2 Ok. I will check if there is something platform-specific about those tests

**Comment by PetrJanouch** [comment]
@sumitd2 could you point me to (ideally a GitHub link to the source) what offset hardcoded to 8192 do you mean?

**Comment by sumitd2** [comment]
@PetrJanouch 

https://github.com/neo4j/neo4j/blob/5ad4387ed521f169a737f9836402dbac8759a9fc/community/community-it/community-it/src/test/java/org/neo4j/io/pagecache/impl/muninn/MuninnPageCacheTest.java#L950

https://github.com/neo4j/neo4j/blob/5ad4387ed521f169a737f9836402dbac8759a9fc/community/io/src/main/java/org/neo4j/io/pagecache/impl/muninn/MuninnPagedFile.java#L590

I changed filePageSize to 65536 only inside this function, and the failing tests passed. Didn't run the entire suite.

**Comment by PetrJanouch** [comment]
@sumitd2 OK, so there is nothing really hardcoded in MuninnPagedFile, is there?
What the test https://github.com/neo4j/neo4j/blob/5ad4387ed521f169a737f9836402dbac8759a9fc/community/community-it/community-it/src/test/java/org/neo4j/io/pagecache/impl/muninn/MuninnPageCacheTest.java#L950
does is just adding a file to the page cache and telling it to use 8K logical pages to do caching and IO. This is processor architecture independent thing. As I wrote above it is the same concept as Postgresql using 8k and Mysql 16k for the same purpose.
I think there is another issue and the test passing with 64K is just a coincidence.

**Comment by PetrJanouch** [comment]
Maybe there is really something ppc64 incompatible in the page cache, but changing the test to use 64K for caching will most likely be just masking the problem. And since all our deployments use 8K pages, we prefer keeping 8k in our tests.

**Comment by sumitd2** [comment]
@PetrJanouch Thanks. The check that actually fails is (the equality)

https://github.com/neo4j/neo4j/blob/5ad4387ed521f169a737f9836402dbac8759a9fc/community/io/src/main/java/org/neo4j/io/pagecache/impl/muninn/MuninnPagedFile.java#L577

So there are two lines where the problem could be:

https://github.com/neo4j/neo4j/blob/5ad4387ed521f169a737f9836402dbac8759a9fc/community/io/src/main/java/org/neo4j/io/pagecache/impl/muninn/MuninnPagedFile.java#L561
https://github.com/neo4j/neo4j/blob/5ad4387ed521f169a737f9836402dbac8759a9fc/community/io/src/main/java/org/neo4j/io/pagecache/impl/muninn/MuninnPagedFile.java#L590

May be that will give you a clue.

**Comment by sumitd2** [comment]
Hi @PetrJanouch, this patch has worked for us, all tests passing on x86_64 and ppc64le. If you confirm its correct, we can raise a PR:
```
diff --git a/community/io/src/main/java/org/neo4j/io/pagecache/impl/muninn/PageList.java b/community/io/src/main/java/org/neo4j/io/pagecache/impl/muninn/PageList.java
index 2b6bec387fa..777af76842e 100644
--- a/community/io/src/main/java/org/neo4j/io/pagecache/impl/muninn/PageList.java
+++ b/community/io/src/main/java/org/neo4j/io/pagecache/impl/muninn/PageList.java
@@ -273,7 +273,11 @@ class PageList implements PageReferenceTranslator {
     long initBuffer(long pageRef) {
         var address = getAddress(pageRef);
         if (address == 0L) {
-            address = memoryAllocator.allocateAligned(getCachePageSize(), bufferAlignment);
+            if (bufferAlignment == UnsafeUtil.pageSize()) {
+                address = memoryAllocator.allocateAligned(getCachePageSize(), getCachePageSize());
+            } else {
+                address = memoryAllocator.allocateAligned(getCachePageSize(), bufferAlignment);
+            }
             UnsafeUtil.putLong(offAddress(pageRef), address);
         }
         return address;

```
cc: @sethp

**Comment by mnd999** [comment]
Reopening this, since it is still being discussed.

**Comment by klaren** [comment]
@sumitd2 This issue is already patched and will be part of the Neo4j 5.9 release next month. The patch will cap the alignment to 8K, basically 

```
address = memoryAllocator.allocateAligned(getCachePageSize(), Math.min(getCachePageSize(), bufferAlignment));
```

This is not enough to support larger page sizes completely though. There are some other issues regarding page size >8K that are also addressed by the same patch.

Fortunately for you, ARM also supports 64K TLB entries :)

**Comment by klaren** [comment]
@sumitd2 Have you been able to give 5.9+ a try to verify it solves the problem?

**Comment by sumitd2** [comment]
@klaren yes we have, it did solve the problem. Thanks.
