### ISSUE TITLE
Unexpected SyntaxError: Concatenating Empty List causes Type Change

### ISSUE THREAD

**Issue by CelineWuest** [neo4j/neo4j#13093]
When running the following query against an empty database:

```cypher
UNWIND [0]+[] AS i RETURN toBoolean(i)
```

I encountered the following error:
```
Type mismatch: expected Boolean, Integer or String but was Float (line 1, column 37 (offset: 36))
"UNWIND [0]+[] AS i RETURN toBoolean(i)"
                                     ^
```

I believe the query mentioned above is semantically and syntactically correct and thus no error should be thrown here.
Additionally, alternatives that evaluate to the same query don't throw an error, like for example:
`UNWIND [0] AS i RETURN toBoolean(i)` or
`UNWIND []+[0] AS i RETURN toBoolean(i)` or
`RETURN toBoolean(0)`

I encountered this issue when testing queries against the **Neo4j 5.5.0 community version** in a Docker container running **alpine v.3**.

### Steps to reproduce
Run the following query and observe it throws an error:
```cypher
UNWIND [0]+[] AS i RETURN toBoolean(i)
```

### Expected behavior
The query should run successfully

### Actual behavior
The query fails with the error message `Type mismatch: expected Boolean, Integer or String but was Float...`

**Comment by HannesSandberg** [comment]
Thanks! We will look into this and come back to you.

**Comment by CelineWuest** [comment]
I saw you mentioned this issue in the latest changelog!
Is it fair to assume the underlying issue is fully fixed and the issue can be closed? :)

**Comment by Lojjs** [comment]
@DominicWuest Good catch, we have fixed this issue in November but missed to close this issue
