### ISSUE TITLE
Exception RelationshipTypeAccessFailed: Relationship type id '-1' not found

### ISSUE THREAD

**Issue by CelineWuest** [neo4j/neo4j#13094]
When running the following query against an empty database:
```cypher
CREATE ()-[m:A]->(), ({t:type(m)})
```

I encountered the following error:
```
Relationship type id '-1' not found
```

I believe the query mentioned above is semantically and syntactically correct and thus no error should be thrown here.

I encountered this issue when testing queries against the **Neo4j 5.5.0 community version** in a Docker container running **alpine v.3**. Queries were sent to the bolt endpoint via the neo4j-go-driver.

However, in the Neo4j Sandbox, on the blank project, this error does not occur, even though the Neo4j versions matched.

### Steps to reproduce
<details>

<summary>Setting up the environment</summary>

Following are the commands in the Dockerfile that set up the environment.
The Dockerfile itself extends `eclipse-temurin:17-jdk-alpine`
```bash
# Download neo4j-community-5.5.0
curl -o neo4j.tar.gz https://dist.neo4j.org/neo4j-community-5.5.0-unix.tar.gz
tar -xzf neo4j.tar.gz
rm neo4j.tar.gz
cd neo4j-community-5.5.0

# Activate apoc
mv labs/apoc-5.5.0-core.jar plugins/apoc-5.5.0-core.jar

# Edit the config
sed -i "s/#dbms.security.auth_enabled=false/dbms.security.auth_enabled=false/g" conf/neo4j.conf
sed -i "s/#server.default_listen_address=0.0.0.0/server.default_listen_address=0.0.0.0/g" conf/neo4j.conf
sed -i "s/server.http.enabled=true/server.http.enabled=false/g" conf/neo4j.conf
sed -i "s/server.http.enabled=true/server.http.enabled=false/g" conf/neo4j.conf
echo "dbms.cypher.lenient_create_relationship = true" >> conf/neo4j.conf

# Run the server
bin/neo4j console
```

</details>

Run the following query and observe it throws an error:
```cypher
CREATE ()-[m:A]->(), ({t:type(m)})
```

### Expected behavior
The query should run successfully

### Actual behavior
The query fails with the error message `Neo4jError: Neo.DatabaseError.Schema.RelationshipTypeAccessFailed (Relationship type id '-1' not found)`

**Comment by AzuObs** [comment]
Hi Dominic,

Thank you very much for your report. As far as I could reproduce, this has little to do with your customised neo4j.conf file and is still a bug in 5.6.0. The bug is happening in community, but not in enterprise.

I have submitted a report to the appropriate team ([private tracker](https://trello.com/c/70mQPISb)).

Warm thanks,

**Comment by pontusmelke** [comment]
Hi @DominicWuest 

We have identified and fixed the problem. A fix will be shipped with the next version of Neo4j server, probably 5.8.

Thanks again for reporting!

Best Regards,
Pontus
