### ISSUE TITLE
[5.6.0] Failed to execute query in transaction

### ISSUE THREAD

**Issue by CelineWuest** [neo4j/neo4j#13099]
When running the following query:
```cypher
CALL { WITH [COUNT { () }] AS n0 RETURN 0 AS n1 } RETURN 0 AS n2
```

I encountered the following error:
```
Neo4jError: Neo.DatabaseError.General.UnknownError (Failed to execute query in transaction "bolt-100")
```

I believe the query mentioned above is semantically and syntactically correct and thus no error should be thrown here.

I encountered this issue when testing queries against the **Neo4j 5.6.0 community version** in a Docker container running **alpine v.3**.
On Neo4j 5.5.0, this query runs successfully and no exception is raised.

### Steps to reproduce
Run the following query and observe it throws an error:
```cypher
CALL { WITH [COUNT { () }] AS n0 RETURN 0 AS n1 } RETURN 0 AS n2
```

### Expected behavior
The query should run successfully

### Actual behavior
The query fails with the error message `Neo4jError: Neo.DatabaseError.General.UnknownError (Failed to execute query in transaction "bolt-100")`

**Comment by HannesSandberg** [comment]
Thanks! We will look into this.

**Comment by arnefischereit** [comment]
Hi @DominicWuest,

Thanks for reporting the issue. We have implemented a fix for it which will be part of the next release, 5.9.

I am closing this issue, should the problem persist (after the release of 5.9) or reappear please reopen this issue or open a new one.

Regards,  

Arne
