### ISSUE TITLE
Unknown expression type during transformation (class ExistsIRExpression)

### ISSUE THREAD

**Issue by CelineWuest** [neo4j/neo4j#13098]
When running the following query:
```cypher
SET (CASE WHEN EXISTS { MATCH () } THEN null END).a = false
```

I encountered the following error:
```
Neo4jError: Neo.DatabaseError.Statement.ExecutionFailed (Unknown expression type during transformation (class org.neo4j.cypher.internal.ir.ast.ExistsIRExpression))
```

I believe the query mentioned above is semantically and syntactically correct and thus no error should be thrown here.

I encountered this issue when testing queries against the **Neo4j 5.6.0 community version** in a Docker container running **alpine v.3**.

### Steps to reproduce
Run the following queries and observe it throws an error:
```cypher
SET (CASE WHEN EXISTS { MATCH () } THEN null END).a = false
```

### Expected behavior
The query should run successfully

### Actual behavior
The query fails with the error message `Neo4jError: Neo.DatabaseError.Statement.ExecutionFailed (Unknown expression type during transformation (class org.neo4j.cypher.internal.ir.ast.ExistsIRExpression))`

**Comment by HannesSandberg** [comment]
Thank you! We will investigate this.

**Comment by arnefischereit** [comment]
Hi @DominicWuest,

Thanks for reporting the issue. We have implemented a fix for it which will be part of the next release, probably 5.11.

I am closing this issue, should the problem persist (after the release of 5.11) or reappear please reopen this issue or open a new one.

Regards,  

Arne
