### ISSUE TITLE
support multiple packages for one unmanaged extension

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#131]
@sarmbruster: 'In neo4j-server.properties it is possible to mount one java package to a extension point url. If the unmanged extensions use multiple package, the only option is to register each package to a separate extension point url. Each extension point url means a seperate Jersey container is used and therefore reusing Injectables accross container boundaries and therefore over package name boundaries is not possible.
What I'd like to see is that I can register multiple packages for a single extension point, e.g.

```
org.neo4j.server.thirdparty_jaxrs_classes=my.package1:my.package2=/extension1, my.package3:my.package4=/extension2
```

My seperating multiple packages using e.g. ":" this approach would maintain backwards compatibility.'

**Comment by technige** [comment]
Closing as unlikely to still be relevant.
