### ISSUE TITLE
Neo.DatabaseError.General.UnknownError

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13108]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.5.0 Enterprise
operating system: windows 10
API：Cypher version 9
query: create (n{age:1}),({k:properties(n{.age})}) return 1
error message:
**Neo.DatabaseError.General.UnknownError 
key not found: age**

But if I execute query:create (n{age:1}) return properties(n{.age}) or query:create (n{age:1}),({k:n.age}) return 1,then they can run successfully.
I'm confused why the key "age" can not be found in the first query.

**Comment by Lojjs** [comment]
@ljhhuxiaoba This sounds like a bug. We will investigate further and come back to you.

Best regards Louise, Neo4j Cypher

**Comment by InverseFalcon** [comment]
While buggy, some things are being done wrong in the query.

I don't believe we support maps as properties, but you are attempting to set a property `k` to a map, which won't work whether it's from the `properties()` output or the map projection.

**Comment by ljhhuxiaoba** [comment]
Thanks.There are some errors in the attribute types, but I think it should throw a syntax error instead of age not found.

**Comment by arnefischereit** [comment]
Hi @ljhhuxiaoba,

Thanks again for testing our product so thoroughly and reporting this issue. We have implemented a fix for it which will be part of the next release, 5.11.

I am closing this issue, should the problem persist (after the release of 5.11) or reappear please reopen this issue or open a new one.

Regards,

Arne
