### ISSUE TITLE
Unexpected SyntaxError: Variable shadowing in `EXISTS`

### ISSUE THREAD

**Issue by CelineWuest** [neo4j/neo4j#13109]
When running the following query:
```cypher
MATCH (x)-->({n0:EXISTS { WITH toBoolean(sum(0)) AS n1, x AS n2 RETURN 0 }}) RETURN 0
```
​
I encountered the following error:
```
Neo.ClientError.Statement.SyntaxError (The variable `x` is shadowing a variable with the same name from the outer scope and needs to be renamed (line 1, column 8 (offset: 7))
"MATCH (x)-->({n0:EXISTS { WITH toBoolean(sum(0)) AS n1, x AS n2 RETURN 0 }}) RETURN 0"
        ^) produced when running query MATCH (x)-->({n0:EXISTS { WITH toBoolean(sum(0)) AS n1, x AS n2 RETURN 0 }}) RETURN 0
```
​
I believe the query mentioned above is semantically and syntactically correct and thus no error should be thrown here.
Additionally, alternatives that evaluate to the same query don't throw an error, like for example:
`MATCH (x)-->({n0:EXISTS { WITH toBoolean(0) AS n1, x AS n2 RETURN 0 }}) RETURN 0`
​
I encountered this issue when testing queries against the **Neo4j 5.6.0 community version** in a Docker container running **alpine v.3**.
​
### Steps to reproduce
Run the following query and observe it throws an error:
```cypher
MATCH (x)-->({n0:EXISTS { WITH toBoolean(sum(0)) AS n1, x AS n2 RETURN 0 }}) RETURN 0
```
​
### Expected behavior
The query should run successfully
​
### Actual behavior
The query fails with the error message ``Neo.ClientError.Statement.SyntaxError (The variable `x` is shadowing a variable with the same name from the outer scope..``

**Comment by Lojjs** [comment]
@DominicWuest Thanks for reporting. This was a bug. It has now been fixed and will start working as expected from Neo4j 5.8.
