### ISSUE TITLE
Tried to alias non-existing slot 'm' with alias 'x'

### ISSUE THREAD

**Issue by CelineWuest** [neo4j/neo4j#13100]
When running the following query:
```cypher
CREATE ()-[m:X]->(), ({n1:EXISTS { RETURN m AS x } })
```

I encountered the following error:
```
Neo4jError: Neo.DatabaseError.Statement.ExecutionFailed (Tried to alias non-existing slot 'm'  with alias 'x')
```

I believe the query mentioned above is semantically and syntactically correct and thus no error should be thrown here.

I encountered this issue when testing queries against the **Neo4j 5.6.0 community version** in a Docker container running **alpine v.3**.

### Steps to reproduce
Run the following query and observe it throws an error:
```cypher
CREATE ()-[m:X]->(), ({n1:EXISTS { RETURN m AS x } })
```

### Expected behavior
The query should run successfully

### Actual behavior
The query fails with the error message `Neo4jError: Neo.DatabaseError.Statement.ExecutionFailed (Tried to alias non-existing slot 'm'  with alias 'x')`

**Comment by HannesSandberg** [comment]
Thanks you! We will investigate this.

**Comment by arnefischereit** [comment]
Hi @DominicWuest,

Thank you for your report and the thorough testing.

The query `CREATE ()-[m:X]->(), ({n1:EXISTS { RETURN m AS x } })` that you used contains a cross-reference (to define the second pattern, we need to evaluate `m` from the first pattern).

Such a cross-reference is ill-defined in that its result is non-deterministic: Should we evaluate the first or the second first? What about circular dependencies?

We have detailed such [in the documentation](https://neo4j.com/docs/cypher-manual/current/clauses/create/#reusing-variables-properties) and decided to forbid cross-references in `CREATE` in the next major version of Neo4j and therefore [deprecated them](https://neo4j.com/docs/cypher-manual/5/deprecations-additions-removals-compatibility/#_deprecated_features) in the current versions.

We also investigated issuing a better error message. But we found no way for this without restricting use-cases which currently work. To not break currently working use-cases, we will therefore leave the product as is.

I hope that clarifies the current behaviour. I will close the issue but if you disagree, please feel free to comment and/or open a new issue on this.

Again, thanks for reporting the issue.

Regards,

Arne
