### ISSUE TITLE
[5.6.0] Variable not defined in `RETURN` alias

### ISSUE THREAD

**Issue by CelineWuest** [neo4j/neo4j#13102]
When running the following query:
```cypher
RETURN EXISTS { WITH 0 AS n0 MATCH ({n1:COUNT { RETURN 0 AS x } }) }
```

I encountered the following error:
```
Neo4jError: Neo.ClientError.Statement.SyntaxError (Variable `x` not defined (line 1, column 61 (offset: 60))
"RETURN EXISTS { WITH 0 AS n0 MATCH ({n1:COUNT { RETURN 0 AS x } }) }"
                                                             ^)
```

I believe the query mentioned above is semantically and syntactically correct and thus no error should be thrown here.

I encountered this issue when testing queries against the **Neo4j 5.6.0 community version** in a Docker container running **alpine v.3**.
On Neo4j 5.5.0, this query runs successfully and no exception is raised.

### Steps to reproduce
Run the following query and observe it throws an error:
```cypher
RETURN EXISTS { WITH 0 AS n0 MATCH ({n1:COUNT { RETURN 0 AS x } }) }
```

### Expected behavior
The query should run successfully

### Actual behavior
Neo4j 5.5.0: The query runs successfully and no exception is raised
Neo4j 5.6.0: The query fails with the error message ``Neo4jError: Neo.ClientError.Statement.SyntaxError (Variable `x` not defined...``

**Comment by HannesSandberg** [comment]
Thanks! We will investigate.

**Comment by gem-neo4j** [comment]
Thanks for reporting, this has now been fixed and will be released in the next release. 5.11 :)
