### ISSUE TITLE
Unexpected Error about maxint

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13104]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.6.0 Enterprise
operating system: windows 10
API：Cypher version 9
query: CREATE (n0:L1{k3:substring("a", 2, 2147483647)})
error message:Ignored either because of an error or RESET
If I replace the "2147483647" with any other smaller positive integer,then the query can run successfully.

**Comment by Lojjs** [comment]
@ljhhuxiaoba Thanks for reporting, this indeed seems to be a bug. We will investigate and come back to you.

Best regards Louise, Neo4j Cypher team

**Comment by JonasHolgersson** [comment]
@ljhhuxiaoba Thanks again for reporting, this has been fixed and should be included in the 5.8 release.
