### ISSUE TITLE
 Unexpected Error about Scope of variable

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13106]
I execute two queries on my neo4j database ,and two error occurs.

Neo4j version: 5.5.0 Enterprise
operating system: windows 10
API：Cypher version 9
query: with count{with 1 as a} as b match (a) return 1
error message:The variable `a` is shadowing a variable with the same name from the outer scope and needs to be renamed
The above error seems to indicate that the variable a defined in the count clause is visible in match clause so that the variable a defined in match clause conflicts with the variable a defined in count clause.
But if I execute another query:with count{with 1 as a} as b with a as c match (a) return 1,then another error occurs:Variable `a` not defined.
So I doubt that the variable a defined in count clause is visible until the match statement and why I can't use variable a in match clause.

**Comment by Lojjs** [comment]
@ljhhuxiaoba Thanks for reporting. The first case is a bug. Variables from the outside scope, defined before the COUNT clause, should be visible inside the COUNT clause . Therefore a query like

```
MATCH (a)
WITH COUNT {WITH 1 AS a}
...
```

should throw the shadowing error for `WITH 1 AS a`.

What is happening here though is actually that the shadowing error is thrown for `WITH 1 AS a`, despite the MATCH clause being after it. So the subclause accidentally sees variables that are not defined yet. We will make a fix for this.

Regarding the second case `with count{with 1 as a} as b with a as c match (a) return 1`, you are correct that the outer scope cannot see variables from inside the COUNT clause, so here the error 'Variable `a` not defined' is correct.

Best regards Louise, Neo4j Cypher team

**Comment by ljhhuxiaoba** [comment]
Thanks a lot for your explanation!

**Comment by Lojjs** [comment]
@ljhhuxiaoba We have changed the shadowing rules so that  this case will be allowed from Neo4j 5.8.
