### ISSUE TITLE
Unexpected Error about MaxInt in round() with precision

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13117]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.6.0 Enterprise
operating system: windows 10
API：Cypher version 9
query: return round(1.2,2147483647)
error message:
Neo.DatabaseError.Statement.ExecutionFailed
BigInteger would overflow supported range

But if I execute query such as:return round(1.2,2147483646) or return round(1.2,2147483645),the same error will happen again.

**Expected behavior**:
The query should run successfully and return 1.2 as result.

**Actual behavior**:
The query failed.

**Comment by AzuObs** [comment]
Hi @ljhhuxiaoba 

Thank you for reporting the error. I have submitted the issue to the appropriate team ([private tracker](https://trello.com/c/haRqjIeh)) for them to investigate.

**Comment by pontusmelke** [comment]
@ljhhuxiaoba Thanks for reporting this. We have fixed the issue and it will be rolled out with the next upcoming release.

Best regards, 
Pontus
