### ISSUE TITLE
Neo4j 5.5.: drastic change of execution plan depending on return limit

### ISSUE THREAD

**Issue by zoowirt** [neo4j/neo4j#13112]
## Issue report
On advice from a more experienced user, I post part of the following StackOverflow question here as an issue:
[https://stackoverflow.com/questions/75912251/neo4j-change-of-execution-plan-in-dependence-on-return-limit](https://stackoverflow.com/questions/75912251/neo4j-change-of-execution-plan-in-dependence-on-return-limit)

**Neo4j Version:** 5.5
**Operating System:** Ubuntu 20.04.4
**API:** Docker

In our neo4j version 5.5 database, we have data` (c1:Company)-[:ADDRESS_MATCH]-(c2:company)` as well as `(t:CompanyNameToken)-[:CONTAINS_TOKEN]-(c:Company)`. Our goal is to find companies with address match and a common token. The execution plan changes unexpectedly when increasing the return limit from 100 to 300.

Matching only the addresses is quick and results in the following execution plan, with 1645 DB hits in 14ms.
```
PROFILE MATCH (c1:Company)-[:ADDRESS_MATCH]->(c2:Company)
RETURN c1, c2 LIMIT 100
```
![image](https://user-images.githubusercontent.com/57291347/230011742-ddce7fa1-aacf-4093-baa4-f2e5522228e5.png)

The execution plan here stays the same when increasing the limit of 100 or removing the limit. Now adding the token match as a condition, for LIMIT 100 the execution plan still has only one branch, with 250.000 DB hits in 58ms.

```
PROFILE MATCH (c1:Company)-[:ADDRESS_MATCH]->(c2:Company),
(c1)<-[r1:CONTAINS_TOKEN]-(t:CompanyNameToken)-[r2:CONTAINS_TOKEN]->(c2)
RETURN c1, c2 LIMIT 100
```
![image](https://user-images.githubusercontent.com/57291347/230011935-e9436aea-88b2-4d23-8942-ea2ee6b494d8.png)

However, when executing the same query with` LIMIT 300` instead of `LIMIT 100`, the execution plan involves multiple branches (cartesian product on c1, c2) and suddenly has 38 Million DB hits in much longer 12000ms. (The transition is somewhere between 200 and 300).

```
PROFILE MATCH (c1:Company)-[:ADDRESS_MATCH]->(c2:Company),
(c1)<-[r1:CONTAINS_TOKEN]-(t:CompanyNameToken)-[r2:CONTAINS_TOKEN]->(c2)
return c1, c2 limit 300
```
![image](https://user-images.githubusercontent.com/57291347/230012121-09fac665-d894-4abd-9023-2acdc6017900.png)

A reformulation of the above query with the exists keyword does not show this behavior. The execution plan stays the same, independent of the limit, or even without the limit. For LIMIT 300, it has 600.000 DB hits in only 190ms.

```
PROFILE MATCH (c1:Company)-[:ADDRESS_MATCH]->(c2:Company)
WHERE EXISTS {(c1)<-[r1:CONTAINS_TOKEN]-(t:CompanyNameToken)-[r2:CONTAINS_TOKEN]->(c2)}
RETURN c1, c2
```

### Expected behavior
I would expect the execution plan to be independent of the limit increase. At least, it should not change that drastically from an efficient plan to a hopelessly naive one.

### Actual behavior
The execution plan changes as described. I tried various planner hints and their combinations with no success. Confusingly, some days before, this behavior did not show up, with almost the same data. I read that execution plans depend on the DB statistics. However, commands like CALL db.clearQueryCaches() or CALL db.prepareForReplanning() also did not change the behavior.

**Comment by Lojjs** [comment]
@zoowirt Thanks for the issue, I will let our planner team have a look and report back to you.

Best regards Louise, Neo4j Cypher team

**Comment by sherfert** [comment]
Hi @zoowirt . Could you give us access to the graph statistics of your database? We would need that to reproduce and investigate the behavior.

You can do that by running `CALL db.stats.retrieve("GRAPH COUNTS")` and attaching the output here (preferrably as a `.json`).

Without that, I can already now tell you that it is expected for the planner to take a `LIMIT` into account when deciding on the best plan, and depending on that `LIMIT` the plan can change. This in itself is not a problem and very useful for many queries. For your particular query, however, it seems that the planner makes a bad decision when the `LIMIT` is too high (or absent).

**Comment by sherfert** [comment]
If you still need help, please reopen the issue with the requested information.
