### ISSUE TITLE
COLLECT subquery failed in Neo4j version: 5.5.0 Enterprise

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13114]
operating system: windows 10
API：Cypher Manual 5 
query: return COLLECT{return 1}
error message:
Neo.ClientError.Statement.SyntaxError
Invalid input '1': expected "," or "}" (line 1, column 23 (offset: 22))
"return COLLECT{return 1}"

Expected behavior:
return [1] as result 

I wonder if COLLECT subquery is not supported in Neo4j version: 5.5.0 Enterprise

**Comment by InverseFalcon** [comment]
This does seem a little buggy. It looks as though `collect{}` subqueries need to start with a pattern or a match.

That said, when there is no pattern to consider, then you wouldn't use a subquery at all, you would just use the `collect()` aggregation function:

```
RETURN collect(1)
```

And if no aggregation is desired, then just use the list literal: `RETURN [1]`

As such there is no loss of functionality here, it's encouraged to use the right tool for the job, and when no patterns need to be matched on, a collect{} is the wrong tool to use.

**Comment by CelineWuest** [comment]
I think this is happening because the `COLLECT` subquery got introduced in [5.6.0](https://github.com/neo4j/neo4j/wiki/Neo4j-5-changelog#560), it wasn't a feature in 5.5.0.

**Comment by ljhhuxiaoba** [comment]
Thanks for your explanation.
