### ISSUE TITLE
Incorrect aggregate result

### ISSUE THREAD

**Issue by kikimo** [neo4j/neo4j#13116]
Neo4j version: neo4j-community-4.4.14

Look at the queries below:

```txt
MATCH
    (v{none_exist_prop: true})
WITH
    (((+80) * ((-49) + 90)) - (-((+22) - (76 * 59)))) AS ri0, (+(+86)) AS ri1, (+82) AS ri2
return
    COUNT((-(+((+ri1) - (ri2 / ri2))))) AS ai0, MAX((ri1 + (((ri0 + ri0) * (ri1 + ri0)) + (+(ri0 * ri1))))) AS ai1

╒═════╤═════╕
│"ai0"│"ai1"│
╞═════╪═════╡
│0    │null │
└─────┴─────┘

MATCH
    (v{none_exist_prop: true})
WITH
    (((+80) * ((-49) + 90)) - (-((+22) - (76 * 59)))) AS ri0, (+(+86)) AS ri1, (+82) AS ri2
return
    COUNT((-(+((+ri1) - (ri2 / ri2))))) AS ai0, MAX((ri1 + (((ri0 + ri0) * (ri1 + ri0)) + (+(ri0 * ri1))))) AS ai1, "abc"

(no changes, no records)
```

The first query return one row in the aggregation and that's expected, but the second query return nothing if adding a groupping key "abc"  whild we think it should no impact the aggregation result.

**Comment by InverseFalcon** [comment]
This is actually correct behavior, since aggregations on zero input rows can only work in the absence of a grouping key.

https://support.neo4j.com/hc/en-us/articles/360053739293-Understanding-aggregations-on-zero-rows

**Comment by AzuObs** [comment]
Hi Kikimo,

Thank you for reporting this issue. I agree with Andrew that this is the correct behaviour. Hopefully the article that he links has been able to shed some light into why aggregation works differently when there is or isn't a grouping key. 

Please let me know whether you have any further questions.

Warm thanks,

**Comment by Lojjs** [comment]
@kikimo As you have gotten answers above, I will close this issue. Feel free to reopen it if there is still a problem.

Best regards Louise, Neo4j Cypher team
