### ISSUE TITLE
UnknownError about path in list

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13111]
I execute a query on my neo4j database ,and an error occurs.

query: return [p=(:L)-[:T]->() where exists{return p} |p]
Neo4j version: 5.7.0 Enterprise
operating system: windows 10
API：Cypher version 9

error message:
Neo.DatabaseError.General.UnknownError
class org.neo4j.cypher.internal.expressions.PathExpression cannot be cast to class org.neo4j.cypher.internal.expressions.LogicalVariable (org.neo4j.cypher.internal.expressions.PathExpression and org.neo4j.cypher.internal.expressions.LogicalVariable are in unnamed module of loader 'app')

Expected behavior:
The query should run successfully and return all the paths like (:L)-[:T]->() as a list

Actual behavior:
The query failed.

Steps to reproduce:
create (:L)-[:T]->();
return [p=(:L)-[:T]->() where exists{return p} |p];

**Comment by Lojjs** [comment]
@ljhhuxiaoba I think this should be supported yes. At least it should not give such an internal and cryptic error. We will take a deeper look and come back to you.

Best regards Louise Neo4j Cypher team

**Comment by gem-neo4j** [comment]
This has now been fixed and will be released in 5.13 :) thanks for reporting!
