### ISSUE TITLE
List concatenation failed in reduce()

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13113]
I execute a query on my neo4j database ,and an error occurs.

query: return reduce(a=[1],b in [["a"]]|a+b)
Neo4j version: 5.5.0 Enterprise
operating system: windows 10
API：Cypher version 9
error message:
Neo.ClientError.Statement.SyntaxError
Type mismatch: accumulator is List<Integer> but expression has type List<Any>

If I execute query:return [1]+["a"],then the query can run successfully and return [1,"a"] as result.I think list of elements of different types should be concatenated successfully in reduce() too.

Expected behavior:
The query should run successfully and return [1,"a"]

Actual behavior:
The query failed.

Steps to reproduce:
return reduce(a=[1],b in [["a"]]|a+b);

**Comment by InverseFalcon** [comment]
This does look like a bug, but a bug related to lists of differing types, we're trying to combine a list of numerics and a list of strings, which doesn't seem to be working when it should.

If you change the accumulator list to `["1"]` then it works, if you change the other list to `[[2]]` then it works.

If we start with an accumulator list of mixed types, like `[1, "b"]` then it also works.

**Comment by Lojjs** [comment]
@ljhhuxiaoba Thanks for reporting. We will investigate and come back to you.

Best regards Louise, Neo4j Cypher

**Comment by Lojjs** [comment]
@ljhhuxiaoba This was a bug in our type checking of reduce. It has know been fixed and the fix will be included in the upcoming Neo4j 5.16 and 4.4.29 releases.
