### ISSUE TITLE
Unexpected ExecutionFailed Error

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13124]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.6.0 Enterprise
operating system: windows 10
API：Cypher version 9
query: match (n) match({k:count{with n return 1}}) return n
error message:
Neo.DatabaseError.Statement.ExecutionFailed
Unknown expression type during transformation (class org.neo4j.cypher.internal.ir.ast.CountIRExpression)

If I replace the count subquery with exists subquery,then the same error will happen.

Expected behavior:
The query should run successfully and no error will happen.

Actual behavior:
The query failed.

**Comment by AzuObs** [comment]
Hi @ljhhuxiaoba ,

Thank you for reporting this issue, I have submitted it to the appropriate team ([private](https://trello.com/c/EoeFbI8Y)). Please let us know if you would like to share with us how you are finding these bugs. Maybe you are working on an exciting project of some kind?

Warm thanks,

**Comment by ljhhuxiaoba** [comment]
I haven't finished my work yet, so I can't share it for the time being. I'm really sorry.

**Comment by AzuObs** [comment]
No problem 😄 

If at any point you would like to show us or even present it to us then please get in touch with anyone from the company by creating a GitHub issue or just contacting us directly on GitHub or LinkedIn. 

daniel.leaver@neo4j.com

**Comment by inmost-light** [comment]
@ljhhuxiaoba 
Thank you for reporting. A fix has been implemented and should be included in 5.9.0.
