### ISSUE TITLE
ExecutionFailed: Arraycopy Index out of Bounds

### ISSUE THREAD

**Issue by CelineWuest** [neo4j/neo4j#13129]
When running the following query:
```cypher
WITH [] AS n0 ORDER BY null CALL { WITH [] AS n1 ORDER BY null UNWIND [0] AS x UNWIND [x] AS n2 RETURN 0 AS n3 } FOREACH ( n4 IN null | MERGE () )
```

I encountered the following error:
```
Neo4jError: Neo.DatabaseError.Statement.ExecutionFailed (arraycopy: last destination index 7 out of bounds for object array[6])
```

I believe the query mentioned above is semantically and syntactically correct and thus no error should be thrown here.

I encountered this issue when testing queries against the **neo4j:5.6.0** Docker container.

### Steps to reproduce
1.
	<details>
	
	<summary>Run the Docker Container</summary>
	
	```
	docker run \
	    -p 7474:7474 -p 7687:7687 \
	    --name neo4j-apoc \
	    -e apoc.export.file.enabled=true \
	    -e apoc.import.file.enabled=true \
	    -e apoc.import.file.use_neo4j_config=true \
	    -e NEO4J_PLUGINS=\[\"apoc\"\] \
	    -e NEO4J_AUTH=none
	    --rm \
	    neo4j:5.6.0
	```
	
	</details>

1. Navigate to the browser interface on [localhost:7474](http://localhost:7474)

1. Run the following query and observe it throws an error:
	```cypher
	WITH [] AS n0 ORDER BY null CALL { WITH [] AS n1 ORDER BY null UNWIND [0] AS x UNWIND [x] AS n2 RETURN 0 AS n3 } FOREACH ( n4 IN null | MERGE () )
	```

### Expected behavior
The query should run successfully.

### Actual behavior
The query fails with the error message `Neo4jError: Neo.DatabaseError.Statement.ExecutionFailed (arraycopy: last destination index 7 out of bounds for object array[6])`.

**Comment by AzuObs** [comment]
Hej Dominic,

Thank you for reporting this issue. This one may take some time to triage. I have submitted it to a team to begin taking a look ([private tracker](https://trello.com/c/KbFnyVPR/4466-github-issue)).

Warm thanks,

**Comment by pontusmelke** [comment]
Hi @DominicWuest, 
Thanks again for reporting. The issue should already be fixed, if you run the query again but use `neo4j:5.7.0` or `neo4j:latest` instead of `neo4j:5.6.0` it should be working as expected.

Best regards,
Pontus

**Comment by CelineWuest** [comment]
Hello @pontusmelke!
I hope I'm not bothering you, but would it be possible to get a quick explanation of what caused this bug?
