### ISSUE TITLE
UnknownError about call{}

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13134]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.6.0 Enterprise
operating system: windows 10
API：Cypher version 9
query: call{with exists{match()} as a return 1} return 1
error message:
Neo.DatabaseError.General.UnknownError
Failed to execute query in transaction "bolt-6387"

The same error also occurs when using count{}.

Expected behavior:
The query should run successfully and return 1.

Actual behavior:
The query failed.

**Comment by AzuObs** [comment]
Hi @ljhhuxiaoba 

Thank you for another useful report. I have submitted this to the appropriate team ([private link](https://trello.com/c/szAyDuW0)).

Warm thanks,

**Comment by arnefischereit** [comment]
Hi @ljhhuxiaoba,

Thanks for reporting the issue. We have implemented a fix for it which will be part of the next release, 5.9.

I am closing this issue, should the problem persist (after the release of 5.9) or reappear please reopen this issue or open a new one.

Regards,  

Arne
