### ISSUE TITLE
Summary counters differ when using native `MERGE` and `apoc.merge.node` in batched subquery

### ISSUE THREAD

**Issue by ClemDoum** [neo4j/neo4j#13139]
# Setup
- Neo4j version: 5.4.0
- Operating system: Docker
- API/Driver: Cypher using the web app

# Bug description

When performing a batch node merge, I'm getting differences in summary counters when using a `apoc.merge.node` or regular `MERGE`. When calling the APOC procedure, the number of created nodes is not reported.
I would expect the number of created nodes to be reported in the summary even if a procedure is called. I'm not sure if the problem is on the APOC side, the neo4j side or if I should call the procedure differently.

### Steps to reproduce
1. Define the `rows` parameter:
```
:param rows =>[{id: '0'}, {id: '1'}, {id: '2'}, {id: '3'}, {id: '4'}, {id: '5'}, {id: '6'}]
```

2. Run:
```
:auto
UNWIND $rows AS row
CALL {
    WITH row
    CALL apoc.merge.node(["Node"], {id: row.id}) yield node as node
} IN TRANSACTIONS OF 2 ROWS
```

3. Delete created nodes
```
MATCH n 
DELETE n
RETURN COUNT(n)
```

4. Run 
```
:auto
UNWIND $rows AS row
CALL {
    WITH row
    MERGE (Node{id: row.id})
} IN TRANSACTIONS OF 2 ROWS
```

### Expected behavior
2. -> `Created 7 nodes, set 7 properties`
3. -> `7`
4. -> `Created 7 nodes, set 7 properties`

### Actual behavior
2. -> `(no changes, no records)`
3. -> `7`
4. -> `Created 7 nodes, set 7 properties`

**Comment by AzuObs** [comment]
Hello Clement,

Thank you very much for reporting this issue. Unfortunately, this is an issue which the database team already knows about. Our internal procedure framework is not integrated with the response summary, and we have an internal ticket ([private link](https://trello.com/c/LMuu95bk)) to improve on this issue. This has so far not been prioritised over other work although there have been recent proposals to incorporate it into upcoming release cycles.

I have attached your issue to the internal ticket. I am very sorry that I was unable to provide a more potent remedy to your issue. Please let me know if you have any follow up questions, and I will happily try my best to answer them.

All the best,

**Comment by ClemDoum** [comment]
Thank you for your quick anwser and good to know it's a known issue. I was interested in the summary to get the count of create nodes, I think I can find a ways to compute this stats in another way. Thank you for your help !
Best,
Clément

**Comment by AzuObs** [comment]
My pleasure Clement, please let us know should you have any further questions.

**Comment by fickludd** [comment]
@AzuObs Is there somewhere public we can vote for fixing this issue? I was experiencing the same problem (but for `apoc.create.node` just now

**Comment by AzuObs** [comment]
Hi Johan,

Thank you for reporting the issue. I am sorry that you have also had a poor experience with this feature. 

Unfortunately, we do not have a public voting system. However, I have also attached your report to our internal tracker. The more reports we receive the more likely it is that the issue will get prioritised. 

Warm thanks,
