### ISSUE TITLE
Wrong result of log(0) and log10(0) 

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13132]
I execute a query on my neo4j database and get wrong result.

Neo4j version: 5.6.0 Enterprise
operating system: windows 10
API：Cypher version 9
query: return log(0),log10(0)

Expected behavior:
The result should be null according to the [docs.](https://neo4j.com/docs/cypher-manual/current/functions/mathematical-logarithmic/)

Actual behavior:
The result is -Infinity .

**Comment by AzuObs** [comment]
Hi @ljhhuxiaoba 

Thank you for reporting this issue. I have submitted it to the appropriate team ([private tracker](https://trello.com/c/KoW6aBNE)).

Warm thanks,

**Comment by gem-neo4j** [comment]
Hi! We analysed this and found the issue was in the documentation, we have updated the docs and the next docs release will update the appropriate areas, thank you :)
