### ISSUE TITLE
Unexpected variable shadowing about path variable

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13140]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.6.0 Enterprise
operating system: windows 10
API：Cypher version 9
query: merge p=(a)-[b:T]->(c) with * where exists{with p as n} return 1 
error message:
Neo.ClientError.Statement.SyntaxError
The variable `p` is shadowing a variable with the same name from the outer scope and needs to be renamed (line 1, column 7 (offset: 6))
"merge p=(a)-[b:T]->(c) with * where exists{with p as n} return 1"

But if I execute another query such as:merge p=(a)-[b:T]->(c) with * where exists{with b as n} return 1 ,then it will run successfully.And I think this inconsistency should not happen.

Steps to reproduce:
merge p=(a)-[b:T]->(c) with * where exists{with p as n} return 1;

Expected behavior:
The query should run successfully and return 1.

Actual behavior:
The query failed.

**Comment by AzuObs** [comment]
Hi @ljhhuxiaoba 

Thanks a lot for your report. I have created a card and assigned to the relevant team ([private](https://trello.com/c/yBBwdG5n)) for further investigation.

Hope you have a nice weekend,

**Comment by gem-neo4j** [comment]
Hi, this has now been fixed and should be released in the next release (5.11).
