### ISSUE TITLE
ExecutionFailed error about SymbolUse in reduce()

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13146]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.6.0 Enterprise
operating system: windows 10
API：Cypher version 9
query:with reduce(b=0,c in [0]|1) as n merge ()-[b:T]->()-[:T]->() return b
error message:
Neo.DatabaseError.Statement.ExecutionFailed
key not found: SymbolUse(b@43(511a2180))

But if I execute another query such as:with reduce(c=0,b in [0]|1) as n merge ()-[b:T]->()-[:T]->() return b,the same error will happen again.

Expected behavior:
The query should run successfully.

Actual behavior:
The query failed.

**Comment by InverseFalcon** [comment]
Looks like it may have the same bug as this issue:
https://github.com/neo4j/neo4j/issues/13143

If you change one of the relationship types in the MERGE pattern then it can run without error.

**Comment by loveleif** [comment]
Thanks a lot @ljhhuxiaoba! I've added this information to the existing ticket for https://github.com/neo4j/neo4j/issues/13143 in our internal bug tracker for further investigation ([link](https://trello.com/c/52Vy8GGo/4698-executionfailed-key-not-found)).

**Comment by Lojjs** [comment]
We have found this bug internally already so there is a fix coming up in Neo4j 5.7.0 which should be released later today or tomorrow.
