### ISSUE TITLE
ExecutionFailed: A bug has occurred in the morsel runtime

### ISSUE THREAD

**Issue by CelineWuest** [neo4j/neo4j#13148]
When running the following query:
```cypher
UNWIND [0] AS n0 CALL { RETURN min(0) AS n1 ORDER BY COUNT { () } } RETURN 0
```

I encountered the following error:
```
Neo4jError: Neo.DatabaseError.Statement.ExecutionFailed (A bug has occurred in the morsel runtime: The target morsel cannot hold the data to copy.)
```

I believe the query mentioned above is semantically and syntactically correct and thus no error should be thrown here.

I encountered this issue when testing queries against the **Neo4j 5.6.0 enterprise version** in a Docker container running **alpine v.3**.

### Steps to reproduce
Run the following query and observe it throws an error:
```cypher
UNWIND [0] AS n0 CALL { RETURN min(0) AS n1 ORDER BY COUNT { () } } RETURN 0
```

### Expected behavior
The query should run successfully

### Actual behavior
The query fails with the error message `Neo4jError: Neo.DatabaseError.Statement.ExecutionFailed (A bug has occurred in the morsel runtime: The target morsel cannot hold the data to copy.)`.

**Comment by InverseFalcon** [comment]
This appears to be a PIPELINED runtime bug.

If I force SLOTTED runtime instead by prefixing with CYPHER runtime=SLOTTED then the query is able to run.

**Comment by loveleif** [comment]
Thanks @DominicWuest, excellent report as always. I've created a ticket in our internal bug tracker for further investigation ([link](https://trello.com/c/6ZcwyYLr)).

**Comment by pontusmelke** [comment]
Hi @DominicWuest 

We have identified and fixed the issue. A fix should go out with the next release of neo4j (probably 5.8).

Thanks again for finding this and reaching out to us!

Best Regards,
Pontus
