### ISSUE TITLE
Unexpected result about null attribute value 

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13145]
I execute a query on my neo4j database and get an unexpected result.

Neo4j version: 5.6.0 Enterprise
operating system: windows 10
API：Cypher version 9
query: create ({k:null}) return exists{match ({k:null})}
result:false

Expected behavior:
The query should return true.

Actual behavior:
The query returns false.

**Comment by CelineWuest** [comment]
I believe the query result is correct. This `MATCH` clause will never return a node. Comparing anything to `NULL` always evaluates to `NULL` and never `true`, so no node could ever match this pattern.
Additionally, no node can ever have a property evaluate to `NULL`, as stated by the first sentence in [this section in the docs](https://neo4j.com/docs/cypher-manual/current/clauses/remove/#remove-remove-a-property).

**Comment by InverseFalcon** [comment]
I agree with DominicWuest on this one for the most part.

`null` is the same as non-existence (setting a property to null is the same thing as removing the property), and comparison to null like this will fail. An `IS NULL` check, however, will succeed, but that's something that belongs in a WHERE clause.

A property can return as `null`, but it really means that the property (or perhaps the node, such as an OPTIONAL MATCH that fails) doesn't exist.

A version of this query that should succeed would be:

```
CREATE ({k:null})  // same as creating an empty node with no properties
RETURN exists{ MATCH (n) WHERE n.k IS NULL}
```

Keep in mind that the property used in the WHERE clause doesn't really matter. We could do `WHERE n.grapefruit IS NULL` and it would be the same result. The node we created has no properties set, so any property we use would pass the `IS NULL` test.

**Comment by ljhhuxiaoba** [comment]
Thanks for your explanation,this is my mistake to neglect the details.
