### ISSUE TITLE
neo4j java client for cluster readers and writers for BoltServerAddress unreasonable  

### ISSUE THREAD

**Issue by zhuyou1234** [neo4j/neo4j#13153]
neo4j server version 4.4.5
![image](https://user-images.githubusercontent.com/15230000/206393005-e83e5e92-e3b1-404d-b336-64c87ae69d81.png)

neo4j client version 4.4.5 
![image](https://user-images.githubusercontent.com/15230000/206393071-68e5a7e8-7051-4873-843e-78bb1b03b95b.png)

I see in neo4j java driver code there strictly separate read and write mode, and in memory there cache readers server list and writers server list,but if I just have three core servers(one leader la and two follow  fb fc),  this means all writer request will just connect to leader, I think if follow server can also process write request, why we not add follow to write servers

![image](https://user-images.githubusercontent.com/15230000/232364288-029aad16-9769-4ef5-9d52-ccc8772c1e3a.png)
can we just separate core and replica , all core server will both add readers and writers ?

**Comment by InverseFalcon** [comment]
In a causal cluster, per database there is only one leader node that processes write transactions. Followers cannot process writes.

That said, it sounds like you may be interested in server-side routing. When configured for server-side routing only, the client will no longer perform routing, allowing you to issue write transactions to any node in the cluster, but internal to the cluster write transactions will be routed to the leader for processing.

https://neo4j.com/docs/operations-manual/current/clustering/setup/routing/#clustering-routing

**Comment by loveleif** [comment]
Thanks for reaching out! I agree with Andrew, this is expected in a causal cluster. Or did we misunderstand something @zhuyou1234?

**Comment by zhuyou1234** [comment]
> In a causal cluster, per database there is only one leader node that processes write transactions. Followers cannot process writes.
> 
> That said, it sounds like you may be interested in server-side routing. When configured for server-side routing only, the client will no longer perform routing, allowing you to issue write transactions to any node in the cluster, but internal to the cluster write transactions will be routed to the leader for processing.
> 
> https://neo4j.com/docs/operations-manual/current/clustering/setup/routing/#clustering-routing

if we enable dbms.routing.enabled (enable  server-side routing). in neo4j driver use connect url "neo4j://followip:followPort", I see neo4j driver will get neo4j servers with role read/writer to collect readers/writers, if exuecte write  transactions, neo4j driver will just choose one server of writers  then get connection and exuecute. I means  if I enable dbms.routing.enabled,  write transaction in neo4j client, driver will only connect to leader, if writer is huge leader connections is huge, I think if follow can also accept write transaction connection but follow just shared connections and forward write request to leader.

by the way if I use bolt://followip:followPort and execute write transaction it will work wrong and error message follow
![image](https://user-images.githubusercontent.com/15230000/232657787-5fe93742-433b-4f8b-a7c4-3e3ffe473f8c.png)

**Comment by InverseFalcon** [comment]
You're not using the `neo4j://` routing protocol, however. Your screenshot shows you are using the `bolt://` protocol, which does not engage routing (ANY routing, including server side) and that's likely why you are getting that error. Try with the `neo4j://` protocol instead.

Also, routing is not binary, there are 3 forms it can take depending on the values of two configuration properties: only client-side routing, hybrid client and server side routing (what you likely have configured now), and only server-side routing. 

The two properties governing the routing are:

dbms.routing.enabled - set to a boolean value. If true then enables server-side routing
dbms.routing.default_router - set to either SERVER or CLIENT (CLIENT is default)

So if you have  `dbms.routing.default_router=CLIENT` or are using defaults, and `dbms.routing.enabled=true` then you are using a hybrid routing, where (provided that you are using the `neo4j://` protocol and not the `bolt://` protocol) the driver will still perform the routing, and if the server you routed a write query to is no longer the leader, the server-side routing will route it to the new leader for execution. If `dbms.routing.default_router=CLIENT` and `dbms.routing.enabled=false`, then you are purely using client-side routing. If `dbms.routing.default_router=SERVER` and `dbms.routing.enabled=true`, then you are purely using server-side routing.

Again, for any routing to take place you need to be using the `neo4j://` protocol in the connection address.

**Comment by caofujun** [comment]
Hi @InverseFalcon, you mentioned "per database there is only one leader node that processes write transactions.", but I noticed that many docs said that there may be multi "core server" in a cluster, does leader and follower node together called "core server". or only leader node called "core server", is it possible there are many leader in a cluster?

**Comment by InverseFalcon** [comment]
@caofujun One common issue with tech is that there are terms which are overloaded.

I'm fairly sure "multi core server" uses "core" to mean "cpu core", which has only to do with hardware components, and nothing to do with Neo4j and clustering.

When we're talking about Neo4j and clustering, "core" is referring to a Neo4j process running on a single server that is configured as `dbms.mode=CORE` (using 4.x config and terminology; there have been changes in 5.x) meaning that in a causal cluster it participates in the Raft protocol, and may be elected a leader for some subset of databases (and if not a db leader, then a follower).

It's also important to remember that Neo4j (as a dbms and cluster) supports multiple databases, and leadership can be different per database.

So if you had a 3 core cluster and 3 databases on your dbms: system, northwind, movies
then it's possible that core 1 could be the `movies` db leader, core 2 could be the `system` db leader, and core 3 could be the `northwind` db leader (with all other nodes otherwise being followers for the databases where they do not hold leadership). When there are more databases than there are cores in the cluster, then some cores may be leaders for multiple databases.

With that in mind, when we're talking about routing to the leader, it is the leader for the database you've specified when you create the transaction or session.

**Comment by zhuyou1234** [comment]
> You're not using the `neo4j://` routing protocol, however. Your screenshot shows you are using the `bolt://` protocol, which does not engage routing (ANY routing, including server side) and that's likely why you are getting that error. Try with the `neo4j://` protocol instead.
> 
> Also, routing is not binary, there are 3 forms it can take depending on the values of two configuration properties: only client-side routing, hybrid client and server side routing (what you likely have configured now), and only server-side routing.
> 
> The two properties governing the routing are:
> 
> dbms.routing.enabled - set to a boolean value. If true then enables server-side routing dbms.routing.default_router - set to either SERVER or CLIENT (CLIENT is default)
> 
> So if you have `dbms.routing.default_router=CLIENT` or are using defaults, and `dbms.routing.enabled=true` then you are using a hybrid routing, where (provided that you are using the `neo4j://` protocol and not the `bolt://` protocol) the driver will still perform the routing, and if the server you routed a write query to is no longer the leader, the server-side routing will route it to the new leader for execution. If `dbms.routing.default_router=CLIENT` and `dbms.routing.enabled=false`, then you are purely using client-side routing. If `dbms.routing.default_router=SERVER` and `dbms.routing.enabled=true`, then you are purely using server-side routing.
> 
> Again, for any routing to take place you need to be using the `neo4j://` protocol in the connection address.


if I use `neo4j://`  routing protocol, with write transaction for AccessMode.WRITE
![image](https://user-images.githubusercontent.com/15230000/232687675-252c1970-013d-4ac0-8774-e9ee99a44c3b.png)

acquireConnection will call LoadBalancer.acquireConnection
![image](https://user-images.githubusercontent.com/15230000/232688053-0ddbc4ca-a99b-487a-895b-c7e743bf9ac2.png)

when AccessMode.WRITE will just get server from  routingTable.writers()

and from code I see routingTable.writers will init by use 
![image](https://user-images.githubusercontent.com/15230000/232688476-27b8052f-56f2-4a08-b58f-8c62ef437ac1.png)

so if I have three core cluster neo4j server a b c, and a is leader, b c is follow.for routingTable writers just contain a（leader）, and readers just contains b c （follow）. so if I use `neo4j://`  routing protocol and for  AccessMode.WRITE transaction  neo4j driver will always choose a(leader) server to connect, I think this is just client-side route, not server-side route. if all of our operation is write transaction, client will just only choose leader a to connect.

**Comment by zhuyou1234** [comment]
> > You're not using the `neo4j://` routing protocol, however. Your screenshot shows you are using the `bolt://` protocol, which does not engage routing (ANY routing, including server side) and that's likely why you are getting that error. Try with the `neo4j://` protocol instead.
> > Also, routing is not binary, there are 3 forms it can take depending on the values of two configuration properties: only client-side routing, hybrid client and server side routing (what you likely have configured now), and only server-side routing.
> > The two properties governing the routing are:
> > dbms.routing.enabled - set to a boolean value. If true then enables server-side routing dbms.routing.default_router - set to either SERVER or CLIENT (CLIENT is default)
> > So if you have `dbms.routing.default_router=CLIENT` or are using defaults, and `dbms.routing.enabled=true` then you are using a hybrid routing, where (provided that you are using the `neo4j://` protocol and not the `bolt://` protocol) the driver will still perform the routing, and if the server you routed a write query to is no longer the leader, the server-side routing will route it to the new leader for execution. If `dbms.routing.default_router=CLIENT` and `dbms.routing.enabled=false`, then you are purely using client-side routing. If `dbms.routing.default_router=SERVER` and `dbms.routing.enabled=true`, then you are purely using server-side routing.
> > Again, for any routing to take place you need to be using the `neo4j://` protocol in the connection address.
> 
> if I use `neo4j://` routing protocol, with write transaction for AccessMode.WRITE ![image](https://user-images.githubusercontent.com/15230000/232687675-252c1970-013d-4ac0-8774-e9ee99a44c3b.png)
> 
> acquireConnection will call LoadBalancer.acquireConnection ![image](https://user-images.githubusercontent.com/15230000/232688053-0ddbc4ca-a99b-487a-895b-c7e743bf9ac2.png)
> 
> when AccessMode.WRITE will just get server from routingTable.writers()
> 
> and from code I see routingTable.writers will init by use ![image](https://user-images.githubusercontent.com/15230000/232688476-27b8052f-56f2-4a08-b58f-8c62ef437ac1.png)
> 
> so if I have three core cluster neo4j server a b c, and a is leader, b c is follow.for routingTable writers just contain a（leader）, and readers just contains b c （follow）. so if I use `neo4j://` routing protocol and for AccessMode.WRITE transaction neo4j driver will always choose a(leader) server to connect, I think this is just client-side route, not server-side route. if all of our operation is write transaction, client will just only choose leader a to connect.



and I also check role with cli  "CALL dbms.cluster.routing.getRoutingTable({}) 
YIELD ttl, servers 
UNWIND servers as server
RETURN ttl, server.role, server.addresses;"

**Comment by InverseFalcon** [comment]
> I think this is just client-side route, not server-side route.

Yes, it likely is, since you've enabled server-side routing, but you have not disabled client-side routing, both of them can coexist, with server-side routing being used only when client-side routing routes to the wrong server (such as a timing issue during a leader switch). 

Have you applied `dbms.routing.default_router=SERVER` yet? That should disable client-side routing, and allow server-side routing to be the only routing system being used.

**Comment by zhuyou1234** [comment]
> > I think this is just client-side route, not server-side route.
> 
> Yes, it likely is, since you've enabled server-side routing, but you have not disabled client-side routing, both of them can coexist, with server-side routing being used only when client-side routing routes to the wrong server (such as a timing issue during a leader switch).
> 
> Have you applied `dbms.routing.default_router=SERVER` yet? That should disable client-side routing, and allow server-side routing to be the only routing system being used.


so if enable server-side routing, I think for routingTable readers and writers both contains all core neo4j server will be better?
follow can also share partial write connection links.

by the way your means when I  config  `dbms.routing.default_router=SERVER`, this will disable client-side routing just effect server-side? this means all core server role will be both read and write role ?just similar to single neo4j server?
![image](https://user-images.githubusercontent.com/15230000/232698706-a91056ac-83e1-4bb5-8692-aa443b398a4d.png)

**Comment by InverseFalcon** [comment]
For ONLY server-side routing you need these:

```
dbms.routing.default_router=SERVER
dbms.routing.enabled=true
```

At that point as long as you are using the `neo4j://` protocol in the connection address, you can connect to any node (or any address that resolves to any node in the cluster, or use a load balancer) and the node will accept the transaction and route it to the leader internally (if it's a write) or execute it immediately if it's a read.

**Comment by zhuyou1234** [comment]
> dbms.routing.default_router=SERVER
> dbms.routing.enabled=true

if I config this what's resonse about 
CALL dbms.cluster.routing.getRoutingTable({}) 
YIELD ttl, servers 
UNWIND servers as server
RETURN ttl, server.role, server.addresses;

all core servers both are read and write role?

**Comment by zhuyou1234** [comment]
> > dbms.routing.default_router=SERVER
> > dbms.routing.enabled=true
> 
> if I config this what's resonse about CALL dbms.cluster.routing.getRoutingTable({}) YIELD ttl, servers UNWIND servers as server RETURN ttl, server.role, server.addresses;
> 
> all core servers both are read and write role?

or just leader in write role, follow in write role ? if in this, neo4j driver in client will always be client-side route. all write transaction will only choose leader to connect and execute(unless leader switch)

**Comment by zhuyou1234** [comment]
> > > dbms.routing.default_router=SERVER
> > > dbms.routing.enabled=true
> > 
> > 
> > if I config this what's resonse about CALL dbms.cluster.routing.getRoutingTable({}) YIELD ttl, servers UNWIND servers as server RETURN ttl, server.role, server.addresses;
> > all core servers both are read and write role?
> 
> or just leader in write role, follow in write role ? if in this, neo4j driver in client will always be client-side route. all write transaction will only choose leader to connect and execute(unless leader switch)

 I means java neo4j driver ，it now default implementation is cache readers and writers , and choose address by accessmode,and Currently, read and write are strictly separated.

**Comment by zhuyou1234** [comment]
> > > > dbms.routing.default_router=SERVER
> > > > dbms.routing.enabled=true
> > > 
> > > 
> > > if I config this what's resonse about CALL dbms.cluster.routing.getRoutingTable({}) YIELD ttl, servers UNWIND servers as server RETURN ttl, server.role, server.addresses;
> > > all core servers both are read and write role?
> > 
> > 
> > or just leader in write role, follow in write role ? if in this, neo4j driver in client will always be client-side route. all write transaction will only choose leader to connect and execute(unless leader switch)
> 
> I means java neo4j driver ，it now default implementation is cache readers and writers , and choose address by accessmode,and Currently, read and write are strictly separated.

![image](https://user-images.githubusercontent.com/15230000/232704208-cc80002f-dde2-4713-9128-4e7cad3f28a9.png)
I guess if I config dbms.routing.default_router=SERVER. the response about 
CALL dbms.cluster.routing.getRoutingTable({})
YIELD ttl, servers
UNWIND servers as server
RETURN ttl, server.role, server.addresses;
will be all core server both contains in read and write role.
or write role get all core server, read role get all follow server?


I don't  have env to verify this ,cloud please help check this result ?

**Comment by zhuyou1234** [comment]
@InverseFalcon 

I guess if I config dbms.routing.default_router=SERVER. the response about
CALL dbms.cluster.routing.getRoutingTable({})
YIELD ttl, servers
UNWIND servers as server
RETURN ttl, server.role, server.addresses;
will be all core server both contains in read and write role.
or write role get all core server, read role get all follow server?

I don't have env to verify this ,cloud please help check this result ?

**Comment by loveleif** [comment]
This issue is beyond my expertise so I've forwarded it to the clustering team ([link to internal issue tracker](https://trello.com/c/2Vk56t2r)).

**Comment by gfx54b** [comment]
All this above is java driver code, clustering provides the list of servers for all roles (what is behind the routing table), but nothing beyond that. Not how is it used either on the server on the client side.
This is for the drivers team.

**Comment by zhuyou1234** [comment]
> All this above is java driver code, clustering provides the list of servers for all roles (what is behind the routing table), but nothing beyond that. Not how is it used either on the server on the client side.
> This is for the drivers team.

I guess if I config dbms.routing.default_router=SERVER. the response about
CALL dbms.cluster.routing.getRoutingTable({})
YIELD ttl, servers
UNWIND servers as server
RETURN ttl, server.role, server.addresses;
will be all core server both contains in read and write role.
or write role get all core server, read role get all follow server?

I don't have env to verify this ,cloud please help check this result ?

I hope know exact result. thanks

**Comment by AndyHeap-NeoTech** [comment]
As this issue has been quiet for a while we will close it. 

If you have follow on questions then please consider opening a question on stackoverflow, our community forums https://community.neo4j.com/ or such. This issues tracker is generally not the right place for general questions unless there's a bug or a suspected bug in the driver involved.
