### ISSUE TITLE
Unexpected variable shadowing about variable 'null'

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13158]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.6.0 Enterprise
operating system: windows 10
API：Cypher version 9
query:with null as null return exists{return null}
error message:
Neo.ClientError.Statement.SyntaxError
The variable `null` is shadowing a variable with the same name from the outer scope and needs to be renamed (line 1, column 40 (offset: 39))
"with null as null return exists{return null}"

But if I execute another query :"with null as a return exists{return a}" or "with null as null return null",then they will run successfully.
So I think there is some kind of bug here.

Expected behavior:
The query should run successfully and return true.

Actual behavior:
The query failed.

**Comment by loveleif** [comment]
Thanks once again @ljhhuxiaoba! `null` is a reserved keyword that is not permitted in variables, see https://neo4j.com/docs/cypher-manual/current/syntax/reserved/. To use `null` as a variable you need to escape it with backticks: ```with null as `null` return exists{return `null`}```.

```
neo4j@neo4j> with null as `null` return exists{return `null`};
+-----------------------+
| exists{return `null`} |
+-----------------------+
| TRUE                  |
+-----------------------+
```

**Comment by ljhhuxiaoba** [comment]
Thanks a lot!It was my mistake to ignore reserved keyword.
