### ISSUE TITLE
UnknownError about return * in subquery

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13156]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.6.0 Enterprise
operating system: windows 10
API：Cypher version 9
query: match (a) return *,exists{with a return *}
error message:
Neo.DatabaseError.General.UnknownError
Failed to execute query in transaction "bolt-19161"

But if I execute queries such as:"match (a) return *,exists{with a return a}" or "match (a) return exists{with a return *}",then they will run successfully.
The same error also occurs in count{}.

Expected behavior:
The query should run successfully and no error occurs.

Actual behavior:
The query failed.

**Comment by loveleif** [comment]
Thanks for keeping them coming @ljhhuxiaoba! Looks like this could be an issue with query parsing. I've created a ticket in our internal bug tracker for further investigation ([link](https://trello.com/c/tHCnsYhP)).

**Comment by ljhhuxiaoba** [comment]
The same query on Neo4j version: 5.7.0 Enterprise will throw another error:
Neo.DatabaseError.General.UnknownError
RETURN should note its Scope in the SemanticState

**Comment by arnefischereit** [comment]
Hi @ljhhuxiaoba,

This is the same issue as #13166 and should therefore also be fixed as part of 5.11.

Regards,

Arne
