### ISSUE TITLE
UnknownError about path variable in exists{}

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13154]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.6.0 Enterprise
operating system: windows 10
API：Cypher version 9
query: unwind [p=()-[]->() where exists{return p}|p] as p return p
error message:
Neo.DatabaseError.General.UnknownError
Failed to execute query in transaction "bolt-1867"

But if I execute another query such as:unwind [p=()-[]->() where exists{return 1}|p] as p return p,then it will run successfully.

Expected behavior:
The query should run successfully.

Actual behavior:
The query failed.

**Comment by loveleif** [comment]
Thanks for the report @ljhhuxiaoba! I'm not completely sure that query is semantically correct. But even if it isn't we should not fail in that way. I've created a ticket in our internal bug tracker for further investigation ([link](https://trello.com/c/CX9Ch4wY)).

**Comment by ljhhuxiaoba** [comment]
The same error also occurs in query "return [p=()-[:T]->()|count{return p}]".And I'm completely sure that this query is semantically correct.

**Comment by sherfert** [comment]
We've identified the issue and a fix will be part of the upcoming 5.13 release.
