### ISSUE TITLE
UnknownError when adding "with *"

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13166]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.6.0 Enterprise
operating system: windows 10
API：Cypher version 9
query: match (a) with a with * order by exists{with a return *} return 1
error message:
Neo.DatabaseError.General.UnknownError
Failed to execute query in transaction "bolt-2792"

But if I remove the clause "with *",then it will run successfully.
The same error also occurs in count{}.

Expected behavior:
The query should run successfully and no error occurs.

Actual behavior:
The query failed.

**Comment by loveleif** [comment]
Thanks again @ljhhuxiaoba 🙏! Looks like a bug in `ExpandStarRewriter` of query planning. I've created an issue for our query planner team ([link](https://trello.com/c/ddqEjYcj)).

**Comment by arnefischereit** [comment]
Hi @ljhhuxiaoba,

Thanks again for testing our product so thoroughly and reporting this issue. We have implemented a fix for it which will be part of the next release, 5.11.

I am closing this issue, should the problem persist (after the release of 5.11) or reappear please reopen this issue or open a new one.

Regards,

Arne
