### ISSUE TITLE
ExecutionFailed:Tried using a map context as a slotted context

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13160]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.6.0 Enterprise
operating system: windows 10
API：Cypher version 9
query:create ()-[:T]->() with 0 as b return [p=()-[]->()|p][b]
error message:
Neo.DatabaseError.Statement.ExecutionFailed
Tried using a map context as a slotted context

But if I execute another query:"create ()-[:T]->() with 0 as b return [p=()-[]->()|p][0]",then it can run successfully.

Expected behavior:
The query should run successfully.

Actual behavior:
The query failed.

**Comment by loveleif** [comment]
Thanks again for taking the time to report all these @ljhhuxiaoba! This query produces an invalid plan. I've created a ticket in our internal bug tracker for further investigation by the query planner team ([link](https://trello.com/c/QvVshQLG)).

**Comment by ljhhuxiaoba** [comment]
I found that this issue was closed, may I ask whether the bug has been fixed?

**Comment by mnd999** [comment]
Yes, it looks like a fix has been merged that closes the issue. It looks like something in the automation caused the issue to close immediately before the fix was synced to the public repo.

**Comment by sherfert** [comment]
Hi. We implemented a fix which will be included in 5.9 and 4.4.21.
