### ISSUE TITLE
Integer overflow caused by MATCH large data

### ISSUE THREAD

**Issue by joyemang33** [neo4j/neo4j#13170]
- Neo4j version: 5.6.0
- Operating system: Ubuntu 20.04
- API/Driver: Cypher

Hi!
I met a large negative integer as a result of  ```count(*)``` triggered by``` MATCH ``` a large number of nodes and there is no exception or warning for the case. 
Would it is possible for you to further confirm and investigate this issue?
Maybe we can use BigInt when Neo4j detects it is going to break the limit of the ```java.long```.

```
MATCH (n0) MATCH (n1) MATCH (n2) MATCH (n3) MATCH (n4) MATCH (n5) MATCH (n6) MATCH (n7) MATCH (n8) RETURN COUNT(*)  
=> -9223372036854775808
```
The graph is created by the statements here [create.log](https://github.com/neo4j/neo4j/files/11286933/create.log)

**Comment by loveleif** [comment]
Thanks again for taking the time to write such a clear report @joyemang33! I can reproduce the issue. I agree it's not optimal to return an incorrect result here. Using BigInt is an option, but that is considered a breaking change ([documentation](https://neo4j.com/docs/cypher-manual/current/functions/aggregating/#functions-count) states `count` should return a 64 bit integer) so would not be possible until version 6. Other options are to throw an exception or update documentation about this caveat. We will investigate further and come back ([link to internal ticket](https://trello.com/c/bhAPDm3s)).

**Comment by joyemang33** [comment]
> Thanks again for taking the time to write such a clear report @joyemang33! I can reproduce the issue. I agree it's not optimal to return an incorrect result here. Using BigInt is an option, but that is considered a breaking change ([documentation](https://neo4j.com/docs/cypher-manual/current/functions/aggregating/#functions-count) states `count` should return a 64 bit integer) so would not be possible until version 6. Other options are to throw an exception or update documentation about this caveat. We will investigate further and come back ([link to internal ticket](https://trello.com/c/bhAPDm3s)).

Thank you very much for your valuable assistance! I completely agree with you that throwing an exception is the better approach when it comes to exceeding limits. (In fact, during some testing that I conducted with Gremlin-based GDBs, I encountered a similar issue :(, and their developer has had no good solution until now to the issue.)

**Comment by pontusmelke** [comment]
Hi @joyemang33 ,
In neo4j integers are limited to 64 bits, at least in 5.x and earlier. However, we should never overflow as you demonstrated here. We have merged a fix that will emit an error instead of overflowing and it will be released with the next version of Neo4j server, probably version 5.8.

Thanks again for reporting this, I'll close the issue but don't hesitate to reopen or open a new one if the fix isn't working for you.

Best regards,
Pontus

**Comment by joyemang33** [comment]
Thank you very much to @loveleif and @pontusmelke for the quick fix and clear explanation!
