### ISSUE TITLE
UnknownError when using ListLiteral in limit

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13173]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.7.0 Enterprise
operating system: windows 10
API：Cypher version 9
query:match (a) with a limit [1][0] return a
error message:
Neo.DatabaseError.General.UnknownError
Failed to evaluate expression ContainerIndex(ListLiteral(List(SignedDecimalIntegerLiteral(1))),SignedDecimalIntegerLiteral(0))

The same error also occurs in skip clause.

Expected behavior:
The query should run successfully.

Actual behavior:
The query failed.

**Comment by PetrJanouch** [comment]
@ljhhuxiaoba thanks for reporting this

**Comment by pontusmelke** [comment]
@ljhhuxiaoba thanks again for reporting this. We have merged a fix that will be released with the next available version, most probably 5.8. I'll close this issue but don't hesitate to reopen or open a new one should the problem reappear.

Best regards,
Pontus
