### ISSUE TITLE
UnknownError:Failed to evaluate expression

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13172]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.7.0 Enterprise
operating system: windows 10
API：Cypher version 9
query:return 1 limit size(keys({}))
error message:
Neo.DatabaseError.General.UnknownError
Failed to evaluate expression FunctionInvocation(Namespace(List()),FunctionName(size),false,Vector(FunctionInvocation(Namespace(List()),FunctionName(keys),false,Vector(MapExpression(ArraySeq())))))

The same error also occurs in skip clause.

Expected behavior:
The query should run successfully.

Actual behavior:
The query failed.

**Comment by PetrJanouch** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UnknownError:Failed to evaluate expression](https://trello.com/c/MqdGjOkY/4513-unknownerrorfailed-to-evaluate-expression)

**Comment by PetrJanouch** [comment]
@ljhhuxiaoba Thank you for reporting this.

**Comment by pontusmelke** [comment]
Hi @ljhhuxiaoba 
This is an example of the same problem you reported [here](https://github.com/neo4j/neo4j/issues/13173). A fix has been merged and will most probably be released with version 5.8.

Thanks again!

Best Regards,
Pontus
