### ISSUE TITLE
ExecutionFailed:Unknown expression type during transformation

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13177]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.7.0 Enterprise
operating system: windows 10
API：Cypher version 9
query:call {return reduce(a=0,b in []|a) as k} match (a) match ({k:exists{return a as b}}) return a
error message:
Neo.DatabaseError.Statement.ExecutionFailed
Unknown expression type during transformation (class org.neo4j.cypher.internal.ir.ast.ExistsIRExpression)

Expected behavior:
The query should run successfully.

Actual behavior:
The query failed.

**Comment by PetrJanouch** [comment]
@ljhhuxiaoba Thanks for reporting this. We will investigate.

It seems like it might be the same issue as https://github.com/neo4j/neo4j/issues/13098

**Comment by arnefischereit** [comment]
Hi @ljhhuxiaoba,

This issue seems to have been fixed in 5.8.

I am closing this issue, should the problem persist or reappear please reopen this issue or open a new one.

Regards,  

Arne
