### ISSUE TITLE
ExecutionFailed:key not found: SymbolUse(a@58(165b698e))

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13171]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.7.0 Enterprise
operating system: windows 10
API：Cypher version 9
query:merge(a) with a as b with null as a return 1 limit reduce(a=1,b in[]|1)
error message:
Neo.DatabaseError.Statement.ExecutionFailed
key not found: SymbolUse(a@58(165b698e))

Expected behavior:
The query should run successfully and return 1.

Actual behavior:
The query failed.

**Comment by loveleif** [comment]
Thanks again for taking the time to report @ljhhuxiaoba! I believe this issue is related to https://github.com/neo4j/neo4j/issues/13078. I have linked this issue to the same internal ticket ([link](https://trello.com/c/py6IFL1E)). Have a nice day!

**Comment by nadja-muller** [comment]
This bug has been fixed in 5.11.0 🎉

**Comment by nadja-muller** [comment]
This has been fixed for 5.11.0 🎉
