### ISSUE TITLE
This query builds a cartesian product between disconnected patterns.

### ISSUE THREAD

**Issue by qqqwex** [neo4j/neo4j#13178]
I have loaded two tables. 
1. Papers 
LOAD CSV WITH HEADERS FROM "file:///papers.csv" AS row
WITH row LIMIT 1000
MERGE (papers:Papers {id:row.id})
SET papers.title = (row.title),
 papers.publicationdate = (row.publicationdate),
 papers.appearsinjournal = (row.appearsinjournal),
 papers.created = (row.created),
 papers.volume = (row.volume),
 papers.startingpage = (row.startingpage),
 papers.appearsinconferenceseries = (row.appearsinconferenceseries),
 papers.type = (row.type),
 papers.language = (row.language)
2. Paperurls 
LOAD CSV WITH HEADERS FROM "file:///paperurls.csv" AS row
with row limit 1000
MERGE (paperurls:Paperurls {hasurl:row.hasurl})
SET paperurls.id = (row.id)

Now I'm trying to make relationships between all nodes
MATCH (a:Papers), (u:Paperurls)
WHERE a.id = u.id
CREATE (a)-[:HAS_URL]->(u)

Neo4j writes this:
If a part of a query contains multiple disconnected patterns, this will build a cartesian product between all those parts. This may produce a large amount of data and slow down query processing. While occasionally intended, it may often be possible to reformulate the query that avoids the use of this cross product, perhaps by adding a relationship between the different parts or by using OPTIONAL MATCH (identifier is: (u))

Please help me :)

**Comment by InverseFalcon** [comment]
There's nothing wrong with your approach, you can disregard the warning.

For cases where you're MATCHing to nodes (that are not connected through a pattern you're MATCHing on already) with the intention of creating a relationship between them, this is the right thing to do (though for this query you will also want an indexes on the properties you are merging on for nodes of those labels, and likely on the id properties for both labels).

**Comment by Lojjs** [comment]
@qqqwex What @InverseFalcon replied above is correct. Feel free to re-open if you have further problems. Best regard Louise, Neo4j Cypher team
