### ISSUE TITLE
Variable shadowing error in order by

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13188]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.7.0 Community
operating system: windows 10
API：Cypher version 9
query:match p=()-[]->() return * order by exists{with p return 1}
error message:
Neo.ClientError.Statement.SyntaxError
The variable `p` is shadowing a variable with the same name from the outer scope and needs to be renamed (line 1, column 49 (offset: 48))
"match p=()-[]->() return * order by exists{with p return 1}"

But if I execute another query such as "match p=()-[]->() return exists{with p return 1}",then it can run successfully and no error occurs.

Expected behavior:
The query should run successfully.

Actual behavior:
The query failed.

**Comment by ncordon** [comment]
Hey @ljhhuxiaoba thanks for reporting. This seems like a bug indeed! We'll keep you posted on progress solving this

**Comment by gem-neo4j** [comment]
Hi, this has now been fixed and should be released in the next release (5.11)
