### ISSUE TITLE
UnknownError:RETURN should note its Scope in the SemanticState

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13187]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.7.0 Community
operating system: windows 10
API：Cypher version 9
query:match p=()-[]->() return * order by exists{with * return p}
error message:
Neo.DatabaseError.General.UnknownError
RETURN should note its Scope in the SemanticState

But if I execute another query such as "match p=()-[]->() return exists{with * return p}",then it can run successfully and no error occurs.

Expected behavior:
The query should run successfully.

Actual behavior:
The query failed.

**Comment by ncordon** [comment]
Hey @ljhhuxiaoba. Thanks for reporting! 

This seems like a bug to me, I've been able to reproduce. We'll keep you posted on progress solving it 😄

**Comment by gem-neo4j** [comment]
Hi @ljhhuxiaoba,

This is the same issue as https://github.com/neo4j/neo4j/issues/13166 and should therefore also be fixed as part of 5.11.

Thanks :)
