### ISSUE TITLE
Issues with corporate CLA

### ISSUE THREAD

**Issue by gerrith3** [neo4j/neo4j#13184]
Hi, we have been looking to contribute patches to port neo4j to the IBM Power platform.  However, in review of your corporate CLA, the language is overly broad, especially when compared to any other open source CLA.  Is there someone we could talk with about the issues we see with the CLA?  We would really like have this source natively support and build on IBM Power systems.

The changes we have are mostly around page size handling (which is different on Power) and most of the rest of the code appears to be architecture independent.

thanks,

Gerrit Huizenga, Lead, IBM Power Open Source Ecosystem

**Comment by klaren** [comment]
Hello, and thanks for reaching out.

To discuss CLA specifics questions you can send an email with your questions directly to [cla@neo4j.com](mailto:cla@neo4j.com) and you will get in contact with our legal team.

https://neo4j.com/developer/cla/#_can_we_discuss_some_items_in_the_cla

**Comment by mnd999** [comment]
This was resolved offline with the CLA team as above.
