### ISSUE TITLE
UnknownError:Scope dependencies have not been computed yet

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13180]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.7.0 Enterprise
operating system: windows 10
API：Cypher version 9
query:call{with exists{return 1} as a return a} return a
error message:
Neo.DatabaseError.General.UnknownError
Scope dependencies have not been computed yet

But if I execute another query "call{with true as a return a} return a",then it can run successfully.I think it's very strange.

Expected behavior:
The query should run successfully.

Actual behavior:
The query failed.

**Comment by PetrJanouch** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UnknownError:Scope dependencies have not been computed yet](https://trello.com/c/8eDQsqRR/662-unknownerrorscope-dependencies-have-not-been-computed-yet)

**Comment by arnefischereit** [comment]
Hi @ljhhuxiaoba,

This is the same issue as #13134 and should therefore also be fixed as part of 5.9.

Regards,

Arne
