### ISSUE TITLE
UnknownError when adding "with *" in subquery

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13186]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.7.0 Community
operating system: windows 10
API：Cypher version 9
query:unwind [p=()-[]-()|count{with * return 1 order by p}] as c return c
error message:
Neo.DatabaseError.General.UnknownError
class org.neo4j.cypher.internal.expressions.PathExpression cannot be cast to class org.neo4j.cypher.internal.expressions.LogicalVariable (org.neo4j.cypher.internal.expressions.PathExpression and org.neo4j.cypher.internal.expressions.LogicalVariable are in unnamed module of loader 'app')

But if I remove the "with *",then it can run successfully and no error occurs.

Expected behavior:
The query should run successfully.

Actual behavior:
The query failed.

**Comment by ncordon** [comment]
Hey @ljhhuxiaoba! Awesome job finding all of the bugs you've found so far!

I am able to reproduce on my side. We'll keep you posted on progress solving this 😄

**Comment by sherfert** [comment]
We've identified the issue and a fix will be part of the upcoming 5.13 release.
