### ISSUE TITLE
Error about "RETURN should note its Scope in the SemanticState"

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13199]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.8.0 Community
operating system: windows 10
API：Cypher version 9
query:MATCH (n1) RETURN *, count{MATCH (n1) RETURN *}
error message:
Neo.DatabaseError.General.UnknownError
RETURN should note its Scope in the SemanticState

Expected behavior:
The query should run successfully.

Actual behavior:
The query failed.

**Comment by LinneaAndersson** [comment]
@ljhhuxiaoba Thanks for reporting this! 

We will investigate it further and get back to you when we have more information
//Linnéa

**Comment by arnefischereit** [comment]
Hi @ljhhuxiaoba,

This is the same issue as #13166 and should therefore also be fixed as part of 5.11.

Regards,

Arne
