### ISSUE TITLE
TypeError being Ignored 

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13193]
I execute a query on my neo4j database ,and an error should have occurred but did not.

Neo4j version: 5.8.0 Community
operating system: windows 10
API：Cypher version 9
query:create (n) return exists{(n)} as n order by exists{(n)}
result:true

But if I execute another query such as "create (n) return exists{(a)} as n order by exists{(n)}",then an error which was expected occurred.I think the inconsistency is very strange and there is a bug here.

**Comment by arnefischereit** [comment]
Hi @ljhhuxiaoba

Thank you for reporting another bug in this area. I could reproduce the issue. We will further investigate and come back to you with our findings.

Regards,

Arne

---

[Internal link for reference](https://trello.com/c/gCGBbPkd/)

**Comment by gem-neo4j** [comment]
Hi, thanks for reporting, we have fixed this and it will be included in the next release :)
