### ISSUE TITLE
Unexpected TypeError: Expected `NO_VALUE` to be a `TextValue` in `split` with `null` literal in list

### ISSUE THREAD

**Issue by CelineWuest** [neo4j/neo4j#13196]
When running the following query:
```cypher
RETURN split(" ", [null])
```

I encountered the following error:
```
Neo4jError: Neo.ClientError.Statement.TypeError (Expected NO_VALUE to be a org.neo4j.values.storable.TextValue, but it was a org.neo4j.values.storable.NoValue)
```

I believe the query mentioned above is semantically and syntactically correct and thus no error should be thrown here.

I encountered this issue when testing queries against the **Neo4j 5.7.0 enterprise version** in a Docker container running **alpine v.3**.

### Steps to reproduce
Run the following query and observe it throws an error:
```cypher
RETURN split(" ", [null])
```

### Expected behavior
The query should run successfully

### Actual behavior
The query fails with the error message `Neo4jError: Neo.ClientError.Statement.TypeError (Expected NO_VALUE to be a org.neo4j.values.storable.TextValue, but it was a org.neo4j.values.storable.NoValue)`

**Comment by arnefischereit** [comment]
Hi @DominicWuest,

Thank you for reporting another bug in this area. I could reproduce the issue. We will further investigate and come back to you with our findings.

Regards,

Arne

---

[Link for internal reference](https://trello.com/c/2iow9ZEW)

**Comment by pontusmelke** [comment]
@DominicWuest thanks again for reporting. We have merged a fix for this that should be part of the next release (5.10)

Best regards,
Pontus
