### ISSUE TITLE
SymbolUse error about variable in reduce()

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13191]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.7.0 Community
operating system: windows 10
API：Cypher version 9
query:return [(a)-[]->()|a][count{(a)}] skip reduce(a=1,n in []|1)
error message:
Neo.DatabaseError.Statement.ExecutionFailed
key not found: SymbolUse(a@46(60f44178))

Expected behavior:
The query should run successfully.

Actual behavior:
The query failed.

**Comment by arnefischereit** [comment]
Hi @ljhhuxiaoba 

Thank you for reporting another bug in this area. I could reproduce the issue. We will further investigate and come back to you with our findings.

Regards,

Arne

---
[Internal link for reference](https://trello.com/c/3YUhNTLF/)

**Comment by Lojjs** [comment]
@ljhhuxiaoba The bug was related to a scoping issue with SKIP and LIMIT and has now been fixed. The fix will be included in upcoming Neo4j 5.11 and 4.4.24 releases. 

Best regards, Louise, Neo4j Cypher team
