### ISSUE TITLE
Simple `WITH` imports restriction in Call {}

### ISSUE THREAD

**Issue by raz-mon** [neo4j/neo4j#13203]
Hi,

I'm wondering what is the reason behind the restriction enforcing simple imports (e.g., "WITH x") in Call {}.
Why are predicates, sorting, complex expressions, aliasing etc. not aloud?

Thanks.

**Comment by LinneaAndersson** [comment]
Hello @raz-mon,  


The purpose of the `WTIH` clause in `CALL {}`, is to be able to import variable bindings from the outer query. The importing is not part of the inner query but of calling it (like passing arguments to a function). The importing WITH clause makes it easy to spot which variables in scope of the inner query are coming from the outer query.

If you would like to process existing variable bindings etc. you could do so in the outer query (before the `CALL {}`), or after the import (inside of `CALL {}`).

For example, this query:

```
MATCH (n:Person)
CALL {
  WITH n.age AS age
  ...
```

could be written:
```
MATCH (n:Person)
WITH n.age AS age
CALL {
  WITH age
```

or
```
MATCH (n:Person)
CALL {
  WITH n
  WITH n.age AS age
```
   

Thanks for your question and please let us know if you have any further questions,
Linnéa

**Comment by raz-mon** [comment]
Hi @LinneaAndersson 
Great, thank you.
