### ISSUE TITLE
Variable shadowing Error when using call{} in exists{}

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13204]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.8.0 Community
operating system: windows 10
API：Cypher version 9
query:match (n) return exists{call{match (n) return 1 as a}}
error message:
Neo.ClientError.Statement.SyntaxError
The variable `n` is shadowing a variable with the same name from the outer scope and needs to be renamed (line 1, column 37 (offset: 36))
"match (n) return exists{call{match (n) return 1 as a}}"
                                     ^

I think the variable "n" in call{} does not shadow the variable "n" from the outer scope because there is no "with n" in the beginning of call{}.
And please see the strange truth that query "match (n) call{match (n) return 1 as a} return 1" can run successfully and does not shadow the variable "n" from the outer scope.

Expected behavior:
The query should run successfully and return true.

Actual behavior:
The query failed.

**Comment by mnd999** [comment]
Thanks, we'll look into it.

**Comment by ljhhuxiaoba** [comment]
And if I add "with *" in the call{} subquery,then the same error still happens.

To produce:
match (n) return exists{call{with * match (n) return 1 as a}}

**Comment by gem-neo4j** [comment]
Hi there, thanks for reporting this! It will be fixed in the next release cycle of Neo4j (5.12)
