### ISSUE TITLE
WIN11 DOWLOAD NEO4J CAN'T START . PLZ HELP!!!

### ISSUE THREAD

**Issue by scs001** [neo4j/neo4j#13205]
## Guidelines
SYSTEM
WIN11

DOWLOAD TAG
[neo4j-community-4.4.21-windows.zip](https://dist.neo4j.org/neo4j-community-4.4.21-windows.zip)
[jdk-8u371-windows-x64.exe](https://download.oracle.com/otn/java/jdk/8u371-b11/ce59cff5c23f4e2eaf4e778a117d4c5b/jdk-8u371-windows-x64.exe?AuthParam=1685891369_cd1f65daae4fc981d79c44a22a0c78a2)

- Neo4j version: 4.4.21

### Steps to reproduce

step1. i install the right version java package for neo4j.i check that in my powershell
C:\Users\smith>java -version
java version "17.0.7" 2023-04-18 LTS
Java(TM) SE Runtime Environment (build 17.0.7+8-LTS-224)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.7+8-LTS-224, mixed mode, sharing)

step2.i install neo4j, and add path. finally console fail
C:\Users\smith>neo4j console
Error: Could not find or load main class org.neo4j.server.startup.Neo4jCommand
Caused by: java.lang.ClassNotFoundException: org.neo4j.server.startup.Neo4jCommand

**Comment by scs001** [comment]
i follw this neo4j document to do https://neo4j.com/docs/operations-manual/current/installation/windows/
i find that i should download java11 to start neo4j 4, but when i finish that, i met same wrong

**Comment by scs001** [comment]
> I finally find the Neo4j version: 4.4.21 based java11. thats really superise me

**Comment by scs001** [comment]
i finally find that must put the NEO4J path to the system environment. because you java path is add in the system environment, so if we put neo4j path to the user environment will make error

**Comment by whyjust** [comment]
> i finally find that must put the NEO4J path to the system environment. because you java path is add in the system environment, so if we put neo4j path to the user environment will make error

nice，NEO4j path should remove from system environment!

**Comment by GsjResilient** [comment]
that depands on your java path,java path and neo4j path should be in the same environment,which i use to solve my problem
