### ISSUE TITLE
Type mismatch error about reduce()

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13213]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.8.0 Community
operating system: windows 10
API：Cypher version 9
query:return length(reduce(a=null,b in []|null+null))
error message:
Neo.ClientError.Statement.SyntaxError
Type mismatch: expected Path but was Any, Float, Integer, Number, String, Duration, Date, Time, LocalTime, LocalDateTime, DateTime or List<T> (line 1, column 15 (offset: 14))
"return length(reduce(a=null,b in [null]|null+null))"
               ^

And please see the strange truth that query "return length(reduce(a=null,b in []|null))" can run successfully.

Expected behavior:
The query should run successfully and return null.

Actual behavior:
The query failed.

**Comment by nadja-muller** [comment]
Hi. Thank you for reporting this. We will have a look.

**Comment by ljhhuxiaoba** [comment]
The same error also happens in 5.9.0

**Comment by gem-neo4j** [comment]
Hi! I looked into this and found the following.

The length function only takes `PATH` values. The reduce function, whilst in both these examples outputs the `null` value, there is a slight difference between them! The first one is outputting the result of an addition, an addition can never return the type `PATH`, therefore, the length function is receiving a value that can definitely not be `PATH`, so fails. The other example, is simply returning `null`, as `null` _could_ be a `PATH` in this example, it is accepted and works, however, outputs `null` as there is no way to do a length on it. We believe, that whilst this may seem confusing here, is correct behaviour. Thank you for reporting though, and I hope this makes sense :)

**Comment by ljhhuxiaoba** [comment]
Thanks for your reply and it can be solved.
