### ISSUE TITLE
[composite] some graph-access operations are allowed on the composite

### ISSUE THREAD

**Issue by ikwattro** [neo4j/neo4j#13218]
**Neo4j Version:** 5.9.0-enterprise
**Operating System:** Irrelevant
**API:** Irrelevant

### Steps to reproduce

Create a composite database and run a graph-accessing operation

```
CREATE COMPOSITE DATABASE composetest
```

```
MATCH (n) WHERE elementId(n) = '4:3da6df5e-685a-46dc-9da4-cff0251acd86:3'
RETURN n
```
The query executes successfully returning no results

However

```
MATCH (n)-[r]->(x) WHERE elementId(n) = '4:3da6df5e-685a-46dc-9da4-cff0251acd86:3'
RETURN n, r, x
```

Throws the following exception

```
Graph access operations are not supported on composite databases.
```

### Expected behavior

Both queries should fail

### Actual behavior

Some queries do not fail

**Comment by nadja-muller** [comment]
Hi. Thank you for reporting this. We will look into it.

**Comment by Lojjs** [comment]
@ikwattro This has been fixed and both queries will throw an error starting from the upcoming Neo4j 5.11 release.

Best regards Louise, Neo4j Cypher team
