### ISSUE TITLE
Gradle-based install contains unresolvable dependency

### ISSUE THREAD

**Issue by ehx-v1** [neo4j/neo4j#13211]
Neo4j 5.8.0 (the latest according to the docs) contains a dependency on Caffeine which cannot be resolved with Gradle (most likely due to having been removed from Maven Central).

**Neo4j Version:** 5.8.0
**Operating System:** not relevant
**API:** Gradle

### Steps to reproduce
1. Add a Gradle dependency: `implementation 'org.neo4j:neo4j:5.8.0'`
2. Run a Gradle install

### Expected behavior
Neo4j and its dependencies are added to the project correctly

### Actual behavior
Gradle produces the following error:
```
Could not resolve com.github.ben-manes.caffeine:caffeine:3.1.6.
Required by:
    project : > org.neo4j:neo4j:5.8.0 > org.neo4j:neo4j-kernel:5.8.0 > org.neo4j:neo4j-collections:5.8.0
    project : > org.neo4j:neo4j:5.8.0 > org.neo4j:neo4j-data-collector:5.8.0 > org.neo4j:neo4j-cypher-planner:5.8.0

```

**Comment by nadja-muller** [comment]
Hi. Thank you for reporting this. We will have a look.

**Comment by hedengran** [comment]
Hi @ehx-v1! I'm unable to reproduce the issue. It seems to me that it's still available on Maven Central: https://central.sonatype.com/artifact/com.github.ben-manes.caffeine/caffeine/3.1.6

If you still have this issue after clearing your gradle caches, can you please provide a simple `build.gradle` that we can use to reproduce the issue?

**Comment by ehx-v1** [comment]
I just loaded the Sonatype link twice. The first time I was under the impression that it loaded rather slowly, and the second time I got a gateway timout. So it's very well possible that Maven Central is just currently having general inconsistencies in Europe.

The project where I was going to use Neo4j was a training exercise where I ended up taking a different approach, meaning that the issue isn't relevant to me personally anymore anyway. So I'll close it for now, feel free to reopen if someone else comes across the same problem.
