### ISSUE TITLE
Neo4j 5.8.0 - The selected target store format 'AF4.3.0' (introduced in 4.3.0) is no longer supported

### ISSUE THREAD

**Issue by arjuncgi** [neo4j/neo4j#13217]
Trying to Upgrade Neo4j from v4.4.4 to v5.8.0 but facing the issue as explained below:
 I did database migration and checked the store format using: `neo4j-admin database info MY_DATABASE_NAME`

**After** Got below:
`Database name:                neo4j
Database in use:              false
Store format version:         record-standard-1.1
Store format introduced in:   5.0.0
Last committed transaction id:15235
Store needs recovery:         false`

Previously it was showing below **Before** doing migration:

`Database name:                neo4j
Database in use:              false
Store format version:         record-standard-0.1
Store format introduced in:   4.3.0
Store format superseded in:   5.0.0
Last committed transaction id:15234
Store needs recovery:         false`

I also tried [https://github.com/Homebrew/homebrew-core/issues/114553](https://github.com/Homebrew/homebrew-core/issues/114553)

To help us understand your issue, please specify important details, primarily:

- Neo4j version: 5.8.0
- Operating system: Windows10

- **Steps to reproduce**
- Expected behavior
- Actual behavior

Additionally, include (as appropriate) log-files, stacktraces, and other debug output.

## Example bug report

Caused by: org.neo4j.kernel.impl.storemigration.UnableToMigrateException: The selected target store format 'AF4.3.0' (introduced in 4.3.0) is no longer supported

### Steps to reproduce
1. Download and Unzip the latest v5.8.0 neo4j setup file.
2. Replace the certificate files from old (v.4.4.4) to v5.8.0
3. Replace the database and transaction folder inside data folder with the v4.4.4
4. Rename the database in v5.8.0
5. Update the neo4j config file the database and ip-address for neo4j setup
6. Do the Database Migration as suggested in [https://neo4j.com/docs/upgrade-migration-guide/current/version-5/migration/](https://neo4j.com/docs/upgrade-migration-guide/current/version-5/migration/)
7. run the neo4j console command 

### Expected behavior
Neo4j Should upgrade from v4.4.4 to v5.8.0

### Actual behavior
When I run neo4j console It still says 'The selected target store format 'AF4.3.0' (introduced in 4.3.0) is no longer supported'

Caused by: org.neo4j.kernel.impl.storemigration.UnableToMigrateException: The selected target store format 'AF4.3.0' (introduced in 4.3.0) is no longer supported

**Comment by emmaholmbergohlsson** [comment]
Hello @arjuncgi 
My guess is that you have another store that has not been migrated yet
In the step `Replace the database and transaction folder inside data folder with the v4.4.4`, do you copy over only the `neo4j ` database's folder or maybe also the folders for `system`?

1. If you have copied over the system database as well you need to make sure to migrate it
2. If my guess is wrong I need some more information. In that case you should be able to find the entire error in the debug.log, could you post it here so we can figure out which database is saying it is on the wrong format

**Comment by arjuncgi** [comment]
@emmaholmbergohlsson Thank you for the solution!

Yes I did migrated folder in data/databases - With Only neo4j(Which was my Application DB name).
After this I didn't do the migration for `system` database - This was the issue.

After doing migration for `system` database migration - It resolved my issue and able to upgrade!

Thanks again!
I'm closing this issue.

**Comment by jonomacx** [comment]
In case anyone is reading this and is still stuck, please check this solution which worked for me, even tho I believed I had removed the btree indexes prior to dump:

https://stackoverflow.com/questions/76420810/unabletomigrateexception-the-selected-target-store-format-af4-3-0-introduced

**Comment by emmaholmbergohlsson** [comment]
Hey @jonomacx,
If you think something is wrong with the migration to 5.x in regards to the btree indexes we would be happy to look into it more.
Do still have the old store and can reproduce it? In that case please open a new issue and we'll try to figure out what went wrong
