### ISSUE TITLE
RuntimeUnsupportedError:Did not find `  UNNAMED0` in the slot configuration

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13216]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.8.0 Community
operating system: windows 10
API：Cypher version 9
query:create a=()-[:T]->(),p=({k:exists{return a}})-[:T]->() return 1
error message:
Neo.ClientError.Statement.RuntimeUnsupportedError
Did not find `  UNNAMED0` in the slot configuration

Expected behavior:
The query should run successfully and return 1.

Actual behavior:
The query failed.

**Comment by nadja-muller** [comment]
Thank you for the report. We will have a look.

**Comment by ljhhuxiaoba** [comment]
This bug is also present in the version 5.9.0

**Comment by arnefischereit** [comment]
Hi @ljhhuxiaoba,

Thank you for your report and the thorough testing.

The query `create a=()-[:T]->(),p=({k:exists{return a}})-[:T]->() return 1` that you used contains a cross-reference (to define the second pattern, we need to evaluate `a` from the first pattern).

Such a cross-reference is ill-defined in that its result is non-deterministic: Should we evaluate the first or the second first? What about circular dependencies?

We have detailed such [in the documentation](https://neo4j.com/docs/cypher-manual/current/clauses/create/#reusing-variables-properties) and decided to forbid cross-references in `CREATE` in the next major version of Neo4j and therefore [deprecated them](https://neo4j.com/docs/cypher-manual/5/deprecations-additions-removals-compatibility/#_deprecated_features) in the current versions.

We also investigated issuing a better error message (the `UNNAMED0` is the first node of `a`). But we found no way for this without restricting use-cases which currently work. To not break currently working use-cases, we will therefore leave the product as is.

I hope that clarifies the current behaviour. I will close the issue but if you disagree, please feel free to comment and/or open a new issue on this.

Again, thanks for reporting the issue.

Regards,

Arne
