### ISSUE TITLE
Unexpected Error about "Variable not defined"

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13221]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.9.0 Community
operating system: windows 10
API：Cypher version 9
query:MATCH ({k:size([(:L)-[]-()|1])}) RETURN 1 
error message:
Neo.ClientError.Statement.SyntaxError
Variable `  UNNAMED0` not defined (line 1, column 17 (offset: 16))
"MATCH ({k:size([(:L)-[]-()|1])}) RETURN 1"
                 ^

But if I execute another query:"MATCH ({k:size([()-[]-()|1])}) RETURN 1",then it can run successfully without the label restriction ":L".I think this is very strange.

Expected behavior:
The query should run successfully.

Actual behavior:
The query failed.

**Comment by pontusmelke** [comment]
Thanks @ljhhuxiaoba 
Looks like an issue alright, we will look into it.

Best regards,
Pontus

**Comment by arnefischereit** [comment]
Hi @ljhhuxiaoba,

Thanks again for testing our product so thoroughly and reporting this issue. We have implemented a fix for it which will be part of the next release, 5.11.

I am closing this issue, should the problem persist (after the release of 5.11) or reappear please reopen this issue or open a new one.

Regards,

Arne
