### ISSUE TITLE
Variable shadowing error about constant

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13220]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.8.0 Community
operating system: windows 10
API：Cypher version 9
query:return 1 order by exists{return 1}
error message:
Neo.ClientError.Statement.SyntaxError
The variable `1` is shadowing a variable with the same name from the outer scope and needs to be renamed (line 1, column 33 (offset: 32))
"return 1 order by exists{return 1}"
                                 ^

But the const '1' is not a variable,so I think the shadowing error is not expected.

Expected behavior:
The query should run successfully and return 1.

Actual behavior:
The query failed.

**Comment by sherfert** [comment]
@ljhhuxiaoba 
Thank you for your bug report.

In Cypher, every column needs a variable name, and even if the query does not provide one in a `RETURN`, one will be generated. The query you provided is equivalent to 

```
RETURN 1 AS `1` ORDER BY EXISTS { RETURN 1 AS `1` }
```

In the case where the variable name is not provided, the error message is slightly unhelpful.
Nevertheless the shadowing issue needs to be circumvented by the user currently, in this case by explicitly aliasing one of the two constants `1`, e.g.  like this:

```
RETURN 1 ORDER BY EXISTS { RETURN 1 AS one }
```

I hope that makes sense and let me know if you agree with this resolution.

**Comment by ljhhuxiaoba** [comment]
Thanks for your explanation.
