### ISSUE TITLE
datetime function not thead-safe under load

### ISSUE THREAD

**Issue by McSwig** [neo4j/neo4j#13227]
When testing the insertion of a few thousand nodes into neo4j that each have a unique timestamp , when we do the insertions in parallel we find that in a small random number of cases the incorrect datetime is inserted. The datetime inserted appears to belong to one of the other nodes that is being inserted in parallel. 

This behaviour can be seen in 5.8,0 and 5.9.0 but the issue does not happen in 5.1.0.

- Neo4j version: 5.9.0
- Operating system: Ubuntu 16.04 - Docker
- API/Driver: Java API - neo4j-java-driver:5.4.0 

- **Steps to reproduce**
- Use parallel connections to Neo4j to insert 2000 nodes containing a datetime into Neo4j

e,g,
CREATE (folder:`MyNode` {globalId: $fId, createdUTC: datetime($fCreated)}) 
:param fCreated => '2021-05-27T09:41:08.173152900'

- Expected behavior : 

Node contains the correct timestamp

{
  "identity": 432,
  "labels": [
    "MyNode"
  ],
  "properties": {
    "globalId": "7a3b718e-bacd-43f5-bf09-2636d6ba4570",
    "createdUTC": "2021-05-27T09:41:08.173152900Z"
  },
  "elementId": "432"
} 

- Actual behavior :

In a small number of cases the incorrect datetime is inserted, this datetime appears to be coming from another node that was being inserted around the same time.
 
{
  "identity": 432,
  "labels": [
    "MyNode"
  ],
  "properties": {
    "globalId": "7a3b718e-bacd-43f5-bf09-2636d6ba4570",
    "createdUTC": "2021-05-27T09:41:07.923142000Z"
  },
  "elementId": "432"
}

**Comment by McSwig** [comment]
The issue can be replicated using the spring boot test below - versions of Neo4j 5.4.0 and onwards to 5.9.0 are failing this test


@Slf4j
@SpringBootTest
@Testcontainers
public class DateTimeIssue {

    @Container
    private static final Neo4jContainer<?> neo4jContainer = new Neo4jContainer<>(DockerImageName.parse("neo4j:5.4.0"))
            .withLabsPlugins(Neo4jLabsPlugin.APOC)
            .withoutAuthentication();

    @DynamicPropertySource
    private static void registerProperties(DynamicPropertyRegistry registry) {
        registry.add("spring.neo4j.uri" , neo4jContainer::getBoltUrl);
    }

    @Autowired
    Neo4jClient neo4jClient;

    private final int NUM_NODES = 1000;

    @Test
    public void generateAndTest() {

        ExecutorService executorService = Executors.newFixedThreadPool(16);

        AtomicInteger nodes = new AtomicInteger(0);

        LocalDateTime baseTime = LocalDateTime.of(2023, Month.JUNE,27,18,26,57);
        for(int i = 0; i < NUM_NODES; i++) {
            int finalNanos = i;
            executorService.execute(() -> {
                LocalDateTime testTime = baseTime.plusNanos(finalNanos);
                String create = "CREATE (Test { myId: \"" + testTime + "\", myDate: datetime(\"" + testTime + "\")})";
                neo4jClient.query(create).run();
                nodes.getAndIncrement();
            });
        }

        while(nodes.get() != NUM_NODES);

        long incorrectDateTimeNodes = (Long) neo4jClient.query("MATCH (n) WHERE datetime(n.myId) <> n.myDate RETURN count(n) AS incorrectDateTimes").fetch().one().get().get("incorrectDateTimes");

        assertThat(incorrectDateTimeNodes,is(0L));
    }

}

**Comment by pontusmelke** [comment]
@McSwig Thanks for reporting this. We have begun investigating the issue.

Best regards,
Pontus

**Comment by pontusmelke** [comment]
@McSwig we have identified and merged a fix. The issue should be resolved in the next release.

Sorry for the inconvenience and thanks a lot for reporting the issue!

Best regards,
Pontus

**Comment by ikwattro** [comment]
@pontusmelke can you confirm it's shipped in 5.10 ? I don't see a mention of it in the changelog https://github.com/neo4j/neo4j/wiki/Neo4j-5-changelog

**Comment by McSwig** [comment]
@pontusmelke @ikwattro Thanks for your help, the test in the comments above now passes using release 5.10.0
