### ISSUE TITLE
ExecutionFailed when using subquery in SET clause

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13226]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.9.0 Community
operating system: windows 10
API：Cypher version 9
query:set (case when exists{return 1} then null end).k=1 return 1
error message:
Neo.DatabaseError.Statement.ExecutionFailed
Unknown expression type during transformation (class org.neo4j.cypher.internal.ir.ast.ExistsIRExpression)

But if I execute another query:"set (case when true then null end).k=1 return 1",then it can run successfully.

Expected behavior:
The query should run successfully and return 1.

Actual behavior:
The query failed.

**Comment by ljhhuxiaoba** [comment]
The same error also occurs in REMOVE.

**Comment by pontusmelke** [comment]
Thanks for reporting @ljhhuxiaoba! We'll investigate.

Best regards,
Pontus

**Comment by arnefischereit** [comment]
Hi @ljhhuxiaoba,

Thank you for reporting the issue. We have implemented a fix for it which will be part of the next releases, 5.11 and 4.4.24.

I am closing this issue. Should the problem persist after the next release or reappear please reopen this issue or open a new one.

Regards,

Arne
