### ISSUE TITLE
Can't stop database with hyphen in name

### ISSUE THREAD

**Issue by christian-becker-ta** [neo4j/neo4j#13230]
- Neo4j version: 5.9.0
- Operating system: Windows 11
- API/Driver: Neo4j Desktop

I want to stop a database with a hyphen in the name. 
Neo4j is not able to stop it and throws an error :
"STOP DATABASE maintenancedata-de"
Invalid input '-': expected ".", "NOWAIT", "WAIT" or <EOF> (line 1, column 30 (offset: 29))
"STOP DATABASE maintenancedata-de"
                                                        ^
Other databases without hyphen can be stopped.

**Comment by mnd999** [comment]
`-` is not a valid character in a database name, it need to be quoted with backticks e.g.

```
STOP DATABASE `maintenancedata-de`
```

See https://neo4j.com/docs/cypher-manual/current/syntax/naming/#symbolic-names-escaping-rules
