### ISSUE TITLE
ExecutionFailed Error about namespacing bug

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13232]
I execute a query on my empty neo4j database ,and an error occurs.

Neo4j version: 5.9.0 Community
operating system: windows 10
API：Cypher version 9
query:unwind [1] AS a0 MATCH (n0) RETURN DISTINCT *,a0 AS a1 ORDER BY a1
error message:
Neo.DatabaseError.Statement.ExecutionFailed
There was a cycle in names: HashSet(a1, a0). This is likely a namespacing bug.

Expected behavior:
The query should run successfully.

Actual behavior:
The query failed.

**Comment by pontusmelke** [comment]
Hi @ljhhuxiaoba,
Thanks for reporting this issue. We will look into it.

Best regards,
Pontus

**Comment by inmost-light** [comment]
@ljhhuxiaoba 
Thank you for reporting, this should be fixed in 5.12.
