### ISSUE TITLE
A constant Conflicts occurred 

### ISSUE THREAD

**Issue by jinsheng200303** [neo4j/neo4j#13238]
## Guidelines

The community version and the desktop version are downloaded at the same time. The community version can be used normally, but the desktop version keeps showing ：
Conflicts occurred 
DBMS Movie DBMS can not be started due to conflicts with external processes.
To fix this problem, let us change these port configurations:
bolt: 7688 → 7689.

However, Even if I click fix configuration, the prompt box still keeps popping up.

## Example bug report

**Neo4j Desktop Version:** 1.5.7
**Neo4j community Version:** 5.6.0
**Operating System:** macOS 11.6.1

### Steps to reproduce
1. stop Neo4j community
2. open Neo4j Desktop
3. Start a database
4. Pop-up alert box
5. Keep clicking the button “fix configuration”, but it doesn't work, and the alert keeps popping up

I sincerely hope that someone can help me solve this problem

**Comment by mnd999** [comment]
Thanks for your report, unfortunately this is not the correct repository for Neo4j Desktop. Please open an issue [here](https://github.com/neo4j-devtools/neo4j-desktop)

**Comment by gabirojo** [comment]
Hello, I have the same problem and same situation with the community and desktop.

I can enter into the browser but not into the projects or DBMS for neo4j Desktop.
bolt: 7688 → 7689.

Did anyone could fix it?
