### ISSUE TITLE
ExecutionFailed:Cannot invoke "org.neo4j.values.AnyValue.isSequenceValue()"

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13239]
I execute a query on my empty neo4j database ,and an error occurs.

Neo4j version: 5.9.0 Community
operating system: windows 10
API：Cypher version 9
query:merge (n{k:([()<-[r0]-()|1] <= [1])}) return 1
error message:
Neo.DatabaseError.Statement.ExecutionFailed
Cannot invoke "org.neo4j.values.AnyValue.isSequenceValue()" because "v1" is null

Expected behavior:
The query should run successfully or at least it shouldn't give such confusing information.

Actual behavior:
The query failed with confusing information

**Comment by pontusmelke** [comment]
@ljhhuxiaoba Thanks for reporting, we'll have a look.

Best regards,
Pontus

**Comment by Dunfluff** [comment]
@ljhhuxiaoba 
This is now scheduled to be fixed for 5.13, thank you for informing us of this issue. Please inform if the problem persists after the 5.13 update.

Kind regards,
Lars
