### ISSUE TITLE
ExecutionFailed:Cannot invoke "org.neo4j.values.AnyValue.ternaryEquals(org.neo4j.values.AnyValue)" because "l" is null

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13242]
I execute a query on my empty neo4j database ,and an error occurs.

Neo4j version: 5.9.0 Community
operating system: windows 10
API：Cypher version 9
query:merge (n0{k:[()<-[]-()|null] = [1]}) return 1
error message:
Neo.DatabaseError.Statement.ExecutionFailed
Cannot invoke "org.neo4j.values.AnyValue.ternaryEquals(org.neo4j.values.AnyValue)" because "l" is null

Expected behavior:
The query should run successfully.

Actual behavior:
The query failed

**Comment by pontusmelke** [comment]
Thanks @ljhhuxiaoba,
we will have a look!

Best regards,
Pontus

**Comment by arnefischereit** [comment]
Hi @ljhhuxiaoba,

This is the same issue as #13239 and should therefore also be fixed as part of 5.13.

Regards,

Arne
