### ISSUE TITLE
UnknownError :key not found

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13244]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.9.0 Community
operating system: windows 10
API：Cypher version 9

To reproduce:
create ()-[:T{k:1}]->();
create ({k:exists{MATCH ()-[r0]->() WHERE reduce(a=true,b in [isEmpty(properties(r0{.k}))]|a) RETURN 1}});

error message:
Neo.DatabaseError.General.UnknownError
key not found: k

Expected behavior:
The query should run successfully.

Actual behavior:
The query failed.

**Comment by pontusmelke** [comment]
Thanks for reporting!

Best regards,
Pontus

**Comment by arnefischereit** [comment]
Hi @ljhhuxiaoba,

This is the same issue as #13108 and should therefore also be fixed as part of 5.11.

Regards,

Arne
