### ISSUE TITLE
SyntaxError:Coercion of list to boolean is not allowed.

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13240]
I execute a query on my empty neo4j database ,and an error occurs.

Neo4j version: 5.9.0 Community
operating system: windows 10
API：Cypher version 9
query:WITH null AS a0 WHERE reduce(a=null,b in [toBooleanList(null)[0]]|a) RETURN 1
error message:
Neo.ClientError.Statement.SyntaxError
Coercion of list to boolean is not allowed. Please use `NOT isEmpty(...)` instead. (line 1, column 23 (offset: 22))
"WITH null AS a0 WHERE reduce(a=null,b in [toBooleanList(null)[0]]|a) RETURN 1"
                       ^

And it is worth noting that another query "WITH 1 AS a0 WHERE reduce(a=null,b in [toBooleanList(null)[0]]|a) RETURN 1" can run successfully.It is strange because I just replace the "null" with "1".

Expected behavior:
The query should run successfully.

Actual behavior:
The query failed.

**Comment by pontusmelke** [comment]
@ljhhuxiaoba thanks for reporting!

We will have a look!

Best regards,
Pontus

**Comment by sherfert** [comment]
We have a fix and it will be part of the upcoming neo4j 5.13 release.
