### ISSUE TITLE
UnknownError about sorted plan

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13245]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.9.0 Community
operating system: windows 10
API：Cypher version 9

To reproduce:
RETURN DISTINCT null AS a2, substring([null][count{RETURN stDev(479716850) ORDER BY null}], null, percentileDisc(null, 0));

error message:
Neo.DatabaseError.General.UnknownError
Expected a sorted plan but got
.aggregation(Seq(), Seq("stDev($`  AUTOINT1`) AS `stDev(479716850)`"))
.argument("a2")
.build()

Expected behavior:
The query should run successfully.

Actual behavior:
The query failed.

**Comment by pontusmelke** [comment]
Good morning,

We will look at it!

Best regards,
Pontus

**Comment by inmost-light** [comment]
Thank you for reporting, should be fixed in 5.13.
