### ISSUE TITLE
ExecutionFailed : Failed rewriting DesugaredMapProjection

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13252]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.9.0 Community
operating system: windows 10
API：Cypher version 9

To reproduce:
DETACH DELETE null with * RETURN {k: 1} AS a0 ORDER BY properties(a0{.k});

error message:
Neo.DatabaseError.Statement.ExecutionFailed
Failed rewriting DesugaredMapProjection(Variable(a0),List(LiteralEntry(PropertyKeyName(k),Property(Variable(a0),PropertyKeyName(k)))),false)
Tried using children: MapExpression(Vector((PropertyKeyName(k),AutoExtractedParameter(  AUTOINT0,Integer,UnknownSize)))),List(LiteralEntry(PropertyKeyName(k),Property(MapExpression(Vector((PropertyKeyName(k),AutoExtractedParameter(  AUTOINT0,Integer,UnknownSize)))),PropertyKeyName(k)))),false

Expected behavior:
The query should run successfully.

Actual behavior:
The query failed.

**Comment by smietana** [comment]
Thank you! We will investigate this.

**Comment by blouerat** [comment]
@ljhhuxiaoba that was a fun one, thank you! I merged a fix last week, it will be available in the next release.

**Comment by ljhhuxiaoba** [comment]
Thanks for your reply and can you briefly explain the cause of the bug, I'm curious as to what went wrong.

**Comment by blouerat** [comment]
Of course. When analysing the dependencies of an expression used in `ORDER BY`, if the said expression is the result of a projection, we first try and rewrite it to its original value. For example in `RETURN actor AS keanu ORDER BY keanu{.name}`, `keanu{.name}` would get rewritten to `actor{.name}`.
We had a bug where we would try to apply the same logic when the original value wasn't merely a variable but a more complex expression. For example in `RETURN {'name': 'Keanu Reeves'} AS keanu ORDER BY keanu{.name}` we would try to rewrite `keanu{.name}` to `{'name': 'Keanu Reeves'}{.name}`, which is not valid, hence the exception.
Hope this makes sense!

**Comment by ljhhuxiaoba** [comment]
Thank you for your patience!
