### ISSUE TITLE
ExecutionFailed : Tried to alias non-existing slot 'n0'  with alias 'a5'

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13251]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.9.0 Community
operating system: windows 10
API：Cypher version 9

To reproduce:
Create (n0) Create (n3{k:exists{RETURN distinct n0 AS a5}}) RETURN 1;

error message:
Neo.DatabaseError.Statement.ExecutionFailed
Tried to alias non-existing slot 'n0'  with alias 'a5'

Expected behavior:
The query should run successfully.

Actual behavior:
The query failed.

**Comment by smietana** [comment]
Thank you! We will investigate this.

**Comment by sherfert** [comment]
Hi, this has been fixed in version 5.12.

**Comment by ljhhuxiaoba** [comment]
Could I ask that what the root cause of the issue is?
