### ISSUE TITLE
ExecutionFailed Error about NoValue cast

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13258]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.9.0 Community
operating system: windows 10
API：Cypher version 9

To create the graph:
create (n4 :L2)-[r0:T]->(n5);

To reproduce:
MATCH p1=(n4 :L2)-[r0]-(n5) WHERE (count{OPTIONAL MATCH (n6)<-[r0]-(n1)-[r1]-(n2:L3) MATCH (n0 :L3)-[r0]-(n1) RETURN 1} > null) RETURN 1;

error message:
Neo.DatabaseError.Statement.ExecutionFailed
class org.neo4j.values.storable.NoValue cannot be cast to class org.neo4j.values.virtual.VirtualNodeValue (org.neo4j.values.storable.NoValue and org.neo4j.values.virtual.VirtualNodeValue are in unnamed module of loader 'app')

Expected behavior:
The query should run successfully.

Actual behavior:
The query failed.

**Comment by phil198** [comment]
Thanks for letting us know. We will investigate.

**Comment by JonasHolgersson** [comment]
Hi @ljhhuxiaoba , thanks for reporting! This has been fixed and will be included in the 5.13 release.

**Comment by ljhhuxiaoba** [comment]
I ran into another bug that looks the same(same error message), but I can't be sure.

To reproduce:
CREATE ()<-[r0:T]-()
OPTIONAL MATCH ()<-[r0{k:"p"}]-(),(n0) OPTIONAL MATCH (n1)-[r1]->() MATCH p0=(n0)-[r1]->() RETURN 1
