### ISSUE TITLE
ExecutionFailed : Introduced variables have not been computed yet

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13253]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.9.0 Community
operating system: windows 10
API：Cypher version 9

To reproduce:
REMOVE (case when exists{OPTIONAL MATCH (n2)<-[r2]-(n1 :L4) OPTIONAL MATCH ()-[:T1{k:true}]->(n3:L2) RETURN DISTINCT 1 AS a2} then null end).k RETURN 1;

error message:
Neo.DatabaseError.Statement.ExecutionFailed
Introduced variables have not been computed yet

Expected behavior:
The query should run successfully.

Actual behavior:
The query failed.

**Comment by smietana** [comment]
Thank you! We will investigate this.

**Comment by sherfert** [comment]
This was fixed in version 5.11
