### ISSUE TITLE
ExecutionFailed Error : key not found: VariableSlotKey(n0)

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13250]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.9.0 Community
operating system: windows 10
API：Cypher version 9

To reproduce:
Create (n0{k:1})-[:T0]->() Create ()-[:T1]->({k:count{with n0.k as a return a}}) RETURN 1;

error message:
Neo.DatabaseError.Statement.ExecutionFailed
key not found: VariableSlotKey(n0)

But another query "Create (n0{k:1})-[:T0]->() Create ()-[:T1]->({k:count{return n0.k as a}}) RETURN 1" can run successfully,which is very confusing.

Expected behavior:
The query should run successfully.

Actual behavior:
The query failed.

**Comment by smietana** [comment]
Thank you! We will investigate this.

**Comment by sherfert** [comment]
Hi, this has been fixed in version 5.12.
