### ISSUE TITLE
How  to create new database in neo4j

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13264]
![image](https://github.com/neo4j/neo4j/assets/67541048/ea42a24d-12b1-4d9d-bcca-67eabd17b7d4)
I get the above error when I create a new database and I would like to know how I can make it.

**Comment by Lojjs** [comment]
@ljhhuxiaoba Multiple databases is an enterprise feature and based on the left menu in your screen shot it looks like you are using Neo4j community, so that is why. The syntax of the Cypher command is correct.

Best regards Louise, Neo4j Cypher team

**Comment by hetao8** [comment]
@Lojjs I also get an error when using create database in the enterprise version,error :CREATE DATABASE is not supported, for more info see https://aura.support.neo4j.com/hc/en-us/articles/360050567093

**Comment by Lojjs** [comment]
@hetao8 Yes it is also correct that it is not supported on Aura, although in the reported case it was community edition

**Comment by hetao8** [comment]
@Lojjs So, can I understand that it is impossible to create multiple databases under a single instance?

**Comment by Lojjs** [comment]
Exactly, that functionality is not supported in Aura nor in community edition of Neo4j

**Comment by hetao8** [comment]
@Lojjs I understand, thank you
