### ISSUE TITLE
ExecutionFailed : Did not find `r1` in the pipeline information

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13260]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.9.0 Community
operating system: windows 10
API：Cypher version 9

To reproduce:
Create ()<-[r1:T1]-() Create ({k:count{WITH r1 ORDER BY r1}}) RETURN 1;

error message:
Neo.DatabaseError.Statement.ExecutionFailed
Did not find `r1` in the pipeline information

It is worth noting that the query "Create ()<-[r1:T1]-() Create ({k:count{WITH r1}}) RETURN 1" can run successfully without the ORDER BY clause,which is strange.

Expected behavior:
The query should run successfully.

Actual behavior:
The query failed.

**Comment by phil198** [comment]
Thanks for letting us know. We will investigate.

**Comment by arnefischereit** [comment]
Hi @ljhhuxiaoba,

Thank you for reporting the issue. We have implemented a fix for it which will be part of the next releases, 5.12 and 4.4.26.

I am closing this issue. Should the problem persist after the next release or reappear please reopen this issue or open a new one.

Regards,

Arne
