### ISSUE TITLE
Unexpected result when querying with empty property

### ISSUE THREAD

**Issue by Lincyaw** [neo4j/neo4j#13262]
Hello, when I was playing with Cypher, I triggered an error

- Neo4j version: 5.9.0
- Operating system: Ubuntu 22.04
- API/Driver: Python

In this query, I get an empty answer. 

```cypher
MATCH p=(v5 {} )-[*..2 {roles: "Sen. Kevin Keeley"}]-() RETURN p
```

<img width="838" alt="image" src="https://github.com/neo4j/neo4j/assets/53161583/e21067e7-e71d-435f-88a3-e19d11ac795e">

But if I delete the `roles` property. The query became 

```cypher
MATCH p=(v5 {} )-[*..2 {}]-() RETURN p
```
And it triggers the following error, which I think it is unexpected?

<img width="835" alt="image" src="https://github.com/neo4j/neo4j/assets/53161583/500fcce2-9f7f-4a2f-89f4-866291e1a1ba">

You can create the graph by `:play movie-graph` in neo4j

**Comment by phil198** [comment]
Hello. Thanks for letting us know. We'll investigate.

**Comment by arnefischereit** [comment]
Hi @Lincyaw,

Thank you for reporting the issue. We have implemented a fix for it which will be part of the next releases, 5.11 and 4.4.24.

I am closing this issue. Should the problem persist after the next release or reappear please reopen this issue or open a new one.

Regards,  

Arne
