### ISSUE TITLE
neo4j backup '*' should ignore composite databases

### ISSUE THREAD

**Issue by ikwattro** [neo4j/neo4j#13265]
When using '*' for the database parameter during online backups, composite databases are picked up and break backup procedure

**Neo4j Version:** 5.9.0-enterprise
**Operating System:** Centos
**API:** Irrelevant

### Steps to reproduce

1. Create a composite database
2. Execute an online backup using `'*'` for the `database` parameter

### Expected behavior

Composite databases should be ignored and all concrete databases should be backed up

### Actual behavior

Backup fails after encountering first composite database with 

```
2023-07-27 21:35:33.900+0000 INFO  [c.n.c.p.h.HandshakeClientInitializer] Lost connection to 127.0.0.1/127.0.0.1:6362 [DBMS version:2.0]
org.neo4j.cli.CommandFailedException: Execution of backup failed. Database 'composer' was not found or not running
```

**Comment by tonbut** [comment]
@ikwattro we have a fix for this merged now and should appear in next release. Thank you for reporting!
