### ISSUE TITLE
Kill transactions with only one query in Neo4j 5

### ISSUE THREAD

**Issue by danielemansillo** [neo4j/neo4j#13266]
### Problem description
In Neo4j 4 it was possible to kill running queries/transactions with one concise command, in Neo4j 5 it is not possible anymore.

Neo4j 4 queries example:
```cypher
CALL dbms.listQueries() YIELD queryId
WITH collect(queryId) AS q
CALL dbms.killQueries(q) YIELD queryId
RETURN queryId;
```
Neo4j 4 transactions example:
```cypher
CALL dbms.listTransactions() YIELD transactionId
WITH collect(transactionId) AS t
CALL dbms.killTransactions(t) YIELD transactionId
RETURN transactionId;
```

### Expected outcome
I would like it to be possible also in Neo4j 5, maybe with something similar:

```cypher
SHOW TRANSACTIONS YIELD transactionId
WITH collect(transactionId) AS t
TERMINATE TRANSACTIONS(t) YIELD transactionId
RETURN transactionId;
```

**Comment by ikwattro** [comment]
It is possible : 

```
SHOW TRANSACTIONS
YIELD transactionId AS txId
TERMINATE TRANSACTION txId
YIELD message
RETURN txId, message
```

As explained in the docs https://neo4j.com/docs/cypher-manual/5/clauses/transaction-clauses/#query-combine-tx-commands

**Comment by danielemansillo** [comment]
Thank you!
