### ISSUE TITLE
saving incremental changes

### ISSUE THREAD

**Issue by siddhsql** [neo4j/neo4j#13278]
Hello,

I am new to this library.

Is it possible to save (and load) incremental changes to a graph with this library? Imagine I have a graph with a billion nodes.
1. I save the graph. 
2. I make a small modification e.g., adding or removing a node
3. I save it again
I don't want step 3 to perform a full rewrite of the entire graph. that would kill the performance. And conversely the library should be able to reconstruct the graph from stream of incremental changes. Does Neo4j support this? How? Any code samples that demonstrate this? Thanks.

**Comment by klaren** [comment]
Hello,

Neo4j uses transactions to make changes to the graph. Once a transaction is committed, that data is saved and persistent on the hard drive. There is no need for manually saving or anything similar.

I recommend you use [neo4j-admin import](https://neo4j.com/docs/operations-manual/current/tools/neo4j-admin/neo4j-admin-import/) if the initial data is large. This is an offline step that is optimized to digest data as fast as possible. After this, just startup Neo4j and it will be ready to accept transactions with modifications.

Regarding the full rewrite, Neo4j will only write the data that was modified. Most small modifications are complete within milliseconds, which includes saving to persistent storage.

**Comment by siddhsql** [comment]
Thanks. could you point me to the library that is being used for
persistence? I am looking for a library that I can use in my application
for saving incremental changes.
