### ISSUE TITLE
Wrong timezone and current time

### ISSUE THREAD

**Issue by Podbrushkin** [neo4j/neo4j#13277]
I discovered there is no way to get correct current datetime in neo4j. All of these return wrong time (3 hrs behind): 
```
return localdatetime.realtime(), datetime.realtime(), datetime(), localdatetime(), datetime({epochmillis:timestamp()})
```
Even though CMD, Powershell, Java, MySQL, system tray clock - all of them output current time correctly. I don't see why neo4j can't do the same. Looks like it can't determine system time zone properly.

Setting `db.temporal.timezone=+03:00` helps to resolve this issue, but I don't see why is this necessary. Neo4j Desktop has so many similarities to what is called bloatware, and still it fails in such a simple function, this is disappointing.

**DBMS Version:** 5.10.0
**Operating System:** Windows 11
**API:** Neo4J Desktop + Browser
In Windows Date & time settings both `Set time automatically` and `Set time zone automatically` are enabled.

**Comment by klaren** [comment]
Hello, and thanks for reaching out.

You have found the setting `db.temporal.timezone`, which is the setting that controls what timezone to use.

https://neo4j.com/docs/operations-manual/5/configuration/configuration-settings/#config_db.temporal.timezone
> Database timezone for temporal functions. All Time and DateTime values that are created without an explicit timezone will use this configured default timezone.

The default value of this is `Z`(otherwise known as `UTC` or `+00:00`). So this works exactly as expected.

If you would like to get a time for a specific time zone, [all of the time methods accept a timezone parameter](https://neo4j.com/docs/cypher-manual/current/functions/temporal/#functions-date), e.g. 

```
return localdatetime.realtime('+03:00'), 
    datetime.realtime('+03:00'),
    datetime({timezone: '+03:00'}),
    localdatetime({timezone: '+03:00'});
```
or you can just configure  `db.temporal.timezone` to avoid having to specify it everywhere.

**Comment by Podbrushkin** [comment]
Thank you for your response.

> The default value of this is Z

Why is it Z? Default value should be fetched from the system, this is a common behavior. Any other value is wrong, unless it was explicitly specified by user.
Defaulting it to Z means "you should set time zone manually" and this is not a pleasant experience.
I don't know any other application which requires explicitly setting a time zone. 

> all of the time methods accept a timezone parameter or you can just configure db.temporal.timezone

Sounds like hardcoding a time zone. If I'm using embedded neo4j server, my personal time zone will end up in project code and in github repo? Doesn't seem right.

**Comment by klaren** [comment]
If you deploy a neo4j server to the cloud having `Z` as default is common practice. The timezone is then deferred to the client's system time, so if you have users in different time zones they will all observe the time in their respective local time.

Arguably this does not apply to embedded, but you can easily address that by passing the following to the `DatabaseManagementServiceBuilder`:

```
.setConfig(GraphDatabaseSettings.db_temporal_timezone, ZoneId.systemDefault())
```
Then you don't have to hardcode any timezone.

**Comment by Podbrushkin** [comment]
Maybe there's something I don't understand. So, is it just my personal expectations not meeting reality, or is it an issue which needs to be solved?

I've just checked MySQL, PostgreSQL and H2 databases, all of them output current time properly without explicitly configuring time zone. Is it a bad practice? Is neo4j different in some way which I don't understand?
Is there any other piece of software which also requires manually setting time zone?
I honestly don't see how it can be my personal problem and not poor decision to default time zone to Z instead of system's default time zone.

**Comment by klaren** [comment]
Behavior is explained and a solution is given.
