### ISSUE TITLE
shortestPath function seems to process strangely with the WHERE clause containing a pattern

### ISSUE THREAD

**Issue by bruucewayne** [neo4j/neo4j#13286]
## Specs
- Neo4j 5.9.0 community image running in a container
- Ubuntu 18.04.6

## My graph description
My graph only has one type of relationship [:Relationship], and one type of node (:Node).

## What I want to do
My goal is to to find the shortest path between two nodes, but I do not want the shortest path returned to contain this pattern:  
**(:Node)<-[:Relationship]-(:Node)-[:Relationship]->(:Node)**

I have read [here](https://neo4j.com/docs/cypher-manual/current/patterns/concepts/) that:

> If the MATCH clause of the shortestPath function includes a WHERE clause, a shortest path that satisfies the WHERE clause conditions is returned if one exists.

so this should be possible, and I have tested without using the shortestPath function that paths that verify this requirement indeed exist in my graph.

## What I have tried
I have tested mutliple ways to filter the shortest path returned, but none of them were successful.  
1. I tried using a combination of *none()* predicate function and an *exists{}* subquery:

        match p = shortestPath((startNode:Node {id : 1})-[:Relationship*]-(endNode:Node {id : 2})) 
        where none(pathNode in nodes(p) where exists{
        match (n1:Node)<-[:Relationship]-(pathNode)-[:Relationship]->(n2:Node)
        where ((n1 in nodes(p)) and (n2 in nodes(p)))
        }) 
        return p

2. as well as using *isEmpty()* predicate function :

        match p = shortestPath((startNode:Node {id : 1})-[:Relationship*]-(endNode:Node {id : 2}))
        where isEmpty ([(n1)<-[:Relationship]-(n2)-[:Relationship]->(n3) where ((n1 in nodes(p)) and (n2 in nodes(p)) and (n3 in nodes(p))) | 
        n2.id])
        return p

## Expected behavior
I expect the queries to return the shortestPath not containing the specified pattern **(the same queries not using the shortestPath() function work properly)**

## Actual behavior, bug report
- My try 1. (see above) query returns 'Unknown expression type during transformation (class org.neo4j.cypher.internal.ir.ast.ExistsIRExpression)'
- try 2. (see above) returns 'Unknown expression type during transformation (class org.neo4j.cypher.internal.ir.ast.ListIRExpression)'

I do not understand why the queries above do not work properly. The shortestPath() function seems to be the problem here.  
I have also asked this question [here]( https://stackoverflow.com/questions/76967760/how-to-find-the-shortest-path-not-containing-a-pattern/76971083#76971083)  
Any help would be appreciated, thank you.

**Comment by Dunfluff** [comment]
Thank you for waiting, this was a fairly complex problem but it has now been fixed and will be available in the 5.15 release.
