### ISSUE TITLE
[^5.10.0] Variable not defined in List Comprehension in Match of Node Property

### ISSUE THREAD

**Issue by CelineWuest** [neo4j/neo4j#13284]
When running the following query:
```cypher
WITH 0 AS n0 MATCH ({n1:[x IN [] | 0]}) RETURN 0
```

I encountered the following error:
```
Neo4jError: Neo.ClientError.Statement.SyntaxError (Variable `x` not defined (line 1, column 39 (offset: 38))
"WITH 0 AS n0 WITH 1 AS n3 MATCH ({n1:[x IN [] | 0]}) RETURN 0"
                                       ^
```

I believe the query mentioned above is semantically and syntactically correct and thus no error should be thrown here.

I encountered this issue when testing queries against the **Neo4j 5.11.0 enterprise version** in a Docker container running **alpine v.3**.

The issue also arised in **Neo4j 5.10.0**, but not in **5.9.0**.

### Steps to reproduce
Run the following queries and observe it throws an error:
```cypher
WITH 0 AS n0 MATCH ({n1:[x IN [] | 0]}) RETURN 0
```

### Expected behavior
The query should run successfully

### Actual behavior
The query fails with the error message ``[...]SyntaxError (Variable `x` not defined[...]``

**Comment by gem-neo4j** [comment]
Hi! This has now been fixed and will be released in 5.13 and 4.4.27 :) Thanks!
