### ISSUE TITLE
Bloom > Unable to export to csv

### ISSUE THREAD

**Issue by adriens** [neo4j/neo4j#13289]
## :grey_question: About

In Bloom I'm not able to export as `csv`... but I cannot find the button to achieve the export.

## :information_source: Environment

- Env : Neo4J Desktop
- Neo4J version : `5.11.0`
- Bloom up-to-date embedded w/ Neo4J Desktop Edition
- OS : `Linux Mint 21.2 Victoria \n \l`

## :footprints: Steps to reproduce

1. Startup database
2. Launch Bloom
3. Open/create a perspective with data
4. Right-click to Export to csv
5. Get the wozard
6. Do not find how to achieve the export
![image](https://github.com/neo4j/neo4j/assets/5235127/59f62f72-9943-4962-b305-6a0cfec74f05)

**Comment by mnd999** [comment]
Thanks for the bug report. Unfortunately, this is not the right repository for Bloom, please open an issue [here](https://github.com/neo4j-devtools/neo4j-bloom)

**Comment by adriens** [comment]
Thanks a lot for the link @mnd999 , job done:
- https://github.com/neo4j-devtools/neo4j-bloom/issues/61
