### ISSUE TITLE
neo4j-streams & neo4j version

### ISSUE THREAD

**Issue by LangYuanzh** [neo4j/neo4j#13285]
I'm trying to stream and sync data from neo4j to Kafka using neo4j kafka-conenctor as a CDC plugin.

For the latest version of neo4j-kafka-connector, the "neo4j.source.type" only supports "QUERY", and this cause some questions:
1. I believe this will  leads to a lot of queries to the neo4j server, thus maybe giving a very high load to the neo4j server.
2. I want to listen to neo4j in real time and synchronise data incrementally. So i must set a property 'timestamp' to all the nodes and set neo4j.source.query like : "MATCH (n) WHERE n.timestamp > $lastCheck"

Using neo4j-stream as an neo4j plugin seems to be an better way, but it only working with neo4j version before 4.4, It's this right?
I can only find links to download versions 4.4 and 5.0 on the official website at the moment, where can I download neo4j 4.3 ? 
Or it's there any other solutions?

**Comment by ali-ince** [comment]
Hello @LangYuanzh,

You can still use [neo4j-streams](https://neo4j.com/docs/kafka-streams/) with neo4j 4.4. With 5.x your only option is to set up your schema to track changes and use our [kafka connect neo4j connector](https://neo4j.com/docs/kafka/) with custom queries to capture changes.

Thanks.

**Comment by LangYuanzh** [comment]
Thanks for your reply @ali-ince 

It's a little confused of the doc [https://neo4j.com/docs/kafka-streams/overview/](url)
it says that neo4j-streams is "deprecated; not guaranteed to work, use Kafka Connect instead" for neo4j version > 4.4.x.
As your reply, it means neo4j-streams 4.0.x and 4.1.x is still work with neo4j 4.4.x, right?

**Comment by ali-ince** [comment]
Yeah just noticed the compatibility table is indeed confusing. I'll make sure we update it accordingly.

Thanks for raising this.
