### ISSUE TITLE
Incorrect Deadlock Detection with Direct Dependency

### ISSUE THREAD

**Issue by mshimokura** [neo4j/neo4j#13291]
I am attempting to implement a similar behaviour to "SELECT FOR UPDATE" using Spring Data Neo4j, without the APOC library. I have run into what I believe is an incorrect deadlock detection, and have produced a minimal reproduction using the `cypher-shell` utility and docker.

When my transaction already has a lock on a node, and there is a second transaction attempting to lock that row, if the first transaction updates a property on that row by referencing itself (`n.lock = n.lock+1`) - the second transaction is aborted with a deadlock detection. This only happens when the second transaction is attempting to lock the node due to a "Direct Dependency" (as defined in [this documentation](https://neo4j.com/docs/operations-manual/current/database-internals/locks-deadlocks/))

**Neo4j Version:** 4.4.25
**Operating System:** macOS (Host) via Docker Desktop
**API:** cypher-shell (also reproduced in Java Driver)

### Steps to reproduce

Pull the docker image and start the container:
```sh
docker pull neo4j:4.4
docker run --rm neo4j:4.4
```

In another terminal, start a cypher-shell session:
```sh
# cypher-shell 1
> docker exec -it a0c7f2954a5c cypher-shell
Connected to Neo4j using Bolt protocol version 4.4 at neo4j://localhost:7687.
Type :help for a list of available commands or :exit to exit the shell.
Note that Cypher queries must end with a semicolon.
@neo4j> CREATE (:TestNode { lock: 0 });
0 rows
ready to start consuming query after 104 ms, results consumed after another 0 ms
Added 1 nodes, Set 1 properties, Added 1 labels
@neo4j> :begin
@neo4j# MATCH (n:TestNode) SET n.lock = n.lock + 1 RETURN n;
+-----------------------+
| n                     |
+-----------------------+
| (:TestNode {lock: 1}) |
+-----------------------+

1 row
ready to start consuming query after 231 ms, results consumed after another 12 ms
Set 1 properties
```

Then in a third terminal, start a second cypher-shell session:
```sh
# cypher-shell 2
> docker exec -it a0c7f2954a5c cypher-shell
Connected to Neo4j using Bolt protocol version 4.4 at neo4j://localhost:7687.
Type :help for a list of available commands or :exit to exit the shell.
Note that Cypher queries must end with a semicolon.
@neo4j> MATCH (n:TestNode) SET n.lock = n.lock + 1 RETURN n;
```

The second session correctly hangs, waiting for a lock on the node. Now, if we execute another command in the first session:
```sh
# cypher-shell 1
@neo4j# MATCH (n:TestNode) SET n.lock = n.lock - 1 RETURN n;
+-----------------------+
| n                     |
+-----------------------+
| (:TestNode {lock: 0}) |
+-----------------------+

1 row
ready to start consuming query after 60 ms, results consumed after another 24 ms
Set 1 properties
```

This causes the transaction in the cypher-shell 2 to abort with the following error:
```
ForsetiClient[transactionId=9, clientId=1] can't acquire ExclusiveLock{owner=ForsetiClient[transactionId=7, clientId=2]} on NODE(0), because holders of that lock are waiting for ForsetiClient[transactionId=9, clientId=1].
 Wait list:ExclusiveLock[
Client[7] waits for [ForsetiClient[transactionId=9, clientId=1]]]
@neo4j> 
```

If you restart this process, but as the "second command in the first session" do not reference the node, then you do not get the error. For example, the following query works properly and does not abort the second transaction:
```sh
# cypher-shell 1
MATCH (n:TestNode) SET n.lock = 0 RETURN n;
```

Furthermore, if the second transaction attempts to lock the row in another way, without using a direct dependency, the transactions behave as expected. These statements do not produce a deadlock detection, but they do correctly wait for their lock to be acquired:

```sh
# cypher-shell 2
MATCH (n:TestNode) SET n.__lock__ = true RETURN n;
MATCH (n:TestNode) SET n.lock = 0 RETURN n;
```

### Expected behavior

Only commands that actually produce a deadlock should abort the transaction. The first transaction is not waiting for the second transaction, because it has an exclusive lock on the node in question while reading & writing the data.

### Actual behavior

The second transaction's statement is detected as modifying the first transaction's lock property, even though it does not have a lock on that node.

In the example, after the first transaction is committed or rolled back, the second transaction should proceed to increment the `lock` property.

**Comment by AzuObs** [comment]
Hi @mshimokura 

Thank you for submitting this very detailed report to us. It has been sent for triaging and will hopefully be investigated soon.

All the best,
Daniel

**Comment by tinwelint** [comment]
@mshimokura Hi, I looked at this and it's a delicacy of the locking internals that is at play here. This happens because it's not only an exclusive `NODE` lock here, but also an exclusive `NODE_RELATIONSHIP_GROUP_DELETE` lock which the Cypher statement (I think when it sees that there's a read dependency for the update it's making) acquires temporarily around the read-and-update. The exclusive `NODE` lock remains tho. Both T1 (second terminal) and T2 (third terminal) does this. This forms this cycle when T1 tries to do the second statement:

`(NODE)-[EXCLUSIVE_OWNER]->(T1)-[WAITING_FOR_EXCLUSIVE]->(NODE_RELATIONSHIP_GROUP_DELETE)-[EXCLUSIVE_OWNER]->(T2)-[WAITING_FOR_EXCLUSIVE]->(NODE)`

Cypher calls an internal method to lock the node exclusively which isn't granular for e.g. only property updates, but also guards for relationship updates. This could probably be improved upon. But at least this is the reason for it.

**Comment by tinwelint** [comment]
Closing due to no response. Feel free to re-open.

**Comment by mshimokura** [comment]
@tinwelint Hi sorry I did not respond to your message. I don't really understand the ramifications of this internal locking behaviour, but is it not true that regardless of the internal behaviour - the API is stating that there is a dependency between these transactions when there should not be? This is important information for a potential fix, but it does not mean there is no bug.

**Comment by tinwelint** [comment]
It's somewhat unfortunate that some internal locking behaviour affects users this way. I agree I don't think the current behaviour in your example feels correct. There could be an opportunity to improve this, but it's hard to tell how difficult it would be since the current locks are there to solve some edge-cases that must be guarded for.
