### ISSUE TITLE
Concatenating Empty List causes type change

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13299]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.11.0 Community
operating system: windows 10
API：Cypher version 9

To reproduce:
WITH round (([]+toIntegerList (null))[0],1) AS a1 RETURN 1

error message:
Neo.ClientError.Statement.SyntaxError
Type mismatch: expected Float but was Any, Integer or Number (line 1, column 39 (offset: 38))
"WITH round (([]+toIntegerList (null))[0],1) AS a1 RETURN 1"
                                       ^

It is worth noting that the query "WITH round ((toIntegerList (null))[0],1) AS a1 RETURN 1" can run successfully without the "[]+" clause,which is strange.

Expected behavior:
The query should run successfully.

Actual behavior:
The query failed.

**Comment by gem-neo4j** [comment]
Hi there! this is now fixed and will be part of the next release (5.15) :)
