### ISSUE TITLE
RuntimeUnsupportedError about Projection

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13305]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.11.0 Community
operating system: windows 10
API：Cypher version 9

To reproduce:
CREATE ()-[r0 :T]->() CREATE ({k:EXISTS{return [r0]}})

error message:
Neo.ClientError.Statement.RuntimeUnsupportedError
Did not find `r0` in the slot configuration of Projection (Id(4))

It is worth noting that the query "CREATE ()-[r0 :T]->() CREATE ({k:EXISTS{return r0}})" can run successfully,which is strange.

Expected behavior:
The query should run successfully.

Actual behavior:
The query failed.

**Comment by arnefischereit** [comment]
Hi @ljhhuxiaoba,

This is the same issue as #13260, which has been fixed in 5.12, which was released last week.

I am closing this issue. Should the problem persist after upgrading to the current release or reappear, please reopen this issue or open a new one.

Regards,

Arne
