### ISSUE TITLE
Variable not defined error about CALL{} in EXISTS{}

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13303]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.11.0 Community
operating system: windows 10
API：Cypher version 9

To reproduce:
RETURN [()-[]-(n1)|EXISTS{CALL{WITH * RETURN n1 as p} RETURN n1}]

error message:
Neo.ClientError.Statement.SyntaxError
Variable `n1` not defined (line 1, column 46 (offset: 45))
"RETURN [()-[]-(n1)|EXISTS{CALL{WITH * RETURN n1 as p} RETURN n1}]"
                                              ^

It is worth noting that the query "RETURN [()-[]-(n1)|EXISTS{CALL{WITH n1 RETURN n1 as p} RETURN n1}]" can run successfully,which is strange.

Expected behavior:
The query should run successfully.

Actual behavior:
The query failed.

**Comment by TomVanWemmel** [comment]
You are creating a subquery, the variable doesn't exist in that scope unless you use an [importing WITH clause](https://neo4j.com/docs/cypher-manual/current/clauses/call-subquery/#subquery-correlated-importing)

**Comment by ljhhuxiaoba** [comment]
I see what you mean, but I don't understand why "WITH n1" works but not "WITH *".And I didn't find anything in the documentation about using "WITH *" in the first clause of a subquery.

**Comment by loveleif** [comment]
Thanks for the report! We will investigate.

**Comment by sherfert** [comment]
@TomVanWemmel is right.

The documentation says:

> An importing WITH clause must:
> * Consist only of simple references to outside variables - e.g. WITH x, y, z. Aliasing or expressions are not supported in importing WITH clauses - e.g. WITH a AS b or WITH a+1 AS b.
> * Be the first clause of a subquery (or the second clause, if directly following a USE clause).

The clause `WITH *` does not follow this pattern, so the compiler does not recognize it as an "importing WITH",
but rather as a _standard_ WITH. That means no variables get imported into the subquery, and `n1` is not available.

**Comment by ljhhuxiaoba** [comment]
Thank for reply and it can be solved.
