### ISSUE TITLE
Unexpected Type mismatch error : expected Boolean but was Relationship

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13301]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.11.0 Community
operating system: windows 10
API：Cypher version 9

To reproduce:
WITH NULL AS a0 WHERE reduce(a=NULL,b IN [type(NULL) contains "e"]|a) RETURN 1

error message:
Neo.ClientError.Statement.SyntaxError
Type mismatch: expected Boolean but was Relationship (line 1, column 23 (offset: 22))
"WITH NULL AS a0 WHERE reduce(a=NULL,b IN [type(NULL) contains "e"]|a) RETURN 1"
                       ^

Expected behavior:
The query should run successfully.

Actual behavior:
The query failed.

**Comment by loveleif** [comment]
Thanks for reporting this issue @ljhhuxiaoba! We're investigating.

**Comment by Lojjs** [comment]
@ljhhuxiaoba This is the same issue as in https://github.com/neo4j/neo4j/issues/13091, which just was fixed last week. The upcoming Neo4j 5.13 release will include the fix.
