### ISSUE TITLE
Variable not defined error about List comprehension

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13302]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.11.0 Community
operating system: windows 10
API：Cypher version 9

To reproduce:
WITH * MATCH ()-[ :T2{k:size([x IN [NULL]|NULL])}]-() RETURN 1 AS a2

error message:
Neo.ClientError.Statement.SyntaxError
Variable `x` not defined (line 1, column 31 (offset: 30))
"WITH * MATCH ()-[ :T2{k:size([x IN [NULL]|NULL])}]-() RETURN 1 AS a2"
                               ^

Expected behavior:
The query should run successfully.

Actual behavior:
The query failed.

**Comment by Tahaouad** [comment]
try : 
WITH * MATCH ()-[ :T2{k:size([NULL|NULL])}]-() RETURN 1 AS a2

**Comment by loveleif** [comment]
Thanks for the report @ljhhuxiaoba! We'll have a look.

**Comment by gem-neo4j** [comment]
Hi! This has now been fixed and will be released in 5.13 and 4.4.27 :) Thanks!
