### ISSUE TITLE
Desktop Installs Hobbled version of APOC plugin  for 5.x .

### ISSUE THREAD

**Issue by rick-carpool** [neo4j/neo4j#13304]
Installing APOC plugin installs apoc5plus-5.11.0.jar that does not have TTL support.    Dropping in the plugin from https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/5.11.0/apoc-5.11.0-extended.jar   will sort of work but it doesn't run the task that actually does the expirations.

Desktop using 4.x installs an APOC with TTL working just fine.

**Comment by gregoryking** [comment]
@rick-carpool Since 5.0 APOC extended is no longer installable directly via the Desktop UI. If you wish to continue using APOC extended you can still manually add this via the plugins folder.
