### ISSUE TITLE
Helm chart neo4j-standalone for Neo4j 5

### ISSUE THREAD

**Issue by NilsMoller** [neo4j/neo4j#13311]
**Is your feature request related to a problem? Please describe.**
The neo4j-standalone helm chart is not on neo4j v5.

**Describe the solution you'd like**
Update the chart to be in line with the current release.

**Comment by NilsMoller** [comment]
Comparing the configuration values with the (updated) default neo4j chart, they seem quite similar, and the `minimumClusterSize = 1` has a comment saying that represents the standalone version. Were they combined?

**Comment by klaren** [comment]
If the issue is helm chart related it should go to https://github.com/neo4j/helm-charts
