### ISSUE TITLE
Neo4j 5 HTTP API how to run multiple queries in parallel

### ISSUE THREAD

**Issue by Reid00** [neo4j/neo4j#13319]
- Neo4j version: 5.7
- Operating system: Centos
- API/Driver: HTTP API

according to https://neo4j.com/docs/http-api/current/transactions/, neo4j 5 HTTP API can run multiple queries but it's in sequenc.
If I want to run 20 queries, it's will be slowly, is there any way to run 20 queries in parallel?

**Comment by gjmwoods** [comment]
Hi @Reid00, many thanks for your question.

To run multiple queries in parallel you can submit a separate HTTP request for each query you wish to execute (for example 20 separate HTTP requests to the `/tx/{dbname}/commit` endpoint).

**Comment by Reid00** [comment]
Thank you @gjmwoods.
This an application-level method to fix my question, Actually, I do it now. 
But I need to wait for the 20 HTTP requests' response with this method, so I want to know is there any other method? 
`apoc.periodic.iterate`, `apoc.cypher.runManyReadOnly` both cannot return path, I try to `apoc.cypher.runParallel2` or  `apoc.cypher.runParallel` but it  always ouput syntax error?
here is my cypher , could you please fix it? 
```cypher
MATCH (n:Person) where n.keyNo IN ["p501f298f6fc918f1c1e0fb94268f53b", "p756de5fbd0f8acc034a55cd43c97821",
"p5baf3e85f5b3e69e5b47871813d0bfb", "pr45eadf7927a52ca7d6a96a1216794e"]
WITH collect(n) as starts
MATCH (m:Company) where m.keyNo IN ["8c9f7ddc1a7bcee3d1f7676773fe9404", "f9caa5f860e1c9faf7867c301b6b6a06", 
"0bf44c895427b4e60801aa4150b908a8", "dd67092006c584c069b36944bbb6043f", "1ac04be0065f9740d1647cade5790adc",
"f5dbba14219585b4578bb63040a3d418"]
WITH  starts, collect(m) as ends
WITH starts + ends AS nodes
UNWIND nodes as n
UNWIND nodes as m
WITH n,m WHERE id(n) < id(m)
MATCH path = allShortestPaths( (n)-[:INVEST|LEGAL|EMPLOY|BRANCH|HISINVEST|HISLEGAL|HISEMPLOY*..15]-(m) )
CALL apoc.cypher.parallel('RETURN path', {}, 'm,n')
YIELD value RETURN value.title as title
```

**Comment by Reid00** [comment]
Hi @gjmwoods , do you have any suggestions?

**Comment by gjmwoods** [comment]
Hi @Reid00, I'll have to ask one of my colleagues to respond about the cypher as I'm more focused on the transport layer but it would help if you could provide the syntax error that you see.

**Comment by gjmwoods** [comment]
Hi @Reid00, I reached out to my colleagues and they pointed out you have also asked this question on the apoc repo: https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/3794. I'll close this ticket down and they will pick it up there.

**Comment by Reid00** [comment]
@gjmwoods Got it, thanks a million.
