### ISSUE TITLE
Node deleted failed when adding "WITH *"

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13318]
I execute two queries on my neo4j database ,and an error occurs.

Neo4j version: 5.12.0 Community
operating system: windows 11
API：Cypher version 9

To create the graph:
[graph.log](https://github.com/neo4j/neo4j/files/12836988/graph.log)

To reproduce:
1️⃣ OPTIONAL MATCH ()-[r0]-()-[]-( :L1),(n0)-[]-()<-[r1]-(n1) DETACH DELETE n1  DETACH DELETE endNode(r0) RETURN n0 AS a0
2️⃣ OPTIONAL MATCH ()-[r0]-()-[]-( :L1),(n0)-[]-()<-[r1]-(n1) DETACH DELETE n1 WITH * DETACH DELETE endNode(r0) RETURN n0 AS a0

The above two queries need to be executed separately on two databases.

I think these two queries are equivalent, but there is only one node in the graph at the end of the first query, while there are two nodes in the graph at the end of the second query. I don't think the "WITH *" added in the second query should have this effect.

**Comment by hedengran** [comment]
Hi @ljhhuxiaoba, thank you for the report. We are looking into it, and will get back to you.

**Comment by ljhhuxiaoba** [comment]
May I ask a question about the LOC of Neo4j currently?

**Comment by sherfert** [comment]
We have identified the problem and the fix will be included in the 5.15 release.

Note that the 2nd query was executing correct while the first was not.
