### ISSUE TITLE
Node created failed by DISTINCT when using OPTIONAL

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13317]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.12.0 Community
operating system: windows 11
API：Cypher version 9

To reproduce:
CREATE (),();
1️⃣ MATCH () CREATE () RETURN DISTINCT 1 AS a1;
2️⃣ OPTIONAL MATCH () CREATE () RETURN DISTINCT 1 AS a1;

The above two queries need to be executed separately.

I think these two queries are equivalent, but when using “OPTIONAL”, only one new node is created, whereas in the first query there are two nodes created.
And when I remove the “DISTINCT” in the second query, the query executes as I expect it to.

**Comment by ljhhuxiaoba** [comment]
The same error also occurs when using DISTINCT in WITH clause.

**Comment by sherfert** [comment]
We have identified the problem and the fix will be included in the 5.15 release.
