### ISSUE TITLE
Question regarding filters

### ISSUE THREAD

**Issue by swilly22** [neo4j/neo4j#13313]
Hi,
A quick question regarding Cypher variable scoping

Consider the following query:

```cypher
UNWIND [1,2,3] AS a
WITH 1 AS one
WHERE a > 0 AND one = 1
MATCH (a)
RETURN 1
```

From my understanding `a` should not be accessible after the `WITH` clause, i.e. the `WHERE` condition is not suppose to see `a`
but It seems like `a` is accessible at that point in time.
If that's the case why am I allowed to reassign `a` as a node ?

Thank you!

**Comment by phil198** [comment]
Hi @swilly22, 

the purpose of the `WITH` clause is actually to _augment_ the what gets passed to the `WHERE` clause (and as such it will not limit what gets passed to a contiguous `WHERE` clause like yours). It will however also _limit_ what gets passed to subsequent `MATCH` clauses, hence why you are allowed to re-assign the `a` to a node in your `MATCH`. 

Including the `a` in the `WITH` like in this (failing) example demonstrates this:

```cypher
UNWIND [1,2,3] AS a
WITH 1 AS one, a
WHERE a > 0 AND one = 1
MATCH (a)
RETURN 1
```

I hope that helps!
