### ISSUE TITLE
Unexpected type error about input for function 'size()'

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13321]
I execute a query on my empty neo4j database ,and an error occurs.

Neo4j version: 5.12.0 Community
operating system: windows 11
API：Cypher version 9
Error message:
Neo.ClientError.Statement.TypeError
Invalid input for function 'size()': Expected a String or List, got: null

To reproduce:
1️⃣ MERGE ({k:size([(n1)<-[r2]-(n2)|'a'])}) RETURN 1
2️⃣ CREATE ({k:size([(n1)<-[r2]-(n2)|'a'])}) RETURN 1

The first query has a type error, but the second query can be executed successfully (just replacing “MERGE” with “CREATE”), and I don't think there should be this inconsistent result.

**Comment by hedengran** [comment]
Hi @ljhhuxiaoba, thank you for the report. We are looking into it, and will get back to you.

**Comment by Lojjs** [comment]
@ljhhuxiaoba This is indeed a bug. It has been fixed in Neo4j very recently as part of another bug fix. From 5.13 both queries will execute successfully.
