### ISSUE TITLE
[How to] install `apoc.ml.openai.embedding` on Free AuraDB?

### ISSUE THREAD

**Issue by mahimairaja** [neo4j/neo4j#13324]
I tried to perform RAG with neo4j graph with the builtin movie dataset dump. 

My code:

``` python
run_query("""
CALL apoc.periodic.iterate(
  'MATCH (m:Movie) RETURN id(m) AS id',
  'MATCH (m:Movie)
   WHERE id(m) = id
   MATCH (m)-[r:ACTED_IN|DIRECTED]-(t)
   WITH m, type(r) as type, collect(t.name) as names
   WITH m, type+": "+reduce(s="", n IN names | s + n + ", ") as types
   WITH m, collect(types) as contexts
   WITH m, "Movie title: "+ m.title + " year: "+coalesce(m.released,"") +" plot: "+ coalesce(m.tagline,"")+"\n" +
        reduce(s="", c in contexts | s + substring(c, 0, size(c)-2) +"\n") as context
   CALL apoc.ml.openai.embedding([context], $apiKey) YIELD embedding
   SET m.embedding = embedding',
  {batchSize:1, retries:3, params: {apiKey: $apiKey}})
""", {'apiKey': openai_api_key})['errorMessages'][0]
```

And I got the error message as:

``` bash
{"There is no procedure with the name `apoc.ml.openai.embedding` registered for this database instance. 
Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.": 160}

```

**Comment by klaren** [comment]
This repository is for the Neo4j database code. Neo4j Aura is a separate product and questions should be directed to the community forums or discord server, see https://aura.support.neo4j.com/hc/en-us/articles/16094506528787-Support-resources-and-FAQ-for-Aura-Free-Tier for more information.

As far as I know, `apoc.ml.openai.embedding` is part of [APOC Extended](https://neo4j.com/labs/apoc/#_apoc_extended) and is unfortunately not available in Aura. But I recommend asking in the forum/discord for a more up-to-date answer :)
