### ISSUE TITLE
Cannot calculate modulus of Long and NO_VALUE

### ISSUE THREAD

**Issue by CelineWuest** [neo4j/neo4j#13337]
When running the following query:
```cypher
RETURN 1 % toInteger("A")
```

I encountered the following error:
```
Neo4jError: Neo.ClientError.Statement.TypeError (Cannot calculate modulus of `Long` and `NO_VALUE`)
```

I believe the query mentioned above is semantically and syntactically correct and thus no error should be thrown here.
Additionally, the following, simplified query does not throw an error and returns `NULL`:
```cypher
RETURN 1 % NULL
```

I encountered this issue when testing queries against the **Neo4j 5.13.0 enterprise version** in a Docker container running **alpine v.3**.

### Steps to reproduce
Run the following queries and observe it throws an error:
```cypher
RETURN 1 % toInteger("A")
```

### Expected behavior
The query should run successfully

### Actual behavior
The query fails with the error message ``Neo4jError: Neo.ClientError.Statement.TypeError (Cannot calculate modulus of `Long` and `NO_VALUE`)``

**Comment by PetrJanouch** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[GitHub issue]Cannot calculate modulus of Long and NO_VALUE](https://trello.com/c/UWRSmg4R/5204-github-issuecannot-calculate-modulus-of-long-and-novalue)

**Comment by PetrJanouch** [comment]
Hi @DominicWuest,

thanks you for spending time on this and reposting it. Yes this this a bug and I have sent it to the responsible team for investigation.
It seems to be runtime-specific. So if it blocks you, you can use slotted runtime. `CYPHER runtime=slotted RETURN 1 % toInteger("A")`

**Comment by pontusmelke** [comment]
Hi @DominicWuest 
Thanks again for reporting. We have managed to track down the error now and a fix has been merged and will be in the next release.

Best regards,
Pontus
