### ISSUE TITLE
Neo4J Desktop > Unable to upgrade to 5.13

### ISSUE THREAD

**Issue by adriens** [neo4j/neo4j#13330]
# :grey_question: About 

On very latest Neo4J Desktop, I cannot upgrade to 5.13 as it crashes unexptectedly almost at 75% of download phasse:

![image](https://github.com/neo4j/neo4j/assets/5235127/d9699404-e4d5-4701-8442-c4737bc4a0b4)

:information_source: Looks like this previous error:
- https://github.com/neo4j/neo4j/issues/13282

**Comment by klaren** [comment]
Hello,

The `net::ERR_NETWORK_CHANGED` indicates a client side network issue. Are you possibly using a proxy or a VPN? The http proxy can be on a network level, so check with your network provider.

Since this issue is not related to neo4j I'll close it.

**Comment by adriens** [comment]
> The net::ERR_NETWORK_CHANGED indicates a client side network issue. Are you possibly using a proxy or a VPN? The http proxy can be on a network level, so check with your network provider.

Hi @klaren , nope, it's from home network, nothing like proxy nor vpn.

I have not changed anything but it could sucessfully download the latest version this morning: 

![image](https://github.com/neo4j/neo4j/assets/5235127/36a4f752-2d88-44f3-8907-e048454c8dfb)

**Comment by klaren** [comment]
Alright, then it might be some other issue with your ISP. 

That's good you finally managed to upgrade!

**Comment by adriens** [comment]
Maybe some caching issue. :thinking:
