### ISSUE TITLE
Unnamed Variable not found in slot configuration of Selection

### ISSUE THREAD

**Issue by CelineWuest** [neo4j/neo4j#13339]
When running the following query:
```cypher
CREATE x = (), ({ a0:COUNT { MATCH () WHERE CASE WHEN true THEN (x IS NULL) END RETURN 0 } })
```

I encountered the following error:
```
Neo4jError: Neo.ClientError.Statement.RuntimeUnsupportedError (Did not find `UNNAMED0` in the slot configuration of Selection (Id(4)))
```

I believe the query mentioned above is semantically and syntactically correct and thus no error should be thrown here.

I encountered this issue when testing queries against the **Neo4j 5.13.0 enterprise version** in a Docker container running **alpine v.3**.

### Steps to reproduce
Run the following queries and observe it throws an error:
```cypher
CREATE x = (), ({ a0:COUNT { MATCH () WHERE CASE WHEN true THEN (x IS NULL) END RETURN 0 } })
```

### Expected behavior
The query should run successfully

### Actual behavior
The query fails with the error message ``Neo4jError: Neo.ClientError.Statement.RuntimeUnsupportedError (Did not find `UNNAMED0` in the slot configuration of Selection (Id(4)))``

**Comment by PetrJanouch** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[GitHub issue]Unnamed Variable not found in slot configuration of Selection](https://trello.com/c/08SSUqYb/5201-github-issueunnamed-variable-not-found-in-slot-configuration-of-selection)

**Comment by PetrJanouch** [comment]
Hi @DominicWuest 

Thank you for reporting the error. I have submitted the issue to the appropriate team for them to investigate.

**Comment by sherfert** [comment]
Same as #13338 (and https://github.com/neo4j/neo4j/issues/13216 and https://github.com/neo4j/neo4j/issues/13316)
