### ISSUE TITLE
Bound edge

### ISSUE THREAD

**Issue by swilly22** [neo4j/neo4j#13333]
This issue discuss and suggest changes to the way edge patterns are handled.

When trying to use bound edge in a `CREATE` clause e.g.

```cypher
MATCH ()-[e:R]->() CREATE ()-[e:R]->()
```

We recieve an error: Variable `e` already declared (line 1, column 29 (offset: 28))

Similarly:

```cypher
MATCH ()-[e]->() MERGE (:A)-[e]->(:Z)
```

The same error is emitted: Variable `e` already declared (line 1, column 30 (offset: 29))

But when doing so in a `MATCH` clause:

```cypher
MATCH (a)-[e]->(b)-[e]->(c) RETURN a
``` 

No error is produced and an empty result-set is returned.
The above query should have returned results, for example when the graph contains self referencing node: `a = b = c`
```cypher
CREATE (a)-[:R]->(a)
```

`a` acts as a source node which is connected via `e` to some destination node `b`
That destination node `b` needs to act also as a source node on the same `e` edge, leading up to destination node `c`.

But looking at the generated execution plan: `explain MATCH (a)-[e]->(b)-[e]->(c) RETURN a`
We see an opening `LIMIT 0` operation. Making sure the query won't return anything.

Reviewing all three queries above, for consistency and simplicity purposes I think
edge patterns `()-[e]-()` should always try to declare the specified edge alias.
If that alias is already defined then the error we've seen before: "Variable `e` already declared" should be emitted.

**Comment by pontusmelke** [comment]
Hi @swilly22 
In Cypher a relationship can only be traversed once in a given match pattern, see for example https://neo4j.com/docs/cypher-manual/current/patterns/reference/#graph-patterns-rules-relationship-uniqueness. That is why `MATCH (a)-[e]->(b)-[e]->(c) RETURN a` will never find any patterns in the database and the planner figures that out and plans a LIMIT 0 so that we don't need to traverse as much of the graph to find out that there are no matches.

If you want your query to find the `a = b = c` self-referencing node you will need to decompose your pattern,

```
MATCH (a)-[e]->(b)
WITH a, e
MATCH (b)-[e]->(c) 
RETURN a
```

Hope that helps!
Best Regards
Pontus

**Comment by swilly22** [comment]
Thank you @pontusmelke.

I'm not trying to figure out how to find self-referencing nodes, but to touch on a more critical point for the language, which is dealing with bounded edges. In my mind referring to a bound edge in a pattern should result in an error, as seen in both:
```cypher
MATCH ()-[e:R]->() CREATE ()-[e:R]->()
```
And 
```cypher
MATCH ()-[e]->() MERGE (:A)-[e]->(:Z)
```

Even the query you've specified
```cypher
MATCH (a)-[e]->(b) WITH a, e MATCH (b)-[e]->(c)  RETURN a
```
If you look at the generated plan, seems to avoid expanding a bound edge, (there's only one traverse operation in that plan).
Therefor I suggest rising an error when a query refference an already declared variable in an relationship pattern.

Thank you!

**Comment by pontusmelke** [comment]
The two first queries fail because we are trying to create an already existing edge. There are legitimate reasons to reuse variables so failing would be a little bit too invasive.

Regards,
Pontus
