### ISSUE TITLE
Powershell script certificate expired/signing missing

### ISSUE THREAD

**Issue by BlairCooper** [neo4j/neo4j#13347]
On 4.4.27 Community Edidtion, running neo4j.bat/ps1 or neo4j-admin.bat/ps1 results in a error indicating that the signing certificate has expired.

The certificate included in the packaging expired November 13th 2023.

On 4.4.28, the Powershell scripts aren't signed at all so they also generate an error.

- Neo4j version: 4.4.27/4.4.28
- Operating system: Windows
- API/Driver: n/a
- **Steps to reproduce**
1) Run neo4j.bat from the command line, e.g. "neo4j update-service"

- Expected behavior
Command runs successfully

- Actual behavior
Certificate expiration error or not signed error is displayed and the command does not run.

**Comment by ghohoj** [comment]
me too

**Comment by charlesdelascasas** [comment]
Running into this issue as well

**Comment by jennyowen** [comment]
Just to let people know, we've seen this and are working on it. 5.x neo4j versions will also be affected.

**Comment by jennyowen** [comment]
I have re-signed and re-uploaded neo4js 4.4.27, 4.4.28, 5.13.0 and 5.14.0. You will need to re-download and unzip the package to get the updated powershell scripts.
