### ISSUE TITLE
Arraycopy: Last destination index out of bounds

### ISSUE THREAD

**Issue by CelineWuest** [neo4j/neo4j#13345]
When running the following query:
```cypher
WITH 0 AS n0 ORDER BY null
CALL {
  RETURN 0 AS n1 ORDER BY null
}
UNWIND 0 AS x
RETURN x
```

I encountered the following error:
```
Neo4jError: Neo.DatabaseError.Statement.ExecutionFailed (arraycopy: last destination index 4 out of bounds for object array[3])
```

I believe the query mentioned above is semantically and syntactically correct and thus no error should be thrown here.

I encountered this issue when testing queries against the **Neo4j 5.13.0 community version** in a Docker container running **alpine v.3**.

### Steps to reproduce
Run the following query and observe it throws an error:
```cypher
WITH 0 AS n0 ORDER BY null CALL { RETURN 0 AS n1 ORDER BY null } UNWIND 0 AS x RETURN x
```

### Expected behavior
The query should run successfully

### Actual behavior
The query fails with the error message `Neo4jError: Neo.DatabaseError.Statement.ExecutionFailed (arraycopy: last destination index 4 out of bounds for object array[3])`

**Comment by sherfert** [comment]
We merged a fix that will appear in 5.15.
