### ISSUE TITLE
neo4j installation crashes Linux systems (Debian or Ubuntu) 

### ISSUE THREAD

**Issue by vickriss** [neo4j/neo4j#13352]
After installing neo4j on either Linux system using appImage file, neo4j desktop initiates and runs.  However when attempting a reboot after this test, OS bootup sequence remains stuck in boot.  At that point the only remedial action was to reinstall the operating system and avoid neo4j desktop installation. I reproduce the issue on 2 laptop machines from 2 different manufacturers .Ubuntu boot pic attached when in this mode. 

- Neo4j desktop version: 1.5.9
- Attempted with both JDK 17 and JDK 19
- Operating system: (Debian 12, Ubuntu 23.1)
- **Steps to reproduce**:
     - fuse install  neo4j desktop appImage
     - Launch neo4j - at this point app runs with dbms
     - Stop dbms
     - Close neo4j
     - Reboot
- Expected behavior: operating system should reboot without any issues
- Actual behavior: operating system bootup sequence stuck, requiring operating system reinstal.  
![IMG_1613](https://github.com/neo4j/neo4j/assets/121537020/60de6735-aeaf-4150-aeeb-f2fdf63ce572)

**Comment by nglgzz** [comment]
Hi @vickriss, what commands are you running to install the appimage? It shouldn't require installation, it should be enough to set is as executable and run it.

**Comment by vickriss** [comment]
Hi @nglgzz, I run the commands below.  Thanks!
1) I download neo4j-desktop-1.5.9-x86_64.AppImage from neo4j download site
2) chmod x+ *
3) sudo apt-get install fuse
4) ./neo4j-desktop-1.5.9-x86_64.AppImage

Command (2) adds executable permissions to  neo4j-desktop-1.5.9-x86_64.AppImage.
Command (3) - AppImages require FUSE to run.
After command (4), neo4j desktop starts up and runs without any issues.  But after rebooting, I run into the issue I described.

**Comment by nglgzz** [comment]
On step 3, could you try installing `libfuse2` instead of `fuse`? 

From https://github.com/AppImage/AppImageKit/wiki/FUSE#install-fuse:
> While libfuse2 is OK, do not install the fuse package as of 22.04 or you may break your system

so it sounds like that might be the issue you encountered.

**Comment by vickriss** [comment]
Good find, thanks!  I'll give it a go today and will let you know

**Comment by vickriss** [comment]
That was it, all set, thanks!

**Comment by nglgzz** [comment]
Awesome, happy I could help :sparkles:
