### ISSUE TITLE
"Neo4j is not running" even though it is

### ISSUE THREAD

**Issue by Podbrushkin** [neo4j/neo4j#13357]
*I have found a workaround already, but still I will post this issue, because probably you will get it too if you'll reproduce the same steps (which are perfectly valid and shouldn't lead to problems I believe). If culprit is to make Maven to pass all tests, then I wonder how it could be done*

Executing `neo4j-admin server status` produces `Neo4j is not running` even though it is running:
```powershell
PS C:\Users\user\Desktop> neo4j-admin server status --verbose
neo4j 5.13.0-SNAPSHOT
VM Name: Java HotSpot(TM) 64-Bit Server VM
VM Vendor: Oracle Corporation
VM Version: 21.0.1+12-LTS-29
JIT compiler: HotSpot 64-Bit Tiered Compilers
VM Arguments: [-Dbasedir=C:\Users\user\AppData\Local\Programs\neo4j-community-5.13.0-SNAPSHOT]
Configuration files used (ordered by priority):
C:\Users\user\AppData\Local\Programs\neo4j-community-5.13.0-SNAPSHOT\conf\neo4j.conf
--------------------
Executing command line: powershell.exe -OutputFormat Text -ExecutionPolicy Bypass -Command Get-Service neo4j | Format-Table -AutoSize
org.neo4j.cli.CommandFailedException: Neo4j is not running.
        at org.neo4j.server.startup.Bootloader$Dbms.status(Bootloader.java:529)
        at org.neo4j.server.startup.StatusCommand.execute(StatusCommand.java:37)
        at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:92)
        at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:37)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at org.neo4j.server.startup.Neo4jAdminCommand.call(Neo4jAdminCommand.java:123)
        at org.neo4j.server.startup.Neo4jAdminCommand.call(Neo4jAdminCommand.java:42)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at org.neo4j.server.startup.Neo4jAdminCommand.main(Neo4jAdminCommand.java:181)
PS C:\Users\user\Desktop> curl http://localhost:7474/
{
  "bolt_routing" : "neo4j://localhost:7687",
  "transaction" : "http://localhost:7474/db/{databaseName}/tx",
  "bolt_direct" : "bolt://localhost:7687",
  "neo4j_version" : "5.13.0-SNAPSHOT",
  "neo4j_edition" : "community"
}
```
Also Neo4j Browser is not available at <http://localhost:7474/>. Maybe it is a clue.

**Neo4j Version:** 5.13.0
**Operating System:** Windows 11
**API:** Docker

### Steps to reproduce

I wasn't able to download zip distribution of Neo4j in Download center by [this link](https://neo4j.com/download-thanks/?edition=community&release=5.13.0&packaging=zip&architecture=x64#) (download doesn't start, sometimes it shows overload messages), and this github repository doesn't provide already built distributions, so I've built Neo4j myself:
1.
```
git clone --depth 1 https://github.com/neo4j/neo4j.git
cd neo4j
$env:MAVEN_OPTS = '-Xmx2048m'
mvn clean install -DskipTests -T1C
```
 * *Tests are skipped because some of them were failing. If needed, I can try to run them again and provide logs here.*

It produced desired `neo4j\packaging\standalone\target\neo4j-community-5.13.0-SNAPSHOT-windows.zip` file with SHA256= `56a91c7fff9278deced1d770d574c2b5f9ccb59bf2c5254c8ce6f76c40d4400f`.

2. Extract it to `C:\Users\user\AppData\Local\Programs`.
3. Add `C:\Users\user\AppData\Local\Programs\neo4j-community-5.13.0-SNAPSHOT\bin` to %PATH% variable.
4. Execute `neo4j windows-service install`.
5. `neo4j-admin server start`
6. `neo4j-admin server status`

### Expected behavior
Should output `Neo4j is running` and Neo4j Browser should be available at <localhost:7474>

### Actual behavior

Outputs `Neo4j is not running` and 404 error at <localhost:7474>

## Solution

Instead of building neo4j yourself, download zip here: http://dist.neo4j.org/neo4j-community-3.15.0-windows.zip with SHA256= `08489344441b09e66ff0b08d0e4e355cf593b4848fdbfaab6d0416501f3e0035`.
All the same steps lead to desired behavior.  

## Maven build test fails

```
[ERROR] Failures:
[ERROR]   SourceTest.shouldTryToExecuteIncompleteStatements:89
Argument(s) are different! Wanted:
cypherShell.execute(
    [CypherStatement[statement=INVALID CYPHER
WITHOUT SEMICOLON
// Comment at end, isComplete=false, beginOffset=0, endOffset=49]]
);
-> at org.neo4j.shell.CypherShell.execute(CypherShell.java:110)
Actual invocations have different arguments:
cypherShell.execute(
    [CypherStatement[statement=INVALID CYPHER
WITHOUT SEMICOLON
// Comment at end, isComplete=false, beginOffset=0, endOffset=51]]
);
-> at org.neo4j.shell.commands.Source.execute(Source.java:53)

[INFO]
[ERROR] Tests run: 370, Failures: 1, Errors: 0, Skipped: 0
[INFO] Neo4j - Cypher Shell ............................... FAILURE [01:09 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:04 min (Wall Clock)
[INFO] Finished at: 2023-11-28T18:01:26+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.1.2:test (default-test) on project cypher-shell: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\user\Desktop\neo4j\community\cypher-shell\cypher-shell\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
```

**Comment by tinwelint** [comment]
Hi @Podbrushkin I tried your exact steps, although on 5.15 (didn't try on 5.13) and it said that it was running and I could access Neo4j UI at localhost:7474. So when calling `neo4j-admin server start` Windows asks you for permission or something (you know the standard Windows thing) with a Yes/No and if clicking Yes then a small other console window appears. Did you close that one? That console window is the neo4j process I think, so it's kinda important :)

**Comment by Podbrushkin** [comment]
Hi @tinwelint. I've just reproduced those steps and something has changed. In my previous report those steps lead to `Neo4j is not running` being printed to console, and now it prints `Neo4j is running` but still 404 at localhost:7474. I believe Neo4j Browser should be available at this address, because that is how it works with pre-built binaries I've mentioned in **Solution** section. They work as expected, but binaries built with maven - don't. 
What I did this time:
```
> neo4j stop
> neo4j windows-service uninstall
```
2. Removed existing Neo4j distribution from env:path variable, closed Windows Terminal and opened it again.
```powershell
> where.exe neo4j
> where.exe neo4j-admin.bat
# both not found

# in empty dir:
git clone --depth 1 https://github.com/neo4j/neo4j.git
cd .\neo4j\
$env:MAVEN_OPTS = '-Xmx2048m'
mvn clean install -DskipTests -T1C
Expand-Archive .\packaging\standalone\target\neo4j-community-5.13.0-SNAPSHOT-windows.zip ..
```
at this point I've added .\delmeNeo4jbuild\neo4j-community-5.13.0-SNAPSHOT\bin to %PATH% and restarted WT;
```powershell
> where.exe neo4j
C:\Users\user\Desktop\delmeNeo4jbuild\neo4j-community-5.13.0-SNAPSHOT\bin\neo4j.bat
> where.exe neo4j-admin.bat
C:\Users\user\Desktop\delmeNeo4jbuild\neo4j-community-5.13.0-SNAPSHOT\bin\neo4j-admin.bat

> neo4j windows-service install
> neo4j-admin server start 
# I've clicked 'yes' in both UAC windows. Console windows disappeared by themselves;

> neo4j-admin server status
Neo4j is running
```
In previous report output was "not running", I don't know why this time it's different. 
At this point I've tried visiting localhost:7474 in browser and got 404.

```powershell
> curl http://localhost:7474/
{
  "bolt_routing" : "neo4j://localhost:7687",
  "transaction" : "http://localhost:7474/db/{databaseName}/tx",
  "bolt_direct" : "bolt://localhost:7687",
  "neo4j_version" : "5.13.0-SNAPSHOT",
  "neo4j_edition" : "community"
}
> ping http://localhost:7474/
Ping request could not find host http://localhost:7474/. Please check the name and try again.

> neo4j-admin server status --verbose
neo4j 5.13.0-SNAPSHOT
VM Name: Java HotSpot(TM) 64-Bit Server VM
VM Vendor: Oracle Corporation
VM Version: 21.0.1+12-LTS-29
JIT compiler: HotSpot 64-Bit Tiered Compilers
VM Arguments: [-Dbasedir=C:\Users\user\Desktop\delmeNeo4jbuild\neo4j-community-5.13.0-SNAPSHOT]
Configuration files used (ordered by priority):
C:\Users\user\Desktop\delmeNeo4jbuild\neo4j-community-5.13.0-SNAPSHOT\conf\neo4j.conf
--------------------
Executing command line: powershell.exe -OutputFormat Text -ExecutionPolicy Bypass -Command Get-Service neo4j | Format-Table -AutoSize
Neo4j is running

> mvn --version
Apache Maven 3.8.7 (b89d5959fcde851dcb1c8946a785a163f14e1e29)
Maven home: C:\Users\user\AppData\Local\Programs\apache-maven-3.8.7
Java version: 21.0.1, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-21.0.1
Default locale: en_US, platform encoding: UTF-8
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"
```

So now problem is not *"Neo4j is not running" even though it is"* as it is stated in issue's title, but Neo4j Browser is not being accessible at localhost:7474 even though it should be (which was part of original problem).
Also I don't know how same steps could produce a different version of neo4j for you (5.15 instead of 5.13). 
If I will try to build 5.15 I will report my results here.

**Comment by tinwelint** [comment]
I'm unsure why a maven build results in a different packaging, but surely this will work if you download an official package, right?

**Comment by Podbrushkin** [comment]
Yes, I'm using official pre-built package without any issues. But this package is available at some obscure link I've found at SO in an answer many years old, and it's possible maintaining of this type of links will stop, and I will lose my only way to get neo4j zip.
Binaries are not available at releases/assets in this github repo.
And I can't download them at neo4j.com/download because of 403 error at [this url](https://neo4j.com/artifact.php?name=neo4j-community-5.15.0-windows.zip).  
That's why I'm interested in being able to produce working binaries from maven project.
Also, just now I've tried to build 5.15 and got same result - `Neo4j is running` but 404 at localhost:7474.

**Comment by tinwelint** [comment]
OK gotcha, and I'm sorry I can't help you with packaging issues, but I'm handing over to someone else that could hopefully help you further. Cheers.

**Comment by Podbrushkin** [comment]
I've built `neo4j-community-5.15.0-SNAPSHOT-windows.zip` in WSL Ubuntu 22 but behavior is the same.

**Comment by jennyowen** [comment]
Hi @Podbrushkin 
The reason this is happening is because the neo4j-browser source code is in a different repository to neo4j.
When you're compiling neo4j from source, you don't have neo4j-browser, so there's nothing making neo4j available on `:7474`. 
The neo4j-browser source is at
https://github.com/neo4j/neo4j-browser

Anyway, that's somewhat irrelevant because the real problem is that you can't download the pre-packaged zip off our website.
I don't really know why the download page wasn't working for you, perhaps it was under maintenance? Some parts of the website have been moved around in the past few months, so the old link you had won't work any more.
 
I just now tried downloading the latest 5.15.0 from the downloads page and it worked. 
I went to https://neo4j.com/deployment-center/#gdb-tab and under the section "Graph Database Self-Managed" I selected the community Windows Executable and it downloaded for me.

**Comment by Podbrushkin** [comment]
> The reason this is happening is because the neo4j-browser source code is in a different repository to neo4j.

Oh, ok. Looks like both problems ("neo4j not running" and not working neo4j browser) I've reported here are either gone or not aren't actually problems.
Yet still I can't download pre-packaged zip. Originally I was following  exactly these steps you've explained. First, page redirects to "Thank for downloading Neo4j", browser shows this page as being loaded for 2 minutes, then it stops without start of downloading. Next, if I'll click ["click here if it doesn't"](https://neo4j.com/artifact.php?name=neo4j-community-5.15.0-windows.zip), I will see 403 error page:
```
403 ERROR
The request could not be satisfied.
Request blocked. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
Generated by cloudfront (CloudFront)
Request ID: Iz_D-l__Gz02wkxeD62UJhsnWlnl1KlZ_Cdu8XlCPS3jrYzBfWtKpw==
```

**Comment by jennyowen** [comment]
@Podbrushkin I will check with our webteam what might be going on there.
If you don't mind me asking... what country are you in?

**Comment by Podbrushkin** [comment]
> what country are you in?

Russian Federation

**Comment by jennyowen** [comment]
Ah that will be why. International sanctions mean we cannot make neo4j available in Russia. The website is geoblocked in your country I'm afraid. 

I do think the error message from the website should be more helpful though. Like it should let you know that you are explicitly blocked rather than just spew an unhelpful cloudfront error. I will ask the web team to fix that, but since it's not specifically a bug in neo4j I will close this issue now.

**Comment by Podbrushkin** [comment]
> International sanctions mean we cannot make neo4j available in Russia

That's not true, sanctions don't regulate file downloading and website availability. Also, neo4j is already available in Russia (if we are speaking about software at least), I doubt it is possible to do anything with that.

> The website is geoblocked in your country I'm afraid.

That's not true, both neo4j.com and aws.amazon.com/cloudfront/ are available and CloudFront doesn't restrict access from Russia for websites of its clients, only if geo-blocking has been explicitly requested by website owner. But since neo4j.com is available, I doubt it is a geo-blocking policy of Neo4j organization.

> I do think the error message from the website should be more helpful though. Like it should let you know that you are explicitly blocked

Absolutely, clear reasoning is valuable regardless of the situation or context. 
But right now, it doesn't look like anyone is blocked. It totally looks like unintended behavior. If this unintended behavior isn't going to be fixed because of reasons you can guess in this situation, I think I will be able to live with it.
