### ISSUE TITLE
Node labels ordering inconsistent

### ISSUE THREAD

**Issue by ellebrecht** [neo4j/neo4j#13350]
When `CREATE`-ing nodes with multiple labels, the given order of labels is not always preserved. Subsequent `RETURN` or `MATCH` consistently gives a different order, depending on the label strings.

**Neo4j version**: 5.12.0
**Operating system**: Docker linux/amd64 neo4j:5.12 
**API/Driver**: Browser

### Steps to reproduce
`CREATE (n:State:Entity) RETURN n, labels(n)`
```
╒═══════════════╤═══════════════════╕
│n              │labels(n)          │
╞═══════════════╪═══════════════════╡
│(:Entity:State)│["Entity", "State"]│
└───────────────┴───────────────────┘
```

`MATCH (n) RETURN DISTINCT(labels(n))`
```
(labels(n))
--
1 | ["Entity", "State"]
```

`CREATE (n:Entity:City) RETURN n, labels(n)`
```
╒══════════════╤══════════════════╕
│n             │labels(n)         │
╞══════════════╪══════════════════╡
│(:City:Entity)│["City", "Entity"]│
└──────────────┴──────────────────┘
```

`MATCH (n) RETURN DISTINCT(labels(n))`
```
(labels(n))
--
1 | ["City", "Entity"]
```

### Expected behavior
`labels()` should give the same ordering used in `CREATE`

### Actual behavior
`labels()` gives a different ordering than the one used in `CREATE`, depending on the label strings. 
For the same list of labels, the ordering is consistent for different `CREATE`s.
The ordering is not consistent between Neo4j versions (4.4 gives a different reordering than 5.12 for the test data above).

**Comment by gem-neo4j** [comment]
Hi there! 

We do not guarantee an ordering of labels on Nodes, in order to get an ordering, you will need to sort the list, which can be done with an UNWIND and ORDER BY. There is, however, no way to preserve the order in which they are created.

Thank you for writing in,
Gem
