### ISSUE TITLE
[Neo4j 5.14] TEXT INDEX readCount and lastRead not populated if AccessMode.READ

### ISSUE THREAD

**Issue by ikwattro** [neo4j/neo4j#13358]
**Neo4j Version:** 5.14.0-enterprise
**Operating System:** Any
**API:** Java

Setup : Neo4j cluster 3 primaries

Take the following setup for the database : 

```
CREATE DATABASE demo WAIT;
:use demo

CREATE (:Person {testName: "Christophe"})
CREATE (:Person {testName: "Luanne"})
CREATE (:Person {testName: "Miro"})

CREATE TEXT INDEX FOR (n:Person) ON n.name
```

Check when is the last time the index is read : 

```
SHOW INDEXES YIELD name, type, labelsOrTypes, properties, readCount, lastRead
WHERE 'Person' IN labelsOrTypes AND type = "TEXT"
RETURN *
```

Current output : 

```
╒══════════╤══════╤═════════════╤════════════╤═════════╤════════════════════════════════╕
│name      │type  │labelsOrTypes│properties  │readCount│lastRead                        │
╞══════════╪══════╪═════════════╪════════════╪═════════╪════════════════════════════════╡
│"cto_test"│"TEXT"│["Person"]   │["testName"]│29       │"2023-11-29T16:30:10.070000000Z"│
└──────────┴──────┴─────────────┴────────────┴─────────┴────────────────────────────────┘
```

Take the following Java code example 

```java
try (Driver driver = GraphDatabase.driver("neo4j://neo4j-xxxxx.graphaware.io", AuthTokens.basic("neo4j", "xxxx"))) { {
            try (Session session = driver.session(SessionConfig.forDatabase("cto.sandbox"))) {
                var result = session.run("MATCH (n:Person) WHERE n.testName ENDS WITH $name RETURN n", Map.of("name", "phe")).list();
            }
        }}
```

You can see the readCount increasing

```
╒══════════╤══════╤═════════════╤════════════╤═════════╤════════════════════════════════╕
│name      │type  │labelsOrTypes│properties  │readCount│lastRead                        │
╞══════════╪══════╪═════════════╪════════════╪═════════╪════════════════════════════════╡
│"cto_test"│"TEXT"│["Person"]   │["testName"]│30       │"2023-11-29T16:47:51.834000000Z"│
└──────────┴──────┴─────────────┴────────────┴─────────┴────────────────────────────────┘
```

However, as soon as we switch to `AccessMode.READ`, the numbers are not increasing

```java
SessionConfig.Builder sessionConfigBuilder = SessionConfig.builder().withDatabase("cto.sandbox").withDefaultAccessMode(AccessMode.READ).build();
try (Driver driver = GraphDatabase.driver("neo4j://neo4j-xxxxx.graphaware.io", AuthTokens.basic("neo4j", "xxxx"))) { {
            try (Session session = driver.session(sessionConfig)) {
                var result = session.run("MATCH (n:Person) WHERE n.testName ENDS WITH $name RETURN n", Map.of("name", "phe")).list();
            }
        }}
```

Probably related to https://github.com/neo4j/neo4j/issues/13342

NB : Having a property type constraint or not on :Person(testName) doesn't change anything. However I can confirm that it IS using the index, verified it by checking the profile on the ResultSummary

**Comment by mnssn** [comment]
Hello ikwattro,

Thank you for the detailed bug report! Makes it much easier to try to pin-point issues.

I believe that you have discovered one of the subtleties of the implementation of index usage statistics, viz. that they are local to the executing cluster member. When you add the access mode `AccessMode.READ` to the driver, you allow it to delegate the query to read replicas, as opposed to `AccessMode.WRITE` which is always directed to the cluster leader for that particular database. 

As the index usage statistics is currently implemented, they are not replicated between cluster members. To get the global usage statistics you would have to query each cluster member individually, and aggregate the result. Unfortunately, the drivers do not support this type of querying directly.

**Comment by ikwattro** [comment]
Thanks for the explanation @mnssn !
