### ISSUE TITLE
It's cost more time when I query all rela nodes of a node with version 5.13 than 3.5. why? 

### ISSUE THREAD

**Issue by xiankaipeng** [neo4j/neo4j#13363]

**Comment by InverseFalcon** [comment]
We would need something concrete to investigate. Can you please provide the query you're using, and provide the visual [EXPLAIN plans](https://neo4j.com/docs/cypher-manual/current/planning-and-tuning/#_note_on_profile_and_explain) (or PROFILE plans, if you're able to run the query to completion) for it (exported to SVG) from running it on 3.5 as well as on 5.13?

**Comment by tomswinkels** [comment]
@xiankaipeng maybe have a look to my issue -> https://github.com/neo4j/neo4j/issues/13354

**Comment by pontusmelke** [comment]
@xiankaipeng could you provide more information about the query?

**Comment by tomswinkels** [comment]
@xiankaipeng do you have any update about this issue?

**Comment by sherfert** [comment]
@xiankaipeng We need more information to act on this. Please reopen the issue with EXPLAIN or PROFILE outputs.
