### ISSUE TITLE
SyntaxError when adding DISTINCT 

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13365]
I execute a query on my empty neo4j database ,and an error occurs.

Neo4j version: 5.14.0 Community
operating system: windows 11
API：Cypher version 9
Error message:
Neo.ClientError.Statement.SyntaxError
PatternExpressions are not allowed to introduce new variables: 'n0'. (line 1, column 67 (offset: 66))
"MATCH (n0)<-[m0:T1]-(n1) RETURN DISTINCT 1 AS a2 ORDER BY exists((n0:L1)-[]-(n1))"

To reproduce:
MATCH (n0)<-[m0:T1]-(n1) RETURN DISTINCT 1 AS a2 ORDER BY exists((n0:L1)-[]-(n1))

**Comment by sherfert** [comment]
If you change your query to

```
MATCH (n0)<-[m0:T1]-(n1) RETURN DISTINCT 1 AS a2 ORDER BY n0
```

You get the following error:

```
In a WITH/RETURN with DISTINCT or an aggregation, it is not possible to access variables declared before the WITH/RETURN: n0
```

So, in your original query, the `n0` and `n1` in `exists((n0:L1)-[]-(n1))` are considered new variables, and, as your error message states: PatternExpressions are not allowed to introduce new variables.

I hope that clears up the confusion.
