### ISSUE TITLE
Misunderstanding due to Inadequate handling of exceptional values

### ISSUE THREAD

**Issue by w158937299** [neo4j/neo4j#13386]
## Guidelines

- Neo4j version: 4.4.26
- Operating system: (Windows 11)
- API/Driver: (py2neo 2021.2.3)
- **Steps to reproduce**

![2](https://github.com/neo4j/neo4j/assets/49486148/d17b1e9b-b2a6-469a-add7-920f8ea9e330)

As shown in this picture, this query returns the names of nodes of type "nt1" and the sum of the "p8" property values for their respective edge sets. It can be observed that there is a difference in the sum of property values returned by Neo4j and AgensGraph. When AgensGraph sets it to none, it indicates that the "p8" property does not exist in the edge set of the node. However, when Neo4j sets it to 0, it might lead to the misconception that the sum of "p8" property values in the edge set of the node is 0, suggesting that "p8" exists in the edge set of the node. We believe this bug may be due to Neo4j's inadequate handling of exceptional values.

**Comment by mnd999** [comment]
Thanks for the report, without looking at the complete graph I can't say for sure what is going on here. The likely reason is that [in Neo4j, `sum(null)` returns 0`](https://neo4j.com/docs/cypher-manual/current/functions/aggregating/#functions-sum). If that is the case, this is by design.

**Comment by w158937299** [comment]
> Thanks for the report, without looking at the complete graph I can't say for sure what is going on here. The likely reason is that [in Neo4j, `sum(null)` returns 0`](https://neo4j.com/docs/cypher-manual/current/functions/aggregating/#functions-sum). If that is the case, this is by design.

Thank you for your reply. I think it could be something like this.  The file below is the complete graph we used.
[edge.csv](https://github.com/neo4j/neo4j/files/13987514/edge.csv)

**Comment by pontusmelke** [comment]
Hi @w158937299,
Thanks for reporting this. As @mnd999 says this is expected behaviour, `sum` excludes all `null` values (https://neo4j.com/docs/cypher-manual/current/functions/aggregating/#functions-sum).

Best regards,
Pontus
