### ISSUE TITLE
Bug when returning both the number of query nodes and the node's property values

### ISSUE THREAD

**Issue by w158937299** [neo4j/neo4j#13385]
## Guidelines

To help us understand your issue, please specify important details, primarily:

- Neo4j version: 4.4.26
- Operating system: (Windows 11）
- API/Driver: (py2neo  2021.2.3)
- **Steps to reproduce**
![1](https://github.com/neo4j/neo4j/assets/49486148/eb78dde1-3895-4096-83af-e6d3beef56c8)

-As shown in this picture, query1 returns the number of nodes of type "nt3" and the mean value of the "p8" property value for nodes of that type. It can be observed that Neo4j and AgensGraph return different node counts. However, the node count returned by query 2 is the same. Therefore, we believe the reason for the bug is that Neo4j, when simultaneously returning the node count and node property values, first considers whether the "p8" property value exists in the properties of nodes of type "nt3". If it exists, it is counted; otherwise, it is not counted, leading to the bug.

**Comment by sherfert** [comment]
Thanks for the report. We fixed the problem.

The fix will be part of 5.18 and 4.4.31
