### ISSUE TITLE
Fix remaining 3.5 pre-release LICENSE.txt files which are still infringing on the Free Software Foundation's AGPL copyright

### ISSUE THREAD

**Issue by jmsuhy** [neo4j/neo4j#13393]
The Free Software Foundation issued a cease and desist to Neo4j, demanding the removal of the commons clause from AGPL LICENSE.txt files or the replacement of the AGPL with a proprietary license to prevent confusion over the software's open-source status.

A commit (https://github.com/neo4j/neo4j/commit/b6237ca4e31706b1efbd0f874d265117b84c12d5) addressed a few infringing LICENSE.txt files, but many remain in the 3.5 pre-release tags.

Please correct the remaining infringing files across all branches and tags.

For more information, refer to the FSF's discussion on this issue: 
https://www.fsf.org/blogs/licensing/protecting-free-software-against-confusing-additional-restrictions.

You can identify the infringing LICENSE.txt files using the shell script attached. 
[neo4j-agpl-infringement-check.txt](https://github.com/neo4j/neo4j/files/14146848/neo4j-agpl-infringement-check.txt)

**Comment by klaren** [comment]
The tags points to actual released code, are you asking us to retroactively change the license of already published code? I'm not sure we can do that. 

Also, it's only the name of the license that changed(to avoid confusion), the content is exactly the same so in regards to terms and restricts etc. nothing changes.

**Comment by jmsuhy** [comment]
I am just pointing out that Neo4j  has not fully complied with the cease and desist instructions.

Please ask your team for and read the cease and desist letter that the Free Software Foundation sent in November. 

There are a significant number of LICENSE.txt files across the 3.5 pre release tags which are still infringing on the Free Software Foundation's AGPL copyright.  

These files state the license is AGPL, have the AGPL preamble, and still have the “commons clause”.     Those files should be verbatim AGPL or you should call the license something else and not use the AGPL name or preamble.  

Example:  https://github.com/neo4j/neo4j/blob/3.5.0-beta03/enterprise/server-enterprise/LICENSE.txt

The tags below still have infringing LICENSE.txt files under the enterprise folders:


https://github.com/neo4j/neo4j/tree/3.5.0-alpha01

through 

https://github.com/neo4j/neo4j/tree/3.5.0-beta03


Please keep in mind that the Free Software Foundation can submit a GitHub DMCA takedown request to address the infringement if not done voluntarily.

**Comment by klaren** [comment]
> Please ask your team for and read the cease and desist letter that the Free Software Foundation sent in November.

They have, and there is ongoing communication between the involved parties. A GitHub issue is not the correct medium to resolve such things.

> Please keep in mind that the Free Software Foundation can submit a GitHub DMCA takedown request to address the infringement if not done voluntarily.

That's not how it works. See https://docs.github.com/en/site-policy/content-removal-policies/dmca-takedown-policy#a-how-does-this-actually-work

> "The DMCA framework is a bit like passing notes in class. The copyright owner hands GitHub a complaint about a user. If it's written correctly, we pass the complaint along to the user. If the user disputes the complaint, they can pass a note back saying so. GitHub exercises little discretion in the process other than determining whether the notices meet the minimum requirements of the DMCA. **It is up to the parties (and their lawyers) to evaluate the merit of their claims**, bearing in mind that notices must be made under penalty of perjury." (emphasis mine)

As stated before, this is already happening between the involved parties. 

If you have any further legal inquiries, I have to ask you to direct them to info@neo4j.com.

**Comment by jmsuhy** [comment]
While I appreciate the ongoing communications and the technicalities involved in addressing the Free Software Foundation's cease and desist letter, it remains crucial to clarify the situation regarding the use of the AGPL license in conjunction with the commons clause in the Neo4j repository. The crux of the issue lies in the potential for confusion within the community. By employing the AGPL, a license dedicated to preserving freedom in software distribution and use, alongside additional restrictions like the commons clause, there is a significant risk of misleading users and developers about the true nature of the software's open-source status. This not only contravenes the spirit of the AGPL but also undermines trust within the open-source community.

To maintain transparency and uphold the principles of free software, it is imperative that Neo4j revisits the licensing of the infringing files to ensure they either comply fully with the AGPL without additional restrictions or adopt an alternative licensing strategy that accurately reflects the limitations imposed by the commons clause. 

This action would demonstrate a commitment to clear communication and integrity in licensing, benefiting both Neo4j and the broader open-source community.

**Comment by jmsuhy** [comment]
It looks like you have been forced to comply with the Free Software Foundation's cease and desist.  

I see the following tags with the infringing AGPL license files are gone.

3.5.0-alpha01
3.5.0-alpha02
3.5.0-alpha04
3.5.0-alpha05
3.5.0-alpha06
3.5.0-alpha07
3.5.0-alpha08
3.5.0-alpha09
3.5.0-beta01
3.5.0-beta02
3.5.0-beta03
