### ISSUE TITLE
neo4j-admin database dump sends --verbose output to the standard output, causing bad dumps

### ISSUE THREAD

**Issue by marco-brandizi** [neo4j/neo4j#13397]
- Neo4j version: 5.15.0 and 5.16.0
- Operating system: macOS and Linux

### Steps to reproduce

Try this command:

```bash
"$NEO4J_HOME/bin/neo4j-admin" database dump --to-stdout neo4j >/tmp/test.dump
```

then, try to give a look to the dump file: 

```bash
less /tmp/test.dump
```

and try to use the dump file with the load command

### Expected behavior

The dump file should be correct, ie, it should contain only dump data, and the load command should restore the dumped database.

### Actual behavior

The dump file contains diagnostic messages coming from `--verbose`, which should be sent to stderr. The resulting dump has an invalid format and the load command tells so. 

This is very bad, since the load command can't tell you the root of the problem and you might take a while before realising what's going on (like the 2 hours I've just spent on it, sigh :-( ).

Clearly, the fix to it is ensuring that all user messages go to stderr, not stdout. Since this might be hard to do (eg, third-party libraries, exceptions), a quicker fix might be adding `--to-file` and `--from-file` to these commands (currently, they only accept a directory, where they expect to find `$dbname.dump`).

**Comment by docrozza** [comment]
Fixed - should be available in 5.19
