### ISSUE TITLE
Neo4j 4.4 after version 4.4.19 uses 3GB more memory compare to 4.4.18

### ISSUE THREAD

**Issue by dmatviichuk** [neo4j/neo4j#13394]
- Neo4j version: 4.4.19-4.4.30
- Operating system: Docker image 4.4.30-enterprise
- API/Driver: neo4j console
- **Steps to reproduce**
- Expected behavior: memory usage same as on 4.4.18 version or lower
- Actual behavior: Neo4j 4.4.19-4.4.30 uses 3GB more memory

1. Pull the image: `docker pull neo4j:4.4.18-enterprise`
2. Check memory consumption:
![image](https://github.com/neo4j/neo4j/assets/140102908/f413896e-76fc-4369-9806-15a2f636540d)

3. Pull the image: `docker pull neo4j:4.4.19-enterprise` (or 21...up to 30)
4. Check memory consumption:
![image](https://github.com/neo4j/neo4j/assets/140102908/1c11da8f-0429-4976-a912-2d6ee35309bc)

**Comment by arnefischereit** [comment]
Hi @dmatviichuk,

For information regarding memory-related questions, please refer to [our documentation](https://neo4j.com/docs/operations-manual/current/performance/memory-configuration/).

I just booted the two versions of Neo4j against each other on my machine and got
- 2.46 GiB memory consumption for 4.4.18-enterprise and
- 1.47 GiB memory consumption for 4.4.19-enterprise.

YMMV but I hope that the documentation gives you enough information to troubleshoot your specific configuration.
