### ISSUE TITLE
Neo4j Vector Index - Dimension limit of 2048

### ISSUE THREAD

**Issue by mfreeman451** [neo4j/neo4j#13406]
My sentence transformer creates 4096 dimension vector arrays and I believe the limit on the index is 2048. 

Any chance we can get support in the vector index for larger vectorized embeddings, maybe up to 4096?

**Comment by klaren** [comment]
It is definitely on the roadmap to increase the number of supported dimensions. I can not guarantee it, but if everything goes as planned it should land in Neo4j 5.18 or Neo4j 5.19.

**Comment by klaren** [comment]
@mfreeman451 5.18 is now released with the requested support for 4096 dimension.

https://neo4j.com/release-notes/database/neo4j-5/

> * Supports for up to 4096 dimensional vectors and integral element vectors
