### ISSUE TITLE
7474 web interface now working? 

### ISSUE THREAD

**Issue by chopin1998** [neo4j/neo4j#13409]
I have compiled neo4j

![image](https://github.com/neo4j/neo4j/assets/643792/774093dd-ec2f-43a2-9269-d14d3f850ad0)

then, unpack and launch server

![image](https://github.com/neo4j/neo4j/assets/643792/089235d4-de4d-4522-b08c-377a90f28545)

server running, when i open link to server 7474 port, it forward to http://192.168.10.20:7474/browser/

but no web page shown..

![image](https://github.com/neo4j/neo4j/assets/643792/8260775b-7237-442b-8589-e7b378447df4)

what's wrong?
Thank you!

**Comment by chopin1998** [comment]
seems it lack neo4j-browser.jar file in lib? 

i copy the file from docker, web brower work now...

**Comment by klaren** [comment]
Yes, that jar file is not part of the main repository. The neo4j browser is developed as a separate project here: https://github.com/neo4j/neo4j-browser
