### ISSUE TITLE
Query sometimes fails with "Could not compile query due to insanely frequent schema changes"

### ISSUE THREAD

**Issue by achantavy** [neo4j/neo4j#13404]
Hi there, the integration test suite for our cartography OSS project has started intermittently failing with a "could not compile query" error.

Link to full docker command line: https://github.com/lyft/cartography/blob/cc30a37471c0a2768eddc4a217c1f739fdae6eec/.github/workflows/test_suite.yml#L32-L38

Neo4j version: issue observed in docker images tagged with 4.4-community, 4.4.29-community, and 4.4.30-community
Operating system: ubuntu-latest as part of docker container
API/Driver: python driver 4.4.x
Python version: 3.10

## Expected behavior

When we run the following code in our CI

```python
neo4j_session.run(
            """
            MERGE (homer:Human{id: "Homer"})
    
            MERGE (bart:Human{id: "Bart"})
            MERGE (homer)<-[:PARENT]-(bart)
    
            MERGE (lisa:Human{id: "Lisa"})
            MERGE (homer)<-[:PARENT]-(lisa)
            """,
        )
```

we expect it to create a graph that looks like this:

```
(:Human{name:"Homer})<-[:PARENT]-(:Human{name:"Bart"})
                                          <-[:PARENT]-(:Human{name:"Lisa"})
```

And we expect it to behave this way every time.

Here is a link to a successful run: https://github.com/lyft/cartography/actions/runs/8012473951/job/21887871412

## Actual behavior

In the past ~4 weeks, we noticed that running this query as part of integration tests in our CI system results in intermittent failures (maybe 2 out of 5 times):

```
=================================== FAILURES ===================================
_______________________________ test_check_rels ________________________________

neo4j_session = <neo4j.work.simple.Session object at 0x7fe16e47a350>

    def test_check_rels(neo4j_session):
        # Arrange
>       neo4j_session.run(
            """
            MERGE (homer:Human{id: "Homer"})
    
            MERGE (bart:Human{id: "Bart"})
            MERGE (homer)<-[:PARENT]-(bart)
    
            MERGE (lisa:Human{id: "Lisa"})
            MERGE (homer)<-[:PARENT]-(lisa)
            """,
        )

tests/integration/test_util.py:9: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/neo4j/work/simple.py:217: in run
    self._autoResult._run(
/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/neo4j/work/result.py:115: in _run
    self._attach()
/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/neo4j/work/result.py:204: in _attach
    self._connection.fetch_message()
/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/neo4j/io/_common.py:187: in inner
    func(*args, **kwargs)
/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/neo4j/io/_bolt4.py:306: in fetch_message
    response.on_failure(summary_metadata or {})
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <neo4j.io._common.Response object at 0x7fe16e479cf0>
metadata = {'code': 'Neo.DatabaseError.Statement.ExecutionFailed', 'message': 'Could not compile query due to insanely frequent schema changes'}

    def on_failure(self, metadata):
        """ Called when a FAILURE message has been received.
        """
        try:
            self.connection.reset()
        except (SessionExpired, ServiceUnavailable):
            pass
        handler = self.handlers.get("on_failure")
        if callable(handler):
            handler(metadata)
        handler = self.handlers.get("on_summary")
        if callable(handler):
            handler()
>       raise Neo4jError.hydrate(**metadata)
E       neo4j.exceptions.DatabaseError: {code: Neo.DatabaseError.Statement.ExecutionFailed} {message: Could not compile query due to insanely frequent schema changes}
```

- Here is a link to that failing CI run: https://github.com/lyft/cartography/actions/runs/8010280995/job/21881522295.

- Link to the [intermittently failing test](https://github.com/lyft/cartography/blob/cc30a37471c0a2768eddc4a217c1f739fdae6eec/tests/integration/test_util.py#L9-L19).

## Other observations
- We are able to workaround this issue by simply re-running the job. Sometimes it resolves itself, but sometimes it continues to fail with the "Could not compile query due to insanely frequent schema changes" error.
- I've observed this problem intermittently occuring in the `neo4j:4.4-community`, `neo4j:4.4.29-community`, and `neo4j:4.4.30-community` official docker images.
- This problem does not occur with the `neo4j:5 docker` image.
- Background: Our integration tests perform several write, read, and delete operations as part of the test graph to make sure our own code behaves as expected.

**Comment by JonasHolgersson** [comment]
Thanks for reporting, we will look into it.

**Comment by arnefischereit** [comment]
There exists a support case in parallel to this issue.

Short description of what is happening:
The query engine optimiser uses indexes and constraints for executing the query. In your scenario, these are added and removed while the optimiser runs and therefore, the optimiser needs to try to run again. It does that 20 times and after that it gives up with the error message that you see.

Without having looked into the details of your setup, I would recommend that if you need queries to be stably planned, to not on the same instance add and remove indexes and/or constraints.

I am sorry for this very high-level answer, I would hope that your support engineer can give you more guidance.

The support case has been closed on our side. I will therefore close this issue. Please reach out to support if you need more help regarding this issue.

**Comment by achantavy** [comment]
Thanks for the reply @arnefischereit.

In our project, we [call](https://github.com/lyft/cartography/blob/fa1be115c80e83cefe0e31be5d738b5cda9a0887/cartography/client/core/tx.py#L252) `CREATE INDEX IF NOT EXISTS ...` before we write a given node type to the graph.

We only see this in our CI integration tests and never in production. These integration tests run on a neo4j docker container that is freshly spun up every time we push code to our Github repo. Since the integration tests write very small amounts of data, we could be calling `CREATE INDEX..` much more frequently than in production where we would be writing signifcantly more data and therefore taking more time in between `CREATE INDEX` calls.

Could this be causing the behavior you're referring to where the query engine adds constraints frequently?

**Comment by blouerat** [comment]
Hi @achantavy,

That sounds right yes. I see 418 indexes in [indexes.cypher](https://github.com/lyft/cartography/blob/fa1be115c80e83cefe0e31be5d738b5cda9a0887/cartography/data/indexes.cypher), it may very well explain why the planner can't finalise its plan successfully.
Waiting a little bit longer for the indexes to be ready before executing your first query against the DB should do the trick in this case.
