### ISSUE TITLE
@UserAggregationFunction should allow function parameters

### ISSUE THREAD

**Issue by rickardoberg** [neo4j/neo4j#13403]
I need to add a histogram custom aggregate function, using the @UserAggregationFunction annotation. Unfortunately it requires a few parameters, like bin ranges, and so these need to be passed to the method somehow.

I would like custom user aggregation functions to be able to take parameters, so that I can use this to customize the output and behavior.

Example:
```
    @UserAggregationFunction("statistics.histogram")
    @Description("Returns histogram bins for selected field")
    public HistogramFunction histogram(List<Map<String, Double>> bins) {
        return new HistogramFunction(bins);
    }
```
to be invoked with:
```
   CALL statistics.histogram(node.somefield,[{from: 0,to: 10},{from:10,to:20}]) YIELD result
```
I think this would be a logical and natural extension of what is already there, and would allow user aggregation functions to do more sophisticated things, like the above.

**Comment by rickardoberg** [comment]
Current workaround is to create a separate stored procedure that takes the parameters and sets them in a threadlocal, and then the aggregation function can use that. 

Yeah. I know. But it works.

**Comment by rickardoberg** [comment]
Got a solution on the forum on how to make this work:
https://community.neo4j.com/t/useraggregationfunction-with-parameters/66440

So the actual issue here appears to be documentation. Just update the UserAggregationFunction docs to explain how to pass in custom parameters.

**Comment by pontusmelke** [comment]
Hi @rickardoberg, long time no see 😄 

Yes, as you have already figured out you can pass in more parameters and docs should definitely have that information. We'll make sure to update docs!

Regards,
Pontus
