### ISSUE TITLE
SessionExpired: Failed to read from defunct connection IPv4Address(('d5dffe81.databases.neo4j.io', 7687)) (ResolvedIPv4Address(('34.126.114.186', 7687)))

### ISSUE THREAD

**Issue by KaifAhmad1** [neo4j/neo4j#13402]
### System Info
Python = 3.10.10
neo4j = 5
cuda = 12.1 
OS = Windows 11 x64 
pip = 24.0 

``` Python 
graph.query("""
UNWIND $data AS row
CREATE (c:Chunk {text: row.text})
WITH c, row
CALL db.create.setVectorProperty(c, 'embedding', row.embedding)
YIELD node
RETURN distinct 'done'
""", {'data': chunks})
```
ERROR:neo4j.io:Failed to read from defunct connection ResolvedIPv4Address(('34.126.114.186', 7687)) (ResolvedIPv4Address(('34.126.114.186', 7687)))
ERROR:neo4j.pool:Unable to retrieve routing information
---------------------------------------------------------------------------
ServiceUnavailable                        Traceback (most recent call last)
[<ipython-input-35-e99e447c089e>](https://localhost:8080/#) in <cell line: 1>()
----> 1 graph.query("""
      2 UNWIND $data AS row
      3 CREATE (c:Chunk {text: row.text})
      4 WITH c, row
      5 CALL db.create.setVectorProperty(c, 'embedding', row.embedding)

6 frames
[/usr/local/lib/python3.10/dist-packages/neo4j/_sync/io/_pool.py](https://localhost:8080/#) in update_routing_table(self, database, imp_user, bookmarks, auth, acquisition_timeout, database_callback)
    802             # None of the routers have been successful, so just fail
    803             log.error("Unable to retrieve routing information")
--> 804             raise ServiceUnavailable("Unable to retrieve routing information")
    805 
    806     def update_connection_pool(self, *, database):

ServiceUnavailable: Unable to retrieve routing information

``` Python 
# Instantiate Neo4j vector from documents
neo4j_vector = Neo4jVector.from_documents(
    processed_text_splits,
    embeddings,
    index_name='KG-Enhanced-QnA-Biomedical',
     url=os.environ["NEO4J_URI"],
    username=os.environ["NEO4J_USERNAME"],
    password=os.environ["NEO4J_PASSWORD"]
)
```

ERROR:neo4j.io:Failed to read from defunct connection IPv4Address(('d5dffe81.databases.neo4j.io', 7687)) (ResolvedIPv4Address(('34.126.114.186', 7687)))
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/neo4j/_sync/io/_common.py](https://localhost:8080/#) in _buffer_one_chunk(self)
     50                     # Determine the chunk size and skip noop
---> 51                     receive_into_buffer(self._socket, self._buffer, 2)
     52                     chunk_size = self._buffer.pop_u16()

16 frames
OSError: No data

The above exception was the direct cause of the following exception:

SessionExpired                            Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/neo4j/_sync/io/_bolt.py](https://localhost:8080/#) in _set_defunct(self, message, error, silent)
    922         else:
    923             if error:
--> 924                 raise SessionExpired(message) from error
    925             else:
    926                 raise SessionExpired(message)

SessionExpired: Failed to read from defunct connection IPv4Address(('d5dffe81.databases.neo4j.io', 7687)) (ResolvedIPv4Address(('34.126.114.186', 7687)))

**Comment by mnd999** [comment]
It's a little hard to tell what is going on here from your description. It could be a simple connectivity problem, or it could be that the database is running out of memory and not responding. You don't say how much data you are loading via `$data` - if it's a large dataset you may wish to test with a couple of nodes to see if that is successful. If so, you might want to look into batching your load into multiple transactions using [CALL IN TRANSACTIONS](https://neo4j.com/docs/cypher-manual/current/subqueries/subqueries-in-transactions/) or one of the APOC functions.

Generally we prefer to answer these types of questions in [our community forums](https://community.neo4j.com/) or on our [discord](https://discord.gg/neo4j) and you will likely get a faster response there. Github is more setup for bug reports in the product.

**Comment by fai-ahm83** [comment]
@KaifAhmad1 , did you manage to get a resolution for it? I am also facing this issue.

**Comment by KaifAhmad1** [comment]
@fai-ahm83   No resolution yet, unfortunately.

**Comment by tipu** [comment]
@KaifAhmad1 i am getting this issue but intermittently, is this something you experience on every run?

**Comment by robsdedude** [comment]
What library are you using and which version? I don't recognize `graph.query` as a driver API.

If the official driver is being used (directly or indirectly), you can enable debug logging. See the [API docs](https://neo4j.com/docs/api/python-driver/current/api.html#logging) on how to do that. Maybe that helps you understand when exactly the connection breaks.

Further, the stack trace is incomplete. At some point it just states "6 frames". That's not very helpful either. Can you share the whole trace, please?

In any case, this is very likely not a but with the driver or the DBMS, but a connectivity issue. Therefore, I will close the issue. Please keep up the discussion. I'm happy to re-open the GH issue should we be able to identify a bug here.
