### ISSUE TITLE
Neo4j v5 Load Error: Failed to load database 'neo4j': Archive does not exist: F:\neo4j-community-5.17.0\import\neo4j.dumpLoad failed for databases: 'neo4j'

### ISSUE THREAD

**Issue by zyh20011** [neo4j/neo4j#13412]
I'm having trouble loading a dump file into neo4j database version5.17.0 in Windows 11

- Neo4j version: 5.17.9
- Operating system: Windows11
- Java version: Java(TM)SE Development Kit 17.0.10(64-bit)

when I run the command：
`neo4j-admin database load --from-path=F:\neo4j-community-5.17.0\import neo4j --overwrite-destination=true`

and the error result is:
`Failed to load database 'neo4j': Archive does not exist: F:\neo4j-community-5.17.0\import\neo4j.dumpLoad failed for databases: 'neo4j'
Load failed for databases: 'neo4j'
Run with '--verbose' for a more detailed error message.`

I have seen some methods in other issues, but didn't succeed, such as return to version 4 and update to version 5.

I want to load the file successfully, thanks for your help!

**Comment by zyh20011** [comment]
oh! I solved it, I just rename the file 'neo4j.dump'.

**Comment by l-heemann** [comment]
Yes `neo4j-admin load` expects the file to be named `<database>.dump`. Closing this issue since it seems like you've found the solution.
