### ISSUE TITLE
Cluster status endpoint returning wrong response

### ISSUE THREAD

**Issue by tim-hanssen** [neo4j/neo4j#13418]
We are seeing an unexpected result of the status endpoints while monitoring a cluster. The read-only and available endpoints are falsely returning that the server is able to respond to queries.

- Neo4j version: 4.4.31
- Operating system: Ubuntu
- API/Driver: HTTP status endpoints

**Steps to reproduce**
- Expected behavior

Response should follow the description as mentioned in the docs https://neo4j.com/docs/operations-manual/4.4/monitoring/causal-cluster/http-endpoints/.

- Actual behavior
The available and read-only endpoints return "true" with a status code of 200 OK. While the server is still doing a store copy and is not able to respond to queries.

![image](https://github.com/neo4j/neo4j/assets/11192051/7d436235-5fd4-48ac-9cb7-ba53ad8b38f9)

If queries are preformed the driver also returns that the database is not available:
"Neo.TransientError.Database.DatabaseUnavailable" and message "Database 'example' is unavailable."

Querying `:sysinfo` on one of the cluster members the server is shown with the state set to `store_copy`.

**Comment by tomswinkels** [comment]
Any update?

**Comment by tim-hanssen** [comment]
I think this has been fixed in 4.4.33.

**Comment by tim-hanssen** [comment]
confirmed to be fixed
