### ISSUE TITLE
Hinting a relationship type scan failed

### ISSUE THREAD

**Issue by salted-yu** [neo4j/neo4j#13414]
- Neo4j version: neo4j-enterprise-5.15
- Operating system: Ubuntu 22.04
- API/Driver: Cypher
- **Steps to reproduce**
1. create the graph
>create (a:b  {name:"Kim", age:514})-[:study]->(b:s{name:"Japanese"})
>create (a)-[:study{year:5}]->(c:s{name:"Math"})
>create (aa:b {name:"Ono", age:114})-[:study]->(b)
2. use the query Hinting a relationship type scan
>match (a:b)-[r:study]->(class:s) using scan  r:study return *;
- Expected behavior
It should run successfully
- Actual behavior
It failed with error message:
>Error: Neo.DatabaseError.Statement.ExecutionFailed
>Failed to fulfil the hints of the query.
>Could not solve these hints: `USING SCAN r:study`
>
>Plan .produceResults("a", "class", "r")
>.filter("class:s")
>.expandAll("(a)-[r:study]->(class)")
>.nodeByLabelScan("a", "b", IndexOrderNone)
>.build()

**Comment by InverseFalcon** [comment]
Can you provide a screenshot of the result of `SHOW INDEXES` ? You will need to confirm the presence of a LOOKUP index on relationships, as it is this lookup index that backs the relationship type scan capability. If no such lookup index exists, then relationship type scans are impossible until you create one.

**Comment by salted-yu** [comment]
Oh, yes. After create this LOOKUP index on the relationship, this query run successfully. Thank you!
