### ISSUE TITLE
Node with 's' label don't show anything in neo4j browser.

### ISSUE THREAD

**Issue by salted-yu** [neo4j/neo4j#13413]
- Neo4j version: Neo4j-Enterprise-5.15.0
- Operating system: Ubuntu 22.04
- API/Driver: Cypher
- **Steps to reproduce**
use the cypher query in neo4j browser with empty database:
> create (a:s  {name:"Kim"})-[:learn]->(b:subject {name:"Japanese"}) return *; 
- Expected behavior
return one node labeled 's' with name "Kim", one node labeled 'subject' with name "Japanese" and an edge "learn". 
- Actual behavior
return one node labeled 's' with no property, one node labeled 'subject' with name "Japanese" and an edge "learn". 
![image](https://github.com/neo4j/neo4j/assets/61446801/13eaf62a-9cfc-44f2-ba6f-02e46deae788)

**Comment by InverseFalcon** [comment]
To note, your screenshot appears to show the expected result: There is a node with label `s` (the orange node), and it has a `name` property with value `Kim`. You can see the property and its value in the side panel of your screenshot.

The orange node does not have a display label showing, but that is a display issue (you can change the display label in the result pane) and the lack of a display label (again, purely a visualizer thing) doesn't say anything about the lack of a property.

**Comment by salted-yu** [comment]
Thank you for your explain. I will close the issue.
