### ISSUE TITLE
message: Unknown function 'genai.vector.encode'

### ISSUE THREAD

**Issue by kamzz1107** [neo4j/neo4j#13422]
I am using the Ubuntu 20.x and updated to neo4j 5.18.0 community version. While tunning the Genai encoder function I am getting error message: Unknown function 'genai.vector.encode'. as per the documentation I should have the jar available in products folder in neo4j_home but the folder itself is missing in the installation. Could you please help if we can get the jar externally as we can get for apoc and GDS.

**Comment by InverseFalcon** [comment]
I'm pretty sure GenAI integrations require Enterprise Edition, and I can see the plugin in Enterprise Edition downloads, including what you can download via Neo4j Desktop.
Here's the page for it in our official docs, notice the "Enterprise Edition" tag in the upper right:
https://neo4j.com/docs/cypher-manual/current/genai-integrations/

**Comment by Manuel-Sphe** [comment]
Also getting the same error on enterprise btw

**Comment by parnmatt** [comment]
As noted by @InverseFalcon the GenAI plugin is an Aura feature, also available for on-prem Enterprise.

Community edition is not packaged with the plugin, and will not contain a `products` directory containing prepackaged plugins. It will have a `labs` directory for a similar purpose.
Enterprise edition will have a `products` directory, which contains prepackaged plugins such as the GenAI plugin.

As with all plugins, be those prepackaged in `products` or `labs`, or you've downloaded yourself, or using something third-party; the plugin JARs would need to be manually moved into the `plugins` directory, as plugins are opt-in. https://neo4j.com/docs/operations-manual/5/configuration/plugins/

If using docker, you can ensure the right plugins are included with `NEO4J_PLUGINS`: https://neo4j.com/docs/operations-manual/current/docker/plugins/

@Manuel-Sphe can you please confirm the enterprise version you are using, and list the contents of the `products` and `plugins` directories (omitting any private plugins you do not wish to disclose publically.)

**Comment by Manuel-Sphe** [comment]
Thanks @parnmatt for the clarification,  I moved the `gen-ai` jar file to the plugins everything works fine.

**Comment by parnmatt** [comment]
@Manuel-Sphe good to hear.
I believe the two noted issues here have been addressed, and thus will close the issue for now.

**Comment by amirsa66** [comment]
Hi there,
I've just installed Neo4j desktop enterprise 5.23.0. I have the same problem: _Unknown function 'genai.vector.encode'_
Unfortunately, there is no `products` directory nor `plugins` as @parnmatt  mentioned.
What should I do?
