### ISSUE TITLE
Unexpected UnknownError because of a plan with no provided order

### ISSUE THREAD

**Issue by CelineWuest** [neo4j/neo4j#13427]
When running the following query:
```cypher
RETURN COUNT {
	RETURN null AS n0
		UNION
	RETURN null AS n0
} AS n1 ORDER BY 0
```

I encountered the following error:
```
UnknownError: While marking leveraged order we encountered a plan with no provided order. This is a bug.
.apply()
.|.aggregation(Seq(), Seq("count(*) AS n1"))
.|.apply()
.|.|.argument()
.|.apply()
.|.|.distinct("`  n0@0` AS `  n0@0`")
.|.|.union()
.|.|.|.projection("`  n0@2` AS `  n0@0`")
.|.|.|.projection("NULL AS `  n0@2`")
.|.|.|.argument()
.|.|.projection("`  n0@1` AS `  n0@0`")
.|.|.projection("NULL AS `  n0@1`")
.|.|.argument()
.|.argument()
.sort("`  $autoint_0@4` ASC")
.projection("$`  AUTOINT0` AS `  $autoint_0@4`")
.argument()
.build()
```

I believe the query mentioned above is semantically and syntactically correct and thus no error should be thrown here.

I encountered this issue when testing queries against the **Neo4j 5.18.0 enterprise version** in a Docker container running **alpine v.3**.

### Steps to reproduce
Run the following query and observe it throws an error:
```cypher
RETURN COUNT {
	RETURN null AS n0
		UNION
	RETURN null AS n0
} AS n1 ORDER BY 0
```

### Expected behavior
The query should run successfully

### Actual behavior
The query fails with the error message `UnknownError: While marking leveraged order we encountered a plan with no provided order. This is a bug. [...]`

**Comment by inmost-light** [comment]
@DominicWuest
Thank you for reporting, this should be fixed in 5.19.
