### ISSUE TITLE
Inconsistent results when adding an inconsequential `WITH *` clause

### ISSUE THREAD

**Issue by CelineWuest** [neo4j/neo4j#13425]
I found a discrepancy when running two semantically equivalent queries against an empty database:

---
1:
```cypher
OPTIONAL MATCH ({n0:0, n1:0})
WITH *
RETURN max(0) AS n2, localdatetime('2015185T19:32:24') AS n3
	ORDER BY localdatetime('2015185T19:32:24')
```
Produces:
```
╒═══╤═════════════════════╕
│n2 │n3                   │
╞═══╪═════════════════════╡
│0  │"2015-07-04T19:32:24"│
└───┴─────────────────────┘
```

---
2:
```cypher
OPTIONAL MATCH ({n0:0, n1:0})
RETURN max(0) AS n2, localdatetime('2015185T19:32:24') AS n3
	ORDER BY localdatetime('2015185T19:32:24')
```
Produces:
```
╒═══╤════╕
│n2 │n3  │
╞═══╪════╡
│0  │null│
└───┴────┘
```
---

I believe the queries mentioned above are semantically equivalent and thus their result should be the same.

Additionally, this result only occurs after the commit **be2da17**, before which both queries return the same result.

I encountered this issue when testing queries against the **Neo4j 5.18.0 community & enterprise version** in a Docker container running **alpine v.3**.

### Steps to reproduce
Run the aforementioned, semantically equivalent, queries against an empty database and observe that their results differ.

### Expected behavior
The queries should result in the same behavior

### Actual behavior
The query results differ

**Comment by inmost-light** [comment]
@DominicWuest Thank you for reporting, this should be fixed in 5.21.
