### ISSUE TITLE
Unexpected UnknownError in SlotConfiguration

### ISSUE THREAD

**Issue by CelineWuest** [neo4j/neo4j#13426]
When running the following query:
```cypher
MATCH ()-[x]-()--()--()--() WHERE false
UNWIND 0 AS n0
MATCH ()--()--(:n1)
MATCH ({n1:x.n2, n1:0})--(), ()--()
RETURN 0 AS n3
	UNION
MERGE ()-[:n4]->()<-[:n5]-()-[:n6]->()-[:n7]->()<-[:n8]-()<-[:n10]-()<-[:n11]-()-[:n12]->()<-[:n13]-()
RETURN 0 AS n3
```

I encountered the following error:
```
UnknownError: SlotWithKeyAndAliases(DuplicatedSlotKey(RuntimeKey(x,PropertyKeyName(n2),RELATIONSHIP_TYPE),11),RefSlot(11,false,Any),Set()) (of class org.neo4j.cypher.internal.physicalplanning.SlotConfiguration$SlotWithKeyAndAliases)
```

I believe the query mentioned above is semantically and syntactically correct and thus no error should be thrown here.

Additionally, this error only occurs after the commit **cc5c444**, before which the query runs fine.

I encountered this issue when testing queries against the **Neo4j 5.18.0 community & enterprise version** in a Docker container running **alpine v.3**.

### Steps to reproduce
Run the following query and observe it throws an error:
```cypher
MATCH ()-[x]-()--()--()--() WHERE false
UNWIND 0 AS n0
MATCH ()--()--(:n1)
MATCH ({n1:x.n2, n1:0})--(), ()--()
RETURN 0 AS n3
	UNION
MERGE ()-[:n4]->()<-[:n5]-()-[:n6]->()-[:n7]->()<-[:n8]-()<-[:n10]-()<-[:n11]-()-[:n12]->()<-[:n13]-()
RETURN 0 AS n3
```

### Expected behavior
The query should run successfully

### Actual behavior
The query fails with the error message `UnknownError: [...] (of class org.neo4j.cypher.internal.physicalplanning.SlotConfiguration$SlotWithKeyAndAliases)`

**Comment by JonasHolgersson** [comment]
Hi @DominicWuest , thanks again for reporting!
This has been fixed in 5.21

Regards,
Jonas
