### ISSUE TITLE
Query causes Stackoverflow

### ISSUE THREAD

**Issue by CelineWuest** [neo4j/neo4j#13431]
When running the following query:
```cypher
MATCH ()
CALL {
	OPTIONAL MATCH ({n0:localtime('12:50:35.556')})
	CALL {
		RETURN null AS n1
			UNION ALL
		RETURN null AS n1
	} WITH 0 AS n2 ORDER BY COUNT { () } SKIP 0
	RETURN 0 AS n3
} RETURN 0
```

The query runs for a while and then errors with a Stackoverflow error.

I encountered this issue when testing queries against the **Neo4j 5.18.0 enterprise version** in a Docker container running **alpine v.3**.

### Steps to reproduce
Run the following queries and observe it throws an error:
```cypher
MATCH ()
CALL {
	OPTIONAL MATCH ({n0:localtime('12:50:35.556')})
	CALL {
		RETURN null AS n1
			UNION ALL
		RETURN null AS n1
	} WITH 0 AS n2 ORDER BY COUNT { () } SKIP 0
	RETURN 0 AS n3
} RETURN 0
```

### Expected behavior
The query should run successfully

### Actual behavior
The query fails due to a Stackoverflow error.

**Comment by pontusmelke** [comment]
Hi @DominicWuest 

Thanks for reporting this! We have identified the problem and a fix will roll out with the next release.

I'll close this one but don't hesitate to reopen or open a new issue should the problem reappear.

Regards,
Pontus
