### ISSUE TITLE
Unexpected SyntaxError in `toBoolean ∘ all`

### ISSUE THREAD

**Issue by CelineWuest** [neo4j/neo4j#13432]
When running the following query:
```cypher
RETURN (CASE toBoolean(all(n0 IN null WHERE true)) WHEN false THEN 0 END)
```

I encountered the following error:
```
Neo4jError: Neo.ClientError.Statement.SyntaxError (Invalid input 'toBoolean': expected "WHEN" (line 1, column 14 (offset: 13))
"RETURN (CASE toBoolean(all(n0 IN null WHERE true)) WHEN false THEN 0 END)"
              ^)
```

I believe the query mentioned above is semantically and syntactically correct and thus no error should be thrown here.

I encountered this issue when testing queries against the **Neo4j 5.18.0 community & enterprise version** in a Docker container running **alpine v.3**.

Similarly, running

```cypher
RETURN toBoolean(all(n0 IN [] WHERE true))
```

results in the following error:
```
Neo4jError: Neo.ClientError.Statement.SyntaxError (Invalid input 'WHERE': expected
  [...]
  "^" (line 1, column 31 (offset: 30))
"RETURN toBoolean(all(n0 IN [] WHERE true))"
                               ^)
```

### Steps to reproduce
Run the following queries and observe it throws an error:
```cypher
RETURN (CASE toBoolean(all(n0 IN null WHERE true)) WHEN false THEN 0 END)
```

### Expected behavior
The query should run successfully

### Actual behavior
The query fails with the error message `SyntaxError (Invalid input 'toBoolean': expected "WHEN")`

**Comment by loveleif** [comment]
Thanks @DominicWuest! Should be fixed in 5.21.
