### ISSUE TITLE
Different results when adding an inconsequential `CASE` clause

### ISSUE THREAD

**Issue by CelineWuest** [neo4j/neo4j#13430]
I found a discrepancy when running two semantically equivalent queries against an empty database:

---
1:
```cypher
CALL {
	FOREACH ( n0 IN [] | MERGE () MERGE () )
} RETURN 0 AS n1
	UNION ALL
RETURN 1 AS n1
	UNION ALL
UNWIND null AS n2
RETURN 2 AS n1
```
Produces:
```
╒═══╕
│n1 │
╞═══╡
│1  │
└───┘
```

---
2:
```cypher
CALL {
	FOREACH ( n0 IN [] | MERGE () MERGE () )
} RETURN 0 AS n1
	UNION ALL
RETURN 1 AS n1
	UNION ALL
UNWIND (CASE WHEN EXISTS { () } THEN null END) AS n2
RETURN 2 AS n1
```
Produces:
```
╒═══╕
│n1 │
╞═══╡
│0  │
└───┘
```
---

I believe the queries mentioned above are semantically equivalent because `null` is equivalent to `CASE WHEN EXISTS { () } THEN null END`.

I encountered this issue when testing queries against the **Neo4j 5.18.0 enterprise version** in a Docker container running **alpine v.3**.
When testing the query against the community edition, the query results equal.

The query results don't differ in **Neo4j 5.13.0**, but do in **Neo4j 5.14.0**.

### Steps to reproduce
Run the aforementioned, semantically equivalent, queries against an empty database and observe that their results differ.

### Expected behavior
The queries should result in the same behavior

### Actual behavior
The query results differ

**Comment by pontusmelke** [comment]
Hi @DominicWuest,
Thanks for reporting this!

I tried to reproduce this but I wasn't able to. I get `0, 1` or `1, 0` as a result of both queries in 5.13, 5.14, 5.18, and 5.18.1 enterprise edition. What am I missing? Could you run the two queries where you get different result with "EXPLAIN" and post the result here? (preferably either the plan you get in cypher-shell or use the "Export TXT" in the top right corner in browser)

Best regards,
Pontus

**Comment by CelineWuest** [comment]
Hello @pontusmelke!
I'm very sorry, I made a mistake when checking result equivalences. I fixed it now and closed another issue where I made the same mistake.

**Comment by pontusmelke** [comment]
No worries, thanks for keeping us on our toes 😅
