### ISSUE TITLE
Result rows do not work as expected.

### ISSUE THREAD

**Issue by wiltshire-eric** [neo4j/neo4j#13434]
Starting with a single Row with one string, then expanding to multiple rows appears to not be serial but rather future result rows is anticipated and affects previous calculations.

TO REPRODUCE

// Create 5 Nodes
CREATE (:TEST {id:1}),(:TEST {id:2}),(:TEST {id:3}),(:TEST {id:4}),(:TEST {id:5})

// Query to Reproduce
WITH toString(toInteger(rand()*1000000)) as r1
MATCH (t:TEST)
WITH t, r1
RETURN t, r1

// EXPECTED RESULTS
I would expect 5 rows with each TEST node and the single value of r1

// ACTUAL RESULTS
I get 5 rows with each TEST node and a recalculated random r1 string 

Version : Enterprise 5.16.0
OS: Ubuntu 22.04
API: Browser

**Comment by InverseFalcon** [comment]
Can you please provide the visual PROFILE plan of the execution? That may provide some clues.

**Comment by wiltshire-eric** [comment]
![image](https://github.com/neo4j/neo4j/assets/10505539/26ca7727-5f12-4244-aa1c-6b1cdc85e2fd)

The query plan is what is throwing me off.  Why is it performing a NodeByLabelScan BEFORE it is requested by the query.  Is it arbitrarily choosing which result set to calculate first? If a LIMIT 1 is added to the first line it completely alters the plan in unanticipated ways. Perhaps this isn't a bug, but It doesn't appear to follow the documentation on how a query is executed in serial.

**Comment by wiltshire-eric** [comment]
![image](https://github.com/neo4j/neo4j/assets/10505539/a15d7d92-430a-4a0f-ad6d-6dc6cb738c84)

**Comment by InverseFalcon** [comment]
I agree, that looks buggy to me. We'll need some eyes on it from our Cypher team.

**Comment by sherfert** [comment]
We had a very similar looking bug that was fixed in 5.18. ([Internal ticket link](https://github.com/neo-technology/neo4j/pull/24409))
Could you please try your query on 5.18 and confirm whether it is fixed/still buggy there?

**Comment by sherfert** [comment]
Assuming this is fixed as of my last comment. Feel free to reopen if that assumption was wrong.
