### ISSUE TITLE
Allow lists with arbitrary strings in CVS import by escaping array delimiter

### ISSUE THREAD

**Issue by nichtich** [neo4j/neo4j#13445]
## Feature request template

**Is your feature request related to a problem? Please describe.**

I want to import a graph with neo4j-admin. The graph is given in [CSV header format](https://neo4j.com/docs/operations-manual/current/tools/neo4j-admin/neo4j-admin-import/#import-tool-header-format) as CSV nodes file and CSV edges file. Some properties have list values. These values may contain arbitrary characters.

Given a minimal CSV nodes file and [delimiters](https://neo4j.com/docs/operations-manual/current/tutorial/neo4j-admin-import/#_csv_file_delimiters)  `--delimiter=";" --array-delimiter="|" --quote="'"`:

~~~
:ID;:LABEL;name:string[]
1;person;'a|b'
~~~

What if the names are not "a" and "b" but "x|y" and "z"? If another array delimiter is used (e.g. `,`), this may also be part of a string value. So there is no way to import strings with arbitrary characters.

**Describe the solution you'd like**
I'd like to escape the array delimiter, e.g. doubling:

~~~
:ID;:LABEL;name:string[]
1;person;'x||y|z'
~~~

would result in same as

~~~
CREATE (`1`:person {name:["x|y","z"]})
~~~

**Describe alternatives you've considered**
Maybe using the null-byte as array separator could work but then the CSV file cannot be edited by hand.

**Comment by brunobuss** [comment]
Hi @nichtich, thanks for the feedback on the CSV Import feature!

Since you mentioned escaping the array delimiter by doubling it, it looks like that you have some control over the generation of the CSVs or maybe a pre-processing phase before passing them to `neo4j-admin import`. So it looks like you're able to also use any arbitrary array delimiter, that would be correct?

You also said that you already thought about using another array delimiter. Besides the null-byte (which does not look like a good one), are you confident that your strings would contain even the [ASCII delimiter characters](https://en.wikipedia.org/wiki/Delimiter#ASCII_delimited_text) for example? The import command also allows you to set the array delimiter as any unicode character, so you're not restricted to ASCII either. Maybe this could help you with your current requirements?

**Comment by nichtich** [comment]
Thanks for the quick reply. Any special character (null byte, information separator code...) is a workaround with drawback of hardly being readable and editable by hand (and one must be sure to not use the character in actual data). For my current use case this is a minor issue indeed.

I'll keep the issue open because even if not being implemented, the limitation and workaround should be made clear in the documentation. The documentation may use the example `--array-delimiter="\x1C"` because escaping of control characters may be unknown to users (I had to look up the right way). Alternatively allow `--array-delimiter=U+001C` to use a specific character given by Unicode code point.

**Comment by brunobuss** [comment]
> Any special character (null byte, information separator code...) is a workaround with drawback of hardly being readable and editable by hand (and one must be sure to not use the character in actual data). For my current use case this is a minor issue indeed.

Handling arbitrary content (or providing the mechanism to do so) is always tricky! For example, if we support the double escaping, then it leads to what we do when we want a property array to contain an empty element (e.g. `'x||y|z'` wants `{name:["x", "", "y","z"]}`) :upside_down_face: 

I'm glad to hear that this is blocking you in using Neo4j though! The team added a note in our backlog of the wish for more flexibility in this aspect. If we revisit the property array parsing mechanism, we'll take this into consideration :)

> I'll keep the issue open because even if not being implemented, the limitation and workaround should be made clear in the documentation. The documentation may use the example --array-delimiter="\x1C" because escaping of control characters may be unknown to users (I had to look up the right way).

About the documentation, this is definitely something we can expand on. To double check, are you mentioning [this page](https://neo4j.com/docs/operations-manual/current/tutorial/neo4j-admin-import/#_csv_file_delimiters) or somewhere else where you feel we missed the opportunity to clarify how to use/pass control characters?

> Alternatively allow --array-delimiter=U+001C to use a specific character given by Unicode code point.

`--array-delimiter` (like other delimiters) supports unicode code points. Have you found an issue when trying to use it?

**Comment by nichtich** [comment]
> About the documentation, this is definitely something we can expand on. To double check, are you mentioning [this page](https://neo4j.com/docs/operations-manual/current/tutorial/neo4j-admin-import/#_csv_file_delimiters)

Yes

> `--array-delimiter` (like other delimiters) supports unicode code points. Have you found an issue when trying to use it?

The issue is only *how to escape a Unicode code point in the shell*. This is no big thing, just something that users might need to look up if it is not shown in the documentation example.

**Comment by brunobuss** [comment]
Hey @nichtich, we have updated [the examples](https://neo4j.com/docs/operations-manual/current/tutorial/neo4j-admin-import/#_csv_file_delimiters) to show how one can use the unicode code point for specifying a delimiter.
