### ISSUE TITLE
Importing csv quote issues even with "" escaping

### ISSUE THREAD

**Issue by spacether** [neo4j/neo4j#13450]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. 
If you have questions on how to use Neo4j, please ask on [StackOverflow](https://stackoverflow.com/questions/tagged/neo4j) instead of creating an issue here.

Before creating a new issue, please check whether someone else has raised the same issue. You may be able to add context to that issue instead of duplicating the report. However, each issue should also only be focussed on a _single_ problem, so do not describe new problems within an existing thread - these are very hard to track and manage, and your problem may be ignored. Finally, do not append comments to closed issues; if the same problem re-occurs, open a new issue, and include a link to the old one.

To help us understand your issue, please specify important details, primarily:

- Neo4j version: 5.19.0
- Operating system: MacOS 12.7.4
- API/Driver: (running LOAD CSV command from browser)
- **Steps to reproduce**
write a csv with the below data named enwiki-20240401-all-titles-in-ns0.csv
run docker with:
```
docker run \
    --restart always \
    --publish=7474:7474 --publish=7687:7687 \
    --volume=/Users/justinblack/programming/punnily/neo4j:/data \
    --volume=/Users/justinblack/programming/punnily/src/punnily:/var/lib/neo4j/import \
    --env apoc.import.file.enabled=true \
    neo4j:5.19.0
```
browse to http://localhost:7474/browser/ and connect to the neo4j database
in the top command input prompt on the webpage, run
```
LOAD CSV WITH HEADERS FROM 'file:/enwiki-20240401-all-titles-in-ns0.csv' AS row FIELDTERMINATOR '#'
WITH row
MERGE (t:Title {title: row.page_title})
```
- Expected behavior
I expect the csv import to work, all double quotes are escaped, and each title has an even number of quotes
- Actual behavior
An error is thrown on import

Additionally, include (as appropriate) log-files, stacktraces, and other debug output.

## Example bug report

When I import a csv with only one column, titles and my data is:
```
page_title
!
!!
!!!
!!!!!!!
!!!Fuck_You!!!
!!!Fuck_You!!!_And_Then_Some
!!!Fuck_You!!!_and_Then_Some
!!!_(!!!_album)
!!!_(American_band)
!!!_(Chk_Chk_Chk)
!!!_(album)
!!!_(band)
!!!_(disambiguation)
!!!_discography
!!Destroy-Oh-Boy!!
!!Fuck_you!!
!!Going_Places!!
!!Que_Corra_La_Voz!!
!!_(chess)
!!_(disambiguation)
!'O!Kung
!'O!Kung_language
!'O-!khung_language
!1streadme.txt
!=
!=ME
!=Me
!?
!?!
!?Revolution!?
!?_(Interesting_move)
!?_(chess)
!A_Luchar!
!Action_Pact!
!Action_pact!
!Adios_Amigos!
!Alabadle!
!Alarma!
!Alarma!_(album)
!Alarma!_(disambiguation)
!Alarma!_(magazine)
!Alarma!_Records
!Alarma!_magazine
!Alfaro_Vive,_Carajo!
!All-Time_Quarterback!
!All-Time_Quarterback!_(EP)
!All-Time_Quarterback!_(album)
!Alla_tu!
!Ama
!Amigos!
!Amigos!_(Arrested_Development_episode)
!Arriba!
!Arriba!_La_Pachanga
!Ask_a_Mexican!
!Atame!
!Ay,_Carmela!_(film)
!Ay,_caramba!
!BANG!
!Bang
!Bang!
!Bang!_TV
!Basta_Ya!
!Bastardos!
!Bastardos!_(album)
!Bastardos_en_Vivo!
!Bienvenido,_Mr._Marshall!
!Ciauetistico!
!Ciautistico!
!DOCTYPE
!Dame!_!Dame!_!Dame!
!Decapitacion!
!DelaDap
!Dos!
!Explora!_Science_Center_and_Children's_Museum
!F
!Forward,_Russia!
!Forward_Russia!
!Franchesckaar!
!Ga!ne_language
!Ga!nge_language
!Gã!ne
!Gã!ne_language
!Gã!nge
!Gã!nge_language
!HERO
!Happy_Birthday_Guadaloupe!
!Happy_Birthday_Guadalupe!
!Haunu
!Haunu_(moon)
!Haunu_(satellite)
!Hello_Friends!
!Hero
!Hero_(album)
!Hola!
!Hola,_Mexico!
!Hu_language
!Hukwe_language
!Hãunu
!Hãunu_(satellite)
!K7
!K7_Music
!K7_Records
!Karas_Region
!Kheis_Local_Municipality
!Kheis_Local_Municipality_elections
!Khuai_language
!Khung_language
!Kora
!Kora_Wars
!Kora_language
!Ku_language
!Kung
!Kung-Ekoka
!Kung_Language
!Kung_San
!Kung_San_people
!Kung_language
!Kung_languages
!Kung_mythology
!Kung_people
!Kweiten-ta-Ken
!Kweiten-ta-ǀǀKen
!Kwi
!Kwi_language
!Kwi_languages
!Lander
!Mayday!
!MuchaLucha!
!Mucha_Lucha!
!No_Pasaran!
!No_pasaran!
!O!kung_language
!O!un_language
!O!ung
!O!ung_language
!Oh,_Mi_Diosa!
!Oh_Gloria_Inmarcesible!
!Oid,_Mortales!
!Oka_Tokat
!Ole_Torme!:_Mel_Torme_Goes_South_of_the_Border_with_Billy_May
!Ora_language
!Ora_people
!Oye_Esteban!
!PAUS3
!Policia!_-_A_Tribute_To_The_Police
!Policia!_-_A_Tribute_to_the_Police
!Por_que_no_te_callas!
!Q'Viva!:_The_Chosen
!Que_Clase_de_Amor!
!Que_viva_la_musica!
!Quiero_Vivir!
!Qué_Clase_de_Amor!
!README
!Show_Biz_Grande_Explosion!
!Showbiz_Grande_Explosion!
!Three_Amigos!
!Tierra_y_Libertad!
!Tr'e!
!Tre!
!Ui_languages
!Uno!
!Vamonos_con_Pancho_Villa!
!Vampiros_en_La_Habana!
!Vampiros_en_la_Habana!
!Vanity_is_a_Sin!
!Viva!_Los_Straitjackets
!Viva!_Vaughan
!Viva_La_Cobra!
!Viva_Nueva!
!Viva_Zapata!
!Viva_los_Muertos!
!Vivo_Latino!
!WOWOW!
!Women_Art_Revolution
!Wowow!
!Xam_Khomani_Heartland
!Xo_language
!Xobile
!Xoo
!Xoo_language
!Xoon_language
!Xoong_language
!Xu
!Xu_(god)
!Xu_language
!Xu_mythology
!Xun
!Xun_language
!Xun_people
!Xung_language
!Xóõ
!Xóõ_language
!Xõó
!Xũ
!Xũ_mythology
!Ya_basta!
!_!
!_(CONFIG.SYS_directive)
!_(Cláudia_Pascoal_album)
!_(Donnie_Vie_Album)
!_(Donnie_Vie_album)
!_(IPA)
!_(The_Dismemberment_Plan_album)
!_(The_Song_Formerly_Known_As)
!_(Trippie_Redd_album)
!_(Trippie_Redd_song)
!_(album)
!_(chess)
!_(disambiguation)
!_(math)
!_(mathematics)
!_(song)
!_Qué_Clase_de_Amor_!
!_point
!aaaH-aH_,yawA_eM_ekaT_oT_gnimoC_er'yehT
!aaaH-aH_,yawA_eM_ekaT_ot_gnimoC_er'yehT
!alo,_Presidente!
!earshot
!f
!gau
!important
!kung
!llmind
!mpact
!mpact_Comics
!mpossible
!nara
!ndigo
!ndigoSpirit
!ndigokids
!ndigotech
!readme
!vote
!xoo
!xoo_language
!xun_language
!xóõ_language
!Ô_language
!’O-!khung_language
""!""
""""
```
I get the error:
`
At /var/lib/neo4j/import/enwiki-20240401-all-titles-in-ns0.csv @ position 3588 -  there's a field starting with a quote and whereas it ends that quote there seems to be characters in that field after that ending quote. That isn't supported. This is what I read: '"!'
`

**Comment by JonasHolgersson** [comment]
Hi @spacether , thanks again for reporting! This is maybe just a case of a not so helpful error message. 

What is happening here is that the first and last quotes in `""!""` marks the start and end of a string value and will be dropped then the line is read. This leaves the string `"!"` with just single quotes to be parsed, which is not allowed. 
If you want to have double quote escaping you need to put the double quotes inside the outermost quotes, like this `"""!"""`. 

The [docs example](https://neo4j.com/docs/cypher-manual/current/clauses/load-csv/#_quotes_escaping) perhaps shows this better where the string `"The ""Symbol"""` has single quotes to tell where the string begins and ends, and the double quotes around `Symbol`. I hope that helps! 
Br,
Jonas

edit: Just to clarify, double quote escaping only applies inside a quoted string. 
Here's the subtle difference
`This is not a "quoted" string` <- no need for double quotes
`"This is a ""quoted"" string"` <- double quotes required
`"""Leading and trailing quotes"""` <- looks like a triple quote but is actually one single quote followed by a double
