### ISSUE TITLE
Error: Unrecognized conversion specifier [d] starting at position 36 in conversion pattern.

### ISSUE THREAD

**Issue by jiangxinke** [neo4j/neo4j#13454]
(base) neo4j/neo4j-community-5.19.0/bin$ ./neo4j start
Validating Neo4j configuration: neo4j/neo4j-community-5.19.0/conf/neo4j.conf
No issues found.

Validating user Log4j configuration:neo4j/neo4j-community-5.19.0/conf/user-logs.xml
4 issues found.
Error: Error creating converter for d
Error: Unrecognized conversion specifier [d] starting at position 36 in conversion pattern.
Error: Error creating converter for d
Error: Unrecognized conversion specifier [d] starting at position 36 in conversion pattern.

Validating server Log4j configuration: neo4j/neo4j-community-5.19.0/conf/server-logs.xml
8 issues found.
Warning: Error creating converter for d
Warning: Unrecognized conversion specifier [d] starting at position 35 in conversion pattern.
Warning: Error creating converter for d
Warning: Unrecognized conversion specifier [d] starting at position 35 in conversion pattern.
Warning: Error creating converter for d
Warning: Unrecognized conversion specifier [d] starting at position 35 in conversion pattern.
Warning: Error creating converter for d
Warning: Unrecognized conversion specifier [d] starting at position 35 in conversion pattern.

**Comment by klaren** [comment]
Hello @jiangxinke,

This looks like configuration issue of the log files. Can you share your `user-logs.xml` and `server-logs.xml`?

**Comment by mnd999** [comment]
Closing this issue as we have not heard back in some time. If it's still an issue please reopen and reply with the information requested above.
