### ISSUE TITLE
Vector encoding provider AzureOpenAI is not supported under genai.vector.encode

### ISSUE THREAD

**Issue by pangyyen** [neo4j/neo4j#13459]
Vector encoding provider `AzureOpenAI` is not supported in `genai.vector.encode`. 

Error message encountered:
```
ClientError: {code: Neo.ClientError.Procedure.ProcedureCallFailed} {message: Failed to invoke function `genai.vector.encode`: Caused by: java.lang.RuntimeException: Vector encoding provider not supported: AzureOpenAI}
```
When calling:
```
# Call on VScode where kg is an instance of my Neo4jGraph`
kg.query("""
    MATCH (chunk:Chunk) 
    WHERE chunk.textEmbedding IS NULL
    WITH chunk, genai.vector.encode(
      chunk.text, 
      "AzureOpenAI", 
      {
        token: $openAiApiKey, 
        resources: $resource,
        deployment: $deployment
      } 
    ) AS vector
    CALL db.create.setNodeVectorProperty(chunk, "textEmbedding", vector)

    """, 
    params={"openAiApiKey":OPENAI_API_KEY, "resource":RESOURCE, "deployment":DEPLOYMENT})

# Call on Neo4j Desktop App

    MATCH (chunk:Chunk) 
    WHERE chunk.textEmbedding IS NULL
    WITH chunk, genai.vector.encode(
      chunk.text, 
      "AzureOpenAI", 
      {
        token: xxxxx, 
        resources: xxxxx
        deployment: "embedding"
      } 
    ) AS vector
    CALL db.create.setNodeVectorProperty(chunk, "textEmbedding", vector)
```
  
I have checked the version of my Neo4j and Apoc and met the requirements for both. My database on VScode has been successfully connected and the rest of the queries work as normal, e.g. `MATCH (n) RETURN n` on Desktop App, `print(kg.schema)` on VScode. The initialisation on VScode is done by calling method provided by langchain:
```
from langchain_community.graphs import Neo4jGraph
kg = Neo4jGraph(
    url=NEO4J_URI, username=NEO4J_USERNAME, password=NEO4J_PASSWORD, database=NEO4J_DATABASE
)
```

- Neo4j version: 5.18.1
- Edition: enterprise 
- Operating system: MacOS Sonoma 14.1
- API/Driver: both VSCode and Neo4j desktop App

**Comment by parnmatt** [comment]
Hey @pangyyen that really is odd.
I've just pulled 5.18.1 directly from the source we provide, and installed the GenAI plugin by moving from `products` to `plugins`.

When running the `genai.vector.encode` function with dummy values for `'AzureOpenAI'` (as I currently don't have an Azure deployment running), I am getting parameter validation issues on those dummy values that could only be returned to me if the Azure OpenAI provider was correctly detected. So for me, it seems to be working.

As silly as it sounds could you triple-check check you are sending the request to a cluster member that is running the Neo4j 5.18.1 enterprise binary, and that the version of the GenAI plugin running within those members are also 5.18.1.
The JAR should be `plugins/neo4j-genai-plugin-5.18.1.jar` by default.
Please check all cluster members, just in case the one that is getting the request is running an older binary version.

**Comment by parnmatt** [comment]
Hey @pangyyen we haven't heard back from you in a month. Hopefully, you've found what was wrong in your environment that prevented the plugin from working as expected.
I will close the issue for now; however, if you still have a problem, please reopen this, or create a new one.
Thanks
