### ISSUE TITLE
Allow custom Analyzers for indexing in Neo4j 2+

### ISSUE THREAD

**Issue by ccondit** [neo4j/neo4j#1346]
Neo4j 1.x allowed clients to supply a custom Lucene Analyzer class providing tremendous flexibility for searching Neo4j graphs. As of 2.0.0M6 there's no way to specify such a custom analyzer with the new schema indexes. It would be a great benefit to re-enable this feature.

See also:
http://stackoverflow.com/questions/19455802/custom-analyzer-with-neo4js-automatic-indexing

**Comment by jakewins** [comment]
Closing this as this remains a wontfix, with a pointer to the workaround outlined above. Alternatively, one could run ElasticSearch next to Neo to handle these full text cases.

**Comment by ccondit** [comment]
@jakewins - just out of curiosity is it possible to run both ElasticSearch and Neo4j on the same JVM? Looks like the Lucene dependency would conflict.
