### ISSUE TITLE
Formal request for Neo4j 5.20.0 community edition source code under GPLv3

### ISSUE THREAD

**Issue by jmsuhy** [neo4j/neo4j#13464]
I am requesting access to the source code for the recently released Neo4j Community Edition 5.20.0, which is available for download on your website.

As Neo4j Community Edition is distributed under the GPLv3 license, it is required that the corresponding source code be made available. However, I have not been able to locate the source code in your GitHub repository or on your website.

Could you please provide the source code for this release or direct me to where it can be accessed?

Thank you for your assistance. I look forward to your prompt response.

**Comment by ericsporre** [comment]
Hello!

Thanks for reporting this issue. 
The source code for 5.20.0 is now available, see 5.20.0 tag and 5.20 branch. My apologies for the delay, we had a slight hiccup with the distribution.

**Comment by jmsuhy** [comment]
Thank you.
