### ISSUE TITLE
Getting different result in top nodes with db.index.vector.queryNodes

### ISSUE THREAD

**Issue by kunal-gandhi22** [neo4j/neo4j#13476]
### Setup Environment
- Neo4j version: 1.5.9
- Operating system: Windows10
- API/Driver: (for example Cypher)
- Embedding Model - text-embedding-ada-002

I am trying to retrieve data from neo4j using vector index. I have created embedding using multiple text fields and stored them in the graph with property named - "entity" and created vector index on that graph with COSINE as distance metric. 

On twitter database I have tried finding nearest nodes using - db.index.vector.queryNodes

Query - "RescueDawn"
K = 3 

1. " score - 0.916699171066284
title: 
tagline: 
released: 
born: 
name: Dawn"

2. "score - 0.900816857814788
title: 
tagline: 
released: 
born: 
name: darkdawn"

3. " score- 0.89201283454895
title: 
tagline: 
released: 
born: 
name: D"

K=5
1."score - 0.916699171066284
title: 
tagline: 
released: 
born: 
name: Dawn"

2. "score - 0.900816857814788
title: 
tagline: 
released: 
born: 
name: darkdawn"

3."score - 0.893120050430297
title: 
tagline: 
released: 
born: 
name: Liad Dadash"

4. "score - 0.89201283454895
title: 
tagline: 
released: 
born: 
name: D"

5. "score - 0.891641616821289
title: 
tagline: 
released: 
born: 
name: D"

Check attached file for full result with score. Thing which I want to point out is when we have k=5 3rd node is different from the 3rd node when k=3. k=3 missed node with name: Liad Dadash even though it has high score compare to node with name : D.

### Steps to reproduce
1. Set up twitter data 
2. Create embedding and index using langchain for text node properties - "text,favorites,name,location,screen_name"
3. use cypher query - CALL db.index.vector.queryNodes($index_name,$k, $embedding)

[k3_ans.csv](https://github.com/user-attachments/files/15911780/k3_ans.csv)
[k5_ans.csv](https://github.com/user-attachments/files/15911781/k5_ans.csv)

### Expected behavior
Top nodes should be same. so for k=3 and k=5 first top 3 nodes should be same.

### Actual behavior
Top nodes are different.

**Comment by parnmatt** [comment]
Though I understand that it looks a little off, this is not a bug and is inherent to _approximate_ nearest neighbor searching.

Neo4j uses an HNSW implementation powered by Apache Lucene. HNSW is an approximate nearest neighbor algorithm, mixing skip lists with graph traversal. Most vector indexes and vector databases in the market are approximate.

As it is approximate, some of the _true_ nearest neighbors will not appear in the results, but their relative _order_ is still respective (as it is based off of the `score`). The fraction of true nearest neighbors to those returned is the **recall**, and it is import to note, it is almost never 1.0.

Depending on the navigation of the internal graph structure, slightly different results can be returned; and one of the factors of this is the number of nearest neighbors you've queried for. HNSW keeps track of the nearest neighbor candidates during traversal, too small and we prune off potential paths that could lead to closer results. You can somewhat think of this as a local vs global extrema problem.

The number it keeps track of is often called _ef_ (or more specifically _ef search_), which is slightly different than the number of nearest neighbors (often noted as _k_). Now has to be greater than or equal to _k_. At the time of writing, Lucene uses _k_ for _ef search_; however, there is a PR open that introduces _ef search_ into the library.

Some other vector index providers and vector databases hide this, and specifically query for more than you ask and filter the results down. We _currently_ do not do this and query exactly for what is asked.

To emulate `ef search` you can `queryNodes` with a higher value, and them `LIMIT` the results to the expected size; a scale factor of at least 1.2 is often good enough without being too much more expensive.

You'll note that in most widely used benchmarks they are often querying for `k=100` or more. The smaller the _k_ the less 'accurate' the returned results are to the ground truth. A good rule of thumb is usually to query for around the square root of the total number of vectors, at least as a rough starting point. However, `k=10` for smaller datasets, `k=100` for medium, and `k=1000` for larger is also a good rule of thumb.

If you want **exact** results, then I would suggest not using the index and to use the [vector similarity functions](https://neo4j.com/docs/cypher-manual/current/functions/vector/) and do a pairwise comparison of your query to all vectors.
For small enough data sets, this can actually be faster than the index, and the graph itself can act as a pre-filter limiting the search space considerably before manually comparing.

**Comment by parnmatt** [comment]
Hi @kunal-gandhi22, it's been a little over a month and we've not heard back, as there is nothing really further here, I will close this issue.

As mentioned above, this is not a bug, but an expected outcome in this situation with approximate nearest neighbour searching.
Hopefully it was a sufficient explanation as to why you're seeing what you are seeing.

If you have further questions, feel free to reach out to the Neo4j community website or discord.

**Comment by datasherlock** [comment]
Thank you for the thorough explanation @parnmatt ! Learnt something new today 👍🏼
