### ISSUE TITLE
Execution Error in Neo4j 5.20

### ISSUE THREAD

**Issue by Aurora-yzj** [neo4j/neo4j#13473]
Hi! I discovered that when Neo4j 5.20 executes the following query, it throws an unknown error exception. The detailed queries are listed below. 
**Neo4j Version:** 5.20.0 Community
**Operating System:** Ubuntu 22.04
**API:** Docker

### Steps to reproduce
1. Pull the image: `docker pull neo4j`
2. Create a directory on the host that will be a mount for the data: `mkdir $HOME/neo4j-data`
3. Start a new container that mounts to this directory: `sudo docker run -d --name neo4j-test -p 17474:7474 -p 17687:7687  -v $HOME/neo4j-data:/data neo4j`
4. Go to the web interface at "http://127.0.0.1:17474", login and run the query:
```
MATCH (n:L1) WHERE ((((((((("<")+("j4"))ENDS WITH(("")+("Ta")))OR(reverse("VU,")=~toUpper("%")))XOR(false))AND(n.k1))XOR(n.k1)))OR(n.k1))XOR(n.k1) RETURN n.k1
```
### Expected behavior
It is a legitimate query, so it should output the result normally.

### Actual behavior
Neo4j threw an exception unexpectedly.

![2024-06-12_19-06](https://github.com/neo4j/neo4j/assets/24768784/a9d38ab1-10ae-42cc-b985-8763d798b516)

Thank you so much for the help!

**Comment by pontusmelke** [comment]
@Aurora-yzj Thanks for reporting, we'll investigate!

Regards,
Pontus

**Comment by SachinVasant** [comment]
Hi @Aurora-yzj ,
Thank you for raising this issue. The fix for this should go out in the next version release.
