### ISSUE TITLE
UnknownError about SlotWithKeyAndAliases...

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13475]
I execute a query on my empty neo4j database ,and an error occurs.

Neo4j version: 5.19.0-community
operating system: windows 10
API：Cypher version 9
query: OPTIONAL MATCH (n6) MATCH (n11) WHERE (n6.k31) STARTS WITH n6.k32 MATCH (n14)<-[r9]-(n15),(n17)<-[r11]-(n18) RETURN 1 AS a2 LIMIT 0 UNION ALL RETURN 1 AS a2

error message:
Neo.DatabaseError.General.UnknownError
SlotWithKeyAndAliases(DuplicatedSlotKey(cache[n6.k31],2),RefSlot(2,true,Any),Set()) (of class org.neo4j.cypher.internal.physicalplanning.SlotConfiguration$SlotWithKeyAndAliases)

**Comment by JonasHolgersson** [comment]
Hi @ljhhuxiaoba 
Thanks for reporting! This is fixed in 5.21 which should be out soon.
