### ISSUE TITLE
Could you not change API

### ISSUE THREAD

**Issue by ErykCh** [neo4j/neo4j#13481]
## Feature request template

**Is your feature request related to a problem? Please describe.**
All AI LLM models give me instructions and code that is irrelevent.

For example:
There is no procedure with the name `db.indexes` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.

one of the many. I tried to fight to create code using different LLM models to use your library but this is very very very hard.
Many instructions are wrong.

**Describe the solution you'd like**
Remove from internet all mentions related to your deprecated API if you want to change something.
This will stop learing LLM models wrong (deprecated) examples and such tools as perplexity start to work
properly to find soution how to use your library.

**Describe alternatives you've considered**
You can also go through all current LLM models (GPT-4o, Cloude 3.5) and replace depracted examples with new ones.

**Additional context**
All others tools as Aider, Cursor and probably all copilots (but I haven't checked them yet) give incorrect instructions on how to use your library.

**Comment by mnd999** [comment]
Thanks for taking the time to write this request. We feel it's important to keep documentation for older versions of the product available as these older versions are still in use by many customers. As such, we will not be proceeding with this feature request

**Comment by ErykCh** [comment]
For those who gave a thumbs down.

I would like you to come back to this post as you start programming with AI, using AI software developer tools (two of my favorites are Aider and Replit Agent).

I will then ask for information on how you work, what causes you the biggest problems.

If you come to the same conclusion. That the code currently writes itself, but it does not work and correcting it takes a lot of time and is tiring. Then think about what causes it. Run this code on versions of libraries from two, five years ago and check if it works then - because it is written by AI trained on code examples from so many years ago. And if you come to the same conclusions, then I will ask you to sign this memo.
