### ISSUE TITLE
Missing tag for neo4j 5.21.0

### ISSUE THREAD

**Issue by migruiz4** [neo4j/neo4j#13485]
### Issue description

As the title mentions, the [Neo4j downloads](https://neo4j.com/deployment-center/) page shows version 5.21.0 was released on June 28th, but the Github repository is missing tag '5.21.0' at https://github.com/neo4j/neo4j/tags.

**Comment by jennyowen** [comment]
@migruiz4 thank you for reporting this, the tag should be there now.
