### ISSUE TITLE
Query produces wrong result since 5.19.0

### ISSUE THREAD

**Issue by CelineWuest** [neo4j/neo4j#13491]
I found a discrepancy when running two semantically equivalent queries against an empty database:

---
1:
```cypher
CALL {
	FOREACH ( n1 IN [0] | FOREACH ( n2 IN [] | MERGE () ) CREATE () )
} RETURN 0 AS n3
	UNION
MATCH ()
CREATE ()
RETURN 0 AS n3
```
Creates one node.

---
2:
```cypher
CALL {
	FOREACH (n0 IN [] | MERGE (:A)<-[:B]-() CREATE () )
	FOREACH ( n1 IN [0] | FOREACH ( n2 IN [] | MERGE () ) CREATE () )
} RETURN 0 AS n3
	UNION
MATCH ()
CREATE ()
RETURN 0 AS n3
```
Creates two nodes.

---

I believe the queries mentioned above are semantically equivalent and thus their result should be the same.
The only difference between them is the addition of a `FOREACH` clause, which iterates over an empty list.

I encountered this issue when testing queries against the **Neo4j 5.21 enterprise version** in a Docker container running **alpine v.3**.

Both queries return the same result in the community version, as well as in enterprise versions older than **5.19.0**.

### Steps to reproduce
Run the aforementioned, semantically equivalent, queries against an empty database and observe that their results differ.

### Expected behavior
The queries should result in the same behavior

### Actual behavior
The query results differ

**Comment by henriknyman** [comment]
@DominicWuest Thanks for reporting! I have merged a fix that should be included in the 5.24 release.
