### ISSUE TITLE
Allow Enums in custom procedures

### ISSUE THREAD

**Issue by TomVanWemmel** [neo4j/neo4j#13502]
The Neo4j Type System does not allow Enum types for parameters in custom procedures/functions. 
We can work around this with a String that represents the label, but it would be easier if Neo4j handles the conversion and validation of Enums.

For instance: we use org.neo4j.graphdb.Direction often as parameter to go from start-node to end-node or the other way around

**Comment by parnmatt** [comment]
The procedure framework only deals with converting to and from the Java type system and the `AnyValue` types (our internal type system used by Cypher and the kernel).

Currently the internally used Neo4j type system does not support enums types, so there's nothing to map to and from. There are long running discussions in regards to enum types potentially being added, but so far we cannot give any promises if enums will be added to Cypher or Kernel type systems.

In general we're not looking to expand the procedure framework functionality too much, unless new types are added into the type systems. If we add enums to Cypher, then we may expand the procedure framework to support something that might be able to be mapped to a Java `Enum`.
