### ISSUE TITLE
Can I downgrades the neo4j version from v5.21.2 to v4.4.11 with dump data from v5.21.2?

### ISSUE THREAD

**Issue by togo-hst** [neo4j/neo4j#13500]
**Is your feature request related to a problem? Please describe.**
I want to make a rollback solution that can make sure the data rolling back to `v4.4.11` version if we upgrade failed to `v5.21.2`.
however, I have a tested and it was failed in our test environment.

**at neo4j v5.21.2 VM node**
```shell
# I use neo4j-admin database dump command export the data in neo4j-v5.21.2
neo4j-admin database dump graph.db --to-path=/tmp/test
neo4j-admin database dump system --to-path=/tmp/test
```

**at neo4j v4.4.11 VM node**
```shell
# execute the neo4j-admin load command in the version v4.4.11, but the dump files by v5.21.2 version
neo4j-admin load --from=/tmp/test/system.dump --database=system --force
neo4j-admin load --from=/tmp/test/graph.db.dump --database=graph.db --force
```
![Screenshot 2024-08-02 at 15 29 48](https://github.com/user-attachments/assets/42b26db7-d732-4b51-9593-73e4a0853638)

**Describe the solution you'd like**
I want a solution that can support importing v5.21.2 dump files in v4.4.11, thank a lot!

**Comment by l-heemann** [comment]
Hello, thanks for your feature request!
There are currently no plans to support migrating data from a newer version to an older version.

Please follow the instructions at https://neo4j.com/docs/upgrade-migration-guide/current/version-5/migration/. Among the outlined steps you will create a backup before performing the upgrade. If the upgrade fails you can always restore to those backups.

**Comment by togo-hst** [comment]
Hello @l-heemann , 

Thank you for your quickly support!

Yes, I had done upgraded the `neo4-v4.4.11` to `neo4j-v5.21.2` successfully by the [guide](https://neo4j.com/docs/upgrade-migration-guide/current/version-5/migration/.), in case we will be running the new version a few days in the PROD environment, if our developers demand to downgrades to origin version(neo4-v4.4.11), so that I have no idea at this point. I wander how?

do you have any solution or idea about that? thank you!

**Comment by l-heemann** [comment]
This is not something that is possible with Neo4j 5.x and 4.x. Ideally ask your developers to test 5.x in your testing environment before performing the upgrade in the prod environment.

**Comment by togo-hst** [comment]
Yes, I got it, Thank you @l-heemann , have a good day!
