### ISSUE TITLE
Can Create Properties with hyphens, but not delete

### ISSUE THREAD

**Issue by ThomasThelen** [neo4j/neo4j#13510]
# Report

It's possible to create properties on nodes that have hyphens in the through GDS, but not possible to delete them through CYPHER.

- Neo4j version: Version 1.5.8 (1.5.8.105)
- Operating system: MacOS 14.5 (23F79)
- API/Driver: CYPHER

- **Steps to reproduce**
- Execute a GDS procedure in _write_ mode, creating a property with a hyphen in it
- Attempt to delete or query the property through Neo4J proper, or the python driver

### Expected behavior

- Retrieve or delete the property

### Actual behavior

- Error about a dash in the name

## Example

Here are screenshots of the data, and error

<img width="325" alt="Screenshot 2024-08-21 at 6 57 48 PM" src="https://github.com/user-attachments/assets/016c7262-40b3-48d8-bae7-a809917075ea">

<img width="795" alt="Screenshot 2024-08-21 at 6 45 00 PM" src="https://github.com/user-attachments/assets/81a7adc1-eb69-4f39-96f7-dd2ee4acb1b8">

**Comment by mnd999** [comment]
You need to escape it with backticks. Please see the documentation on [Using special characters in names](https://neo4j.com/docs/cypher-manual/current/syntax/naming/#symbolic-names-escaping-rules). e.g.

```
match (b:Officer) remove b.`n2v-embedding`
```
