### ISSUE TITLE
Where can I find GenAI plugin for neo4j community in version 5.23?

### ISSUE THREAD

**Issue by aerfafeng** [neo4j/neo4j#13518]
Just as I described in the title.
I have found that the GenAI plugin is available in neo4j community 5.23, but I can't find any jar file about it.
I have learned from another issue that plugins can be found in /labs folder (#13422 ), but there is only a plugin for APOC.

**Comment by parnmatt** [comment]
it is in the `products` directory

https://neo4j.com/docs/cypher-manual/current/genai-integrations/#_installation

**Comment by aerfafeng** [comment]
I have searched in my neo4j_home directory and there's no such directory called `products`.
I know this folder is only available in the enterprise version so can't be accessed by the community version.
If the plugin can only be found in the `products` directory, I think it is still unavailable in the community version, which conflicts with the statement in the document.

**Comment by parnmatt** [comment]
Interesting. I have downloaded the tarball `neo4j-community-5.23.0-unix.tar.gz` directly from our distribution server.
I can confirm and see it is located `products/neo4j-genai-plugin-5.23.0.jar`

Just to rule things out, can you double check you are looking in home directory of a Neo4j 5.23 CE installation, and not an earlier version you may already have installed.

Can you also confirm how you sourced the 5.23 CE. Was it via Neo4j Desktop, Deployment Center (deb/zip/tar), a package manage (apt/yum), DockerHub, compiled from source code, or some other means?

**Comment by aerfafeng** [comment]
After I saw the message above, I downloaded the tarball directly and found the `products` folder and the plugin in it, just as the message mentioned.

I was using wsl with Ubuntu v22.04.3(default wsl installation system), and installed neo4j by `apt-get` command. In this case, I hadn't found the `products` folder in `/var/lib/neo4j`.

I can confirm that I have installed the v5.23 of neo4j community because I have tried this two times. The first time I upgraded it from v5.22 and the second time I directly installed it with `apt-get` in another wsl machine that hadn't installed neo4j.

**Comment by aerfafeng** [comment]
Can I directly move the plugin file found in `neo4j-community-5.23.0-unix.tar.gz` to `/var/lib/neo4j/plugins` to use it?

**Comment by parnmatt** [comment]
Thanks @aerfafeng for confirming. I use Ubunutu myself, so I checked the installation via apt and can confirm that the products directory is missing in that location; whereas it does exist in the enterprise version.

Indeed, this seems like an oversight in the packaging process for CE, it's quite possible the DEB and RPM packages are both effected here. I will notify the relevant team.

Until then, yes, manually dropping the JAR into the plugins directory should work, provided the versions match.

**Comment by parnmatt** [comment]
Thanks again for reporting this @aerfafeng, there indeed was something missing in the packaging of the DEB and RPM packages, the former would implicitly be used in the method of your installation.

A fix has been merged a couple days ago, and included in the Neo4j 5.24 release.

---
In summary for future reference

A user wishing to use the GenAI plugin with Neo4j 5.23 Community Edition packaged for DEB and RPM, (and thus also `apt` and `yum`), would have to acquire the JAR from the tarball / zip, and install the plugin as usual.
