### ISSUE TITLE
The version 5.23.0 of Neo4j is not compatible with the version 2.8.0 of GDS.

### ISSUE THREAD

**Issue by chen-xiaochen** [neo4j/neo4j#13513]
![Clip_2024-08-26_15-18-02](https://github.com/user-attachments/assets/2ce6dcd3-316c-4dd2-8966-32a2e4130c7a)

Neo4j version 5.23.0 cannot be used with GDS version 2.8.0, and the corresponding version of GDS cannot be found on the official website.

The specific error message is shown in the figure, how should I deal with this issue?

**Comment by parnmatt** [comment]
Thanks for reaching out. This issue should be raised with GDS: https://github.com/neo4j/graph-data-science
However, I can see that a 2.9.0 tag has been recently created there, and is likely in the release pipeline to be officially released soon.

**Comment by parnmatt** [comment]
Covered by: https://github.com/neo4j/graph-data-science/issues/326
