### ISSUE TITLE
Neo4j Desktop (1.6.0)  not showing the latest neo4j version (5.23)

### ISSUE THREAD

**Issue by ShanteshSindgi** [neo4j/neo4j#13515]
The Neo4j desktop Mac doesn't show the latest version 
<img width="1728" alt="Screenshot 2024-08-27 at 6 33 04 PM" src="https://github.com/user-attachments/assets/596b05c5-3766-486a-87e2-8f3ef2df75ec">

**Comment by mnd999** [comment]
I has a quick check and it seems to be there now, sometimes it takes a little while to filter through. Are you still having issues?

**Comment by ShanteshSindgi** [comment]
Its visible now, Thanks @mnd999
