### ISSUE TITLE
An idea for my PhD work

### ISSUE THREAD

**Issue by Nazar32** [neo4j/neo4j#13528]
I'm starting work on my PhD and I haven't come up with the idea yet. I definitely would love to contribute to the neo4j project, but not sure how and in what areas exactly. I don't want to perform some unneccessary and useless work – I would rather do something helpfull that will make its contribution into neo4j ecosystem.

I would definitely spend some time to investigate some potential topics that could be beneficial for neo4j to implement, but I wonder if there are some topics that your team doesn't have time to implement or that requires some extra research development. Maybe you can give me a hint or some specific topics that I could work on – then I would save my time searching for them.

**Comment by mnd999** [comment]
I would suggest you take a look at https://neo4j.com/research/ and then get in touch via research@neo4j.com
