### ISSUE TITLE
neo4j.com is down

### ISSUE THREAD

**Issue by qin-nz** [neo4j/neo4j#13523]
### Steps to reproduce
Use chrome to open https://neo4j.com

### Actual behavior
![image](https://github.com/user-attachments/assets/d514e19e-50ae-4c29-bae0-70502d1164b9)

This malfunction has been ongoing for at least 4 days.

**Comment by Arrogant-Q** [comment]
I also can not open website,but my roomate can get it.
![Uploading 微信图片_20240918184746.png…]()

**Comment by yanmingcao** [comment]
Looks like access from some region is blocked by the site.

**Comment by qin-nz** [comment]
I can access https://neo4j.com/ now.
