### ISSUE TITLE
Cypher query returns empty set instead expected values

### ISSUE THREAD

**Issue by XylopaZonk42** [neo4j/neo4j#13522]
When running the following Cypher query on a Neo4j database containing a single node, the query returns an empty result set. However, I think the expected behavior is to return a single row with count(1) equal to 0 and c1 equal to 1.

**Neo4j Version:** 5.19.0

### Steps to reproduce

```cypher
CREATE (n)
```

```cypher
MATCH (n)
WITH count(1) AS c1
MATCH (n)
WHERE FALSE
RETURN count(1), c1
```

### Expected behavior

```
+----------+----+
| count(1) | c1 |
+----------+----+
| 0        | 1  |
+----------+----+
```

### Actual behavior

The query returns an empty set.

**Comment by InverseFalcon** [comment]
The behavior and result are actually expected and correct.
This has to do with how aggregations work (when you have 0 rows) per the grouping key (non-aggregation terms) you are using.

https://neo4j.com/developer/kb/understanding-aggregations-on-zero-rows/#_when_non_aggregation_terms_are_present_you_cannot_aggregate_on_0_rows

If you want the counts to be truly independent, and able to work as _you_ expect when one of the matches doesn't match on anything, then you will need to use some technique to isolate your matching. Subqueries, for example, isolate the rows from outside the subquery from being affected by what you do inside, at least until you return from the subquery. That means if you MATCH or filter inside your subquery and rows go to 0, it won't wipe out the data present in the row being executed upon for the subquery call, not unless you return an empty result set. You can aggregate and return its result:

- The easiest way is to use COUNT {} subqueries (introduced in Neo4j 5.3)


```
RETURN COUNT {MATCH (n)} as c1, 
        COUNT {MATCH (n) WHERE FALSE} as c2
```

- If using a version earlier than that, you can use regular CALL {} subqueries, and perform and match and count() inside.

```
CALL {
    MATCH (n)
    RETURN count(n) as c1
}

CALL {
    MATCH (n)
    WHERE FALSE
    RETURN count(n) as c2
}

RETURN c1, c2
```


- You can use OPTIONAL MATCH as a guard on any match that could return 0 rows

```
OPTIONAL MATCH (n)
WITH count(n) AS c1
OPTIONAL MATCH (n)
WHERE FALSE
RETURN c1, count(n) as c2
```

**Comment by XylopaZonk42** [comment]
Thanks for your reply!
