### ISSUE TITLE
Cannot use the unsecured protocols(neo4j, bolt) in web GUI

### ISSUE THREAD

**Issue by d-lavayen** [neo4j/neo4j#13527]
- Neo4j version:  5.23.0
- Operating system:  Docker(https://hub.docker.com/_/neo4j)
-enable http and bolt only(sic!)

I deploy application in Openshift, then I create route to expose https to http(container/backend) traffic, but it only allows me to connect via +s protocols(neo4j+s, bolt+s) in web GUI

If I expose the traffic without edge tls termination it's gonna show me protocols without +s(bolt, neo4j)

**Comment by robsdedude** [comment]
Hi and thanks for reaching out.

I don't fully understand the set-up. Could you please elaborate? Specifically about the exposing of ports. What ports with what protocol does the docker container itself expose? And what exactly does the route you created look like? I.e., what port is forwarded to which and is TLS maybe terminated in that router?

Generally, please note that when you open the web GUI (I assume you mean neo4j browser) via https, you browser enforces all websocket connections to be secure, too. So maybe it already fixes your issue to make sure the browser is also served via an insecure connection (HTTP, not HTTPS). But maybe there's more to it.

**Comment by robsdedude** [comment]
Since I've not heard back in 4 weeks, I'll close the issue. Please feel free to keep commenting if needed.
