### ISSUE TITLE
The official website is not accessible.

### ISSUE THREAD

**Issue by LuckyCurve** [neo4j/neo4j#13533]
## bug report

Visiting the official website https://neo4j.com/ returns a 403 error. I have tried changing the browser and proxy, but the issue persists.

### Expected behavior

The website is returning content normally.

### Actual behavior

403 ERROR
The request could not be satisfied.
Request blocked. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
Generated by cloudfront (CloudFront)
Request ID: U9dPQ2bfg7zEZxrr3rivZzjklTTemz8cyntnPxzq0s2qIXmzM0u_7w==

[neo4j.com.zip](https://github.com/user-attachments/files/17309934/neo4j.com.zip)

**Comment by Winstoncccc** [comment]
So was mine.

**Comment by loveleif** [comment]
Thanks for the report, and sorry for the delay. The website is up when I checked now.

**Comment by XiongGuoQinn** [comment]
It seems to have happened again

**Comment by Appleww** [comment]
Same for me, 403 error and I tried VPN but it didn't work.

**Comment by ieayoio** [comment]
On December 6, 2024, the website is still inaccessible
