### ISSUE TITLE
No compatible "graph-data-science" plugin found for Neo4j 5.24.1 community

### ISSUE THREAD

**Issue by oubeichen** [neo4j/neo4j#13535]
https://github.com/neo4j/graph-data-science/issues/333

**Describe the bug**
The Neo4j Graph Data Science (GDS) plugin is not loading due to incompatibility with Neo4j version 5.24.1 community edition. When attempting to fetch the `versions.json` for the GDS plugin, the following error occurs:

```
Fetching versions.json for Plugin 'graph-data-science' from https://graphdatascience.ninja/versions.json
ERROR: No compatible "graph-data-science" plugin found for Neo4j 5.24.1 community.
    This can happen with the newest Neo4j versions when a compatible plugin has not yet been released.
    You can either use an older version of Neo4j, or continue without graph-data-science.
    Neo4j will continue to start, but "graph-data-science" will not be loaded.
Applying default values for plugin graph-data-science to neo4j.conf

```

**To Reproduce**

Latest docker image with env 
```
NEO4J_PLUGINS: '["graph-data-science", "apoc"]'
```

GDS version: Not applicable (plugin cannot be loaded)
Neo4j version: 5.24.1 community
Operating system: Ubuntu 20.04

- [ ] Graph/dataset to reproduce the bug.  Alternatively describe as much as possible the data, e.g., graph size and other schema/structure details.
- [ ] Create Query 
- [ ] Further queries

**Expected behavior**

The GDS plugin should load and be functional with Neo4j 5.24.1 community, as it is expected to support the latest stable versions of Neo4j.

**Additional context**
The error message suggests that the plugin might not yet be released for the latest Neo4j version, which causes Neo4j to continue running without loading the GDS plugin. This impacts the ability to perform any graph data science-related queries.

**Comment by knutwalker** [comment]
This is fixed on the GDS side: neo4j/graph-data-science#333
