### ISSUE TITLE
springboot neo4j

### ISSUE THREAD

**Issue by lsq888lsq** [neo4j/neo4j#13549]
I annotated a custom class attribute with the @ Relationship annotation in Springboot, which is a list collection. When I use the program to map a node to an entity class, the list collection is empty. When I use the save method provided by the Neo4jRepository interface to save the node, all existing relationships will disappear.

**Comment by michael-simons** [comment]
Please reopen the issue in https://github.com/spring-projects/spring-data-neo4j, together with the versions of Spring Data you are using. This is the repository for the database itself, and we can't help you here.
