### ISSUE TITLE
Incorrect query result on adding predicate (Where clause)

### ISSUE THREAD

**Issue by 1sand0s** [neo4j/neo4j#13540]
# Incorrect query result

I discovered that executing the query described below gives an incorrect result.

Neo4j Version: 5.23.0
Operating System: Ubuntu 20.04
API: Docker
Reproducible on 5.24.2-community  

## Steps to reproduce

1. Pull the image: docker pull neo4j/neo4j:5.23.0-community
2. Download the database compressed dump file `neo4j_dump.tar.gz` attached to this issue into `/home/downloads` directory (for example) and extract it with `tar -xzvf neo4j_dump.tar.gz`
[neo4j_dump.tar.gz](https://github.com/user-attachments/files/17440861/neo4j_dump.tar.gz)

3. Start a new docker container by mounting `/home/downloads` directory:
    `docker run -d --name neo4j-test -p 7474:7474 -v /home/downloads:/data neo4j/neo4j:5.23.0-community`
4. Execute command inside the container to load the dump file into the database:
    `neo4j-admin database load --from-path=/data neo4j`
5. Execute the problematic query:
    `MATCH(n1:startor)<-[e1:maggots]-(n2:grottesco)-[e2:ensnarements]->(n3:renitent)  WHERE n2.mangeiest=106  RETURN  DISTINCT n3.relumining;`

## Expected behavior

2 items -> -96 and 126

## Actual behavior

0 items

## Context:

Here is a snippet of the loaded data on Neo4j browser. I have hidden irrelevant nodes and showing only those of interest to the problematic query.
![image](https://github.com/user-attachments/assets/59cdfc52-784e-4820-93bb-df4d980b2637)

The `startor`, `grottesco` and `renitent` nodes are shown in blue, pink and green respectively.  We clearly see that the pattern given in the `MATCH` clause of the problematic query in Step 5 `(n1:startor)<-[e1:maggots]-(n2:grottesco)-[e2:ensnarements]->(n3:renitent)` exists. The `106` shown for the pink node is the value of its property `mangeiest`. When the predicate `WHERE n2.mangeiest=106` is removed, the query returns the right result but adding this predicate makes the query return an `empty` result. However, we see from the figure that there are 2 nodes of label `renitent ` connected to a `grottesco` node with its mangeiest property equal to 106. So we expect 2 items corresponding to the `relumining` property of these 2 `renitent` nodes to be returned.

**Comment by ikwattro** [comment]
If you hover your properties, you will find out that the type of the mangeiest property is String, thus you need to enclose your filter with quotes.

![Screenshot 2024-10-19 at 14 43 34](https://github.com/user-attachments/assets/73a106d7-1b7c-460d-a9d2-df9f9d7a662b)


```
MATCH (n1:startor)<-[e1:maggots]-(n2:grottesco)-[e2:ensnarements]->(n3:renitent)  
WHERE n2.mangeiest="106"
RETURN  DISTINCT n3.relumining;
```

In the future, please make use of the community forums such as Stackoverflow or the Neo4j discord/community https://community.neo4j.com/ for standard questions/queries.
