### ISSUE TITLE
Neo4j Vector Index search result is impacted by limit k

### ISSUE THREAD

**Issue by ChanningZhang** [neo4j/neo4j#13542]
When I perform a vector query for the text 'Sorceress(Witch)' with different values of k (2, 3, 4, 5, etc.), 'Sorceress' consistently appears as the top result:
`CALL { 
    CALL db.index.vector.queryNodes('unit_vector_idx', 2, [0.03331563249230385, -0.011911444365978241, ......., -0.0001251611829502508]
) YIELD node, score WITH collect({node:node, score:score}) AS nodes, max(score) AS max UNWIND nodes AS n RETURN n.node AS node, (n.score / max) AS score 
} WITH node, max(score) AS score ORDER BY score DESC LIMIT 10 RETURN node.`title` AS text, score, node {.*, `title`: Null, `embedding`: Null, id: Null } AS metadata
`
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/233cd5bc-193e-4125-b7d5-13d6b39f1edc">

However, when I set k to 1, the returned result is different:
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/0b43fca0-85a4-468a-a8b1-17ab3da66be1">

This discrepancy confuses me. Could this be a bug?

- Neo4j version: 5.24.0
- Operating system: MacOS
- API/Driver: Cypher

Embedding provider is OpenAIEmbedding 'text-embedding-3-small'

**Comment by mauvo** [comment]
Hi @ChanningZhang - this is an artefact of how the HNSW approximate nearest neighbor algorithm works. If you only want a single result, but require higher recall accuracy you can try:

1. Fetching more results and discarding the excess.
2. Perform an exhaustive search which ensure 100% accuracy but is slower.
3. Use the HNSW tuning parameters (M and EF_Construction) that let you trade slow index population for more accurate results. https://neo4j.com/docs/cypher-manual/current/indexes/semantic-indexes/vector-indexes/#configuration-settings

Exhaustive search looks like this:
```
  MATCH (n:Unit)
  RETURN n.Title
  ORDER BY vector.similarity.euclidean(n.vector, $query_vector) DESC
  LIMIT 100
```
