### ISSUE TITLE
I keep getting this error even though I have followed the steps in the documentation. Please help! "SSO token was not accepted by neo4j"  

### ISSUE THREAD

**Issue by loneshark99** [neo4j/neo4j#13544]
I installed a Enterprise Edition Neo4j in Azure and I am trying to enable the SSO. I have followed the steps and created the Enterprise App in Azure and set up the roles and claims for authentication. 

When I try to login, it gives the error ""SSO token was not accepted by neo4j".  It goes to login and then I can see the token in the http trace, however it fails after that. Please suggest what could be the issue. **When i check the access_token in the jwt.io, I can see the groups as admin with valid email and other information.** 

**2024-11-01 19:44:44.808+0000 ERROR [<email address here>]: failed to log in: invalid principal or credentials**

OIDC/OAuth# [2024-11-01T20:42:43.549Z] 'log' Credentials assembled with token type "access_token" as password. If connection still does not succeed, make sure 'neo4j.conf' is set up correctly

{
    "token_type": "Bearer",
    "scope": "api://GUID/access-token",
    "expires_in": 3935,
    "ext_expires_in": 3935,
    "access_token": "<Value here>",
    "refresh_token": "<Value here>",
    "id_token": "<Value here>"
}

These are my neo4j.conf settings.

dbms.security.authentication_providers=oidc-azure,native
dbms.security.authorization_providers=oidc-azure,native
dbms.security.oidc.azure.display_name=Azure
dbms.security.oidc.azure.auth_flow=pkce
dbms.security.oidc.azure.well_known_discovery_uri=https://login.microsoftonline.com/<GUID>/v2.0/.well-known/openid-configuration
dbms.security.oidc.azure.config=principal=preferred_username;code_challenge_method=S256;token_type_principal=access_token;token_type_authentication=access_token
dbms.security.oidc.azure.token_endpoint=https://login.microsoftonline.com/<GUID>/oauth2/v2.0/token
dbms.security.oidc.azure.issuer=https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/
dbms.security.oidc.azure.params=client_id=<CLID ID GUID>;response_type=code;scope=openid profile email api://cdffe8df-b5e7-4a56-84a1-41ccaa8d57a1/access-token
dbms.security.oidc.azure.claims.username=preferred_username
dbms.security.oidc.azure.audience=<CLIENT ID GUID>
dbms.security.oidc.azure.authorization.group_to_role_mapping="admin"="admin"
dbms.security.oidc.azure.claims.groups=groups
dbms.security.logs.oidc.jwt_claims_at_debug_level_enabled=true
dbms.logs.security.level=DEBUG

Please suggest some way I can debug.

Thanks.

**Comment by mnd999** [comment]
As SSO is an enterprise only feature, in the first instance I would suggest opening an enterprise support ticket if you are able to do so.

**Comment by loneshark99** [comment]
Thanks @mnd999 . I am using the Evaluation Version of Enterprise to make sure this works for our scenario. Can you please provide some help on this, so that I can confirm that this works as expected?

**Comment by mnd999** [comment]
Okay, you can use `:debug` in browser to get the client side debug logs out, but it seems likely that this part of login is okay. 

On the server side, debug.log (with debug logging turned up) will log some things discovery and from login, also the security log might contain a little more info on why the token is being rejected. Likely the token is missing something required or something the server is expecting does not match. You don't say what version of Neo4j you are using, but the output is better in later 5.x versions than it is in 4.4 for example. One thing that sometimes catches people out is that the server needs connectivity to the IdP. . 

Without a support agreement in place, we can only look at what you are willing to share publicly, which can make assisting with these things more difficult.

**Comment by loneshark99** [comment]
@mnd999 Thanks, this is the token that gets returned. Can you please help check if the neo4j.conf looks correct?  I can see that the token has the group admin and correct name/email.  I have checked that the neo4j can access the IdP.


{
  "_claim_names": {
    "groups": "src1"
  },
  "_claim_sources": {
    "src1": {
      "endpoint": "https://graph.windows.net/GUID/users/6167b76d-7026-4911-ae88-b6c110e0bada/getMemberObjects"
    }
  },
  "aio": "AaQAW/8YAAAAOHyEBjYd2qPfVMuUVG3pKEwYF+WYCBq6qvOLJL9R6530n3w/fFNKlFUMkJkL50qX0T9GTnjzdOQMD3s05a6/nOtmqzILqougF1tMaZAAGgWaf63dyFBdksArUHkqMU7n5qxMy4niIWsQfoeGojkMjWGn6Jfxft45aKG+NBMHQLAT6k9oVLUI+a2KAH2ee0vQv8R+9WNgBJx0o95jcZj6xg==",
  "azp": "cdffe8df-b5e7-4a56-84a1-41ccaa8d57a1",
  "azpacr": "0",
  "name": "Name",
  "oid": "6167b76d-7026-4911-ae88-b6c110e0bada",
  "preferred_username": "a@a.com",
  "rh": "1.ARoAv4j5cvGGr0GRqy180BHbR9_o_83ntVZKhKFBzKqNV6EaAPMaAA.",
  "roles": [
    "admin"
  ],
  "scp": "access-token",
  "sub": "VGkyQbBUJjX8knT28ASYYDjj4_K0gq28--9PykW6GQI",
  "tid": "72f988bf-86f1-41af-91ab-2d7cd011db47",
  "uti": "aFOGIAgco0y0kP-XDPoDAQ",
  "ver": "2.0",
  "wids": [
    "b79fbf4d-3ef9-4689-8143-76b194e85509"
  ]
}


Security.log just shows this  : 2024-11-05 13:26:46.796+0000 ERROR [email]: failed to log in: invalid principal or credentials
Debug.log doesnt have much information, some errors related to SSL because I am using a self signed cert but it works from the browser after accepting the cert exception.



I am using  "Neo4j Kernel" | "5.19.0" | "enterprise" Version.

Thanks for your help.

**Comment by mnd999** [comment]
Do the SSL errors relate to the server attempting to talk to the IdP? That would be a problem because it will not be able to validate the token signature.
The fields in the token we require are `exp`, `iat`, `sub`, `iss` and `aud`.  If the token does not have `iss` then it will just get ignored because there is no way tie it back to a configuration to validate it.

**Comment by loneshark99** [comment]
@mnd999  No its not for ldp.  Yes those 5 attributes are present in the token.


{
  "aud": "cdffe8df-b5e7-4a56-84a1-41ccaa8d57a1",
  "iss": "https://login.microsoftonline.com/GUID/v2.0",
  "iat": 1730812904,
  "nbf": 1730812904,
  "exp": 1730817180,
  "_claim_names": {
    "groups": "src1"
  },
  "_claim_sources": {
    "src1": {
      "endpoint": "https://graph.windows.net/GUID/users/6167b76d-7026-4911-ae88-b6c110e0bada/getMemberObjects"
    }
  },
  "aio": "AaQAW/8YAAAAOHyEBjYd2qPfVMuUVG3pKEwYF+WYCBq6qvOLJL9R6530n3w/fFNKlFUMkJkL50qX0T9GTnjzdOQMD3s05a6/nOtmqzILqougF1tMaZAAGgWaf63dyFBdksArUHkqMU7n5qxMy4niIWsQfoeGojkMjWGn6Jfxft45aKG+NBMHQLAT6k9oVLUI+a2KAH2ee0vQv8R+9WNgBJx0o95jcZj6xg==",
  "azp": "cdffe8df-b5e7-4a56-84a1-41ccaa8d57a1",
  "azpacr": "0",
  "name": "NAME",
  "oid": "6167b76d-7026-4911-ae88-b6c110e0bada",
  "preferred_username": "email",
  "rh": "1.ARoAv4j5cvGGr0GRqy180BHbR9_o_83ntVZKhKFBzKqNV6EaAPMaAA.",
  "roles": [
    "admin"
  ],
  "scp": "access-token",
  "sub": "VGkyQbBUJjX8knT28ASYYDjj4_K0gq28--9PykW6GQI",
  "tid": "72f988bf-86f1-41af-91ab-2d7cd011db47",
  "uti": "aFOGIAgco0y0kP-XDPoDAQ",
  "ver": "2.0",
  "wids": [
    "b79fbf4d-3ef9-4689-8143-76b194e85509"
  ]
}


I feel like my neo4j.config has something wrong interms of the Groups and how  the user gets added to the admin group?  Could that be a possibility.


dbms.security.authentication_providers=oidc-azure,native
dbms.security.authorization_providers=oidc-azure,native
dbms.security.oidc.azure.display_name=Azure
dbms.security.oidc.azure.auth_flow=pkce
dbms.security.oidc.azure.well_known_discovery_uri=https://login.microsoftonline.com//v2.0/.well-known/openid-configuration
dbms.security.oidc.azure.config=principal=preferred_username;code_challenge_method=S256;token_type_principal=access_token;token_type_authentication=access_token
dbms.security.oidc.azure.token_endpoint=https://login.microsoftonline.com//oauth2/v2.0/token
dbms.security.oidc.azure.issuer=https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/
dbms.security.oidc.azure.params=client_id=;response_type=code;scope=openid profile email api://cdffe8df-b5e7-4a56-84a1-41ccaa8d57a1/access-token
dbms.security.oidc.azure.claims.username=preferred_username
**dbms.security.oidc.azure.audience=
dbms.security.oidc.azure.authorization.group_to_role_mapping="admin"="admin"
dbms.security.oidc.azure.claims.groups=groups
dbms.security.logs.oidc.jwt_claims_at_debug_level_enabled=true
dbms.logs.security.level=DEBUG**

**Comment by mnd999** [comment]
Yes, I presume you want `dbms.security.oidc.azure.claims.groups=roles` since you do not have a groups claim in the token (or maybe you do but Entra isn't using it because of a high number of groups). That wouldn't fail login though, you would just not get the right privileges.

You configuration is missing a value for audience, but maybe you are blanking it out. It should match the value in the token. Same for issuer which appears not to match the value in the token. I'm not an expert in Entra, but the issuer in the config looks like it might be from an older API version.

**Comment by loneshark99** [comment]
Thanks a lot @mnd999  for the help you provide. The issue was due to the incorrect issuer and the group setting as you rightly pointed out.  Once I fixed those, it works great.

Have a great day!
