### ISSUE TITLE
Performing QA in Neo4j using NLP [PLEASE HELP]

### ISSUE THREAD

**Issue by jais001** [neo4j/neo4j#13546]
Hi team,

I’m new to Neo4j and have built a dynamic Neo4j database with extensive parent-child relationships. Each node has its own set of properties, and child nodes are connected to their respective parents. I want to implement a question-answering system using NLP to query this knowledge base, similar to a Retrieval-Augmented Generation (RAG) approach.

I’m using Python to interact with Neo4j, and I’m posting this in Issues since I couldn’t find a Discussions page for the repository. Any guidance on integrating NLP for querying and retrieving information based on node properties and relationships would be greatly appreciated.

Thank you!

**Comment by mnd999** [comment]
Hi @jais001, thanks for reaching out. For this type of discussion, you're probably better off in [our community forums](https://community.neo4j.com/) or on our [discord](https://discord.gg/neo4j) and you will likely get a faster response there. Github is more setup for bug reports in the product.
