### ISSUE TITLE
Nodes missing from query results when indexed property is null

### ISSUE THREAD

**Issue by dracoooooo** [neo4j/neo4j#13550]
I have encountered a potential bug in Neo4j where creating an index causes nodes with null or missing properties to be omitted from query results. Below are the details to reproduce the issue:

### Steps to reproduce
```cypher
CREATE (n:N0 {p0:1, p1:1})
CREATE (n:N0 {p0:1})
CREATE INDEX idx_n0_p1 IF NOT EXISTS FOR (n:N0) ON (n.p1)

MATCH (n:N1) WITH collect(n.p0) AS c0
MATCH (n:N0)
WHERE NOT (any(v IN c0 WHERE n.p1 = v))
RETURN *
```
### Expected behavior
The final MATCH query should return two nodes with the label N0 because:
- c0 is an empty list [] (since there are no nodes with label N1).
- The expression `any(v IN c0 WHERE n.p1 = v)` should return false for an empty list.
- Therefore, NOT false evaluates to true, so all N0 nodes should be returned.

### Actual behavior
- With the index `idx_n0_p1` created, the query returns only one node.
- Without the index, the query returns two nodes (as expected).

**Neo4j Version:** 5.19.0
**Operating System:** MacOS 15.1
**API:** Docker

**Comment by LinneaAndersson** [comment]
@dracoooooo Thanks for reporting this and for giving us a good example. I was able to reproduce it, we will have a look at it and get back to you once we have more information.

**Comment by Dunfluff** [comment]
@dracoooooo This has now been fixed and added to the next release. Thank you for informing us.
