### ISSUE TITLE
Parallel runtime creates invalid plan

### ISSUE THREAD

**Issue by CelineWuest** [neo4j/neo4j#13552]
When running the following query:
```cypher
CYPHER runtime = parallel
CALL {
	UNWIND 0 AS n0
	RETURN 0 AS n1
} WITH * ORDER BY 0
RETURN collect(0) AS n2, EXISTS { RETURN 0 AS n3 } AS n4
```

I encountered the following error:
```
Neo4jError: Neo.DatabaseError.General.UnknownError (While marking leveraged order we encountered a plan with no provided order. This is a bug. In the meantime, try running without `runtime=parallel`.
.letSemiApply("n4")
.|.projection("$`  AUTOINT4` AS n3")
.|.argument()
.apply()
.|.argument("n1")
.sort("`  $autoint_2@1` ASC")
.projection("$`  AUTOINT2` AS `  $autoint_2@1`")
.apply()
.|.argument("n1")
.cartesianProduct()
.|.projection("$`  AUTOINT1` AS n1")
.|.apply()
.|.|.argument("n0")
.|.unwind("$`  AUTOINT0` AS n0")
.|.argument()
.argument()
.build())
```

I believe the query mentioned above is semantically and syntactically correct and thus no error should be thrown here.

This error seems to have been introduced in **fa9d0eb**.

I encountered this issue when testing queries against the **Neo4j 5.25.1 enterprise version** in a Docker container running **alpine v.3**.

### Steps to reproduce
Run the following query and observe it throws an error:
```cypher
CYPHER runtime = parallel CALL { UNWIND 0 AS n0 RETURN 0 AS n1 } WITH * ORDER BY 0 RETURN collect(0) AS n2, EXISTS { RETURN 0 AS n3 } AS n4
```

### Expected behavior
The query should run successfully

### Actual behavior
The query fails with the error message `Neo4jError: Neo.DatabaseError.General.UnknownError (While marking leveraged order we encountered a plan with no provided order. This is a bug. In the meantime, try running without `runtime=parallel`.
.letSemiApply("n4")
.|.projection("$`  AUTOINT4` AS n3")
.|.argument()
.apply()
.|.argument("n1")
.sort("`  $autoint_2@1` ASC")
.projection("$`  AUTOINT2` AS `  $autoint_2@1`")
.apply()
.|.argument("n1")
.cartesianProduct()
.|.projection("$`  AUTOINT1` AS n1")
.|.apply()
.|.|.argument("n0")
.|.unwind("$`  AUTOINT0` AS n0")
.|.argument()
.argument()
.build())`

**Comment by hvub** [comment]
Hi Celine,

thanks for reporting this. It is noted.

The error message suggest an immediate workaround — "try running without `runtime=parallel`". Your example works without parallel runtime. 

Additionally, I like to point out that the `WITH * ORDER BY 0` is semantically pointless. Without it

```
CYPHER runtime = parallel
CALL {
	UNWIND 0 AS n0
	RETURN 0 AS n1
}
RETURN collect(0) AS n2, EXISTS { RETURN 0 AS n3 } AS n4
```

the query also works in parallel runtime.

Note that `CALL { ... }` does not need to be followed by a `WITH`.

So, that gives you another workaround.

**Comment by CelineWuest** [comment]
Hi Hannes,

Thanks for your quick response!
The query was found using a fuzzer and was reduced heavily from a much larger query, which is why the semantically pointless clauses showed up :)

**Comment by SachinVasant** [comment]
Hi Celine,
Thanks for reporting this. I have now merged a fix for this that should make it to an upcoming version.

Thanks and regards,
Sachin Vasant
