### ISSUE TITLE
not able to invoke keyword based search please resolve

### ISSUE THREAD

**Issue by Akshaybhure111** [neo4j/neo4j#13553]
# Step 1: Retrieve entities from the entity chain
# print("Invoking entity chain to extract entities...")
entities = entity_chain.invoke({"question": question})
print(f"Extracted entities: {entities.names}")

# Step 2: Iterate through entities and query the graph
for entity1 in entities.names:
    # print(f"\nProcessing entity: {entity}")

    # Generate the full-text query for the current entity
    full_text_query = generate_full_text_query(entity1)
    print(f"Generated full text query for entity '{entity1}': {full_text_query}")

    # Query the graph
    print(f"Querying the graph for entity '{entity1}'...")
    response = graph.query(
        """CALL db.index.fulltext.queryNodes('entity_index', $query, {limit:2})
        YIELD node,score
        CALL {
          WITH node
          MATCH (node)-[r:!MENTIONS]->(neighbor)
          RETURN node.id + ' - ' + type(r) + ' -> ' + neighbor.id AS output
          UNION ALL
          WITH node
          MATCH (node)<-[r:!MENTIONS]-(neighbor)
          RETURN neighbor.id + ' - ' + type(r) + ' -> ' + node.id AS output
        }
        RETURN output LIMIT 50
        """,
        {"query": full_text_query},
    )
    print(f"Graph query response for entity '{entity1}': {response}")

    # Append the outputs from the query to the result
    outputs = [el['output'] for el in response]
    # print(f"Outputs for entity '{entity}': {outputs}")
    result += "\n".join(outputs)

# Final result
print(f"\nFinal result:\n{result}")
return result
please check in above code I am successfully taking response from similarity search but when trying to get output from keysearch that time its not able to give answer
but when I am running below query then it is able to giving answer please sujjest
graph.query(
"CREATE FULLTEXT INDEX entity_index IF NOT EXISTS FOR (n:__Entity__) ON EACH [n.id, n.text]"

**Comment by Dunfluff** [comment]
Hi @Akshaybhure111 
I would try contacting support about this question if you are a paying customer, otherwise you can ask for help on the community forums: https://community.neo4j.com/.
