### ISSUE TITLE
Test failures for 5.20 with java 21.0.5 on MacOS

### ISSUE THREAD

**Issue by michaelwechner** [neo4j/neo4j#13562]
Hi Receive the following test failures for 5.20 with java 21.0.5 on MacOS.

Should I use another branch or another JDK?

[ERROR] Tests run: 32, Failures: 2, Errors: 0, Skipped: 6
[INFO] 
[INFO] 
[INFO] --- failsafe:3.2.5:verify (verify) @ neo4j ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Neo4j - Parent 5.20.0-SNAPSHOT:
[INFO] 
[INFO] Neo4j - Parent ..................................... SUCCESS [  0.740 s]
[INFO] Neo4j - Annotation processors ...................... SUCCESS [  3.978 s]
[INFO] Neo4j - Arrow Bill of Materials .................... SUCCESS [  0.098 s]
[INFO] Zstandard .......................................... SUCCESS [  0.056 s]
[INFO] Neo4j - Common ..................................... SUCCESS [  6.104 s]
[INFO] Neo4j - Unsafe Access .............................. SUCCESS [  1.631 s]
[INFO] Neo4j - Native ..................................... SUCCESS [  0.946 s]
[INFO] Neo4j - Concurrent ................................. SUCCESS [  4.173 s]
[INFO] Neo4j - IO ......................................... SUCCESS [  6.286 s]
[INFO] Neo4j - Token API .................................. SUCCESS [  2.070 s]
[INFO] Neo4j - Resource interface ......................... SUCCESS [  0.185 s]
[INFO] Neo4j - Collections ................................ SUCCESS [ 40.994 s]
[INFO] Neo4j - Graph Database API ......................... SUCCESS [  2.213 s]
[INFO] Neo4j - Exceptions ................................. SUCCESS [  1.275 s]
[INFO] Neo4j - Testing Utils Parent ....................... SUCCESS [  0.014 s]
[INFO] Neo4j - Test utilities ............................. SUCCESS [  6.340 s]
[INFO] Neo4j - Value ...................................... SUCCESS [  5.417 s]
[INFO] Neo4j - Random Value Test Utils .................... SUCCESS [  3.862 s]
[INFO] Neo4j - Test IO utilities .......................... SUCCESS [  5.784 s]
[INFO] Neo4j - Logging .................................... SUCCESS [  6.743 s]
[INFO] Neo4j - Test logging utilities ..................... SUCCESS [  0.279 s]
[INFO] Neo4j - Configuration .............................. SUCCESS [  5.862 s]
[INFO] Neo4j - Locking .................................... SUCCESS [ 24.219 s]
[INFO] Neo4j - Schema ..................................... SUCCESS [  2.831 s]
[INFO] Neo4j - Procedure API .............................. SUCCESS [  0.213 s]
[INFO] Neo4j - Layout ..................................... SUCCESS [  0.235 s]
[INFO] Neo4j - Monitoring ................................. SUCCESS [  1.861 s]
[INFO] Neo4j - Diagnostics ................................ SUCCESS [  0.198 s]
[INFO] Neo4j - Native index ............................... SUCCESS [  0.899 s]
[INFO] Neo4j - gbptree-tests .............................. SUCCESS [01:03 min]
[INFO] Neo4j - ID Generator ............................... SUCCESS [ 35.047 s]
[INFO] Neo4j - Kernel API ................................. SUCCESS [  5.872 s]
[INFO] Neo4j - CSV reading and parsing .................... SUCCESS [  5.459 s]
[INFO] Neo4j - Storage Engine Implementation utilities .... SUCCESS [ 10.383 s]
[INFO] Neo4j - Import Utilities ........................... SUCCESS [ 42.124 s]
[INFO] Neo4j - Storage Engine Test Utilities .............. SUCCESS [  0.297 s]
[INFO] Neo4j - Write-Ahead Log ............................ SUCCESS [  0.409 s]
[INFO] Neo4j - Write-Ahead Logging Test Utilities ......... SUCCESS [  0.577 s]
[INFO] Neo4j - Test Batch Import utilities ................ SUCCESS [  0.280 s]
[INFO] Neo4j - Database Layout API utilities .............. SUCCESS [  1.620 s]
[INFO] Neo4j - Test kernel API utilities .................. SUCCESS [  0.252 s]
[INFO] Neo4j - Native Spatial Index ....................... SUCCESS [ 22.999 s]
[INFO] Neo4j - Lucene Index ............................... SUCCESS [ 29.784 s]
[INFO] Neo4j - Fulltext index ............................. SUCCESS [  1.834 s]
[INFO] Neo4j - Cloud ...................................... SUCCESS [  3.222 s]
[INFO] Neo4j - Graph Database Kernel ...................... SUCCESS [  4.316 s]
[INFO] Neo4j - Graph Database Kernel Test Utils ........... SUCCESS [  3.242 s]
[INFO] Neo4j - Record storage engine ...................... SUCCESS [01:15 min]
[INFO] Neo4j - Command Line ............................... SUCCESS [  1.492 s]
[INFO] Neo4j - Database Management System ................. SUCCESS [ 16.585 s]
[INFO] Neo4j - Community Cypher Build ..................... SUCCESS [  0.169 s]
[INFO] openCypher Front End Parent ........................ SUCCESS [  0.039 s]
[INFO] openCypher Test Utils .............................. SUCCESS [  7.534 s]
[INFO] openCypher Utils ................................... SUCCESS [ 17.172 s]
[INFO] Neo4j - Cypher Configuration ....................... SUCCESS [  8.983 s]
[INFO] Neo4j - Code Generator ............................. SUCCESS [ 23.151 s]
[INFO] openCypher Expressions ............................. SUCCESS [ 13.183 s]
[INFO] openCypher AST for the Cypher Query Language ....... SUCCESS [ 26.864 s]
[INFO] Neo4j - GQL status ................................. SUCCESS [  0.809 s]
[INFO] Neo4j - Notifications .............................. SUCCESS [  5.388 s]
[INFO] Neo4j - Cypher AST factory ......................... SUCCESS [  0.215 s]
[INFO] Neo4j - Cypher JavaCC based parser ................. SUCCESS [  1.373 s]
[INFO] Neo4j - Cypher ANTLR4 based parser ................. SUCCESS [  0.399 s]
[INFO] Neo4j - Cypher ANTLR4 parser listener .............. SUCCESS [  0.099 s]
[INFO] Neo4j - Cypher Macros .............................. SUCCESS [  4.947 s]
[INFO] Neo4j - Neo4j CST factory .......................... SUCCESS [ 10.265 s]
[INFO] Neo4j - Neo4j/OpenCypher AST factory ............... SUCCESS [08:26 min]
[INFO] openCypher Rewriting ............................... SUCCESS [ 19.029 s]
[INFO] Neo4j - Cypher AST generator ....................... SUCCESS [  8.974 s]
[INFO] openCypher Front End ............................... SUCCESS [ 43.842 s]
[INFO] Neo4j - Cypher Intermediate Representation ......... SUCCESS [ 15.453 s]
[INFO] Neo4j - Cypher Logical Plans ....................... SUCCESS [01:04 min]
[INFO] Neo4j - Cypher Logical Plan Builder ................ SUCCESS [ 41.448 s]
[INFO] Neo4j - Cypher Planner SPI ......................... SUCCESS [  6.436 s]
[INFO] Neo4j - Cypher Runtime Utilities ................... SUCCESS [ 19.620 s]
[INFO] Neo4j - Graph Algorithms ........................... SUCCESS [  2.271 s]
[INFO] Neo4j - Cypher Interpreted Runtime ................. SUCCESS [ 50.127 s]
[INFO] Neo4j - Cypher Expression Evaluator ................ SUCCESS [  6.412 s]
[INFO] Neo4j - Cypher Cache ............................... SUCCESS [  6.744 s]
[INFO] Neo4j - Cypher Rendering ........................... SUCCESS [  1.656 s]
[INFO] Neo4j - Cypher Graph Counts ........................ SUCCESS [  6.107 s]
[INFO] Neo4j - Cypher Planner ............................. SUCCESS [02:37 min]
[INFO] Neo4j - Cypher Physical Planning ................... SUCCESS [ 18.440 s]
[INFO] Neo4j - Cypher Slotted Runtime ..................... SUCCESS [ 25.988 s]
[INFO] Neo4j - Cypher ..................................... SUCCESS [ 49.506 s]
[INFO] Neo4j - SSL ........................................ SUCCESS [  5.614 s]
[INFO] Neo4j - Server API ................................. SUCCESS [  1.493 s]
[INFO] Neo4j - Security ................................... SUCCESS [  7.573 s]
[INFO] Neo4j - Bolt Protocol Version 1 .................... SUCCESS [ 22.453 s]
[INFO] Neo4j - Fabric Parent .............................. SUCCESS [  0.027 s]
[INFO] Neo4j - Fabric ..................................... SUCCESS [ 22.161 s]
[INFO] Neo4j - Query Router ............................... SUCCESS [  6.069 s]
[INFO] Neo4j - Capabilities ............................... SUCCESS [  2.385 s]
[INFO] Neo4j - Community Procedures ....................... SUCCESS [ 10.305 s]
[INFO] Neo4j - Data Collector ............................. SUCCESS [  5.802 s]
[INFO] Neo4j - Consistency Checker ........................ SUCCESS [  1.378 s]
[INFO] Neo4j - Import Command Line Tool ................... SUCCESS [ 11.363 s]
[INFO] Neo4j - Server ..................................... SUCCESS [ 11.074 s]
[INFO] Neo4j - SLF4J Provider ............................. SUCCESS [  2.050 s]
[INFO] Neo4j - User data collector ........................ SUCCESS [  0.316 s]
[INFO] Neo4j - Community .................................. FAILURE [03:09 min]
[INFO] Neo4j - Procedure Compiler Core .................... SKIPPED
[INFO] Neo4j - Community Integration Tests ................ SKIPPED
[INFO] Neo4j - Community Integration Test Support ......... SKIPPED
[INFO] neo4j-server-test-utils ............................ SKIPPED
[INFO] Neo4j - Test Harness ............................... SKIPPED
[INFO] Neo4j - Procedure Compiler Parent POM .............. SKIPPED
[INFO] Neo4j - Procedure Compiler Integration Tests ....... SKIPPED
[INFO] Neo4j - Graph Database Kernel Test ................. SKIPPED
[INFO] Neo4j - Community (Bill of Materials) .............. SKIPPED
[INFO] Neo4j - Record Storage Engine Integration Tests .... SKIPPED
[INFO] Neo4j - Community Kernel Integration Tests ......... SKIPPED
[INFO] Neo4j - Community Index Integration Tests .......... SKIPPED
[INFO] Neo4j - Community Import Integration Tests ......... SKIPPED
[INFO] Neo4j - Community DBMS Integration Tests ........... SKIPPED
[INFO] Neo4j - Community Graph Algorithms Integration Tests SKIPPED
[INFO] Neo4j - Community Bolt Integration Tests ........... SKIPPED
[INFO] Neo4j - Community Generic Integration Tests ........ SKIPPED
[INFO] Neo4j - Community Fabric Integration Tests ......... SKIPPED
[INFO] Neo4j - Community Security Integration Tests ....... SKIPPED
[INFO] Neo4j - Integration Tests without deep reflection into JDK internals SKIPPED
[INFO] Neo4j - SLF4J Provider Integration Tests ........... SKIPPED
[INFO] Neo4j - Cypher Testing ............................. SKIPPED
[INFO] Neo4j - Community Cypher Integration Tests ......... SKIPPED
[INFO] Neo4j - Test proxy ................................. SKIPPED
[INFO] Neo4j - Push To Cloud - Admin command .............. SKIPPED
[INFO] Neo4j - Boot ....................................... SKIPPED
[INFO] Neo4j - Cypher ANTLR4 parser plugin ................ SKIPPED
[INFO] Neo4j - Cypher Specification Suite Tools ........... SKIPPED
[INFO] Neo4j - Cypher Compatibility Specification Suite ... SKIPPED
[INFO] Neo4j - Cypher Logical Plan Generator .............. SKIPPED
[INFO] Neo4j - Cypher Runtime Acceptance .................. SKIPPED
[INFO] Neo4j - Cypher Literal Interpreter ................. SKIPPED
[INFO] Neo4j - Cypher Shell Parent ........................ SKIPPED
[INFO] Neo4j - Cypher Shell ............................... SKIPPED
[INFO] Neo4j - Cypher Shell Integration Test .............. SKIPPED
[INFO] Neo4j - Cypher Shell Integration Test 2 ............ SKIPPED
[INFO] Neo4j - Community Build ............................ SKIPPED
[INFO] Neo4j - Server Assembler ........................... SKIPPED
[INFO] Neo4j - Community Server Assembler ................. SKIPPED
[INFO] Neo4j - Packaging Build ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  32:12 min
[INFO] Finished at: 2024-12-12T11:30:56+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:3.2.5:verify (verify) on project neo4j: There are test failures.

**Comment by michaelwechner** [comment]
I just built with java 17.0.12 2024-07-16 LTS and receive the same test failures

[ERROR] Tests run: 32, Failures: 2, Errors: 0, Skipped: 6
[INFO] 
[INFO] 
[INFO] --- failsafe:3.2.5:verify (verify) @ neo4j ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Neo4j - Parent 5.20.0-SNAPSHOT:
[INFO] 
[INFO] Neo4j - Parent ..................................... SUCCESS [  0.968 s]
[INFO] Neo4j - Annotation processors ...................... SUCCESS [  3.968 s]
[INFO] Neo4j - Arrow Bill of Materials .................... SUCCESS [  0.106 s]
[INFO] Zstandard .......................................... SUCCESS [  0.063 s]
[INFO] Neo4j - Common ..................................... SUCCESS [  7.145 s]
[INFO] Neo4j - Unsafe Access .............................. SUCCESS [  1.664 s]
[INFO] Neo4j - Native ..................................... SUCCESS [  0.903 s]
[INFO] Neo4j - Concurrent ................................. SUCCESS [  4.562 s]
[INFO] Neo4j - IO ......................................... SUCCESS [  5.927 s]
[INFO] Neo4j - Token API .................................. SUCCESS [  2.112 s]
[INFO] Neo4j - Resource interface ......................... SUCCESS [  0.228 s]
[INFO] Neo4j - Collections ................................ SUCCESS [ 38.269 s]
[INFO] Neo4j - Graph Database API ......................... SUCCESS [  2.183 s]
[INFO] Neo4j - Exceptions ................................. SUCCESS [  1.336 s]
[INFO] Neo4j - Testing Utils Parent ....................... SUCCESS [  0.012 s]
[INFO] Neo4j - Test utilities ............................. SUCCESS [  6.338 s]
[INFO] Neo4j - Value ...................................... SUCCESS [  5.092 s]
[INFO] Neo4j - Random Value Test Utils .................... SUCCESS [  3.600 s]
[INFO] Neo4j - Test IO utilities .......................... SUCCESS [  5.440 s]
[INFO] Neo4j - Logging .................................... SUCCESS [  7.225 s]
[INFO] Neo4j - Test logging utilities ..................... SUCCESS [  0.317 s]
[INFO] Neo4j - Configuration .............................. SUCCESS [  6.255 s]
[INFO] Neo4j - Locking .................................... SUCCESS [ 25.358 s]
[INFO] Neo4j - Schema ..................................... SUCCESS [  2.539 s]
[INFO] Neo4j - Procedure API .............................. SUCCESS [  0.236 s]
[INFO] Neo4j - Layout ..................................... SUCCESS [  0.278 s]
[INFO] Neo4j - Monitoring ................................. SUCCESS [  1.891 s]
[INFO] Neo4j - Diagnostics ................................ SUCCESS [  0.225 s]
[INFO] Neo4j - Native index ............................... SUCCESS [  1.086 s]
[INFO] Neo4j - gbptree-tests .............................. SUCCESS [ 54.268 s]
[INFO] Neo4j - ID Generator ............................... SUCCESS [ 35.329 s]
[INFO] Neo4j - Kernel API ................................. SUCCESS [  5.908 s]
[INFO] Neo4j - CSV reading and parsing .................... SUCCESS [  5.365 s]
[INFO] Neo4j - Storage Engine Implementation utilities .... SUCCESS [ 10.162 s]
[INFO] Neo4j - Import Utilities ........................... SUCCESS [ 41.272 s]
[INFO] Neo4j - Storage Engine Test Utilities .............. SUCCESS [  0.245 s]
[INFO] Neo4j - Write-Ahead Log ............................ SUCCESS [  0.368 s]
[INFO] Neo4j - Write-Ahead Logging Test Utilities ......... SUCCESS [  0.396 s]
[INFO] Neo4j - Test Batch Import utilities ................ SUCCESS [  0.289 s]
[INFO] Neo4j - Database Layout API utilities .............. SUCCESS [  1.519 s]
[INFO] Neo4j - Test kernel API utilities .................. SUCCESS [  0.288 s]
[INFO] Neo4j - Native Spatial Index ....................... SUCCESS [ 20.399 s]
[INFO] Neo4j - Lucene Index ............................... SUCCESS [ 26.665 s]
[INFO] Neo4j - Fulltext index ............................. SUCCESS [  1.879 s]
[INFO] Neo4j - Cloud ...................................... SUCCESS [  3.567 s]
[INFO] Neo4j - Graph Database Kernel ...................... SUCCESS [  4.482 s]
[INFO] Neo4j - Graph Database Kernel Test Utils ........... SUCCESS [  3.343 s]
[INFO] Neo4j - Record storage engine ...................... SUCCESS [01:17 min]
[INFO] Neo4j - Command Line ............................... SUCCESS [  1.288 s]
[INFO] Neo4j - Database Management System ................. SUCCESS [ 15.619 s]
[INFO] Neo4j - Community Cypher Build ..................... SUCCESS [  0.162 s]
[INFO] openCypher Front End Parent ........................ SUCCESS [  0.017 s]
[INFO] openCypher Test Utils .............................. SUCCESS [  7.894 s]
[INFO] openCypher Utils ................................... SUCCESS [ 17.062 s]
[INFO] Neo4j - Cypher Configuration ....................... SUCCESS [  9.110 s]
[INFO] Neo4j - Code Generator ............................. SUCCESS [ 22.315 s]
[INFO] openCypher Expressions ............................. SUCCESS [ 13.109 s]
[INFO] openCypher AST for the Cypher Query Language ....... SUCCESS [ 27.590 s]
[INFO] Neo4j - GQL status ................................. SUCCESS [  0.805 s]
[INFO] Neo4j - Notifications .............................. SUCCESS [  5.263 s]
[INFO] Neo4j - Cypher AST factory ......................... SUCCESS [  0.085 s]
[INFO] Neo4j - Cypher JavaCC based parser ................. SUCCESS [  1.271 s]
[INFO] Neo4j - Cypher ANTLR4 based parser ................. SUCCESS [  0.359 s]
[INFO] Neo4j - Cypher ANTLR4 parser listener .............. SUCCESS [  0.079 s]
[INFO] Neo4j - Cypher Macros .............................. SUCCESS [  4.691 s]
[INFO] Neo4j - Neo4j CST factory .......................... SUCCESS [  9.897 s]
[INFO] Neo4j - Neo4j/OpenCypher AST factory ............... SUCCESS [07:58 min]
[INFO] openCypher Rewriting ............................... SUCCESS [ 18.785 s]
[INFO] Neo4j - Cypher AST generator ....................... SUCCESS [  8.696 s]
[INFO] openCypher Front End ............................... SUCCESS [ 41.051 s]
[INFO] Neo4j - Cypher Intermediate Representation ......... SUCCESS [ 15.517 s]
[INFO] Neo4j - Cypher Logical Plans ....................... SUCCESS [01:05 min]
[INFO] Neo4j - Cypher Logical Plan Builder ................ SUCCESS [ 44.635 s]
[INFO] Neo4j - Cypher Planner SPI ......................... SUCCESS [  6.477 s]
[INFO] Neo4j - Cypher Runtime Utilities ................... SUCCESS [ 20.231 s]
[INFO] Neo4j - Graph Algorithms ........................... SUCCESS [  2.309 s]
[INFO] Neo4j - Cypher Interpreted Runtime ................. SUCCESS [ 55.629 s]
[INFO] Neo4j - Cypher Expression Evaluator ................ SUCCESS [  6.600 s]
[INFO] Neo4j - Cypher Cache ............................... SUCCESS [  6.549 s]
[INFO] Neo4j - Cypher Rendering ........................... SUCCESS [  1.632 s]
[INFO] Neo4j - Cypher Graph Counts ........................ SUCCESS [  6.368 s]
[INFO] Neo4j - Cypher Planner ............................. SUCCESS [02:43 min]
[INFO] Neo4j - Cypher Physical Planning ................... SUCCESS [ 17.352 s]
[INFO] Neo4j - Cypher Slotted Runtime ..................... SUCCESS [ 24.438 s]
[INFO] Neo4j - Cypher ..................................... SUCCESS [ 46.952 s]
[INFO] Neo4j - SSL ........................................ SUCCESS [  6.235 s]
[INFO] Neo4j - Server API ................................. SUCCESS [  1.611 s]
[INFO] Neo4j - Security ................................... SUCCESS [  7.044 s]
[INFO] Neo4j - Bolt Protocol Version 1 .................... SUCCESS [ 22.156 s]
[INFO] Neo4j - Fabric Parent .............................. SUCCESS [  0.039 s]
[INFO] Neo4j - Fabric ..................................... SUCCESS [ 20.449 s]
[INFO] Neo4j - Query Router ............................... SUCCESS [  5.731 s]
[INFO] Neo4j - Capabilities ............................... SUCCESS [  2.314 s]
[INFO] Neo4j - Community Procedures ....................... SUCCESS [  9.198 s]
[INFO] Neo4j - Data Collector ............................. SUCCESS [  5.715 s]
[INFO] Neo4j - Consistency Checker ........................ SUCCESS [  1.591 s]
[INFO] Neo4j - Import Command Line Tool ................... SUCCESS [ 10.445 s]
[INFO] Neo4j - Server ..................................... SUCCESS [ 10.273 s]
[INFO] Neo4j - SLF4J Provider ............................. SUCCESS [  1.891 s]
[INFO] Neo4j - User data collector ........................ SUCCESS [  0.382 s]
[INFO] Neo4j - Community .................................. FAILURE [02:47 min]
[INFO] Neo4j - Procedure Compiler Core .................... SKIPPED
[INFO] Neo4j - Community Integration Tests ................ SKIPPED
[INFO] Neo4j - Community Integration Test Support ......... SKIPPED
[INFO] neo4j-server-test-utils ............................ SKIPPED
[INFO] Neo4j - Test Harness ............................... SKIPPED
[INFO] Neo4j - Procedure Compiler Parent POM .............. SKIPPED
[INFO] Neo4j - Procedure Compiler Integration Tests ....... SKIPPED
[INFO] Neo4j - Graph Database Kernel Test ................. SKIPPED
[INFO] Neo4j - Community (Bill of Materials) .............. SKIPPED
[INFO] Neo4j - Record Storage Engine Integration Tests .... SKIPPED
[INFO] Neo4j - Community Kernel Integration Tests ......... SKIPPED
[INFO] Neo4j - Community Index Integration Tests .......... SKIPPED
[INFO] Neo4j - Community Import Integration Tests ......... SKIPPED
[INFO] Neo4j - Community DBMS Integration Tests ........... SKIPPED
[INFO] Neo4j - Community Graph Algorithms Integration Tests SKIPPED
[INFO] Neo4j - Community Bolt Integration Tests ........... SKIPPED
[INFO] Neo4j - Community Generic Integration Tests ........ SKIPPED
[INFO] Neo4j - Community Fabric Integration Tests ......... SKIPPED
[INFO] Neo4j - Community Security Integration Tests ....... SKIPPED
[INFO] Neo4j - Integration Tests without deep reflection into JDK internals SKIPPED
[INFO] Neo4j - SLF4J Provider Integration Tests ........... SKIPPED
[INFO] Neo4j - Cypher Testing ............................. SKIPPED
[INFO] Neo4j - Community Cypher Integration Tests ......... SKIPPED
[INFO] Neo4j - Test proxy ................................. SKIPPED
[INFO] Neo4j - Push To Cloud - Admin command .............. SKIPPED
[INFO] Neo4j - Boot ....................................... SKIPPED
[INFO] Neo4j - Cypher ANTLR4 parser plugin ................ SKIPPED
[INFO] Neo4j - Cypher Specification Suite Tools ........... SKIPPED
[INFO] Neo4j - Cypher Compatibility Specification Suite ... SKIPPED
[INFO] Neo4j - Cypher Logical Plan Generator .............. SKIPPED
[INFO] Neo4j - Cypher Runtime Acceptance .................. SKIPPED
[INFO] Neo4j - Cypher Literal Interpreter ................. SKIPPED
[INFO] Neo4j - Cypher Shell Parent ........................ SKIPPED
[INFO] Neo4j - Cypher Shell ............................... SKIPPED
[INFO] Neo4j - Cypher Shell Integration Test .............. SKIPPED
[INFO] Neo4j - Cypher Shell Integration Test 2 ............ SKIPPED
[INFO] Neo4j - Community Build ............................ SKIPPED
[INFO] Neo4j - Server Assembler ........................... SKIPPED
[INFO] Neo4j - Community Server Assembler ................. SKIPPED
[INFO] Neo4j - Packaging Build ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  31:07 min
[INFO] Finished at: 2024-12-12T12:57:21+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:3.2.5:verify (verify) on project neo4j: There are test failures.

**Comment by hvub** [comment]
Well, which test are failing precisely?

Your console log only show which modules are failing to build. While it is the same module that fails to build, according to you log, it may not necessarily be the same two tests in that module.

Which maven command are you running?

**Comment by michaelwechner** [comment]
I was running "mvn clean install" according to the README

I have deleted the source and I have installed Neo4j as docker in the meantime, which works very fine :-)
