### ISSUE TITLE
Feature Request - Config option to disable ID reuse

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#137]
@dcolebatch: 'There is conflicting reports out there, some google group posts say you can disable vertex ID reuse[1], some say you can't[2].  

We'd love to be able to disable ID reuse in embedded mode and think it could be documented in Chapter 21[3] if it is there already... ?

1: https://groups.google.com/forum/?fromgroups#!searchin/neo4j/node$20ID/neo4j/wn5sQA1BFf4/T-siwqtof5QJ
2: https://groups.google.com/forum/#!topic/neo4j/ilq7624PwaU
3: http://docs.neo4j.org/chunked/milestone/embedded-configuration.html
'

**Comment by fixundfertig123** [comment]
Hey. @akollegger Is there an progress concerning the feature to generate those unique values Neo4j-internally? This feature looks to me like it is requested by various people (see http://stackoverflow.com/search?q=%5Bneo4j%5D+unique+id). Thanks for your work!

**Comment by triomen** [comment]
Hi,

@akollegger , does it mean that there will be a new way to generate UID or that we will be able to rely on node ID in future Neo4j version ?

Thanks for your work !

**Comment by ADTC** [comment]
If you didn't want people to misuse database internals, you shouldn't have exposed them in the first place. I like the idea of making these internal IDs private and hidden, and instead repurposing the `getID` to get an actual externally usable unchanging id (stored as a property), which is also auto-incremented for every new node with the matching criteria (or for simplicity, just incremented database-wide).
