### ISSUE TITLE
Server startup fails in a bad way if lsof is not in path

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#139]
@gorbachev: 'Using 1.6.1 on Unix.

If lsof is not in path, the server startup fails and leaves the database in a dirty state.

$ bin/neo4j start
WARNING: Detected a limit of 16384 for maximum open files, while a minimum value of 40000 is recommended.
WARNING: Problems with the operation of the server may occur. Please refer to the Neo4j manual regarding lifting this limitation.
Starting Neo4j Server...WARNING: not changing user
 process [10861]... waiting for server to be ready.bin/neo4j: line 213: lsof: command not found
.bin/neo4j: line 213: lsof: command not found
.bin/neo4j: line 213: lsof: command not found
.bin/neo4j: line 213: lsof: command not found
[several more of the same errors omitted]
.bin/neo4j: line 213: lsof: command not found
. BAD.
 another server-process is running with []

The script should check that lsof is in path before proceeding.'

**Comment by benbc** [comment]
Our scripts no longer use `lsof`.
