### ISSUE TITLE
Old Labels still being displayed

### ISSUE THREAD

**Issue by mehdibouiri** [neo4j/neo4j#1407]
I created a bunch of labels then  uninstalled  neo4j 2.0 beta and deleted the database.
I installed the same version again with a new database and I still see the old labels.
Attached is a screen shot.
![neo4j data graph_label_issue db](https://f.cloud.github.com/assets/1529372/1454827/1de9bf48-430f-11e3-8601-4cdb597fffec.png)

**Comment by apcj** [comment]
This was fixed in Neo4j 2.1.
