### ISSUE TITLE
sometimes! loss of identifiers on WHERE ... IN with collections

### ISSUE THREAD

**Issue by bossie** [neo4j/neo4j#1421]
The example at http://console.neo4j.org/?id=f9ltpb throws this exception: org.neo4j.graphdb.NotFoundException: Unknown identifier `user`, but only when there is an actual user in the database.

A workaround is a WITH clause, as witnessed here: http://console.neo4j.org/r/b1yyhp

The original question on stackoverflow.com is here: http://stackoverflow.com/questions/19632504/neo4j-similar-queries-one-works-one-fails-with-notfoundexception-unknown-id

**Comment by jakewins** [comment]
Verified that this has since been resolved as per the console link above.
