### ISSUE TITLE
2.0.0-M06 MERGE doesn't ALWAYS work with Constrains

### ISSUE THREAD

**Issue by GoSkyLine** [neo4j/neo4j#1428]
Hello everybody, I'm having issue with MERGE with Constrains in 2.0.0-M06
Basically, I need to insert buge amount of tweets with relationships between them into Neo4j via REST API's Batch endpoint, approx 5k/s
Sometime, it's a single node creation for a tweet; sometime, I need to create both parent and child nodes first and then create relationship.

---

My Schema
[code]
neo4j-sh (0)$ schema
==> Indexes
==>   ON :REPLY(created_at)   ONLINE  
==>   ON :REPLY(ids)          ONLINE (for uniqueness constraint) 
==>   ON :RETWEET(created_at) ONLINE  
==>   ON :RETWEET(ids)        ONLINE (for uniqueness constraint) 
==>   ON :Status(userId)      ONLINE  
==>   ON :Status(statusId)    ONLINE (for uniqueness constraint) 
==> 
==> Constraints
==>   ON (status:Status) ASSERT status.statusId IS UNIQUE
==>   ON (retweet:RETWEET) ASSERT retweet.ids IS UNIQUE
==>   ON (reply:REPLY) ASSERT reply.ids IS UNIQUE
[/code]

---

ISSUE #ONE: MERGE doesn't ALWAYS work with Constrains properly (or Constrains doesn't work with MERGE properly). (random exception)

Here are my test cases:
1. Two MERGE's and one CREATE UNIQUE
When I tried to add two tweets with one relationship between them, I got a exception, which complaining existing node for the child
neo4j-sh (0)$ MERGE (parent:Status {statusId:385813052047626240, userId:466042117}) MERGE (child:Status {statusId:385814827270017024, userId:1130050117}) CREATE UNIQUE parent-[relationship:REPLY {ids:'385813052047626240_385814827270017024', created_at:'Thu Oct 03 14:13:17 ADT 2013' }]->child;
==> CypherExecutionException: Node 270100 already exists with label Status and property "statusId"=[385814827270017024]
1. Then, I broke down my joint query to small pieces. So first, I tried to create the parent node with a single MERGE, it works as expected
   neo4j-sh (0)$ MERGE (parent:Status {statusId:385813052047626240, userId:466042117}) RETURN parent;
   ==> +------------------------------------------------------------+
   ==> | parent                                                     |
   ==> +------------------------------------------------------------+
   ==> | Node[284599]{userId:466042117,statusId:385813052047626240} |
   ==> +------------------------------------------------------------+
   ==> 1 row
   ==> Nodes created: 1
   ==> Properties set: 2
   ==> Labels added: 1
   ==> 4 ms
   neo4j-sh (0)$ MERGE (parent:Status {statusId:385813052047626240, userId:466042117}) RETURN parent;
   ==> +------------------------------------------------------------+
   ==> | parent                                                     |
   ==> +------------------------------------------------------------+
   ==> | Node[284599]{statusId:385813052047626240,userId:466042117} |
   ==> +------------------------------------------------------------+
   ==> 1 row
   ==> 1 ms
2. Next, I tried to create the child node with a single MERGE, but it failed like step 1.
   neo4j-sh (0)$ MERGE (child:Status {statusId:385814827270017024, userId:1130050117}) RETURN child;
   ==> CypherExecutionException: Node 270100 already exists with label Status and property "statusId"=[385814827270017024]
3. I tried MERGE on few more exsting nodes, some worked, some failed.
   I thought it may cased by existing relationship, so I checked both direction of a problemtic node, which turns out it doesn't have any existing relationship in place.
   neo4j-sh (0)$ MERGE (child:Status {statusId:385814902293553153, userId:1725656978});
   ==> CypherExecutionException: Node 301777 already exists with label Status and property "statusId"=[385814902293553153]
   neo4j-sh (0)$ START a = node(301777) MATCH a-[r]->b RETURN b;
   ==> +---+
   ==> | b |
   ==> +---+
   ==> +---+
   ==> 0 row
   ==> 1 ms
   neo4j-sh (0)$ START a = node(301777) MATCH b-[r]->a RETURN b;
   ==> +---+
   ==> | b |
   ==> +---+
   ==> +---+
   ==> 0 row
   ==> 0 ms

---

ISSUE #TWO: Constrained property on relationship doesn't work with CREATE UNIQUE properly, I was able to create duplicate reltionships with same constrained property.
1. First, I have created two nodes and one relationship between them. (MERGE with Constrains worked this time :)), the results below is to show I have them in DB
   neo4j-sh (0)$ MERGE (parent:Status {statusId:1001, userId:901}) MERGE (child:Status {statusId:1002, userId:902}) CREATE UNIQUE parent-[relationship:RETWEET {ids:'1001_1002', created_at:'Mon Nov 04 14:37:56 AST 2013' }]->child RETURN parent, relationship, child;
   ==> +------------------------------------------------------------------------------------------------------------------------------------------------+
   ==> | parent                            | relationship                                                           | child                             |
   ==> +------------------------------------------------------------------------------------------------------------------------------------------------+
   ==> | Node[1]{statusId:1001,userId:901} | :RETWEET[0]{ids:"1001_1002",created_at:"Mon Nov 04 14:37:56 AST 2013"} | Node[2]{statusId:1002,userId:902} |
   ==> +------------------------------------------------------------------------------------------------------------------------------------------------+
   ==> 1 row
   ==> 13 ms
2. Then, I modified the script a bit, where I changed year in created_at from 2013 to 2019, and I expect this to fail, coz the unique constrain is on ids, but the script created a new relationship between same nodes, so it ends up I have two relationships with same constrained ids between two same nodes.
   neo4j-sh (0)$ MERGE (parent:Status {statusId:1001, userId:901}) MERGE (child:Status {statusId:1002, userId:902}) CREATE UNIQUE parent-[relationship:RETWEET {ids:'1001_1002', created_at:'Mon Nov 04 14:37:56 AST 2019' }]->child RETURN parent, relationship, child;
   ==> +-----------------------------------------------------------------------------------------------------------------------------------------------------+
   ==> | parent                            | relationship                                                                | child                             |
   ==> +-----------------------------------------------------------------------------------------------------------------------------------------------------+
   ==> | Node[1]{statusId:1001,userId:901} | :RETWEET[224428]{ids:"1001_1002",created_at:"Mon Nov 04 14:37:56 AST 2019"} | Node[2]{statusId:1002,userId:902} |
   ==> +-----------------------------------------------------------------------------------------------------------------------------------------------------+
   ==> 1 row
   ==> Relationships created: 1
   ==> Properties set: 2
   ==> 12 ms
   neo4j-sh (0)$ START parent=node(1) MATCH parent-[relationship]->(child) WHERE child.statusId=1002 RETURN parent,relationship,child;
   ==> +-----------------------------------------------------------------------------------------------------------------------------------------------------+
   ==> | parent                            | relationship                                                                | child                             |
   ==> +-----------------------------------------------------------------------------------------------------------------------------------------------------+
   ==> | Node[1]{statusId:1001,userId:901} | :RETWEET[0]{ids:"1001_1002",created_at:"Mon Nov 04 14:37:56 AST 2013"}      | Node[2]{statusId:1002,userId:902} |
   ==> | Node[1]{statusId:1001,userId:901} | :RETWEET[224428]{ids:"1001_1002",created_at:"Mon Nov 04 14:37:56 AST 2019"} | Node[2]{statusId:1002,userId:902} |
   ==> +-----------------------------------------------------------------------------------------------------------------------------------------------------+
   ==> 2 rows
   ==> 7 ms

Any help would be much appreciated!!!!! Thank you!
- Jack

**Comment by ghost** [comment]
Hi, I'm experiencing this issue with Neo4j v2.2.0. Using py2neo (python driver) to excute cypher statements (via REST interface).

```
py2neo.cypher.error.schema.ConstraintViolation: Node 1341389 already exists with label User and property "user_id"=[xxxxx]
```

user_id have unique constraints here.

**Comment by trevithj** [comment]
Hmm. I found this to be a bit non-intuitive at first. Here is a solution that seems to work. I want a single query that will do one of 3 things:
1. Create and populate a node if it doesn't exist.
2. Ignore the node if it exists and has the same properties.
3. Update the node if it exists and has new/changed properties.

The original attempt was pretty much just like GoSkyLine's version. I was getting confused around points 2 and 3, probably coming from the assumption that Merge naturally searches on unique identifiers (which it doesn't). In particular, things fell apart when one of the _non-key_ properties changed. After studying the Merge docs at http://neo4j.com/docs/stable/query-merge.html I figured this out:

```
MERGE (n:Actor {id:12345}) WITH n SET n += {name:"Tom Hanks", born:1956} RETURN n
```

This assumes that `id:12345` is a unique identifier. So to avoid duplicates, the MERGE needs to use _only_ the uniqueness constraint. Using `WITH` seems to set the properties regardless of Create/Match, which works for this case. I'm not sure about the _efficiency_ of this approach though (eg, it doesn't exactly ignore the node if properties match. If there is a better way of doing this, an example would be welcome.)

So the above example could perhaps be done like this:

```
MERGE (int:INTERACTION { url: {props}.url })
WITH int SET int.body = {props}.body, int.title = {props}.title
RETURN int
```

This is in Neo4j v2.2.3.

**Comment by sherfert** [comment]
Let us revisit this after a couple years.

- @GoSkyLine and @fguimara and @3denizotesi  experience `Node xxx already exists` errors

- It has been pointed out MERGE is all or nothing, so these errors are expected and an alternative query was given

- @trevithj formulated a feature request. Fortunately, the syntax you want exists. It looks like, e.g.:

```
MERGE (n:Person {name: $value})
  ON CREATE SET n.created = timestamp()
  ON MATCH SET
    n.counter = coalesce(n.counter, 0) + 1,
    n.accessTime = timestamp()
```

I hope everyone is happy now!
