### ISSUE TITLE
2.0.0.M6 - inconsistent behavior when deleting multiple relationships in a merge

### ISSUE THREAD

**Issue by billw1955** [neo4j/neo4j#1430]
You have to run this query twice to replicate. The first time is clean as everything is new. The second time through is when existing pieces, like multiple predecessor nodes, get removed, triggering the 'error'.

BTW, this query is for repeated sync into neo4j from another source (think rsync --delete). I'm running in parallel with a legacy job scheduler. The ongoing edits to host assignment, predecessor jobs and the various process details still happen over there. However, I need to keep the process node ids constant over here as I'm going to hang considerable new schema off of them. The basic idea is that rather than trying to compute what's different, I just strip off the existing 'from over there' state for each n:Process and replace. Relationships I've added over here don't get touched. So far, I haven't had to add properties over here, so I can still get away with set = {map}.

// Is there an 'if exists' on constraints to avoid error noise on subsequent runs?
CREATE CONSTRAINT ON (n:Process) assert n.appname is unique;
CREATE CONSTRAINT ON (n:Category) assert n.name is unique;

// uncomment the following 4 lines to 'pre-delete' n-ary relationship and it works on subsequent passes.
//merge (proc:Process {appname:'dep1and2'})
//with proc
//match proc-[_4?:DEPENDS_ON]->(_d:Process)
//delete _4;
// first run is fine, but subsequent runs with
// 2 or more DEPENDS_ON, fail with CypherExecutionException: Node nnn already exists with label Process and property "appname"=[dep1and2] 
merge (proc:Process {appname:'dep1and2'})
merge (cat:Category {name:'cat1'}) 
merge (_dep0:Process {appname:'pred1'})
merge (_dep1:Process {appname:'pred2'})
with proc, cat, _dep0, _dep1
match 
proc-[_1?:MEMBER_OF]->(_a:Category)
,proc-[_4?:DEPENDS_ON]->(_d:Process)
remove proc:Process
set proc = {appname:'dep1and2', autoexit : 'Y', dayschedule :'Ex,Mo,Tu,We,Th,Fr' }
set proc:Process
delete _1, _4
create unique proc-[:MEMBER_OF]->cat
create unique proc-[:DEPENDS_ON]->_dep0
create unique proc-[:DEPENDS_ON]->_dep1
;

// 0 or 1 DEPENDS_ON works
merge (proc:Process {appname:'doubledep'})
merge (cat:Category {name:'cat1'}) 
merge (_dep0:Process {appname:'d12'})
with proc, cat, _dep0
match 
proc-[_1?:MEMBER_OF]->(_a:Category)
,proc-[_4?:DEPENDS_ON]->(_d:Process)
remove proc:Process
set proc = {appname:'doubledep', autoexit : 'Y', dayschedule :'Ex,Mo,Tu,We,Th,Fr' }
set proc:Process
delete _1, _4
create unique proc-[:MEMBER_OF]->cat
create unique proc-[:DEPENDS_ON]->_dep0
;

// 0 or 1 DEPENDS_ON works
merge (proc:Process {appname:'deponly1'})
merge (cat:Category {name:'cat1'}) 
merge (_dep0:Process {appname:'pred1'})
with proc, cat, _dep0
match 
proc-[_1?:MEMBER_OF]->(_a:Category)
,proc-[_4?:DEPENDS_ON]->(_d:Process)
remove proc:Process
set proc = {appname:'deponly1', autoexit : 'Y', dayschedule :'Ex,Mo,Tu,We,Th,Fr' }
set proc:Process
delete _1, _4
create unique proc-[:MEMBER_OF]->cat
create unique proc-[:DEPENDS_ON]->_dep0
;

merge (proc:Process {appname:'pred1'})
merge (cat:Category {name:'cat1'})
with proc, cat
match 
proc-[_1?:MEMBER_OF]->(_a:Category)
,proc-[_4?:DEPENDS_ON]->(_d:Process)
remove proc:Process
set proc = {appname:'pred1', starttime : '111111', autoexit : 'Y', dayschedule :'Ex,Mo,Tu,We,Th,Fr' }
set proc:Process
delete _1, _4
create unique proc-[:MEMBER_OF]->cat
;

merge (proc:Process {appname:'pred2'})
merge (cat:Category {name:'cat1'})
with proc, cat
match 
proc-[_1?:MEMBER_OF]->(_a:Category)
,proc-[_4?:DEPENDS_ON]->(_d:Process)
remove proc:Process
set proc = {appname:'pred2', starttime : '222222', autoexit : 'Y', dayschedule :'Ex,Mo,Tu,We,Th,Fr' }
set proc:Process
delete _1, _4
create unique proc-[:MEMBER_OF]->cat
;
start n=node(_) return id(n), n.appname, labels(n);
start n=node(_) match p=(n:Process)-->() return p;

**Comment by sherfert** [comment]
I am sincerely sorry to be picking this up a _little_ late. Anyhow, it would be awesome if you could provide a  script (.cypher) that we can execute in neo4j-shell or cypher-shell in version 2.3 or later. That script should reproducibly trigger your bug.

Also, a simple verbatim paste of your error message would be tremendously helpful.

Thanks!

**Comment by sherfert** [comment]
Closing for now. Please reopen if needed.
