### ISSUE TITLE
Node becomes queryable before a property from the same transaction

### ISSUE THREAD

**Issue by jzarrelli** [neo4j/neo4j#1436]
During a transaction:
1) I start a transaction.
2) I create a node object with db.createNode().
3) I add various properties to the node, and add some of them to indexes.
4) I commit the transaction.
Potentially in a different thread:
1) I query the index and receive the node created above
2) I attempt to access a different property on the node.
3) The property is not present, causing an error.

I have noticed that at least usually (and possibly always, but I am not certain), the .setProperty call for the missing property was made after the index.add call of the index that the node was retrieved from, although they are both contained in the same transaction. The node is never modified in subsequent transactions.

I currently work around this by doing the following:
while (!node.hasProperty(property)) {
            try {
                Thread.sleep(40);
            }

This happens only occasionally, but often enough to happen once every ten minutes or so under heavy load. This is done using embedded mode of Neo4j 1.9.4.

**Comment by jakewins** [comment]
This was a caching issue, which has been resolved in the 2.x series of releases. The initial fix is in 2.1, and the cache is removed entirely in 2.3.
