### ISSUE TITLE
Lucene Auto Index Case Insensitive Configuration Setting

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#148]
@SepiaGroup: 'Add a setting that will lowercase all auto indexed values and searches such as auto_index_lowercase=true

https://groups.google.com/forum/?fromgroups#!topic/neo4j/MA7s6umhISM
'

**Comment by toddleo** [comment]
Is this issue solved yet? Is `case_insensitive` available now?

**Comment by ghost** [comment]
This would be a great feature.

**Comment by burqen** [comment]
Case insensitive feature is available for manual indexes. See https://neo4j.com/docs/java-reference/current/#indexing-create-advanced

**Comment by francescoinfante** [comment]
I don't understand why this issue was closed @burqen. Indeed this could be a great feature. The auto index is much easier to create than a manual index.

**Comment by davidrapin** [comment]
@burqen please don't close issues so abruptly, this is a critical feature and, as far as I know, it's still impossible to enable case-insensitivity for automatic indices.

Either keep the issue open or provider some helpful information on how to enable case-insensitivity in this scenario (using Neo4j 3):
```
# neo4j configuration file

# nodes automatic indices
dbms.auto_index.nodes.enabled=true
dbms.auto_index.nodes.keys=name,address,city
# how do I make these node-indices case-insensitive? 

# relationships automatic indices
dbms.auto_index.relationships.enabled=true
dbms.auto_index.relationships.keys=role,salary
# how do I make these relationship-indices case-insensitive? 
```

**Comment by burqen** [comment]
@francescoinfante @davidrapin Sorry! I was being to quick to judge here. Re-opening this issue and adding feature request to backlog.
Thank you for poking me about this! 😄

**Comment by chrisvest** [comment]
The fulltext schema indexes added in 3.5 do case insensitive querying by default. Auto- and manual-indexes are deprecated for removal in 4.0.
