### ISSUE TITLE
Sorry! Too many neighbours

### ISSUE THREAD

**Issue by galliva** [neo4j/neo4j#1517]
I have a node representing a person with 94 relationships to friends:

```
START a=node:node_auto_index(name="John Doe") 
MATCH (a)-[:FRIEND_OF]->(b)
RETURN count(b)

> 94
```

In the neo4j console I would like to click on John and see his neighbours, so I execute:

```
START a=node:node_auto_index(name="John Doe") 
RETURN a
```

as expected, one node is returned represented by a circle.

If I double-click on the node, a javascript alert saying "Sorry! Too many neighbours" appears, and I'm not able to "open" the node.

I looked in google, but there is only one result regarding this error...

Anyone can help?
How "many neighbours" is too much?
Can I configure the maximum?

Thanks!

**Comment by ambition-consulting** [comment]
At least make it configurable - it's the user's choice how much time he got to wait for results.

**Comment by jexp** [comment]
it is configurable, see: http://neo4j.com/developer/guide-neo4j-browser/#_some_tips_and_tricks_for_neo4j_browser

**Comment by ambition-consulting** [comment]
good to know - cheers! :)
