### ISSUE TITLE
Relationship schema indexes

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#155]
@sarmbruster: 'As of now, autoindexing is supported for properties on nodes and relationships.

Please add a capability to index the relationshipType to the relationship auto index.'

**Comment by burqen** [comment]
@sarmbruster Is this still relevant to you or can we close this ticket?

**Comment by sarmbruster** [comment]
based on @burqen 's request I'm closing this one.
Can be easily implemented via APOC these days.
