### ISSUE TITLE
Unit testing in version 2

### ISSUE THREAD

**Issue by aramk** [neo4j/neo4j#1551]
I was following the basic unit testing tutorial here:

http://docs.neo4j.org/chunked/stable/tutorials-java-unit-testing.html

When I noticed that the dependencies listed don't work if I specify `2.0.0-M6` or `2.0.0-RC1`. I had to roll back to `1.9.4` to prevent any issues. The working configuration I'm using for Maven is:

```
<properties>
    <neo4j.version>1.9.4</neo4j.version>
  </properties>

<dependency>
      <groupId>org.neo4j</groupId>
      <artifactId>neo4j</artifactId>
      <version>${neo4j.version}</version>
</dependency>

<dependency>
      <groupId>org.neo4j</groupId>
      <artifactId>neo4j-kernel</artifactId>
      <version>${neo4j.version}</version>
      <type>test-jar</type>
      <scope>test</scope>
</dependency>
```

The issues revolve around missing classes such as `org.neo4j.tooling.Clock` (which is in a different package in version 2). I'm guessing this is expected as the new version is being developed, but thought I'd mention it here for others.

**Comment by jakewins** [comment]
As there's been no reply to Michaels question in this ticket for two years, closing this. Please re-open if this issue remains.
