### ISSUE TITLE
Specify optional decimal places with round(num,dp)

### ISSUE THREAD

**Issue by jacquibo** [neo4j/neo4j#1580]
Would it be possible to add the functionality to optionally specify the decimal places to round a number to?

At the moment round() only rounds to the nearest integer, but it would be great to be able to do something like the following:

round(3.1474001,3) to get 3.147
round(3.1474001,2) to get 3.15
round(3.147001) to get 3

Thank you :)

**Comment by chrisvest** [comment]
Doesn't look like a common thing for languages to have, so I'm closing this with the assumption that this need is rare enough that people don't mind to work around it.

**Comment by relicmelex** [comment]
@jacquibo Did you ever figure this out? I'm running into this issue and it's obnoxious that the Cypher Query can't add two numbers simply for me. How terrible!?

@mneedham They took down your work around, can you maybe follow up what you did here, of if you've heard of another solution to this floating point addition issue?
