### ISSUE TITLE
neo4j-enterprise-2.0.0-RC1: shell not responding

### ISSUE THREAD

**Issue by galliva** [neo4j/neo4j#1588]
I have a remote neo4j installation, shell is enabled on port 1337:

$ telnet MYIP 1337
Trying MYIP...
Connected to MYIP

When I try to start the shell the connection seem to work (it is not refused), but nothing happens. The console just hangs on a blank line and nothing happens.

Any idea?

Thanks and best!

**Comment by pedrorjbr** [comment]
I am facing the same issue. Is there a solution?

**Comment by craigtaverner** [comment]
Neo4j-shell has been deprecated since Neo4j 3.0, and is replaced by cypher-shell. Please try with cypher-shell and if the same problems exist there open a new issue. Neo4j-shell will be removed from the product soon.
