### ISSUE TITLE
Detected a limit of 256 for maximum open files, while a minimum value of 40000 is recommended

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#159]
@anderskristian: 'Problems with the operation of the server may occur. Please refer to the Neo4j manual regarding lifting this limitation.

I have tried to "lifting" this limitation on my OSX 10.7.3.
In the beginning I found no solution to the problem.

But then I found a tool to set the limit to 100 open files
ulimit -S -n 100

Then I  Restart neo4j and got warning.... Detected a limit of 100 for maximum open files....

But it still worked..
And the number of open files is
sudo lsof | grep REG |grep -c "PID"
That is over 200
(Replace PID with the pid from bin/neo4j info)

So my final conclusion is that the warning is wrong.
Reading: http://krypted.com/mac-os-x/maximum-files-in-mac-os-x/ says that OSX by default has over 10.000 in this value.

This also explains why my neo4j works. 

Conclusion: The warning is not necessary.'

**Comment by ajmazurie** [comment]
Not sure why this was closed; I am having the exact same problem with Neo4j 2.3.0 on OSX 10.10.5.

**Comment by jakewins** [comment]
@ajmazurie hmm, that's likely a regression then. Reopening.
