### ISSUE TITLE
feature request: expose server directory to classpath

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#160]
@sarmbruster: 'Some third party tools load resources from the classpath using classloader.getResoource(name). It would be useful if Neo4j's startup process exposes some directory to act as classpath. This is the same behaviour like lib/classes in tomcat: lib holds the jars, lib/classes holds some externalized configs (e.g. properties,xml files).'

**Comment by technige** [comment]
Closing as unlikely to still be relevant.
