### ISSUE TITLE
2.0-RC1: IllegalStateException accessing TransactionData/createdRelationships

### ISSUE THREAD

**Issue by rakvat** [neo4j/neo4j#1634]
I wrote a ServerPlugin that registers TransactionEventHandler. In afterCommit I access transactionData.createdRelationships(). When iterating over the created relationships and accessing e.g. relationship.getType() or relationship.getStartNode() I get "java.lang.IllegalStateException: Tx status is: STATUS_COMMITED".

I was able to do that in 2.0-M06 without catching an Exception.

**Comment by jakewins** [comment]
As of 6bfa6be9a40e8cbb346dde8dcf979941679784d9 this issue should be resolved.
