### ISSUE TITLE
Provide a way to get back all properties of a node/rel

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#164]
@peterneubauer: 'I wold like to have a way to explore stuff on a node/rel, like

start n = node(0) return collect(n.*)

or something.'

**Comment by Cyrille37** [comment]
Hi,
I found [here](https://github.com/neo4j/neo4j/pull/3884#issue-55726932) this query that return a list of all properties that match a string:

example that return an array (_row in cypher way_) with all nodes's properties name, properties with name start with "n" (_like name, node, noob_): 
`MATCH (n) WITH keys(n) AS p UNWIND p AS x WITH DISTINCT x WHERE x =~ "n.*" RETURN collect(x) AS SET;`
Do not forget to add "row" in "resultDataContents" query parameter:

```
"resultDataContents": [
        "row",
        "graph"
      ]

```
