### ISSUE TITLE
Expose MERGE operation through Java API

### ISSUE THREAD

**Issue by Bohtvaroh** [neo4j/neo4j#1640]
Please, expose Cypher's MERGE operation through Neo4j Java API.

**Comment by noam-paz** [comment]
@karabijavad, I'd like to support @Bohtvaroh on his  issue.

First, Cypher's MERGE is in a sense an atomic Operation. Your Suggestion (find the node, query all its relationships and perhaps create a new relationship) is not.

Second, and more important: graphDb.findNode() allows searching for exactly ONE property. What if I need to match (or create) a node with more properties like in the following  MERGE statement:
MERGE (category:P_Category    {name: cat,    level: toInt('1'), from_year: toInt('2016'), from_month: toInt('11'), from_day: toInt('21')})   ?
Yes, it is doable in Java, but IMHO awkward.

Finally I think, the more the Cypher Interface and the Java Interface resemble each other, the better. Ideally you can use exactly the same code in the Interface of your choice.

So: is there a chance to expose Cypher's MERGE operation through Neo4j Java API? 
As of 3.0.7 I could not find it.

Thanks!
Noam

**Comment by burqen** [comment]
@Bohtvaroh @noam-paz Thank you for reporting!
I agree that it is quite awkward to do thought the Java API.

Seeing as the preferred way of using Neo4j is through Cypher and Drivers I don't see this being prioritised any time soon.

What you can do is to simple use `GraphDatabaseService.execute( String query )` to execute the merge query.

A comment on atomicity.
The atomicity (apply all or nothing) of the transaction is gonna be the same independently if you use merge through cypher or manually create stuff through the java API.

/Anton

**Comment by tinwelint** [comment]
The Java API will not see continued development like this. Please use Cypher, or the `execute` work-around as Anton suggests.

**Comment by ivangreene** [comment]
What is the reason not to continue the Java API development? I would rather write this:
```java
Node orange = transaction.mergeNode(Label.label("fruit"));
orange.setProperty("type", "orange");
orange.createRelationshipTo( ...
```
Than this:
```java
Result result = transaction.execute("MERGE (f:Fruit { type: $type }) RETURN id(f) AS id", Map.of("type", "orange"));
Node orange = transaction.getNodeById((long) result.next().get("id"));
orange.createRelationshipTo( ...
```
Please let me know if there is an easier way to do this kind of operation in the Java API and gain access to the existing or created Node for creating relationships, etc
