### ISSUE TITLE
Ant exception compiling neo4j-browser

### ISSUE THREAD

**Issue by mauriff** [neo4j/neo4j#1643]
When run mvn  package on neo4j-browser project an exception occurs:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.6:run (default) on project neo4j-browser: An Ant BuildException has occured: unless=cmdsuccess -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.6:run (default) on project neo4j-browser: An Ant BuildException has occured: unless=cmdsuccess

Notice that I'm running on Windows OS and And task is for unix SO:

                <exec executable="node_modules/.bin/grunt" dir="${project.basedir}" osfamily="unix" resultproperty="cmdresult">
                  <arg line="no-color build" />
                </exec>

Output for 
community\browser>mvn package -Dlicensing.skip -DskipTests -e -X

Apache Maven 3.0.5 (r01de14724cdef164cd33c7c8c2fe155faf9602da; 2013-02-19 10:51:28-0300)
Maven home: C:\software\apache-maven-3.0.5-bin\apache-maven-3.0.5\bin\..
Java version: 1.7.0_17, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.7.0_17\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"
[INFO] Error stacktraces are turned on.
.....[INFO logs]....
Setting project property: settings.localRepository -> C:\Users\fbqn87\.m2\repository
Setting project property: org.neo4j:neo4j-kernel:jar -> C:\Users\fbqn87\.m2\repository\org\neo4j\neo4j-kernel\2.0-SNAPSHOT\neo4j-kernel-2.0-SNAPSHOT.jar
Setting project property: org.apache.geronimo.specs:geronimo-jta_1.1_spec:jar -> C:\Users\fbqn87\.m2\repository\org\apache\geronimo\specs\geronimo-jta_1.1_spec\1.1.1\geronimo-jta_1.1_spec-1.1.1.jar
Setting project property: com.sun.tools:tools:jar -> C:\Program Files\Java\jdk1.7.0_17\jre\..\lib\tools.jar
Setting project property: maven.project.dependencies.versions -> 2.0-20131206.154632-39;1.1.1;1.7;
Setting project property: maven.dependency.org.neo4j.neo4j-kernel.jar.path -> C:\Users\fbqn87\.m2\repository\org\neo4j\neo4j-kernel\2.0-SNAPSHOT\neo4j-kernel-2.0-SNAPSHOT.jar
Setting project property: maven.dependency.org.apache.geronimo.specs.geronimo-jta_1.1_spec.jar.path -> C:\Users\fbqn87\.m2\repository\org\apache\geronimo\specs\geronimo-jta_1.1_spec\1.1.1\geronimo-jta_1.1_spec-1.1.1.jar
Setting project property: maven.dependency.com.sun.tools.tools.jar.path -> C:\Program Files\Java\jdk1.7.0_17\jre\..\lib\tools.jar
[INFO] Executing tasks
Build sequence for target(s) `hipster build' is [hipster build]
Complete build sequence is [hipster build, ]

hipster build:
Class org.apache.tools.ant.taskdefs.condition.Equals loaded from parent loader (parentFirst)
Property "cmdresult" has not been set
Condition false; not setting cmdsuccess
     [fail] failing due to unless=cmdsuccess
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.672s
[INFO] Finished at: Sun Dec 08 14:04:22 GMT-03:00 2013
[INFO] Final Memory: 9M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.6:run (default) on project neo4j-browser: An Ant BuildException has occured: unless=cmdsuccess -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.6:run (default) on project neo4j-browser: An Ant BuildException has occured: unless=cmdsuccess
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)

**Comment by apcj** [comment]
Hi, sadly building the browser code is not currently supported on windows. If you want to build the other parts of the codebase, you can run maven with `-DskipBrowser`.
