### ISSUE TITLE
Browser :help, multiple issues

### ISSUE THREAD

**Issue by jakewins** [neo4j/neo4j#1645]
From @jexp 

- [ ] `:help <unknown keyword>` yields an "Unknown Error"
- [ ] `:help remove` is linked but unknown
- [ ]  `:help index` is hidden under `:help create index on`
- [ ]  `:help delete` has incorrect links for `:help return` and `:help remove`
- [ ]  no help on constraints

**Comment by oskarhane** [comment]
All except `:help index` are fixed so I'll close this and create an internal note for the remaining one.
