### ISSUE TITLE
Obsolete labels remain in local storage

### ISSUE THREAD

**Issue by jakewins** [neo4j/neo4j#1649]
From @pekrau

When displaying graphs, the label representations include labels that no longer exist in the data. I traced the cause to the local browser storage for the Neo4j browser app page, which I cleared "by hand" using the Chrome developer tools. Then the obsolete labels disappeared as I redisplayed the page.

It was not sufficient to delete browser data ("Cache", and ""Data from hosted apps").

Not sure how to fix it, but when experimenting with labels, it's annoying to have old labels hang around for ever.

**Comment by snig-b** [comment]
How to remove labels that do not have any node associated now? 
I created a node and added a label to it, deleted the node but the label is still present.
Old test labels hanging in the studio is a bit of a hindrance.
I do not see any eye icon or stylesheet for a specific graph, there is a generic stylesheet in the menu and it is already in the default style.

**Comment by jexp** [comment]
Unfortunately that's right now not possible but we will do that going forward.

The screenshot was for Neo4j 2.1.x now it looks like this:

![](http://dev.assets.neo4j.com.s3.amazonaws.com/wp-content/uploads/style_sheet_grass.jpg)

**Comment by Brandyparty** [comment]
Is there a way to get rid of old labels, relationships and properties that are not used in the newer versions of neo4j? The methods discussed here don't seem to work for me.
