### ISSUE TITLE
Representation of arrays and nested arrays in tables is broken

### ISSUE THREAD

**Issue by jakewins** [neo4j/neo4j#1657]
From @jexp

Misses the distinction of the nestedness (just a flat comma list) and also no square brackets to indicate an array / list -> could also just be a comma separated string.

See:
`return [1,2,3]`

`return [[1,2,3],[4,5,6]]`

**Comment by oskarhane** [comment]
Fixed in https://github.com/neo4j/neo4j/pull/4005
