### ISSUE TITLE
style REST result JSON similar to the table view for graphs

### ISSUE THREAD

**Issue by jakewins** [neo4j/neo4j#1658]
From @jexp 

I mean like this (just with correct array handling), but pretty print would be awesome already :)

![neo4j data_graph db](https://f.cloud.github.com/assets/67427/1550212/3fbec790-4dfe-11e3-845e-06237e9db531.jpg)

**Comment by oskarhane** [comment]
This issue was moved to neo4j/neo4j-browser#117
