### ISSUE TITLE
Syntax highlighting of "id"

### ISSUE THREAD

**Issue by jakewins** [neo4j/neo4j#1665]
From @akollegger @alexaverbuch 

Properties named "id" are syntax highlighted in black, whereas all other properties are in green

![neo4jbrowser__id__highlight](https://f.cloud.github.com/assets/53756/1502259/10e904d2-4898-11e3-849a-31a4dce86577.png)

**Comment by oskarhane** [comment]
This issue was moved to neo4j/neo4j-browser#119
