### ISSUE TITLE
Cannot set style of node with multiple labels

### ISSUE THREAD

**Issue by jakewins** [neo4j/neo4j#1666]
From @npryce

My graph has nodes with multiple labels.  E.g. {Object} (represents an object) and {Object,Array} (represents an object that is an array).  I'd like to style {Object,Array } nodes differently from {Object} nodes.  However...

If I define a stylesheet rule for node.Array, the rule for node.Object takes precedence and the Array rule is not applied.

If I define a stylesheet rule for node.Object.Array (CSS-like syntax for an element with multiple classes), the ".Array" part is discarded -- the rule is parsed as node.Object.

This problem occurs if I have the rule for node.Object before node.Array or vice versa.

**Comment by apcj** [comment]
Hi @npryce, this was finally fixed in https://github.com/neo4j/neo4j/pull/4092
