### ISSUE TITLE
Wanted: a quick way to apply a GraSS stylesheet

### ISSUE THREAD

**Issue by jakewins** [neo4j/neo4j#1667]
From @npryce

At the moment, it's a bit of a schlep to upload a GraSS stylesheet.  You have to run a query, click on one of the nodes to open the style popup, click on "View stylesheet" in the style popup to open a stylesheet dialog, and then drag a GrASS file into a drop target in the stylesheet dialog.

It would be nice if there was a convenient way to install a stylesheet before running queries.

**Comment by apcj** [comment]
The GraSS editor is now available from the `:style` command, and from a button in the left-hand drawer.
