### ISSUE TITLE
Let the user enter a node label expression in the style selector popup

### ISSUE THREAD

**Issue by jakewins** [neo4j/neo4j#1668]
From @npryce

I'd like to use the GraSS template syntax for labelling nodes but the style selector popup only allows me to pick a property to use as the label.

E.g. if I have a node with properties 'address' and 'size' I'd like to specify the node label to be "[{size}]@{address}"

**Comment by apcj** [comment]
You can specify a compound caption formed from multiple properties in GraSS using a line like this:

```
caption: '[{size}]@{address}'
```
