### ISSUE TITLE
[Feature Request] Cypher syntax checking API

### ISSUE THREAD

**Issue by ducky427** [neo4j/neo4j#1683]
It would be nice if there was a way in the REST API to check if a cypher query is valid or not without actually having to run it and then checking for errors.

**Comment by joelhandwell** [comment]
+1, would there any milestone be set for this feature? This API would allow IDE, editor, or lint tool integration

**Comment by jexp** [comment]
you can actually already do it with 2.2.x

just send the query with EXPLAIN prefix to the transactional rest endpoint.
You'll get a query plan, sometimes warnings and errors for invalid queries back.

**Comment by joelhandwell** [comment]
@jexp Thanks!

**Comment by chrisvest** [comment]
Closing because `EXPLAIN` is how to do this.
