### ISSUE TITLE
List property names of a map

### ISSUE THREAD

**Issue by freethejazz** [neo4j/neo4j#1695]
Now that maps are supported, I think it would be a good idea to be able get the property names of a map (as well as those of nodes and relationships, perhaps).  It's currently possible to get all the values in a map, but getting all of the property names could be valuable, too.

For example:

    WITH { foo: 2, bar: "stool" } as mapLit
    RETURN keys(mapLit)

would return the collection: `[ "foo", "bar" ]`.  I'm using `keys` here as a placeholder method name for the functionality I'm proposing (from JavaScript's `Object.keys()` .)

Alone this would provide little more than exploration of the graph, but when paired with dynamic property access, things get more interesting. (See https://github.com/neo4j/neo4j/issues/1696)

Expanding to nodes and relationships would need some extra consideration, particularly because you're often dealing with collections of nodes and relationships Should the entire collection be traversed and all keys be returned, similar to how labels works?  Should only unique keys be returned?  Maybe `keys` would be strictly for maps, and a separate `toMap` function could be created to convert nodes and relationships into maps of just their properties.

A lot of ideas for adding better map support were thrown around in https://github.com/neo4j/neo4j/issues/33, but there were several layers of issues being discussed at once (maps, expressing nodes/rels as maps, syntax for maps).  It was good for opening the conversation and getting the thought process going, but as for coming to decisions, biting off smaller chunks is a more realistic approach, in my opinion.

**Comment by antonio-castellon** [comment]
I'm looking exactly for the same feature..I wrote a message on the google group https://groups.google.com/forum/#!topic/neo4j/SJ4F3_dG8Tk I hope that someone take the baton from Neo4j team.

**Comment by freethejazz** [comment]
I'd be more than happy to get a PR together for this, but would like some feedback from the maintainers before setting out on that path. Anyone?

**Comment by antonio-castellon** [comment]
Me too... How we can do it?

**Comment by systay** [comment]
I'll bite!

I think it makes sense to add the `keys()` function. It should accept all types of maps - in Cypher, nodes and relationships are considered to be a type of map. I don't think we should have `keys()` accepting collections or paths - that is a separate concern.

Unless you already stumbled over it, here is a starting point: http://neo4j.com/docs/stable/community-contributing-code.html

Please don't hesitate to reach out if you need a hand or two.

Cheers

**Comment by freethejazz** [comment]
Bitten! Thanks @systay. I'll play around with this over the weekend with my scala :tophat: on.

**Comment by antonio-castellon** [comment]
Dear systay, fist of all .. I want to known if this feature is in the scope of the current roadmap for Neo4j future versions or not.
The second, is that I just downloaded and compiled all the sources, but really we need a someone that orient to us into the source code. Do you known someone? I cansee quickly classes like `parser`, `commands`, ...and maybe the most important for us, the `functions` (like `Labels`). Exist any document that describe as an exmaple how is working the cypher engine (from the String Sentence to the execution of the search)?

Thanks in advance

**Comment by freethejazz** [comment]
@antonio-castellon If you want to do some digging into the codebase, search through the github repository for `coalesce`. You'll see instances in the the code of pretty much all the places you need to work on. I've never worked directly on neo4j, though, so this is just an educated guess. I had environment issues last weekend, but have resolved them and will be working on this feature this weekend.

**Comment by boggle** [comment]
We are considering adding dynamic property lookup to Cypher; please comment on the proposal at

https://docs.google.com/document/d/1FPfGkgzhcRXVkleBLBsA92U94Mx4yafu3nO-Xf-NzsE/edit?usp=sharing
