### ISSUE TITLE
Add dynamic property lookup

### ISSUE THREAD

**Issue by freethejazz** [neo4j/neo4j#1696]
At this point in time, it's only possible to access properties on a node, relationship, or map if you know what the property name is ahead of time.  I suggesting adding the ability to dynamically access those properties with bound identifiers.

Square bracket notation (like JavaScript) would be a possible way of expressing it:

    MATCH (n)
    WITH n, "propName" as test
    RETURN n[test]

Where `n[test]` is standing in for `n.propName`.  Elsewhere in the language, square brackets are used differently, so it may not be clear.

Potential uses would be checking nodes to insure they have a list of properties passed in via parameters:

_Parameters_

    {
        desiredProps: ["name", "birthday", "favoriteColor"]
    }

_Query_

    MATCH (n)-[:OWNS]->()
    WHERE filter( node in n WHERE all( prop in {desiredProps} WHERE has(node[prop])))
    RETURN n;

Or when combined with listing property names of a map (https://github.com/neo4j/neo4j/issues/1695), one could easily evolve a schema dynamically:

_Parameters_

    {
        fieldsToAdd: {
            favoriteColor: "blue, no green",
            mileTime: 8.5
        }
    }

_Query_

    MATCH (n)
    FOREACH( newProp in keys({fieldsToAdd}) |
        SET n[newProp] = {fieldsToAdd}[newProp]
     )

**Comment by boggle** [comment]
We are considering adding dynamic property lookup to Cypher; please comment on the proposal at

https://docs.google.com/document/d/1FPfGkgzhcRXVkleBLBsA92U94Mx4yafu3nO-Xf-NzsE/edit?usp=sharing

**Comment by lutovich** [comment]
Requested feature has been added to 2.3 branch: https://github.com/neo4j/neo4j/pull/4796
