### ISSUE TITLE
(Question) inquiring size of relationship array of a node

### ISSUE THREAD

**Issue by giladmanor** [neo4j/neo4j#1700]
Hi, 
I need a fast way to measure the number of relationships on a particular node.
this information is (i believe) available on NodeImpl.getRelationshipIds()

My problem is that in my application i have an instance of a NodeProxy
that is returned to me from an index hit

is there a way i can grab an instance of the NodeImpl by a given ID?
(my intention is then to cast it on one of my own classes that extends it and get the info i am looking for)

the other option is of course to iterate on the results from the proxy, but that is a huge strain on performance.

cheers
gilad

**Comment by jakewins** [comment]
This is now part of the API via `getDegree`
