### ISSUE TITLE
Configurable Log Rotation

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#172]
@bachmanm: 'It would be nice if it was possible to configure when Neo does its log rotation, so this can be triggered during quiet periods.'

**Comment by tinwelint** [comment]
This is now essentially replaced by checkpointing in version 2.3, you can configure both checkpoint time interval and number of transactions interval. Checkpointing is now where the store flushing happens. Log rotation is just a cheap operation unrelated to heavy store I/O.

With this said it's still not possible to configure to checkpoint a certain time of day. Do you think this is still an issue worth pursuing?

**Comment by chrisvest** [comment]
I doubt it. Log rotation typically completes within a handful of milliseconds these days.

**Comment by tinwelint** [comment]
@chrisvest I'm thinking about checkpointing, forget about log rotation

**Comment by bachmanm** [comment]
I'd close it as won't fix. Haven't come across anybody wanting this since over 3 years ago when I reported it. Cheers!

**Comment by chrisvest** [comment]
Alright, closing as won't fix. We already have it on the plan to make the check-pointing thread be more gentle when doing IO, such that there won't be a need to schedule it to run in off-hours. This way, there is also no change of extremely long recovery times if a crash happens after a no-check-pointing period.
