### ISSUE TITLE
Strange TransactionEventHandler-behaviour

### ISSUE THREAD

**Issue by micotom** [neo4j/neo4j#1752]
<p>I'm currently facing strange behaviour in my transaction event handler using the Java API. When registering the handler to my (everytime newly created) embedded graph database and adding nodes and relationships to the db, the <b>afterCommit- and beforeCommit-methods fire randomly with no valid TransactionData</b> (iterating over all the integrated structures brings no diff element at all) inbetween the insert-threads.</p>
<p>Those threads are synchronized in a manner, that only one thread can be actively inserting. 
Same code with <b>Neo4j 1.9 works perfectly</b> (event the tx.close/success exchange makes no difference)!</p>

<b>What happens in the code is as follows:</b>
+ Parsing of a XML-file
   - collects three different types of objects and inserts them into different (java-)sets</p>
   - when such a set reaches a certain size, a thread is kicked off from one of the the threadpool specialized to the certain objectType, that has to insert the set
+ Thread-Inserts
   - three different types of object get inserted into Neo4j while parsing (and naturally given afterwards parsing)
      * type ObjectA becomes a node with some properties (fetched by getOrCreate())
      * type ObjectB becomes a node with a relation to another node (fetched by getOrCreate())
      * type ObjectC becomes two nodes with a relation inbetween (both fetched by getOrCreate())
   - threads are synchronized in a manner, that only one can be actively inserting into the db. This is realized by a semaphore as follows:
      * all objectType-pools query an atomic integer to be 0: if so, release the thread that waits in beforeExecute (raise semaphore to 1 and start a tx)
      * when the thread is finished, do not touch the semaphore, but wait for the registered TransactionEventHandler to call afterCommit() - only that will decrease the semaphore to 0

With Neo4j 2.0 the TransactionEventHandler now also fires, when no thread is finished - this <b>does not cause a TX-deadlock</b>, but it decreases the semaphore below 0 (so my synchronization does not work properly anymore). The data within the afterCommit() in turn here is empty - although the docs state that the TransactionEventHandler does not fire when there was nothing to commit. To make things worse, <b>the handler does sometimes not fire, when a thread has finished (a tx should be committed)</b>.

**Comment by jakewins** [comment]
There were extensive issues with event handlers when we first released 2.x. The transaction event handling system was reworked from scratch in 2.1, meaning this issue should be resolved. Please re-open if the problem remains in Neo4j 2.1+, and if so, if you could include a little code snippet that shows the problem that would be brilliant.
