### ISSUE TITLE
Cypher looks for the most distant nodes first.

### ISSUE THREAD

**Issue by PieterJanVanAeken** [neo4j/neo4j#1759]
Suppose a message chain structure like this :

**(start:START)-[:NEXT]->(message1:MESSAGE)-[:NEXT]->
(message2:MESSAGE)-[:NEXT]-> ... -[:NEXT]->(end:END)**

Now, if I do the following query : 

**MATCH (end:END)<-[:NEXT*]-(message:MESSAGE)
RETURN message
LIMIT 10;**

You would expect to get the last 10 messages, in stead you get the first 10. Which not only does not make sense, it's also not performant. You'd expect it to incrementally go one :NEXT relationship furter until it has found 10 messages. In stead it goes over all the :NEXT relationships all the way to the end, and then returns the first 10 messages, 

If you want to do a quick test, execute the following queries in Neo4j.

**CREATE (start:START)-[:NEXT]->(msg1:MSG {id: "1"})-[:NEXT]->(msg2:MSG {id: "2"})-[:NEXT]->(end:END);**

**MATCH (end:END)<-[:NEXT*]-(message:MSG) 
RETURN message.id 
LIMIT 1;**

The second query should return 2, in stead it returns 1.

**Comment by jakewins** [comment]
The efficiency aspect of this should be resolved by the new cost planner. As per the behavior itself, agree with Leishman above that this is not wrong, the query needs an `ORDER BY` - or, better yet, describe it as a single path to look up, with the limit in there, and unwind to return, something like:

```
MATCH p=(:END)<-[:NEXT1*10]-(:MESSAGE)
WITH nodes(p) AS messages 
UNWIND messages AS message
RETURN message.id
```

**Comment by jexp** [comment]
If you use this it returns each of the last messages of a each sub-path.

``` sql
MATCH (end:END)<-[:NEXT*]-(message:MESSAGE)
RETURN end
LIMIT 10;
```

For Jake's proposal I'd use:

``` sql
MATCH p=(:END)<-[:NEXT1*10]-(:MESSAGE)
WITH p ORDER BY LENGTH(p) DESC LIMIT 1
UNWIND nodes(p) AS message
RETURN message.id
```
