### ISSUE TITLE
Export self contained interactive html page of result set.

### ISSUE THREAD

**Issue by chrisgogreen** [neo4j/neo4j#1761]
I want to send the results of a Cypher query in visual form to a team member. If in addition to the current csv export we could download a zip archive with the files: index.html, styles.css, scripts.js, data.json all tied together so the user can just open the index.html and explore the data with a subset of features from the browser.  Currently I just screen-print the graph results which doesn't allow viewing properties or changing the css.

**Comment by oskarhane** [comment]
This issue was moved to neo4j/neo4j-browser#122
