### ISSUE TITLE
IncomparableValuesException thrown when trying to order by node labels

### ISSUE THREAD

**Issue by symonsjo** [neo4j/neo4j#1776]
Server version 2.0.0 Enterprise Stable.

Trying to compare across all nodes and order by labels in cypher throws an IncomparableValuesException:

```
neo4j-sh (?)$ START n=node(*) RETURN labels(n), count(*) ORDER BY labels(n);                                       
IncomparableValuesException: Don't know how to compare that. Left: ["NHS_TRUST_LOCATION"] ($colon$colon); Right: ["NRLS_DATA_TYPE"] ($colon$colon)
```

Workaround provided as:

```
START n=node(*) RETURN labels(n), count(*) ORDER BY labels(n)[0];
```

Or for named ordering:

```
START n=node(*) RETURN labels(n)[0] AS node_labels, count(*) ORDER BY node_labels;
```

Note that order by type on relationships works fine.

[Original google group post](https://groups.google.com/forum/#!topic/neo4j/xJvisYRaTrQ)

**Comment by sherfert** [comment]
I cannot reproduce on 2.3 or later.
