### ISSUE TITLE
Function to turn timestamp() result into year-month-day hour:minute:second.microsecond ISO format

### ISSUE THREAD

**Issue by Marsaly** [neo4j/neo4j#1810]
It is usually better to assign timestamps on server, but what if developer prefers readable ISO-formatted timestamp strings?

**Comment by ADTC** [comment]
I would prefer if there was an explicit "timestamp" data type that could be used (so anyone looking at the property value would know it's a timestamp and not a random `long` number). Given that there's no such provision, I would have at least expected functions to convert the long into different string representations to be used in the `CREATE/MERGE/SET/RETURN` clauses. Similar to `TO_DATE` and `TO_STRING`.

**Comment by jexp** [comment]
For the time being you can use the apoc procedures for that: https://github.com/neo4j-contrib/neo4j-apoc-procedures#datetime-support
