### ISSUE TITLE
Dynamic reload of server extensions

### ISSUE THREAD

**Issue by iKlaus** [neo4j/neo4j#1812]
We'd built an extension which solves some performance issues in our scenario by providing custom REST-endpoints for critical tasks which then are implemented directly on the server. Works like a charm.

One thing however turned out to be a real annoyance: deploying new versions of the extension. Having to restart the server every time a new version is deployed takes a huge amount of time and empties all caches. Both are very inconvenient consequences in a high traffic environment.

I'd find it rather useful to have a switch on the init-script/neo4j binary to reload the extensions only, without affecting uptime or caches; like so:

``` sh
/etc/init.d/neo4j-service reload
```

I'm not a Java dev by any means, but heard of dynamic loading and unloading classes and that what I have in mind should be possible in theory. 

Maybe this is something you might consider implementing in the future.

**Comment by technige** [comment]
This has now been added to our internal system for discussion.
