### ISSUE TITLE
return query execution time

### ISSUE THREAD

**Issue by sovos** [neo4j/neo4j#1826]
figuring out precisely the execution time of queries can be a pain (and in the end just imprecise) if the command is executed via the REST option. should there be implemented a way to get execution time among the fields returned in a Cypher query?

**Comment by cybrwshl** [comment]
I have the exact same problem. And I wondered how the webinterface get the execution time of every transaction. Maybe its possible to extend the includeStats option to return the execution time.

**Comment by Izhaki** [comment]
+1

**Comment by technige** [comment]
Closing as execution timings have been now been available in Bolt result metadata for some time.
