### ISSUE TITLE
Make logback file location configurable

### ISSUE THREAD

**Issue by wouterv** [neo4j/neo4j#1827]
Currently it seems that the name of the logback configuration file needs to be "neo4j-logback.xml" and that it has to be on the classpath. 

This needs to be more flexible.

See also http://stackoverflow.com/questions/20346204/how-can-embedded-neo4j-have-a-custom-logback-file

**Comment by jakewins** [comment]
Recent releases of Neo4j has removed our logback configuration entirely, it now remains only to manage the http-logging, where the location of the config file is configurable.

**Comment by LostKali** [comment]
@jakewins so is it impossible to customize neo4j logging in version 3+?
