### ISSUE TITLE
extensions and /ext inconsistent?

### ISSUE THREAD

**Issue by gsummer** [neo4j/neo4j#1830]
neo4j-community 2.0
plugins installed: neo4j/community/server-examples/
further info & discussion: 
https://groups.google.com/forum/#!topic/neo4j/YKGAHHTEdvw

$ curl http://localhost:7474/db/data/
{
  "extensions" : {
    "GetAll" : {
      "get_all_nodes" : "http://localhost:7474/db/data/ext/GetAll/graphdb/get_all_nodes",
      "getAllRelationships" : "http://localhost:7474/db/data/ext/GetAll/graphdb/getAllRelationships"
    }
  } ...

and 

$ curl http://localhost:7474/db/data/ext
{
  "GetAll" : "http://localhost:7474/db/data/ext/GetAll",
  "ShortestPath" : "http://localhost:7474/db/data/ext/ShortestPath",
  "DepthTwo" : "http://localhost:7474/db/data/ext/DepthTwo"
}

show different results.

**Comment by jakewins** [comment]
As per the note in the linked ML chain, this is by design. GetAll is a global plugin, so is seen on `/db/data`, while `ShortestPath` and `DepthTwo` is a node plugin, so it will only show up if you look at node representations.
