### ISSUE TITLE
Support variable length relationship predicates

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#187]
@therubymug: 'Given the following graph:

```
John-Follows-Sarah 
John-Follows-Kyle 

Sarah-Follows-Derek 
Sarah-Follows-Kyle 
Sarah-Follows-Max

Derek-Follows-Andy
Derek-Follows-Pam
Derek-Follows-Kyle
```

I want all my 3rd degree friends to NOT show any friends I may already follow on previous degrees (1st and 2nd).

```
Expected Result: Andy, Pam
```

Ideally this would work (given I also want to check a 'status' property on the Follows Relationship):

    START me=node:users(name='John') 
    MATCH p=(me)-[rels:follows*3..3]-(degree3) 
    WHERE 
      ALL(f in rels WHERE f.status = 'connected')
      AND NONE(n in NODES(p) WHERE me-[:follows*1..2]->n) 
    RETURN degree3.name 

Unfortunately, Cypher doesn't _yet_ support variable-length relationship predicates.'

**Comment by maxdemarzi** [comment]
This is better handled now using NOT relationthips and with Triadic Selection introduced in 2.3. See http://neo4j.com/blog/neo4j-2-3-milestone-3-release/ . Closing.
