### ISSUE TITLE
Windows Service Installer fails when directory has space.

### ISSUE THREAD

**Issue by baardl** [neo4j/neo4j#1900]
Hi.

I've tried to install neo4j as windows service, on this path d:\Servers\Neo4j Community\neo4j-community-2.0.0. This fails with the error below.
Fix: Renamed dir to d:\Servers\Neo4j-Commuity\neo4j-community-2.0.0. Ie without any spaces. Then the installer worked ok.

Error message: 
D:\Servers\Neo4j Community\neo4j-community-2.0.0>bin\Neo4jInstaller.bat install
Press any key to continue . . .
DESCRIPTION:
        Creates a service entry in the registry and Service Database.
USAGE:
        sc <server> create [service name] [binPath= ] <option1> <option2>...

OPTIONS:
NOTE: The option name includes the equal sign.
      A space is required between the equal sign and the value.
 type= <own|share|interact|kernel|filesys|rec>
       (default = own)
 start= <boot|system|auto|demand|disabled|delayed-auto>
       (default = demand)
 error= <normal|severe|critical|ignore>
       (default = normal)
 binPath= <BinaryPathName>
 group= <LoadOrderGroup>
 tag= <yes|no>
 depend= <Dependencies(separated by / (forward slash))>
 obj= <AccountName|ObjectName>
       (default = LocalSystem)
 DisplayName= <display name>
 password= <password>
[SC] StartService: OpenService FAILED 1060:

The specified service does not exist as an installed service.

Hope this fix helps for other people too :-).
Bård

**Comment by jakewins** [comment]
Resolved in PR4433
