### ISSUE TITLE
Full text indexes in cypher

### ISSUE THREAD

**Issue by ghost** [neo4j/neo4j#1919]
Using neo 2.0.1, the query:

```
match (n:States)
where n.name =~ '.*rul.*'
return n.name order by n.name desc
limit 200
```

returns result after 14 secs. Number of n:States nodes is about 450 000, number of nodes fullfilling the condition is about 130 000 and count with the same condition returns in 1 sec. There is index on :States(name).

Profiling returns

```
ColumnFilter(symKeys=["n", "n.name"], returnItemNames=["n.name"], _rows=200, _db_hits=0)
Top(orderBy=["SortItem(Cached(n.name of type Any),false)"], limit="Literal(200)", _rows=200, _db_hits=0)
Extract(symKeys=["n"], exprKeys=["n.name"], _rows=131072, _db_hits=131072)
Filter(pred="LiteralRegularExpression(Property(n,name(1)),Literal(.*rul.*))", _rows=131072, _db_hits=458752)
       NodeByLabel(label="States", identifier="n", _rows=458752, _db_hits=0)
```

Now, this type of match is very common to all applications - table with filter and ordering, so performance is important.

This query probably doesn't use the index (because of the condition) but it should because of the order by.
When running this type of query in MSSQL, server works as follows:

Using index scan in descending order goes over every value and evaluates the condition. When number of items fulfilling the condition reaches 200 the work is done and result is returned. In many cases this happens in very short time (enough of items fulfilling the condition is found at the end of indexed items)

In  Neo4j with cypher, server probably sorts all items fulfilling the condition and then returns the 200 from the begining.

Is there some plan to optimize this type of queries?

Thanx and sorry, I'm new to Neo and GitHub :)

**Comment by jakewins** [comment]
That last point is because it scans up to the highest id that could exist in the node storage file, so it's taking that long because there's a big disk scan happening. We're working to make that not be a thing :) 

On the main part of this ticket: I'm going to treat this as a feature request for full-text indexes in Cypher, and mark it as such.

**Comment by LinneaAndersson** [comment]
I will close this issue as we have full text search index in all supported versions, see more here: https://neo4j.com/docs/cypher-manual/current/indexes-for-full-text-search/

Let us know if you have any other questions or feature requests, 
Linnéa
