### ISSUE TITLE
Add a specific error code for Deadlocks

### ISSUE THREAD

**Issue by aranm** [neo4j/neo4j#1922]
When executing cypher statements via the rest endpoint at the moment the only way to to detect a deadlock is to run code similar to this on the returned error:

```
var deadlockOccurred =  (error.code == "Neo.DatabaseError.Statement.ExecutionFailure") && (error.message.indexOf("deadlock") != -1);
```

There should be a specific error code returned when a deadlock occurs.

Personal opinion time:

It seems to me that the error returned

Neo.DatabaseError.Statement.ExecutionFailure

is to generic and it should actually be maybe a sub-error of

Neo.DatabaseError.Transaction.CouldNotCommit

**Comment by aseemk** [comment]
I just want to give you guys props for adding this, and more generally, the `TransientError` classification.

HTTP is great in differentiating 4xx client vs. 5xx server errors, but you guys really got it right by adding this third classification for known retryable errors.

We are now retrying these errors automatically in our app, and it has made a dramatic difference in reducing our user-facing error rate and internal-facing alert noise. (/cc and /ht @ryanwe for that.)

So thanks. =)
