### ISSUE TITLE
A bi-directional interface with Hadoop (use Membase as a property store)

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#195]
@espeed: 'See 
http://www.cloudera.com/blog/2011/02/an-emerging-data-management-architectural-pattern-behind-interactive-web-application/

A different variation...

Nathan Marz is the guy who built Storm for Twitter. A few weeks ago he posted an article "How to Beat the CAP Theorem" (http://nathanmarz.com/blog/how-to-beat-the-cap-theorem.html, http://news.ycombinator.com/item?id=3108087) where he proposes a batch + real-time mashup model, and uses Hadoop + ElephantDB for batch and Storm + Cassandra for real-time.

It would be interesting to see how to use Neo4j for the real-time piece, and then Hadoop for the batch processing piece. 

You could query Neo4j, and it would pull from its local store and combine it with the distributed portion using  a last-write-wins algorithm

In such a model, disk persistence on the Neo4j/graph DB side may not even be needed because everything is also persisted to the batch side so it eventually "catches up" after some processing delay. 

A few months back Jim Webber posted, "The holy grail of graph algorithms is to balance a graph across database instances by creating a minimum point cut for a graph, where graph nodes are placed such that there are few relationships that span shards. The trouble with this picture is that it's hard to achieve in practice, especially since connected graphs can mutate rapidly and unpredictably at runtime" (http://jim.webber.name/2011/02/16/3b8f4b3d-c884-4fba-ae6b-7b75a191fa22.aspx).

Keeping the distributed portion read only and not mutable would make finding and maintaining the minimum cut point easier. 

And if you were to regenerate the distributed portion once per day, you could keep the real-time portion in memory by using something like an event-sourcing Distruptor pattern (http://code.google.com/p/disruptor/) where "replaying a days worth of journals - takes less than a minute" (http://martinfowler.com/articles/lmax.html). 

Having the real-time portion in memory means you wouldn't have to contend with cloud disk IO so it would improve the write performance. 
'

**Comment by chrisvest** [comment]
Closing since our issue tracker is no place for recording such speculative ideas.
