### ISSUE TITLE
Cypher's ExecutionResult is traversable only once, but it is an Iterable - document this

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#20]
@wujek-srujek: 'I am using the ExecutionEngine / ExecutionResult classes form the 'javacompat' package. The following  code:
```groovy
        ExecutionResult res = new ExecutionEngine(graphDb).execute('start from = node({from}) match from-[:IS_PART_OF]->t return t', [from: node])
        println '> first traversal start'
        for (def o : res) {
            println o['t']
        }
        println '> first traversal end'
        println '> second traversal start'
        for (def o : res) {
            println o['t']
        }
        println '> second traversal end'
```
results in:
> first traversal start
Node[3]
> first traversal end
> second traversal start
> second traversal end

The second traversal (calling iterator() for the second time) yields an Scala iterator whose toString() method says 'empty iterator'.
On the other hand, when people see an Iterable, they most likely expect it to be traversable more than once. If some API, like this one, doesn't implement this, it must be documented.

I know this can be too late, but how about changing the result types to Iterator? This will mean it can be traversed only once and be clearly documented by the API itself.'

**Comment by jakewins** [comment]
The new `Result` cypher result in the core api is no longer `Iterable`.
