### ISSUE TITLE
Neo4j Browser - Display Node Properties (In addition to ID property)

### ISSUE THREAD

**Issue by andrewpugliese** [neo4j/neo4j#2004]
By default the browser application's stream (output) section only displays the ID properties of the nodes in the graph db. I have added several nodes with additional properties and relationships. When the graph is displayed in the stream window I only see default ID inside of the node pictures. When I click on the node a popup will show all my properties.
Currently you can only display node-property OR node-id as caption, use the popup dialog that shows when you click on a node or relationship.

Can you have neo4j display arbitrary amounts of properties and or id's.

**Comment by naisanza** [comment]
Followed the answer given here http://stackoverflow.com/a/35617249/2015890


> In browser version 2.0.1 graph you can click on the entity name at the top of the graph. At the bottom of the graph there becomes options for size of the circles/nodes and the color of the circle/nodes. Just to the right of that, the option is there to select a different property to display in the graph.

1. Click label
2. Select property to display
3. Save GRASS

![](http://imgur.com/c2XqLzj.jpg)

**Comment by oskarhane** [comment]
This is a very old issue we missed when we broke out neo4j-browser to it's own repo.
Feel free to open it in https://github.com/neo4j/neo4j-browser if the request still stands.
But I do not think we will display more than one property in a node in the viz in neo4j-browser.
Might be something for https://neo4j.com/bloom/ though.
