### ISSUE TITLE
Create relationship between nodes via the neo4j web browser

### ISSUE THREAD

**Issue by thomasfr** [neo4j/neo4j#2045]
At the moment it is not possible to create a single relationship from one node to another from within the neo4j web browser without cypher.
One possibility to do this would be to add marker when one hovers over a node. When clicking on this marker, all other visible nodes also get this marker added. after clicking on one of these markers the relationship type has to be entered. After pressing enter the relationship gets created and the corresponding cypher query gets displayed in the browser console.

**Comment by oskarhane** [comment]
This issue was moved to neo4j/neo4j-browser#124
