### ISSUE TITLE
Make the Groovy Script Engine engineReplacementDecision configurable

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#207]
@espeed: 'Right now the GSM engineReplacementDecision is hard coded to be recreated every 500 requests. 

However, there is no need to recreate it if clients are executing the same script every time, and recreating the GSM reduces performance because each script has to be recompiled every 500 requests.

The user should be configurable to set a config param for the engineReplacementDecision interval and be able to set it so that it never gets replaced.

I also added a ticket to the Groovy issue tracker to deal with the core problem: 
http://jira.codehaus.org/browse/GROOVY-5187'

**Comment by maxdemarzi** [comment]
engineReplacementDecision is no longer in the product.
