### ISSUE TITLE
Shortest Path and Timeout configuration

### ISSUE THREAD

**Issue by gm2012** [neo4j/neo4j#2080]
I am using Java API in an embedded graph (version 1.9.4) and using the following code to get the ShortestPath -
GraphAlgoFactory.shortestPath(expander, 15)
where expander is a expander with specific relationship types.

In rare cases, the graph (which is about 28 G on a JVM sized to 10G) just spins for more than 30 minutes. Is there a way to specify the timeout so that shortestPath query is cancelled?

**Comment by burqen** [comment]
@gm2012 You can set global transaction timeout with `dbms.transaction.timeout`. It was introduced in `3.0`.
