### ISSUE TITLE
PID file location and console.log location hardcoded in bin/neo4j, ignore configuration in conf/*

### ISSUE THREAD

**Issue by bonneau** [neo4j/neo4j#2103]
On _NIX platforms, the PID file location and console.log location are hardcoded in neo4j, ignoring the configuration options set in the various config and properties files in conf/*.  As a result, neo4j will fail to start if there isn't a data/ directory directly under $NEO4J_HOME, even if you've configured your graph data to live elsewhere.  It's minor, but it's confusing and creates a deployment annoyance.

**Comment by benbc** [comment]
The entire directory structure of Neo4j is being reworked for version 3.0. That will indirectly address the problems here. We don't currently plan to backport a fix to any of the 2.x series. Please reopen this issue if that's a problem.
