### ISSUE TITLE
More helpful HTTP Status Code

### ISSUE THREAD

**Issue by hhariri** [neo4j/neo4j#2104]
I'm trying to figure out the HTTP API and often times when sending incorrect requests, I'm getting status codes that don't really make sense. For instance:
1. When sending a request that does not set the Content-Type header, I'm getting method not allowed with an allow header of GET, HEAD. 
2. When sending a request for a query that does not contain params, I'm getting Internal Server Error.

I'd say in the case of the first it would be more helpful to send a 415 Unsupported media type.

And in the case of the second, a 400 Bad Request. In both cases, having some error message in the body would also be very useful. 

In my case it's creating nodes, but probably might apply to other types of queries too.

**Comment by technige** [comment]
Closing as this applies to a deprecated endpoint.
