### ISSUE TITLE
Ghost node

### ISSUE THREAD

**Issue by atorgfr** [neo4j/neo4j#2115]
I got a problem that i don't really understand why this is happen.

MATCH (n:USER) where n.email = 'email@hotmail.com' return count(n);
This return me 1.

MATCH (n:USER{email:'email@hotmail.com'}) return count(n);
This return me 1.

MATCH (n:USER) return count(n);
This return me 1150012.

MATCH (n:USER) where n.email <> 'email@hotmail.com' return count(n);
This return me 1150012.

Have you any idea why this can happen ?

Thx

**Comment by jakewins** [comment]
@jexp @atorgfr was there ever a resolution to this ticket?

**Comment by sherfert** [comment]
@jakewins Didn't get any reponse and we failed prior to that at offering timely support. Closing now, please reopen if needed.
