### ISSUE TITLE
Web UI navigator issues with large data sets

### ISSUE THREAD

**Issue by Vramin** [neo4j/neo4j#2134]
The web UI seems to be broken on the 2.0.1 and the 2.1.0.M01 releases. The label names highlight, but clicking them gets no response. I'm on OS X 10.8.5, seeing the same behavior with both Chrome and Safari. My 2.0.0 instances still work fine, but I was trying to use the newer versions with my newer graphs and it isn't working. In Safari the labels don't even highlight on mouseover, but they do in Chrome. Using the community version.

**Comment by jakewins** [comment]
I'm marking this partially as a browser feature request, in that the browser could give better feedback here - "loading" or something.

But mainly, this is about quality of service where these browser requests get crowded out by the other load. This will be resolved by our implementaiton of the new remoting protocol, Bolt, so I'm also marking this as a remoting issue.

**Comment by oskarhane** [comment]
This issue was moved to neo4j/neo4j-browser#125
