### ISSUE TITLE
Error building project

### ISSUE THREAD

**Issue by mihairaulea** [neo4j/neo4j#2177]
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:java (p
arse-cypherdoc) on project neo4j-cypher-docs: An exception occured while executi
ng the Java class. null: InvocationTargetException: Failed while executing file:
 uniqueness.asciidoc in the directory C:\tapitoo\neo4j\neo4j\community\cypher\do
cs\cypher-docs\target\docs\parsed-graphgists: PermGen space -> [Help 1]

**Comment by jakewins** [comment]
You need to increase the amount of RAM you give maven. See here for details: http://stackoverflow.com/questions/3101128/java-lang-outofmemoryerror-permgen-space-in-maven-build
