### ISSUE TITLE
Lucene index query exceptions not caught or described by ExecutionEngine

### ISSUE THREAD

**Issue by moxious** [neo4j/neo4j#2185]
ExecutionEngine and its execute method generally has the contract that it will return an ExecutionResult, or it will throw a CypherException.

When working with lucene indexes though, many different things can go wrong; certain malformed lucene query strings will result in NullPointerExceptions that propagate all the way up; this leaves the developer in a situation where there is no explanation why the query failed.  An example query which displays this behavior is when this query 

<pre>start n=node:node_auto_index({query}) return n limit 10;</pre>

When {query} is bound to the string 'name:foo~' (including the single ticks) this gets interpolated incorrectly, which seems to create a parse error, and a resulting NullPointerException.  Without the single ticks, it would work fine (reference/example:  https://stackoverflow.com/questions/22637914/overcoming-nullpointerexception-on-cypher-lucene-query) 

In other situations, when there is a known legitimate error in the lucene query syntax, the result is an org.apache.lucene.queryParser.ParseException, which gets re-thrown somewhere as a RuntimeException.

In both of these cases, I think a more appropriate behavior would be to throw a CypherException with an explanation of what went wrong.

More details and stack trace examples can be found here: https://groups.google.com/forum/#!topic/neo4j/viNBYECmg34

**Comment by sherfert** [comment]
I tried to reproduce your NullPointerException but I couldn't. I created the auto-index with `neo4j-shell` and then ran in the browser:

```
:params {query: "'name:foo~'"}
start n=node:node_auto_index({query}) return n limit 10;
```

Either this has been fixed in the last 3 years or I am doing something wrong. @moxious

**Comment by sherfert** [comment]
Closing now. Feel free to reopen if issue is still up to date.
