### ISSUE TITLE
Bug: /db/data/cypher doesn't return error for failed deletion

### ISSUE THREAD

**Issue by aseemk** [neo4j/neo4j#2197]
Though the new /db/data/transaction/commit endpoint does. Neo4j 2.0.1.

Setup: create a node that's connected to one or more other nodes. Mine happens to be labeled `User`.

Here's the Cypher query I'm running to attempt to delete this node while it's still connected to others:

``` cypher
MATCH (user:User)
WHERE ID(user) = {id}
DELETE user
```

If I simply paste this into the Neo4j browser (replacing `{id}`), I properly get back an error:

```
javax.transaction.HeuristicRollbackException: Failed to commit transaction Transaction(633, owner:"qtp841090834-124")[STATUS_NO_TRANSACTION,Resources=1], transaction rolled back ---> javax.transaction.xa.XAException
Neo.DatabaseError.Transaction.CouldNotCommit
```

And I can replicate this by going to the underlying transaction endpoint myself:

```
:POST /db/data/transaction/commit {"statements": [{"statement": "MATCH (user:User) WHERE ID(user) = {id} DELETE user", "parameters": {"id": 63}}]}
```

But if I go to the old(er) Cypher endpoint, it claims to succeed:

```
:POST /db/data/cypher {"query": "MATCH (user:User) WHERE ID(user) = {id} DELETE user", "params": {"id": 63}}
```

```
{
  "columns": [],
  "data": []
}
```

Is this a known issue with Neo4j 2.0? Is the old `/db/data/cypher` endpoint beyond deprecated and known to actually not work in some cases? Or is this just a bug that just slipped through the cracks?

Thanks!

**Comment by technige** [comment]
Closing as this only applies to a deprecated endpoint.
