### ISSUE TITLE
Database Upgrade - multiple backups not supported

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#220]
@Romiko: 'Hi,

I notice that if a DB Upgrade needs to be performed, it will try upgrade the database, but if there was already a backup of the DB from a previous upgrade, it then fails.

[WaWorkerHost.exe] 	at org.neo4j.server.Bootstrapper.main(Bootstrapper.java:52)
[WaWorkerHost.exe] Caused by: org.neo4j.kernel.impl.storemigration.StoreUpgrader$UnableToUpgradeException: Cannot proceed with upgrade because there is an existing upgrade backup in the way at C:\AzureTemp\neo4j-db\upgrade_backup. If you do not need this backup please delete it or move it out of the way before re-attempting upgrade.

I am wondering, would it not be better to have support for multiple backup folders.'

**Comment by fsperling** [comment]
As #2557 and #2526 show this issue is still causing problems.

Should there be support for multiple backups?
Or don't support it but add better error messages.

**Comment by tinwelint** [comment]
Neo4j no longer takes backup during store upgrade, which makes backup decoupled from upgrade. So this can be closed.
