### ISSUE TITLE
Support case insensitive regexps

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#222]
@systay: 're: http://docs.neo4j.org/chunked/snapshot/query-where.html#where-regular-expressions

Is there a way to use case insensitive regular expressions in Cypher where
clauses?

node.property =~ /foo.*/i

does not appear to work.

This would be a great addition to the language, if it's currently unsupported.'

**Comment by aseemk** [comment]
FYI I also ran into this a while back, and discovered (undocumented) that you can put `(?i)` into the regex itself to achieve this. Pull #4833 adds this documentation.

**Comment by chrisvest** [comment]
Thank you, @aseemk
