### ISSUE TITLE
declare the Index<T>.query() methods to throw ParseException

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#224]
@st-p: 'if the org.neo4j.graphdb.index.Index<T>.query() methods are passed malformed query expressions, they throw a RuntimeException as of 1.5.02M. in order to be able to catch the nested org.apache.lucene.queryParser.ParseException it would be desirable to have the query methods throwing the ParseException directly, since it is bad style to catch a general RuntimeException.'

**Comment by burqen** [comment]
This require a change in public API. Added to backlog for next major release, 4.0.
