### ISSUE TITLE
Feature request: Build-in authentication

### ISSUE THREAD

**Issue by hoffmaaxe** [neo4j/neo4j#2268]
I wish a authentication feature for the Neo4j server. Without authentication I only can restrict the access to the database, so that only daemons on the localhost has access. I can't serve the database to other host in the local network or internet.

At the beginning it would be nice to integrate a simple authentication like in the authentication plugin, which doesn't work anymore with Neo4j 2.0.2 (see neo4j-contrib/authentication-extension#25 and #2264).

**Comment by chrisvest** [comment]
We have authentication now. It's even enabled by default.
