### ISSUE TITLE
Remove or upgrade dependancy on jersey REST library

### ISSUE THREAD

**Issue by mangrish** [neo4j/neo4j#2272]
For some reason the neo4j community server has a dependancy on a REST library which I feel is problematic for two reasons:
1) The core server should be able to be wrapped by a REST interface rather than forcing the option.
2) Upgrades to the wrapping library (in this case the neo4j-rest-binding) now have to make compatible upgrades to both itself and this library creating a circular dependancy.

My proposal would be to remove the dependancy on jersey 1.x from the java-server project and migrate the code to the rest binding project. This code could then be governed under the same project and kept in line with upgrades (in this case to the new improved jax-rs 2.0 libraries).

The problematic pom is: https://github.com/neo4j/neo4j/blob/master/community/server/pom.xml

Upgrade of jersey library to 2.7 can be found on my fork of the 2.0 branch of the java-rest-binding project here: https://github.com/inner-loop/java-rest-binding/commit/3b6b4e06bc7205c651e15386d040cb8f0772ec56

The thread on upgrading the java-rest-binding is here: https://github.com/neo4j/java-rest-binding/issues/69

**Comment by technige** [comment]
Closing as issue is obsolete.
