### ISSUE TITLE
'identifier unknown' in ORDER BY when using UNION

### ISSUE THREAD

**Issue by jimading** [neo4j/neo4j#2308]
I have a graph with TAG-nodes and PERSON-nodes and run the following two queries:

```
MATCH (p:Person)-[r_ptq]->(tq:Tag)
WHERE tq.name IN ["soccer", "tennis", "basketball"]
RETURN DISTINCT (p) AS person, count(r_ptq) AS score, collect(tq.name) AS tags
ORDER BY score DESC 
LIMIT 10
```

and

```
MATCH (tq:Tag)-[r_tqt]->(t:Tag)
WHERE tq.name IN ["soccer", "tennis", "basketball"]
WITH DISTINCT t, sum(r_tqt.weight) AS weight
ORDER BY weight DESC
LIMIT 10
MATCH (t)<--(p:Person)
RETURN DISTINCT p AS person, sum(weight) AS score, collect(t.name) AS tags
ORDER BY score DESC
LIMIT 10
```

each of them runs without any error and returns 'person', 'score' and 'tags'.
Now, if i want to combine the results of both queries using UNION, i.e.

```
MATCH (tq:Tag)-[r_tqt]->(t:Tag)
WHERE tq.name IN ["soccer", "tennis", "basketball"]
WITH DISTINCT t, sum(r_tqt.weight) AS weight
ORDER BY weight DESC
LIMIT 10
MATCH (t)<--(p:Person)
RETURN DISTINCT p AS person, sum(weight) AS score, collect(t.name) AS tags
ORDER BY score DESC
LIMIT 10
UNION
MATCH (p:Person)-[r_ptq]->(tq:Tag)
WHERE tq.name IN ["soccer", "tennis", "basketball"]
RETURN DISTINCT (p) AS person, count(r_ptq) AS score, collect(tq.name) AS tags
ORDER BY score DESC 
LIMIT 10
```

I get 

```
Unknown identifier `weight`.
```

It seems like the identifier is only unknown within the ORDER BY statement. If I comment the ORDER BY statements, the combined query works but of course without ordering I don't get the desired results. It's really strange to me that this only happens when using the UNION statement but not for the individual queries when run independently.

Any clue on how to resolve this?

(by the way: in the second query I have to use a nested MATCH since I have a fairly large clustering coefficient and it would take too long without restricting the first MATCH results prior to the second MATCH condition.)

**Comment by sherfert** [comment]
Can you specify the version on which this is failing?

**Comment by sherfert** [comment]
I haven't been able to reproduce this on any of our supported versions. Can you add some more information? Maybe a small setup of nodes necessary to trigger that behavior? @jimading

**Comment by sherfert** [comment]
Closing this issue for now. Please reopen if this is still an issue.
