### ISSUE TITLE
Arbiter shows as role UNKNOWN in jmx

### ISSUE THREAD

**Issue by wouterv** [neo4j/neo4j#2369]
Master and slave have a nice name in High Availability attribute haRole in array InstancesInCluster, but arbiter is UNKNOWN instead of just "arbiter".

See screenshot.

![screenshot from 2014-05-05 16 51 01](https://cloud.githubusercontent.com/assets/616997/2879030/b170aa38-d464-11e3-9953-6c0265402709.png)

Master is shown correctly:
![screenshot from 2014-05-05 16 52 33](https://cloud.githubusercontent.com/assets/616997/2879051/e9783bda-d464-11e3-8c6f-5843a07b4304.png)

**Comment by martinfurmanski** [comment]
I don't know if this still is an issue, but it will not be fixed and it has been over 3 years, so I am closing it.
