### ISSUE TITLE
Detect database directory being moved/deleted at runtime, and fail gracefully

### ISSUE THREAD

**Issue by BHSDuncan** [neo4j/neo4j#2404]
If the data/ or graph.db/ directory is deleted, moved, or otherwise becomes inaccessible/unwritable, Neo4j does not notice or at least doesn't produce any obvious notifications (e.g. in the logs).  

Subsequent writes are lost without notification as well!

Currently the only way found to detect such an issue is to look in the "High Availability" attribute in Neo4j's JMX MBeans and see if "LastCommittdTxId" has been set to -1.

**Comment by chrisvest** [comment]
We now log an error when this happens. We'll keep the file handles open and the database running, however, so you have a chance to undo your mistake to the best of the ability of your operator and operating system.
