### ISSUE TITLE
HTTP endpoint feature request to support byte arrays

### ISSUE THREAD

**Issue by freeeve** [neo4j/neo4j#2405]
I need a good way to send byte arrays to Neo4j as parameters, rather than strings, and AFAIK there's no good way to do this short of an unmanaged extension. Perhaps this can be tied into one of the output formatting improvements that are being proposed for the HTTP endpoints, if they involve types or type wrapping.

**Comment by freeeve** [comment]
this can probably be closed with bolt coming in as an alternative... (at least for my use case)

**Comment by technige** [comment]
The Bolt server and driver now fully support byte arrays, so closing this ticket.
