### ISSUE TITLE
Inconsistent behaviour when missing cypher parameters

### ISSUE THREAD

**Issue by jayniz** [neo4j/neo4j#2423]
The responses when a parameter of a cypher query is missing are a little confusing. In all of the three following cases I would expect a `ParameterNotFoundException`, but I'm getting a different response for each query.

Let's take a query that uses `ORDER BY` but with a parameter missing:
```shell
curl -XPOST -d'{"query":"MATCH n WHERE n.foo={missing_param} RETURN n ORDER BY n.bar","params":{}}' -H'Content-Type:application/json' -H'Accept:application/json;xxstream=true;charset=UTF-8'  http://localhost:7474/db/data/cypher
```

Throws a `ParameterNotFoundException` as expected.

Now, if I take the same query but leave out the `ORDER BY` clause, I get a `BadInputException`:

```shell
curl -XPOST -d'{"query":"MATCH n WHERE n.foo={missing_param} RETURN n","params":{}}' -H'Content-Type:application/json' -H'Accept:application/json;xxstream=true;charset=UTF-8'  http://localhost:7474/db/data/cypher
```

If, however, I express the query differently:

```shell
curl -XPOST -d'{"query":"MATCH (n:Foo{bar:{missing_param}}) RETURN n ORDER BY n.bar","params":{}}' -H'Content-Type:application/json' -H'Accept:application/json;xxstream=true;charset=UTF-8'  http://localhost:7474/db/data/cypher
```
I just get an empty result set with _no exception_ whatsoever (tried it with 2.0.3).

**Comment by jakewins** [comment]
Verified that this has been resolved for the second case, but remains an issue in the first case. On 3.0.0-M01: 

`MATCH (n) WHERE n.foo={missing_param} RETURN n ORDER BY n.bar`

```
"errors" : [ {
  "code" : "Neo.ClientError.Statement.ParameterMissing",
  "message" : "Expected a parameter named missing_param"
} ]
```

`MATCH (n) WHERE n.foo={missing_param} RETURN n`

```
"errors" : [ {
  "code" : "Neo.ClientError.Request.InvalidFormat",
  "message" : "Expected a parameter named missing_param"
} ]
```

`MATCH (n:Foo{bar:{missing_param}}) RETURN n ORDER BY n.bar`

```
{
  "columns" : [ "n" ],
  "data" : [ ]
}
```

**Comment by jayniz** [comment]
:+1:

**Comment by Mats-SX** [comment]
This has since been fixed. You will however need to have (at least) one node for the `MATCH` to find, otherwise the parameter will never be checked for.
