### ISSUE TITLE
Validate grass file uploads to avoid graph display bork

### ISSUE THREAD

**Issue by majensen** [neo4j/neo4j#2464]
I ran into this same problem:
http://stackoverflow.com/questions/22049798/neo4j-2-0-1-graphstyle-grass-stylesheet-issue

but it seems that hacking the browser via dev tools is not the most graceful way to recover. If the uploaded grass is bad, I would think the browser would kick it back. 

Now, where is that Firefox manual...

**Comment by oskarhane** [comment]
This issue was moved to neo4j/neo4j-browser#126
