### ISSUE TITLE
[feature request] Cypher - syntax for extending maps

### ISSUE THREAD

**Issue by zaboco** [neo4j/neo4j#2473]
It would be useful to extend a map with other properties when returning results (or in WITH clauses, etc.). For example (using, for example `&` for extend operator)

```
match (n {name: 'node'}) return n & { id: id(n) }
```

would return `{ name: 'node', id: 15 }`

**Comment by boggle** [comment]
This is possible since 3.1: https://neo4j.com/blog/cypher-graphql-neo4j-3-1-preview/
