### ISSUE TITLE
dump issues

### ISSUE THREAD

**Issue by lbuczkow** [neo4j/neo4j#2491]
The following dump from a database (neo4j v.2.1):

```
begin
create constraint on (n:`Device`) assert n.`id` is unique
create constraint on (n:`User`) assert n.`id` is unique
create (_0:`Device` {`created`:1401616258184, `createdFrom`:"/192.168.1.21", `exchangeKey`:[-17, -114, 72, 100, -45, -62, 18, 122, 26, -10, -97, 71, 45, 89, -52, 8, 79, 77, -102, 14, -20, 104, -66, -46, -2, 24, -2, 60, 64, 14, -10, -39], ...
;
commit


```

is not a valid shell script. It should be:

```
begin
create constraint on (n:`Device`) assert n.`id` is unique;
create constraint on (n:`User`) assert n.`id` is unique;
commit
begin
create (_0:`Device` {`created`:1401616258184, `createdFrom`:"/192.168.1.21", `exchangeKey`:[-17, -114, 72, 100, -45, -62, 18, 122, 26, -10, -97, 71, 45, 89, -52, 8, 79, 77, -102, 14, -20, 104, -66, -46, -2, 24, -2, 60, 64, 14, -10, -39], ...
;
commit

```

Another issue is that exchangeKey originally of byte[] type cannot be cast into byte[] again after restoring database from the dump.

**Comment by jexp** [comment]
This should be fixed with https://github.com/neo4j/neo4j/pull/6481

Only schema await is not part of that.

And unfortunately cypher doesn't know byte-arrays (yet) and it is hard to express them as JSON even as shell parameter.

**Comment by jjaderberg** [comment]
With the `db.schemaAwait()` procedure I consider this resolved. The request for byte array support in Cypher is tracked elsewhere.
