### ISSUE TITLE
Provide pure JTA XAResource implementation

### ISSUE THREAD

**Issue by ALRubinger** [neo4j/neo4j#2522]
Full explanation and comments here:

  https://stackoverflow.com/questions/23824518/how-to-enlist-xaresource-with-existing-transaction

I'd like to enlist Neo4j as a resource with an existing JTA Transaction, and not use its internal TransactionManager implementation.  My current solution on StackOverflow above involves wrapping an existing TM in Neo's, like so:

```
// Create the DB
        final GraphDatabaseService graphDatabaseService = new GraphDatabaseFactory().
                newEmbeddedDatabaseBuilder(FILE_NAME_STORAGE).setConfig(
                GraphDatabaseSettings.tx_manager_impl.name(),
                Neo4jExternalTransactionManager.Provider.NAME)
                .newGraphDatabase();

        final TransactionManager tm = ((GraphDatabaseAPI) graphDatabaseService).getDependencyResolver().
                resolveDependency(TransactionManager.class);
```

What I'd like to do instead is simply enlist an XAResource implementation for Neo4j with my JTA Transaction.

Comments and questions welcomed.

**Comment by klaren** [comment]
`TransactionManager` was rewritten and sadly, `XAResource` were not part of that change. Do you still want this feature or could we close the issue?
