### ISSUE TITLE
Timeout for large LOAD CSV

### ISSUE THREAD

**Issue by jmatsushita** [neo4j/neo4j#2525]
Hi there,

I'm trying to launch this cypher query.
```
LOAD CSV FROM 'https://raw.githubusercontent.com/iilab/openoil/master/data/BP%20Dataset%202014.05.28%20%28Full%20AR2013%20Scrape%20-%20edited%29%20-%20Sheet1.csv' AS line
MERGE (c:Company { name: line[0], ID: line[6], sourceURL: line[7], sourcePubDate: line[9]})
MERGE (p:Company { name: line[2]})
MERGE (j:Country { name: line[4]})
MERGE (conf:Confidence { level: line[8]})
MERGE (c)-[dir:DIRECT { immediate: line[1]}]->(p)
MERGE (c)-[jur:JURISDICTION]->(j)
MERGE (c)-[con:CONFIDENCE]->(conf)
```

Both on a local and server install it sometimes gets stuck on 'Executing query' and the spinner, and sometimes displays 'Unknown Error'.

See screen shot below where it worked after trying 3 times then failed again. 

![image](https://cloud.githubusercontent.com/assets/356097/3203833/ac6dcbd2-eda1-11e3-8860-47dff49b8f03.png)

Since it succeeded after 42 seconds on that 4th time, it's probably a timeout or memory issue but the error message is not helping. Is there a server configuration that could help?

Cheers,

Jun

**Comment by oskarhane** [comment]
This issue was moved to neo4j/neo4j-browser#127
