### ISSUE TITLE
Problem using LOAD CSV with custom FIELDTERMINATOR (2.1.1)

### ISSUE THREAD

**Issue by DenisVuyka** [neo4j/neo4j#2548]
When using LOAD CSV with custom FIELDTERMINATOR (for instance | symbol) execution crashes when any of the row values contains double quotes symbol. Should I expect neo4j doing character escaping transparently or this is something for client application to handle?

**Comment by sherfert** [comment]
Can you provide a reproducible minimal example? Both a CSV file and the CYPHER query executed would be nice.

**Comment by DenysVuika** [comment]
The issue was created on 10 Jun 2014, I gave up already since that time.
