### ISSUE TITLE
NOT is not parsed properly when nested inside expressions without parentheses

### ISSUE THREAD

**Issue by davidegrohmann** [neo4j/neo4j#2556]
To reproduce just try to parse:

RETURN true = not(42 = 32)

it will fail since NOT is parsed as a function invocation rather than the boolean negation operator.

**Comment by jakewins** [comment]
Verified that this remains an issue: http://console.neo4j.org/r/zcjuk8

**Comment by cleishm** [comment]
Hard to fix this, due the precedence approach (`not` is higher precedence than `=`, so it's not expected on the rhs). `true = (not (42 = 32))` is the workaround.

**Comment by OliviaYtterbrink** [comment]
Given the OpenCypher grammar this is the intended behaviour. Any request to change this should be directed to https://github.com/opencypher/openCypher

**Comment by davidegrohmann** [comment]
Can we at least provide a decent error message?

**Comment by cleishm** [comment]
@davidegrohmann That should be easy enough. If the AST ends up with a function named 'not', then it's an error.

**Comment by OliviaYtterbrink** [comment]
That we should be able to do
