### ISSUE TITLE
Better error message for failed ORDER BY with non-grouped variable

### ISSUE THREAD

**Issue by bruth** [neo4j/neo4j#2591]
I ran the following query and it resulted in an `InvalidSyntax` exception with a message `Unknown identifier 'b'`:

```cypher
MATCH ({`origins:uuid`: '6126a7db-3bb7-4ed9-a3b7-9190150da383'})<--(b:`prov:Bundle`)-->(e:`prov:Event`)-->(a)
RETURN e, labels(e), collect(a)
ORDER BY b.`origins:timestamp`
```
At first glance it confused me, but then I realized the `collect` is performing an implicit group by. Knowing how SQL GROUP BY works, I understood why `b` was not be *defined* since you cannot ORDER BY a value that has been selected/returned.

I recommend adding a better error message, e.g `Cannot ORDER BY grouped rows with non-returned identifier: 'b'`

**Comment by jakewins** [comment]
This has been resolved as per: http://console.neo4j.org/r/wjhlux
