### ISSUE TITLE
server start fails if rrdb.location dir is not present

### ISSUE THREAD

**Issue by seventwenty** [neo4j/neo4j#2594]
neo4j server does not start up and does not provide a helpful (console.log) message in case the servers _round-robin_ database directory does not exist.

Details to reproduce the issue:
0. preconditions
* (OS is ubuntu 14.04)
* neo4j server working directory is /var/lib/neo4j
* neo4j server has correct access rights for /var/lib/neo4j
1. open neo4j configuration (/etc/neo4j/neo4j-server.properties)
2. org.neo4j.server.database.location=data/graph.db (default)
3. change org.neo4j.server.webadmin.rrdb.location to some subdirectory that does not exist, e.g. data2, that it reads  org.neo4j.server.webadmin.rrdb.location=data2/rrd
4. start neo4j  # /etc/init.d/neo4j-service start

I get the message "Failed to start within 120 seconds. Neo4j Server may have failed to start, please check the logs.
The console.log isn't very helpful as well since it tells me "Successfully started database" (see below)

I figured out that the bug occurs only if 
* org.neo4j.server.webadmin.rrdb.location contains a subdirectory that does not exist AND
* org.neo4j.server.database.location is a different directory, i.e. graph.db and rrd are configured to be in different directories.  

In case one changes the configuration to
org.neo4j.server.database.location=data2/graph.db
org.neo4j.server.webadmin.rrdb.location=data2/rrd
/var/lib/neo4j/data2/graph.db and /var/lib/neo4j/data2/rrd are created and the server starts up. It seems that when attempting to create the round robin database, subdirectories can not be created? 

console.log:
19:04:00,818 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
19:04:00,819 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
19:04:00,819 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/usr/share/neo4j/system/lib/neo4j-server-2.1.2.jar!/logback.xml]
19:04:00,820 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
19:04:00,820 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/usr/share/neo4j/plugins/dmp-graph.jar!/logback.xml]
19:04:00,820 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/usr/share/neo4j/system/lib/neo4j-server-2.1.2.jar!/logback.xml]
19:04:00,834 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@29e54f45 - URL [jar:file:/usr/share/neo4j/system/lib/neo4j-server-2.1.2.jar!/logback.xml] is not of type file
19:04:00,919 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
19:04:00,923 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
19:04:00,928 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
19:04:00,944 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
19:04:00,986 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
19:04:00,986 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
19:04:00,987 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
19:04:00,988 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@db75080 - Registering current configuration as safe fallback point

2014-06-20 17:04:01.306+0000 INFO  [API]
				Setting startup timeout to: 120000ms based on -1
2014-06-20 17:04:04.553+0000 INFO  [API]
				Successfully started database

**Comment by jakewins** [comment]
RRD has been removed as per https://github.com/neo4j/neo4j/commit/9dac34dd2d6c5d05ee40ef1fda71fac522e2e4ed
