### ISSUE TITLE
Feature request: Consistency checks in Community Edition

### ISSUE THREAD

**Issue by albertoperdomo** [neo4j/neo4j#2619]
Consistency is extremely important. Community Edition does not include the consitency check tool, thus users of Community Edition are left with no method to check if their store is consistent or not.

I understand that this is currently a feature that is tied to the hot backups, but it the consistency check tool could be included so that it could be run against the local store directory.

We have seen the importance of this after [2.1.2 was released and users were encouraged to use the tool](http://neo4j.com/blog/neo4j-2-1-2/) included in the evaluation version of Enterprise to check the consistency of stores upgrade with version 2.1.2.

Consistency should not optional, this this tool should be present in both editions.

**Comment by jakewins** [comment]
Consistency check is now properly included in Community edition.
