### ISSUE TITLE
Feature request: Run consistency check on server start, before / after store upgrade

### ISSUE THREAD

**Issue by albertoperdomo** [neo4j/neo4j#2620]
Related to #2619.

Rationale: If a store is inconsistent the user should find out ASAP. The last thing you want if to find out after a long period of time, and after entering more data.

While users of Enterprise Edition can find out about eventual inconsistencies every time they take a backup, users of Community Edition don't have this option.

Following scenarios are ideal situations to check for consistency:
- Start: Prevent the user from storing additional data in a store which has been corrupted
- Store upgrade: Prevent user from upgrading a corrupt store to a new version to avoid (not sure if this is done ATM)

I'm aware that a check can take very long if the store is large. Ideas:
- Use a flag in config to enable/disable
- Make a copy of the store and run the check in parallel
- ?

**Comment by chrisvest** [comment]
The consistency checker takes a long time to run, so I can't imagine we'd ever want to do it on startup. At some point we'd like to make store upgrade an explicit neo4j-admin command (at least we've been contemplating this) and it would make sense to add it as an option there. Online backup has now had flags for consistency checking for a while, so Enterprise customers can do this today by just taking backups more often. To narrow the window further, it'd be better to be able to run the consistency checker while the database is online and serving transactions.

**Comment by albertoperdomo** [comment]
Hey @chrisvest ! Thanks for looking at this old issue!

>The consistency checker takes a long time to run, so I can't imagine we'd ever want to do it on startup.

Agreed.

>At some point we'd like to make store upgrade an explicit neo4j-admin command (at least we've been contemplating this) and it would make sense to add it as an option there.

Explicit store upgrades seems good to me. I could also imagine having a config var that allows/disallows implicit store upgrades.

>Online backup has now had flags for consistency checking for a while, so Enterprise customers can do this today by just taking backups more often.

Makes sense.

>To narrow the window further, it'd be better to be able to run the consistency checker while the database is online and serving transactions.

This would be ideal. Is this feasible? The consistency check itself is pretty resource intensive, I don't know about the side effects it could have on a server running in parallel on the same instance.

Look forward to see what you end up implementing.

**Comment by chrisvest** [comment]
@albertoperdomo We had a discussion about this internally, and because of the capabilities of online backup, we decided to not prioritise this for the time being 😕

**Comment by albertoperdomo** [comment]
@chrisvest Understand! ¯\_(ツ)_/¯

**Comment by klaren** [comment]
As the suggestion to have the consistency checker run online is not related to the issue, would you mind us closing it?

If you want to run the consistency checker before starting this could be done manually or through a script:
```
./neo4j-admin check-consistency && ./neo4j start
```
since the consistency checker is bundled with the server.

**Comment by albertoperdomo** [comment]
>As the suggestion to have the consistency checker run online is not related to the issue, would you mind us closing it?

OK, with me.
