### ISSUE TITLE
SocketHandler logging

### ISSUE THREAD

**Issue by gerhard** [neo4j/neo4j#2637]
I'm running 2.0.3 and would like to forward all logs to papertrail. This is my logging.properties file:

```
handlers=java.util.logging.SocketHandler
.level=INFO
java.util.logging.SocketHandler.host=logs.papertrailapp.com
java.util.logging.SocketHandler.port=11111
java.util.logging.SocketHandler.formatter=java.util.logging.SimpleFormatter
```

I cannot see any logs appearing in papertrail. Has anyone configured this successfully?

**Comment by chrisvest** [comment]
We now use a custom logging infrastructure that we would like to keep as simple as possible. I suggest that you have a separate program that reads the log files and ships the entries where you want them.
