### ISSUE TITLE
Refer to results of Cypher query in subsequent query using Batch API

### ISSUE THREAD

**Issue by stephenmuss** [neo4j/neo4j#2641]
Using the batch API it would be extremely useful to be able to refer to the results of one Cypher query in a following query.

Is this something that would be technically possible? It would make for a very valuable feature.

This would make it possible to break down complex Cypher queries into several smaller queries while keeping HTTP overhead to a minimum.

**Comment by jakewins** [comment]
Sorry to follow up so long after this was initially opened, but we're somewhat exploring this now, albeit not for the batch API. 

Could you expand on what use cases you had in mind where this would be helpful?

**Comment by stephenmuss** [comment]
It has been quite a while now so I can't remember the exact use I had for this. However I think I was hoping to be able to find and create nodes in earlier queries while being able to refer to them in subsequent ones. All within the same batch.

**Comment by chrisvest** [comment]
This would require keeping potentially large volumes of state around for a feature that I would imagine would be hardly ever used. I suggest you instead extract the state you need, and return it in the subsequent query as parameters. The `UNWIND` clause might be helpful here.
