### ISSUE TITLE
relationships(path) showing empty results in the browser text results

### ISSUE THREAD

**Issue by whatSocks** [neo4j/neo4j#2676]
Here is the same query run in the browser and the webadmin console:

In the graphical display you can see the two relationships as expected:

![screen shot 2014-07-14 at 9 41 13 am](https://cloud.githubusercontent.com/assets/2731744/3571393/f6a336b4-0b5c-11e4-8de8-06a25736003e.png)

But there's nothing when you want to see the text version:

![screen shot 2014-07-14 at 9 41 21 am](https://cloud.githubusercontent.com/assets/2731744/3571404/0a50910c-0b5d-11e4-830c-3094f06f292c.png)

Double-checking to see if there is in fact a text version, the same query has results in the webadmin:

![screen shot 2014-07-14 at 9 41 59 am](https://cloud.githubusercontent.com/assets/2731744/3571407/15f0b32a-0b5d-11e4-980e-5c43ef21a3d7.png)

**Comment by oskarhane** [comment]
This issue was moved to neo4j/neo4j-browser#128
