### ISSUE TITLE
Missing backup manpage in deb

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#268]
@nawroth: 'All other manpages show up in the system after installing the corresponding package, but the backup manpage is missing in the enterprise package.'

**Comment by davidoliverSP2** [comment]
Comment from @jennyowen:

`man neo4j-admin` tells you to check `neo4-admin help`.
`neo4-admin help` says you can do `neo4j-admin help <command>` to get more details on subcommands. Which seems to be true for backup.

I checked this on ubuntu 16.04, against the latest released 3.4.

-------

Closing issue.
