### ISSUE TITLE
MATCH (u:User)-[r]-(t) RETURN u.id isn't a superset of MATCH (u:User)-[r]-(t:Timeslip) RETURN u.id? 

### ISSUE THREAD

**Issue by whatSocks** [neo4j/neo4j#2693]
Reposted from https://github.com/neo4j-contrib/rabbithole/issues/77

I understand that 

`MATCH (u:User)-[r]-(t) RETURN DISTINCT u.id` should return a superset of `MATCH (u:User)-[r]-(t:Timeslip) RETURN DISTINCT u.id`, but this seems to be not happening:

```
neo4j-sh (?)$ match (u:User)-[r]-(b) return distinct u.id;
==> +--------+
==> | u.id   |
==> +--------+
==> | 220192 |
==> | 256746 |
==> | 264374 |
==> +--------+
==> 3 rows
==> 18 ms
neo4j-sh (?)$ match (u:User)-[r]-(b:Timeslip) return distinct u.id;
==> +--------+
==> | u.id   |
==> +--------+
==> | 236985 |
==> | 283070 |
==> | 273840 |
==> | 208398 |
==> | 208401 |
==> | 262101 |
==> | 279178 |
==> | 235911 |
==> | 208400 |
==> | 268785 |
==> | 208399 |
==> | 264374 |
==> | 220192 |
==> | 256746 |
==> +--------+
==> 14 rows
==> 1010 ms
```

The first one stops working after 18 ms and returns too few Users, the second works for 1010 ms and returns 14 users. 

Why the difference? 

The fix was to delete the `graph.db/schema/labels`

Possible steps to create this error:

I have a script that (in this order) creates constraints for users and timeslips (and other things), creates users, then creates timeslips and connects them to users. All is via REST.

What may have happened - I was populating graph cancelled the script with control+c pretty quickly, so I could have been in the users part. I then tried to delete the contents of the database using cypher, but got an error (something about rollback). Then I repopulated the graph using the same script.

**Comment by jakewins** [comment]
Closed as the inconsistency error has been resolved. Please reopen if you see this issue on a later version of Neo4j.
