### ISSUE TITLE
'Node concurrently deleted while loading its relationships' error when issuing concurrent 'delete all' Cypher query

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#27]
@blevine: 'Environment:
  Neo4j Communit 1.8GA
  Ubuntu 12.04
  Oracle JDK 1.6.0_32-b05
  Node.js/node-neo4j driver

This problem is most likely related to issue [#872](https://github.com/neo4j/community/issues/872). After running a similar test for a while, I see the following error:

```
"Node[1877] concurrently deleted while loading its relationships?"
```

as a result of the following 'delete all' query:

```
start n = node(*) match n-[r?]-() delete r,n
```

At this point all attempts to execute that query (both programmatically and from the Data Browser) result in the same error. Nothing appears in the log related to this error.

I then went to the Data Browser and was able to view Node 1877 although all of its properties had been deleted.  I then restarted the server after which Node 1877 disappeared (according to the Data Browser).  I was then able to issue the 'delete all' query successfully.'

**Comment by jakewins** [comment]
This was a bug in transaction state management in 1.8, it has since been resolved.
