### ISSUE TITLE
Neo4j Install Error on RedHat Linux

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#270]
@Muzaknut: 'Problem:

Trying to install neo4j as a service on Red Hat Linux per documentation at 
http://docs.neo4j.org/chunked/1.6/server-installation.html#_linux_service
but getting the "command not found" error below:

[pharos_priv_user@pdevdv1db128]$ sudo ./bin/neo4j install
Graph-like power should be handled carefully. What user should run Neo4j? [neo4j]
/opt/neo4j-enterprise-1.6/bin/neo4j: line 349: update-rc.d: command
not found

Is update-rc.d command specific to Ubuntu distribution?
If so, how can neo4j service be installed on RedHat?

Environment:

Red Hat Enterprise Linux Server release 5.6 (Tikanga)
Neo4j - Graph Database Kernel 1.6 (Enterprise)
java version "1.6.0_25"
Java(TM) SE Runtime Environment (build 1.6.0_25-b06)
Java HotSpot(TM) 64-Bit Server VM (build 20.0-b11, mixed mode) 
'

**Comment by benbc** [comment]
The install functionality in the `neo4j` script has been removed in favour of distro-specific packages.
