### ISSUE TITLE
Saved Scripts in Web UI Issue

### ISSUE THREAD

**Issue by edschembor** [neo4j/neo4j#2713]
So I'm not sure if this would could as a feature request or an issue. 

If you run a saved script in the Web UI and then cntrl-up to grab it from your history of searches, it no longer appears as a saved search. ie) the star is no longer gold and saving it creates a copy as opposed to overwriting. 

Pretty new to Neo4j, but I want to get involved with development so I'll try to look into the issue myself

**Comment by oskarhane** [comment]
This issue was moved to neo4j/neo4j-browser#129
