### ISSUE TITLE
Performance degrades for COUNT as the Label index size grows

### ISSUE THREAD

**Issue by bradnussbaum** [neo4j/neo4j#2754]
Using Neo4j 2.1.2 with WARM cache for each.

First test with 10,000 nodes.
MATCH (n:Movie) RETURN COUNT(n);
Returns in 67ms

Second test with 100,000 nodes.
MATCH (n:Movie) RETURN COUNT(n);
Returns in 169ms

Third test with 1,000,000 nodes.
MATCH (n:Movie) RETURN COUNT(n);
Returns in 560ms

With a COLD cache, above 1M nodes, the queries start around 5s and increase from there.

**Comment by alexpetroaica** [comment]
Any updates on this? COUNT queries are still very slow in 2.3.5. I am running the following query on a database with 5 million users for user "x" which has all other 5 million users following them and the query takes 5000ms. Are there any alternatives to using COUNT in this case?

MATCH (follower)-[r:FOLLOWS]->(followed:User {guid: "x"}) RETURN COUNT(r)

**Comment by jexp** [comment]
Yes, label / rel-type count queries are instant in 3.x.

The query you have will be very fast if you rewrite it to:

`MATCH (followed:User {guid: "x"}) RETURN SIZE( ()-[:FOLLOWS]->(followed) ) as follows`

As it will actually not load and count the relationships but read the degree of the node of this type and direction.

**Comment by chrisvest** [comment]
As Michael says, we now resolve these queries using the counts store whenever possible.

**Comment by HassanHashemi** [comment]
thanks to @jexp i came up with this query:

 `Match (t:Tag)-[:TAGS]->(:Music)<-[:TAGS]-(t2:Tag) `
`       Where t.TageID = 610 and t2.Type = 1`
`            with Size( (t2)-[:TAGS]->(:Music) )	as size, t2`
`    		return DISTINCT	   t2.Tage		as tag,`
`			  size 		as degree`
`					order by degree desc`
`                	Limit 10; `

this query is very slow when :Music is present in "sizeof" operator, however if i remove :Music from there it runs very fast.
my requirement is to have :Music in there.
any ideas?
(i want all the tags related to a tag via a music and sort them by number of music connected to it.)
