### ISSUE TITLE
Provide a way for validating Cypher queries

### ISSUE THREAD

**Issue by gunnarmorling** [neo4j/neo4j#2766]
There should be an API for validating that a given Cypher query is syntactically correct, without actually executing it.

This was originally [brought up](https://groups.google.com/forum/#!topic/neo4j/a95sdLS4gfM) in the user group.

**Comment by jakewins** [comment]
The browser now transparently runs `EXPLAIN <statement>` as a statement is written, and provides hints about issues with it as warning markers in the margin. If you are not using the browser, or if you want more detail than the browser gives automatically, manually running `EXPLAIN` is the suggested approach to doing this - it tells you if the statement is syntactically correct, and provides warnings if you are, for instance, doing things that causes cypher to make the query eager (loading the entire working set into RAM) or if you are using deprecated aspects of cypher.
