### ISSUE TITLE
[Feature Request] Compound indexes

### ISSUE THREAD

**Issue by conker84** [neo4j/neo4j#2825]
Hy guys,
i have learned that neo4j doesn't support compound indexes.
Is it possible to open a feature request?

Something like that:

``` cypher
CREATE CONSTRAINT ON (n:Person) ASSERT n.name, n.title IS UNIQUE
```

Thanks

**Comment by chrisvest** [comment]
We now have this in 3.2 in the form of `NODE KEY`s: https://neo4j.com/docs/developer-manual/3.2/cypher/schema/constraints/#query-constraint-node-key
