### ISSUE TITLE
Neo4J's Rest API returns 404 Not Found on relationship url for existing node in Batch.

### ISSUE THREAD

**Issue by skormos** [neo4j/neo4j#2837]
I'm writing a batch job to POST to /db/data/batch in Neo4J a la the documentation here: http://docs.neo4j.org/chunked/2.0.4/rest-api-batch-ops.html.

I'm creating a Node via a POST operation, then creating a relationship via POST from a previously existing node, to the one created in the batch. Neo4J returns a 404 - Not Found on the relationship URL for the previously existing Node.

Here's the request:

``` javascript
[ {
    "method" : "POST",
    "to"     : "/node",
    "id"     : 0,
    "body"   : {
      "entityType"  : "TimeOff",
      "start"       : "2014-08-13",
      "end"         : "2014-08-13",
      "status"      : "Approve",
      "reqId"       : 13579
    }
  }, {
    "method" : "POST",
    "to"     : "/node/1234/relationships",
    "id"     : 1,
    "body"   : {
      "to"   : "{0}",
      "type" : "REQUEST"
    }
  }
]
```

If I repeat this via SSH and cURL, it works without issue. Same database server, and same application server. The 404 seems to result from "/node/1234/relationships", even though cURL GETs to "/node/1234" and "/node/1234/relationships/all" work fine, as well as a POST via cURL.

I feel like there is something wrong with the server that is causing a 404, maybe due to a time-out or similar. Is this possible?

**Comment by technige** [comment]
Closing old thread. Please reopen if still an issue.
