### ISSUE TITLE
Make it easy to store list properties

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#294]
@espeed: 'Probably do this by either exposing utils that convert the JSON-converted ArrayList to an Object[], or convert all valid list params automatically.

See https://groups.google.com/d/topic/neo4j/sjH2f5dulTQ/discussion

But as it is now, with no way to store server-side scripts, including the conversion code in the Gremlin script on each request would seriously bloat the number of bits sent per request and be a PITA for users.
- James'

**Comment by burqen** [comment]
Hello! Going over old issues. Sorry for the super late answer.
Adding automatic value conversion magic does not seem like the correct way to handle this.
Suggested approach is to convert to a string array or decompose array into nodes and relationships, depending on use case.
Thank you for reporting!
