### ISSUE TITLE
Feature request: complex patterns with commas in MERGE

### ISSUE THREAD

**Issue by bossie** [neo4j/neo4j#2973]
I've described the original issue at  [stackoverflow.com](http://stackoverflow.com/questions/25601380/neo4j-merge-with-comma-in-pattern-throws-invalid-syntax-unlike-match-or-crea).

CREATE and especially MATCH support more or less complex patterns that can't be written without breaking up the pattern into multiple parts, separated by commas. This is due to the one-dimensional nature of a line of text used to describe the pattern in Cypher.

For example, in order to get my mom, dad and brother I have to split up the pattern and repeat the node identifier (me):

```
MATCH (dad)<-[:FATHER]-(me { Name: 'Jan'})-[:MOTHER]->(mom), (me)-[:BROTHER]->(brother)
RETURN mom, dad, brother;
```

I expected that MERGE would allow for the same syntax, but it does not: it returns an error:

```
Invalid input ',': expected whitespace, a relationship pattern ...
```

I can't split up the pattern into multiple MERGEs because that would give different results (either the _whole_ pattern matches or it doesn't).

Can this be supported?

Thanks,
Jan

**Comment by gilbert** [comment]
I just ran into the need for something like this. I have three existing entities: an exam, question, and student. I want to create an answer that has a relationship with all three, but only if one does not already exist.

I tried the multiple MERGE workaround, but that ended up relating a single answer to multiple questions:

![bad-graph](https://cloud.githubusercontent.com/assets/17013/10353142/ac85dc10-6d19-11e5-923a-1b7e88abe07c.png)

I'm fairly new to cypher. Are there any other workarounds I can use?

**Comment by jexp** [comment]
Best to ask the question on stackoverflow.

If you create an answer it has no relationships yet :)

If you take an existing answer you can just filter before you do the merge

```
MATCH (a:Answer {id:23})
WHERE size((a)-[:ANSWER_TO]->()) = 0
MATCH (e:Exam {id:12})
MATCH (q:Question {id:13})
MATCH (s:Student {id:14})
MERGE (a)-[:ANSWER_TO]->(e)
MERGE (a)-[:ANSWER_TO]->(q)
MERGE (a)-[:ANSWER_TO]->(s);
```

**Comment by gilbert** [comment]
Thanks for the response. For the record, this won't work for me because the answer's id is unknown; it may or may not exist. You can think of an answer's id as a composite key between an exam, question, and student.

**Comment by jexp** [comment]
Try this:

```
MATCH (e:Exam {id:12})
MATCH (q:Question {id:13})
MATCH (s:Student {id:14})
OPTIONAL MATCH (q)-[:ANSWER_TO]->(a)-[:ANSWER_TO]->(e),(a)-[:ANSWER_TO]->(s)
WITH a,e,q,s
WHERE a is null
MERGE (q)<-[:ANSWER_TO]-(a)-[:ANSWER_TO]->(e)
MERGE (a)-[:ANSWER_TO]->(s);
```

**Comment by gilbert** [comment]
Thank for the suggestion! This is the query that ended up working, which is an acceptable workaround to the topic of this issue:

```
MATCH (user:User), (exam:Exam), (question:Question)
WHERE id(user)     = {userId}
  AND id(exam)     = {examId}
  AND id(question) = {questionId}

OPTIONAL MATCH
  (existing:Answer)-[:ANSWER_TO]->(question),
  (existing:Answer)-[:ANSWERED_BY]->(user),
  (existing:Answer)-[:ANSWER_FOR]->(exam)

WITH user, exam, question, existing
WHERE existing IS NULL

CREATE
  (answer:Answer)-[:ANSWER_TO]->(question),
  (answer:Answer)-[:ANSWERED_BY]->(user),
  (answer:Answer)-[:ANSWER_FOR]->(exam)

RETURN answer
```

**Comment by gilbert** [comment]
For the record, the query I posted isn't good; if you send off two of these queries simultaneously, then two answers will get created.

**Comment by akopchinskiy** [comment]
@cleishm Any related changes after 6 years?

**Comment by philastrophist** [comment]
Doesn't look like it. This issue is why I can't use neo4j at the moment

**Comment by cosmeowpawlitan** [comment]
> Best to ask the question on stackoverflow.
> 
> If you create an answer it has no relationships yet :)
> 
> If you take an existing answer you can just filter before you do the merge
> 
> ```
> MATCH (a:Answer {id:23})
> WHERE size((a)-[:ANSWER_TO]->()) = 0
> MATCH (e:Exam {id:12})
> MATCH (q:Question {id:13})
> MATCH (s:Student {id:14})
> MERGE (a)-[:ANSWER_TO]->(e)
> MERGE (a)-[:ANSWER_TO]->(q)
> MERGE (a)-[:ANSWER_TO]->(s);
> ```

This don't work if I would like to create new node, if an exact fork pattern doesn't exists but partial pattern exists.
For example, if (a)-(x)-(b) and (x)-(c) is already in the database.
All I want to do is to create node y for (a)-(y)-(b), (y)-(d) the first time I execute the transaction, match (y) if the patterns already exists.
Separated merge will behave as following:

> initialize database
> `CREATE (a)-(x)-(b)`
> `CREATE (x)-(c)`
> transaction begin
> `MERGE  (a)-(k)-(b)` this will match x for k as (a)-(x)-(b) are already there
> `MERGE  (k)-(d)`, this will create (x)-(d) as (x)-(d) do not exists
> transaction end, resulting in (a)-(x)-(b), (x)-(c) and (x)-(d), a fork with three prongs
![graph](https://user-images.githubusercontent.com/50871412/162425793-09ca4d77-d080-4def-a69a-eff0cc547aac.png)

My workaround is to add a dummy property like this:

> initialize database
> `CREATE (a)-(x{forkId: id(c)})-(b)`
> `CREATE (x)-(c)`
> transaction begin
> `MERGE  (a)-(k{forkId: id(d)})-(b)` now this will create new node for me as there are no matched pattern for this particular `forkId`
> `MERGE  (k)-(d)`
> transaction end, resulting in (a)-(x)-(b), (x)-(c). (a)-(y)-(b) and (y)-(d), two connect fork, each having two prongs, or a square loop with two loose hands
![graph(1)](https://user-images.githubusercontent.com/50871412/162425783-357a3e6f-55ff-4e4d-b5ec-864ea0dcc195.png)


Although there is a workaround, but relying something like a foreign key is feeling like violating the philosophy of graph database.
Unfortunately, I heavily use such pattern in my project (for multiple reasons, not just this"fork pattern merging problem").
(in one case I use such "foreign key" pattern on relationship property to achieve something doable when multi label relationship is allowed)

I would be happy if I am told that such pattern will not slow my database down a lot / at all.
