### ISSUE TITLE
[Feature Request] : IN clause working with COLLECTION of nested objects

### ISSUE THREAD

**Issue by ophileon** [neo4j/neo4j#3010]
you can now compare items to a collection of primitives, but not to a collection of nested objects.

in SO question http://stackoverflow.com/questions/25709309/syntax-issue-passing-objects-as-parameters-in-neo4j-cypher-statement  a case was illustrated.

**Comment by sherfert** [comment]
Hey and first of all sorry for the late response. Could you formulate a concise Cypher query with the syntax you would like to have?

**Comment by Lojjs** [comment]
@ophileon Since we have not received the requested concise Cypher query I will close the github issue for now. Feel free to reopen it if/when you have more info for us.

Best regards Louise, Neo4j Cypher team

**Comment by tomzeppenfeldt** [comment]
Issue can be closed indeed, because  the example below now works

Thanks

``` 
with [

{
    key1:1,
    key2:{
      key21:2,
      key23:3
	}
},
{
    key1:100,
    key2:{
      key21:200,
      key23:300
	}
}

] as coll,
{
    key1:100,
    key2:{
      key21:200,
      key23:300
	}
}  as item
return coll, (item IN coll)
```
