### ISSUE TITLE
Cypher: Add 'force delete' modifier so that Nodes with existing relationships can be deleted along with those relatioships

### ISSUE THREAD

**Issue by blevine** [neo4j/neo4j#303]
This a request for a convenience modifier described in the subject.  This would allow Cypher queries to be constructed without having to figure out how to add additional clauses to delete the nodes' relationships.

Rationale:

For a "simple" delete this is easy enough:

START n = node(...) MATCH n-[r?]-() DELETE r,n

But when the query gets more complex, the clause needed to find the relationships becomes more complex as well.

It would be convenient if the Cypher query could simply indicate the intent of deleting certain nodes and Cypher takes care of doing whatever needs to be done to make that happen.  It could look something like:

START n = node(...), m=node(...) MATCH [match clause that may find other nodes]  FORCE DELETE n, m, other_nodes...

This is in keeping with query languages like SQL, in which you define a predicate.  That predicate is then used  to either return the result or delete the result without requiring additions to the predicate itself.

**Comment by chrisvest** [comment]
This is implemented with `DETACH DELETE`: http://neo4j.com/docs/stable/query-delete.html#delete-delete-a-node-with-all-its-relationships
