### ISSUE TITLE
Hide/show specific types of relationships in query results

### ISSUE THREAD

**Issue by nizhikov** [neo4j/neo4j#3112]
I want to propose to implement simple feature in query results window:
I want to have ability to hide/show specific types of relationships.

My use case is:

I modeling city road graph.
My nodes labels is 
- POINT - connected by ROAD relationships, representing road joint. 
- GEO_POINT - representing road curve, have specific coordinates, connected by GEO_ROAD

Each POINT node is GEO_POINT also.
There is queries when I want to see only ROAD relationships, but there is no such feature in web admin application.

If that appropriate I even cam implement feature by mysefl.
But I need some advice.

**Comment by oskarhane** [comment]
This refers to 'web admin' which is retired since long now.
If this feature request still is valid, feel free to open it on https://github.com/neo4j/neo4j-browser
