### ISSUE TITLE
Browser does not show nodes which have relations with themselves 

### ISSUE THREAD

**Issue by ChristopherHackett** [neo4j/neo4j#3189]
I would expect the below cypher to result in a drawn graph with some indication that node a is self related.

```
CREATE (a:Page {name:'a'}),(b:Page {name:'b'}), (c:Page {name:'c'}), (a)-[:link]->(a), (b)-[:link]->(a),(c)-[:link]->(a)
MATCH (a) RETURN a
```

![image](https://cloud.githubusercontent.com/assets/1075126/4459410/cd15e590-48aa-11e4-8c0d-1ce9aae218b6.png)

**Comment by oskarhane** [comment]
Fixed in https://github.com/neo4j/neo4j/issues/3984
