### ISSUE TITLE
cypher SET node = {param} : failed removing properties via map, value null

### ISSUE THREAD

**Issue by tbaum** [neo4j/neo4j#324]
removing a property by updating (set-operation)  fails.

        engine.execute(
                "START n=node(0) SET n = {data}",
                map( "data",
                        map("key1", null)
                )
        );

... throws a 

    java.lang.IllegalStateException: Node[0] has been deleted in this tx

failing test:

https://github.com/tbaum/neo4j/blob/master/community/cypher/src/test/java/org/neo4j/cypher/javacompat/CypherUpdateMapTest.java

**Comment by jakewins** [comment]
This should be resolved now - please re-open if this issue persists
