### ISSUE TITLE
Lists returned from Cypher queries not serialised correctly over REST

### ISSUE THREAD

**Issue by nigelsmall** [neo4j/neo4j#328]
The results of Cypher queries which return lists are not serialised correctly when the query is made over the REST interface. The following (slightly contrived) example illustrates this:

```bash
curl -X POST http://localhost:7474/db/data/cypher -H "Content-Type: application/json" -d "{\"query\": \"START s=node(6788) RETURN extract(a in collect(s): ['a', 23123, 2.3]) as y;\"}"
```

returns:

```javascript
{
  "columns" : [ "y" ],
  "data" : [ [ [ "List(a, 23123, 2.3)" ] ] ]
}
```

Obviously this string value is useless to a client application and should probably be turned into a JSON array instead.

Cheers
Nige

**Comment by jakewins** [comment]
Verified that this has been resolved, sorry about the 3 year delay and all. Also, Cypher has gotten way nicer in the past few years :) 

```
$ curl -X POST http://localhost:7474/db/data/cypher -H "Content-Type: application/json" -d "{\"query\": \"RETURN ['a', 23123, 2.3] as y;\"}"
{
  "columns" : [ "y" ],
  "data" : [ [ [ "a", 23123, 2.3 ] ] ]
}
```
