### ISSUE TITLE
Only one version of the required dependencies should be included in the pom

### ISSUE THREAD

**Issue by DavideD** [neo4j/neo4j#3325]
See discussion at https://groups.google.com/forum/#!topic/neo4j/fDLiKEnKnAM

**Comment by benbc** [comment]
@craigtaverner Do you think this is still a problem?

**Comment by Mats-SX** [comment]
Cypher needs to keep several dependencies on the classpath to support [compatibility mode](http://neo4j.com/docs/developer-manual/current/cypher/#cypher-compatibility). Closing this.
