### ISSUE TITLE
Allow OrderedByTypeExpander to take an array (or equivalent)

### ISSUE THREAD

**Issue by maxdemarzi** [neo4j/neo4j#339]
https://github.com/neo4j/neo4j/blob/master/community/kernel/src/main/java/org/neo4j/kernel/OrderedByTypeExpander.java

Trying to to the equivalent of:
 person-[:TWITTER_FOLLOWERS|FB_FRIENDS]->(friends)<-[:LIKES]-()<-[:BELONGS_TO]-(parent)

**Comment by tinwelint** [comment]
@maxdemarzi echo :) is this still an issue, or even a thing anymore?

**Comment by maxdemarzi** [comment]
Custom traversal are the work around but a little helper method here would be nice.

**Comment by burqen** [comment]
Outdated
