### ISSUE TITLE
Cypher: Allow parameters for relationship types

### ISSUE THREAD

**Issue by freeeve** [neo4j/neo4j#340]
like

```
{
  query:"START n=node(1)
         MATCH n-[r:{type}]->()
         RETURN n,r;",
  params:{type:"knows"}
}
```

Handy for `create` too.

**Comment by magemello** [comment]
any news on this?

**Comment by magemello** [comment]
I need it for the CREATE too

**Comment by buzzdan** [comment]
need it too

**Comment by sephib** [comment]
@cleishm when running a `MATCH` cypher query - is there a performance penalty for inserting the relationship type in the `WHERE` clause and not in the `[r]` itself?
```
MATCH (a)-[r]->(b)
WHERE type(r) = {param}
```
vs. (that doesn't work today)
```
MATCH (a)-[r{param}]->(b)
```

**Comment by boggle** [comment]
Dynamic label parameterization is under consideration for Cypher 10 and GQL.

**Comment by MathReynaud** [comment]
We need it too ! Looking forward for Cypher 10 then ;)

**Comment by id8ai** [comment]
Yes please for Cypher 10 - makes some great opportunities for pipeline and integration

**Comment by mdfrenchman** [comment]
We do parameterized types prior to sending it across the neo4j-dotnet-driver connection.

Our typical usage is for temporality:
```csharp
var iteration = 1;
var cypher = $@"
    MATCH (n:Node1), (a:Node2) 
    MERGE (n)-[:RelBase_{interation}]->(a)
";
using (var session = driver.Session(AccessMode.Write)){
session.Run(cypher);
}
```

The plus side, is it still allows us to take advantage of the query cache.

**Comment by qomhmd** [comment]
I also need it.

**Comment by Pushplaybang** [comment]
This would drastically reduce the number of queries I have to maintain around create/merge/delete.

I think its a nonissue for MATCH etc.

**Comment by amaaradji** [comment]
It is actually possible to do this using apoc.create.relationship function in APOC, here is an exemple (on the offshore leaks database after importing the csv files)

```
MATCH (i1:Intermediary {node_id:e.START_ID}),(e:Edge),(i2:Intermediary {node_id:e.END_ID}) 
CALL apoc.create.relationship(i1,e.TYPE,{},i2) YIELD rel
Return i1,rel,i2
```
there is a SO thread on this too https://stackoverflow.com/questions/38324104/using-parameters-for-create-relationship-in-neo4j

**Comment by john681611** [comment]
> We do parameterized types prior to sending it across the neo4j-dotnet-driver connection.
> 
> Our typical usage is for temporality:
> 
> ```cs
> var iteration = 1;
> var cypher = $@"
>     MATCH (n:Node1), (a:Node2) 
>     MERGE (n)-[:RelBase_{interation}]->(a)
> ";
> using (var session = driver.Session(AccessMode.Write)){
> session.Run(cypher);
> }
> ```
> 
> The plus side, is it still allows us to take advantage of the query cache.

This would allow a  SQL injection-like attack to occur. Hence why we need to be able to pass it as a parameter

**Comment by freeeve** [comment]
I think the apoc solution is good enough (see: https://github.com/neo4j/neo4j/issues/340#issuecomment-793219411), and I have been using it for a while for various use-cases (also the renaming of relationship types is quite handy). As the original requestor (back in 2012!) I'll go ahead and close it.

**Comment by mdfrenchman** [comment]
I disagree that the APOC function is sufficient. The APOC solution only works for create doesn't it? This is/was still useful for matching.

However that being said, with indexing of properties on Relationships, and sharding of data across parametrized DBs. The end goal for parameterized reads is likely resolved, albeit a bit more complicated design wise. 

Since performance is still better for type and no prop index in a single graph. There's still some value for it. Probably not enough to warrant the effort though. 


We'll continue using string interpolation app side before sending the query (yes protected against cypher injection), until we migrate to split those parameters across different DBs in v5.

**Comment by jamthief** [comment]
Hi there. Neo4j now fully supports dynamic labels and types as of versions 2025.03 and 5.26.4 LTS, released in March of this year.

You can read more about them [here](https://neo4j.com/blog/developer/cypher-dynamism/), or read the documentation [here](https://neo4j.com/docs/cypher-manual/current/clauses/match/#dynamic-match).

Thanks for your patience and happy MATCHing!
