### ISSUE TITLE
LSOF version 4.88 breaks "start" command

### ISSUE THREAD

**Issue by johnnadratowski** [neo4j/neo4j#3414]
I was working with Neo when I updated by machine (I use a rolling-release distro) and Neo4j stopped working.  Specifically start-no-wait still seemed to function properly, but start would fail saying that it reached it's 120 second timeout (which it hadn't).

When I dug in I found that it was trying to compare a process ID using lsof.  It seems that the output of lsof v4.88 is a little different from what neo is expecting.  Neo expects it to output the process id as the second-to-last line of output from lsof, but it's doing it as the first line.  For example:

The source for the neo4j runner getting the process id is:
```
newpid=$(lsof -i :$NEO4J_SERVER_PORT -F T -Ts | grep -i "TST=LISTEN" -B1 | head -n1)
```

The output from lsof -i :$NEO4J_SERVER_PORT -F T -Ts is this:
```
p23916
f123
TST=LISTEN
```

It expects the output being:
```
f123
p23916
TST=LISTEN
```

So it registers the newpid variable as "123" and fails on the check.

In my mind, there are two fixes that need to be done:

1) The check should iterate through the lsof output and look for the 'p' line prefix for the process id
2) The error message should not be a cryptic "Neo4j Failed to start after 120 seconds".  It should indicate that something went wrong, not that a timeout was hit.

**Comment by spacecowboy** [comment]
Fixed in #5601
