### ISSUE TITLE
Typo or intended with relationship_deleted?

### ISSUE THREAD

**Issue by endyjasmi** [neo4j/neo4j#3421]
Whenever request are made through the cypher endpoint which requires meta query data, the server will embed the meta data query with the result. There is one field called `relationship_deleted`.

Shouldn't it be `relationships_deleted` as per the counter part of `relationships_created`?

Is it intended or typo made it way to production?

Thanks in advance, from a guy that love consistency.

**Comment by jakewins** [comment]
Relabeling this as a feature since it is more of an enhancement than a bug.
