### ISSUE TITLE
Neo4j 2.1.5 shutdown in low memory condition corrupted database

### ISSUE THREAD

**Issue by bunkat** [neo4j/neo4j#3424]
I left the Neo4j browser window up on my Dev machine and it eventually consumed all available memory including swap space (I think it was component.js).  I then attempted to shutdown Neo4j using `./neo4j stop` and it seemed to work but I got the message `forced shutdown` at the end of the stop procedure. 

I then rebooted the machine and started Neo4j back up with `./neo4j start` and it started without any errors.  However, when I started trying to use the database I found that there is a lot of missing data (data for entire users is just gone).  I'm also getting lots of errors like this one:

````
{Code:"Neo.ClientError.Statement.EntityNotFound", Message:"Node with id 116694"},
````

I would have expected some error on startup or something in the logs but I don't see anything. Shouldn't the operator get warned if data has been corrupted or could not be written safely to disk?

**Comment by chrisvest** [comment]
There was a bug that we fixed in 2.1.6, where, if the database crashed at a particular point during the shut down procedure, it could lead to inconsistencies like this. I'm going to close this since that fix is out.
