### ISSUE TITLE
g.V.outE("is").sideEffect{ g.removeEdge(it) } errors with "Relationship[0] not found"

### ISSUE THREAD

**Issue by radford** [neo4j/neo4j#347]
Given, the following setup:

    START r=node(0) CREATE r-[:is]->()<-[:was]-r;

this gremlin script fails with "Relationship[0] not found"

    g.V.outE("is").sideEffect{ g.removeEdge(it) }

though the relationship is removed.

**Comment by maxdemarzi** [comment]
Gremlin is no longer in the product directly. See https://github.com/neo4j-contrib/gremlin-plugin if this issue still exists.
