### ISSUE TITLE
Missing node properties under heavy loads

### ISSUE THREAD

**Issue by tkroman** [neo4j/neo4j#3489]
I started to experience some troubles within even mildly concurrent environment recently. Having something like 32-48 concurrent RPS, which trigger graph traversals (implemented via Traversal API, not Cypher-based ones) that use some properties that are guaranteed to be present for each node in the graph, sometimes I get `NotFoundException`s with messages saying that the node doesn't have such a property. However, if I check the node with the Cypher query after the traversal fails, I can see the property being present. (And I can guarantee that it was there when it 'was not found').
I think that this has something to do with concurrency because in the same time *a lot* of `DeadlockDetectedException`s are thrown, upon catching which I'm retrying the whole transaction, which might succeed on 2-3-4-5th try. I don't really admire the way this issue has to be dealt with, but at least there is something that can be done, while silent failures of properties' fetches are rather unpleasant.
Neo4j version is 2.1.5, cache type (in case this matters) is HA, distribution runs from an embedded Java app on a Linux machine 16GB RAM with Xmx=4G and enough space configured for caches. Load is something like 90% per core for 4-core CPU.
This is rather sporadic behaviour and I can't specify steps to reproduce (other than "create 100K nodes and try to traverse them concurrently until you fail"), and unfortunately I didn't fetch the logs last time, so if anything like this happens anytime soon, I'll update the issue with more useful information.

**Comment by jakewins** [comment]
@tkroman I am _incredibly_ sorry it has taken this long for you to get a reply to this ticket. This issue is indeed the same issue as in #3864 as you suspected - and both of these issues are the same as #37. 

Please see my comment at the very end of #3864 for details on the status of this. Lets consolidate these issues into the oldest one raised, #37.
