### ISSUE TITLE
logback.xml included in neo4j-server.jar

### ISSUE THREAD

**Issue by alexxv** [neo4j/neo4j#352]
Hi, 

I'm using logback in my project and also neo4j-server, I'm getting WARN from logback because of multiple logback.xml file found in classpath,
I think you should rename your file to neo4j-server-logback.xml or something like this.

I've posted a question on SO with more details
http://stackoverflow.com/questions/13788346/logback-xml-from-imported-jar-cause-a-warning

Thanks

Alex

**Comment by jakewins** [comment]
It is no longer supported to bundle Neo4j server as a whole in an application, other than for testing. However - we do actually no longer ship a `logback.xml` on the classpath, so this has been resolved :)
