### ISSUE TITLE
tx.close() causing "FileNotFound exception: Too many open files in system"

### ISSUE THREAD

**Issue by jerdeb** [neo4j/neo4j#3538]
I am noticing that over 10K transactions, the tx.close() function is throwing a "FileNotFound exception...: (Too many open files in system)". My initial thought is that lucene files are not being closed after a transection, but I could be wrong.

I am running my test application locally using a Mac (10.9.5) and Eclipse Kepler.

Code:

```
public void compute(Quad quad){
        try ( Transaction tx = graphDb.beginTx() )
        {
               // check if quad.subject exists as a node and return it, else create a new one
               // check if quad.object exists as a node and return it, else create a new one
               // create relationship between quad.subject and quad.object
               tx.success();
               tx.close(); // added this just to check if this would actually work, but made no difference
        }
}
```

I am using maven and the Neo4j version I'm using is 2.1.5.

Message.log can be found here: https://gist.github.com/jerdeb/410b00b7f67cfa0e0d7a

For testing purposes, I can also provide access to the current code as it can be found in a public github.

**Comment by klaren** [comment]
According to the internet:
```
By default, the maximum number of files that Mac OS X can open is set to 12,288 and 
the maximum number of files a given process can open is 10,240.
```
How to actually change the maximum value differs from each major version, a semi-complete list can be found in the answers here: 
https://superuser.com/questions/433746/is-there-a-fix-for-the-too-many-open-files-in-system-error-on-os-x-10-7-1
