### ISSUE TITLE
Cypher: Need a way to set an existing Node's labels to a known set.

### ISSUE THREAD

**Issue by blevine** [neo4j/neo4j#3571]
In Cypher, there is currently no way to set an existing Node's labels to an explicit set of labels. The SET statement can be used to add labels to the set of labels for a Node, but there is no way to update all of the labels for an exiting Node.  This is in contrast to Node properties where you can do SET n = {map_of_props} to set or update all properties of the Node. This makes it difficult to set the entire state of an existing Node (I consider both the properties and labels of the Node to be part of the state) in a single Cypher query.

In our application, all Nodes have a unique id property (a GUID) and we use MERGE queries with ON CREATE/ON MATCH to implement "in place" create-or-update logic on Nodes using a query similar to:

`MERGE (n:Node {guid:theguid}) ON CREATE SET n:label1:label2:label3, n = {props_for_create} ON MATCH SET n:label4:label5, n = {props_for_update} RETURN n`

This allows us to implement save logic without having to know whether the Node with the specified GUID exists (i.e., whether the operation is a create or update).  The intent is that an existing Node would have its properties set to the properties in the props_for_upate map and the labels set to "label4", label5. However, this doesn't quite work because `ON MATCH SET n:label4:label5` adds "label4" and "label5" to the Node rather than replacing the existing labels. For us to be able to implement the "update" part of the create-or-update logic efficiently, we need to be able to replace the entire state of the node including properties and labels.

**Comment by optimuspaul** [comment]
+1.  this is driving me crazy right now.  There appears to be a way to do it via REST, but not in cypher.

**Comment by jakewins** [comment]
This would be a great feature to add, agreed. We've got a ticket tracking this, so I'm going to close this as a duplicate: https://github.com/neo4j/neo4j/issues/2073
