### ISSUE TITLE
Browser uses absolute urls for the backend

### ISSUE THREAD

**Issue by hans-d** [neo4j/neo4j#3593]
see https://github.com/neo4j/neo4j/blob/master/community/browser/app/scripts/settings.coffee#L22

This makes the browser to work only with absolute URLs for the backend (which may be configured to use relative urls).

Currently the `neo4j-browser-<version>.jar` needs to be hacked to modify this when using the resulting build. Would be great if this is easier to configure after the code is build.

**Comment by oskarhane** [comment]
I don't know when this was fixed, but this is no longer the case.
