### ISSUE TITLE
neo4j-io test-jar required for ImpermanentGraphStore with 2.2

### ISSUE THREAD

**Issue by jotomo** [neo4j/neo4j#3650]
With 2.1, running unit tests using the _ImpermanentGraphStore_ required the _test-jar_ of the _neo4j-kernel_ artifact as described in the _Basic unit testing_ section of the docs.

With 2.2.0-M01, I get a _ClassNotFoundExepction_ for _EphemeralFileSystemAbstraction_, which (now) lives in the _neo4j-io_ artifact. Adding the _neo4j-io_ artifact, with the _test-jar_ classifier unbreaks my tests. 
Is this intended? If so, the docs should be updated and the changelog should probably add a note about this, no?

**Comment by ducky427** [comment]
bump.

In the final release, I also came across this issue.

**Comment by jexp** [comment]
What @jakewins said ... so far the meta-module has not been created.

**Comment by ducky427** [comment]
Thanks @jexp.

So I came across this by searching github. Probably not the best workflow as this is a breaking change. It probably makes sense to document it in "Deprecations" Section of the manual as well.

**Comment by klaren** [comment]
Seeing that this was a breaking change over two years ago and all currently supported versions have the same documentation and module structure in unit testing regard, I'm going to close this issue.
