### ISSUE TITLE
TransactionEventHandler: No way to read properties of entities in afterCommit() method

### ISSUE THREAD

**Issue by blevine** [neo4j/neo4j#3659]
Running Neo4j 2.1.5

I've implemented a TransactionEventHandler.  An IllegalStateException (TX_COMMIT...) exception is thrown when accessing any property of a Node or Relationship that is included in the TransactionData. I assume that this is because the transaction has already completed. This greatly reduces the value of the afterCommit() method if you can't find out anything (other than the ids) of the entities that have been affected during the transaction.

**Comment by tinwelint** [comment]
Could you provide the entire stack trace of the exception?

**Comment by jakewins** [comment]
The event handling subsystem has been significantly overhauled in recent releases of Neo4j. This should no longer be an issue. Please reopen if it remains a problem, and if so include a full strack trace.
