### ISSUE TITLE
Neo4j in Docker returns wrong server url

### ISSUE THREAD

**Issue by derekshi** [neo4j/neo4j#3678]
I used neo4j in docker and forwarded 7474 port to localhost. When querying neo4j using REST api (via py2neo 2.0), the server returns url like http://bb2343242:7474, which is not the url I requested, which supposed to be http://localhost:7474. I wonder if there is any place in neo4j source code that returns server name wrong. The issue only exists when neo4j is running inside Docker image. Not a problem when it is deployed on normal servers.

**Comment by derekshi** [comment]
@jimwebber Here is the curl command (note: http://192.168.59.103 is my docker host and I forwarded port from 7474 to 7470): 

curl -v -X POST -d @data.txt  http://192.168.59.103:7470/db/data/transaction/commit -H "X-Stream:true" -H "Host:192.168.59.103:7470" -H "Content-Type:application/json"

data.txt has following JSON data:
{
  "statements" : [ {
    "statement" : "MATCH (t:Token) WHERE t.id = 'Some Token' RETURN t;",
	"parameters" : {},
	"resultDataContents" : [ "REST" ]
  } ]
}

And the curl results are as follows:
{"results":[{"columns":["t"],"data":[{"rest":[{"outgoing_relationships":"http://07fe0cc1bfc3:7474/db/data/node/34/relationships/out","labels":"http://07fe0cc1bfc3:7474/db/data/node/34/labels","traverse":"http://07fe0cc1bfc3:7474/db/data/node/34/traverse/{returnType}","all_typed_relationships":"http://07fe0cc1bfc3:7474/db/data/node/34/relationships/all/{-list|&|types}","self":"http://07fe0cc1bfc3:7474/db/data/node/34","property":"http://07fe0cc1bfc3:7474/db/data/node/34/properties/{key}","properties":"http://07fe0cc1bfc3:7474/db/data/node/34/properties","outgoing_typed_relationships":"http://07fe0cc1bfc3:7474/db/data/node/34/relationships/out/{-list|&|types}","incoming_relationships":"http://07fe0cc1bfc3:7474/db/data/node/34/relationships/in","create_relationship":"http://07fe0cc1bfc3:7474/db/data/node/34/relationships","paged_traverse":"http://07fe0cc1bfc3:7474/db/data/node/34/paged/traverse/{returnType}{?pageSize,leaseTime}","all_relationships":"http://07fe0cc1bfc3:7474/db/data/node/34/relationships/all","incoming_typed_relationships":"http://07fe0cc1bfc3:7474/db/data/node/34/relationships/in/{-list|&|types}","metadata":{"id":34,"labels":["Token"]},"data":{"id":"Some Token"}}]}]}],"errors":[]}

**Comment by jimwebber** [comment]
@derekshi which version of Neo4j are you using?

**Comment by derekshi** [comment]
2.1.6

**Comment by jimwebber** [comment]
@derekshi I think 2.1.7-SNAPSHOT doesn't have this problem. A bunch of changes got backported from 2.2 which remove any dependency on asking the server for a URI (instead accepted the Host header).

The easiest way to test this is by substituting 2.1.6 on your Docker image for 2.2-M01, just for a quick test.

Could you try that and report back?

**Comment by derekshi** [comment]
@jimwebber I tested against 2.2-m01, it DOES fix the issue. Thanks a lot!

**Comment by jimwebber** [comment]
Oh, cool @derekshi, thank you very much indeed for all your help.

Is it ok (and to @dekobon too) if I close off this issue?
