### ISSUE TITLE
Support "repeatable read" within a single cypher statement

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#37]
_NOTE: This description has been updated, the original description is at the bottom_

While Neo4j primitives are `read committed`, Cypher composes these primitives together in ways that can lead to errors - notably cypher may read an entity that is subsequently deleted, and will then fail to perform some operation on it.

While this could be construed as a cypher issue, it is really an issue of isolation levels - we need to implement `repeatable read` isolation in the kernel to allow cypher to expose a single cypher statement as a read committed operation.
### If you suspect an isolation issue

If you believe you are hitting a problem related to transaction isolation levels, please post a comment on this ticket with:
- Any setup required
- All cypher statements involved
- What you expected the result to be
- What the result actually is
- Your Neo4j version, Java version and operating system
### Lock the read set

Many (but not all) of the cases where this is an issue have a format like:

```
<match some stuff>
<perform some mutation>
```

For this category of statements, we suffer the same problem as SQL solves with `SELECT ... FOR UPDATE`. Cypher does not yet support a construct like that, but it can be emulated using the following pattern:

```
<match some stuff>
<set a property, for instance __lock__>
WITH <stuff>
<perform some mutation>
```

For example:

```
MATCH (n:Person)
SET n.__lock__ = 1
WITH n
SET n.description = "Some description"
```
### Retry transaction

Particularly for small read operations and small writes, given the transactional nature of Neo4j, you can rollback and retry any transaction where a statement fails due to this issue. A common pattern for this is to model your query as a unit of work that can be retried.
## Original message

@peterneubauer: 'See https://groups.google.com/group/neo4j/browse_thread/thread/9355edd2059d70e2/a51d06c894107327?lnk=gst&q=Concurrent+reading+and+deleting+on+relationships+leads+to+NotFoundException.+How+to+ignore%3F#a51d06c894107327 for background.

Example code is at http://code.google.com/p/graph-query-benchmarks/source/browse/trunk/graph-query-benchmarks/src/test/nz/ac/massey/cs/graphbenchmarks/spikes/neo4j/NeoIssues.java'

**Comment by jonathancrosmer** [comment]
Any word on this?  This bug has caused us some headaches.

**Comment by lszumel** [comment]
I have a cypher query like:```
START n=node(123)
MATCH p=(n)-[r:R]-(b) 
WHERE r.BeginTime > 1
RETURN p

``````
This query is sometimes failing at runtime _if new R rels are being created in another thread_, with an error like this:```
org.neo4j.graphdb.NotFoundException: RELATIONSHIP[11590158] has no property with propertyKey="BeginTime".
``````

After the failure, I look at `r` and it has the BeginTime property. `r` is created in a single transaction using the Java API on an embedded instance. So it appears that my Cypher query is traversing a partially-committed transaction.

Is this a case of the same bug described here?

**Comment by jakewins** [comment]
@lszumel +1. For your particular case, you can work around it by tricking cypher into locking that node, something like:

```
START n=node(123)
SET n._lock=1 WITH n
MATCH p=(n)-[r:R]-(b) 
WHERE r.BeginTime > 1
RETURN p
```

**Comment by jakewins** [comment]
@jonathancrosmer super, super sorry for the late reply. See my reply above for an intermediary workaround. 

For the larger issue: We know how to fix it, and we know how to do it without impacting read performance, it's prioritized as an upcoming epic.

**Comment by jonathancrosmer** [comment]
Thanks!

**Comment by alph486** [comment]
@jakewins have any of these fixes been slated for any particular release yet?

**Comment by jakewins** [comment]
@alph486 the canned response to that is that we don't commit to release dates for features/fixes - eg. we work on them in prio order and ship the ones that are production ready when we do minor releases, which we (generally) do twice a year.

The non-canned response is that the fix requires some rather intricate changes to the storage layer, which will take time to do properly. We're doing a spike to "dry run" those changes, and before that is done it's very hard to say how long it will take.

**Comment by Sahasrara** [comment]
#7288 <-- duplicate

**Comment by Lojjs** [comment]
This has been completed this February according to @MishaDemianenko
