### ISSUE TITLE
Save state of graph layout in neo4j web interface. 

### ISSUE THREAD

**Issue by pumplerod** [neo4j/neo4j#371]
It would be a HUGE help to be able to save the positional state of nodes in the visualization graph. 

I often write queries to change parameter values and because the values do not update I have to refresh the graph which causes everything to scramble again. 

What I'd love is to assemble nodes into a layout that works for me and then lock those nodes down so that when I refresh the only thing to change would be the label and parameter values.

**Comment by oskarhane** [comment]
This issue was moved to neo4j/neo4j-browser#111
