### ISSUE TITLE
Browser: No Longer Displays Node ID

### ISSUE THREAD

**Issue by dolvany** [neo4j/neo4j#3713]
Panning and node details on mouseover are two great improvements to the viz in 2.2. Although I did have to click for node details in 2.1, I found it especially useful that it displayed the node id so I could differentiate between nodes that are otherwise identical. It would be great if this functionality were retained going forward. The node id could be added to the mouseover node details as perhaps 'id(): [id]'.

**Comment by oskarhane** [comment]
Hi @dolvany!
Yes, this could be useful and it was added in a recent milestone.

Click the **Caption: <id>** at the bottom to have the node ID displayed inside the nodes of a certain label.

![oskar4j 2015-02-05 at 15 05 17](https://cloud.githubusercontent.com/assets/570998/6061506/a7adb6a4-ad48-11e4-91bf-851ed66ba999.png)
