### ISSUE TITLE
Browser: Displays relationship that doesn't match query

### ISSUE THREAD

**Issue by dolvany** [neo4j/neo4j#3714]
Perhaps this is for some reason by design, but the following behavior doesn't seem quite right to me.

I create some nodes and relationships: create (a)-[:edge{layer:1}]->(b)-[:edge{layer:1}]->(c)-[:edge{layer:2}]->(a)

I query and get the expected result of two nodes and a single relationship: match ()-[a{layer:2}]->() return a

I query expecting two nodes and two relationships, but the viz displays the third relationship: match ()-[a{layer:1}]->() return a

The result table doesn't contain the erroneous(?) third relationship, only the viz.

**Comment by oskarhane** [comment]
There's now a switch to toggle the auto-completion of internal relationship between nodes.
