### ISSUE TITLE
Neo4j 2.1.6 Cypher UNWIND throws Neo.ClientError.Statement.InvalidSyntax error

### ISSUE THREAD

**Issue by bunkat** [neo4j/neo4j#3720]
I have queries that worked in Neo4j 2.1.5 that are now broken in 2.1.6. I checked the release notes but didn't see any mention about a change in functionality for UNWIND.

````
[{Neo.ClientError.Statement.InvalidSyntax Invalid input 'W': expected 'i/I' (line 14, column 43)
"  WITH COLLECT(p) + COLLECT(sp) AS coll UNWIND coll AS p"}]
````

Did UNWIND get replaced with something else?

**Comment by jakewins** [comment]
Verified that this has been resolved in recent versions of Neo4j: http://console.neo4j.org/r/nqops4
