### ISSUE TITLE
Neo4j 2.2M02 returns Java error for LOAD CSV cypher script working in previous version

### ISSUE THREAD

**Issue by danielcor** [neo4j/neo4j#3727]
This error recommends the use of tryExtract appears to be a Java error message rather than a cypher one...   The CSV File does have empty strings.

{"results":[],"errors":[{"code":"Neo.DatabaseError.Statement.ExecutionFailure","message":"String didn't extract value for Mark[line:2, from:191, to:191]. For values which are optional please use tryExtract method instead","stackTrace":"java.lang.IllegalStateException: String didn't extract value for Mark[line:2, from:191, to:191]. For values which are optional please use tryExtract method instead\r\n\tat org.neo4j.csv.reader.BufferedCharSeeker.extract(BufferedCharSeeker.java:197)\r\n\tat org.neo4j.cypher.internal.compiler.v2_2.spi.CSVResources$$anon$1$$anonfun$readNextRow$1.apply$mcV$sp(CSVResources.scala:58)\r\n\tat scala.util.control.Breaks.breakable(Breaks.scala:37)\r\n\tat org.neo4j.cypher.internal.compiler.v2_2.spi.CSVResources$$anon$1.readNextRow(CSVResources.scala:56)\r\n\tat org.neo4j.cypher.internal.compiler.v2_2.spi.CSVResources$$anon$1.next(CSVResources.scala:76)\r\n\tat org.neo4j.cypher.internal.compiler.v2_2.spi.CSVResources$$anon$1.next(CSVResources.scala:53)\r\n\tat org.neo4j.cypher.internal.compiler.v2_2.pipes.LoadCSVPipe$$anonfun$internalCreateResults$1.apply(LoadCSVPipe.scala:70)\r\n\tat org.neo4j.cypher.internal.compiler.v2_2.pipes.LoadCSVPipe$$anonfun$internalCreateResults$1.apply(LoadCSVPipe.scala:62)\r\n\tat scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)\r\n\tat scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)\r\n\tat scala.collection.Iterator$class.foreach(Iterator.scala:727)\r\n\tat scala.collection.AbstractIterator.foreach(Iterator.scala:1157)\r\n\tat scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)\r\n\tat scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:176)\r\n\tat scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:45)\r\n\tat scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)\r\n\tat scala.collection.AbstractIterator.to(Iterator.scala:1157)\r\n\tat scala.collection.TraversableOnce$class.toList(TraversableOnce.scala:257)\r\n\tat scala.collection.AbstractIterator.toList(Iterator.scala:1157)\r\n\tat org.neo4j.cypher.internal.compiler.v2_2.pipes.EagerPipe.internalCreateResults(EagerPipe.scala:32)\r\n\tat org.neo4j.cypher.internal.compiler.v2_2.pipes.PipeWithSource.createResults(Pipe.scala:119)\r\n\tat org.neo4j.cypher.internal.compiler.v2_2.pipes.PipeWithSource.createResults(Pipe.scala:116)\r\n\tat org.neo4j.cypher.internal.compiler.v2_2.pipes.PipeWithSource.createResults(Pipe.scala:116)\r\n\tat org.neo4j.cypher.internal.compiler.v2_2.pipes.PipeWithSource.createResults(Pipe.scala:116)\r\n\tat org.neo4j.cypher.internal.compiler.v2_2.pipes.PipeWithSource.createResults(Pipe.scala:116)\r\n\tat org.neo4j.cypher.internal.compiler.v2_2.pipes.PipeWithSource.createResults(Pipe.scala:116)\r\n\tat org.neo4j.cypher.internal.compiler.v2_2.pipes.PipeWithSource.createResults(Pipe.scala:116)\r\n\tat org.neo4j.cypher.internal.compiler.v2_2.executionplan.DefaultExecutionResultBuilderFactory$ExecutionWorkflowBuilder.createResults(DefaultExecutionResultBuilderFactory.scala:92)\r\n\tat org.neo4j.cypher.internal.compiler.v2_2.executionplan.DefaultExecutionResultBuilderFactory$ExecutionWorkflowBuilder.build(DefaultExecutionResultBuilderFactory.scala:64)\r\n\tat org.neo4j.cypher.internal.compiler.v2_2.executionplan.ExecutionPlanBuilder$$anonfun$getExecutionPlanFunction$1.apply(ExecutionPlanBuilder.scala:121)\r\n\tat org.neo4j.cypher.internal.compiler.v2_2.executionplan.ExecutionPlanBuilder$$anonfun$getExecutionPlanFunction$1.apply(ExecutionPlanBuilder.scala:106)\r\n\tat org.neo4j.cypher.internal.compiler.v2_2.executionplan.ExecutionPlanBuilder$$anon$1.execute(ExecutionPlanBuilder.scala:70)\r\n\tat org.neo4j.cypher.internal.compatibility.CompatibilityFor2_2$ExecutionPlanWrapper$$anonfun$execute$1.apply(CompatibilityFor2_2.scala:141)\r\n\tat org.neo4j.cypher.internal.compatibility.CompatibilityFor2_2$ExecutionPlanWrapper$$anonfun$execute$1.apply(CompatibilityFor2_2.scala:141)\r\n\tat org.neo4j.cypher.internal.compatibility.exceptionHandlerFor2_2$.runSafely(CompatibilityFor2_2.scala:97)\r\n\tat org.neo4j.cypher.internal.compatibility.CompatibilityFor2_2$ExecutionPlanWrapper.execute(CompatibilityFor2_2.scala:140)\r\n\tat org.neo4j.cypher.internal.compatibility.CompatibilityFor2_2$ExecutionPlanWrapper.execute(CompatibilityFor2_2.scala:127)\r\n\tat org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:84)\r\n\tat org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:79)\r\n\tat org.neo4j.cypher.javacompat.ExecutionEngine.execute(ExecutionEngine.java:87)\r\n\tat org.neo4j.cypher.javacompat.internal.ServerExecutionEngine.executeQuery(ServerExecutionEngine.java:59)\r\n\tat org.neo4j.server.rest.transactional.TransactionHandle.executeStatements(TransactionHandle.java:320)\r\n\tat org.neo4j.server.rest.transactional.TransactionHandle.commit(TransactionHandle.java:139)\r\n\tat org.neo4j.server.rest.web.TransactionalService$2.write(TransactionalService.java:204)\r\n\tat com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:71)\r\n\tat com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:57)\r\n\tat com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:302)\r\n\tat com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1510)\r\n\tat com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)\r\n\tat com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)\r\n\tat com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)\r\n\tat com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540)\r\n\tat com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715)\r\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790)\r\n\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:751)\r\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1666)\r\n\tat org.neo4j.server.guard.GuardingRequestFilter.doFilter(GuardingRequestFilter.java:68)\r\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1636)\r\n\tat org.neo4j.server.guard.GuardingRequestFilter.doFilter(GuardingRequestFilter.java:68)\r\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1636)\r\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:564)\r\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:219)\r\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1111)\r\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:498)\r\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)\r\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1045)\r\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)\r\n\tat org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)\r\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:98)\r\n\tat org.eclipse.jetty.server.Server.handle(Server.java:461)\r\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:284)\r\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244)\r\n\tat org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:534)\r\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)\r\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)\r\n\tat java.lang.Thread.run(Unknown Source)\r\n"}]}

**Comment by spacecowboy** [comment]
This has been fixed. Verified on 2.3.2
