### ISSUE TITLE
Neo4j 2.1.6 REST  API deallock in unit test 

### ISSUE THREAD

**Issue by pivstone** [neo4j/neo4j#3732]
I use ` Transactional Cypher HTTP endpoint ` to add and clear test data in Junit test.The endpoint is `http://192.168.X.X:7474/db/data/transaction/commit`.

Before test method  add some test data by cyber query like this:

>Merge (n:Book{bid:1}) on create set n.date=123241

Then after test method clear all test data by the cyber:

> Match (n) Optional Match (n)-[r]-() Delete n,r

The first test method was OK ,but the second test method was deadlock at the `@After`,the REST API did't have any response.

Then I run the query in Browse, it says that,

> Neo.TransientError.Transaction.DeadlockDetected.

**Comment by jakewins** [comment]
Since there's not been a reply here in a year, I'm closing this. Please don't hesitate to re-open if the issue still remains.
