### ISSUE TITLE
Query returns lots of nodes but no relationships - nothing visible

### ISSUE THREAD

**Issue by kenahoo-windlogics** [neo4j/neo4j#3735]
In the neo4j browser, the following query returns "797 nodes, 796 relationships", and all are visible in the graphical output:

    MATCH (a {id:"08363_A"}) WITH a MATCH a-[:CONNECTS_TO*..28]->b RETURN a, b;

However, the same query with 1 more degree of separation allowed returns "804 nodes, 0 relationships" and nothing at all is visible in the output:

    MATCH (a {id:"08363_A"}) WITH a MATCH a-[:CONNECTS_TO*..29]->b RETURN a, b;

Both queries return quite fast.

Is this a known bug?  I'm using Neo4j Community edition, v2.1.6, and Chrome 39.0.2171.95 (64-bit), both on a single Ubuntu 14.10 machine.

**Comment by jexp** [comment]
Can you check your javascript console, if there are any error messages?
Can you reproduce it with another browser? e.g. Firefox?

**Comment by AshishBarde** [comment]
I am using 2.0.3 version of neo4j graph database. using adaptor layer I
have develope code in java these code execute the sql query on server side
database and read the data from server side and put it into neo4j graph
database for that I have created DOM in Json format giving the information
about relationship and properties and labels and these running successfully
and their is no need of csv file or excel file.. for reading .... these is
a big achivement for us these task I have done in April 2014.....

On Sat, Jan 3, 2015 at 5:29 PM, Michael Hunger <notifications@github.com>
wrote:

> Can you check your javascript console, if there are any error messages?
> Can you reproduce it with another browser? e.g. Firefox?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neo4j/neo4j/issues/3735#issuecomment-68592724>.
>



-- 
hi..
if u want any document plz reply me

**Comment by oskarhane** [comment]
This issue was moved to neo4j/neo4j-browser#130
