### ISSUE TITLE
Community version 2.16 (binary) is missing neo4j.io.jar (CORRECTION)

### ISSUE THREAD

**Issue by lhmcdonald** [neo4j/neo4j#3737]
Oops :: of course, the source code on github is not necessarily compatible with earlier versions of neo4j.
Obviously, org.neo4j.io has been added since v2.16.

My real point here is that community edition (binary) 2.16 does not include the source code for examples; and there is no SIMPLE way to obtain these sources after the github version has changed.  It would therefore be nice to include said correct, example source code in the community edition (binary).
(Promo : it would also be nice to have more examples!)

**Comment by jakewins** [comment]
As per @jexp above, the examples for a given version can be found by looking at that tag on github.
