### ISSUE TITLE
Neo4j Server failed to start

### ISSUE THREAD

**Issue by rootsical** [neo4j/neo4j#3740]
this is the error message:
`Starting Neo4j Server...process [1059]... waiting for server to be ready........ Failed to start within 120 seconds.
Neo4j Server failed to start, please check the logs for details.
If startup is blocked on a long recovery, use '/opt/neo4j-community-2.1.6/bin/neo4j start-no-wait' to give the startup more time`    
    
i am on arch linux on a virtualbox. i have downloaded and extracted neo4j to /opt. when i run `bin/neo4j start` the server fails to start. if i run `bin/neo4j start-no-wait` the server starts almost immediately. i can also run `bin/neo4j console` without problems. i have changed the startup time from 120 to 1200 in the confs but it makes no difference. to be honest, i am running java jdk 8, but have never had problems before. the only problem i can find in logs is that snakeoil self cert cannot be found. i am also running as root if that makes a difference. i have no *neo4j* user and all the neo4j files are owned by root. thanks

**Comment by jotomo** [comment]
@rootsical You're probably running into #3414. You could apply the [patch](https://github.com/neo4j/neo4j/pull/3402/files) to the start script that was submitted but unfortunately can't be merged officially.

**Comment by rootsical** [comment]
thank you thank you. modifying the bin/neo4j file on line 148 as in the patch did it for me. thank you thank you..

**Comment by djvs** [comment]
This is a serious bug!  This configuration setting is useless and the first suggested answer on Google.  Currently dealing with production downtime due to failed recovery.

**Comment by jotomo** [comment]
@djvs What Linux are running this on?

**Comment by djvs** [comment]
Sorry, after deeper investigation, it appears this was a bit of a mirage - I was hitting Out of Memory errors due to some database corruption, which  at first appeared to be an issue of the 120s limit being reached (until I realized it was crashing in 80 seconds and checked messages.log).
