### ISSUE TITLE
Graph Style Sheet doesn't support attribute selectors styling

### ISSUE THREAD

**Issue by liudonghua123** [neo4j/neo4j#3751]
In Neo4j's browser graph visualization, graph style sheet only supports tag and tag.class selector, multiple chained class like "tag.class1.class2" is not support(see  https://github.com/neo4j/neo4j/issues/2112), I think attribute selectors is more important than multiple chained class.
For example, we can use the following to distinguish person of different gender.
node.Person[gender="male"] {
......
}
node.Person[gender="female"] {
......
}
And we could highlight the 1980s movies via
node.Movie[released^="198"] {
......
}

For more attribute selectors example, see http://www.w3schools.com/css/css_attribute_selectors.asp

**Comment by Gary-Li** [comment]
+1

**Comment by khatkar** [comment]
Agree, this would be a really cool feature.
+1

**Comment by slorg1** [comment]
+1

**Comment by oskarhane** [comment]
This issue was moved to neo4j/neo4j-browser#131
