### ISSUE TITLE
Blueprint context definition (OSGI-INF/blueprint/neo4j-kernel.xml) is invalid 

### ISSUE THREAD

**Issue by brampouwelse** [neo4j/neo4j#377]
The blueprint context definition in the neo4j-kernel jar  is causing a problem because it's referencing org.neo4j.graphdb.index.IndexProvider without the  ext:proxy-method='classes'. 

Log: 

2012-12-18 07:52:25,622 | INFO  | rint Extender: 3 | ReferenceListRecipe              | nt.container.ReferenceListRecipe  137 | 7 - org.apache.aries.blueprint.core - 1.0.1 | Error tracking new service reference
org.osgi.service.blueprint.container.ComponentDefinitionException: A class org.neo4j.graphdb.index.IndexProvider was found in the interfaces list, but class proxying is not allowed by default. The ext:proxy-method='classes' attribute needs to be added to this service referen

As the neo4j jars don't have all the required OSGi meta data and the blueprint context isn't mentioned in the documentation about running neo4j in an OSGi it may be better to delete the blueprint context from the jar.

**Comment by jakewins** [comment]
We've removed the OSGi definitions from the code base now, they were poorly tested and unmaintained.
