### ISSUE TITLE
Browser: Ability to export saved scripts

### ISSUE THREAD

**Issue by edschembor** [neo4j/neo4j#3781]
If I understand correctly, the saved scripts in the browser are saved locally on the clients web browser. Are there any plans for a method to export selected saved scripts so that a bunch of them could be easily imported to another web browser? Or is the main method for doing so still manually moving them? (see http://stackoverflow.com/questions/23966160/neo4j-export-cypher-scripts-from-localhost7474-frontend-how-to)

Thanks!

**Comment by oskarhane** [comment]
This issue was moved to neo4j/neo4j-browser#132
