### ISSUE TITLE
Provide lucene-like faceted search capabilities

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#38]
@chillenious: 'See some discussion here: https://groups.google.com/forum/?fromgroups=#!topic/neo4j/FI0IwV626k8

The problem is that for some cases - in my case because I want to calculate facets - it can be useful to have direct access to index documents. Opening up a (read only) index directly on the FS isn't an option  as it may take a while before neo4j flushes (so stuff will be out of date, and might not even have a readable cache yet).

I have a work around that uses nodes and properties, but the overhead is unfortunately unacceptable for this case. I'd love to create a better solution, but need to somehow - doesn't have to be neat or generic - to be able to access index documents directly when I do a search. Currently, this is pretty much impossible due to the visibility of most of the involved classes.'

**Comment by janhoy** [comment]
> This will be addressed by the integrated indexing in upcoming 2.0 releases, I believe :)

Did this ever happen in 2.0? Please provide a documentation link...
