### ISSUE TITLE
Error while loading CSV (2.2 M02)

### ISSUE THREAD

**Issue by pducrot** [neo4j/neo4j#3806]
Hi, I get the following error message when with the following cypher command extracted from here: http://jexp.github.io/blog/html/simple_nlp_with_graphs.html
I'm pretty sure it worked with previous versions.

String didn't extract value for Mark[line:7, from:325, to:325]. For values which are optional please use tryExtract method instead

load csv from "https://dl.dropboxusercontent.com/u/14493611/one-ring.txt" as row fieldterminator "."
with row
unwind row as text
with reduce(t=tolower(text), delim in [",",".","!","?",'"',":",";","'","-"] | replace(t,delim,"")) as normalized
with [w in split(normalized," ") | trim(w)] as words
unwind range(0,size(words)-2) as idx
MERGE (w1:Word {name:words[idx]})
MERGE (w2:Word {name:words[idx+1]})
MERGE (w1)-[r:NEXT]->(w2)
  ON CREATE SET r.count = 1 ON MATCH SET r.count = r.count +1
Thanks
Pierre

**Comment by jexp** [comment]
Thanks for reporting it, it's an issue introduced in M02, we fixed it in the snapshot already will be available in the next milestone.

The blog post used 2.1.6.
