### ISSUE TITLE
no results if there is a trailing comma while using transactional cypher HTTP endpoint

### ISSUE THREAD

**Issue by manV** [neo4j/neo4j#3818]
I am trying this endpoint /db/data/transaction/commit using this json post payload 

```json
{
  "statements" : [ {
    "statement" : "match (n)-[]->(m) return n,m",
  } ]
}
```
this returns
```json
{
    "results": [],
    "errors": []
}
```
and if I try 
```json
{
  "statements" : [ {
    "statement" : "match (n)-[]->(m) return n,m"
  } ]
}
```
gives the result as intended.

In first case the payload is a perfectly valid javascript object so that shuld work, or neo4j doesn't support trailing comma on json payload then it should fail with some parsing error.

I am using version 2.1.6

**Comment by nigelsmall** [comment]
While trailing commas are supported in some languages - such as Python - the JSON specification makes no mention of them. Therefore, a valid payload cannot contain trailing commas.

**Comment by manV** [comment]
@nigelsmall should't there be something indicating that I have this problem with my payload?

**Comment by nigelsmall** [comment]
Yes, a better error response would be useful here.

**Comment by jakewins** [comment]
Verified that this has been resolved:

```
$ curl -XPOST -d'{"statements":[{"statement":"MATCH (n) RETURN n",}]}' -H'Content-Type:application/json' -H'Accept:application/json;xxstream=true;charset=UTF-8'  http://localhost:7474/dbdata/transaction/commit
{"results":[],"errors":[{"code":"Neo.ClientError.Request.InvalidFormat","message":"Unable to deserialize request: Unexpected character ('}' (code 125)): was expecting double-quote to start field name\n at [Source: HttpInputOverHTTP@736b1e7b; line: 1, column: 51]"}]}
```
