### ISSUE TITLE
Neo4jnstaller.BAT does not return a non-zero error code if it Java is not detected

### ISSUE THREAD

**Issue by glennsarti** [neo4j/neo4j#3823]
The Neo4jnstaller.BAT returns exit code 0 if Java is not installed.  This makes automating Neo4j installation difficult as you can't depend on the exit code to indicate that the installation was successful.

This is package I'm creating;
https://chocolatey.org/packages/neo4j-community/2.1.6

When the correct version of Java is installed the exitcode will come from the last SC.EXE command that's executed.

Environment:
Neo4j-community-windows.zip version 2.1.6 and 2.2.0-M2
Java - Not installed
Windows 8 or 8.1 - 64bit

Possible resolution:
https://github.com/neo4j/neo4j/blob/master/packaging/standalone/src/main/distribution/shell-scripts/bin/Neo4jInstaller.bat

As an example, Line 51 - replace
```
  if not "%javaHomeError%" == "" (
    echo %javaHomeError%
    call:instructions
    goto:eof
  )
```
with
```
  if not "%javaHomeError%" == "" (
    echo %javaHomeError%
    call:instructions
    exit /B 255
  )
```

This would return error code 255 to the caller

**Comment by benbc** [comment]
@glennsarti Since you've now replaced this script, I'm going to close this issue.
