### ISSUE TITLE
split function error in load csv command

### ISSUE THREAD

**Issue by afergadis** [neo4j/neo4j#3824]
I have a file for nodes that has multiple values in columns `en` and `el`. For some nodes there might be no values, eg the id 1 has no values in column `el`.

    id;en;el
    1;"United States of America;USA;U.S.A.";
    2;"Greece;Hellas;Hellenic Republic";"Ελλάδα;Ελλάς;Ελληνική Δημοκρατία"

Using neo4j version 2.1.5 I was able to import this nodes with the following command:

    LOAD CSV WITH HEADERS FROM "file:///home/aris/tmp/nodes.csv" as node FIELDTERMINATOR ';' CREATE(:Location {id: node.id, en: split(node.en, ";"), el: split(node.el, ";")});

Using neo4j version 2.2.0-M02 I get the following error:

    String didn't extract value for Mark[line:2, from:77, to:77]. For values which are optional please use tryExtract method instead

Obviously the lack of values in `el` column produces the error.

**Comment by tinwelint** [comment]
This has been fixed after M02, and will be included in the next release

**Comment by Davidmylove** [comment]
Or I was just ahead of my game today
