### ISSUE TITLE
Cannot authorize via REST API

### ISSUE THREAD

**Issue by seenickcode** [neo4j/neo4j#3844]
Using Neo4j Enterprise version 2.2.0-M02, I can't seem to authenticate.  I tried changing my token many times via ``http://neo4j.com/docs/2.2.0-M01/rest-api-security.html#rest-api-security-authorization-tokens``

See attached screenshots for an example.

![screen shot 2015-01-20 at 4 09 52 pm](https://cloud.githubusercontent.com/assets/75833/5826232/226b1e54-a0bf-11e4-8fb9-688d9de04c64.png)
![screen shot 2015-01-20 at 4 10 05 pm](https://cloud.githubusercontent.com/assets/75833/5826233/24a549ec-a0bf-11e4-9313-5f2e81ca52d1.png)

Thanks.

**Comment by seenickcode** [comment]
Going to try to reproduce via curl... seems like the HTTP client app I was using wasn't working correctly.

**Comment by seenickcode** [comment]
Ok, still having the same issue and showing an example with curl:

````
curl -X POST http://localhost:7474/db/data/transaction/commit \
 -H "Accept: application/json; charset=UTF-8" \
 -H "Content-Type: application/json" \
 -H "Authorization: Basic realm="Neo4j" cee35b356a500f6bfd640146b4f3a771" \
 --data '{
  "statements" : [ {
    "statement" : "CREATE (n) RETURN id(n)"
  } ]
}'

{
  "errors" : [ {
    "code" : "Neo.ClientError.Security.AuthorizationFailed",
    "message" : "Invalid authorization token supplied."
  } ],
  "authentication" : "http://localhost:7474/authentication"
}
````

**Comment by jexp** [comment]
You would have to use the token as the password and use uuencode (base64) on the string. Our use `curl -u ":token"`

````
curl -X POST http://localhost:7474/db/data/transaction/commit \
 -H "Accept: application/json; charset=UTF-8" \
 -H "Content-Type: application/json" \
 -u ":cee35b356a500f6bfd640146b4f3a771" \
 --data '{
  "statements" : [ {
    "statement" : "CREATE (n) RETURN id(n)"
  } ]
}'

{
  "errors" : [ {
    "code" : "Neo.ClientError.Security.AuthorizationFailed",
    "message" : "Invalid authorization token supplied."
  } ],
  "authentication" : "http://localhost:7474/authentication"
}
````

**Comment by seenickcode** [comment]
Cool, it works with ":<token>" but what did you mean as use uuencode on the string?  What string exactly?  

So were the not up to date or was I don't reading them correctly?:  http://neo4j.com/docs/2.2.0-M01/rest-api-security.html#rest-api-security-authorization-tokens

**Comment by jexp** [comment]
I mean the basic auth string, see:

http://en.wikipedia.org/wiki/Basic_access_authentication#Protocol

**Comment by seenickcode** [comment]
Gotcha, so it's the standard "username:password" but the Neo4j documentation is not clear on that (or at least I didn't get it to work).  Strongly recommended to update the documentation.  Thanks for your help Michal.

**Comment by seenickcode** [comment]
Didn't read carefully enough, you have to include the ':' when you base64 encode the password.
