### ISSUE TITLE
issue on link reference

### ISSUE THREAD

**Issue by antonio-castellon** [neo4j/neo4j#3851]
the webpage https://github.com/neo4j/neo4j/blob/master/RepositoryOverview.asciidoc 
returns `404 error` when you try to go to the neo4j-cypher link on : 

_neo4j-cypher_
_This module provides the Cypher Execution Engine, which allows users to query using the Cypher Query Language. As it is partly written in Scala, working with this module requires some extra setup as discussed [here](https://github.com/neo4j/neo4j/blob/master/community/cypher/README.txt)._

maybe it needs to be changed to the link : https://github.com/neo4j/neo4j/tree/master/community/cypher/cypher/README.txt

BR,

**Comment by nawroth** [comment]
That's true. I think the document need a refresh in general.
