### ISSUE TITLE
Manual doc images only avaiable on Mac environment

### ISSUE THREAD

**Issue by antonio-castellon** [neo4j/neo4j#3855]
Dear Neo4j developers,

I try to understand how is function internally Neo4j and how was my surprise when I try to read the files on the folder: `\neo4j\manual\docs` , this files are only avaiable in a propietary format from the product [Omnigraffle](https://www.omnigroup.com/omnigraffle) that's only available for Mac and iPad environment. Please, could you consider to export this documentation to another more common format files? like any images or any Open Office document (Pdf, ...) ?

Thanks in advance
Antonio

**Comment by nawroth** [comment]
I think the content of those have made it into the manual in a different format, so they are really not interesting any more. And the rest of the files in there are information about the documentation tooling, not about Neo4j.
