### ISSUE TITLE
docsBuild target throws an exception in "Cypher Reference Card"

### ISSUE THREAD

**Issue by antonio-castellon** [neo4j/neo4j#3858]
Dear Neo4j developers,

I trying to generate all documentation from Neo4j using different commands described into the `readme.asciidoc` files, but always throws with the same exception:

```
[INFO] --- exec-maven-plugin:1.2.1:exec (execute-asciidoc-html5) @ neo4j-cypher-refcard ---
#
#
# Setting correct file permissions and moving source code.
# Copy configuration, so we can combine different config sources easily.
#
#
find /c/DEV/github/neo4j/manual/refcard/target/tools \( -path '*.py' -o -path '*.sh' \) -exec chmod 0755 {} \;
File not found - *.py
make: *** [initialize] Error 2
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

I try to take a look into the script `refcard\target\tools\make\initialize.make` where is the `find` command, but everything looks only for Linux environments (I'm using Windows). It's true?

Regards,
Antonio

**Comment by nawroth** [comment]
Right, we haven't set up a build that works under Windows. There's a plan to do so, getting rid of the dependencies on  `make`, `python`, and `bash`. But it will take some time to get there. For now, I recommend setting up a virtual Ubuntu box to build the docs.

**Comment by antonio-castellon** [comment]
Ok, and ... exists any possibility to download from any repository the pdfs generated? I need some documentation to analyze how to implement a new feature into Cypher Language [issues/1695#issuecomment-70860258](https://github.com/neo4j/neo4j/issues/1695#issuecomment-70860258)

Thanks in advance for your help
Antonio

**Comment by nawroth** [comment]
You'll get the currently latest PDF of the manual here:
http://neo4j.com/resources/neo4j-docs-pdf/?version=2.2.0-M02

Daily builds are only available as HTML, in case you want the very latest version:
http://neo4j.com/docs/snapshot/

**Comment by antonio-castellon** [comment]
Thanks a lot nawroth, 
I was excepted to find something like `UML` and other `SDD`'s. But Probably It's it's hidden for the rest of the community. Do you known who is the person responsable from the `Cypher Engine`? I want to contact with him in order to clarify the best method to add a new function feature into the `Cypher Language`. At the moment is clear how to extends Neo4j, but really I want to extend the Language from Cypher.

**Comment by nawroth** [comment]
The manual is for users rather than people who want to extend Neo4j.

I suggest you ask your question(s) over at https://groups.google.com/forum/#!forum/neo4j
There's people who know the code behind Cypher well both in the community and in the Neo4j developer team.

**Comment by antonio-castellon** [comment]
Ok ;) Thanks for your time!
