### ISSUE TITLE
Cypher: errors ghost nodes switching from 1.9.M01 to 1.9.M02 or 1.8.1

### ISSUE THREAD

**Issue by flipside** [neo4j/neo4j#386]
I'm trying to switch from 1.9.M01 to 1.9.M02 or 1.8.1 but I'm getting a lot of errors in my cypher queries that involve deleting nodes. My tests were all green before so I'm not sure what changed between versions.

Here's an example (normally paramaterized). The disappearing node is the combo, not the dimension.

START dimension = node:dimensions("dimension_id:77292")
MATCH dimension<-[r1?:DESCRIBES]-combo<-[r2?]-(), descriptor<-[r3?:COPY_OF]-combo-[r4?:USES]->()
WHERE r2 is null AND NOT(combo.descriptor_id? IN([1234, 12352]))
DELETE r1, combo, r3, r4
WITH dimension
MATCH dimension<-[?:DESCRIBES]-combo<-[r?]-(), combo-[?:USES]->template
RETURN dimension, combo, COUNT(DISTINCT r) as combo_inbound, template, COUNT(DISTINCT combo) as template_inbound

"Error: Node[119] not found"

The node is getting deleted, but it is also getting 'found' only to be surprised it's not really there. Help?

**Comment by jakewins** [comment]
This was an issue with transaction state management, which has been resolved.
