### ISSUE TITLE
populate data browser query field from url

### ISSUE THREAD

**Issue by collin** [neo4j/neo4j#3861]
For debugging purposes it'd be great to be able to log out a url like...
```
http://neo4jhost:7474/browser/?query=MATCH (n:Label)-[:relationship]->(m:label {property:'value'} return n, m
```
And be able to just open that url in a browser and have the data browser automatically run that query.
Would that be easy to implement in the data browser?

**Comment by jexp** [comment]
You can do that with the Neo4j console. 

http://console.neo4j.org?init=create%20data%20query&query=your%20query

**Comment by collin** [comment]
Is there a version of that console that runs against my local neo4j server?

Even in that case it would be nice to have the same feature in the browser. The browser lets you expand node relationships in the graph view, which is very nice for walking around the data while debugging.

**Comment by yuruki** [comment]
This would allow user to execute a query and show the resulting graph simply by clicking on a link.

We have been missing this feature since we started using Neo4j browser.

**Comment by jessmartin** [comment]
:+1:! Would love to have this feature as well.

**Comment by oskarhane** [comment]
This issue was moved to neo4j/neo4j-browser#133
