### ISSUE TITLE
Transaction (and if any, other classes) should implement Closeable instead of AutoCloseable

### ISSUE THREAD

**Issue by ceefour** [neo4j/neo4j#3869]
`Closeable` works with Groovy's `withCloseable`.

Besides, `Closeable` (in JDK7) already implements `AutoCloseable` so there should be no problem for Neo4j.

**Comment by jakewins** [comment]
`Closable` is an IO API, it throws `IOException`. `AutoClosable` was explicitly introduced for general closable resources. 

Groovy not supporting AutoClosable is not a compelling enough argument to force all our users to handle `IOException`s that will never be thrown, this sounds more like an issue with Groovy.

Closing this as a wontfix.
