### ISSUE TITLE
(2.2.0M02, bug) Browser / Saved scripts: only adds the first of dragged files

### ISSUE THREAD

**Issue by mindrones** [neo4j/neo4j#3875]
In the Neo4j browser, "Saved scripts" tab:
- add own folder
- switch to the Finder
- drag 2 .cql files to "Drag Cypher script to import"
- -> I get only one in scripts listed in my folder

The same happens in Chrome and Firefox.

*System*
- Neo4j 2.2.0 M02
- Mac OS X 10.7.5
- Chrome 40.0.2214.91
- Firefox 35.0.1

**Comment by oskarhane** [comment]
Thanks, this is how it was implemented from the beginning as far as I can see. 
I'll add it in the backlog so it gets fixed.

**Comment by mindrones** [comment]
Ah ok, thanks!

**Comment by jeffmay** [comment]
This would be a useful feature as we have a lot of saved queries and since the tool doesn't support adding a single file with multiple queries, it would be nice to be able to drag and drop multiple files.

**Comment by oskarhane** [comment]
This issue was moved to neo4j/neo4j-browser#134
