### ISSUE TITLE
(feature request) Browser: query assistant

### ISSUE THREAD

**Issue by mindrones** [neo4j/neo4j#3876]
When writing clauses in the browser "shell" I'd like be able to **autocomplete clauses** pressing TAB:
- type `MA`
- press `TAB`
- completes to `MATCH`

Possibly keeping the current capitalization (`ma` + `TAB` => `match`, `MA` + `TAB` => `MATCH`)

**Comment by mindrones** [comment]
Given nodes with property `type` on them, another use case would be:
- type `match (n) set n.ty`
- press `TAB`
- completes to `match (n) set n.type`

In case we have multiple properties starting with `ty`, pressing `TAB` multiple times would alternate among possible properties names and the original string (`ty`):
- type `match (n) set n.ty`
- press `TAB`
- update to `match (n) set n.type`
- press `TAB`
- update to `match (n) set n.typos`
- press `TAB`
- back to `match (n) set n.ty`

**Comment by oskarhane** [comment]
Yes, we definitely want to have autocompletion for the browser.  
We're having discussions on how to implement it and appreciate all input.

**Comment by mindrones** [comment]
Another nice feature would be to autocomplete labels and relationship types.

If our DB has node labels ANIMAL/PERSON and relationship types OWNS/LOVES:

*Node labels*
- type `match (n:`
- press `TAB`
- completes to `match (n:ANIMAL`
- press `TAB`
- completes to `match (n:PERSON`
- type `match (n:PERSON:`
- press `TAB`
- completes to `match (n:PERSON:ANIMAL`

*Relationship types*
- type `match (n)-[r:`
- press `TAB`
- completes to `match (n)-[r:LOVES`
- press `TAB`
- completes to `match (n)-[r:OWNS`

**Comment by mindrones** [comment]
Another nice feature would be useful to assist the user building the query to what we can put next.
If we use `TAB` to complete words, I'd use two fast `TAB` (like a double click), or maybe using arrows (`^` + `->`?) to tell the shell we wanna see what's next.

> In the examples below I use `|` to indicate the position of the cursor (not a pipe).

- type `match (n:``|`
- press `TAB`
- completes to `match (n:ANDROID``|`
- press `TAB`
- completes to `match (n:ANIMAL``|`
- press `^` + '->`
- completes to `match (n:ANIMAL:``|`
- press `^` + '->`
- completes to `match (n:ANIMAL {``|`
- press `^` + '->`
- completes to `match (n:ANIMAL)``|`

If we change our mind we should be able to use the same pattern.

- we have `match (n:ANIMAL``|`
- press `^` + '->`
- we get `match (n:ANIMAL:``|`
- press `^` + '->`
- we get `match (n:ANIMAL {``|`
- press `^` + '<-`
- we get `match (n:ANIMAL:``|`
- press `^` + '<-`
- we get `match (n:ANIMAL``|`

**Comment by mindrones** [comment]
Another useful feature would be to **show if labels/types/properties we're typing exist**.

> In the examples, the DB has node labels ANDROID/ANIMAL/PERSON and relationship types OWNS/LIKES/LOVES; PERSON nodes have properties name/surname

**Labels and relationship type**

- type `match (a:ANDROID)-[r:DREAMS]-(s:SHEEP)`
- the strings `DREAMS` and `SHEEP` gets a red background-color to indicate they don't exist in the DB

**Properties**

- type `match (p:PERSON {ram: '8Gb'})`
- the string `ram` gets a red background-color to indicate that in the current DB there aren't nodes labeled PERSON with a property named `ram`

**Comment by oskarhane** [comment]
This issue was moved to neo4j/neo4j-browser#135
