### ISSUE TITLE
(2.2.0M02, bug) Browser: query output panels bugged in Firefox

### ISSUE THREAD

**Issue by mindrones** [neo4j/neo4j#3877]
After doing the same query in Chrome and Firefox I get two completely different result panels.
Even if the one in Firefox is evidently bugged, it also shows features that are not present in Chrome, like a green label "Cypher" before the query string.

The most prominent bug is that the result panel is too wide, hence **I can't delete it**.

Also, the graphs in the 2 browsers have different styles.

**Chrome**
![neo4j_browser_chrome40_ok](https://cloud.githubusercontent.com/assets/1309648/5915906/6990404c-a60b-11e4-9df1-afb370bb04d0.png)

**Firefox**
![neo4j_browser_firefox35_bug](https://cloud.githubusercontent.com/assets/1309648/5915917/82829abe-a60b-11e4-8c0d-19db5d622eb1.png)

*System*
- Neo4j 2.2.0 M02
- Mac OS X 10.7.5
- Chrome 40.0.2214.91
- Firefox 35.0.1

**Comment by mindrones** [comment]
Confirming this also for 2.2.0-M03

**Comment by oskarhane** [comment]
@mindrones Thanks for the report! This looks like a cache problem. If you look at the top of the frame it says CYPHER on the firefox version.  
That title is gone in 2.2, as you can see in the Chrome version.

Firefox can be VERY aggressive when caching and I would suggest that you try to refresh without cache (Command+Shift+R).  

We change the name of js and css files for every release to prevent cache problems, but when the web browser loads the old html file that has link to the old css/js files that are also cached, there's not much we can do :)

**Comment by mindrones** [comment]
Indeed it works, uhm.. I usually do hard-refresh (Command+Shift+R) when I check this sort of things, but I have recently cleaned up Firefox's cache via preference panel so maybe that's why it works now.

Oh btw, since I'm a D3 developer, maybe I can help with the browser viz :)
Do you have a public list of "nice to have" features?

Thanks!

**Comment by mindrones** [comment]
Also, any reason why the graphs in the 2 browsers have different styles?

**Comment by oskarhane** [comment]
Great!  
There's no public list of nice-to-have features for the moment.  

Cool that you know d3! We could always use some optimizations so we can draw bigger graphs and still keep 60fps :) 

Regarding the graph style, it's not stored in the database but in the client (your web browser) and can therefore be different from browser to browser.

**Comment by mindrones** [comment]
> We could always use some optimizations so we can draw bigger graphs and still keep 60fps :) 

OK will think about it and possibly will come back with a PR :)
