### ISSUE TITLE
Unable to access jarfile ...\windows-service-wrapper-*.jar

### ISSUE THREAD

**Issue by kkurni** [neo4j/neo4j#391]
Hi,

I get this error on my windows 8 machine.

I try using 1.8 and 1.9 but still get the same error when calling neo4j.bat start

Any hints ?

Thanks

**Comment by tinwelint** [comment]
Didn't we remove the windows wrapper thing as a whole recently?

**Comment by chrisvest** [comment]
Closing because the Windows scripts have since been rewritten in PowerShell.
