### ISSUE TITLE
2.2M03 - Error message regression for syntax error

### ISSUE THREAD

**Issue by ikwattro** [neo4j/neo4j#3910]
Hello,

This regards the following query : 

```
MATCH (fork:Fork)
MATCH p=(user)-[:DO]->(fe)-[:FORK]->(fork)-[:FORK_OF]->(repo)
<-[:PR_ON_REPO]-(pr)<-[:PR_OPEN]-(pre)-[:DO]-(user)
-[:DO]->()-[:FORK]->(fork)
WITH p, (pre.time - fe.time) as diffs
RETURN count(p), avg(diffs);
```

Sometimes, when you copy paste this query from medium to the neo4j browser for e.g., the `minus sign` is replaced by a `long dash`.

So executing it will trigger an error.

The error in 2.2M03 is simply : 

```
Conversion = '''
Neo.DatabaseError.Statement.ExecutionFailure
```

However in 2.1.6, the error is more accurate and you know exactly where you have a syntax error : 

```
Invalid input '—': expected whitespace, comment, '.', node labels, '[', "=~", IN, IS, '^', '*', '/', '%', '+', '-', '<', '>', "<=", ">=", '=', "<>", "!=", AND, XOR, OR or ')' (line 5, column 20)
"WITH p, (fe.time — pre.time) as diffs"
```

The same happens for some queries where you forget a space between a node closing parenthesis and a new statement (can happens when you build queries dynamically in your app)

**Comment by cleishm** [comment]
Hi @ikwattro!

Can you supply me the query including the long dash?

Cheers,
Chris

**Comment by ikwattro** [comment]
Sure, here it is : 

```
MATCH (pre:PullRequestEvent)
MATCH (user)-[:DO]->(pre)-[:PR_MERGE]->(pr)-[:PR_ON_REPO]->(repo)
MATCH p=(user)-[:DO]->(forkEvent)-[:FORK]->(fork)-[:FORK_OF]->(repo)
WITH (pre.time — forkEvent.time) as diff
RETURN avg(diff);
```

**Comment by cleishm** [comment]
We found the issue - that's for supplying the full query, it was very helpful!

**Comment by ikwattro** [comment]
Thanks to you for fixing it

**Comment by ikwattro** [comment]
I guess I misunderstood you only wanted the query portion containing the long dash, my apologies

**Comment by stuaccountongithub** [comment]
I've been stumped by exactly the same issue for a while. Thanks
