### ISSUE TITLE
[Idea] Support referencing saved scripts in console

### ISSUE THREAD

**Issue by bruth** [neo4j/neo4j#3913]
I have a tendency to build up a bunch of small queries in the console while I am data modeling. The current way to emulate a series of queries is by clicking the play button on each saved script in order. I thought it would be nice to be able to reference existing saved scripts by name to compose a sequence of queries.

```cypher
// Referenced existing saved scripts.
// browser would send this request first
@import "Create nodes"
@import "Create edges"

// Inline query
MATCH ...
```

**Comment by jexp** [comment]
Are those included queries always setup queries?

I wonder if this https://github.com/neo4j-contrib/graphgist-cms/issues/57 would help you? Then you could document your use cases as a graphgist and import them in one click, optionally executing more queries of te

**Comment by bruth** [comment]
The feature you linked to feels like a different workflow than what this idea is about. This is more of a convenience while working inside of the browser console. As the title stated, this was purely an idea, not necessarily a feature request.

**Comment by oskarhane** [comment]
Thanks for the idea, we're rethinking some parts of the ux and will keep this in mind.
