### ISSUE TITLE
Labels created with the BatchInserter don't obey set semantics

### ISSUE THREAD

**Issue by ccondit** [neo4j/neo4j#3917]
`BatchInserter` should defensively respect set semantics of node labels. Having duplicate labels on nodes isn't logical. 

When adding labels using the embedded API the following holds:

```
node.addLabel(LABEL);
node.addLabel(LABEL);
node.getLabels(); // equals {LABEL}
```

however `BatchInserter` allows the following:

```
inserter.setNodeLabels(nodeId, LABEL, LABEL);
inserter.getNodeLabels(); // equals {LABEL, LABEL}
```

and further, after the resulting graph has been loaded by the embedded API:

```
node.getLabels(); // equals {LABEL, LABEL}
```

Duplicate labels should be ignored by the batch inserter.

**Comment by klaren** [comment]
This was fixed in #3962
