### ISSUE TITLE
BatchInserter doesn't order label IDs causing strange behavior in the embedded api

### ISSUE THREAD

**Issue by ccondit** [neo4j/neo4j#3919]
`BatchInserter` adds labels (and returns labels) independently of the label ID ordering. The embedded API, however, expects the label IDs to be sorted when executing `node.hasLabel()` since it uses a binary search to determine if a node has a label. This leads to the following inconsistent behavior when label order is switched using the `BatchInserter`:

```java
public class EmbeddedHasLabelProblem {

  Label foo = DynamicLabel.label("foo");
  Label bar = DynamicLabel.label("bar");

  @Test
  public void embeddedHasLabelShouldHaveConsistentState() throws Exception {
	  // GIVEN
      Path path = Files.createTempDirectory("neo4j-batch-label-test");
      BatchInserter inserter = BatchInserters.inserter(path.toFile().getAbsolutePath());
    
      // WHEN
      long nodeId = inserter.createNode(Collections.<String, Object>emptyMap(), foo, bar);
      inserter.setNodeLabels(nodeId, bar, foo);
      inserter.shutdown();
      GraphDatabaseService graphDb = new GraphDatabaseFactory().newEmbeddedDatabase(path.toString());
      
      // THEN
      try (Transaction tx = graphDb.beginTx()) {
    	  Node node = graphDb.getNodeById(nodeId);
      
    	  assertThat(node.getLabels(), containsInAnyOrder(foo, bar)); // PASS
    	  assertThat(node.hasLabel(bar), is(true)); // PASS
    	  assertThat(node.hasLabel(foo), is(true)); // FAIL
    	  tx.success();
      }
      graphDb.shutdown();
      // Delete path
  }

}
```

`node.getLabels()` returns the labels as expected but `hasLabel()` yields inconsistent results because the array of label IDs is not sorted. Note that this doesn't affect `BatchInserter` or `BatchInserters.batchDatabase` since they both iterate to check label existence. This is only a problem when switching the order of labels with the batch api, loading the graph with the embedded api, and checking for label existence.

I'll submit a possible pull request that sorts labels at addition time, but this may not be the best solution. I'm not familiar with the mechanics of the `shutdown()` method. It's possibly better to sort all the labels when running the `labelUpdateVisitor`.

I'm also not sure of the best way to unit test this (without creating a temporary graph on disk) since it crosses the boundary between the batch and embedded api.

**Comment by jakewins** [comment]
Fixed in https://github.com/neo4j/neo4j/pull/3962
