### ISSUE TITLE
<script> tags in a property are executed by the browser

### ISSUE THREAD

**Issue by cskardon** [neo4j/neo4j#3946]
So, to replicate, in the web browser:

`CREATE (n:ScriptTest {Value:'<script>window.alert(\'test\');</script>'})`

Then

`MATCH (n:ScriptTest) RETURN n`

You should see an alert box.

I presume this *shouldn't* be happening?

**Comment by oskarhane** [comment]
Thanks @cskardon, what version of Neo4j are you using?

**Comment by cskardon** [comment]
2.1.4 running on Windows

**Comment by oskarhane** [comment]
@cskardon A patch for this was released with 2.1.5. See commit: https://github.com/neo4j/neo4j/commit/71aa3ed67d7d7bac1bf5b0a95a83dd84b3afb40a
