### ISSUE TITLE
[feature request] hooks, watchers or observer for supporting reactivity.

### ISSUE THREAD

**Issue by wuxianliang** [neo4j/neo4j#3955]
When using Neo4j with Meteor.js, we found the difference between Neo4j and Mysql/Redis/MongoDB.
We need hooks, watchers or observer or something like that to keep watching the change of data in Neo4j as we do in other database. With this feature, we can change the data in Neo4j Browser, then the front end data change reactively without need of refreshing browser.

Or is there a solution right now for this kind of reactivity? Thank you.

**Comment by cleishm** [comment]
Hi @wuxianliang,

Please note that this issue tracker is for bugs and issues in the codebase of Neo4j. For questions on using Neo4j or feedback and requests, please raise questions in the [Google Group](http://groups.google.com/group/neo4j).

(That said, you might like to look at http://neo4j.com/docs/stable/transactions-events.html )

Cheers!
Chris

**Comment by jexp** [comment]
Hey, just to let you know there is a fresh meteor driver for Neo4j, which implements reactivity by using an intermediate datasource, see more here: http://neo4j.com/developer/javascript/#_meteor_js

And for a change-feed you can also check: http://graphaware.com/neo4j/2014/08/27/graphaware-neo4j-changefeed.html

**Comment by wuxianliang** [comment]
Thank you! @cleishm

**Comment by wuxianliang** [comment]
Dear @jexp 
I came from https://github.com/VeliovGroup/Meteor-Leaderboard-Neo4j/issues/14
and I found another way to keep reactivity but need helps.
https://github.com/hharnisc/python-meteor/issues/16

By the way I like your blog. Thank you very much!

**Comment by dr-dimitru** [comment]
@wuxianliang you always welcome to ask me
