### ISSUE TITLE
Regression in WITH collection AS x, neo4j community 2.2.0-M03

### ISSUE THREAD

**Issue by redsk** [neo4j/neo4j#3994]
Hi, there seems to be a regression in neo4j community 2.2.0-M03 from 2.2.0-M02.
After loading the standard Movies Graph in version 2.2.0-M03 and issuing the following query from the browser:

WITH [0, 154] AS x
MATCH (n) WHERE ID(n) IN x
MATCH (m) WHERE ID(m) IN x
MATCH paths = allShortestPaths((n)-[*..3]-(m))
RETURN paths

I get the following error:
Neo.DatabaseError.Statement.ExecutionFailure

Failed to create a plan for the given QueryGraph QueryGraph(Set(),Set(IdName(n), IdName(m)),Set(IdName(x)),Selections(Set(Predicate(Set(IdName(m), IdName(x)),In(FunctionInvocation(FunctionName(ID),false,Vector(Identifier(m))),Identifier(x))), Predicate(Set(IdName(n), IdName(x)),In(FunctionInvocation(FunctionName(ID),false,Vector(Identifier(n))),Identifier(x))))),List(),Set(),Set(ShortestPathPattern(Some(IdName(paths)),PatternRelationship(IdName(  UNNAMED108),(IdName(n),IdName(m)),BOTH,List(),VarPatternLength(1,Some(3))),false)))

Conversely, if I issue:

MATCH (n) WHERE ID(n) IN [0, 154]
MATCH (m) WHERE ID(m) IN [0, 154]
MATCH paths = allShortestPaths((n)-[*..3]-(m))
RETURN paths

it works correctly. Moreover, both queries work as expected with version 2.2.0-M02.

**Comment by jakewins** [comment]
Verified that this has been resolved: http://console.neo4j.org/r/ur7j3u
