### ISSUE TITLE
code style (formatter)

### ISSUE THREAD

**Issue by rpau** [neo4j/neo4j#4009]
Hi, 

I am the project leader of walkmod (walkmod.com), an open source tool to apply code conventions and I am trying to understand how can I help to the most visible open source Java projects and improve walkmod.

I have forked the project and I have tried to apply the formatter of https://github.com/neo4j/neo4j.github.com/blob/master/code-style/neo4j-eclipse.xml into your code base and there are many corrections to apply and I would like to understand why: developers forget to configure the IDE? The formatter is obsolete? Or you don't like how eclipse produces the code?

I am not just focused on the formatting options, but also remove dead code or producing "patterns of code" automatically. Would you like that I help you with the incoming pull requests or commits?

Thank you very much for your time.

**Comment by jakewins** [comment]
This is partially because the code style has changed over time, and we didn't reformat the older parts of the code base when we did, as well as us not being particularly strict in enforcing code style on commits. This may change if our core dev team chooses to adopt a stricter position on code style.

**Comment by rpau** [comment]
Hi @jakewins ,

Thank you for your information. Are you interested into a PR with a walkmod.xml to start to get a list of code conventions? We can start deleting dead code without affecting the formatter settings of the affected files.
