### ISSUE TITLE
Neo4j-2.2.0-M04 NotInTransactionException while loading

### ISSUE THREAD

**Issue by pducrot** [neo4j/neo4j#4013]
I'm trying to upload data into neo4j-community-2.2.0-M04. Upload is down from several CSV files using shell and cypher scripts. The exact same script as used to successfully upload data into neo4j-2.1.7 are used. Neo4j 2.1.7 uploads the 201589 nodes and 2163494 edges in 9 minutes.

Neo4j-2.2.0-M04 properly uploads the first three types of nodes (26k nodes) but hence fails uploading the last two files, returning: "NotInTransactionException: The statement has been closed.".

Cypher command is the following:

CREATE INDEX ON :Fingerprint(Code);
CREATE INDEX ON :Fingerprint(Size);
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM 'mypath_to_file.csv' as csvLine FIELDTERMINATOR '\t' MATCH (m:Molecule {NSC: toInt(csvLine.NSC)}) MERGE (f:Fingerprint {Code: toInt(csvLine.Identifier), Size: toInt(csvLine.Distance)}) CREATE (m) -[:hasBit {Type: 'SCFP6', Atoms: csvLine.Atoms}]-> (f);
Data in the cvs file look like this:

NSC Identifier  Distance    Atoms   Substructure
128 1   0   1   [*]C(=[*])[*]
128 0   0   2   [*]C
128 13  0   3   [*]=O
128 9   0   4   [*]N([*])[*]
128 3   0   5   [*][c](:[*]):[*]
128 17  0   12  [*]S[*]
128 1256995004  2   1 2 3 4 [*]N([*])C(=O)C
128 136627117   2   1 2 [*]C(=[*])C
128 1311071855  2   1 3 [*]C(=O)[*]

I can upload properly the first 999 rows of the file, it fails with the first 1000. Row 1000 is the following:
1163	1	0	2	[]C(=[])[*]

It doesn't seem to be much different from the others.

Please don't hesitate if you need addition information of example files and scripts.

**Comment by pducrot** [comment]
One additional observation, with the second files, which has nothing to do with the one described above, upload also fails with the first 1000 lines and not with the first 999.

**Comment by pducrot** [comment]
Looking more deeply in the cypher queries involved, I see that all queries that worked properly with both neo4j 2.1.7 and 2.2.0-M04 where simple node or edge creation such as:
LOAD CSV... CREATE (n:Label {Property: csv.Property}) RETURN count(*);
LOAD CSV... MATCH (a:LabelA {Name: csv.NameA}), (b:LabelB {Name: csv.NameB}) CREATE (a) -[:Type {Property: csv.Property}]-> (b);

Whereas the two cypher queries that work with neo4j2.1.7 and fail with 2.2.0-M04 are involving pattern creations such as the one depicted above: MATCH (a...) MERGE (b:Label {some props}) ON CREATE SET some props to b CREATE (a) -[:Type { some props }]-> (b);

Hope this helps identifying the issue.
Pierre

**Comment by ingramleedy** [comment]
Having the same issue when using COMMIT, around 669 lines of import. Any updates?

**Comment by jexp** [comment]
Sorry for the issue.
Should be fixed here, will be released with the next release (RC1)

https://github.com/neo4j/neo4j/pull/4026

**Comment by pducrot** [comment]
Issue has been addressed in neo4j 2.2.0-RC01. Full load of 20158 nodes and 2163494 edges in 3 minutes vs 9 minutes with neo4j 2.1.7.
