### ISSUE TITLE
Neo4jshell doesn't show cursor when pressing left or right arrow key in Neo4j Windows

### ISSUE THREAD

**Issue by s101d1** [neo4j/neo4j#4050]
For neo4j windows version (I'm using v2.1.7), in the neo4jshell session, you can't see the cursor when the cursor is moved by pressing or holding left or right arrow key. In this case it's very hard for me to position the cursor.

**Comment by craigtaverner** [comment]
Neo4j-shell has been deprecated since Neo4j 3.0 and will be entirely removed from the product in the next release.
