### ISSUE TITLE
Neo4j does not start database from  2.2.0-M01 to 2.2.0-M4 

### ISSUE THREAD

**Issue by kschwidder** [neo4j/neo4j#4063]
I have migrated from 2.1.6 to 2.2.0-M01 and wanted to use M4 instead. However the database does not start due to the following error in the graphdb log !

'neostore.nodestore.db' has a store version number that we cannot upgrade from. Expected 'v0.A.3' but file is version 'NodeStore v0.A.4'

Any help highly appreciated !

**Comment by jexp** [comment]
Hi Kai,

unfortunately there is no migration between milestones. Did you update your db in 2.2.0-M01 or not? There were some changes in the index representation.

I wrote a tool a while  ago that you could try to copy your data

https://github.com/jexp/store-utils/tree/revert-store

**Comment by kschwidder** [comment]
I will give it a try. When the final release will be announced would it be possible to leverage the database of the given milestone ? This is really critical in our environment as we test new features which we do not have in the older releases :-)

**Comment by jakewins** [comment]
Milestones are unfortunately exclusively for feature evaluation and feedback, there are no guarantees whatsoever that upgrades or migrations are possible.

The best approach here is likely to use the Neo4j shell or similar to export the M01 database and then import it back via the shell for the GA.
