### ISSUE TITLE
Neo4j 2.1.7 regression: transactional REST format hyperlinks

### ISSUE THREAD

**Issue by aseemk** [neo4j/neo4j#4076]
Hi folks,

Neo4j 2.1.7 seems to have regressed in the REST format for transactional endpoint responses.

To repro, send the following to `POST /db/data/transaction/commit`:

```json
{
    "statements": [{
        "statement": "START r=rel(*) RETURN r LIMIT 1",
        "resultDataContents": ["REST"]
    }]
}
```

It's a simple example query to just return one relationship.

The result in 2.1.7 is now:

```json
{
    "errors": [], 
    "results": [
        {
            "columns": [
                "r"
            ], 
            "data": [
                {
                    "rest": [
                        {
                            "data": {}, 
                            "end": "http://localhost:7474/db/data/transaction/commitdb/data/node/44", 
                            "metadata": {
                                "id": 18, 
                                "type": "follows"
                            }, 
                            "properties": "http://localhost:7474/db/data/transaction/commitdb/data/relationship/18/properties", 
                            "property": "http://localhost:7474/db/data/transaction/commitdb/data/relationship/18/properties/{key}", 
                            "self": "http://localhost:7474/db/data/transaction/commitdb/data/relationship/18", 
                            "start": "http://localhost:7474/db/data/transaction/commitdb/data/node/21", 
                            "type": "follows"
                        }
                    ]
                }
            ]
        }
    ]
}
```

Notice how all the hypermedia URLs are `.../db/data/transaction/commitdb/data/...` when they should be just `.../db/data/...` instead.

Unfortunately, 2.1.7 has shipped, so this ship has sailed (no pun intended :smile:), so drivers will need to be robust to this. But might be good to fix anyway.

Hope this helps!

**Comment by aseemk** [comment]
Just to be clear, the `commitdb` shows this is clearly a bug. Concatenated `/db/data/transaction/commit` with `db/data/...` (no leading slash).

**Comment by jexp** [comment]
Hey @aseemk sorry for the mess.

I think this issue a duplicate of https://github.com/nigelsmall/py2neo/issues/389
and should be fixed here:
https://github.com/neo4j/neo4j/pull/3968

Please confirm.

Will make it in the next release.

**Comment by aseemk** [comment]
Yes, that's it. Thanks! That's great.
