### ISSUE TITLE
Writes - how scale them up? (2.2.0-M04)

### ISSUE THREAD

**Issue by FylmTM** [neo4j/neo4j#4078]
Hi,

I wrote unmanaged extension for my specific task. What it does:
* Takes data
* Serialize them
* Persist everything in single transaction

About data - in consists of N units. Each unit is tree of ~11000 nodes. 
So, I persist 11000 nodes in one transactions.

Then, in example, I have 15000 such units. And i want to persist them in Neo4j as fast, as possible.
Currently my tests leads me to 15 units (transactions) per second. Looks like that Neo4j can't make more writes.
This is ~165000 nodes/sec (connected with relationships).
All 15000 units can be persisted in 17 minutes.

Simplified version of code that I use now in unmanaged extension:
```java
@Path("/sync")
public class SyncResource {
    protected final GraphDatabaseService db;
    public SyncResource(@Context GraphDatabaseService db) {
        this.db = db;
    }

    @POST
    @Path("/simple")
    public Response simpleNetworkSync(final InputStream stream) {
        TreeNode treeNode = ... // convert stream to tree

        try (Transaction tx = db.beginTx()) {
            persistTreeNode(treeNode);
            tx.success();
        }
    }

    private void persistTreeNode(TreeNode treeNode) {
        Node node = constructNode(treeNode); //convert to Neo4j node

        for (TreeNode childTreeNode : treeNode.getChildren()) {
            Node childNode = persistTreeNode(childTreeNode);
            node.createRelationshipTo(childNode, Relationships.CHILDREN);
        }

        return node;
    }

    private Node constructNode(TreeNode treeNode) {
        Node node = db.createNode();
        // node filled with data here
        return node;
    }
}
```
------
Question is - can I make this faster? Maybe there is some batch operations, that I can use?

**Comment by jexp** [comment]
Best to ask such questions on stack-overflow or the google group.

Just parallelize your calls. 

As I would _not_ recommend starting new threads in the extension,
I'd split up the tree-nodes on the client-side and do one http cal per tree-node.

Also I presume the JSON that you have to parse is pretty large, so parsing it to a single TreeNode will take a lot of time on it's own.
