### ISSUE TITLE
Neo4j-2.2.0-M04 NotInTransactionException while loading error

### ISSUE THREAD

**Issue by rocketman4u** [neo4j/neo4j#4122]
I have the same error as this:
http://stackoverflow.com/questions/28515027/neo4j-2-2-0-m03-notintransactionexception-while-loading 

I am using Milestone 4, the above link shows it was an issue also on M03.

I can load a sample file of 10 records, but when I try to load my entire CSV (millions of records), I get the error.

I don't see anything in my console log near the timestamp of the error.  

I am going to break the file apart and try it in chunks to see if that helps.

Thanks,
Jeff

**Comment by jexp** [comment]
Sorry, there was a bug introduced in M04 but it will be fixed in RC1 which is due this week. 
If you leave off periodic commit or replace merge with create it should work in M04

**Comment by rocketman4u** [comment]
Cool, thank you!
Last night I tried a few things and finally tried it without the periodic commit. It worked, but it just takes longer to load such a large file.  It's good to know that is also what you recommend.

Thank you.

I'm looking forward to RC1.  :-)
