### ISSUE TITLE
Returning array with hash breaks gremlin

### ISSUE THREAD

**Issue by elado** [neo4j/neo4j#413]
Try on the web console, http://localhost:7474/webadmin/#/console/http

```
# this is fine
http> POST /db/data/ext/GremlinPlugin/graphdb/execute_script { "script": "1" }
==> 200 OK
==> 1

# this is fine too
http> POST /db/data/ext/GremlinPlugin/graphdb/execute_script { "script": "[1,2,3]" }
==> 200 OK
==> [ 1, 2, 3 ]

# this is not
http> POST /db/data/ext/GremlinPlugin/graphdb/execute_script { "script": "[{}]" }
==> 200 OK
==> [ "Script1$_run_closure1@2b0a141e" ]
http>
```

Tried on neo4j-community-1.9.M03

**Comment by jakewins** [comment]
This is an issue with Gremlin itself, I believe - or with the Gremlin Plugin for Neo4j. Please raise a ticket with https://github.com/tinkerpop/gremlin or with https://github.com/neo4j-contrib/gremlin-plugin
