### ISSUE TITLE
`Neo.DatabaseError.Transaction.CouldNotCommit` after non-fatal errors

### ISSUE THREAD

**Issue by aseemk** [neo4j/neo4j#4137]
Hi guys,

We at @FiftyThree have mentioned this to @jhfneo on an internal support ticket, but thought this was worthy of a public discussion. (I'd like to reach out to other driver authors about this.)

If you:

1. Begin a transaction (over the REST API, via the transactional endpoint);
2. Execute a statement successfully;
3. Execute another statement that fails with a `ClientError` or `TransientError`;
4. Execute a third statement ***successfully*** (e.g. a retry in response to the `TransientError`);
5. Then attempt to commit the transaction...

Neo4j 2.1.x consistently fails with the mentioned `Neo.DatabaseError.Transaction.CouldNotCommit`, whereas I would expect the transaction to commit successfully.

Here is the full Neo4j stack trace: https://gist.github.com/aseemk/070419175f3d8c0b3c24

—

I feel that this is a clear bug for the following reasons:

- The docs clearly say that transactions are rolled back only on `DatabaseError`s — *not* `ClientErrors` or `TransientErrors`. http://neo4j.com/docs/stable/status-codes.html#_classifications

- As I emphasized above, the third statement succeeded, so clearly the transaction is still considered open and valid after the second statement's failure.

- The response of `DatabaseError` suggests this is a bug or oversight in the Neo4j code, *not* an invalid client action (like posting to a rolled back transaction normally is, resulting in a `ClientError` instead).

I really hope the interpretation isn't that transactions should *always* be rolled back. That would defeat the purpose of having `TransientError`s in particular; there wouldn't be any opportunity to retry then.

Thanks!

**Comment by cleishm** [comment]
If I understand correctly, you're suggesting that a statement can stay valid even if there are failing statements within it.

That might be possible in some cases, although I wonder at the value. It definitely wouldn't be possible in several cases. For example, deadlock detection is a transient error - where a retry will likely succeed - but the locks must be held and released on a transaction basis, so the whole transaction would need to be aborted and retried.

**Comment by aseemk** [comment]
Thanks for clarifying, @cleishm.

So my first q is: what do the docs mean if not exactly what you said? (Re: "a transaction can stay valid even if there are failing statements within it.")

i.e. Why the distinction between the different error classifications on whether the tx gets rolled back or not? http://neo4j.com/docs/stable/status-codes.html#_classifications

My second q is: in the case of a deadlock detected transient error, couldn't a retry succeed if *another* transaction finished? Why does the *current* transaction need to be entirely aborted and retried?

(I'd have to confirm with @ryanwe, but I believe we *did* have retries succeed within transactions; they just wouldn't commit later.)

**Comment by cleishm** [comment]
All good points. Those docs are definitely misleading, as there are certainly cases where a TransientError would need a rollback (e.g. deadlocks).

**Comment by cleishm** [comment]
Regarding the requirement for an abort, the other transaction cannot finish until there is an abort. That's the definition of a deadlock: nobody can proceed. The only way to resolve that is to abort one of the deadlocking parties.

**Comment by aseemk** [comment]
Ah, my understanding of the `DeadlockDetected` error was that locks *were* automatically released — but only for that query, not for the entire tx. Is that right or wrong? Thanks Chris.

**Comment by cleishm** [comment]
Locks are managed on the transaction level, and they must be held until commit or abort of the transaction. Thus deadlock detection also operates on a transaction level. It's also the case that the locks involved in a deadlock could be in place from a previous query within the same transaction: I don't believe it's possible to accurately track or limit those to just the last query.

(It's also true that even if this type of error is marked as a TransientError, caution should be used when retrying - as the condition that results in deadlock may still exist for an indeterminate amount of time, e.g. when it's caused by a long running transaction that holds locks for an indeterminately long period)

**Comment by aseemk** [comment]
I inadvertently created a dupe of this issue in #5258, but it was fixed there.
