### ISSUE TITLE
Missing JSON Content-Type on 401 Unauthorized responses

### ISSUE THREAD

**Issue by aseemk** [neo4j/neo4j#4140]
E.g. repros with [HTTPie](http://httpie.org/):

```
$ http GET localhost:7474/user/neo4j
HTTP/1.1 401 Unauthorized
Content-Length: 139
Date: Sun, 08 Mar 2015 01:29:54 GMT
Server: Jetty(9.2.4.v20141103)
WWW-Authenticate: None

{
  "errors" : [ {
    "code" : "Neo.ClientError.Security.AuthorizationFailed",
    "message" : "No authorization header supplied."
  } ]
}
```

```
$ http -a neo4j:foo GET localhost:7474/user/neo4j
HTTP/1.1 401 Unauthorized
Content-Length: 135
Date: Sun, 08 Mar 2015 01:58:15 GMT
Server: Jetty(9.2.4.v20141103)
WWW-Authenticate: None

{
  "errors" : [ {
    "code" : "Neo.ClientError.Security.AuthorizationFailed",
    "message" : "Invalid username or password."
  } ]
}
```

**Comment by iansrobinson** [comment]
Plus, shouldn't the Authenticate header be prompting for Basic with realm?

**Comment by cleishm** [comment]
Good catch @assemk. We'll make sure to add the content type.

Regarding the `WWW-Authenticate`: with a 401 response, we have to send a `WWW-Authenticate` header, according the the RFC. Having it specify Basic and a realm would be theoretically better, except doing that causes browsers to try and retry after prompting a user for credentials, i.e. with a username and password popup, even for requests made by JavaScript. We don't want that, as Neo4j browser needs to see the 401 response and handle it without a popup. Sending `WWW-Authenticate  None` stops that behaviour in the browser, and non-browser drivers wouldn't look at that header anyway.

If there's a better way, of course we'd happily consider that!
