### ISSUE TITLE
Indexing documentation fix

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4j/neo4j#4141]
I wasn't sure if there was an official place to submit this, se feel free to correct me.  I'm also happy to do a PR if the docs are on GitHub.

On this page in the docs:

http://neo4j.com/docs/milestone/indexing.html

_"support for legacy indexes remains, because certain features, such as uniqueness constraints, are not yet handled by the new indexes"_

I think that's out of date because Neo4j supports uniqueness constraints now.  Maybe it's better to mention full-text indexing, instead?

**Comment by mariascharin** [comment]
Unfortunately this issue has been aging for some time. Indexes and unique constraints are correctly described in the Developer manual from 3.0 and forward (http://neo4j.com/docs/developer-manual/3.0/cypher/#cypher-schema). Therefore we're closing the issue.
