### ISSUE TITLE
Windows Wrapper not logging due to invalid path for the logging properties

### ISSUE THREAD

**Issue by glennsarti** [neo4j/neo4j#4142]
The windows-wrapper-logging.properties file is not appear to be read when the Neo4J Server starts.  This means there is no logging from the Windows Wrapper.

OS: Windows 8.1
Neo4j: 2.2.0-RC1 although I suspect the version won't matter too much
Installation method: Chocolatey install of 2.2.0-RC01 (basically an unzip and then run Neo4jInstaller)

Steps to reproduce:
* Install Neo4j Community 2.2.0-RC01 and make sure the service is stopped
* Install the Sysinternals tool ProcMon (process monitor)
* Start ProcMon and change the filter to only file system events, and include "Path if it contains wrapper".  This will display all file system events for anything with the word wrapper in the path of the file.
* Start the Neo4j Server and notice there are a LOT of events loading the wrapper jar etc.
* Search for the file windows-wrapper-logging.properties

Notice that the full path it's using is c:\windows\system32\conf\..... and that it returned File Not Found.

I also experimented with changing the ImagePath value for the Neo4j Server and used an absolute path instead of relative;
```
"C:\Program Files\Java\jdk1.7.0_71\jre\bin\java.exe" -Djava.util.logging.config.file=C:\tools\NEO4J-~1\NEO4J-~1.0-R\conf\windows-wrapper-logging.properties -DworkingDir=C:\tools\NEO4J-~1\NEO4J-~1.0-R\bin\.. -DconfigFile=conf\neo4j-wrapper.conf -DserverClasspath=lib/*.jar;system/lib/*.jar;plugins/**/*.jar;./conf* -DserverMainClass=org.neo4j.server.Bootstrapper -Dorg.neo4j.cluster.logdirectory=C:\tools\NEO4J-~1\NEO4J-~1.0-R\bin\..\data\log -jar C:\tools\NEO4J-~1\NEO4J-~1.0-R\bin\windows-service-wrapper-5.jar
```
to
```
"C:\Program Files\Java\jdk1.7.0_71\jre\bin\java.exe" -Djava.util.logging.config.file=C:\tools\NEO4J-~1\NEO4J-~1.0-R\conf\windows-wrapper-logging.properties -DworkingDir=C:\tools\NEO4J-~1\NEO4J-~1.0-R\bin\.. -DconfigFile=conf\neo4j-wrapper.conf -DserverClasspath=lib/*.jar;system/lib/*.jar;plugins/**/*.jar;./conf* -DserverMainClass=org.neo4j.server.Bootstrapper -Dorg.neo4j.cluster.logdirectory=C:\tools\NEO4J-~1\NEO4J-~1.0-R\bin\..\data\log -jar C:\tools\NEO4J-~1\NEO4J-~1.0-R\bin\windows-service-wrapper-5.jar  Neo4j-Server
```
This changed the ProcMon output and the file was indeed read however no log file was generated.

I also the ImagePath as a console session (by removing the trailing Neo4j-Server) with the absolute File Paths and received the following error message;
```
...
Can't load log handler "java.util.logging.FileHandler"
java.io.IOException: Couldn't get lock for data/log/windows-wrapper.%u.%g.log
java.io.IOException: Couldn't get lock for data/log/windows-wrapper.%u.%g.log
        at java.util.logging.FileHandler.openFiles(FileHandler.java:389)
        at java.util.logging.FileHandler.<init>(FileHandler.java:225)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstruct
orAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingC
onstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at java.lang.Class.newInstance(Class.java:379)
        at java.util.logging.LogManager$4.run(LogManager.java:809)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:802)
        at java.util.logging.LogManager.initializeGlobalHandlers(LogManager.java
:1406)
        at java.util.logging.LogManager.access$1500(LogManager.java:148)
        at java.util.logging.LogManager$RootLogger.accessCheckedHandlers(LogMana
ger.java:1493)
        at java.util.logging.Logger.getHandlers(Logger.java:1350)
        at java.util.logging.Logger.log(Logger.java:612)
        at java.util.logging.Logger.doLog(Logger.java:641)
        at java.util.logging.Logger.log(Logger.java:664)
        at java.util.logging.Logger.info(Logger.java:1182)
        at org.neo4j.wrapper.NeoServiceWrapper.main(NeoServiceWrapper.java:29)
Mar 08, 2015 9:49:07 PM org.neo4j.wrapper.NeoServiceWrapper main
...
```
So I'm sure the logging properties file is being read (due to the reference to windows-wrapper) but I suspect there are still some issues in the config.  Perhaps there is a dependency on the working directory?

**Comment by zhenlineo** [comment]
The reason for this error is that java.util.lgging.FileHandler will not create any folders if they do not exist. This problem could be solved by creating a "NEO4J_HOME/data/log" folder. But of course, here is the fix https://github.com/neo4j/windows-wrapper/pull/3 for this embarrassing error.

**Comment by glennsarti** [comment]
The directory does already exist.  The issue is that the windows wrapper config file is not even read because it is trying to read it from %SYSTEMROOT% instead of %NEO4J_HOME%

**Comment by zhenlineo** [comment]
aha you are running windowsinstaller bat. But, are you running it from NE4J_HOME or SYSTEMROOT? The FileHandler will always try to load a class using the current running folder as the parent folder. I though I only need fix this path issue in neo4j.bat. Okay, will check the installer.

**Comment by glennsarti** [comment]
Sorry...I should've made it more explicit.  This is running as a Windows Service.  I'm not invoking a batch file to start it.  There is no option to set a Working Directory in a Windows Service and defaults to the same directory as the initial executable.  In this case it's java.exe

I also confirmed I'm having the same issue using Neo4j Community 2.1.4 on Server 2012 R2

**Comment by zhenlineo** [comment]
If I got your problem correctly, so you have successfully load the file `windows-wrapper-logging.properties`, but failed to find any log files with this relative path `data/log/windows-wrapper.%u.%g.log` correctly. Therefore, you get this 
```
Can't load log handler "java.util.logging.FileHandler"
java.io.IOException: Couldn't get lock for data/log/windows-wrapper.%u.%g.log
```
So a simple and quick fix for you to run is to change this 'data/log/windows-wrapper.%u.%g.log' relative path to a absolute path in 'windows-wrapper-logging.properties'.

Let me know if this could help to solve your problem.

**Comment by glennsarti** [comment]
My first problem is;
* The default install of Neo is configured so that the `windows-wrapper-logging.properties` is never loaded

I then change the windows service command line to use an absolute path and I can confirm that the properties file is loaded, but it fails to load the handler because, I suspect, it will then be trying to write the file to C:\Windows\System32\data\log\.....  I need to check my process monitor logs to see if it's actually doing this.  In which case, I'd need to modify both the windows server command line and the .properties file to use absolute names.

**Comment by zhenlineo** [comment]
Yes, it will try to create a log file using `C:\Windows\System32\data\log.....` if we invoke the service in folder `C:\Windows\System32` and specify the path with a relative path in `windows-wrapper-logging.properties` 
```
java.util.logging.FileHandler.pattern=data/log/windows-wrapper.%u.%g.log
```
Because the code use something like 
```
File logFile = new File( "data\log\windows-wrapper.0.0.log" );
```
to create a log file, which is equivalent to 
```
File logFile = new File( currentWorkingDir, "data\log\windows-wrapper.0.0.log" );
```
So if we invoke this program from some other folder except NEO4j_HOME (the folder where all resource code unzipped), the currentWorkingDir is not pointed to NEO4J_HOME and therefore we cannot find the file specified with the relative path.

If you start the neo4j with bat files, we could help to make sure the working directory is set correctly, however if you invoke it outside, then I could hardly think of other better way than change this path
```
java.util.logging.FileHandler.pattern=data/log/windows-wrapper.%u.%g.log
```
to an absolute path.

**Comment by glennsarti** [comment]
Ok...so this will require some changes to the Neo4jInstaller.BAT file.

Do you know if you can use environment variables in the wrapper config file e.g.

```
java.util.logging.FileHandler.pattern=%NEO4J_HOME%/data/log/windows-wrapper.%u.%g.log
```

**Comment by jexp** [comment]
should be able to pass it in as System Property with `-Djava.util.logging.FileHandler.pattern=%NEO4J_HOME%/data/log/windows-wrapper.%u.%g.log`

Environment variables can also be used from java.

**Comment by glennsarti** [comment]
As a workaround I suppose it's ok.  I can't say that I'm too happy about putting in absolute paths in config files.  Is it a supported configuration to have more than one Neo4j Instance on a windows host?

I'm imagine then you would need to user per-user environment variable for %NEO4J_HOME% and then have each service in it's own user context.

**Comment by zhenlineo** [comment]
I do not think you could use %NEO4J_HOME% in that wrapper config file. The content is read by java.util.logging.FileHandler directly, which is why it is a bit out of our control. However it accept some other parameters such as %t (More info could be found in the FileHandler's class comments http://docs.oracle.com/javase/7/docs/api/java/util/logging/FileHandler.html). 

If you run the program from your own bat, I would recommend you change the working dir in your bat, something like the new line added in this pr: https://github.com/neo4j/neo4j/pull/4196/files

**Comment by glennsarti** [comment]
@zhenlineo @jexp I'm not sure why you closed this issue.  I'm not running the program from my own Batch file.  It's running as a Windows Service i.e. java.exe.  I can replicate the issue on multiple OSes with different versions of Neo.  There seems to be an underlying issue with how Neo installs itself (Neo4jInstaller.bat) as a Windows Service.

I'm not sure on what process is used for issue resolution, but this issue requires source code changes and a pull request to be fixed.  Does the PR need to be raised referencing this issue? or should this issue remain open until a PR is merged that fixes it?

**Comment by zhenlineo** [comment]
@glennsarti Oh, sorry, re-open it and I am working on this.

**Comment by zhenlineo** [comment]
https://github.com/neo4j/windows-wrapper/pull/5

**Comment by atulshukla123** [comment]
How to check the version of Neo4j running on ubuntu
