### ISSUE TITLE
2.2.0-RC01 regression: DatabaseError for missing parameters

### ISSUE THREAD

**Issue by aseemk** [neo4j/neo4j#4144]
Run this query (e.g. in the browser) without a `foo` parameter:

```cypher
RETURN {foo}
```

Neo4j 2.1 and 2.0 respond with `Neo.ClientError.Statement.ParameterMissing`.
Neo4j 2.2.0-RC01 responds with `Neo.DatabaseError.Statement.ExecutionFailure`.

**Comment by apcj** [comment]
Thanks for reporting this @aseemk . I've added a simple test so we don't miss something like this again.
