### ISSUE TITLE
2.2.0-RC01 regression-ish: DatabaseError for node not found

### ISSUE THREAD

**Issue by aseemk** [neo4j/neo4j#4145]
Query a non-existent node via the REST API, e.g.:

```
GET /db/data/node/-1
```

Neo4j 2.1 and 2.0 respond with a 404 status code and this body:

```json
{
    "message": "Cannot find node with id [-1] in database.",
    "exception": "NodeNotFoundException",
    "fullname": "org.neo4j.server.rest.web.NodeNotFoundException",
    "stacktrace": [
        "org.neo4j.server.rest.web.DatabaseActions.node(DatabaseActions.java:175)",
        "org.neo4j.server.rest.web.DatabaseActions.getNode(DatabaseActions.java:220)",
        "org.neo4j.server.rest.web.RestfulGraphDatabase.getNode(RestfulGraphDatabase.java:265)",
        "java.lang.reflect.Method.invoke(Method.java:483)",
        "org.neo4j.server.rest.transactional.TransactionalRequestDispatcher.dispatch(TransactionalRequestDispatcher.java:139)",
        "org.neo4j.server.rest.dbms.AuthorizationFilter.doFilter(AuthorizationFilter.java:120)",
        "java.lang.Thread.run(Thread.java:745)"
    ]
}
```

Neo4j 2.2.0-RC01 *also* responds with a 404 and that body... but it also adds this bit to the end:

```json
    "errors": [
        {
            "code": "Neo.DatabaseError.General.UnknownFailure",
            "message": "Cannot find node with id [-1] in database.",
            "stacktrace": "org.neo4j.server.rest.web.NodeNotFoundException: Cannot find node with id [-1] in database.\n\tat ...\n"
        }
    ]
```

I'm guessing you guys are standardizing on the new `errors: [{code, message}]` format for errors (tangentially, I have some questions and feedback on that), but you should probably make sure to map all 4xx status codes to `ClientError`s and not `DatabaseError`s.

**Comment by aseemk** [comment]
Whoa, also just ran into the fact this `errors[0].stacktrace` is lowercase `stacktrace`, while every other case I've encountered is camel-case `stackTrace`. Which should it be?

(In general, I've also noticed that this stack trace property is undocumented. But it's useful when present, bc it can be provided to you guys to help debug.)

**Comment by apcj** [comment]
Hi Aseem,

Thanks for spotting this. I've narrowed it down a bit: I think that it's only `NodeNotFoundException` that isn't being mapped properly to a `ClientError`. For example, using a similar part of the API I can produce a `Neo.ClientError.Schema.ConstraintViolation` in the `errors` array:

    POST /db/data/node # create node 0
    POST /db/data/node # create node 1
    POST /db/data/node/0/labels "Person"
    POST /db/data/node/1/labels "Person"
    POST /db/data/schema/constraint/Person/uniqueness/ { "property_keys" : [ "name" ] }
    PUT /db/data/node/0/properties/name "Alistair"
    PUT /db/data/node/1/properties/name "Alistair"

The last request produces an errors array like this:

    "errors": [
        {
            "code": "Neo.ClientError.Schema.ConstraintViolation",
            "message": "Node 0 already exists with label 0 and property 0=Alistair"
        }
    ]

There is special handling of `NodeNotFoundException` for some legacy reasons, but I think that can be made consistent now.

Also, thanks for pointing out the `stackTrace` vs `stacktrace` mismatch. We'll fix it to the camel-case version, so `stackTrace`.
