### ISSUE TITLE
Pressing tab in neo4j-shell with invalid command started causes shell to emit stack trace

### ISSUE THREAD

**Issue by MikeBenza** [neo4j/neo4j#4157]
If you start the shell and enter an invalid command, a space, and then hit tab any time in a query after that, you get a stack dump in the console.

`moo[tab]` -> ok
`moo [tab]` -> stack dump in console
`moo cow[tab]` -> stack dump in console

**Comment by MikeBenza** [comment]
To clarify, this is 2.1.6

**Comment by craigtaverner** [comment]
Neo4j-shell has been deprecated since Neo4j 3.0 and will be removed from the product in the next release. Please try cypher-shell instead.
