### ISSUE TITLE
no reference to `:play sysinfo` in `:help play`

### ISSUE THREAD

**Issue by whatSocks** [neo4j/neo4j#4186]
![screenshot 2015-03-12 00 36 39](https://cloud.githubusercontent.com/assets/2731744/6612303/2d6f632e-c850-11e4-8398-6655f9f0d181.png)

Testing 2.2. There's no reference to `:play sysinfo` in the help page for `play` commands.

**Comment by apcj** [comment]
Fixed by https://github.com/neo4j/neo4j/commit/38abcd515d3f5ada2fe0f0db0543bd31f16aefc5
