### ISSUE TITLE
my neo4j cypher is very slow. how to improve?

### ISSUE THREAD

**Issue by ronyongxian** [neo4j/neo4j#4189]
there are 15M nodes and 150M relations in the db, i run the following cypher and it takes more than 200 secondes to get the result. machine cpu&memory is low. what should i do to improve? I'd appreciate some advise.

cypher:

START me=node:node_auto_index(userId='32887522')

MATCH (me)-[:RELATIONSHIP_TYPE_FRIEND]-(people)-[:RELATIONSHIP_TYPE_FRIEND]-(fof)

RETURN fof,count(*) AS commonFriends

ORDER BY commonFriends DESC

LIMIT 100;

and get the excute plan:

ColumnFilter(symKeys=["fof", " INTERNAL_AGGREGATEeaff758c-8eda-498a-9366-9965f62d16fc"], returnItemNames=["fof", "commonFriends"], _rows=100, _db_hits=0)

==> Top(orderBy=["SortItem(Cached( INTERNAL_AGGREGATEeaff758c-8eda-498a-9366-9965f62d16fc of type Long),false)"], limit="Literal", _rows=100, _db_hits=0)

==> EagerAggregation(keys=["fof"], aggregates=["( INTERNAL_AGGREGATEeaff758c-8eda-498a-9366-9965f62d16fc,CountStar)"], _rows=3661, _db_hits=0)

==> TraversalMatcher(trail="(me)-[ UNNAMED62:RELATIONSHIP_TYPE_FRIEND WHERE true AND true]-(people)-[ UNNAMED99:RELATIONSHIP_TYPE_FRIEND WHERE true AND true]-(fof)", _rows=15470, _db_hits=15547)

==> ParameterPipe(_rows=1, _db_hits=0)

**Comment by jexp** [comment]
Please ask this question on the google group or stackoverflow. GitHub is for issue tracking only.
