### ISSUE TITLE
Feedback on schema-related parts of REST API

### ISSUE THREAD

**Issue by aseemk** [neo4j/neo4j#4214]
Hey folks,

I just implemented schema management functionality in node-neo4j:

https://github.com/thingdom/node-neo4j/blob/v2/API_v2.md#schema

And ran into a number of gotchas, quirks, and inconsistencies when dealing with the indexing and constraints parts of the REST API:

http://neo4j.com/docs/stable/rest-api-schema-indexes.html
http://neo4j.com/docs/stable/rest-api-schema-constraints.html

I wanted to pass them along, so here's an umbrella issue for all the feedback.

Btw, I understand that Cypher is the future, but it seems like most of these REST APIs are still necessary, as much of the functionality isn't available over Cypher today.

Thanks!

—

**Indexes**
- **Online/populating/failed status isn't returned**, so no way to know if an index is available yet or not. (There isn't a way with regular Cypher either. There is with the shell, and the browser via a custom API.) This feels pretty significant: the browser shouldn't need to use custom APIs.
- This is less relevant until online/populating status is returned, but there's **no way to retrieve a specific index**. E.g. there's no `GET .../index/:label/:prop` — even though there is `GET .../constraint/:label/uniqueness/:prop`. Any reason?
- **Creating an index that already exists** returns a 409 Conflict response, with a `Neo.ClientError.Schema.IndexAlreadyExists` error. This is undocumented, but it's also **inconsistent with Cypher**, which _doesn't_ throw an exception. Why not just return a 304 Not Modified here? (Ideally, the index info would still be returned, e.g. for online/populating/failed status.)
  
  (The use case is optimistically registering indexes and constraints freely, e.g. anytime new code is pushed. We do this at FiftyThree since the operation is idempotent through Cypher.)

**Constraints**
- The endpoint for **retrieving a specific constraint**, `GET .../constraint/:label/uniqueness/:prop`, still **returns an array** of constraints. Why?
- Creating a constraint _seems_ to be a synchronous/blocking operation, unlike indexes. Is that right? If so, maybe that could be documented explicitly.
- Like with indexes above, **creating a constraint that already exists** also returns a 409 Conflict `Neo.ClientError.Schema.ConstraintAlreadyExists` error. This is again both undocumented and **inconsistent with Cypher**. Why not return a 304 Not Modified here too?

**Both**
- The JSON representation for both has an **array of `property_keys`**, but in practice, there's only one property. This is even codified in the URLs, e.g. `DELETE .../index/:label/:prop` and `GET` & `DELETE .../constraint/:label/uniqueness/:prop`. So why the array?

**Comment by apcj** [comment]
Thanks for all the feedback!

We're planning to re-implement the `:schema` command in Neo4j Browser so that is uses these APIs. That should drive out most of the things you've suggested.

We'll update this issue when we get there - should hopefully be soon.

**Comment by aseemk** [comment]
It looks like this regressed a bit somewhere in between 2.2.0-RC1 and 2.2.2: the REST API for creating a constraint or index that already exists now returns `ConstraintViolation` as the error code (in all cases), rather than the more helpful `ConstraintAlreadyExists` or `IndexAlreadyExists`. (The inner `cause`s still have those more helpful codes, though.)

Here is a table summarizing:
- Creating a constraint that already exists:
  - Cypher: successful; just no results
  - REST API: 409 w/ `ConstraintViolation` error in 2.2.2; inner cause has `ConstraintAlreadyExists`
- Creating an index that already exists:
  - Cypher: successful; just no results
  - REST API: 409 w/ `ConstraintViolation` error in 2.2.2; inner cause has `IndexAlreadyExists`
- Creating an index that already exists _from a constraint_:
  - Cypher: `ConstraintAlreadyExists` error
  - REST API: 409 w/ `ConstraintViolation` error in 2.2.2; inner cause has `ConstraintAlreadyExists`

I'd like to make node-neo4j _not_ throw an error if an index or constraint already exists. (In all cases we have, at least, we are okay with that since these calls are meant to be idempotent.)

Are there any cases where the REST API returning `ConstraintViolation` for "create index" or "create constraint" is anything _other than_ "already exists"? Thanks.

**Comment by cleishm** [comment]
Thanks @aseemk. I'll pass those along to the appropriate people.

**Comment by jexp** [comment]
Hey @aseemk why do you go via the REST API in the first place and not via cypher directly? I would ignore the REST API and for Cypher (esp. when we create an index for an existing constraint) I'd just ignore the concrete error code, perhaps configurable via user supplied (optional) parameter.

**Comment by aseemk** [comment]
It's a good q @jexp and I haven't been sure.

The reality is that Cypher doesn't have a way to _read_ indexes and constraints. Since I have to use the REST API for reads, I thought for consistency I'd implement _writes_ over the REST API too.

More importantly though, it would be nice to be able to report back whether an index or constraint was created, or it already existed. Cypher doesn't report that either, AFAICT; it always just returns empty.

**Comment by MishaDemianenko** [comment]
Hi @aseemk we will not gonna change exception types that REST API throws as part of 2.x releases since that will brake compatibility, that can be included in 3.x. 
@aseemk , @apcj do we have any other open points here or we can close this issue?

**Comment by aseemk** [comment]
Sorry @MishaDemianenko, I may be misunderstanding, but re:

> do we have any other open points here or we can close this issue?

The issue description lists a number of other points here beyond exception types. E.g. returning offline/online/populating status for indexes.

Understood about some things being breaking changes, so they'd have to wait for 3.x. Is it your guys' practice to close issues just based on that? No value in tracking for 3.x?

**Comment by MishaDemianenko** [comment]
Hey @aseemk that's almost my point :)
This card contains more then one item which is generally hard to track and easy to forget. And if @apcj already have any decision from his side i would prefer to close this issue with some appropriate links/next steps, otherwise it will hang in limbo forever in a half answered or resolved state.

But agree with you, it fully makes sense to have something for 3.x about that.

**Comment by aseemk** [comment]
Sounds good. I'll leave it to you guys to handle as you like. Just wanted to give this feedback.

**Comment by technige** [comment]
Copying this issue over to an internal Trello card and closing the GitHub Issue.
