### ISSUE TITLE
2.2.0-RC1 query difference

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4j/neo4j#4231]
This seems like a bug to me, but I'll let you be the judge:

Run these two commands in 2.1.7 and 2.2.0-RC01 and you get different results.

The setup:
```cypher
CREATE (a:Foo)-[:HAS]->(b:Bar)<-[:HAS]-(c:Foo), (d:Foo)-[:HAS]->(e:Bar)
```

The query:
```cypher
MATCH (a:Foo) OPTIONAL MATCH a--(b:Bar) WHERE NOT(a--(b:Bar)--()) RETURN b
```

In 2.1.7, one `Bar` object is returned.  In 2.2.0-RC01 three `null` rows are returned

**Comment by cleishm** [comment]
Hi @cheerfulstoic,

To confirm, 2.1.7 actually returns 3 results:

```
% cd ~/neo4j-enterprise-2.1.7
% ./bin/neo4j-shell
neo4j-sh (?)$ MATCH (a:Foo) OPTIONAL MATCH a--(b:Bar) WHERE NOT(a--(b:Bar)--()) RETURN b;
+-----------+
| b         |
+-----------+
| <null>    |
| <null>    |
| Node[4]{} |
+-----------+
3 rows
% cd ~/neo4j-enterprise-2.2.0-RC01
% ./bin/neo4j-shell
neo4j-sh (?)$ MATCH (a:Foo) OPTIONAL MATCH a--(b:Bar) WHERE NOT(a--(b:Bar)--()) RETURN b;
+--------+
| b      |
+--------+
| <null> |
| <null> |
| <null> |
+--------+
3 rows
```

Certainly you are correct beyond that detail: Neo4j 2.2.0-Rc01 is incorrectly returning null in all 3 cases.

**Comment by cheerfulstoic** [comment]
Ah, good point.  I see that now when I switch to the table view in the web console

**Comment by jakewins** [comment]
Verified that this issue remains: http://console.neo4j.org/r/96bk1k

**Comment by jakewins** [comment]
Wait no, I misunderstood this. I meant the opposite: Verified that this now correctly returns two nulls and one node.

**Comment by cheerfulstoic** [comment]
:metal:
