### ISSUE TITLE
Explain that schema = indices + constraints in section 3.7 of documentation

### ISSUE THREAD

**Issue by krichter722** [neo4j/neo4j#4258]
Chapter 13 states clearly that "Together, indexes and constraints are the schema of the graph"<ref>http://neo4j.com/docs/stable/cypher-schema.html</ref> whereas this is not clear at all after reading the "Schema" section on http://neo4j.com/docs/stable/graphdb-neo4j-schema.html. I thought the sections on indexes and contraints are unrelated.

**Comment by kman0** [comment]
@krichter722 The second URL is down. Are you referring to the right documentation with the discrepancy?

**Comment by krichter722** [comment]
If it's gone we don't have to worry about it anymore. I'll reopen if I find something mismatching or misleading.
