### ISSUE TITLE
[2.2RC01][Cypher] Matching relationship by id throws exception if relationship not found

### ISSUE THREAD

**Issue by ikwattro** [neo4j/neo4j#4273]
Hi,

Matching a node by id 

```
MATCH (n) WHERE id(n) = 123 RETURN n;
```

Returns an empty result if the node does not exist.

However, doing the same for a relationship throws an exception when the relationship does not exist: 

```
MATCH ()-[r]-() WHERE id(r) = 123444 RETURN r
```

```
$MATCH ()-[r]-() WHERE id(r) = 123444 RETURN r
Relationship 123444 not found
 Neo.DatabaseError.Statement.ExecutionFailure
```

**Comment by jexp** [comment]
Fixed here: https://github.com/neo4j/neo4j/pull/4284
