### ISSUE TITLE
Feature request: Multi-property constraints

### ISSUE THREAD

**Issue by subvertallchris** [neo4j/neo4j#4274]
It would be very nice to define a constraint on combinations of properties. For instance, say I have three properties: `username`, `id`, and `source_network`. I don't care if these properties are reused independently but if someone tries to create a node with an existing combination of the three, it's a problem.

```
CREATE GROUP CONSTRAINT ON (user:User) ASSERT user.username, user.id, user.source_network IS UNIQUE
```

Something like that. Doable?

**Comment by jexp** [comment]
Feature request noted.

You can work around it by either concatenating the three into an additional property, or using and array property to store the three. And create a constraint on those.

**Comment by chrisvest** [comment]
In 3.2 we now have `NODE KEY` https://neo4j.com/docs/developer-manual/3.2/cypher/schema/constraints/#query-constraint-node-key
