### ISSUE TITLE
Is there any way to bypass authentication in 2.2

### ISSUE THREAD

**Issue by ktei** [neo4j/neo4j#4296]
We upgraded to 2.2 but noticed that it needs authentication token for REST API, which means change in our back-end code, which we prefer to do later. Currently, is there any way to bypass the authentication? In that case we don't need to change back-end code for now.

Many thanks

**Comment by jexp** [comment]
See: http://neo4j.com/docs/stable/security-server.html#security-server-auth

In neo4j-server.properties:
````
# Disable authorization
dbms.security.auth_enabled=false
````
