### ISSUE TITLE
Alleged duplicate result column names in 2.2

### ISSUE THREAD

**Issue by area** [neo4j/neo4j#4331]
I just upgraded from 2.1.7 to 2.2, and I've found an apparent regression in some cypher queries. I have only managed to test on 2.1.5, but I believe I saw this behaviour on 2.1.7 also. The following query works in 2.1.5, using the Movie stars sample data.

```
MATCH (p:Person {name:"Tom Hanks"}) with p, 10 as prop RETURN sum(p.born)*prop as a, sum(p.born)*prop as b
```

But on 2.2, I get the error

```
Multiple result columns with the same name are not supported (line 1, column 75 (offset: 74))
"MATCH (p:Person {name:"Tom Hanks"}) with p, 10 as prop RETURN sum(p.born)*prop as a, sum(p.name)*prop as b"
```

I note that this error remains even if the field being sum is different in these two cases. For example:

```
MATCH (p:Person {name:"Tom Hanks"}) with p, 10 as prop RETURN sum(p.born)*prop as a, sum(p.name)*prop as b
```

I know that such a query makes no sense with this dataset, but it is sufficient to show that on 2.2.0, you get the same 'multiple result columns' error, and on 2.1.5 you get

```
SUM(Property(p,name(3))) can only handle numerical values, or null.
```

i.e. indicating this query has still passed the check for duplicate result columns.

The query

```
MATCH (p:Person {name:"Tom Hanks"}) with p RETURN sum(p.born) as a, sum(p.born) as b
```

returns correctly.

**Comment by cleishm** [comment]
Thanks for the report! I've confirmed the issue and will pass it along to our team.

**Comment by spacecowboy** [comment]
Fixed in https://github.com/neo4j/neo4j/pull/4340
