### ISSUE TITLE
ORDER BY variable undefined

### ISSUE THREAD

**Issue by area** [neo4j/neo4j#4332]
As with my other bug report, this query works correctly on both 2.1.5 and 2.2.0:

```
MATCH (p:Person) with p, rand() as rng return p, rng
```

but this one only works on 2.1.5:

```
MATCH (p:Person) with p, rand() as rng return p ORDER BY rng
```

and on 2.2.0 gives the error:

```
rng not defined (line 1, column 58 (offset: 57))
"MATCH (p:Person) with p, rand() as rng return p ORDER BY rng"
```

**Comment by cleishm** [comment]
Thanks for the report! I've confirmed the issue and will pass it along to our team.

**Comment by area** [comment]
Further to this, the following command works:

```
MATCH (p:Person) with p, rand() as rng return p, rng order by rng
```
