### ISSUE TITLE
2.2.0 Cypher Bug - Parameterized Legacy Index query with UNION exception

### ISSUE THREAD

**Issue by Deevian** [neo4j/neo4j#4342]
We've also ran into this issue while trying out 2.2.0, and although somewhat esoteric, it's applicable to some of our queries. Consider this one:

```
START root=node:Person(id='deevian')
RETURN ID(root) as id

UNION 

START root=node:Person(id='retophy')
RETURN ID(root) as id
```

Executing it, Neo4j returns `key not found: SymbolUse(id@23)`, with a `Neo.DatabaseError.Statement.ExecutionFailure`message.

This only occurs if the statements have at least one `UNION`, and if one the parameters (in this case, `id`) is named the same as one of return aliases.

It does not occur when executed separately (without the `UNION`), when replacing `(id='deev')` with `('id:deev')`, or when changing the return alias to whatever else.

**Comment by cleishm** [comment]
Thanks @Deevian! I've verified this issue and passed it along to our team.

**Comment by rheusinkveld** [comment]
The issue still exists in 2.2.2 if you use an index hint on the same property. So using the example above the query below will still result in a `key not found: SymbolUse` error: 

```
START root=node:Person(id='deevian') USING INDEX node:Person(id)
RETURN ID(root) as id

UNION 

START root=node:Person(id='retophy') USING INDEX node:Person(id)
RETURN ID(root) as id
```

**Comment by jexp** [comment]
but `USING INDEX node:Person(id)` is for schema indexes not for manual/legacy indexes.

So perhaps the error message should be different, but it is an invalid query in the first place :)
