### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by protheusfr** [neo4j/neo4j#4365]
First, I would to thank Neo4j team for the excellent work achieved on Neo4j 2.2.
By using Neo4j daily, I've begin a wishes list in order to improve again this fantastic product :

Finalize the dump function, to make them usable with any size of DB (it could be really really usefull to make Neo4j more "production ready")
Add a stored proceduresmechanisms in order to store the must used Cypher queries into the graph
Add a node or relationship executable properties , the idea here is an analogy to value functions in Scala, the possibilities to store an evaluated function into a property value in order to get the result of this function when the property is read by a Cypher query (it could be just a new value Type).
This last functionality could open a large way of data processing possibilities without leaving the Cypher langage.

**Comment by chrisvest** [comment]
Our `neo4j-admin` tool has online and offline backup features, and Cypher can now be extended with java procedures. Not quite the same as stored procedures, but close. Storing executable Cypher in the database sounds a little far out, but would have to go through the Cypher Improvement Process, I think.

Feel free to open individual feature requests for anything you think is missing.
