### ISSUE TITLE
regex bug neo4j

### ISSUE THREAD

**Issue by fernandoclaudio** [neo4j/neo4j#4368]
This query with 'regex' works:

WITH ['qwert yuiop', 'qwert find-me yuiop', 'find-me asdfg hjkl'] AS txts
UNWIND txts AS t
  WITH t WHERE t =~ '.*find-me.*'
  RETURN t
;
result:
==> "qwert find-me yuiop"
==> "find-me asdfg hjkl"
==> 2 rows
Works!

But if texts contain '\n' (linebreak), this don't work:

WITH ['qwert yuiop', '\n qwert find-me yuiop', 'find-me asdfg hjkl \n'] AS txts
UNWIND txts AS t
  WITH t WHERE t =~ '.*find-me.*'
  RETURN t
;
result:
==> 0 row
Fail :(

My version:
Neo4j - Graph Database Kernel (neo4j-kernel), version: 2.2.0 (neo4j-community-2.2.0-unix.tar.gz)
java version "1.7.0_75"
Linux neo4jServer 3.2.0-4-amd64 SMP Debian 3.2.65-1+deb7u1 x86_64 GNU/Linux

Workaround:
If texts are properties of node/rels then use legacy index with a lucene query: 

START t=node:node_auto_index('text:*find-me*')
RETURN t;

**Comment by fernandoclaudio** [comment]
It's not a bug it's a feature.

In Regex there are languages dependent small differences: grep, Perl, PHP, Java, sed.

In Neo4j this worked just add "(?s)" at the beginning of search string.

Example: 
identifier =~ '(?s).*find-me.*'

But... could enrich the documentation with more examples, including multi-line example.

http://neo4j.com/docs/stable/query-where.html#_regular_expressions

Thanx

**Comment by jexp** [comment]
Thanks for the feedback, yep a quick example or at least linking to the Java Regexp docs would make sense. 

But for your use-case the lucene option might be the better fit anyway.
