### ISSUE TITLE
ConcurrentLinkedHashMap --> Caffeine when Java-8 based

### ISSUE THREAD

**Issue by ben-manes** [neo4j/neo4j#4384]
Neo4J uses CLHM in its cypher model. When transitions to requiring Java 8, please upgrade to [Caffeine](https://github.com/ben-manes/caffeine). The performance should be relatively the same with a smaller memory footprint.

[ConcurrentLinkedHashMap](https://code.google.com/p/concurrentlinkedhashmap/) changes will continue to be minimal, even more so now, and driven by requests from Java 6 users unable to upgrade. Caffeine is ideally the upgrade path for Guava cache users too, which due to Android cannot be significantly modified.

**Comment by cleishm** [comment]
Hey @ben-manes,

Thanks for the heads up about your project. Certainly looks interesting, and will keep it in mind.

Next time however, please raise these kind of topics on our google group. This issue tracker is for bugs and issues identified in Neo4j.

Cheers,
Chris

**Comment by ben-manes** [comment]
Sure, sorry about that. I wanted to make this was easy to track and the messages on mailing lists often get forgotten in the flood.
