### ISSUE TITLE
Neo4j fails to start on OSX 10.10.3

### ISSUE THREAD

**Issue by area** [neo4j/neo4j#4395]
I am assuming it is the upgrade to OSX 10.10.3 that is causing this issue, as prior to the upgrade Neo4j was working, and afterwards it is not. Unfortunately for this interpretation, I have not found anyone else complaining about it - though given the update has only been public for less than a day, perhaps this is not surprising.

Upon trying to start Neo4j, it times out:

```
neo4j start
Starting Neo4j Server...WARNING: not changing user
process [74567]... waiting for server to be ready............................................................................................................................................... Failed to start within 120 seconds.
Neo4j Server may have failed to start, please check the logs.
```

The log from console.log can be found at https://gist.github.com/area/1812a35d47678eb2fa26

I see this with both v2.1.7 and v2.2.0

My first suspect was java had been nuked, but

```
java -version
java version "1.7.0_71"
Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.71-b01, mixed mode)
```

i.e. it's still 1.7.

**Comment by area** [comment]
I've somehow managed to coax it into running, but I'm not sure how. But either way, the fact I've managed it suggests it's not a problem for Neo4j to fix.

**Comment by area** [comment]
Okay, I have no clue what is going on, but I think I am now able to reproduce the above error.

I use a SOCKS proxy (i.e. `ssh -D 8080 remoteip`) to tunnel my internet connection over SSH. This is not a connection to the machine that neo4j is running on (i.e. neo4j is running locally). If I have this SOCKS proxy activated, then neo4j cannot start up. If I change the port for the remote CLI from 1337 in `neo4j.properties`, then it succeeds in starting up with the proxy activated.

`lsof -n -i4TCP:1337 | grep LISTEN` shows no other processes trying to use 1337.

The SSH connection in question only effects ports 8080, 9999, 7575, based on my ~/.ssh/config file.

I'm at a loss. I've had this setup with the SSH tunnel for months, and never seen this issue before until this morning. I upgraded to 10.10.3 last night. Given I now know how to work around this, I'm happy to leave this closed, but if anyone has any suggestions as to what the heck is going on, I'm all ears.

**Comment by jexp** [comment]
Can you try to disable the remote shell in neo4j.properties and see if the problem persists?

**Comment by area** [comment]
Disabling the remote shell also seems to allow it to start up. I saw this problem without the tunnel activated this morning, so I think that's a red herring, which should make this easier to work out the origin of the problem!
