### ISSUE TITLE
Abnormal performance drop with length increase of "in" operator argument

### ISSUE THREAD

**Issue by rsk700** [neo4j/neo4j#4423]
Was tested with 2.2, but looks like same valid for 2.1.7

STR:

Test data:

```
unwind range(1,100000) as r
create (:page {
category: 'category-' + str(r)
})
```

Check performance:

```
match (p:page)
where p.category in ['category-1']
return count(*)
```

**58 ms**

```
match (p:page)
where p.category in ['category-1', 'cat-1', 'cat-2', 'cat-3', 'cat-4', 'cat-5', 'cat-6', 'cat-7', 'cat-8', 'cat-9', 'cat-10', 'cat-11', 'cat-12', 'cat-13', 'cat-14', 'cat-15', 'cat-16', 'cat-17', 'cat-18', 'cat-19', 'cat-20']
return count(*)
```

**1059 ms**

increasing length of list leads to significant performance drop

**Comment by jexp** [comment]
did you create an index on `:page(category)` ?
otherwise it will have to scan all nodes and for each node do the IN check (which is not optimized using a Set yet)

**Comment by jexp** [comment]
The second query executes in less than 40ms for me, please also note you misspelt the "category-xxx" values for everything > 1

**Comment by jexp** [comment]
2.2 has an issue where it doesn't automatically use the index when the collection is an expression or parameter, but you can force index usage like this:

```
profile
with [r in range(1,20) | 'category-'+r] as cats
match (p:page)
using index p:page(category)
where p.category in cats
return count(*)
```

![plan 12](https://cloud.githubusercontent.com/assets/67427/7116001/12d9819a-e1ee-11e4-8783-510295238c3c.png)

**Comment by rsk700** [comment]
> did you create an index on :page(category) ?
> otherwise it will have to scan all nodes and for each node do the IN check (which is not optimized using a Set yet)

yes I know, I didn't create index on purpose, and yes both queries scan all nodes, but second query makes it much much slower

> The second query executes in less than 40ms for me, please also note you misspelt the "category-xxx" values for everything > 1

I did not misspell, it made on purpose, all queries return same value "1", "cat-x" is fake values to show issue, only one page "category-1" is counted

Can you say which neo4j version you was using? I have this performance issue on 2 servers.

**Comment by rsk700** [comment]
@jexp you misunderstood issue please run queries exactly as I provided, there is definitely performance issue in comparing parameter with list

**Comment by jexp** [comment]
Sure, I said so "IN comparison" across all nodes without an index is **not** an optimized operation, and if you do it for 100k nodes it takes a bit (4s on my machine).

And as you can see in the profile it creates quite a bit of db-hits:

![plan 14](https://cloud.githubusercontent.com/assets/67427/7116783/7f81ba00-e1f4-11e4-9e2a-651b984a462b.png)

**Comment by rsk700** [comment]
Thanks for explanation, I see.

Can it be optimization request ;-) ? My point here this operation possible to make just once, from what I see neo4j runs query again and again separately for each member of list:
`2 * 100000 * 21 = 4 200 000 db hits`

but it can be one operation similar to this:

```
match (p:page)
where p.category =~ 'category-1|cat-1|cat-2|cat-3|cat-4|cat-5|cat-6|cat-7|cat-8|cat-9|cat-10|cat-11|cat-12|cat-13|cat-14|cat-15|cat-16|cat-17|cat-18|cat-19|cat-20'
return count(*)
```

this gives 200 000 db hits

**Comment by apivaral** [comment]
@jexp any plans to make "IN comparison" an optimised operation?
