### ISSUE TITLE
Install multiple windows service instances

### ISSUE THREAD

**Issue by cskardon** [neo4j/neo4j#4432]
I'd like to be able to install the db to a differently name service, so I can have more than one instance of the db running at a time.

Ideally something like:

```
Neo4jInstaller.bat install neo4j-my-thing "Neo4j for My Thing"
```

So in services, I could have:

![image](https://cloud.githubusercontent.com/assets/1875805/7137204/a86598f4-e2af-11e4-99c0-a8d744076cb3.png)

**Comment by spacecowboy** [comment]
Fixed in #4433
