### ISSUE TITLE
Neo4j 2.2 - Wrong integer handling

### ISSUE THREAD

**Issue by denistoikka** [neo4j/neo4j#4450]
1. If I set node parameter as int32:
   REST API saves it as int32
   Browser interface saves it as int64
   Difference confuses
2. If I make SUM of two numbers 1073741824 (int32) I expect 2147483648 (int64) as a result, but actually get -2147483648 (int32)

**Comment by jonnic** [comment]
Seeing the same issue with the python module py2neo, values get inserted as int32 and this constrains sum() to 32 bit.

**Comment by technige** [comment]
Closing as this is an old thread discussing known type mapping quirks with no current action to take AFAICT.
