### ISSUE TITLE
Feature request: Extending maps in cypher

### ISSUE THREAD

**Issue by Yomguithereal** [neo4j/neo4j#4470]
After working for a while with cypher, and pardon me if I did not find the way to do so if there is indeed one, the only thing I find lacking is to be able to extend native maps.

What I mean by extending is the following:

``` js
{a: 1, b: 2} + {b: 3, c: 4} --> {a: 1, b: 3, c: 4}
```

_Practical example_

``` cypher
MATCH n
RETURN {id: id(n), properties: n}
LIMIT 1
```

will produce 

``` js
{id: 34, properties: {text: 'whatever', title: 'anything'}}
```

while what I would really want is

``` js
{id: 34, text: 'whatever', title: 'anything'}
```

I am not sure whether this feature would be useful to other people but it would certainly simplify the interactions with the database by being able to format data in an already final form without further treatments in the receiving code.

**Comment by bunkat** [comment]
I've requested something similar where you could at least use SET on existing maps so that you could extend an existing map with additional properties.

```
WITH {a: 1, b: 2} AS results
SET results.b = 3, results.c = 4
```

Currently, you need to rebuild the map every time.

```
WITH {a: 1, b: 2} AS results
WITH {a: results.a, b: 3, c: 4} AS results
```

Being able to merge maps would be helpful as well.

**Comment by Yomguithereal** [comment]
Yes, being able to use `SET` would be a start indeed (I tried once to do so, thinking it would work, and the engine exploded :) ).

But it still requires to know and write explicitly the keys you need.

**Comment by boggle** [comment]
Thank you for the suggestion. Updating clauses only work on persisted data (graphs, nodes, edges). Maps and lists cannot be updated but new maps and lists may be derived from existing ones, e.g. using map and list comprehensions. We'll look into wether to add `+` operator for maps.

**Comment by sherfert** [comment]
The _Practical example_ can be solved by a [map projection](https://neo4j.com/docs/cypher-manual/current/syntax/maps/#cypher-map-projection).

That would look like this:
```
MATCH n
RETURN n {*, id:id(n)}
LIMIT 1
```

That does not solve the general problem of "merging" two maps. Plus is already too overloaded in Cypher. We do not want to add yet another meaning to it. Therefore, a function (or set of functions) would be better.

[APOC](https://neo4j-contrib.github.io/neo4j-apoc-procedures/#map-functions) already provides such functions:

* `apoc.map.merge(base, patch)`
* `apoc.map.updateTree(tree, key, value)`

We currently don't consider adding these functions into Neo4j.
