### ISSUE TITLE
Cannot Build 2.2

### ISSUE THREAD

**Issue by ghost** [neo4j/neo4j#4480]
Attempting to build recently cloned repository on Ubuntu 14.04 trusty.

Maven Version:

Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.7.0_75, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-43-generic", arch: "amd64", family: "unix"

Running:

`mvn clean install -DminimalBuild`

results in:

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.171s
[INFO] Finished at: Tue Apr 21 09:51:27 EDT 2015
[INFO] Final Memory: 36M/239M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project neo4j-kernel: Could not resolve dependencies for project org.neo4j:neo4j-kernel:jar:2.2.2-SNAPSHOT: The following artifacts could not be resolved: org.neo4j:neo4j-io:jar:tests:2.2.2-SNAPSHOT, org.neo4j:neo4j-primitive-collections:jar:tests:2.2.2-SNAPSHOT: Could not find artifact org.neo4j:neo4j-io:jar:tests:2.2.2-SNAPSHOT in neo4j-snapshot-repository (http://m2.neo4j.org/content/repositories/snapshots/) -> [Help 1]

**Comment by jakewins** [comment]
You need to do a full-ish initial build to get those test jars installed locally. The quickest way to do that is to do a full build sans running the actual tests;

```
mvn clean install -DskipTests
```
