### ISSUE TITLE
Cannot Build 2.3

### ISSUE THREAD

**Issue by ghost** [neo4j/neo4j#4481]
Attempting to build recently cloned repository on Ubuntu 14.04 trusty.

Maven Version:

Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.7.0_75, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-43-generic", arch: "amd64", family: "unix"

Running `mvn clean install -DminimalBuild`

Results in:

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7:43.068s
[INFO] Finished at: Tue Apr 21 10:02:00 EDT 2015
[INFO] Final Memory: 140M/546M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project neo4j-ha: Could not resolve dependencies for project org.neo4j:neo4j-ha:jar:2.3-SNAPSHOT: Failure to find org.neo4j:neo4j-backup:jar:tests:2.3-SNAPSHOT in http://m2.neo4j.org/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of neo4j-snapshot-repository has elapsed or updates are forced -> [Help 1]

**Comment by chrisvest** [comment]
I usually build with `mvn clean install -DskipTests`. That would also put some snapshot jars in your local maven repository, in case that's the only thing preventing the `-DminimalBuild` from working.

**Comment by jakewins** [comment]
https://github.com/neo4j/neo4j/blob/2.3/README.asciidoc

**Comment by jakewins** [comment]
Sorry, that was meant to be a link to a commit, not to the README. I've updated the readme to not talk about -DminimalBuild; https://github.com/neo4j/neo4j/commit/a472c909849e871995d49fc812cf36d5797029d3
