### ISSUE TITLE
No such topic to play: `:play sysinfo`

### ISSUE THREAD

**Issue by thobe** [neo4j/neo4j#4487]
Clicking this button:
![clicking this button](https://cloud.githubusercontent.com/assets/104385/7269831/603db57e-e8d7-11e4-8ea0-4be3630bc1f0.png)

Gives this result:
![gives this result](https://cloud.githubusercontent.com/assets/104385/7269837/66461cd6-e8d7-11e4-9784-91d9852a0233.png)

`:play sysinfo` works in version `2.2.0`, but not in `2.2.1` or `2.3.0-M01`.

**Comment by dvic** [comment]
I have the same problem.

**Comment by samis** [comment]
I have this too.

**Comment by richarddavenport** [comment]
Yep.

**Comment by oskarhane** [comment]
Fixed in https://github.com/neo4j/neo4j/pull/4606
