### ISSUE TITLE
Different aggregated results between 2.2.0 and 2.2.1

### ISSUE THREAD

**Issue by dthomas62** [neo4j/neo4j#4492]
I've been running the following query on 2.17 through to 2.2.0:

MATCH (e:Event {eventType: "14", timeslot: 5}) 
WITH e 
MATCH (Serial {id: e.serial})-[:INSEGMENT]-(seg:Segment {id: 4}), 
path = (e)-[:PREV_3]->(pe:Event) 
RETURN [node in nodes(path)[1..] | node.eventType] as et, count(_) as count 
ORDER by count desc

I get a list of aggregated results as expected:

et          count
[14, 7, 14] 9
[12, 8, 7]      8
[14, 14, 14]    8
[14, 14, 7] 6
[8, 14, 8]      6
etc 

returns 154 rows

When I run the same query on 2.2.1 I get 1 for each count, i.e. no aggregation takes place.

et              count
[8, 7, 14]      1
[16, 16, 14]    1
[14, 7, 14] 1
[8, 14, 8]      1
[14, 14, 14]    1
etc 

returns 279 rows 

Manual aggregation returns the correct results.

Additionally on 2.2.1 when I precede the query with PLANNER RULE I get the expected results as in 2.2.0.

Not sure if there is a problem with my query but thought I should report this result anyway.

**Comment by sherfert** [comment]
Sorry to be picking this up so late. Can you do two things:

- Provide a CYPHER query that sets up a minimal set of nodes and relationships to trigger that behavior subsequently

- Verify that the issue still exists on 2.3 or later (our currently supported versions)

**Comment by sherfert** [comment]
Am closing because of the lacking response. Feel free to reopen if that is still an issue
