### ISSUE TITLE
Cypher Parser bug: do not allow to get property of node in collection

### ISSUE THREAD

**Issue by garmoshka-mo** [neo4j/neo4j#4526]
`relationships(path)[1].index` says:

```
Invalid input '.': expected whitespace, '[', "=~", IN, IS, '^', '*', '/', '%', '+', '-', '<', '>', "<=", ">=", '=', "<>", "!=", AND, XOR, OR, AS, ',', Order, Skip, Limit, LOAD CSV, START, MATCH, UNWIND, MERGE, CREATE, SET, DELETE, REMOVE, FOREACH, WITH, RETURN, UNION, ';' or end of input 
```

Workaround is ugly as hell:  `[r IN [relationships(path)[1]] | r.index][0]`

**Comment by jexp** [comment]
```
WITH relationships(path)[1] as r
 ...r.index
```

**Comment by garmoshka-mo** [comment]
It is better workaround, but not for each case,
mine is:

```
MATCH p=({ID: 8898})-->()<-[*0..2]-({ID:5385})
return reduce(min_weight=100, i IN range(0, length(p)) |
    CASE
      WHEN min_weight > COALESCE(toInt([r IN [relationships(p)[i]] | r.index][0]), 100)
        THEN COALESCE(toInt([r IN [relationships(p)[i]] | r.index][0]), 100)
      ELSE
        min_weight
    END
) as min_weight
```

Sense is to return thinnest relation

**Comment by cleishm** [comment]
It's likely a precedence concern. Try `(relationships(path)[1]).index`?

**Comment by garmoshka-mo** [comment]
Yeah, that works, thanx!

**Comment by jexp** [comment]
Just FYI your query is not likely to perform well on larger datasets if you don't provide a label + index on your nodes..

**Comment by garmoshka-mo** [comment]
Thanx, will optimize this

**Comment by AshishBarde** [comment]
Hi,
     My name is Ashish Bardiya from India I am using Neo4j graph database I
have one problem when my data is 10 lakh nodes the cypher query execution
goes very slow It will take 2 to 3 min for excecution please help me out on
these... and also give me some solution how to take hot backup of neo4j
graph database

On Sat, Apr 25, 2015 at 12:29 PM, garmoshka-mo notifications@github.com
wrote:

> Thanx, will optimize this
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/neo4j/neo4j/issues/4526#issuecomment-96144783.

## 

hi..
if u want any document plz reply me
