### ISSUE TITLE
Windows Installer failes privilege escalation

### ISSUE THREAD

**Issue by tbaum** [neo4j/neo4j#4538]
I downloaded the x64 windows installer.
Started the installation, it fails writing to programm-files directory.
I'm not running my desktop with admin privileges.

The installer should ask for admin-credentials and escalate if the user is trying to install into an admin-only directory.

**Comment by glennsarti** [comment]
@tbaum Hi,  can I get some more information about this issue;
- Operating system version
- What are the current settings for UAC (http://windows.microsoft.com/en-AU/windows7/How-do-I-change-the-behavior-of-User-Account-Control-by-using-Group-Policy)
- Did you try the 32bit installer to see if has the same behaviour?

**Comment by tbaum** [comment]
> Am 29.04.2015 um 06:39 schrieb Glenn notifications@github.com:
> 
> @tbaum https://github.com/tbaum Hi, can I get some more information about this issue;
> 
> Operating system version
> Windows 7 ultimate (german) 64bit 
> Service Pack 1

# cmd reports:

Microsoft Windows [Version 6.1.7601]

> What are the current settings for UAC (http://windows.microsoft.com/en-AU/windows7/How-do-I-change-the-behavior-of-User-Account-Control-by-using-Group-Policy http://windows.microsoft.com/en-AU/windows7/How-do-I-change-the-behavior-of-User-Account-Control-by-using-Group-Policy)
> default settings:  always ask.  (slider at top)  
> I attached the gpo settings (sorry windows prints them localized)

keep in mind I’m not logged in with admin privileges

> Did you try the 32bit installer to see if has the same behaviour?
> —
> Reply to this email directly or view it on GitHub https://github.com/neo4j/neo4j/issues/4538#issuecomment-97302330.

Richtlinie  Sicherheitseinstellung
Interaktive Anmeldung: Anzahl zwischenzuspeichernder vorheriger Anmeldungen (für den Fall, dass der Domänencontroller nicht verfügbar ist)   10 Anmeldungen
Netzwerksicherheit: Minimale Sitzungssicherheit für NTLM-SSP-basierte Clients (einschließlich sicherer RPC-Clients)   128-Bit-Verschlüsselung erfordern
Netzwerksicherheit: Minimale Sitzungssicherheit für NTLM-SSP-basierte Server (einschließlich sicherer RPC-Server) 128-Bit-Verschlüsselung erfordern
Microsoft-Netzwerk (Server): Leerlaufzeitspanne bis zum Anhalten der Sitzung    15 Minuten
Domänenmitglied: Maximalalter von Computerkontenkennwörtern   30 Tage

Interaktive Anmeldung: Anwender vor Ablauf des Kennworts zum Ändern des Kennworts auffordern   5 Tage
Konten: Administrator umbenennen    Administrator
Benutzerkontensteuerung: Alle Administratoren im Administratorbestätigungsmodus ausführen Aktiviert
Benutzerkontensteuerung: Anwendungsinstallationen erkennen und erhöhte Rechte anfordern    Aktiviert
Benutzerkontensteuerung: Bei Benutzeraufforderung nach erhöhten Rechten zum sicheren Desktop wechseln  Aktiviert
Benutzerkontensteuerung: Datei- und Registrierungsschreibfehler an Einzelbenutzerstandorte virtualisieren   Aktiviert
Benutzerkontensteuerung: Erhöhte Rechte nur für UIAccess-Anwendungen, die an sicheren Orten installiert sind  Aktiviert
Domänenmitglied: Daten des sicheren Kanals digital signieren (wenn möglich)   Aktiviert
Domänenmitglied: Daten des sicheren Kanals digital verschlüsseln (wenn möglich)  Aktiviert
Domänenmitglied: Daten des sicheren Kanals digital verschlüsseln oder signieren (immer)   Aktiviert
Domänenmitglied: Starker Sitzungsschlüssel erforderlich (Windows 2000 oder höher)    Aktiviert
Geräte: Entfernen ohne vorherige Anmeldung erlauben    Aktiviert
Herunterfahren: Herunterfahren des Systems ohne Anmeldung zulassen  Aktiviert
Konten: Lokale Kontenverwendung von leeren Kennwörtern auf Konsolenanmeldung beschränken  Aktiviert
Microsoft-Netzwerk (Client): Kommunikation digital signieren (wenn Server zustimmt) Aktiviert
Microsoft-Netzwerk (Server): Clientverbindungen aufheben, wenn die Anmeldezeit überschritten wird  Aktiviert
Netzwerksicherheit: Keine LAN Manager-Hashwerte für nächste Kennwortänderung speichern   Aktiviert
Netzwerkzugriff: Anonyme Aufzählung von SAM-Konten nicht erlauben  Aktiviert
Netzwerkzugriff: Anonymen Zugriff auf Named Pipes und Freigaben einschränken   Aktiviert
Systemobjekte: Groß-/Kleinschreibung für Nicht-Windows-Subsysteme ignorieren  Aktiviert
Systemobjekte: Standardberechtigungen interner Systemobjekte (z. B. symbolischer Verknüpfungen) verstärken    Aktiviert
Benutzerkontensteuerung: Administratorbestätigungsmodus für das integrierte Administratorkonto    Deaktiviert
Benutzerkontensteuerung: Nur ausführbare Dateien heraufstufen, die signiert und überprüft sind   Deaktiviert
Benutzerkontensteuerung: UIAccess-Anwendungen können erhöhte Rechte ohne sicheren Desktop anfordern   Deaktiviert
Domänenmitglied: Änderungen von Computerkontenkennwörtern deaktivieren   Deaktiviert
Geräte: Anwendern das Installieren von Druckertreibern nicht erlauben  Deaktiviert
Herunterfahren: Auslagerungsdatei des virtuellen Arbeitspeichers löschen   Deaktiviert
Interaktive Anmeldung: Domänencontrollerauthentifizierung zum Aufheben der Sperrung der Arbeitsstation erforderlich    Deaktiviert
Interaktive Anmeldung: Letzten Benutzernamen nicht anzeigen Deaktiviert
Interaktive Anmeldung: Smartcard erforderlich   Deaktiviert
Konten: Administratorkontostatus    Deaktiviert
Konten: Gastkontenstatus    Deaktiviert
Microsoft-Netzwerk (Client): Kommunikation digital signieren (immer)    Deaktiviert
Microsoft-Netzwerk (Client): Unverschlüsseltes Kennwort an SMB-Server von Drittanbietern senden    Deaktiviert
Microsoft-Netzwerk (Server): Kommunikation digital signieren (immer)    Deaktiviert
Microsoft-Netzwerk (Server): Kommunikation digital signieren (wenn Client zustimmt) Deaktiviert
Netzwerksicherheit: Abmeldung nach Ablauf der Anmeldezeit erzwingen Deaktiviert
Netzwerkzugriff: Anonyme Aufzählung von SAM-Konten und Freigaben nicht erlauben    Deaktiviert
Netzwerkzugriff: Anonyme SID-/Namensübersetzung zulassen   Deaktiviert
Netzwerkzugriff: Die Verwendung von "Jeder"-Berechtigungen für anonyme Benutzer ermöglichen   Deaktiviert
Netzwerkzugriff: Speicherung von Kennwörtern und Anmeldeinformationen für die Netzwerkauthentifizierung nicht zulassen    Deaktiviert
Systemeinstellungen: Zertifikatsregeln zur Durchsetzung von Softwareeinschränkungsrichtlinien auf Windows-Programme anwenden   Deaktiviert
Systemkryptografie: FIPS-konformen Algorithmus für Verschlüsselung, Hashing und Signatur verwenden    Deaktiviert
Überwachung: Die Verwendung des Sicherungs- und Wiederherstellungsrechts überprüfen  Deaktiviert
Überwachung: System sofort herunterfahren, wenn Sicherheitsüberprüfungen nicht protokolliert werden können  Deaktiviert
Überwachung: Zugriff auf globale Systemobjekte prüfen Deaktiviert
Wiederherstellungskonsole: Automatische administrative Anmeldungen zulassen Deaktiviert
Wiederherstellungskonsole: Kopieren von Disketten und Zugriff auf alle Laufwerke und alle Ordner zulassen   Deaktiviert
Benutzerkontensteuerung: Verhalten der Eingabeaufforderung für erhöhte Rechte für Standardbenutzer   Eingabeaufforderung zu Anmeldeinformationen
Benutzerkontensteuerung: Verhalten der Eingabeaufforderung für erhöhte Rechte für Administratoren im Administratorbestätigungsmodus Eingabeaufforderung zur Zustimmung für Nicht-Windows-Binärdateien
Konten: Gastkonto umbenennen    Gast
Interaktive Anmeldung: Verhalten beim Entfernen von Smartcards  Keine Aktion
Netzwerkzugriff: Modell für gemeinsame Nutzung und Sicherheitsmodell für lokale Konten    Klassisch - lokale Benutzer authentifizieren sich als sie selbst
DCOM: Computerstarteinschränkungen in Security Descriptor Definition Language (SDDL)-Syntax    Nicht definiert
DCOM: Computerzugriffseinschränkungen in Security Descriptor Definition Language (SDDL)-Syntax Nicht definiert
Domänencontroller: Änderungen von Computerkontenkennwörtern verweigern   Nicht definiert
Domänencontroller: Serveroperatoren das Einrichten von geplanten Aufgaben erlauben Nicht definiert
Domänencontroller: Signaturanforderungen für LDAP-Server  Nicht definiert
Geräte: Formatieren und Auswerfen von Wechselmedien zulassen   Nicht definiert
Geräte: Zugriff auf CD-ROM-Laufwerke auf lokal angemeldete Benutzer beschränken   Nicht definiert
Geräte: Zugriff auf Diskettenlaufwerke auf lokal angemeldete Benutzer beschränken Nicht definiert
Interaktive Anmeldung: Benutzerinformationen anzeigen, wenn Sitzung gesperrt ist    Nicht definiert
Interaktive Anmeldung: Kein STRG+ALT+ENTF erforderlich  Nicht definiert

Microsoft-Netzwerkserver: SPN-Zielnamenüberprüfungsstufe für Server  Nicht definiert
Netzwerksicherheit: Beschränken von NTLM: Ausgehender NTLM-Datenverkehr zu Remoteservern   Nicht definiert
Netzwerksicherheit: Beschränken von NTLM: Eingehenden NTLM-Datenverkehr überwachen    Nicht definiert
Netzwerksicherheit: Beschränken von NTLM: Eingehender NTLM-Datenverkehr    Nicht definiert
Netzwerksicherheit: Beschränken von NTLM: NTLM-Authentifizierung in dieser Domäne Nicht definiert
Netzwerksicherheit: Beschränken von NTLM: NTLM-Authentifizierung in dieser Domäne überwachen Nicht definiert
Netzwerksicherheit: Beschränken von NTLM: Remoteserverausnahmen für die NTLM-Authentifizierung hinzufügen    Nicht definiert
Netzwerksicherheit: Beschränken von NTLM: Serverausnahmen in dieser Domäne hinzufügen    Nicht definiert
Netzwerksicherheit: Für Kerberos zulässige Verschlüsselungstypen konfigurieren   Nicht definiert
Netzwerksicherheit: LAN Manager-Authentifizierungsebene Nicht definiert

Netzwerksicherheit: Lokalem System die Verwendung der Computeridentität für NTLM erlauben Nicht definiert
Netzwerksicherheit: Zulassen von an diesen Computer gerichteten PKU2U-Authentifizierungsanforderungen zur Verwendung von Onlineidentitäten Nicht definiert
Netzwerksicherheit: Zurückgreifen auf NULL-Sitzung für lokales System zulassen    Nicht definiert
Netzwerkzugriff: Freigaben, auf die anonym zugegriffen werden kann  Nicht definiert
Systemkryptografie: Starken Schlüsselschutz für auf dem Computer gespeicherte Benutzerschlüssel erzwingen    Nicht definiert
Überwachung: Unterkategorieeinstellungen der Überwachungsrichtlinie erzwingen (Windows Vista oder höher), um Kategorieeinstellungen der Überwachungsrichtlinie außer Kraft zu setzen   Nicht definiert

Systemeinstellungen: optionale Subsysteme   Posix
Netzwerksicherheit: Signaturanforderungen für LDAP-Clients Signatur aushandeln
Netzwerkzugriff: Registrierungspfade und -unterpfade, auf die von anderen Computern aus zugegriffen werden kann System\CurrentControlSet\Control\Print\Printers,System\CurrentControlSet\Services\Eventlog,Software\Microsoft\OLAP Server,Software\Microsoft\Windows NT\CurrentVersion\Print,Software\Microsoft\Windows NT\CurrentVersion\Windows,System\CurrentControlSet\Control\ContentIndex,System\CurrentControlSet\Control\Terminal Server,System\CurrentControlSet\Control\Terminal Server\UserConfig,System\CurrentControlSet\Control\Terminal Server\DefaultUserConfiguration,Software\Microsoft\Windows NT\CurrentVersion\Perflib,System\CurrentControlSet\Services\SysmonLog
Netzwerkzugriff: Registrierungspfade, auf die von anderen Computern aus zugegriffen werden kann System\CurrentControlSet\Control\ProductOptions,System\CurrentControlSet\Control\Server Applications,Software\Microsoft\Windows NT\CurrentVersion

Interaktive Anmeldung: Nachricht für Benutzer, die sich anmelden wollen  
Interaktive Anmeldung: Nachrichtentitel für Benutzer, die sich anmelden wollen 
Netzwerkzugriff: Named Pipes, auf die anonym zugegriffen werden kann

**Comment by glennsarti** [comment]
Thanks @tbaum . My German isn't great but I can still decipher the settings.  Did you get a change to try a 32bit install to see if it has a similar issue?  The reason I'm asking is I think 32bit apps automatically get elevated whereas 64bit will depend whether the app requests it.  A quick look over the Install4j script suggests that it does say it want's to elevate.

**Comment by glennsarti** [comment]
Hi @tbaum 

Just chasing up if you managed to try the 32bit install?
