### ISSUE TITLE
Support Java 8

### ISSUE THREAD

**Issue by shemnon** [neo4j/neo4j#4581]
I saw this line in the message log.  (Neo4j 2.2.1 community edition)

2015-05-06 16:25:41.416+0000 INFO  [org.neo4j]: You are using an unsupported version of the Java runtime. Please use Oracle(R) Java(TM) Runtime Environment 7 or OpenJDK(TM) 7.

Oracle has stopped pubic support for Java 7, so no new security patches will find their way into the public or open JDK trees.  

The bug is that Neo4j should have a community version that is supported on at least one JDK version that is supported by Oracle.

**Comment by cleishm** [comment]
Hi @shemnon,

The Neo4j team are actively working on certifying Neo4j with Java 8 JVMs. Once we're confident that it is as reliable on Java 8 as it has been on Java 7, we'll make a new release that removes that warning.

Cheers,
Chris

**Comment by cleishm** [comment]
Java 8 support is available as of the Neo4j 2.2.2 release.
