### ISSUE TITLE
Isn't TransactionTemplate missing the failure handling?

### ISSUE THREAD

**Issue by tkroman** [neo4j/neo4j#4582]
I really like how easy it became to handle non-fatal exceptions now that the `TransactionTemplate` was introduced, but the `Monitor` class seems to have `failed()` method, which isn't used anywhere, while another (`failure()`) is used in case a `Throwable` is caught. Is it the intended behavior? Do you have some plans for the future? I think it would be useful to place a call to `failed()` right before the `break` happens (in case an exception is not accepted by the predicate).
https://github.com/neo4j/neo4j/blob/2.2.1/community/kernel/src/main/java/org/neo4j/helpers/TransactionTemplate.java#L157

You might have completely different intentions about the usage, so I'm just asking if the fact that this method is unused is normal or just something someone had overlooked.

I would be glad to implement the feature myself along with a couple of tests in case I'm right.

**Comment by klaren** [comment]
This looks like a bug in the implementation, I've created a PR to fix it. `failed()` is called after all the retries have failed or the thread is interrupted. Since this bug fix changes behavior, it will only go into the next release and not be backported.

Thanks for reporting!
