### ISSUE TITLE
Incorrect Response for Invalid HTTP Method

### ISSUE THREAD

**Issue by ToastedBits** [neo4j/neo4j#4584]
When invoking the neo4j REST api with the wrong http method, the client receives an "invalid authorization" message instead of "invalid http method" message, despite the credentials being correct. This misleads the developer to believe they are providing incorrect credentials or something else is wrong with the authentication mechanism.

In my testing I used Jersey Client and was improperly using http post against /db/data instead of get. API works as expected after correcting to the proper http method. Suspect this is an issue affecting more than /db/data/ but have not tested further.

**Comment by cleishm** [comment]
Hi @ToastedBits,

I can't reproduce this myself:

```
% curl -u 'neo4j:test' -v -X POST http://127.0.0.1:7474/db/data/
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 7474 (#0)
* Server auth using Basic with user 'neo4j'
> POST /db/data/ HTTP/1.1
> Authorization: Basic bmVvNGo6dGVzdA==
> User-Agent: curl/7.37.1
> Host: 127.0.0.1:7474
> Accept: */*
> 
< HTTP/1.1 405 Method Not Allowed
< Date: Sat, 09 May 2015 08:51:43 GMT
< Allow: GET,OPTIONS,HEAD
< Access-Control-Allow-Origin: *
< Content-Length: 0
* Server Jetty(9.2.4.v20141103) is not blacklisted
< Server: Jetty(9.2.4.v20141103)
< 
* Connection #0 to host 127.0.0.1 left intact
```

Do you have any further detail regarding this, that would help to reproduce it?
