### ISSUE TITLE
Build fails while generating man pages

### ISSUE THREAD

**Issue by citruz** [neo4j/neo4j#4627]
Hi,

I am trying to build Neo4j from source on Mac OSX 10.10 by executing `mvn clean install -DfullBuild -DskipTests=true`.
70% of the modules compile without errors, until I get an error while processing "Cypher Reference Card - Reference Manual":

```
Creating manpage 'neo4j-import' from component 'import-tool' at /Users/felix/Development/neo4j/manual/target/manpages/neo4j-import.1.xml
asciidoc: WARNING: neo4j-import.1.asciidoc: line 26: include file not found: /Users/felix/Development/neo4j/manual/target/contents/docs/neo4j-import-tool-docs-jar/man/options.adoc
asciidoc: WARNING: neo4j-import.1.asciidoc: line 43: include file not found: /Users/felix/Development/neo4j/manual/target/contents/docs/neo4j-import-tool-docs-jar/ops/movies.csv
...
make: *** [manpages] Error 1
```

Is this an issue on my side? How to fix it?

Cheers, Felix

**Comment by jexp** [comment]
If you skip tests much of the docs sources is not generated 

Von meinem iPhone gesendet

**Comment by citruz** [comment]
Oh I see. I just did that because it takes forever on my little MacBook ;) 
Thanks for the hint!
