### ISSUE TITLE
error in pom file during building Neo4j-2.3-Snapshot

### ISSUE THREAD

**Issue by vinaykaradia** [neo4j/neo4j#4652]
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T07:57:37-04:00)
Maven home: /usr/local/apache-maven-3.3.3
Java version: 1.8.0_40-internal, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-ppc64el/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.16.0-23-generic", arch: "ppc64", family: "unix"

Running : 
mvn -X clean install  -Dlicense.skip=true

Result in Error: 

[INFO] Scanning for projects...
Downloading: https://repo.maven.apache.org/maven2/org/neo4j/build/parent-central/41/parent-central-41.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.neo4j:parent:2.3-SNAPSHOT: Could not transfer artifact org.neo4j.build:parent-central:pom:41 from/to central (https://repo.maven.apache.org/maven2): java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty and 'parent.relativePath' points at no local POM @ line 5, column 11
 @
[ERROR] The build could not read 1 project -> [Help 1]

**Comment by daonb** [comment]
BUMP!
I suspect it's has something to do with java-8. It got that error under this configuration:

```
$ mvn -v
Apache Maven 3.3.3
Maven home: /usr/share/maven
Java version: 1.8.0_66-internal, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
```

And not wuth the older java :

```
$ mvn -v
Apache Maven 3.3.3
Maven home: /usr/share/maven
Java version: 1.7.0_85, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.2.0-16-generic", arch: "amd64", family: "unix"
```

**Comment by spacecowboy** [comment]
Neo4j 2.3 must be built with java7.
