### ISSUE TITLE
Scalar function on returned String failed (null)

### ISSUE THREAD

**Issue by fcauchois** [neo4j/neo4j#4688]
... toInt(myattribute) => work as espected
... toInt(str(myattribute)) => null value returned (every time !)

Exemple 1 :

myattribute : "< 152"
toInt(replace(myattribute, "< ", "")) => 152
toInt(replace(str(myattribute), "< ", "")) => null

Exemple 2 (even simplier) :

toInt("4") => 4
toInt(str("4")) => null

**Comment by jexp** [comment]
Thanks a lot for your report, I forwarded it to the engineering team.

**Comment by cleishm** [comment]
Hey @lourai: Try using `toString(...)` instead of `str(...)`?

**Comment by Mats-SX** [comment]
Since `str()` no longer exist, this issue is obsolete. Closing.
