### ISSUE TITLE
Can't use a "seek by id" operator when using unwind

### ISSUE THREAD

**Issue by telaviv** [neo4j/neo4j#4693]
I have the following query:

``` cypher
profile
unwind [83, 84] as record
match (m:match)
where id(m) = record
return m
```

and this is the query plan it gives for me:

![Query Plan showing a seek by label](http://s4.postimg.org/p8gwsbxhp/Screen_Shot_2015_05_25_at_3_15_31_PM.png)

As you can see it chooses to scan by label instead of seeking by id. Outside of an unwind it works as expected. Since I need the unwind, I think my workaround for this will be to use my own uuid as a property and put an index on it. Hopefully that works too.

**Comment by jexp** [comment]
Thanks a lot for your report, I forwarded it to the cypher team.

**Comment by systay** [comment]
Hi there @telaviv 

Is it possible for you to try this on a recent copy of Neo4j 2.3? When I try to reproduce your problem locally, I get the expected NodeByIdSeek and not a NodeByLabelScan.

**Comment by boggle** [comment]
Works in 2.3
