### ISSUE TITLE
CREATE UNIQUE race condition

### ISSUE THREAD

**Issue by area** [neo4j/neo4j#4697]
I am using the REST endpoint for making Cypher queries. I have encountered an issue that if I have two nodes (a `user` node and a `decision` node) with no relationship between them, and then fire two identical queries in quick succession to the endpoint:

```
MATCH (u:user {id:{userid}}), (a:decision {id:{decisionid}}) CREATE UNIQUE (u)-[r:VOTES]->(a)
```

Then I end up with two VOTES relationships, which is obviously undesired if I am using `CREATE UNIQUE`. I cannot put a constraint on a relationship, so I'm not sure how to guarantee uniqueness in this situation. Is there a recommended solution?

Of course, if I POST to the endpoint with some amount of time between the requests, I end up with only one relationship, as desired. However, as users will ultimately be able to trigger these requests, this isn't really a useful solution!

**Comment by lamoni** [comment]
+1

**Comment by galbello** [comment]
+1

**Comment by tanapoln** [comment]
+1

**Comment by RomanCher** [comment]
+1

**Comment by lauralorenz** [comment]
+1

**Comment by systay** [comment]
`CREATE UNIQUE` has been deprecated. Use `MERGE` instead, which will take the appropriate locks to make sure that this never happens.

**Comment by Gudahtt** [comment]
@systay has this deprecation been documented anywhere? Or is that due for the next release
