### ISSUE TITLE
Distinct with returning multiple properties

### ISSUE THREAD

**Issue by snig-b** [neo4j/neo4j#4709]
I am running neo4j v 2.2.2

I want to return specific properties of my nodes out of my Match but I want to return only rows where field_name is unique.

Example : 

Match (a:A) - [r:R] -> [b:B] - [r1:R1] -> (c:C)
RETURN distinct b.field_name, a.foo, a.bar, b.foo1, c.bar1

Should return me unique field_names in b and the corresponding matched node's properties.

How can I make this possible since distinct works on the full row. 
And I do not want to use collect() aas it is a GROUP_BY version which is not my requirement.

Expected Output:

| **field_name** | **foo** | **bar** | **foo1** | **bar1** |
| --- | --- | --- | --- | --- |
| abc | 1 | x | y | z |
| def | 3 | x | a | b |
| xyz | 4 | f | b | c |

but any match with b.field_name = abc is not included.

Any help appreciated. Thanks

**Comment by jexp** [comment]
> RETURN  b.field_name, head(collect([a.foo, a.bar, b.foo1, c.bar1]))

Von meinem iPhone gesendet
