### ISSUE TITLE
Login information persisted in browser

### ISSUE THREAD

**Issue by ghost** [neo4j/neo4j#4712]
After logging in to a neo4j instance, the username and password are kept in local storage. It would be better if this was not persisted and the user was forced to log in every time they wished to access a neo4j instance.

**Comment by jakewins** [comment]
This feature is available in Neo4j enterprise, simply `dbms.browser.store_credentials=false` or `dbms.browser.credential_timeout=60s`. For community edition, you'll have to log out manually.
