### ISSUE TITLE
Difference in cypher match behaviour between 2.1.8 and 2.2.2

### ISSUE THREAD

**Issue by ivotkv** [neo4j/neo4j#4717]
Hi,

We've run into an issue with a query that works fine in 2.1.8 but returns no results in 2.2.2:

```
START       n = NODE({ids})
MATCH       n<-[:comment*1..3]-c,
            pc<-[:comment]-c
RETURN      ID(pc), ID(c)
```

Changing the query to this fixed the problem:

```
START       n = NODE({ids})]
MATCH       n<-[:comment*1..3]-c
WITH        c
MATCH       pc<-[:comment]-c
RETURN      ID(pc), ID(c)
```

Thanks!

**Comment by jexp** [comment]
Can you share the two query plans that are created by prefixing your query wit `PROFILE` in the browser.

**Comment by ivotkv** [comment]
Hi Michael,

Here is the plan for the original query:

![plan1](https://cloud.githubusercontent.com/assets/462940/7869947/d1b5b1a0-0553-11e5-825b-0b79aaf42d57.png)

And the plan for the corrected query:

![plan2](https://cloud.githubusercontent.com/assets/462940/7869948/d1b785ca-0553-11e5-90c6-906c14446a04.png)

**Comment by jexp** [comment]
Can you check manually on the data that the result in 2.1.x is _really correct_?
We fixed some incorrect behavior of this pattern matching in 2.2.x 

Would you be able to create a sample graph setup that shows the wrong results in 2.2 and the correct ones in 2.1.x ?

**Comment by jexp** [comment]
Can you also try to rewrite your query to, **not use START**

```
MATCH       n<-[:comment*1..3]-c,
            pc<-[:comment]-c
WHERE id(n) IN {ids}
RETURN      ID(pc), ID(c)
```

**Comment by ivotkv** [comment]
The rewritten query also yields no results, here is the query plan:

![plan](https://cloud.githubusercontent.com/assets/462940/7897259/e73d1c52-06a2-11e5-8b8e-223860498974.png)

I am certain that the results in 2.1.8 are correct and reflect the actual data. However, it's possible that the syntax we were using is a bit strange and is not the actual intended way to be using cypher in that case, I'm merely pointing out that the behaviour has changed.

The data itself is fairly simple, it's a tree-like structure of comments that looks like:

(n1)<-[:comment]-(n2)<-[:comment]-(n3)
(n1)<-[:comment]-(n4)
etc...

We basically match all nodes in the tree, and for each node return its id and its parent's id.

If I were to guess why the original single-match pattern no longer works:

```
MATCH       n<-[:comment*1..3]-c,
            pc<-[:comment]-c
```

I would say that it expects `pc` to be a new node that has not already been matched (since `pc`, being the parent of `c`, would've been traversed in the first line), and since no such node exists it returns an empty result.

Again, I'm not sure what the correct behaviour of cypher is expected to be, just that it has changed.

**Comment by jexp** [comment]
It is probably already this that would make your query succeed:

I presume you want to see the parent-comment of the last comment, while doing that you run into the relationship-uniqueness criteria of cypher, within a single pattern each relationship _must_ only appear once.

And in your pattern the last `:comment` relationship-instance appears twice which is filtered out so no paths are returned.

```
MATCH       n<-[:comment*1..3]-c
MATCH            pc<-[:comment]-c
WHERE id(n) IN {ids}
RETURN      ID(pc), ID(c)
```

If you split up the pattern like this then you get two different paths where the check of relationship-uniqueness doesn't happen across both.

You can also split up your normal match like this, which should also work and is more efficient.

```
MATCH       n<-[:comment*0..2]-pc<-[:comment]-c
WHERE id(n) IN {ids}
RETURN      ID(pc), ID(c)
```

Please try it and report back.

**Comment by ivotkv** [comment]
Hi Michael,

Yes, both of those return the correct results. From your explanation, it seems the behaviour in 2.1.8 was actually a bug which has now been fixed.

Thanks!
