### ISSUE TITLE
Browser console: multi-line comments are not greyed out

### ISSUE THREAD

**Issue by mindrones** [neo4j/neo4j#4721]
In the browser console, multi-line comments are not greyed out as single-line comments.

![neo4j_browser_multiline_comment](https://cloud.githubusercontent.com/assets/1309648/7880974/c4d1e0c0-05fe-11e5-97c2-5dffe41c2702.png)

BTW: although working as expected, multi-line comments are not mentioned [in the documentation](http://neo4j.com/docs/2.2.2/cypher-comments.html), is this intended?

**Comment by jexp** [comment]
Not sure this was intentional to work :) At least I haven't seen it before anywhere.

**Comment by mindrones** [comment]
Well then please consider this a feature request :)

**Comment by oskarhane** [comment]
This issue was moved to neo4j/neo4j-browser#138
