### ISSUE TITLE
neo4j deleting my array data.  Array operations seem broken.

### ISSUE THREAD

**Issue by MichaelJCole** [neo4j/neo4j#4734]
Hi, I'm importing data into a Neo4j graph.

I'm importing "Topics", some of which have .aliases set as an array, some don't.

The CSV comes with:

```
TopicName, Alias, Aliases
'Bob', 'Robert', 'Bobby;BigB''
```

```
LOAD CSV WITH HEADERS FROM "file:///home/michael/db/Aliases.csv" AS r
MATCH (t:Topic { mysql_id: toInt(r.id)})
SET t.aliases = [] + t.aliases + split(r.aliases, ';') + r.alias;
// Where t.aliases, r.aliases, or r.alias can be null.
// If any are null then the result is null, erasing the other data.
```

The problem is adding any null to an array nulls the array. Which seems _crazy_ to me.  What use case was that behavior designed for?  Adding null to an array should treat the null as an empty set, not an existential crisis and obliterate itself.

I made a workaround by using three queries:

Create Topic and set t.aliases = [] + r.alias which may be null
Update Topic with r.aliases WHERE NOT HAS(t.aliases).
Update Topic with r.aliases WHERE HAS (t.aliases)

This seems like a broken syntax if I have to write 3 queries to work around it.

Am I missing something here?

**Comment by jexp** [comment]
You can use coalesce to deal with null values:

```
LOAD CSV WITH HEADERS FROM "file:///home/michael/db/Aliases.csv" AS r
MATCH (t:Topic { mysql_id: toInt(r.id)})
SET t.aliases = coalesce(t.aliases,[]) + split(coalesce(r.aliases,''), ';') + coalesce(r.alias,[]);
```

**Comment by MichaelJCole** [comment]
Ok, thank you!
