### ISSUE TITLE
upgrade jersey to 1.19 to be java 8 compatible

### ISSUE THREAD

**Issue by boferri** [neo4j/neo4j#4735]
since neo4j version 2.2.2 you claim to be java 8 compatible. however, neo4j-server isn't really java 8 compatible, since jersey version is 1.18.1. jersey 1.x is java 8 compatible from version 1.19 on. see http://blog.dejavu.sk/2015/02/13/jersey-1-19-is-released/

**Comment by boferri** [comment]
ping @jexp, @jimwebber et al.

**Comment by cleishm** [comment]
Hi @zazi,

To confirm: we test and this support running Neo4j on JDK 8. However, Neo4j server, which uses jersey as a dependency, is still built using Java 7. We'll likely switch to building with Java 8 in the next major release. If you're building server extensions, I'd suggest also building with JDK 7 for now.

Cheers,
Chris

**Comment by boferri** [comment]
@cleishm thanks a lot for the heads up ;)
We are building building our unmanaged extension even with Java 8 right now. However, we cannot make use of the syntactic sugar (lambdas etc.) that comes with Java 8 (in Jersey Resources (?!)) ;)
So next major release means 2.3 stable?

**Comment by boferri** [comment]
so, jersey 1.19 is integrated in neo4j 2.2.3?

**Comment by jotomo** [comment]
Yup, jersey 1.19 is in 2.2.3: https://github.com/neo4j/neo4j/blob/2.2.3/pom.xml#L653. However, what @cleishm said still applies w.r.t. JDK versions.

_Next major release_ should mean 3.0, see https://github.com/neo4j/neo4j/pull/4747#issuecomment-111218027

**Comment by cleishm** [comment]
Right, next major is Neo4j 3.0.

The inclusion of Jersey 1.19 into Neo4j 2.2.3 does mean that Neo4j will be able to read extensions compiled with Java 8 constructs. However, Neo4j itself is compiled with JDK 7, and we haven't tested or done any verification of the mixed use of JDK 7 compiled Neo4j and JDK 8 compiled extensions, so we continue to not recommend it for now.

**Comment by cleishm** [comment]
I will close this issue though, given Jersey 1.19 is in.
