### ISSUE TITLE
In a single query how to get feeds and also the information about which feeds have been liked by the logged in user

### ISSUE THREAD

**Issue by alchemistgo87** [neo4j/neo4j#4755]
"MATCH (f:Feed) WHERE f.feedType = 'sports' RETURN f order by f.timeAdded desc SKIP 4 LIMIT 10"

I want to retrieve feeds related to sports with pagination. For that I have written the query as above. But with this I also need to know about which resulting feeds have been liked by the logged in user. Suppose I have a user with username john, how would i add [:LIKE] relation to the above query.

**Comment by jexp** [comment]
Please ask such questions on [StackOverflow](http://stackoverflow.com/questions/tagged/neo4j) or the [Google Group](http://groups.google.com/group/neo4j/pendmsg).

This is an issue tracker for the Neo4j codebase. Thanks so much.
