### ISSUE TITLE
OPTIONAL MATCH behavior is different in 2.2.2 from how it used to work in 2.1.7

### ISSUE THREAD

**Issue by arturosevilla** [neo4j/neo4j#4758]
If I create the following database:

```
CREATE (user:User), (task:Task), (site:Site)
```

And I execute the following query:

```
MATCH (user:User)
OPTIONAL MATCH (user)-[pRel:WORKS_AT]->(site:Site)
with site
match (task:Task)
with task, site
optional match (task)-[originRel:FROM]->(site)
return task, originRel
```

No task will be returned. Note that `site` is actually `null` from the first leg of the query, and so the optional match being executed with the `FROM` relationship type would fail. But according to what happened in 2.1.7 only `originRel` would be set as null and not filter out the row.

Now if I execute the following query the task node will be returned as expected

```
MATCH (user:User)
OPTIONAL MATCH (user)-[pRel:WORKS_AT]->(site:Site)
with site
match (task:Task)
with task
optional match (task)-[originRel:FROM]->(site)
return task, originRel
```

And if I remove the with altogether as in the following query, then the task will not be returned once again. 

```
MATCH (user:User)
OPTIONAL MATCH (user)-[pRel:WORKS_AT]->(site:Site)
with site
match (task:Task)
optional match (task)-[originRel:FROM]->(site)
return task, originRel
```

In 2.1.7 all of these queries were returning the same result just with `originRel` as null

**Comment by cleishm** [comment]
Hi @arturosevilla,

I've reproduced that issue and passed it along to our team.

Cheers,
Chris
