### ISSUE TITLE
RelationshipType (in)equality

### ISSUE THREAD

**Issue by bachmanm** [neo4j/neo4j#4772]
I think this has bothered a lot of people for a long time, just checking if anyone would agree this should be fixed? Thanks

```
@Test
public void showLabelEquality() {
    assertEquals(DynamicLabel.label("TEST"), DynamicLabel.label("TEST"));
    assertEquals(DynamicLabel.label("TEST").name(), DynamicLabel.label("TEST").name());
}

@Test
public void showRelTypeEquality() {
    ///WATCH OUT!
    assertNotEquals(DynamicRelationshipType.withName("TEST"), DynamicRelationshipType.withName("TEST"));
    assertEquals(DynamicRelationshipType.withName("TEST").name(), DynamicRelationshipType.withName("TEST").name());
}
```

**Comment by jexp** [comment]
Actually it's not possible as RelationshipType is an interface.

So you can create arbitrary classes that implement that interface and if they don't implement their own equals & hashCode they don't equal other relationship-types.

We could implement that for DynamicRelationshipType and for the one returned from Kernel but in the end, every rel-type enum you'd write would have to implement those same methods and if only one doesn't the contract is broken.

So as much as I'd love to see that. I think it will not be possible.

Where do you need this functionality?? there is `relationship.hasType(type)`

**Comment by bachmanm** [comment]
Actually, this is the full story:

```
public class Gotcha {

    enum RelTypes implements RelationshipType {
        RT1,
    }

    enum Labels implements Label {
        L1,
    }

    @Test
    public void showLabelEquality() {
        assertEquals(DynamicLabel.label("L1"), DynamicLabel.label("L1"));
        assertNotEquals(L1, DynamicLabel.label("L1"));
        assertEquals(DynamicLabel.label("L1"), L1);  //this is not commutative
        assertEquals(L1, L1);
    }

    @Test
    public void showRelTypeEquality() {
        assertNotEquals(DynamicRelationshipType.withName("RT1"), DynamicRelationshipType.withName("RT1"));
        assertNotEquals(RT1, DynamicRelationshipType.withName("RT1"));
        assertNotEquals(DynamicRelationshipType.withName("RT1"), RT1);
        assertEquals(RT1, RT1);
    }
}

```

There are mainly two problems here and that's why I brought it up:
1) it is inconsistent
2) people who use their IDEs to get `hashCode()` and `equals()` generated for classes using `RelationshipType` or `Label` as fields get bitten by this. But I understand it is not possible to fix because they are interfaces.

Feel free to close this, maybe it's a case for a "gotcha" blog post than a fix. Cheers.

**Comment by chrisvest** [comment]
`DynamicRelationshipType` and `DynamicLabel` will be deprecated in 3.0 in favour of static factory methods on `RelationshipType` and `Label`, respectively. And the dynamic instances that these methods return will have consistent type+value equality:

https://github.com/neo4j/neo4j/commit/451252475140d47866602abf349575a41aa41cfa
