### ISSUE TITLE
Establish a convention for CSV comments

### ISSUE THREAD

**Issue by mindrones** [neo4j/neo4j#4776]
I'd like to comment rows for:
- comment out data without delete it 
- documentation
- navigation (a reference for the eye when manually scrolling long files containing "blocks" of data - different node/rel types for example)

I see that [rfc4180](http://tools.ietf.org/html/rfc4180) doesn't indicate how to comment a row so I'm supposing it's left to the application to follow a convention.

Would it be an option to establish a convention for CSV comments such that neo4j would not import comment lines?

Right now this `single_line_comments.csv`

```
:ID|:LABEL|name
foo|NODE|"foo"
// don't import these
//qoo|NODE|"qoo"
//baz|NODE|"baz"
bar|NODE|"bar"
```

imports 2 nodes of type `NODE` and 3 nodes with no label.

![screen shot 2015-06-05 at 12 53 46 pm](https://cloud.githubusercontent.com/assets/1309648/8004673/f1ae80f2-0b81-11e5-89a7-f7cddac81a2f.png)

**Comment by mindrones** [comment]
Possibly we might have `neo4j-import` options to indicate which string we intend to use for comments.

**`--line-comment`**

This string would indicate when how start a comment. For example

```
neo4j-import --into ../db --delimiter "|"  --line-comment "//" --nodes single_line_comments.csv
```

would skip line comments in `single_line_comments.csv` above.

**`--block-comment`**

This string would indicate the start and the end of a multi-line comment. For example

```
neo4j-import --into ../db --delimiter "|"  --block-comment "/**/" --nodes block-comments.csv
```

would skip block comments in `block-comments.csv`:

```
:ID|:LABEL|name
foo|NODE|"foo"
/*
qoo|NODE|"qoo"
baz|NODE|"baz"
*/
bar|NODE|"bar"
```

**Comment by chrisvest** [comment]
I think it's better if we just stick to following the standard, and rely on people to filter out any custom CSV format extensions they might have, prior to importing.
