### ISSUE TITLE
StandardBranchCollisionDetector memory footprint enhancement

### ISSUE THREAD

**Issue by AlexanderYastrebov** [neo4j/neo4j#4790]
Hi all.
Currently StandardBranchCollisionDetector saves all found paths in internal map (returnedPaths.add):
https://github.com/neo4j/neo4j/blob/fbf49112621991730617b0d7ffcd6afa632ea9b9/community/kernel/src/main/java/org/neo4j/kernel/StandardBranchCollisionDetector.java#L74

On the other hand BidirectionalTraverserIterator may filter out many of them (and filters out most of them in case of Uniqueness.NODE_PATH i.e. AllSimplePaths):
https://github.com/neo4j/neo4j/blob/fbf49112621991730617b0d7ffcd6afa632ea9b9/community/kernel/src/main/java/org/neo4j/kernel/impl/traversal/BidirectionalTraverserIterator.java#L168

The proposal is to pass Uniqueness(BidirectionalUniquenessFilter) to StandardBranchCollisionDetector so it could filter out paths before adding them to its map which leads to great memory/GC saving.

**Comment by spacecowboy** [comment]
Fixed by #4865
