### ISSUE TITLE
Consider to support extraction of REGEXP groups from statements

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#48]
@peterneubauer: 'It would be very practical to use regexp in conjunction with WITH to extract groups from regexp on properties for further processing, just like any other function. Something like

```
START n = node(1)
WITH EXTRACT(n.name, '(N.*) (Matrix)', 1) as neo
CREATE n-[:NAME_CONTAINS]-{name:neo}
```

where `EXTRACT(n.name, '(N.*) (Matrix)', 1) as neo` specifies the string expression, the REGEXP and the group(s) from the regexp to extract. '

**Comment by Mats-SX** [comment]
Support for regular expressions is not a currently planned feature.
