### ISSUE TITLE
Sum function returning a same result for all properties when applying where condition on it

### ISSUE THREAD

**Issue by AshishBarde** [neo4j/neo4j#4811]
MATCH (SMARTORDER_SMARTORDER:SMARTORDER_SMARTORDER)-[SMARTORDER_SMARTORDERHASCOMPANY:HAS]->(COMPANY:COMPANY)-[COMPANYHAS_SITESITE:HAS_SITE]->(SITE:SITE)-[SITEHASITEM:HAS]->(ITEM:ITEM)-[ITEMHAS_POPURCHASEORDER:HAS_PO]->(PURCHASEORDER:PURCHASEORDER)-[PURCHASEORDERHAS_TOTRANSFERORDER:HAS_TO]->(TRANSFERORDER:TRANSFERORDER)-[TRANSFERORDERHAS_GRGOODSRECIEPT:HAS_GR]->(GOODSRECIEPT:GOODSRECIEPT)  WITH DISTINCT GOODSRECIEPT AS GOODSRECIEPT, ITEM AS ITEM RETURN DISTINCT ITEM.ItemName AS DIMENSION, sum(toFloat(GOODSRECIEPT.ShortFall)) AS MEASURES1 ORDER BY DIMENSION

these is my first query it's giving exact result I want like
DIMENSION    MEASURES1
cap                   500.234
sap                   700.454  
deal                  900.3478         and so on................
I am applying filter on above query  like  GOODSRECIEPT.ShortFall > 500  then it's giving me output like 
DIMENSION    MEASURES1
sap                   1000  
deal                  1000

so please help me out for these issue

**Comment by jexp** [comment]
PLEASE NOTE: This is a bug/issue tracker not a support forum !

To test it, just let it return the values and look at them.
REMOVE the distinct from your `RETURN` clause, as you are already doing an aggregation.

The WHERE condition It will not filter single nodes but whole paths !

Please next time be more considerate when raising an issue like this, your query is not formatted and impossible to read. You will not get help if you are inconsiderate to people helping.
