### ISSUE TITLE
Unable to update to 2.3.0-M02 in maven

### ISSUE THREAD

**Issue by FylmTM** [neo4j/neo4j#4832]
Hi,

I am unable to update my dependencies to 2.3.0-M02. 
I receive error:

```
[ERROR] Failed to collect dependencies at org.neo4j.app:neo4j-server:jar:2.3.0-M02 -> org.neo4j:neo4j-ndp-transport-socket:jar:2.3.0-M02: 
Failed to read artifact descriptor for org.neo4j:neo4j-ndp-transport-socket:jar:2.3.0-M02: 
Failure to find org.neo4j:neo4j-data-protocol-parent:pom:2.3.0-M02 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
```

There are no `org.neo4j:neo4j-data-protocol-parent:pom:2.3.0-M02` in maven central.

How this issue can be fixed?

Thanks.

**Comment by tkroman** [comment]
+1

**Comment by sfat** [comment]
@FylmTM have you tried `mvn -U <your goals>`.I am pretty sure that will help you guys. That error usually occurs because of the maven cache. -U forces refreshing of the local cache. http://mvnrepository.com/artifact/org.neo4j.app/neo4j-server/2.3.0-M02 shows that it is on maven central.

**Comment by FylmTM** [comment]
@sfat Looks like that this doesn't work for me.
In fact - I can't find `neo4j-data-protocol-parent` dependency in maven central.

`neo4j-ndp-transport-socket` has `neo4j-data-protocal-parent` as parent. Pom: [pom.xml](http://central.maven.org/maven2/org/neo4j/neo4j-ndp-transport-socket/2.3.0-M02/neo4j-ndp-transport-socket-2.3.0-M02.pom)

**Comment by jakewins** [comment]
Good find, looks like our deployment scripts skipped this new module. We'll have to see if we can retroactively deploy that module, and we'll make sure to fix it for the next milestone.

In the meantime, one workaround would be to manually deploy this parent pom, something like:

```
git clone git@github.com:neo4j/neo4j.git
cd neo4j/community/ndp
git checkout 2.3.0-M02
mvn clean install -DskipTests
```

**Comment by FylmTM** [comment]
@jakewins Thanks for info!

One more thing, if this is suitable to ask there. I am curious about this NDP thing. This service will be available in 2.3.0 release (at least in alpha stage)? 
In fact - NDP is something that will be great for my current project.

**Comment by jakewins** [comment]
@FylmTM officially, it is not available in public releases yet. However, you're right you can technically enable it in 2.3.x - but that does void your warranty, it's not production ready yet :) That said, given that you're running the Neo4j Server, the magic config option is:

```
# in neo4j-server.properties
xx.ndp.enabled=true
```

Which lets you connect using the (also experimental and actively-having-breaking-changes-made-to-it) java driver: https://github.com/neo4j/neo4j-java-driver

If you try it, do let us know what you think!

**Comment by FylmTM** [comment]
Great! We definitely going to try this. We currently have unmanaged extension with our own custom binary protocol (using Kryo). But your solution looks better and more peformant. 

If I have any questions and feedback on NDP, where I should write them? SO, Github, something else?

**Comment by jakewins** [comment]
For issues with the driver or protocol themselves - github issues work well. For general feedback, you can email me at jake <at> neotechnology.com, and I'll forward it to the rest of the team :)

**Comment by FylmTM** [comment]
Update.

Build from `community/ndp` leads to:

```
[WARNING] The POM for org.neo4j:neo4j:jar:2.3-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.neo4j:neo4j-streams:jar:2.3-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.neo4j:neo4j-kernel:jar:tests:2.3-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.neo4j:neo4j-io:jar:tests:2.3-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.neo4j:neo4j-streams:jar:tests:2.3-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.neo4j:neo4j-logging:jar:tests:2.3-SNAPSHOT is missing, no dependency information available
```

Trying `mvn clean install -DminimalBuild -DskipBrowser` from root directory leads to:

```
[ERROR] Failed to execute goal on project neo4j-logging: Could not resolve dependencies for project org.neo4j:neo4j-logging:jar:2.3-SNAPSHOT: Failure to find org.neo4j:neo4j-io:jar:tests:
2.3-SNAPSHOT in http://cifwk-oss.lmera.ericsson.se:8081/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of nex
us has elapsed or updates are forced
```

Trying `mvn clean install -DskipBrowser -DskipTests` from root directory leads to:

```
[ERROR] Failed to execute goal on project neo4j-server: Could not resolve dependencies for project org.neo4j.app:neo4j-server:jar:2.3-SNAPSHOT: Could not find artifact org.neo4j.app:neo4j-browser:jar:2.3-SNAPSHOT in nexus (http://cifwk-oss.lmera.ericsson.se:8081/nexus/content/groups/public) -> [Help 1]
```

---

But, anyway, `mvn clean install -DskipBrowser -DskipTests` is enough to build NDP. Even it fails, because at this point all mandatory artifacts are build.

**Comment by jakewins** [comment]
@FylmTM did you do `git checkout 2.3.0-M02`? It looks like it's trying to build the snapshot versions, rather than the milestone release.

**Comment by FylmTM** [comment]
@jakewins  Yeap. I do. But there is 2.3-SNAPSHOT version. 
Maybe tag is placed on wrong commit?

**Comment by FylmTM** [comment]
More details:

```
# fylmtm at ubuntu in ~/workspace/github/neo4j on git:master x [14:51:24]
$ git checkout 2.3.0-M02
Note: checking out '2.3.0-M02'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 7423eb1... Scheduler should throw RejectedExecutionException if not started On rotation, if there is a REE then do the rotation in the same thread instead.

# fylmtm at ubuntu in ~/workspace/github/neo4j on git:7423eb1 o [14:51:26]
$
```

So. It switches to 7423eb1 commit. Here - https://github.com/neo4j/neo4j/blob/7423eb108753b1555fb1686284321a2dbef5bd8e/pom.xml
