### ISSUE TITLE
Better support for lucene numerics notation

### ISSUE THREAD

**Issue by NicholasAStuart** [neo4j/neo4j#485]
When I try to use use Lucene supported notation for numerical values in cypher, such as `[0 TO 1]` or `[0 TO *]`, these do not match numically stored values that I have created with neo4j in the index. Some of this works, such as doing `[0 TO 2]` for a numeric of `1`, but if I do `[1 TO 1]` or `[0 TO 1]` which works for lucene I do not get any results in Cypher.

**Comment by jakewins** [comment]
The suggested approach to this is now to use the range query capabilities of the schema indexes, rather than manual lucene indexes. See here: http://neo4j.com/docs/stable/query-where.html#_using_ranges
