### ISSUE TITLE
Question regarding org.neo4j.helpers.collection.IteratorUtil#single

### ISSUE THREAD

**Issue by ducky427** [neo4j/neo4j#4860]
Looking at the code of the method [`org.neo4j.helpers.collection.IteratorUtil#single`](https://github.com/neo4j/neo4j/blob/28484b2ca5a6cff28ff4003dfab6c8e2e39c4594/community/kernel/src/main/java/org/neo4j/helpers/collection/IteratorUtil.java#L337), I notice that the function will close a `Resource` if it is passed (thinking of `ResourceIterator`).

This is not mentioned in the documentation.  So could this be added to the doc string so that people can rely on that fact?

Thanks!

**Comment by jakewins** [comment]
`org.neo4j.helpers` is not a public package - we don't guarantee any contracts (implicit or explicit) on those packages to remain stable. Public Java APIs are those that are publicly documented here: http://neo4j.com/docs/stable/javadocs/

If you want a utility library for working with collections, I'd suggest to have a look at Google Guava or Apache Commons or some similar dedicated utility library. Closing this as a wontfix.

**Comment by ducky427** [comment]
Actually `org.neo4j.helpers` is mentioned in the public java API under the `Helpers` section and so is [org.neo4j.helpers.collection.IteratorUtil#single](http://neo4j.com/docs/stable/javadocs/org/neo4j/helpers/collection/IteratorUtil.html#single%28java.lang.Iterable%29)

Thats how I became aware of the method.

**Comment by jakewins** [comment]
Doh, you are absolutely right.

**Comment by spacecowboy** [comment]
The docs have been updated to reflect this fact.
