### ISSUE TITLE
how to access to database other than the default one

### ISSUE THREAD

**Issue by BondWong** [neo4j/neo4j#4871]
Hi guys, I am new to neo4j and currently developing an iOS application using the neo4j as backend database.
 In my code, I create a database with this path "target/pamelaGDB", and add some nodes and relationships into it. I want to access the database I created by using other ways other than neo4j java api.
One way I can do that is using the neo4j shell and provide it with a path. Are there other ways to achieve this?

**Comment by jexp** [comment]
You can edit `conf/neo4j-server.properties` and set the database location to your path.
Just make sure you don't have custom code and the server running on the same directory at the same time.
