### ISSUE TITLE
Invoking Bootstrapper#main() is no longer supported. If you see this error, please contact Neo4j support.

### ISSUE THREAD

**Issue by Calpicow** [neo4j/neo4j#4876]
Installed Neo4j 2.3.0-M02_1 from the Yum repo, and getting the above error in the logs when I try to start the service.

**Comment by raymondjplante** [comment]
Seeing this as well.  

```
 Exception in thread "main" java.lang.UnsupportedOperationException: Invoking Bootstrapper#main() is no longer supported. 
  If you see this error, please contact Neo4j support.
    at org.neo4j.server.Bootstrapper.main(Bootstrapper.java:66)
```

Running java 1.7.0_7  an Amazon AWS Linux instance with yum manually as the cloudformation script on the neo4j site doesn't work.  Does this happen with the ubuntu/debian?  Guess I'll need to blow away my instance, create an Ubuntu version to test.

**Comment by lutovich** [comment]
@Calpicow, @raymondjplante would it be OK for you guys to call concrete implementation of `Bootstrapper` like `CommunityBootstrapper#main()` or `EnterpriseBootstrapper#main()` ?

**Comment by lutovich** [comment]
Sorry, missed the fact that you get this error while trying to start the service.
We'll work on fixing Yum packages.

**Comment by jakewins** [comment]
Resolved by https://github.com/neo4j/neo4j/commit/4872ffc151e3ab0fe884821f31f51024d1784709

**Comment by jakewins** [comment]
Noting that the fix is not released yet, will go out with the next 2.3.0 series release.

**Comment by TrueDub** [comment]
When is the planned release date for this? Our Neo4J work is dead in the water without this fix.

**Comment by jakewins** [comment]
@TrueDub this work is all in the 2.3 series, of which there is no stable release yet - if you are working on production code, you should be using a stable release, currently the 2.2 series. 

I can't give a release date for the next 2.3 milestone, the release is driven by the backlog, so it will be out once the pending WIP is completed. I can say that there's little work left, so ideally the next 2.3 milestone will be in the next few weeks.

**Comment by kenahoo** [comment]
Is there a workaround for this in the meantime?  Some other way to start the server?  I'm not running this in production, but my _development_ work around neo4j is dead until I can figure this out.

**Comment by kenahoo** [comment]
By the way - the other problem that this issue highlighted is that the `/etc/init.d/neo4j` script can't actually tell that startup failed.  It reports that neo4j started up just fine, so I had to sleuth around to find `/var/log/neo4j/console.log` (not `$NEO4J_DIR/messages.log` like I'd have thought) with this error message about "Bootstrapper" in it.  Seems like that's a bug too, in the startup script?

**Comment by Calpicow** [comment]
Here's a fixed `neo4jd` script in the meantime: https://gist.github.com/Calpicow/eda8837fd90c5252cff8. This is for CentOS 6.x, and maybe others.

**Comment by kenahoo** [comment]
Thanks @Calpicow - I just noticed that there are some curly quotes in that script, probably those should be nuked.  My guess is they're getting passed to `getopts` with the rest of the intended string.

**Comment by Alan-R** [comment]
@lutovich  Why does the repo default to an unsupported, pre-release version? This should not happen when installing according to the directions at http://yum.neo4j.org/

**Comment by lutovich** [comment]
@Alan-R good question. I do not know actually. But can definitely agree with you. Will try to figure this out. It would definitely make sense to default to latest released 2.2 version.

**Comment by Alan-R** [comment]
I've opened a new issue about this alone, since this one is closed.

**Comment by Alan-R** [comment]
I've opened a new issue for this here: https://github.com/neo4j/neo4j/issues/5388
