### ISSUE TITLE
Bug in neo4j browser, possibly because of many edges

### ISSUE THREAD

**Issue by halflings** [neo4j/neo4j#4888]
I consistently get this glitch with my graph in neo4j browser, but only when showing a specific relationship where the two same nodes are often linked by many relationships.
(labels blurred by me)

![neo4j-bug-blurred](https://cloud.githubusercontent.com/assets/1626936/8326613/8a490410-1a62-11e5-9d6d-a01c3414a4b2.png)
(neo4j browser running on Firefox)

This "ray casting" moves in an unpredictable way when moving the nodes.

**Comment by halflings** [comment]
Just tried changing the color of the grey nodes (to red), and the "shadow" remains in gray, so it might be unrelated to the actual color of the nodes.

Also: the "shadow" keeps moving in all directions until all nodes are stationary (then it's still there, just not moving)

**Comment by halflings** [comment]
Just tried this in Chrome: It doesn't have the same problem (huge areas covered in gray) but there are some flickering edges.

**Comment by oskarhane** [comment]
Thanks @halflings, yes, we're aware of these edge cases (pun intended) than one can run into having lot's of relationships between two nodes.  
We're on it.

**Comment by oskarhane** [comment]
This is now fixed in 3.0 RC releases.
