### ISSUE TITLE
Circular relationship "Jake likes Jake"

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#49]
@gokcemutlu: 'Hi,

I have a simple model:

```
START root=node(0) CREATE UNIQUE root-[:PEOPLE]->(jake {Name:'Jake'}), root-[:PEOPLE]->(jill {Name:'Jill'}), jake-[:LIKE]->jill, jill-[:LIKE]->jake, jake-[:LIKE]->jake;
```

In this model 
* Jake likes Jill, 
* Jill likes Jake
* Jake likes Jake

I want to find out Jake likes who.

```
START r = node(0) MATCH r-[:PEOPLE]->jake, path=(jake-[:LIKE]->person-[:LIKE]->jake) where jake.Name = 'Jake' RETURN person;
```

This query returns only Jill and this is wrong.

Please let me know.

Regards,
Gokce'

**Comment by jakewins** [comment]
Since this has been idle for this long, assuming the solution proposed above resolved this, please reopen if not.
