### ISSUE TITLE
Index scan seems doesn't work without hinting in neo4j 2.2

### ISSUE THREAD

**Issue by s101d1** [neo4j/neo4j#4902]
For example, I have created an index on `Actor` label for `id` property in Neo4j v2.2.x:

`CREATE INDEX ON :Actor(id)`

Then I also inserted some Actor nodes.

But when I did an explain of a match query:

`EXPLAIN MATCH (a:Actor {id: "1"}) RETURN a;`

The result I got is:

```
Compiler CYPHER 2.2

Planner COST

Filter
  |
  +NodeByLabelScan

+-----------------+---------------+-------------+-------------------------+
|        Operator | EstimatedRows | Identifiers |                   Other |
+-----------------+---------------+-------------+-------------------------+
|          Filter |             1 |           a | a.id == {  AUTOSTRING0} |
| NodeByLabelScan |             3 |           a |                  :Actor |
+-----------------+---------------+-------------+-------------------------+
```

So it didn't scan by index.

But if used hint syntax (USING):

`EXPLAIN MATCH (a:Actor {id: "1"}) USING INDEX a:Actor(id) RETURN a;`

It scanned by index:

```
Compiler CYPHER 2.2

Planner COST

NodeIndexSeek

+---------------+---------------+-------------+------------+
|      Operator | EstimatedRows | Identifiers |      Other |
+---------------+---------------+-------------+------------+
| NodeIndexSeek |             1 |           a | :Actor(id) |
+---------------+---------------+-------------+------------+
```

So anyone can explain what happened here? Why index scan is not enabled automatically?

**Comment by jexp** [comment]
How many nodes do you have in your graph? As the planner uses statistics, it might be cheaper to just scan the label and compare nodes than going to a separate index system.

Try to create a few more actor nodes and see if that changes the plan.

**Comment by s101d1** [comment]
I have tried with 2000 nodes, same result, no change.

I'm using Neo4j v2.2.2 community on windows.

**Comment by jexp** [comment]
What does `:schema` say? Or `schema` in the shell?

Add more I think there is a treshold somewhere.

**Comment by s101d1** [comment]
Indexes
  ON :Actor(id)          ONLINE

**Comment by s101d1** [comment]
I tried with 10000 nodes, same result.

But I found something new, I added `ORDER BY a.id` to the query, I got different explain result:

```
+---------------+---------------+--------------------------+-----------------------+
|      Operator | EstimatedRows |              Identifiers |                 Other |
+---------------+---------------+--------------------------+-----------------------+
| Projection(0) |             1 | anon[39], anon[52], a, a |              anon[39] |
|          Sort |             1 |    anon[39], anon[52], a |              anon[52] |
| Projection(1) |             1 |    anon[39], anon[52], a | anon[39]; anon[39].id |
| Projection(2) |             1 |              anon[39], a |                     a |
| NodeIndexSeek |             1 |                        a |            :Actor(id) |
+---------------+---------------+--------------------------+-----------------------+
```

Then I also did something like this:

`EXPLAIN MATCH (a:Actor {id: "1"}) WITH a RETURN a`

The explain result showed that it used `NodeIndexSeek`.

Finally, I changed my query to use WHERE:

`EXPLAIN MATCH (a:Actor) WHERE a.id = "1" RETURN a;`

And the result said it uses `NodeIndexSeek`.

So it seems the simple "`MATCH (a:Label {prop: "value"}) RETURN a`" query can't utilize index scan?

**Comment by jexp** [comment]
Which version is this? You said in the beginning 2.2.x ?

**Comment by s101d1** [comment]
2.2.2

**Comment by s101d1** [comment]
I just installed v2.2.3, and the index scan works fine for "`MATCH (a:Label {prop: "value"}) RETURN a`" pattern, so it seems it's specific v2.2.2 problem.

**Comment by jexp** [comment]
Ok, thanks !
