### ISSUE TITLE
Prefer NodeByIdSeek scan over NodeIndexSeek where query can use either

### ISSUE THREAD

**Issue by ducky427** [neo4j/neo4j#4911]
We are using Neo4j 2.2.3.

I'll try to explain our cypher query issue using the movies dataset.

1) Create the movies  using :play movies.
2) Add the following index: `CREATE INDEX ON :Movie(title);`

Our queries are of the type:

`MATCH (n)-[:ACTED_IN]->(m:Movie) WHERE ID(n) = 71 AND m.title = 'Cloud Atlas'
RETURN ID(m), m, LABELS(m) LIMIT 1`

The query plan for this looks like:

![image1](https://cloud.githubusercontent.com/assets/83426/8406046/c9b81e46-1e50-11e5-9312-a20b7e88f641.png)

What we'd like is that instead of doing the scan on the index first, the query planner first does the look by node Id.

We tried rewriting the query as:

`MATCH (n) WHERE ID(n) = 71
WITH n
MATCH (n)-[:ACTED_IN]->(m:Movie) WHERE m.title = 'Cloud Atlas' RETURN ID(m), m, LABELS(m) LIMIT 1`

but the query planner optimised the query the same way as above.

We switched to using the RULE based query planner and it was 10x faster than the default COST based planner. 

![image2](https://cloud.githubusercontent.com/assets/83426/8406173/b665c25c-1e51-11e5-9249-8d5f0b4c2709.png)

The time took for a pretty complex query of this type was 22 second in the COST based planner and 1.8 seconds in the RULE based planner.

From the [documentation](http://neo4j.com/docs/stable/how-are-queries-executed.html), it seems selecting the planner being used isn't going to be possible in the future.

I think there are cases where the COST based planner should prefer to use NodeByIdSeek instead of NodeIndexSeek. Currently I am guessing that the planner prefer the latter to the former.

**Comment by Mats-SX** [comment]
Hello @ducky427 and thanks for your question.

I followed your steps verbatim and executed the queries you posted. They are both very fast and the solution uses the `IndexSeek` plan, which I find is fine. Could you please send me an example of a the kind of complex queries that you mention takes 22 seconds with the above plan?

**Comment by systay** [comment]
Please re-open if this is still an issue!
