### ISSUE TITLE
Jersey 2x for Json

### ISSUE THREAD

**Issue by monowai** [neo4j/neo4j#4920]
Given that JSON is now prolific, and is indeed the format supported by Neo4j, I was surprised to find it was not a native option when writing unmanaged extensions. Instead, we are welcomed with a 415 when serializing a pojo to an endpoint annotated with  @Consumes(MediaType.APPLICATION_JSON). Why am I writing an UMX? - because I'm having to move a ton of code to support the SDN 4 library upgrade and all the SDN3 features it no longer supports so that I can get on to neo2.2 

We really shouldn't have to be thinking [this hard](https://jersey.java.net/documentation/1.19/json.html#json.pojo.approach.section) about supporting JSON in the Neo4j environment - where is the web.xml file anyway? The idea of annotating ALL my pojos with @XmlRootElement is a pollutant, and I'd rather avoid yet another library just to support serialization in to n4j and while this approach might be useful for Neo's internal purposes, but ain't so great from an integration perspective.

**Comment by jexp** [comment]
Hi Mike,

You can also use SDN 3.3.1 which is compatible with Neo4j 2.2.2 :)

But in general, is only the additional dependency needed out of the box?

Did you note to the SDN4 group which relevant features are missing?

Edit: perhaps this helps? http://stackoverflow.com/questions/30929203/consuming-json-in-neo4j-server-extension

**Comment by technige** [comment]
Closing as it's unclear what needs to be done (if anything). Please reopen if necessary.
