### ISSUE TITLE
neo4j-community_windows_2_2_3.exe installation on Windows 8.1 prof 64bit gives error

### ISSUE THREAD

**Issue by ajit555** [neo4j/neo4j#4923]
It says the installation file is corrupted. If it is a download please try again. 

I downloaded couple of times,  but the same issue. I already have installed neo4j-community_windows-x64_2_1_4.exe and it works perfectly.

**Comment by benbc** [comment]
Hello @ajit555. I can't reproduce the problem that you're seeing. Please could you try again and reopen this issue if it's still happening?

**Comment by ajit555** [comment]
Downloaded it again and started the install with admin mode. It worked.
