### ISSUE TITLE
Neo4jInstaller.bat still checks for Java 7

### ISSUE THREAD

**Issue by dnauck** [neo4j/neo4j#4926]
Neo4jInstaller.bat [1] still check for java 7 and refuse to start with java 8 (that should be now fully supported)

[1] https://github.com/neo4j/neo4j/blob/2.3/packaging/standalone/src/main/distribution/shell-scripts/bin/Neo4jInstaller.bat#L147

**Comment by cleishm** [comment]
Thanks @dnauck,

I've triaged that to our team for investigation.

Cheers,
Chris

**Comment by jotomo** [comment]
(this:Issue)-[:HAS_FIX]->(https://github.com/neo4j/neo4j/commit/1cd3ff962ddbc71fd698b0d85b14b9ca079b0f57)

**Comment by spacecowboy** [comment]
fixed in https://github.com/neo4j/neo4j/commit/1cd3ff962ddbc71fd698b0d85b14b9ca079b0f57
