### ISSUE TITLE
Force Neo4J web console to retry connecting to server after restart

### ISSUE THREAD

**Issue by mbyrne00** [neo4j/neo4j#4929]
When then Neo4J server goes down the web browser/console displays a red banner with the message: **Disconnected from Neo4j. Please check if the cord is unplugged.**

The banner will not disappear until it checks again. It would be nice to have a link in that banner "try again" or similar. Have noticed this when restarting the server locally to restore a db backup.

**Comment by marcinwasilewski** [comment]
How do you reconnect without refreshing the window? Is it even possible? My banner seems to just stay red forever.

**Comment by mbyrne00** [comment]
It seemed to go away after a while for me on Chrome but took a long time - normally just refresh which isn't great.

**Comment by jotomo** [comment]
@mbyrne00 by default the UI checks to see if the server is alive every 60 seconds. You can issue the command `:config heartbeat:1` to set it to 1s.

**Comment by mbyrne00** [comment]
Thanks for the tip @jotomo! Great workaround.

Would still be nice to have a "retry now" link much like the slack app has on mac.

**Comment by jotomo** [comment]
Agreed, such a link/button would be pretty handy.

**Comment by oskarhane** [comment]
As part of https://github.com/neo4j/neo4j/pull/5148 the browser now tries to reconnect every two seconds while disconnected. Once connected the checks goes back to its configured interval.
