### ISSUE TITLE
Cypher: Integer division should maybe result in Float, if appropriate?

### ISSUE THREAD

**Issue by freeeve** [neo4j/neo4j#493]
What do you guys think? I was kind of hoping this would give me 0.5:

http://console.neo4j.org/?id=aoipbr

Otherwise, maybe we need some way of casting to a float after all?

1/2.0 works as expected, at least.

**Comment by ccorcos** [comment]
wait... no workaround this? So I cant compute a ratio of two integers?

**Comment by cleishm** [comment]
Cypher now supports `toFloat(...)`, which will allow you to do what you're asking for, e.g. `toFloat(3)/4`

**Comment by ccorcos** [comment]
ok. sweet
