### ISSUE TITLE
No logs/warnings are produced when Neo4j doesn't have the right permissions to graph.db

### ISSUE THREAD

**Issue by marcinwasilewski** [neo4j/neo4j#4934]
I created my graph.db using neo4j-import and copied it to data folder. I forgot to change permissions and was completely dumbfounded that neo4j service wouldn't start - neo4j produces no logs in this case and issues no warnings. Perhaps it tries to write to messages.log inside graph.db - which it can't access - but I think it should output something to /var/logs/neo4j/

**Comment by jexp** [comment]
thanks a lot Marcin, I raised that with the team.
