### ISSUE TITLE
2.2 ORDER BY "not defined" regression

### ISSUE THREAD

**Issue by aseemk** [neo4j/neo4j#4937]
Using http://console.neo4j.org/ as an example...

This query works:

``` cypher
MATCH (crew:Crew {name: 'Neo'})
WITH crew, 0 AS relevance
RETURN crew
ORDER BY relevance
```

But this query (just added another clause to the `ORDER BY`) doesn't:

``` cypher
MATCH (crew:Crew {name: 'Neo'})
WITH crew, 0 AS relevance
RETURN crew
ORDER BY relevance, crew.name
```

This is the `Neo.ClientError.Statement.InvalidSyntax` error that's thrown:

```
Error: relevance not defined (line 1, column 85 (offset: 84))
"MATCH (crew:Crew { name: 'Neo' })  WITH crew, 0 AS relevance  RETURN crew  ORDER BY relevance, crew.name"
                                                                                     ^
```

The query used to work in 2.1.

**Comment by aseemk** [comment]
As a workaround, you can simply add `relevance` to the `RETURN`.

**Comment by jexp** [comment]
Hey Aseem

this is part of the more rigid "only order by things that are visible / accessible".
So you can only order by things in your return clause or by things accessible from there.

Or you just use your WITH to order

```
MATCH (crew:Crew {name: 'Neo'})
WITH crew, 0 AS relevance
ORDER BY relevance, crew.name
RETURN crew
```

**Comment by aseemk** [comment]
Hey @jexp, thanks for the quick reply.

> this is part of the more rigid "only order by things that are visible / accessible".
> So you can only order by things in your return clause or by things accessible from there.

But (a) that's clearly not the case in the first example I provided, and more importantly, (b) if this is a breaking change between 2.1 and 2.2, shouldn't it have been properly communicated?

http://neo4j.com/release-notes/

> Or you just use your WITH to order

Yep, this was a simplified example.

**Comment by jexp** [comment]
Hey @aseemk 

I think it was always intended to be like that, so it was more or less a bugfix, but @systay and @boggle would know more.

And you're right the first example shouldn't work either :)

**Comment by Mats-SX** [comment]
I think this looks like there was a bug introduced in 2.2, related to the special scope of `ORDER BY`. The non-working query should work. Another workaround is by putting it like this:

```
MATCH (crew:Crew {name: 'Neo'})
WITH crew, 0 AS relevance, crew.name AS name
RETURN crew
ORDER BY relevance, name
```
