### ISSUE TITLE
Return meaningful information to REST endpoint for MERGE or SET cypher statements

### ISSUE THREAD

**Issue by joshuacano** [neo4j/neo4j#4965]
If you post to the REST or Legacy Cypher endpoint a simple merge statement (I.e. { "statements" : [{ "statement" : "MATCH (w:Work) with w limit 10 set w.test = 0 " }] } The endpoint will provide no response as to what it has done. If you post this same simple statement to the Browser, you will get a meaningful response. (In this case. Set 10 properties, statement executed in 300 ms) Can we have some response back to the caller indicating how many properties/nodes/relationships were affected?

Thank you.

**Comment by jexp** [comment]
this is additional meta-information which is usually not required, you can get it with `{..., "includeStats":true}`

**Comment by joshuacano** [comment]
Thanks Michael.
