### ISSUE TITLE
Empty CSV file causes neo4j-import to infinite loop and fill the disk

### ISSUE THREAD

**Issue by jimbobhickville** [neo4j/neo4j#4977]
I am working on a program to convert a gedcom file into a neo4j database.  I generate a series of CSV files, one for each node type and relationship type, then pass all those along to neo4j-import to generate the database.  Due to some poor bounds-checking on my end, one of the generated CSV files was empty, but rather than either erroring out or ignoring it, neo4j-import went into an infinite loop and repeatedly imported the remaining node files until my disk was full.  It never made it to the relationships.  What should have been a 170MB database ended up filling up nearly 300GB of disk before it crashed.  I fixed the bug in my csv exporter, but neo4j-import should probably behave in a more sane fashion should this happen.

**Comment by jexp** [comment]
Thanks a lot for reporting this @jimbobhickville 
Was the file completely empty or did it have  a header row?
And which version did you use? 2.2 or 2.3-milestone 2?

**Comment by jimbobhickville** [comment]
I believe it was completely empty but it may have had a single newline
character in it.  I'll try to find a minimal repeatable case and add it to
the issue.

**Comment by jimbobhickville** [comment]
Yeah, completely empty.  Doesn't matter how big the other file is.  Here's a snippet.  I killed the process after it went for a minute or so:

```
$ cat A.csv
A,B,C,D
a,b,c,d
e,f,g,h
$ cat B.csv
$ neo4j-import --into /tmp/graph.db --nodes A.csv --nodes B.csv
Importing the contents of these files into /tmp/graph.db:
Nodes:
  A.csv

  B.csv

Available memory:
  Free machine memory: 3.44 GB
  Max heap memory : 3.56 GB

Nodes
[*>:8.00 MB/s------------|NODE:0.00 B-----------|LABEL SCAN-------------|v:34.84 MB/s----------]
[*>:2.67 MB/s----------------------------------------------------------------------------------] 
2[*>:1.60 MB/s----------------------------------------------------------------------------------] 
4[*>:1.14 MB/s----------------------------------------------------------------------------------] 
7[*>:910.22 kB/s--------------------------------------------------------------------------------] 
9[*>:744.73 kB/s--------------------------------------------------------------------------------]
125M^C

$ du -h /tmp/graph.db
  0B    /tmp/graph.db/schema/label/lucene
  0B    /tmp/graph.db/schema/label
  0B    /tmp/graph.db/schema
1.8G    /tmp/graph.db
```

**Comment by jimbobhickville** [comment]
Oh, it's community edition 2.2.3

**Comment by chrisvest** [comment]
Looks like a fix was merged for this.
