### ISSUE TITLE
Unable to index more than 64 properties in a single index

### ISSUE THREAD

**Issue by cmorgner** [neo4j/neo4j#4993]
In Structr we support an arbitrary number of (indexable) properties which can be both local node properties or composite index values for which there is no actual value in the database. When storing such a node, it is re-indexed with all its properties in the same transaction.

The recent change in Neo4j 2.2.3 effectively prevents nodes with more than 63 properties from being indexed (automatically) at all, even in the same index.

I suspect that the index access counter simply counts the number of index accesses, regardless of the index and property name that is updated.

The following failing test demonstrates the behaviour.

```
public class IndexingFailTest {

    public static void main(final String[] args) {

        final GraphDatabaseService graphDb = new GraphDatabaseFactory().newEmbeddedDatabase("/tmp/neo4j-test-" + System.currentTimeMillis());
        try (final Transaction tx = graphDb.beginTx()) {

            final Index<Node> index = graphDb.index().forNodes("fulltextIndex", LuceneIndexImplementation.FULLTEXT_CONFIG);
            final Node node         = graphDb.createNode();

            for (int i=0; i<65; i++) {
                index.add(node, "name" + i, i);
            }

            tx.success();

        } catch (Throwable t) {
            t.printStackTrace();
        }
    }
}
```

This is a real blocker for us, it prevents us from using Neo4j 2.2.3 in Structr at all.

Please advise.

**Comment by cmorgner** [comment]
The limit is also reached when indexing individual nodes with a single value, i.e. it's not possible to index more than 63 nodes in a single transaction with this limitation any more, which is even more critical.

**Comment by cmorgner** [comment]
See the following slightly modified test:

```
public class IndexingFailTest {

    public static void main(final String[] args) {

        final GraphDatabaseService graphDb = new GraphDatabaseFactory().newEmbeddedDatabase("/tmp/neo4j-test-" + System.currentTimeMillis());
        try (final Transaction tx = graphDb.beginTx()) {

            final Index<Node> index = graphDb.index().forNodes("fulltextIndex", LuceneIndexImplementation.FULLTEXT_CONFIG);

            for (int i=0; i<65; i++) {

                final Node node = graphDb.createNode();
                index.add(node, "name" + i, i);
            }

            tx.success();

        } catch (Throwable t) {
            t.printStackTrace();
        }
    }
}
```

**Comment by tinwelint** [comment]
I can definitely see that this is a problem. The legacy indexes have been a little bit left behind in the 2.2 refactorings which put some restrictions on its functionality. Integrating legacy indexes a bit better into the kernel API will solve this problem. I hope this can be fixed soon, for 2.2.4 even.

On second thought: this change will require a store change so it makes much more sense to do this for 2.3 IMHO.

**Comment by cmorgner** [comment]
Is updating the same index more than 63 times in a transaction really a problem that needs a store change? Looking at the code that does the check, I think that the check is too simple because it just increases a counter for every time the method is called, without taking into account that it might be the same index or the same name.

**Comment by tinwelint** [comment]
It's about how many unique legacy index keys and index names that the command can hold. This change will require a log format change and also most likely a change to `index.db` i.e. a store change.

**Comment by cmorgner** [comment]
The second test shows that I cannot even index more than 63 nodes with the same name in the same index.

Edit: sorry, correction: you're right, the test changes the name as well.

**Comment by spacecowboy** [comment]
Has been fixed.
