### ISSUE TITLE
Question related to Neo4j Browser

### ISSUE THREAD

**Issue by JosemyDuarte** [neo4j/neo4j#5000]
I am trying to integrate the Neo4j Browser with MongoDB for a College Project... But I really dont know how to make it work with my JS... Which framework was used to make this? That may help me to understand how all these work together..

Thanks!

Really nice work..

**Comment by jexp** [comment]
Sorry this is an issue tracker, not a forum. You might be best off asking on StackOverflow. The Neo4j browser was written with Angular.js in coffeescript, the sources can be found in community/browser.
