### ISSUE TITLE
Cypher offset with parameter

### ISSUE THREAD

**Issue by destronije** [neo4j/neo4j#5016]
Hi, perhaps this isn't an issue and it is supposed to be that way, but here it goes.

I want to get one random blog post for example in single query, without knowing the blog count before executing, so the query would be:

```
MATCH (blog:Blog)-[has_post:HAS_POST]->(:Post) WHERE id(blog) = { blog_id }
WITH blog, toInt(RAND() * COUNT(has_post)) as random_offset
MATCH (blog)-[:HAS_POST]->(post:Post)
RETURN post SKIP random_offset LIMIT 1
```

The problem is that the SKIP clause does not accept variables passed with WITH. Is it supposed to work that way or?
I know that i can load all posts and then order them by RAND() function. The problem is that if there are many "posts" neo4j will have to load them all and order them first, before returning only the first.
I think the above way will only skip the random number, and loading them all is prevented.

Thanks in advance and sorry if this was already asked, but i could not find any similar issue.

**Comment by Mats-SX** [comment]
Hello @destronije and thank you for your feedback.

What version of neo4j are you using?

**Comment by destronije** [comment]
Hello Mats, i'm using 2.2.3-1

**Comment by Mats-SX** [comment]
So, the `random_offset` is a column, and the `SKIP` operator can only accept scalar values. You might think that rewriting the query as follows would help

```
MATCH (blog:Blog)-[has_post:HAS_POST]->(:Post) WHERE id(blog) = { blog_id }
WITH blog, has_post
MATCH (blog)-[:HAS_POST]->(post:Post)
RETURN post SKIP toInt(RAND() * COUNT(has_post)) LIMIT 1
```

But this query is impossible. The reason for this is that `SKIP` (as well as `LIMIT`) can only accept values that are independent of the query graph (ie, "constants"). Introducing an aggregating function (as in my quoted alternative) would actually group the results to the `post` key, meaning it would change the results before actually skipping rows.

So, unfortunately what you want to do is not possible. It looks like you will have to use more than one query to do this.

EDIT: However, I have added a card for us to support statements like `SKIP toInt(rand())` in some future version.

**Comment by Mats-SX** [comment]
@destronije See #5381 if you still would like to see `SKIP toInt(rand())`.

**Comment by destronije** [comment]
Thank you for the update, didn't expect you would remember this issue :)
Will try it asap.
