### ISSUE TITLE
Cypher: getting start/end node of relationship

### ISSUE THREAD

**Issue by Bouncner** [neo4j/neo4j#503]
Hi,

I'd like to have the ability to easily get the start or end note of a relationship in Cypher. I have certain key information about a relationships, which are many (in my case tens thousands) and which all have the same start node.
Example:
start r=rel:transactions(sender_address='KEY')
match n-[r]->()
return n limit 1

This query apparently first gets the list of all qualifying relationships and then outputs the first hit, which is quite slow.

A solution like this would be great:
start r=rel:transactions(sender_address='KEY')
return startNode(r) / return endNode(r)

**Comment by chrisvest** [comment]
Duplicate has been marked as fixed. Closing.
