### ISSUE TITLE
TransactionFailureException - can't delete or add node(s) even after server reboot.

### ISSUE THREAD

**Issue by levidamian** [neo4j/neo4j#5034]
neo4j-sh (?)$ match (n:Description) with n limit 1 DELETE n;  
+-------------------+
| No data returned. |
+-------------------+
Nodes deleted: 1
61 ms
TransactionFailureException: Transaction was marked as successful, but unable to commit transaction so rolled back.

More details here:
http://stackoverflow.com/questions/31614335/neo4j-transactions-rolled-back

**Comment by jexp** [comment]
Your node might still have relationships, so please try to check that, and if so, use.

```
match (n:Description) 
with n limit 1
match (n)-[r]-()
DELETE n,r;
```

**Comment by levidamian** [comment]
Thank you, I will use this approach for the next delete.

Levi.
