### ISSUE TITLE
Cypher ORDER BY after RETURN aliasing

### ISSUE THREAD

**Issue by andrewotoole** [neo4j/neo4j#5041]
The following query syntactically works in 2.1 but not in 2.2:

```
MATCH (n:Person) WITH n RETURN { fullName:n.name } AS result ORDER BY n.age;
```

The fix would be to have the query look like this:

```
MATCH (n:Person) WITH n RETURN { fullName:n.name, age:n.age } AS result ORDER BY result.age;
```

It seems as though the reference to the nodes was dropped immediately after the aliasing to "result." This breaks backwards compatibility with 2.1.

**Comment by jexp** [comment]
It was a fix, that `order by` only sees what's visible from the returned dataset, otherwise it wouldn't be consistent.

so what you could do alternatively is to move the `order by` to the `WITH` statement

```
MATCH (n:Person) WITH n ORDER BY n.age RETURN { fullName:n.name } AS result;
```
