### ISSUE TITLE
[FeatureRequest] Tag Cypher statement

### ISSUE THREAD

**Issue by ikwattro** [neo4j/neo4j#5065]
I can understand if it is too late, but we never know :)

So the use case : 

When sending multiple statements at once via the `db/data/transaction/commit` endpoint, in case of exception, there is no way to tell which statement causes the problem, which can be a nightmare to find out when you send 1000 almost similar statements.

```
Fathom\Exception\PersistenceException: Neo4j Exception with code "Neo.ClientError.Statement.InvalidSyntax" and message "Invalid input ' ': expected 'e/E' (line 1, column 6 (offset: 5))
"CREAT (_55ba41be99333:`Entity_Play_Entities_Book`:`Item`:`Book`:`Product`)"
      ^"
```

It would be nice to be able to tag cypher statements and retrieve this tag in case of exception and even in the `results` array of the http response.

**Comment by technige** [comment]
It's never too late @ikwattro! I'm just seeing this now but we can add it to the list for internal discussion.

**Comment by technige** [comment]
We will factor this into our work on tracking statement and transaction execution.
