### ISSUE TITLE
TransactionEventHandlers and exception propagation

### ISSUE THREAD

**Issue by pietermartin** [neo4j/neo4j#508]
If an exception is raised in a TransactionEventHandler it currently gets wrapped 3 times before it is propagated to client code.

In TransactionEventHandlers.beforeCompletion it gets wrapped in a RuntimeException. This in turn is wrapped in a RollbackException which is wrapped in a TransactionFailureException.

This results in client code having to dig to find the relevant exception.

Thanks

**Comment by burqen** [comment]
@pietermartin Thank you for reporting! This remove one layer of wrapping https://github.com/neo4j/neo4j/pull/10373
Right now, the other layers are necessary for exception to be propagated from internals and out.
