### ISSUE TITLE
Basic usage of RoR gems not returning or returned with TimeoutError: too many connection resets

### ISSUE THREAD

**Issue by levidamian** [neo4j/neo4j#5085]
Here is what i am using (rails console):

```
$ gem list neo
*** LOCAL GEMS ***
neo4j (5.0.9)
neo4j-core (5.0.6)

irb(main):001:0> l = Language.find_by(iso_639_2_code: 'eng')
 CYPHER 150ms MATCH (n:`Language`) WHERE (n.iso_639_2_code = {n_iso_639_2_code}) RETURN n LIMIT {limit_1} | {:n_iso_639_2_code=>"eng", :limit_1=>1}
=> Language uuid: nil, english_name_of_language: "English", french_name_of_language: "anglais", german_name_of_language: "Englisch", iso_639_1_code: "en", iso_639_2_code: "eng", spoken_in: "English, a West Germanic language is the first language for about 309–400 million people. See: Countries by Languages - English Speaking Countries."

irb(main):003:0> n = l.descriptions.count
 Language#descriptions 6695ms MATCH language137, language137-[rel1:`DESCRIBED_IN`]->(result_descriptions:`Description`) WHERE (ID(language137) = {ID_language137}) RETURN count(result_descriptions) AS result_descriptions | {:ID_language137=>137}
=> 2107041

Trying to get the first description in English:
irb(main):008:0>  d = l.descriptions.first

After a very long run the result is:
 Language#descriptions 1200265ms MATCH language137, language137-[rel1:`DESCRIBED_IN`]->(result_descriptions:`Description`) WHERE (ID(language137) = {ID_language137}) RETURN result_descriptions | {:ID_language137=>137}
Faraday::TimeoutError: too many connection resets (due to Net::ReadTimeout - Net::ReadTimeout) after 0 requests on 70276164611260, last used 1438711280.7209878 seconds ago
```

During the long processing no other connection is allowed to the database and if one is still open, any processing there takes for ever until the first session is terminated.
Most of the time a server reboot is required to resume normal usage of the database.

**Comment by jexp** [comment]
I think you should raise this on github.com/neo4jrb /cc @cheerfulstoic

I think Brian pushed a fix for that.

**Comment by levidamian** [comment]
Another failure time to time is:
 d = l.descriptions.first
 Language#descriptions 951802ms MATCH language137, language137-[rel1:`DESCRIBED_IN`]->(result_descriptions:`Description`) WHERE (ID(language137) = {ID_language137}) RETURN result_descriptions | {:ID_language137=>137}
Neo4j::Session::CypherError: Java heap space
    from /Users/levi/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/neo4j-core-5.0.6/lib/neo4j-server/cypher_response.rb:211:in `raise_cypher_error'

**Comment by cheerfulstoic** [comment]
Yes, sorry, when I said to create an issue in the `neo4j` repo I mean the repo for the `neo4j` gem which is under the `neo4jrb` account.  That's here:

https://github.com/neo4jrb/neo4j/issues/new

**Comment by levidamian** [comment]
OK, sorry, the issue https://github.com/neo4jrb/neo4j/issues/900 https://github.com/neo4jrb/neo4j/issues/900 is created now.

Please close the old one.

Thank you,
Levi.

**Comment by levidamian** [comment]
The issue https://github.com/neo4jrb/neo4j/issues/900 was created instead of this one.

**Comment by levidamian** [comment]
closed while a new one was open in the neo4jrb repo.
