### ISSUE TITLE
Bitwise Operators

### ISSUE THREAD

**Issue by gregaubert** [neo4j/neo4j#5092]
Hello,
I noticed there is no bitwise operators like in Java (&, |, ^, ~), it would really be great to have it! Does it seems hard to implement ?
Are there any plan to do it in near future ? If not I could do a PR if you point me in the right direction...

**Comment by jexp** [comment]
Could you explain your use-case? that would be helpful.

**Comment by gregaubert** [comment]
Yeah, our use case is a system of user rights management : 
- We create nodes for every users and groups
- and relationships between them with **one property** representing the access they have over the group
- every user can have relations with multiple groups and every groups can have relations with other groups
- and given the number of different permissions possible over a group, we use a **decimal value** where **the bits represent a permission** (for example 0011 -> 3 = the right to read and write resource x, but not the right to delete or rename it)

And with the bitwise operators, we could easily navigate in the graph, filtering the paths that don't match a given mask, to retrieve for example : all the groups that a user can access with the permissions to read and write the resource x.

Actually we can't do it directly in Neo4j, so we have to retrieve all the groups accessible by the user (which can be a lot of paths and nodes) and filter them afterwards in our application with the mask (which often result in just few paths and nodes).

Well, I guess you get the idea ? Plus I think it's pretty common to use decimal values for that purpose in ACL, User rights and that kind of stuff...

**Comment by thobe** [comment]
While I think it would be great for Cypher to have bitwise operations, I think that should depend on the existence of a `BitVector` type. I am very much not a fan of bitwise operations between numbers, because it leaks representational concerns.

**Comment by gregaubert** [comment]
Yeah, I guess a `BitVector` type would be a nice solution to these kind of problems too.
I can understand many people don't like working this way with numbers, it can be confusing. But most of current languages allow it and it can be a very powerful tool.

**Comment by thobe** [comment]
It's been a while since we did anything on this ticket.

I think that to a large extent the convenience of being able to do perform bitwise operations on numbers would be achieved by having a very simple way of converting from `Number` to `BitVector` and from `BitVector` to number. The only thing I don't quite know how that would work is sign extension and `BitVector` size in a world where we assume arbitrarily large integers.

**Comment by thobe** [comment]
This is now tracked as a Cypher feature request: opencypher/openCypher#260
