### ISSUE TITLE
Add usage message to neo4j-import if no input

### ISSUE THREAD

**Issue by mdamien** [neo4j/neo4j#5108]
When executing the script without any arguments, it just throws an error:

```
./bin/neo4j-import
Input error: Missing argument 'into'
```

An error message with a usage example would be more user-friendly.

Something like [in the guide](http://neo4j.com/developer/guide-import-csv/):

```
Usage: neo4j-import --into <destination.db> --id-type <id-type> \
                 --nodes:<node-type> <filename.csv> \
                 --relationships:<rel-name> <filename.csv>
```

**Comment by hczerpak** [comment]
I wanted to contribute on this ticket and checked it. Apparently there is a test in 

``` java
ImportToolTest.usageMessagePrintedOnEmptyInputParameters()
```

which covers this use case. It prints full help with an example.

**Comment by chrisvest** [comment]
`neo4j-import` and `neo4j-admin import` now print help messages when they are called with no arguments.
