### ISSUE TITLE
neo4-import: Line number is random

### ISSUE THREAD

**Issue by mdamien** [neo4j/neo4j#5110]
I have a big csv (4Gb) and when neo-import parse it, I have an error. But the line number is wrong and random. I can upload the csv if you want to reproduce.

**Comment by chrisvest** [comment]
Are there more than 2.147.483.647 lines in your file?

**Comment by mdamien** [comment]
There's `6 674 303` lines

It fails at lines like `2068390` for example. Like this:

``` console
  in field: title:string:2
  for header: [postId:ID(Post), title:string, body:string]
  raw field value: 2529361
  original error: At /home/linku/prog/stack/csvs/posts.csv:2068390 -  there's a field starting with a quote and whereas it ends that quote there seems  to be characters in that field after that ending quote. That isn't supported. This is what I read: 'Problem converting path string from /, ","<'
```

(this error was solved by the way)

This is the dump: https://archive.org/details/stackexchange

**Comment by jexp** [comment]
But the line number you mentioned was reported:

```
original error: At /home/linku/prog/stack/csvs/posts.csv:2068390

```

**Comment by mdamien** [comment]
Humm..I think the best thing would be to just upload the .csv so you can reproduce

**Comment by jexp** [comment]
ya, please provide it on dropbox or s3 or such.
and the exact neo4j-import command you ran.

**Comment by mdamien** [comment]
I can't reproduce and generating each file takes a really long time so let's close this.
