### ISSUE TITLE
neo4-import: Field quote escaping to include in the docs

### ISSUE THREAD

**Issue by mdamien** [neo4j/neo4j#5111]
To include a `"` inside a csv field, it looks like you have to use `\"` with neo4j-import.

The default python setting is to concat two quote like this: **'""'**

Example:

``` python
a.writerow(['hello"lol','lolito"','osdadsa\\"'])
---> will give:
"hello""lol","lolito""","osdadsa\"""
```

So the correct setting is to set `escapechar` to `\` and `doublequote` to `false`.

But this is not documented for now. I put this issue here also so people can find help in case they have the same problem.

**Comment by jexp** [comment]
Did you see this?

> --quote <quotation-character>
> Character to treat as quotation character for values in CSV data. The default option is ". Quotes inside quotes escaped like """Go away"", he said." and "\"Go away\", he said." are supported. If you have set "'" to be used as the quotation character, you could write the previous example like this instead: '"Go away", he said.'

from: http://neo4j.com/docs/stable/re03.html

**Comment by mdamien** [comment]
oops, didn't find this page. I guess it's another issues we can close :)
