### ISSUE TITLE
Cypher queries with scientific notation fails

### ISSUE THREAD

**Issue by pbashyal-nmdp** [neo4j/neo4j#5114]
Using scientific notation for double values does not work.

``` cypher
CREATE (n {name:"World", freq: 3.90447424859787e-05}) RETURN "hello", n.name
```

gives me `Neo.ClientError.Statement.InvalidSyntax`

But if I turn it into decimal value without scientific notation, it works.

``` cypher
CREATE (n {name:"World", freq: 0.0000390447424859787}) RETURN "hello", n.name
```

This is proving to be a big limitation for us. Is there a workaround?

**Comment by pbashyal-nmdp** [comment]
I got it working with turning the freq into a string and using `toFloat` to turn it back into float.

``` cypher
CREATE (n {name:"World", freq: toFloat("3.90447424859787e-05")}) RETURN "hello", n.name
```

**Comment by cleishm** [comment]
Have you tried using a capital E in the exponent form (e.g. `3.90447424859787E-05`)?

**Comment by pbashyal-nmdp** [comment]
No, I hadn't. Thanks, the uppercase E works.
By default, most languages use lowercase e when printing in scientific notation. e.g. in Python:

``` python
>>> b = 3.90447424859787E-05
>>> b
3.90447424859787e-05
>>> print b
3.9044742486e-05
```

I'd say this is a bug as exporting data from most programs would output lowercase e.

Thanks again!
