### ISSUE TITLE
Which declaration of executeQuery() is executed in TransactionHandler.java?

### ISSUE THREAD

**Issue by alsoba13** [neo4j/neo4j#5115]
Hey!
I'm trying to understanding the code. I've tried to execute it while printing some log in console for debugging. I've proceed like this:
In community directory I do: `mvn compile`
After success, in community/server directory I execute: `mvn exec:java`
The server is now up.
This is what happens when I request a transaction to http://localhost:7474/db/data/transaction/commit:
1. Server executes the `public Response commitNewTransaction( final InputStream input, @Context final UriInfo uriInfo, @Context final HttpServletRequest request )` function of TransactionService.java file.
2. Then the function `public void commit( StatementDeserializer statements, ExecutionResultSerializer output, boolean pristine, HttpServletRequest request )` of TransactionHandler.java. In the switch, it matches the case `EXECUTE_STATEMENT`. This Switch case calls `executeStatements` which also calls `engine.executeQuery( statement.statement(), statement.parameters(), sessionFactory.create( request ) );``

My problem comes here. I've tried to debug the function `executeQuery` of `ExecutionEngine` class, but it's never executed (For debugging, I print some messages through System.out.println), and I can't find any other implementation of `executeQuery`.

What am I missing?

Thanks!

**Comment by jexp** [comment]
this is not a discussion forum but an issue tracker :)
what are you trying to achieve? please take this question / discussion to the google group. Thanks a lot!
