### ISSUE TITLE
Multiple OPTIONAL MATCH neo4j cypher

### ISSUE THREAD

**Issue by gottamp** [neo4j/neo4j#5125]
multiple OPTIONAL MATCH returning the below error in Neo4j 2.2.3. I am using Cypher 2.2 parser. 
"org.neo4j.rest.graphdb.RestResultException: null at NullPointerException". The same query works perfectly in Neo4j 2.1.7.

" Neo.DatabaseError.Statement.ExecutionFailure"

Sample Query that failed.

match (user:user)-[k:SUBSCRIBED]->(package) 
 where package.startDate < 1439268888365 and package.endDate > 1439268888365 
 with package,user optional match (package)-[j:HAS]->(products) 
 with package,j,products,user optional match (package)-[j:HAS]-(otherpackages) 
 return distinct package,products,user,otherpackages

**Comment by gottamp** [comment]
To add, this looks like Cypher 2.2 parser problem than anything else. I am not sure if 2.2 supports multiple OPTIONAL MATCHES.

**Comment by jexp** [comment]
Can you share a "PROFILE " or "EXPLAIN" of your query?

When I try to run your query it works just fine.

Does the query also fail in neo4j-browser?

And did you provide the auth for 2.2 ?

**Comment by jexp** [comment]
Works for me. @gottamp can you share the information requested before? And a download of the JSON request result.
