### ISSUE TITLE
Manual incorrectly shows querylog configurable in neo4j.properties; should be neo4j-server.properties

### ISSUE THREAD

**Issue by bradnussbaum** [neo4j/neo4j#5140]
The manual for 2.2 (http://neo4j.com/docs/2.2.4/configuration-settings.html) incorrectly shows that querylog is configurable from neo4j.properties when in fact it is only configurable through neo4j-server.properties.

**Comment by jexp** [comment]
According to the code it's read from the database configuration, i.e. neo4j.properties
