### ISSUE TITLE
Please mention the #neo4j on freenode in the docs

### ISSUE THREAD

**Issue by oren** [neo4j/neo4j#5156]
There are 40 people on the chat and many people find live interaction with the community as a valuable tool for accelerate learning and creating meaningful relationships with other members.
It will be great if there will be a link from http://neo4j.com/community page to another page with a few lines explaining about the chat and what clients are available for accessing it.

Here is an example for that page:

Neo4j chat on freenode is is a place to have real time conversation with other community members. The chat is accessible via multiple clients. Some of them are web-based and some are available on your laptop or your phone.  
- **Basic web-based**: http://webchat.freenode.net/?channels=neo4j
- **Web-based, Linux, Mac, Windows**: https://en.wikipedia.org/wiki/Comparison_of_Internet_Relay_Chat_cl
- **Android**: http://www.reddit.com/r/irc/comments/1ogoy4/suggested_android_irc_clients/
- **iOS**: http://www.reddit.com/r/irc/comments/18a8ll/best_irc_for_an_iphone_user/

I use [weechat](https://weechat.org/about/features), text-based IRC client running on a $5 Digital Ocean so I am connected 24/7.

**Comment by oren** [comment]
someone on the IRC chat told me about https://neo4j-users.slack.com/
maybe we can unite them using https://sameroom.io/blog/creating-a-portal-with-slack/ ?

**Comment by oren** [comment]
I can't figure out how to sign into the slack channel.
https://neo4j-users.slack.com/ show me a sign in page but i can't login with another slack account I have. i hit the 'sign up for free' button on the top right. I am not sure what to do next. maybe someone from neo4j is suppose to invite me to the neo4js slack team?

This is very confusing ):

**Comment by jexp** [comment]
Check neo4j-users-slack-invite.herokuapp.com

Sorry slack doesn't make it easy to sign up to public channels ;)

Von meinem iPhone gesendet

**Comment by oren** [comment]
Thanks you. i joined. 

Now, since I don't want to open my browser for chat and I have a text-based clients that is connected 24/7 (weechat) I would like to access this chat from my client. I believe you need to turn on gateway access as described here - https://slack.zendesk.com/hc/en-us/articles/201727913-Connecting-to-Slack-over-IRC-and-XMPP

Also, please look at sameroom.io for unifying the the #neo4j on freenode with slack and if you think it's a good idea, also update the docs about the link you just sent me. I would send a PR but I am not sure where the repo is.
