### ISSUE TITLE
Neo4j - Browser ................................... FAILURE [  4.565 s] - Error: Cannot find module 'findup-sync'

### ISSUE THREAD

**Issue by dbl001** [neo4j/neo4j#5157]
I'm on OS X 10.10.4.

David-Laxers-MacBook-Pro:neo4j davidlaxer$ mvn -version
Apache Maven 3.2.1 (ea8b2b07643dbb1b84b6d16e1f08391b666bc1e9; 2014-02-14T09:37:52-08:00)
Maven home: /Users/davidlaxer/Downloads/apache-maven-3.2.1
Java version: 1.8.0_05, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.4", arch: "x86_64", family: "mac"
David-Laxers-MacBook-Pro:neo4j davidlaxer$ ant -version
Apache Ant(TM) version 1.9.6 compiled on June 29 2015
David-Laxers-MacBook-Pro:neo4j davidlaxer$ java -version
java version "1.8.0_05"
Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.5-b02, mixed mode)
David-Laxers-MacBook-Pro:neo4j davidlaxer$ 

hipster build:
     [exec] npm WARN prefer global bower@0.10.0 should be installed with -g
     [exec] npm WARN unmet dependency /Users/davidlaxer/neo4j/community/browser/node_modules/karma/node_modules/http-proxy requires colors@'0.x.x' but will load
     [exec] npm WARN unmet dependency /Users/davidlaxer/neo4j/community/browser/node_modules/karma/node_modules/colors,
     [exec] npm WARN unmet dependency which is version 0.6.0-1
     [exec] module.js:338
     [exec]     throw err;
     [exec]           ^
     [exec] Error: Cannot find module 'findup-sync'
     [exec]     at Function.Module._resolveFilename (module.js:336:15)
     [exec]     at Function.Module._load (module.js:278:25)
     [exec]     at Module.require (module.js:365:17)
     [exec]     at require (module.js:384:17)
     [exec]     at Object.<anonymous> (/Users/davidlaxer/neo4j/community/browser/node_modules/.bin/grunt:8:14)
     [exec]     at Module._compile (module.js:460:26)
     [exec]     at Object.Module._extensions..js (module.js:478:10)
     [exec]     at Module.load (module.js:355:32)
     [exec]     at Function.Module._load (module.js:310:12)
     [exec]     at Function.Module.runMain (module.js:501:10)
     [exec] Result: 1
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Neo4j ............................................. SUCCESS [  2.579 s]
[INFO] Neo4j - Licensing configuration ................... SUCCESS [  1.972 s]
[INFO] Neo4j - Unsafe Access ............................. SUCCESS [  2.041 s]
[INFO] Neo4j - Logging ................................... SUCCESS [  3.161 s]
[INFO] Neo4j - Primitive Collections ..................... SUCCESS [01:25 min]
[INFO] Neo4j - IO ........................................ SUCCESS [07:18 min]
[INFO] Neo4j - CSV reading and parsing ................... SUCCESS [  4.960 s]
[INFO] Neo4j - Logging ................................... SUCCESS [  4.078 s]
[INFO] SLF4J Neo4j Binding ............................... SUCCESS [  1.642 s]
[INFO] Neo4j - Graph Database Kernel ..................... SUCCESS [06:32 min]
[INFO] Neo4j - JMX support ............................... SUCCESS [  5.176 s]
[INFO] Neo4j - Usage Data Collection ..................... SUCCESS [  9.765 s]
[INFO] Neo4j - Monitor Logging ........................... SUCCESS [  6.580 s]
[INFO] Neo4j - Graphviz generation ....................... SUCCESS [  6.214 s]
[INFO] Neo4j - Lucene Index .............................. SUCCESS [01:00 min]
[INFO] Neo4j - Graph Algorithms .......................... SUCCESS [ 14.842 s]
[INFO] Neo4j - Graph Matching ............................ SUCCESS [  5.760 s]
[INFO] Neo4j - Community Cypher Build .................... SUCCESS [  1.527 s]
[INFO] Neo4j - Cypher Compiler 2.3 ....................... SUCCESS [13:59 min]
[INFO] Neo4j - Cypher .................................... SUCCESS [08:11 min]
[INFO] Neo4j - Consistency Checker ....................... SUCCESS [04:18 min]
[INFO] Neo4j - Community ................................. SUCCESS [04:00 min]
[INFO] Neo4j - Community ................................. SUCCESS [  0.599 s]
[INFO] Neo4j - Generic shell ............................. SUCCESS [01:33 min]
[INFO] Neo4j - Import Command Line Tool .................. SUCCESS [ 29.552 s]
[INFO] Neo4j - Examples .................................. SUCCESS [ 22.924 s]
[INFO] Neo4j - Server API ................................ SUCCESS [  2.356 s]
[INFO] Neo4j - Streams ................................... SUCCESS [  0.279 s]
[INFO] Neo4j - Data Protocol Project ..................... SUCCESS [  0.126 s]
[INFO] Neo4j - NDP Runtime ............................... SUCCESS [ 23.371 s]
[INFO] Neo4j - PackStream ................................ SUCCESS [ 16.926 s]
[INFO] Neo4j - NDP Messaging Library V1 .................. SUCCESS [  3.030 s]
[INFO] Neo4j - Browser ................................... FAILURE [  4.565 s]
[INFO] Neo4j - Server .................................... SKIPPED
[INFO] Neo4j - NDP Socket Transport ...................... SKIPPED
[INFO] Neo4j - NDP Kernel Extension ...................... SKIPPED
[INFO] Neo4j - Data Protocol Documentation V1 ............ SKIPPED
[INFO] Neo4j - Test Harness .............................. SKIPPED
[INFO] Neo4j - Server Plugin Tests ....................... SKIPPED
[INFO] Neo4j - Server Examples ........................... SKIPPED
[INFO] Neo4j - Cypher Acceptance ......................... SKIPPED
[INFO] Neo4j - GraphGist ................................. SKIPPED
[INFO] Neo4j - Cypher Documentation ...................... SKIPPED
[INFO] Neo4j - Cypher Reference Card Tests ............... SKIPPED
[INFO] Neo4j - Community Build ........................... SKIPPED
[INFO] Neo4j - Graph DB Monitoring and Management tools .. SKIPPED
[INFO] Neo4j - Advanced .................................. SKIPPED
[INFO] Neo4j - Advanced Server ........................... SKIPPED
[INFO] Neo4j - Advanced Build ............................ SKIPPED
[INFO] Neo4j - Query Logging ............................. SKIPPED
[INFO] Neo4j - Communication Package ..................... SKIPPED
[INFO] Neo4j - Clustering Infrastructure ................. SKIPPED
[INFO] Neo4j - Backup Tool ............................... SKIPPED
[INFO] Neo4j - High Availability ......................... SKIPPED
[INFO] Neo4j - Enterprise ................................ SKIPPED
[INFO] Neo4j - Enterprise Server ......................... SKIPPED
[INFO] Neo4j - Enterprise Performance Tests .............. SKIPPED
[INFO] Neo4j - Enterprise Build .......................... SKIPPED
[INFO] Neo4j - Integration Tests ......................... SKIPPED
[INFO] Neo4j - Stress Tests .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 51:19 min
[INFO] Finished at: 2015-08-15T23:53:34-08:00
[INFO] Final Memory: 87M/343M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.6:run (default) on project neo4j-browser: An Ant BuildException has occured: unless=cmdsuccess -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :neo4j-browser

Any ideas?

**Comment by jexp** [comment]
Can you try to delete node_modules in browser and run again? Any other ideas @oskarhane ?

**Comment by dbl001** [comment]
Do you mean remove the directory 'node_modules' in ~/neo4j?

David-Laxers-MacBook-Pro:neo4j davidlaxer$ ls
README.asciidoc         manual
RepositoryOverview.asciidoc node_modules
advanced            npm-debug.log
cla-management          packaging
code-analysis           pom.xml
community           skipped-tests.py
docs                stresstests
enterprise          target
integrationtests
David-Laxers-MacBook-Pro:neo4j davidlaxer$ vi pom.xml 
David-Laxers-MacBook-Pro:neo4j davidlaxer$ ls node_modules/
easyimage   grunt       grunt-cli   i
David-Laxers-MacBook-Pro:neo4j davidlaxer$

**Comment by jexp** [comment]
if you build neo4j there is community/browser/node_modules

**Comment by dbl001** [comment]
$ mvn clean install -DrunITs

…

[INFO] Reactor Summary:
[INFO] 
[INFO] Neo4j ............................................. SUCCESS [  1.836 s]
[INFO] Neo4j - Licensing configuration ................... SUCCESS [  1.534 s]
[INFO] Neo4j - Unsafe Access ............................. SUCCESS [  1.562 s]
[INFO] Neo4j - Logging ................................... SUCCESS [  2.111 s]
[INFO] Neo4j - Primitive Collections ..................... SUCCESS [01:20 min]
[INFO] Neo4j - IO ........................................ SUCCESS [06:26 min]
[INFO] Neo4j - CSV reading and parsing ................... SUCCESS [  3.830 s]
[INFO] Neo4j - Logging ................................... SUCCESS [  6.485 s]
[INFO] SLF4J Neo4j Binding ............................... SUCCESS [  1.639 s]
[INFO] Neo4j - Graph Database Kernel ..................... SUCCESS [07:48 min]
[INFO] Neo4j - JMX support ............................... SUCCESS [  4.151 s]
[INFO] Neo4j - Usage Data Collection ..................... SUCCESS [ 12.680 s]
[INFO] Neo4j - Monitor Logging ........................... SUCCESS [  4.970 s]
[INFO] Neo4j - Graphviz generation ....................... SUCCESS [  4.699 s]
[INFO] Neo4j - Lucene Index .............................. SUCCESS [01:55 min]
[INFO] Neo4j - Graph Algorithms .......................... SUCCESS [ 10.754 s]
[INFO] Neo4j - Graph Matching ............................ SUCCESS [  6.451 s]
[INFO] Neo4j - Community Cypher Build .................... SUCCESS [  0.984 s]
[INFO] Neo4j - Cypher Compiler 2.3 ....................... SUCCESS [10:33 min]
[INFO] Neo4j - Cypher .................................... SUCCESS [06:13 min]
[INFO] Neo4j - Consistency Checker ....................... SUCCESS [03:06 min]
[INFO] Neo4j - Community ................................. SUCCESS [03:43 min]
[INFO] Neo4j - Community ................................. SUCCESS [  0.333 s]
[INFO] Neo4j - Generic shell ............................. SUCCESS [01:25 min]
[INFO] Neo4j - Import Command Line Tool .................. SUCCESS [ 42.648 s]
[INFO] Neo4j - Examples .................................. SUCCESS [ 30.345 s]
[INFO] Neo4j - Server API ................................ SUCCESS [  2.092 s]
[INFO] Neo4j - Streams ................................... SUCCESS [  0.425 s]
[INFO] Neo4j - Data Protocol Project ..................... SUCCESS [  0.090 s]
[INFO] Neo4j - NDP Runtime ............................... SUCCESS [ 24.451 s]
[INFO] Neo4j - PackStream ................................ SUCCESS [ 14.926 s]
[INFO] Neo4j - NDP Messaging Library V1 .................. SUCCESS [  2.221 s]
[INFO] Neo4j - Browser ................................... SUCCESS [03:42 min]
[INFO] Neo4j - Server .................................... SUCCESS [06:37 min]
[INFO] Neo4j - NDP Socket Transport ...................... SUCCESS [ 38.641 s]
[INFO] Neo4j - NDP Kernel Extension ...................... FAILURE [  0.475 s]
[INFO] Neo4j - Data Protocol Documentation V1 ............ SKIPPED
[INFO] Neo4j - Test Harness .............................. SKIPPED
[INFO] Neo4j - Server Plugin Tests ....................... SKIPPED
[INFO] Neo4j - Server Examples ........................... SKIPPED
[INFO] Neo4j - Cypher Acceptance ......................... SKIPPED
[INFO] Neo4j - GraphGist ................................. SKIPPED
[INFO] Neo4j - Cypher Documentation ...................... SKIPPED
[INFO] Neo4j - Cypher Reference Card Tests ............... SKIPPED
[INFO] Neo4j - Community Build ........................... SKIPPED
[INFO] Neo4j - Graph DB Monitoring and Management tools .. SKIPPED
[INFO] Neo4j - Advanced .................................. SKIPPED
[INFO] Neo4j - Advanced Server ........................... SKIPPED
[INFO] Neo4j - Advanced Build ............................ SKIPPED
[INFO] Neo4j - Query Logging ............................. SKIPPED
[INFO] Neo4j - Communication Package ..................... SKIPPED
[INFO] Neo4j - Clustering Infrastructure ................. SKIPPED
[INFO] Neo4j - Backup Tool ............................... SKIPPED
[INFO] Neo4j - High Availability ......................... SKIPPED
[INFO] Neo4j - Enterprise ................................ SKIPPED
[INFO] Neo4j - Enterprise Server ......................... SKIPPED
[INFO] Neo4j - Enterprise Performance Tests .............. SKIPPED
[INFO] Neo4j - Enterprise Build .......................... SKIPPED
[INFO] Neo4j - Integration Tests ......................... SKIPPED
[INFO] Neo4j - Stress Tests .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 56:38 min
[INFO] Finished at: 2015-08-29T14:49:40-08:00
[INFO] Final Memory: 108M/473M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.neo4j.build.plugins:licensing-maven-plugin:1.7.5:check (list-all-licenses) on project neo4j-ndp-kernelextension: Generated file differs from the existing file.
[ERROR] Generated: /Users/davidlaxer/neo4j/community/ndp/kernelextension/target/neo4j-ndp-kernelextension-2.3-SNAPSHOT-NOTICE.txt
[ERROR] Existing: /Users/davidlaxer/neo4j/community/ndp/kernelextension/target/../NOTICE.txt
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :neo4j-ndp-kernelextension
David-Laxers-MacBook-Pro:neo4j davidlaxer$

**Comment by jexp** [comment]
Did you pull the latest state from github?

Which version do you want to build? 2.2.x ? Then please use a tagged release branch.

For 2.3 master (in development) some things might be flaky, otherwise please use the latest tagged 2.3-M02.

**Comment by dbl001** [comment]
Results :

Failed tests: 
  TxPushStrategyConfigIT.twoRoundRobin:83->assertLastTransactions:222 tx id on server:2, expected [2] but was [4], tx id on server:5, expected [4] but was [1]

Tests run: 79, Failures: 1, Errors: 0, Skipped: 4

[INFO] 
[INFO] --- maven-failsafe-plugin:2.15:verify (integration-verify) @ neo4j-ha ---
[INFO] Failsafe report directory: /Users/davidlaxer/neo4j/enterprise/ha/target/failsafe-reports
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Neo4j ............................................. SUCCESS [  1.944 s]
[INFO] Neo4j - Licensing configuration ................... SUCCESS [  1.313 s]
[INFO] Neo4j - Unsafe Access ............................. SUCCESS [  1.443 s]
[INFO] Neo4j - Primitive Collections ..................... SUCCESS [01:23 min]
[INFO] Neo4j - IO ........................................ SUCCESS [07:15 min]
[INFO] Neo4j - CSV reading and parsing ................... SUCCESS [  3.029 s]
[INFO] Neo4j - Graph Database Kernel ..................... SUCCESS [05:56 min]
[INFO] Neo4j - JMX support ............................... SUCCESS [  2.787 s]
[INFO] Neo4j - Usage Data Collection ..................... SUCCESS [  7.814 s]
[INFO] Neo4j - Monitor Logging ........................... SUCCESS [  3.200 s]
[INFO] Neo4j - Graphviz generation ....................... SUCCESS [  3.496 s]
[INFO] Neo4j - Lucene Index .............................. SUCCESS [01:34 min]
[INFO] Neo4j - Graph Algorithms .......................... SUCCESS [  9.064 s]
[INFO] Neo4j - Graph Matching ............................ SUCCESS [  3.855 s]
[INFO] Neo4j - Community Cypher Build .................... SUCCESS [  0.634 s]
[INFO] Neo4j - Cypher Compiler 2.2 ....................... SUCCESS [07:18 min]
[INFO] Neo4j - Cypher .................................... SUCCESS [06:15 min]
[INFO] Neo4j - Consistency Checker ....................... SUCCESS [02:33 min]
[INFO] Neo4j - Community ................................. SUCCESS [02:48 min]
[INFO] Neo4j - Community ................................. SUCCESS [  0.097 s]
[INFO] Neo4j - Generic shell ............................. SUCCESS [01:08 min]
[INFO] Neo4j - Import Command Line Tool .................. SUCCESS [ 38.225 s]
[INFO] Neo4j - Examples .................................. SUCCESS [ 29.999 s]
[INFO] Neo4j - Server API ................................ SUCCESS [  1.488 s]
[INFO] Neo4j - Browser ................................... SUCCESS [03:44 min]
[INFO] Neo4j - Server .................................... SUCCESS [06:32 min]
[INFO] Neo4j - Test Harness .............................. SUCCESS [ 22.695 s]
[INFO] Neo4j - Server Plugin Tests ....................... SUCCESS [  8.662 s]
[INFO] Neo4j - Server Examples ........................... SUCCESS [ 19.109 s]
[INFO] Neo4j - GraphGist ................................. SUCCESS [ 20.525 s]
[INFO] Neo4j - Cypher Documentation ...................... SUCCESS [02:01 min]
[INFO] Neo4j - Cypher Reference Card Tests ............... SUCCESS [ 36.252 s]
[INFO] Neo4j - Cypher Compiler 2.2 for scala 2.11 ........ SUCCESS [07:08 min]
[INFO] Neo4j - Community Build ........................... SUCCESS [  0.098 s]
[INFO] Neo4j - Graph DB Monitoring and Management tools .. SUCCESS [  4.423 s]
[INFO] Neo4j - Advanced .................................. SUCCESS [  0.301 s]
[INFO] Neo4j - Advanced Server ........................... SUCCESS [ 23.018 s]
[INFO] Neo4j - Advanced Build ............................ SUCCESS [  0.126 s]
[INFO] Neo4j - Query Logging ............................. SUCCESS [  7.058 s]
[INFO] Neo4j - Communication Package ..................... SUCCESS [ 11.750 s]
[INFO] Neo4j - Clustering Infrastructure ................. SUCCESS [ 17.843 s]
[INFO] Neo4j - Backup Tool ............................... SUCCESS [01:20 min]
[INFO] Neo4j - High Availability ......................... FAILURE [21:34 min]
[INFO] Neo4j - Enterprise ................................ SKIPPED
[INFO] Neo4j - Enterprise Server ......................... SKIPPED
[INFO] Neo4j - Enterprise Performance Tests .............. SKIPPED
[INFO] Neo4j - Enterprise Build .......................... SKIPPED
[INFO] Neo4j - Integration Tests ......................... SKIPPED
[INFO] Neo4j - Stress Tests .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:23 h
[INFO] Finished at: 2015-08-31T04:33:32-08:00
[INFO] Final Memory: 96M/437M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.15:verify (integration-verify) on project neo4j-ha: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/davidlaxer/neo4j/enterprise/ha/target/failsafe-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :neo4j-ha
David-Laxers-MacBook-Pro:neo4j davidlaxer$

**Comment by jakewins** [comment]
The `TxPushStrategy` test was non-deterministic. It should be resolved now. If you keep having trouble running the Neo4j build, please raise this on the neo4j mailing list, as that is a better venue to talk about development issues.
