### ISSUE TITLE
[Cypher] Complex CSV import. Issue with property set

### ISSUE THREAD

**Issue by alex-shpak** [neo4j/neo4j#5203]
Hi.

I'm using CSV importing for large amount of nodes. In my import in each row I need to set property in node if it was matched by name and there is existing path from another node to it, otherwise I should create the new node.
To achieve this I used trick with `FOREACH` and `CASE`

``` Cypher
LOAD CSV WITH HEADERS FROM "file:/file.csv" AS csvLine
WITH toInt(csvLine.id) as id, LOWER(TRIM(csvLine.name)) as name, LOWER(TRIM(csvLine.rank)) as rank,
     toInt(csvLine.parent_id) as parent_id, LOWER(TRIM(csvLine.parent_name)) as parent_name, LOWER(TRIM(csvLine.parent_rank)) as parent_rank

MATCH (r:Species {
    cid: 0 //this is the root to check is there path to current row
})
OPTIONAL MATCH (p:Species {
    cid: parent_id //this is the parent node
})
OPTIONAL MATCH (n:Species {
    name: name, //this is the node for current row
    rank: rank
})
FOREACH(ignore IN CASE WHEN (n IS NULL OR NOT ((p)-->(n) OR (r)-[*]->(n))) THEN [1] ELSE [] END |
    MERGE (:Species {
        cid: id,
        name: name,
        rank: rank
    })
)
FOREACH(ignore IN CASE WHEN ((p)-->(n) OR (r)-[*]->(n)) THEN [1] ELSE [] END |
    SET n.cid = id
)
RETURN n, p;
```

It works almost correct, but the thing is that if I set `cid` in current row then in the next row matching for `cid` for already set id is not working. (looks like changes that happened in for previous row is not affecting next row)

As an example:
In progress of import in one row I'm setting `cid` property to `0` but in next row of import if I will try `MATCH (p:Species{cid:0})` - `p` will be `NULL`

I tried to use `USING PERIODIC COMMIT 1` but it didn't help
Is it expected behaviour or I missing something? 

I'm using `neo4j CE 2.2.2` and executing cypher via `neo4j-shell`

**Comment by jexp** [comment]
Thanks for your question, please note that this is an issue tracker, not a help-forum.
Please ask your question on:
- [our google group](http://groups.google.com/group/neo4j)
- [our public slack](http://neo4j-users-slack-invite.herokuapp.com)
- [stackoverflow](http://stackoverflow.com/questions/tagged/neo4j)

Thanks a lot

What you are seeing is the cypher isolation guarantee, that updates executed within the statement don't affect previous reads.
For your conditional you should use `shortestPath( (r)-[*]->(n) )`

**Comment by alex-shpak** [comment]
Ok. Thanks.
I wasn't sure where to write it. (maybe it's a bug)
My problem is not about `(r)-[*]->(n)` but about `(p)-->(n)`
because if in previous row from csv I set `cid` field for node in next row it's not visible for match.

But I will move this question somwhere to forums, thanks.
