### ISSUE TITLE
Cypher - RETURN two combined nodes

### ISSUE THREAD

**Issue by vinerz** [neo4j/neo4j#5204]
Hello everyone! I'm trying to approach a multilingual graph database but I'm struggling on how to achieve an optimal model.

The current proposal is to make two node types: `Movie` and `MovieTranslation`.

`Movie` contains all relationships as `likes`, `ratings` and `comments`. `MovieTranslation` contains all translatable data (`title`, `plot`, `genres`). `Movie` does not contain these kind of properties, only the `original_title`.

`Movie` and `MovieTranslation` are tied by a `translation` relationship.

I want to make a cypher query that when a node has a relationship `translation` with the property `lang=:queried_language`, get the translation node, merge with the movie and RETURN it. I don't want to save it, just join on queries. As the fields are unknown, I can't do this manually.

What can I do? Also, if you guys have another suggestion for the database model, it'll be appreciated.

**Comment by jexp** [comment]
Hey @vinerz 
this is the Neo4j bug tracker, please ask your question on stackoverflow or the neo4j google group. 
Thanks a lot.

Your model is ok. You can `RETURN movie, translation` or `RETURN {movie:movie, translation:translation}` In the future there might be something like: `RETURN toMap(movie) + toMap(translation)`

**Comment by vinerz** [comment]
Hello @jexp! I'm deeply sorry for writing on the wrong channel. I saw that you have answered my question on StackOverflow, so I'll continue the discussion there. Thank you for answering here too.
