### ISSUE TITLE
[Suggestion] LIMIT before SKIP in Neo4j cypher

### ISSUE THREAD

**Issue by s101d1** [neo4j/neo4j#5285]
I found out SKIP must exist before LIMIT if you use both of them in the cypher:

```
MATCH (n:Actor)
RETURN n
SKIP 5
LIMIT 20
```

So if you swap them you will get error:

```
MATCH (n:Actor)
RETURN n
LIMIT 20
SKIP 5
```

The error message is not really clear too:

```
QueryExecutionKernelException: Invalid input 'K': expected 't/T' or 'e/E' (line 4, column 2 (offset: 35))
"SKIP 5"
```

This might be a small thing, but how about to make the LIMIT and SKIP independent of its position so LIMIT can be put before SKIP.

**Comment by cleishm** [comment]
Changing the order would, I think, create confusion as to the meaning. The current approach of having `SKIP` before `LIMIT` can be clearly described as "skip 5 items in the results, then give me the next 20". The other way around, however, could be read differently - something like "give me the first 20 results, then skip over the first 5". Requiring skip before limit does avoid that confusion.

Agreed that the message isn't great!

**Comment by jexp** [comment]
I agree with Chris that would make it more confusing. 

The parser exception is not nice, that's true but that is a larger effort to cover more and better parser error handling.

Thanks for bringing it up though.
