### ISSUE TITLE
CSS / GRASS Doesn't Parse '<node>' in Caption

### ISSUE THREAD

**Issue by typinator** [neo4j/neo4j#5293]
It should be possible to display the label(s) of a node in a web browser.
http://neo4j.com/developer/guide-neo4j-browser/ states that this is possible using the CSS statement:

> caption: '{name} of <type>';

This however just results in '<type>' appearing in the caption for the node. 

This is repeatable in the 2.2.4 and 2.2.5 web browser.

**Comment by jexp** [comment]
Sorry, my bad, I described something that is not there,

We're discussing the best way to render labels. As there might be 0..n and also different orders (by id, by name, by importance).

**Comment by typinator** [comment]
Understand and sympathise but it's pretty essential to the semantics of the visualisation. With no labels (types) it loses a lot of power.  I'm trying to demonstrate the utility as the basis for a proper enterprise architecture tool using the TRAK metamodel - https://en.wikipedia.org/wiki/TRAK#TRAK_Metamodel.

I have a taxonomy / class hierarchy and, yes, potentially an element may have several labels e.g. a **Standard** is a **Document** is an **Architecture Description Element** hence 3 potential labels.

I'd rather have adequacy now and wait for perfection!

**Comment by oskarhane** [comment]
This issue was moved to neo4j/neo4j-browser#139
