### ISSUE TITLE
[Neo4j on Powershell] - Could not run example on "Create a three node cluster on the local computer"

### ISSUE THREAD

**Issue by glindroth** [neo4j/neo4j#5327]
In the documentation there is a segment on "Create a three node cluster on the local computer". 

I tried the command by copying and pasting from the documentation page:

'C:\Neo4j-1' |
Initialize-Neo4jServer `
 -ListenOnIPAddress 127.0.0.1`
 -HTTPPort 7474 `
 -OnlineBackupServer '127.0.0.1:6362'`
 -PassThru |
Initialize-Neo4jHACluster `
 -ServerID 1`
 -InitialHosts '127.0.0.1:5001' `
 -ClusterServer '127.0.0.1:5001'`
 -HAServer '127.0.0.1:6001' `
 -PassThru |
Start-Neo4jServer -Console

but got attachment_1 as result

I then tried to put all commands on one line but got attachment_2 as result.
![attachment_1](https://cloud.githubusercontent.com/assets/12694230/9788014/737cb572-57c7-11e5-86c0-6c9c78ff55e1.png)
![attachment_2](https://cloud.githubusercontent.com/assets/12694230/9788015/7634f432-57c7-11e5-8023-260be0f7e469.png)

**Comment by glindroth** [comment]
@glennsarti

**Comment by glennsarti** [comment]
@glindroth I'll have a look at it as soon as I can.  In the mean time can you send throught as much info as possble to repro the problem.

**Comment by glennsarti** [comment]
@glindroth

Yeah the backtick "`" requires an empty line to terminate.  I think I'll suggest modifying the documentation and remove the backticks and use only pipe chars.  In the mean time just press enter again until it runs.

The error is saying that the neo4j installation at c:\neo4j-1 isn't a valid one.  Can you check that the following paths exist;

C:\Neo4j-1\bin
C:\Neo4j-1\data
C:\Neo4j-1\lib

and to get more debug information, append -Verbose to commands

**Comment by glindroth** [comment]
Hi,
Sorry i did not read the documentation properly, i.e. the part about having the 3 installations. Please disregard from this issue.
