### ISSUE TITLE
str() is not safe for use on strings

### ISSUE THREAD

**Issue by mmmmmrob** [neo4j/neo4j#5337]
RETURN str(1)+str(2) // returns 12
RETURN str('1')+str('2') // returns "1""2"
RETURN str(str(str('foo'))) // returns """foo"""
RETURN str('foo') = 'foo' // returns false

str(string) currently changes the string value by surrounding it in quotes.

For situations where string concatenation, or regex, is used against a property value that may be null, string or number it would be desirable for str(string) to simple return the string value unaltered.

**Comment by jexp** [comment]
Hi @mmmmmrob yes, `str()` is weird and will go away, have you tried `toString()` ?

**Comment by mmmmmrob** [comment]
My use case is safe concatenation of properties where the value may be string, int or null. In this case toString is also not useful.

RETURN toString('foo') // returns 'foo'
RETURN toString(null) // returns null (expected empty string)
RETURN 'foo' + null // returns null (expected 'foo')
RETURN toString('foo') + toString(null) // returns null (expected 'foo')

**Comment by jakewins** [comment]
Adding this as a feature request for cypher, pending cypher team feedback. In the meantime, you can work around this using `coalesce`:

```
RETURN toString( coalesce( null, "" ) )
```

**Comment by jonasagx** [comment]
Is there anyone working on it right now? Or was it already solved? If no for both questions I would like to do it. I'm new here.

**Comment by Lojjs** [comment]
While str() is not supported in Cypher, this will unfortunately not be fixed. I refer to @jakewins solution of using toString() combined with coalesce(). I will hereby close this issue, feel free to re-open it or create a new one if there are remaining issues regarding this.

Best regards Cypher Team through Louise
