### ISSUE TITLE
Difference between `properties` endpoint for node and relationships on `PUT` method

### ISSUE THREAD

**Issue by dr-dimitru** [neo4j/neo4j#5341]
- Endpoint `/relationship/{id}/properties` on `PUT` method updates existing props and creates new props.
- Endpoint `/node/{id}/properties` on `PUT` method removes all existing props and creates new set

I believe if Neo4j REST API follows hypermedia standards - both endpoints should act at same way on same methods. If there is any reason for it - please explain.

**Comment by jexp** [comment]
It was probably an oversight, I was only aware of the way the node-endpoint does it.

I think it is best to not bother with the rest endpoints and use a cypher statement instead. It has been around for 5 years so I presume it will not be fixed for now.

`MATCH (n) where id(n) = {id} SET n + {props}`
