### ISSUE TITLE
neo4j-import crashes on rows with quotations marks and no content

### ISSUE THREAD

**Issue by halflings** [neo4j/neo4j#5357]
If you try to create a database using neo4j-import and this file:

```
contactEmail:ID
example@example.com
anotherexample@example.com
""
```

This is the output:

```
neo4j-import --into "another_test.db" --nodes:Email test.csv --stacktraces true
Importing the contents of these files into another_test.db:
Nodes:
  :Email
  /Users/akachkach/workspace/risk-batch/offline_learn/graph/src/test.csv

Available memory:
  Free machine memory: 6,24 GB
  Max heap memory : 3,56 GB

Nodes
Import error: Encoder StringEncoder[2] returned an illegal encoded value 0
```

This is because of the last line: two quotation marks without anything inside.

**Comment by chrisvest** [comment]
It looks like your `--nodes:Email test.csv` argument is understood as two separate arguments:

    Nodes:
      :Email
      /Users/akachkach/workspace/risk-batch/offline_learn/graph/src/test.csv

Does it work better if you wrap it in double-quotes?
`neo4j-import --into "another_test.db" "--nodes:Email test.csv" --stacktraces true`

**Comment by tinwelint** [comment]
@halflings This issue has been fixed. Which version are you using?

**Comment by halflings** [comment]
[EDIT: this is an answer to a comment that has now been deleted]
I don't think that's what was causing the problem here (I've been running this code for a while now, without any problems; it's really this "edge case" value that made it crash)

---

I just updated to 2.2.5 (was using 2.2.4) before, and now that example doesn't crash anymore!

It does give me this when building edges between another type of node and these Email nodes:

```
Import error: InputRelationship:
   source: [some_file_here]:7170
   startNode: some_node_id_here
   endNode: null
   type: USED_EMAIL
 is missing END_ID field
```

But that makes sense because that line is "some_node_id_here,"

So, maybe this was fixed in 2.2.5?

**Comment by tinwelint** [comment]
This is the commit: 75e12f448c49d1636b28ebfa70d5f665d460c8d0 , so 2.2.5 is the first version with this fix, correct.

**Comment by halflings** [comment]
Thanks!

Maybe neo4j-import also shouldn't crash on the new "error" (`Import error: InputRelationship`) but just gracefully skip that row instead.

**Comment by tinwelint** [comment]
Perhaps, although question is how forgiving it should be. Too much isn't
good either because you might import data that doesn't make sense in the
end.

On Tue, Sep 15, 2015 at 2:12 PM, Ahmed Kachkach notifications@github.com
wrote:

> Thanks!
> 
> Maybe neo4j-import also shouldn't crash on the new "error"
> (InputRelationship) but just gracefully skip that row instead.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/neo4j/neo4j/issues/5357#issuecomment-140369631.

## 

Mattias Persson
Neo4j Hacker at Neo Technology

**Comment by halflings** [comment]
Since neo4j-import already skips rows that have edges to inexistent nodes, it might make sense to do the same thing with null values. (just log them in bad.log)

**Comment by halflings** [comment]
Closing this since the main error (crash on empty value for a node) is fixed.
