### ISSUE TITLE
CREATE INDEX does nothing

### ISSUE THREAD

**Issue by mmmmmrob** [neo4j/neo4j#5367]
After creating a large number of indexes (~1,450) CREATE INDEX statements start to return with "nothing changed" and the index is not created.

Macbook Pro, OS X 10.10.5, 8GB
java version "1.7.0_71"
Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.71-b01, mixed mode)

**Comment by tinwelint** [comment]
Could you provide output from Cypher execution, if any? Also indexes are created lazily in the background and will be used as soon as they are built, i.e. status ONLINE. You can see status of indexes by executing the shell command `schema` or via [embedded API](https://github.com/neo4j/neo4j/blob/2.3/community/kernel/src/main/java/org/neo4j/graphdb/GraphDatabaseService.java#L312). I believe cypher will treat a `CREATE INDEX` query idempotently, so that if that index already existed it won't be created and nothing would happen.

**Comment by dav009** [comment]
I'm having a related issue.
I have a large DB, on which I call `CREATE INDEX`.
As @tinwelint  points out, the index is being created on the background but it takes ageeess.

would it be possible to include an option to create the index in the batch importer tool?

**Comment by tinwelint** [comment]
At least that's a planned feature addition, to have import tool create schema and populate indexes as part of the import.

**Comment by dav009** [comment]
I'm willing to contribute with it. 
Can you point me to any docs/classes on how are indexes stored ?

**Comment by tinwelint** [comment]
@dav009 Alright, I'm just going to point you to [LuceneIndexAccessor](https://github.com/neo4j/neo4j/blob/3.0/community/lucene-index/src/main/java/org/neo4j/kernel/api/impl/index/LuceneIndexAccessor.java) which is the, sort of, entry point class for a Lucene schema index in Neo4j. In there you'll see a `LuceneIndexUpdater` which should eventually be able to point you to format and all that.

Schema rules (index/constraint definitions) are stored in [SchemaStore](https://github.com/neo4j/neo4j/blob/3.0/community/kernel/src/main/java/org/neo4j/kernel/impl/store/SchemaStore.java).

The import tool does things in parallel and batches, so it may not be super straight forward to get right immediately, but you're absolutely free to give it a go!

**Comment by dav009** [comment]
:+1:  thanks!

**Comment by jakewins** [comment]
@tinwelint @mmmmmrob the original issue here seems unrelated to the async index creation though; cypher should report that indexes were created, even if they are not yet online. 

@mmmmmrob which Neo4j version are you running, and is there any chance you can send us your `messages.log` debug log? It should be located under `data/graph.db/messages.log` if you are running Neo4j Server.

**Comment by Mats-SX** [comment]
@dav009 Is this still a problem for you, or can we close this issue?

**Comment by Lojjs** [comment]
@mmmmmrob In order to help you we would need additional data about which Neo4j version you are running and your debug log. Because we have not got those answers, I will close this issue. If this is still an issue for you or you want to fill us in with more info, please re-open it.
