### ISSUE TITLE
Creating a large number of indexes causes out of memory error.

### ISSUE THREAD

**Issue by mmmmmrob** [neo4j/neo4j#5368]
Creating a large number of indexes in one query (~1,400) causes the server to attempt to populate them at the same time, causing a Java out of memory error.

**Comment by chrisvest** [comment]
Hi @mmmmmrob, sorry for the late reply. Do you remember what version you were trying this on?

**Comment by chrisvest** [comment]
This does not look like a problem anymore. Closing.
