### ISSUE TITLE
Passing parameters as command line arguments to neo4j-shell (or cypher-shell)

### ISSUE THREAD

**Issue by halflings** [neo4j/neo4j#5384]
It's rather common that you'd have a cypher script saved in a file that you run with `neo4j-shell -file`; and often, that file has some values that you want to change depending on what you want to do.

Currently, a "hack" to do this would be to write a new file with `export someparameter="somevalue"` and then cat the cypher file into it, using that parameter.

This is not very convenient, and it also doesn't work for some commands that don't support parameters (like `LOAD CSV`).

It would be great if we could have some support for passing parameters to `neo4j-shell`, something like: `neo4j-shell -path graph.db -file queries.cypher --a=5 --b=test --csvfile="/graph-data/db.csv"`

**Comment by mmmmmrob** [comment]
+1 for more ability to pass values into neo4j-shell to change variables and paths for LOAD CSV

**Comment by cleishm** [comment]
Great input, thanks! `neo4j-shell` began life well before cypher, and thus it was never really designed with a cypher workflow in mind. Indeed, that you can supply a file containing cypher commands and have them evaluated in order is more of a happy coincidence than the result of a careful plan.

We do, however, intend to build a new shell tool in the hopefully not-too-distant future, and considerations like this will be a big input into that design. So thanks for the input!

**Comment by halflings** [comment]
Refering to https://github.com/nicolewhite/cycli by any chance? :smiley: 
Looking forward to what that will look like in any case! :+1:

**Comment by craigtaverner** [comment]
It looks like this feature was not included in the new cypher-shell released with Neo4j 3.x. We could consider this.

**Comment by alecmuffett** [comment]
+1 - I just came up with a really good use-case for this feature, only to find that is doesn't exist yet. :-( 

edit: and, yes, I would like parameters for `LOAD CSV` as well as being able to pass them into `cypher-shell`, please

**Comment by cleishm** [comment]
@alecmuffett This is possible with [neo4j-client](https://neo4j-client.net/) as follows:

```
neo4j-client --eval ':export x="hello world"' --source input.cypher -u neo4j -P localhost
```

It simply evaluates the inline string (`:export x="hello world"`) before sourcing the input file. I'll consider adding a more obvious '--export` option to simplify this.

**Comment by sherfert** [comment]
This feature was added in https://github.com/neo4j/cypher-shell/pull/164
