### ISSUE TITLE
ORDER BY should fail when argument is a literal

### ISSUE THREAD

**Issue by cybersam** [neo4j/neo4j#5387]
Currently, queries containing `ORDER BY` clauses with literal arguments are accepted by Cypher, but seem to be executed as if the `ORDER BY` clause does not exist. For example:
- `MATCH (n) RETURN n ORDER BY 123`
- `MATCH (n) RETURN n ORDER BY "abc" DESC LIMIT 3`

Shouldn't Cypher treat such usage as errors instead of silently ignoring the `ORDER BY` clause?

**Comment by cleishm** [comment]
Hey @cybersam,

Neo4j isn't exactly ignoring the `ORDER BY` clause. It's just ordering them by the given expression in your example, which, as it's a literal (123 or `"abc"`), means it always evaluates to exactly the same value. That results is that all rows of the output having the same order position, and thus they get ordered in the same way they would in the case `ORDER BY` hadn't been specified in the first place. The same would occur if you used `ORDER BY 1+2`, for example.

There definitely could be a warning added if the expression doesn't contain any identifiers, although I'm not sure if it should be an outright failure. Will pass the request along to the team.

**Comment by systay** [comment]
Hey Sam,

Thanks a lot for your feedback.

Given our current load, this is not an urgent issue to work on. We always welcome external contributions, however.
