### ISSUE TITLE
RPM does not mark `/etc/sysconfig/neo4j` as noreplace config file

### ISSUE THREAD

**Issue by wcooley** [neo4j/neo4j#5389]
The RPM spec file does not mark `/etc/sysconfig/neo4j` as a configuration file, so RPM makes no attempt to preserve the contents on upgrade. Since this is where the tuning for the JVM goes, it's kinda important that it not get wacked on upgrade.

Ideally, it will be marked as "noreplace" like the files in `/etc/neo4j`, so that, when modified, new versions are created as `/etc/sysconfig/neo4j.rpmnew`.

I can see where in `packaging/installer-linux/installer-rpm/pom.xml` this should happen approximately, but not having a build environment and not knowing Maven, I regret to say that I do not have a patch.

**Comment by benbc** [comment]
Thanks for raising this @wcooley. We're planning to rework the RPM soon and we'll make sure to sort this out when we do.
