### ISSUE TITLE
build failed due to unresolved dependency

### ISSUE THREAD

**Issue by manonthemat** [neo4j/neo4j#5399]
2.3 branch

Running

```
mvn install -DfullBuild -Dmaven.test.skip=true -DskipBrowser
```

on OS X results in

[ERROR] Failed to execute goal on project neo4j-cypher-refcard: Could not resolve dependencies for project org.neo4j.doc:neo4j-cypher-refcard:jar:2.3-SNAPSHOT: Failure to find org.neo4j.doc:neo4j-cypher-refcard-tests:jar:docs:2.3-SNAPSHOT in http://m2.neo4j.org/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of neo4j-snapshot-repository has elapsed or updates are forced -> [Help 1]

**Comment by manonthemat** [comment]
On Ubuntu 14.04 the same command results in

[ERROR] Failed to execute goal on project neo4j-io: Could not resolve dependencies for project org.neo4j:neo4j-io:jar:2.3-SNAPSHOT: Could not find artifact org.neo4j:neo4j-unsafe:jar:tests:2.3-SNAPSHOT in neo4j-snapshot-repository (http://m2.neo4j.org/content/repositories/snapshots/) -> [Help 1]

**Comment by jotomo** [comment]
The missing artefacts are test jars in both cases. Since the documentation is build from those jars, the tests aren't optional when doing a full build. Removing the _-Dmaven.test.skip flag_ will help.

**Comment by manonthemat** [comment]
Thanks for the explanation.
