### ISSUE TITLE
Percentile should throw InvalidArgumentException immediately on incorrect argument value

### ISSUE THREAD

**Issue by tkroman** [neo4j/neo4j#5432]
I tried to compute a percentile without paying too much attention to the docs (used 95 instead of 0.95):

![](https://i.imgur.com/e42ufqk.png)

Instead of telling me the correct value range for `{percentile}`, the function computation started (and took quite a bit of time), and threw `"java.lang.IndexOutOfBoundsException: 1231999804`, which I traced back to the `PercentileFunction`:

```
val floatIdx = perc * (count - 1)
val floor = floatIdx.toInt
val ceil = math.ceil(floatIdx).toInt
if(ceil == floor || floor == count - 1) temp(floor)
 // floor == 1231999804 on the next line
else asDouble(temp(floor)) * (ceil - floatIdx) + asDouble(temp(ceil)) * (floatIdx - floor)
```

If the function was fail-fast and checked the arguments, it wouldn't consume so much resources just to throw an internal exception.

**Comment by Mats-SX** [comment]
Thanks for reporting this, @tkroman. We have put this on our todo list, and will get around to it soon.
