### ISSUE TITLE
RPM incorrectly removes user/group on upgrade

### ISSUE THREAD

**Issue by wcooley** [neo4j/neo4j#5433]
The RPMs incorrectly removes the _neo4j_ user & group on upgrade, which breaks upgrades by leaving all of the files without an owner and group:

```
$ ls -l /var/lib/neo4j/
total 20340
-rw-r--r--. 1 496 497       11 Sep  8  2014 active_tx_log
drwxr-xr-x. 2 496 497     4096 Mar 11  2015 index/
-rw-r--r--. 1 496 497 20661455 Mar 26 11:53 messages.log
-rw-r--r--. 1 496 497       96 Mar 11  2015 neostore
-rw-r--r--. 1 496 497        9 Mar 11  2015 neostore.id
...
```

This is due to unconditionally removing the user & group in the _postuninstall_ scriptlet:

```
$ rpm -qp --scripts neo4j-2.2.5-1.noarch.rpm
...
postuninstall scriptlet (using /bin/sh):
/usr/bin/getent group neo4j > /dev/null 2>&1 && /usr/sbin/userdel neo4j
```

This should be conditional upon `$1 == 0`, which indicates a complete removal; see
https://fedoraproject.org/wiki/Packaging:ScriptletSnippets#Syntax

Alternatively, just don't remove the user & group automatically, as advised here:
https://fedoraproject.org/wiki/Packaging:UsersAndGroups?rd=Packaging/UsersAndGroups#Allocation_Strategies

**Comment by benbc** [comment]
Thanks, @wcooley. We'll sort this out.
