### ISSUE TITLE
LowestCommonAncestor: Incorrect results for DAGs

### ISSUE THREAD

**Issue by jdgarrett** [neo4j/neo4j#544]
The lowestCommonAncestor algorithm under org.neo4j.graphalgo.impl.ancestor.AncestorsUtil seems to only work for trees.  It returns incorrect results when performing the algorithm on DAGs.  For example, given the following graph:
`A`
`|\`
`B C`
`| |`
`D |`
`|/`
`E`
The common ancestor for D and C returns A correctly, however the common ancestor between  E and C also returns A, when it should return C, since C is a direct ancestor of E.

**Comment by burqen** [comment]
Thank you for reporting!
Issue confirmed and added to backlog.

**Comment by tinwelint** [comment]
6,5 years later I read this issue and notice that `AncestorUtil` and that `lowestCommonAncestor` algorithm is gone, so I can do no more than close this card. Sorry.
