### ISSUE TITLE
what is the default password?  it is not 'neo4j'

### ISSUE THREAD

**Issue by pangguoming** [neo4j/neo4j#5444]
i try to login with  account: neo4j password:neo4j
it say: Invalid username or password. 
what is the default password?

**Comment by jexp** [comment]
default is user:neo4j, password:neo4j

you probably set it in the past, just delete the `data/dbms/auth` file and restart the db.

**Comment by pangguoming** [comment]
i install neo4j again, when i try to login with another web browser, it still say:: Invalid username or password.

**Comment by pangguoming** [comment]
Thanks, i did it

**Comment by Korun1** [comment]
where is data/dbms/auth ?

**Comment by gggordon** [comment]
@Korun1 you may find this by default in your neo4j data directory (specified in your config file usually located at ```/etc/neo4j/neo4j.conf``` )

Default path : ```/var/lib/neo4j/data```

**Comment by akshayB1993** [comment]
Thank you very much

**Comment by narutosanjiv** [comment]
Its depend on OS and how you have installed Neo4J. If you are on Mac OS X and installed Neo4j using brew, then path may something like below:

`/usr/local/Cellar/neo4j/3.3.0/libexec/data/dbms/auth`

**Comment by Anishx** [comment]
Any idea as to how this is done on windows ?

**Comment by pangguoming** [comment]
@Anishx just delete data/dbms/auth file

**Comment by jacks808** [comment]
same issue
neo4j version:

neo4j 3.5.11

password 'neo4j' not work

**Comment by aaron-dsouza-zz** [comment]
@Anishx Its located at %HOMEPATH%\.Neo4jDesktop\neo4jDatabases\database-xxxxxx\installation-xxx\data\dbms

**Comment by srishino1016** [comment]
Hi All, I am stuck in opening http://localhost:7474/browser/, following from the above discussion I deleted the auth file which was present to me at: $HOMEPATH$:.Neo4jDesktop\relate-data\dbmss\dbms-39c3c302-aef2-4752-97cc-e07143fd22bf\data\dbms.
Before deleting the file atleast the 7474/browser page was opening and asking for username(my input: neo4j) and password (my input: neo4j) but now the page is not even opening. I am working on windows 10, please give a solution for this. Thank you very much.

**Comment by adeel2020** [comment]
click on the right down corner "Reset DBMS password" to change the password

**

<img width="897" alt="Image" src="https://github.com/user-attachments/assets/2e7158c1-c327-4605-b310-4ac41936401c" />

**
