### ISSUE TITLE
RPM Java dependencies

### ISSUE THREAD

**Issue by Alan-R** [neo4j/neo4j#5484]
I'm aware that RPMs are considered experimental (as per discussion in #5388). They should be the default way to install Neo4j outside of a container (as I said there).

Currently the Neo4j Java dependencies are for a specific 1.7 version of Java. However, 1.7 is obsolescent and the newest Linux distros only supply 1.8. If the RPM dependency were on the java capability, then it would accept any package that provided the java capability. There is a good discussion of this here: http://stevenengelhardt.com/2013/05/29/creating-a-virtual-java-rpm/ - where he explains that it's a little more complicated than I explained it. But still, it seems worthwhile to consider.

Specifically, I can't install Neo4j RPMs on Fedora 21 or 22 because of this issue. Fedora 21 was the basis for RHEL7.

When I install tar balls, the installer explains that this is not the optimal way to install the code, and I shouldn't be using it either. As far as I know, it's either tar balls or RPMs for a big chunk of Linux ;-).

**Comment by vargok** [comment]
I agree that it would be great if the dependencies were updated to prefer only java >= 1.7, or whatever the real requirement is actually rather than a specific requirement.

Also, can the Yum repo be made to include repoView so that we can review the contents?  Company doesn't make it easy to use YUM, but would still like to base downloads off the yum repository.

**Comment by Alan-R** [comment]
And for good measure,  make sure you don't drop experimental RPMS into your yum repository.

**Comment by benbc** [comment]
Thanks for raising these points, @Alan-R and @vargok. We're hoping to rework the RPM soon and we'll make sure to cover the things you've raised.

**Comment by Alan-R** [comment]
Just to be clear, @benbc: You intend this to mean the problems discussed in https://github.com/neo4j/neo4j/issues/5388 as well. Certainly, that's what @wcooley and @vargok and I all would like. And for that matter - anyone using RPMs ;-).

**Comment by benbc** [comment]
@Alan-R I meant the Java dependency problem mentioned in this issue. But yes, we will also sort out the repo.
