### ISSUE TITLE
[Browser] Intercom opt-in message obscures editor

### ISSUE THREAD

**Issue by simpsonjulian** [neo4j/neo4j#5493]
A new Neo4j install is unusable unless you opt in or out of Intercom.  New users do get confused by this.

![neo4j__var_lib_neo4j_data_graph_db](https://cloud.githubusercontent.com/assets/35637/10181575/52cb00fe-6776-11e5-9919-c09d4114c968.png)

**Comment by nicolewhite** [comment]
:+1: 

Unless you're already familiar with the browser, it's not clear that the query window is being blocked. Some users never figure out where they are supposed to write queries.

**Comment by oskarhane** [comment]
I agree. This will be gone in 2.3.
