### ISSUE TITLE
[Powershell] - Start-Neo4jShell fails with "Connection refused"

### ISSUE THREAD

**Issue by glindroth** [neo4j/neo4j#5531]
The following fails on Windows 10:
1. Download zip from packaging (https://build.neohq.net/viewLog.html?buildId=271206&buildTypeId=Neo4j23_Packaging&tab=artifacts)
2. Unzip to your local drive
3. Open powershell as administrator
4. Follow Import-Module command as stated on http://neo4j.com/docs/snapshot/powershell.html
5. Run the command '[db location]' | Start-Neo4jShell

Expected result:
Neo4j shell should be started

Actual result:
Error occurs - "Connection refused" - see attached image
![screen shot 2015-10-05 at 09 20 28](https://cloud.githubusercontent.com/assets/12694230/10274871/9fcc374a-6b42-11e5-81c8-8fc1543e8cb3.png)

**Comment by glindroth** [comment]
@glennsarti - Please look at this as soon as you can - may be release blocking for 2.3

**Comment by glindroth** [comment]
Tried to add a simple -file argument without success - same error Connection refused

**Comment by glindroth** [comment]
Also tried to specify -port 7474 but got the following output:

PS C:\Windows\system32> 'C:\neo4j-1\neo4j-enterprise-2.3.0-RC1\' | Start-Neo4jShell -port 7474 -Console -Wait -Verbose

Exception in thread "main" java.lang.IllegalArgumentException: There are multiple values for 'port'
at org.neo4j.helpers.Args.getSingleOptionOrNull(Args.java:216)
at org.neo4j.helpers.Args.get(Args.java:228)
at org.neo4j.shell.StartClient.start(StartClient.java:156)
at org.neo4j.shell.StartClient.main(StartClient.java:135)

**Comment by glindroth** [comment]
Heard from @lassewesth that as long as the command knows the location of the database directory, then it is clever enough to read the property file, either that or default to port 1337.

Any pointers on my command? Am I running incorrectly?

**Comment by glennsarti** [comment]
In the first case, I think you were trying to connect a Neo4j shell but there was no remote Neo4j Server running on port 7474.  It could be firewall related but it's hard to tell from the screenshot.  Normally the firewall will drop the packet instead of send a refusal which is what makes me think that there is nothing listening on 7474 thus 'connection refused'

In the second case of the `-file` parameter, and third case of `-port` I'll try and repro the issues

**Comment by glennsarti** [comment]
Ok...the `-file` parameter won't help the connection refused issue.

I can repro the `-port` issue

**Comment by glindroth** [comment]
FYI:
- I ensured to start a server and verified it up and running via browser
- I opened a new powershell prompt and ran the neo4jShell command and still got Connection refused
- I ensured all Windows firewalls were turned off

**Comment by glennsarti** [comment]
Stupid question maybe.  Was the remote shell enabled? By default it's not.

`conf\neo4j.properties` file
`remote_shell_enabled=true`

Also you can do a `netstat -a -n -o` and you should hopefully see something on Port 1337 (default)

e.g.`TCP     0.0.0.0:1337      0.0.0.0:0      LISTENTING   1234`

**Comment by glindroth** [comment]
It was not enabled. However I enabled it by uncommenting that line, restarted the server and reran the shell command and got the same result.

Netstat gave me nothing on port 1337:

PS C:\Windows\system32> netstat -a -n -o

Active Connections

  Proto  Local Address          Foreign Address        State           PID
  TCP    0.0.0.0:135            0.0.0.0:0              LISTENING       612
  TCP    0.0.0.0:445            0.0.0.0:0              LISTENING       4
  TCP    0.0.0.0:5357           0.0.0.0:0              LISTENING       4
  TCP    0.0.0.0:7680           0.0.0.0:0              LISTENING       896
  TCP    0.0.0.0:49408          0.0.0.0:0              LISTENING       400
  TCP    0.0.0.0:49409          0.0.0.0:0              LISTENING       836
  TCP    0.0.0.0:49410          0.0.0.0:0              LISTENING       896
  TCP    0.0.0.0:49411          0.0.0.0:0              LISTENING       1068
  TCP    0.0.0.0:49412          0.0.0.0:0              LISTENING       472
  TCP    0.0.0.0:49435          0.0.0.0:0              LISTENING       480
  TCP    0.0.0.0:51809          0.0.0.0:0              LISTENING       5256
  TCP    10.0.2.15:139          0.0.0.0:0              LISTENING       4
  TCP    10.0.2.15:51804        204.79.197.200:443     CLOSE_WAIT      5668
  TCP    10.0.2.15:51805        204.79.197.200:443     CLOSE_WAIT      5668
  TCP    10.0.2.15:51806        204.79.197.200:443     CLOSE_WAIT      5668
  TCP    10.0.2.15:51891        191.232.139.254:443    TIME_WAIT       0
  TCP    127.0.0.1:5001         0.0.0.0:0              LISTENING       6080
  TCP    127.0.0.1:5001         127.0.0.1:51829        TIME_WAIT       0
  TCP    127.0.0.1:5001         127.0.0.1:51904        ESTABLISHED     6080
  TCP    127.0.0.1:6001         0.0.0.0:0              LISTENING       6080
  TCP    127.0.0.1:6362         0.0.0.0:0              LISTENING       6080
  TCP    127.0.0.1:7474         0.0.0.0:0              LISTENING       6080
  TCP    127.0.0.1:51817        127.0.0.1:51818        TIME_WAIT       0
  TCP    127.0.0.1:51819        127.0.0.1:51820        TIME_WAIT       0
  TCP    127.0.0.1:51821        127.0.0.1:51822        TIME_WAIT       0
  TCP    127.0.0.1:51823        127.0.0.1:51824        TIME_WAIT       0
  TCP    127.0.0.1:51825        127.0.0.1:51826        TIME_WAIT       0
  TCP    127.0.0.1:51827        127.0.0.1:51828        TIME_WAIT       0
  TCP    127.0.0.1:51830        127.0.0.1:51831        TIME_WAIT       0
  TCP    127.0.0.1:51832        127.0.0.1:51833        TIME_WAIT       0
  TCP    127.0.0.1:51834        127.0.0.1:51835        TIME_WAIT       0
  TCP    127.0.0.1:51836        127.0.0.1:51837        TIME_WAIT       0
  TCP    127.0.0.1:51838        127.0.0.1:51839        TIME_WAIT       0
  TCP    127.0.0.1:51840        127.0.0.1:51841        TIME_WAIT       0
  TCP    127.0.0.1:51842        127.0.0.1:51843        TIME_WAIT       0
  TCP    127.0.0.1:51844        127.0.0.1:51845        TIME_WAIT       0
  TCP    127.0.0.1:51846        127.0.0.1:51847        TIME_WAIT       0
  TCP    127.0.0.1:51848        127.0.0.1:51849        TIME_WAIT       0
  TCP    127.0.0.1:51850        127.0.0.1:51851        TIME_WAIT       0
  TCP    127.0.0.1:51852        127.0.0.1:51853        TIME_WAIT       0
  TCP    127.0.0.1:51854        127.0.0.1:51855        TIME_WAIT       0
  TCP    127.0.0.1:51856        127.0.0.1:51857        TIME_WAIT       0
  TCP    127.0.0.1:51858        127.0.0.1:51859        TIME_WAIT       0
  TCP    127.0.0.1:51860        127.0.0.1:51861        TIME_WAIT       0
  TCP    127.0.0.1:51862        127.0.0.1:51863        TIME_WAIT       0
  TCP    127.0.0.1:51864        127.0.0.1:51865        TIME_WAIT       0
  TCP    127.0.0.1:51866        127.0.0.1:51867        TIME_WAIT       0
  TCP    127.0.0.1:51868        127.0.0.1:51869        TIME_WAIT       0
  TCP    127.0.0.1:51870        127.0.0.1:51871        TIME_WAIT       0
  TCP    127.0.0.1:51872        127.0.0.1:51873        TIME_WAIT       0
  TCP    127.0.0.1:51874        127.0.0.1:51875        TIME_WAIT       0
  TCP    127.0.0.1:51876        127.0.0.1:51877        TIME_WAIT       0
  TCP    127.0.0.1:51878        127.0.0.1:51879        TIME_WAIT       0
  TCP    127.0.0.1:51880        127.0.0.1:51881        TIME_WAIT       0
  TCP    127.0.0.1:51892        127.0.0.1:51893        ESTABLISHED     6080
  TCP    127.0.0.1:51893        127.0.0.1:51892        ESTABLISHED     6080
  TCP    127.0.0.1:51894        127.0.0.1:51895        ESTABLISHED     6080
  TCP    127.0.0.1:51895        127.0.0.1:51894        ESTABLISHED     6080
  TCP    127.0.0.1:51896        127.0.0.1:51897        ESTABLISHED     6080
  TCP    127.0.0.1:51897        127.0.0.1:51896        ESTABLISHED     6080
  TCP    127.0.0.1:51898        127.0.0.1:51899        ESTABLISHED     6080
  TCP    127.0.0.1:51899        127.0.0.1:51898        ESTABLISHED     6080
  TCP    127.0.0.1:51900        127.0.0.1:51901        ESTABLISHED     6080
  TCP    127.0.0.1:51901        127.0.0.1:51900        ESTABLISHED     6080
  TCP    127.0.0.1:51902        127.0.0.1:51903        ESTABLISHED     6080
  TCP    127.0.0.1:51903        127.0.0.1:51902        ESTABLISHED     6080
  TCP    127.0.0.1:51904        127.0.0.1:5001         ESTABLISHED     6080
  TCP    127.0.0.1:51905        127.0.0.1:51906        ESTABLISHED     6080
  TCP    127.0.0.1:51906        127.0.0.1:51905        ESTABLISHED     6080
  TCP    127.0.0.1:51907        127.0.0.1:51908        ESTABLISHED     6080
  TCP    127.0.0.1:51908        127.0.0.1:51907        ESTABLISHED     6080
  TCP    127.0.0.1:51909        127.0.0.1:51910        ESTABLISHED     6080
  TCP    127.0.0.1:51910        127.0.0.1:51909        ESTABLISHED     6080
  TCP    127.0.0.1:51911        127.0.0.1:51912        ESTABLISHED     6080
  TCP    127.0.0.1:51912        127.0.0.1:51911        ESTABLISHED     6080
  TCP    127.0.0.1:51913        127.0.0.1:51914        ESTABLISHED     6080
  TCP    127.0.0.1:51914        127.0.0.1:51913        ESTABLISHED     6080
  TCP    127.0.0.1:51915        127.0.0.1:51916        ESTABLISHED     6080
  TCP    127.0.0.1:51916        127.0.0.1:51915        ESTABLISHED     6080
  TCP    127.0.0.1:51917        127.0.0.1:51918        ESTABLISHED     6080
  TCP    127.0.0.1:51918        127.0.0.1:51917        ESTABLISHED     6080
  TCP    127.0.0.1:51919        127.0.0.1:51920        ESTABLISHED     6080
  TCP    127.0.0.1:51920        127.0.0.1:51919        ESTABLISHED     6080
  TCP    127.0.0.1:51921        127.0.0.1:51922        ESTABLISHED     6080
  TCP    127.0.0.1:51922        127.0.0.1:51921        ESTABLISHED     6080
  TCP    127.0.0.1:51923        127.0.0.1:51924        ESTABLISHED     6080
  TCP    127.0.0.1:51924        127.0.0.1:51923        ESTABLISHED     6080
  TCP    127.0.0.1:51925        127.0.0.1:51926        ESTABLISHED     6080
  TCP    127.0.0.1:51926        127.0.0.1:51925        ESTABLISHED     6080
  TCP    127.0.0.1:51927        127.0.0.1:51928        ESTABLISHED     6080
  TCP    127.0.0.1:51928        127.0.0.1:51927        ESTABLISHED     6080
  TCP    127.0.0.1:51929        127.0.0.1:51930        ESTABLISHED     6080
  TCP    127.0.0.1:51930        127.0.0.1:51929        ESTABLISHED     6080
  TCP    127.0.0.1:51931        127.0.0.1:51932        ESTABLISHED     6080
  TCP    127.0.0.1:51932        127.0.0.1:51931        ESTABLISHED     6080
  TCP    127.0.0.1:51933        127.0.0.1:51934        ESTABLISHED     6080
  TCP    127.0.0.1:51934        127.0.0.1:51933        ESTABLISHED     6080
  TCP    127.0.0.1:51935        127.0.0.1:51936        ESTABLISHED     6080
  TCP    127.0.0.1:51936        127.0.0.1:51935        ESTABLISHED     6080
  TCP    127.0.0.1:51937        127.0.0.1:51938        ESTABLISHED     6080
  TCP    127.0.0.1:51938        127.0.0.1:51937        ESTABLISHED     6080
  TCP    127.0.0.1:51939        127.0.0.1:51940        ESTABLISHED     6080
  TCP    127.0.0.1:51940        127.0.0.1:51939        ESTABLISHED     6080
  TCP    127.0.0.1:51941        127.0.0.1:51942        ESTABLISHED     6080
  TCP    127.0.0.1:51942        127.0.0.1:51941        ESTABLISHED     6080
  TCP    127.0.0.1:51943        127.0.0.1:51944        ESTABLISHED     6080
  TCP    127.0.0.1:51944        127.0.0.1:51943        ESTABLISHED     6080
  TCP    127.0.0.1:51945        127.0.0.1:51946        ESTABLISHED     6080
  TCP    127.0.0.1:51946        127.0.0.1:51945        ESTABLISHED     6080
  TCP    127.0.0.1:51947        127.0.0.1:51948        ESTABLISHED     6080
  TCP    127.0.0.1:51948        127.0.0.1:51947        ESTABLISHED     6080
  TCP    127.0.0.1:51949        127.0.0.1:51950        ESTABLISHED     6080
  TCP    127.0.0.1:51950        127.0.0.1:51949        ESTABLISHED     6080
  TCP    127.0.0.1:51951        127.0.0.1:51952        ESTABLISHED     6080
  TCP    127.0.0.1:51952        127.0.0.1:51951        ESTABLISHED     6080
  TCP    127.0.0.1:51953        127.0.0.1:51954        ESTABLISHED     6080
  TCP    127.0.0.1:51954        127.0.0.1:51953        ESTABLISHED     6080
  TCP    127.0.0.1:51955        127.0.0.1:51956        ESTABLISHED     6080
  TCP    127.0.0.1:51956        127.0.0.1:51955        ESTABLISHED     6080
  TCP    [::]:135               [::]:0                 LISTENING       612
  TCP    [::]:445               [::]:0                 LISTENING       4
  TCP    [::]:5357              [::]:0                 LISTENING       4
  TCP    [::]:7680              [::]:0                 LISTENING       896
  TCP    [::]:49408             [::]:0                 LISTENING       400
  TCP    [::]:49409             [::]:0                 LISTENING       836
  TCP    [::]:49410             [::]:0                 LISTENING       896
  TCP    [::]:49411             [::]:0                 LISTENING       1068
  TCP    [::]:49412             [::]:0                 LISTENING       472
  TCP    [::]:49435             [::]:0                 LISTENING       480
  TCP    [::]:51809             [::]:0                 LISTENING       5256
  UDP    0.0.0.0:500            _:_                                    896
  UDP    0.0.0.0:3544           _:_                                    896
  UDP    0.0.0.0:3702           _:_                                    904
  UDP    0.0.0.0:3702           _:_                                    904
  UDP    0.0.0.0:3702           _:_                                    844
  UDP    0.0.0.0:3702           _:_                                    844
  UDP    0.0.0.0:3702           _:_                                    1992
  UDP    0.0.0.0:3702           _:_                                    1992
  UDP    0.0.0.0:4500           _:_                                    896
  UDP    0.0.0.0:5353           _:_                                    540
  UDP    0.0.0.0:5355           _:_                                    540
  UDP    0.0.0.0:59406          _:_                                    844
  UDP    0.0.0.0:59408          _:_                                    904
  UDP    0.0.0.0:63961          _:_                                    1992
  UDP    10.0.2.15:137          _:_                                    4
  UDP    10.0.2.15:138          _:_                                    4
  UDP    10.0.2.15:1900         _:_                                    844
  UDP    10.0.2.15:59412        _:_                                    844
  UDP    10.0.2.15:61549        _:_                                    896
  UDP    127.0.0.1:1900         _:_                                    844
  UDP    127.0.0.1:59413        _:_                                    844
  UDP    [::]:500               _:_                                    896
  UDP    [::]:3702              _:_                                    904
  UDP    [::]:3702              _:_                                    1992
  UDP    [::]:3702              _:_                                    844
  UDP    [::]:3702              _:_                                    844
  UDP    [::]:3702              _:_                                    1992
  UDP    [::]:3702              _:_                                    904
  UDP    [::]:4500              _:_                                    896
  UDP    [::]:5353              _:_                                    540
  UDP    [::]:5355              _:_                                    540
  UDP    [::]:59407             _:_                                    844
  UDP    [::]:59409             _:_                                    904
  UDP    [::]:63962             _:_                                    1992
  UDP    [::1]:1900             _:_                                    844
  UDP    [::1]:59411            _:_                                    844
  UDP    [fe80::14e8:2b00:2b5d:5491%4]:546  _:_                                    836
  UDP    [fe80::4c30:865b:b6e0:a0b3%5]:546  _:_                                    836
  UDP    [fe80::4c30:865b:b6e0:a0b3%5]:1900  _:_                                    844
  UDP    [fe80::4c30:865b:b6e0:a0b3%5]:59410  _:_                                    844
PS C:\Windows\system32>

**Comment by glindroth** [comment]
Sorry saw that there were properties for host and port as well. Trying with those as well now

**Comment by glindroth** [comment]
After commenting out the host and port properties I am getting this error:

PS C:\Windows\system32> 'C:\neo4j-1\neo4j-enterprise-2.3.0-RC1\' | Start-Neo4jShell -Console -Wait -Verbose
Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Int32".
At C:\neo4j-1\neo4j-enterprise-2.3.0-RC1\bin\Neo4j-Management\Start-Neo4jShell.ps1:122 char:99
+ ... ) -and ($_.Name -eq 'remote_shell_port')) { $Port = [int]($_.Value) }
+                                                 ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : ConvertToFinalInvalidCastException

**Comment by glennsarti** [comment]
It thinks there are multiple `remote_shell_port=xxx` lines in your config file
Also the `-Console` is not required.  Only applicable for Start-Neo4jServer and Arbiter

Have you tried using the batch file neo4jshell.bat to rule out that it's the server that's causing the issue, not the client powershell code?

**Comment by glindroth** [comment]
Yes! I saw that the properties file was a mess. There was a remote_shell_enabled=false at the bottom. Once I commented out that and ensured there was only one reference of remote_shell_port set to 1337 the shell started nicely.

Sorry about the mess. But on the other hand I guess the fact that I am new to all of this is a good testing exercise..

I think this issue needs no further work.

**Comment by glennsarti** [comment]
I found some minor things wrong with that function (Missing Write-Verbose and missing aliases for Port and Host)

**Comment by glindroth** [comment]
OK, is there also a way to give something more than connection refused as feedback?

**Comment by glennsarti** [comment]
The Connection Refused is coming the Neo4j Console java code, not powershell. As far as PS is concerned, it started the java app, no problem.

**Comment by glindroth** [comment]
ok I understand
