### ISSUE TITLE
[Powershell] - Example with 3-node cluster fails on Windows 10

### ISSUE THREAD

**Issue by glindroth** [neo4j/neo4j#5532]
Tried the following example:

Create a three node cluster on the local computer. This example assumes three installations of the Enterprise version of Neo4j installed at C:\Neo4j-1,C:\Neo4j-2 and C:\Neo4j-3.

On Windows 10.
- Sometimes only first instance was started. Sometimes only 2 instances (either second or third).
- The instance that is not started gets the content of the db deleted on disk.

Error messages attached.
![screen shot 2015-10-05 at 09 36 40](https://cloud.githubusercontent.com/assets/12694230/10275062/b46bc25e-6b44-11e5-9627-f6dce4e251a3.png)

**Comment by glindroth** [comment]
@glennsarti - Please look at this as soon as you can. May be 2.3 release blocking.

**Comment by glindroth** [comment]
Cannot reproduce in consecutive runs. Must have screwed up my environment somehow.  Not 2.3 release blocking for now.

**Comment by jakewins** [comment]
@glindroth if you don't mind, I'm going to close this ticket for now - please reopen if you disagree or if you're able to replicate the issue.
