### ISSUE TITLE
[Powershell] - Start-Neo4jServer is not working

### ISSUE THREAD

**Issue by glindroth** [neo4j/neo4j#5533]
On Windows 10 - When running the examples stated on http://neo4j.com/docs/snapshot/powershell.html (under header Basic Examples ) Example1 (Start-Neo4jServer without any other arguments) does not work. Example 2 works.
![screen_shot_2015-10-05_at_09 38 49](https://cloud.githubusercontent.com/assets/12694230/10275198/e864c21c-6b45-11e5-941a-03edf933857d.png)

**Comment by glindroth** [comment]
@glennsarti - Please look at this as soon as possible. Could be 2.3 blocking.

**Comment by glindroth** [comment]
Further testing shows that an Install is required. This should be clearer in the documentation. This issue is not blocking for 2.3.

**Comment by glennsarti** [comment]
Example1 - It expects that Neo4j has already been installed as a Windows Service (with Install-Neo4jServer).  It seems that Neo4j has never been installed as a service (Could not find service....)

Example 2 - The example uses `-Console -Wait` whereas your command does not.  Therefore it tried to start a Windows Service by default.  Same error as Example 1

**Comment by glennsarti** [comment]
I can update the help text for example 1 saying it assumes that the Windows Service is installed

**Comment by glindroth** [comment]
OK great thanks.
