### ISSUE TITLE
[Powershell] - Get-Neo4jHome / Get-Neo4jServer is not working

### ISSUE THREAD

**Issue by glindroth** [neo4j/neo4j#5536]
If running Get-Neo4jServer without arguments the documentation stated that this command will be run for whatever Get-Neo4jHome returns.

As seen in attached image this does not work.
![screen_shot_2015-10-05_at_11 08 47 1](https://cloud.githubusercontent.com/assets/12694230/10279405/c7151880-6b65-11e5-81e9-9b034d439d03.png)

**Comment by glindroth** [comment]
@glennsarti - please look at this issue - this one and https://github.com/neo4j/neo4j/issues/5531 has highest priority

**Comment by glennsarti** [comment]
@glindroth 
Is this the wrong screen shot? It only shows Start-Neo4jServer not Get-Neo4jServer

**Comment by glindroth** [comment]
@glennsarti Sorry, correct screenshot uploaded now.

**Comment by glennsarti** [comment]
Was the `NEO4J_HOME` environment variable set?

If not it can't detect the neo4j installation path.

**Comment by glindroth** [comment]
Hmm is this something provided when using the desktop installer? In our examples we have simply unzipped the zip file retrieved from packaging. Do we need to set that env variable also in the case of not using the installer?

**Comment by glennsarti** [comment]
You only need the Env Var if you're not explicitly tell the script where the neo4j installation is.  I did toy with the idea of defaulting to the location of the Neo4j Powershell script.

**Comment by glindroth** [comment]
Is there anything stated about the NEO4j_HOME env variable somewhere in the documentation? I was not aware of its existence. But then again I am doing this as a complete layman and users that work with this have more insight than I have?

**Comment by glennsarti** [comment]
Reference: http://neo4j.com/docs/stable/server-installation.html#windows-console

**Comment by glindroth** [comment]
OK if that is the entry point for all powershell users then I am content with that. If there is a way to state somewhere (either in examples or help texts) that this env variable needs to be set I would be even more content :)

**Comment by glennsarti** [comment]
I can reference that URL in the help text.  I can also mention that the env var is only required if the path is not explicitly set

**Comment by glennsarti** [comment]
As a "feature request" I'd like to add the following to Get-Neo4jHome;

Detect a neo4j install in the current working directory
Detect a neo4j install from the root of the invoked powershell script

Implementation at a later date.

**Comment by glindroth** [comment]
OK great thank you.
