### ISSUE TITLE
Cypher not processing mixed number types in array well

### ISSUE THREAD

**Issue by whitfa99** [neo4j/neo4j#5565]
This doesn't work:

WITH [1, 1.01] as numbers
RETURN [n in numbers|round(n)] as round_of_numbers

returns:  expected Float but was Number

**Comment by cleishm** [comment]
Hi @whitfa99,

You have a collection of mixed number types (`Integer` and `Float`), which gets treated as the type-in-common `Number`. The function `round(...)` expects `Float` input, and returns a `Float`.

So you have two choices:

1) Write the collection to contain all `Float` values, e.g. `WITH [1.0, 1.01] ...`
or
2) Use `toFloat(...)`, e.g. `RETURN [n in numbers|round(toFloat(n))] ...`

Hope that helps!

Cheers,
Chris
