### ISSUE TITLE
Batch execute CREATE statements in Cypher / Neo4j

### ISSUE THREAD

**Issue by pangguoming** [neo4j/neo4j#5587]
I have a file that contains about 2,000 statements like this :
CREATE (station_1:STATION {id:1,name:"Tercer Milenio",description:"Av. Caracas entre calles 7bis y 6",latitude:4.597835,longitude:-74.084126,line:"A"})
CREATE UNIQUE (station_48)-[:B94 { line:"D", bus:"B94" } ]->(station_15)

I want to import them in my local neo4j server; when I copy that all statements into web console to excute . but it return error: Neo.DatabaseError.General.UnknownFailure

how to deal with this problem ?

**Comment by pangguoming** [comment]
or can you please tell how to export the whole database from window version to  the neo4j ubuntu version?

**Comment by jexp** [comment]
shut down your server on both systems

copy the graph.db directory contents to data/graph.db on linux
start server on linux

**Comment by pangguoming** [comment]
yes,  i know that way.
on windows it is 'default.graphdb' folder. i copy that folder to ubuntu and rename the folder name: 'graph.db'.
but when i restart neo4j on ubuntu, it failed to reboot

**Comment by jexp** [comment]
please ask in the google group or on stackoverflow, this is a bugtracker for Neo4j :)
if you do please share the graph.db/messages.log, it's probably a permission issue

**Comment by pangguoming** [comment]
thanks a lot , i did it one more time and success.
