### ISSUE TITLE
Limitations and Scalability down the line

### ISSUE THREAD

**Issue by corporatepiyush** [neo4j/neo4j#5590]
I wanted to adopt neo4j community edition for one of my new project. Its datasize will grow exponentially after say couple of years. I could not able to find an answer for  couple of questions in terms of limitations and scalability so asking them here.
1. As mentioned in the http://neo4j.com/docs/stable/capabilities-capacity.html max nodes is limited to 2 ^ 35. are there any ways to mitigate this limitation with v2.2.5  ? or at least would it change in near future (in less than 2 years) to a greater value ?
2. Is it safe to rely on or use neo4j embedded API or is it frequently changing on every release . will there be drastic changes in API in near future.
3. In neo4j enterprise edition, is it possible to use neo4j as embedded and master-slave clustering mode. If yes how much is the maximum nodes allowed ?

**Comment by corporatepiyush** [comment]
Where is the explanation for this ? Is that how you guys go on closing the
issues ?

**Comment by jexp** [comment]
You cross posted to the google group, I answered there. 
This is a issue tracker for Neo4j, not a discussion forum :)

**Comment by corporatepiyush** [comment]
Cool thanks
