### ISSUE TITLE
how can i get Shortest Path cypher query?

### ISSUE THREAD

**Issue by pangguoming** [neo4j/neo4j#5600]
I created a Neo4j database with the cypher statement here:https://gist.github.com/neoecos/8748091

i want to know : how to get : 1.less Transfer Paths (order by transfer) 2.the Shortest Path （order by path length) 3.the optimal Path (less Transfer and the Shortest Path)

please give the corresponding query. And do you think that is the best way to create a Bus inquiry system？ Thanks a lot.

**Comment by jexp** [comment]
Please post the question to our google group or stackoverflow as it might cause a longer discussion.
GitHub issues is an bug/issue tracker. Not a discussion forum :)
