### ISSUE TITLE
Merging nodes with unique constraints does not respect label pattern

### ISSUE THREAD

**Issue by cornerman** [neo4j/neo4j#5631]
```
neo4j-sh (?)$ create constraint on (n:TEST) assert n.title is unique;
+-------------------+
| No data returned. |
+-------------------+
Unique constraints added: 1
262 ms
neo4j-sh (?)$ create (test:TEST:A {title : "test"});
+-------------------+
| No data returned. |
+-------------------+
Nodes created: 1
Properties set: 1
Labels added: 2
322 ms
neo4j-sh (?)$ merge (test:TEST:B {title : "test"}) return labels(test);
+--------------+
| labels(test) |
+--------------+
| ["TEST","A"] |
+--------------+
1 row
202 ms
```

The expected output of the last command would be to throw a `Unique constraint violation`. But instead, it wrongly matches the previously created node with labels `"TEST" and "A"`.

I tried with neo4j version 2.2.2 and version 2.3.0-M03.

**Comment by jexp** [comment]
MERGE never causes a unique constraint violation.
CREATE would.

MERGE just uses your constraint, it is a get-or-create operation.

**Comment by cornerman** [comment]
@jexp I am not sure, I can follow your explaination. The last merge command should match or create a node with labels `TEST` and `B`, but actually returns a node with labels `TEST` and `A` - this is wrong. Without a constraint the merge command would create a new node with the correct labels.

**Comment by jexp** [comment]
The constraint is only valid for its label + property pair.

You're right MERGE should at least check for also the `:B` label.

**Comment by cornerman** [comment]
Thanks for the fast response.

I think the central question is: **Does MERGE guarantee, that it returns exactly what was requested?**

If the answer is yes, then MERGE needs to throw an error because - respecting the constraint - it cannot return what was requested.

In this example, the unique constraint is valid for the label `TEST` and the property `title`. So there is no way the merge command can succeed. As there is no node that matches the pattern and creating a new node is not possible because otherwise there would be two nodes with label `TEST` and the same title (violating the constraint). So, the merge command would need to throw a `unique constraint violation`, right?

**Comment by systay** [comment]
Yes, that's right. Your query should result in a failure - no matching node can be found, and no node can be created to match the given description. Pontus' fix checks exactly that. 

Thanks for alerting us to this problem!
