### ISSUE TITLE
[2.3.0-RC1] [Browser] Schema command not working

### ISSUE THREAD

**Issue by ikwattro** [neo4j/neo4j#5636]
Using 2.3.0 RC1. Typing `:schema` in the browser never ends. Works pretty fast in the shell.

Seems like due to a 404 error to the console endpoint : 

![capture d ecran 2015-10-15 a 02 04 35](https://cloud.githubusercontent.com/assets/1222009/10501385/2cd6308c-72e1-11e5-82eb-7305608231bb.png)

**Comment by jexp** [comment]
Probably due to the removal of webadmin, the http shell endpoint is then gone.

**Comment by akollegger** [comment]
An inadvertent change to defaults has caused webadmin (and by extension, the console endpoint) to be disabled by default. We'll correct that. 

In the meantime, add `dbms.webadmin.enabled=true` to `conf/neo4j-server.properties`.

Apologies,
Andreas

**Comment by ikwattro** [comment]
Thanks for the config tip @akollegger . No need to apologize ;-)

**Comment by oskarhane** [comment]
Fixed with https://github.com/neo4j/neo4j/issues/5640.
