### ISSUE TITLE
Wrong match results if two variables bind to the same node

### ISSUE THREAD

**Issue by BGehrels** [neo4j/neo4j#564]
If my graph looks like this:

    (1)-[:L1]->(2)

i would expect

    START
        n=node(1),
        m=node(1)
    MATCH m-[:L1]->x<-[:L1]-n
    RETURN x.name AS x

to return

    x = node(2)

Instead, it returns an empty result. This may even be a feature, not a bug, but it should then be explicitly documented somewhere.

But i would propose not to call this a feature: If i would have wanted both edges to differ, i would have added a

    rel1 != rel2

condition.

**Comment by jakewins** [comment]
Cypher does not allow binding the same node to multiple identifiers, this is an explicit design choice which significantly limits the complexity of writing queries. Cypher today should throw an exception for the query above.
