### ISSUE TITLE
HTTP authentication feedback

### ISSUE THREAD

**Issue by escitalopram** [neo4j/neo4j#5660]
This issue is partly a response to https://github.com/neo4j/neo4j/issues/4140#issuecomment-77749778
I opened a new issue, because this is not about the missing `Content-Type` header, but about the casually mentioned issue with the malformed `WWW-Authenticate` header.

In case you haven't noticed: Your refusal to correctly implement HTTP Authentication leads to all kinds of odd behaviors, for example:

If I want to test a server extension in my browser, by using a URL like
http://localhost:7474/examples/unmanaged/example/blah
the browser (and any other sane HTTP user agent) will not ask for a password, because there is no valid auth challenge. So how should I authenticate?

Even worse, when I use a URL
http://neo4j:blah@localhost:7474/examples/unmanaged/example/blah
The user agent (tested with current firefox and wget) will not send the credentials, but first try to provoke the server to produce an authentication challenge. It then finds that the server does not even support Basic auth and will send NO authentication at all, and I'm still not authenticated.

The only way your confused implementation of HTTP Authentication can work at all is if the user agent »optimizes out« the request to find out about the supported auth schemes (which is allowed for the user agent as per https://tools.ietf.org/html/rfc7235#section-4.1). However, when you send 401 errors, you MUST specify at least one challenge (specified in the same chapter). If you don't want users to authenticate, you should send 403, but obviously, you do want them to. And if you want any interoperability with popular user agents at all, you'd better use well known, IANA-registered challenges (http://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml) instead of the unregistered `None`.

If you don't want the browser to authenticate, instead of this mess, you could as well have implemented a `X-Neo4j-Authentication`-header, the interoperability would have been the same (you can do that with AJAX, but no standards compliant user agent will ever support it out of the box) and the limitation would have been more obvious, saving your user base the protocol debugging.

An obvious way to use HTTP authentication with a web application is to authenticate the index page. All subsequent AJAX calls and whatnot will use the same authentication in the same Realm, so no popups, unless you change the credentials on the server.

Furthermore, if you want any kind of scalable authentication (e.g. using an external LDAP server), it would be a good idea to not force the server to authenticate every single request, but allow the user to authenticate a session, also. This would also be the preferred solution for authenticating a webapp anyway, because there is an interoperable way to log out.

Also, if you want a more specific way to prevent AJAX queries from popping up password dialogs, you could, as a compromise, detect the `X-Requested-With` request header and use its value to determine whether you want to send a valid 401 or… the current solution. (But I still think there might be some circumstances where the current behavior might knock out even AJAX requests.)

**Comment by cleishm** [comment]
Thank you for providing valuable feedback. We've discussed some options to provide more obvious behavior wrt the `WWW-Authenticate` header, and we have some ideas to do so.

Obviously the most important things to ensure that browsers using javascript do not popup password dialogs, as that would break the typical browser experience. This is why it was developed in the way it currently is. And whilst that may be problematic in some cases, it's not broken or non-compliant according the the RFCs. It simply requires that user agents explicitly set the Authorization header based on credentials provided in advance by the user, which has proven to be no problem for the majority of user agents.

That said, we're considering providing a mechanism for returning `WWW-Authenticate: None` only for javascript requests from browsers. We haven't implemented anything such at this time, and we still need to determine the best way to identify such requests. We may just do it via a custom header in the request (`X-No-Authorization-Negotiation: true` or similar). How about that idea?

**Comment by escitalopram** [comment]
Yes, I think that is a good idea to explicitly request the »surprising« behavior using its own request header. That's even better than detecting `X-Requested-With`.

**Comment by jakewins** [comment]
@escitalopram just a heads up that this is tracked in a backlog internally, we'll update this ticket once we've resolved these issues.
