### ISSUE TITLE
i can not add an Two dimensional array property to a relationship

### ISSUE THREAD

**Issue by pangguoming** [neo4j/neo4j#5662]
i test Two dimensional array like:
RETURN [[0,1],[2,3],[4,5],[6,7],[8,9]] AS collection
it works.

but , when i try to add an Two dimensional array property to a relationship like:
MATCH (station_44:STATION {id:44}), (station_38:STATION {id:38}) CREATE UNIQUE (station_44)-[:test2 { path:[[1,2],[2,3],[3,4]] } ]->(station_38)
I get error: Collections containing mixed types can not be stored in properties.

How can i do it? is it  a bug?

**Comment by jexp** [comment]
Neo currently only supports single dimensional arrays.

You can either serialize it as json-string

Or you could create a one-dimensional array of  length + data entries.
Or if you have a fixed sub-length of 2, you can also just flatten the array.

**Comment by pangguoming** [comment]
ok, thanks
