### ISSUE TITLE
[2.3.0-RC1][Rest API] BC when listing labels - /labels endpoint

### ISSUE THREAD

**Issue by ikwattro** [neo4j/neo4j#5665]
I know it's sunday :) 

I guess it is related to the fact that unused labels are removed.

There is a slight BC when listing labels with the `/db/data/labels` endpoint : 
1. Fresh new install of neo
2. Create a new index : `CREATE INDEX ON :TestNode(id);`
3. Try to list labels : `GET http://localhost:7474/db/data/labels`

Returns an empty body, in 2.2.6 it is returning the `TestNode` label.

This has as side effect that you can not list all indexes of the database from a driver without passing by the `/manage/server/console/` endpoint, which is anyway inadvertently disabled in RC1.

I personally don't think that not listing the label is an `issue` but rather there is a BC for the `labels` endpoint which might affect other users or drivers.

Cheers

Chris

**Comment by oskarhane** [comment]
Hi @ikwattro, thanks for the report / heads up on this.  
You can still fetch all labels like before, by passing the query param `in_use=0`, like `:GET /db/data/labels?in_use=0`.  

And regarding the disabled `/manage/server/console/`, that is fixed and will be in the next release. 

Cheers

**Comment by ikwattro** [comment]
Thanks Oscar,

I wasn't aware of this param. Thanks.

Cheers

On 19 October 2015 at 08:54, Oskar Hane notifications@github.com wrote:

> Hi @ikwattro https://github.com/ikwattro, thanks for the report / heads
> up on this.
> 
> You can still fetch all labels like before, by passing the query param
> in_use=0, like :GET /db/data/labels?in_use=0.
> 
> And regarding the disabled /manage/server/console/, that is fixed and
> will be in the next release.
> 
> Cheers
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/neo4j/neo4j/issues/5665#issuecomment-149119733.

## 

Christophe Willemsen | Graph Aware Limited

Phone: +44 (0) 333 444 7274 | Mobile: +32 (0) 489 687 208
christophe@graphaware.com | @graph_aware | www.graphaware.com

**Comment by ikwattro** [comment]
@oskarhane Maybe I can close this issue and make a PR for the documentation instead ?
