### ISSUE TITLE
webinterface

### ISSUE THREAD

**Issue by flip111** [neo4j/neo4j#5666]
The webinterface is beautiful, some suggestions that might improve it:
- Make the view more compact (or make it an option) so more queries fit in the history.
- When having many pinned queries you don't see the last query result. Perhaps this could be two scrollable area's with the pinned queries in the bottom area.
- Syntax highlighting for executed queries (on the top of the result box)

**Comment by oskarhane** [comment]
Thanks for the improvement suggestions @flip111, good points!  
A more compact view would definitely improve the experience for those with smaller screens.  

I'll note these so we have them in consideration for future updates.
