### ISSUE TITLE
MERGE and CREATE UNIQUE

### ISSUE THREAD

**Issue by Sally-Yang-Jing-Ou** [neo4j/neo4j#5672]
Hello Neo4j,
I've been looking everywhere but I couldn't find a definite answer to the 'difference between MERGE and CREATE UNIQUE'. I've figured it'd be best to ask the developers directly :) 

http://neo4j.com/blog/new-milestone-release-neo4j-2-0-0-m03/ seems to suggest MERGE has replaced CREATE UNIQUE, but http://neo4j.com/docs/stable/query-create-unique.html suggests that "MERGE might be what you want to use instead of CREATE UNIQUE. Note however, **that MERGE doesn’t give as strong guarantees for relationships being unique**." Which explanation is more reliable?

Question: Can I just use MERGE?

**Comment by maxsumrall** [comment]
Answer: Yes, you can probably just use MERGE, but it depends on what you would like to achieve. If you want further help in writing applications, feel free to post to StackOverflow or the public Neo4j-slack group. 

http://stackoverflow.com/questions/tagged/neo4j
http://neo4j.com/blog/public-neo4j-users-slack-group/

http://neo4j.com/docs/stable/query-merge.html
http://neo4j.com/docs/stable/query-create-unique.html
