### ISSUE TITLE
Change configuration to start binding 0.0.0.0 keep sayng localhost on console

### ISSUE THREAD

**Issue by antonini** [neo4j/neo4j#5682]
I changed my `neo4j-server.properties` to bind the server listening to `0.0.0.0`.

When I execute: `$ neo4j start`, Neo4J keeps me saying that it is available over `http://localhost:7474`.

**Comment by benbc** [comment]
Hello @antonini. Can you tell me which version of Neo4j you are using? Could you please verify whether it is actually binding `localhost`, or whether it is just a logging problem? Could you post here the configuration fragment you are using to change the address, please?

**Comment by antonini** [comment]
@benbc It's just a logging problem. I was using Neo4J 2.2.6.

**Comment by benbc** [comment]
Thank you. And thanks for reporting this.

**Comment by benbc** [comment]
@antonini The fix for this will be in 3.0.

**Comment by antonini** [comment]
@benbc Thanks!
