### ISSUE TITLE
For mathematics  function , there is no 'power' function?

### ISSUE THREAD

**Issue by pangguoming** [neo4j/neo4j#5688]
For mathematics  function , there is no 'power' function?

**Comment by cleishm** [comment]
Hi @pangguoming,

This github issue tracker is for reporting specific bugs and issues in Neo4j. If you have questions on usage, I suggest it's better to use stackoverflow: http://stackoverflow.com/questions/tagged/neo4j

However, I can answer your question this time: the "power" function is available using the `^` operator (e.g. `8 ^ 2`).

Cheers,
Chris

**Comment by pangguoming** [comment]
ok, thanks, i got it
