### ISSUE TITLE
Let Cypher return subgraphs

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#57]
@peterneubauer: 'See https://gist.github.com/1171908 for a proposed representation, even http://groups.google.com/group/neo4j/browse_thread/thread/aae7068526e35c55/a8d9d3245e979fc7?lnk=gst&q=most+efficient#a8d9d3245e979fc7 for discussion.'

**Comment by boggle** [comment]
This is being worked on as part of Cypher 10 and GQL.
