### ISSUE TITLE
[2.2.3] Legacy Index setCacheCapacity missing in

### ISSUE THREAD

**Issue by joewhite86** [neo4j/neo4j#5703]
The method to set the index cache capacity is missing in 2.2.3 to 2.2.6.

I wonder how we should set the capacity now, since the documentation is outdated here: http://neo4j.com/docs/stable/indexing-lucene-extras.html

**Comment by chrisvest** [comment]
There is currently no way to set a cache capacity for legacy index lookups. It's very likely not something that we are going to add back.

**Comment by joewhite86** [comment]
Alright, I thought so, just wanted to note that it's still in the docs.

**Comment by chrisvest** [comment]
Yeah, we'll get the docs fixed, thanks.
