### ISSUE TITLE
cypher-neo4j 2.3, "Supported CypherVersion values are: 1.9, 2.2, 2.3"

### ISSUE THREAD

**Issue by tbaum** [neo4j/neo4j#5710]
I would expect  the last 3 versions here (2.1, 2.2 and  2.3). 

Is this a bug or by intention?

**Comment by craigtaverner** [comment]
I believe the policy is to support the previous minor release, and the last release of the previous major version. That would be 2.2 and 1.9 respectively, making this by intention, not a bug.
