### ISSUE TITLE
Feature request: Create connections in the console using the mouse

### ISSUE THREAD

**Issue by Joshfindit** [neo4j/neo4j#5713]
If drag-and-drop is functional:
- Clicking on a node, then dragging to another node shows an indicator that there will be a connection (for example, a low-opacity connection arrow)
- On mouse release, a dialog comes up for a label.
- When enter is pressed in the dialog, the connection is made with the dialog entry as the label

If drag-and-drop is not functional:
- Clicking on a node selects it
- Clicking on a node while pressing a modifier key brings up a dialog that asks for a label
- When enter is pressed in the dialog, the connection is made with the dialog entry as the label

In both cases, the user would expect that the connection is one-way starting with the first node, and directed at the second node.

**Comment by oskarhane** [comment]
This issue was moved to neo4j/neo4j-browser#140
