### ISSUE TITLE
neo4j-desktop.install4j specifies Java 1.7

### ISSUE THREAD

**Issue by plutext** [neo4j/neo4j#5723]
The Windows installer runs Neo4j using Java 7, even though 8 is installed and preferred.

I guess this is because of  <application javaMinVersion="1.7" javaMaxVersion="1.7" 
in https://github.com/neo4j/neo4j/blob/2.3/packaging/neo4j-desktop/neo4j-desktop.install4j

This causes problems with plugins compiled for 1.8.  See for example http://stackoverflow.com/questions/33325539/force-neo4j-ce-exe-2-3-0-to-use-java-8

**Comment by jexp** [comment]
It bundles Java7, so it uses the one which is bundled.

I think you would have to go with the zip download to use your own Java version.
