### ISSUE TITLE
Stop displaying additional relationships in Webapp

### ISSUE THREAD

**Issue by ahmad-musleh** [neo4j/neo4j#5728]
Hello,

I am running a command similar to:

```
MATCH p=shortestPath(
    (n1:NODE_TYPE_1)-[*]-(n2:NODE_TYPE_2{property:"xyx"})
)
RETURN p
```

Which is synonymous to retrieving the shortest path from all nodes of NODE_TYPE_1 to n2 (That have a path to n2).

I have also run a similar command along the lines of:

```
MATCH (n1:NODE_TYPE_1)-[r1]-(n2)-[r2]-(n3:NODE_TYPE_2{property:"xyx"}) 
RETURN (n1)-[r1]-(n2)-[r2]-(n3)
```

These queries work, however they also retrieve all the relationships that the intermediary nodes have (ie. alot of noise) in the webapp. I was wondering if there is a way to have the webapp not display the additional relationships between the intermediary nodes as, for now, they are irrelevant.

**Comment by jexp** [comment]
There is an autocomplete switch on the lower right

Von meinem iPhone gesendet

**Comment by ahmad-musleh** [comment]
Well that simplifies many things ... Thank you :D
