### ISSUE TITLE
DELETE statement fails

### ISSUE THREAD

**Issue by djvs** [neo4j/neo4j#5735]
```
neo4j-sh (?)$ MATCH (node)-[n]-() WHERE ID(n) = 255393 DELETE n;
null
neo4j-sh (?)$ MATCH (node)-[n]-() WHERE ID(n) = 255393 RETURN n;
+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| n                                                                                                                                                              |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| :routes[255393]{...} |
| :routes[255393]{...} |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

Maybe my database is corrupted?  I really have no idea at this point.  I have done neo4j-backup and neo4j-import in the last week to try to resolve any corruption, but am experiencing all kinds of problems like this.  Why is it returning "null"?

These same types of queries - deletes and I believe also updates - are failing on _all_ rels. 

This is urgent for us...please help!!!

**Comment by tinwelint** [comment]
Which version was this produced on?

**Comment by djvs** [comment]
This behavior was produced in the 2.3.0 currently in the Ubuntu 14.04 repos (I don't think it's any kind of milestone release).  However the database corruption I think caused it comes from a 2.2 version.

**Comment by djvs** [comment]
P.S.... (brand new rel)

```
neo4j-sh (?)$ MATCH (x)-[r]->(y) WHERE ID(r) = 305953 DELETE r;
null
neo4j-sh (?)$ MATCH (x)-[r]->(y) WHERE ID(r) = 305953 RETURN ID(r), x.uuid, y.uuid, x.title, y.title;
+----------------------------------------------------------------------------------------------------------------------------------------+
| ID(r)  | x.uuid                                 | y.uuid                                 | x.title | y.title                           |
+----------------------------------------------------------------------------------------------------------------------------------------+
| 305953 | "0e292d7a-4677-4b6b-9c06-fcb69af77579" | "00012847-38c8-45ba-b969-300bbbd63fe6" | <null>  | "Chapter 09. Pricing the product" |
+----------------------------------------------------------------------------------------------------------------------------------------+
1 row
7 ms
neo4j-sh (?)$ MATCH (x)-[r]->(y) WHERE ID(r) = 305953 DELETE r;
null
neo4j-sh (?)$ MATCH (x)-[r]->(y) WHERE ID(r) = 305953 RETURN ID(r), x.uuid, y.uuid, x.title, y.title;
+----------------------------------------------------------------------------------------------------------------------------------------+
| ID(r)  | x.uuid                                 | y.uuid                                 | x.title | y.title                           |
+----------------------------------------------------------------------------------------------------------------------------------------+
| 305953 | "0e292d7a-4677-4b6b-9c06-fcb69af77579" | "00012847-38c8-45ba-b969-300bbbd63fe6" | <null>  | "Chapter 09. Pricing the product" |
+----------------------------------------------------------------------------------------------------------------------------------------+
1 row
1
```

**Comment by djvs** [comment]
Also...

```
neo4j-sh (?)$ match (n) RETURN count(n)
> ;
+----------+
| count(n) |
+----------+
| 75156    |
+----------+
1 row
567 ms
neo4j-sh (?)$ match (n) RETURN count(n);
+----------+
| count(n) |
+----------+
| 75156    |
+----------+
1 row
222 ms
neo4j-sh (?)$ match (n)-[r]->(o) RETURN count(r);
null
neo4j-sh (?)$ match (n)-[r]->(o) RETURN count(n), count(r);
n
```

**Comment by djvs** [comment]
Apparently fixed via store-utils (100k extraneous relationships).  Or I should say, symptoms fixed.

**Comment by djvs** [comment]
Well, that operation did eliminate the strange behavior, but erased half the rels in the database.  Apparently an originally inconsistent database was broken further via the store-upgrade, producing this bug.  Bug is in the process of being hackishly resolved by Hunger's export-cypher from a backup of the 2.2.6 database, grepping for rels, and then implanting them into the store-copy'ed version of the broken 2.3 database.

**Comment by djvs** [comment]
Transplanting the rels actually _reproduced_ the problem.  An additional store copy and graph.db replacement brought us to the current "I'm pretty sure it's fixed" state (where we can no longer apparently produce the "null" results, and have at least most of our database there).

**Comment by Mats-SX** [comment]
@djvs Am I correct in assuming that you are no longer suffering from this issue anymore?

My take on the history here is that the behaviour of `DELETE` was wrong not because of a planner/runtime error in Cypher, but because the underlying store was corrupted. Do you agree that this seems likely?

**Comment by djvs** [comment]
It's hard to be sure...I did a full run through of this store through jexp's store-utils, which apparently solved the problem, but then I did get another null on relationship select later, possibly triggered by a massive number of relationship inserts.

**Comment by Mats-SX** [comment]
But you have never seen this issue manifest itself on any other store but either a corrupted one or a corrupted-but-then-patched one?

**Comment by djvs** [comment]
Not sure.  Don't think so.

**Comment by Mats-SX** [comment]
Then I'll close this issue, and ascribe the erroneous behaviour to the corrupted state of the store.

Thanks a lot for reporting this issue, @djvs, and feel free to get back to it if you see something similar appear again, and we can reopen it at that point.
