### ISSUE TITLE
CSV export from neo4j-shell

### ISSUE THREAD

**Issue by boferri** [neo4j/neo4j#5751]
it would be cool, if I could execute a cypher query via neo4j-shell and export the result into a CSV file (as it is possible from the web browser or this not-that-straight-forward method described at http://neo4j.com/blog/export-csv-from-neo4j-curl-cypher-jq/)

**Comment by jexp** [comment]
You can with github.com/jexp/neo4j-shell-tools

import-cypher -o file.csv match ...

Von meinem iPhone gesendet

**Comment by boferri** [comment]
ok, thx. I'll try this one.
However, I'm wondering why you do not provide such functionality directly in neo4j tooling á la neo4j-shell?

**Comment by boferri** [comment]
it's working, but ( ;) ) the output file was located in NEO4J_HOME and why do I need to utilise an import command for this? (that's not really intuitive ;) ). just my 5p

**Comment by jexp** [comment]
You can use a fully qualified path.
