### ISSUE TITLE
/opt/local/bin/lsof: illegal option -- T

### ISSUE THREAD

**Issue by webjay** [neo4j/neo4j#576]
When I start Neo4j on SmartOS I use this script:

	#!/bin/sh

	JAVA_HOME=/opt/local/java/sun6
	export JAVA_HOME

	ulimit -n 65536

	`dirname $0`/bin/neo4j start-no-wait

That works, but I get this:

	/opt/local/bin/lsof: illegal option -- T

**Comment by jakewins** [comment]
This is now part of the `neo4j` script that we bundle in the product.
