### ISSUE TITLE
Calling `toString()` with a boolean

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4j/neo4j#5777]
Gives me the error: `Type mismatch: expected Float, Integer or String but was Boolean`

The `str` function works fine, but that's going to be deprecated, so it would be good if `toString` could take it's place in this respect

**Comment by craigtaverner** [comment]
I tested this on 2.1.8, 2.2.0, 2.2.6 and 2.3.0 and we see the same behavior on all (ie. same as what you see, str accepts boolean, but toString does not). So this is not a regression, but should still be decided on in terms of what behavior is actually desired.

**Comment by cleishm** [comment]
`toString` currently only accepts Floats, Integers and Strings (https://github.com/neo4j/neo4j/blob/3.0/community/cypher/frontend-3.0/src/main/scala/org/neo4j/cypher/internal/frontend/v3_0/ast/functions/ToString.scala#L29-L31).

Certainly the the cypher group could consider expanding that to include other types, including Boolean. Possibly it should accept `Any` and simply return an appropriate string representation (although I'm unsure what that would be in the case of complex types like Lists, Maps, Nodes and Rels).

**Comment by cheerfulstoic** [comment]
Yeah, I didn't really think it was a regression, except for the fact that `str` is able to do this currently.  So when `str` eventually goes away there won't be a way to do the same thing anymore.
