### ISSUE TITLE
Java 6 support in the 1.8.x branch

### ISSUE THREAD

**Issue by fommil** [neo4j/neo4j#5798]
I was under the impression that neo4j 2.0 was the release that deprecated Java 6 http://neo4j.com/guides/upgrade/

However, I get this when using neo4j 1.9.9 on Java 6 (this is a deployment requirement, so I cannot change Java version)

```
[info] 15:31:22.333 WARN  None o.n.k.EmbeddedGraphDatabase - You are using an unsupported version of the Java runtime. Please use Oracle(R) Java(TM) Runtime Environment 7.
```

so which version should I use?

I recommend issuing a 1.9.10 release that has been built on Java 6.

**Comment by fommil** [comment]
checking was added in 858d3cb95a108a0be59a9c8b854990dd5dd92166 but I don't see this in the release notes :cry: http://neo4j.com/release-notes/neo4j-1-9/

Looks like I need to go back to 1.8.x...

**Comment by fommil** [comment]
_sigh_ 1.8.3 doesn't work on Java 6...

```
[error] Caused by: java.lang.VerifyError: class org.neo4j.index.impl.lucene.LuceneDataSource$1 overrides final method tokenStream.(Ljava/lang/String;Ljava/io/Reader;)Lorg/apache/lucene/analysis/TokenStream;
```

this looks **nasty**.

**Comment by fommil** [comment]
oh, this looks like you're using lucene here. If I could turn off the Lucene kernel, it might start to work...

**Comment by fommil** [comment]
(I have a lucene, so this seems to be more of a lucene version mismatch than a Java problem)

**Comment by chrisvest** [comment]
It's a warning, not an error. And the release notes do actually mention this:

> Also note that Neo4j 1.9 is tested and supported with Oracle JRE 7. Users of previous Java versions should upgrade to Oracle JRE 7 when deploying Neo4j 1.9.

The keyword here is "supported," which is in the context of paying customers. 1.9.x was still built on Java6 and should still work on that version, but with 1.9 most of the testing was moved to Java7.

**Comment by fommil** [comment]
@chrisvest interesting, I got an exception when I tried. But it might be related to the Lucene mismatch. I'll try again now that I've reverted my version of Lucene to 3.5.

**Comment by fommil** [comment]
@chrisvest you're right! It works now that I've downgraded Lucene. :smile: (well, that's not too great, but it is good enough)

**Comment by fommil** [comment]
actually I was depending on `neo4j-kernel` before now I'm depending on everything. I'm confused what the minimal dependency is for embedded use.
