### ISSUE TITLE
Shortest path does not correctly solve all predicates

### ISSUE THREAD

**Issue by tomzeppenfeldt** [neo4j/neo4j#5803]
With the possibility to include `WHERE` predicates that are taken into account in the `shortestPath()` function, the next obvious thing would be to limit the path length in a construct like:

`with x as lower, y as upper`
`match p=(n)-[*lower..upper]->(m)`

or (perhaps suboptimal, depending when the predicate is included in the evaluation)

`match p=(n)-[*]->(m)`
`where lower <= length(p) <= upper`

I have a specific usecase where I need to find the shortest path that includes an arbitrary list of waypoints, and even start and finish can be any of the nodes. For this, I would, for every combination of start-finish nodes, evaluate the `shortestPath()` between start end end pure and simple and use its length to as lower limit for path length in the subsequent `shortestPath() ...  WHERE ..`   search of paths through the waypoints.

**Comment by Mats-SX** [comment]
Hello @ophileon 

I don't quite understand what it is you're trying to accomplish. Could you write a full query for what it is you want to do?

If what you want is to simply have a predicate on the length of the shortest path, that is possible already:

```
MATCH p = shortestPath((src:A)-[rs*]->(dst:D))
WHERE length(p) % 2 = 1 // Only uneven paths wanted!
RETURN nodes(p) AS nodes
```

**Comment by tomzeppenfeldt** [comment]
Hello @Mats-SX 
I prefer to avoid predicates, because  (at least in 2.3.0) evaluation of predicates is not 100% predictable. 

What I want to achieve is minimizing the cost of determining the shortestPath. In my specific case, I need a path that goes through n waypoints,  so shortestPath less then length n do not need to be looked for.

the enclosed file illustrated this further, and also provides a case illustrating the  imperfection of shortestPath() combined with predicates in 2.3.0
[waypointsproblem.docx](https://github.com/neo4j/neo4j/files/35468/waypointsproblem.docx)

BTW.. the case was also provided to Michael Hunger from Neo4j

**Comment by systay** [comment]
Hi Tom!

This is something that you'll be able to do in 3.0 with predicates. The problem is that the shortest path algorithm that we use internally is not able to handle "shortest path that is longer than _i_" queries, so the planner will fall back on an exhaustive search for the patterns, which is pretty expensive.

**Comment by Mats-SX** [comment]
Hey @ophileon 

So what we're doing, as @systay says, is that we're fixing the actual problem, which is that our shortest path algorithm does not correctly solve predicates. We're doing so by falling back to an exhaustive Cypher-based search, which will be more expensive, but correct. That search will be able to solve predicates such as the ones you present here.

We're repurposing this issue to more directly represent what we view is the actual problem with the product here, which is the non-adherence to predicates.
