### ISSUE TITLE
Neo.DatabaseError.Statement.ExecutionFailure on match relationship

### ISSUE THREAD

**Issue by DigitalResonance** [neo4j/neo4j#5811]
This problem started happening after we upgraded from 2.2.5 to 2.3.0

We have (:User) and (:Product) Nodes in our database.
There are 3 kinds of relationships between them
[:View], [:Share], [:Buy]

We deleted the view relationships in order to recreate them from another data source.

Now I get this error "Neo.DatabaseError.Statement.ExecutionFailure" when i execute the following statements

"match (:User)-[r]->(:Product) return count(r)"      this query would previously return the count of the other relationships. This statement is used in our c# api code and fails. it also fails in the browser console.

I also get the same error when I try 

"match (:User)-[r:View]->(:Product) return count(r)"   this query would previously return 0
and 
"match (u:User)-[r]->(p:Product) return u,r,p" 
and
"optional match (:User)-[r]->(:Product) return r"

This is the error data I receive on the console. was there a problem with the upgrade and what do i do to fix it

{
  "results": [
    {
      "columns": [
        "r"
      ],
      "data": []
    }
  ],
  "errors": [
    {
      "code": "Neo.DatabaseError.Statement.ExecutionFailure",
      "message": null,
      "stackTrace": "java.lang.IndexOutOfBoundsException\n\tat org.neo4j.io.pagecache.impl.muninn.MuninnPageCursor.setOffset(MuninnPageCursor.java:419)\n\tat org.neo4j.kernel.impl.store.RelationshipGroupStore.readRecord(RelationshipGroupStore.java:143)\n\tat org.neo4j.kernel.impl.store.RelationshipGroupStore.forceGetRecord(RelationshipGroupStore.java:106)\n\tat org.neo4j.kernel.impl.api.store.StoreNodeRelationshipCursor.init(StoreNodeRelationshipCursor.java:89)\n\tat org.neo4j.kernel.impl.api.store.StoreAbstractNodeCursor.relationships(StoreAbstractNodeCursor.java:196)\n\tat org.neo4j.kernel.api.cursor.NodeItem$NodeItemHelper.getRelationships(NodeItem.java:87)\n\tat org.neo4j.kernel.impl.api.OperationsFacade.nodeGetRelationships(OperationsFacade.java:330)\n\tat org.neo4j.cypher.internal.spi.v2_3.TransactionBoundQueryContext.getRelationshipsForIds(TransactionBoundQueryContext.scala:143)\n\tat org.neo4j.cypher.internal.compiler.v2_3.spi.DelegatingQueryContext.getRelationshipsForIds(DelegatingQueryContext.scala:63)\n\tat org.neo4j.cypher.internal.compiler.v2_3.pipes.ExpandAllPipe$$anonfun$internalCreateResults$1.apply(ExpandAllPipe.scala:43)\n\tat org.neo4j.cypher.internal.compiler.v2_3.pipes.ExpandAllPipe$$anonfun$internalCreateResults$1.apply(ExpandAllPipe.scala:40)\n\tat scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:396)\n\tat scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:413)\n\tat scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:369)\n\tat org.neo4j.cypher.internal.compiler.v2_3.ClosingIterator$$anonfun$next$1.apply(ResultIterator.scala:77)\n\tat org.neo4j.cypher.internal.compiler.v2_3.ClosingIterator$$anonfun$next$1.apply(ResultIterator.scala:72)\n\tat org.neo4j.cypher.internal.compiler.v2_3.ClosingIterator$$anonfun$failIfThrows$1.apply(ResultIterator.scala:121)\n\tat org.neo4j.cypher.internal.compiler.v2_3.ClosingIterator.decoratedCypherException(ResultIterator.scala:130)\n\tat org.neo4j.cypher.internal.compiler.v2_3.ClosingIterator.failIfThrows(ResultIterator.scala:119)\n\tat org.neo4j.cypher.internal.compiler.v2_3.ClosingIterator.next(ResultIterator.scala:72)\n\tat org.neo4j.cypher.internal.compiler.v2_3.ClosingIterator.next(ResultIterator.scala:50)\n\tat org.neo4j.cypher.internal.compiler.v2_3.PipeExecutionResult.next(PipeExecutionResult.scala:77)\n\tat org.neo4j.cypher.internal.compiler.v2_3.PipeExecutionResult.next(PipeExecutionResult.scala:40)\n\tat org.neo4j.cypher.internal.compiler.v2_3.helpers.iteratorToVisitable$.accept(iteratorToVisitable.scala:35)\n\tat org.neo4j.cypher.internal.compiler.v2_3.PipeExecutionResult.accept(PipeExecutionResult.scala:114)\n\tat org.neo4j.cypher.internal.compatibility.ExecutionResultWrapperFor2_3$$anonfun$accept$1.apply$mcV$sp(CompatibilityFor2_3.scala:328)\n\tat org.neo4j.cypher.internal.compatibility.ExecutionResultWrapperFor2_3$$anonfun$accept$1.apply(CompatibilityFor2_3.scala:327)\n\tat org.neo4j.cypher.internal.compatibility.ExecutionResultWrapperFor2_3$$anonfun$accept$1.apply(CompatibilityFor2_3.scala:327)\n\tat org.neo4j.cypher.internal.compatibility.exceptionHandlerFor2_3$.runSafely(CompatibilityFor2_3.scala:114)\n\tat org.neo4j.cypher.internal.compatibility.ExecutionResultWrapperFor2_3.accept(CompatibilityFor2_3.scala:327)\n\tat org.neo4j.cypher.javacompat.ExecutionResult.accept(ExecutionResult.java:309)\n\tat org.neo4j.server.rest.transactional.ExecutionResultSerializer.writeRows(ExecutionResultSerializer.java:436)\n\tat org.neo4j.server.rest.transactional.ExecutionResultSerializer.statementResult(ExecutionResultSerializer.java:110)\n\tat org.neo4j.server.rest.transactional.TransactionHandle.executeStatements(TransactionHandle.java:330)\n\tat org.neo4j.server.rest.transactional.TransactionHandle.commit(TransactionHandle.java:147)\n\tat org.neo4j.server.rest.web.TransactionalService$2.write(TransactionalService.java:211)\n\tat com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:71)\n\tat com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:57)\n\tat com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:302)\n\tat com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1510)\n\tat com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)\n\tat com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)\n\tat com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)\n\tat com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)\n\tat com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790)\n\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)\n\tat org.neo4j.server.rest.dbms.AuthorizationFilter.doFilter(AuthorizationFilter.java:116)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)\n\tat org.neo4j.server.rest.web.CollectUserAgentFilter.doFilter(CollectUserAgentFilter.java:69)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)\n\tat org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:497)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)\n\tat org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:620)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:540)\n\tat java.lang.Thread.run(Thread.java:745)\n"
    }
  ]
}

**Comment by lutovich** [comment]
Hello @digitalresonance,

This is probably the same issue reported here https://github.com/neo4j/neo4j/issues/5691 and fixed here https://github.com/neo4j/neo4j/pull/5694. It is indeed a regression introduced in 2.3.0. Fix will be available in 2.3.1. Sorry for inconvenience.

**Comment by DigitalResonance** [comment]
Thank you for your prompt and accurate reply. May I know the estimated date when 2.3.1 will be available ?

**Comment by lutovich** [comment]
@digitalresonance I do not know the exact date but it should be out in the matter of weeks. I'll notify you about the release in this thread and only then close it.

**Comment by lutovich** [comment]
@digitalresonance version 2.3.1 with the mentioned fix was released.
