### ISSUE TITLE
Using LOG() on weights between 1 and 0 not returning desired results

### ISSUE THREAD

**Issue by ahmad-musleh** [neo4j/neo4j#5840]
Hello, 

I have a command similar to this:

```
    MATCH ()-[r]-() SET r.new_weight = -LOG(r.weight)
```

I have run that command on 2 nodes and the weight was 0 < weight < 1. However I manually checked and found that it is incorrect. They weight I tried was 0.666666667 and the value of new_weight was 0.40546510810766434 which is not the case if you take the actual log of 0.6666667 which is 0.17609... . Not being able to do this command would be costly for me as I have to query each edge and then change the log manually then reinsert into the database. The above command would be faster in my opinion, however the LOG function does not seem to provide the required output. Please note that my whole database consists of edges between 0 and 1 (Hope this is helpful).

**Comment by jexp** [comment]
You mean log10 and neo uses ln (log-e)

As you probably know you can do ln(x) / ln(10)  = log10(x)
