### ISSUE TITLE
Feature request: Connection string in HTML console

### ISSUE THREAD

**Issue by cosimosimeoneTR** [neo4j/neo4j#5842]
I found myself working with many DB installations.
When working with HTML console, it's impossible to tell which instance the browser tab is about DEV, BUILD, PROD, ...

**Comment by jakewins** [comment]
@cosimosimeoneTR what do you mean when you say "HTML console"? Are you referring to the Neo4j browser?

**Comment by cosimosimeoneTR** [comment]
Yep, exactly.
HTML title is just "neo4j", might be better something like

```
neo4j - neo4j@127.0.0.1:7474
```

as in

```
neo4j - user@host:port
```

**Comment by oskarhane** [comment]
This issue was moved to neo4j/neo4j-browser#142

**Comment by cosimosimeoneTR** [comment]
Hi there! Any news? :-)
