### ISSUE TITLE
We should set ulimit -n in the init script

### ISSUE THREAD

**Issue by txaj** [neo4j/neo4j#5849]
This bug report is focused on Debian, I did not check what's up on other distros. 

The init script uses `start-stop-daemon` :  https://github.com/neo4j/neo4j/blob/3.0/packaging/installer-linux/installer-debian/src/main/resources/common/neo4j-service#L61 

It's well known that by default, `start-stop-daemon` does not pull limits set in limits.conf ( http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=302079 )

If we don't enforce anything, the value of `ulimit -n` for the neo4j process is the same as the process invoked it. When it's an automation program (like Puppet) it's problematic. 

I propose to add the `ulimit -n 40000` in the init script, just before the call to start-stop-daemon. This is what mongodb did : https://github.com/mongodb/mongo/blob/411e9810075556fb196278a669fab0f19ea901ce/debian/init.d#L127-L131

**Comment by spacecowboy** [comment]
#7095 adds the ability to set the ulimit setting for the service. It will let you add a line in `/etc/default/neo4j`:

``` shell
NEO4J_ULIMIT_NOFILE=60000
```

**Comment by txaj** [comment]
Thanks @spacecowboy :)
