### ISSUE TITLE
Error message pointing at wrong URL

### ISSUE THREAD

**Issue by cosimosimeoneTR** [neo4j/neo4j#5885]
Hey there!
While creating fake data to try out neo4j 2.3 EE, i create a relationship file without TYPE field, so import gave me a

```
Relationship missing mandatory field 'TYPE', read more about relationship format in the manual:  http://neo4j.com/docs/2.3.0,c6c3a7b/import-tool-header-format.html#import-tool-header-format-rels
```

which is fair enough, but URL goes 404

**Comment by thobe** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;QI71ltAV&#x2F;1680-gh-5885-error-message-pointing-at-wrong-url"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> GH#5885 - Error message pointing at wrong URL</a>

**Comment by nawroth** [comment]
Fixed (see above).
