### ISSUE TITLE
Neo.TransientError.Transaction.DeadlockDetected

### ISSUE THREAD

**Issue by galbello** [neo4j/neo4j#5896]
Hello Guys,
Attaching a serious 'deadlock' issue we are currently dealing with in our production neo4j graph cluster.
We have a strong belief that it's right to assume that it is caused by an inner code bug within the neo4J platform.

Our production Neo4J cluster is up and running successfully for a while, but since yesterday the Deadlock has started showing in our log files.
At first we thought it might be due to writing new cross relationships between different entities, although, it has started only when we started running ReadOnly queries from our graph in order to present the results as recommended related links on our website.
The current state is crucial to our website and we really want to get your advice with this,  your assistance is most appreciable.
Thank You very much for your support,
Gal- uTab.com

[neo4jException.txt](https://github.com/neo4j/neo4j/files/33117/neo4jException.txt)

**Comment by jexp** [comment]
Hi Gal, can you please raise a support issue with your support account. That's better suited to deal with production issues in a timely manner.

**Comment by galbello** [comment]
Hi Jesp, Thank you for the quick response.
As a small start-up company we only have an official license for Neo4J cluster but not a support account.
Any other suggestion?
Thank You.

**Comment by jexp** [comment]
What kinds of queries are you running? Which update-queries and which read-only queries? 

Can you make sure that nodes are ordered for update operations always in the same way (e.g. by id) or you group them by subgraph so that there is no overlap.

**Comment by jakewins** [comment]
@galbello since it's been close to a month with no reply, I'm going to close this for now. Please don't hesitate to re-open and fill in the details @jexp was asking for above if the issue persists!

**Comment by gghez** [comment]
Maybe it would have been nice to explain us how this kind of error could happen? I'm facing it too and no clue for investigation.

**Comment by jakewins** [comment]
@gghez did you see the manual section on deadlocks? 

http://neo4j.com/docs/java-reference/current/#transactions-deadlocks

There's also a knowledge base article:

https://neo4j.com/developer/kb/explanation-of-error-deadlockdetectedexception-forseticlient-0-cant-acquire-exclusivelock/

If you had seen them, or if they don't help explain deadlocks for you, feel free to circle back and raise a ticket for the documentation team to improve the explanations.

**Comment by gghez** [comment]
good links thank you.
