### ISSUE TITLE
Package 'org.neo4j.unsafe.batchinsert' in neo4j-lucene-index conflicts with neo4j-kernel in OSGi

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#59]
@ceefour: 'In Karaf 3.0.0-SNAPSHOT :

```
Error executing command: Could not start bundle mvn:id.co.bippo.commerce/commerce-core/4.0.1-SNAPSHOT in feature(s) commerce-core-4.0.1-SNAPSHOT: Uses constraint violation. Unable to resolve bundle revision wrap_mvn_org.neo4j_neo4j-lucene-index_1.8.M07 [1326.0] because it exports package 'org.neo4j.unsafe.batchinsert' and is also exposed to it from bundle revision wrap_mvn_org.neo4j_neo4j-kernel_1.8.M07 [1325.0] via the following dependency chain:

  wrap_mvn_org.neo4j_neo4j-lucene-index_1.8.M07 [1326.0]
    import: (osgi.wiring.package=org.neo4j.kernel.impl.batchinsert)
     |
    export: osgi.wiring.package=org.neo4j.kernel.impl.batchinsert; uses:=org.neo4j.unsafe.batchinsert
    export: osgi.wiring.package=org.neo4j.unsafe.batchinsert
  wrap_mvn_org.neo4j_neo4j-kernel_1.8.M07 [1325.0]
```

neo4j-lucene-index should use its own package namespace, and not using the same package names (`org.neo4j.unsafe.batchinsert`)  from other JARs
'

**Comment by jakewins** [comment]
Since we do not officially support OSGi, I'm marking this as a feature rather than a bug, as well as noting the area for it. Independent of OSGi, this seems like a nice thing to clean up, we shouldn't have leaf packages split this way.

**Comment by klaren** [comment]
`neo4j-lucene-index` exposes `org.neo4j.index.lucene.unsafe.batchinsert` since a while back. I've witness neo4j running in an OSGi environment since at least version 2.2 without issues.
