### ISSUE TITLE
neo4j-shell should honor line breaks in statements in a file

### ISSUE THREAD

**Issue by obfischer** [neo4j/neo4j#5901]
Given the following Cypher statement, which is valid and can be executed via `neo4j-shell`:

```
MATCH       (a)-[r]->(b)                // <1>
RETURN     type(r)  AS relation, // <2>
                    count(r) AS count    // <3>
ORDER BY count DESC            // <4>
LIMIT           5;                            // <5>
```

If I put this statement into a file and run it `neo4-j-shell -f statement.cypher` I will get the following error message from `neo4j-shell`:

```
Warning: Exiting with unterminated multi-line input.
```

It seems so that `neo4j-shell` does not honor the line breaks in a statement file. 

I would expect that `neo4j-shell` will process the statment in the file as it does it if I enter the statment in the same form in `neo4j-shell`.

**Comment by jexp** [comment]
The problem is that // is cypher comment, but the cypher statement ends with the semicolon `;`

That's why the last piece (the comment) is not "terminated".

By moving the semicolon on the next line or adding an additional semicolon when sending the command to the shell you should avoid this issue.

**Comment by obfischer** [comment]
But the ; is in front of the comment. The parser should read the last line until the ; to read the statement. The comment after the ; can be skipped.
So I think this issue is still valid. WDYT?

**Comment by sherfert** [comment]
I think a couple of things have changed since this has been reported, but the issue is still valid, unfortunately.

When giving your file to `cypher-shell` like: `cypher-shell < ~/Downloads/comment.cypher` that works and gives results.

In `neo4j-shell`, when typing the command without comments we get the same results, with comments we get the error message you have mentioned above: `Warning: Exiting with unterminated multi-line input.` and no results.

**Comment by victoriastuart** [comment]
As explained below, I believe that this Issue also applies to cypher statements ending in semicolons that are commented out using the // preface.

This is a significant usability issue for me: when I use *.cypher scripts with Cycli, lines that I comment out in my script that terminate in a semicolon are interpreted (not ignored). 

Thus, when I am writing scripts and and I want to comment out statements that end in a semicolon with my keyboard shortcut (Neovim editor), I ALSO need to go to the end of all of those //-commented lines and delete those semicolons (reversing that tedious process when uncommenting those lines).

glycolysis.cypher:

```
LOAD CSV WITH HEADERS FROM "file:/glycolysis_bioentities.csv" AS row
MERGE (n:Glycolysis {name:row.name})
// RETURN n, labels(n), n.name;
RETURN n.name;
// Same:
// MATCH (n) RETURN n.name;
```
Script execution:

```
cycli -P 7474 -u victoria -p <password_obfuscated_here> -f glycolysis.cypher

> LOAD CSV WITH HEADERS FROM "/glycolysis_bioentities.csv" AS row
MERGE (n:Glycolysis {name:row.name})
// RETURN n, labels(n), n.name;
109 ms

> RETURN n.name;
Variable `n` not defined (line 1, column 8 (offset: 7))
"RETURN n.name;"
        ^

> // Same:
// MATCH (n) RETURN n.name;
Unexpected end of input: expected whitespace, comment, CYPHER options, EXPLAIN, PROFILE or Query (line 2, column 29 (offset: 37))
"// MATCH (n) RETURN n.name;"
                            ^

(py35) [victoria@victoria Vancouver]$ 
```

Compare that to this modified script (deleted semicolons at ends of //-commented lines):

```
LOAD CSV WITH HEADERS FROM "file:/glycolysis_bioentities.csv" AS row
MERGE (n:Glycolysis {name:row.name})
// RETURN n, labels(n), n.name
RETURN n.name;
// Same
// MATCH (n) RETURN n.name
```

Script execution:

```
cycli -P 7474 -u victoria -p <password_obfuscated_here> -f glycolysis.cypher

> LOAD CSV WITH HEADERS FROM "file:/glycolysis_bioentities.csv" AS row
MERGE (n:Glycolysis {name:row.name})
// RETURN n, labels(n), n.name
RETURN n.name;
n.name                                  
----------------------------------------
α-D-glucose                             
glucose 6-phosphate                     
fructose 6-phosphate                    
fructose 1,6-bisphosphate               
dihydroxyacetone phosphate              
D-glyceraldehyde 3-phosphate            
1,3-bisphosphoglycerate                 
3-phosphoglycerate                      
2-phosphoglycerate                      
phosphoenolpyruvate                     
pyruvate                                
hexokinase                              
glucose-6-phosphatase                   
phosphoglucose isomerase                
phosphofructokinase                     
fructose-bisphosphate aldolase, class I 
triosephosphate isomerase (TIM)         
glyceraldehyde-3-phosphate dehydrogenase
phosphoglycerate kinase                 
phosphoglycerate mutase                 
enolase                                 
pyruvate kinase                         

109 ms

```

Aside: this does not occur when loading that same .cypher script into cypher-shell: `cat glycolysis.cypher |  cypher-shell -u victoria -p <password_obfuscated_here>` -- it runs fine in cypher-shell.

**Comment by craigtaverner** [comment]
This bug is specific to `neo4j-shell` which is deprecated and replaced by `cypher-shell`.

**Comment by obfischer** [comment]
Hi @craigtaverner, does `cypher-shell` behaves differently?

**Comment by sherfert** [comment]
Yes @obfischer :

> When giving your file to `cypher-shell` like: `cypher-shell < ~/Downloads/comment.cypher` that works and gives results.

**Comment by obfischer** [comment]
Hi @sherfert, in that case we could close the issue.

**Comment by chencjiajy** [comment]
I use like :`cypher-shell -u username -p password < ~/Downloads/comment.cypher`  or `cat  ~/Downloads/comment.cypher |  cypher-shell -u username -p password` 
both commands can't get result, and there is no error. (my comment.cypher mainly include "create like cypher"
@sherfert

**Comment by sherfert** [comment]
@chencjiajy Can you post your `comment.cypher` here?

**Comment by chencjiajy** [comment]
Sorry, It's all my fault, **I didn't add `;`** between `create` commands (create node directly) and `LOAD CSV` command(create load from csv file). So when I use cypher-shell ,there is no response.
ps: Could you please write the [cypher-shell doc](https://neo4j.com/docs/operations-manual/current/tools/cypher-shell/)  about how to execute a cypher file more specific?
