### ISSUE TITLE
No way to tell neo4j version (Comunity vs enterprise)

### ISSUE THREAD

**Issue by cosimosimeoneTR** [neo4j/neo4j#5904]
Hi there!
As far as i found (i did it a lot), there is no way (apart from README.txt file) to tell which version of neo4j you are running (Comunity ot Enterprise).

**Comment by cosimosimeoneTR** [comment]
:play start
has it, but i don't want to use console,  i want to use neo4j-shell etc.

**Comment by tinwelint** [comment]
You can use:

`:GET http://localhost:7474/db/manage/server/version`

i.e. it's available in a REST endpoint currently.

**Comment by cosimosimeoneTR** [comment]
Cheers Mattias!
Any chance we can have is as a command, like

```
neo4j-shell -c "about"
```

?

**Comment by tinwelint** [comment]
That do sound like a nice thing to have :) I think Neo4j should at least expose this in a JMX bean, this way shell/rest/browser/whatever could access it.

**Comment by thobe** [comment]
With #5995 you will be able to tell the edition of Neo4j that is running through `neo4j-shell -c "dbinfo -g Kernel Edition"`, which would print either `{"Edition": "Community"}` or `{"Edition": "Enterprise"}`.

**Comment by cosimosimeoneTR** [comment]
Just found this:

```
 $ neo4j-shell -c "dbinfo -g Configuration edition"
{"edition": "Enterprise"}
```

**Comment by maxsumrall** [comment]
Usage now tested in #5995.
