### ISSUE TITLE
Feature Request: Equivalent of MySQL Dump to Export Data with/without Structure for Interoperability

### ISSUE THREAD

**Issue by typinator** [neo4j/neo4j#5912]
LOAD CSV gets data / structure into Neo4J but it's missing the ability to export in order to:-
1) support round-trip data exchange
2) provide interoperability with other tools
3) provide a means of archiving / transport of a project between platforms (since the different Windows and Mac file structures used for Neo4J seems to prevent a simple compress - move - decompress operation)

Something like the equivalent to the MySQL DUMP which can selectively export just the structure or structure + data would help (albeit Neo4J doesn't have a schema in the same way but it does have identified labels, properties, data types and constraints).

**Comment by jexp** [comment]
Great feedback thanks, a lot!.

In Neo4j browser you can export cypher results as CSV.

There is a "dump" command in neo4j-shell which outputs a format that works for small graphs.

I wrote an alternative variant of that here, that project also contains a means of exporting csv from cypher statements directly.

https://github.com/jexp/neo4j-shell-tools#cypher-export

**Comment by typinator** [comment]
Thanks for that link. Certainly seems to solve some problems. Have managed to 'dump' graph as Cypher statements so with a little bash scripting would be basis for archiving snapshots eg by adding a time stamp to the output file name.

**Comment by chrisvest** [comment]
`neo4j-admin dump/load` should solve this problem: https://neo4j.com/docs/operations-manual/3.2/tools/dump-load/
