### ISSUE TITLE
Weird behaviour/ errors in 2.3.1    (worked fine in 2.2.2)

### ISSUE THREAD

**Issue by tomzeppenfeldt** [neo4j/neo4j#5921]
We have some weird behaviour with collections :(

neo4j-sh (?)$ export selection=[30688,27682]```

This query runs fine:

neo4j-sh (?)$ with  {selection} as collection

> match p=(n)-[_..3]-(m) 
> // no paths that pass through other nodes in the selection
> where 
>     id(n) in collection
>     and NOT (n IN TAIL(nodes(p)))
> with id(m) as idm,id(n) as idn,length(p) as lp, count(_) as count,collection order by idm,idn,lp asc
> with idm,idn,collect([lp,count]) as c1,collection
>    where NOT idm IN collection
> // weighing of paths.. each hop further a factor 10 less
> with idm,idn, c1,reduce (score=0.0, i in c1 | score + (i[1]*10^(3-i[0]))) as reduced
> with idm, collect([idn,reduced]) as cr, sum(reduced) as sr 
> with idm,cr,size(cr) as lcr, sr where lcr>1
> with idm, cr, sr order by sr desc limit 5
> unwind cr as rel
> with idm as from,rel[0] as to,rel[1] as relscore
> return *;
> +--------------------------+
> | from  | relscore | to    |
> +--------------------------+
> | 30668 | 36.0     | 30688 |
> | 30668 | 2.0      | 27682 |
> | 30196 | 24.0     | 30688 |
> | 30196 | 1.0      | 27682 |
> +--------------------------+
> 4 rows
> 56 ms

now adding two MATCH statements at the end causes an error 

neo4j-sh (?)$ with  {selection} as collection

> match p=(n)-[_..3]-(m) 
> // no paths that pass through other nodes in the selection
> where 
>     id(n) in collection
>     and NOT (n IN TAIL(nodes(p)))
> with id(m) as idm,id(n) as idn,length(p) as lp, count(_) as count,collection order by idm,idn,lp asc
> with idm,idn,collect([lp,count]) as c1,collection
>    where NOT idm IN collection
> // weighing of paths.. each hop further a factor 10 less
> with idm,idn, c1,reduce (score=0.0, i in c1 | score + (i[1]*10^(3-i[0]))) as reduced
> with idm, collect([idn,reduced]) as cr, sum(reduced) as sr 
> with idm,cr,size(cr) as lcr, sr where lcr>1
> with idm, cr, sr order by sr desc limit 5
> unwind cr as rel
> with idm as from,rel[0] as to,rel[1] as relscore
> 
> match (n) where id(n)=from
> match (m) where id(m)=to
> return id(m),id(n);
> 57 ms

WARNING: Unexpected error during late semantic checking: Type mismatch: expected Collection<Integer> but was Collection<Number>

but when I replace the {selection} by static values, it does run again.

neo4j-sh (?)$ with  [30688,27682] as collection

> match p=(n)-[_..3]-(m) 
> // no paths that pass through other nodes in the selection
> where 
>     id(n) in collection
>     and NOT (n IN TAIL(nodes(p)))
> with id(m) as idm,id(n) as idn,length(p) as lp, count(_) as count,collection order by idm,idn,lp asc
> with idm,idn,collect([lp,count]) as c1,collection
>    where NOT idm IN collection
> // weighing of paths.. each hop further a factor 10 less
> with idm,idn, c1,reduce (score=0.0, i in c1 | score + (i[1]*10^(3-i[0]))) as reduced
> with idm, collect([idn,reduced]) as cr, sum(reduced) as sr 
> with idm,cr,size(cr) as lcr, sr where lcr>1
> with idm, cr, sr order by sr desc limit 5
> unwind cr as rel
> with idm as from,rel[0] as to,rel[1] as relscore
> 
> match (n) where id(n)=from
> match (m) where id(m)=to
> return id(m),id(n);
> +---------------+
> | id(m) | id(n) |
> +---------------+
> | 30688 | 30668 |
> | 27682 | 30668 |
> | 27682 | 30196 |
> | 30688 | 30196 |
> +---------------+
> 4 rows
> 246 ms

**Comment by tomzeppenfeldt** [comment]
2 pointers, thanks to michael hunger:

when prefixing the query with planner=rule   , there's no error

2.2.2 works but 2.2.4+ stopped working

**Comment by Mats-SX** [comment]
Hey @ophileon and thanks for reporting this problem.

We've identified the problem, and are working on constructing a solution for it. In the meantime we also have another workaround, if you don't want to use the rule planner. The issue is exposed by an additional round of semantic checking, which is done when the predicates in the last two `WHERE` clauses are rewritten to another internal structure, which does semantic checking slightly differently. This rewriting can be avoided by nesting the `id()` function call in a call to the `toInt()` function (basically a no-op).

```
match p=(n)-[..3]-(m) 
// ...
match (n) where toInt(id(n))=from
match (m) where toInt(id(m))=to
return id(m),id(n);
```
