### ISSUE TITLE
Neo4J 2.3.0 on Mac Osx El Capitan: Could not find or load main class org.neo4j.tooling.ImportTool

### ISSUE THREAD

**Issue by boldtrn** [neo4j/neo4j#5938]
Hi,

I just installed neo4j on my mac using the dmg provided from your homepage (decided to use 2.3.0 since I want to use neo4j/spatial which seems to be only available for 2.3.0).

Now I want to import data from a CSV file. Therefore, I wanted to go to my terminal and type `neo4j-import` but it's not on my path, also not in ' /bin/neo4j-import`.

So I thought I use the `Command Prompt` option, thats shipped with the neo4j.dmg. When I enter neo4j-import in that bash, the command is found but I get this reply:

```
bash-3.2$ neo4j-import 
Error: Could not find or load main class org.neo4j.tooling.ImportTool
```

Any idea why this is happening?

Best,
Robin

**Comment by jexp** [comment]
Sorry that is a bug in the packaging, please download the zip edition to use neo4j-import for now.

**Comment by boldtrn** [comment]
Thanks @jexp ,

I downloaded the tar version (not sure if there is a zip for unix). The import works wit that tool.

**Comment by Izhaki** [comment]
Related: https://github.com/neo4j/neo4j/issues/8347

**Comment by jexp** [comment]
Try this: https://gist.github.com/jexp/4692ad9cd14b6d9c1cc8bffa079c98fa

**Comment by Izhaki** [comment]
Thanks @jexp , but the gist does not seem to apply to tar images
