### ISSUE TITLE
Feature Request: Add an ALERT message in messages.log when an explicit store upgrade is required

### ISSUE THREAD

**Issue by santo-it** [neo4j/neo4j#5940]
Hi,

This is a FR to improve supportability and easiness of use of Neo4j Enterprise when an Explicit Store Upgrade is required

Version used for this test: Neo4j Enterprise 2.3.0
Platform: Windows 7

Step to reproduce the problem:
- download & install Neo4j Enterprise. Start it and make sure everything is working as expected
- shutdown the server
- make a backup copy of the current data directory (e.g. data/graph.db)
- copy (unzip if necessary) an old graph.db directory (e.g. a graph.db that you are sure that requires an Explicit Store Upgrade) under your data directory (you may use, for instance drwho.zip from http://neo4j.com/developer/example-data/)
- clean the file messages.log (if applicable)
- make sure you do not have allow_store_upgrade=true in your configuration file
- start Neo4j

If the above steps are followed, Neo4j will not start

Now, please, try to troubleshoot the issue (as it would do a user/customer/support engineer that does not know what is happening):
- check the messages.log for useful information on the issue; you'll find something like the following:

[...]
--- INITIALIZED diagnostics END ---
Initiating metrics..
--- STOPPING diagnostics START ---
--- STOPPING diagnostics END ---
Shutdown started

Note how in the messages.log there is no indication that something went wrong. We find a "Shutdown started" message, but we can't understand - by reading the log - what happened. Actually the "Shutdown started" message (without an ALERT) may even create confusion, as it may indicate that a "normal" stutdown was started (but this is not the case). There is no indication that a (compatibility) issue occurred

This FR is to please print in messages.log, if possible, something like this:

[...]
ALERT Failed to start Neo4j with an older data store version. To enable automatic upgrade, please set configuration parameter "allow_store_upgrade=true"
Shutdown started

Note that the above ALERT is the same ALERT that the Community version of Neo4j reports in a windows dialog (please just print the same message in the messages.log so that it will be more easy for Enterprise users to troubleshoot and fix this issue)

Reference:
- Explicit Store Upgrade process: http://neo4j.com/docs/stable/deployment-upgrading.html

Many Thanks,

**Comment by benbc** [comment]
Thanks for reporting this @santo-it. We are reviewing our start-up diagnostics at the moment and we'll make sure that this case is clear.

**Comment by spacecowboy** [comment]
This is actually already printed in `console.log` (which if run with `neo4j console` is printed to stdout).

Example with referenced drwho data and 2.3.1:

```
[...]
2015-10-09 17:18:01.632+0200 INFO  Remote interface ready and available at http://localhost:7474/
2015-10-09 17:21:50.214+0200 INFO  Neo4j Server shutdown initiated by request
2015-10-09 17:21:50.227+0200 INFO  Successfully shutdown Neo4j Server
2015-10-09 17:21:50.419+0200 INFO  Successfully stopped database
2015-10-09 17:21:50.419+0200 INFO  Successfully shutdown database
2016-01-14 16:51:51.086+0100 INFO  Successfully shutdown Neo4j Server
2016-01-14 16:51:51.087+0100 ERROR Neo4j cannot be started, because the database files require upgrading and upgrades are disabled in configuration. Please set 'allow_store_upgrade' to 'true' in your configuration file and try again.
```

**Comment by santo-neo** [comment]
Hi,

I have tested this with 3.0.2

Yes, if the command "neo4j console" is used the error message "ERROR Neo4j cannot be started, because the database files require upgrading [...]" is printed to stdout. If the service was installed with "neo4j install-service" and then started with "neo4j start" that error is written to the file neo4j.log

Reason why I was not seeing it in 2.3 was that I was using Neo4j.bat (without console)

Much better now. However, an additional question or possible issue: even after receiving this error my "neo4j-error.log" is empty. benbc, what is expected in this case: should an entry be added in "neo4j-error.log"?

Many thanks,

**Comment by benbc** [comment]
@santo-neo `neo4j-error.log` is a Windows service-specific log file to which we only log if there is a critical problem with the Windows service (as opposed to a more general Neo4j problem).

**Comment by santo-neo** [comment]
Thanks

Okay, let's close this 5940
