### ISSUE TITLE
FR: Implement ability to remove node from view in neo4j browser

### ISSUE THREAD

**Issue by ml054** [neo4j/neo4j#5965]
I'd would be great to have an option to hide node on query result screen in neo4j browser. In many cases when traversing graph I end up with messy graph due to many connections to few nodes. It would to great to mark this node as hidden - this can be implemented purely as client side code + we have to send 'ignored node ids list' in fetch neighbors request to avoid displaying them again when performing further traversal.

**Comment by oskarhane** [comment]
This is added in the 3.0 RC releases.
