### ISSUE TITLE
graph.db can be move while neo4j-service running[2.3.1]

### ISSUE THREAD

**Issue by darwinwu13** [neo4j/neo4j#5977]
I am new in neo4j, but i want to ask about something that i think is important.
I find out the graph.db folder while neo4j running can be move, and the strange thing is, when i insert a new node from browser, it will new file in graph.db folder, i see a new schema folder created, and the database is still running well, so i thought, does neo4j cached all of my node in the RAM?
what will happened if my node size is bigger than my RAM? does it still cached?

i think when neo4j-service is running, the graph.db folder shouldnt be moved. or maybe u should lock the file, just like any RDBMS do, i found out any RDBMS that i try, it lock their data folder when the service running.

why do we need to move graph.db folder when running? no we wont move it, but accident can be happened, like wrong deletion, so  do you have any work around?

**Comment by jexp** [comment]
it **should not be moved** what you see is just unix filesystems being lenient.

Neo4j tries to memory-map as much of the files as possible, the page-cache will control which data is needed in memory.

**Comment by darwinwu13** [comment]
thanks for the fast response @jexp , so to prevent this what Operating System should i use?
now i am using Linux Ubuntu 14.04 for testing and development.

**Comment by cleishm** [comment]
@darkeus: this is a common behavior of unix filesystems, and also in windows to a lesser degree.

If you're worried about users moving the database store whilst the database is still running, then you'd best run Neo4j under a different user account and ensure that the filesystem permissions are set such that other users cannot access or manipulate the files in the database store, or move the directory itself.

**Comment by cleishm** [comment]
PS. You might find this related stackoverflow post of interest: https://stackoverflow.com/questions/11818802/why-can-i-successfully-move-a-file-in-linux-while-it-is-being-written-to
