### ISSUE TITLE
neo4j PlaceboTransaction 

### ISSUE THREAD

**Issue by xghrbc1001** [neo4j/neo4j#5978]
```
  Transaction beginTx = db.beginTx();
    try{
     // do update neo4j
      beginTx.success();
      System.println("ok");
    }catch(Exception ex){
    }finally{
     beginTx.close();
    }
```

console print "ok",but my data not saved to neo4j,and I found this transaction is PlaceboTransaction ,not TopLevelTransaction

**Comment by thobe** [comment]
That means that you have a previous transaction that is still open, and the changes you are making are actually being recorded into that transaction. The changes will be applied to the database when that open "top level" transaction is closed.
