### ISSUE TITLE
graphdb's size

### ISSUE THREAD

**Issue by xghrbc1001** [neo4j/neo4j#5983]
our neo4j's graphid is nonsequence。
for example: first node id is 1000,the second id is 1050,the thrid is 2000

but we found not used graph id also need disk space. especially this file  neostore.nodestore.db

what config we can use that we can make no-used-graph-id not need disk space.

**Comment by cleishm** [comment]
Hi @xghrbc1001,

This issue tracker is for bugs and issues in the codebase of Neo4j. Questions on usage should be made on [StackOverflow](http://stackoverflow.com/questions/tagged/neo4j) or in the [Google Group](http://groups.google.com/group/neo4j).

Cheers,
Chris

**Comment by xghrbc1001** [comment]
@cleishm  yes,I put it into stackoverflow also,but  no answer about this,so I put it there

**Comment by jexp** [comment]
Which Neo4j version did you use? 
Do you run a cluster?
This rather seems like an issue with the id-generato grab-size.

**Comment by xghrbc1001** [comment]
@jexp no cluster, we use version 2.2.5 , I think the unused graphId also allocated disk space.
