### ISSUE TITLE
ReST API - Add an INDEX representation

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#60]
@kwattro: 'Hello,

Version: 1.8M07
Context:
### API - List all node indexes : Returns the following :

```
{
  "node_auto_index" : {
    "template" : "http://localhost:7474/db/data/index/node/node_auto_index/{key}/{value}",
    "provider" : "lucene",
    "type" : "exact"
  },
  "favorites" : {
    "template" : "http://localhost:7474/db/data/index/node/favorites/{key}/{value}",
    "provider" : "lucene",
    "type" : "exact"
  }
}
```

Problem :
- You do not have a proper uri to access the node index, only the template to add a node to the index.
- If you want to delete an index, you have to hardcode the index name in the uri.

I think that having an index representation would be a nice feature for the ReST API.

Reference to documentation : http://docs.neo4j.org/chunked/milestone/rest-api-indexes.html#rest-api-list-node-indexes

Mailing list subject : https://groups.google.com/forum/?fromgroups#!topic/neo4j/zTPJvjz4L6A%5B1-25%5D

Cheers,

Christophe'

**Comment by chrisvest** [comment]
This is from before we had schema indexes (for which there is an end-point like that), and before many other things. Closing because I don't think there is a demand for this feature any more.
