### ISSUE TITLE
An adaptive algorithm for join index determination

### ISSUE THREAD

**Issue by dhimmel** [neo4j/neo4j#6030]
## Background

When traversing paths, neo4j is capable of starting the search from both ends and performing a `NodeHashJoin` where the expansions meet. The COST planner seems somewhat intelligent at determining this join index. It appears that the planner:

1) performs a sequential search, omitting a join, when the estimated number of rows is low
2) otherwise attempts a balanced join, so both sides have a similar number of estimated rows

where row estimates are based on average node degree.
## Problem

The optimal join index is _highly_ query specific. Certain queries will end up traversing high degree nodes at a given depth and this cannot necessarily be predicted before hand.

[See this example](https://twitter.com/dhimmel/status/669933541514326016) where the planner didn't include a join leading to ~100 times inferior performance. And even when I do specify starting from both ends with `USING INDEX` in 2.3.1 the chosen join index results in lopsided `NodeHashJoin`:

![lopsided-plan](https://cloud.githubusercontent.com/assets/1117703/11603507/faa65f78-9a96-11e5-9b6e-7b3c6e918bdc.png)

I have found specifying the label of each node in the path allows better row estimates and therefore join index determination. However, specifying labels leads to unnecessary filter steps.
## Proposed solution

Could the join index be adaptively chosen during runtime? If the search is breadth first, then the size of each expansion could be assessed before deciding which side to proceed expanding from.

Future releases [will allow](https://github.com/neo4j/neo4j/pull/5038#issuecomment-162104365) users to specify the join index with a join hint (`USING JOIN ON`). This will help users avoid potential worst case scenarios, but it won't take advantage of the query-specific optimality.

**Comment by Lojjs** [comment]
@dhimmel I'm very sorry about our extreme late reply, but I just want to notify you about that we in the Cypher team have noticed this issue and will review the priority of this and consider it for future development.

**Comment by LinneaAndersson** [comment]
@dhimmel In all supported versions we now allow the user to give "join hints", you can read more about it here: https://neo4j.com/docs/cypher-manual/current/query-tuning/using/#query-using-join-hint

I will close this issue for now, but please let us know if you have further questions or thoughts about it. 
//Linnéa

**Comment by dhimmel** [comment]
Thanks @LinneaAndersson for taking a look at this old issue!

I don't think `USING JOIN ON node` is exactly the optimization I was proposing:

> Could the join index be adaptively chosen during runtime? If the search is breadth first, then the size of each expansion could be assessed before deciding which side to proceed expanding from.

But also haven't checked recent versions of Neo4j to evaluate the default join behavior (without specifying a specific node to join on). No problem keeping this closed as it hasn't generated any additional support in ~6 years haha.
