### ISSUE TITLE
Unnecessary deadlocks occur when using tx.acquireReadLock(..)

### ISSUE THREAD

**Issue by bachmanm** [neo4j/neo4j#6036]
Neo4j 2.3.1. 

Simplified scenario of a real-world use case. I would like to make sure that threads that update something in the graph peacefully co-exist with reader threads. I was under the impression that this could be achieved using locks. Consider this test, where a single node exists in the database. Some threads are updating a single property, some threads are reading it. 

``` java
public class BugTest {

    private GraphDatabaseService database;

    @Before
    public void setUp() {
        database = new TestGraphDatabaseFactory().newImpermanentDatabase();
        try (Transaction tx = database.beginTx()) {
            database.createNode(DynamicLabel.label("Test"));
            tx.success();
        }
    }

    @After
    public void tearDown() {
        database.shutdown();
    }

    @Test
    public void verifyConcurrentInsertsAndFetchesFromTheLinkedList() throws InterruptedException {
        ExecutorService executor = Executors.newFixedThreadPool(50);
        int noRequests = 1000;
        final AtomicBoolean success = new AtomicBoolean(true);

        for (int i = 0; i < noRequests; i++) {
            executor.execute(new Runnable() {
                @Override
                public void run() {
                    try {
                        increment();
                    } catch (Exception e) {
                        success.set(false);
                        e.printStackTrace();
                    }
                }
            });
            executor.execute(new Runnable() {
                @Override
                public void run() {
                    try {
                        System.out.println("counter = " + get());
                    } catch (Exception e) {
                        success.set(false);
                        e.printStackTrace();
                    }
                }
            });
        }

        long start = System.currentTimeMillis();

        executor.shutdown();
        executor.awaitTermination(120, TimeUnit.SECONDS);

        System.out.println("Took " + (System.currentTimeMillis() - start) + " ms");

        assertTrue("At least one operation failed", success.get());

        try (Transaction tx = database.beginTx()) {
            assertEquals(noRequests, database.getNodeById(0).getProperty("counter"));
            tx.success();
        }
    }

    private void increment() {
        try (Transaction tx = database.beginTx()) {
            Node node = database.getNodeById(0);

            tx.acquireWriteLock(node);

            node.setProperty("counter", (int) node.getProperty("counter", 0) + 1);

            tx.success();
        }
    }

    private int get() {
        int result = -1;

        try (Transaction tx = database.beginTx()) {
            Node node = database.getNodeById(0);
            tx.acquireReadLock(node);
            result = (int) node.getProperty("counter", 0);
            tx.success();
        }

        return result;
    }
}
```

This results in `DeadlockDetectedException` where the first one always look like this:

```
org.neo4j.kernel.DeadlockDetectedException: ForsetiClient[48] can't acquire UpdateLock{objectId=1486737951, refCount=1, holder=ForsetiClient[45]} on NODE(0), because holders of that lock are waiting for ForsetiClient[48].
 Wait list:SharedLock[
Client[45] waits for []]
    at org.neo4j.kernel.impl.enterprise.lock.forseti.ForsetiClient.markAsWaitingFor(ForsetiClient.java:782)
    at org.neo4j.kernel.impl.enterprise.lock.forseti.ForsetiClient.acquireExclusive(ForsetiClient.java:276)
    at org.neo4j.kernel.impl.api.LockingStatementOperations.acquireExclusive(LockingStatementOperations.java:504)
```

From the message, it actually seems it should not be a deadlock, because one of the clients waits for nothing (45 in this case).

Note that removing `tx.acquireReadLock(node)` makes the tests pass, but there is a point to having it for the real-world use case, which reads/writes subgraphs (trees) rooted at that node. The idea is to have that root serve as _the_ lock for the entire tree. 

Cheers!

**Comment by bachmanm** [comment]
Actually, under heavier concurrency, the test fails even if everybody just tries to take a write lock.

**Comment by tinwelint** [comment]
Hi, this is a drawback of the deadlock detection algorithm [dreadlocks], which is built for maximum performance with a low probability of false deadlocks reported. See more details at https://www.cs.nyu.edu/~ejk/papers/dreadlocks-spaa08.pdf . You can try with the `community` lock manager as it should not run into this problem. You enable it using the neo4j setting `lock_manager=community`

**Comment by bachmanm** [comment]
Thanks - just a note, with `community` lock under heavy concurrency, the database is much faster (more than 10x). But I guess that may be expected in favour of speed under less heavy concurrency.

**Comment by chrisvest** [comment]
@bachmanm Can you describe the workload in some detail? It sounds like a good addition to our internal benchmarks.

**Comment by bachmanm** [comment]
The very test in this issue. Just change `noRequests` to (say) 10k and also try to increase the number of threads. With `noRequests=10_000` and 500 threads, it takes about 50s on my MacBook Pro with default locking, but a few seconds using community lock

**Comment by tinwelint** [comment]
So in the face of all these false deadlocks there will be loads of transaction retrying, so that's expected isn't it. It's just suboptimal that _so many_ false deadlocks are triggered.

**Comment by jakewins** [comment]
This PR improves the situation somewhat, for `c=50` and `noRequests=10_000`, it cuts the deadlock rate roughly in half, averaged over four runs. https://github.com/neo4j/neo4j/pull/6287

However, I think this stumbles on something really interesting relating to how we upgrade shared locks to exclusive. Thanks so much for writing this up Michal, the test case is super helpful. I think we will be able to improve locking a lot using this!

**Comment by bachmanm** [comment]
Any time! Thanks for taking a look at this!
