### ISSUE TITLE
Feature Request: Online index creation

### ISSUE THREAD

**Issue by cosimosimeoneTR** [neo4j/neo4j#6067]
I might have lost it, but when creating index on huge datasets, shell returns prompt with OK, but in fact index is in POPULATING STATE

```
neo4j-sh (?)$ create index on :node (attribute) ;
+-------------------+
| No data returned. |
+-------------------+
Indexes added: 1
26771 ms
neo4j-sh (?)$ schema ls
Indexes
  ON :node(attribute) POPULATING

$ tail -f messages 
2015-12-10 09:22:25.580+0000 INFO  [o.n.k.i.a.i.IndexPopulationJob] Index population started: [:node(attribute) [provider: {key=lucene, version=1.0}]]
2015-12-10 09:23:44.673+0000 INFO  [o.n.k.i.a.i.IndexPopulationJob] Index population completed. Index is now online: [:node(attribute) [provider: {key=lucene, version=1.0}]]
```

Fact, to check if index is created i'd need to loop on 

```
neo4j-shell -c "schema ls"
```

and wait for index to be created.

What i'd need is an option like

```
neo4j-sh (?)$ create index on :node (attribute)  ONLINE;
```

that returns  me the prompt _only_ when index is in ONLINE state, eg. no background index craetion.

**Comment by jotomo** [comment]
The _schema_ command has a (relatively new AFAIK) subcommand _await_, which you can use to block till an index is populated, see _help schema_ for details. Note that the shell just submits the Cypher statement to create an index. Creating index synchronously via Cypher is not yet supported, but IIRC this is being considered.

**Comment by jexp** [comment]
For now it is `schema await`, we consider moving this functionality to the remoting layer for 3.x
