### ISSUE TITLE
Neo4j 2.3.0 Transaction REST endpoint service Error

### ISSUE THREAD

**Issue by corporatepiyush** [neo4j/neo4j#6076]
I am getting an error while executing the cypher query from REST endpoint

`
Message:
    Failed: [{"code":"Neo.ClientError.Statement.InvalidSyntax","message":"Invalid input 'H': expected 'i/I' (line 1, column 39 (offset: 38))\n\"MATCH (n:User) SET n += {properties} WHERE ID(n) = {id} RETURN ID(n) as id, n as user\"\n                                       ^"}]
`

Query to REST endpoint
"/db/data/transaction/commit"

`{ 
  statement: 'MATCH (n:User) SET n += {properties} WHERE ID(n) = {id} RETURN ID(n) as id, n as user',
  parameters: { id: 185, properties: { lastName: 'Banderas', age: 40 } } 
}`

**Comment by corporatepiyush** [comment]
got an answer from http://stackoverflow.com/questions/34220599/neo4j-2-3-0-transaction-rest-endpoint-service-error.

The error message is misleading.

**Comment by jexp** [comment]
Put the WHERE before the SET, WHERE belongs to MATCH.
