### ISSUE TITLE
RPM-provided init script should look for run-as user from sysconfig/neo4j

### ISSUE THREAD

**Issue by vargok** [neo4j/neo4j#6079]
Please update the /etc/init.d/neo4j script to look for another user specified, e.g., in /etc/sysconfig/neo4j.

For example:
[/etc/sysconfig/neo4j]

```
export NEO4J_USER='runasuser'
```

[/etc/init.d/neo4j]

```
...
+ neo4j_user="${NEO4J_USER:-neo4j}";
...
start() {
...
- daemon --user neo4j --pidfile $pidfile $exec start
+ daemon --user ${neo4j_user} --pidfile $pidfile $exec start
```

**Comment by benbc** [comment]
@vargok Thank you for reporting this. We are planning to overhaul our RPM package to make it officially production ready. We shall certainly do this as part of that work.

**Comment by vargok** [comment]
Great! Any idea when that might be?  Early January, maybe?

**Comment by benbc** [comment]
@vargok Unlikely to be that soon, I'm afraid. We hope to do it in Q1 2016.

**Comment by vargok** [comment]
Any update?  Q1 is almost over.  We're blocked going forward with this until the RPM is fixed.

**Comment by benbc** [comment]
@vargok We hope to have it done in the next month, but still can't be certain.

**Comment by heavydawson** [comment]
+2 for this functionality.
