### ISSUE TITLE
Shell script errors on OSX with 2.3.1 edition

### ISSUE THREAD

**Issue by ascheman** [neo4j/neo4j#6084]
I found two bugs in the OSX 2.3.1 community edition: Both, neo4j-shell and neo4j-import refuse to run with a similar error:

`Error: Could not find or load main class org.neo4j.shell.StartClient`

and

`Error: Could not find or load main class org.neo4j.tooling.ImportTool`

Both are due to a wrong search for jar files in the distribution. Obviously they search for a `lib` directory beyond the base dir, e.g., `/Applications/Neo4j Community Edition.app/Contents/Resources/app/lib` which does not exist. The jars live in the `bin` directory.

I have attached a ZIP with patches for these files: [neo4j-diffs.zip](https://github.com/neo4j/neo4j/files/60090/neo4j-diffs.zip).
Maybe this can make it into the regression test suite for OSX in the future? ;-)

**Comment by benbc** [comment]
@ascheman Thanks for the report. I think you're using the Mac Desktop installer, rather than the tarball: is that correct?

**Comment by ascheman** [comment]
@benbc Yes, right, I downloaded the DMG and installed neo4j from the image!

**Comment by benbc** [comment]
@ascheman These problems are fixed by https://github.com/neo4j/neo4j/commit/dd1987174e4fb3652626f18575221aa07df45cd3 and https://github.com/neo4j/neo4j/commit/e41c30cf51f710907f07b30fa57ba0c45119a653. The fixes will be included in the 2.3.2 release.
