### ISSUE TITLE
Troubles running in test stage

### ISSUE THREAD

**Issue by pdipietro** [neo4j/neo4j#6093]
I downloaded two days ago the latest version of neo4j and neo4jrb.
I then made the required changes to upgrade from rake start to /bin/neo4j start
It runs fine in dev stage.
I just cloned my dev machine to create a dedicated test one.
Neo4j started, but rails cannot connect with it if started with -etest 

Is there any work to do to tell Neo4j to run in test?

Also, by your experience, in production stage, it is better to run both neo4j and rails in background?

Paolo

**Comment by craigtaverner** [comment]
Hi @pdipietro, sorry this issue never got any attention, but I think that is because it looks like something for the Ruby library at https://github.com/neo4jrb/neo4j. If you are still having similar issues, could you open a new issue there?
