### ISSUE TITLE
Degraded query performance in 2.3.1

### ISSUE THREAD

**Issue by genemishchenko** [neo4j/neo4j#6104]
Hi.

After migrating to Neo4j version 2.3.1 from 2.2.4 for my NLP application I see that some queries now hang the system. Before they took under a second to execute on the same hardware.
I don't see any swapping going on, so memory is probably not an issue.

Moreover, when I terminate the Java program that runs these queries I see from resource utilization that the DB engine is still working. To resolve that I have to shut down everything completely. That may be a separate issue.

Below is one of the queries that the new version of Neo4j stumbles on:
match (d:Document{document_ID:5})--(s:Sentence)--(e_t1:Entity{ent_type:'TERM'})--(:Token)-[:next]->({word:'of'})-[:next]->()--(e_m1:Entity{ent_type:'MONEY'})--(:Token)-[:next]->(t_c2)-[:next]->()--(e_m2:Entity{ent_type:'MONEY'})--(:Token)-[:next]->({word:'in'})-[:next]->()--(e_t2:Entity{ent_type:'TERM'}) where t_c2.word in ['and','on'] return id(e_m1),id(e_m2);

Any insight would be greatly appreciated.
Gene.

**Comment by genemishchenko** [comment]
Update: I can't even see the EXPLAIN plan for the above query. The statement also hangs, executing indefinitely.

**Comment by jexp** [comment]
As a workaround you can prefix your query with `cypher planner=rule MATCH ...`
or configure the RULE planner in your neo4j.properties.

But let's solve the underlying issue.

**Comment by jexp** [comment]
Which kinds of indexes / constraints do you have?

**Comment by genemishchenko** [comment]
Michael,

I have an index on :Document(document_ID). That is my only "entry point" to the data.

Unfortunately, I can't run anything on my end any more in 2.3.1.
For my project I had to revert to 2.2.7 and so I created two Neo4j CE installations (2.2.7 and 2.3.1) and two databases of the corresponding versions.
For some reason the 2.3.1 installation gives me trouble now, when I have two versions of software installed on the same machine. This was not the case when 2.3.1 was installed alone.
Below are some screenshots of what's going on. I don't see any error messages in messages.log.

![neo4j_browser_err_1](https://cloud.githubusercontent.com/assets/9038701/11811547/2556ee16-a304-11e5-8135-0b072d87a8d6.PNG)
![neo4j_browser_err_2](https://cloud.githubusercontent.com/assets/9038701/11811554/2c574300-a304-11e5-8840-50e3e57e14e6.PNG)
![neo4j_browser_err_3](https://cloud.githubusercontent.com/assets/9038701/11811563/33ed6cde-a304-11e5-95df-0fdeffbe70e3.PNG)

Here's the ZIP of the test database that I'm working with. Hope you can identify the problem with the provided query on your end.
(I had to append the .txt extension because the ZIP was not being uploaded)
[remora.graph_2.3.1_test.zip.txt](https://github.com/neo4j/neo4j/files/62496/remora.graph_2.3.1_test.zip.txt)

In general, out of dozens of queries that I have as a part of my application, there are four that just halt (I initially provided one of them) and one that is borderline acceptable (running for 30 seconds now), but the rest are not really OK either. Putting these five aside, migrating from 2.2 to 2.3 made things slower for me 2-3 times across the board.
I did not do any tuning and did not use any hints. This is just out of the box.

Thanks!
Gene.

**Comment by Mats-SX** [comment]
Hello @genemishchenko 

Is this issue still a problem for you? Have you had the chance to try a `3.0.x` version, or a `3.1.0-Mx` milestone to see whether this particular issue has been resolved?

All the best
Mats

**Comment by genemishchenko** [comment]
Hi Mats,

thanks for following up on this.
Unfortunately, I did not get a chance to test my queries under any versions later than 2.2.X because at first I ran into trouble with multiple installations of Neo4j CE co-existing on the same machine, and then we actually stopped using Neo4j.
So I think we can close the issue.

Thank you.
Gene.
