### ISSUE TITLE
neo4j-shell does not execute Cypher statements starting with WITH

### ISSUE THREAD

**Issue by obfischer** [neo4j/neo4j#6137]
I am just preparing a playground project for myself to play a little bit around with Cypher within a controlled test data environment.

In the Ne04j browser I can execute the following statements:

**WITH statement**

```
WITH    ["Wilhelm", "Herbert", "Otto"] AS names
FOREACH (m in names | CREATE (p:Male { name: m}));
```

**CREATE statement**

```
create (p);
```

Both statements runs fine in the browser. But if I put the WITH statement in a file to load it via `neo4j-shell` and try to execute it I get always to following error:

```
> neo4j-shell -file with.cy
ERROR (-v for expanded information):
    Unknown command 'with   ["wilhelm",'

 -host      Domain name or IP of host to connect to (default: localhost)
 -port      Port of host to connect to (default: 1337)
 -name      RMI name, i.e. rmi://<host>:<port>/<name> (default: shell)
 -pid       Process ID to connect to
 -c         Command line to execute. After executing it the shell exits
 -file      File containing commands to execute, or '-' to read from stdin. After executing it the shell exits
 -readonly  Connect in readonly mode (only for connecting with -path)
 -path      Points to a neo4j db path so that a local server can be started there
 -config    Points to a config file when starting a local server

Example arguments for remote:
    -port 1337
    -host 192.168.1.234 -port 1337 -name shell
    -host localhost -readonly
    ...or no arguments for default values
Example arguments for local:
    -path /path/to/db
    -path /path/to/db -config /path/to/neo4j.config
    -path /path/to/db -readonly
```

If I put the CREATE statement in a file I can run it via `neo4j-shell` without any problems:

```
 neo4j-shell -v -file create.cy
+-------------------+
| No data returned. |
+-------------------+
Nodes created: 1
3 ms
```

So, why can't I execute a statement starting with `WITH` via `neo4j-shell -file`?

**Comment by jexp** [comment]
Neo4j shell uses a "first command" mechanism for executing commands. For running cypher natively **some** of the cypher keywords have been mapped to a command.

for all others you can just prefix your statement  with `CYPHER`

So in your case: `CYPHER WITH ["Wilhelm", "Herbert", "Otto"] AS names ...`

In hindsight it would have been better to only allow statements with a `cypher` prefix to be executed as cypher statements in shell.
