### ISSUE TITLE
Spring Data Neo4j 4 is not storing any data

### ISSUE THREAD

**Issue by BondWong** [neo4j/neo4j#6138]
I encountered a very strange problem, I dont know whether that is a bug or not. Here is the link, http://stackoverflow.com/questions/34340317/spring-data-neo4j-4-is-not-storing-any-data ,
I need help, thanks!

**Comment by luanne** [comment]
Crossposted here https://github.com/spring-projects/spring-data-neo4j/issues/323 and on StackOverflow. The Neo4j Github Issues is only for core Neo4j issues. We'll respond on StackOverflow.

**Comment by spacecowboy** [comment]
Closing as it's a Spring issue.
