### ISSUE TITLE
There is *no* proper way to install Neo4j on RPM-based systems.

### ISSUE THREAD

**Issue by Alan-R** [neo4j/neo4j#6148]
If you install from the tar ball, it says "this is not the right way to install Neo4j on your platform". If you use the RPM repository it gives several very serious (and problematic) warnings about it being experimental.

So, there is **no** proper/supported way to install Neo4j on RPM-based systems. 

95+% of all cloud instances are Linux-based. More than half of those run an RPM-based distribution. The most mission-critical organizations gravitate towards RHEL or SUSE Linux (both of which are RPM-based).

Professional, supportable products on these platforms _require_ high-quality RPMs, and a properly-managed RPM repository generated automatically from your production build system. Without these, your customers cannot properly manage Neo4j installations. It brands the product as amateurish.

Neo4j has neither of these. I've put references to a number of the related bugs below.

Moreover, you should (at least minimally) test your product from the RPMs on a number of platforms. Personally, I do this on my product using Docker - it makes it very straightforward.

The upshot of this for me is that I have potential customers who are reluctant to use _my_ product because of _your_ poor RPM support. I certainly understand why they feel this way. I should not have to package your product and create my own RPM repository just to get past your issue.

I appreciate that this may be a set of skills that you may not have in-house. The good news is that these skills are available out there in the real world.  But you need to spend the money and time to make this happen if you want to have production (meaning people-who-pay-you-money) Linux customers.
## Related issues
- neo4j RPM repository has digital signature issues #6143 
- neo4j RPM does not work with SuSE Linux #6142
- RPM-provided init script should look for run-as user from sysconfig/neo4j feature operability #6079 
- RPM Java dependencies feature operability #5484 
- RPM incorrectly removes user/group on upgrade bug operability #5433
- RPM does not mark `/etc/sysconfig/neo4j` as noreplace config file feature operability #5389 
- packages incorrectly depend on a specific version of Java 2.3 bug #5100

**Comment by cleishm** [comment]
Hi Allen,

Thanks for raising your concerns. We certainly take them onboard.

As you state, our RPM support is currently experimental and hasn't had a lot of investment at this time. That said, we do have many, many production users on Linux, so this hasn't been as big an impediment as we might have otherwise suspected initially. However, as you've recognized would be the case, most of them do not use the RPM packages that are currently available due to their experimental nature. Instead, most typical deployments we see run Neo4j directly from an unpackaged .tar.gz.

However, we would like to improve on that. To that end, supported RPM packages are definitely something we have on our roadmap to develop, and it's now been given a high priority. I'm hoping we see some progress on that early next year.

I hope that insight is helpful, and thank you again for the constructive feedback!

Cheers,
Chris

**Comment by Alan-R** [comment]
So, I'm having trouble reconciling "high priority" and "closed". Can you help me understand which it is?

**Comment by cleishm** [comment]
Hi Allan,

Don't worry, your feedback is received and our internal planning boards now include reference to your thoughts on how the packaging should work.

Thus there is no need to keep this issue open, as these issues don't represent our feature work and it doesn't track a specific bug in the current codebase of Neo4j. Closing it helps reduce tracking overhead for us.

You can always reach out to me directly if you have questions or would like status updates in future.

Thanks for your continued interest in Neo4j, and for your constructive contributions!

Cheers,
Chris

**Comment by Alan-R** [comment]
Also, when installing the tar ball, it states that "this may not be the correct/optimum way to install this on your system". I agree - it's not ;-). There is no way of installing Neo4j from tar ball _or_ RPM that doesn't give you a bad feeling that you're probably not doing the right thing - which is the point of this issue. The RPM warnings are more serious both in words and in practice, but both of them give you warnings.

**Comment by cleishm** [comment]
I think you're referring to the warning that is generated from `./bin/neo4j-installer`. That is definitely deprecated, and the warning ("this installer is deprecated and may not be the optimal way to install Neo4j on your system") is quite true.

When I mention that many production users run from an unpacked tarball, I mean that quite literally. They untar the .tar.gz, and then run `./bin/neo4j start` (or wire it into their own system startup script). Whilst a workable and common approach, we definitely recognise this is much more work than a complete and supported package would be for each and every OS. That is the work I mention we're taking on with some renewed priority. Indeed, one of the first deliverables in that area, which may be of interest to you, is a supported docker image of Neo4j: http://neo4j.com/developer/docker/

Cheers,
Chris

**Comment by ddamoursNRC** [comment]
By closing this issues, are you implying that RPM based install is not supported? This seems like a major impediment to get new users up and running or for very restrictive production environments.

**Comment by Alan-R** [comment]
I think this means "we use github issues for bugs, not features, and this is a feature". I've been in contact with @cleishm, and that seems to be the view. As I understand it, they've put together a team to deal with a bunch of the operability issues including this one. @srbaker is my contact on this team.

@cleishm: Since this is my understanding of what you've told me about the packages and repositories, it would be good for you or @srbaker to make that statement here. Of course, if I've misunderstood, please correct me. I think people would be encouraged to know what I've been told.

To be clear and factual - if you've deprecated the installer and at the moment, Neo4j has no way of installing through RPM packages, that means that Neo4j currently supplies no supported way of installing at all on RPM-based systems.

_At the current time_, the only _supported_ way to install is for each customer to create all the infrastructure to perform the installation and track changes, and so on. This is essentially requiring the customer to do the work of packaging or re-invent a local packaging infrastructure themselves. Moreover, it's not really supported either - since any problems with the packaging would fall back on the customer.

If Neo4j has a different view, then please take this opportunity to clarify this.

That's the bad news. The good news is that I believe that Neo4j is planning on fixing this.

**Comment by cleishm** [comment]
Hey @ddamoursNRC,

@Alan-R is correct. We absolutely want to provide _good, supported RPM packages_. What is available currently is neither of those, and whilst they were marked as experimental, we agree this was confusing and frustrating for some. But we have a team working on that, and hopefully we'll see some change there very soon.

Meanwhile, what most customers we work with do, is to directly use the neo4j tar.gz distribution. Something like:

``` console
# cd /usr/local
# tar xzf neo4j-community-2.3.2-unix.tar.gz
# ln -s neo4j-enterprise-2.3.2 neo4j
# cd neo4j
# vi conf/neo4j-server.properties # and edit other config files
# ./bin/neo4j start
```

And for auto-recovery, they'll often put the call to `neo4j start` into a script that's called at startup.

Obviously that's not as convenient as a OS specific packaging, but it does work well and does make it easy to keep multiple versions of neo4j available on the system.

I hope that's helpful information. And when we release official RPM packages, we'll certainly make a fanfare about it :)

Cheers,
Chris

**Comment by spacecowboy** [comment]
@Alan-R @ddamoursNRC @vargo @esplinr @wcooley

Thank you for reporting issues on RPMs. It's been a while but we've
now got proper RPM support again.

Yesterday `3.2.0-alpha04` became the first published RPM to
the [testing repo](http://yum.neo4j.org/testing/).

Stable versions will be published to
the [stable repo](http://yum.neo4j.org/stable).

We will also backport the RPM packaging to the `3.1` series soon.

Please continue to report any issues you might find.

And I'm sorry for the delay here.

**Comment by Alan-R** [comment]
Thanks @spacecowboy and everyone else involved in making this work!

**Comment by vikingops** [comment]
Hey @spacecowboy and others.

Currently I'm unable to use the `/stable` version of your yum repository, yet the `/testing` one works fine.

As an example (I sanitized the output slightly to make it quicker to read).

```
[root@ip-10-0-1-20 ~]# yum clean all
Loaded plugins: langpacks, versionlock
Repository epel is listed more than once in the configuration
Cleaning repos: base centosplus elasticsearch-1.4 elasticsearch-1.5 elasticsearch-1.7 elasticsearch-2.x epel extras intelworks ius neo4j nginx nodesource pgdg95 rightscale-epel updates yarn
Cleaning up everything
[root@ip-10-0-1-20 ~]# cat /etc/yum.repos.d/neo4j.repo
[neo4j]
name=Neo4j Yum Repo
baseurl=http://yum.neo4j.org/stable
enabled=1
gpgcheck=1
[root@ip-10-0-1-20 ~]# yum list --showduplicates neo4j
Loaded plugins: langpacks, versionlock
base                                                                                                                                                                                                                   | 3.6 kB  00:00:00
[...]
neo4j                                                                                                                                                                                                                  | 2.9 kB  00:00:00
[...]
(11/21): neo4j/primary_db                                                                                                                                                                                              | 1.1 kB  00:00:00
[...]
Error: No matching Packages to list
[root@ip-10-0-1-20 ~]#
```

Here's when I change it to `testing`:

```
[root@ip-10-0-1-20 ~]# cat /etc/yum.repos.d/neo4j.repo
[neo4j]
name=Neo4j Yum Repo
baseurl=http://yum.neo4j.org/testing
enabled=1
gpgcheck=1
[root@ip-10-0-1-20 ~]# yum clean all
Loaded plugins: langpacks, versionlock
Repository epel is listed more than once in the configuration
Cleaning repos: base centosplus elasticsearch-1.4 elasticsearch-1.5 elasticsearch-1.7 elasticsearch-2.x epel extras intelworks ius neo4j nginx nodesource pgdg95 rightscale-epel updates yarn
Cleaning up everything
[root@ip-10-0-1-20 ~]# yum list --showduplicates neo4j
Loaded plugins: langpacks, versionlock
Repository epel is listed more than once in the configuration
base                                                                                                                                                                                                                   | 3.6 kB  00:00:00
[...]
neo4j                                                                                                                                                                                                                  | 2.9 kB  00:00:00
[...]
(14/21): neo4j/primary_db                                                                                                                                                                                              |  85 kB  00:00:00
[...]
Available Packages
[...]
neo4j.noarch                                                                                                      2.2.1-1                                                                                                                neo4j
neo4j.noarch                                                                                                      2.2.2-1                                                                                                                neo4j
neo4j.noarch                                                                                                      2.2.3-1                                                                                                                neo4j
neo4j.noarch                                                                                                      2.2.4-1                                                                                                                neo4j
neo4j.noarch                                                                                                      2.2.5-1                                                                                                                neo4j
neo4j.noarch                                                                                                      2.2.6-1                                                                                                                neo4j
neo4j.noarch                                                                                                      2.2.7-1                                                                                                                neo4j
neo4j.noarch                                                                                                      2.2.8-1                                                                                                                neo4j
neo4j.noarch                                                                                                      2.2.9-1                                                                                                                neo4j
neo4j.noarch                                                                                                      2.2.10-1                                                                                                               neo4j
neo4j.noarch                                                                                                      2.3.0-M01_1                                                                                                            neo4j
neo4j.noarch                                                                                                      2.3.0-M02_1                                                                                                            neo4j
neo4j.noarch                                                                                                      2.3.0-M03_1                                                                                                            neo4j
neo4j.noarch                                                                                                      2.3.0-RC1_1                                                                                                            neo4j
neo4j.noarch                                                                                                      2.3.0-1                                                                                                                neo4j
neo4j.noarch                                                                                                      2.3.1-1                                                                                                                neo4j
neo4j.noarch                                                                                                      2.3.2-1                                                                                                                neo4j
neo4j.noarch                                                                                                      2.3.3-1                                                                                                                neo4j
neo4j.noarch                                                                                                      2.3.4-1                                                                                                                neo4j
neo4j.noarch                                                                                                      2.3.5-1                                                                                                                neo4j
neo4j.noarch                                                                                                      2.3.6-1                                                                                                                neo4j
neo4j.noarch                                                                                                      2.3.7-1                                                                                                                neo4j
neo4j.noarch                                                                                                      2.3.8-1                                                                                                                neo4j
neo4j.noarch                                                                                                      3.0.0-M01_1                                                                                                            neo4j
[...]
```

I assume that I can still use the testing repo as long as the versions I use match what I would want from the stable repo. Just fyi. :)

**Comment by spacecowboy** [comment]
@thomaskrag no new package has been published to `stable` yet. Only 3.2 alpha is available at this moment. I am working on getting 3.1 up as RPM today in `stable` though.

**Comment by vikingops** [comment]
Hey @spacecowboy. Thanks for replying so quickly.

 My point is that there are no packages available when using the `stable` repo. We do still use a rather old package (`2.3.1`), so that might not be available there either? :)

**Comment by spacecowboy** [comment]
@thomaskrag correct because no stable RPM have in fact ever been released. The entire repo was considered experimental before (and have both stable and testing versions of neo4j) hence they all live in `testing` now

**Comment by vikingops** [comment]
@spacecowboy Explains everything! Thanks! 👍

**Comment by spacecowboy** [comment]
@thomaskrag `3.1.1` is now available on the `stable` repo

**Comment by frankthetank** [comment]
So I am using the stable repo to install 3.1.1 (in fact, I did this for the recent Graph Day in D.C.).  Unfortunately I still receive the signature verification error:

```
Signature verification failed for file 'repomd.xml' from repository 'neo4j'.
Warning: This might be caused by a malicious change in the file!
```

This causes my automated update checks to fail now.

**Comment by spacecowboy** [comment]
@frankthetank  did you import the Neo4j GPG key as instructed on http://yum.neo4j.org/stable/ ?

**Comment by frankthetank** [comment]
Yes - I followed the steps outlined on the site.

**Comment by spacecowboy** [comment]
@frankthetank could give some more details? For example, what distro are you running?

**Comment by frankthetank** [comment]
I am running openSUSE Tumbleweed x86_64, up to date as of 5 minutes ago.

Here is the info on the neo4j RPM that does seem to install fine:
```
toybox:/home/frank # rpm -qi neo4j
Name        : neo4j
Version     : 3.1.1
Release     : 1
Architecture: noarch
Install Date: Mon 27 Feb 2017 09:26:05 PM EST
Group       : Unspecified
Size        : 86443396
License     : GPLv3
Signature   : RSA/SHA1, Wed 15 Feb 2017 10:04:35 AM EST, Key ID 26c95cf201182252
Source RPM  : neo4j-3.1.1-1.src.rpm
Build Date  : Wed 15 Feb 2017 10:02:09 AM EST
Build Host  : skeletor
Relocations : (not relocatable)
URL         : http://neo4j.org/
Summary     : Neo4j server is a database that stores data as graphs rather than tables.
Description :

Neo4j is a highly scalable, native graph database purpose-built to
leverage not only data but also its relationships.
Distribution: (none)
```
and the corresponding key:
```
Distribution: (none)
Name        : gpg-pubkey
Version     : 01182252
Release     : 544ee144
Architecture: (none)
Install Date: Mon 27 Feb 2017 08:57:31 PM EST
Group       : Public Keys
Size        : 0
License     : pubkey
Signature   : (none)
Source RPM  : (none)
Build Date  : Mon 27 Oct 2014 08:20:20 PM EDT
Build Host  : localhost
Relocations : (not relocatable)
Packager    : Neo Technology Admins <admins@neotechnology.com>
Summary     : gpg(Neo Technology Admins <admins@neotechnology.com>)
Description :
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: rpm-4.12.0.1 (NSS-3)

mQINBFRO4UQBEADzzMOKKrxJ9bIzgLmMsTc/7E+h+7MeuHTEU79cynz9ORHPQTXY
<...truncated for brevity...>
3iWKpPfXUgCqT85ByFOnYuqiW+YFV18Z/ISOZxO1v+rg5qRc0+W3PUwZX4HMUa8B
r6RX
=j3eL
-----END PGP PUBLIC KEY BLOCK-----
```

I also have another Neo4j gpg key:
```
Distribution: (none)
Name        : gpg-pubkey
Version     : d37f5f19
Release     : 58113cda
Architecture: (none)
Install Date: Mon 27 Feb 2017 08:57:31 PM EST
Group       : Public Keys
Size        : 0
License     : pubkey
Signature   : (none)
Source RPM  : (none)
Build Date  : Wed 26 Oct 2016 07:31:38 PM EDT
Build Host  : localhost
Relocations : (not relocatable)
Packager    : Neo4j Admins <admins@neotechnology.com>
Summary     : gpg(Neo4j Admins <admins@neotechnology.com>)
```
Additionally, I have attached the zypper log showing where the presumably correct key is found but cannot be verified against the current repomd.xml file.

Let me know if there is anything more you need.
[neo4j-zypper-gpgkey.txt](https://github.com/neo4j/neo4j/files/823124/neo4j-zypper-gpgkey.txt)

**Comment by Alan-R** [comment]
I ran into similar problems with SUSE. 

On March 6, 2017 6:50:31 PM MST, Frank <notifications@github.com> wrote:
>I am running openSUSE Tumbleweed x86_64, up to date as of 5 minutes
>ago.
>
>Here is the info on the neo4j RPM that does seem to install fine:
>```
>toybox:/home/frank # rpm -qi neo4j
>Name        : neo4j
>Version     : 3.1.1
>Release     : 1
>Architecture: noarch
>Install Date: Mon 27 Feb 2017 09:26:05 PM EST
>Group       : Unspecified
>Size        : 86443396
>License     : GPLv3
>Signature   : RSA/SHA1, Wed 15 Feb 2017 10:04:35 AM EST, Key ID
>26c95cf201182252
>Source RPM  : neo4j-3.1.1-1.src.rpm
>Build Date  : Wed 15 Feb 2017 10:02:09 AM EST
>Build Host  : skeletor
>Relocations : (not relocatable)
>URL         : http://neo4j.org/
>Summary     : Neo4j server is a database that stores data as graphs
>rather than tables.
>Description :
>
>Neo4j is a highly scalable, native graph database purpose-built to
>leverage not only data but also its relationships.
>Distribution: (none)
>```
>and the corresponding key:
>```
>Distribution: (none)
>Name        : gpg-pubkey
>Version     : 01182252
>Release     : 544ee144
>Architecture: (none)
>Install Date: Mon 27 Feb 2017 08:57:31 PM EST
>Group       : Public Keys
>Size        : 0
>License     : pubkey
>Signature   : (none)
>Source RPM  : (none)
>Build Date  : Mon 27 Oct 2014 08:20:20 PM EDT
>Build Host  : localhost
>Relocations : (not relocatable)
>Packager    : Neo Technology Admins <admins@neotechnology.com>
>Summary     : gpg(Neo Technology Admins <admins@neotechnology.com>)
>Description :
>-----BEGIN PGP PUBLIC KEY BLOCK-----
>Version: rpm-4.12.0.1 (NSS-3)
>
>mQINBFRO4UQBEADzzMOKKrxJ9bIzgLmMsTc/7E+h+7MeuHTEU79cynz9ORHPQTXY
><...truncated for brevity...>
>3iWKpPfXUgCqT85ByFOnYuqiW+YFV18Z/ISOZxO1v+rg5qRc0+W3PUwZX4HMUa8B
>r6RX
>=j3eL
>-----END PGP PUBLIC KEY BLOCK-----
>```
>
>I also have another Neo4j gpg key:
>```
>Distribution: (none)
>Name        : gpg-pubkey
>Version     : d37f5f19
>Release     : 58113cda
>Architecture: (none)
>Install Date: Mon 27 Feb 2017 08:57:31 PM EST
>Group       : Public Keys
>Size        : 0
>License     : pubkey
>Signature   : (none)
>Source RPM  : (none)
>Build Date  : Wed 26 Oct 2016 07:31:38 PM EDT
>Build Host  : localhost
>Relocations : (not relocatable)
>Packager    : Neo4j Admins <admins@neotechnology.com>
>Summary     : gpg(Neo4j Admins <admins@neotechnology.com>)
>```
>Additionally, I have attached the zypper log showing where the
>presumably correct key is found but cannot be verified against the
>current repomd.xml file.
>
>Let me know if there is anything more you need.
>[neo4j-zypper-gpgkey.txt](https://github.com/neo4j/neo4j/files/823124/neo4j-zypper-gpgkey.txt)
>
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/neo4j/neo4j/issues/6148#issuecomment-284595532

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by spacecowboy** [comment]
@frankthetank thanks for the info. I think we found the issue. It seems the repo metadata isn't signed everytime it is regenerated. I'm making some changes that hopefully will have it fixed.

**Comment by spacecowboy** [comment]
discussion moved to https://github.com/neo4j/neo4j/issues/8996

**Comment by spacecowboy** [comment]
This is now actually fixed. SUSE should not complain any more.
