### ISSUE TITLE
Neo4j Browser label not found 

### ISSUE THREAD

**Issue by darwinwu13** [neo4j/neo4j#6150]
So i just found this bug today, i use php as my server side language, using neoclient from neoxygen.
so what i do is create some index and unique index first , then i after that i go to browser to check it. and yes it created successfully, the strange thing is, my data is not created yet, but the label shown, 
on my neo4j 2.3.1-enterprise(startup license) exactly about two weeks ago  it wont show the label if there is no data, im satisfied with this, but today when i do test it again it become like neo4j 2.2 version again which is i dont like it. 

Then the bug is now i add a new node and it is created into Lessons Label, then i go to browser again, and the Lessons Label is not shown, but when i query it well it is there. the data is found.  i dont know if this is really a bug or my mistakes on configuration, but this is quite strange, since 2 weeks ago its just work fine, i dont know if my neo4j has been upgraded or not.

please help me thanks.

**Comment by ikwattro** [comment]
Hi @darkeus , can you please provide the code you are using for creating your Lessons nodes, or even the php code.

Secondly concerning the labels showing up or not, you can refer to this : 

https://github.com/neo4j/neo4j/issues/5665

**Comment by jexp** [comment]
Labels just for indexes / constraints are not shown when there is no data associated with them.
