### ISSUE TITLE
Disabling traversal endpoint is not as simple as removing the class form the classpath

### ISSUE THREAD

**Issue by AWinterman** [neo4j/neo4j#6155]
The traversal api class doesn't appear to ever appear in the classpath, so the directions to disabling it seem to be misleading. (re: http://neo4j.com/docs/stable/security-server.html#_arbitrary_code_execution)

**Comment by chrisvest** [comment]
Hey, sorry it took us so long to pick this up. We're going to add a setting for disabling the traversal endpoint script execution: #11078

**Comment by chrisvest** [comment]
The PR has been merged and the setting will appear in the next releases.
