### ISSUE TITLE
Download URL for 3.3.0-M02 seems broken

### ISSUE THREAD

**Issue by mindrones** [neo4j/neo4j#6161]
Hi,

the current [neo4j homebrew formula](https://github.com/Homebrew/homebrew/blob/9db8edac66a41b2dcbf0b3407c8d4f1cb020da08/Library/Formula/neo4j.rb) has this download URL: http://dist.neo4j.org/neo4j-community-2.3.1-unix.tar.gz. 
After editing that formula using the same scheme, curl can't download 3.3.0-M01 and 3.3.0-M02:

``` bash
$ brew install --devel neo4j
==> Downloading http://dist.neo4j.org/neo4j-community-3.3.0-M02-unix.tar.gz

curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "neo4j"
Download failed: http://dist.neo4j.org/neo4j-community-3.3.0-M02-unix.tar.gz
```

Is it a server problem of some sort or the download scheme is different now?
Thanks!

**Comment by jotomo** [comment]
You're looking for 3.0.0-M02, not 3.3.0-M02 I think :-)
Such as: http://dist.neo4j.org/neo4j-community-3.0.0-M02-unix.tar.gz

**Comment by mindrones** [comment]
Gosh, thanks! I must be tired :) Closing, sorry for the noise and btw happy holidays!
