### ISSUE TITLE
JSON Export Contains Duplicate Row for Tuple

### ISSUE THREAD

**Issue by typinator** [neo4j/neo4j#6169]
I have a single tuple / triple, say nodes A and B with a relationship R.

If I return the triple by specifying the Ids for A and B:=

``` cypher
MATCH (a)-[conn]->(b)
WHERE a.`object ID`=1660 AND b.`object ID`=1659
RETURN a As startSt,b As endSt,conn As relationship
```

 and export as JSON I get the 2 nodes (A and B) under 'nodes' followed by the connector under 'relationships'.

If, however, I just match the connector to return the triple:-

``` cypher
MATCH (a)-[conn {`connector ID`: 1048}]-(b)
RETURN a As startSt,b As endSt,conn As relationship
```

I get a different result in the JSON - I get two identical rows, each consisting of the nodes A, B followed by the relationship R.

In both cases the display of the single triple is identical as you'd expect. This appears to be a bug since in the second case the single triple displayed is described twice in the JSON output.

**Comment by chrisvest** [comment]
Your second query does not specify a direction for the relationship, so the pattern matches both ways. The two rows have the `a` and `b` nodes flipped.

**Comment by typinator** [comment]
I understand this but nevertheless it doesn’t match what is seen in the visualisation - the visualisation presents a single tuple with no duplication / redundancy and therefore you expect to the output tach this.

**Comment by jexp** [comment]
The UI deduplicates anyway as any node can be reached an returned via many paths

Also what you see is inherent pattern matching 

Von meinem iPhone gesendet

> Am 19.01.2016 um 18:32 schrieb typinator notifications@github.com:
> 
> I understand this but nevertheless it doesn’t match what is seen in the visualisation - the visualisation presents a single tuple with no duplication / redundancy and therefore you expect to the output tach this.
>
