### ISSUE TITLE
v3.0 release plan

### ISSUE THREAD

**Issue by mbande** [neo4j/neo4j#6173]
Hello all,
Is there any approximate release date for the first production ready 3.0.x version?
I wan't to see if it is a wise decision to base new projects on new introduced technologies (Bolt and drivers).

**Comment by cleishm** [comment]
Hi @mbande,

We typically don't comment too much on future release dates, but we're certainly hopeful that we'll see 3.0 released before the (northern hemisphere) summer.

Cheers,
Chris
