### ISSUE TITLE
OSGified Manifest Bolt / Driver

### ISSUE THREAD

**Issue by wem** [neo4j/neo4j#6182]
Hello

At the moment (3.0.0 M2) there are no OSGi information available in the Bolt / Driver jar. So we have to create an uber jar or re-package for it. Further it would be nice when we already can use it in a proper way (no exports of internals for example)

Regards
Michel

**Comment by jexp** [comment]
OSGi is not very high on our prio list. Usually people create their own wrapper / bundles when they need it. I don't think it such a big issue as it has to done for several libraries anyway?

**Comment by wem** [comment]
No, its really not a big issue. My consideration was just for a new library it would be nice to have.

**Comment by technige** [comment]
Closing as `wontfix`.
