### ISSUE TITLE
neo4j-shell does not execute Cypher statements

### ISSUE THREAD

**Issue by gokulreddy07** [neo4j/neo4j#6187]
Hi guys,
 I'm executing many queries with neo4j shell but i'm failing to execute two queries in neo4j shell,but same queries executes in browser
here is the error message
 ERROR (-v for expanded information):
    Unknown command '')'

 -host      Domain name or IP of host to connect to (default: localhost)
 -port      Port of host to connect to (default: 1337)
 -name      RMI name, i.e. rmi://<host>:<port>/<name> (default: shell)
 -pid       Process ID to connect to
 -c         Command line to execute. After executing it the shell exits
 -file      File containing commands to execute, or '-' to read from stdin. After executing it the shell exits
 -readonly  Connect in readonly mode (only for connecting with -path)
 -path      Points to a neo4j db path so that a local server can be started there
 -config    Points to a config file when starting a local server

Example arguments for remote:
    -port 1337
    -host 192.168.1.234 -port 1337 -name shell
    -host localhost -readonly
    ...or no arguments for default values
Example arguments for local:
    -path /path/to/db
    -path /path/to/db -config /path/to/neo4j.config
    -path /path/to/db -readonly

here is my query
LOAD CSV WITH HEADERS FROM 'file:///<pwd>/ingredients.csv' AS ingredient
WITH ingredient
MATCH (recipe:Recipe) WHERE recipe.name=ingredient.name
WITH ingredient, SPLIT(ingredient.ingredients,'&&') as ings, recipe
UNWIND ings as ing
WITH SPLIT(ing,'##') as in, recipe
CREATE (ingred:Ingredient {name:in[0]})
CREATE (ingred)<-[q:QUANTITY {quantity:in[1]}]-(recipe)
RETURN recipe,ingred;

**Comment by jexp** [comment]
`&&` is a separator in the shell and it seems that command line parsing is preceding cypher parsing.

You can try to work around it with using `'&'+'&'` instead

**Comment by gokulreddy07** [comment]
Thanks Michael issue solved.
