### ISSUE TITLE
Can't find JAR executable after building

### ISSUE THREAD

**Issue by telmotrooper** [neo4j/neo4j#6234]
After building Neo4j with "mvn clean install -DskipTests" to execute it I'm supposed to go to packaging/standalone/, pick the version I want (standalone-community), extract it from a tarball and run Neo4j, right? Well, after building, everything I see inside standalone-community are a pom.xml, a readme.txt and a src folder. Am I doing something wrong?

**Comment by spacecowboy** [comment]
@telmotrooper After you've executed `mvn clean install -DskipTests` in the root directory, go into `/packaging` and execute `mvn install -DskipTests` there as well. 

Then the tarballs will be built and you'll find them in `standalone/target/`
