### ISSUE TITLE
Performance RelationShip Merge

### ISSUE THREAD

**Issue by mabelanski** [neo4j/neo4j#6241]
Hi,

We coding a program for make an import of our sql database to neo4j. We use HTTP API and CSV import query for import all datas 

We have no probleme with MERGE on nodes but with MERGE on relationships take very very long time (take 15min just for MERGE 10 000 relations ...). We replaced it by CREATE command and it's really better faster but it's a problem because all relationships are duplicate ... and clear all of them with this command crash the server 

MATCH (s:Ticket)-[r:AskOn]-(t:Project)
WITH s, t, TAIL (COLLECT (r)) as rr
FOREACH (r IN rr | DELETE r)

And more database is big and more time MERGE command take 
We have lots of data, few millions of relationship and nodes

So what your recommandations ? We love neo4j but it's a real problem for us and we can't wait so much time to set up to date our neo4j database

We also coded 3 process : 
- One for up to date neo database everytime that we have change in our sql database, but some time we have problem and some data missing ... 
- On for set up first time all data from sql database to neo database, and it's very very slow, we still not succeed to insert all data :(
- On for set up to date the last week data of sql database to neo4j 

Thanks you for your helps ans recommandations

**Comment by jexp** [comment]
**Hi, can you share your MERGE / CREATE code?**
And also the query plan that the PROFILE statement provides?

For your second statement, you probably don't have enough RAM to keep all deleted tx-state in memory.

You might just batch that statement. Repeat until it returns 0

```
MATCH (s:Ticket)-[r:AskOn]-(t:Project)
WITH r LIMIT 100000
DELETE r
RETURN count(*);
```

For your initial insert you can also just generate CSV from your SQL database with the changes and use LOAD CSV.

I hope you are using parameterized statements when inserting the data.

You should be able to insert a few million nodes and relationships in a few minutes.

If you need to, we can also help you find consulting for your import setup.

**Comment by mabelanski** [comment]
Hi

Here the code and query plan of query

```
USING PERIODIC COMMIT 10000
LOAD CSV WITH HEADERS FROM 'http://ip/myfile.csv' AS row
MATCH (source:Ticket {Id: toInt(row.id_ticket)})
MATCH (target:Company {Id: toInt(row.id_client)})
MERGE (source)-[rel:`AskOn` {}]->(target);
```

![profil](https://cloud.githubusercontent.com/assets/13732495/12395054/169365fc-be08-11e5-941f-6b90de2f5a8c.png)

If i can, i prefer to stay with merge mode, because even on initial import there are some errors or connexions lost, so i need to restart import 

Thanks for your help

**Comment by jexp** [comment]
Which Neo4j version are you using? 
Looks like an older one.
Can you please try it on 2.3.1 ?

It looks like a dense-node-merge issue.

If you can't upgrade I can point you to some workarounds for this issue.
But please test it first with 2.3.1 to make sure.

**Comment by mabelanski** [comment]
Hi

We install the last version 2.3.2 but it's now more slow ... :(

![profile neo](https://cloud.githubusercontent.com/assets/13732495/12452379/c85b833e-bf96-11e5-9c30-f003708604ab.png)

**Comment by mabelanski** [comment]
Wait a minute, i forgot the index and CONSTRAINT UNIQUE on Id 
so i will retest it

**Comment by mabelanski** [comment]
ok it's now Fast and Fast !!!! I'm so happy thanks !!!!
For each 10 000 relations MERGE that take 3s ;)

Thanks for your help
