### ISSUE TITLE
Constraint on edges

### ISSUE THREAD

**Issue by kengz** [neo4j/neo4j#6247]
It seems that `CREATE CONSTRAINT ON` is only applicable to nodes, but not edges. Is this by design? Or it's something that can be introduced in the future?

**Comment by jexp** [comment]
We plan to provide constraints (cardinality, direction etc.) for relationships in the future too.
Some time in the 3.x series.

**Comment by kengz** [comment]
Thanks @jexp 
Is there a public forum to keep track of the neo4j roadmap? Or are these things closed?

**Comment by jexp** [comment]
Right now that plan is not public as it is a bit far out.
Btw. you can already constraint property existence on relationships in Neo4j Enterprise.
