### ISSUE TITLE
Deprecation warnings, and config issues

### ISSUE THREAD

**Issue by pboling** [neo4j/neo4j#625]
These kinds of messages in the log ([example](http://pastie.org/6506884)) seem like low hanging fruit.

1. `INFO ... Could NOT find resource [logback.groovy]`
2. `INFO ... Could NOT find resource [logback-test.xml]`
3. `ERROR ... Could not find resource corresponding to [custom-logback.xml]`
4. And this one

        WARNING! Deprecated configuration options used. See manual for details
        cannot configure writers and searchers individually since they go together

**Comment by jakewins** [comment]
Logging warnings resolved by https://github.com/neo4j/neo4j/commit/74cc8f0a2d9af713854733c3634e45b5a9ebc75b

The deprecation warning is from Neo4j itself, I think you are using deprecated config options in `neo4j.properties`, configuring lucene searchers in some way that is no longer supported?
