### ISSUE TITLE
UTC date/time format

### ISSUE THREAD

**Issue by kengz** [neo4j/neo4j#6281]
Currently on the documentation neo4j supports UTC timestamp, but only in milliseconds though; e.g. `return timestamp()` yields `1453473747575`.

Is there currently supports also for other ISO 8601 (UTC) formats, such as those [outlined here](https://en.wikipedia.org/wiki/ISO_8601#UTC); e.g. `2016-01-22T14:42:27.579Z`

More generally, what about these Date/Time formats [as seen in postgresql](http://www.postgresql.org/docs/9.1/static/datatype-datetime.html)?

**Comment by spacecowboy** [comment]
Neo4j does not yet have native support for other timestamp formats. So depending on your usecases, you either have to store the datetimes as either strings (however you like) or longs (to be able to compare with `timestamp()`).

**Comment by AndrewHannigan** [comment]
@spacecowboy Is this still the case?
