### ISSUE TITLE
Browser: hover text to explain icons in :sysinfo output

### ISSUE THREAD

**Issue by mbyrne00** [neo4j/neo4j#6308]
`:sysinfo` or `:play sysinfo` has icons and different background colours in the **Cluster** section. It would be nice if you could see a quick description of what these meant when you hover your mouse over them.

Also the (i) icon links to a neo4j documentation page on **Architecture** with no documentation on the meaning of the cluster output.

Examples:
- Hammer means master node
- Tick vs status smiley face ... what's the difference? What other options are there?
- Background turns yellow when the node isn't ready
- Any more??

This may be documented somewhere but I haven't been able to find it - either way it would be nice to have some contextual help.

**Comment by oskarhane** [comment]
Thanks for the feedback on this @mbyrne00. I'll put it in our backlog so it get's done.

**Comment by oskarhane** [comment]
This issue was moved to neo4j/neo4j-browser#144
