### ISSUE TITLE
Regression in 2.3.1 - Parameterisation of query causing sever performance issue (old bug #4357)

### ISSUE THREAD

**Issue by dgem** [neo4j/neo4j#6309]
We have an instance of about 25GB, which takes about 20 seconds to exectute a query:

```
MATCH (p:Person{uuid:{uuid}})<-[:HAS_MEMBER]-(m:Membership)
OPTIONAL MATCH (m)-[:HAS_ORGANISATION]->(o:Organisation)
OPTIONAL MATCH (m)-[rr:HAS_ROLE]->(r:Role)
...
RETURN collect ({p:p, m:m}) as rs
```

This is despite there being a suitable index:

```
Indexes
  ON :Concept(uuid)      ONLINE (for uniqueness constraint) 
  ON :Content(uuid)      ONLINE (for uniqueness constraint) 
  ON :Membership(uuid)   ONLINE (for uniqueness constraint) 
  ON :Organisation(uuid) ONLINE (for uniqueness constraint) 
  ON :Person(uuid)       ONLINE (for uniqueness constraint) 
  ON :Role(uuid)         ONLINE (for uniqueness constraint) 
  ON :Thing(uuid)        ONLINE (for uniqueness constraint) 

Constraints
  ON (thing:Thing) ASSERT thing.uuid IS UNIQUE
  ON (concept:Concept) ASSERT concept.uuid IS UNIQUE
  ON (person:Person) ASSERT person.uuid IS UNIQUE
  ON (role:Role) ASSERT role.uuid IS UNIQUE
  ON (membership:Membership) ASSERT membership.uuid IS UNIQUE
  ON (content:Content) ASSERT content.uuid IS UNIQUE
  ON (organisation:Organisation) ASSERT organisation.uuid IS UNIQUE
```

Curiously we saw the same performance hit when we ran the query in the UI and subsituted a value for the query:

```
MATCH (p:Person{uuid:"fc9817ea-41cc-31b3-bfaa-214ae3d57d88"})<-[:HAS_MEMBER]-(m:Membership)
OPTIONAL MATCH (m)-[:HAS_ORGANISATION]->(o:Organisation)
OPTIONAL MATCH (m)-[rr:HAS_ROLE]->(r:Role)
```

We fixed the literal query by telling Neo to use the `Person` index:

```
MATCH (p:Person{uuid:"fc9817ea-41cc-31b3-bfaa-214ae3d57d88"})<-[:HAS_MEMBER]-(m:Membership)
USING INDEX p:Person(uuid)
```

However the parameterised version was still doing a NodeScanByLabel when we added the `USING` clause. I then found issue #4357, which seemed to be a perfect match.
As per the work around in this issue we added a `PLANNER RULE` which has was suggested in #4357. 

We can get the query to execute in less than 1 second if we modify the original to:

```
PLANNER RULE MATCH (p:Person{uuid:{uuid}})
USING INDEX p:Person(uuid)
MATCH (p)<-[:HAS_MEMBER]-(m:Membership)
OPTIONAL MATCH (m)-[:HAS_ORGANISATION]->(o:Organisation)
OPTIONAL MATCH (m)-[rr:HAS_ROLE]->(r:Role)
...
```

_(I split the original `MATCH` into two sepertate statements to give maximum hints to the optimiser)_

It may be that we have two bugs:
1. Parameterised query is ignoring an index and requires a `PLANNER RULE` and `USING` to fix
2. Literal query also ignores the index and needs a `USING` to fix

This issue is to report the bug with the parameterised query, if you'd like a seperate issue for the literal one let me know. Likewise, let me also know if you need some recreational or debug info.

Thanks

**Comment by jexp** [comment]
Did you try 2.3.2 ?

Two unrelated observations:

in general for your query reducing the cardinality between optional matches if your potential degree in those is > 1 is advised, by using `WITH` with either `distinct` or aggregation.
e.g. `WITH p, collect(m)`

Also if you just want to use these matches as conditions, then a `WHERE exists (pattern)` could also help.

**Comment by dgem** [comment]
Hi, nope I've not tried 2.3.2 as I didn't see it had popped out :)
We have discovered a corruption of a count file (neostore.counts.db.*) so you might want to hold off until I can verify that the problem exisits on a fresh DB (or at least one where that file is not corrupted) as its quite possible that this is effecting the optimiser

**Comment by jexp** [comment]
Just delete the counts store, it is regenerated. It only contains database statistics.

**Comment by Mats-SX** [comment]
@dgem Thanks a lot for reporting this issue. Did you check whether the work we did in 2.3.2 solved this problem on your data?

**Comment by dgem** [comment]
@Mats-SX I've been unable to reproduce since deleting and allowing the neostore.counts.db.\* files.
@jexp the comments about reducing cardinality is very interesting and I'm looking at this
Obviously there is a worry about the corruption of these files, but this is a seperate issue.

Since the problem no longer occurs with the rebuilt counts files, I suggest we should close the issue. I'm not sure if you use any particular tags for closing - so I'll leave you to tag and close.

Many thanks
Dan

**Comment by Mats-SX** [comment]
Thanks @dgem, and please reopen this issue if you re-encounter it somehow.
