### ISSUE TITLE
acquireWriteLock with timeout

### ISSUE THREAD

**Issue by pietermartin** [neo4j/neo4j#631]
Add a feature to Transaction.acquireWriteLock( PropertyContainer entity ) to include a timeout.

That way a client can be sure that threads will throw an exception rather than waiting  indefinitely.

Thanks

**Comment by jakewins** [comment]
As this is a feature request, relabeling as such and tagging it as a kernel feature

**Comment by rh78** [comment]
Yeah yeah yeah: https://github.com/neo4j/neo4j/pull/8062 -> its in Neo4J 3.2

**Comment by burqen** [comment]
Closing this issue since there is a solution (https://github.com/neo4j/neo4j/pull/8062). Feel free to open this again if this solution is not sufficient.
