### ISSUE TITLE
Allow ->[:REL]-> for programmer productivity

### ISSUE THREAD

**Issue by rulatir** [neo4j/neo4j#6320]
At least for the case of right-pointing relation arrows, please allow the minus-greater arrow on _both_ sides of [].

Rationale: the '->' key sequence is carved deeply into the muscle memory of most programmers. When I think 'arrow', I type an arrow, and I absolutely **do** think 'arrow' when I think 'directed graph edge'. Extra arrow before [] is the most frequent syntax error I make, so frequent it cuts significantly into my productivity. It is _very_ hard to unlearn typing '->' whenever you think 'arrow'.

Please make it allowed syntax!

**Comment by cleishm** [comment]
Discussion and suggestions for the Cypher query language are now handled as part of the openCypher initiative: http://www.opencypher.org/. They have a forum where you can share your thoughts and feedback: https://groups.google.com/forum/#!forum/opencypher
