### ISSUE TITLE
csv import tool sensitive to whitespace

### ISSUE THREAD

**Issue by tkvogt** [neo4j/neo4j#6331]
Using the import tool with a csv-header like this:

uniqueFunction:ID, functionName

results in unintuitive behaviour. It is possible to extract the first value with a cypher query. The other value is displayed correctly in the spring-layout-visualization but seems to be null when queried.

Only after dumping the json I understood that the csv import tool keeps the whitespace at the beginning of the second value: " functionName".

Not using whitespace in a csv header solves the problem, but in my opinion whitespace in the beginning and end of a string should be deleted.

**Comment by spacecowboy** [comment]
I agree that this can pose issues. A very unscientific survey shows that our current behavior is also the default behavior of other parsers ([python](https://docs.python.org/2/library/csv.html), [nodejs](http://csv.adaltas.com/parse/)), but that they also offer options for ignoring the whitespace.

We recently made a change to ignore whitespace for numerical values: https://github.com/neo4j/neo4j/pull/6321 and I believe it would be sensible to include a command line option (`--trim`) to enable that functionality also for strings/headers.

**Comment by tinwelint** [comment]
@tkvogt Can this be closed bow since the related PR has been merged?

**Comment by tkvogt** [comment]
OK
