### ISSUE TITLE
Commit deadlock error should have dedicated error code

### ISSUE THREAD

**Issue by mbyrne00** [neo4j/neo4j#6336]
When using the REST API, if get deadlock errors we usually get back an error code: `Neo.TransientError.Transaction.DeadlockDetected`, however if we encounter deadlock errors during commit we get a generic error code: `Neo.DatabaseError.Transaction.CouldNotCommit`.

An example is below with an error message.

```
Neo.DatabaseError.Transaction.CouldNotCommit: ForsetiClient[5] can't acquire ExclusiveLock{owner=ForsetiClient[8]} on RELATIONSHIP(25531575), because holders of that lock are waiting for ForsetiClient[5].
 Wait list:ExclusiveLock[
Client[8] waits for [5]]
```

The problem with this is that it makes it difficult and delicate for us to categorise deadlocks and treat them in a specific way (retry after a random sleep between x and y for example). We need to look at the error code and look for a substring in the error message ... yuck!

It would be nice if we could have a specific error code for deadlocks that occur during a commit, such as 
`Neo.DatabaseError.Transaction.CommitDeadlockDetected` (names aren't my strength but you get the point).

**Comment by spacecowboy** [comment]
Sounds like a reasonable improvement.

**Comment by chrisvest** [comment]
We, uhh, should not get deadlocks during commit _at all_.

In two-phase locking, commit time should only release locks, not take them. If you somehow still have the complete stack trace, then that might be historically interesting. Looking at the code now, I don't think it's possible to get deadlocks during commit, but if it is then let's have an issue about that.
