### ISSUE TITLE
How can we copy labels from one node to another in one cypher?

### ISSUE THREAD

**Issue by zhanghan987** [neo4j/neo4j#6350]
The question is just as the title, and the cypher statement is just like the follow:
    Match (n: test) CREATE (copy : LABELS(n)) set copy = n
Its purpose is to create a node with the same properties and same labels as the other node, but it doesn't work now because we can't use a expression like "LABELS(n)" to set lobel to a node. 
How can I make it work?

**Comment by cleishm** [comment]
Hi @zhanghan987 ,

This issue tracker is for reporting and tracking source code issues in the Neo4j code base. We kindly ask that questions on usage be posted to [stackoverflow](http://stackoverflow.com/questions/tagged/neo4j) or in the [google group](http://groups.google.com/group/neo4j).

Cheers,
Chris
