### ISSUE TITLE
Is there a way to avoid cycling?

### ISSUE THREAD

**Issue by AlexKovalevych** [neo4j/neo4j#6360]
Having such graph: http://console.neo4j.org/r/9cwo4x

The query works fine for the most of my cases, but in this particular case it takes an eternity to complete and returns many duplicates. Is there a way to avoid such behavior?

**Comment by tkroman** [comment]
Github issues is a place for bug reports and/or feature requests etc. You should try asking on Stackoverflow instead.

Also, what is the purpose of `collect(x)` in your code?

**Comment by AlexKovalevych** [comment]
Thank you for response. Sorry, my example was incomplete, and removing `collect` solved that case. Here is an updated graph: http://console.neo4j.org/r/rirz9f

The problem i'm trying to solve here is that it does too many operations when i try to get all connected Uid (U) nodes to the given node under any relation nesting level, so it can be any level:

 `(U)->(C)->(U)->(C)->(U)->...`

It should return only 2 Uid nodes in the console example, but does too many operations and fails.

**Comment by jexp** [comment]
Did you try?

```
MATCH (u:Uid),(x:Uid)
WHERE u.uid = '1' AND u <> x
MATCH p = shortestPath((u)-[r:DMP*]-(x))
WHERE length(p)> 1
RETURN DISTINCT u, x, length(p)
```

**Comment by spacecowboy** [comment]
closing as it is not an issue.

**Comment by AlexKovalevych** [comment]
@jexp yup, that did it, thank you!
