### ISSUE TITLE
Packaging Bug: 3.0 M03 Community Mac DMG does not enable Bolt

### ISSUE THREAD

**Issue by leehericks** [neo4j/neo4j#6373]
There are no setting options for Bolt in this package and running the database does not open the appropriate ports.

I installed the Nightly Enterprise tar package and everything runs as expected.
I have not tried the Nightly Community tar package.

**Comment by benbc** [comment]
@leehericks Bolt is enabled by default in the 3.0.0 GA release. Enjoy!
