### ISSUE TITLE
Support for Live Queries

### ISSUE THREAD

**Issue by siderakis** [neo4j/neo4j#6374]
See: RethinkDB, Firebase and OrientDB

**Comment by craigtaverner** [comment]
This issue does not define what 'Live Queries' means. I did a search for 'live queries' and found two possible descriptions:

* pagination over large results, and suspect that is perhaps what this issue might be above.
* queries that block until a condition is met, and respond the moment that condition is met. See https://orientdb.org/docs//2.1.x/Live-Query.html

For pagination, I think the discussions in the issue at https://github.com/neo4j/neo4j/issues/3125 are worth reviewing.

For the blocking queries, this would need to be considered by the drivers stack. I suspect this might be possible with procedures that share state with transaction triggers, but that would be a custom solution.

**Comment by technige** [comment]
This issue does not give enough detail about the feature request, therefore closing. Please reopen if you can provide a full description of what you'd like to see.
