### ISSUE TITLE
CSV export should use quotes for text

### ISSUE THREAD

**Issue by JohnLonginotto** [neo4j/neo4j#6375]
CSV is a format with three special characters - a row delimiter (usually \n) and a column delimiter (usually ,) and a quote character (usually the pipe |)
The quote character is used when the text to be converted to CSV already contains a row or column delimiter. If it does, that whole field is quoted with the pipe. If pipes are also already found in the text, they are escaped with .

The bug is that Neo4J's CSV exporter through the HTTP interface doesn't quote text with a newline in it. It may also not quote text with a comma in it - I haven't tested.

```
match (n)
return n.id,n.textWithNewlines
```

from the HTTP interface, and then download the result in CSV, you might find a result like:

> n.id,n.textWithNewlines
> 1,This is some text
> that
> contains newlines
> 2,This is also
> some text
> that contains
> newlines

Thanks for looking into it and as always thank you so much for developing Neo4j in the first place - it's absolutely awesome!!!! :D :cake:

**Comment by JohnLonginotto** [comment]
Also, not really the same bug but as a result of trying to force quoting with some character, I ran

`return n.id,"'",n.textWithNewlines,"'"`
and 
`return n.id,'"',n.textWithNewlines,'"'`

both result in a parse error - wether I escape the quotes or not - because it seems that you cant insert the same static column of text twice. So even 

`return n.id,'banana',n.textWithNewlines,'banana'`

doesn't work. Not sure if bug or feature :P

**Comment by jexp** [comment]
Btw the default quote character is in most cases just a double quote `"`.

**Comment by jexp** [comment]
I just tried it and it works well,

when I use `return "1,\n2"`

which returns a result that exported to CSV looks like this which is correctly quoted in my view.

```
field
"1,
2"
```

**Comment by JohnLonginotto** [comment]
Oh, I thought double quote was rarely used because its found frequently in text (and thus requires more escaping). I guess it's different in different areas/languages :) Good to know!

I will try and create a reproducible example for you right away :)

**Comment by jexp** [comment]
Actually double quote are most frequently used. And double quotes in themselves are escaped by doubling them. i.e. a string like `a"b` is turned into  `"a""b"`

**Comment by jexp** [comment]
the thing you tried with the single quotes in multiple columns would rather be done by string concatenation.

i.e. `return n.id as id,'"'+n.textWithNewlines+'"' as text`

Although not sure what this would change in this case.

**Comment by mbyrne00** [comment]
@jexp: I've noticed that comma values by themselves handled in neo 2.3.2 CSV export. Example value that is not escaped "test, string" (without quotes). Saw this while trying to export data from a server, so I need to try a few workarounds.

As soon as I put a quote in my string it will add the extra quotes to handle it. I haven't had a chance to try in a newer version, but thought I'd pass on my feedback in the mean time.

**Comment by maysara** [comment]
although closed, I'm still facing a nightmare unable to control the quoting of all fields. this should at least be configurable in the neo4j conf.
