### ISSUE TITLE
[Feature request] [Java API] Expose more index search features in API

### ISSUE THREAD

**Issue by tkroman** [neo4j/neo4j#6379]
It would be nice if some index search facilities like range or prefix search were exposed via public API. I have in mind something like:

```
db.findNodes(label, propertyKey, startsWith("prefix"));
db.findNodes(label, propertyKey, range(0, 100));
db.findNodes(label, propertyKey, rangeInclusive(0, 100));
```

etc.

Also, some kind of toolkit for construction of general logical expressions like

```
db.findNodes(label, and(startsWith(stringKey, prefix), range(longKey, 0, 100), ...))
```

After looking through the Cypher backend sources, there's a solid foundation behind these features already present. For example, MongoDB's Scala and Java drivers provide similar features, as do other NoSQL APIs.

**Comment by DFoxinator** [comment]
+1

Though the workaround isn't terrible (you can just use Cypher), if you're using the Java API then there's a good chance it's partly for performance and you'd rather not have to mix in Cypher queries. I ran into this issue recently. http://stackoverflow.com/questions/33711643/neo4j-java-api-schema-index-range-lookup

**Comment by tkroman** [comment]
@DFoxinator I know, right? Especially when you are asking if it is possible to do an _index_ search and they suggest using manual filtering :grin: I just hope this FR will be at least considered.
