### ISSUE TITLE
http://neo4j.com/developer/example-data/#_importing_data_sets github link 404

### ISSUE THREAD

**Issue by paul-shannon** [neo4j/neo4j#6383]
The github link provided for the full cineasts movie database seems to be broken:

  http://github.com/SpringSource/spring-data-neo4j/tree/master/spring-data-neo4j-examples/cineasts

The direct zip file link -does- work, which is good, but apparently this is an out-of-date database dump, obliging the novice user to parse through the java stacktrace, create a config file with 

```
allow_store_upgrade=true
```

and then call

 neo4j-shell -path cineasts_12k_movies_50k_actors.db -config neo4j.config

These small fixes would be nice to see!

Thanks for the fine software.

 -0 Paul

**Comment by jexp** [comment]
Hi @paul-shannon thanks a lot for your feedback.

Where did you see this link?

The new example for SDN4 is here (along with many other example projects):
- https://github.com/neo4j-examples/sdn4-cineasts
- https://github.com/neo4j-examples/cineasts-spring-data-neo4j

Meanwhile you can use:
- http://example-data.neo4j.org/files/cineasts_12k_movies_50k_actors-2.3.zip
- http://example-data.neo4j.org/files/cineasts_12k_movies_50k_actors-2.2.zip

**Comment by paul-shannon** [comment]
Hi jexp,

The broken link to github is on 

```
http://neo4j.com/developer/example-data/
```

See the image below.

Related, smaller question:  is there a comparable download for the much smaller movie database used in the neo4j cypher tutorials?

Thanks!
- Paul

![image](https://cloud.githubusercontent.com/assets/2480712/12925160/c8091c36-cf11-11e5-8327-be6d656320a7.png)

**Comment by jexp** [comment]
The create statement for the small dataset used in the tutorials is contained within the browser.
Just run `:play movies` and copy the cypher statement to a file.

**Comment by jexp** [comment]
Thanks a lot, we wanted to work on and improve this page in the next few weeks anyway.

**Comment by jexp** [comment]
You can track the progress here, and feel free to send pull-requests.
Cheers Michael

https://github.com/neo4j-contrib/developer-resources/blob/gh-pages/working-with-data/example-data/example-data.adoc

**Comment by jjaderberg** [comment]
Updated the link to point to examples repo.
