### ISSUE TITLE
Browser: GRASS can get rearranged if the Label hierarchy is changed after style changes have been made in the Browser

### ISSUE THREAD

**Issue by Joshfindit** [neo4j/neo4j#6402]
To reproduce:
1. Start with each node type having it's own label (3-4 is helpful).
2. Populate the database and return the graph.
3. Change the styles for each node.
4. Dump the database.
5. Change the nodes to be Subclasses. Add a root class.
6. Populate the database and return the graph.
7. Change the style for the root class. Notice that it's subclassed nodes have changed style.
8. Change the style for the subclassed nodes: they are now overridden.

[GRASS can get rearranged.example.md.txt](https://github.com/neo4j/neo4j/files/125367/GRASS.can.get.rearranged.example.md.txt)

**Comment by oskarhane** [comment]
This issue was moved to neo4j/neo4j-browser#145
