### ISSUE TITLE
Minimum memory and disc space for small database

### ISSUE THREAD

**Issue by ghost** [neo4j/neo4j#6442]
I'd like to use neo4j on a small home server, which has 2G memory and 32GB disc space. I'd like to give neo4j 512M memory and 8GB disc space. The database will be small, only about 20.000 nodes and not too many connections between them. Is this possible? How can I set the memory and disc space limits on Ubuntu (14.04 server)?

According to the manual http://neo4j.com/docs/stable/deployment-requirements.html the minimum memory is 2G and the minimum disc space is 10GB. I am not sure whether this is correct, since by http://lattice.cf/docs/docker-image-examples/ they use 512M memory and I measured 140M memory usage by the community edition on a small database. What is the real minimum?

**Comment by jexp** [comment]
See my answer on stackoverflow

The real minimum depends on your use-cases

Von meinem iPhone gesendet

**Comment by ghost** [comment]
@jexp: Thanks!

( http://stackoverflow.com/a/35423902/607033 )
