### ISSUE TITLE
3.0.0 write.lock file not being removed after neo4j stops

### ISSUE THREAD

**Issue by tasmar** [neo4j/neo4j#6447]
I have been testing out the 3.0.0-M03 docker image and noticed that when I mount /data to a volume on my host, then stop the container, write.lock is not removed, along with other files not being touched/cleaned up, which is preventing me from running a batch script to populate some data.

To recreate the issue I went through these steps.
1. Pull the image `docker pull neo4j/neo4j:3.0.0-M03`
2. Create a directory on the host that will be a mount for the data `mkdir /home/neo4j-data`
3. Start a new container the mounts to this directory `docker run -d --name neo4j-test -p 7474:7474 -v /home/neo4j:/data neo4j/neo4j:3.0.0-M03`
4. Navigate to the write.lock file `/data/databases/graph.db/schema/label/lucene/labelStore/1/write.lock`
5. Stop the container `docker stop neo4j-test`
6. The write.lock file should be gone now but it is not.  

I tested this in neo4j:2.3.0 and the write.lock file does get removed after a docker stop, granted the directory locations are different from v2.3 to v3.0.

**Comment by MishaDemianenko** [comment]
Hey @tasmar, thank you for reporting, we will take a look! 
Will keep you posted.

**Comment by MishaDemianenko** [comment]
Hey @tasmar write.lock is no longer removed by lucene and it's presence does not mean locked index anymore.  Corresponding jira issue is: https://issues.apache.org/jira/browse/LUCENE-5612 and corresponding commit is here: https://github.com/apache/lucene-solr/commit/14a9e19e18dcac85272deb197f74a319d954e303
Hope this helps!

**Comment by tasmar** [comment]
@MishaDemianenko thank you for the quick reply!  I will play around with this in the next day or so and get back to you.

**Comment by tasmar** [comment]
We testing this and you are correct.  The write.lock file does not prevent us from running our batch script for 3.0.0-M03.  Thank you for all your help!
