### ISSUE TITLE
White spaces are ignored when setting property values in Neo4j 3.0.0 M3

### ISSUE THREAD

**Issue by webzhao** [neo4j/neo4j#6468]
Hi,

I found a bug in Neo4j version 3.0.0 M3. Suppose there is a node:

```
(n {content: 'a b'})
```

Note that there is **ONE SPACE** between `a` and `b`. When updating the `content` property value using:

```
set n.content='a    b'
```

The value of property `content` remains `a b`. It seems that, white space changes are ignored when updating property value.

**Comment by jexp** [comment]
I think that's only a visualization thing. As html collapses multiple whitespace into one.
Try it with code or look into the </> tab for the raw response.

**Comment by webzhao** [comment]
@jexp It's not a visual thing.

![image](https://cloud.githubusercontent.com/assets/1564776/13170995/3f08f268-d72b-11e5-830c-480e0d0b82ba.png)
