### ISSUE TITLE
Cypher based SET of property using a long value loses precision

### ISSUE THREAD

**Issue by SteveDraper** [neo4j/neo4j#6488]
In the Neo browser UI (same applies to other vehicles, but this is illustrative) try the following:

create (t:Test {along:92233720368547750}) return t

The value specified is several digits short of the max value for a 64-bit long, but the resulting (returned) node's property value differs from that set.

Hypothetically I **think** that the value is being converted to a floating point value then back to a long at some point, with loss of precision as a result.

I am running 2.3.1on a Mac

**Comment by cleishm** [comment]
This is a known issue that only affects the rendering of the result in the browser. The actual data sent to, and returned from, Neo4j will be the correct value with no loss of precision.

Because the response is returned using JSON, and browsers inherently treat all numbers in JavaScript as floating point, the reading and then rendering of the response loses precision.

We do plan to use a different mechanism for communication in future versions, that is not JSON and will make it possible to avoid this issue.

**Comment by jexp** [comment]
you can test that by running `MATCH (t:Test) RETURN toString(t.along)`

**Comment by SteveDraper** [comment]
Fascinating!  It returns the correct value.  Thanks for the insight to that degree.

However, the case I posted was an attempt to simplify to a minimal case what I had originally run across, and the explanation does not account for some slightly more complex behavior.  Consider this:

create (t:Test {along:16000000000000001}) return toString(t.along%16000)

This return 0.0 (note that it returns a float as well as it being incorrect).  I have also verified that the JSON contains 0.0.  This implies a related issue server-side in the modulo calculation

**Comment by jexp** [comment]
works for me

```
return 16000000000000001 % 16000, toString(16000000000000001 % 16000);
+-----------------------------------------------------------------+
| 16000000000000001 % 16000 | toString(16000000000000001 % 16000) |
+-----------------------------------------------------------------+
| 1                         | "1"                                 |
+-----------------------------------------------------------------+
1 row
132 ms
```

**Comment by jexp** [comment]
Ok, you're right, that's really weird:

```
create (t:Test {along:16000000000000001}) return toString(t.along%16000);
+-------------------------+
| toString(t.along%16000) |
+-------------------------+
| "0.0"                   |
+-------------------------+
1 row
Nodes created: 1
Properties set: 1
Labels added: 1
neo4j-sh (?)$ match (t:Test) return toString(t.along);
+---------------------+
| toString(t.along)   |
+---------------------+
| "16000000000000001" |
+---------------------+
neo4j-sh (?)$ match (t:Test) return toString(t.along%16000);
+-------------------------+
| toString(t.along%16000) |
+-------------------------+
| "0.0"                   |
+-------------------------+
neo4j-sh (?)$ match (t:Test) return t.along%16000;
+---------------+
| t.along%16000 |
+---------------+
| 0.0           |
+---------------+
```

**Comment by jexp** [comment]
Seems to loose precision b/c it converts them into a double first:

https://github.com/neo4j/neo4j/blob/3.0/community/cypher/cypher-compiler-3.0/src/main/scala/org/neo4j/cypher/internal/compiler/v3_0/commands/expressions/Modulo.scala#L23

**Comment by jexp** [comment]
@SteveDraper what's your use-case for using large integer numbers?

**Comment by SteveDraper** [comment]
@jexp it's nothing we cannot work around.  In this case we apply a 64-bit hash as a (indexed) property on a large set of nodes, to allow us to query for a pseudo-random sample by specifying a range on said hash.  Restricting the hash to 56 bits (say) is a perfectly good work-around.

**Comment by petraselmer** [comment]
The fix for this has now been merged (https://github.com/neo4j/neo4j/pull/6756), and will be part of the next release.
