### ISSUE TITLE
Cannot start Neo4j Server via Powershell

### ISSUE THREAD

**Issue by brunotomas** [neo4j/neo4j#6502]
I'm having problems to start Neo4j server through PowerShell.

```
PS C:\Users\brunotomas> 'E:\neo4j' | Start-Neo4jServer -Console -Wait
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't obtain class com.sun.jna.CallbackReference.AttachOptions
        at com.sun.jna.Native.initIDs(Native Method)
        at com.sun.jna.Native.<clinit>(Native.java:115)
        at com.sun.jna.Structure.<clinit>(Structure.java:132)
        at org.rzo.yajsw.WindowsXPProcess.start(WindowsXPProcess.java:1474)
        at org.neo4j.wrapper.ServerProcessConsole.doStart(ServerProcessConsole.java:45)
        at org.neo4j.wrapper.ServerProcess.<init>(ServerProcess.java:115)
        at org.neo4j.wrapper.ServerProcessConsole.<init>(ServerProcessConsole.java:31)
        at org.neo4j.wrapper.NeoServiceWrapper.launchAsConsoleApp(NeoServiceWrapper.java:48)
        at org.neo4j.wrapper.NeoServiceWrapper.main(NeoServiceWrapper.java:35)
1
```

Any ideas of what is going on?

**Comment by spacecowboy** [comment]
@brunotomas What version of Neo4j are you trying to start?

**Comment by brunotomas** [comment]
@spacecowboy Version 2.3.2 (zip)
Running on a Windows Server 2008 with JDK 8

**Comment by brunotomas** [comment]
@spacecowboy Any ideas of what might have causing this behavior? I'm pretty sure the dependencies are ok, since it was working fine last week. I'm really lost here.

**Comment by jexp** [comment]
Can you see if you have anything set in environment variables for JAVA_HOME or CLASSPATH or JAVA_OPTS that is unusual?

**Comment by jexp** [comment]
@glennsarti any ideas?

**Comment by glennsarti** [comment]
Hi @brunotomas.  That's a weird error.  It's failing to launch the Windows Service wrapper.  Can you run your console start command with -Verbose i.e. `'E:\neo4j' | Start-Neo4jServer -Console -Wait -Verbose` and that should hopefully output the java command to launch the wrapper.  Also, if possible can you post your windows-wrapper config file.  It should be `conf/neo4j-wrapper.conf`

**Comment by brunotomas** [comment]
Hi, @glennsarti 
Here's the verbose output:

```
PS C:\Users\brunotomas> 'E:\neo4j' | Start-Neo4jServer -Console -Wait -Verbose
VERBOSE: Performing operation "Start Neo4j" on Target "C:\Program Files\Java\jre1.8.0_74\bin\java.exe
-DworkingDir="E:\neo4j" -Djava.util.logging.config.file="E:\neo4j\conf\windows-wrapper-logging.properties"
-DconfigFile="conf/neo4j-wrapper.conf" -DserverClasspath="lib/*.jar;system/lib/*.jar;plugins/**/*.jar;./conf*"
-DserverMainClass=org.neo4j.server.CommunityBootstrapper -jar "E:\neo4j\bin\windows-service-wrapper-5.jar"".
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't obtain class com.sun.jna.CallbackReference.AttachOption
s
        at com.sun.jna.Native.initIDs(Native Method)
        at com.sun.jna.Native.<clinit>(Native.java:115)
        at com.sun.jna.Structure.<clinit>(Structure.java:132)
        at org.rzo.yajsw.WindowsXPProcess.start(WindowsXPProcess.java:1474)
        at org.neo4j.wrapper.ServerProcessConsole.doStart(ServerProcessConsole.java:45)
        at org.neo4j.wrapper.ServerProcess.<init>(ServerProcess.java:115)
        at org.neo4j.wrapper.ServerProcessConsole.<init>(ServerProcessConsole.java:31)
        at org.neo4j.wrapper.NeoServiceWrapper.launchAsConsoleApp(NeoServiceWrapper.java:48)
        at org.neo4j.wrapper.NeoServiceWrapper.main(NeoServiceWrapper.java:35)
1

```

And the neo4j-wrapper.conf: 

```
#********************************************************************
# Property file references
#********************************************************************

wrapper.java.additional=-Dorg.neo4j.server.properties=conf/neo4j-server.properties
wrapper.java.additional=-Dlog4j.configuration=file:conf/log4j.properties

#********************************************************************
# JVM Parameters
#********************************************************************

wrapper.java.additional=-XX:+UseG1GC
wrapper.java.additional=-XX:-OmitStackTraceInFastThrow
wrapper.java.additional=-XX:hashCode=5

# Uncomment the following lines to enable garbage collection logging
#wrapper.java.additional=-Xloggc:data/log/neo4j-gc.log
#wrapper.java.additional=-XX:+PrintGCDetails
#wrapper.java.additional=-XX:+PrintGCDateStamps
#wrapper.java.additional=-XX:+PrintGCApplicationStoppedTime
#wrapper.java.additional=-XX:+PrintPromotionFailure
#wrapper.java.additional=-XX:+PrintTenuringDistribution

# Java Heap Size: by default the Java heap size is dynamically
# calculated based on available system resources.
# Uncomment these lines to set specific initial and maximum
# heap size in MB.
#wrapper.java.initmemory=512
#wrapper.java.maxmemory=512

#********************************************************************
# Wrapper settings
#********************************************************************
# path is relative to the bin dir
wrapper.pidfile=../data/neo4j-server.pid

#********************************************************************
# Wrapper Windows NT/2000/XP Service Properties
#********************************************************************
# WARNING - Do not modify any of these properties when an application
#  using this configuration file has been installed as a service.
#  Please uninstall the service before modifying this section.  The
#  service can then be reinstalled.

# Name of the service
wrapper.name=Neo4j-Server

# User account to be used for linux installs. Will default to current
# user if not set.
wrapper.user=

#********************************************************************
# Other Neo4j system properties
#********************************************************************
wrapper.java.additional=-Dneo4j.ext.udc.source=zip
```

**Comment by brunotomas** [comment]
@jexp Actually, I don't have these environment variables. 
I have "C:\ProgramData\Oracle\Java\javapath" in my Path variable. 
Does it ring any bells?

**Comment by glennsarti** [comment]
Cross referencing;
http://stackoverflow.com/questions/35562203/neo4j-server-not-starting

**Comment by glennsarti** [comment]
So digging around the "java.lang.UnsatisfiedLinkError" is caused at runtime by trying to load an assembly that doesn't exist.  It looks like it's trying to load com.sun.jna.CallbackReference.AttachOption.  Given that's a Sun assembly I suspect there's something wrong with your java install or environment.  I noticed that you mentioned having C:\ProgramData\Oracle... in your path statement, yet java is from C:\Program Files... 

So it sounds like we've got some cross-java-instance-bad-things happening as from the brief reading I did, the class loader will search the PATH environment variable.

Save your path setting and remove the C:\ProgramData\Oracle...reference.  This will require a reboot to take effect.  If this works then we need to figure out if you still need that directory in the path. Or can we make the other application use the Oracle java install using a per process environment variable.

Note - C:\ProgramData is not the usual place for application binaries on Windows.

ping @jexp  @brunotomas

**Comment by brunotomas** [comment]
@glennsarti Removed the reference, but it didn't work. 
I think it is looking for java in the right place, given that the verbose output indicates the correct java path: 

`VERBOSE: Performing operation "Start Neo4j" on Target "C:\Program Files\Java\jre1.8.0_74\bin\java.exe
`

Do you have any other suspicions about what can cause this error?

**Comment by glennsarti** [comment]
@brunotomas  Have you tried using any of the other java tools? shell, import etc?

**Comment by glennsarti** [comment]
@brunotomas A more indepth tool would be to use Process Monitor during the load and to see what DLL it's trying to load and from which directories.  Are you familiar with using procmon?

**Comment by brunotomas** [comment]
@glennsarti  No, I just tried to start my server as a windows service, and I had the problem you saw on Stackoverflow.If I try to start on console, it gives this exception. I thought the first was linked to this exception aborting the start process and the service not receiving an answer (timeout).

About the other question, I am not familiar with procmon.

**Comment by glennsarti** [comment]
@brunotomas Yeah the 1503 is expected if the service wrapper never starts, which is what's happening here.  I still suspect a broken java environment but it's difficult to test.

1) uninstall and reinstall java, but that's really heavy handed
2) If you have another windows box somewhere, install java on that, copy the neo4j instance to it and try and run the console there.  That will prove that the neo4j instance and config is fine and the environment is broken.

I'll have a quick look at my java config and see what file it's trying to load.

**Comment by glennsarti** [comment]
So all of the JNI/JNA stuff is inside the windows-service-wrapper jar.  I did notice I had jna DLLs in my temp folder, presumably the architecture specific jnidispatch DLLs are extracted to temp and then referenced at run time.  It could be a long shot, but perhaps purge your %TMP% as much as possible and try again.

**Comment by brunotomas** [comment]
@glennsarti I've found three JNA DLLs on my Temp folder. I removed them and tried to run server on console mode. Same error.

**Comment by brunotomas** [comment]
After almost a month I have finally found the problem. Neo4j was misusing jnidispatch.dll from another application (Tableau).  Just removed the reference from `PATH` and it works.

Thanks for the help.

**Comment by glennsarti** [comment]
@brunotomas Wow....yeah, would've been tough to find.  Thanks for letting us know.  Did you want to close this issue?

**Comment by brunotomas** [comment]
@glennsarti  Yes, please

**Comment by glennsarti** [comment]
@jexp Issue can be closed.

**Comment by brunotomas** [comment]
Actually, just figured out that I can start on console but not as a service.

```
Start-Service : Service 'Neo4j-Server (Neo4j-Server)' cannot be started due to the following error: Cannot start servi
e Neo4j-Server on computer '.'.
At E:\neo4j\bin\Neo4j-Management\Start-Neo4jServer.ps1:142 char:30
+       $result = Start-Service <<<<  -Name $ServiceName -PassThru
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],
   ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand

```

And the Event Viewer logs:

```
The Neo4j-Server service failed to start due to the following error: 
The service did not respond to the start or control request in a timely fashion.
```

`A timeout was reached (60000 milliseconds) while waiting for the Neo4j-Server service to connect.`

**Comment by bvalyou** [comment]
I'm having the same problem @brunotomas referenced in his most recent comment. My first run worked fine, but after restarting the computer, it's failing with the same error:
`Start-Service : Service 'Neo4j-Server (Neo4j-Server)' cannot be started due to the following error: Cannot start service Neo4j-Server on computer '.'.`
It works fine with the console, but as a service it fails.

**Comment by Bennollo** [comment]
Hi @brunotomas and @bvalyou , which version of Java are you picking up? (x86, x64)
I was getting similar (almost identical error in Win 10) starting Neo4j and it was a result of the wrong JRE being picked up. Just adding this in case it helps someone else.

**Comment by drshitj2** [comment]
Hi @brunotomas 
Is there any way we can directly connect neo4j database as data source to Tableau like we can connect relational database rather than dumping data in csv or excel and then using with Tableau.

**Comment by glennsarti** [comment]
@drshitj2 would you be able to create a new issue for this or perhaps ask on other support channels (https://support.neo4j.com/hc/en-us).  Your question does not appear to relate to starting Neo4j and PowerShell.

**Comment by jexp** [comment]
See GitHub.com/neo4j-contrib/neo4j-tableau for many options
