### ISSUE TITLE
Allow enforcing read-only queries on Cypher endpoint via header

### ISSUE THREAD

**Issue by mikesname** [neo4j/neo4j#6516]
It should be possible to set a header (i.e. `X-ReadOnly: true`) on the Cypher endpoint to immediately fail a query if it mutates the graph in any way.

My use-case is that while most of my application runs via custom business logic (doing mutating stuff), I would like to allow direct read-only Cypher query access to a subset of trusted uses for typical analytics purposes (via my own interface - not the Neo4j browser.)

I don't, however, trust these users (or myself, for that matter) quite enough to risk one of them accidentally entering `MATCH n DETACH DELETE n` into a Cypher prompt. (I also don't want to put my faith in a hack that scans a query for mutating clauses before submitting it.)

I also think a mechanism such as this would be broadly useful for protecting programmers from themselves.

Apologies if this issue covers old ground but I could not see any new discussion of this since [a thread on the mailing list in 2012](https://groups.google.com/forum/#!searchin/neo4j/read-only$20cypher/neo4j/7XOquRJZnh4/CCFkR5U44lUJ).

**Comment by ikwattro** [comment]
Actually, you can handle this at the application level. 

Run a transaction with the query and includeStats = true

If the stats contains mutations, rollback and return error, otherwise commit and return success.

**Comment by mikesname** [comment]
@ikwattro thanks, I had not considered this approach and it would _mostly_ do what I want, albeit with a bit too much ceremony. However there are a few wrinkles:
- Doesn't fail fast. If you have a decently-sized graph certain operations will take a while to run and then, if necessary, roll back. Ideally the statements themselves would simply not run if they would mutate anything.
- Prevents you streaming the JSON results directly to the client, since you need to parse them and verify the query stats (not just a hypothetical: I currently do this and it's handy when the raw results from something like `MATCH n RETURN n` is hundreds of megabytes.)

**Comment by ikwattro** [comment]
@mikesname these are good arguments.
1. doesn't fail fast, I think the behavior would be the same at the transactional level.
2. no workaround in my mind for that.

Another solution that come to my mind, is to configure HAProxy to fail immediately if the cypher queries contains write clauses, an example from this blog post concerning the parsing : 

http://blog.armbruster-it.de/2015/08/neo4j-and-haproxy-some-best-practices-and-tricks/

**Comment by zhenlineo** [comment]
We will consider this feature request and we've added it to our future work list.
