### ISSUE TITLE
"Failed to mark transaction as rollback only" exception and NPE

### ISSUE THREAD

**Issue by amorgner** [neo4j/neo4j#658]
In Neo4j 1.9.M02-M05 you cannot delete nodes and relationships which stem from cypher queries outside a transaction.

For details, see this article on SO:
http://stackoverflow.com/questions/15571909/intended-change-in-behaviour-with-cypher-in-neo4j-1-9-m02-m05

**Comment by boggle** [comment]
Since Neo4j 2.1 (perhaps even 2.0) use of transactions was made mandatory so in order to delete a node you have to be in a transaction. That node proxy may very well haven been obtained by running a Cypher query in a previous transaction.

**Comment by jakewins** [comment]
Closing this as it should be resolved in all maintained versions. Please re-open if the issue remains.
