### ISSUE TITLE
Feature request: Please update documentation for CREATE UNIQUE

### ISSUE THREAD

**Issue by rationalism** [neo4j/neo4j#6585]
The documentation for neo4j 2.3.2 says:

"CREATE UNIQUE is in the middle of MATCH and CREATE — it will match what it can, and create what is missing. CREATE UNIQUE will always make the least change possible to the graph — if it can use parts of the existing graph, it will." (http://neo4j.com/docs/stable/query-create-unique.html)

This seems inaccurate, or at least confusing. There are several StackOverflow threads where people say that CREATE UNIQUE doesn't follow the "least change possible" rule:

http://stackoverflow.com/questions/35290079/create-unique-in-neo4j-produces-duplicate-nodes

http://stackoverflow.com/questions/13583504/neo4j-not-reusing-existing-vertex-in-cypher-create-unique-query

**Comment by Lojjs** [comment]
Thanks for reporting and sorry for the late replay. @petraselmer, who is responsible for the Cypher documentation, is currently working on clarifying the documentation around CREATE UNIQUE. We will let you know when this work is finished.

**Comment by petraselmer** [comment]
@rationalism & @Lojjs  The following file (and associated PR) encompasses the `CREATE UNIQUE` -> `MERGE` pathway (along with a whole bunch of removal notices): [link to file](https://github.com/petraselmer/neo4j-documentation/blob/1d9275a098393353e03569a506904bc7b8f27ee9/cypher/cypher-docs/src/docs/dev/ql/create-unique/index.asciidoc )

It ought to be published very soon in the Developer Manual.

**Comment by petraselmer** [comment]
The documentation for `CREATE UNIQUE` has now been published [here](https://neo4j.com/docs/developer-manual/current/cypher/clauses/create-unique/)
