### ISSUE TITLE
Feature request: Hierarchical indexes

### ISSUE THREAD

**Issue by rationalism** [neo4j/neo4j#6588]
Suppose there's a neo4j graph with a node for every person in the US (not exactly my use case, but close enough). Each person has both a name and a city. I want to do a fast lookup of the John Smith in Springfield, but there are (say) 10,000 cities in the graph, each with 30,000 people, and there are also 30,000 John Smiths. If I create a neo4j index on person:name, then neo4j needs to do a linear scan over the 30,000 John Smiths; if I create a neo4j index on person:city, then neo4j does a linear scan over all 30,000 people in Springfield; and both of these are annoyingly slow.

My current solution is to create a separate label for each city - person_springfield, person_boston, person_buffalo, and so on - and make a separate index for each of them, but this seems ugly and potentially prone to problems, and I also have to add a redundant "person" label to look up people across cities. Alternatively, I could have separate properties for "name", "city", and "namecity" (which stores the two strings concatenated) and put an index on those, but then each piece of data would be stored twice, and would have to be kept in sync manually. 

It would be really great if neo4j had native support for nested/hierarchical indexes, allowing one to look things up by name and then by city (or vice-versa) within the same index. Relevant StackOverflow threads:

http://stackoverflow.com/questions/20491371/index-on-multiple-properties-in-neo4j-cypher

http://stackoverflow.com/questions/22498054/how-to-create-unique-constraint-involving-multiple-properties-in-neo4j

http://stackoverflow.com/questions/18860415/neo4j-cypher-index-query

http://stackoverflow.com/questions/12166283/performance-issues-while-creating-index-on-multiple-fields-in-spring-data-neo4j

**Comment by astesin** [comment]
It seems to me that you are proposing implementing an RDBMS approach to your task, but it has a different solution which ideologically fits graph database approach to things. It's a matter of data modelling, I think. WBR, Andrii

**Comment by rationalism** [comment]
@astesin If by data modeling you mean storing everything as graph relationships, I agree that would be really cool! I chose neo4j because I loved graphs, after all. Unfortunately, I don't think it would be efficient, given neo4j's current architecture and the problem constraints.

To expand on the earlier example, suppose you want to find John Smith in the city of Springfield. In an empty graph, I tried storing the name "John Smith" as its own node and the city "Springfield" as its own node  - both of these nodes should be easy to find by simple indexes. I then created 50,000 person nodes with the name John Smith (as a "name" relationship in the graph), and 50,000 person nodes with the city Springfield (as a "city" relationship in the graph). I created one person with both the name John Smith and the city Springfield, this being the person we want to find. Finally, there's a MATCH query to find a path through the graph between the John Smith node and the Springfield node, which identifies the person we want. 

Unfortunately, according to PROFILE, this required O(N) scanning over all 100,000 relationships. Here's a screenshot of the execution plan:

![graph_scan](https://cloud.githubusercontent.com/assets/813306/13488971/200adcf2-e0d9-11e5-906e-2b8a41bd9ee7.png)

One could accomplish much the same thing as hierarchical indexes by having indexes that were specific to particular graph nodes - in this case, one could index the relationships of the node "John Smith" by city (or vice versa), allowing fast lookup from nodes with many relationships. However, my tentative guess is that this might be harder to do than just extending conventional schema indexes.

**Comment by astesin** [comment]
> @astesin If by data modeling you mean storing everything as graph relationships, I agree that would be really cool!

Yes, this is exactly what I mean :) I already discovered some time ago
(with neo4j 2.1.*) that my self-made tree index with depth 5, as soon
as Cypher query is done right - gives me pretty much the same request
time, as lucene index lookup over the very same data. It works for me
at least :)

And I still is on the way from "simple" tree-structured graph
"indexes" to more sophisticated trees i.e.
https://en.wikipedia.org/wiki/Self-balancing_binary_search_tree and so
on.

> I chose neo4j because I loved graphs, after all. Unfortunately, I don't think it would be efficient, given neo4j's current architecture and the problem constraints.

Just do some experiments and you will be surprised. The dataset you
described is not that big, after all.

> To expand on the earlier example, suppose you want to find John Smith in the city of Springfield.

This in fact means that - speaking math - you want to find
intersections of 2 sets of (p:Person) nodes:

1) (p0)-[:HAS_FULL_NAME]->(js:FullName {fname: 'John Smith'})

2) (p1)-[:IS_LOCATED_AT]->(spf:City {city_name: 'Springfield'})

But we are working with graph databases, aren't we? So we want to
convert the task of finding an intersection of two sets (afaik Oracle
RDBMS is good in this) to the task of discovering a set of _paths_
between

MATCH (js:FullName {fname: 'John
Smith'})<-[rel_name:HAS_FULL_NAME]-(p:Person)-[rel_city:IS_LOCATED_AT]->(spf:City
{city_name: 'Springfield'})

This is a bad idea from many different points of view, first of all
you always have problems as soon there are more than 10000 of Persons
_directly_ linked to a _single_ city!

To make things somewhat better, you can just split the query using WITH

MATCH
    (x:FullName {fname: 'John
Smith'})<-[rel_name:HAS_FULL_NAME]-(p:Person) // we get thousands of
those... bad!
WITH
    p AS john_smith
MATCH
    (john_smith)-[rel_city:IS_LOCATED_AT]->(spf:City {city_name:
'Springfield'}) // this shortens the set to what we need
WITH
    john_smith AS john_smith_from_Springfield
//
// go further do whatever we want

but this is still a RDBMS-style approach

> One could accomplish much the same thing as hierarchical indexes

And implement the hierarchical index with graph DB approach is to
create a search tree between the city node and FullName nodes of
Persons who are located in the city (either a simple binary tree, a
balanced binary tree or some other kind of tree structure) and
traverse the tree with a carefully crafted query starting from it's
root (the Springfield city node) until we will find a node with
desired FullName and that's it.

WBR,
Andrii

**Comment by astesin** [comment]
UPD. In practice this mean (at least what I'd do in this case) that:

1) First you find the complete list of existing possible FullNames in
your country.

2) If you don't know (at least approximate) frequencies of appearance
of those or those FullNames in real life, just create a static
exemplary balanced binary tree [1] of those - which tree allows you to
very quickly find desired FullName in it, using your own assumptions
about frequencies, selected at your personal biased discretion. Do I
need to say that the most frequent FullName should become a root of
this tree, and the higher the frequency, the closer this FullName is
to the root?

If you get some reliable frequency information somewhere, just use it :)

3) Remember that your information may become outdated at any given
moment - as soon as someone with a certain completely new FullName
will arrive - so keep in mind that it occasionally you will need to
insert a new FullName into the tree.

4) There will be too much an overkill to store each and every possible
FullName on the Earth for each City. So probably the best approach
will be to build a balanced tree of height say 10 which means 2047
most frequent FullNames and insert appropriate new FullNames on demand
later. (Or maybe height 16 will do better?)

So, now you have an exemplary balanced binary tree of FullNames. Ok,
now give an own copy of this "standard" tree to each and every City in
your database (and don't forget to add even more ones for each new
City which you will be adding later).

Now as soon as you need to allocate John Smith into Springfield, you
establish a relation between (js:Person) and a FullName node which
resides in the exact instance (copy) of your fast tree which belongs
specially to Springfield.

You don't like binary trees? Choose a tree of different breed. I.e.
you may compute a "key" for each FullName which for the start consists
of first letter of the first name and first letter of the last name.
For John Smith this first-level key will be string "JS", for my name
this will be "AS" and so on. Root node (0-level) of your tree will
have exactly 676 relationships from it. one for each possible pair of
letters.

At level 1, repeat this: i.e. for John Smith you will follow a "JS"
relationship from 0-level root node and will come to the 1-level node
which in turn has 676 outgoing relationships, for each possible pair
of SECOND letters of the first and last name. So next hop will follow
string "OM" and get you to 2-level node, which obviously will not have
too much FullName nodes tied to it.

This gives you a constant-height (of two) tree with 456976 1-level
nodes. Add one more level and you will get a tree of constant height
of 3 with 309373428 total nodes, which obviously is an overkill :)
2-level index with 457652 nodes seems to fit the purpose.

Why this MAY (I'm not sure, experiments needed) be faster than a
balanced binary tree? Your search will ALWAYS consist of exactly(!) 3
steps (hops):

1) WITH your city, you retrieve a relationship to the root of the tree
and the root node itself,
2) WITH root node, you retrieve an appropriate relationship from 676
possible, and 1-level node itself,
3) WITH 1-level node, you retrieve a second appropriate relationship
from 676 possible, and 2-level node and FullName (if exists) and
Person(s) (if any exist).

Note that you don't need to store each and every possible FullName on
the Earth for every city, Ok? And we already covered 457652 buckets of
FullNames which is par-par with binary tree of height 19 (!!!)

And I have no damn idea of what the height of City's balanced binary
tree of FullNames will actually be, given in USA you have the whole
spectrum of first and last names from every language in the world?

HINT: computation of 2-letter key string in memory from other string
costs nothing, just zero cost. Each new lookup hop "WITH startnode
MATCH appropriate relationship and endnode" costs something and may
even involve disk access (at least for the first time, or for every
occasion when this info is not cached already).

That were the ideas of mine.

WBR,
Andrii

**Comment by rationalism** [comment]
@astesin Thanks for the discussion, but that sounds like a very complicated solution. Isn't the entire point of databases to save application programmers from having to roll their own self-balancing search trees? There's also the extra inefficiency from two layers of abstraction - whichever search trees neo4j uses rest directly on the filesystem, while search trees inside neo4j rest on neo4j's internal search trees, which themselves rest on the filesystem.

**Comment by astesin** [comment]
Once again, we are in fact discussing the problem "how to determine an
intersection of 2 sets" and graph database is strong in finding paths but
not aware of sets.

For set intersection, there IS a solution right now: use so-called "legacy
index" (node_autoindex seems to be the most convenient way). Given we have
needed node properties indexed, we can construct queries then, which begin
with START clause and use Lucene expressions to achieve quick discovery of
set intersections. Check Lucene query abilities at
https://lucene.apache.org/core/5_5_0/queryparser/org/apache/lucene/queryparser/classic/package-summary.html#package_description

WBR,
Andrii

**Comment by rationalism** [comment]
@astesin Since neo4j legacy indexes are deprecated and strongly discouraged, it seems like any solution using them would have to be rewritten soon anyway. Could the neo4j developers comment on the timeframe for replacing legacy indexes? Will all of the functionality be moved over to schema indexes, or will some functionality be dropped? Thanks

**Comment by astesin** [comment]
On Fri, Mar 4, 2016 at 5:06 AM, rationalism notifications@github.com wrote:

> @astesin Since neo4j legacy indexes are deprecated and strongly discouraged,

What??? I think they will last forever, for their specific purpose -
look at the documentation for future 3.0 here

http://neo4j.com/docs/snapshot/query-start.html

and especially here

http://neo4j.com/docs/snapshot/indexing.html ATTN: they are called
MANUAL indexes from now ;)

> it seems like any solution using them would have to be rewritten soon
> anyway. Could the neo4j developers comment on the timeframe for replacing
> legacy indexes?

Yes, I second your question.

> Will all of the functionality be moved over to schema
> indexes, or will some functionality be dropped? Thanks

**Comment by rationalism** [comment]
@astesin Neo4j has explicitly confirmed that legacy indexes are deprecated and will be replaced. See this quote from a [blog post from last week](http://neo4j.com/blog/dark-side-neo4j-worst-practices/):

"Seriously, you should always use schema indexes whenever possible. Schema indexes were added in Neo4j 2.0, and now with Neo4j 2.3, they have been significantly improved. You can now do prefix queries based on indexes as well as range queries, and I hope we see more in the future on that. Our long-term goal is leave legacy indexes behind entirely.

There’s a story about that. When we first released Neo4j 2.0, we had converted all the functionality of the legacy indexes into the schema indexes, but we had done it really fast. That’s why we initially labeled the older indexes as “legacy.”

But there are cases when you still need legacy indexes. For example, if you want to do full-text indexing, you can’t do that with schema indexes. Sorry. As we work to replace legacy indexes entirely (including for full-text indexing), we’ve chosen to make legacy indexes a little bit hard to use. So if you’re finding them difficult, that’s good, because one day, they’ll be gone forever."

**Comment by astesin** [comment]
On Fri, Mar 4, 2016 at 5:28 AM, rationalism notifications@github.com wrote:

> @astesin Neo4j has explicitly confirmed that legacy indexes are deprecated
> and will be replaced. See this quote from a blog post from last week:
> 
> "Seriously, you should always use schema indexes whenever possible. Schema
> indexes were added in Neo4j 2.0, and now with Neo4j 2.3, they have been
> significantly improved. You can now do prefix queries based on indexes as
> well as range queries,

Agh, Ok, it wasn't possible with 2.2 at least. But see below:

> and I hope we see more in the future on that. Our
> long-term goal is leave legacy indexes behind entirely.
> 
> There’s a story about that. When we first released Neo4j 2.0, we had
> converted all the functionality of the legacy indexes into the schema
> indexes, but we had done it really fast. That’s why we initially labeled the
> older indexes as “legacy.”
> 
> But there are cases when you still need legacy indexes. For example, if you
> want to do full-text indexing, you can’t do that with schema indexes. Sorry.

So what do you think? Will they REALLY drop manual indexes and lose a
full-text ability entirely? Do you believe this will happen
anytime soon?

> As we work to replace legacy indexes entirely (including for full-text
> indexing),

Something makes me think that this will not be done at least until 4.0.

> we’ve chosen to make legacy indexes a little bit hard to use. So
> if you’re finding them difficult, that’s good, because one day, they’ll be
> gone forever."

...and you will loose the single present possibility to index
relationships(!) on their properties? This is damn unbelievable :)

Ok, I'll personally stick with Neo4j 3.\* forever then :)

WBR,
Andrii

**Comment by tkroman** [comment]
@astesin, IMO indexing relationships by _properties_ shouldn't be the reason for using manual indexes. That same functionality can be achieved by means of rethinking the model itself. What _I_ find to be the reason why MI support shouldn't be dropped right now is indexing relationships by their nodes. When your graph grows and you find, quite unexpectedly, that your nodes have millions of attached relationships, that linear-time search by ResourceIterators becomes a real pain in the ass. It's just my opinion, of course.

**Comment by astesin** [comment]
@tkroman you knew this :) BTW how do you MI relationships by their STARTNODE() and ENDNODE() ? 

from Cypher I've done this by creating properties inside relationships:

MATCH (a)-[r]->(b) WHERE ...whatever... SET r.p_start = ID(a), r.p_end = ID(b)

and MI-ed relationships on their properties p_start and p_end

This is not the only single valid case for MI on relationship properties, though.

**Comment by jexp** [comment]
In Neo4j 3.0 you will be able to hash-join both index lookups

```
MATCH (p:Person {name:"John Smith"})
WITH p
MATCH (o:Person {city:"Springfield"})
WHERE p = o
RETURN p

```

which results in a plan like this:

```
+------------------+----------------+------+---------+-----------+---------------+
| Operator         | Estimated Rows | Rows | DB Hits | Variables | Other         |
+------------------+----------------+------+---------+-----------+---------------+
| +ProduceResults  |              0 |    1 |       0 | p         | p             |
| |                +----------------+------+---------+-----------+---------------+
| +ValueHashJoin   |              0 |    1 |       0 | p -- o    | p; o          |
| |\               +----------------+------+---------+-----------+---------------+
| | +NodeIndexSeek |              1 |    1 |       2 | o         | :Person(city) |
| |                +----------------+------+---------+-----------+---------------+
| +NodeIndexSeek   |              1 |    1 |       2 | p         | :Person(name) |
+------------------+----------------+------+---------+-----------+---------------+
```

**Comment by astesin** [comment]
@jexp this is incredible :) Thanks!

**Comment by rationalism** [comment]
@jexp Cool, thanks! That solves the problem, so I've closed out the issue.

**Comment by ehx-v1** [comment]
@astesin I think you misunderstood what's going on about dropping manual indexes, schema indexes are planned to support everything manual indexes support now, so when they're done with porting functionality they will drop the manual indexes, not before
