### ISSUE TITLE
Feature request: Native support for node merges

### ISSUE THREAD

**Issue by rationalism** [neo4j/neo4j#6589]
Suppose I have this node:

(n:person {name: "Bob Smith", city: "Boston"})-[:brother]-(n:person {name: "Dave Smith"})

and this node:

(n:person {name: "Bob Smith", haircolor: "brown"})-[:brother]-(n:person {name: "Frank Smith"})

It would be great to have an automatic way of combining them, to get:

(n:person {name: "Frank Smith"})-[:brother]-(n:person {name: "Bob Smith", city: "Boston", haircolor:"brown"})-[:brother]-(n:person {name: "Dave Smith"})

Right now I'm doing this manually, by taking one node's properties and relationships, inserting them with MERGE into the other node, and then deleting the redundant first node, but this is clunky and requires multiple round-trips between neo4j and the server. One person suggested using MERGE to avoid duplicates, but unfortunately I can only detect them with a complex machine learning algorithm, so there's no real way to screen them out in advance.

Relevant StackOverflow thread: http://stackoverflow.com/questions/23376881/neo4j-merge-2-or-multiple-duplicate-nodes

**Comment by spacecowboy** [comment]
What you describe as a "node" is in fact two nodes and a relationship. And I think your request won't make much sense as you gain more experience with Neo4j.

`MERGE` is intended to be used to created the nodes and relationships in the first place, in order to avoid duplicates.

For your use case, use `MERGE` instead of `CREATE`.

For example, starting out you want to make sure you have  node for 'Bob' in the graph. You are not sure if 'Bob' already exists in the graph, but he should only have one node. So you use `MERGE`:

```
MERGE (n:person {name: "Bob Smith", city: "Boston"})
```

Now the graph contains just one node, 'Bob'.

Later, you learn that 'Bob' is the brother of 'Dave', again you are not sure if 'Bob' or 'Dave' exists in the database, or if the 'brother' relationship exists. No matter, `MERGE` will do the right thing:

```
MERGE (n:person {name: "Bob Smith"})-[:brother]-(n:person {name: "Dave Smith"})
```

Now the graph will contain two nodes, 'Bob' and 'Dave', and one relationship between them of type 'brother'.

Even later still, you find out that 'Bob' is also the brother of 'Frank'. So you do:

```
MERGE (n:person {name: "Bob Smith"})-[:brother]-(n:person {name: "Frank Smith"})
```

At this point, three nodes exists (Bob, Frank, Dave), and two relationships, connecting Bob as the brother of Frank and Dave.

As you can see, your feature request doesn't make much sense at this point because using `MERGE`, no duplicate information was ever created in the first place.

Please note that you have some caveats to consider while using `MERGE`,  see the manual for more information: http://neo4j.com/docs/stable/query-merge.html

**Comment by rationalism** [comment]
@spacecowboy Thank you for the explanation. (The examples I used are indeed two nodes and a relationship, I was just using sloppy language.) I certainly understand if my use case for neo4j is too unusual to support, and if that's the case, please do close the issue. However, using MERGE to prevent all duplicates simply will not work for me. I'm not a database expert, but I used to work on a team of roughly twenty other programmers which found duplicates in Google's Knowledge Graph, so please trust me when I say that duplicate detection is very complicated and can't always be handled with MERGE.

For example, suppose there are two different people, each named Bob Smith:

(a:person {name: "Bob Smith"}) (b:person {name: "Bob Smith"})

MERGE will create one node, even though these are two different people. That's easy to fix, though, just add more data:

(a:person {name: "Bob Smith", email: "bobsmith@gmail.com"}) (b:person {name: "Bob Smith", email: "bobsmith@yahoo.com"})

There, now MERGE will create two nodes, if the parameters are fully specified. But what if those Bobs are actually the same person? People, of course, can have more than one email address. A user might get one email from bobsmith@gmail.com in 2013, and another email from bobsmith@yahoo.com in 2014, and then only find out in 2015 that they're from the same person. 

Or if we classify people by city, we might have:

(a:person {name: "Bob Smith", city: "Brooklyn"}) (b:person {name: "Bob Smith", city: "New York City"}) (c:person {name: "Bob Smith", city: "Jakarta"}) 

Bob Smith's Facebook page might say "Brooklyn, New York", and his LinkedIn page might say "New York City, New York", or vice versa. Of course, Brooklyn is inside New York City, and so these Bob Smiths are probably the same, while the Bob in Jakarta is probably a different Bob. But neo4j doesn't know that - checking which cities are inside which other cities more-or-less has to be done at the application level, not the database level.

In some cases, duplicate detection can be done in-app before touching the database, but other times necessary information can only be found inside neo4j. For example, one might have this data inside neo4j:

(a:person {name: "Bob Smith"})-[:attended]->(b:event {name: "Festival of Rock"})-[:location]->(c:venue {name: "Coca-Cola Concert Hall"})-[:city]->(d:city {name: "Brownsville, Texas"})

(e:event {name: "Churnham and Burnham Circus"})-[:location]->(f:venue {name: "Davey Jones Park"})-[:city]->(g:city {name: "Brownsville, Texas"})

Later, the application learns (from Facebook, say) that a man named Bob Smith attended the Churnham and Burnham Circus. Since both events are in Brownsville, TX, this new Bob is probably the same as the other Bob (node "a"). But there's no way to know that without merging the information in-memory with the information in neo4j. In theory, one could download the data about node "e" from neo4j into memory, do the merger there, and then re-upload reconciled data to neo4j; but in my application, there might be twenty or thirty of these paths to check for each label, and figuring out which information to download for each path in advance would get very messy and require many server-client roundtrips. It's much simpler to use MERGE on node "e" to create:

(h:person {name: "Bob Smith"})-[:attended]->(e:event {name: "Churnham and Burnham Circus"})-[:location]->(f:venue {name: "Davey Jones Park"})-[:city]->(g:city {name: "Brownsville, Texas"})

and then download the result of querying the [:attended, :location, :city] path and all the other relevant paths from neo4j, crunch the numbers, and afterwards combine node "a" with node "h".

There's also the issue of inevitable mistakes in the database. One might have these two nodes:

(a:person {name: "Alan Smith"}) (b:person {name: "Alan Smithq"})

and these are actually the same person, despite the different names, because someone made a typo. But MERGE can't detect this, because they aren't the same string. One could fix this by saying:

(a:person {first-name: "Alan" last-name: "Smith"}) (b:person {first-name: "Alan" last-name:"Smithq"})

and then using MERGE on first-name, but (leaving aside all the other people named "Alan") this would fail when you saw:

(a:person {first-name: "Alan" last-name: "Smith"}) (b:person {first-name: "Alan" last-name:"Smithee"})

because Alan Smithee isn't the same as the first Alan, and isn't even a real person, but is a pseudonym used by disgruntled movie directors. (Google has a chunk of code written specifically for this edge case. For more problems with names, I enjoy reading eg. the blog post at http://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/.)

I haven't gotten there yet in my own application, but soon enough, there will also be the issue of foreign languages. For example, these are all the same person, at least according to Google Translate:

(a:person {name: "Bob Smith"}) (b:person {name: "Боб Смит"}) (c:person {name: "ቦብ ስሚዝ"}) (d:person {name: "鮑勃·史密斯"}) (e:person {name: "ბობ სმიტი"}) 

and the only real way to detect it (absent other identifiers) is with some kind of translation software. However, in probabilistic terms, the Russian Bob Smith is much less likely to match the American Bob Smith, vs. when comparing two American Bob Smiths.

So I can absolutely use MERGE to preemptively de-duplicate globally unique identifiers like emails and (fully internationalized) phone numbers and timestamps and DOI numbers and so on, but it's very far from a general solution to the duplication problem. 

(Also, FWIW, I think this description might be inaccurate?

"Later, you learn that 'Bob' is the brother of 'Dave', again you are not sure if 'Bob' or 'Dave' exists in the database, or if the 'brother' relationship exists. No matter, MERGE will do the right thing:

MERGE (n:person {name: "Bob Smith"})-[:brother]-(n:person {name: "Dave Smith"})

Now the graph will contain two nodes, 'Bob' and 'Dave', and one relationship between them of type 'brother'."

The documentation describes MERGE as all-or-nothing, so if the set {Bob node, Dave node, brother relationship} is partially but not fully present, that MERGE command will create a whole new set. Eg., when I try the queries:

CREATE (n:person {name: "Bob Smith"}), (m:person {name: "Dave Smith"})
MERGE (n:person {name: "Bob Smith"})-[:brother]-(m:person {name: "Dave Smith"})
MATCH (a:person) OPTIONAL MATCH (a)--(r) RETURN a, r

the MATCH shows four nodes of type person - two nodes of Dave Smith and two nodes of Bob Smith. I tried using CREATE UNIQUE for this, but it doesn't seem to do that either, see issue #6585).

**Comment by spacecowboy** [comment]
Now I see that your use-case is slightly more involved than I initially suspected. Duplicates of these, where a user might register with two different emails for example, are unavoidable in any database, and MERGE will not solve the issue since the unique element actually differs.

So for your usecase, I would recommend either using [unmanaged extensions](http://neo4j.com/docs/stable/server-unmanaged-extensions.html) or the coming [procedures in 3.0](https://github.com/neo4j/neo4j/wiki/Neo4j-3.0-changelog#300-m04). It should be possible to build the functionality you want using either of those. E.g., given duplicates have been detected, load them, merge their properties/relationships, delete duplicates.

**Comment by astesin** [comment]
I agree with @spacecowboy here

**Comment by jexp** [comment]
@rationalism so you just need a means of merging two nodes?

If you know the relationship-types you can automate it a bit by doing this:

```
MATCH (n1:Label) WHERE ...
MATCH (n2:Label) WHERE ...
SET n1 +=n2
OPTIONAL MATCH (n2)-[r1:TYPE]->(o)
CREATE (n1)-[r2:TYPE]->(o) SET r2 = r1
WITH distinct n1,n2
OPTIONAL MATCH (n2)<-[r1:TYPE]-(o)
CREATE (n1)<-[r2:TYPE]-(o) SET r2 = r1
DETACH DELETE n2
```

For Neo4j 3.0 I wrote a procedure for doing that, see:

https://github.com/neo4j-contrib/graph-refactoring/blob/master/src/main/java/refactor/GraphRefactoring.java#L58

which are callable from Cypher.

I have to update the repo to the latest version but then you can call:

```
MATCH (n1:Label) WHERE ...
MATCH (n2:Label) WHERE ...
CALL refactor.mergeNodes(n1,[n2]);
```

**Comment by rationalism** [comment]
@jexp Cool! Does the procedure use CREATE or MERGE for making the new relationships? It seems like MERGE would be better, to avoid duplicate links.

**Comment by Lojjs** [comment]
@rationalism Are you still having an issue here or are you satisfied with the answers you got (I know it have been a long time since you posted this)? If I don't receive any answer from you I will close the issue, but feel free to re-open it or create a new issue if you need more help.

**Comment by Lojjs** [comment]
@rationalism Since I haven't heard back from you I will close this issue for now. Feel free to reopen it or create a new one if you still have troubles. 
Best regards Louise, Neo4j Cypher Team

**Comment by Lojjs** [comment]
@rationalism Since I haven't heard back from you I will close this issue for now. Feel free to reopen it or create a new one if you still have troubles. 
Best regards Louise, Neo4j Cypher Team
