### ISSUE TITLE
Feature request: Stronger schema guarantees

### ISSUE THREAD

**Issue by rationalism** [neo4j/neo4j#6617]
In 2.3, neo4j's options for schema guarantees are very limited, essentially just uniqueness of values and property existence:

http://neo4j.com/docs/stable/query-constraints.html

This lack of checking makes it easy for "silent bugs", or other apps writing to the same database, to quietly violate an application's intended graph model. Some guarantees that would be helpful, at least for my use cases, are:
- Type checking: Property X on Label Y must have/cannot have Type Z (integer, float, string, etc.).
- Relationship checking: Nodes with Label X must have/cannot have relationships with Label Y.
- Direction checking: Relationships with Label X can only be inbound/outbound from nodes with Label Y.
- Value checking: Property X on Label Y must be under/over a certain length (for strings), within a certain range (for numbers), and so on.

Here is a relevant StackOverflow thread: http://stackoverflow.com/questions/27709274/are-there-label-properties-is-there-a-neo4j-schema-for-labels

**Comment by Mats-SX** [comment]
Hey @rationalism and thanks for the suggestions.

We do have further constraints in mind, but the unfortunate reality is that these plans haven't bubbled up all the way across the priority sheets. We're tracking this internally, so I will close this issue for now. I can't really tell you anything about timeframes for these features at this time, but do keep a lookout for upcoming blog posts, where I'd say it's likely we'll advertise further schema features in the future.
