### ISSUE TITLE
Integer overflow in ForsetiClient#acquireExclusive leads to infinite loop

### ISSUE THREAD

**Issue by tkroman** [neo4j/neo4j#6653]
As discussed in #6559, I'm separating two different issues. This one is about integer overflow (affects all actual neo4j releases):

```
@Test
public void shouldAcquireExclusiveLock() throws Exception {
    Locks locks = dbRule
            .getGraphDatabaseAPI()
            .getDependencyResolver()
            .resolveDependency(Locks.class);

    Client client = locks.newClient();

    for (int i = 0; i < Integer.MAX_VALUE; i++) {
        client.acquireExclusive(ResourceTypes.RELATIONSHIP, 0L);
    } // heldCount = 7fffffff
    client.acquireExclusive(ResourceTypes.RELATIONSHIP, 0L); // heldCount = 80000000
    for (int i = 0; i < Integer.MAX_VALUE; i++) {
        client.acquireExclusive(ResourceTypes.RELATIONSHIP, 0L);
    } // heldCount = -1 now

    // Stuck here
    client.acquireExclusive(ResourceTypes.RELATIONSHIP, 0L);
}
```

When `heldCount` reaches -1 (after overflow, from below), locking mechanism is forever stuck in this loop: https://github.com/neo4j/neo4j/blob/a58e9fd60c2c4aab06d4c2cba4e729f3e0c8a82d/enterprise/kernel/src/main/java/org/neo4j/kernel/impl/enterprise/lock/forseti/ForsetiClient.java#L269

**Comment by chrisvest** [comment]
Thanks for writing this up. I already fixed this in #6612, which will be part of 3.0, so I think we can close it and focus on the other issue since I don't think anyone actually runs into this in practice.
