### ISSUE TITLE
Recursive table growing in HopScotchHashingAlgorithm may lead to some table entries getting lost.

### ISSUE THREAD

**Issue by tkroman** [neo4j/neo4j#6654]
As discussed in #6559, I'm separating two different issues. This one is about neo4j hanging while attempting to acquire lock for some write operation (e.g. deletion) in case there's an index on some property of the target entity.

I created a repository containing this bug's reproduction scenario: https://github.com/tkroman/demo (run `Demo.main()`).

Line of interest is https://github.com/tkroman/demo/blob/master/src/main/java/Demo.java#L44. 

If it's commented, everything works fine. 
If it's uncommented and un-comment line 43, everything works as well. 
Also, if an `ORDER BY` clause is presented in `DETACH DELETE`, everything works fine.

**Comment by chrisvest** [comment]
Thank you for chasing this so far.

I can reproduce the lock-up locally with your demo program when both indexes are enabled. It also works if I use the `EnterpriseGraphDatabaseFactory` instead of the `HighlyAvailableGraphDatabaseFactory`, which is nice because that's a much simpler system. It does _not_, however, reproduce when I use the normal community `GraphDatabaseFactory` which gives me the CommunityLockManager.

I'm suspecting some kind of lock ordering problem. Without the indexes, we likely scan the store, which is in node-id order, so this effectively gives us the `ORDER BY id(n)`. However, with the index, we get the nodes from an index scan, where we process them in whatever order is most convenient for the index. Why this actually _matters_ to the ForsettiLockManager, I don't know. But at least now we have something tangible to work with.

**Comment by chrisvest** [comment]
If I change the query to

```
MATCH (n:Node { treeId:{treeId} })
WHERE NOT n:Root 
WITH n 
limit 500 optional match (n)-[r]-()
with n, r
DELETE n, r
```

Then I can reproduce it on 2.2.8 as well.

**Comment by tkroman** [comment]
Awesome! Thanks for paying so much attention to this issue.

There's also another case when I'm bumping into such a behavior, but I still can't reproduce it outside of full application, so here's the gist: 
having `(parent)<-[CHILD_OF]-(node)<-[CHILD_OF]-(child)`, where the count of `node`s is of order of hundreds, I create the following patterns (via Java API, manually):
`(node)-[NEXT]->(next_node_version)` and `(child)-[CHILD_OF]->(next_node_version)` for each `child` of `node`. 
In this case I get the same lock acquisition problems, so maybe this will give you more insight. If I'll be able to reproduce this, too, I'll let you know.

**Comment by chrisvest** [comment]
I might have been mistaken about the 2.2.8 repro, because I can no longer do it. Maybe I had wrong jars on the classpath that one time. I also can't reproduce it on 3.0.0-SNAPSHOT.

**Comment by tkroman** [comment]
It's good to know that 3.0 is OK w.r.t. this, since we are already
experimenting with 3.0 branch.

**Comment by chrisvest** [comment]
Interesting find: If I comment out the two calls to `reopenIfShould`, then the bug does not manifest:
https://github.com/tkroman/demo/blob/master/src/main/java/Demo.java#L86

**Comment by tkroman** [comment]
@chrisvest, here's something worthy, I think. I noticed that `resourceId`s are mostly repeating themselves between the test launches, so I tinkered around with the code to add some debug prints and checks and here's what I got. I think the problem is in the HopScotch-table's `put` method. Just take look at this screenshot: https://i.imgur.com/KwGssHS.png.

Some explanations: `35652` was the rel id that gave me the 'deadlock' most of the time. I noticed that, while putting some other values into the table, we may end up with some present entries dropped out. On the screenshot, `x0` is the value of `get(35652)` before the `put(35490)` call, and `x1` is it's value after. As you can see, `x0 == 1` and `x1 == -1`. From this point and afterwards, a lock is present in the `lockMap`, but the record in `heldLocks` is absent.

I still haven't found the spare time dig around all the table resizing stuff (and the correctness of hopscotch implementation in general), but i think that has something to do with that. In case you won't have the time to investigate on your own, I guess, I'll let you know if my search was successful.

Just for the history: dump of the table _before_ insertion: https://paste.ubuntu.com/15432078 and the one _after_: https://paste.ubuntu.com/15432087

**Comment by tkroman** [comment]
Yup. If you get this:

```
@Override
    public int put(final long key, int value)
    {
        Map<Long, Integer> before = readValues();
        int unpack = unpack(HopScotchHashingAlgorithm.put(table, monitor, DEFAULT_HASHING, key, pack(value), this));
        Map<Long, Integer> after = readValues();
        before.remove(key);
        after.remove(key);
        if (!before.equals(after)) {
            System.out.println("not eq! " + before + " " + after);
            boolean x1 = before.keySet().removeAll(after.keySet());
            System.out.println(before.keySet());
        }
        return unpack;
    }
```

into the `org.neo4j.collection.primitive.hopscotch.PrimitiveLongIntHashMap`, you'll notice that 'deadlocks' happen exactly for those values, which are reported to be absent after the insertion.

**Comment by chrisvest** [comment]
@tkroman That's also where I'm at in my investigation. I suspect it might only happen to `PrimitiveLongIntHashMap`s that have been `clear()`ed at some point. It's certainly not a concurrency or pool initialisation issue.

**Comment by tkroman** [comment]
@chrisvest, I believe, it's rather growing we should be checking out. Here's the permanently failing test (is it failing for you?):

```
    @Test
    public void t0()
    {
        PrimitiveLongIntMap map = Primitive.longIntMap();
        List<Long> lst = Arrays.asList(
                44988L, 44868L, 44271L, 44399L, 44502L, 44655L, 44348L, 44843L,
                44254L, 44774L, 44476L, 44664L, 44485L, 44237L, 44953L, 44468L,
                44970L, 44808L, 44527L, 44987L, 44672L, 44647L, 44467L, 44825L,
                44740L, 44220L, 44851L, 44902L, 44791L, 44416L, 44365L, 44382L,
                44885L, 44510L, 44553L, 44894L, 44288L, 44306L, 44450L, 44689L,
                44305L, 44374L, 44323L, 44493L, 44706L, 44681L, 44578L, 44723L,
                44331L, 44936L, 44289L, 44919L, 44433L, 44826L, 44757L, 44561L,
                44595L, 44612L, 44996L, 44646L, 44834L, 44314L, 44544L, 44629L
        );
        fill(map, lst);

        final Set<Long> k0 = keys(map);
        map.put(44357, 1);
        final Set<Long> k1 = keys(map);
        assertEquals(1, map.get(44450));
        k0.removeAll(k1);
        if (!k0.isEmpty()) {
            assertTrue(k0.isEmpty());
        }
    }

    private Set<Long> keys(PrimitiveLongIntMap map) {
        final Set<Long> k0 = new HashSet<>();
        try {
            map.visitKeys(new PrimitiveLongVisitor<Exception>() {
                @Override
                public boolean visited(long value) throws Exception {
                    k0.add(value);
                    return false;
                }
            });
        } catch (Exception e) {
            e.printStackTrace();
        }
        return k0;
    }

    private void fill(PrimitiveLongIntMap map, List<Long> lst) {
        List<Long> longs = lst;
        for (Long aLong : longs) {
            map.put(aLong, 1);
        }
    }
```

This allows to debug the very point of failure without unnecessary data dumps. I'll get back to this in a couple of hours, I believe we're veeery close :)

**Comment by tkroman** [comment]
@chrisvest, woo-hoo. Looks like I have a fix. tl;dr: https://gist.github.com/tkroman/3d2c0bac46379905dd6c. New test passes, so do the old ones, so I guess that's it.

The problem was with the call to `resizeMonitor.grewTable(newTable)` due to the recursive nature of the method. If this happens:

```
put
 grow
  put
   grow
   ...
```

the `resizeMonitor` will get a `newTable`, which is actually not that new, i.e. there's already a newer, more actual table, which was set down the call stack, but when we are popping out of recursion, we overwrite it with the top-level one. Pretty simple, actually, but kinda hard to spot.

The solution is to make the table reassignment right _after it's created_. This way we set the newest version of table each time it's resized (_before_ descending down the stack) instead of overwriting newer version with older ones while going up the stack.

I'm not doing a pull-request since I'd like for @tinwelint (who is the original author) to take a look at this as well. Also, the proposed version is simple, but may be error-prone in case `grow()` throws `IllegalStateException` in recursive call, so the state won't be reset to the correct one. I ran all the tests in all the core packages and they didn't stumble into this issue, so it's up to you whether it's actually a problem or not. (May also be fixed, if adding a try-catch won't be e performance issue):

```
try
        {
            for (int i = 0; i < capacity; i++) {
                long key = oldTable.key(i);
                if (key != nullKey) {
                    VALUE putResult = put(newTable, monitor, hashFunction, key, oldTable.value(i), resizeMonitor);
                    if (putResult != null) {
                        throw new IllegalStateException("Couldn't add " + key + " when growing table");
                    }
                }
            }
        }
        catch (IllegalStateException e)
        {
            // failed, so should return the old table back in its place
            resizeMonitor.tableGrew(oldTable);
            throw e;
        }
```

This is by far the most exciting debugging session I've ever had, however sloppy it was at first. Also, left me wondering how these little basic things can reveal themselves on a much higher level :)

**Comment by chrisvest** [comment]
@tkroman Impressive work. It turns out that the reason we haven't seen this manifest on 2.2, is because the default size of the collections are larger there, so they skip a lot of initial growing. But the recursive grow problem is still present.

**Comment by tkroman** [comment]
Thanks @chrisvest! I hope the fix, whatever form it will be in, will be available in the nearest update.

**Comment by tinwelint** [comment]
@tkroman that's a wonderful finding. I wonder though... couldn't we do something like this if a grow fails:
- Abort current grow, i.e. scrap the newTable
- Create a newTable with even more capacity, e.g. `capacity << 2`
- Populate and see if it fits, otherwise loop until it works (should rarely be multiple rounds in the loop)

Because I see no reason that a particular `put` should fail (seemingly randomly) and then another one succeed.

**Comment by tkroman** [comment]
@tinwelint, that would certainly reduce the number of interim allocations, but requires transforming current implementation into a non-recursive one (if we don't want to use exceptions for arbitrary jumps up the stack). Would you like me to try or are you taking the matter into your own hands? I'm mostly doing this in my free time, so there might be some pauses in development during workdays.

**Comment by tinwelint** [comment]
@tkroman I wouldn't mind taking it over to our development team because it's a bug in a core component of the product. So far thanks for great work and effort you've put into this.

**Comment by tkroman** [comment]
Found a bug in my proposition, did as @tinwelint suggested. Comment's here: https://github.com/chrisvest/neo4j/commit/fe06f3e7acd3420e9b610aa794660d94ae9c4108#commitcomment-16797890
