### ISSUE TITLE
500 Internal Server Error on concurrent relations creation

### ISSUE THREAD

**Issue by drgraduss** [neo4j/neo4j#6678]
I'm experiencing 500 Internal Server Error occasionally when performing concurrent writes to Neo4j. Query example below.

```
MATCH (u1:User {id:{id1}})
MATCH (u2:User {id:{id2}})
MERGE (u1)-[:FOLLOWS]->(u2)
```

In case of very popular user you can experience high number of concurrent relationship creations for the `u2` node.

At the moment I'm explicitly handling `DeadlockDetectedException` and have a retry logic in place. But from time to time I'm getting 500 from the server with response body below.

```
 <html>
     <head><title>500 Internal Server Error</title></head>
     <body bgcolor="white">
         <center><h1>500 Internal Server Error</h1></center>
         <hr><center>nginx</center>
      </body>
 </html>
```

Which gives me no clue what happened on the server. If I handle it and perform a retry everything works as expected. But this looks pretty dodgy as I basically guessing that in this particular case deadlock happened which might be wrong and unrelated to the actual server error.
- Neo4j version: 2.3.2
- CentOS
- .Net Neo4jClient v.1.1.0.29

Asked this question on [StackOverflow](http://stackoverflow.com/questions/35916869/neo4j-500-internal-server-error-on-concurrent-writes) with no response. So reporting it here.

**Comment by chrisvest** [comment]
Are there any exceptions printed to `console.log` or `messages.log`?

**Comment by drgraduss** [comment]
I'm closing this issue as it was related to our box ngnix configuration which gave generic 500 in some occasions instead of propagating `DeadlockDetectedException`.
