### ISSUE TITLE
Collecting Aggregation Documentation - Grammar

### ISSUE THREAD

**Issue by pmbaumgartner** [neo4j/neo4j#6714]
Found on: 
**The Neo4j Manual v2.3.2
3.4. Getting the Results You Want
Collecting Aggregation**
http://neo4j.com/docs/stable/cypherdoc-getting-the-results-you-want.html#_collecting_aggregation

First sentence:

> The most helpful aggregation function is collect, which, as the name says, collects all aggregated values into a real array or list. This comes very handy in many situations as you don’t **loose** the detail information while aggregating.

Correct to _lose_ instead of _loose_. http://grammarist.com/usage/loose-lose/

**Comment by spacecowboy** [comment]
Thanks, we'll correct this!
