### ISSUE TITLE
3.0.0 M05 - Cypher UPPERCASE versus lowercase has different query optimizations

### ISSUE THREAD

**Issue by brandonburkett** [neo4j/neo4j#6716]
Running different cased cypher queries gets different query optimizations and causing (in our case) a 68ms query to be 12s.  

**Neo4j version:** 3.0.0 M05
**Operating system:** OSX 10.11.3
**API/Driver:** Cypher through neo web browser
### Steps to reproduce
1. Have a large set a data for multiple labels (around 14 million rows or so for `:_IMAGE` in this case)
2. Run `match (i:_IMAGE) return count(i)` all lowercase and it is consistently fast. Running `explain` shows that `NodeCountFromCountStore` is being used.
3. Run `MATCH (i:_IMAGE) RETURN COUNT(i)` all uppercase and it is consistently slow. Running `explain` shows that `NodeByLabelScan` is being used.
4. Run `MaTcH (i:_IMAGE) ReTuRn CoUnT(i)` with mixed case and it is consistently slow. Running `explain` shows that `NodeByLabelScan` is being used.
### Expected behavior

Cypher to ❤️ queries, regardless of case.
### Actual behavior

Cypher ❤️ lowercase?  Cypher 💔 UPPERCASE and MiXeD CaSe?

We also poked around and saw some stuff in the test suite that just uses lowercase.

![lowercase](https://cloud.githubusercontent.com/assets/1877193/13797460/c0cd521c-eadb-11e5-8022-6b8d05bbdbc3.png)
![caps](https://cloud.githubusercontent.com/assets/1877193/13797462/c2d6b80a-eadb-11e5-96f7-d9f9af74917d.png)

**Comment by pontusmelke** [comment]
That is a little embarrassing :blush: 

I have created a PR for fixing this https://github.com/neo4j/neo4j/pull/6717. It should be fixed in the next milestone.

Thanks a bunch for reporting the error!
