### ISSUE TITLE
Feature Request - One config file to rule them all

### ISSUE THREAD

**Issue by versae** [neo4j/neo4j#673]
As discussed in the [list](https://groups.google.com/forum/?fromgroups=#!topic/neo4j/EYMul1CW6W0), I propose to have one single config for all the settings in Neo4j, for example a `neo4j.conf`. That file could have sections for the current config files:
- `neo4j.properties`, embedded graph db
- `neo4j-server.properties` jetty based servlet container around the embedded db
- `neo4j-wrapper.conf`, arguments and settings for the JVM that starts the servlet container

**Comment by chrisvest** [comment]
We now actually have collected all of those into a `neo4j.conf` file!  🎉
