### ISSUE TITLE
Regular expression operator surprise + documentation

### ISSUE THREAD

**Issue by aseemk** [neo4j/neo4j#6734]
Hi folks,

I was struggling to get a regex query to work, and then discovered that it was because `^` and `$` are implied in Neo4j's regex implementation!

``` cypher
// This returns false!
RETURN 'hello' =~ 'e'

// You have to manually say "anything before and after":
RETURN 'hello' =~ '.*e.*'
```

Is there a reason for this behavior? I'm not familiar with most other databases, but at least for programming languages (plus `grep` etc.), regexes typically _don't_ assume `^` and `$`.

(I wasn't sure about Java, but it _seems_ from online examples that Java is the same as well.)

—

Before I discovered this, I also tried to look for documentation on this operator, under the "Syntax" > "Operators" section where I'd expect it, and there's basically none:

http://neo4j.com/docs/stable/query-operators.html#query-operators-string

I then searched these issues, and discovered via pull #4833 that it's under `WHERE`:

http://neo4j.com/docs/snapshot/query-where.html#query-where-regex

So consider this feedback to maybe move this documentation to the actual operators section (the `WHERE` section could still link to it), since it applies to more than just `WHERE`.

And please also document non-standard behavior like implied `^` and `$`. =)

—

Thanks!

P.S. I'm running Neo4j 2.2.8.

**Comment by jexp** [comment]
Hey Aseem,

it's the java thing that it has to match the whole string, at least if you use `string.matches()` there are some other variants that can do substring, like `Pattern.matcher(string).find()`

**Comment by petraselmer** [comment]
Hi Aseem

Thanks very much for the feedback on the documentation. I have noted this, and we should be attending to it next week at the latest.

**Comment by aseemk** [comment]
Thanks folks.

I'm guessing a change to the behavior (which it sounds is possible) won't be considered, as it'd be a breaking change?

**Comment by jexp** [comment]
Would CONTAINS work for your use-case? 

Von meinem iPhone gesendet

**Comment by cleishm** [comment]
@aseemk: I doubt changing it would be a good option, considering that it could break existing usage. Much better to start adding alternatives, like CONTAINS, that achieve the same end-goals... and also have other advantages (like the potential to index).

**Comment by petraselmer** [comment]
@aseemk Circling back on this issue: the Cypher chapter has undergone a large change in recent months. These two links: [all ops at a glance](https://neo4j.com/docs/developer-manual/preview/cypher/syntax/operators/#query-operators-summary) and [string ops](https://neo4j.com/docs/developer-manual/preview/cypher/syntax/operators/#query-operators-string) should now reflect the gist of your suggestions. 

Moreover, the provided example (in second link) implicitly illustrates the implied usage of `^` and `$`.

I will therefore close this issue.

**Comment by asishallab** [comment]
Dear neo4j developers,

thanks for developing such a useful tool that is neo4j. This issue somehow remains a problem, as regular expressions are typically not implemented expecting whole string matches, except in Java and neo4j that is. In most other query languages to match whole strings you'd have to explicitly use the `^` and `$` operators. Hence Cypher regular expressions are counter intuitive to a degree. Furthermore the mentioned start (`^`) and end (`$`) operators become meaningless in most cases, except e.g. when aiming at matching multi-line texts. 

Would introducing a new operator like `=~f` for finding (in the Java sense) regular expressions inside a candidate string solve the problem with counter intuitive regular expression behavior while maintaining backwards compatibility?

Thank you for your attention and consideration.
