### ISSUE TITLE
Neo.DatabaseError.Statement.ExecutionFailure On 2.3.2 Enterprise

### ISSUE THREAD

**Issue by leunamnauj** [neo4j/neo4j#6761]
Executing the example query: "MATCH (n) RETURN n LIMIT 25" I got the following:
**"Property record with id 6 not in use"**
and in the bottom: **Neo.DatabaseError.Statement.ExecutionFailure**

According to my research this kind of issue got fixed on 2.3.1.
I'm not quite sure whats going on here, if it is a coding problem or a Neo4j cluster problem (this is a 3 nodes cluster)

Any advice or guidance?

Thanks in advance

**Comment by jexp** [comment]
You can raise a support ticket for your enterprise license.

In general if you take a backup from the store you should see if the consistency-checker returns any issues.

Can you check your graph.db/messages.log if your got any errors recently?

**Comment by leunamnauj** [comment]
Hello jexp!
First of all, thanks for your quick response.

**grep -i err messages.log 
2016-02-25 19:46:20.296+0000 ERROR [o.n.k.i.a.i.IndexPopulationJob] Failed to populate index: [:User(id) [provider: {key=lucene, version=1.0}]] DynamicRecord Not in use, blockId[4392]**

This is the only error I have. Seems to be a single event but I still wondering what would trigger it.

**Comment by jexp** [comment]
Can you try the other two things?

> You can raise a support ticket for your enterprise license.
> 
> In general if you take a backup from the store you should see if the consistency-checker returns any issues.

**Comment by leunamnauj** [comment]
I've performed consistency check and showed nothing. I'll raise a ticket to support.

Thanks

**Comment by chrisvest** [comment]
I'm going to close this under the assumption that this has long since been taken care of via the support channels. Otherwise feel free to reopen if this is still an issue.
