### ISSUE TITLE
Error on full build ("mvn clean package -DfullBuild")

### ISSUE THREAD

**Issue by jackbergus** [neo4j/neo4j#6790]
# Error on full build ("mvn clean package -DfullBuild")
- **Neo4j version**: 2.3.3
- **Operating system**: MacOs X El Capitan, 10.11.3
- **API/Driver**: (for example Cypher/Java API/Python driver vX.Y.Z)
- **Steps to reproduce**: Run the command `mvn clean package -DfullBuild`
- **Expected behavior**: the command halts successfully
- **Actual behaviour**: the compilation aborts with the following log 

> 1 error
> 1 warning
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary:
> [INFO]
> [INFO] Neo4j .............................................. SUCCESS [  1.036 s]
> [INFO] Neo4j - Licensing configuration .................... SUCCESS [  0.267 s]
> [INFO] Neo4j - Unsafe Access .............................. SUCCESS [  4.952 s]
> [INFO] Neo4j - Functions .................................. SUCCESS [  4.761 s]
> [INFO] Neo4j - Primitive Collections ...................... SUCCESS [ 27.346 s]
> [INFO] Neo4j - IO ......................................... SUCCESS [05:11 min]
> [INFO] Neo4j - CSV reading and parsing .................... SUCCESS [  6.417 s]
> [INFO] Neo4j - Logging .................................... SUCCESS [  7.694 s]
> [INFO] SLF4J Neo4j Binding ................................ SUCCESS [  9.928 s]
> [INFO] Neo4j - Code Generator ............................. SUCCESS [  7.273 s]
> [INFO] Neo4j - Graph Database Kernel ...................... SUCCESS [04:39 min]
> [INFO] Neo4j - JMX support ................................ SUCCESS [  8.219 s]
> [INFO] Neo4j - Usage Data Collection ...................... SUCCESS [ 10.164 s]
> [INFO] Neo4j - Monitor Logging ............................ SUCCESS [ 11.671 s]
> [INFO] Neo4j - Graphviz generation ........................ SUCCESS [  8.571 s]
> [INFO] Neo4j - Lucene Index ............................... SUCCESS [ 35.947 s]
> [INFO] Neo4j - Graph Algorithms ........................... SUCCESS [ 11.705 s]
> [INFO] Neo4j - Graph Matching ............................. SUCCESS [  8.821 s]
> [INFO] Neo4j - Community Cypher Build ..................... SUCCESS [  0.285 s]
> [INFO] Neo4j - Cypher Frontend 2.3 ........................ SUCCESS [ 44.104 s]
> [INFO] Neo4j - Cypher Compiler 2.3 ........................ SUCCESS [02:43 min]
> [INFO] Neo4j - Cypher ..................................... SUCCESS [04:40 min]
> [INFO] Neo4j - Legacy Consistency Checker ................. SUCCESS [01:19 min]
> [INFO] Neo4j - Consistency Checker ........................ SUCCESS [01:16 min]
> [INFO] Neo4j - Community .................................. SUCCESS [02:13 min]
> [INFO] Neo4j - Community .................................. SUCCESS [  0.025 s]
> [INFO] Neo4j - Generic shell .............................. SUCCESS [01:25 min]
> [INFO] Neo4j - Import Command Line Tool ................... SUCCESS [ 49.174 s]
> [INFO] Neo4j - Examples ................................... SUCCESS [ 27.483 s]
> [INFO] Neo4j - Server API ................................. SUCCESS [  7.229 s]
> [INFO] Neo4j - Browser .................................... SUCCESS [01:08 min]
> [INFO] Neo4j - Server ..................................... SUCCESS [02:06 min]
> [INFO] Neo4j - Test Harness ............................... SUCCESS [ 27.215 s]
> [INFO] Neo4j - Server Plugin Tests ........................ SUCCESS [  4.229 s]
> [INFO] Neo4j - Server Examples ............................ SUCCESS [ 23.131 s]
> [INFO] Neo4j - Cypher Acceptance .......................... SUCCESS [03:13 min]
> [INFO] Neo4j - Cypher Compatibility Suite ................. SUCCESS [ 50.191 s]
> [INFO] Neo4j - Community Build ............................ SUCCESS [  0.016 s]
> [INFO] Neo4j - Graph DB Monitoring and Management tools ... SUCCESS [ 10.709 s]
> [INFO] Neo4j - Advanced ................................... SUCCESS [  6.363 s]
> [INFO] Neo4j - Advanced Server ............................ SUCCESS [ 24.302 s]
> [INFO] Neo4j - Advanced Build ............................. SUCCESS [  0.015 s]
> [INFO] Neo4j - Query Logging .............................. SUCCESS [ 12.482 s]
> [INFO] Neo4j - Enterprise Graph Database Kernel Features .. SUCCESS [ 40.019 s]
> [INFO] Neo4j - Communication Package ...................... SUCCESS [ 20.664 s]
> [INFO] Neo4j - Clustering Infrastructure .................. SUCCESS [ 25.975 s]
> [INFO] Neo4j - Backup Tool ................................ SUCCESS [ 52.667 s]
> [INFO] Neo4j - High Availability .......................... SUCCESS [17:41 min]
> [INFO] Neo4j - Metrics Kernel Extension ................... SUCCESS [ 20.048 s]
> [INFO] Neo4j - Enterprise ................................. SUCCESS [  9.246 s]
> [INFO] Neo4j - Enterprise Server .......................... SUCCESS [ 44.448 s]
> [INFO] Neo4j - Enterprise Performance Tests ............... SUCCESS [ 14.230 s]
> [INFO] Neo4j - Enterprise Build ........................... SUCCESS [  0.029 s]
> [INFO] Neo4j - Integration Tests .......................... SUCCESS [ 54.086 s]
> [INFO] Neo4j - Stress Tests ............................... SUCCESS [  0.189 s]
> [INFO] Neo4j - Low Level Tools ............................ FAILURE [ 17.266 s]
> [INFO] Neo4j - Cypher Documentation Build ................. SKIPPED
> [INFO] Neo4j - GraphGist .................................. SKIPPED
> [INFO] Neo4j - Cypher Documentation ....................... SKIPPED
> [INFO] Neo4j - Test Harness Documentation tests ........... SKIPPED
> [INFO] Neo4j - Reference Manual Contents .................. SKIPPED
> [INFO] Neo4j - Javadocs ................................... SKIPPED
> [INFO] Neo4j - Cypher Reference Card Tests ................ SKIPPED
> [INFO] Neo4j - Cypher Reference Card ...................... SKIPPED
> [INFO] Neo4j - Reference Manual ........................... SKIPPED
> [INFO] Neo4j - Reference Manual Build ..................... SKIPPED
> [INFO] Neo4j - Server Assembler ........................... SKIPPED
> [INFO] Neo4j Community - Server Assembler ................. SKIPPED
> [INFO] Neo4j Advanced - Server Assembler .................. SKIPPED
> [INFO] Neo4j Enterprise - Server Assembler ................ SKIPPED
> [INFO] Neo4j Desktop ...................................... SKIPPED
> [INFO] Neo4j Packaging Build .............................. SKIPPED
> [INFO] Neo4j Debian Installers ............................ SKIPPED
> [INFO] Neo4j RPM Installers ............................... SKIPPED
> [INFO] Neo4j Community RPM ................................ SKIPPED
> [INFO] Neo4j Advanced RPM ................................. SKIPPED
> [INFO] Neo4j Enterprise RPM ............................... SKIPPED
> [INFO] Neo4j Linux Installers ............................. SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 01:00 h
> [INFO] Finished at: 2016-03-25T19:39:59+01:00
> [INFO] Final Memory: 358M/1559M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.3:jar (attach-javadoc) on project neo4j-tools: MavenReportException: Error while generating Javadoc:
> [ERROR] Exit code: 1 - /Users/vasistas/Downloads/neo4j-2.3.3/tools/src/main/java/org/neo4j/tools/console/input/ConsoleInput.java:69: error: reference not found
> [ERROR] \* @param command {@link Command} to {@link Command#run(String[]) run} as part of command line
> [ERROR] ^
> [ERROR] /Users/vasistas/Downloads/neo4j-2.3.3/tools/src/main/java/org/neo4j/tools/console/input/ConsoleInput.java:72: warning - Tag @link: can't find run(String[]) in org.neo4j.tools.console.input.Command
> [ERROR]
> [ERROR] Command line was: /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/../bin/javadoc @options @packages
> [ERROR]
> [ERROR] Refer to the generated Javadoc files in '/Users/vasistas/Downloads/neo4j-2.3.3/tools/target/apidocs' dir.
> [ERROR] -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
> [ERROR]
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR]   mvn <goals> -rf :neo4j-tools

**Comment by spacecowboy** [comment]
Minimal command invocation to reproduce:

```
mvn package -am -pl tools -DskipTests -T 2C -DskipBrowser -DfullBuild
```

Thank you for the report, but this is likely not something we will change. The fullBuild parameter will trigger several tasks which are related to building the manual, which require certain integration tests to be executed. So running `mvn install -DfullBuild` instead of `package` should resolve it.
