### ISSUE TITLE
Feature request: Consistent display of IDs vs. values in Neo4j browser app

### ISSUE THREAD

**Issue by rationalism** [neo4j/neo4j#6792]
I'm running neo4j 2.3.2 Enterprise on Ubuntu 15.10. When I try these commands in the neo4j browser app (at localhost:7474/browser/):

CREATE (n:dog {val: 10})
CREATE (n:cat {val:20})

and then these MATCH commands:

MATCH (n:dog) OPTIONAL MATCH (o:cat) RETURN n, o
MATCH (n:cat) OPTIONAL MATCH (o:dog) RETURN n, o

the "dog" node is colored blue and labeled with its ID (4010), while the "cat" node is left grey and labeled with its value (10). (Both MATCH commands above return the same result.) Here's a screenshot:

![neo4j_node_colors](https://cloud.githubusercontent.com/assets/813306/14059147/09d22f4c-f2f6-11e5-837d-3acacaf7b63d.png)

I think it would be good to be consistent - either always have colors that represent labels, or never do, and either always display the value or always display the node ID. I'm really not sure why these seemingly-similar nodes are displayed differently. I thought it might be that I created the dog node first and the cat node second, but I tried reversing the order of the CREATE statements, and the result was the same, so it's not that.

**Comment by chrisvest** [comment]
If you click the labels in the top bar, you can change their rendering settings.

**Comment by jexp** [comment]
you can also use `:style` to view the current GRASS stylesheet, which probably aggregated multiple label-stylings over the course of your work.

Vou might have configured the rendering for dog's before. By default it tries to use attributes like `name`, `title` as caption.

There are only a limited number of colors that the default styling chooses from. When they are used up, or nodes have no label, they will be rendered as default "gray".

Use `:style reset` to reset it to defaults.

**Comment by rationalism** [comment]
Cool! :style reset made it consistent, so I've closed this out.
