### ISSUE TITLE
Neo.DatabaseError.General.UnknownFailure

### ISSUE THREAD

**Issue by suryasumukh** [neo4j/neo4j#6793]
I'm trying to retrieve a bunch of nodes (order of 10,000's) with this query
`MATCH (node)
WHERE ID(node) in [...]
RETURN node
`
With the UI and i encounter this error -  Neo.DatabaseError.General.UnknownFailure. 
With neo4jrestclient, i get - 
TransactionException: Code [500]: Internal Server Error. Server got itself in trouble.
Element not found
I know for a fact that all the nodes i'm trying to retrieve is stored in the database.
- Neo4j version: 2.3.3 (Community Edition)
- Operating system: Ubuntu 15.10
- neo4jrestclient (2.1.1)
- Python 2.7.11 :: Anaconda 2.5.0 (64-bit)

![screen shot 2016-03-26 at 7 49 44 pm](https://cloud.githubusercontent.com/assets/7255741/14063566/0028d284-f38c-11e5-86dc-17ec4071efb1.png)
Any light on this error is much appreciated.
Thanks!

**Comment by jexp** [comment]
In the `</> Code` tab you should see the http response, can you share that too?

Can you try to return the count first?

The browser itself is not made for displaying 10k nodes.

`MATCH (node) WHERE ID(node) in [...] RETURN count(*)`

in real code you should use parameters

`MATCH (node) WHERE ID(node) in {ids} RETURN count(*)`

**Comment by suryasumukh** [comment]
Thanks jexp. Here's the HTTP response.
I got the same error with `count(*)`
[http_response.txt](https://github.com/neo4j/neo4j/files/212199/http_response.txt)
![screen shot 2016-04-10 at 6 55 49 pm](https://cloud.githubusercontent.com/assets/7255741/14415057/e01d380c-ff4f-11e5-9008-5c36db246d9b.png)

**Comment by jexp** [comment]
1. your query is probably too gigantic to parse
2. you should use parameters (in your program)
