### ISSUE TITLE
Improve/implement auth interface

### ISSUE THREAD

**Issue by dbkaplun** [neo4j/neo4j#6797]
Right now it seems the only way to update auth with a typical neo4j install is to [manually edit data/dbms/auth](http://neo4j.com/docs/stable/security-server.html#security-server-auth). It would be great if there was a RESTful endpoint that manages auth or an admin interface.

**Comment by jexp** [comment]
Actually manually editing that file is not recommended.

There is a REST API for managing auth, see: http://neo4j.com/docs/stable/rest-api-security.html

In Neo4j 3.0 there will be appropriate stored procedures.

**Comment by dbkaplun** [comment]
How can I create a new user?

**Comment by jexp** [comment]
That's currently not officially supported.

There is a community contribution for an extension doing it: 
https://leanjavaengineering.wordpress.com/2015/04/16/neo4j-2-2-authentication-and-adding-extra-users/
