### ISSUE TITLE
JVM tuning properties ignored on version 2.3.3 for mac

### ISSUE THREAD

**Issue by v4lenz** [neo4j/neo4j#6810]
This is my setting:
- Neo4j version: 2.3.3 (EDIT: I also tried the latest 3.0.0-M05)
- Operating system: osx 10.11.4
- Macbook air with 8GB of RAM

Through the GUI, I press "options" and then under the section Java VM Tuning I press "edit" to edit the file /Users/user/Documents/Neo4j/.neo4j-community.vmoptions. In particular I add -Xmx4g and then I restart the application and press "Start". This creates a new database in the path that I specify.
### Expected behavior

The JVM should get 4GB as maximum memory
### Actual behavior

The JVM still gets the default value as maximum memory, which for my configuration is 1.78GB.

Attached the messages.log file that clearly shows what I'm saying. This is a cut of the relevant part:

2016-03-29 21:06:23.312+0000 INFO  [o.n.k.i.DiagnosticsManager] JVM memory information:
2016-03-29 21:06:23.312+0000 INFO  [o.n.k.i.DiagnosticsManager] Free  memory: 74.25 MB
2016-03-29 21:06:23.312+0000 INFO  [o.n.k.i.DiagnosticsManager] Total memory: 123.00 MB
2016-03-29 21:06:23.312+0000 INFO  [o.n.k.i.DiagnosticsManager] Max   memory: 1.78 GB

[messages.log.zip](https://github.com/neo4j/neo4j/files/194353/messages.log.zip)

**Comment by spacecowboy** [comment]
@vdidonato The GUI seems to be editing an unused file. Memory settings are configured in the regular neo4j configuration file, please see the manual here: http://neo4j.com/docs/stable/server-performance.html

**Comment by v4lenz** [comment]
@spacecowboy Can you more specific? Because it says:

Tuning the standalone server is achieved by editing the neo4j-wrapper.conf file in the conf directory of NEO4J_HOME

I'm assuming that on mac the NEO4J_HOME is 
/Applications/Neo4j Community Edition.app/Contents/Resources/app

but there is no conf directory. Note that I also tried to manually create the conf directory and the neo4j-wrapper.conf file manually but the file is ignored in this case too.

**Comment by s-b-u** [comment]
Hi,
same behavoir on Windows.
It turns out that bin/neo4j-community.vmoptions has to be renamed to bin/neo4j-ce.vmoptions since the launcher is called neo4j-ce.exe.
To verify, start the launcher as neo4j-ce.exe /create-i4j-log and inspect the generated logfile.

**Comment by spacecowboy** [comment]
@s-b-u that's quite surprising. It should use `neo4j-community.vmoptions`.

@vdidonato the manual discusses the standalone installation which does not apply here (my mistake). It should pick up the options you specified in your original report.

**Comment by s-b-u** [comment]
Hi spacecowbay,

launcher name was changed with 63631c54800f3fbca820ef7b4d4b0c7cae610258 but neo4j-community.vmoptions was left untouched

**Comment by v4lenz** [comment]
I can confirm that on Windows changing the name of the file bin/neo4j-community.vmoptions to bin/neo4j-ce.vmoptions induces neo4j to consider the file \AppData\Romaing\Neo4j Community Edition\neo4j-community.vmoptions (that is the one accessed through the GUI). 

On mac things are a little bit different and it's yet not clear to me how to fix it..

**Comment by benbc** [comment]
I've re-labelled this as it's a Desktop-specific problem.

**Comment by oskarhane** [comment]
Since old neo4j-desktop is unmaintained and replaced with a completely new application this issue is no longer relevant.
