### ISSUE TITLE
3.0.0-SNAPSHOT of Mar. 30, 2016 - browser UI fails to connect to websocket over LAN

### ISSUE THREAD

**Issue by astesin** [neo4j/neo4j#6822]
![screenshot from 2016-03-31 03-21-22](https://cloud.githubusercontent.com/assets/7247555/14162273/27100894-f6f3-11e5-8153-7f237b3e02b0.png)
Built 3.0.0-SNAPSHOT from sources as of Mar. 30, 2016, got .deb installer built Ok.

Installed it Ubuntu 15.10 laptop with GUI, http://localhost:7474 works fine.
### Steps to reproduce

Copied the same .deb file to an Ubuntu Server 15.10 and installed it, configured neo4j.conf parameters:
- HTTP endpoint to listen at 0.0.0.0:7474
- BOLT endpoint to listen at 0.0.0.0:7687

From the same LAN segment in which server resides, pointed browser at http://servername.dom.ain:7474
### Actual behavior

HTML part of browser UI works, but it also wants to connect to ws://localhost:7687 (see screenshot) and browser fails. See screenshot.
### Expected behavior

UI respects configuration of BOLT listening address.
### Attempted workaround №1 - failed

In neo4j.conf set
- HTTP endpoint to listen at servername.dom.ain:7474
- BOLT endpoint to listen at servername.dom.ain:7687

Result: "ERR: connection refused" though neo4j.log tells me that HTTP interface started and available at http://servername.dom.ain:7474
### Attempted workaround №2 - failed

Server IP is 10.20.30.16, client box IP is 10.20.30.17 - in neo4j.conf I set server IP in numeric notation
- HTTP endpoint to listen at 10.20.30.16:7474
- BOLT endpoint to listen at 10.20.30.16:7687

Browser connects to HTTP UI endpoint but (similar to main case) the page tries to connect to ws://localhost:7687 instead of ws://10.20.30.16:7687 (effectively ignores config parameter).

WBR,
Andrii

**Comment by spacecowboy** [comment]
Thanks for the report. We'll look into it.

**Comment by oskarhane** [comment]
This is fixed in the lastest RC release.
