### ISSUE TITLE
Feature request: changes option for resultDataContents

### ISSUE THREAD

**Issue by venkatd** [neo4j/neo4j#6838]
It would be nice if I could pass `changes` as an option for for the `resultDataContents` in the same way I can pass in `rest`, `graph`, and `rows` and get back the following:
- Nodes created/updated/deleted
- Relationships created/updated/deleted

Motivation: we are building a reactive interface on the front end. Here is the workflow:
- Front end sends an API call to our backend
- Backend performs some operations on the neo4j db
- Backend returns back success/failure along with a changeset
- Front end performs an incremental update of its views based on what was changed

When I execute a cypher query, I get back a message like this:

> Created 2 nodes, created 1 relationship, statement executed in 13 ms.

So it seems like the information is there but just not being exposed.

Thoughts?

**Comment by jexp** [comment]
You probably mean this:

http://neo4j.com/docs/stable/rest-api-transactional.html#rest-api-include-query-statistics
