### ISSUE TITLE
Neo4j CE 2.3.3 "TLS certificate error occurred..." when switch to new empty folder.

### ISSUE THREAD

**Issue by ghost** [neo4j/neo4j#6839]
"TLS certificate error occurred, unable to start server: java.io.IOException:
Parse Generalized time, invalid format" when switch to new empty folder.
- Neo4j version: CE 2.3.3
- OS: Windows 7 (64bit)
- Java 8u77 (64bit)

Attach image show the alert windows.
![neo4j_2 3 3 tls error](https://cloud.githubusercontent.com/assets/5121989/14228600/0e15792a-f944-11e5-9e9a-d5131f3f0c01.jpg)
### Steps to reproduce
1. Start Neo4j from shortcuts
2. Click 'Choose' and select empty folder for new 'Database Location'.
3. Click 'Start' server., then alert show as attached image.
   Note: no error when reproduce with Neo4j CE 2.3.2
### Expected behavior

The server should create new database in empty folder and start server successfully.
### Actual behavior

Files in folder after error.
newfolder/
-- neo4j.properties
-- dbms/
---- ssl/
-------- snakeoil.cert
-------- snakeoil.key
### Other question
- Why is there 'jre' (version 1.7.0_80) folder in 'Neo4j CE 2.3.3' binary?
  Neo4j CE 2.3.2 don't have this folder.

**Comment by craigtaverner** [comment]
I'm under the impression this old issue no longer exists, but feel free to re-open it if it is still a problem.
