### ISSUE TITLE
Error on full build 2 ("mvn install -DfullBuild")

### ISSUE THREAD

**Issue by jackbergus** [neo4j/neo4j#6840]
- Neo4j version: 2.3.3
- Operating system: MacOs X El Capitan, 10.11.3
- API/Driver: current version
- Steps to reproduce: Run the command `mvn install -DfullBuild`
- Expected behavior: the command halts successfully
- Actual behaviour: the compilation aborts with the following log

> Tests run: 6, Failures: 0, Errors: 6, Skipped: 0, Time elapsed: 0.263 sec <<< FAILURE! - in org.neo4j.shell.TestReadOnlyServer
> executeWriteCommands(org.neo4j.shell.TestReadOnlyServer)  Time elapsed: 0.089 sec  <<< ERROR!
> java.lang.VerifyError: Bad type on operand stack
> Exception Details:
>   Location:
>     org/neo4j/shell/kernel/ReadOnlyGraphDatabaseProxy.lambda$nodes$3(Lorg/neo4j/graphdb/ResourceIterable;)Lorg/neo4j/graphdb/ResourceIterator; @7: invokedynamic
>   Reason:
>     Type 'org/neo4j/graphdb/ResourceIterable' (current frame, stack[1]) is not assignable to 'org/neo4j/shell/kernel/ReadOnlyGraphDatabaseProxy'
>   Current Frame:
>     bci: @7
>     flags: { }
>     locals: { 'org/neo4j/graphdb/ResourceIterable' }
>     stack: { 'org/neo4j/graphdb/ResourceIterator', 'org/neo4j/graphdb/ResourceIterable' }
>   Bytecode:
>     0x0000000: 2ab9 0042 0100 2aba 0043 0000 b900 4402
>     0x0000010: 00b0
> 
>   at org.neo4j.shell.TestReadOnlyServer.newServer(TestReadOnlyServer.java:37)
> 
> executeWriteCommands(org.neo4j.shell.TestReadOnlyServer)  Time elapsed: 0.089 sec  <<< ERROR!
> java.lang.NullPointerException: null
>   at org.neo4j.shell.AbstractShellTest.doAfter(AbstractShellTest.java:104)
>   at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:483)
>   at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
>   at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
>   at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
>   at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
>   at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
>   at org.junit.rules.RunRules.evaluate(RunRules.java:20)
>   at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
>   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
>   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
>   at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
>   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
>   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
>   at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
>   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
>   at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
>   at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
>   at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
>   at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
>   at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
>   at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
>   at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
> 
> readOnlyTransactionsShouldNotFail(org.neo4j.shell.TestReadOnlyServer)  Time elapsed: 0.087 sec  <<< ERROR!
> java.lang.VerifyError: Bad type on operand stack
> Exception Details:
>   Location:
>     org/neo4j/shell/kernel/ReadOnlyGraphDatabaseProxy.lambda$nodes$3(Lorg/neo4j/graphdb/ResourceIterable;)Lorg/neo4j/graphdb/ResourceIterator; @7: invokedynamic
>   Reason:
>     Type 'org/neo4j/graphdb/ResourceIterable' (current frame, stack[1]) is not assignable to 'org/neo4j/shell/kernel/ReadOnlyGraphDatabaseProxy'
>   Current Frame:
>     bci: @7
>     flags: { }
>     locals: { 'org/neo4j/graphdb/ResourceIterable' }
>     stack: { 'org/neo4j/graphdb/ResourceIterator', 'org/neo4j/graphdb/ResourceIterable' }
>   Bytecode:
>     0x0000000: 2ab9 0042 0100 2aba 0043 0000 b900 4402
>     0x0000010: 00b0
> 
>   at org.neo4j.shell.TestReadOnlyServer.newServer(TestReadOnlyServer.java:37)
> 
> readOnlyTransactionsShouldNotFail(org.neo4j.shell.TestReadOnlyServer)  Time elapsed: 0.087 sec  <<< ERROR!
> java.lang.NullPointerException: null
>   at org.neo4j.shell.AbstractShellTest.doAfter(AbstractShellTest.java:104)
>   at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:483)
>   at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
>   at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
>   at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
>   at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
>   at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
>   at org.junit.rules.RunRules.evaluate(RunRules.java:20)
>   at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
>   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
>   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
>   at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
>   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
>   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
>   at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
>   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
>   at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
>   at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
>   at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
>   at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
>   at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
>   at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
>   at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
> 
> executeReadCommands(org.neo4j.shell.TestReadOnlyServer)  Time elapsed: 0.086 sec  <<< ERROR!
> java.lang.VerifyError: Bad type on operand stack
> Exception Details:
>   Location:
>     org/neo4j/shell/kernel/ReadOnlyGraphDatabaseProxy.lambda$nodes$3(Lorg/neo4j/graphdb/ResourceIterable;)Lorg/neo4j/graphdb/ResourceIterator; @7: invokedynamic
>   Reason:
>     Type 'org/neo4j/graphdb/ResourceIterable' (current frame, stack[1]) is not assignable to 'org/neo4j/shell/kernel/ReadOnlyGraphDatabaseProxy'
>   Current Frame:
>     bci: @7
>     flags: { }
>     locals: { 'org/neo4j/graphdb/ResourceIterable' }
>     stack: { 'org/neo4j/graphdb/ResourceIterator', 'org/neo4j/graphdb/ResourceIterable' }
>   Bytecode:
>     0x0000000: 2ab9 0042 0100 2aba 0043 0000 b900 4402
>     0x0000010: 00b0
> 
>   at org.neo4j.shell.TestReadOnlyServer.newServer(TestReadOnlyServer.java:37)
> 
> executeReadCommands(org.neo4j.shell.TestReadOnlyServer)  Time elapsed: 0.086 sec  <<< ERROR!
> java.lang.NullPointerException: null
>   at org.neo4j.shell.AbstractShellTest.doAfter(AbstractShellTest.java:104)
>   at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:483)
>   at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
>   at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
>   at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
>   at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
>   at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
>   at org.junit.rules.RunRules.evaluate(RunRules.java:20)
>   at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
>   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
>   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
>   at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
>   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
>   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
>   at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
>   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
>   at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
>   at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
>   at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
>   at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
>   at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
>   at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
>   at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
> 
> Running org.neo4j.shell.TestRmiPublication
> Welcome to the Neo4j Shell! Enter 'help' for a list of commands
> 
> Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.421 sec - in org.neo4j.shell.TestRmiPublication
> Running org.neo4j.shell.TestTransactionApps
> Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 30.6 sec - in org.neo4j.shell.TestTransactionApps
> 
> Results :
> 
> Tests in error:
>   TestReadOnlyServer>AbstractShellTest.doBefore:72->newServer:37 Verify Bad type...
>   TestReadOnlyServer>AbstractShellTest.doAfter:104 » NullPointer
>   TestReadOnlyServer>AbstractShellTest.doBefore:72->newServer:37 Verify Bad type...
>   TestReadOnlyServer>AbstractShellTest.doAfter:104 » NullPointer
>   TestReadOnlyServer>AbstractShellTest.doBefore:72->newServer:37 Verify Bad type...
>   TestReadOnlyServer>AbstractShellTest.doAfter:104 » NullPointer
> 
> Tests run: 138, Failures: 0, Errors: 6, Skipped: 1

**Comment by spacecowboy** [comment]
This is typically a problem with your environment or class path. See http://stackoverflow.com/questions/100107/reasons-of-getting-a-java-lang-verifyerror

Try a `mvn clean` first. Possibly even `git clean -fxd`.

**Comment by jackbergus** [comment]
There is still an error

> executeWriteCommands(org.neo4j.shell.TestReadOnlyServer)  Time elapsed: 0.092 sec  <<< ERROR!
> java.lang.VerifyError: Bad type on operand stack
> Exception Details:
>   Location:
>     org/neo4j/shell/kernel/ReadOnlyGraphDatabaseProxy.lambda$nodes$3(Lorg/neo4j/graphdb/ResourceIterable;)Lorg/neo4j/graphdb/ResourceIterator; @7: invokedynamic
>   Reason:
>     Type 'org/neo4j/graphdb/ResourceIterable' (current frame, stack[1]) is not assignable to 'org/neo4j/shell/kernel/ReadOnlyGraphDatabaseProxy'
>   Current Frame:
>     bci: @7
>     flags: { }
>     locals: { 'org/neo4j/graphdb/ResourceIterable' }
>     stack: { 'org/neo4j/graphdb/ResourceIterator', 'org/neo4j/graphdb/ResourceIterable' }
>   Bytecode:
>     0x0000000: 2ab9 0042 0100 2aba 0043 0000 b900 4402
>     0x0000010: 00b0
> 
>   at org.neo4j.shell.TestReadOnlyServer.newServer(TestReadOnlyServer.java:37)
> 
> executeWriteCommands(org.neo4j.shell.TestReadOnlyServer)  Time elapsed: 0.092 sec  <<< ERROR!
> java.lang.NullPointerException: null
>   at org.neo4j.shell.AbstractShellTest.doAfter(AbstractShellTest.java:104)
>   at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:483)
>   at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
>   at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
>   at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
>   at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
>   at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
>   at org.junit.rules.RunRules.evaluate(RunRules.java:20)
>   at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
>   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
>   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
>   at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
>   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
>   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
>   at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
>   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
>   at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
>   at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
>   at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
>   at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
>   at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
>   at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
>   at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
> 
> readOnlyTransactionsShouldNotFail(org.neo4j.shell.TestReadOnlyServer)  Time elapsed: 0.079 sec  <<< ERROR!
> java.lang.VerifyError: Bad type on operand stack
> Exception Details:
>   Location:
>     org/neo4j/shell/kernel/ReadOnlyGraphDatabaseProxy.lambda$nodes$3(Lorg/neo4j/graphdb/ResourceIterable;)Lorg/neo4j/graphdb/ResourceIterator; @7: invokedynamic
>   Reason:
>     Type 'org/neo4j/graphdb/ResourceIterable' (current frame, stack[1]) is not assignable to 'org/neo4j/shell/kernel/ReadOnlyGraphDatabaseProxy'
>   Current Frame:
>     bci: @7
>     flags: { }
>     locals: { 'org/neo4j/graphdb/ResourceIterable' }
>     stack: { 'org/neo4j/graphdb/ResourceIterator', 'org/neo4j/graphdb/ResourceIterable' }
>   Bytecode:
>     0x0000000: 2ab9 0042 0100 2aba 0043 0000 b900 4402
>     0x0000010: 00b0
> 
>   at org.neo4j.shell.TestReadOnlyServer.newServer(TestReadOnlyServer.java:37)
> 
> readOnlyTransactionsShouldNotFail(org.neo4j.shell.TestReadOnlyServer)  Time elapsed: 0.079 sec  <<< ERROR!
> java.lang.NullPointerException: null
>   at org.neo4j.shell.AbstractShellTest.doAfter(AbstractShellTest.java:104)
>   at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:483)
>   at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
>   at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
>   at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
>   at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
>   at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
>   at org.junit.rules.RunRules.evaluate(RunRules.java:20)
>   at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
>   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
>   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
>   at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
>   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
>   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
>   at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
>   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
>   at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
>   at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
>   at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
>   at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
>   at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
>   at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
>   at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
> 
> executeReadCommands(org.neo4j.shell.TestReadOnlyServer)  Time elapsed: 0.088 sec  <<< ERROR!
> java.lang.VerifyError: Bad type on operand stack
> Exception Details:
>   Location:
>     org/neo4j/shell/kernel/ReadOnlyGraphDatabaseProxy.lambda$nodes$3(Lorg/neo4j/graphdb/ResourceIterable;)Lorg/neo4j/graphdb/ResourceIterator; @7: invokedynamic
>   Reason:
>     Type 'org/neo4j/graphdb/ResourceIterable' (current frame, stack[1]) is not assignable to 'org/neo4j/shell/kernel/ReadOnlyGraphDatabaseProxy'
>   Current Frame:
>     bci: @7
>     flags: { }
>     locals: { 'org/neo4j/graphdb/ResourceIterable' }
>     stack: { 'org/neo4j/graphdb/ResourceIterator', 'org/neo4j/graphdb/ResourceIterable' }
>   Bytecode:
>     0x0000000: 2ab9 0042 0100 2aba 0043 0000 b900 4402
>     0x0000010: 00b0
> 
>   at org.neo4j.shell.TestReadOnlyServer.newServer(TestReadOnlyServer.java:37)
> 
> executeReadCommands(org.neo4j.shell.TestReadOnlyServer)  Time elapsed: 0.088 sec  <<< ERROR!
> java.lang.NullPointerException: null
>   at org.neo4j.shell.AbstractShellTest.doAfter(AbstractShellTest.java:104)
>   at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:483)
>   at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
>   at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
>   at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
>   at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
>   at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
>   at org.junit.rules.RunRules.evaluate(RunRules.java:20)
>   at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
>   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
>   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
>   at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
>   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
>   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
>   at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
>   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
>   at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
>   at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
>   at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
>   at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
>   at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
>   at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
>   at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
> 
> Running org.neo4j.shell.TestRmiPublication
> Welcome to the Neo4j Shell! Enter 'help' for a list of commands
> 
> Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.293 sec - in org.neo4j.shell.TestRmiPublication
> Running org.neo4j.shell.TestTransactionApps
> Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 30.598 sec - in org.neo4j.shell.TestTransactionApps
> 
> Results :
> 
> Tests in error:
>   TestReadOnlyServer>AbstractShellTest.doBefore:72->newServer:37 Verify Bad type...
>   TestReadOnlyServer>AbstractShellTest.doAfter:104 » NullPointer
>   TestReadOnlyServer>AbstractShellTest.doBefore:72->newServer:37 Verify Bad type...
>   TestReadOnlyServer>AbstractShellTest.doAfter:104 » NullPointer
>   TestReadOnlyServer>AbstractShellTest.doBefore:72->newServer:37 Verify Bad type...
>   TestReadOnlyServer>AbstractShellTest.doAfter:104 » NullPointer
> 
> Tests run: 138, Failures: 0, Errors: 6, Skipped: 1
> 
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary:
> [INFO]
> [INFO] Neo4j .............................................. SUCCESS [  2.352 s]
> [INFO] Neo4j - Licensing configuration .................... SUCCESS [  0.309 s]
> [INFO] Neo4j - Common ..................................... SUCCESS [ 11.162 s]
> [INFO] Neo4j - Resource interface ......................... SUCCESS [  3.595 s]
> [INFO] Neo4j - Collections ................................ SUCCESS [  8.190 s]
> [INFO] Neo4j - Unsafe Access .............................. SUCCESS [  6.398 s]
> [INFO] Neo4j - Primitive Collections ...................... SUCCESS [ 44.598 s]
> [INFO] Neo4j - Graph Database API ......................... SUCCESS [ 10.256 s]
> [INFO] Neo4j - IO ......................................... SUCCESS [04:13 min]
> [INFO] Neo4j - CSV reading and parsing .................... SUCCESS [ 15.935 s]
> [INFO] Neo4j - Logging .................................... SUCCESS [ 12.605 s]
> [INFO] Neo4j - Security ................................... SUCCESS [ 13.644 s]
> [INFO] SLF4J Neo4j Binding ................................ SUCCESS [  7.907 s]
> [INFO] Neo4j - Code Generator ............................. SUCCESS [ 11.545 s]
> [INFO] Neo4j - Lucene Index Upgrade ....................... SUCCESS [  7.041 s]
> [INFO] Neo4j - Graph Database Kernel ...................... SUCCESS [07:19 min]
> [INFO] Neo4j - JMX support ................................ SUCCESS [ 14.432 s]
> [INFO] Neo4j - Usage Data Collection ...................... SUCCESS [ 16.308 s]
> [INFO] Neo4j - Monitor Logging ............................ SUCCESS [ 13.514 s]
> [INFO] Neo4j - Graphviz generation ........................ SUCCESS [ 13.401 s]
> [INFO] Neo4j - Lucene Index ............................... SUCCESS [02:12 min]
> [INFO] Neo4j - Graph Algorithms ........................... SUCCESS [ 20.539 s]
> [INFO] Neo4j - Graph Matching ............................. SUCCESS [ 13.162 s]
> [INFO] Neo4j - Community Cypher Build ..................... SUCCESS [  0.329 s]
> [INFO] Neo4j - Cypher Frontend 3.1 ........................ SUCCESS [01:29 min]
> [INFO] Neo4j - Cypher Compiler 3.1 ........................ SUCCESS [06:10 min]
> [INFO] Neo4j - Cypher ..................................... SUCCESS [10:12 min]
> [INFO] Neo4j - Consistency Checker ........................ SUCCESS [02:27 min]
> [INFO] Neo4j - Community .................................. SUCCESS [05:09 min]
> [INFO] Neo4j - Community .................................. SUCCESS [  0.052 s]
> [INFO] Neo4j - Generic shell .............................. FAILURE [01:01 min]
> [INFO] Neo4j - Import Command Line Tool ................... SKIPPED
> [INFO] Neo4j - Server API ................................. SKIPPED
> [INFO] Neo4j - Bolt Protocol Version 1 .................... SKIPPED
> [INFO] Neo4j - Database Management System ................. SKIPPED
> [INFO] Neo4j - Server ..................................... SKIPPED
> [INFO] Neo4j - Server Plugin Tests ........................ SKIPPED
> [INFO] Neo4j - Test Harness ............................... SKIPPED
> [INFO] Neo4j - Cypher Acceptance .......................... SKIPPED
> [INFO] Neo4j - Cypher Compatibility Suite ................. SKIPPED
> [INFO] Neo4j - Community Build ............................ SKIPPED
> [INFO] Neo4j - Query Logging .............................. SKIPPED
> [INFO] Neo4j - Enterprise Graph Database Kernel Features .. SKIPPED
> [INFO] Neo4j - Communication Package ...................... SKIPPED
> [INFO] Neo4j - Clustering Infrastructure .................. SKIPPED
> [INFO] Neo4j - Backup Tool ................................ SKIPPED
> [INFO] Neo4j - Graph DB Monitoring and Management tools ... SKIPPED
> [INFO] Neo4j - High Availability .......................... SKIPPED
> [INFO] Neo4j - Core Edge .................................. SKIPPED
> [INFO] Neo4j - Metrics Kernel Extension ................... SKIPPED
> [INFO] Neo4j - Enterprise ................................. SKIPPED
> [INFO] Neo4j - Enterprise Server .......................... SKIPPED
> [INFO] Neo4j - Enterprise Test Harness .................... SKIPPED
> [INFO] Neo4j - Enterprise Build ........................... SKIPPED
> [INFO] Neo4j - Integration Tests .......................... SKIPPED
> [INFO] Neo4j - Stress Tests ............................... SKIPPED
> [INFO] Neo4j - Low Level Tools ............................ SKIPPED
> [INFO] Neo4j - Cypher Documentation Build ................. SKIPPED
> [INFO] Neo4j - GraphGist .................................. SKIPPED
> [INFO] Neo4j - Cypher Documentation ....................... SKIPPED
> [INFO] Neo4j - Examples ................................... SKIPPED
> [INFO] Neo4j - Test Harness Documentation tests ........... SKIPPED
> [INFO] Neo4j - Server Examples ............................ SKIPPED
> [INFO] Neo4j - Reference Manual Contents .................. SKIPPED
> [INFO] Neo4j - Javadocs ................................... SKIPPED
> [INFO] Neo4j - Cypher Reference Card Tests ................ SKIPPED
> [INFO] Neo4j - Cypher Reference Card ...................... SKIPPED
> [INFO] Neo4j - Reference Manual ........................... SKIPPED
> [INFO] Neo4j - Test Harness Enterprise Documentation tests  SKIPPED
> [INFO] Neo4j - Reference Manual Build ..................... SKIPPED
> [INFO] Neo4j - Server Assembler ........................... SKIPPED
> [INFO] Neo4j Community - Server Assembler ................. SKIPPED
> [INFO] Neo4j Enterprise - Server Assembler ................ SKIPPED
> [INFO] Neo4j Desktop ...................................... SKIPPED
> [INFO] Neo4j Packaging Build .............................. SKIPPED
> [INFO] Neo4j Debian Installers ............................ SKIPPED
> [INFO] Neo4j RPM Installers ............................... SKIPPED
> [INFO] Neo4j Community RPM ................................ SKIPPED
> [INFO] Neo4j Enterprise RPM ............................... SKIPPED
> [INFO] Neo4j Linux Installers ............................. SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 44:25 min
> [INFO] Finished at: 2016-04-08T12:57:45+02:00
> [INFO] Final Memory: 159M/1841M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.15:test (default-test) on project neo4j-shell: There are test failures.
> [ERROR]
> [ERROR] Please refer to /Users/vasistas/Downloads/neo4j/community/shell/target/surefire-reports for the individual test results.
> [ERROR] -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
> [ERROR]
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR]   mvn <goals> -rf :neo4j-shell
