### ISSUE TITLE
[feature request]Add support for multiple index readers in queries

### ISSUE THREAD

**Issue by tkroman** [neo4j/neo4j#6841]
This is not allowed currently:

```
MATCH (x:Person{name:"john", surname:"doe"})
USING INDEX x:Person(name)
USING INDEX x:Person(surname)
```

or 

```
MATCH (x:Person)
USING INDEX x:Person(dob)
USING INDEX x:Person(name)
WHERE x.dob > "12312323"   // e.g. day of birth unixtime
AND x.name = "john"
```

It's possible to use multiple index readers in Lucene, so there's just a matter of utilizing this feature in existing infrastructure.

**Comment by rationalism** [comment]
@tkroman This might already be covered in 3.0? See the discussion at issue #6588

**Comment by tkroman** [comment]
@rationalism, I've seen that thread (I've even replied there), but from what I understand, hash joins are limited as of now, e.g. they don't support WHERE clause etc. I'd be happy to be mistaken, though.

**Comment by craigtaverner** [comment]
The first of the two queries is solved by the addition of _composite indexes_ in Neo4j 3.2. It allows multiple equality predicates to be simultaneously solved by a single index.

The second query could also be solved by the composite indexes, mixing equality, range and existence predicates. But this is not yet available, and it is not certain which release of Neo4j this will be supported in.

Try Neo4j 3.2 and see if the composite index feature works well enough for your needs. See the relevant docs at http://neo4j.com/docs/developer-manual/current/cypher/schema/index/#use-a-composite-index-with-where-using-equality

**Comment by tkroman** [comment]
@craigtaverner even though I haven't used neo4j in prod for quite some time, it's really great to see this thing implemented. Thanks to everyone on neo4j team :)
