### ISSUE TITLE
Optional match is not anchoring correctly

### ISSUE THREAD

**Issue by dmikov** [neo4j/neo4j#6862]
Following query returns results almost correctly 
`match (n:Employee)-[:USE]->(c:Computer)-[:OCCUR]->(i:Incident) where c.netbios_name='cole' return i.name as name, count(n.lastname) as cnt`

> name  cnt
> ddos  147
> ratter    184
> rootkit   151
> spear 158
> worm  182
> policy    190
> virus 174
> trojan    152
> phishing  136

However since we might want to show computers not associated with incidents, following optional match is introduced. It looks however that (c) node is not anchored to the where clause or match clause
`match (n:Employee)-[:USE]->(c:Computer) optional match (c)-[:OCCUR]->(i:Incident) where c.netbios_name='cole' return i.name as name, count(n.lastname) as cnt`

> name  cnt
> 
> ddos  147
> ratter    184
> rootkit   151
> spear 158
> worm  182
> policy    190
> trojan    152
> virus 174
> phishing  136
> **> null    999105**

**Comment by jexp** [comment]
This where clause belongs to the match clause not the optional one

It is pulled into the matching process of the preceding clause it belongs to

Like ON in sql JOIN

**Comment by dmikov** [comment]
Thank you. #Slapforehead.

**Comment by spacecowboy** [comment]
@dmikov did this resolve your issue and can it be closed now?

**Comment by manonthemat** [comment]
Didn't know this either, but this is from the [docs](http://neo4j.com/docs/stable/query-optional-match.html): 

> Either the whole pattern is matched, or nothing is matched. Remember that WHERE is part of the pattern description, and the predicates will be considered while looking for matches, not after. This matters especially in the case of multiple (OPTIONAL) MATCH clauses, where it is crucial to put WHERE together with the MATCH it belongs to.

**Comment by dmikov** [comment]
Yes, it resolved the issue. Ergo slapping my forehead :)
Thank you very much Manonthemat. I will try to avoid where from now on. It is not easy using .net client, but I will try to put it as json on node match part.

**Comment by chrisvest** [comment]
Yeah, `match … optional match … where … return …` is interpreted as `match … (optional match … where …) return …`, so you probably want to write `match … where … optional match … return …` instead.
