### ISSUE TITLE
Error while running "mvn clean install exec:java" seems no config?

### ISSUE THREAD

**Issue by HaFoLuoKe** [neo4j/neo4j#6885]
hi, while running mvn clean install exec:java 
it throws exception :

WARN Config file [/home/myname/neo4j-3.0/community/server/neo4j-home/conf/neo4j.conf] does not exist.
Failed to start Neo4j on unknown address An HTTP connector must be configured to run the server
java.lang.IllegalArgumentException: An HTTP connector must be configured to run the server
at org.neo4j.server.AbstractNeoServer.lambda$new$0(AbstractNeoServer.java:153)

seems need some config files ?
what should I do to start the server?

**Comment by spacecowboy** [comment]
It is not intended that you should be able to start it in this way.

There probably is a way that is similar to what you want to do, but TBH I always build the tarball, then extract and start it. E.g.

``` bash
mvn clean install -DdocsBuild
cd packaging
mvn clean install
cd standalone/target
cp neo4j-community-3.0.0-SNAPSHOT-unix.tar.gz /PATH/TO/SOMEDIR
cd /PATH/TO/SOMEDIR
tar zxvf neo4j-community-3.0.0-SNAPSHOT-unix.tar.gz
cd neo4j-community-3.0.0-SNAPSHOT
bin/neo4j console
```
