### ISSUE TITLE
Documentation request: Neo4j warmup period

### ISSUE THREAD

**Issue by rationalism** [neo4j/neo4j#6894]
Hello. This isn't really a bug, but something that I think might be good to add to the neo4j documentation. I've heard rumors of a "warm-up period" for neo4j before, but the effect is really very dramatic, and I think it should be emphasized more. It threw me off for a while when trying to write some simple performance tests in a naive way.

As a quick demo, I blanked the database, and then ran the query:

CREATE (n:dog {val:3})

followed by the query: 

MATCH (n) WHERE ID(n) = (.... ID of the node....) RETURN n.val

This is about as simple as it gets: form one node, store one value, retrieve the value.

Then I tried the query (in Clojure):

(->> "MATCH (n) WHERE ID(n) = (.... ID of the node....) RETURN n.val" (repeat 1000) cypher-combined-tx)

which creates a transaction where the same query is run one thousand times in a row. This should be very fast, as it's just retrieving one piece of data from one node, and the queries are all identical so caching should be very simple.

When testing, this transaction took 30.1 seconds (30,100 us per query). That's pretty slow.

But if I try:

(->> "CREATE (n:dog {val:3})" (repeat 100000) cypher-combined-tx)

i.e. create 100,000 nodes of this type (all the same), this time each query is dramatically faster. This whole thing took 2.7 seconds, or 27 us per query. That's three orders of magnitude faster! Quite a huge difference.

And then if I try, after creating all the nodes above:

MATCH (n) RETURN ID(n) LIMIT 1

(->> "MATCH (n) WHERE ID(n) = (.... ID from the first query....) RETURN n.val" (repeat 100000) cypher-combined-tx)

suddenly, it is now lightning-fast. This whole thing takes 0.94 seconds, or 9.4 us per query. Three and a half orders of magnitude of speedup. Maybe there's something on my system which is unusual and is throwing off these results, but if not, I think it's important to let people know about how big this difference is, so they don't come away thinking that neo4j is much slower than it really is.

**Comment by ikwattro** [comment]
Did you used parameters for the `WHERE id(n) = ...` ?

Actually, I get it in 89ms, 1000 cypher statements with parameters

**Comment by jexp** [comment]
It's probably just JVM just in time compilation (which kicks in after 10k iterations of a piece of code).

You should use parameters for the id's and values to make sure your queries are cached.

Are you running this embedded or via http?

**Comment by rationalism** [comment]
This is via HTTP, not embedded. The cypher-combined-tx function I'm using here is a wrapper around the Neocons function clojurewerkz.neocons.rest.transaction/in-transaction, which is in turn a wrapper around http://neo4j.com/docs/milestone/rest-api-transactional.html#rest-api-begin-and-commit-a-transaction-in-one-request in the neo4j API.

I tried blanking the database again (with "MATCH (n) DETACH DELETE n"), and then re-running everything above with parameters in queries, instead of raw strings. There weren't any noticeable speed changes, either for CREATE or for MATCH.

Blanking the database, re-inserting a single node, and then running "MATCH (n) WHERE ID(n) = {id} RETURN n.val" {:id 115977} 11,000 times was actually even slower per query than running it 1,000 times, so there doesn't seem to be a "threshold effect" where groups of more than 10,000 queries are executed faster than groups of fewer than 10,000 queries. This took 40,100 us per query (or 441.2 seconds for 11,000 total), compared to 30,100 us per query previously. 

This is a bit off-topic, but when I Google 'neo4j prepared statements', there are results on StackOverflow, GitHub, etc. but not on the neo4j website. Is there a difference between "prepared statements" in traditional SQL, and "parameters" in neo4j Cypher? Or are these just two different names for the same thing? Thanks.

**Comment by rationalism** [comment]
FWIW, using parameters did make things much faster when the IDs were all different. Running the query:

MATCH (n) WHERE ID(n) = xxxxxx RETURN n.val

where xxxxxx is substituted with a string, took 9.2 seconds for a set of 10,000 queries with 10,000 different IDs (920 usec/query). Running:

MATCH (n) WHERE ID(n) = {id} RETURN n.val

and then using a parameter for {id} took 0.109 seconds (10.9 usec/query), which is essentially the same performance as when the IDs were all the same. Presumably this is from the execution plan cache that @jexp mentioned.

**Comment by fickludd** [comment]
Hi there @rationalism,

This is very interesting results you find, and I must say I have never seen such big changes in query execution time. Could you share the source for your benchmarks?

I tried to reproduce this with the following [jmh benchmark](http://openjdk.java.net/projects/code-tools/jmh/)

```
// Omitted package and imports

@State( Scope.Thread )
public class WarmupBenchmark
{
    private Driver driver = GraphDatabase.driver( URI.create("bolt://localhost:7687"), AuthTokens.basic( "neo4j", "123" ) );
    private Session session;
    private Transaction tx;
    private long id;

    @Setup( Level.Iteration )
    public void setup()
    {
        session = driver.session();

        try ( Transaction writeTx = session.beginTransaction() )
        {
            StatementResult result = writeTx.run( "CREATE (n:dog {val:3}) RETURN id( n ) as id" );
            id = result.single().get( 0 ).asLong();
            writeTx.success();
        }

        tx = session.beginTransaction();
    }

    @TearDown( Level.Iteration )
    public void teardown()
    {
        tx.close();

        try ( Transaction writeTx = session.beginTransaction() )
        {
            writeTx.run( "MATCH (n) DELETE n" ).consume();
            writeTx.success();
        }

        session.close();
    }

    @Benchmark
    @BenchmarkMode( Mode.SampleTime )
    @OutputTimeUnit( TimeUnit.MICROSECONDS )
    public ResultSummary query() throws InterruptedException
    {
        return tx.run( format( "MATCH (n) WHERE ID(n) = %d RETURN n.val", id ) ).consume();
    }

    public static void main( String[] args ) throws RunnerException
    {
        Options opt =
                new OptionsBuilder()
                        .include( ".*" + WarmupBenchmark.class.getSimpleName() + ".*" )
                        .warmupIterations( 5 )
                        .measurementIterations( 10 )
                        .forks( 1 )
                        .build();

        new Runner( opt ).run();
    }
}
```

executed against a fresh Neo4j enterprise 3.3.2 which was just started. 

In this setup I get...

```
Benchmark                              Mode     Cnt     Score   Error  Units
WarmupBenchmark.query                sample  100160    99.834 ± 0.904  us/op
WarmupBenchmark.query:query·p0.00    sample            80.512          us/op
WarmupBenchmark.query:query·p0.50    sample            94.464          us/op
WarmupBenchmark.query:query·p0.90    sample           116.608          us/op
WarmupBenchmark.query:query·p0.95    sample           128.768          us/op
WarmupBenchmark.query:query·p0.99    sample           166.400          us/op
WarmupBenchmark.query:query·p0.999   sample           220.160          us/op
WarmupBenchmark.query:query·p0.9999  sample          6053.756          us/op
WarmupBenchmark.query:query·p1.00    sample          9945.088          us/op
```

...average latencies on 100 us/query, which is very different from your result of 30100 us/query. If we look at the warmup iterations, we that the first queries execute slower at about 760 us/query, but it quickly settles of the fast execution.

```
# Warmup Iteration   1: 759.276 ±(99.9%) 158.054 us/op
# Warmup Iteration   2: 337.632 ±(99.9%) 16.928 us/op
# Warmup Iteration   3: 227.152 ±(99.9%) 10.787 us/op
# Warmup Iteration   4: 199.641 ±(99.9%) 7.040 us/op
# Warmup Iteration   5: 142.061 ±(99.9%) 7.454 us/op
```

In general Neo4j needs warmup to allow the JIT compiler time to compile hot methods, and to load data into memory from disc. In this case we're only looking at JIT warmup though, as the store is only one node.

Following all of the above: 
 * **Do you still think there is there is a need from warmup documentation?** 
 * **Where in the documentation would you expect to find information about warmup?**

Thank you for sharing your concerns!

**Comment by fickludd** [comment]
As I cannot currently reproduce the described problems this issue will be closed. If there's more information on how to achieve these warmup-problems though, post it here and we can re-open and continue finding the cause and possibly adding documentation. Thanks again for reporting!
