### ISSUE TITLE
Feature request: REST API for creating/dropping existence constraints

### ISSUE THREAD

**Issue by rationalism** [neo4j/neo4j#6907]
According to http://neo4j.com/docs/milestone/rest-api-schema-constraints.html, it looks like there are REST API commands for creating and dropping uniqueness constraints, but not for creating and dropping property existence constraints. Could these commands be added to the API? Thanks.

**Comment by jexp** [comment]
You can do both with Cypher, which is also the supported way going forward.

**Comment by rationalism** [comment]
Thanks. If the plan going forward is to do everything in Cypher, is there a Cypher command for listing all existing constraints, as opposed to just create/drop for a single particular constraint? I didn't see any listed at http://neo4j.com/docs/stable/query-constraints.html, so right now I'm doing that via the REST API (http://neo4j.com/docs/milestone/rest-api-schema-constraints.html#rest-api-get-all-constraints).

**Comment by jexp** [comment]
yes, that's the plan for 3.0

see here: http://neo4j.com/docs/3.0.0-SNAPSHOT/procedures.html#_built_in_procedures

**Comment by rationalism** [comment]
Great! Closing this out, then.
