### ISSUE TITLE
relationshipDelete() and relationshipCreate() have inconsistent node locking orders

### ISSUE THREAD

**Issue by cybersam** [neo4j/neo4j#6914]
In [org.neo4j.kernel.impl.apiLockingStatementOperations](https://github.com/neo4j/neo4j/blob/3.1/community/kernel/src/main/java/org/neo4j/kernel/impl/api/LockingStatementOperations.java), the relationshipDelete() and relationshipCreate() methods have inconsistent node locking orders. This inconsistency has been there since at least 2.2, and is still there in the 3.1 branch.
- `relationshipDelete()` always locks the **start node first**.
- `relationshipCreate()` always locks the **node with the lower ID first** (“to lower the risk of deadlocks”).

Because of this inconsistency, the neo4j kernel can be responsible for unnecessary deadlocks, and it is generally impossible for client code implementors to come up a node locking order that reliably avoids deadlocks.

Those 2 methods must use a consistent locking order. This probably means that `relationshipDelete()` must be changed to use the same ordering policy as `relationshipCreate()`.

Also, once this is fixed, the locking order (of a relationship AND its 2 nodes) must be documented in the manual, say in the [Default locking behavior](http://neo4j.com/docs/stable/transactions-locking.html) section so that client code implementors can understand better how they must order their locking to avoid deadlocks.

**Comment by chrisvest** [comment]
Yeah, that looks like an oversight.

**Comment by amadfida** [comment]
@chrisvest is there a plan to address either in 2.3 or 3.0? This is effecting us pretty badly ... would appreciate some feedback.

**Comment by chrisvest** [comment]
Yes, this was fixed in 2.2.10, 2.3.4, 3.0: #6930
