### ISSUE TITLE
Cypher returns 0 rows for "nested" aggregation when nodes in label aren't present

### ISSUE THREAD

**Issue by freeeve** [neo4j/neo4j#6921]
I feel like this should not return 0 rows. 

Assume greater than 0 `:Dummy1` records, and 0 `:Dummy2` records.

```
match (dummy:Dummy1)
with count(1) as dummy
match (dummy2:Dummy2)
return count(1) as dummy2, dummy
```

**Comment by Mats-SX** [comment]
Hello @freeeve and thanks for reporting this.

This behaviour is expected, but the reason behind it might not be obvious. The difference to keep in mind is between _grouping_ and _aggregation_. Whenever an aggregating expression (such as `count()`) is placed together with another value in a projection, it is implicitly turned into a grouping aggregation, and grouping aggregations will only produce rows if there are incoming rows.

On an empty graph, this will return one row:

```
MATCH ()
RETURN count(*)
```

while this will return zero rows:

```
MATCH ()
RETURN count(*), 1
```

This has the consequence of not allowing values past an (non-grouping) aggregating query horizon, which makes 'double aggregation', such as in your query, difficult. There is a way around this, however; using `OPTIONAL MATCH`:

```
MATCH (dummy:Dummy1)
WITH count(1) AS dummy
OTPIONAL MATCH (dummy2:Dummy2)
RETURN count(1) AS dummy2, dummy
```
