### ISSUE TITLE
Constraint failing to constrain on MERGE causing   More than one item in org.neo4j.helpers.collection.IteratorUtil

### ISSUE THREAD

**Issue by codewithcheese** [neo4j/neo4j#6926]
Hi

I am regularly using MERGE to apply data onto an existing graph. Today I am encountering a new error on a previous working MERGE. I believe this to be a bug.

I am receiving error "More than one item in org.neo4j.helpers.collection.IteratorUtil$12@44c217b1, first:55110598, second:55114825" when trying to merge.

There is a constraint ON :Impression(hash)    ONLINE (for uniqueness constraint) 

Trying a MERGE as simple as "MERGE (a:Impression {hash:'e612b20ac8dc47b1b08e1fbc67b5a3a2'}) ON CREATE SET a:Test ON MATCH SET a:Test" Causes the issue.

Running "MATCH (a:Impression {hash:'e612b20ac8dc47b1b08e1fbc67b5a3a2'}) RETURN a" now returns 22 nodes. 

Running 2.3.2 ENTERPRISE

Ubuntu 14.04

Using Cypher, testing in Neo4j browser

My database is 500GB, I could provide ssh access to a copy of it, if need be.

Thank for your help.

**Comment by jexp** [comment]
Thanks a lot for the report.
Can you give any specifics on how you imported the data? And if you created the constraints before or after or if your dropped them in between. Or if there was any abnormal thing in the mean time? Crash / out of disk space etc?

Are you using embedded Java API or Cypher (remote or embedded) ?

**Comment by jexp** [comment]
It would be cool if you could compress your database and send it to us privateley via a dropbox/gdrive or similar link: michael@neo4j.com

Thanks a lot.

**Comment by codewithcheese** [comment]
I will send you more details along with a copy of the compressed database tomorrow. 

Can you recommend a way to delete duplicate nodes on a non embedded database for nodes not matching the constraints in the meantime. Since this is a production server I would like to get it operational for updates again. Hopefully if i delete the duplicate nodes I can temporarily avoid the error.

Thanks

**Comment by bHacklv** [comment]
@codewithcheese you could match by id(node) and delete duplicated data.

**Comment by codewithcheese** [comment]
Thanks, I wrote a custom script. Just thought their might be some clever cypher voodoo to remove all duplicated nodes for each label index key in one query, that I could not conceive :)

**Comment by bHacklv** [comment]
@codewithcheese 
You can use `skip 1`, i.e.:
`
MATCH (n:YourLabelHere {propKey:'propVal'}) 
WITH n
SKIP 1 
DELETE a
`
should do the trick ;)

**Comment by codewithcheese** [comment]
@jexp emailed you a link to the database and some description of what happened leading up to the bug

@bHacklv thanks thats a smart approach, i came up with something more complex.

`MATCH (a:%s {hash: {hash}})
WITH a
ORDER BY id(a) ASC
WITH collect(a) as nodes
UNWIND tail(nodes) as dupes
OPTIONAL MATCH (dupes)-[r]-(x)
DELETE r, dupes`

Problem is I still need to iterate through every node matching the label to get the constraint key value. One label has 32 million nodes. SKIP LIMIT my way through this becomes very slow after a million or so.

**Comment by jexp** [comment]
You can probably use DETACH DELETE instead.

MATCH (n:YourLabelHere {propKey:'propVal'})
WITH n SKIP 1
DETACH DELETE n

**Comment by jexp** [comment]
I usually use:

```
MATCH (n:YourLabelHere)
WITH n.propKey as key, collect(n) as nodes WHERE size(nodes) > 1
FOREACH (n IN tail(nodes) | DETACH DELETE n)
```

or if that's not feasible on a large db you can try

```
MATCH (n:YourLabelHere)
WITH n.propKey as key, collect(id(n)) as nodes WHERE size(nodes) > 1
UNWIND tail(nodes) as id MATCH (n) where id(n) = id
DETACH DELETE n
```

**Comment by MishaDemianenko** [comment]
Hey @codewithcheese logs are full of OOM errors during index flushing and it means that indexes are not consistent with store. Please rebuild indexes to prevent merge error in future and increase memory limit to prevent OOM on lucene index flush, hope this helps
