### ISSUE TITLE
server don't start on Win7 with Roaming profile.

### ISSUE THREAD

**Issue by sergzin** [neo4j/neo4j#6941]
- Neo4j version: 2.3.3
- Operating system: Windows 7
- Expected behavior: After installation on Windows7 Neo4j server starts when pressing button "start"
- Actual behavior: Neo4j server doesn't start.

Alert popup contains the following message.

Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@4dfab464' was successfully initialized, but failed to start. Please see attached cause exception.

`neo4j.properties` located in the following folder. 
\fileserver\HQHome$\username\Documents\Neo4j\default.graphdb\neo4j.properties

**Comment by ehx-v1** [comment]
if you never ever made it run you could try deleting the graph database folder and having it set up by Neo4j again by keeping it chosen, or make sure it's on a location Neo4j can write to at all, perhaps you have your Win7 set up in a way that gives JavaVM (e.g. Eclipse) admin permissions but Neo4j only gets ordinary user permissions (even though that would be really strange)

**Comment by sergzin** [comment]
if I select manually before starting the database location once again "database tuning"  option changes to `C:\neo4jdb\neo4j.properties` from `\fileserver\HQHome$\username\Documents\Neo4j\default.graphdb\neo4j.properties`
then database starts without errors.

**Comment by ehx-v1** [comment]
ok then I think you have errors in your local properties, or your file server cleared them, anyway you should check what's in the file, try comparing with the one in `C:\neo4jdb` if you don't know what it should look like

**Comment by craigtaverner** [comment]
If I understood this discussion above, this is no longer an issue. Please re-open if there are still problems.
