### ISSUE TITLE
OPTIONAL MATCH Query runs with wildly erratic timing

### ISSUE THREAD

**Issue by Alan-R** [neo4j/neo4j#6952]
### Environment

I'm using Neo4j 2.3.3 with py2neo 2.0.8 on Ubuntu 15.10.
### Expected Behavior

Query returns results with reasonably consistent timing
### Actual Behavior

Query returns results with highly erratic timing
### Details

I originally thought this might be a py2neo or queue flush behavior, but for reasons I'll explain below I no longer think so.

I have at least one query which either runs quickly, or runs quickly for the almost the whole query, then there's a pause of several seconds followed by the last three rows of the result. An example output from my assimcli query command is included below:

```
::ffff:10.10.10.1 20-cf-30-3c-f3-cf undefined DNS: lauralee OUI:ASUSTek COMPUTER INC.
::ffff:10.10.10.100 00-c0-48-21-92-9f undefined DNS: baytech OUI:BAY TECHNICAL ASSOCIATES
::ffff:10.10.10.12 00-1e-c0-89-40-7f undefined DNS: ntp OUI:Microchip Technology Inc.
::ffff:10.10.10.18 6c-62-6d-84-98-4b undefined DNS: silas OUI:Micro-Star INT'L CO., LTD
::ffff:10.10.10.20 6c-62-6d-84-98-4b undefined DNS: dnshost OUI:Micro-Star INT'L CO., LTD
::ffff:10.10.10.248 c4-04-15-a8-5d-80 undefined DNS: netgearswitchoffice OUI:NETGEAR INC.,
::ffff:10.10.10.250 c4-3d-c7-96-9c-e4 c4-3d-c7-96-9c-e4 DNS: netgearswitch2 OUI:NETGEAR
::ffff:10.10.10.254 cc-b2-55-d5-6d-4b undefined DNS: gw OUI:D-Link International
::ffff:10.10.10.32 00-11-d9-0b-1f-1e undefined DNS: tivo2 OUI:TiVo
::ffff:10.10.10.5 40-16-7e-37-21-1b servidor DNS: servidor OUI:ASUSTek COMPUTER INC.
::ffff:10.10.10.58 00-11-d9-5e-c9-e2 undefined DNS: dhcp58 OUI:TiVo
::ffff:10.10.10.62 80-fa-5b-13-e0-7e undefined DNS: undefined OUI:CLEVO CO.
::ffff:10.10.10.79 00-11-d9-5e-c9-e1 undefined DNS: undefined OUI:TiVo
::ffff:10.10.10.94 d8-cb-8a-01-14-c1 undefined DNS: undefined OUI:Micro-Star INTL CO., LTD.
::ffff:10.10.10.98 00-0e-f3-31-24-c4 undefined DNS: undefined OUI:Smarthome
========LONG PAUSE HERE========
::ffff:162.125.32.129 undefined undefined DNS: undefined OUI:undefined
::ffff:172.17.42.1 96-58-44-1b-93-97 servidor DNS: undefined OUI:undefined
::ffff:185.30.166.37 undefined undefined DNS: verne.freenode.net OUI:undefined

real    0m4.830s
user    0m0.224s
sys     0m0.020s
```

It doesn't seem to matter how many rows are going to ultimately be delivered, the pause is just before the last three lines. Sometimes it takes as long as 10 seconds(!).

Here's this particular query:
               START ip=node:IPaddrNode('_:_')
               OPTIONAL MATCH ip<-[:ipowner]-nic
               OPTIONAL MATCH ip<-[:ipowner]-nic<-[:nicowner]-system
               RETURN DISTINCT ip, nic, system
               ORDER BY ip.ipaddr

I'm using the cypher.stream method. Each time I run the query, I'm doing it from a new binary invocation - against the same running database.

When it runs fast, timing looks more like this:

```
real    0m0.403s
user    0m0.204s
sys     0m0.044s
```

Note that I can run the same CLI command over and over, and still I get these wildly varying timings. The database is idle, and surely its cache is warm after doing the same query over and over again. The entire database likely fits into memory. For each line, it has to access three graph nodes. So, we're looking at something like 60 graph nodes of a at most a few thousand bytes each being accessed. I've moved all my big strings out to dedicated nodes (one string per node) - and this query doesn't access any large strings.

OK. I changed the sort order, and now the pause happens at 7 from the end. And in both cases, it occurred before the IP address ::ffff:162.125.32.129. So, I added a clause to the query that said "WHERE ip.ipaddr <> '::ffff:162.125.32.129' - and now it runs like gangbusters all the time.

This is the revised query which runs fast all the time (just doesn't do what I want):

```
START ip=node:IPaddrNode('*:*')
WHERE ip.ipaddr <> '::ffff:162.125.32.129'
OPTIONAL MATCH ip<-[:ipowner]-nic
OPTIONAL MATCH ip<-[:ipowner]-nic<-[:nicowner]-system
RETURN DISTINCT ip, nic, system
```

162.125.32.129 is an IP address which doesn't match either of the OPTIONAL MATCH phrases above. When I eliminate it from the query, then it runs consistently fast.

**Comment by jexp** [comment]
I think you can also leave off the first optional match (otherwise it will span up a larger tree).

does that IP have higher / lower relationship counts otherwise?

Can you also share a profile output of your query?

**Comment by Alan-R** [comment]
Hi Michael,

My memory is that it takes both of these MATCH clauses to get the full set of results. I asked about this on the mailing list, and this is what we came up with that worked. But I'll try it and let you know how it works out. In fact, I'm pretty sure that's how I had it originally - and it didn't find those where it only had the IP address. But better not to rely on my memory - better to test it.

There are three ways we discover IP addresses:

```
1) They are on a system we have an agent on. Then we get all three nodes.
          IP address, MAC address, and agent-equipped (Drone) node.
2) We find out about them by listening to ARP packets. Then we have two of the three nodes.
3) We discover them as an IP address we're connecting to (via netstat).
    In this case, we get the IP address only.
```

It's this third case where I have no other relationships that I eliminated by the WHERE clause.

**Comment by ehx-v1** [comment]
looks like the first OPTIONAL MATCH has no index it can use, so finding nothing takes a while, creating an appropriate index might solve it
just a thought though, I can't test it of course

**Comment by Alan-R** [comment]
There are no labels in this graph - and there are only about 30 nodes in the starting set. Should be able to read _all_ those nodes in from disk (cold) in a second or less.

The no labels part is due to some issues in Neo4j "batch" updates not being able to label newly-created nodes in the same transaction. I need to switch my code to use Cypher transactions - in my copious free time ;-).

**Comment by freeeve** [comment]
This is likely fixed in 3.0.0. Not using labels prior to 3.0 had a penalty involved with many deleted nodes. It would have to scan the entire node file in a slow manner. I recently closed my issue #1714 (just making a guess that this is why it's happening--do you delete and create nodes often?). If you want a quick test, try adding a :Node label to all your nodes, and then query them with :Node. Like: `match (n) set n:Node`

Edit: Nevermind, I see you're using a legacy-style index. I'd say it still might be the legacy index iterator causing trouble, not sure how they work though. Why not use labels?

**Comment by Alan-R** [comment]
Hi @freeeve!

The reason for not using labels is that my transaction layer uses "batch" operations, and they don't support labels properly. You can add labels, but not to nodes created in this transaction.  I have to rewrite my transaction layer. Then I can use labels. I have a layer on top of py2neo which treats Neo4j as a transactional object store. This has made my application code much clearer and cleaner.

When 2.0.0 came out and didn't work (at least for me), that was my window for rewriting things - and 2.0.1 took a long time to come out. I tried adding labels bug ran into the batch bug/limitation So I need to rewrite my transaction layer. There have been lots of changes in Neo4j, and py2neo, and it's been hard to keep up with them all, and there have been unexpected bugs and limitations ;-). It's hard to prioritize rewriting the transaction code above fixing bugs or adding new features (things that are more likely to bring in money).

But I _do_ delete things - LOTS AND LOTS of things. In particular, every time I run a test I delete everything and then run the test. I suppose I should stop the database, destroy it and recreate it. Probably 10x to 100x as many nodes deleted as nodes that exist.

One thing I don't do is remove my indexes - so they are likely full of deleted nodes too. This is what I was thinking when I said I thought I had something to look into.

3.0.0 is working for me - so it might be better with 3.0.0. I haven't tested it yet.

**Comment by Mats-SX** [comment]
@Alan-R It seems from the discussion here that your issue has been handled, mainly by new alternatives to solving your problem (labels, higher version, etc). Do you have further considerations and/or questions related to the issue at hand, or can we close this as handled?

All the best
Mats

**Comment by ehx-v1** [comment]
Also, what do you mean by "prioritizing rewriting the transaction code above fixing bugs"? That slow runtime IS a bug of yours, right in your transaction layer!

**Comment by Alan-R** [comment]
@ehx-v1: I only have write transactions, not read transactions. So, no it isn't a bug in my (write) transaction layer. The tool that's doing this is just doing a Cypher query - and has no specific notion of transactions. It's the Cypher query that has such erratic timing.

Although the bug might be exclusively associated with the fact that I'm using legacy indexes - it's very worrisome that _any_ query should have such incredibly different timings on an idle machine.

In general, I want to make sure my vendors know about misbehaviors in their code.  It's part of my responsibility as a good customer - because bugs may have one obvious manifestation, and many other less-obvious but more serious manifestations. You never know. The wild swings in timing on machines with a warm cache are definitely in that category. My guess is that it will take 6 months or so for me to be able to get the time to fix this in my code. Even after I rewrite my (write) transaction layer, I have 30 or 40 queries to rewrite and retest.

I haven't tried this again since I converted my code to 3.0.1 (10 days ago). I ran into several other bugs and changes in 3.0 that took several days of my time to work around (like no installer) - I was out sick for a week, and at a conference this week. I'll try and give this a shot with 3.0.1 to see if it still behaves this way.

**Comment by jexp** [comment]
Alan, something that just came to my mind.

Did you configure your memory (heap) and did you have a look at your messages.log (for application pause times) or enable GC logging (in neo4j-wrapper.conf) and share the gc-logs.

It looks almost if it runs into a GC just before it finishes returning the full data.

**Comment by Alan-R** [comment]
I've rewritten everything with labels, and more modern Neo4j usage. Will reopen if this recurs.
