### ISSUE TITLE
[3.0-RC1][Bolt] Wrong marker header returned for all types when value is between 2^15 and (2^16)-1

### ISSUE THREAD

**Issue by ikwattro** [neo4j/neo4j#6959]
When a node has more than 32767 properties, the map marker header `0xda` is returned instead of `0xd9`.

How to reproduce ?

This is a bit low level, I found this because I do a check between the header and the map size produced in my php driver. I did the following step to prove it from Java side : 
- in the [unpackMapHeader()](https://github.com/neo4j/neo4j-java-driver/blob/1.1/driver/src/main/java/org/neo4j/driver/internal/packstream/PackStream.java#L474) method from the `Packstream` class in the `neo4j-java-driver`, output to the console the marker header received.
- create an integration test creating and returning a node with 32768 properties.
- Check the console and it will output it has received a `MAP32` header.

```
public long unpackMapHeader() throws IOException
        {
            final byte markerByte = in.readByte();
            final byte markerHighNibble = (byte) (markerByte & 0xF0);
            final byte markerLowNibble = (byte) (markerByte & 0x0F);

            if ( markerHighNibble == TINY_MAP ) { return markerLowNibble; }
            switch(markerByte)
            {
            case MAP_8: return unpackUINT8();
            case MAP_16:
                System.out.println("MAP16");
                return unpackUINT16();
            case MAP_32:
                System.out.println("MAP32");
                return unpackUINT32();
            default: throw new Unexpected( "Expected a map, but got: " + toHexString( markerByte ));
            }
        }
```

```
@Test
    public void testShouldReturnNodeWithHighNumberOfProps() {
        session.run("MATCH (n) DETACH DELETE n");
        HashMap<String, Object> params = new HashMap<>();
        HashMap<String, Object> props = new HashMap<>();
        for (int i = 0; i < 32770; ++ i) {
            props.put("key" + i, i);
        }
        params.put("props", props);
        session.run("CREATE (n) SET n += {props} RETURN n", params);
    }
```

```
Starting Neo4j.
Started neo4j (pid 5397). By default, it is available at http://localhost:7474/
There may be a short delay until the server is ready.
See /Users/ikwattro/dev/bugs/neo4j-java-driver/target/neo4j/3.1.0-NIGHTLY/logs/neo4j.log for current status.
MAP32
Stopping Neo4j.. stopped
```

I have actually a branch with the steps in my fork of the neo4j-java-driver  : 

https://github.com/ikwattro/neo4j-java-driver/tree/map16

/cc @nigelsmall

**Comment by ikwattro** [comment]
ping @nigelsmall @jakewins @zhenlineo 

I found why :)

From the packstream docs it defines that 16 bytes maps have a size fewer than 2^16 values (max 65535), but when you pack, you use `Short.MAX_VALUE` which is 2^15 (32768) , ref here : 

https://github.com/neo4j/neo4j/blob/3.1/community/bolt/src/main/java/org/neo4j/bolt/v1/packstream/PackStream.java#L285

Ref for Short datatype : https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html

By looking at the the Packer class, it seems this affects all types.

**Comment by zhenlineo** [comment]
Closing this issue as it should no longer be an issue.

**Comment by ikwattro** [comment]
@zhenlineo This is still an issue. Check https://github.com/neo4j/neo4j/blob/3.5/community/bolt/src/main/java/org/neo4j/bolt/v1/packstream/PackStream.java#L425

You are still checking for Short.MAX_VALUE when returning a 16 bytes map marker header, which is not correct.

**Comment by zhenlineo** [comment]
Hi @ikwattro,

It is on purpose designed on the server to pack and unpack the size of Map, List, Strings, and Bytes in this way. The idea is that we create a more "tolerance" server. 

When packing a size in the range of `2^15 ~ 2^16-1`, we currently pack it as a int (using two extra bytes). If we change to pack it as a unsigned short, we will risk breaking clients that unpack the size as a signed value. 

The server also unpack the size as a unsigned value, so that the server could read both clients that pack the size as a signed or a unsigned value.

Thus also is the reason that your suggested fix on the java driver was merged. We just forgot to communicate back on this issue.

Cheers,
Zhen

**Comment by ikwattro** [comment]
I'm not sure what I understand what is exactly you are trying to tell me ? Are you gonna apply the same fix in Neo4j itself as well ?

**Comment by zhenlineo** [comment]
@ikwattro No, we think there is nothing to fix on Neo4j Bolt server regarding the packing of Map size. 
The server is on purpose to use `short.MAX_VALUE` when packing to support drivers that can unpack Map size as a unsigned value, as well as the drivers that can unpack Map size as signed value.

**Comment by ikwattro** [comment]
Ok, I think we are maybe not clear on the real effect of the issue.

As a driver author following the specification provided by Neo a while back and the following scenario : 

I have to unpack a Map with a size of 32769 kv pairs : 
The Neo4j server will return a marker header with `0xda` (2^15) which means that internally I can create a max-sized Map that has a max size of 2^15.

However, because 32769 is higher than 2^15, while iterating the elements returned by the server and add them to the map, I will reach an unsupported operation once the number of elements added is higher than the max size ( because the marker header returned by the server was wrong ).

IMO, you are breaking clients (those following the specs), from the beginning, even if this use case is extremely rare.

**Comment by technige** [comment]
Hey @ikwattro. Sounds like it might be easier to talk through the issue over a higher-bandwidth channel. I'll ping you a message off-GitHub and we can arrange a video call to work this through.

**Comment by ikwattro** [comment]
So, after a cool chat with the drivers team, it seems that the issue is resolved. The header informs of the minimal bytes range supporting the value.
