### ISSUE TITLE
Long datatype property values displayed incorrectly in browser

### ISSUE THREAD

**Issue by eliorar** [neo4j/neo4j#6961]
I discovered that when saving long numbers in property e.g. 708663653625634816, the value displayed in browser is incorrect, in this case, the browser displays the property as 7086636536256348**00**.
The problem exists only on browser (and its exports), while using the API the data retrieved correctly.

**Neo4j Version:** 2.3.2 Enterprise
**Operating System:** Ubuntu 12.04.5 LTS
**API:** Browser, Firefox 45.0.2 / Chrome  49.0.2623.112
### Steps to reproduce
1. Insert new node with property, pid: 708663653625634816, `create (n:Person {pid:708663653625634816})`
2. Match the node with query on browser, `match (n:Person {pid:708663653625634816}) return n`
3. Review the property value - displayed 708663653625634800 instead of 708663653625634816
   ![capture](https://cloud.githubusercontent.com/assets/18514119/14587378/b3eb5eb0-04ba-11e6-856b-ed8b4aa54172.PNG)
### Expected behavior

The displayed property value should be the same as the value in DB.
### Actual behavior

The displayed property value differs than the value in DB (somewhat rounded).

**Comment by spacecowboy** [comment]
ping @oskarhane

**Comment by oskarhane** [comment]
Thanks for the report @eliorar.  
This is a known limitation in the Neo4j Browser / UI because of Javascripts limited number support (2^53).  
This will be (is) fixed in the upcoming 3.0 release.
