### ISSUE TITLE
[feature requrest] Ability to import relationship CSV refering to second label

### ISSUE THREAD

**Issue by cosimosimeoneTR** [neo4j/neo4j#6967]
As from your example in
http://alpha.neohq.net/docs/server-manual/import-tool-examples.html#import-tool-id-handling
i would like to be able to create a roles7.csv like this

```
:START_ID(Actor),role,:END_ID(Movie)
1,"Neo",1
2,"Morpheus",1
3,"Trinity",1
```

and a roles7Seq.csvlike

```
:START_ID(Actor),role,:END_ID(Sequel)
1,"Neo",2
1,"Neo",3
2,"Morpheus",2
2,"Morpheus",3
3,"Trinity",2
3,"Trinity",3
```

without getting the

```
There were bad entries which were skipped and logged into /mnt/databaseDisk/CosTEST/bad.log
```

error.

This is a feature request, so please don't mark it as bug and don't provide a workaround.

**Comment by spacecowboy** [comment]
Please don't open duplicate issues. We are happy to assist in the original report: https://github.com/neo4j/neo4j/issues/6910
