### ISSUE TITLE
[3.0-RC1] Document changes of Neo4j status codes in Changelog

### ISSUE THREAD

**Issue by ikwattro** [neo4j/neo4j#7009]
Hi,

Minor stuff but it broke one of my tests.

Between M05 and RC1, the 

`Neo.ClientError.Statement.InvalidSyntax` status code

has been replaced by `Neo.ClientError.Statement.SyntaxError`

Please add it to the changelog for helping other devs.

Thanks !

**Comment by spacecowboy** [comment]
Sorry, this must have fallen through the cracks. I've updated the RC1 notes to mention this now.

See the [manual](http://neo4j.com/docs/developer-manual/current/#_status_codes) for a complete list of the current status codes.
