### ISSUE TITLE
Create Relations performance

### ISSUE THREAD

**Issue by BoasE** [neo4j/neo4j#7024]
Hi

I'm quite new to neo4j and currently evaluating wether it would fit with our requirements. I

As the first step I try to push data from our own graph system to neo4j using the c# client. 
First I pushed
       477 companies
240.000 stations of companies 

This part was very fast (all together about 30 seconds)
Each station is related by a company Id  to a company

now I want to relate them with this command

``` csharp
      await client.Cypher
                    .Match(string.Format("({0}:{0})", sourceName), string.Format("({0}:{0})", targetName))
                    .Where(join)
                    .Create(string.Format("{0}-[:{2}]->{1}", sourceName, targetName, relationName))
                    .MaxExecutionTime(span)
                    .ExecuteWithoutResultsAsync();
```

this step too k 10 minutes. I expected it much better. I can see thjat the cpu was below 80% and the ram didn't use the 16GB I have defined in config.

Around the whole process I put a transaction with "RequiresNew"

the next step would be to import about 10mio. connections linked to the stations of the companies. but I fear the link process would take days :-(

Would it be better to process the data batches ? e.g. for each company ? 

Are there any recommandations what I can do better ? (Configuration, Using CSV?,...)?
I post also a best practice question looking at this topic here: http://stackoverflow.com/questions/36815503/best-practices-when-inserting-edges-and-vertices
Many thanks in advance!

**Comment by jexp** [comment]
Did you use a label for :Company and :Station ? and create a constraint on
:Company(id) and :Station(id) ? ie. the properties you used to match?

CREATE CONSTRAINT ON (c:Company) ASSERT c.id IS UNIQUE;
CREATE CONSTRAINT ON (s:Station) ASSERT s.id IS UNIQUE;

MATCH (c:Company {id:{companyId}),(s:Station {id:{stationId})
CREATE (c)<-[:BELONGS_TO]-(s);

**Comment by BoasE** [comment]
I didn't have that constraint on it. now I created it via the c# api, but no change. is there a way to check if the  constraints / indeces exists via the ui or a query?

**Comment by jexp** [comment]
:schema

In 3.0 you can

call db.labels;

Von meinem iPhone gesendet

**Comment by BoasE** [comment]
hmm i got 2.3.3 i'll check 3.0 later on

**Comment by BoasE** [comment]
I now checked it indirectly. I when I try to add a node with an existing id i got a unique constraint exception so I assume the uniqe constraint is there.

But it took 8 minutes (instead of 10...) Btw i 'm currently only using the community edition if this can be a difference.

Also would there be any expected performance improvements with 3.0 ?
Here the commands that I've send

Would it make a difference when I create the index bevor adding the data ? 

``` cipher
CREATE (n:GraphCompany {nodes})
CREATE CONSTRAINT ON (GraphCompany:GraphCompany) ASSERT GraphCompany.Id IS UNIQUE

CREATE (n:GraphCompanyStop {nodes})
CREATE INDEX ON :GraphCompanyStop(CompanyId)
CREATE CONSTRAINT ON (GraphCompanyStop:GraphCompanyStop) ASSERT GraphCompanyStop.Id IS UNIQUE

MATCH (GraphCompanyStop:GraphCompanyStop), (GraphCompany:GraphCompany)
WHERE (GraphCompanyStop.CompanyId = GraphCompany.Id)
CREATE GraphCompanyStop-[:StopOfCompany]->GraphCompany
```

**Comment by sherfert** [comment]
Upgrading to newer versions usually improves the speed. This is quite old, do you still need assisstance @BoasE ?

**Comment by sherfert** [comment]
Closing in lack of a response. Feel free to reopen.
