### ISSUE TITLE
Feature request: Zoom in/out in the neo4j browser

### ISSUE THREAD

**Issue by rationalism** [neo4j/neo4j#7028]
The use case is pretty obvious: this would let the user have a more comprehensive view of large graphs. You can do this with various hacks or third-party applications, but it would be much more convenient to have it built-in to neo4j itself.

Relevant StackOverflow question: http://stackoverflow.com/questions/29475911/how-do-i-zoom-in-out-in-the-web-client-are-there-other-clients

Previous related issue: #1672

**Comment by smoofra** [comment]
+1 like star

**Comment by chrisvest** [comment]
If you full-screen a result frame, you have zoom in/out buttons in the lower right corner.

**Comment by rationalism** [comment]
Cool, thanks. Could those be added to the non-full-screen windows, and bound to the third mouse button (mouse wheel), as in Google Maps?

**Comment by craigtaverner** [comment]
The mouse wheel is already bound to scroll the inner-window in the browser.

**Comment by oskarhane** [comment]
We have decided to add zoom buttons in full screen view only, due to the already small size the the viz is in the stream of frames.
Feel free to open a feature request in the [neo4j-browser](https://github.com/neo4j/neo4j-browser) repo for the mouse wheel binding.
