### ISSUE TITLE
Upgrade to Lucene 6

### ISSUE THREAD

**Issue by Hronom** [neo4j/neo4j#7029]
Hi,
You done amazing job in upgrading Neo4j to use Lucene 5.

So how about next step: [8 April 2016 - Apache Lucene 6.0.0 Available](https://lucene.apache.org/#8-april-2016-apache-lucene-600-available)

It will be super amazing!

**Comment by chrisvest** [comment]
Our plan is to upgrade to the latest Lucene version in 4.0, whenever that comes around.

**Comment by Hronom** [comment]
It's hard to survive till version of Neo4j 4.0.

So guys how it's going? We here in 2018 year got problem. 

You know, we have here new release of `Apache Lucene 7.3.0`: https://lucene.apache.org/#4-april-2018-apache-lucene-730-and-apache-solr-730-available

Also even guys from `Elasticsearch` [upgraded to 7.2.1](https://search.maven.org/#artifactdetails%7Corg.elasticsearch%7Celasticsearch%7C6.2.4%7Cjar)

So I decide to send you a message from future, hope you get noted, the github time-machine pretty unstable...

**Comment by tinwelint** [comment]
Apparently the future arrived and Neo4j 4.0 will have Lucene version 8.2.0 in it.

Eventuality has it that this issue will be closed one way or another and whereas this hasn't been fixed to your exact suggested Lucene version it sort of has been fixed. Cheers!
