### ISSUE TITLE
Rails 5.0.0.beta4 - to_prepare is deprecated

### ISSUE THREAD

**Issue by Joshfindit** [neo4j/neo4j#7032]
I'm sure this is minor, and may be addressed elsewhere, but it's over my head and I'm submitting just in case.

`DEPRECATION WARNING: to_prepare is deprecated and will be removed from Rails 5.1 (use ActiveSupport::Reloader.to_prepare instead) (called from <class:Railtie> at /home/josh/.rvm/gems/ruby-2.2.4/bundler/gems/neo4j-f7f7f6f94642/lib/neo4j/railtie.rb:11)`

When running `rails s` with:

```
gem 'rails', '>= 5.0.0.beta4', '< 5.1'
gem 'neo4j', github: 'neo4jrb/neo4j', branch: 'rails5'
```

The app does serve pages as expected.

**Comment by chrisvest** [comment]
This is the repository for the Neo4j database. The active model wrapper is here: https://github.com/neo4jrb/neo4j so please report your issue there.
