### ISSUE TITLE
Browser: various reference links in 3.0.0 don't work

### ISSUE THREAD

**Issue by freeeve** [neo4j/neo4j#7034]
I was exploring the :help command in the new browser. It has several useful pages, but following any links that go to pages like `neo4j.com/docs/3.0.0/...` don't seem to work (404). I'm not sure if this is a browser issue or a docs issue, but I figured I would let you all know via this issue.

**Comment by spacecowboy** [comment]
thanks @freeeve we'll sort this out for the next patch release.

**Comment by spacecowboy** [comment]
please have a look @oskarhane

**Comment by Masadow** [comment]
From the README of 3.0.0

`For full instructions, see http://neo4j.com/docs/3.0.0/deployment.html`

Leads to a 404

**Comment by oskarhane** [comment]
Thanks, these are now fixed with commit: https://github.com/neo4j/neo4j-browser/commit/f8af94337d9596e788f2ea2585b1d7866729b70f and will be in the next release.
