### ISSUE TITLE
Big Integer Display Problem

### ISSUE THREAD

**Issue by kassemshehady** [neo4j/neo4j#7043]
I am facing this problem 
MATCH (n:Tweet{id:727189530466459649}) RETURN n LIMIT 25
it returns
 {  "favorites": 0,
              "created_at": "Mon May 02 17:34:29 +0000 2016",
              "id": 727189530466459600  
}

Different Ids any help?

**Comment by freeeve** [comment]
javascript (or something on the client) is casting it to a float and losing precision. where are you seeing this?

**Comment by ikwattro** [comment]
This is a limitation of javascript itself (limited to 2^53 for numbers).

**Comment by freeeve** [comment]
a good workaround is to cast it to string in cypher if it's causing you issues (or to just store it like that initially). it should work fine for non-javascript clients, though.

```
MATCH (n:Tweet{id:727189530466459649})
RETURN toString(n.id)
```

**Comment by ikwattro** [comment]
Yup, like Twitter API is doing for their API : 

```
For those of you still accessing the numeric IDs via Javascript or any other non-statically-typed language, we strongly suggest using the “id_str” property instead, which treats the user ID as a string. (This property has existed on user objects for some time - it is not a new addition). Where available, “id_str” continues to be the best way to access any ID in the system, even for platforms which support 64-bit integers.
```

**Comment by spacecowboy** [comment]
Seems to be answered. So closing issue. The workaround given by @freeeve is probably the way to go here to avoid JavaScript's limitations.
