### ISSUE TITLE
Browser: text selections in cypher editor not visible in dark theme

### ISSUE THREAD

**Issue by DannyMeister** [neo4j/neo4j#7044]
I thought text selections were broken in 3.0.0 for several days, but turns out it is just the styling in the dark theme.
- Neo4j version: 3.0.0
- Operating system: Windows 7
- browser: Chrome 50.0.2661.94m

*\* Steps to reproduce
1. In the Browser->Browser Options->Theme choose Dark.
2. Type or open any existing cypher query.
3. Click+drag or shift+arrow to make a text selection.

*\* Expected
The selected text will be visually highlighted.
*\* Actual behavior
The cursor visually disappears.

**Comment by oskarhane** [comment]
Fixed with https://github.com/neo4j/neo4j-browser/commit/eb8fbf271392f379c958576cbb9ae4c269fe9fc7
