### ISSUE TITLE
explicitly cast items  in multi-type collections are considered as Any

### ISSUE THREAD

**Issue by tomzeppenfeldt** [neo4j/neo4j#7055]
**Neo4j Version:** 2.3.1  
**Operating System:** Ubuntu 14.10  
### Steps to reproduce

Creating a collection of collections, e.g.

`Collect([TOINT(idn),STR(name),TOINT(status),TOINT(days_norm),TOINT(days_spent)]) as flowsteps`

and later on adding up corresponding items

`REDUCE (x=0, i IN flowsteps | x + TOINT(STRING(i[3]))) as normP`

throws an error

`Cypher error: Type mismatch: expected Float, Integer or String but was Any (line 33, column 57 (offset: 1271)) " REDUCE (x=0, i IN flowsteps | x + TOINT(TOSTRING(i[3]))) as normP`
### Expected behavior

If I cast something WITH TOINT(), then this should work:

`REDUCE (x=0, i IN flowsteps | x + i[3]) as normP`
### Actual behavior

Only works with a workaround  by TOINT(STR()), which is no longer works in 3.0, because STR() is no longer available.

**Comment by spacecowboy** [comment]
The error is the same as in #7053 , so this looks like a duplicate.

**Comment by tomzeppenfeldt** [comment]
The error message is the same, but the cause is slightly different. I added the error only to prove that the collection items are considered as  Any.
