### ISSUE TITLE
Regex clause matching everything

### ISSUE THREAD

**Issue by mmcauliffe** [neo4j/neo4j#7059]
Hello,

I've been finding that using a regex in where clause for matching is initially matching every node.

So for the a database with nodes with a `label` property, something like:

```
MATCH (n) WHERE n.label =~ '(?i)cat' RETURN n
```

Returns every node.  It's been consistently working once a database has been up and running, but usually the first couple of runs of such a query will return all nodes.  I'm not sure what changes eventually to make the same query work.  

It looks like regex clauses for other properties besides `label` are working just fine, so maybe that's the issue?

**Neo4j Version:** 3.0.0
**Operating System:** Windows 10, but also found on Travis CI (Ubuntu 12.04)  
### Steps to reproduce
1. Start with a fresh database
2. Populate with some nodes with various `label` properties
3. Run regex matching query on node's `label` property
### Expected behavior

Only nodes that match the regex should be returned
### Actual behavior

All nodes are returned for the first few queries, but eventually (sometimes) the expected behavior happens

**Comment by chrisvest** [comment]
Try prepending `PROFILE` to your queries, to see if the query plan changes when the queries go from non-working to working.

**Comment by mmcauliffe** [comment]
Good call, so there are couple differences between the working and non working versions of the query.

When running a similar query (which doesn't work):

```
PROFILE MATCH (n:phone_type:timed) where n.label =~ 'a.' return n
```

Doing `EXPLAIN` on it to begin with, gives multiple warnings: "The provided property key is not in the database (the missing property name is is: label)", "The provided label is not in the database (the missing label name is is: phone_type)", and "The provided label is not in the database (the missing label name is is: timed)".  In the `PROFILE`, it does a `NodeIndexScan` (for `n`), following by a `Filter` (`n`, `n:timed`) followed by `ProduceResults` and `Result`.

Two similar queries do work as expected.  If a different property is specified as in:

```
PROFILE MATCH (n:phone_type:timed) where n.place_of_articulation =~ 'a.*' return n
```

There is no warnings given in `EXPLAIN` and the plan is: `NodeByLabelScan` (`n`, `:timed`), followed by a `Filter` (`n.place_of_articulation ~= {AUTOSTRING0} AND n:phone_type`) followed by `ProduceResults` and `Result`.

And a third that also does expected behavior:

```
PROFILE MATCH (n:phone_type) where n.label =~ 'a.' return n
```

No warnings on this one, and the plan is `NodeByLabelScan` (`n`, `:phone_type`), followed by `Filter` (`n`, `n.label ~= {AUTOSTRING0}`) followed by `ProduceResults` and `Result`.

So it seems to be an interaction of having two labels specified while queries a property named `label`?

**Comment by pontusmelke** [comment]
Hi, 
Are you sure no nodes have been added between that you run the queries? I am asking since for your first example

```
MATCH (n:phone_type:timed) where n.label =~ 'a.' return n
```

you say you get warnings about there not existing any nodes with labels `phone_type` and `timed` nor any nodes with the property `label`. Are you sure that this query really gives you any nodes back?

The second query

```
 MATCH (n:phone_type:timed) where n.place_of_articulation =~ 'a.*' return n
```

uses the same labels but here you get no warnings? This seems to indicate that there are now nodes with those labels in the database?

Could you send a few examples how you do the step 2  `Populate with some nodes with various label properties`? Also could you post what indexes you have?

Regards,
Pontus

**Comment by mmcauliffe** [comment]
Ok, so it seems that creating nodes like:

```
Create (n:timed:phone_type {label:'aa', height: 'low'}), (w:timed:phone_type {label:'ae', height: 'low'}), (t:timed:phone_type {label:'iy', height:'high'}) 
```

And then running 

```
MATCH (n:phone_type:timed) where n.label =~ 'a.' return n
```

Returns the correct results (i.e., everything but the node labelled `iy`)

The issue looks to be with `LOAD CSV` and `create index`.  So if you create the nodes manually as above, creating an index before or after the load results in the correct behavior.  With `LOAD CSV`, if the index is created first before the loading, then the regex match doesn't behave properly.  Dropping the index and recreating fixes the behavior.  I should have mentioned that's how the nodes were being created earlier.

```
CREATE INDEX ON :phone_type(label)
```

And then

```
LOAD CSV WITH HEADERS FROM "file:///path/to/phone_type.txt" as csvLine MERGE (n:phone_type:timed {id: csvLine.id, label:csvLine.label})
```

Will result in regex matches not working, but reversing the order does work.

Test CSV: [phone_type.txt](https://github.com/neo4j/neo4j/files/269105/phone_type.txt)

**Comment by jexp** [comment]
Please note that regular expression predicates don't use an index.

You probably didn't wait until the index was online?

You can check with `schema` if the index is still populating.

If you import via neo4j-shell consider using `schema await` to make sure indexes are online.

**Comment by mmcauliffe** [comment]
So from a fresh database, doing: `create index on :phone_type(label)`, it completes and `:schema` lists it as online.  Then I do the load from CSV above, and run the regex match query, and it returns all nodes.  If I do `drop index on :phone_type(label)` and the do the regex match query, it returns the correct nodes.  It may not use the index, but the presence of the index/when the index is created seems to matter.

**Comment by jexp** [comment]
Can you share the PROFILE query plan for both cases? 

Von meinem iPhone gesendet

**Comment by mmcauliffe** [comment]
For the query that doesn't work after loading from csv:
![plan 3](https://cloud.githubusercontent.com/assets/2791247/15343516/61ad95a0-1c6b-11e6-9085-20a78793f334.png)

Once the index is dropped:
![plan 2](https://cloud.githubusercontent.com/assets/2791247/15343517/63ecf50e-1c6b-11e6-9c0c-e3bdbb23716f.png)

**Comment by pontusmelke** [comment]
Ok that looks clearly wrong. I will investigate.

Thanks for taking your time to report this!
