### ISSUE TITLE
Can't login from browser view in HA mode

### ISSUE THREAD

**Issue by Masadow** [neo4j/neo4j#7066]
Hi,

Under new neo4j 3.0.0. I'm running a HA cluster. I can properly login from master:7474 but I can't login from slave:7474.

If I check in the browser console, the following response is returned from the API :

**Neo4j Version:** 3.0.0  
**Operating System:** Debian 8 Jessie  
### Steps to reproduce
1. Setup a password on the master server
2. Run the HA cluster
3. Go to one slave member's browser interface (port 7474)
4. Try to :server connect
### Expected behavior

I should login in
### Actual behavior

Request takes ages to resolve and finally throw the following error :

`[{code: "Neo.ClientError.Security.Unauthorized", message: "No authentication header supplied."}]`

**Comment by spacecowboy** [comment]
Looks like a browser bug @oskarhane ?

**Comment by Masadow** [comment]
Also, when I run `:play sysinfo` from the master, it says that HA & Cluster are not enabled. However, from the log files point of view on both master and slaves, everything is running smoothly

**Comment by oskarhane** [comment]
Hi @Masadow and thanks for the report. We'll look into this as soon as we can.  
That is a strange error message.  
1. Does it work if you disable auth (just for troubleshooting this issue of course, I'm not suggesting you should disable it in a prod env)?
2. Are you using our debian package to install?
3. Could you try to enable (or disable) Bolt in the Neo4j Browser configuration and see if there's any change in behavior?

Also, the display of the HA parts of `:play sysinfo` is broken in 3.0.0. That bug is fixed in the next release.

**Comment by oharlem** [comment]
@Masadow @oskarhane 
I'm observing the same issue right now, however I believe this may be related to another one I'm experiencing: https://groups.google.com/forum/#!topic/neo4j/2WuGgPRiiyo

Context:
- Debian 8.4
- AWS / EC2
- If accessing this instance via 7474, it asks me for a login/pas; I'm entering correct credentials and it freezes. Behind the scenes I see a failing AJAX request.
- Database block of the left panel looks like:
  "Version:
  Name: -
  Size: -
  ", i.e. no values, just dashes and space for a version.
- My sysinfo screen of this slave - attached.

Thank you!

![screen shot 2016-05-17 at 12 00 26 pm](https://cloud.githubusercontent.com/assets/6718777/15329524/060fb00a-1c27-11e6-8fd6-4e9a8eaa730e.png)

**Comment by oharlem** [comment]
@Masadow @oskarhane 
I have some progress: https://groups.google.com/forum/#!topic/neo4j/2WuGgPRiiyo
In my case, back-end issue were the reason behind inability to log in.
To be fair, for some reason, it took long time for one node's browser to start responding, so I had to reload page a number of time with a Developer's Panel open (to kill browser cache).

**Comment by oskarhane** [comment]
Thanks a lot @mpmlj, I suspected this wasn't a browser issue.  
Can you confirm that this resolves your issue @Masadow?
