### ISSUE TITLE
Cypher 3.0 Cost Planner produces unusual query plan

### ISSUE THREAD

**Issue by bunkat** [neo4j/neo4j#7082]
I'm running a simple Cypher query to return a set of nodes from a parent node.  When profiling I noticed that the COST PLANNER is creating a very unusual plan for the query that I don't think is intended behavior.
- Neo4j version: 3.0.1
- Operating system: Ubuntu 14.04
- API/Driver: Cypher using transaction endpoint
### Statements to reproduce

```
Statement 1:
CREATE (:Project {"id":"lsRy1VDVLnMxc","object":"project","name":"p1","no":0})

Statement 2:
MATCH (p:Project { id: "lsRy1VDVLnMxc" })
CREATE UNIQUE (p)-[:has]->(g:FileGroup)
CREATE UNIQUE (g)-[:has]->(n:File {"id":"lsRy1VDVM2fhP","object":"file","name":"c1","no":0})

Statement 3:
MATCH (p:Project { id: "lsRy1VDVLnMxc" })
WITH p

MATCH (p)-[:has]->(:FileGroup)-[:has]->(n:File)
WITH n ORDER BY n.no
RETURN COLLECT({id: n.id, object: n.object, name: n.name, no: n.no})
```
### Expected behavior

Statement 3 produces the unusual query plan.  If I attempt to just match the project, it produces the correct plan using the NodeUniqueIndexSeek on Project.id.

```
PROFILE
MATCH (p:Project { id: "lsRy1VDVLnMxc" })
RETURN p
```

![image](https://cloud.githubusercontent.com/assets/665885/15099953/caef4c42-1519-11e6-90bc-c3914b4b052d.png)
### Actual behavior

However, if I profile the query in Statement 3 it produces the following profile:

![image](https://cloud.githubusercontent.com/assets/665885/15099963/ffbf1b1e-1519-11e6-8fd0-70e8694f2b85.png)

It starts by doing a NodeByLabelScan on FileGroup since file group has no indexes and then proceeds to to an Expand and Filter operation to find the Project with the matching id which takes 12 db hits and 3 rows.  Whereas using the index finds the node in 1 row and 2 db hits.

I would never expect a query planner to:
- Perform out of order execution of the query across WITH statements
- Prefer a starting node that has no index above one with an index

Updating the query to enforce the index produces the expected results:

```
MATCH (p:Project { id: "lsRy1VDVLnMxc" })
USING INDEX p:Project(id)
WITH p

MATCH (p)-[:has]->(:FileGroup)-[:has]->(n:File)
WITH n ORDER BY n.no
RETURN COLLECT({id: n.id, object: n.object, name: n.name, no: n.no})
```

![image](https://cloud.githubusercontent.com/assets/665885/15100056/514e2dd8-151c-11e6-909a-f79c2ca28477.png)

**Comment by craigtaverner** [comment]
Can I assume that this database has only the data you put in above? If so, then the behavior is probably as expected because a NodeLabelScan is cheaper than a NodeIndexSeek for there being only one File and one Project.

If your real world data will have many more Files than Projects, I suggest you simulate this by adding a lot of dummy Files, with something like:

```
UNWIND range(0,200) as fileid CREATE (:File {id:"x"+toString(fileid)})
```

Then the cost planner should find the Project index more efficient, and plan that. Let me know if that clarifies things, or if there is still an issue.

**Comment by bunkat** [comment]
Ah, this must just be an odd edge case then.  As long as the database has more nodes it does in fact use the index.  It was just odd because when it did use the NodeLabelScan it was about 20% slower than using the index during my testing so I wasn't sure why it would ever do that.  But it doesn't look like this will ever effect the execution of the query in production.
