### ISSUE TITLE
[BUG?PROPOSAL?RFC?] Referencing a unexisting index returns a (wrong) error message

### ISSUE THREAD

**Issue by cosimosimeoneTR** [neo4j/neo4j#7098]
Running query

```
match (t:Target)-[]->()
using index t:Target(id)
where t.id = "213000001634753"
return *
```

returns correct results.

Running

```
match (t:target)-[]->()
using index t:Target(id)
where t.id = "213000001634753"
return *
```

or

```
match (t:Target)-[]->()
using index t:target(id)
where t.id = "213000001634753"
return *
```

returns

```
Cannot use index hint in this context. Index hints are only supported for the following predicates in WHERE (either directly or as part of a top-level AND): equality comparison, inequality (range) comparison, STARTS WITH, IN condition or checking property existence. The comparison cannot be performed between two property values. Note that the label and property comparison must be specified on a non-optional node (line 2, column 1 (offset: 24))
```

which _in my opinion_:
1. Message is way too verbose and displacing since index hint has being used in WHERE condition
2. I might need to reference a non existing index, for some reason
3. Query should not crash for a wrong hint

**Comment by cosimosimeoneTR** [comment]
This query

```
match (t:Target)-[]->()
using index t:Target(id)
where 1=1
return *
limit 100
```

returns same error message.

**Comment by spacecowboy** [comment]
Agreed, that error message is misleading.

To clarify for other people with weak eyes, there is a difference between the case of the leading `T` in `[tT]arget`, and the problem is related to a mismatch of the case in the match and the index statements.

**Comment by cosimosimeoneTR** [comment]
Thanks for answer!

Don't forget, this is not (just) a bug highlight, but (also) a feature request :-)
In _all_ (r)dbms systems, wrong hints are ignored, or -at worst- rise a warning, they **never** let query fail.

**Comment by systay** [comment]
Hi @cosimosimeoneTR!

My background is from MS SQL Server, and there, hints could absolutely fail queries.

We see the value in both ways of looking at it, so you can change your settings on a per-database level by using `cypher.hints_error` and setting it to false. Then you'll only get a warning for the missing index, but the query still runs. Hopes that helps!

**Comment by cosimosimeoneTR** [comment]
Hi @systay 
My background is Oracle database, and there, hints will never fail queries.

Your choice is (at least) pour.
