### ISSUE TITLE
[BUG] 404 on :help query plan link

### ISSUE THREAD

**Issue by cosimosimeoneTR** [neo4j/neo4j#7099]
in :help query plan, last "tab", there is a link 

```
Reference:  Execution Plans manual page
```

which references 
http://neo4j.com/docs/3.0.0/execution-plans.html
which is 404

**Comment by ikwattro** [comment]
This was already reported here https://github.com/neo4j/neo4j/issues/7034

And fixed in https://github.com/neo4j/neo4j-browser/commit/f8af94337d9596e788f2ea2585b1d7866729b70f

**Comment by spacecowboy** [comment]
Yes, this should have been fixed very recently, but thanks for reporting it!
