### ISSUE TITLE
Comment at the beginning of a query causes an error

### ISSUE THREAD

**Issue by jstepien** [neo4j/neo4j#711]
I was having this great Neo4j workshop with @sarmbruster today when I encountered a following problem in the community edition 1.9.RC1.

```
start x = node(*)
// this works
return x
```

```
start x = node(*)
return x
// this works as well
```

yet surprisingly

```
// this breaks
start x = node(*)
return x
```

executed in the web interface returns:

> **Unknown error**
> 
> An unknown error occurred, was unable to retrieve a result for you.

**Comment by chrisvest** [comment]
This is not a problem in the new Neo4j Browser.
