### ISSUE TITLE
[3.0][Procedure] Can't use Long safely as procedure argument type

### ISSUE THREAD

**Issue by ikwattro** [neo4j/neo4j#7115]
**Neo4j Version:** 3.0.1
**Operating System:** OSX
**API:** Browser/PHP

In the below example, using Long as procedure argument's type is not safe, because : 
1. It is treated as long when you pass a number as procedure call argument.
2. It is treated as integer when you pass a the same number as query parameter and use the parameter as procedure call parameter

Which means that we can't use a type of `Integer` or `Long` as procedure argument type, because the type coerced differs from Cypher inline vs Query parameter.
### Steps to reproduce

``` java
package proc;

import org.neo4j.procedure.Context;
import org.neo4j.procedure.Name;
import org.neo4j.procedure.Procedure;

import java.util.stream.Stream;

public class LongInt {

    @Procedure
    public Stream<Record> test(@Name("object") Object object) {
        return Stream.of(new Record(object.getClass()));
    }

    public class Record {

        public final Object value;

        public Record(Object value) {
            this.value = value;
        }

    }
}
```

Procedure parameter passed inline in the Cypher query

``` java
@Test
public void testIt1() {
  Driver driver = GraphDatabase.driver( "bolt://localhost" );
  Session session = driver.session();
  StatementResult rs = session.run("CALL proc.test(500)");
  rs.consume();
  session.close();
  driver.close();

  // Returns class java.lang.Long
}
```

Procedure parameter passed from query parameters map // Procedure parse it as Integer

``` java
@Test
public void testIt2() {
  Driver driver = GraphDatabase.driver( "bolt://localhost" );
  Session session = driver.session();
  Map<String, Object> params = new HashMap<>();
  params.put("v", 500);
  StatementResult rs = session.run("CALL proc.test({v})", params);
  rs.consume();
  session.close();
  driver.close();

  // Returns class java.lang.Integer
}
```

**Comment by jexp** [comment]
That's really weird, b/c bolt should have no concept of `ints`. @nigelsmall ?

How does it behave with http ?

**Comment by ikwattro** [comment]
Well, in PHP, we don't have concept of longs ;-)

**Comment by ikwattro** [comment]
The behavior with http is exactly the same. 

By the way, in Bolt the marker for the parameter value will be INT8.

**Comment by zhenlineo** [comment]
Closing this issue as it is too old. If anyone would like to reopen this, pls give more explanations.
