### ISSUE TITLE
Deadlock error messages

### ISSUE THREAD

**Issue by rationalism** [neo4j/neo4j#7116]
In Neo4j 3.0.0 (Ubuntu, with the Java driver), I sometimes get exceptions, with error messages like this:

"An unexpected failure occurred, see details in the database logs, reference number 7aac3a63-6d27-4485-9fb0-afd5f6b670e0."

Looking at the logs/debug.log file, these exceptions and reference numbers seem to be caused by deadlocks in Neo4j. However, the error message that's sent to the client doesn't mention deadlocks, and the exception type is org.neo4j.driver.v1.exceptions.TransientException, which is very vague. Could the Neo4j driver include an exception type and error message that's specific to deadlocks, so the client can distinguish these from other errors? Thanks.

**Comment by zhenlineo** [comment]
https://github.com/neo4j/neo4j/pull/7463
The deadlock error will be sent to server in next 3.0 release. It will be classified as transient error, which basically means if you retry the error might just go away.

**Comment by rationalism** [comment]
Excellent, thank you.
