### ISSUE TITLE
Support for DECODE function

### ISSUE THREAD

**Issue by ADTC** [neo4j/neo4j#7139]
_Moved to opencypher/openCypher#62._

Can Neo4j Cypher support `DECODE` function in a future version? It could simply be an alias to the simple `CASE`:

```
CASE test
WHEN value THEN result
[WHEN ...]
[ELSE default]
END
```

translates as `DECODE` to:

```
DECODE ( test
, value , result
[, value , result
, ...]
[, default] )
```

The function is less verbose than simple `CASE`.

**Comment by systay** [comment]
Hi @ADTC!

Language proposals like this are best aimed at https://github.com/opencypher/openCypher

Thanks!
