### ISSUE TITLE
To start neo4j via docker with an existing data dir didn't work out

### ISSUE THREAD

**Issue by dalanlan** [neo4j/neo4j#7194]
I was trying to start neo4j with an existing data dir via docker. 
### How to reproduce

1.I've got a dir with data imported say `/Users/simei.he/Documents/graphDB/gracenote/databases/graceLight.db`

2.Start neo4j with 

```
docker run --publish=7474:7474 --publish=7687:7687 --volume=/Users/simei.he/Documents/graphDB/gracenote:/data --volume=/Users/simei.he/Documents/graphDB/gracenote/conf:/conf --link mazerunner:mazerunner --link hdfs:hdfs neo4j:3.0 
```

3.For `/Users/simei.he/Documents/graphDB/gracenote/conf`, I have 

```
$ tree
.
├── neo4j-wrapper.conf
└── neo4j.conf
```

And inside `vineo4j.conf`, we have 

```
dbms.active_database=graceLight.db
dbms.directories.data=/Users/simei.he/Documents/graphDB/gracenote
```

4.The volumes are both mounted successfully and when I tried to test it out with `neo4j-shell`, I've got nothing. Meaning it's an empty graph db as of now.

```
$ docker exec -it 6a7c895f17c2 bin/neo4j-shell
Welcome to the Neo4j Shell! Enter 'help' for a list of commands
NOTE: Remote Neo4j graph database service 'shell' at port 1337

neo4j-sh (?)$ match (n) return count(n);
+----------+
| count(n) |
+----------+
| 0        |
+----------+
1 row
213 ms
```

5.Also when I tried to connect it with local port, while `192.168.99.100` is the default machine IP 192.168.99.100 on my MAC.

```
$ curl http://192.168.99.100:7474
curl: (7) Failed to connect to 192.168.99.100 port 7474: Connection refused
```

I was wondering if I missed anything. Thanks in advance.

/cc @benbc @rishabhjain08 Wondering if you could help me out once again:)

**Comment by spacecowboy** [comment]
@dalanlan 

You are giving an incorrect path to the database.

You are mounting this volume

```
--volume=/Users/simei.he/Documents/graphDB/gracenote:/data
```

But then you specify the following in your config file

```
dbms.directories.data=/Users/simei.he/Documents/graphDB/gracenote
```

Which makes no sense inside of docker. You mounted it as `/data`. So that's what you should specify in your config:

```
dbms.directories.data=/data
```

**Comment by dalanlan** [comment]
@spacecowboy Indeed, that helps a lot:) 
Yet I still got following error when I tried to access the server even after I fixed previous issue. Any idea?

```
$ curl http://192.168.99.100:7474
curl: (7) Failed to connect to 192.168.99.100 port 7474: Connection refused
```

**Comment by spacecowboy** [comment]
what does the log from `docker run ...` print?

**Comment by dalanlan** [comment]
@spacecowboy It seems all right to me. 

```
$ docker run --publish=7474:7474 --publish=7687:7687 --volume=/Users/simei.he/Documents/graphDB/gracenote:/data --volume=/Users/simei.he/Documents/graphDB/gracenote/conf:/conf neo4j:3.0 
Starting Neo4j.
2016-05-24 11:10:29.140+0000 INFO  No SSL certificate found, generating a self-signed certificate..
2016-05-24 11:10:30.147+0000 INFO  Starting...
2016-05-24 11:10:31.409+0000 INFO  Bolt enabled on localhost:7687.
2016-05-24 11:10:40.659+0000 INFO  Started.
2016-05-24 11:10:42.961+0000 INFO  Remote interface available at http://localhost:7474/
```

I was wondering if there is anything to do with the os. However I was able to ping that ip, fyi

```
$ ping 192.168.99.100
PING 192.168.99.100 (192.168.99.100): 56 data bytes
64 bytes from 192.168.99.100: icmp_seq=0 ttl=64 time=0.376 ms
64 bytes from 192.168.99.100: icmp_seq=1 ttl=64 time=0.491 ms
64 bytes from 192.168.99.100: icmp_seq=2 ttl=64 time=0.345 ms
64 bytes from 192.168.99.100: icmp_seq=3 ttl=64 time=0.457 ms
```

and also

```
$ nc -zv 192.168.99.100 7474
nc: connectx to 192.168.99.100 port 7474 (tcp) failed: Connection refused
```

**Comment by spacecowboy** [comment]
The log shows the problem

```
Remote interface available at http://localhost:7474/
```

It is listening on localhost only, which means that you can't access it from outside of the container. Since you are using a configuration file directly via a configuration volume, you need to set  `dbms.connector.http.address=0.0.0.0:7474`. 

See this bit in the manual for details:
http://neo4j.com/docs/operations-manual/current/#security-server

**Comment by dalanlan** [comment]
@spacecowboy 
Ah no, I've tried to publish the port to the host, that should work, you see?
```
 -p, --publish=[]                Publish a container's port(s) to the host
```
and docker tries to publish the port for me.
```
3c196fa9a5ac        neo4j:3.0                              "/docker-entrypoint.s"   39 hours ago        Up 39 hours         0.0.0.0:7474->7474/tcp, 7473/tcp, 0.0.0.0:7687->7687/tcp                                                                cranky_feynman
```
I can't see why that doesn't help.

**Comment by dalanlan** [comment]
To whoever might be interested,
here is the [guide](http://neo4j.com/developer/docker/) to start neo4j with docker
