### ISSUE TITLE
Feature request: Docker image wait until Neo4j is actually available before continuing

### ISSUE THREAD

**Issue by Joshfindit** [neo4j/neo4j#7203]
I'm not filing this as a bug, since Neo4j works as expected.
But it could be better.

With docker-compose, we can specify `depends_on:`, telling Docker to start the Neo4j container before starting the app container.
Neo4j's status message seems to tell Docker that it's ready before it's able to serve requests.

Waiting until `INFO  Remote interface available at http://0.0.0.0:7474/` would work.

**Comment by spacecowboy** [comment]
This is not a Neo4j thing. The same is true for all containers which have some kind of start-up time.

A workaround for this limitation in docker-compose is to add a wait-script to the entrypoint script of your dependant container. For example, something like

``` sh
#!/bin/bash -eu

IFS=',' read -ra NEO4J <<< "$NEO4J"

ELAPSED=0

while true; do
  sleep 5
  ELAPSED=$((ELAPSED + 5))

  UP=0
  for host in "${NEO4J[@]}"; do
    if curl -s -I http://"${host}":7474 | grep -q "200 OK"; then
      UP=$((UP + 1))
    fi
  done

  if [ "$UP" -eq "${#NEO4J[@]}" ]; then
    echo "All hosts are available after $ELAPSED seconds"
    exit 0
  else
    echo "Only $UP hosts up so far [${ELAPSED}s]"
    continue
  fi
done
```

Which, assuming neo4j is available as the name `neo4j` in your docker-compose file (using link or docker networks), you would call as: `neo4jupyet.sh neo4j`

Which will only exit once neo4j is actually ready

**Comment by ehx-v1** [comment]
Is there a way to make this available as Docker patch or plugin? Because I feel like that would make a better solution to Docker users than having to homebrew this script on each situation.
I have little knowledge of Docker myself though, so no idea if my suggestion is nonsense or not ;-)

**Comment by DeltaWhy** [comment]
This solution does not work when NEO4J_AUTH is set. The server appears ready, but then stops and restarts. The problem appears to be here: https://github.com/neo4j/docker-neo4j-publish/blob/22114d5022d6bd414fc7d34046b7a5f9cfdc930c/3.0.6/community/docker-entrypoint.sh#L41

It looks like it starts the server, changes the password using an HTTP request, stops it again, and then starts it again further down. A workaround would be to use basic auth and wait on `/db/data/` so it only returns 200 once the server is really ready. A solution would perhaps be to have the server listen on localhost only when it comes up the first time to set the password.

Edit: This workaround does not work - if the container is restarted then the password will already be set but it will still do the up/down/up routine.

**Comment by spacecowboy** [comment]
@DeltaWhy thisway of setting the password is the only way to do it on the 2.x versions. 3.x supports a cleaner approach using a `Procedure`, and it's on our backlist to update the container to us this new method. Once done, there will be no more restarts to set the password.

**Comment by benbc** [comment]
The change to 3.1 avoid the restart cycle is already available in 3.1 milestone releases (implemented in https://github.com/neo4j/docker-neo4j/commit/d2522f43d800fc9371ff5234142a82b1cdb044fc).

**Comment by benbc** [comment]
@DeltaWhy I'm surprised by what you are seeing. The (pre-3.1) start/stop cycle for setting credentials runs with Neo4j bound to `127.0.0.1` rather than `0.0.0.0` so you should not see the server as "up" during that cycle.

Can you give more details of what you are doing?

**Comment by DeltaWhy** [comment]
@benbc It looks like `127.0.0.1` is the default, but after it's set to `0.0.0.0` on the first run of the container, it stays that way. So it's only when an existing neo4j container is restarted that this issue appears. My use case is running integration tests on a web app using docker-compose, which starts and stops the containers for every test suite run but only recreates them when necessary.

I built my own image using the official `Dockerfile` and `docker-entrypoint.sh` but adding a line to explicitly set the address to `127.0.0.1` before bringing up the server for the credential change, and it does work as expected with that change. I'd send a pull request but I'm not clear on where it should go.

**Comment by benbc** [comment]
@DeltaWhy Ah! You're absolutely right -- we had not considered the case of stopping and restarting containers. Thank you.

This is a _bug_ and we'd love to have a PR for a fix. The change needs to go [here](https://github.com/neo4j/docker-neo4j/blob/master/src/2.3/docker-entrypoint.sh#L30) (`setting "org.neo4j.server.webserver.address" "127.0.0.1" neo4j-server.properties`) and [here](https://github.com/neo4j/docker-neo4j/blob/master/src/3.0/docker-entrypoint.sh#L41) (`setting "dbms.connector.http.address" "127.0.0.1:7474"`).

**Comment by DeltaWhy** [comment]
@benbc Thanks, sent.

**Comment by alepee** [comment]
You can use the HEALTHCHECK in your Dockerfile or docker-compose.yml

**Dockerfile**: [HEALTHCHECK](https://docs.docker.com/engine/reference/builder/#healthcheck)
**docker-compose**: [healthcheck](https://docs.docker.com/compose/compose-file/compose-file-v2/#healthcheck) combined with [depends_on and condition](https://docs.docker.com/compose/compose-file/compose-file-v2/#depends_on)

You may want to use `curl`. It is not installed by default in the neo4j image

**Comment by craigtaverner** [comment]
The PR attached above seems to be the one to fix the issue, so I'm closing this. Re-open it if that was not the case.

**Comment by panosprotopapas** [comment]
> You may want to use `curl`. It is not installed by default in the neo4j image

Since the neo4j image doesn't include  `curl` by default, I would suggest the use of `wget` (which is included) if curl is not otherwise needed. Especially for CI/CD situations where customizing a public image might require some more work.

**Comment by RyanSnodgrass** [comment]
For those googling this- here's what worked for me. 

The healthcheck definition goes in the neo4j service where it will query against itself to determine readiness. Use wget as commented above since the base neo4j image does not come with curl. Then your dependent service (web app, API, etc) depends on the neo4j service to be healthy. 

In my experience I found the http adapter to be the consistent last place finisher at startup (at least in neo4j v3.5.x)  so it was my choice for the health check.

Good luck!

```yaml
# docker-compose.yml
version: "3.9"
networks:
  neo4j_user:
services:
  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474 # http://0.0.0.0:7474/
      - 7687:7687 # bolt
    expose:
      - 7474
      - 7687
    volumes:
      - neo4j_data:/data
    networks:
      - neo4j_user
    healthcheck:
        test: wget http://localhost:7474 || exit 1
        interval: 1s
        timeout: 10s
        retries: 20
        start_period: 3s
  app:
    build: .
    depends_on:
      neo4j:
        condition: service_healthy
    networks:
      - neo4j_user

volumes:
  neo4j_data:
```

**Comment by alisomay** [comment]
@RyanSnodgrass Thank you <3

**Comment by mateuszpawlik** [comment]
@RyanSnodgrass, thanks for your healthcheck. It works but for me it seems to cause endless creation of files like `index.html.` in `/var/lib/neo4j`.
Files content:
```json
{"bolt_routing":"neo4j://localhost:7687","transaction":"http://localhost:7474/db/{databaseName}/tx","bolt_direct":"bolt://localhost:7687","neo4j_version":"5.21.2","neo4j_edition":"community"}
```

How about using `test: wget --spider http://localhost:7474 || exit 1` to prevent wget to download the resource?
