### ISSUE TITLE
Feature Request - Cypher Query Syntax Proposal: USE

### ISSUE THREAD

**Issue by versae** [neo4j/neo4j#721]
So far, the only way to have different graph databases in the same Neo4j instance is using indexes.

The future version 2.0 introduces the notion of Labels (tentative name), and it makes easier to handle set of nodes and automatic (re)indexing, which is really useful to manage isolated graphs.

In my use case, I have running Neo4j instances and each of them has several graphs identified by indexes. But the query syntax is kind of ugly since I have to use the regular index syntax. Labels will be helpful, but still don't solve the problem.

What I propose is to have something like this:

```
USE Graph001
MATCH (thing:Red)
WHERE thing.uid = "TK-421" 
RETURN labels(thing);
```

So once you set USE Label, all nodes are by default queried using the label Label. What it should be the same as next query:

```
MATCH (thing:Red:Graph001)
WHERE thing.uid = "TK-421" 
RETURN labels(thing);
```

Obviously, for simple queries like the one above, could be avoided, but the more complicated the query, the more helpful the USE syntax would be.

Finally, for sake of consistency, `labels(thing)` must return `Graph001` as well. Also, if finally `AND` and `OR` syntax is implemented (like `USE Red OR Blue`), what can complicate things, returning `Graph001` can be helpful.

**Comment by mnd999** [comment]
Closing this very old feature request since `USE` has been implemented to select database / alias in multi-database environment. This kind of separation can be achieved with multiple databases.
