### ISSUE TITLE
The demo in your web page is not correct

### ISSUE THREAD

**Issue by luochen1990** [neo4j/neo4j#7214]
http://neo4j.com/developer/

the "social" demo:

![image](https://cloud.githubusercontent.com/assets/2309868/15526145/33310dfe-2262-11e6-91ce-a481523c1674.png)

maybe you should swap "sally" and "bob"

**Comment by spacecowboy** [comment]
True! :)

**Comment by ehx-v1** [comment]
Not true. But it's misleading: The picture implies that the search root is Anna, while actually it's Joe. Perhaps you should higlight the search root in any way, and point out the red highlighted node is the search result. Also, same goes for Sally as for Bob. And you should point out the relationships are actually bidirectional in this case, despite being modelled as unidirectional.

**Comment by mariascharin** [comment]
@ehx-v1 Thanks for your input! I can see how it isn't entirely clear what's supposed to be illustrated. We will take your comments into account when we refresh this content.

I'll close this issue. If you have more input, please visit our public slack (https://neo4j-users.slack.com) or enter a new issue. 

Kind regards,
Maria
