### ISSUE TITLE
Playing guides from URL fails despite CORS being enabled

### ISSUE THREAD

**Issue by dhimmel** [neo4j/neo4j#7227]
I am trying to play guides from URLs in the Neo4j 3.0.1 Community browser.

The specific browser command I am using to troubleshoot is:

```
:play https://gist.githubusercontent.com/dhimmel/83829c940d1b118af775c8e9ac6746a1/raw/81c93e06b168f70da8511b9109a170ee636ed23d/clofarabine-MS.html
```

Prior to setting `browser.remote_content_hostname_whitelist=*` in `conf/neo4j.conf`, I was getting the following error as expected:

```
Requested host is not whitelisted in browser.remote_content_hostname_whitelist.
```

However, now that I have whitelisted all remote content hosts, I get the following error:

```
No 'Access-Control-Allow-Origin' header is present on the requested resource and can therefore not be played.
```

However, [the URL](https://gist.githubusercontent.com/dhimmel/83829c940d1b118af775c8e9ac6746a1/raw/81c93e06b168f70da8511b9109a170ee636ed23d/clofarabine-MS.html) I'm playing the guide from appears to include `Access-Control-Allow-Origin:*` in its response header. Hence, I think we may have a bug on our hands. 

CCing @jexp who first [mentioned guides](http://stackoverflow.com/a/37377745/4651668) to me.

**Comment by jexp** [comment]
@dhimmel better to move it to https://github.com/neo4j/neo4j-browser/issues

The CORS stuff is really tricky, I haven't found a clear way to tell which hosting works and which not.
