### ISSUE TITLE
load csv: neo4j is too fast

### ISSUE THREAD

**Issue by freeeve** [neo4j/neo4j#7237]
`Added 27302 labels, created 27302 nodes, set 68794 properties, created 138628 relationships, returned 1 row in 0 ms.`

My somewhat complex load csv script usually takes ~10 seconds or so. For some reason in 3.0.1 it's now reporting that it took 0ms to do this. (In the browser.)

**Comment by freeeve** [comment]
oh, I figured it out--it's periodic commit that seems to cause it.

**Comment by freeeve** [comment]
I was going to close this but I suppose it might be useful to have real timing reported in the statistics if you use periodic commit.

**Comment by oskarhane** [comment]
Thanks @freeeve
This is fixed and will be in the next release, by this (quite badly named pull request): https://github.com/neo4j/neo4j-browser/pull/166
