### ISSUE TITLE
Neo4j 3.0.1 load csv error

### ISSUE THREAD

**Issue by xjianster** [neo4j/neo4j#7240]
LOAD CSV WITH HEADERS FROM "file:///C:/test.csv" has error. When this command looks for the file, it always start from the position where database file stored.

**Comment by ikwattro** [comment]
@xjianster This is intended and definitely not an issue. Check the response given here : http://stackoverflow.com/questions/37444448/neo4j-load-csv-returns-couldnt-load-external-resource-neo4j-lost-in-directory/37444571#37444571

**Comment by spacecowboy** [comment]
@xjianster as @ikwattro mentions, this is an intended change in 3.0. To get the behavior you want, you need to remove/change this line from your config:

```
dbms.directories.import=import
```

**Comment by xjianster** [comment]
ok
