### ISSUE TITLE
Import does not report invalid arguments

### ISSUE THREAD

**Issue by jkaster** [neo4j/neo4j#7250]
## neo4j-import in 3.0.1 and 2.3.4 don't load relationships with "relations"

**Updated based on new info from Michael Hunger**

In my editing during testing, I changed relationships to "relations" in one round, then repeated the problem. If the import tool reported invalid arguments, I would have found that immediately. Please update the import tool to report invalid arguments.

If I have other issues to report, I'll make a new case.

**Original report***

I have found multiple issues in both versions of the importer.
1. using `%source%` or any other variable in front of a file name reference for the path results in relationships not being loaded, even if `source` is blank
2. Most of the relationship files in my import batch fail to establish a relationship at all even though the keys are set correctly, and csv headers and names follow conventions outlined in the documentation.

**Neo4j Version:** 3.0.1 and 2.3.4
**Operating System:** Windows 10 64-bit
**API:** neo4j-import
### Steps to reproduce
1. extract the files from `test.zip` into a folder
2. modify the variables in `imp.cmd` to work for your environment
3. try any of the dozens of import commands in `imp.cmd` and see the results. only 1 set of files results in setting 3 relationships, and in many scenarios those 3 relationships will not be set, either
### Expected behavior
1. `%source%` or other variable establishing the source path in a file name should not cause issues
2. all relationships should be set
### Actual behavior
1. `%source%` makes relationship linking fail
2. only 3 relationships out of hundreds are set. (See `rem` comments in `imp.cmd` for details)
   [test.zip](https://github.com/neo4j/neo4j/files/288018/test.zip)

**Comment by jexp** [comment]
You have a typo in the import file. You should always use `--relationships:` not `--relations:`

**Comment by jkaster** [comment]
You are right. I'll modify this issue to say it's not reporting bad arguments.

**Comment by craigtaverner** [comment]
`Neo4j-import` is deprecated in favour of `neo4j-admin import` which does report on invalid arguments. I will close this issue but feel free to open it if the change to neo4j-admin is insufficient.
