### ISSUE TITLE
GraphDatabaseService methods findNode and findNodes overload for multiple properties

### ISSUE THREAD

**Issue by ADTC** [neo4j/neo4j#7257]
`GraphDatabaseService` methods `findNode` and `findNodes`

Can these methods be overloaded to accept `Map<String, Object> properties` instead of the `String key, Object value` available now?

What if we do want to match nodes based on more than one property? In fact, the `Label, Map<String, Object>` version should have been made as the base method, with the `Label, String, Object` method added for convenience (no need to create a `Map` for just one property).

**Comment by ADTC** [comment]
Did a bit of digging and looks like the damage is much deeper than I thought (see `PropertyValueFilteringNodeIdIterator`). I guess we'd have to resort to plain Cypher. No other choice (if you don't want to manually iterate through the nodes and filter the list).

**Comment by chrisvest** [comment]
In Cypher it will also be clear whether the predicates are composed with AND or OR.

**Comment by ADTC** [comment]
Can't argue with that, though I was only picturing an AND scenario.

**Comment by ADTC** [comment]
In any case, I built a custom method for the AND scenario. Any bugs you notice or suggestions?

``` java
@Context
public GraphDatabaseService db;

protected List<Node> findNodesByParams(Label nodeLabel, Map<String, Object> params) {
    ResourceIterator<Node> nodes = db.findNodes(nodeLabel);
    List<Node> nodesArray = new ArrayList<Node>();
    while (nodes.hasNext()) {
        Node node = nodes.next();
        boolean nodeMatched = true;

        Iterator<Entry<String, Object>> entries = params.entrySet().iterator();
        while (entries.hasNext()) {
            Entry<String, Object> entry = entries.next();
            String key = entry.getKey();
            nodeMatched = nodeMatched && node.hasProperty(key);
            nodeMatched = nodeMatched && (
                    (node.getProperty(key)==null && entry.getValue()==null)
                    || (node.getProperty(key)!=null && node.getProperty(key).equals(entry.getValue()))
                    );
            if (!nodeMatched) break;
        }

        if (!nodeMatched) continue;
        nodesArray.add(node);
    }
    return nodesArray;
}
```

**Comment by chrisvest** [comment]
@ADTC Instead of the label scan with `db.findNodes(nodeLabel)`, you could do index lookups with one of the properties from your params. Depending on your model, you might even have some idea about which property is most selective (smallest result set). Then use `Node.getProperties( String... )` to filter for the rest of the properties you are looking for.

**Comment by ADTC** [comment]
Would `findNodes(label, property, value)` use the index as you described? I think I could use that with one of the entries to narrow down, then just check the remaining entries. Which entry is picked for that initial filter could be based on the known model, automatically guessed from existing indexes (how to check if a label/property has index?) or randomly picked (generally a bad idea).

Also, it's ok to collect nodes into a `List`, right? If the `ResourceIterator` is closed, do the nodes become invalid?

Thank you for your help :)

**Comment by chrisvest** [comment]
`findNodes(label, property, value)` would use an index if there is one. You can use `db.schema().getIndexes( label )`, then scan for one that matches a property. You'd only do this if you need to discover the model programatically, though.

It's perfectly fine to collect the nodes in a list, as long as you only access them within a transaction. The resources hiding behind the `ResourceIterator` are things like pooled objects, cursors and page-level locks.

**Comment by ADTC** [comment]
Thanks for clearing that up. But we can't programmatically determine the **size** of the index (in _any_ suitable unit), or can we?

**Comment by chrisvest** [comment]
Not from Core API, no. Maybe Cypher can.

**Comment by chrisvest** [comment]
Closing since it looks like a solution has been found. You are welcome to reopen if you disagree.

**Comment by ADTC** [comment]
@chrisvest I rewrote the method following your suggestions. Would appreciate if you can check :smiley: 

``` java
protected final List<Node> findNodesByParams(Label nodeLabel, Map<String, Object> params) {
    Entry<String, Object> indexedEntry = null;

    indexSearch:
    for (IndexDefinition index : db.schema().getIndexes(nodeLabel)) {
        for (String property : index.getPropertyKeys()) {
            for (Entry<String, Object> entry : params.entrySet()) {
                if (property!=null && entry!=null && property.equals(entry.getKey())) {
                    indexedEntry = entry;
                    break indexSearch;
                }
            }
        }
    }

    ResourceIterator<Node> nodes =
            indexedEntry!=null
            ? db.findNodes(nodeLabel, indexedEntry.getKey(), indexedEntry.getValue())
            : db.findNodes(nodeLabel);

    List<Node> nodesArray = new ArrayList<Node>();
    String[] paramsKeySetArray = params.keySet().toArray(new String[]{});

    nodeSearch:
    while (nodes.hasNext()) {
        Node node = nodes.next();
        boolean nodeMatched = true;

        Map<String, Object> properties = node.getProperties(paramsKeySetArray);

        for (String key : params.keySet()) { // not properties.keySet() as it may only be a subset

            // if this was the indexed property, just skip checks and continue to next property
            if (indexedEntry!=null && key.equals(indexedEntry.getKey())) continue;

            // if node doesn't contain a property, consider it a mismatch
            nodeMatched = nodeMatched && properties.containsKey(key);
            if (!nodeMatched) continue nodeSearch; // mismatched node, continue to next node

            // if both values are null, consider it a match
            boolean nullMatch = properties.get(key)==null && params.get(key)==null;

            // if any of the values is not null, check equality
            if (!nullMatch) {

                // ensure we don't check equality on a null value
                // fail fast as mismatch since we can infer the other value is not null
                nodeMatched = nodeMatched && properties.get(key)!=null;

                // check equality
                nodeMatched = nodeMatched && properties.get(key).equals(params.get(key));
            }

            if (!nodeMatched) continue nodeSearch; // mismatched node, continue to next node
        }

        nodesArray.add(node); // node matched, add to list
    }

    nodes.close();
    return nodesArray;
}
```

_(Note: Code has been updated following below comments.)_

**Comment by chrisvest** [comment]
You can move `params.keySet().toArray(new String[]{})` out of the while-loop, but otherwise it looks good.

**Comment by ADTC** [comment]
Ah, nice catch! Thanks!

**Comment by gianglaodai** [comment]
I just got the same problem and found it here. Why don't you use Map.containsKey(K key) to remove one for-loop in indexSearch

**Comment by patricker** [comment]
@ADTC I appreciate the code. I wish this allowed for querying composite indexes, but that looks like the limitation you mentioned with findNodes; no way to pass in multiple property names/values to even try querying a composite index.

**Comment by craigtaverner** [comment]
For reference, Neo4j 3.4 includes an expansion to the Core API to support finding nodes on multiple properties in a way that supports composite indexes. See the java docs at https://neo4j.com/docs/java-reference/current/javadocs/org/neo4j/graphdb/GraphDatabaseService.html#findNodes-org.neo4j.graphdb.Label-java.util.Map-
