### ISSUE TITLE
neo4j-import 3.0.2 does not support header files

### ISSUE THREAD

**Issue by jkaster** [neo4j/neo4j#7307]
## Import fails when using CSV header files for relationships and nodes

Imports using header files run successfully in 2.2.4, but throw an error in 3.0.2

**Neo4j Version:** 3.0.2
**Operating System:** Windows 10 64-bit
**API:** Neo4j import
### Steps to reproduce
1. Extract [importwithheaders.zip](https://github.com/neo4j/neo4j/files/296632/importwithheaders.zip) into a folder
2. Update the `neo` variable in `import.cmd` to point to either the 3.0.2 or 2.2.4 import tool (see below)
3. Run `import.cmd`
### Expected behavior

The import should complete without errors in 3.0.2 like it does in 2.2.4
### Actual behavior

You see the error:

> "Invoke-Neo4jImport : Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'ArgumentList'. Specified
> method is not supported.
> At line:1 char:57
> - ... sd1'; Exit (Invoke-Neo4jImport --into d:/data/test --db-config d:/imp ...
> -                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   - CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>   - FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-Neo4jImport

Note: You can ignore the python summarize script call

**Comment by spacecowboy** [comment]
Thank you for the report. This is a known issue on Windows. A fix is currently under review in https://github.com/neo4j/neo4j/pull/7292

**Comment by benbc** [comment]
A fix for this has been merged and will be available in 3.0.4 (currently unscheduled).

**Comment by jkaster** [comment]
Thanks!
