### ISSUE TITLE
bolt/cypher should allow for manipulation of error positions

### ISSUE THREAD

**Issue by cleishm** [neo4j/neo4j#7318]
Errors generated from Cypher indicate the position of the error relative the statement sent via BOLT, treating the first character of the statement as position `line 1, column 1 (offset 0)`.

However, when a client is sending a sequence of statements sourced from a single input file/stream, then the user considers the first character of a statement to be at a specific position relative to the input file/stream, and thus the error positions returned from bolt/cypher are nonsensical.

E.g.:

```
% neo4j-client neo4j://neo4j:neo4j@localhost <<-EOM
return 1;

invalid command;
EOM
"1"
1
Invalid input 'i': expected <init> (line 1, column 1 (offset: 0))
"invalid command"
 ^
```

To resolve this, it would be helpful for bolt to accept a 'initial position' for statements and, when it is provided, report any errors using positions relative to that initial position.

**Comment by technige** [comment]
I see little benefit in the server needing to know about the ultimate context of the original source of a statement. From the server's point of view, the offset returned is correct, passing other values around merely adds traffic.

Instead, the line and offset should probably be returned as individual, consumable fields. The application (or perhaps driver) could then add a relative offset to the line number before reporting it back to the user.

That said, I'm not sure how deep that change would need to go.

**Comment by cleishm** [comment]
Yes, that would work also - although it's a much larger change, given the position is embedded within the error message strings.

**Comment by cleishm** [comment]
In the example above, the failure metadata is:

```
{
    code: "Neo.ClientError.Statement.SyntaxError",
    message: "Invalid input 'i': expected <init> (line 1, column 1 (offset: 0))
\"invalid command\"
 ^"
}
```

So taking the suggested approach, it would be necessary to split the message into individual components, such that the client can re-construct the error string after adjusting the position. For example:

```
{
    code: "Neo.ClientError.Statement.SyntaxError",
    message: "Invalid input 'i': expected <init>"
    position: { line: 1, column: 1, offset: 0 },
    context: { line: "invalid command", offset: 0 }
}
```

That would be nice, as it gives the client more options for rendering - including ignoring the `context` and instead identifying the position using the text in the editor (e.g. in the browser) - but it is a large change and not backward compatible.

**Comment by cleishm** [comment]
@nigelsmall Another use-case just appeared, whereby I'd also want to include the source file in the error. At this point, I agree with you. Whilst adding an offset would be easier the re-working the entire error response, it's insufficient for this new need. So then I'd also need a source filename added, and that's _way_ too client centric for the server to be handling.

**Comment by cleishm** [comment]
Does closing this mean one of the proposed solutions has been implemented? Are "the line and offset ... returned as individual, consumable fields" now, as @technige suggested?
