### ISSUE TITLE
fail to adopt neo4j extension  

### ISSUE THREAD

**Issue by dalanlan** [neo4j/neo4j#7319]
Hi folks!

Thank you for your amazing work of neo4j, again:)

I am trying to get my hands dirty on [extensions](http://neo4j.com/docs/java-reference/current/#server-unmanaged-extensions) and I am not able to get it work.
### How to reproduce
1. following the steps on given [guide](https://github.com/dmontag/neo4j-unmanaged-extension-template) to get jar file.
2. copy it to `plugins` dir.
3. enable the configuration in the `neo4j.conf`
   `
   dbms.unmanaged_extension_classes=org.neo4j.examples.server.unmanaged=/examples/unmanaged
   `
4. start the server and bang! failed to start correcly. Full error log is posted [here](https://gist.github.com/dalanlan/e354928b32df0d3e78b200975d980634).

Any idea, please? Thanks so much.
### Some thoughts

I've ruled out following possible causes:
- typo
- permission of jar file
- I believe it has nothing to do with the extension code itself because I run into exactly the same problem with an official [hello world example](https://github.com/neo4j/neo4j/blob/3.0/manual/server-examples/src/main/java/org/neo4j/examples/server/unmanaged/HelloWorldResource.java).
- could be an eclipse issue? (according to someone on stackoverflow) Had no idea what he was talking about though.
### Additional Info
- neo4j: 3.0.0

**Comment by dalanlan** [comment]
I didnt touch [movies-extensions](https://github.com/neo4j-examples/movies-java-server-extension) because that's even worse.

```
$ mvn clean package
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Neo4j Movies Demo Extension 2.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ neo4j-movies ---
[INFO] Deleting /Users/simei.he/Documents/movies-java-server-extension/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ neo4j-movies ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ neo4j-movies ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /Users/simei.he/Documents/movies-java-server-extension/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ neo4j-movies ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/simei.he/Documents/movies-java-server-extension/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ neo4j-movies ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /Users/simei.he/Documents/movies-java-server-extension/target/test-classes
[WARNING] /Users/simei.he/Documents/movies-java-server-extension/src/test/java/example/extension/movies/MovieServiceIntegrationTest.java: /Users/simei.he/Documents/movies-java-server-extension/src/test/java/example/extension/movies/MovieServiceIntegrationTest.java uses or overrides a deprecated API.
[WARNING] /Users/simei.he/Documents/movies-java-server-extension/src/test/java/example/extension/movies/MovieServiceIntegrationTest.java: Recompile with -Xlint:deprecation for details.
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ neo4j-movies ---
[INFO] Surefire report directory: /Users/simei.he/Documents/movies-java-server-extension/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running example.extension.movies.MovieServiceIntegrationTest
server.baseUri() = http://localhost:7474/
15:46:06.349 [main] WARN  o.e.j.server.handler.ContextHandler - o.e.j.s.ServletContextHandler@2687f956{/,null,null} contextPath ends with /
15:46:06.351 [main] WARN  o.e.j.server.handler.ContextHandler - Empty contextPath
15:46:06.354 [main] INFO  org.eclipse.jetty.server.Server - jetty-9.0.5.v20130815
15:46:06.382 [main] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.h.MovedContextHandler@aa10649{/,null,AVAILABLE}
Jun 06, 2016 3:46:06 PM com.sun.jersey.api.core.PackagesResourceConfig init
INFO: Scanning for root resource and provider classes in the packages:
  example.extension.movies
Jun 06, 2016 3:46:06 PM com.sun.jersey.api.core.ScanningResourceConfig logClasses
INFO: Root resource classes found:
  class example.extension.movies.MovieResource
Jun 06, 2016 3:46:06 PM com.sun.jersey.api.core.ScanningResourceConfig init
INFO: No provider classes found.
Jun 06, 2016 3:46:06 PM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.9 09/02/2011 11:17 AM'
15:46:06.674 [main] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@bb9ab64{/movie,null,AVAILABLE}
Jun 06, 2016 3:46:06 PM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.9 09/02/2011 11:17 AM'
15:46:06.766 [main] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@7048535f{/db/manage,null,AVAILABLE}
Jun 06, 2016 3:46:06 PM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.9 09/02/2011 11:17 AM'
15:46:06.913 [main] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@6d2dc9d2{/db/data,null,AVAILABLE}
15:46:06.974 [main] INFO  o.e.j.w.StandardDescriptorProcessor - NO JSP Support for /browser, did not find org.apache.jasper.servlet.JspServlet
15:46:06.983 [main] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.w.WebAppContext@7aa9e414{/browser,jar:file:/Users/simei.he/.m2/repository/org/neo4j/app/neo4j-browser/2.1.4/neo4j-browser-2.1.4.jar!/browser,AVAILABLE}
Jun 06, 2016 3:46:06 PM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.9 09/02/2011 11:17 AM'
15:46:07.067 [main] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@2687f956{/,null,AVAILABLE}
15:46:07.096 [main] INFO  o.e.jetty.server.ServerConnector - Started ServerConnector@4096aa05{HTTP/1.1}{localhost:7474}
404
404
404
404
404
404
```

**Comment by jexp** [comment]
In David Montag's example the config is wrong because the package is different (he probably changed the package w/o updating the readme). So the server tries to find a resource in the wrong package.

This should work.

```
dbms.unmanaged_extension_classes=com.neo4j.example.extension=/examples/unmanaged 
```

I recommend to rather look into procedures for 3.0

**Comment by dalanlan** [comment]
As I put in the original post, I did what exactly you listed. This WONT work for my case.
```
dbms.unmanaged_extension_classes=org.neo4j.examples.server.unmanaged=/examples/unmanaged
```

**Comment by dalanlan** [comment]
@jexp Please kindly reopen this issue until it's been actually resolved.

**Comment by dalanlan** [comment]
Uhh, I am getting a little confused. Sorry for my not paying close attention.

```
dbms.unmanaged_extension_classes=org.neo4j.examples.server.unmanaged=/examples/unmanaged
```

The line I quote is located in your `conf` comment and also [here](http://neo4j.com/docs/java-reference/current/#server-unmanaged-extensions). 
If there is a problem with that, it's not only about David's repo. It's about the doc I mentioned and reference of your own work in the `conf` file.

**Comment by jexp** [comment]
- I fixed the movies example.
- send a PR to David's repository, only _he changed_ the package from what it was in the docs
- for the docs it's correct b/c the package there is `org.neo4j.examples.server.unmanaged`

**Comment by jexp** [comment]
The package always has to match the package of the actual resources. The line in the config file is just an example that matches our documentation project.
The actual code (where you see the package) is linked from the docs page

https://github.com/neo4j/neo4j/blob/3.0/manual/server-examples/src/main/java/org/neo4j/examples/server/unmanaged/HelloWorldResource.java

**Comment by dalanlan** [comment]
That makes sense. You've made my day! (I'm terribly sorry that I'm a n00b in java. )
I'm gonna take another look at the helloWorld case tomorrow. Would you mind leaving this open until then?

**Comment by dalanlan** [comment]
I can confirm that both helloWorld and movie example work as they should.  Thanks:)
Got another problem though, is it possible to enable multiple extension support at the same time? 
/cc @jexp

**Comment by jexp** [comment]
Sure, just comma separate them 

Von meinem iPhone gesendet

**Comment by dalanlan** [comment]
That's great! Thank you for your time.
Closing this issue.
