### ISSUE TITLE
dput error

### ISSUE THREAD

**Issue by piyush121** [neo4j/neo4j#7321]
Command executed on ubuntu:
$sudo apt-get install graphviz maven make openjdk-8-jdk devscripts debhelper rpm

Setting up dput (0.9.6.4ubuntu1.1) ...
**\* Error compiling '/usr/share/dput/ftp.py'...
  File "/usr/share/dput/ftp.py", line 9
    print "D: FTP-Connection to host: %s" % fqdn
SyntaxError: Missing parentheses in call to 'print'

**\* Error compiling '/usr/share/dput/helper/dputhelper.py'...
  File "/usr/share/dput/helper/dputhelper.py", line 12
    print "Error: Failed to execute '"+file+"'."
                                     ^
SyntaxError: Missing parentheses in call to 'print'

**\* Error compiling '/usr/share/dput/http.py'...
  File "/usr/share/dput/http.py", line 55
    except ValueError, e:
                     ^
SyntaxError: invalid syntax

**\* Error compiling '/usr/share/dput/https.py'...
  File "/usr/share/dput/https.py", line 3
    exec open("/usr/share/dput/http.py") in d
            ^
SyntaxError: invalid syntax

**Comment by spacecowboy** [comment]
That's not a Neo4j error. You are trying to run a python2 script with python3:

```
Setting up dput (0.9.6.4ubuntu1.1) ...
*** Error compiling '/usr/share/dput/ftp.py'...
File "/usr/share/dput/ftp.py", line 9
print "D: FTP-Connection to host: %s" % fqdn
SyntaxError: Missing parentheses in call to 'print'
```

`dput` is included in either `devscripts` or `debhelper`. You should consider reporting a bug to ubuntu about this.

But, meanwhile, just install python2 first:

```
apt-get install python
```

and that should hopefully fix it for you.
