### ISSUE TITLE
NFE is uncaught - consider changing?

### ISSUE THREAD

**Issue by ehx-v1** [neo4j/neo4j#7325]
Title almost says it all. The reason why NFE could make sense to be a caught exception is that I notice that in many cases users do catch NFE. This is especially true in the context of the Spatial extension, where NFE is mostly an indicator for invalid records having been modified manually and having to be replaced (e.g. the spatial root or the Layer root nodes), but there are also many other contexts where you cannot be sure whether a particular node can be retrieved, generally frameworks with their own infrastructure which must be prepared all the time for this infrastructure to be broken by manual invasions. If the other cases make it nonsense to make NFE caught, or it would screw up too much code (which I can both understand) I would still highly appreciate NFE occurrences to be properly documented by Javadoc `@throws`.

**Comment by craigtaverner** [comment]
It would be great if you included references to sample code that exemplifies this case.

**Comment by ehx-v1** [comment]
An example from Spatial: https://github.com/neo4j-contrib/spatial/blob/master/src/main/java/org/neo4j/gis/spatial/SpatialDatabaseService.java
The `isValid()` code that we are discussing. I can imagine similar cases wherever an application- or framework-built infrastructure can be manipulated manually.

**Comment by tinwelint** [comment]
This would be a very impactful change and the Java API will generally not be further developed or changed in big ways... in favor of the goal of everything-Cypher.
