### ISSUE TITLE
Performance degradation with float/double values

### ISSUE THREAD

**Issue by kamilos2** [neo4j/neo4j#7361]
# Environnement
- Neo4j version: 3.0.0
- Operating system: Windows 10
- API/Driver: Java API
# Steps to reproduce

1) Create a property "age" on nodes having a label  "Person"
2) Execute following code which update the "age" property of 50 nodes

```
Node node;
ArrayList<Node> toUpdate=new ArrayList<Node>();
time1=System.nanoTime();

try (Transaction tx = graphDb.beginTx()) {

    for(int i = 1;i<=50;i++){ 
        node = graphDb.findNode(labelPerson, "name", i);
        if(node != null)
           toUpdate.add(node);
    }

    for(int i = 0;i<toUpdate.size();i++){
        toUpdate.get(i).setProperty("age", Math.random());                   //SOLUTION 1  // generate a double between 0.000000 and 1.0000000
        toUpdate.get(i).setProperty("age", String.valueOf(Math.random())); //SOLUTION  2 // same number but stored as a string
    }

    tx.success();
}

time2=System.nanoTime();
```
# Problem encountered

Updating the "age" property with a "double" value takes a lot of times (200 sec with a graph containing 100 000 nodes !). The same problem arrises if we cast it as a Float.

However, if we store this double as a String, the update is instantaneous, why ?

**Comment by chrisvest** [comment]
@kamilos2 Do you have an index on the `age` property?

**Comment by kamilos2** [comment]
@chrisvest 
Yes, it was created when inserting the data using the batch inserter the following way

```
Label personLabel = DynamicLabel.label("Person");
BatchInserter inserter.createDeferredConstraint(personLabel).assertPropertyIsUnique(propertyName).create(); 
inserter.createDeferredSchemaIndex(personLabel).on(propertyAge).create();
```

I veryfied that the index exists before executing the query via : 

```
Iterator<IndexDefinition> index = graphDb.schema().getIndexes().iterator();
while (index.hasNext()) {
  System.out.println(index.next());
}
```

which correctly returns 
_IndexDefinition[label:Person, on:age]_

**Comment by MishaDemianenko** [comment]
@kamilos2 I have tried to reproduce it on 3.2 and on latest 3.1, and time for both cases are comparable. Do you still have this problem or we can close this issue?

**Comment by MishaDemianenko** [comment]
Closing as not reproducible, please feel free to reopen if it's still the issue.
