### ISSUE TITLE
Urgent feature request: Neo4j should create database if not existant

### ISSUE THREAD

**Issue by ehx-v1** [neo4j/neo4j#7373]
When you try to give Neo4j 2.3 a name of a non-existant graph database (this is both so in the browser launcher, and in the Java API), it fails to do so, expressing that the directory is either not existant or occupied. But normally, you would enter a name of a non-existant graph database to make Neo4j create the graph database properly, right? Wouldn't it then make sense to try creating the graph database, and to only throw the exception if that fails (thus, the directory exists or is on a non-writable path)?

I stumbled several times over the problem that Neo4j is simply unable to create a graph database if it does not exist, and can also imagine a large amount of users staring at the StoreLockException and wondering why on Earth, if Neo4j doesn't find a graph database, it can't simply create it.

I can understand, of course, if that would be too difficult - I suspect this is not done for a reason. But there should be a way to create a graph database having all files Neo4j expects - without creating the directory and each file manually.

**Comment by spacecowboy** [comment]
This is already how it works.

Could you describe an actual use case, with _clear steps_ to reproduce? It's possible that you might have found a bug in the initialization, or just made a configuration error.

**Comment by ehx-v1** [comment]
I'm making JUnit tests for a custom importer on a Spatial layer. In the `setUp()` method the test database is initialized, and in `tearDown()` it is cleared and shut down.

It should be also noticed that the exceptions appear on from the second test case. I had a couple of exceptions (resulting from that my graph database is wrapped in a custom GraphDatabaseService which does not implement GraphDatabaseAPI, and I tried to use it in GlobalGraphOperations; this should be fine now that I pass the actual graph database to GlobalGraphOperations, and that is an EmbeddedGraphDatabase; however as a side note you perhaps should rework GlobalGraphOperations for better handling of such wrapper databases) in my first test case.

It might be that the errors in the test case prevent `tearDown()` from being called, thus the database is not shut down after the first test and causes store locks in the subsequent tests.

So as a summary, this is the situation:
- A test environment opens a database in `setUp()` and shuts it down in `tearDown()`.
- In the first test case, an exception rises.
- All subsequent tests fail with StoreLock.

**Comment by spacecowboy** [comment]
Without actual code we can't really help you, but you are doing something wrong.

Starting/stopping a database for every test sounds like a bad idea. Use a `ClassRule` instead.

I can suggest looking at some of the unit tests in neo4j for inspiration. Some examples:
- [EmbeddedDatabaseRule.java](https://github.com/neo4j/neo4j/blob/6280974efc9b082d5f40044df362355134a8632b/community/kernel/src/test/java/org/neo4j/test/rule/EmbeddedDatabaseRule.java)
- [EnterpriseDatabaseRule.java](https://github.com/neo4j/neo4j/blob/6280974efc9b082d5f40044df362355134a8632b/enterprise/kernel/src/test/java/org/neo4j/test/rule/EnterpriseDatabaseRule.java)
- [CreateAndDeleteNodesIT.java](https://github.com/neo4j/neo4j/blob/5650e8b32e51964eff3ead47e88f9831efc8851b/community/kernel/src/test/java/org/neo4j/graphdb/CreateAndDeleteNodesIT.java)
- [ConstraintCreationIT.java](https://github.com/neo4j/neo4j/blob/6280974efc9b082d5f40044df362355134a8632b/community/lucene-index/src/test/java/org/neo4j/kernel/impl/api/constraints/ConstraintCreationIT.java)
- [RecoveryTest.java](https://github.com/neo4j/neo4j/blob/b5f2c1236417e93d33087893c44d93467366661b/community/lucene-index/src/test/java/org/neo4j/index/impl/lucene/legacy/RecoveryTest.java)

**Comment by ehx-v1** [comment]
My shame. Forgot to make a transaction when making tabula rasa in `tearDown()`. But I need one because I make tabula rasa via the classic `match ()-[r]-() delete r; match (n) delete n`.

Now that I found the cause, I think I can safely close this.

**Comment by chrisvest** [comment]
Since you are using 2.3, I think you can also use `match (n) detach delete n;` to delete everything.
