### ISSUE TITLE
[RFC] integrate with swagger

### ISSUE THREAD

**Issue by dalanlan** [neo4j/neo4j#7396]
I'm not positive whether it's a good idea, just to bring it up so that we could make a move on this.
Since swagger is used widely in restful world, do you believe if we could introduce swagger into this?
Thanks in advance.

**Comment by craigtaverner** [comment]
I'm guessing this refers to the OpenAPI specification for RESTful web services? If so, perhaps the fact that the REST API in Neo4j is deprecated in favor of BOLT means we will not consider this.

https://en.wikipedia.org/wiki/OpenAPI_Specification

I'll close this issue for now, but if people see value in it, they should feel free to re-open it with more details.
