### ISSUE TITLE
Load CSV not using available unique constraints

### ISSUE THREAD

**Issue by mmcauliffe** [neo4j/neo4j#7446]
I'm getting an issue where constraints aren't getting used in a `LOAD CSV` command.  The normal behavior is shown in regular_plan.png,  but the first time that it's run I get the slow_plan.png (where it just does a `NodeIndexScan`, rather than a `NodeUniqueIndexSeek(Locking)`).  The regular command takes 9709 ms, and the slow command takes 339136 ms.  The regular plan still doesn't use all the available unique constraints, since Speaker.name also has a unique constraint on it.

Regular performance plan:

![regular_plan](https://cloud.githubusercontent.com/assets/2791247/16359780/e7c7ed16-3b10-11e6-9178-4d7f4e0b1d61.png)

Slow performance plan:

![slow_plan](https://cloud.githubusercontent.com/assets/2791247/16359783/f105bf16-3b10-11e6-931a-8f0c1f698fa5.png)

The query for both is:

```
PROFILE USING PERIODIC COMMIT 4000
LOAD CSV WITH HEADERS FROM 'file:///path/to/csvs/s01_phone.csv' AS csvLine
MATCH (n:phone_type {id: csvLine.type_id}), (super:word:`buckeye` {id: csvLine.word}),
(d:Discourse:`buckeye` {name: csvLine.discourse}),
(s:Speaker:`buckeye` { name: csvLine.speaker})
CREATE (t:phone:`buckeye`:speech {id: csvLine.id, begin: toFloat(csvLine.begin),
                            end: toFloat(csvLine.end), label: csvLine.label }),
                            (t)-[:is_a]->(n),
                            (t)-[:contained_by]->(super),
                            (t)-[:spoken_in]->(d),
                            (t)-[:spoken_by]->(s)
WITH t, csvLine
MATCH (p:phone:`buckeye`:speech {id: csvLine.previous_id})
CREATE (p)-[:precedes]->(t)
```

[schema.txt](https://github.com/neo4j/neo4j/files/333355/schema.txt)

I've uploaded the output of `:schema`. Further information, the workflow I have does a set of two interconnected CSVs that I'm loading, one for words, one for phones.  The key point is that Neo4j can't use the Unique id from the words when loading loading the phones (since loading phones requires a look up of previously loaded words).

It isn't always the first query that is slow, but sometimes the first one is fast (i.e., regular plan) and then the second one is slow.

**Neo4j Version:** 3.0.3
**Operating System:** Windows 10
### Steps to reproduce
1. Create constraints/indexes on relevant properties (see uploaded schema).
2. Import words via `LOAD CSV`
3. Import phones via `LOAD CSV`
### Expected behavior

Cypher plan should use the unique constraint, rather a node index seek.
### Actual behavior

Cypher plan initially uses a node index seek, and then future queries use unique index seek.  Sometimes there the first query goes quick and the second one go long (so I assume use the slow query plan).

**Comment by spacecowboy** [comment]
Thanks for the very thorough report

**Comment by KrishnanSrinivasan** [comment]
Hi, were you able to the reason. I'm facing the exact problem. The first load uses NodeIndexScan which makes the query ridiculously slow, and the subsequent runs switch to a NodeUniqueIndexSeek.

**Comment by jexp** [comment]
By default it only uses on index per query but you can use index hints after your MATCH clause to make it use indexes. 
.e.g
`USING INDEX super:word(id)`
see: https://neo4j.com/docs/developer-manual/current/cypher/query-tuning/using/#query-using-index-hint

You have some inconsistent casing in your label names.

**Comment by KrishnanSrinivasan** [comment]
I'm not sure, but here is how I solved it. You could tell me if my assumption is correct. The datatype of the ID was string. I changed the logic to generate integer ID. And now, what used to take 40 secs to import takes ~5 secs. My understanding is NodeIndexScan is used when there's a range look up. Is a String lookup considered a range? Please correct me if Im wrong.

**Comment by Hunterness** [comment]
Hi, since you seem to have solved this I'm closing the issue.
