### ISSUE TITLE
Neo4j-import reports zero (0) relationships

### ISSUE THREAD

**Issue by jkaster** [neo4j/neo4j#7458]
## Small import sets have 0 relationships

The import tool is reporting 0 relationships on small import sets. Doesn't happen with large sets.

**Neo4j Version:** 3.0.3  
**Operating System:** Windows 10 64-bit 
**API:** neo4j-import
### Steps to reproduce
1. Download [zero.zip](https://github.com/neo4j/neo4j/files/336028/zero.zip)
2. run `import [destinationpath]`
### Expected behavior

See the number of relationships created
### Actual behavior

See

```
IMPORT DONE in 2s 151ms. Imported:
  144 nodes
  0 relationships
  1726 properties
```

The relationships are definitely created, as shown here:
![image](https://cloud.githubusercontent.com/assets/6099714/16399630/101769b2-3c89-11e6-81a1-e78384ec6276.png)

**Comment by klaraseitz** [comment]
Any progress on this?
I encountered the same problem with 
**Neo4j Version:** 3.0.4 
**OS:** Ubuntu 14.04.5 LTS, 64-bit,
**API:** neo4j-import
Except I had to restart the server to see and access the newly added relationships.

**Comment by chrisvest** [comment]
@klaraseitz Were you using `import-tool` while the database was running?

**Comment by klaraseitz** [comment]
@chrisvest yes. i removed the graph.db folder though before running the import-tool.

**Comment by chrisvest** [comment]
@klaraseitz When you delete files on Linux, if the files are open, they won't actually be deleted until the last file handle to them are closed. Thus, when you deleted the graph.db folder while the database was running, it continued to use the database files that you had deleted. So to do what you wanted to do, you have to first stop the database, then run import-tool, and then start the database again.

**Comment by whatSocks** [comment]
I think this is fixed (3.0.5)

**Comment by tinwelint** [comment]
Cheers, I was just about to suggest this as well, I fixed a probably cause of this in 3.0.5. Closing

**Comment by mongoose54** [comment]
Neo4j Version: 3.1.3
OS: Ubuntu 14.04.5 LTS, 64-bit,
API: neo4j-import

@chrisvest I am also getting 0 relationships when I do `batch-import` but the relationships are successfully loaded in the database. Should I worry that they were not loaded properly.

Thanks!
-Alex

**Comment by tinwelint** [comment]
I think that's just a statistics issue in the importer, if your dataset looks OK, then nothing to worry about. Would it be possible for you provide the output and/or dataset for your import so that we could diagnose?
