### ISSUE TITLE
Startup fails with "Bad value for setting 'neostore.propertystore.db.strings.mapped_memory': value does not match expression:\d+[kmgKMG]?"

### ISSUE THREAD

**Issue by amorgner** [neo4j/neo4j#746]
If Neo4j embedded is started on a machine with less physical memory than the JVM tries to allocate, the following exception is thrown (with a varying number nn):

    Bad value '-nnM' for setting 'neostore.propertystore.db.strings.mapped_memory': value does not match expression:\d+[kmgKMG]?

The error can easily be reproduced on a virtual machine with f.e. 128 MB RAM.

**Comment by chrisvest** [comment]
@jakewins Yes, this was fixed in 2.2.0.
