### ISSUE TITLE
Error message when connecting a readonly EmbeddedDatabase to db built with earlier version (1.9.M03 and 1.9.RC1)

### ISSUE THREAD

**Issue by jennifersmith** [neo4j/neo4j#749]
Hello,

We found a strange error message in our log files and we wondered if it was possible to improve the error messaging.

We created a database on Windows 7, running 1.9.M03. We have an app that uses this database in readonly mode. We had recently upgraded this to 1.9.RC1.

After doing this upgrade, we were unable to load up the 1.9.M03 created store dir in readonly mode. That's understandable - connecting while writable presumably performs an upgrade to the data files but that's not something you want to allow in readonly mode. It would be nice to get a better error message though. We got this stacktrace https://gist.github.com/jennifersmith/5494471 - which was telling us that the storedir did not exist so it took us a little while to track down the problem. 

Thanks

Jen

**Comment by jakewins** [comment]
As this ticket is actually about improving error messages when database cannot start in read only mode, relabeling this as a feature and tagging as an operability problem.
