### ISSUE TITLE
Generating nodes using unwind range(1,700000) 

### ISSUE THREAD

**Issue by dmarkovitz** [neo4j/neo4j#7494]
Hi

I'm trying to generate nodes using the following code:

`unwind range(1,700000) as id create (:t700k{id:id})`

1.
Generating 100K-600K nodes finishes successfully but the execution time seems to be exponential which is obviously an issue with scalability. 
Is this an expected behavior?

> Added 100000 labels, created 100000 nodes, set 100000 properties, statement executed in 1694 ms.
> Added 200000 labels, created 200000 nodes, set 200000 properties,
>  statement executed in 3478 ms.
> Added 300000 labels, created 300000 nodes, set 300000 properties, statement executed in 4622 ms.
> Added 400000 labels, created 400000 nodes, set 400000 properties, statement executed in 7240 ms.
> Added 500000 labels, created 500000 nodes, set 500000 properties, statement executed in 19388 ms.
> Added 600000 labels, created 600000 nodes, set 600000 properties, statement executed in 56200 ms.

2.
Generating 700K nodes fails with the following error - 
"Error: undefined - undefined"

There are also no [ERROR] records in C:\Users\dmarkovitz\Documents\Neo4j\default.graphdb\logs\debug.log
[debug.log.txt](https://github.com/neo4j/neo4j/files/344935/debug.log.txt)
### version

I'm working from the web browser

neo4j-community_windows-x64_3_0_3.exe
Neo4j Browser version 1.1.6
COMMUNITY EDITION 3.0.3
### systeminfo

OS Name:                   Microsoft Windows 7 Enterprise
OS Version:                6.1.7601 Service Pack 1 Build 7601
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
System Manufacturer:       Dell Inc.
System Model:              OptiPlex 9020
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 60 Stepping 3 GenuineIntel ~3401 Mhz
BIOS Version:              Dell Inc. A05, 12/5/2013
Total Physical Memory:     8,134 MB
Available Physical Memory: 864 MB
Virtual Memory: Max Size:  16,267 MB
Virtual Memory: Available: 6,599 MB
Virtual Memory: In Use:    9,668 MB

Thanks

Dudu

**Comment by chrisvest** [comment]
> 2016-07-03 07:24:21.926+0000 INFO  [o.n.k.i.DiagnosticsManager] JVM memory information:
> 2016-07-03 07:24:21.926+0000 INFO  [o.n.k.i.DiagnosticsManager] Free  memory: 237.92 MB
> 2016-07-03 07:24:21.926+0000 INFO  [o.n.k.i.DiagnosticsManager] Total memory: 1.77 GB
> 2016-07-03 07:24:21.926+0000 INFO  [o.n.k.i.DiagnosticsManager] Max   memory: 1.77 GB

Neo4j keeps transaction state in heap memory, and this is apparently not enough to keep your 700.000 nodes. Increase the amount of heap memory you give to the database, or create your data in smaller batches.
http://neo4j.com/docs/operations-manual/current/#heap-sizing

> Error: undefined - undefined

If you are running this query from the browser, it might have timed out. What do you think, @oskarhane ?

**Comment by jexp** [comment]
Transaction state is held in heap memory. When you reach heap limits it will get slower, as it wills struggle to find memory. 

So make sure:
1. the amount of data you create in a single tx fits into memory
2. adapt your heap settings accordingly.

What are the heap settings in your neo4-wrapper.conf ?

Looking at your debug.log it seems that you run with only 1.7G total heap which leaves 1.5G for the young and old generational spaces.

And as you can see at the end of your debug log, the database (and the JVM is desperately trying to make room for more heap).

**Comment by jexp** [comment]
@chrisvest we should probably look at the memory usage of tx-state again, 700k nodes with one label and one simple id property shouldn't take that much heap.

**Comment by MishaDemianenko** [comment]
Hi @dmarkovitz you should follow @chrisvest advise and split huge transactions into separate smaller transactions and that should solve that kind of problems. If you do not mind I will close this issue since suggestion should solve your problem for some time already?

**Comment by jexp** [comment]
You can also use APOC for larger operations.

e.g.

```
call apoc.periodic.iterate('
unwind range(1,700000) as id return id
','
create (:t700k{id:id})
',{batchSize:100000,iterateList:true});

```

**Comment by MishaDemianenko** [comment]
@dmarkovitz closing as answered, please feel free to reopen in case this is still an issue
