### ISSUE TITLE
Shortest Path without specifying relationship details over HTTP REST API

### ISSUE THREAD

**Issue by bzier** [neo4j/neo4j#7497]
The shortest path between two nodes is not being returned properly without specifying relationship details.

**Neo4j Version:** 3.0.3
**Operating System:** Ubuntu 15.04
**API:** HTTP REST
### Steps to reproduce

With a completely fresh database:

`merge ()-[:friend]->()-[:friend]->()`

This should generate nodes with IDs 0, 1, and 2 with `:friend` relationship IDs 0, 1.

---

HTTP POST to the URL:

`http://localhost:7474/db/data/node/0/paths`

with the following data:

``` JSON
{
    "to":"http://localhost:7474/db/data/node/2",
    "algorithm":"allPaths",
    "max_depth":5
}
```

Returns the following response (as expected):

``` JSON
[
  {
    "relationships": [
      "http://localhost:7575/db/data/relationship/0",
      "http://localhost:7575/db/data/relationship/1"
    ],
    "nodes": [
      "http://localhost:7575/db/data/node/0",
      "http://localhost:7575/db/data/node/1",
      "http://localhost:7575/db/data/node/2"
    ],
    "directions": [
      "->",
      "->"
    ],
    "start": "http://localhost:7575/db/data/node/0",
    "length": 2,
    "end": "http://localhost:7575/db/data/node/2"
  }
]
```

---

HTTP POST to the URL:

`http://localhost:7474/db/data/node/0/paths`

with the following data:

``` JSON
{
    "to":"http://localhost:7474/db/data/node/2",
    "algorithm":"shortestPath",
    "max_depth":5
}
```

Returns the following response:

``` JSON
[]
```

---

HTTP POST to the URL:

`http://localhost:7474/db/data/node/0/paths`

with the following data:

``` JSON
{
    "to":"http://localhost:7575/db/data/node/2",
    "max_depth":5,
    "relationships" : {
        "type" : "friend",
        "direction" : "all"
        },
    "algorithm":"shortestPath"
}
```

Returns the following response (as expected):

``` JSON
[
  {
    "relationships": [
      "http://localhost:7575/db/data/relationship/0",
      "http://localhost:7575/db/data/relationship/1"
    ],
    "nodes": [
      "http://localhost:7575/db/data/node/0",
      "http://localhost:7575/db/data/node/1",
      "http://localhost:7575/db/data/node/2"
    ],
    "directions": [
      "->",
      "->"
    ],
    "start": "http://localhost:7575/db/data/node/0",
    "length": 2,
    "end": "http://localhost:7575/db/data/node/2"
  }
]
```
### Expected behavior

Without specifying the `relationships` property on the request, the shortest path should be returned regardless of relationship type and direction.
### Actual behavior

Without specifying the `relationships` property on the request, no relationships are matched and none are returned, despite that there are paths between them. Asking for `allPaths` returns the paths appropriately with and without specifying the `relationships` property on the request.
### Testing
- Testing in 2.2.3, this behavior works as expected. 
- In 3.0.3, it is not working.

I have tried adding relationships in varying directions, with one or more nodes between, connecting the two end nodes. I have tried giving more than one shortest path, as well as a clear single shortest path. The only case that works properly is a direct connection between the two nodes.

**Comment by jexp** [comment]
I think the change by @tinwelint when [breaking out the algorithm](https://github.com/neo4j/neo4j/blame/3.1/community/server/src/main/java/org/neo4j/server/rest/domain/RelationshipExpanderBuilder.java#L35) to default to Expander.empty() and not Expander.all() might be the culprit here.

But you should be easily able to work around it, by just not providing a type in the relationships-map.

Is there any reason for you to use the REST API instead of Cypher?

**Comment by bzier** [comment]
Leaving out the type results in a 500 server error. I can leave out the direction and it defaults to 'all', but can't leave off the type.

I mentioned on the neo4j-users slack #help channel how/why I bumped into this if you want details, but the simple answer is that I'm using an older PHP library that is using the REST API. I'm gonna try to work away from it though.
