### ISSUE TITLE
[Feature Request] In web console, add Roll-up option

### ISSUE THREAD

**Issue by cosimosimeoneTR** [neo4j/neo4j#7510]
As in Gnome 2.x / Kde

http://www.howtogeek.com/105009/roll-up-a-window-in-linux-mint-12/

**Comment by spacecowboy** [comment]
Not sure how this applies to the web console. Can you be more specific? Perhaps a screenshot of which part you think should roll-up would be in order?

**Comment by cosimosimeoneTR** [comment]
There you go
![capture](https://cloud.githubusercontent.com/assets/14905526/16612905/b8483eea-4369-11e6-9ee3-c89593c5db39.PNG)

**Comment by spacecowboy** [comment]
Thanks, that made it much clearer

**Comment by oskarhane** [comment]
This feature is implemented but we must have missed to close this issue.
