### ISSUE TITLE
[3.0.3][Cypher] Use case where NodeIndexSeek produces a serious amount of db hits

### ISSUE THREAD

**Issue by ikwattro** [neo4j/neo4j#7518]
## Use case where NodeIndexSeek produces a serious amount of db hits

**Neo4j Version:** 3.0.3  
**Operating System:** Ubuntu 14.10
**API:** All
### Steps to reproduce

Take the following query : 

```
PROFILE 
MATCH (cat:Category) WHERE cat.category_type IN ["cat","xx","yy"]
WITH collect(cat) as categories
MATCH (m:Entity)
WHERE m.domain_id IN ["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16,"17","18","19"]
WITH m, categories
MATCH (m)<-[r]-(n)
RETURN count(n)
```

Works ok and there is 38 db hits for :Entity(domain_id) NodeUniqueIndexSeek.

![plan 6](https://cloud.githubusercontent.com/assets/1222009/16596314/a38c9f58-42f3-11e6-9c91-0ad2f9a8e97f.png)

However adding a `WHERE ANY(x IN categories WHERE (n)-[:HAS_CATEGORY]->(x))` after the last match, the amount of db hits for `:Entity(domain_id)` is _4million+_ and there is nothing related to it in this WHERE clause:

```
PROFILE 
MATCH (cat:Category) WHERE cat.category_type IN ["cat","xx","yy"]
WITH collect(cat) as categories
MATCH (m:Entity)
WHERE m.domain_id IN ["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16,"17","18","19"]
WITH m, categories
MATCH (m)<-[r]-(n)
WHERE ANY(x IN categories WHERE (n)-[:HAS_CATEGORY]->(x))
RETURN count(n)
```

![plan 7](https://cloud.githubusercontent.com/assets/1222009/16596324/aac3ed4e-42f3-11e6-96cd-756e5f776517.png)
### Expected behavior

Should produce the same amount of db hits for :Entity(domain_id)
### Actual behavior

Serious amount of db hits

**Comment by ikwattro** [comment]
cc @jexp @systay @bachmanm

**Comment by sherfert** [comment]
That was fixed here: https://github.com/neo4j/neo4j/pull/8892
