### ISSUE TITLE
Neo.ClientError.Statement.EntityNotFound; Description: Unable to load NODE with id

### ISSUE THREAD

**Issue by Artgit** [neo4j/neo4j#7546]
- Neo4j version: 3.0.3
- Operating system: Windows 10
- API/Driver: Java
- **Steps to reproduce**

I have faced a following issue with Neo4j 3.0.3 http://stackoverflow.com/questions/38295786/spring-data-neo4j-neo-clienterror-statement-entitynotfound-description-unable

Could you please check this ? This looks like a Neo4j issue.

**Comment by spacecowboy** [comment]
Please provide some steps to reproduce the issue. We are unable to diagnose the issue otherwise.

Either a script or a csv file to create a dataset where the query fails would do.

**Comment by Artgit** [comment]
This is a sample database:

[default.graphdb.zip](https://github.com/neo4j/neo4j/files/357246/default.graphdb.zip)

Please try a following query:

`MATCH (d:Decision) WHERE id(d) IN [155, 163, 144] OPTIONAL MATCH (d)<-[:COMMENTED_ON*]-(com:Comment) DETACH DELETE com WITH d OPTIONAL MATCH (d)<-[:DEFINED_BY]-(c) WITH d, c OPTIONAL MATCH (c)<-[:VOTED_ON]-(vg) WITH d, c, vg OPTIONAL MATCH (vg)-[:CONTAINS]->(v) DETACH DELETE v, vg, c, d`

**Comment by spacecowboy** [comment]
Thank you
