### ISSUE TITLE
neo4j community edition on mac is missing binaries

### ISSUE THREAD

**Issue by jimbobhickville** [neo4j/neo4j#7566]
- Neo4j version: 3.0.3 Community Edition
- Operating system: Mac OS:X 
- API/Driver: N/A
- **Steps to reproduce**
1. Install neo4j from dmg
2. Try to run `/Applications/Neo4j Community Edition.app/Contents/Resources/app/bin/neo4j-import`
3. Try to run `neo4j start` or `/Applications/Neo4j Community Edition.app/Contents/Resources/app/bin/neo4j start`
- Expected behavior
  neo4j-import should function
  a neo4j binary to start/stop the service should exist somewhere on the filesystem
- Actual behavior

neo4j-import fails because it's expecting another file to exist:
`/Applications/Neo4j Community Edition.app/Contents/Resources/app/bin/neo4j-import: line 26: /Applications/Neo4j Community Edition.app/Contents/Resources/app/bin/neo4j-shared.sh: No such file or directory`

neo4j (the binary) does not exist, so you can't control the program via the command line at all.

Googling suggests that people have been having this problem for at least 4 months, but no solutions other than "install from homebrew instead".

**Comment by spacecowboy** [comment]
Thanks for the report. There is actually a PR intending to fix the installers as part of its work #7501 but I had not noticed the lack of the `neo4j-shared.sh` script. Will fix that there.
