### ISSUE TITLE
[3.1][Documentation] - Request for more explanations about pattern comprehension

### ISSUE THREAD

**Issue by ikwattro** [neo4j/neo4j#7577]
Hi,

Recently patterns comprehensions has been merged into 3.1 and after checking the doc I still don't really understand what it should do neither what are the benefits of it.

Ref commit is https://github.com/neo4j/neo4j/commit/c067fd918c23aebb156f4cec268e134b1f61c08e#diff-726176c1183002e63d5bb9361f5e1c52R114

Is it possible to add a bit more documentation to it. Thanks !

/cc @jexp

**Comment by systay** [comment]
Hi Christophe!

It might not be particularly easy to find, but there is a little something there: 
http://neo4j.com/docs/developer-manual/beta/cypher/#_pattern_comprehension

Is there anything in particular you are missing?

(Please also check out [map projections](http://neo4j.com/docs/developer-manual/beta/cypher/#_map_projection), another cool (IMHO) feature in Neo4j 3.1)

**Comment by ikwattro** [comment]
Thanks @systay !

Actually at the time of the issue I was looking what problem it was solving, more a use case with before / after. I'll dig into some tests.

Thanks for map projections, this is actually awesome !
