### ISSUE TITLE
weird cypher implementation

### ISSUE THREAD

**Issue by iCoolchar** [neo4j/neo4j#7590]
first: 
`profile MATCH (src)-[:Friend]-(dst) WHERE id(src)=359340  and id(dst)=630950  return 1 as N`
Cypher version: CYPHER 2.3, planner: COST. 2551 total db hits in 1483 ms.

second:
`profile MATCH (src),(dst) WHERE (src)-[:Friend]-(dst) and id(src)= 359340 and id(dst)= 630950 return 1 as n`
Cypher version: CYPHER 2.3, planner: COST. 126 total db hits in 133 ms.

Why don't you process the first cypher with the second proceedure? I think the first writing is more elegant and if the implementation could be like the second one, it would be much better.
- Neo4j version: 2.3.2
- Operating system: Mac
- Cypher version: CYPHER 2.3

Many thanks!

**Comment by jexp** [comment]
Can you share the two profiles?

**Comment by jexp** [comment]
I think it would make sense as a general approach for this kind of query.
- load both nodes by id
- do an expand-into

An expand + id-comparison will never be faster than that.

**Comment by iCoolchar** [comment]
Sorry I can't post the image due to the network problem. But I think it's easy to reproduce in local database. I would really appreciate it if you could enhance it asap. Thanks!

**Comment by craigtaverner** [comment]
The two queries above do two different, but related things. The first will find all friend relationships, while the second will find all combinations for which at least one relationship exists. If there is only one relationship, they behave the same, but if there are more they do not.

So it is not possible to plan the one as the other. For this reason I would like to close this issue.

However, you are also implying (and Michael asserted this also) that there is an issue with the first query not planning with an ExpandInto. For most databases the difference between the two plans (Expand(All) versus Expand(Into)) is negligable. However, if there are super-nodes involved, Expand(Into) can be much faster. There is a known issue in planning for those cases, and that is reported elsewhere. There is also a workaround, which is to insert an extra WITH clause between the node matches and the relationship match. The following query will do the same as the first one above, but use ExpandInto, and therefore perform more like the second:

    explain MATCH (src),(dst) WITH src,dst,true as x MATCH (src)-[:Friend]-(dst) WHERE id(src)=359340 and id(dst)=630950 return 1 as N
