### ISSUE TITLE
[Feature request] : possibility to set a subgraph as a context

### ISSUE THREAD

**Issue by tomzeppenfeldt** [neo4j/neo4j#7593]
## Problem

I have situations in which I use `allShortestPaths()` in combination with a couple of predicates, for instance in betweenness-centrality calculations like

```
WITH [123,456] as nodeIds
MATCH p=allShortestPaths((a)-[*]-(b))
WHERE 
     id(a) in nodeIds 
     AND id(b) in nodeIds 
     AND id(a) < id(b) 
     AND length(p)> 1 
     AND NOT (a)--(b)
WITH a,
     b,
     collect(p) AS allpaths, 
     count(p) AS allcount
UNWIND allpaths AS p 
UNWIND nodes(p)[1..-1] AS n
WITH n,
     a,
     b,
     tofloat(count(p))/tofloat(allcount) AS fraction
RETURN n.name, 
       sum(fraction) AS betweenness_centrality
ORDER BY betweenness_centrality DESC
```

which works fine in case there are paths and the graph is not too big. trying to limit the search of paths to nodes of a certain type , like this

```
WITH ['label1','label2'] as nodelabels, [123,456] as nodeIds
MATCH p=allShortestPaths((a)-[*]-(b))
WHERE 
     ALL(n in nodes(p) WHERE 
           ALL (l IN labels(n) WHERE l IN nodelabels)
    ) 
     id(a) in nodeIds 
     AND id(b) in nodeIds 
     AND id(a) < id(b) 
     AND length(p)> 1 
     AND NOT (a)--(b)
```

very often leads to time-out, especially in cases where there is no path.
## Possible solution?

If there would be an option to set some context in which the shortestPaths are searched, previous to the actual calculation process, for instance like this:

```
WITH ['label1','label2'] as nodelabels, ['TYPE1','TYPE2','TYPE3'] as reltypes, ][123,456] as nodeIds
MATCH (n)-[r]-(m) 
WHERE 
       labels(n) IN nodelabels
      AND labels(m) IN nodelabels
      AND type(r) IN reltypes
WITH COLLECT(r) as mySubgraph,nodeIds

// set context of allShortestPaths to mySubGraph    
MATCH p=allShortestPaths((a)-[*]-(b) IN mySubGraph)      << or any other syntax of course     

WHERE 
     id(a) in nodeIds 
     AND id(b) in nodeIds 
     AND id(a) < id(b) 
     AND length(p)> 1 
     AND NOT (a)--(b)
```

it would be great.

**Comment by sherfert** [comment]
This is heavily discussed be in Cypher Implementers Meetings. Have a look at https://github.com/opencypher/openCypher/issues/182 and http://www.opencypher.org/
It will have to go through there before we can implement that.

**Comment by sherfert** [comment]
Better link: https://github.com/boggle/openCypher/blob/CIP2017-06-18-multiple-graphs/cip/1.accepted/CIP2017-06-18-multiple-graphs.adoc
