### ISSUE TITLE
weird ghost node

### ISSUE THREAD

**Issue by iCoolchar** [neo4j/neo4j#7603]
I don't think I have ever created any node with a label named "ghost". But today I found there were many nodes with no properties at all in production evironment. But unfortunately I couldn't reproduce it in my local environment. Is it kind of some historical version upgrade problem? Could I just delete them? Is there any concern? Any suggestion would be appreciated!

production:
Neo4j version: 2.1-2.3
Operating system: Linux

local:
Neo4j version: 2.3.2
Operating system: Mac

**Comment by jexp** [comment]
Could als be a Cypher query with a typo in a relationship create or merge. 

Von meinem iPhone gesendet

**Comment by iCoolchar** [comment]
I don't think so. If there is a typo, it would create a node without any properties or labels. But in my case, there is a ghost label...

**Comment by ehx-v1** [comment]
A "ghost" label... No properties... And you didn't create it...
Kind of creepy. But most probably just a joke from a peer of yours. As long as no nodes went missing, it's nothing you should pay attention to.

**Comment by chrisvest** [comment]
Tokens like that are created on demand when they are mentioned in a query, even if the transaction that the query runs within is rolled back. That is probably what you are seeing the result of.
