### ISSUE TITLE
PathImpl.singular throws exception when calling reverseNodes()

### ISSUE THREAD

**Issue by astone282** [neo4j/neo4j#7609]
When instantiating a path using PathImpl.singular, using reverseNodes is throwing an exception.

Neo4j 2.3.1

```
Path myPath = PathImpl.singular(node); // somewhere in the code 
Iterator<Node> reverseIterator = myPath.reverseNodes().iterator();  // used somewhere else
if (reverseIterator.hasNext())  {  // This returns true
     Node aNode = reverseIterator().next(); // this throws exception
}
```

Exception is as follows:

> java.util.NoSuchElementException: null
>   at org.neo4j.graphalgo.impl.util.PathImpl$1$1.next(PathImpl.java:201) ~[neo4j-graph-algo-2.3.1.jar:2.3.1]
>   at org.neo4j.graphalgo.impl.util.PathImpl$1$1.next(PathImpl.java:187) ~[neo4j-graph-algo-2.3.1.jar:2.3.1]

**Comment by spacecowboy** [comment]
Thanks for the clear report, managed to reproduce bug.

**Comment by astone282** [comment]
great, thanks!
