### ISSUE TITLE
`db.constraints` should have backticks around labels and properties

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4j/neo4j#7634]
If I create a constraint like so:

``` cypher
CREATE CONSTRAINT ON (n:`Foo:Bar`) ASSERT n.`blah.baz` IS UNIQUE
```

And then get a list of constraints:

``` cypher
CALL db.constraints()
```

The relevant row that I get is:

```
CONSTRAINT ON ( foo:bar:Foo:Bar ) ASSERT foo:bar.blah.baz IS UNIQUE
```

I would expect this to be:

```
CONSTRAINT ON ( `foo:bar`:`Foo:Bar` ) ASSERT `foo:bar`.`blah.baz` IS UNIQUE
```

Or even:

```
CONSTRAINT ON ( foo_bar:`Foo:Bar` ) ASSERT foo_bar.`blah.baz` IS UNIQUE
```

I'm currently working on the Bolt driver for the `neo4j` gem and the gem needs to be able to look for indexes and constraints.  The gem sometimes creates labels which match a Ruby namespaced class (like `Module1::Module2::ModelClass`).  I won't be able to reliably parse the results of `db.constraints()` and `db.indexes()` without sometime to indicate where the label and property start/end.
- Neo4j version: Tested on 3.0.1 and 3.0.3
- Operating system: OS X, `tar.gz` version
- API/Driver: Web console

**Comment by cheerfulstoic** [comment]
Sorry, I didn't actually test `db.indexes`, but I see that it has multiple columns and so I think it would be possible to parse out the label / property / type from that.  Does the `node_unique_property` in the `type` column of `db.indexes` always mean that the index comes from a unique constraint?

**Comment by spacecowboy** [comment]
Yes, I believe that it does mean that.

**Comment by cheerfulstoic** [comment]
Aren't there other characters which should be escaped?   Would it make sense to just always have quotes?

**Comment by jexp** [comment]
I don't think it's a good idea in the first place.

Then those backticks are also displayed in all other UIs that use the procedure which is really not a user-friendly approach.

I think it's valid to put the responsbility of adding backticks to identifiers to the library that generates cypher text strings from some input. As it has to do it for other identifiers that it generates itself or gets from other sources anyhow.

If you were to use the output of the procedures, e.g. from an embedded API you would have to remove the backticks first, which would be super annoying.

@systay @pontusmelke
