### ISSUE TITLE
Neo4j-import is unknow (nothing in /bin)

### ISSUE THREAD

**Issue by ftriss** [neo4j/neo4j#7672]
I just installed Neo4j 3.0.4 CE (.exe) and there is no import tool in the bin folder.

In v2.3, there was some .bat in the bin folder, and on the .zip version, powershell have some command.

**Comment by spacecowboy** [comment]
Thank you for the report

**Comment by chrisvest** [comment]
The new Neo4j Desktop does not have this problem.
