### ISSUE TITLE
[feature request]  multiple relations in shortest path cypher

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#77]
@yaronn: 'Hi

I build a social network:

user-->FRIENDS_WITH-->user
user-->LIKES-->product

given a user and a product how can I use cypher (over rest) to find the shortest path between them if exist? e.g. I have a friend which has a friend that like the product.

I am able to do the match I want:

MATCH (n)<-[:friends_with*0..5]-(x)<-[:likes]-(y)

but this syntax is not valid for a shortest path. I'm only able to use:

shortestPath( n-[:friends_with]-x )

which means I cannot express the fact that a user I am FRIEND_WITH also LIKES a product.

how can I use the same semantic in the shortestPath, e.g. "the path should follow all outgoing FRIENDS_WITH and LIKE links and end after the first LIKE link in the path"

Thanks,
Yaron'

**Comment by alinador** [comment]
+1

**Comment by boggle** [comment]
This is being worked on as part of Cypher 10 and GQL.

**Comment by Lojjs** [comment]
@lassewesth I will close this super old Github issue (which I think you are not the original author of but have transferred from somewhere else). This will be supported with the new GPM shortest syntax
