### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by thiagomorato** [neo4j/neo4j#7700]
I'm not sure if this issue is related to the spatial plugin or the neo4j itself, here is link to the issue:

https://github.com/neo4j-contrib/spatial/issues/264
- Neo4j version: 3.0.4
- Spatial plugin version: 0.19 for neo4j 3.0.3
- Operating system: Mac OSX 10.10
- API/Driver: http
- **Steps to reproduce**: not sure, it is a bit volatile, maybe it is a matter of configuration. I will try to isolate the issue but if anyone have any tip it would be more than welcome.
- Expected behavior: It shouldn't refuse connections after a few thousand requests.
- Actual behavior: It refuse connections after a few thousand requests.

**Comment by spacecowboy** [comment]
Without reproduction steps there is little we can do to help I'm afraid :(

Do you get connection refused also if you go to http://localhost:7474 in your browser?

**Comment by thiagomorato** [comment]
Yeah I know, and yes it was working in the browser. Anyway suddenly it started to work fine but I have no idea what was going on, if it happens again I will try to isolate the issue with fake data, thanks for your attention.

**Comment by spacecowboy** [comment]
Alright. I'll close the issue for now then. Feel free to re-open or file a new one if you manage to reproduce it.
