### ISSUE TITLE
Link broken in neo4j text file

### ISSUE THREAD

**Issue by rationalism** [neo4j/neo4j#7712]
The UPGRADE.txt file in the neo4j 3.0.4 download reads:

"For upgrade instructions, please see http://neo4j.com/docs/operations-manual/current/#upgrading."

This link looks broken. The appropriate link appears to be http://neo4j.com/docs/operations-manual/current/deployment/#upgrade.

**Comment by spacecowboy** [comment]
Thanks for the report!

**Comment by spacecowboy** [comment]
fixed in https://github.com/neo4j/neo4j/pull/8059
