### ISSUE TITLE
Neo4j 3.1M06 'publisher' role can delete entire graph

### ISSUE THREAD

**Issue by graphadvantage** [neo4j/neo4j#7741]
Neo4j 3.1 Enterprise Windows M06

In testing the new RBAC procedures I noticed the following:

Assume two users, with role 'publisher'

```
CALL dbms.createUser('Paul','neo4j',false)
CALL dbms.createUser('Polly','neo4j',false)

CALL dbms.addUserToRole('Paul','publisher')
CALL dbms.addUserToRole('Polly','publisher')

CALL dbms.listUsersForRole('publisher')
```

╒═════╕
│value│
╞═════╡
│Paul │
├─────┤
│Polly│
└─────┘

Polly logs in, creates a node
`:server connect`
You are connected as user Polly
to the server http://localhost:7474/browser/
`CREATE (n:RBAC {name:'nodeMadeByPolly'}) RETURN *`
`:server disconnect`

Paul logs in, creates a node
`:server connect`
You are connected as user Paul
to the server http://localhost:7474/browser/
`CREATE (n:RBAC {name:'nodeMadeByPaul'}) RETURN *`
`:server disconnect`

Polly logs in:
`:server connect`
You are connected as user Polly
to the server http://localhost:7474/browser/

`MATCH (n:RBAC) RETURN n`
╒═══════════════════════╕
│n                      │
╞═══════════════════════╡
│{name: nodeMadeByPolly}│
├───────────────────────┤
│{name: nodeMadeByPaul} │
└───────────────────────┘

`MATCH (n) DETACH DELETE n`

Deleted 2 nodes, statement executed in 16 ms.

Poof!  The whole graph is gone....deleted by Polly, someone who is neither an architect nor an admin.

Is this the desired behavior?  Seems like a pretty big, unsafe, privilege for an enterprise db.

Perhaps this could be handled with a flag in neo.conf for whether publishers can delete all objects (default) or be restricted to deleting only their own objects.  If delete only own objects is set, then a createdByUser property could be set on the user's created/merged objects and then used to restrict delete scope. 

Then the expected behavior for user Polly would be
`MATCH (n) DETACH DELETE n`

Deleted 1 node, statement executed in 16 ms.
`MATCH (n:RBAC) RETURN n`

╒═══════════════════════╕
│n                      │
╞═══════════════════════╡
│{name: nodeMadeByPaul} │
└───────────────────────┘

And Paul's stuff is safe....

**Comment by henriknyman** [comment]
The plan for 3.1 is that the publisher role has write access to the whole graph. Generalized fine-grained permissions on the graph is in the backlog and will come post 3.1.
However, we currently plan to have an intermediate step for achieving fine-grained permissions through stored procedures, by letting you specify custom roles that are allowed to execute a procedure. The procedure can then run with a less restricted access mode then the user (e.g. write access to the full graph), and the responsibility of enforcing more limited access falls on the procedure writer (e.g. you could have specific procedures for performing specific tasks/queries).

**Comment by graphadvantage** [comment]
Hi Henrik - thanks for the explanation, looking forward to seeing this!
