### ISSUE TITLE
TransactionFailureException and ConcurrentRequests

### ISSUE THREAD

**Issue by snig-b** [neo4j/neo4j#7742]
I am getting 400 status on almost all api hits on neo4j server. TransactionFailureExceptions relating to locks and ConcurrentRequests. 
I also get this response in some requests and the below stacktrace for others: 
Status code = 400. 'message': u'org.neo4j.kernel.api.exceptions.TransactionFailureException: The lock session requested to start is already in use. Please retry your request in a few seconds.', u'code': u'Neo.ClientError.Transaction.ConcurrentRequest'
- Neo4j version: 2.2.3
- Operating system: Ubuntu 14.04.1 LTS
- API/Driver: (Cypher
- **Steps to reproduce** : Constant response for almost all api hits.
- Expected behavior - Response 200/201
- Actual behavior: 
  Status code return was 400. 
  Stacktrace: 
  Errors returned were [{u'stackTrace': u'org.neo4j.com.ComException: MasterClient214 could not connect to /172.22.65.169:6001\n\tat org.neo4j.com.Client$1.create(Client.java:151)\n\tat org.neo4j.com.Client$1.create(Client.java:135)\n\tat org.neo4j.com.ResourcePool.acquire(ResourcePool.java:176)\n\tat org.neo4j.com.Client.acquireChannelContext(Client.java:302)\n\tat org.neo4j.com.Client.sendRequest(Client.java:214)\n\tat org.neo4j.com.Client.sendRequest(Client.java:207)\n\tat org.neo4j.kernel.ha.MasterClient210.newLockSession(MasterClient210.java:213)\n\tat sun.reflect.GeneratedMethodAccessor151.invoke(Unknown Source)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:606)\n\tat org.neo4j.kernel.ha.DelegateInvocationHandler.proxyInvoke(DelegateInvocationHandler.java:107)\n\tat org.neo4j.kernel.ha.DelegateInvocationHandler.access$100(DelegateInvocationHandler.java:44)\n\tat org.neo4j.kernel.ha.DelegateInvocationHandler$Concrete.invoke(DelegateInvocationHandler.java:158)\n\tat com.sun.proxy.$Proxy61.newLockSession(Unknown Source)\n\tat org.neo4j.kernel.ha.lock.SlaveLocksClient.makeSureTxHasBeenInitialized(SlaveLocksClient.java:324)\n\tat org.neo4j.kernel.ha.lock.SlaveLocksClient.acquireExclusiveOnMaster(SlaveLocksClient.java:292)\n\tat org.neo4j.kernel.ha.lock.SlaveLocksClient.acquireExclusive(SlaveLocksClient.java:123)\n\tat org.neo4j.kernel.impl.api.ConstraintEnforcingEntityOperations.nodeGetUniqueFromIndexLookup(ConstraintEnforcingEntityOperations.java:241)\n\tat org.neo4j.kernel.impl.api.GuardingStatementOperations.nodeGetUniqueFromIndexLookup(GuardingStatementOperations.java:181)\n\tat org.neo4j.kernel.impl.api.OperationsFacade.nodeGetUniqueFromIndexLookup(OperationsFacade.java:180)\n\tat org.neo4j.cypher.internal.spi.v2_2.TransactionBoundQueryContext.exactUniqueIndexSearch(TransactionBoundQueryContext.scala:134)\n\tat org.neo4j.cypher.internal.compiler.v2_2.spi.DelegatingQueryContext.exactUniqueIndexSearch(DelegatingQueryContext.scala:96)\n\tat org.neo4j.cypher.internal.compatibility.ExceptionTranslatingQueryContext.org$neo4j$cypher$internal$compatibility$ExceptionTranslatingQueryContext$$super$exactUniqueIndexSearch(ExceptionTranslatingQueryContext.scala:131)\n\tat org.neo4j.cypher.internal.compatibility.ExceptionTranslatingQueryContext$$anonfun$exactUniqueIndexSearch$1.apply(ExceptionTranslatingQueryContext.scala:131)\n\tat org.neo4j.cypher.internal.compatibility.ExceptionTranslatingQueryContext$$anonfun$exactUniqueIndexSearch$1.apply(ExceptionTranslatingQueryContext.scala:131)\n\tat org.neo4j.cypher.internal.compatibility.ExceptionTranslatingQueryContext.org$neo4j$cypher$internal$compatibility$ExceptionTranslatingQueryContext$$translateException(ExceptionTranslatingQueryContext.scala:182)\n\tat org.neo4j.cypher.internal.compatibility.ExceptionTranslatingQueryContext.exactUniqueIndexSearch(ExceptionTranslatingQueryContext.scala:131)\n\tat org.neo4j.cypher.internal.compiler.v2_2.pipes.NodeIndexSeekPipe$$anonfun$1$$anonfun$apply$1.apply(NodeIndexSeekPipe.scala:45)\n\tat org.neo4j.cypher.internal.compiler.v2_2.pipes.NodeIndexSeekPipe$$anonfun$1$$anonfun$apply$1.apply(NodeIndexSeekPipe.scala:45)\n\tat org.neo4j.cypher.internal.compiler.v2_2.commands.indexQuery$$anonfun$apply$1.apply(indexQuery.scala:53)\n\tat org.neo4j.cypher.internal.compiler.v2_2.commands.indexQuery$$anonfun$apply$1.apply(indexQuery.scala:51)\n\tat scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)\n\tat scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)\n\tat scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)\n\tat scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)\n\tat scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)\n\tat scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)\n\tat org.neo4j.cypher.internal.compiler.v2_2.commands.indexQuery$.apply(indexQuery.scala:50)\n\tat org.neo4j.cypher.internal.compiler.v2_2.pipes.NodeIndexSeekPipe.internalCreateResults(NodeIndexSeekPipe.scala:55)\n\tat org.neo4j.cypher.internal.compiler.v2_2.pipes.Pipe$class.createResults(Pipe.scala:58)\n\tat org.neo4j.cypher.internal.compiler.v2_2.pipes.NodeIndexSeekPipe.createResults(NodeIndexSeekPipe.scala:33)\n\tat org.neo4j.cypher.internal.compiler.v2_2.pipes.PipeWithSource.createResults(Pipe.scala:119)\n\tat org.neo4j.cypher.internal.compiler.v2_2.pipes.PipeWithSource.createResults(Pipe.scala:119)\n\tat org.neo4j.cypher.internal.compiler.v2_2.pipes.PipeWithSource.createResults(Pipe.scala:119)\n\tat org.neo4j.cypher.internal.compiler.v2_2.pipes.PipeWithSource.createResults(Pipe.scala:119)\n\tat org.neo4j.cypher.internal.compiler.v2_2.pipes.PipeWithSource.createResults(Pipe.scala:119)\n\tat org.neo4j.cypher.internal.compiler.v2_2.pipes.PipeWithSource.createResults(Pipe.scala:119)\n\tat org.neo4j.cypher.internal.compiler.v2_2.pipes.NewUnionPipe.internalCreateResults(UnionPipe.scala:58)\n\tat org.neo4j.cypher.internal.compiler.v2_2.pipes.Pipe$class.createResults(Pipe.scala:58)\n\tat org.neo4j.cypher.internal.compiler.v2_2.pipes.NewUnionPipe.createResults(UnionPipe.scala:49)\n\tat org.neo4j.cypher.internal.compiler.v2_2.pipes.NewUnionPipe.internalCreateResults(UnionPipe.scala:58)\n\tat org.neo4j.cypher.internal.compiler.v2_2.pipes.Pipe$class.createResults(Pipe.scala:58)\n\tat org.neo4j.cypher.internal.compiler.v2_2.pipes.NewUnionPipe.createResults(UnionPipe.scala:49)\n\tat org.neo4j.cypher.internal.compiler.v2_2.pipes.PipeWithSource.createResults(Pipe.scala:119)\n\tat org.neo4j.cypher.internal.compiler.v2_2.executionplan.DefaultExecutionResultBuilderFactory$ExecutionWorkflowBuilder.createResults(DefaultExecutionResultBuilderFactory.scala:92)\n\tat org.neo4j.cypher.internal.compiler.v2_2.executionplan.DefaultExecutionResultBuilderFactory$ExecutionWorkflowBuilder.build(DefaultExecutionResultBuilderFactory.scala:64)\n\tat org.neo4j.cypher.internal.compiler.v2_2.executionplan.ExecutionPlanBuilder$$anonfun$getExecutionPlanFunction$1.apply(ExecutionPlanBuilder.scala:121)\n\tat org.neo4j.cypher.internal.compiler.v2_2.executionplan.ExecutionPlanBuilder$$anonfun$getExecutionPlanFunction$1.apply(ExecutionPlanBuilder.scala:105)\n\tat org.neo4j.cypher.internal.compiler.v2_2.executionplan.ExecutionPlanBuilder$$anon$1.run(ExecutionPlanBuilder.scala:69)\n\tat org.neo4j.cypher.internal.compatibility.CompatibilityFor2_2$ExecutionPlanWrapper$$anonfun$run$1.apply(CompatibilityFor2_2.scala:178)\n\tat org.neo4j.cypher.internal.compatibility.CompatibilityFor2_2$ExecutionPlanWrapper$$anonfun$run$1.apply(CompatibilityFor2_2.scala:178)\n\tat org.neo4j.cypher.internal.compatibility.exceptionHandlerFor2_2$.runSafely(CompatibilityFor2_2.scala:108)\n\tat org.neo4j.cypher.internal.compatibility.CompatibilityFor2_2$ExecutionPlanWrapper.run(CompatibilityFor2_2.scala:177)\n\tat org.neo4j.cypher.internal.PreparedPlanExecution.execute(PreparedPlanExecution.scala:28)\n\tat org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:108)\n\tat org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:102)\n\tat org.neo4j.cypher.javacompat.internal.ServerExecutionEngine.executeQuery(ServerExecutionEngine.java:61)\n\tat org.neo4j.server.rest.web.CypherService.cypher(CypherService.java:118)\n\tat sun.reflect.GeneratedMethodAccessor105.invoke(Unknown Source)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:606)\n\tat com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)\n\tat com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)\n\tat com.sun.

Could you tell me why is this error being raised and what can I do to prevent it or any guidelines where I should look for debugging this.

**Comment by snig-b** [comment]
I am using the legacy URL '/cypher'. Could this be the problem? Should I move onto transaction  based URLs?

**Comment by jexp** [comment]
Yes and also upgrade to a more recent version. 

Can you detail the operations/queries that you are running?

Von meinem iPhone gesendet

**Comment by snig-b** [comment]
We are using basic MERGE - ON CREATE for writing data and MATCH - OPTIONAL MATCH along with UNIONS for reading. 
Nothing too advanced here. I'll move onto the transaction based URLs and also upgrade the version, will update here if it does not fix the problem. 
Thanks

**Comment by chrisvest** [comment]
I'm pretty sure we've fixed multiple problems around "MasterClient214" related things, so I'll close this. Feel free to open another issue if this is still a problem in recent versions.
