### ISSUE TITLE
Build failure - mvn clean install -DfullBuild -Dlicensing.skip

### ISSUE THREAD

**Issue by F-I-D-O** [neo4j/neo4j#7759]
- Neo4j branch: 3.0 and 3.1
- Operating system: Windows 10

I've experienced build failure when building neo4j right after clone with:

`mvn clean install -DfullBuild -Dlicensing.skip`

The failure is in IO module test FileSystemAbstractionInterruptionTest. The message in test log:

> ---
> ## Test set: org.neo4j.io.fs.FileSystemAbstractionInterruptionTest
> 
> Tests run: 34, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.403 sec <<< FAILURE! - in org.neo4j.io.fs.FileSystemAbstractionInterruptionTest
> ch_isOpen[real](org.neo4j.io.fs.FileSystemAbstractionInterruptionTest)  Time elapsed: 0.019 sec  <<< ERROR!
> java.lang.RuntimeException: java.nio.file.FileSystemException: C:\Workspaces\neo4j-custom\neo4j\community\io\target\test-data\org.neo4j.io.fs.FileSystemAbstractionInterruptionTest\9CE79004BCCB8DD617265E761C3C433F\a: Proces nemá přístup k souboru, neboť jej právě využívá  jiný  proces (The process can not access the file because it is being used by another process).
> 
>   at org.neo4j.test.rule.TestDirectory.complete(TestDirectory.java:208)
>   at org.neo4j.test.rule.TestDirectory.access$200(TestDirectory.java:57)
>   at org.neo4j.test.rule.TestDirectory$1.evaluate(TestDirectory.java:113)
>   at org.junit.rules.RunRules.evaluate(RunRules.java:20)
>   at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
>   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
>   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
>   at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
>   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
>   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
>   at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
>   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
>   at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
>   at org.junit.runners.Suite.runChild(Suite.java:128)
>   at org.junit.runners.Suite.runChild(Suite.java:27)
>   at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
>   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
>   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
>   at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
>   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
>   at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
>   at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
>   at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
>   at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
>   at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
>   at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
>   at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
> Caused by: java.nio.file.FileSystemException: C:\Workspaces\neo4j-custom\neo4j\community\io\target\test-data\org.neo4j.io.fs.FileSystemAbstractionInterruptionTest\9CE79004BCCB8DD617265E761C3C433F\a: Proces nem� p��stup k souboru, nebo� jej pr�v� vyu��v� jin� proces.
> 
>   at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
>   at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
>   at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
>   at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
>   at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
>   at java.nio.file.Files.delete(Files.java:1126)
>   at org.neo4j.io.fs.FileUtils.deleteFileWithRetries(FileUtils.java:428)
>   at org.neo4j.io.fs.FileUtils.access$000(FileUtils.java:60)
>   at org.neo4j.io.fs.FileUtils$1.visitFile(FileUtils.java:81)
>   at org.neo4j.io.fs.FileUtils$1.visitFile(FileUtils.java:77)
>   at java.nio.file.Files.walkFileTree(Files.java:2670)
>   at java.nio.file.Files.walkFileTree(Files.java:2742)
>   at org.neo4j.io.fs.FileUtils.deletePathRecursively(FileUtils.java:76)
>   at org.neo4j.io.fs.FileUtils.deleteRecursively(FileUtils.java:71)
>   at org.neo4j.io.fs.DefaultFileSystemAbstraction.deleteRecursively(DefaultFileSystemAbstraction.java:132)
>   at org.neo4j.test.rule.TestDirectory.complete(TestDirectory.java:199)
>   at org.neo4j.test.rule.TestDirectory.access$200(TestDirectory.java:57)
>   at org.neo4j.test.rule.TestDirectory$1.evaluate(TestDirectory.java:113)
>   at org.junit.rules.RunRules.evaluate(RunRules.java:20)
>   at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
>   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
>   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
>   at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
>   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
>   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
>   at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
>   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
>   at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
>   at org.junit.runners.Suite.runChild(Suite.java:128)
>   at org.junit.runners.Suite.runChild(Suite.java:27)
>   at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
>   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
>   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
>   at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
>   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
>   at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
>   at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
>   at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
>   at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
>   at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
>   at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
>   at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
> 
> ch_tryLock[real](org.neo4j.io.fs.FileSystemAbstractionInterruptionTest)  Time elapsed: 0.009 sec  <<< ERROR!
> java.lang.RuntimeException: java.nio.file.FileSystemException: C:\Workspaces\neo4j-custom\neo4j\community\io\target\test-data\org.neo4j.io.fs.FileSystemAbstractionInterruptionTest\961F26929D1D97591F0F108ACAD797A6\a: Proces nem� p��stup k souboru, nebo� jej pr�v� vyu��v� jin� proces.
> 
>   at org.neo4j.test.rule.TestDirectory.complete(TestDirectory.java:208)
>   at org.neo4j.test.rule.TestDirectory.access$200(TestDirectory.java:57)
>   at org.neo4j.test.rule.TestDirectory$1.evaluate(TestDirectory.java:113)
>   at org.junit.rules.RunRules.evaluate(RunRules.java:20)
>   at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
>   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
>   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
>   at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
>   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
>   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
>   at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
>   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
>   at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
>   at org.junit.runners.Suite.runChild(Suite.java:128)
>   at org.junit.runners.Suite.runChild(Suite.java:27)
>   at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
>   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
>   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
>   at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
>   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
>   at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
>   at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
>   at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
>   at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
>   at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
>   at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
>   at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
> Caused by: java.nio.file.FileSystemException: C:\Workspaces\neo4j-custom\neo4j\community\io\target\test-data\org.neo4j.io.fs.FileSystemAbstractionInterruptionTest\961F26929D1D97591F0F108ACAD797A6\a: Proces nem� p��stup k souboru, nebo� jej pr�v� vyu��v� jin� proces.
> 
>   at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
>   at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
>   at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
>   at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
>   at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
>   at java.nio.file.Files.delete(Files.java:1126)
>   at org.neo4j.io.fs.FileUtils.deleteFileWithRetries(FileUtils.java:428)
>   at org.neo4j.io.fs.FileUtils.access$000(FileUtils.java:60)
>   at org.neo4j.io.fs.FileUtils$1.visitFile(FileUtils.java:81)
>   at org.neo4j.io.fs.FileUtils$1.visitFile(FileUtils.java:77)
>   at java.nio.file.Files.walkFileTree(Files.java:2670)
>   at java.nio.file.Files.walkFileTree(Files.java:2742)
>   at org.neo4j.io.fs.FileUtils.deletePathRecursively(FileUtils.java:76)
>   at org.neo4j.io.fs.FileUtils.deleteRecursively(FileUtils.java:71)
>   at org.neo4j.io.fs.DefaultFileSystemAbstraction.deleteRecursively(DefaultFileSystemAbstraction.java:132)
>   at org.neo4j.test.rule.TestDirectory.complete(TestDirectory.java:199)
>   at org.neo4j.test.rule.TestDirectory.access$200(TestDirectory.java:57)
>   at org.neo4j.test.rule.TestDirectory$1.evaluate(TestDirectory.java:113)
>   at org.junit.rules.RunRules.evaluate(RunRules.java:20)
>   at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
>   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
>   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
>   at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
>   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
>   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
>   at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
>   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
>   at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
>   at org.junit.runners.Suite.runChild(Suite.java:128)
>   at org.junit.runners.Suite.runChild(Suite.java:27)
>   at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
>   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
>   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
>   at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
>   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
>   at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
>   at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
>   at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
>   at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
>   at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
>   at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
>   at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

The summary part of build log (full log is attached):

> ---
> 
> Reactor Summary:
> 
> Neo4j ............................................. SUCCESS [41.693s]
> Neo4j - Licensing configuration ................... SUCCESS [2.457s]
> Neo4j - Common .................................... SUCCESS [23.214s]
> Neo4j - Resource interface ........................ SUCCESS [6.939s]
> Neo4j - Collections ............................... SUCCESS [22.718s]
> Neo4j - Unsafe Access ............................. SUCCESS [14.178s]
> Neo4j - Primitive Collections ..................... SUCCESS [1:17.711s]
> Neo4j - Graph Database API ........................ SUCCESS [33.756s]
> Neo4j - IO ........................................ FAILURE [22.133s]
> Neo4j - CSV reading and parsing ................... SKIPPED
> Neo4j - Logging ................................... SKIPPED
> ...

I've also used the process monitor to monitor access to the folder where error occured, but it is only accessed by java.exe.

[log.txt](https://github.com/neo4j/neo4j/files/428357/log.txt)

**Comment by spacecowboy** [comment]
Thanks for the report!

Rest assured, we run the windows build on our CI servers. There is usually no point in reporting failures in the build since we become aware of them internally and fix them in due course.

The latest HEAD is for example experiencing some instabilities at the moment I write this. This might or might not be true tomorrow for instance.
