### ISSUE TITLE
Feature Request: longestSequences() function

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j/neo4j#7760]
This proposed function adds additional subgraph matching that I don't believe Cypher or existing Cypher graph algorithm functions provide, at least not easily.
## longestSequences()

(please rename to something more concise and accurate, I'm crap at naming things)

longestSequences() is meant to take a pattern parameter with a variable-length relationship, and (based on the pattern parameter and the following WHERE clause) return the largest contiguous sequences. This is most useful when we do not have defined start or end nodes for the sequence, only the kind of nodes and relationships that should occur in matched sequences.

This [StackOverflow question](http://stackoverflow.com/questions/39056872/cypher-query-to-return-or-keep-only-the-final-sequence-when-variable-length-rela) is a type that is hard to solve currently with Cypher, yet could be solved easily with longestSequences().

This type of query defines the kind of nodes that should be present in the matched pattern, and the restrictions on the properties of the relationship. Here is the starting attempt so far using Cypher:

```
MATCH p=(a)-[rels:NEXT*]->(b) 
WHERE ALL(n in nodes(p) WHERE n.name in ['graph', 'server' ,'db']) 
AND ALL( r in rels WHERE rels[0]['seqid'] = r.seqid ) 
RETURN p
```

This query returns all possible subsequences that match the predicate, matching a and b to every possible subsequence segment. But from these results, it is very hard to figure out which patterns are only subsequences of larger patterns, and to trim those away to only leave the patterns of longest matching sequences.

Maybe we could do this with some kind of set operation on the collection of nodes() in the pattern, eliminating any patterns where the nodes are subsets of the patterns of other nodes, but that seems costly, and I'm not sure how one would begin to do this with Cypher.

Alternately to improve this kind of query to get the results we want we could add additional predicates on a and b that will define them as logical end nodes of the sequences we're after. However this is non-trivial. 

Let's try tackling matching the b node to the end of a sequence. To be the end node of a sequence, b must meet all of the following: 

a) not have a :NEXT relationship to another node.
b) if there is a :NEXT relationship, it must not have the same seqid as the other relationships in the pattern.
c) if there is a :NEXT relationship with the same seqid, the node it connects to must not have its name in the collection of possible names.

While Neo4j 3.1's planned pattern comprehension would help us out here, in Neo4j 3.0.x and Neo4j 2.3.6 (the version used by the asker of the StackOverflow question) there's some difficulty defining this, as NOT EXISTS() doesn't give us the expression needed to define the above restrictions. Since we don't have access to an EXCLUDE MATCH operation (which would be a great addition to Neo4j) we need to use use an OPTIONAL MATCH and trim results where that optional match exists:

```
WITH ['graph', 'server' ,'db'] as names
MATCH p=(a)-[rels:NEXT*]->(b) 
WHERE ALL(n in nodes(p) WHERE n.name in names) 
AND ALL( r in rels WHERE rels[0]['seqid'] = r.seqid ) 
WITH names, p, a, rels, b
OPTIONAL MATCH (b)-[rel:NEXT]->(c)
WHERE c.name in names
AND rel.seqid = rels[0]['seqid']
WITH p, a, b, c
WHERE c IS NULL
RETURN p, a, b
```

And of course we have to repeat this approach on a to restrict it to matching on sequence start nodes.

longestSequences() is meant to replace this complicated approach, expanding out the matched pattern such that for each pattern returned, a and b will only be matched to the start and end nodes of contiguous sequences instead of on all occurring subsequences.

**Comment by sherfert** [comment]
Adding new features to Cypher should be coordinated by the openCypher group. When the community agrres this is useful, it could become a Cypher Improvement Proposal (CIP). I think @Mats-SX can probably answer questions related to how you can go about and propose a new feature.

**Comment by Mats-SX** [comment]
(Hello Andrew. You probably know this, but I'll type it out for anyone else reading.)

If you want to propose this function as an addition to the (emerging) Cypher standard, the process is to create a [Cypher Improvement Request (CIR)](https://github.com/opencypher/openCypher/blob/master/CIP-PROCESS.adoc#cypher-improvement-requests-cirs) as an issue to this repository: https://github.com/opencypher/openCypher

I would say that it is unlikely that this function will be adopted by Neo4j without having been adopted as part of the standard. However, since Neo4j features user-defined functions (UDFs), you can write it yourself for your application, or submit it to/request it from some well-know open source library with user-defined procedures and functions (f.e. [apoc](https://github.com/neo4j-contrib/neo4j-apoc-procedures)).

**Comment by sherfert** [comment]
Moved: https://github.com/opencypher/openCypher/issues/259
