### ISSUE TITLE
Bolt client authentication error after changing the login user name to anything else than `neo4j`

### ISSUE THREAD

**Issue by florinpatrascu** [neo4j/neo4j#7773]
I installed a clean 3.0.4 instance (community Ed.) and changed the credentials from the default: `neo4j/neo4j`, to: `test/test`. Happily using the server with the browser after that, using the new username/password combination; tried both http and https protocols. A Bolt client however cannot authenticate with the new credentials; I see the following error (excerpt):

```
raise error(metadata.get("message", "INIT failed"))
neo4j.v1.exceptions.Unauthorized: The client is unauthorized due to authentication failure.
```

I discovered that changing the username back to: `neo4j` (using any password), is fixing this issue and I can authenticate with Bolt too, but only if the login username is: `neo4j`.
- Neo4j version: 3.0.1, 3.0.4
- Operating system: OSX
- API/Driver: python/Elixir

Steps to reproduce:
1. install a new server (or delete the `dbms/auth` file when the server is off). Start the server
2. using the browser on `http://localhost:7474`, change the username to something else than `neo4j`
3. the browser session will continue successfully while any attempt to connect using a Bolt client will fail with the authentication error above. The official python Bolt client can be used for this test.
4. stop the server, delete the `dbms/auth`, start the server, and change the username back to: `neo4j`( use any password). Bolt is now authenticating successfully.

Expected: - when I am able to authenticate successfully from a browser, I should be able to connect to the sever from a Bolt client, with the same login credentials, username/password used in the browser.

**Comment by spacecowboy** [comment]
@florinpatrascu there is no way to change the default username from neo4j to anything else in 3.0.4. The browser only asks you to change the password for the default user. So I am not sure how you accomplish step 2 tbh.

**Comment by florinpatrascu** [comment]
Tried to recover my old setup (using now 3.0.5) and I can't reproduce this anymore :( You're right, I can't change the username, only the password.
