### ISSUE TITLE
":play sysinfo" displays tables with no values on the master of a cluster

### ISSUE THREAD

**Issue by fpavageau** [neo4j/neo4j#7806]
When Neo4j is running in HA mode, the `:play sysinfo` command in the browser of the master node displays all tables without any values, like this:

<img width="600" alt="sysinfo-ha-master" src="https://cloud.githubusercontent.com/assets/800088/17961739/dab08f62-6aad-11e6-82e6-9f04f08555b0.png">

This is on a single-node cluster, configured with

``` ini
dbms.mode=HA
ha.server_id=1
ha.initial_hosts=127.0.0.1:5001
ha.host.coordination=127.0.0.1:5001
ha.host.data=127.0.0.1:6001
```

but it's the same on a multi-node cluster. The browser of the slave nodes displays the information correctly, including the HA and cluster parts.

When running in single mode, the same instance also displays the tables correctly:

<img width="600" alt="sysinfo-single" src="https://cloud.githubusercontent.com/assets/800088/17961808/1d88f0d6-6aae-11e6-9643-38a7ca1622c5.png">
# Additional information

**Neo4j version:** 3.0.4 Enterprise
**Operating System:** OS X El Capitan (10.11.6)
**Browser version:** Google Chrome 52.0.2743.116

Using the Chrome Dev Tools, an error can be seen in the console:

```
TypeError: Cannot read property 'length' of undefined
    at cbdd8ec2.scripts.js:9
    at processQueue (97ea0b85.components.js:11)
    at 97ea0b85.components.js:11
    at Scope.$eval (97ea0b85.components.js:11)
    at Scope.$digest (97ea0b85.components.js:11)
    at Scope.$apply (97ea0b85.components.js:11)
    at HTMLBodyElement.<anonymous> (cbdd8ec2.scripts.js:1)
    at HTMLBodyElement.dispatch (97ea0b85.components.js:3)
    at HTMLBodyElement.elemData.handle (97ea0b85.components.js:3)
```

The problem was mentioned in #7066 in May (on 3.0.0), with a comment saying it would be fixed in the next release, but it's still present in 3.0.4.

**Comment by spacecowboy** [comment]
thanks for the report

**Comment by oskarhane** [comment]
This is fixed since then. Closing.
