### ISSUE TITLE
NEO4J_PIDFILE not populated with `neo4j console`

### ISSUE THREAD

**Issue by wuntee** [neo4j/neo4j#7833]
## Example bug report

When starting neo4j via `neo4j console >> some_log_file` a NEO4J_PIDFILE is not populated and thus `neo4j status` will return "neo4j is not running"
### Steps to reproduce

~/Desktop/tmp|⇒ neo4j console &
[1] 60638
Starting Neo4j.
2016-08-30 20:22:24.808+0000 INFO  Starting...
2016-08-30 20:22:25.546+0000 INFO  Bolt enabled on localhost:7687.
2016-08-30 20:22:29.295+0000 INFO  Started.
2016-08-30 20:22:30.724+0000 INFO  Remote interface available at http://localhost:7474/
~/Desktop/tmp|⇒ neo4j status
Neo4j is not running
### Expected behavior

It should show that neo4j is running
### Actual behavior

It shows "neo4j is not running"

**Comment by spacecowboy** [comment]
It is not intended for that use case. the neo4j script is a mix between init script and executable. the start/stop/status are meant to be used as init script, whereas console is used to execute neo4j directly. (yes, this is _not_ optimal at all).

In the future, we will split these into two very separate things and the pidfile will go away entirely in that case as well.

**Comment by wuntee** [comment]
`neo4j status` says "neo4j is not running" when it actually is. It would be helpful to make that more clear that it may be, but just in console mode. Caused a bug in one of our deploy scripts.

**Comment by spacecowboy** [comment]
do not rely on `neo4j status` when running `neo4j console`. `neo4j status` only works if you use `neo4j start`.
