### ISSUE TITLE
Cypher: Allow comparison between arrays of the same type

### ISSUE THREAD

**Issue by ArenaSource** [neo4j/neo4j#784]
It's not a bug but it would be nice to be able to compare/order by property arrays.

CREATE (:TestLabel {name:['A','B']}), (:TestLabel {name:['A','C']})

MATCH n:TestLabel RETURN n ORDER BY n.name

Error: Don't know how to compare that. Left: [Ljava.lang.String;@7fd77ab5; Right: [Ljava.lang.String;@1bb942a5

CREATE (n:LabelInt {data:[0,2]})

MATCH n:LabelInt WHERE n.data > [0,1] RETURN n

Error: Don't know how to compare that. Left: [J@3456d1f5; Right: List(0, 1)

**Comment by chrisvest** [comment]
Looks like this is fixed.
