### ISSUE TITLE
neo-shell readonly model can't work with index

### ISSUE THREAD

**Issue by fudy** [neo4j/neo4j#785]
I modified the demo EmbeddedNeo4jWithIndexing.java . Comment all shutdown() method
after do it, I open the database by neo4j-shell -readonly,then I run 
start n=node:nodes("*:*") return n;
I get 0 rows
if I open the database without -readonly ,and run the command above,it successed!
I am very confused about it
I tried 1.8.2 and 1.9

**Comment by jakewins** [comment]
Unable to replicate on 2.3.1. If this issue remains, please don't hesitate to re-open, and if so, please provide your `neo4j.properties` configuration as well as the `messages.log` file that you'll find in the database directory.
