### ISSUE TITLE
Queries with DISTINCT, aliases, and OPTIONAL MATCH fail.

### ISSUE THREAD

**Issue by arturosevilla** [neo4j/neo4j#7962]
I have a system with some working queries. I tried upgrading to 3.0, but some queries started misbehaving with an ExecutionFailed error. I narrowed the error to a distinct clauses that are being used in conjunction with variable aliases and an OPTIONAL MATCH.

**Neo4j Version:** Neo4j Community Edition 3.0.4
**Operating System:** Windows Server 2008 R2 Enterprise and Windows 7
**API:** HTTP
### Steps to reproduce
- Download Neo4j Community Edition 3.0.4
- Create a graph database and populate it with the following data:

`CREATE (node1:NodeA), (node2:NodeB)`
- Execute the following query (through the browser shell is ok):

```
match (n1:NodeA), (n2:NodeB)
optional match (n1)-[:RELATION]->(n3)
with n1 as alias, n1, n2, n3
return distinct n1, n2, alias, n3
```
- You will see that the query failed with `Neo.DatabaseError.Statement.ExecutionFailed` message, and the following message will be displayed: `(ArrayBuffer(Node[0], Node[1], Node[0]),null) (of class scala.Tuple2)`

However if you execute the following queries they work as expected:

```
match (n1:NodeA), (n2:NodeB)
optional match (n1)-[:RELATION]->(n3)
with n1 as alias, n1, n2, n3
return distinct n1, n2, alias
```

```
match (n1:NodeA), (n2:NodeB)
optional match (n1)-[:RELATION]->(n3)
with n1 as alias, n1, n2, n3
return distinct n1, n2, n3
```

```
match (n1:NodeA), (n2:NodeB)
optional match (n1)-[:RELATION]->(n3)
with n1 as alias, n1, n2, n3
return n1, n2, n3, alias
```

```
match (n1:NodeA), (n2:NodeB)
optional match (n1)-[:RELATION]->(n3)
with n1 as alias, n1, n2, n3
return distinct id(n1), id(n2), id(alias), id(coalesce(n3, n1))
```

The first one is missing the n3 from the optional match, the second is missing the alias, the third one retrieves all the variables but does not have a distinct, while the fourth is just getting the `id()`s of the nodes.

I expect the troublesome query to work as the aforementioned query that does not have a distinct.

**Comment by jexp** [comment]
Can you try to verify it on 3.0.6

It should be fixed there. Sorry for the inconvenience.

**Comment by arturosevilla** [comment]
I will be closing the issue as I have confirmed that it works on 3.0.6.

Thanks.
