### ISSUE TITLE
Missing docs for new config dbms.rest.transaction.idle_timeout

### ISSUE THREAD

**Issue by bradnussbaum** [neo4j/neo4j#7965]
New config 'dbms.rest.transaction.idle_timeout' is not documented. An deprecated config is not updated to indicate deprecation:
http://neo4j.com/docs/operations-manual/beta/reference/#config_dbms.transaction_timeout
- Neo4j version: 3.1.0-M09
- Operating system: Ubuntu 16.04

2016-09-17 18:38:19.614+0000 WARN  WARNING! Deprecated configuration options used. See manual for details
2016-09-17 18:38:19.616+0000 WARN  dbms.transaction_timeout has been replaced with dbms.rest.transaction.idle_timeout.

**Comment by spacecowboy** [comment]
The setting is (now) documented: https://neo4j.com/docs/operations-manual/current/reference/configuration-settings/ (and the old one is not)

The setting is migrated at runtime (which prints the warning)

Closing as fixed.
