### ISSUE TITLE
FILTER operation applied to paths does not return a correct result

### ISSUE THREAD

**Issue by ramshorn** [neo4j/neo4j#7977]
In the example below, the FILTER operation applied to paths does not return a correct result. Or am I getting it wrong?

**Neo4j Version:** 3.0.4
**Operating System:** Windows 10
**API:** Browser (Google Chrome) / Cypher
### Steps to reproduce
1. Create the graph "SIL" with the Cypher script below. This represents a subset inclusion lattice with the basic sets a,b,c,d,e,f. The lattice has 63 nodes and 186 relationships (the empty set is omitted from the lattice)
2. Compute the complement of the :abcd sub-lattice with:
   
   // All nodes and relationships in the lattice
   MATCH n=(:abcdef)-->(l01)-->(l02)-->(l03)-->(l04)-->(l05)
   // All nodes in the downset of :abcd
   MATCH p=(:abcd)-->(l11)-->(l12)-->(l13)
   // Get those nodes that are not in the downset of :abcd
   RETURN FILTER (x IN nodes(n) WHERE NOT (x IN nodes(p)))
### Expected behavior

Return all nodes and relationships that do not belong to the :abcd sub-lattice
### Actual behavior

All nodes except the upper bound of the complete lattice (:abcdef) and their relationships are returned. The computation takes on the order of a minute on a Lenovo T400s.
### Cypher statements to create "SIL"

// All n = 6 elements in one set
Create (abcdef:abcdef {headline:'a,b,c,d,e,f'})

 // n-1 = 5 elements per set
 Create (bcdef:bcdef {headline:'b,c,d,e,f'})
 Create (acdef:acdef {headline:'a,c,d,e,f'})
 Create (abdef:abdef {headline:'a,b,d,e,f'})
 Create (abcef:abcef {headline:'a,b,c,e,f'})
 Create (abcdf:abcdf {headline:'a,b,c,d,f'})
 Create (abcde:abcde {headline:'a,b,c,d,e'})
 // superset relationships level 6 - level 5
 CREATE (abcdef) - [:superset] ->(bcdef)
 CREATE (abcdef) - [:superset] ->(acdef)
 CREATE (abcdef) - [:superset] ->(abdef)
 CREATE (abcdef) - [:superset] ->(abcef)
 CREATE (abcdef) - [:superset] ->(abcdf)
 CREATE (abcdef) - [:superset] ->(abcde)

 // n-2 = 4 elements per set
 Create (cdef:cdef {headline:'c,d,e,f'})
 Create (bdef:bdef {headline:'b,d,e,f'})
 Create (bcef:bcef {headline:'b,c,e,f'})
 Create (bcdf:bcdf {headline:'b,c,d,f'})
 Create (bcde:bcde {headline:'b,c,d,e'})
 Create (adef:adef {headline:'a,d,e,f'})
 Create (acef:acef {headline:'a,c,e,f'})
 Create (acdf:acdf {headline:'a,c,d,f'})
 Create (acde:acde {headline:'a,c,d,e'})
 Create (abef:abef {headline:'a,b,e,f'})
 Create (abdf:abdf {headline:'a,b,d,f'})
 Create (abde:abde {headline:'a,b,d,e'})
 Create (abcf:abcf {headline:'a,b,c,f'})
 Create (abce:abce {headline:'a,b,c,e'})
 Create (abcd:abcd {headline:'a,b,c,d'})
 // superset relationships level 5 to level 4
 CREATE (bcdef) - [:superset] ->(cdef)
 CREATE (bcdef) - [:superset] ->(bdef)
 CREATE (bcdef) - [:superset] ->(bcef)
 CREATE (bcdef) - [:superset] ->(bcdf)
 CREATE (bcdef) - [:superset] ->(bcde)
 CREATE (acdef) - [:superset] ->(cdef)
 CREATE (acdef) - [:superset] ->(adef)
 CREATE (acdef) - [:superset] ->(acef)
 CREATE (acdef) - [:superset] ->(acdf)
 CREATE (acdef) - [:superset] ->(acde)
 CREATE (abdef) - [:superset] ->(bdef)
 CREATE (abdef) - [:superset] ->(adef)
 CREATE (abdef) - [:superset] ->(abef)
 CREATE (abdef) - [:superset] ->(abdf)
 CREATE (abdef) - [:superset] ->(abde)
 CREATE (abcef) - [:superset] ->(bcef)
 CREATE (abcef) - [:superset] ->(acef)
 CREATE (abcef) - [:superset] ->(abef)
 CREATE (abcef) - [:superset] ->(abcf)
 CREATE (abcef) - [:superset] ->(abce)
 CREATE (abcdf) - [:superset] ->(bcdf)
 CREATE (abcdf) - [:superset] ->(acdf)
 CREATE (abcdf) - [:superset] ->(abdf)
 CREATE (abcdf) - [:superset] ->(abcf)
 CREATE (abcdf) - [:superset] ->(abcd)
 CREATE (abcde) - [:superset] ->(bcde)
 CREATE (abcde) - [:superset] ->(acde)
 CREATE (abcde) - [:superset] ->(abde)
 CREATE (abcde) - [:superset] ->(abce)
 CREATE (abcde) - [:superset] ->(abcd)

 // n-3 = 3 elements per set
 Create (def:def {headline:'d,e,f'})
 Create (cef:cef {headline:'c,e,f'})
 Create (cdf:cdf {headline:'c,d,f'})
 Create (cde:cde {headline:'c,d,e'})
 Create (bef:bef {headline:'b,e,f'})
 Create (bdf:bdf {headline:'b,d,f'})
 Create (bde:bde {headline:'b,d,e'})
 Create (bcf:bcf {headline:'b,c,f'})
 Create (bce:bce {headline:'b,c,e'})
 Create (bcd:bcd {headline:'b,c,d'})
 Create (aef:aef {headline:'a,e,f'})
 Create (adf:adf {headline:'a,d,f'})
 Create (ade:ade {headline:'a,d,e'})
 Create (acf:acf {headline:'a,c,f'})
 Create (ace:ace {headline:'a,c,e'})
 Create (acd:acd {headline:'a,c,d'})
 Create (abf:abf {headline:'a,b,f'})
 Create (abe:abe {headline:'a,b,e'})
 Create (abd:abd {headline:'a,b,d'})
 Create (abc:abc {headline:'a,b,c'})
 // superset relationships level 4 to level 3
 Create (cdef) - [:superset] ->(def)
 Create (cdef) - [:superset] ->(cef)
 Create (cdef) - [:superset] ->(cdf)
 Create (cdef) - [:superset] ->(cde) 
 Create (bdef) - [:superset] ->(def)
 Create (bdef) - [:superset] ->(bef)
 Create (bdef) - [:superset] ->(bdf)
 Create (bdef) - [:superset] ->(bde)
 Create (bcef) - [:superset] ->(cef)
 Create (bcef) - [:superset] ->(bef)
 Create (bcef) - [:superset] ->(bcf)
 Create (bcef) - [:superset] ->(bce)
 Create (bcdf) - [:superset] ->(cdf)
 Create (bcdf) - [:superset] ->(bdf)
 Create (bcdf) - [:superset] ->(bcf)
 Create (bcdf) - [:superset] ->(bcd)
 Create (bcde) - [:superset] ->(cde)
 Create (bcde) - [:superset] ->(bde)
 Create (bcde) - [:superset] ->(bce)
 Create (bcde) - [:superset] ->(bcd)
 Create (adef) - [:superset] ->(def)
 Create (adef) - [:superset] ->(aef)
 Create (adef) - [:superset] ->(adf)
 Create (adef) - [:superset] ->(ade)
 Create (acef) - [:superset] ->(cef)
 Create (acef) - [:superset] ->(aef)
 Create (acef) - [:superset] ->(acf)
 Create (acef) - [:superset] ->(ace)
 Create (acdf) - [:superset] ->(cdf)
 Create (acdf) - [:superset] ->(adf)
 Create (acdf) - [:superset] ->(acf)
 Create (acdf) - [:superset] ->(acd)
 Create (acde) - [:superset] ->(cde)
 Create (acde) - [:superset] ->(ade)
 Create (acde) - [:superset] ->(ace)
 Create (acde) - [:superset] ->(acd)
 Create (abef) - [:superset] ->(bef)
 Create (abef) - [:superset] ->(aef)
 Create (abef) - [:superset] ->(abf)
 Create (abef) - [:superset] ->(abe)
 Create (abdf) - [:superset] ->(bdf)
 Create (abdf) - [:superset] ->(adf)
 Create (abdf) - [:superset] ->(abf)
 Create (abdf) - [:superset] ->(abd)
 Create (abde) - [:superset] ->(bde)
 Create (abde) - [:superset] ->(ade)
 Create (abde) - [:superset] ->(abe)
 Create (abde) - [:superset] ->(abd)
 Create (abcf) - [:superset] ->(bcf)
 Create (abcf) - [:superset] ->(acf)
 Create (abcf) - [:superset] ->(abf)
 Create (abcf) - [:superset] ->(abc)
 Create (abce) - [:superset] ->(bce)
 Create (abce) - [:superset] ->(ace)
 Create (abce) - [:superset] ->(abe)
 Create (abce) - [:superset] ->(abc)
 Create (abcd) - [:superset] ->(bcd)
 Create (abcd) - [:superset] ->(acd)
 Create (abcd) - [:superset] ->(abd)
 Create (abcd) - [:superset] ->(abc)

 // n-4 = 2 elements per set
 Create (ef:ef {headline:'e,f'})
 Create (df:df {headline:'d,f'})
 Create (de:de {headline:'d,e'})
 Create (cf:cf {headline:'c,f'})
 Create (ce:ce {headline:'c,e'})
 Create (cd:cd {headline:'c,d'})
 Create (bf:bf {headline:'b,f'})
 Create (be:be {headline:'b,e'})
 Create (bd:bd {headline:'b,d'})
 Create (bc:bc {headline:'b,c'})
 Create (af:af {headline:'a,f'})
 Create (ae:ae {headline:'a,e'})
 Create (ad:ad {headline:'a,d'})
 Create (ac:ac {headline:'a,c'})
 Create (ab:ab {headline:'a,b'})
 // Superset relationships level 3 to level 2
 Create (def) - [:superset] -> (ef)
 Create (def) - [:superset] -> (df)
 Create (def) - [:superset] -> (de)
 Create (cef) - [:superset] -> (ef)
 Create (cef) - [:superset] -> (cf)
 Create (cef) - [:superset] -> (ce)
 Create (cdf) - [:superset] -> (df)
 Create (cdf) - [:superset] -> (cf)
 Create (cdf) - [:superset] -> (cd)
 Create (cde) - [:superset] -> (de)
 Create (cde) - [:superset] -> (ce)
 Create (cde) - [:superset] -> (cd)
 Create (bef) - [:superset] -> (ef)
 Create (bef) - [:superset] -> (bf)
 Create (bef) - [:superset] -> (be)
 Create (bdf) - [:superset] -> (df)
 Create (bdf) - [:superset] -> (bf)
 Create (bdf) - [:superset] -> (bd)
 Create (bde) - [:superset] -> (de)
 Create (bde) - [:superset] -> (be)
 Create (bde) - [:superset] -> (bd)
 Create (bcf) - [:superset] -> (cf)
 Create (bcf) - [:superset] -> (bf)
 Create (bcf) - [:superset] -> (bc)
 Create (bce) - [:superset] -> (ce)
 Create (bce) - [:superset] -> (be)
 Create (bce) - [:superset] -> (bc)
 Create (bcd) - [:superset] -> (cd)
 Create (bcd) - [:superset] -> (bd)
 Create (bcd) - [:superset] -> (bc)
 Create (aef) - [:superset] -> (ef)
 Create (aef) - [:superset] -> (af)
 Create (aef) - [:superset] -> (ae)
 Create (adf) - [:superset] -> (df)
 Create (adf) - [:superset] -> (af)
 Create (adf) - [:superset] -> (ad)
 Create (ade) - [:superset] -> (de)
 Create (ade) - [:superset] -> (ae)
 Create (ade) - [:superset] -> (ad)
 Create (acf) - [:superset] -> (cf)
 Create (acf) - [:superset] -> (af)
 Create (acf) - [:superset] -> (ac)
 Create (ace) - [:superset] -> (ce)
 Create (ace) - [:superset] -> (ae)
 Create (ace) - [:superset] -> (ac)
 Create (acd) - [:superset] -> (cd)
 Create (acd) - [:superset] -> (ad)
 Create (acd) - [:superset] -> (ac)
 Create (abf) - [:superset] -> (bf)
 Create (abf) - [:superset] -> (af)
 Create (abf) - [:superset] -> (ab)
 Create (abe) - [:superset] -> (be)
 Create (abe) - [:superset] -> (ae)
 Create (abe) - [:superset] -> (ab)
 Create (abd) - [:superset] -> (bd)
 Create (abd) - [:superset] -> (ad)
 Create (abd) - [:superset] -> (ab)
 Create (abc) - [:superset] -> (bc)
 Create (abc) - [:superset] -> (ac)
 Create (abc) - [:superset] -> (ab)

 // n-(n-1) = 1 element per set
 Create (a:a {headline:'a'})
 Create (b:b {headline:'b'})
 Create (c:c {headline:'c'})
 Create (d:d {headline:'d'})
 Create (e:e {headline:'e'})
 Create (f:f {headline:'f'})
 // Superset relationships level 3 to level 2
 Create (ef) - [:superset] -> (f)
 Create (ef) - [:superset] -> (e)
 Create (df) - [:superset] -> (f)
 Create (df) - [:superset] -> (d)
 Create (de) - [:superset] -> (e)
 Create (de) - [:superset] -> (d)
 Create (cf) - [:superset] -> (f)
 Create (cf) - [:superset] -> (c)
 Create (ce) - [:superset] -> (e)
 Create (ce) - [:superset] -> (c)
 Create (cd) - [:superset] -> (d)
 Create (cd) - [:superset] -> (c)
 Create (bf) - [:superset] -> (f)
 Create (bf) - [:superset] -> (b)
 Create (be) - [:superset] -> (e)
 Create (be) - [:superset] -> (b)
 Create (bd) - [:superset] -> (d)
 Create (bd) - [:superset] -> (b)
 Create (bc) - [:superset] -> (c)
 Create (bc) - [:superset] -> (b)
 Create (af) - [:superset] -> (f)
 Create (af) - [:superset] -> (a)
 Create (ae) - [:superset] -> (e)
 Create (ae) - [:superset] -> (a)
 Create (ad) - [:superset] -> (d)
 Create (ad) - [:superset] -> (a)
 Create (ac) - [:superset] -> (c)
 Create (ac) - [:superset] -> (a)
 Create (ab) - [:superset] -> (b)
 Create (ab) - [:superset] -> (a)

**Comment by spacecowboy** [comment]
Thanks for you report.

Unfortunately, your cypher statements are not complete in order to reproduce the problem.

For example, no statement creates any nodes of type `:abcdef`, which is illustrated by the fact that this returns nothing:

```
MATCH (n:abcdef) RETURN n;
```

I also wonder if your query should not be written like this instead:

```
MATCH n=(:abcdef)-->(l01)-->(l02)-->(l03)-->(l04)-->(l05)
WITH n
MATCH p=(:abcd)-->(l11)-->(l12)-->(l13)
RETURN FILTER (x IN nodes(n) WHERE NOT x IN nodes(p));
```

**Comment by ramshorn** [comment]
Thank you for the comment. The node of type `:abcdef` was missing to a copy error; I have fixed this.

``` javascript
Added 63 labels, created 63 nodes, set 63 properties, created 186 relationships, 
statement executed in 172 ms.
```

Running the query you propose does not give me the complement set I am looking for and apparently returns many duplicates. The query also takes on the order of a few minutes; the 6070ms given below are misleading.

``` javascript
Returned 17280 rows in 6070 ms, displaying first 1000 rows.
```

I realize I have to dig deeper into the manuals but any pointer / trick is appreciated.

**Comment by spacecowboy** [comment]
Well your filtering approach is a O(n²) operation, so it will become time-consuming very fast.

Will try again with your changes.

**Comment by spacecowboy** [comment]
@ramshorn thanks for the correction. I was able to figure it out now.

## What you actually want to do

This is the cypher that you actually want to run (change the 2 to the number you are interested in)

```
MATCH p=(:abcdef)-[*2]->()
RETURN p
```

This means grab all paths starting from `:abcdef` nodes going out 2 relations deep. You will also find that this query is lightning fast.

Results:

```
(:abcdef {headline: "a,b,c,d,e,f"})-[:superset]->(:bcdef {headline: "b,c,d,e,f"})<-[:superset]-(:cdef {headline: "c,d,e,f"})
(:abcdef {headline: "a,b,c,d,e,f"})-[:superset]->(:bcdef {headline: "b,c,d,e,f"})<-[:superset]-(:bdef {headline: "b,d,e,f"})
(:abcdef {headline: "a,b,c,d,e,f"})-[:superset]->(:bcdef {headline: "b,c,d,e,f"})<-[:superset]-(:bcef {headline: "b,c,e,f"})
(:abcdef {headline: "a,b,c,d,e,f"})-[:superset]->(:bcdef {headline: "b,c,d,e,f"})<-[:superset]-(:bcdf {headline: "b,c,d,f"})
(:abcdef {headline: "a,b,c,d,e,f"})-[:superset]->(:bcdef {headline: "b,c,d,e,f"})<-[:superset]-(:bcde {headline: "b,c,d,e"})
(:abcdef {headline: "a,b,c,d,e,f"})-[:superset]->(:acdef {headline: "a,c,d,e,f"})<-[:superset]-(:cdef {headline: "c,d,e,f"})
(:abcdef {headline: "a,b,c,d,e,f"})-[:superset]->(:acdef {headline: "a,c,d,e,f"})<-[:superset]-(:adef {headline: "a,d,e,f"})
(:abcdef {headline: "a,b,c,d,e,f"})-[:superset]->(:acdef {headline: "a,c,d,e,f"})<-[:superset]-(:acef {headline: "a,c,e,f"})
(:abcdef {headline: "a,b,c,d,e,f"})-[:superset]->(:acdef {headline: "a,c,d,e,f"})<-[:superset]-(:acdf {headline: "a,c,d,f"})
(:abcdef {headline: "a,b,c,d,e,f"})-[:superset]->(:acdef {headline: "a,c,d,e,f"})<-[:superset]-(:acde {headline: "a,c,d,e"})
(:abcdef {headline: "a,b,c,d,e,f"})-[:superset]->(:abdef {headline: "a,b,d,e,f"})<-[:superset]-(:adef {headline: "a,d,e,f"})
(:abcdef {headline: "a,b,c,d,e,f"})-[:superset]->(:abdef {headline: "a,b,d,e,f"})<-[:superset]-(:bdef {headline: "b,d,e,f"})
(:abcdef {headline: "a,b,c,d,e,f"})-[:superset]->(:abdef {headline: "a,b,d,e,f"})<-[:superset]-(:abdf {headline: "a,b,d,f"})
(:abcdef {headline: "a,b,c,d,e,f"})-[:superset]->(:abdef {headline: "a,b,d,e,f"})<-[:superset]-(:abef {headline: "a,b,e,f"})
(:abcdef {headline: "a,b,c,d,e,f"})-[:superset]->(:abdef {headline: "a,b,d,e,f"})<-[:superset]-(:abde {headline: "a,b,d,e"})
(:abcdef {headline: "a,b,c,d,e,f"})-[:superset]->(:abcef {headline: "a,b,c,e,f"})<-[:superset]-(:bcef {headline: "b,c,e,f"})
(:abcdef {headline: "a,b,c,d,e,f"})-[:superset]->(:abcef {headline: "a,b,c,e,f"})<-[:superset]-(:abef {headline: "a,b,e,f"})
(:abcdef {headline: "a,b,c,d,e,f"})-[:superset]->(:abcef {headline: "a,b,c,e,f"})<-[:superset]-(:acef {headline: "a,c,e,f"})
(:abcdef {headline: "a,b,c,d,e,f"})-[:superset]->(:abcef {headline: "a,b,c,e,f"})<-[:superset]-(:abce {headline: "a,b,c,e"})
(:abcdef {headline: "a,b,c,d,e,f"})-[:superset]->(:abcef {headline: "a,b,c,e,f"})<-[:superset]-(:abcf {headline: "a,b,c,f"})
(:abcdef {headline: "a,b,c,d,e,f"})-[:superset]->(:abcdf {headline: "a,b,c,d,f"})<-[:superset]-(:acdf {headline: "a,c,d,f"})
(:abcdef {headline: "a,b,c,d,e,f"})-[:superset]->(:abcdf {headline: "a,b,c,d,f"})<-[:superset]-(:bcdf {headline: "b,c,d,f"})
(:abcdef {headline: "a,b,c,d,e,f"})-[:superset]->(:abcdf {headline: "a,b,c,d,f"})<-[:superset]-(:abcf {headline: "a,b,c,f"})
(:abcdef {headline: "a,b,c,d,e,f"})-[:superset]->(:abcdf {headline: "a,b,c,d,f"})<-[:superset]-(:abdf {headline: "a,b,d,f"})
(:abcdef {headline: "a,b,c,d,e,f"})-[:superset]->(:abcdf {headline: "a,b,c,d,f"})<-[:superset]-(:abcd {headline: "a,b,c,d"})
(:abcdef {headline: "a,b,c,d,e,f"})-[:superset]->(:abcde {headline: "a,b,c,d,e"})<-[:superset]-(:bcde {headline: "b,c,d,e"})
(:abcdef {headline: "a,b,c,d,e,f"})-[:superset]->(:abcde {headline: "a,b,c,d,e"})<-[:superset]-(:abce {headline: "a,b,c,e"})
(:abcdef {headline: "a,b,c,d,e,f"})-[:superset]->(:abcde {headline: "a,b,c,d,e"})<-[:superset]-(:abcd {headline: "a,b,c,d"})
(:abcdef {headline: "a,b,c,d,e,f"})-[:superset]->(:abcde {headline: "a,b,c,d,e"})<-[:superset]-(:acde {headline: "a,c,d,e"})
(:abcdef {headline: "a,b,c,d,e,f"})-[:superset]->(:abcde {headline: "a,b,c,d,e"})<-[:superset]-(:abde {headline: "a,b,d,e"})
```

## Why your original query didn't work

The problem with your original query was that the FILTER operation was not actually filtering anything.  It was slow because it was indeed doing a n² iteration of all nodes.

Essentially, the `x` in your filter statement was referring to a path, not a node. So there was no way it was going to return the right result.

**Comment by ramshorn** [comment]
Thanks but what I really want is not finding all nodes one or two hops away from a given node. 

I want, given a subset inclusion lattice of 6 elements a, b, c, d, e, f, all nodes that cannot be reached from the node that represents the subset {a,b,c,d}. Please see https://en.wikipedia.org/wiki/Lattice_(order) for the structure of lattices.

I switched to the `-[*]->` syntax (thanks!) and reduced the size of the sets I use to continue looking for the proper CYPHER query. The correct set of operations should be linear in the number of nodes and relations but I can't find the proper way to do this in CYPHER. My impression is that I don't use CYPHER in the way it is intended to be used.

As a simpler example below there is computing the intersection of two down sets. Again, I would like to find CYPHER operations to do this in linear time. 

``` javascript
// Each set in the subset inclusion lattice corresponds to a node
// Subsets are linked via the :superset relationship
// A down set is represented as a collection of paths that starts from the node that represents its
// least upper bound 
MATCH p=(:bcd)-[*]->()  // The down set of {b,c,d} as collection of paths
MATCH q=(:cde)-[*]->()  // The down set of {c,d,e} as collection of paths
 // Find the nodes representing the sets in the intersection of the down sets of {b,c,d} and {c,d,e}
RETURN FILTER (x IN nodes(p) WHERE x IN nodes(q))
```

**Comment by spacecowboy** [comment]
I can recommend that you read up on Cypher a bit:

https://neo4j.com/docs/cypher-refcard/current/
https://neo4j.com/docs/developer-manual/current/cypher/

An intersection is equivalent to a `UNION`, so your query is just this:

```
       MATCH p=(:bcd)-[*]->()
       RETURN p
       UNION
       MATCH p=(:cde)-[*]->()
       RETURN p;
```

**Comment by spacecowboy** [comment]
@ramshorn Does this query answer your original question?

```
MATCH p=(:abcdef)-[*]->()
WHERE NONE(n IN NODES(p) WHERE ANY(l IN LABELS(n) WHERE l = "abcd"))
RETURN p;
```

**Comment by ramshorn** [comment]
@spacecowboy Thank you for the links (which I have been looking at) and for your patience. I realise this is not a neo4j issue in the sense of a defect but my lack of understanding. Thank you again for your time and help.

`tl;dr`
Let's use the standard notions of union and intersection, provided e.g. in https://en.wikipedia.org/wiki/Set_(mathematics). Take two sets {a,b,c} and {c,d,e}. The union is {a,b,c,d,e},  the intersection is {c}.

The query directly above does not answer the original question. Instead, it returns all nodes except the one labelled "abcd". 

The original question is to find all nodes that do not belong to the down set of "abcd". In other words, find all the nodes that cannot be reached from node "abcd" by navigating the directed `-[:superset]->` relationships. These turn out to be all nodes that do not contain any of {a, b, c, d} in their labels (or types or headlines; I have encoded the sets redundantly in various ways). Please note that I am trying to query the graph and find node patterns in terms of lattice relationships, not in terms of node labels, types, or properties. Those latter ones are only used to identify the starting points for pattern queries.

**Comment by spacecowboy** [comment]
@ramshorn correct, got confused about terminology for a second.

But your original query is answered I believe. Your lattice is just a tree, and the query returns the entire tree _except_ for the the sub-tree(s) rooted in the `:abcd` node(s). Slightly better output is achieved through this query:

```
MATCH p=(root:abcdef)-->(l01)-->(l02)-->(l03)-->(l04)-->(l05)
WHERE NONE( x IN NODES(p) WHERE 'abcd' IN LABELS(x) )
RETURN p;
```

All paths except those going through `abcd` nodes are returned.

In case it's still not what you are looking for, I recommend you ask the question on http://stackoverflow.com/questions/tagged/neo4j . You are likely to get a better response there.
