### ISSUE TITLE
Neo4j throws DatabaseException and stack trace

### ISSUE THREAD

**Issue by rationalism** [neo4j/neo4j#7983]
- Neo4j version: 3.0.5 Enterprise
- Operating system: Ubuntu 14.04.4 LTS
- API/Driver: neo4j-java-driver 1.0.5

Query: MATCH (a) WHERE ID(a) = {id} MERGE (b:`email-addr_user_60257` {`val`: {v}}) CREATE (a)-[r:`email-addr` {src3: {cnt}}]->(b)

This query caused a DatabaseException in the Java driver, with the error message: Stack trace: org.neo4j.driver.v1.exceptions.DatabaseException: An unexpected failure occurred, see details in the database logs, reference number ef52d97f-c326-4043-9e9e-6fb02a842f17.

Here's the stack trace in debug.log:

https://gist.github.com/rationalism/374958231d436734c9e6374b878eb0b1

This looked vaguely similar to this issue (https://groups.google.com/forum/#!topic/neo4j/aubHjERXVpk), so I ran a consistency check on the database, and the output seemed to be fine.

**Comment by spacecowboy** [comment]
Thanks for the report.

Despite what the consistency checker tells you, you do indeed seem to have a corrupt store. So I'd say the driver is doing the right thing erroring out here.

**Comment by rationalism** [comment]
Huh. Well, I don't think this error has happened again since I posted this a week ago, so maybe the inconsistent bits have just been deleted since then.

**Comment by rationalism** [comment]
I think I found what the inconsistency was - an index seemed to be having problems when some of the values it was indexing were very long strings (> ~100 KB). I dropped and re-created the index, and I haven't seen any problems since then, so closing this out.

**Comment by spacecowboy** [comment]
@rationalism interesting. were you able to recreate the problem consistently? If so, I'd say it's a bug with the indexing. Feel free to open another issue for that problem if it happens again.
