### ISSUE TITLE
Hardcoded path in the webadmin data browser

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#80]
@amergin: 'As discussed on the google groups (https://groups.google.com/forum/?fromgroups#!topic/neo4j/oGEb5AIY6cM), it seems that there is a hard-coded path on the webadmin data browser tab:

Consider the following case:

1) Neo4j instance is running on a remote server, localhost port 7474. I created a ssh tunnel, mapping my workstation port 9090 to the remote server localhost port 7474 by issuing ssh -L 9090:localhost:7474 user@server.

2. neo4j-server.properties has the following settings:
org.neo4j.server.webserver.address=localhost
org.neo4j.server.webserver.port=7474
org.neo4j.server.webadmin.data.uri=/ASDF/db/data/
org.neo4j.server.webadmin.management.uri=/ASDF/db/manage/

3. When I open the webadmin front page on my workstation at http://localhost:9090/webadmin, I see in Firebug that ajax calls are made to various paths including http://localhost:9090/ASDF/db/data/ & http://localhost:9090/ASDF/db/manage. These calls yield normal responses.

4. I open the data browser tab. To get the root node, the app makes an ajax call to http://localhost:9090/db/data/node/0?_=1342169326640 which yields 404 (because ASDF is not in the path). If I try to search for node 123, it makes an ajax call to http://localhost:9090/db/data/node/123?_=1342169335448, again 404. See http://i.imgur.com/Hajo7.png.

Why is this wrong path used in the call and why is it only seen in the data browser tab? I tried two browsers and cleared the cache beforehand. I'm using Enterprise 1.8.M03.'

**Comment by jakewins** [comment]
This was caused by incorrect locations in the Node representations, it should work as expected now.
