### ISSUE TITLE
Cypher Query fail while defining the relationship count

### ISSUE THREAD

**Issue by jeevaengg21** [neo4j/neo4j#8009]
Neo4j Version: 3.0.4

Objective of the below query is to eliminate duplicate bus service and bustop in a path, it work fine if i didn't provide the relationship count **-[r:CONNECTSWITH]->** but if the relationship count defined **-[r:CONNECTSWITH*..3]->** ,then its throwing 

`Key not found: r`

**Working:**

`OPTIONAL  MATCH p=(o:PORT{name:"busstop1"})-[r:CONNECTSWITH]->(d:PORT{name:"busstop2"}) where  ALL(r1 in rels(p) WHERE 1=size(filter(r2 in rels(p)where(r1.service=r2.service)))) and ALL(n in nodes(p) where 1=size(filter(m in nodes(p) WHERE id(m)=id(n))))  RETURN p  limit 10`

**Not Working:**

`OPTIONAL  MATCH p=(o:PORT{name:"busstop1"})-[r:CONNECTSWITH*..3]->(d:PORT{name:"busstop2"}) where  ALL(r1 in rels(p) WHERE 1=size(filter(r2 in rels(p)where(r1.service=r2.service)))) and ALL(n in nodes(p) where 1=size(filter(m in nodes(p) WHERE id(m)=id(n))))  RETURN p  limit 10`

**Comment by jexp** [comment]
In varlength paths r is s collection 

Try return sum(size(r))

Von meinem iPhone gesendet

**Comment by jeevaengg21** [comment]
`**** RETURN p, sum(size(r)) limit 10` also throws `Key not found: r`

**Comment by Hunterness** [comment]
Hi, is this still an issue for you in newer Neo4j versions?

**Comment by LinneaAndersson** [comment]
@jeevaengg21 I will close this issue, as there has not been any action for quite some time. Let us know if you still have any questions and we will help you. 

Thanks for reaching out to us,
Linnéa
