### ISSUE TITLE
Recursive create

### ISSUE THREAD

**Issue by milani** [neo4j/neo4j#804]
Suppose I want to add a relation from all nodes available in my graph to a newly created node. I used the following query:

```
MATCH n
CREATE UNIQUE n-[:FOLLOWS]->(f:PERSON {id:13423423})
RETURN f
```

Neo4j goes to infinite loop and creates infinite nodes and relations. I guess it is because it doesn't cache selected nodes at the start but tries to match a new node in each iteration.

The expected behaviour is to create relation between all AVAILABLE nodes ( at the current state ) and the new node.

Tested using neo4j v2.0.0M02

**Comment by chrisvest** [comment]
Looks like this is fixed.
