### ISSUE TITLE
NullValue.asString() returns inappropriate/inconvenient value 

### ISSUE THREAD

**Issue by meganalnico** [neo4j/neo4j#8048]
Calling asString() on an instance of org.neo4j.driver.internal.value.NullValue returns the string "null" and not the value [null]. This makes creating beans from Value objects unnecessarily complicated as you have ot check the type before calling asString().

**Neo4j** 'org.neo4j.driver:neo4j-java-driver:1.0.4'
### Steps to reproduce

``` java
public static BeanResult from(Value value) {        
        BeanResult result = new BeanResult();
        result.setId(value.get(ID_KEY).asString());
        result.setName(value.get(NAME_KEY).asString());
        result.setFileFormat(value.get(FILE_FORMAT_KEY).asString());
        result.setCreatedByUserId(value.get(CREATED_BY_USER_ID_KEY).asString();
        result.setCreateTimestamp(Instant.ofEpochMilli(value.get(CREATE_TIMESTAMP_KEY).asLong()).toString());
        result.setActive(value.get(ACTIVE_KEY).asBoolean());
        result.setType(value.get(TYPE_KEY).asString());
        result.setSubType(value.get(SUBTYPE_KEY).asString());
        result.setProjectUri(value.get(PROJECT_URI_KEY).asString());
        result.setModels(links.asList(ModelResult::from));
        return result;
    }
}
```
### Expected behavior

``` java
     value.getSubType() == null
```

When there is no corresponding property.
### Actual behavior

In the above code if a key does not exist for a string property an instance of NullValue is returned. NullValue returns the actual string "null". This sets properties to an invalid, and unexpected, value.

``` java
     value.getSubType() == "null"
```

**Comment by spacecowboy** [comment]
Thank you for your feedback.

This is working exactly as intended. The string representation of `null` is `"null"`. The method you want is `asObject`.

If you really want nulls, then instead of doing this:

``` java
result.setName(value.get(NAME_KEY).asString())
```

Do something like this

``` java
result.setName((String) value.get(NAME_KEY).asObject())
```

Or use a utility method:

``` java
static String toNullableString(Value value) {
  if (NullValue.NULL.equals(value)) {
    return null;
  }
  return value.asString();
}
```

**Comment by meganalnico** [comment]
Thank you for your time. We explored your suggestions before posting this bug and while I understand your point from a purely academic perspective. I believe it violates the principle of least surprise. `"null"`  is just not a useful value. If any value has come to be synonymous with a null string, it's the empty string `""`.  Yes, I understand how `String.valueOf()` works but a better example is `+`. 
In the end I just can't see how anyone is going to use `"null"` to their advantage in their program.
