### ISSUE TITLE
Incorrect documentation on procedure record types

### ISSUE THREAD

**Issue by fpavageau** [neo4j/neo4j#8067]
The documentation for [record types](http://neo4j.com/docs/java-reference/3.0/#writing-procedure) mentions (for the `SearchHit` class):

> These classes can only have public non-final fields

However, I tested the deployment of a procedure returning a record type with final fields in 3.0.6, and that works.

It might be a bad copy/paste from the documentation of procedure classes and the restrictions on their fields.

**Comment by petraselmer** [comment]
Hi Frank

Thanks for bringing this to our attention. 

This has now been fixed in https://github.com/neo-technology/neo4j-manual-modeling/pull/155. The changes will take effect the next time the documentation is built.
