### ISSUE TITLE
Cache sharding mispelled in official docs

### ISSUE THREAD

**Issue by drew-moore** [neo4j/neo4j#8069]
[Chapter 1.2.1 of the official documentation](http://neo4j.com/docs/operations-manual/current/introduction/design-considerations/#_read_scalability) contains an unfortunate typo: "Cache _sharding_" is spelled "cache _charding_" in two places.

**Comment by jjaderberg** [comment]
It has been fixed and will appear next time we publish the docs (in a day or two). Thanks for reporting!
