### ISSUE TITLE
Neo4j can't detect open file limit

### ISSUE THREAD

**Issue by rationalism** [neo4j/neo4j#8087]
- Neo4j version: 3.0.5 Enterprise
- Operating system: Ubuntu 14.04.4 LTS
- API/Driver: neo4j-java-driver 1.0.5

I get this warning on neo4j startup:

"WARNING: Max 1024 open files allowed, minimum of 40000 recommended. See the Neo4j manual."

However, I've already followed the manual instructions at https://neo4j.com/docs/operations-manual/current/deployment/post-installation/. Here is my /etc/security/limits.conf file:

root    soft    nofile  40000
root    hard    nofile  40000
neo4j   soft    nofile  40000
neo4j   hard    nofile  40000
panos   soft    nofile  40000
panos   hard    nofile  40000
ubuntu  soft    nofile  40000
ubuntu  hard    nofile  40000
-       soft    nofile      40000
-       hard    nofile      40000

"session    required   pam_limits.so" has been uncommented in /etc/pam.d/su, the machine has been restarted, and "ulimit -n" confirms that the limit has been set to 40,000. Nevertheless, neo4j still displays this warning on startup.

**Comment by chrisvest** [comment]
Even if you run `ulimit -n` as the `neo4j` user? The script uses `ulimit -n` to check for this.

**Comment by rationalism** [comment]
It looks like there's actually no neo4j user set up on this machine, neo4j just runs as the ubuntu user. Is it necessary to have a separate neo4j user?

**Comment by spacecowboy** [comment]
@rationalism it is not necessary, the debian package creates a `neo4j` user.

In fact, if you install the debian package, the open file limit is fixed for you at installation time.

Ultimately, the appropriate way to set the open file limit comes down to how you start neo4j.
- If running it manually in the terminal, then setting the file limit as for your current user in `/etc/security/limits.conf` is appropriate.
- If running as a service, then `/etc/security/limits.conf` is ignored on ubuntu. You have to set the limits inside the service script itself.

I recommend you install the 3.0.5 debian package, and simply run neo4j with the included service file. This will take care of the nolimits setting for you.

**Comment by rationalism** [comment]
Aha. I'm running neo4j as a service, that must be why. Can this be added to the documentation? Thanks

**Comment by spacecowboy** [comment]
cc @jjaderberg

**Comment by polibenitez** [comment]
To configure one needs to create/edit /etc/default/neo4j and define it to include

NEO4J_ULIMIT_NOFILE=40000

Look the documentation [here](https://neo4j.com/developer/kb/how-do-i-set-max-open-files-for-debian-installs/)

**Comment by rationalism** [comment]
@zadik Thanks, but I did try that, it did not work on my system. Only setting the file limit within the Upstart script itself worked.

**Comment by veleritas** [comment]
@spacecowboy 

Could you please elaborate on what you mean by:

> If running as a service, then /etc/security/limits.conf is ignored on ubuntu. You have to set the limits inside the service script itself.

I'm using neo4j (version 2.3.3 community) from Python 3.5. At the moment my Python code downloads the tarball for neo4j, unpacks it, and starts the neo4j service with a subprocess call. I'm also seeing the max 1024 files open warning, and I was wondering how I should set the open file limits if the `/etc/security/limits.conf` file is ignored.

What is the "service script" referring to here, and how do I change said script?

Thanks for your help!

**Comment by spacecowboy** [comment]
@veleritas `service` in this context refers to a system service which means you run it either with SysVinit (also known as `init.d`) or SystemD. This means that neo4j is started automatically when the machine boots up.

You do *not* get a system service if you download neo4j as a tarball.

You are *not* running as a service because you have a python script which runs  the `neo4j` binary directly. So in your case, set the number of files for the user.

**Comment by spacecowboy** [comment]
@veleritas also, for setting number of open files with python subprocesses see for example http://stackoverflow.com/questions/1689505/python-ulimit-and-nice-for-subprocess-call-subprocess-popen#1689991

**Comment by chrisvest** [comment]
This looks like it got solved.
