### ISSUE TITLE
Feature Request: add configuration setting to disable support for recovery

### ISSUE THREAD

**Issue by stefanneuhaus** [neo4j/neo4j#8115]
I would like to have a configuration setting to disable support for recovery. This probably includes transaction logging and checkpointing.

In our setup we do not care about recovery (we rebuild the graph regularly from a different datasource), but we do care about disk space. If I understand correctly, we do not need the transaction log and checkpointing in this scenario.

The current workaround is to use a rather aggressive checkpointing and log pruning. Though there are no strict guarantees about when checkpointing will occur, this seems to be feasible for us. Nevertheless completely disabling recovery support seems like the neater and more efficient solution.

**Comment by chrisvest** [comment]
I don't think we're going to address this niche, sorry.
