### ISSUE TITLE
Neo4j crashes on startup

### ISSUE THREAD

**Issue by rationalism** [neo4j/neo4j#8150]
- Neo4j version: 3.0.5 Enterprise
- Operating system: Ubuntu 14.04.4 LTS
- API/Driver: neo4j-java-driver 1.0.5

After starting up, neo4j prints this to the terminal:

Starting Neo4j.
2016-10-12 21:50:09.882+0000 INFO  Starting...
2016-10-12 21:50:10.613+0000 INFO  Bolt enabled on localhost:7687.
2016-10-12 21:50:10.646+0000 INFO  Initiating metrics...

prints this to the debug.log file: https://gist.github.com/rationalism/d969a5bb830833fd36afea8a1d5af5c4

and then runs for about ten minutes, using up all the allocated memory (6 GB heap) and all of the machine's CPU, finally crashing with "java.lang.OutOfMemoryError: Java heap space" (no further messages are printed to the log file).

Following the instructions from https://github.com/neo4j/neo4j/issues/7106, I added a heap dump on OOM argument to the config file, but I'm not sure how to analyze the heap dump, and it's too big to upload to GitHub (10 GB file).

**Comment by rationalism** [comment]
I fixed this by restoring from remote backup, but that is obviously not an ideal solution. :)

**Comment by MishaDemianenko** [comment]
Hi @rationalism, as soon as you will zip/gzip dump file it will be much much smaller. Can you please do that and then we will try to find a way to get that dump! Thx a lot for your report!

**Comment by rationalism** [comment]
@MishaDemianenko Thanks a lot, but it is still quite large after zip (gigabytes). I could scp the file to a machine you have access to, but otherwise I'm not sure how I could transfer it; do you have any ideas?

**Comment by MishaDemianenko** [comment]
Hi @rationalism i think you can upload it into dropbox for example and share link with us. You can send it to mikhaylo dot demianenko at neotechnology dot com, for example. Thx a lot!

**Comment by rationalism** [comment]
@MishaDemianenko Done! Thanks. Please confirm receipt

**Comment by MishaDemianenko** [comment]
Hi @rationalism yes we have it.

Yeah, that have nothing to do with https://github.com/neo4j/neo4j/issues/7106 and those fixes will not gonna help here.

Dump shows that you tried to do a recovery and most of the memory occupied by actual nodes (around 25%) and lucene related things. 
Is it expected that you recovery will affect that much nodes? 
Also have checked you dump for custom checkpointing configuration and can't find any. Can you please confirm that or even better can you send us your config file so we can take a look?

**Comment by rationalism** [comment]
@MishaDemianenko Sure, have shared config files via Dropbox. Don't think there's any custom checkpointing configuration.

Re: 

"Is it expected that you recovery will affect that much nodes?"

Sorry, I'm not sure what you mean. Does recovering from an error mean that the whole database has to be loaded into RAM? That would be a big problem - if 6 GB isn't enough for my fairly small database (~1M nodes), how would neo4j recover a database with 100M or 1G nodes?

**Comment by MishaDemianenko** [comment]
@rationalism thx for sharing those!

Nope, that's why i was wondering about custom checkpoint configuration.
We would only re-apply transactions that occurred after last successful checkpoint. With default settings that should not be that much things to recover, most of the time.

Since now we have everything we need to investigate, thx a lot! As soon as we will have some news we will come back!

**Comment by rationalism** [comment]
The same thing happened again today. There shoudn't have been any "recovery"; this happened after I shut down neo4j myself for server maintenance, not because of any kind of error. Here's the relevant portion of debug.log:

https://gist.github.com/rationalism/3f81bc1766f50c932116042c2c408f90

**Comment by rationalism** [comment]
This was "fixed" by restoring from remote backup again.

**Comment by rationalism** [comment]
This is also for a fairly small database (1.1M nodes, 3.6M relationships), so it seems unlikely to be a size-of-data problem, AFAICT.

**Comment by MishaDemianenko** [comment]
Hi @rationalism in latest debug log and in memory dump that we have I have found 2 things:
1. In the beginning of debug log (https://gist.github.com/rationalism/3f81bc1766f50c932116042c2c408f90) there is message: `Starting store flush...`. But there is nothing about finish doing it.
   I believe, this is how You end-up doing recovery later on. How db was stopped in that case? What script did You use to do that?
2. Even if failure occurred as result of first item you still should be able to proceed during next start without any failures. Provided dump showed a problem with lucene indexes during recovery and as result some default settings for index writers will be updated and some additional flags for special cases introduced please see https://github.com/neo4j/neo4j/pull/8188 for details. With those even default settings you should be able to proceed.

Hope this helps, and really interesting to hearing from You how state described in first item was achieved.

**Comment by rationalism** [comment]
@MishaDemianenko Great, thanks a lot. Can I apply patch #8188 myself, or do I need to wait for the next version of neo4j to come out?

Regarding point #1, I stop and start neo4j using a simple Upstart script (http://upstart.ubuntu.com/); the command is "sudo service neo4j [stop/start]". Here is the script I use:

https://gist.github.com/rationalism/806312069bac11daeca1c2fce0d911eb

**Comment by MishaDemianenko** [comment]
@rationalism if its not super urgent and You do not want to maintain your own build of the product i would suggest to wait for next release

**Comment by benbc** [comment]
Hello @rationalism. I think the problem is that Upstart's default service stop timeout is too short. We recommend a stop timeout of at least two minutes. You can configure this with a `kill timeout` stanza in the service definition.

**Comment by rationalism** [comment]
@benbc Thanks! I have done that. 

Could this be added to the neo4j documentation? This blog post covers both this and issue #8087 (although it only covers systemd, not Upstart), so maybe the docs could just link to that?

https://www.graphgrid.com/systemd-neo4j-ubuntu/

**Comment by chrisvest** [comment]
Looks like this has been fixed.
