### ISSUE TITLE
neo4j-import enhancement request: automatically sort the node inputs by id groups

### ISSUE THREAD

**Issue by fpavageau** [neo4j/neo4j#8162]
Currently with `neo4j-import`, if the same id group is used in multiple node inputs (see the workaround in #8161), the user needs to manually sort her inputs to avoid interleaving id groups.

> Import error: Nodes for any specific group must be added in sequence before adding nodes for any other group

**Neo4j version:** 3.0.6
**Operating system:** MacOS
## Steps to reproduce
1. Create CSV files for the import
   - `a.csv`:
   
   ```
   :ID(Default-ID)
   abc
   ```
   - `b.csv`:
   
   ```
   :ID(B-ID)
   def
   ```
   - `c.csv`:
   
   ```
   :ID(Default-ID)
   xyz
   ```
2. Try to import:

```
$ /path/to/neo4j/bin/neo4j-import --into graph.db --id-type string --nodes:A a.csv --nodes:B b.csv --nodes:C c.csv --stacktrace true
Neo4j version: 3.0.6
Importing the contents of these files into graph.db:
Nodes:
  :A
  /tmp/a.csv

  :B
  /tmp/b.csv

  :C
  /tmp/c.csv

Available resources:
  Free machine memory: 71,86 MB
  Max heap memory : 3,56 GB
  Processors: 8

Nodes
Import error: Nodes for any specific group must be added in sequence before adding nodes for any other group
Caused by:Nodes for any specific group must be added in sequence before adding nodes for any other group
java.lang.IllegalStateException: Nodes for any specific group must be added in sequence before adding nodes for any other group
    at org.neo4j.unsafe.impl.batchimport.cache.idmapping.string.EncodingIdMapper.put(EncodingIdMapper.java:204)
    at org.neo4j.unsafe.impl.batchimport.NodeEncoderStep.process(NodeEncoderStep.java:78)
    at org.neo4j.unsafe.impl.batchimport.NodeEncoderStep.process(NodeEncoderStep.java:44)
    at org.neo4j.unsafe.impl.batchimport.staging.ProcessorStep.lambda$receive$2(ProcessorStep.java:97)
    at org.neo4j.unsafe.impl.batchimport.executor.DynamicTaskExecutor$Processor.run(DynamicTaskExecutor.java:243)
```
## Workaround

As mentioned before, just sort the inputs manually, i.e.

```
bin/neo4j-import --into graph.db --id-type string --nodes:A a.csv --nodes:C c.csv --nodes:B b.csv
```

or

```
bin/neo4j-import --into graph.db --id-type string --nodes:B b.csv --nodes:A a.csv --nodes:C c.csv
```

It gets tedious when the number of input files and the number of groups both increase.
## Enhancement

If the code cannot be modified to accept split definitions of id groups, re-order the node inputs by analyzing the CSV headers first then automatically grouping inputs by the referenced id group. The original order can be mostly maintained, to avoid confusion.

Like #8161, it's not a big deal either, but I think it would definitely reduce the friction when using `neo4j-import`.

**Comment by tinwelint** [comment]
This has been fixed for 3.4 and forwards.
