### ISSUE TITLE
about NEO4J.3.1.beta

### ISSUE THREAD

**Issue by GameFreedom** [neo4j/neo4j#8166]
HI,
Download can't pop up, click to download, will jump to 404 pages.

**Comment by mneedham** [comment]
Have you tried one of the links on this page? https://neo4j.com/download/other-releases/

I just tried it now and it's working for me...

**Comment by GameFreedom** [comment]
Enter the url https://neo4j.com/download/other-releases/, click on the name of ‘Neo4j 3.1.0-BETA1 (Windows x64, exe) ’ button .After the jump page, no download. Click retry the download, pop up, 404

**Comment by spacecowboy** [comment]
@GameFreedom thanks for the report. The link is indeed wrong. 
- It points to https://neo4j.com/artifact.php?name=neo4j-community_windows-x64_3_1_0-BETA11.exe
- But it should point to https://neo4j.com/artifact.php?name=neo4j-community_windows-x64_3_1_0-BETA1.exe

We'll fix this. In the mean time, you can download the executable from here: https://neo4j.com/artifact.php?name=neo4j-community_windows-x64_3_1_0-BETA1.exe

**Comment by simpsonjulian** [comment]
Hi @GameFreedom - thanks for pointing this out.

That link is fixed now.  Sorry about that!

Props to @mneedham and @spacecowboy for letting us know.
