### ISSUE TITLE
Enhance error message

### ISSUE THREAD

**Issue by wadael** [neo4j/neo4j#8173]
Several classes may return this error message
"WARNING: Cannot merge node using null property value for id" 

I got it in a LOAD CSV block
it gives 2 informations : a merge failed because of the computed value for the id property
however it is close to useless

What would be AWESOME is to get the name and the line number of the file that failed.

https://github.com/neo4j/neo4j/search?utf8=%E2%9C%93&q=Cannot+merge+node
- Neo4j version: 3.0.6
- Operating system: Ubuntu 16.04
- CYPHER , using neo4j-shell

**Neo4j Version:** 3.0M03  
**Operating System:** Ubuntu 15.10  
### Expected behavior

"WARNING: Cannot merge node using null property value for id at line 5555 of file opendataset.csv" 
### Actual behavior

"WARNING: Cannot merge node using null property value for id"

**Comment by spacecowboy** [comment]
Thanks for the feedback. You're quite right. That error message is absolutely useless.

**Comment by sherfert** [comment]
Error messages include the line number from the CSV file from neo4j version 4.0 and newer. I hope that resolves the issue. (And yes, we should have notified you that this behavior was in place slightly earlier).
