### ISSUE TITLE
ldap integration or new user addition

### ISSUE THREAD

**Issue by asmksf** [neo4j/neo4j#8178]
is it possible to integrate neo4j 3.0 open source one to integrate with active dir or any other way to add more users  ? 
- Neo4j version: 3.0
- Operating system: (Ubuntu 14.04)
- API/Driver:

**Comment by spacecowboy** [comment]
@mkaja neo4j 3.0 does not officially support integration with ldap, or additional users.

This is however one of the new features in Neo4j 3.1 Enterprise: https://github.com/neo4j/neo4j/wiki/Neo4j-3.1-changelog#310-m05
