### ISSUE TITLE
User function in a write cypher command

### ISSUE THREAD

**Issue by szenyo** [neo4j/neo4j#8181]
**Neo4j Version:** 3.1.0-M10
**Operating System:** macOS 10.12 Sierra
### Steps to reproduce
1. I created a new User function.

```
    @UserFunction
    @Description("apoc.similarity.cosine([list1],[list2])")
    public double cosine(@Name("list1") List<Double> list1, @Name("list2") List<Double> list2) {
        double dotProduct = 0.0;
        double normA = 0.0;
        double normB = 0.0;
        for (int i = 0; i < list1.size(); i++) {
            dotProduct += list1.get(i) * list2.get(i);
            normA += Math.pow(list1.get(i), 2);
            normB += Math.pow(list2.get(i), 2);
        }   
        return dotProduct / (Math.sqrt(normA) * Math.sqrt(normB));
    }
```

Build, put into plugins directoy, restart.
1. My Nodes vector properties look like this:
   `c1.vector=[0,1,0,1]`
2. I tried this:
   `MATCH (c1:Cetli), (c2:Cetli)
   return apoc.similarity.cosine(c1.vector,c2.vector)
   It works, return a double.`
### Expected behavior

"Functions are more limited than procedures: they can’t execute writes or schema operations and are expected to return a single value, not a stream of values.
But this makes it also easier to write and use them.”
And the example is:
`CREATE (v:Value {id:{id}, data:{data}, created: apoc.date.format(timestamp()) })`
### Actual behavior

I tried this:
`MATCH (c1:Cetli), (c2:Cetli)
CREATE (c1)-[s:SIMILARITY {similarity:apoc.similarity.cosine(c1.vector,c2.vector)}]->(c2)`
It returns error:
`Write operations are not allowed for 'neo4j overridden by OVERRIDE_READ’.`

**Comment by spacecowboy** [comment]
Thanks for the report

**Comment by pontusmelke** [comment]
Thanks for reporting this. The issue has been fixed and will be part of the next release.

Regards,
Pontus

**Comment by spacecowboy** [comment]
Closing as already fixed.
