### ISSUE TITLE
Improve allocated ressources for windows launcher

### ISSUE THREAD

**Issue by wadael** [neo4j/neo4j#8186]
- Neo4j version: 3.0.6
- Operating system: Windows 7 and 10
- **Steps to reproduce**
  Click the neo4j.exe to start the launcher.
- Expected behavior
  Expected Neo to be as quick as usual that on my laptop considering students laptops are newer.
  However, mine is under linux, correctly set up for the open files limit and with a generous JAVA_OPTS system variable.
- Actual behavior
  Students with windows laptop tend to click the exe to launch Neo  _despite advices_ then importing via LOAD CSV, even with a commit step set to 5000, was slow as creeping death
- Propositions
  Allocate more memory when Neo is started or propose between 1Gb,2Gb,4Gb 
  Give instructions to increase open files limit

**Comment by ikwattro** [comment]
How big are your CSV files ? We just ran a full day training during GraphConnect and with _normal_ files we had no issue on windows (except when in VM's).

Also it depends of the number of operations during every commit step, so 5000 \* number of ops

**Comment by wadael** [comment]
The CSV is from the French national adresses database 
See https://adresse.data.gouv.fr/download/ 
Students chose their department (from ile de France, files are between 23 and 57 Mb)
This is what I used in my article (in Linux Mag) and in my workshops.

After creating the constraints and indexes, 

```
CREATE CONSTRAINT ON (v:Ville) ASSERT v.libelle IS UNIQUE;
CREATE CONSTRAINT ON (c:Commune) ASSERT c.codePostal IS UNIQUE;
CREATE CONSTRAINT ON (e:Endroit) ASSERT e.id IS UNIQUE;

CREATE INDEX ON :Endroit(lat);
CREATE INDEX ON :Endroit(lon);
CREATE INDEX ON :Endroit(numero);
CREATE INDEX ON :Endroit(nomVoie);
```

they adapted this script

```
USING PERIODIC COMMIT 5000

LOAD CSV WITH HEADERS FROM 'file:///home/jerome/BAN_licence_gratuite_repartage_75.csv'
AS ligne FIELDTERMINATOR ';'

MERGE (ou:Endroit {id: ligne.id})

SET ou.numero = TOINT(ligne.numero)
SET ou.rep = ligne.rep
SET ou.nomVoie = ligne.nom_voie
SET ou.alias = ligne.alias
SET ou.lon = TOFLOAT(ligne.lon)
SET ou.lat = TOFLOAT(ligne.lat)
SET ou.codeInsee = ligne.`code_insee`

MERGE (comm:Commune { codePostal: TOINT(ligne.`code_post`) })
SET comm.nom = ligne.nom_commune

MERGE (ville:Ville {libelle: ligne.libelle_acheminement })
SET ville.codeDepartement = left(ligne.`code_post`,2)

MERGE (comm)-[:APPARTIENT_A]->(ville)
MERGE (ou)-[:SITUE_DANS]->(comm) ;
```

Some times ago, I was told by a trusty source I'll keep anonymous that the windows launcher was ok for playing with the movies db but weak for tough work.

**Comment by wadael** [comment]
Pardon my French

**Comment by tinwelint** [comment]
Did you try the importer (neo4j-import)? It's magnitudes faster than LOAD CSV for initial bulk-loading data, see https://neo4j.com/docs/operations-manual/3.5/tools/import/. And generally the "launcher", currently called the Desktop does better at allocating proper amounts of memory.

Since this is 3y old and I believe there are solutions to your problems I'm closing this issue.
