### ISSUE TITLE
Improve LOAD CSV WITH HEADERS, allow use of cursor[index]

### ISSUE THREAD

**Issue by wadael** [neo4j/neo4j#8190]
When importing open data, the CSV is not always as 'clean' as expected.
Sometimes, the headers are present but not of optimum use, when they are like `a long description with spaces and accentuated characters like éàùè`.

In that case, it would be nice to be able to use the line[columNumber] shortcut too, even if the cypher user is LOAD CSV WITH HEADERS.

(my workaround is to remove the headers from the file  & do a LOAD CSV but it sucks for auto-updates)
- **Steps to reproduce**
- Expected behavior
  A cypher query like this one should work  (the first SET is the breaking point)

LOAD CSV WITH HEADERS FROM 'file:///funkyheaders.csv' AS ligne FIELDTERMINATOR ';'
MERGE (node:FunkyHeaders {id: ligne.id})
SET node.funkyCol = ligne[1]
SET node.funkyCol2 = ligne.`colonne 2`
SET node.funkyCol3 = ligne.`colonne 3`
;

with this CSV content
id;mon libellé super long qui explique bien ce que c'est;colonne 2;colonne 3
1;azertyuiop;2;3
2;qwertyuiop;3;4
3;qwertzuiop;4;5
- Actual behavior : message displayed in browser 
  Expected 1 to be a java.lang.String, but it was a java.lang.Long

**Neo4j Version:** 3.0.6
**Operating System:** Ubuntu 16.10 
**API:** Cypher
### Steps to reproduce
1. Create the funkyheaders.csv file in NEO_HOME/import
2. In the browser :  CREATE CONSTRAINT ON (node:FunkyHeaders) ASSERT node.id IS UNIQUE;
3. In the browser :  
   LOAD CSV WITH HEADERS FROM 'file:///funkyheaders.csv' AS ligne FIELDTERMINATOR ';'
   MERGE (node:FunkyHeaders {id: ligne.id})
   SET node.funkyCol = ligne[1]
   SET node.funkyCol2 = ligne.`colonne 2`
   SET node.funkyCol3 = ligne.`colonne 3`;
### Expected behavior

Import works without whining
### Actual behavior

Import whines

**Comment by ikwattro** [comment]
@wadael 

I think you can just use `LOAD CSV` without headers and skip the first line ?  This works for me : 

``` bash
neo4j-sh (?)$ LOAD CSV FROM 'file:///file.csv' AS ligne FIELDTERMINATOR ';' WITH ligne SKIP 1
> MERGE (node:FunkyHeaders {id: ligne[0]})
> SET node.funkyCol = ligne[1]
> SET node.funkyCol2 = ligne[2]
> SET node.funkyCol3 = ligne[3];
+-------------------+
| No data returned. |
+-------------------+
Nodes created: 3
Properties set: 12
Labels added: 3
132 ms
neo4j-sh (?)$
```

``` bash
ikwattro@graphaware ~/d/_/3/import> cat file.csv
id;mon libellé super long qui explique bien ce que c'est;colonne 2;colonne 3
1;azertyuiop;2;3
2;qwertyuiop;3;4
3;qwertzuiop;4;5
ikwattro@graphaware ~/d/_/3/import>
```

**Comment by jexp** [comment]
You should also be able to do this:

```
LOAD CSV WITH HEADERS FROM 'file:///funkyheaders.csv' AS ligne FIELDTERMINATOR ';'
WITH keys(ligne) as keys, ligne
MERGE (node:FunkyHeaders {id: ligne.id})
SET node.funkyCol = ligne[keys[1]]
SET node.funkyCol2 = ligne.`colonne 2`
SET node.funkyCol3 = ligne.`colonne 3`
```

**Comment by ikwattro** [comment]
Confirms that @jexp solution works also : 

``` bash
neo4j-sh (?)$ LOAD CSV WITH HEADERS FROM 'file:///file.csv' AS ligne FIELDTERMINATOR ';'
> WITH keys(ligne) as keys, ligne
> MERGE (node:FunkyHeaders {id: ligne.id})
> SET node.funkyCol = ligne[keys[1]]
> SET node.funkyCol2 = ligne.`colonne 2`
> SET node.funkyCol3 = ligne.`colonne 3`;
+-------------------+
| No data returned. |
+-------------------+
Nodes created: 3
Properties set: 12
Labels added: 3
158 ms
neo4j-sh (?)$
```

**Comment by wadael** [comment]
Thanks guys, re-learned SKIP 1 and learned  WITH keys(ligne) as keys, ligne
That's what I wanted, being able to mix labels and indexes.
The goal being to keep the cypher query readable by not having ligne.`un grand libellé à ingérer ùéèôà`

I guess I have a pledge to write a PR for the documentation then :)

**Comment by wadael** [comment]
So, its ok for me to close this issue

LOAD CSV WITH HEADERS FROM 'file:///funkyheaders.csv' AS ligne FIELDTERMINATOR ';'
**WITH keys(ligne) as keys, ligne**
MERGE (node:FunkyHeaders {id: ligne.id})
SET node.funkyCol = **ligne[keys[1]]**
SET node.funkyCol2 = ligne.`colonne 2`
SET node.funkyCol3 = ligne.`colonne 3

**Comment by spacecowboy** [comment]
Closing as requested
