### ISSUE TITLE
`shortestPath()` returns strange object when used as a function in an expression

### ISSUE THREAD

**Issue by ToreUprising** [neo4j/neo4j#8201]
I misapplied `shortestPath` in a `WITH` statement expression and found some very strange behavior in the resulting object; it seems to behave as a collection of Paths that do not behave like Paths _or_ Nodes/Relationships in Cypher, though in the python driver it is properly hydrated as a Path (and the individual collection items as Nodes or Relationships, respectively).
- **Neo4j version** : 3.0.3, 3.0.6, 3.1BETA1
- **Operating system** : Ubuntu 14.04
- **API/Driver** : Web frontend and `neo4j-python-driver`
## Actual Behavior

![screenshot 2016-10-17 at 11 29 26 pm](https://cloud.githubusercontent.com/assets/15202973/19482235/1c972656-9516-11e6-8b54-7920dd7beed5.png)
Here is the initial result of the "incorrect" but valid use of `shortestPath`; it appears to be a regular Path. However, if you try to run `Nodes()` on the object, you get this error:
![screenshot 2016-10-17 at 11 29 51 pm](https://cloud.githubusercontent.com/assets/15202973/19482351/70100f32-9516-11e6-922c-b226852e4c6b.png)
So it appears to be a Collection. However, in `python`, this object is returned as a Path, not a Collection. It does support indexing in Cypher, though:
![screenshot 2016-10-17 at 11 38 23 pm](https://cloud.githubusercontent.com/assets/15202973/19482378/91a9bee0-9516-11e6-8743-c78685135f77.png)
In `python`, these objects are correctly hydrated as Nodes or Relationships, so when the Collection is broken up in Cypher, it seems to be a Collection of the Path elements. However, if one attempts to use `Labels()` on one of these elements (or `Type()` if a relationship), we get an error:
![screenshot 2016-10-17 at 11 39 46 pm](https://cloud.githubusercontent.com/assets/15202973/19482591/2a64be3c-9517-11e6-9a79-2e1e482f5f23.png)
It is also impossible to access the attributes of these objects, and most Path functions do not work on them (though `Length()` will return 1 for any of them). So the original object returned from `shortestPath()` in an expression operates like a collection, but the elements don't behave in Cypher like anything (though they are returned with enough data that the `python` driver can correctly identify them, turning the Collection into a Path and treating the Collection objects as Nodes or Relationships).
## Expected behavior

Given the increase in function syntax use coming in 3.1, it seems like `shortestPath()` (whose syntax is identical to a function call) should either generate an ordinary path when used in an expression, or should throw an error so that new users know to only use them in a `MATCH` statement.

**Comment by spacecowboy** [comment]
Thank you for the clear report. I agree that the behavior is surprising.

**Comment by spacecowboy** [comment]
Fixed in https://github.com/neo4j/neo4j/pull/10249
