### ISSUE TITLE
 Surprising Type Error when accessing a nested list and then concatenating it to another list

### ISSUE THREAD

**Issue by jacknoble** [neo4j/neo4j#8204]
Hi! I found this behavior strange enough that it should probably be considered a bug. 

In Cypher lists can be concatenated
`return [] + [1]` => `[1]`
and the head of a list can be accessed by the `head` function
`return head([[], 1])` => `[]`

And naturally one expects to be able to compose these expressions. But that's a type error.
`return head([[],1]) + [1]` => `Type mismatch: expected Collection<Any> but was Collection<Integer>`

I would expect this expression to return `[1]`. Cypher users probably shouldn't ever see errors related to typed collections right?

(Discovered using Neo4j 3.0.4, that's probably sufficient for reproducing)

**Comment by Mats-SX** [comment]
Hello @jacknoble and thanks for reporting. Confirming this as a bug; list concatenation should work on any list types and the result of the expression should be a list of the least common super-type of the elements of the concatenated lists.

**Comment by sherfert** [comment]
In both 3.2 and 3.3 (and possibly earlier too) this was fixed.
