### ISSUE TITLE
[Feature request] In browser, one big red X cross to close 'em all

### ISSUE THREAD

**Issue by wadael** [neo4j/neo4j#8210]
When using the browser, the display seems cluttered with all the cards of the previous instructions executed. It would be great to have all the cards closed in one click 

On those damn recent screens in compressed landscape format, vertical space is scarce so it would be great to be able to close all cards so that next one can spread in all the vertical space available.

One big cross to rule 'em all !
Hail to the big cross !
Hail to Kriss
Hail to Kross

Jump ! Jump ! 
(in case ya R 2 young to know   https://www.youtube.com/watch?v=010KyIQjkTk

Current workaround is to use a client-side plugin like webmonkey to create it.

**Comment by oskarhane** [comment]
Hi, there's a separate repository for the [neo4j-browser](https://github.com/neo4j/neo4j-browser).
There's a `:clear` command you can type to clear all result frames from the stream.
