### ISSUE TITLE
UnknownError using 'WITH DISTINCT json' 

### ISSUE THREAD

**Issue by allanben13** [neo4j/neo4j#8212]
Hi all, I'm running Neo4j on my macbook pro and i'm facing an issue on Neo4j enterprise 3.1.0 Beta. 

This query fails: 

WITH {json} as data
UNWIND data as q
UNWIND q.data as posts
UNWIND posts.from as userFroms
MERGE (s:Status { statusId: split(posts.id,"_")[toInt(1)]}) ON CREATE SET s.statusName = posts.name,  s.message=posts.message, s.description=posts.description, s.link=posts.link, s.type=posts.status_type, s.createdTime=posts.created_time, s.privacy=posts.privacy.value
FOREACH(ignoreMe IN CASE WHEN EXISTS(userFroms.id) THEN [1] ELSE [] END |
MERGE (userFrom:UserFacebook{id:userFroms.id}) ON CREATE SET userFrom.facebookName=userFroms.name
MERGE (userFrom)-[:HAS_POSTED_STATUS]->(s)
)

```
  WITH distinct q, posts 
  MERGE (s:Status { statusId: split(posts.id,"_")[toInt(1)]})
  MERGE (user:User {id:q.user_id})
  MERGE (user)-[:HAS_RECEIVED_STATUS]-(s)
```

This is the error : 

Erreur : Client error: (400) Bad Request
Neo.DatabaseError.General.UnknownError
unknown value: ((data,[{created_time=2016-10-17T20:52:29+0000, from={name=Antonella Benham's, id=10152984092575861}, caption=business.lesechos.fr, link=http://business.lesechos

If I remove "distinct"  from "WITH distinct q, posts" , the query works but it takes much longer.

This query use to work on neo4j 3.0.3 enterprise.

**Comment by spacecowboy** [comment]
Thank you for the report

**Comment by Zenithar** [comment]
I have the same error on a Community 3.0.6.

```
UNWIND {rows} as row
        WITH row
        MERGE (o:Observable:Hash:SHA256 {urn: row.urn})
            ON CREATE SET o.created = toInt(row.created), o.updated = toInt(row.created), o.value = row.value
            ON MATCH SET o.updated = toInt(row.created)
        WITH distinct row, o
        UNWIND row.feeds as feed
            MATCH (f:Feed {urn: feed.object})
            WITH row, o, f, feed
            WHERE f IS NOT null
                CREATE UNIQUE (o)-[:IN_FEED]->(f)
                MERGE (o)-[r:IN_FEED]->(f)
                    SET r.timestamp = toInt(feed.timestamp)
```

```
errors=[{Neo.DatabaseError.Statement.ExecutionFailed  unknown value: ((urn,hash:sha256:4772e91a6e6df461b30c3c6507861179d6d51a1f5fed18272d0da241e43b91c2)) of type class scala.Tuple2)}] model=SHA256
```

This request seamlessly worked on a 3.0.3 too.

**Comment by systay** [comment]
Could you share what the content of the parameters are when these queries fail, @Zenithar or @allanben13?

**Comment by systay** [comment]
or, missing the parameter value, a full stack trace would be really helpful. I have a hunch, but I would love to understand better what is happening.

**Comment by Zenithar** [comment]
```
[
  { 
    "urn": "hash:sha256:4772e91a6e6df461b30c3c6507861179d6d51a1f5fed18272d0da241e43b91c2",
    "created": 1477474906522,
    "updated": 1477474906522,
    "value": "4772e91a6e6df461b30c3c6507861179d6d51a1f5fed18272d0da241e43b91c2",
    "feeds": [
      {
        "timestamp": 1477474906522,
        "object": "feed:report:9393f70a9b0138aa9e76d1354db9936a6e939617dbef9d7de86399ffc6d10d89"
      }
    ]
  }
]
```

Hash exists, and Feed too.

When I remove the `distinct` from WITH statement, it works.

I work with Go (neoism.v1) via HTTP endpoint, all my test cases failed with this error when using `WITH distinct row`.

**Comment by systay** [comment]
Hi @Zenithar and @allanben13!

I've been looking at your problem today, and I think it was fixed a few days ago with this PR: https://github.com/neo4j/neo4j/pull/8225

That made it into the 3.1 branch just after the release of Neo4j 3.1-m12-beta2. If you have access to snapshots, you can check if your problem has been solved. If not, wait for the next public release and it should be fixed.

Thanks for reporting it!
