### ISSUE TITLE
Transient NullPointerException thrown on query

### ISSUE THREAD

**Issue by rationalism** [neo4j/neo4j#8239]
- Neo4j version: 3.0.5 Enterprise
- Operating system: Ubuntu 14.04.4 LTS
- API/Driver: neo4j-java-driver 1.0.5

The query 

```
MATCH (root:`norecon`) RETURN labels(root), count(*)
```

 threw a DatabaseException/NullPointerException for unknown reasons. This appears to be a transient error, so it might be harmless, but I figured I'd report it anyway just in case. Here's the stack trace in debug.log:

https://gist.github.com/rationalism/031a7f010e43eccc13f5a0e0ed3faaa3

**Comment by spacecowboy** [comment]
Thank you for the report. `NullPointerException`s are always considered bugs.
