### ISSUE TITLE
Pattern Comprehension might not be working correctly in 3.1 Beta 2

### ISSUE THREAD

**Issue by sandyplace** [neo4j/neo4j#8249]
## New pattern comprehension fails with the following error:

`An unexpected failure occurred, see details in the database logs, reference number d7b45b9f-8abf-47ec-b5a7-8b74079be924.`

The log file looks like:
`2016-10-25 03:31:12.331+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [UnknownError]: key not found: PatternComprehension(None,RelationshipsPattern(RelationshipChain(NodePattern(Some(Variable(e)),List(),None),RelationshipPattern(None,false,List(),None,None,OUTGOING),NodePattern(Some(Variable(t)),List(),None))),None,DesugaredMapProjection(Variable(t),List(LiteralEntry(PropertyKeyName(amount),Property(Variable(t),PropertyKeyName(amount)))),false),Set()). See debug.log for more details, reference d7b45b9f-8abf-47ec-b5a7-8b74079be924.`

**Neo4j Version:** 3.1Beta2
**Operating System:** Windows 10.1  
### Steps to reproduce

I receive the error stated above when I run the following Neo4j query:
`MATCH (e:Employee) WITH e LIMIT 5 RETURN [(e) --> (t) | t { .amount }]`

However the following query is successful:
`MATCH (e:Employee) WITH e LIMIT 5 MATCH (e) --> (t) RETURN collect(t {.amount}) as result`
### Expected behavior

the first query I believe is valid and should work.
### Actual behavior

an exception is thrown.

**Comment by stijnvandrunen** [comment]
In 3.1.0-M13-beta3 seems to still be a bug:

MATCH (bla:Bla)
RETURN bla{
	.name,
	.uuid,
    test: [(bla)-->(u) | u.uuid][0]
}

results in key not found: MapProjection(Variable(bla),List(PropertySelector(Variable(name)), PropertySelector(Variable(uuid)), LiteralEntry(PropertyKeyName(test),ContainerIndex(PatternComprehension(None,RelationshipsPattern(RelationshipChain(NodePattern(Some(Variable(bla)),List(),None),RelationshipPattern(None,false,List(),None,None,OUTGOING),NodePattern(Some(Variable(u)),List(),None))),None,Property(Variable(u),PropertyKeyName(uuid)),Set(Variable(bla), Variable(filter_area))),SignedDecimalIntegerLiteral(0)))))

Additional info: if I remove .uuid and .name than it works... If I rewrite .uuid to uuid: bla.uuid it works... But the whole point in 3.1 is to be able to do .uuid and to add test: with pattern comprehension.

**Comment by systay** [comment]
@stijnvandrunen Just making sure that this is the same issue we discussed in the public slack channel. The problem is solved on the SNAPSHOT you have tried it on, right?

**Comment by stijnvandrunen** [comment]
@systay Correct! It works in the provided release, so should be fixed in next official release (>beta3).
