### ISSUE TITLE
Neo4j web client is creating a new websocket every 1 minute

### ISSUE THREAD

**Issue by sandyplace** [neo4j/neo4j#8298]
When i leave chrome browser open on the Neo4j window for 4 hours I run out of sockets and various applications start to fail as a result. Chrome has a limit of 255 open sockets.

**Neo4j Version:** 3.1M012
**Operating System:** Windows 

### Steps to reproduce
1. Open the Neo4j browser window run a query.
2. Do not close the browser. You will see in the network tab in the chrome debugger a web socket being allocated every minute.
5. After about 4 hours any browser window will fail that uses websockets

### Expected behavior
Neo4j should close the socket.

### Actual behavior
Various chrome applications start to fail.

**Comment by oskarhane** [comment]
Hi @sandyplace and thanks for the report. 
Would you mind opening this issue in the https://github.com/neo4j/neo4j-browser repository instead since it's probably a client bug?

Thank you
