### ISSUE TITLE
Dark theme renders text unreadable in browser console

### ISSUE THREAD

**Issue by Manish-Giri** [neo4j/neo4j#8316]
In the browser, I loaded the example movie database and executed the first CREATE query. Then while viewing the query results below, I switched to the "text" tab, the results were not readable. This happened when I had the "dark" theme selected in settings. When I switch to "normal" theme, the text is readable again (screenshots included).

- Neo4j version: 1.1.8 (Neo4J Browser), 3.0.6(Neo4J CE)
- Operating system: macOS Sierra
- API/Driver: Cypher

### Steps to reproduce
1. Login to the browser console on http://localhost:7474/browser/
2. Load the sample movie database, and execute the first "create" query.
3. When the results load, switch to the "text" tab.

### Expected behavior
The text should be readable (as in the normal theme) - 
![screenshot 2016-11-05 14 53 53](https://cloud.githubusercontent.com/assets/11348778/20032841/830cc628-a369-11e6-809b-141bf40e9dd4.png)

### Actual behavior
The text is unreadable in dark theme - 

![screenshot 2016-11-05 14 53 09](https://cloud.githubusercontent.com/assets/11348778/20032846/9631ebe8-a369-11e6-8c54-6fd2a90a12ea.png)

**Comment by jexp** [comment]
@Manish-Giri can you move this issue to: https://github.com/neo4j/neo4j-browser/issues ?

**Comment by Manish-Giri** [comment]
@jexp Will do. Thanks!
