### ISSUE TITLE
Possibly incorrect result with count() on self loops

### ISSUE THREAD

**Issue by pranet** [neo4j/neo4j#8324]
- Neo4j version: 3.0.4
- Operating system: El Capitan 10.11.13
- API/Driver: Cypher

- **Steps to reproduce**
Create a graph using the following commands:
create (n)-[r:CALL]->(n)
create (n)-[r:CALL]->(n)
create (u)-[r:CALL]->(v)

(Total 4 nodes, with 2 self loops, and one more edge)

Query A: 
match(n)-[r:CALL]->(n)
return count(r)
- Expected behavior
2
- Actual behavior
3

Query B: 
match(n)-[r:CALL]->(n)
where id(n) = id(n)
return count(r)
- Expected behavior
2
- Actual behavior
2

Query C: 
match(n)-[r:CALL]->(n)
return r
- Expected behavior
2 edges returned
- Actual behavior
2 edges returned

Profiling for A gives the following 
<img width="1280" alt="screen shot 2016-11-08 at 3 55 35 pm" src="https://cloud.githubusercontent.com/assets/5443393/20095545/e6910cd6-a5cb-11e6-91bf-d2b925e5eaee.png">

Seems to be completely ignoring the match clause. Query B, and C work as expected however.

**Comment by spacecowboy** [comment]
I agree. The result for Query A is surprising. Thanks for the report.
