### ISSUE TITLE
License declaration for the community edition - GPL v3 or AGPL v3 ?

### ISSUE THREAD

**Issue by sgustafsson** [neo4j/neo4j#8331]
The NOTICE file at https://github.com/neo4j/neo4j/blob/3.1/community/NOTICE.txt says:

"If you have not executed a Commercial Agreement with Neo Technology, the
Software is subject to the terms of the GNU AFFERO GENERAL PUBLIC LICENSE
Version 3 (http://www.fsf.org/licensing/licenses/agpl-3.0.html), included
in the LICENSE.txt file."

The LICENSE file at https://github.com/neo4j/neo4j/blob/3.1/community/LICENSE.txt says: 

"The software ("Software") developed and owned by Network Engine for
Objects in Lund AB (referred to in this notice as "Neo Technology") is
licensed under the GNU GENERAL PUBLIC LICENSE Version 3 to all third
parties and that license is included below."

The README says 

"Neo4j is an open source product. We support a Community edition under the GPLv3 license. The Enterprise edition is available under the AGPLv3 license for open source projects otherwise under a commercial license"

So I assume the reference to the AGPL v3 license in the NOTICE file of the community edition is wrong, and should be referring to the GPL v3?

**Comment by spacecowboy** [comment]
@sgustafsson yes you are correct. The notice file is incorrect (result of a bad merge). Thank you for bringing it to our attention

**Comment by jimwebber** [comment]
Fixed in https://github.com/neo4j/neo4j/pull/8391.

Thanks for the feedback @sgustafsson
