### ISSUE TITLE
MacOS - Neo4j 3.1.0-M13-beta3 neo4j-import - Could not find or load main class

### ISSUE THREAD

**Issue by Kerruba** [neo4j/neo4j#8347]
**Neo4j Version:**: 3.1.0-M13-beta3 Community Edition
**Operating System:**: macOS Sierra 10.12.1

### Steps to reproduce
- Download the 3.1.0-M13-beta3 Community Edition version from neo4j site
- Run neo4j-import 

### Expected behavior
- Should start the process

### Actual behavior
- Got an **Error: Could not find or load main class org.neo4j.tooling.ImportTool**

**Comment by spacecowboy** [comment]
Thanks for the report, this is indeed a bug.

As a work around, are you able to invoke `neo4j-admin import` instead? This is the new entry point for that functionality.

**Comment by spacecowboy** [comment]
@Kerruba is this the desktop version or the standalone version?

**Comment by Kerruba** [comment]
@spacecowboy what's the difference sorry...

**Comment by spacecowboy** [comment]
@Kerruba when you downloaded neo4j, did you download a `dmg`-file or a `tar.gz`-file?

**Comment by Kerruba** [comment]
`dmg`-file

**Comment by lgibelli** [comment]
I'm experiencing the same problem. I'm running neo4j 3.1 for macosx (dmg package).

It happens with all command line tools:

bash-4.4$ ./neo4j-admin import 
Could not find or load main class org.neo4j.commandline.admin.AdminTool
bash-4.4$ ./neo4j-import 
Could not find or load main class org.neo4j.tooling.ImportTool
bash-4.4$ ./neo4j-shell 
Could not find or load main class org.neo4j.shell.StartClient

Dirty workaround: 

   $ sudo mkdir /Applications/Neo4j\ Community\ Edition\ 3.1.0.app/Contents/Resources/app/lib
   $ sudo cp /Applications/Neo4j\ Community\ Edition\ 3.1.0.app/Contents/Resources/app/bin/neo4j-desktop-3.1.0.jar /Applications/Neo4j\ Community\ Edition\ 3.1.0.app/Contents/Resources/app/lib

Looks like a regression from https://github.com/neo4j/neo4j/issues/6084

**Comment by spacecowboy** [comment]
@lgibelli thanks for the info

**Comment by ersel** [comment]
Experiencing the same issue here

Mac OS Yosemite 10.10.5
Neo4j Community Edition 3.1.0 installed via dmg file

@lgibelli 's workaround works...

**Comment by DiegOrtega** [comment]
ey! neo4j developers how is it going that fix?

**Comment by fblamanna** [comment]
Same error here with Neo4j 3.1.2 on OS 10.11.6

**Comment by ric-bianchi** [comment]
I confirm that @lgibelli workaround works fine with Neo4j 3.1.3 community edition dmg on MacOS 10.12.4.  Thanks, @lgibelli !

**Comment by Izhaki** [comment]
OK. It's been more than 6 months since this ticket was create, still no fix?

Same issue with 3.2.0, tar, OS 10.10.5

**Comment by Izhaki** [comment]
OK, I may have been wrong about it. If I download the package and extract manually it works, but using `download-cli` with the extract flag messes things up it seems.

**Comment by AvinashGupta** [comment]
@lgibelli thanks! it works.

**Comment by jzym** [comment]
Same error on v3.2.1 on MacOS 10.12.5, but @lgibelli is working, thanks.

**Comment by ericvangeem** [comment]
Thanks to [this SO post](https://stackoverflow.com/questions/33848211/error-could-not-find-or-load-main-class-org-neo4j-shell-startclient), it seems that using the bin/ and lib/ directory files from the tar.gz distribution fixes the problem. I just dropped those two folders into my existing Neo4j installation and it works fine as a result.

**Comment by markburns** [comment]
Confirmed fix from @lgibelli - https://github.com/neo4j/neo4j/issues/8347#issuecomment-267845383 

Updated command for v3.2.2 for convenience:

```
sudo mkdir /Applications/Neo4j\ Community\ Edition\ 3.2.2.app/Contents/Resources/app/lib
sudo cp /Applications/Neo4j\ Community\ Edition\ 3.2.2.app/Contents/Resources/app/bin/neo4j-desktop-3.2.2.jar /Applications/Neo4j\ Community\ Edition\ 3.2.2.app/Contents/Resources/app/lib
```

**Comment by pksuf07** [comment]
For v3.2.3, it didn't work for me. Instead, I copied neo4j-desktop-3.2.3.jar to /Library/Java/Extensions and it works. Please correct me if I did something wrong.

**Comment by szeitlin** [comment]
worked for me for 3.2.3

**Comment by SharvariNagesh** [comment]
@pksuf07 , with version 3.3.0, copying the jar file to lib did not work but copying it to /Library/Java/Extensions worked. Thanks for the answer

**Comment by lhesterberg** [comment]
Has anyone encountered this issue with Linux, and if so is there an equivalent fix?

**Comment by ajaradv** [comment]
@lhesterberg, I encountered a similar user, running as sudo allowed me to run the import tool from both neo4j-admin and neo4j-import...

**Comment by chrisvest** [comment]
Lot's of different issues are floating around in the comments. The original problem is solved by the new Neo4j Desktop app, which is effectively just using the tar.gz version behind the nice user interface.
