### ISSUE TITLE
Complete list of configuration options missing dbms.connector.http.enabled

### ISSUE THREAD

**Issue by heavydawson** [neo4j/neo4j#8359]
I was trying to reduce the neo4j.conf file to the smallest possible set of values (in order to use as many defaults as possible). I began with an empty neo4j.conf file, and I got the following error when I tried to start Neo4J:
```
2016-11-14 13:02:04.941+0000 WARN  Config file [/Applications/neo4j-community-3.1.0-M13-beta3/conf/neo4j.conf] does not exist.
2016-11-14 13:02:04.968+0000 ERROR Failed to start Neo4j on unknown address. An HTTP connector must be configured to run the server
java.lang.IllegalArgumentException: An HTTP connector must be configured to run the server
	at org.neo4j.server.AbstractNeoServer.lambda$new$0(AbstractNeoServer.java:158)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.neo4j.server.AbstractNeoServer.<init>(AbstractNeoServer.java:157)
	at org.neo4j.server.CommunityNeoServer.<init>(CommunityNeoServer.java:69)
	at org.neo4j.server.CommunityNeoServer.<init>(CommunityNeoServer.java:63)
	at org.neo4j.server.CommunityBootstrapper.createNeoServer(CommunityBootstrapper.java:43)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:90)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:68)
	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:28)
```

Looking the shipped config file example, it was obvious the property that needed to be added was:

`dbms.connector.http.enabled=true
`
Once I added the line alone to my empty neo4j.conf, the server started without issue.
However, the config property above is not listed here:
http://neo4j.com/docs/operations-manual/beta/reference/#configuration-settings

**Neo4j Version:** 3.1M13-beta3  
**Operating System:** OSX 10.11.6  
**API:** All

### Steps to reproduce
1. Download neo4j 3.1.0-M13-Beta3
2. Remove (or backup) neo4j.conf from the <DIST>/conf folder
3. Attempt to start neo4j with <DIST>/bin/neo4j start
4. Observe errors in <DIST>/logs/neo4j.log

### Expected behavior
* Neo4j should default to using HTTP connector?
* HTTP/HTTPS/BOLT-enabling properties should be documented here:
http://neo4j.com/docs/operations-manual/beta/reference/#configuration-settings

### Actual behavior
* Neo4J doesn't use any connector by default
* No documentation around enabling connectors in config reference

**Comment by spacecowboy** [comment]
Thanks for the report. 

We are aware of the connectors not being documented in the configuration section of the manual (they are documented elsewhere though, for example here: https://neo4j.com/docs/operations-manual/current/deployment/post-installation/#connectors) and aim to have this rectified soon.

Regarding the functionality, it is working as intended. We no longer default any connectors to on in the code itself because that introduced problems in the past. In fact, your minimal config is surprisingly minimal since you have not defined the type of the connector:

```
dbms.connector.http.enabled=true
dbms.connector.http.type=HTTP
```

is a future proof minimal config file.

**Comment by heavydawson** [comment]
Thanks spacecowboy. Appreciate the clarification

**Comment by jjaderberg** [comment]
The settings reference contains entries for connectors and a few other outliers (like JVM options and Windows service name) from 3.2 on--see [here](https://neo4j.com/docs/operations-manual/current/reference/configuration-settings/) soon or preview [here](https://neo4j.com/docs/operations-manual/preview/reference/configuration-settings/) now.
The tooling happened at neo4j/neo4j-documentation#26.
The reference entries are short on detail so the [connectors config page](https://neo4j.com/docs/operations-manual/current/configuration/connectors/) remains the best place to go to read about configuring the connector settings.

**Comment by jessitron** [comment]
for the record (since I found this on Google and others might too), I also needed

`dbms.connector.bolt.enabled=true`

in my config file.
