### ISSUE TITLE
Cypher WHERE clause error in 2.0.0 M02

### ISSUE THREAD

**Issue by RichSimon** [neo4j/neo4j#836]
Using v1.9.3 RC2, this Cypher query works fine. Using 2.0.0 M02, my console hangs and the Java process seems to run away unless I remove the constraining, highlighted part of the where clause (and m.strength > 0.8):

start n1=node:entities('entityID:_'), n2=node:entities('entityID:_')
match n1-[:has_address]->add1-[m:MATCHES_TO]-add2<-[:has_address]-n2,
    add1-[:has_street]-street1, add2-[:has_street]-street2
where (m.strength < 1 and m.strength > 0.8)
return distinct add1.addressID, n1.entityID, street1.line1, add2.addressID, street2.line2, m.strength limit 1;

**Comment by sherfert** [comment]
I am assuming this issue has been solved in the meantime with newer versions @RichSimon ?

**Comment by sherfert** [comment]
I am closing this now. Feel free to reopen if needed!
