### ISSUE TITLE
Feature Request - ignoring "null" properties in CREATE (n {map})

### ISSUE THREAD

**Issue by rherschke** [neo4j/neo4j#841]
Hi,

when executing the following cypher query:

```
CREATE (n {map})
```

with a Map as a query parameter `map` that contains null values for some keys, please ignore these keys and don't create properties for these keys.

Regards,
Robert

**Comment by aseemk** [comment]
This issue is older, but FYI a dupe issue was created that has some more details: #3870.

**Comment by chrisvest** [comment]
Looks like nulls are now ignored for CREATE statements.
