### ISSUE TITLE
Add methods for getting ids of Relationship's start/end node

### ISSUE THREAD

**Issue by cypressious** [neo4j/neo4j#8411]
In a performance ciritical method, I want to compare a relationship's end/start node id to some value. I don't need the actual node for that.

Currently, I need to get the start/end node which is moderately expensive, compared to just returning a `long`.

AFAIK, there is already a method for that: https://github.com/neo4j/neo4j/blob/6a089b33fae53fe184c7155954fcbf10e7785644/community/kernel/src/main/java/org/neo4j/kernel/impl/core/RelationshipProxy.java#L134.

**Comment by MishaDemianenko** [comment]
@cypressious fixed by https://github.com/neo4j/neo4j/pull/8721
