### ISSUE TITLE
neo4j-import is perhaps overly strict on parsing spaces

### ISSUE THREAD

**Issue by ghoetker** [neo4j/neo4j#8420]
- Neo4j version: 3.0.7
- Operating system: MacOS 10.12
- API/Driver: Terminal

Following the tutorial for using the bulk CSV importer with multiple  files, I issued the following command:

    $NB/neo4j-import --into test.db --nodes "header.csv, patents.csv" --delimiter "|" --skip-duplicate-nodes

# Expected behavior

Import of the records in patents.csv.

# Actual behavior

Zero records being imported. Looking at the feedback generated by Neo4J, it was clear (in retrospect) that only the header.csv file was ingested, but no hint of why.

Through the wonderful StackOverflow community, I learned that the problem was the space after the comma in "header.csv, patents.csv". Removing that space made everything work fine.

As a naive user, this seems to perhaps be overly strict parsing behavior, especially since the list of files is enclosed within quotes.  Possible enhancements include:

* Allowing less strict parsing, so that my original command would run. Or, if that were not possible
* Noting the requirement to have no spaces in the file list as part of the tutorial and other documentation (just as the need to enclose the list in quotes is currently noted) &/or
* Generating a more informative error message.
 
Wonderful program. Thanks for considering.

**Comment by klaren** [comment]
Should be solved by https://github.com/neo4j/neo4j/pull/12343
