### ISSUE TITLE
Impossible nested logical expressions in Cypher

### ISSUE THREAD

**Issue by rduga** [neo4j/neo4j#843]
Neo4j cypher query language doesn't support nested logical expressions, i.e.:

This is valid query expression and returns true:

    start n=node(3) return 1 <> 2

But this is not:

    start n=node(3) return (1 <> 2) = true

it should return also true, but it returns error:

Error: string matching regex `\z' expected but `=' found

Similar queries like (which also fail):

    start n = node(3) return not(true = true) = true
    start n = node(3) return (true <> true) = true

(queries tested on http://docs.neo4j.org/chunked/stable/query-where.html when click on try this query live)

**Comment by jakewins** [comment]
This is now resolved: http://console.neo4j.org/r/hnmv5n
