### ISSUE TITLE
USING INDEX causes error even though property value comparisons are now supported

### ISSUE THREAD

**Issue by astrosam** [neo4j/neo4j#8463]
Neo4j version: 3.1.0-M13-beta3
Operating system: OSX (10.11.6)
Using the neo4j browser

**Steps to reproduce**
1. Create an index:

       CREATE INDEX ON :Foo(id)

2. Execute query below, and look at profile results (you should see that the index is used when comparing the property values `f.id` and `row.id`):

       PROFILE
       WITH {id: 123} AS row
       MATCH (f:Foo {id: row.id})
       RETURN f

3. Execute query below (which simply adds an appropriate `USING INDEX` clause), and observe that it causes error message:

       PROFILE
       WITH {id: 123} AS row
       MATCH (f:Foo {id: row.id})
       USING INDEX f:Foo(id)
       RETURN f

- Expected behavior: #2 and #3 should cause essentially same profile. Certainly, #3 should not cause error.

- Actual behavior: #3 causes error, presumably because of comparison between 2 properties.

**Comment by Mats-SX** [comment]
This has been fixed by #8500.
