### ISSUE TITLE
cypher start node by unique constraints

### ISSUE THREAD

**Issue by Ming-Lei** [neo4j/neo4j#8480]
use the neo4j 3.0.6
I create some unique constraints by browser
```
CREATE CONSTRAINT ON (c:company)
ASSERT c.companyId IS UNIQUE
```
this is the result of `:schema`
```
Indexes
  ON :company(companyId) ONLINE (for uniqueness constraint) 
  ON :geti(getiId)       ONLINE (for uniqueness constraint) 
  ON :person(personId)   ONLINE (for uniqueness constraint) 

Constraints
  ON (company:company) ASSERT company.companyId IS UNIQUE
  ON (person:person) ASSERT person.personId IS UNIQUE
  ON (geti:geti) ASSERT geti.getiId IS UNIQUE
```
but when I use the `start n=node:companyId(companyId='717314') return n`
return a error `Index `companyId` does not exist`
so the uniqueness constraint can't used for start node?
or what's the correct usage?

**Comment by chrisvest** [comment]
The `start` syntax is specific for manual indexes: http://neo4j.com/docs/developer-manual/current/cypher/#query-start

When you use schema indexes, like in your example, you need to use the `match` clause: http://neo4j.com/docs/developer-manual/current/cypher/#query-match

So your query should probably look something like this:
`match (n) where n.companyId = '717314' return n`
