### ISSUE TITLE
Don't delete labels that don't used

### ISSUE THREAD

**Issue by kienbui1995** [neo4j/neo4j#8484]
- Neo4j version: 3.0.7
- Operating system: Windows 10
- API/Driver: Cypher

**Steps to reproduce**
1. Create a normal database with nodes, relationships, property. 
2. Delete all of nodes and relationships.
### Expected behavior
Don't want to see all of labels 
### Actual behavior
Still exist labels without node or relationship.

I don't like it because I see so many labels that the don't used.	
I think it is a bug of Neo4j's browser. It show all label include label that don't used or remove all of nodes and relationships

**Comment by oskarhane** [comment]
Hi @kienbui1995. I have a hard time reproducing this issue.
What's response do you get back when querying for the labels like: `CALL db.labels()`?

**Comment by kienbui1995** [comment]
when CALL db. labels(), I see labels, but I don't think that they still exist. I want to delete all of them because I delete all of nodes.

**Comment by oskarhane** [comment]
Thanks, I just wanted to confirm that it's not a Neo4j Browser bug.
If you `MATCH (n) RETURN n LIMIT 10` you get nothing back?

**Comment by kienbui1995** [comment]
Sure, I try 
```MATCH (n) RETURN n LIMIT 10``` and nothing!
![image](https://cloud.githubusercontent.com/assets/10261351/20974408/a66e0e64-bcce-11e6-8354-84907529e217.png)

**Comment by Mats-SX** [comment]
First raised at https://github.com/opencypher/openCypher/issues/161.

**Comment by spacecowboy** [comment]
This is not currently supported but might be in the future. Labeling as enhancement.

**Comment by webtic** [comment]
Had a similar issue of labels not being stuck.
Found that for the labels which were stuck a CONSTRAINT was still defined. 
After removing the constraint the label is removed automagically.

Browser: 3.1.4  Neo 3.3.4

**Comment by craigtaverner** [comment]
I'm hoping that @webtic answer is sufficient and will close this issue. If that is not sufficient, please feel free to re-open it.

**Comment by rogererens** [comment]
Sorry, it's not sufficiently clear to me :-/
I have the same issue that after playing with the Northwind Graph (using :play northwind-graph), I wanted to get rid of this demo data (using MATCH (n) DETACH DELETE n).

Now in the side bar, with the 'Database Information' tab selected, the sidebar still shows all labels that were used in the demo; also, all Property Keys are still shown in the side bar. I have the same image as kienbui1995 posted.

I would expect the sidebar to show no labels and property keys anymore after having deleted all nodes and relationships.

Being a newbie, removing 'the constraint' (which one?) on the label is not straightforward (CALL db.constraints did not return data)

**Comment by Romulus79** [comment]
If you have constraints or indexes related to the empty nodes label, they'll be displayed. After deleting those constraints, indexes etc , the labels will disappear.  I encountered this issue myself.

**Comment by faaizshah** [comment]
@Romulus79 is very much righ.
I did solve my problem as well.
Just type in neo4j browsers  `:Schema` . It will display list  as below.
 
`Indexes`
  `ON :Label1(id) ONLINE `
  `ON :Label2(id) ONLINE`

Now drop If there are no nodes in Label1, then you can simply drop it by 

`DROP INDEX ON :Label1(id)`

This worked for me!
