### ISSUE TITLE
How to implement neo4j with microservices?

### ISSUE THREAD

**Issue by Medhavin** [neo4j/neo4j#8495]
I am building an application based on microservices approach and want to use different instances of neo4j for different microservices.

I have two independent services namely creative and project with their own neo4j instances. What would be the best way to create a relationship between a node of creative and a node of project?

**Comment by spacecowboy** [comment]
Please take questions such as this to http://stackoverflow.com/questions/tagged/neo4j for faster feeback.

Github Issues are for bug reports and feature requests.
