### ISSUE TITLE
Cypher: Relationship functions missing

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#85]
@systay: 'We need functions that can return start node from a relationship. It would allow for checking relationship directions in Cypher:

```
START a=node(*)
MATCH a-[r]-()
RETURN a,r, endNode(r) as startNode
```

'

**Comment by ooker777** [comment]
the link is dead now

**Comment by jexp** [comment]
https://neo4j.com/docs/cypher-manual/current/functions/scalar/#functions-startnode

@davidoliverSP2 for redirects of previous docs
