### ISSUE TITLE
Neo4j process still in memory after stopping and closing the window

### ISSUE THREAD

**Issue by RaderDave** [neo4j/neo4j#8504]
Had a version mismatch with downloaded apoc jar files. After stopping neo4j and closing the window, I tried to remove the jar file and got the error that the move could not be performed because it was still in use by neo4j-ce.  Used the task manager to confirm that it was still in memory

**Neo4j Version:** 3.0.6 Community Edition  
**Operating System:** Windows10 

### Steps to reproduce
1. Using the neo4j console, stop the currently running database
2. Close the console window
3. Open Windows Explorer and navigate to c:/Program Files/Neo4j CE 3.0.6/plugins
4. Try to move one of the jar files to a different folder (try back to downloads)

### Expected behavior
move should work

### Actual behavior
Error stating jar still in use.  A restart of Windows clears the memory and the jar file can be moved just fine.  The "assets" attached to this are a screen shot of Task Manager showing neo4j-ce still in memory (after stopping and closing).  Not obvious if the image paste worked, so also saved as a file and uploaded that.

![image](https://cloud.githubusercontent.com/assets/24416805/21123442/9450563e-c08d-11e6-9a81-b668b9396276.png)

![capture](https://cloud.githubusercontent.com/assets/24416805/21123437/89c6efc0-c08d-11e6-8c23-dcc6d757942d.JPG)

**Comment by chrisvest** [comment]
Did you download and install via the `.exe` or the `.zip` file? By "console" do you mean command line, or a GUI? If you are using the `.exe`, did you quit the task bar Neo4j process? There would be an icon (unless Windows is somehow hiding it) for it in the task bar, if the desktop process has not been stopped (even though the database has been stopped).

**Comment by RaderDave** [comment]
I'm pretty sure I downloaded and installed off the .zip file (no longer on
the PC). I run off the .exe and use the GUI (see pasted in image).


![image](https://cloud.githubusercontent.com/assets/24416805/21189289/0e66d90c-c1d3-11e6-984b-483f1021f765.png)


After stopping, I close the GUI by clicking on the "X" button.

Not sure if this is helpful ... here is an image of the bin folder (running
Win10 on a machine upgraded from Win8, hence the folder naming):


![image](https://cloud.githubusercontent.com/assets/24416805/21189308/1b884c06-c1d3-11e6-9b4e-2a72cdad9610.png)

**Comment by chrisvest** [comment]
Your images are not showing on Github.

**Comment by RaderDave** [comment]
edited on github to have the images as githubusercontent assets

**Comment by chrisvest** [comment]
@RaderDave Thanks, yes, this is a feature; even if you close the main window, Neo4j can still run in the background. To stop the process completely, you need to right-click on the task bar icon, and choose _Exit_.
![screen shot 2016-12-15 at 13 21 14](https://cloud.githubusercontent.com/assets/7993/21223889/d1dad414-c2c9-11e6-817b-bfd91f02182a.png)
