### ISSUE TITLE
Method createRelationshipTo hangs up 

### ISSUE THREAD

**Issue by retrostyle** [neo4j/neo4j#851]
Hey i use the Community Neo4J 1.9 Stable Release Version and i have big Problem,
if i create a Relation with this Line,

`Relationship createtRelation = sourceNode.createRelationshipTo(targetNode, relation);`

the Embedded Transaction Hangs Up and i dont now why... i think it is a Neo4J internel problem!?
And some minutes later i got this Exception:

`WARNING: GRIZZLY0023: Interrupting idle Thread: http-thread-pool-8080(1)
  (com.sun.grizzly.http.KeepAliveThreadAttachment timedOut)`

Greetz Chriss

**Comment by jakewins** [comment]
Since there's no reply in the past two years, closing this as per @tinwelint's comment above.
