### ISSUE TITLE
[Rest api] diacritics gets malformed when using batches

### ISSUE THREAD

**Issue by bazo** [neo4j/neo4j#852]
as i already explained on jadell/neo4jphp https://github.com/jadell/neo4jphp/issues/78 thinking, it was a bug in the library, but found it is a bug directly in neo4j

if you do a request like with property values containing diacritics, the diacritics gets malformed. 
 ```
post /db/data/batch [{"method" : "POST", "to" : "/node", "body" : {"name" : "ľščťžýáíéúäôň", "hej": "hou"}}]
````
if you delete the "hej" property so the request look like this
```
post /db/data/batch [{"method" : "POST", "to" : "/node", "body" : {"name" : "ľščťžýáíéúäôň"}}]
````
neo4j throws a BadInputException

There's no problem with diacritics when not using batches.

tested on neo4j 1.8.2 and 1.9 stable.

**Comment by jakewins** [comment]
It's been two years with no reply here; UTF-8 should work without issue. Please re-open this ticket if the issue persists, and if so, please send us the `messages.log` file found under `data/graph.db/`
