### ISSUE TITLE
Feature Request: Extend the flexibility of CASE WHEN

### ISSUE THREAD

**Issue by simoami** [neo4j/neo4j#8542]
## Description

CASE / WHEN does not allow embedding other operators like CREATE, MERGE or DELETE.

## Use Case

Delete an activity node in a chain. Consider the newsfeed graph:
http://neo4j.com/docs/2.3.8/cypher-cookbook-newsfeed.html

Given `(root)-[:STATUS]->(a1)-[:NEXT]->(a2)-[:NEXT]->(a3)`, where root is the user profile node and a1, a2, a3 are the user activities. The user has the option to delete an activity node:
- if we delete (a1), the relationship to the left [:STATUS] needs to be recreated between (root) and (a2), like so:
`(root)-[:STATUS]->(a2)-[:NEXT]->(a3)`
- if we take (a2) out, the relationship to the left [:NEXT] needs to be recreated between (a1) and (a3), like so:
`(root)-[:STATUS]->(a1)-[:NEXT]->(a3)`

Unless there is a better way to create a cypher query that fulfills the above requirement, the following would only be possible if CASE WHEN is extended to allow CREATE statements.

```
MATCH(a:Activity) WHERE ID(a) = {id_of_activity_to_delete}
MATCH (n1)-[r1]->(a)
OPTIONAL MATCH (a)-[r2]->(n2)
CASE TYPE(r1) WHEN "NEXT" THEN CREATE (n1)-[:NEXT]->(n2)
ELSE CREATE (n1)-[:STATUS]->(n2) END
DETACH DELETE a
```

**Comment by spacecowboy** [comment]
@simoami Not sure if I'd consider it better, but you can write a cypher query that does it. For example:

```
MATCH (left)-[:STATUS]->(a)-[r]->(right)
WHERE a.name = $name
WITH a, left, right
     MERGE (left)-[:STATUS]->(right)
RETURN a

UNION

MATCH (left)-[:NEXT]->(a)-[r]->(right)
WHERE a.name = $name
WITH a, left, right
     MERGE (left)-[:NEXT]->(right)
RETURN a

UNION

MATCH (a)
WHERE a.name = $name
WITH a
     DETACH DELETE a
RETURN a
```

Where I for convenience used a query parameter **name**.  

You can create an example graph to test it on with 

```
MERGE p=(:User {name:"bob"})-[:STATUS]->(:Status {date:1, name:"bob_s1", text:"bobs status 1"})-[:NEXT]->(:Status {date:4, name:"bob_s2", text:"bobs status2"})-[:NEXT]->(:Status {date:9, name:"bob_s3", text:"bobs status3"}) RETURN p;
```

And choose the value of **name** to be `bob_s1`, `bob_s2`, or `bob_s3`. 

And you can of course view the result with a query like

```
MATCH p=(:User {name:"bob"})-[*]-(:Status) RETURN p;
```

**Comment by simoami** [comment]
@spacecowboy Thanks for the great trick. It works well as a workaround. But compared to the CASE WHEN syntax it's rather verbose and not as intuitive, if you agree.

**Comment by Mats-SX** [comment]
Hello @simoami and thanks for reaching out to us with this proposal.

There aren't currently any plans to extend the `CASE` expression. We're more likely looking towards replacing it with something that fits better with the rest of the language, but there aren't any concrete plans made yet. I hope you find the above workaround acceptable.

All the best
Mats

**Comment by simoami** [comment]
Yep workaround works for now. Thanks!
