### ISSUE TITLE
Does PerformsWrites not work? 

### ISSUE THREAD

**Issue by fcbruce** [neo4j/neo4j#8543]
Hi all,

I extends neo4j by procedure with an annotation `PerformsWrites`, however there is an error occurred while creating an node and setting a unique property. I think maybe it conflicts while the operation is concurrency.

I noticed that the annotation `PerformsWrites` is deprecated after 3.1.0. If I should update my neo4j and use `mode = Mode.WRITE` to fix it.

Neo4j version: 3.0.7
Operating System: CentOS 7.4

**Comment by fbiville** [comment]
Would you mind providing the stack trace when the error you mention occurs? Thanks in advance!

**Comment by fcbruce** [comment]
@fbiville Hi, I could only get the error message like this: 

> Neo.ClientError.Procedure.ProcedureCallFailed, error message: Failed to invoke procedure \`graph.calculateTimeOfAddConnection\`: Caused by: org.neo4j.graphdb.ConstraintViolationException: Node 1886321 already exists with label User and property "userId"=[*******]

The property `userId` has a unique constraint. This error only occurs when send two request that need to create a node and set `userId` at same time. And the procedure would find the node by Label and the property first, if it doesn't found then create the node and set the property.

Thanks.

**Comment by fcbruce** [comment]
And I tried to use `synchronized` at a static method to create the node. Unfortunately, the deadlock occurred.

**Comment by jexp** [comment]
Can you share the code of your procedure? Why don't you just use merge which takes the proper locks. 

Von meinem iPhone gesendet

**Comment by fcbruce** [comment]
@jexp Hi, the code with synchronized is :
```
  @PerformsWrites
  private static Node findOrCreate(GraphDatabaseService db, String id) {
    Node node = db.findNode(LABEL, UNIQUE_KEY, id);
    if (node == null) {
      synchronized (NeighborsDetector.class) {
        node = db.findNode(LABEL, UNIQUE_KEY, id);
        if (node == null) {
          node = db.createNode(LABEL);
          node.setProperty(UNIQUE_KEY, id);
          node.setProperty(JUDGE_PROPERTY, System.currentTimeMillis());
        }
      }
    }
    return node;
  }

  @Procedure("graph.addConnection")
  @PerformsWrites
  public void addConnection(@Name("hostId") String hostId, @Name("hostRegisterTime") long hostRegisterTime, @Name("guestId") String guestId) {

    Node host = findOrCreate(db, hostId);
    Node guest = findOrCreate(db, guestId);

    host.setProperty(JUDGE_PROPERTY, hostRegisterTime);

    if (hostId.equals(guestId)) {
      return ;
    }

    for (Relationship relationship : host.getRelationships()) {
      if (relationship.getEndNode().equals(guest)) {
        return ;
      }
    }

    host.createRelationshipTo(guest, RELATIONSHIP);
  }
```
It occurred deadlock.

And the code occurred `ConstraintViolationException` is :
```
  @Procedure("graph.addConnection")
  @PerformsWrites
  public void addConnection(@Name("hostId") String hostId, @Name("hostRegisterTime") long hostRegisterTime, @Name("guestId") String guestId) {

    Node host = db.findNode(LABEL, UNIQUE_KEY, hostId);
    Node guest = db.findNode(LABEL, UNIQUE_KEY, guestId);

    if (host == null) {
      host = db.createNode(LABEL);
      host.setProperty(UNIQUE_KEY, hostId);
    }

    host.setProperty(JUDGE_PROPERTY, hostRegisterTime);

    if (hostId.equals(guestId)) {
      return ;
    }

    if (guest == null) {
      long guestTime = System.currentTimeMillis();
      guest = db.createNode(LABEL);
      guest.setProperty(UNIQUE_KEY, guestId);
      guest.setProperty(JUDGE_PROPERTY, guestTime);
    }

    for (Relationship relationship : host.getRelationships()) {
      if (relationship.getEndNode().equals(guest)) {
        return ;
      }
    }

    host.createRelationshipTo(guest, RELATIONSHIP);
  }
```

How could I use merge in procedure?

Thanks.

**Comment by fcbruce** [comment]
The variable `db` is `GraphDatabaseService`.

**Comment by fbiville** [comment]
You should avoid this lock pattern as much as possible.
Either rely on Cypher [`MERGE`](http://neo4j.com/docs/developer-manual/current/cypher/clauses/merge/) to create a unique node or use the [`Schema`](https://neo4j.com/docs/java-reference/current/javadocs/org/neo4j/graphdb/schema/Schema.html) API to enforce unicity constraint.

**Comment by fcbruce** [comment]
Hi @fbiville , 
Well, Cypher `MERGE` is a solution to do it. But I want to know if there is any other way to solve the concurrency that several requests to create the same unique node. It seems that the neo4j procedure(a jar in `plugins` folder) will create the node and then commit to the database(I'm not sure if my guess is correct). And the `Schema` API seems to get the index and the constraint.
Thanks.

**Comment by fcbruce** [comment]
And I tried to catch the `ConstraintViolationException` then looked for the node, it returned `null`.

**Comment by jexp** [comment]
The problem is that the transaction has already started when you start your synchronized block and your synchronized ends before the transaction commits, so when your synchronized ends the other concurrent transaction continues and the two nodes.

*This is quite advanced stuff are you sure you really need it??*

The transaction instance which you can get injected `@Context public KernelTransaction tx;` can acquire locks on nodes, relationships. In the Kernel API there are also means to lock on index + property-name.

**Comment by jexp** [comment]
I suggest to use `MERGE`.

**Comment by fcbruce** [comment]
Well, I use `MERGE` finally. Thanks.
