### ISSUE TITLE
Unexpected Type mismatch error using tail() in Cypher

### ISSUE THREAD

**Issue by dhimmel** [neo4j/neo4j#8546]
Run queries at https://neo4j.het.io/browser/ (which is currently running Neo4j 3.1.0 as [described here](https://thinklab.com/discussion/hosting-hetionet-in-the-cloud-creating-a-public-neo4j-instance/216), queries from [this discussion](https://thinklab.com/discussion/decomposing-the-dwpc-to-assess-intermediate-node-contributions/228#3)).

The following query works:

```
MATCH path = (n0:Compound)-[:BINDS_CbG]-(n1)-[:PARTICIPATES_GpPW]-
  (n2)-[:PARTICIPATES_GpPW]-(n3)-[:ASSOCIATES_DaG]-(n4:Disease)
USING JOIN ON n2
WHERE n0.name = 'Enalapril'
  AND n4.name = 'coronary artery disease'
  AND n1 <> n3
WITH
  path,
[
  size((n0)-[:BINDS_CbG]-()),
  size(()-[:BINDS_CbG]-(n1)),
  size((n1)-[:PARTICIPATES_GpPW]-()),
  size(()-[:PARTICIPATES_GpPW]-(n2)),
  size((n2)-[:PARTICIPATES_GpPW]-()),
  size(()-[:PARTICIPATES_GpPW]-(n3)),
  size((n3)-[:ASSOCIATES_DaG]-()),
  size(()-[:ASSOCIATES_DaG]-(n4))
] AS degrees, n3, n4
RETURN
  n4.name AS target_name,
  type(relationships(path)[3]) AS target_edge_type,
  n3.name AS n3_name,
  sum(reduce(pdp = 1.0, d in degrees| pdp * d ^ -0.4)) AS DWPC
ORDER BY DWPC DESC
```

Changing `type(relationships(path)[3])` to `type(tail(relationships(path)))` throws the following error:

```
Type mismatch: expected Relationship but was List<Relationship> (line 21, column 8 (offset: 590))
"  type(tail(relationships(path))) AS target_edge_type,"
```

However, switch `tail` to `head` and this query works.

**Comment by craigtaverner** [comment]
The function `head()` returns the first element of the list, while the function `tail()` returns the _rest of the list_ (which is also a list). This means the behaviour reported above is correct.

See https://neo4j.com/docs/cypher-refcard/current/ (search for 'tail')

Are you perhaps after the type of the last element? Perhaps you could try `type(last(relationships(path)))`.

**Comment by dhimmel** [comment]
Thanks @craigtaverner -- confirming that I confused `tail` with `last`.
