### ISSUE TITLE
Compliance to a predefined schema in neo4j

### ISSUE THREAD

**Issue by aahoo** [neo4j/neo4j#8565]
I am thinking of using a graph DB to store [IFC](https://en.wikipedia.org/wiki/Industry_Foundation_Classes#Architecture) data. Ideally, the DB should provide a way to define all the rule types defined in the IFC schema. However, I don't think there are any such databases because some of the rule types in IFC are very complex and requires querying the DB. Others are simple, like uniqueness of GUID, existence of mandatory attributes, or [data validation](https://en.wikipedia.org/wiki/Data_validation#Different_kinds_of_validation). Neo4j seem to have a few constraint enforcing methods:

> Neo4j helps enforce data integrity with the use of constraints. Constraints can be applied to either nodes or relationships. Unique node property constraints can be created, as well as node and relationship property existence constraints.

Are there other methods that can ensure compliance of entered data with a predefined schema?

If not, is there anything planned?

If not, please consider this post as a feature request.

**Comment by jexp** [comment]
As you noted there are currently existence constraints for properties. We want to extend those capabilities for optional schema in the future.

Other constraints can be enforced manually, e.g. with transaction event handlers.

My colleague wrote an article on how to do that with the example of a schema declared as RDF Ontology: https://jesusbarrasa.wordpress.com/2016/04/06/building-a-semantic-graph-in-neo4j/

Hope that helps.

**Comment by aahoo** [comment]
Thanks @jexp. That was very helpful.
