### ISSUE TITLE
Node returns incorrect empty array property type

### ISSUE THREAD

**Issue by bHacklv** [neo4j/neo4j#8587]
When I create Node(s) with property that has *empty array value* of *any type* (long[], Long[], double[], etc.), when I read this(these) Node(s) from the store - the above properties type is *ALWAYS* empty String[] array. I would expect to receive correct initial array type...

**Neo4j Version:** 3.1
**Operating System:** Win7

### Steps to reproduce
1. Create Node with Empty Array Property Value Long[] type
2. Read Node from store
3. Read above property
4. Assert Property's type

### Expected behavior
instanceof Long[].class

### Actual behavior
instanceof String[].class

### 'Pseudo' test code
```java
final Transaction transaction = beginTransaction();
final Map<String, Object> queryParam = new HashMap<>(1);
queryParam.put("val", new Long[0]);
transaction.run("CREATE (n:`Default Label`) SET n.key = {val}", queryParam).close()
final Node n = (Node) execute.next().get("n");
assertThat(((ClientNodeWrapper) n).getProperty("key")).isInstanceOf(Long[].class);

===

Expecting:<[]>to be an instance of: <java.lang.Long[]>but was instance of:<java.lang.String[]>
```

### My investigation
I've investigated how the property value is being read:
```java
433: NodeProxy#getAllProperties -> propertyCursor.get().value()
220: StorePropertyPayloadCursor#value() -> type()
337: PropertyType#getPropertyTypeOrNull() -> typeIdentifier( propBlock );
-> returns 10 (Array) // correct!
245: StorePropertyPayloadCursor#arrayValue()
215: StorePropertyPayloadCursor#arrayValue() -> readArrayFromBuffer( buffer )
316: StorePropertyPayloadCursor#readArrayFromBuffer() -> buffer.get() -> returns 9
320: StorePropertyPayloadCursor -> if ( typeId == PropertyType.STRING.intValue() ) -> true....
```
So I assume that either the property type is incorrectly read from the store, or when empty array is written to the store, it defaults(?) or incorrectly written as empty String array...

While investigating writes, I've got down till ``org.neo4j.cypher.internal.ExecutionEngine`` and I was not able to dl source code for it.

### BOLT
**API:** neo4j-java-driver 1.1.0

When using Driver (BOLT) the problem is the same, but the return type is different: *java.util.Collections$EmptyList*.

I found that the type is being 'lost' in:
```
182: ExplicitTransaction#run -> value(statementParameters)
232: Values#value -> value( entry.getValue() )
// if property was of type long[]
89: Values#value -> if ( value instanceof long[] ) { return value( (long[]) value ); } // creates ListValue with Value[]
// if property was of type Long[]
94: Values#value -> if ( value instanceof Object[] ) { return value( Arrays.asList( (Object[]) value )); } // creates List<Object> which is then iterated over and passed into ListValue as Value[] which is returned same as with primitives.
```

So both driver (bolt) and database transforms empty arrays and looses the types. Is this then design decision?

**Comment by spacecowboy** [comment]
any idea on this @Mats-SX?

**Comment by Mats-SX** [comment]
@bHacklv No, I don't think this is a conscious design decision, but rather a consequence of us storing empty Cypher lists as string arrays in the kernel (e.g. `SET n.prop = []`).

I'll look into fixing this by preserving the input array also for empty arrays, but initial investigations show that it may not be possible through the driver API, as the Bolt packstream erases the array type as well for empty parameter arrays.

**Comment by tinwelint** [comment]
Perhaps Bolt can add it to its protocol?
