### ISSUE TITLE
New Feature - Cypher- Return Deleted Items

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#86]
@Romiko: 'Hi,

Please can we have a feature in Cypher, to return results of items deleted

e.g
match..n....r.....s....p.....
delete n, r, s, p
return deleted.n, deleted.r, deleted.s, deleted.p

Of course sometimes you do not care about returning this data, so in such cases it does not when you specify to not return deleted.

This allows you to delete/update items in one DB call and get the results, very powerful for updates + auditing.'

**Comment by fiatjaf** [comment]
Is this going to be implemented? Why not? Is it impossible?

**Comment by MichaelJCole** [comment]
Wow.  I'd classify this as an API bug, but ok.  

Here's my use case:  We're using Neo4j for graph searching.  When I run this query:

`MATCH (n:Topic { mongoId: {_id} })-[r]-() DELETE n,r RETURN r;`

I then have to delete 'r' from another database.  Would be great if I didn't have to run two queries.  

There's a workaround here http://stackoverflow.com/questions/31124541/cypher-get-info-from-deleted-relationships

```
MATCH (n:Topic {mongoId: "558d714e01990e354bffe824" })-[r]-() 
WITH r.mongoId as docId, n,r 
DELETE n,r 
RETURN docId
```

**Comment by Mats-SX** [comment]
This is possible in current versions of Neo4j. Note that labels and properties of deleted elements are not accessible, but must be read before the deletion has semantic effect. For example:

```
CREATE (:Node {id: 1});

MATCH (nodeFromBefore:Node {id: 1})
CREATE (newNode:Node {id: 2})
WITH *, properties(nodeFromBefore) AS propsBeforeDelete, labels(newNode) AS labelsBeforeDelete
DELETE nodeFromBefore, newNode
RETURN 
  nodeFromBefore, properties(nodeFromBefore) AS propsAfterDelete, propsBeforeDelete,
  newNode, labelsBeforeDelete; // cannot do labels(newNode) on deleted node
```
