### ISSUE TITLE
Run Neo4j Browser over HTTPS

### ISSUE THREAD

**Issue by naisanza** [neo4j/neo4j#8634]
It would be nice if the same port used to reach the Neo4j browser is also HTTPS

**Neo4j version:** [3.1.0 community Dockerfile](https://github.com/neo4j/docker-neo4j-publish/blob/36ac547bcffcce2c7c0f249b340d062ba08e2598/3.1.0/community/Dockerfile)
**Operating system:** Ubuntu 16.10 
**API/Driver:** Kubernetes/Cypher

**Comment by spacecowboy** [comment]
You mean it would be nice if HTTP and HTTPS were both on the same port? I don't think that's technically feasible.

Neo4j has full support for HTTPS. And since you're using docker, just bind the https port (`7473`) and forget about the http one.

**Comment by naisanza** [comment]
@spacecowboy I actually didn't realize there was an HTTPS service running as well. Most forums just referenced the HTTP port

**Comment by spacecowboy** [comment]
I can recommend a stop by our official documentation if you wanna *one-up* those forums next time: https://neo4j.com/docs/operations-manual/current/installation/docker/

**Comment by naisanza** [comment]
And I think I wrote that question after having been up for more than 20 hours. I just re-read it, and yeah, it makes no sense for it to be on the same port. I was just looking for the HTTPS port
