### ISSUE TITLE
Add `path` and `paths` to the node entity of the REST API

### ISSUE THREAD

**Issue by ddossot** [neo4j/neo4j#866]
Having:

```
"path" : "http://localhost:7474/db/data/node/50/path",
"paths" : "http://localhost:7474/db/data/node/50/paths"
```

in the node JSON entity would help with these interactions: http://docs.neo4j.org/chunked/milestone/rest-api-graph-algos.html

**Comment by chrisvest** [comment]
Closing because I think finding paths is something that is better left for Cypher to do.
