### ISSUE TITLE
Executing queries on console does not affect the graph

### ISSUE THREAD

**Issue by Manish-Giri** [neo4j/neo4j#8663]
I've just started using the [console](http://console.neo4j.org/), but no matter which query I execute, the results of the query are reflected only in a tabular form (rows/columns), and not in the graph on the right. It doesn't show the query result, the only visible effect is that all the nodes change colors randomly.

From the tutorial videos that I've been watching, the expected result is that the matched nodes/relationships are highlighted in some color. But this doesn't happen.

This is the [query](http://console.neo4j.org/?id=d8tqgy) that I was executing.

- Neo4j version: latest
- Operating system: Windows 10
- API/Driver: Cypher

### Steps to reproduce
1. Open the [console](http://console.neo4j.org/)
2. Execute the query - `match (agent :Matrix) return agent`

### Expected behavior
The results of the query should be displayed in the tabular form, and the returned nodes should be highlighted in the graph on the right.

### Actual behavior
Results are returned only in tabular form, no effect of the query on the graph on the right. 

I've also logged an [issue](https://github.com/neo4j-contrib/rabbithole/issues/85) in the Github repo linked in the console, but not sure if that's active, so reposting here.

---

Adding some screenshots to specify the problem - 

This is the default screen when I launch the console - 

![default](https://cloud.githubusercontent.com/assets/11348778/22178629/390a41a8-e00a-11e6-99fe-1679bac66054.png)

Next, I execute the query - `match (agent: Matrix) return agent`. The result is - 

![def-1](https://cloud.githubusercontent.com/assets/11348778/22178630/4f1d0b2e-e00a-11e6-9666-fb55245c8cb6.png)

Lastly, I excute the query - `match (a)-[r: CODED_BY]->(b) return a,r,b`. The result is - 

![def-2](https://cloud.githubusercontent.com/assets/11348778/22178634/5e1b6166-e00a-11e6-867f-245433caa862.png)

As you can see through the sequence of screenshots, the results are only reflected in the tabular form, not in the graph. 

Thank You.

**Comment by jexp** [comment]
That's intentional, actually the nodes returned from the query should be highlighted.

I changed the visualization a few weeks back, so there might be still something off, I have a look.
As it is not a Neo4j issue I close it here. Thanks for reporting.
