### ISSUE TITLE
Benchmark results: Dgraph vs Neo4j

### ISSUE THREAD

**Issue by lazharichir** [neo4j/neo4j#8684]
Just thought you guys would be interested into this benchmark of Neo4j versus Dgraph: https://open.dgraph.io/post/benchmark-neo4j/

- Dgraph is 160x faster than Neo4j for loading graph data.
- Dgraph consumes 5x lesser memory compared to Neo4j and is at least 3x faster for intertwined reads and writes.
- For intertwined reads and writes, Dgraph is at least 3x to 6x faster..

What do you guys think?

L

**Comment by jimwebber** [comment]
I think vendor benchmarks aren't worth the paper they're written on. This one doesn't even distinguish between caching results (neo4j doesn't) and query plans (it certainly does). Their setup of neo4j is (deliberately?) naive too. On the whole, my position is that they need to prove themselves in the marketplace and not on their blog.
