### ISSUE TITLE
Queries with multiple "coalesce" functions takes much more time than expected

### ISSUE THREAD

**Issue by rsk700** [neo4j/neo4j#8736]
- Neo4j version: 3.1.1
- Operating system: Ubuntu 14.04.5
- API/Driver: any

**Steps to reproduce**

Generate test data set:

```
unwind range(1,100000) as i
create (:user {
name: 'name-' + toString(i)
})
```

Now, run this query:

```
match (u:user) return distinct u, coalesce(u.v1, 0) as v1, coalesce(u.v2, 0) as v2, coalesce(u.v3, 0) as v3, coalesce(u.v4,0 ) as v4 order by v1 desc limit 2
Returned 2 records in 1324447 ms.
```

As you can see it takes a lot of time, similar query, finishes much quicker:

```
match (u:user) return distinct u, coalesce(u.v1, 0) as v1 order by v1 desc limit 2
Returned 2 records in 383 ms.
```

Removing "distinct" or ordering from slow query also fixes performance issue.

**Comment by jexp** [comment]
Can you compare it with a query with the same number of attribute reads.

*distinct* makes no sense in your query

`match (u:user) return distinct u, u.v1, u.v2, u.v3, u.v4 order by u.v1 desc limit 2
`
or

```
match (u:user) return
with u, coalesce(u.v1, 0) as v1, coalesce(u.v2, 0) as v2, coalesce(u.v3, 0) as v3, coalesce(u.v4,0 ) as v4 
return *
order by v1 desc limit 2

```

**Comment by rsk700** [comment]
> match (u:user) return distinct u, u.v1, u.v2, u.v3, u.v4 order by u.v1 desc limit 2
> or
> 
> match (u:user) return
> with u, coalesce(u.v1, 0) as v1, coalesce(u.v2, 0) as v2, coalesce(u.v3, 0) as v3, coalesce(u.v4,0 ) as v4 
> return *
> order by v1 desc limit 2
> 

your examples works without problems

> distinct makes no sense in your query

in my query, just all items will be distinct, its not an error to use like this, and as I mentioned removing "distinct" or ordering will fix performance issue.

**Comment by sherfert** [comment]
This performance problem appears gone in the current version 3.3.
