### ISSUE TITLE
How to get the current active transactions?

### ISSUE THREAD

**Issue by i37anko** [neo4j/neo4j#8765]
Hi,
Is there any way to get the current active transactions? I found another issue ([#6009](https://github.com/neo4j/neo4j/issues/6009)) related to this. But, I can not find the procedure from [the official website](https://neo4j.com/docs/operations-manual/current/reference/procedures/). Isn't it a built-in procedure?

**Comment by jexp** [comment]
what do you actually want to do?

**Comment by i37anko** [comment]
The Neo4j server was getting stuck close to 100% CPU because slow query or dead loop query in our production environment. So I want to known the current active queries that might resemble `show processlist` in MySQL.

Thanks

**Comment by jexp** [comment]
have you tried ":queries" in browser or the procedure that it calls, i.e.

CALL dbms.listQueries()

in Neo4j Enterprise you can also get a list of currently held locks via JMX
or if you use apoc there is also apoc.monitor.locks(100)

In Neo4j 3.2. the locks information will be in listQueries.

**Comment by i37anko** [comment]
I'm going to upgrade Neo4j from 2.3.6 to 3.2 in production environment. Thanks.

**Comment by i37anko** [comment]
Is Neo4j 3.2 alpha? The `apoc.monitor.locks` is very useful command, but I can not get the detail query statement from output.

**Comment by jexp** [comment]
Yes, neo4j 3.2 is currently at alpha 03

**Comment by i37anko** [comment]
Thanks

**Comment by chrisvest** [comment]
For the record, we don't recommend putting alpha releases (or any non-GA release) in production :)

**Comment by i37anko** [comment]
I will wait for stable release version. Thanks for reminding :)

**Comment by chrisvest** [comment]
I think the question has been answered, so closing.
