### ISSUE TITLE
neo4j-import stops at "Calculate dense nodes"

### ISSUE THREAD

**Issue by chuajiesheng** [neo4j/neo4j#8767]
# Setup
- Neo4j version: Community Edition, 3.1.1
- Operating system: Ubuntu 16.04
- API/Driver: neo4j-import

# **Steps to reproduce**
1. Create a AWS instance with Ubuntu image
2. Install neo4j using standard installation guide (neo4j supplied)
3. Run the neo4j-import command as per screenshot

- Actual behavior

<img width="836" alt="screen shot 2017-02-06 at 17 59 05" src="https://cloud.githubusercontent.com/assets/1419998/22642521/033137ce-ec96-11e6-846e-50c4635a2fa4.png">

- Log

<img width="839" alt="screen shot 2017-02-06 at 18 00 17" src="https://cloud.githubusercontent.com/assets/1419998/22642555/2466dbec-ec96-11e6-993f-ef9c7015714d.png">

# Bug report

When neo4j-import is importing relation.csv, it just stops at calculating dense nodes is not able to move forward.

Sample of relation.csv:
<img width="737" alt="screen shot 2017-02-06 at 18 01 36" src="https://cloud.githubusercontent.com/assets/1419998/22642611/64aa59f4-ec96-11e6-8bbf-7e3f2a166b36.png">

**Comment by jexp** [comment]
It might be an data error that's correctly reported in newer versions.

Can you please try to run it with `--stacktrace true --multiline-fields true`

And see if you get any data error.

**Comment by chuajiesheng** [comment]
@jexp, it does report errors but it does not seems to exit.
(I actually managed to solve it, more details after the screenshots)

<img width="831" alt="screen shot 2017-02-07 at 14 45 48" src="https://cloud.githubusercontent.com/assets/1419998/22680684/44c02c14-ed44-11e6-9c90-68fde83fb132.png">

<img width="836" alt="screen shot 2017-02-07 at 14 47 01" src="https://cloud.githubusercontent.com/assets/1419998/22680696/5311bd32-ed44-11e6-8ed5-eebd05430439.png">

# How I managed to solve this problems

1. In the original data file, my userIDs are part of the node properties:
From the two screenshot, you can see that userId:ID is declared in `users.csv` and also in `retweet.csv` (as just userId)
I remove this property in all the file and declare it as relation

<img width="397" alt="screen shot 2017-02-07 at 14 49 59" src="https://cloud.githubusercontent.com/assets/1419998/22680769/c637b136-ed44-11e6-8bec-a1502849ad54.png">

<img width="248" alt="screen shot 2017-02-07 at 14 50 45" src="https://cloud.githubusercontent.com/assets/1419998/22680780/d44cab82-ed44-11e6-9f13-3584a4d0856e.png">

2. Similarly, in my `retweets.csv` and `replies.csv`, I declared tweetID which refers to either tweetId, retweetId or replyId
I guess this totally confused the import tool.

<img width="380" alt="screen shot 2017-02-07 at 14 52 26" src="https://cloud.githubusercontent.com/assets/1419998/22680873/5d0718d6-ed45-11e6-9432-25e313cb024b.png">
<img width="393" alt="screen shot 2017-02-07 at 14 52 30" src="https://cloud.githubusercontent.com/assets/1419998/22680874/5d5ce608-ed45-11e6-9718-48be70634b90.png">
<img width="341" alt="screen shot 2017-02-07 at 14 54 36" src="https://cloud.githubusercontent.com/assets/1419998/22680875/5d5eb3a2-ed45-11e6-96b4-af4a0e16330f.png">

**Comment by jexp** [comment]
Yes, the "not-exit" is the bug which is fixed in later versions.

The reported errors state that you have unresolved relationships. You can also just increase the 

`--bad-tolerance 100000`

	Number of bad entries before the import is considered failed. This tolerance 
	threshold is about relationships refering to missing nodes. Format errors in 
	input data are still treated as errors. Default value: 1000

**Comment by spacecowboy** [comment]
@jexp so we can close this as already fixed?

**Comment by spacecowboy** [comment]
This should be a different issue than the one mentioned by @jexp . Labeling as bug while we investigate.

**Comment by MishaDemianenko** [comment]
Fixed by https://github.com/neo4j/neo4j/pull/8966
