### ISSUE TITLE
Minor logging inconsistency

### ISSUE THREAD

**Issue by darkshade9** [neo4j/neo4j#8794]
Neo4j version: 3.1.1
OS:  Linux - Ubuntu 14.04
API/Driver:  C#

Logging inconsistency issue (very minor)
-- We use Filebeat to ship neo4j logs into Logstash and ultimately into Elasticsearch for centralized logging.  Our Logstash nodes apply Grok patterns to the logs to parse out interesting data such as exact timestamps (time the issue occurred versus time that the log was consumed), severity and other such items.  I noticed a minor logging inconsistency between severity types -- I've only seen INFO, WARN and ERROR so far, but here is the data I have:

#Actual Behavior
With INFO and WARN logs:
`2017-02-09 15:50:30.395+0000 INFO  [o.n.c.c.c.s.RaftLogShipper] MemberId{8cc492de}[matchIndex: 48611385, lastSentIndex: 48611380, localAppendIndex: 48611385, mode: CATCHUP]: caught up, moving to PIPELINE mode`

`2017-02-09 15:50:30.395+0000 WARN  [o.n.c.c.c.s.RaftLogShipper] MemberId{8cc492de}[matchIndex: 48611385, lastSentIndex: 48611380, localAppendIndex: 48611385, mode: CATCHUP]: match index not progressing. This should be transient.`

With ERROR logs:
`2017-02-09 16:30:25.045+0000 ERROR [o.n.b.t.SocketTransportHandler] Fatal error occurred when handling a client connection: Connection reset by peer Connection reset by peer`

**Github comments do not seem to show the double space, but it exists**:
The **double space** after the severity in the INFO/WARN log messages and the **single space** in the ERROR log.  I haven't had the opportunity to see the other severity types, so I can't check if they also have this inconsistency.
![Uploaded Photo](http://i.imgur.com/bAbjw8B.png)

#Expected Behavior:

All log messages should have consistent spacing between fields for ease of log parsing.

Example file:  [https://github.com/neo4j/neo4j/blob/3.2/community/logging/src/main/java/org/neo4j/logging/FormattedLog.java#L344-L347](https://github.com/neo4j/neo4j/blob/3.2/community/logging/src/main/java/org/neo4j/logging/FormattedLog.java#L344-L347)

Thanks

**Comment by darkshade9** [comment]
As an addendum, if the convention requires a 5 letter word, could it be encapsulated inside of square brackets, like this example:

`[2017-02-09T20:52:32,340] [INFO ] [o.e.c.m.MetaDataMappingService]`

**Comment by spacecowboy** [comment]
Thank you for the report. We'll have a look.

**Comment by praveenag** [comment]
@darkshade9 this has been fixed. We'll be releasing in the next 3.2 milestone release.
