### ISSUE TITLE
centos 6 cant fulfill 3.2 rpm requirements 

### ISSUE THREAD

**Issue by attachmentgenie** [neo4j/neo4j#8810]
The new rpm package declares javapackages-tools as a dependency but this package is only available on centos 7 not on centos 6.

- Neo4j version: 3.2.0-0.1.alpha04
- Operating system: centos 6.8
- API/Driver: rpm
- **Steps to reproduce**
- Expected behavior
- Actual behavior

### Steps to reproduce
```
cd /tmp
wget http://debian.neo4j.org/neotechnology.gpg.key
rpm --import neotechnology.gpg.key
cat <<EOF>  /etc/yum.repos.d/neo4j-testing.repo
[neo4j]
name=Neo4j Testing Yum Repo
baseurl=http://yum.neo4j.org/testing
enabled=1
gpgcheck=1
EOF
yum install neo4j
```

### Expected behavior
```
[root@puppet4-centos-73 ~]# yum install neo4j -y
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.prolocation.net
 * extras: mirror.netrouting.net
 * updates: mirror.prolocation.net
Resolving Dependencies
--> Running transaction check
---> Package neo4j.noarch 0:3.2.0-0.1.alpha04 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================================================================================================================
 Package                                Arch                                    Version                                            Repository                              Size
================================================================================================================================================================================
Installing:
 neo4j                                  noarch                                  3.2.0-0.1.alpha04                                  neo4j                                   74 M

Transaction Summary
================================================================================================================================================================================
Install  1 Package

Total size: 74 M
Installed size: 74 M
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : neo4j-3.2.0-0.1.alpha04.noarch                                                                                                                               1/1 
  Verifying  : neo4j-3.2.0-0.1.alpha04.noarch                                                                                                                               1/1 

Installed:
  neo4j.noarch 0:3.2.0-0.1.alpha04                                                                                                                                              

Complete!
```

### Actual behavior
```
[root@puppet4-centos-68 ~]# yum install neo4j -y
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: linux.cs.uu.nl
 * extras: ftp.nluug.nl
 * updates: mirror.1000mbps.com
Resolving Dependencies
--> Running transaction check
---> Package neo4j.noarch 0:3.2.0-0.1.alpha04 will be installed
--> Processing Dependency: javapackages-tools for package: neo4j-3.2.0-0.1.alpha04.noarch
--> Finished Dependency Resolution
Error: Package: neo4j-3.2.0-0.1.alpha04.noarch (neo4j)
           Requires: javapackages-tools
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

```

**Comment by attachmentgenie** [comment]
you add requirements specific to certain oses [1], how i judging what the package provides on rhel/centos7 [2]. i dont think it should be a dependency at all of eventual rpm, but it is a development dependency.

[1] http://fedoraproject.org/wiki/Packaging:DistTag#Conditionals
[2] https://www.rpmfind.net/linux/RPM/centos/7.3.1611/x86_64/Packages/javapackages-tools-3.4.1-11.el7.noarch.html

**Comment by spacecowboy** [comment]
@attachmentgenie thank you for testing the new RPM package!

That dependency was a result of trying to follow the guidelines here https://fedoraproject.org/wiki/Packaging:Java but it is most likely an unneeded dependency. I'll remove it and see if it works.

**Comment by spacecowboy** [comment]
Yup, worked fine. Fix in https://github.com/neo4j/neo4j/pull/8819

**Comment by attachmentgenie** [comment]
@spacecowboy thanks. When will you be releasing new packages?

**Comment by spacecowboy** [comment]
@attachmentgenie the next version of neo4j will have these changes. sadly the packaging is currently tied to the neo4j release cycle (we are aiming to change this soon). However if you are really keen to try it now I can make sure an updated package lands on repo.

**Comment by attachmentgenie** [comment]
@spacecowboy i think i would appreciate a new package, this will allow us to test our full matrix.

**Comment by spacecowboy** [comment]
@attachmentgenie I've pushed a new package with the fixed dependency. If you refresh your repos you should see `3.2.0-0.2.alpha04`.

Furthermore, I have also uploaded `3.1.1` (with the same fixed dependency) to the stable repo

**Comment by spacecowboy** [comment]
I have also added CentOS 6 (previously only 7) to our internal test matrix

**Comment by attachmentgenie** [comment]
@spacecowboy i can confirm all is now well for for us.

**Comment by spacecowboy** [comment]
@attachmentgenie fantastic. do let me know if anything else comes up
