### ISSUE TITLE
error message when upgrading 2.x graph.db that wasn't cleanly shut down

### ISSUE THREAD

**Issue by whatSocks** [neo4j/neo4j#8820]
**Background**

* I was going to use the graph.db from this repo+commit:
https://github.com/neo4j-contrib/graphgist-cms/tree/b5eeb74423adc0e7c3d0360750287ec0e69777c7/database.
* I was running 3.1.1 on a Mac, and expected to have to do follow this path https://neo4j.com/docs/operations-manual/current/upgrade/#supported-upgrade-paths
* I don't know what version of Neo4j was used to shut down the database compressed in the repo^

**What actually happened**

Upon attempting to upgrade, I got an error message like:

```
Caused by: java.lang.IllegalStateException: Mismatching store version found (v0.A.3 while expecting ''). The store cannot be automatically upgraded since it isn't cleanly shutdown. Recover by starting the database using the previous Neo4j version, followed by a clean shutdown. Then start with this version again.
```

This is confusing because:

* Expected store version isn't displayed
* "the previous Neo4j version" doesn't tell me what version of Neo4j I should download to fix my graph.db

**I eventually resolved this issue by:**

* downloading Neo4j v2.0.0 and going up in version until one was able to use the graph.db (2.1.1)
* cleanly shutting down
* tried upgrading 2.1.1 -> 3.1.1 and failed 
* upgraded 2.1.1 -> 3.0.9
* upgraded 3.0.9 -> 3.1.1 after realizing I had to manually edit my conf file(s)

**Comment by spacecowboy** [comment]
@whatSocks I'd recommend you open an issue at https://github.com/neo4j-contrib/graphgist-cms instead because that's where the problem should be fixed

@simpsonjulian @cheerfulstoic could you have a look please

**Comment by whatSocks** [comment]
I found out about the problem from this issue: https://github.com/neo4j-contrib/graphgist-cms/issues/94 
I updated the graphgist-cms repo with a database that runs with 3.1 after following the steps above.

I made the bug here in case someone else inherits a 2.x database that was not shut down cleanly and doesn't know what to do in the case that they don't know the version of Neo4j that was used to shut down the database.

**Comment by spacecowboy** [comment]
The fix is to not provide databases which were not shutdown cleanly, which you've corrected.

About the version, you can use `neo4j-admin version` in 3.2 to check the version of a database. But even that might have trouble because databases which were shutdown uncleanly don't have all the required metadata necessarily.
