### ISSUE TITLE
Load CSV from drive other than C: drive (windows)

### ISSUE THREAD

**Issue by DrYSG** [neo4j/neo4j#8839]
When I try to execute the following command in the browser. I get the following error about trying to load it from a very different path.

I would have guessed that I am not using the file:/// protocol correctly. But the docs that I have seen seem to say this is what works for folks. 

```
LOAD CSV WITH HEADERS FROM "file:///g:/crs2/DataFlowDB.csv" AS row
CREATE (actor:Actor { partition:row.Partition, csci:row.csci, name:row.Actor, direction:row.Direction, rate:toInt(row.Rate), wordLength:row.WorldLength })
return actor

Couldn't load the external resource at: file:/C:/Users/ysg4206/Documents/Neo4j/default.graphdb/import/crs2/DataFlowDB.csv
````

If I place the same file a the "suggested" path, (i.e. in the /import/ folder) and then use the command below, it works fine. (The G: drive is local file system on my windows machine)

```
LOAD CSV WITH HEADERS FROM "file:///DataFlowDB.csv" AS row
```

Should be reproducible with any csv file.

- Neo4j version: 3.1.1
- Operating system: Win 7 (64bit)
- API/Driver: Neo4j Web Browser: 2.0.0-M10

**Comment by chrisvest** [comment]
This is a feature, for security.
Look at the `dbms.directories.import` setting:
https://neo4j.com/docs/operations-manual/current/reference/configuration-settings/#config_dbms.directories.import

**Comment by DrYSG** [comment]
Thanks @chrisvest , that was really fast and timely. Consider adding this tidbit to the FAQ, or a comment on the documentation on CSV Load. Newbies don't have global understanding of neo4j, so they will see the csv load documentation, but will not know about a detail in the config that can effect that. (Think of what local graphs are all about. I can focus on the local information my a ego-centric position, and not have to know about all the data scattered through the system! I.e. the Neo4J philosophy can all teach us about managing our lives and complexity!
