### ISSUE TITLE
Exception thrown: 'Neo4j.Driver.V1.ServiceUnavailableException' in Neo4j.Driver.dll

### ISSUE THREAD

**Issue by mhelal** [neo4j/neo4j#8851]
Hi,

I am receiving the above exception while creating a session from .Net C# driver using the following code while the neo4j community edition 3.1.1 is running and I can connect to it from the browser on port 7474 :

using (var driver = GraphDatabase.Driver("bolt://localhost:7687", AuthTokens.Basic("neo4j", "password")))
using (var session = driver.Session())

I am using Visual Studio 2015 on windows 10, and .Net driver downloaded from Nuget with runtime version v4.0.30319, and .Net framework 4.6.1. In the same project I have both the Neo4j .Net driver and the Neo4jClient to try it later on. This project where it fails to connect is created as a Solid Works Addin using references to the Solid Works APIs, which is what is needed for the project. However, I have another project without Solid Works on the same versions of VS, windows and everything and it connects fine,

Any idea what I need to do to trace and solve this problem?

I appreciate your support very much, thank you,

Manal

**Comment by zhenlineo** [comment]
Hi, which .net driver [version](https://github.com/neo4j/neo4j-dotnet-driver/releases) you are using in your project?

Could you also try to turn off ssl by providing a config on driver creation `new Config {EncryptionLevel = EncryptionLevel.None}`?

**Comment by mhelal** [comment]
Hi, 

Thank you very much for your reply. I tried turning off the encryption as you said and still the same problem.

I am using .Net Driver version 1.1.0.0 and runtime verison v4.0.30319

thanks again,

**Comment by zhenlineo** [comment]
Hi @mhelal,

First, give a try of 1.1.2 driver?

I am not very familiar with Solid Works, could you help me do something in your project to help me troubleshooting the problem?

So the problem you described looks like that the driver cannot establish a tcp connection with the server via Solid works. The driver uses the very basic .Net core [TcpClient](https://docs.microsoft.com/en-us/dotnet/core/api/system.net.sockets.tcpclient). The way it was used in the driver is in Class named [TcpSocketClient](https://github.com/neo4j/neo4j-dotnet-driver/blob/1.2/Neo4j.Driver/Neo4j.Driver/Internal/Connector/TcpSocketClient.cs).

Could you try to modify the TcpSocketClient code and use it in a class such as SocketClient ([Ref](https://github.com/neo4j/neo4j-dotnet-driver/blob/1.2/Neo4j.Driver/Neo4j.Driver/Internal/Connector/SocketClient.cs)), e.g.
```
class SocketClient
{
  private TcpSocketClient _tcpSocketClient = new TcpSocketClient();
  async Task Start()
  {
    await _tcpSocketClient.ConnectAsync(_uri).ConfigureAwait(false);
  }
  async Task Stop()
  {
    await _tcpSocketClient.DisconnectAsync().ConfigureAwait(false);
    _tcpSocketClient.Dispose();
  }
}
```
Then in your project call this SocketClient like this
```
var client = new SocketClient();
Task.Run(() => _client.Start()).Wait();
```

If you could establish this connection,  then you should theoretically be able to use the driver to connect to the server. If you found any silly code that made it impossible to establish tcp connection, then pls let me know.

Cheers,
Zhen

**Comment by mhelal** [comment]
Hi, 

Thanks again.

I tried the following:

PM> Install-Package Neo4j.Driver -Version 1.1.2
Package 'Neo4j.Driver.1.1.2' already exists in project

However, propertied of the Neo4j.Driver in the references says its version is 1.1.0.0

I tried the code you sent, and it doesnot compile:


Error	CS0246	The type or namespace name 'TcpSocketClient' could not be found (are you missing a using directive or an assembly reference?)	

I added these namespaces and no good:

using System.Threading.Tasks;
using System.Net.Sockets;

I also get this error in the call (Task.Run(() => _client.Start()).Wait();):

'SocketClient.Start()' is inaccessible due to its protection level	

Thanks,

**Comment by zhenlineo** [comment]
Hi, The file is not accessable due to internal modifier, but could you create the files yourself and modify them to work with you program? There is no need to import the driver in this case.

Thanks,
Zhen

**Comment by zhenlineo** [comment]
@mhelal Could you try with the [1.3.0-beta01 driver](https://github.com/neo4j/neo4j-dotnet-driver/releases/tag/1.3.0-beta01)? Pls let me know if the problem still exists with the new driver.

**Comment by mhelal** [comment]
I actually switched to Neo4jClient and it is working fine. I don't have time nor motivation to go back for the native driver. 

If I fail to receive variable node types on the same path through the Neo4jClient PathResult object, then searching for solutions, I might need to come back to this, and update you again, 

If interesting, my path is p = (n1: type1)-[r1:reltype1]->(n2: type2)-[r2:reltype2]->(n3: type3)-[r3:reltype3]->(n4: type4)

it is more of a pattern for a common relationship, that I need to search. It works successfully on the web browser on Neo4j, and the query in Neo4jClient is successful, but serializing p to PathResult object return null on all rows, other return elements are successful, such as n1, n2, ... etc. Any ideas will be very useful, 

thanks for your suggestions,

**Comment by technige** [comment]
Closing due to workaround.
