### ISSUE TITLE
regular expression

### ISSUE THREAD

**Issue by zhangmoon** [neo4j/neo4j#8864]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests.  If you have questions on how to use Neo4j, please ask on [StackOverflow](http://stackoverflow.com/questions/tagged/neo4j) instead of creating an issue here.

If you want to make a feature request then there is no guideline, so feel free to stop reading and open an issue. If you have a bug report however, please continue reading.

To help us understand your issue, please specify important details, primarily:

- Neo4j version: 2.3.8
- Operating system: Ubuntu 16.04

Additionally, include (as appropriate) log-files, stacktraces, and other debug output.

## Example bug report
http://stackoverflow.com/questions/42357913/neo4j-regular-expression-error

**Comment by spacecowboy** [comment]
No actual issue/question posted. Closing.
