### ISSUE TITLE
OutOfMemory

### ISSUE THREAD

**Issue by iositan** [neo4j/neo4j#8874]
While deleting duplicate relationships after a while the heap got exhausted.

Action executed:
call apoc.periodic.commit("match (a)-[r]-(b) 
with a,b, TAIL(collect(r)) as rr 
where length(rr)>0 
foreach (r in rr | delete r)",{limit:10000});

![image](https://cloud.githubusercontent.com/assets/1593474/23226052/3f790360-f902-11e6-904f-5a5bee0248ee.png)

Heap dump:
![image](https://cloud.githubusercontent.com/assets/1593474/23226078/521daa98-f902-11e6-9a68-71df0655d126.png)

JVM:
-Dlog4j.configuration=file:conf/log4j.properties
-Dneo4j.ext.udc.source=zip-powershell
-Dorg.neo4j.cluster.logdirectory=data/log
-Xms24g
-Xmx24g
-XX:+UseG1GC
-XX:-OmitStackTraceInFastThrow
-XX:+AlwaysPreTouch
-XX:+UnlockExperimentalVMOptions
-XX:+TrustFinalNonStaticFields
-XX:+DisableExplicitGC
-Djdk.tls.ephemeralDHKeySize=2048
-Dunsupported.dbms.udc.source=zip
-Xloggc:C:\Local.Work\neo4j-enterprise-3.1.1-SNAPSHOT/gc.log
-XX:+PrintGCDetails
-XX:+PrintGCDateStamps
-XX:+PrintGCApplicationStoppedTime
-XX:+PrintPromotionFailure
-XX:+PrintTenuringDistribution
-XX:GCLogFileSize=20m
-XX:NumberOfGCLogFiles=5
-Dfile.encoding=UTF-8

Nodes
MATCH (n) RETURN count(n)
count(n)
44594815

Relationships
$MATCH ()-->() RETURN count(*);
count(*)
28557252

**Comment by jexp** [comment]
I think you misunderstood how the procedure works also this is APOC related, not Neo4j.
You actually have to add in a {limit} parameter and return the number of updates.
This should work:


```
call apoc.periodic.commit("
match (a)-[r]-(b)
with a,b, TAIL(collect(r)) as rr
where length(rr)>0
WITH rr LIMIT {limit}
UNWIND rr AS r
DELETE r
RETURN count(*)",{limit:10000});
```

**Comment by iositan** [comment]
Hi jexp

Thank you for your answer

However, with the syntax updated as per your suggestion
![image](https://cloud.githubusercontent.com/assets/1593474/23261683/7be43aa6-f9a5-11e6-88ce-02ac3d68b443.png)


I still have Java heap space error:
C:\Local.Work\neo4j-enterprise-3.1.1-SNAPSHOT\bin>cd /d C:\Local.Work\neo4j-ente
rprise-3.1.1-SNAPSHOT\bin

C:\Local.Work\neo4j-enterprise-3.1.1-SNAPSHOT\bin>neo4j.bat console
2017-02-23 13:07:58.813+0000 INFO  Starting...
2017-02-23 13:07:59.577+0000 INFO  Bolt enabled on 0.0.0.0:7687.
2017-02-23 13:07:59.577+0000 INFO  Initiating metrics...
2017-02-23 13:08:10.903+0000 INFO  Started.
2017-02-23 13:08:11.090+0000 INFO  Mounted REST API at: /db/manage
2017-02-23 13:08:11.886+0000 INFO  Remote interface available at http://localhos
t:7474/
2017-02-23 13:43:51.132+0000 WARN   Java heap space
java.lang.OutOfMemoryError: Java heap space
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.addWaiter(Abstr
actQueuedSynchronizer.java:606)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireInterr
uptibly(AbstractQueuedSynchronizer.java:885)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterrup
tibly(AbstractQueuedSynchronizer.java:1222)
        at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantL
ock.java:335)
        at org.eclipse.jetty.util.BlockingArrayQueue.poll(BlockingArrayQueue.jav
a:380)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.idleJobPoll(QueuedThre
adPool.java:531)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.access$700(QueuedThrea
dPool.java:47)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool
.java:590)
        at java.lang.Thread.run(Thread.java:745)
2017-02-23 13:43:51.134+0000 WARN  Unexpected thread death: {} in {}

**Comment by jexp** [comment]
Yes the big aggregation in there, kinda defeats the purpose of periodic.commit
You should also add a direction and a degree check.
It could also help to reduce the limit.

Also it doesn't seem as if there was any heap size configured for your neo4j instance?

```
call apoc.periodic.commit("
match (a) WHERE size( (a)-->() ) > 1
WITH a LIMIT {limit}
match (a)-[r]->(b)
with a,b, TAIL(collect(r)) as rr
where length(rr)>0
UNWIND rr AS r
DELETE r
RETURN count(*)",{limit:100});

```
another, better option is to mark nodes to be processed.

```
call apoc.periodic.commit("
match (a) WHERE not a:Process AND size( (a)-->() ) > 1
WITH a LIMIT {limit}
SET a:Process
RETURN count(*)",{limit:10000});

call apoc.periodic.commit("
match (a:Process) WITH a LIMIT {limit}
REMOVE a:Process
match (a)-[r]->(b)
with a,b, TAIL(collect(r)) as rr
where length(rr)>0
UNWIND rr AS r
DELETE r
RETURN count(*)",{limit:100});

```

**Comment by iositan** [comment]
Finally, only the solution as offered above (below is a slight syntax fix) worked.

Note that simply delete as the initial attempt worked up to 10M records only, on a machine with 32Gb of RAM.
Not even on a machine with three times memory (96GB) and heap of 80Gb, page size 6Gb, didn't worked for 30M records !

Revised code below; execution took approx 10 min.

```
call apoc.periodic.commit("
match (a:Process) 
REMOVE a:Process 
WITH a LIMIT {limit}
match (a)-[r]-(b)
WITH a,b, TAIL(collect(r)) as rr
where length(rr)>0
UNWIND rr AS r
DELETE r
RETURN count(*)",{limit:10000});
```

**Comment by iositan** [comment]
Thanks for help!
