### ISSUE TITLE
Cypher Neo4j Couldn't load the external resource from an arbitrary directory

### ISSUE THREAD

**Issue by iCoolchar** [neo4j/neo4j#8912]
- Neo4j version: 3.0
- Operating system: Linux

problem like this

http://stackoverflow.com/questions/28398778/cypher-neo4j-couldnt-load-the-external-resource/42526906#42526906

I tried all the answers but didn't work.

I finally find the solution:

I have to explicitly add
> dbms.security.allow_csv_import_from_file_urls=true
> dbms.directories.import=import

to my neo4j.conf, which locates at /etc/neo4j/

and put my csv file to the import file under /usr/share/neo4j/import directory

I tried other directories like dbms.directories.import=/root/import according to the instructions in http://neo4j.com/docs/developer-manual/current/cypher/clauses/load-csv/ but it didn't work. I have already set up an issue to neo4j github, hope to get an answer soon.
Additionally, include (as appropriate) log-files, stacktraces, and other debug output.

Is there any problem with assigning an arbitrary directory for csv location?

Thanks in advance!

**Comment by mayanez** [comment]
I am also seeing the same problem on Linux with Neo4j version: 3.2.6

**Comment by cpieringer** [comment]
I have the same problem with Neo4j Desktop version on Windows 10. I cannot import a csv file.

**Comment by SJBertram** [comment]
I'm currently hitting this with 3.3.5 from the Ubuntu repo. Even when I put the file in the import directory and allow CSV import from URLs then I still get "Couldn't load the external resource from…".

**Comment by RavenKe** [comment]
the same problem on ubuntu 16.0.4 with Neo4j version: 3.4.0

**Comment by Th3-Muffin-Man** [comment]
SOLUTIONS:
----------

This is a security feature that is auto-enabled in neo4j 3.0 and above. It disallows files to be loaded from anywhere in the filesystem. 

You have 2 Solutions/Options:

 1. Leave the setting as is and simply place all CSV files to be read in the "import" directory(folder) located in the install directory(folder).
 2. Change the security feature to allow the importation of CSVs from any directory in the filesystem.



OPTION 1:
---------

This option is straight forward, simply copy and paste all CSV files to be read in the "import" directory(folder) located in the install directory(folder).

Then use the path as follows for the file (eg. to load a CSV file "data.csv" which was pasted into the import directory(folder)

    LOAD CSV file:///data.csv



OPTION 2:
---------

To allow any url or filepath to be imported, you must navigate to the neo4j.conf file. The file is found in the conf Folder in the install directory. Alternatively, you can simply search for the "neo4j.conf" file.

Upon locating the file open it (using Notepad or other). Then ensure that "dbms.security.allow_csv_import_from_file_urls=true" below is NOT commented out (remove "#") && "dbms.directories.import=import" below is commented out (add "#").
 

    # Determines if Cypher will allow using file URLs when loading data using
    # `LOAD CSV`. Setting this value to `false` will cause Neo4j to fail `LOAD CSV`
    # clauses that load data from the file system.
    dbms.security.allow_csv_import_from_file_urls=true
    
    # This setting constrains all `LOAD CSV` import files to be under the `import` directory. Remove or comment it out to
    # allow files to be loaded from anywhere in the filesystem; this introduces possible security problems. See the
    # `LOAD CSV` section of the manual for details.
    #dbms.directories.import=import

**Comment by tinwelint** [comment]
This turned into a KB entry, which is great. In any case it doesn't need to be an open issue anymore, closing.

**Comment by mskhan1403** [comment]
I have the same problem on ubuntu 16.0.4 with Neo4j Docker version: 3.1.7
I tried both Options 1 & 2 but still not able to get it running..

**Comment by mustfkeskin** [comment]
Hello i have same problem

I copy my csv in docker container
`docker cp my.csv  testneo4j:/var/lib/neo4j/import/
`
My Config:
`dbms.directories.import=import`
`dbms.security.allow_csv_import_from_file_urls`
This work for me

**Comment by hlin-0420** [comment]
> LOAD CSV file:///data.csv

This instruction doesn't work since it is invalid and is expecting 'FROM' or 'WITH HEADERS'. Could you check which type of command allows data loading?
