### ISSUE TITLE
Expected a string value for <function1>, but got: ...; perhaps you'd like to cast to a string it with str().

### ISSUE THREAD

**Issue by stdob** [neo4j/neo4j#8938]
For example, we add following nodes:

```
MERGE (A:Test {name: 'Ab'})
MERGE (B:Test {name: 1976})
```

And we want to search for nodes by name-insensitive:

```
MATCH (A:Test) WHERE toLower(A.name) contains 'ab'
RETURN A
```

And we get an error:

> Expected a string value for <function1>, but got: 1976; perhaps you'd like to cast to a string it with str().

It is clear that we can use typecasting, but it is believed that "neo4j" free from the typecasting?

**Comment by jexp** [comment]
It's not really free from type-casting when it comes to function arguments.
Some operations like comparisons are managing different types.
And some functions are defined for the "Any" type, like toString

```
MATCH (A:Test) WHERE toLower(toString(A.name)) contains 'ab'
RETURN A
```

**Comment by stdob** [comment]
Yes @jexp , thank you, we are now using a function toLower. 

But maybe it's worth in this cases return null as function result?

**Comment by systay** [comment]
Pretty sure `toLower` handles `null`s without hiccups.
