### ISSUE TITLE
Feature Request: Support exclusion of properties in map projection

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j/neo4j#8939]
Currently with map projection, you can specify the properties to include by their key, and you can include all properties with `.*`.

However, the case for returning all properties except some specific few isn't supported. You would instead have to explicitly include all properties except those to be excluded, or use some APOC functionality to limit what is included in the map.

This requests a means of declaring properties to exclude from a map projection, and only makes sense when combined with `.*`. Perhaps a `-` can be used to designate properties to exclude.

An example of use:

```entity {.*, -.sensitiveProperty1, -.sensitiveProperty2}```

**Comment by petraselmer** [comment]
Hi there

I was wondering whether or not you had seen our list of 'Cypher Improvement Requests' [here](https://github.com/opencypher/openCypher/issues?q=is%3Aopen+is%3Aissue+label%3ACIR)? Essentially, this is the place where additions / modifications / ideas for Cypher can be suggested. The idea is that these will lead to proposals - basically, mini-specifications - being written, incorporated into Cypher and thence into Neo4j. A more detailed description of this process can be found [here](https://github.com/opencypher/openCypher/blob/master/CIP-PROCESS.adoc).

It would be great if you could write a CIR, containing your feature request. It does not need to be anything formal - a basic transcript of what you've written above would be more than sufficient. 

Many thanks!

**Comment by InverseFalcon** [comment]
Thanks, just added this as an opencypher issue. Should we close up here?

**Comment by petraselmer** [comment]
Great - have just seen your CIRs - thanks for this! 

Closing....

**Comment by g3rd** [comment]
For those getting here via google searches, and want to follow along with the progress of the request: https://github.com/opencypher/openCypher/issues/201
