### ISSUE TITLE
Cypher start doesnt allow combining multiple starting points with start node sets

### ISSUE THREAD

**Issue by gerbenoostra** [neo4j/neo4j#897]
With the following cypher query:
START a=node(1,2,3), b=node(1,2,3)
MATCH a-[:EDGE]-b
RETURN a
In a complete graph, only edges to/from node 1 are returned.

After playing with some different ids, it seems that of one of the two node id sets, only the first is actually used.

I'm using neo4j version.2.0.0-M03

**Comment by sherfert** [comment]
This issue only affects the `START` syntax, not `MATCH`. The former is deprecated and therefore we will likely not fix this issue.

**Comment by jexp** [comment]
Multiple MATCH can be linked together with `WHERE a = b ` 
which will create a node-hash-join operation.
