### ISSUE TITLE
Query Hangs until server exited

### ISSUE THREAD

**Issue by jbrumwell** [neo4j/neo4j#8980]
We have an odd situation where specific nodes seem to be read only, any mutations to them, including add relationships causes the server to hand indefinitely. Other nodes of the same type operate as expected.

- Neo4j version: 3.1.1 & 3.1.0
- Operating system: ubuntu 16.04
- API/Driver: cypher-shell, tcp
- **Steps to reproduce**

```
neo4j> MATCH(user:USER)
            WHERE NOT user:INACTIVE AND user.id=67
            MERGE(user)-[:CONTACTMANAGER]->(manager:CONTACTMANAGER)
            RETURN manager;
```
- Expected behavior

```
manager
(:CONTACTMANAGER)
Added 1 nodes, Created 1 relationships, Added 1 labels
neo4j>
```

- Actual behavior
Hangs indefinitely

The only thing located in debug.log is a stacktrace for connection reset by peer. Is there something I can try or a way to get more information about what is happening?

**Comment by jexp** [comment]
You could look at the currently held locks, perhaps you have background
processes that keep interacting with certain parts of the graph / schema.

You can see these locks via JMX or via apoc.monitor.locks(100)

Please check and let us know.

**Comment by jbrumwell** [comment]
@jexp rebuilding with 3.1.0 and apoc caused the issue to be resolved. If it occurs again I will use your advise thank you :+1:

**Comment by jbrumwell** [comment]
@jexp This has now re-appeared;

```
neo4j> MATCH(user:USER)
               WHERE NOT user:INACTIVE AND user.id IN [75]
               RETURN ID(user);
ID(user)
89
neo4j> CALL apoc.monitor.locks(100);
advertedDeadLocks, lockCount, contendedLockCount, minimumWaitTimeMs, contendedLocks, info
-1, 3, 3, 100, [{description: "ExclusiveLock[
Client[1] waits for []]", resourceId: "79", resourceType: "NODE"}, {description: "ExclusiveLock[
Client[7] waits for []]", resourceId: "89", resourceType: "NODE"}, {description: "SharedLock[
Client[1] waits for [], 
Client[2] waits for [1], 
Client[12] waits for [1], 
Client[18] waits for [1], 
Client[8] waits for [1], 
Client[13] waits for [1], 
Client[17] waits for [1], 
Client[7] waits for []
Client[10] waits for [7], 
Client[21] waits for [7], 
Client[20] waits for [7], 
Client[11] waits for []]", resourceId: "0", resourceType: "SCHEMA"}], "Showing contended locks where threads have waited for at least 100 ms."
```

I assume it may be transactions that are not being committed / rolled back?

```
neo4j> CALL apoc.monitor.tx();
rolledBackTx, peakTx, lastTxId, currentOpenedTx, totalOpenedTx, totalTx
14, 22, 402, 12, 2111, 2085
```

**Comment by jbrumwell** [comment]
Resolved, had a non-transactional query accessing a locked record from a transaction
