### ISSUE TITLE
PERIODIC COMMIT is prohibited even though query calls an updating plugin procedure

### ISSUE THREAD

**Issue by cybersam** [neo4j/neo4j#8994]
### Environment
- Neo4j version: 3.1.1
- Operating system: OS X 10.11.6
- API/Driver: None (using browser ui)

### Steps to reproduce
Attempt to use the `PERIODIC COMMIT` option of `LOAD CSV` in a Cypher query that makes no updates directly, but includes a call to an APOC procedure that performs updates.

### Expected behavior
The query completes normally.

### Actual behavior
The query failed with an `Cannot use periodic commit in a non-updating query` error. 

### Suggested fix
You can add warnings to the browser UI, but otherwise allow queries that call procedures to use `PERIODIC COMMIT`.

**Comment by spacecowboy** [comment]
Could you provide exact steps to reproduce the issue please?

Also consider reporting this on https://github.com/neo4j-contrib/neo4j-apoc-procedures

**Comment by craigtaverner** [comment]
I was unable to reproduce this in either the 3.1 code-base or an installed version of 3.1.1. I installed APOC 3.1.0.4 into an installation of Neo4j 3.1.1, created a test CSV file containing 1000 lines with the numbers 000 through 999, and then ran the following command:

    USING PERIODIC COMMIT 10
    LOAD CSV FROM 'file:///test.csv' AS line
    CALL apoc.create.node(['Person'],{id:line[0]}) YIELD node
    RETURN node.id

This worked fine using BOLT from the browser. When disabling BOLT I got an error, presumably unrelated to this issue, and will be reported elsewhere:

    The requested operation cannot be performed, because it has to be performed in a transaction.
    Ensure you are wrapping your operation in the appropriate transaction boilerplate and try again.

Could you provide more information on exactly how you got the error you reported in this issue.

**Comment by craigtaverner** [comment]
Unable to reproduce.
