### ISSUE TITLE
YUM repository signature on repomd.xml is not being regenerated with repository updates

### ISSUE THREAD

**Issue by frankthetank** [neo4j/neo4j#8996]
My bad for continuing the discussion on closed Issue #6148 (It was closed in 2015!).  I didn't check its state before piling on.

Most of the details are over there but I wanted to create this new ticket as a trackable item so it doesn't fall through the cracks.
My configuration and logs are at https://github.com/neo4j/neo4j/issues/6148#issuecomment-284595532

According to @spacecowboy : "@frankthetank thanks for the info. I think we found the issue. It seems the repo metadata isn't signed everytime it is regenerated. I'm making some changes that hopefully will have it fixed."

If nothing else the research is done and closing this ticket quickly will make your average time to close go down ;-)

**Comment by spacecowboy** [comment]
@frankthetank no worries. we pushed a change this last night and it should be signed everytime it's updated now.

As a side note, it was previously unclear which GPG key was used to sign the repo. We created a new one in order to abandon the old key which used SHA1. So you might *possibly* need to accept the key once more but it should then be good going forward.

Please re-open if the problem re-appears!

**Comment by frankthetank** [comment]
Can't yet say that it is fixed.

Based on your above note about a new key I removed the two existing keys:
```
rpm -e gpg-pubkey-01182252-544ee144 gpg-pubkey-d37f5f19-58113cda
``` 
then reimported:
```
rpm --import http://debian.neo4j.org/neotechnology.gpg.key
```
Assuming the repomd.xml was resigned, the new key was not copied to the neotechnology.gpg.key file.
```
zypper refresh
Retrieving repository 'neo4j' metadata ------------------------------------------------------------------------------------------------------------------------------[\]
File 'repomd.xml' from repository 'neo4j' is signed with an unknown key '26C95CF201182252'. Continue? [yes/no] (no): 
```

Thanks for working this out!  Unfortunately I can't reopen the ticket since you (the project collaborator) closed it.

**Comment by spacecowboy** [comment]
So one issue might be that http://debian.neo4j.org/neotechnology.gpg.key contains 2 keys, the old *and* the new one.

I'm not 100% certain but I think you can just do

```
rpm -e gpg-pubkey-01182252-544ee144 gpg-pubkey-d37f5f19-58113cda
zypper refresh
```

alternatively, use `yast` to edit the keys as well. I have also added the public key to the repo itself. Hopefully this means zypper/yast will download the correct key on their own and you need only approve of it.

**Comment by frankthetank** [comment]
So while using ```zypper refresh``` and accepting the file does accept the repomd.xml it does not import any key by default.  The key has to be called ```repomd.xml.key``` as documented at https://en.opensuse.org/SDB:Secure_installation_sources#The_.22repomd.22_or_.22YUM.22_format

**Comment by spacecowboy** [comment]
the `repomd.xml.key` file is what I was referring to. it is there.

I have discovered the real problem though. When we rebuild the repo and thus re-sign it, it ended up in a weird state where the `repomd.xml` file was not updated but the file indexes were, and so the timestamps were wrong.

I have now changed our scripts to absolutely generate all of the files at all times to make sure we have correct cross-references. So now it *really* should be no more signature issues.

As a side-note I discovered our versioning for the pre-release RPMs was flawed so I am updatating that here: https://github.com/neo4j/neo4j/pull/9008 and will rebuild all 3.2.0 testing packages when that has been approved and merged.

Thanks for your help.

**Comment by frankthetank** [comment]
hmmm - whether using the command line's "zypper refresh" or Yast I was not given the opportunity to download the key automatically.  

My local zypp cache includes the following:
```
toybox:/home/frank # ls /var/cache/zypp/raw/neo4j_1/repodata/
3485b4d7931a28270a307631783be141a5ca5a40e7035296892f6f522842bcee-primary.xml.gz
45b54204307de57c8e83db9219448cf0f743028ba96a6d6a683cc6d4261437b4-filelists.sqlite.bz2
500461745c1c1ec6af9f5f66402fa38d3848a33df86f5a24edeba8c7fcad4a9c-primary.sqlite.bz2
ef2e8a014ef082ad2931ae84a6b7d75418308e47906a8d38d36d81977205bce0-other.sqlite.bz2
repomd.xml
repomd.xml.asc
```

So now I did a ```zypper clean``` and then ```zypper refresh``` and I think maybe you are still working on it?
```
File '/repodata/repomd.xml' not found on medium 'http://yum.neo4j.org/stable/'
```

**Comment by spacecowboy** [comment]
@frankthetank yes. though I did the same thing to the stable repo now just because you mentioned it.

**Comment by frankthetank** [comment]
Woot!  I can now automatically refresh and check for neo4j updates.  Thank you!!

**Comment by spacecowboy** [comment]
Now really fixed. Suse should not complain anymore
