### ISSUE TITLE
Suggestion: returning all nodes connected to another could be hugely more efficient

### ISSUE THREAD

**Issue by benstevens48** [neo4j/neo4j#9031]
I want to return all nodes connected to another node. My query looks like this.
```
MATCH (:Waypoint {id:"myid"})-[:LeadsTo*]-(n:Waypoint) RETURN n;
```
(Note that id is a property on the node which I've added). I've also tried writing
```
MATCH p = (:Waypoint {id:"myid"})-[:LeadsTo*]-(n:Waypoint) RETURN nodes(p);
```
Neither of these queries ever finish. I assume that's because they're trying to match paths (of which there are infinitely many if they are allowed to be self-intersecting), then extract the nodes.

As a workaround, I'm pulling all the nodes and their nearest neighbours from the database and then finding all the nodes connected to the base node using code. It's possible to do this in no more than O(r log(n)) operations, where r is the total number of relationships and n the total number of nodes in the graph. This is because all you need to do is follow all paths from the start node, keeping a 'Map' or indexed list of the nodes you've already found, and stop following a path as soon as you hit a node you've already found. (So you go along at most O(r) edges and for each one you have to lookup/insert something in the 'Map' wich is at most O(log n)). Since my graph is quite small this only takes a few milliseconds.

It would be good if it was possible to write a query to do this. Ideally, neo4j should be able to work out that this is the best way to execute the above queries. If this is difficult, then a dedicated function like the shortestPath function would also work.

**Comment by InverseFalcon** [comment]
What you're describing sounds like an expansion using 'NODE_GLOBAL' [uniqueness](http://neo4j.com/docs/java-reference/current/javadocs/org/neo4j/graphdb/traversal/Uniqueness.html).

As far as improvements to let Cypher infer queries where the paths don't matter, just the nodes, and optimizing the traversal accordingly, Max de Marzi mentioned this in a [recent blog post](https://maxdemarzi.com/2017/02/06/neo4j-is-faster-than-mysql-in-performing-recursive-query/), and a PruningVarExpander enhancement may be coming with Neo4j 3.2 to handle this.

In the meantime, you may want to look at APOC Procedures, specifically [path expander procedures](https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_expand_paths), which allow you to expand using different kinds of uniqueness. A convenience procedure `apoc.path.subgraphNodes()` is available that expands using 'NODE_GLOBAL' uniqueness, returning just the nodes, and is usually more efficient than Cypher's current variable-length expansions. 

You'll want to use the relationship filter to restrict your expansion just to the relationships you want. 

There's also a means to declare a label filter, one of which (the "/" operation) ensures that the only nodes returned are those of a specific label. The side effect here is that once one of these end nodes is found along a path and included as a result, traversal does not continue past that node. This makes it good for cases where traversal should stop once an end-node is found, but if you want to continue expanding past end nodes to other end nodes along the same path, you'll probably not want to use this feature.

Give it a try, see if it meets your needs!

**Comment by benstevens48** [comment]
Hi @InverseFalcon ,
Thanks for your detailed reply. The apoc.path.subgraphNodes() procedure looks like it does exactly what I want. I'll give it a try when I have time. 

I feel that either this should be included in Neo4j by default, or the Cypher queries above should be optimised better, or both! It seems to me that finding all the nodes  connected to a given node (possibly including relationships so you get the whole 'subgraph') is one of the most fundamental things you can do with a graph.

**Comment by InverseFalcon** [comment]
If you want relationships among those nodes too, look at `apoc.path.subgraphAll()`, that will get you the collection of nodes and the collection of relationships between all of those nodes.

**Comment by sherfert** [comment]
This is addressed in a CIR to openCypher: https://github.com/opencypher/openCypher/issues/174
