### ISSUE TITLE
Cypher: Deleting relationships actually duplicates some of them

### ISSUE THREAD

**Issue by gamedev8** [neo4j/neo4j#9041]
- Neo4j version: 3.1.2
- Operating system: Ubuntu 16.04
- API/Driver: Cypher

Hey guys
I've been exporting some data from ArangoDB to test out in Neo4J. I've imported a bunch of member nodes, and attribute nodes. Members nodes are connected (relationships) to several Attributes nodes.
- Member nodes only have the one property
- Attribute nodes only have the one property
- the relationships have no properties

I executed the following command to add the relationships between the Member and Attribute nodes, but  what I didn't realize was that there were some duplicates in the Attributes nodes.

```
using periodic commit
load csv from "file:///is.csv" as row with row limit 1
match (m:Member {username:row[0]}), (a:Attribute {name:row[1]})
create (m)-[:IS]->(a)

```

When I realized that I had duplicates I decided to delete the Attribute nodes and the relationships, and then try again.

Now as I recall, I executed the following query:
`match (m)-[r]->(a) delete r,a`
After a few minutes, it said the query completed, but now I realize it didn't delete everything - it left about **12,000** relationships from what I remember and I don't remember how many Attribute nodes were left over.

I tried it again:
Relationships increased to **20714** (increased by at least 8,000)
Duration: 20 minutes

I tried to delete just 1 relationship:
`match (m)-[r:IS]->(a:Attribute) with r limit 1 delete r`
First attempt
Relationships increased to **30949** (increased by 9780), Duration: 36 minutes

Second attempt
Relationships increased to **41281** (increased by 10787), Duration: over 40 minutes

I tried a detach delete:
`match (a:Attribute {name:"isSmoker"}) detach delete a`
The result in the UI says - "Deleted 12 nodes, deleted 1560 relationships, statement completed in 2852664 ms."
The 12 nodes were deleted, but the relationships were actually increased to **49933**.

What other info do you need to diagnose?

**Comment by InverseFalcon** [comment]
Deleting nodes relationships should never create more. I don't think there's any way for that to happen.

What you're describing almost sounds like the periodic commit import was executed and continued to run even as you started deleting graph elements, but that would only make sense of you didn't have `limit 1` in the import query. Did you ever execute an import query on a large CSV without a limit?

**Comment by gamedev8** [comment]
@InverseFalcon  That sounds very plausible. I think I did insert without a limit at one point.
