### ISSUE TITLE
No RPM?

### ISSUE THREAD

**Issue by xmstspider** [neo4j/neo4j#9050]
Hello,

following the [https://neo4j.com/download/community-edition/](https://neo4j.com/download/community-edition/), when selecting Linux, only the tar archive, Debian package and Docker images are available, but there is no RPM for either RHEL/CentOS or SUSE.

Is it possible for you to provide RPMs? If you are missing resources, let me know, I am able to help you with the RPM packaging.

Thanks

//Zdenek

**Comment by spacecowboy** [comment]
We do provide RPM. See

http://yum.neo4j.org/stable/

and 

http://yum.neo4j.org/testing/

but thanks for exposing that the web page doesn't mention it. @simpsonjulian something you can look at?

**Comment by spacecowboy** [comment]
closing as fixed
