### ISSUE TITLE
Merge ReflectiveProcedureCompiler and procedure-compiler logic

### ISSUE THREAD

**Issue by fbiville** [neo4j/neo4j#9052]
Right now, the validation is implemented twice, albeit a tad bit differently (one is reflection-based, one is [element](https://docs.oracle.com/javase/7/docs/api/javax/lang/model/element/package-summary.html)-based).

Most logic is the same and we should find a way to centralize this as much as possible.
That way, when a new kind of Cypher extension is developed, the effort to keep the compiler up-to-date would remain minimal.

**Comment by Lojjs** [comment]
Hi @fbiville and sorry for the late reply. Our performance team will have a look at this and come back to you.
Best regards Louise, Neo4j Cypher team

**Comment by fbiville** [comment]
No worries, the PR was at a very very early stage.

The idea would consist in extracting a separate module with a common Neo4j extension model and common validation logic (i.e. 95+% of validation cases?), re-used by the reflective validation module and the compile-time one.

Then, find a way to plug custom validation logic (5+% of cases) where relevant.

In terms of validation differences, here are the ones I can think of right now:

 - generic types can be properly validated at compile-time, they are not erased yet (so we could enforce at compile-time the use of `Map<String, Object>` instead of rawtypes or wrong generic type parameters)
 - extension uniqueness can only be 100% validated at runtime, the procedure compiler processes 1 compilation unit at a time and cannot know about the multiple extension JARs deployed against a specific Neo4j instance

**Comment by fickludd** [comment]
Hi again Florent!

I think everyone agree that this makes a lot of sense, but we just have too many other prioritized things to do to get around to this in a while. If you are passionate about pushing this we will gladly guide a PR, but no-one is available to drive this from Neo4j.

Would you mind closing the issue, or do you want it to remain open?

**Comment by fbiville** [comment]
Let's close it for now. I can create a new issue when I have some available bandwidth again.
