### ISSUE TITLE
Create/update nodes and relationships in the browser?

### ISSUE THREAD

**Issue by airbone42** [neo4j/neo4j#9053]
Are you planning to add functionality for creating/updating nodes and relationships in the browser?

I think that would help a lot to people not yet knowing cypher to try-out Neo4j.

**Comment by spacecowboy** [comment]
No I do not believe we are. Cypher is a great query language and we'd like everyone to learn it.

**Comment by jexp** [comment]
@airbone42 see my last blog post for a way of doing that

http://jexp.de/blog/2017/03/creating-a-neo4j-example-graph-with-the-arrows-tool/

you can access it directly via `:play http://guides.neo4j.com/arrows`

there is also `:play query template` for a form based variant to create data.

We plan to add interactive graph editing functionality in the future.

Thanks a lot for the feedback, we add it to that feature request.

**Comment by mctouch** [comment]
:play query template is not working for me in either the desktop or under linux and windows. Do I have to install something to get this to work?
