### ISSUE TITLE
Query execution time in Dashboard console is wrong

### ISSUE THREAD

**Issue by creotiv** [neo4j/neo4j#9066]
I found that query execution time in dashboard console calculated wrong. Instead of showing query time it shows query time + time of getting and rendering response in dashboard console, basically query time depends on the internet speed. Which makes it useless.
How to reproduce:
Send any cypher query from console which has heavy response, get the query time, and then send same query instead of result return just True, and get the query time, then you will see difference, which basically shouldn't exist. Also you can check this wi limiting speed of your internet connection.

- Neo4j version: 2.3
- Operating system: Ubuntu 16.04

**Comment by oskarhane** [comment]
This is not the case in newer versions (since bolt started reporting query timings).
