### ISSUE TITLE
causal_clustering.discovery_listen_address doesn't set the IP address

### ISSUE THREAD

**Issue by mikernorton** [neo4j/neo4j#9071]
- Neo4j version: 3.1.1
- Operating system: Red Hat 7.3

We generally like to make sure all listening ports are bound to a specific IP for security reasons. This works for almost all neo4j configured addresses except for the discovery port. First I tried setting the connector default, "dbms.connectors.default_listen_address=172.17.0.3", but that did not set the address for the discovery. Nor does setting "causal_clustering.discovery_listen_address=172.17.0.3:5000"

Instead, the discovery port is always bound to ":::5000", meaning you can connect using any IP on the box.

Steps to reproduce:
1) In the neo4j.conf file set
causal_clustering.discovery_listen_address=172.17.0.3:5000
(For your own IP.)
2) bring up Neo4j.

- Expected behavior
netstat -plnt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name 
...   
tcp6       0      0 **172.17.0.3:5000**         :::*                    LISTEN      2281/java         
...

- Actual behavior
netstat -plnt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name   
... 
tcp6       0      0 **:::5000**                 :::*                    LISTEN      2281/java           
...

The only debug output IO could find for the parameter shows it is set properly:
/var/log/neo4j/debug.log:2017-03-21 22:15:38.275+0000 INFO  [o.n.k.i.DiagnosticsManager] causal_clustering.discovery_listen_address=172.17.0.3:5000

**Comment by spacecowboy** [comment]
@mikernorton thanks for the report, we'll investigate

**Comment by mneedham** [comment]
@mikernorton this commit should fix this issue -  https://github.com/neo4j/neo4j/pull/9086

**Comment by spacecowboy** [comment]
Fixed by #9071
