### ISSUE TITLE
Get string like slug

### ISSUE THREAD

**Issue by tomswinkels** [neo4j/neo4j#9090]
Hi,

I want to get an result by word (This is a word) that was in the url of my webpage, www.example.com?q=this-is-a-word.

This is what i use on this moment;

```
MATCH (region:TS_P2000Region)
WHERE replace(replace(region.name,' ','-'),'--','-') =~ 'this-is-a-word'
RETURN region
```

Maybe it is an idea that there is some slug function?

```
MATCH (region:TS_P2000Region)
WHERE slug(region.name,'-'), =~ 'this-is-a-word'
RETURN region
```

**Comment by jexp** [comment]
Migrated to APOC
