### ISSUE TITLE
Graph Visualization Styles: Support {propertyName} template in Icon URL

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#91]
@ceefour: 'Thank you for adding Graph Visualization to Neo4j Web Admin !

Most of our graph nodes contain information about picture/photo of the node.

It would be great if we can specify Icon URL just like title, e.g.

    http://dav.berbatik.com/person/t/{photoId}_t.jpg

Which would take the Icon URL from the URL specified by the template including the `photoId` property of the node.'

**Comment by oskarhane** [comment]
This issue was moved to neo4j/neo4j-browser#110
