### ISSUE TITLE
How to Get edge count ?

### ISSUE THREAD

**Issue by rajkuttie** [neo4j/neo4j#9101]
I create two lables. There are User and post. Now I relations between user and post. That relation name is Like (Edges). Now I want calculate No of likes. Then How I can calculate no.of.edges ?

**Comment by jexp** [comment]
Hi, this is an issue tracker. For questions please go to http://stackoverflow.com/questions/tagged/neo4j or neo4j.com/slack

For the number of relationships you run `MATCH (:User)-[:LIKES]->(:Post) RETURN count(*)`
Note that labels and relationship-types are case sensitive.
