### ISSUE TITLE
How to Get Mutual Friends ?

### ISSUE THREAD

**Issue by rajkuttie** [neo4j/neo4j#9109]
I have a one label. That label name is users. All users can be related with follow edge. Now I want get show for non-relation users.  Like facebook **people you may know friends**  Or Facebook mutual friends. 
How I can show ? Can anybody tell example Query . 

Thanks,

**Comment by jastax** [comment]
This is not an issue. Please ask questions somewhere else, like stackoverflow. 

Match (u:User {identifier: identifier_of_user})-[:FRIEND]->(:User)-[:FRIEND]->(new:Friend) 
WHERE NOT (u)-[:FRIEND]->(new)
RETURN new

**Comment by rajkuttie** [comment]
@jansta Thanks man
