### ISSUE TITLE
Unmanaged server extensions not working for me

### ISSUE THREAD

**Issue by sagargithub399** [neo4j/neo4j#9131]
I am following this java reference guidehttps://neo4j.com/docs/java-reference/3.1/#procedures-extensions-desktop seciton 1.2.  HelloWorldResource example is not working for me. Below are the details

I have created plugins folder in neo4j_home and pasted the jars
javax.servlet-api-3.1.0,neo4j-3.1.2 and unmanaged-0.0.1-SNAPSHOT.
Created conf folder and in that created neo4j.conf inside it with content 
dbms.unmanaged_extension_classes=com.sagar.unmanaged=/examples/unmanaged

Requesting http://localhost:7474/examples/unmanaged/helloworld/123 giving me 404.

What I am doing wrong over here, Am I not making the jar properly.
Attaching the pom file.
[pomFile.zip](https://github.com/neo4j/neo4j/files/888543/pomFile.zip)
Any suggestion. Thanks is advance.

**Comment by MMJM** [comment]
Hi did you ever solve this issue?

I'm having a similar problem and getting a 404 after following all the install instructions.

**Comment by jexp** [comment]
It would be good if either of you could share a full copy of the project you're building and a copy of your config and listing of the `$NEO4J_HOME/plugins` directory.

**Comment by MMJM** [comment]
Mine is solved now. Don't bother with the Mac dmg get the tar ball then the instructions probably work as the dmg seems to get files from different places.

**Comment by Lojjs** [comment]
@362466 While have not received the info requested by @jepx above, I will close this issue. If you still would have problems, feel free to re-open it or create a new one.

Best regards Louise, Neo4j Cypher team
