### ISSUE TITLE
Access-Control-Allow-Origin header missing on responses other than 200 or 404.

### ISSUE THREAD

**Issue by Vilx2** [neo4j/neo4j#9151]
When performing requests against the REST endpoints, the Access-Control-Allow-Origin header is only present on the responses that have HTTP status codes 200 and 404. Other responses (like 302, 401, 400, etc) do not have this header. As a result ajax requests from the browser fail in these cases and do not report any status information to the calling script. This makes it impossible to distinguish between cases like a wrong URL, incorrect credentials, etc.

**Neo4j Version:** 3.1.3 
**Operating System:** Windows 7
**API:** Javascript from a browser using REST endpoints

### Steps to reproduce
Execute a script that uses XMLHttpRequest to retrieve http://localhost:7475/db/data/ but passes incorrect credentials.

### Expected behavior
XMLHttpRequest reports status 401.

### Actual behavior
XMLHttpRequest reports status 0

**Comment by technige** [comment]
Thanks, we'll look into this.
