### ISSUE TITLE
Neo4j community edition and Ldap integration

### ISSUE THREAD

**Issue by mayankdevops** [neo4j/neo4j#9161]
Need some help with Neo4j and Ldap(AD) integration. I saw in the docs that security logs are only available with enterprise version. Is Ldap integration allowed with community version ?

I am using Neo4j community edition 3.1.3 (Windows 64 bit , zip distribution) Please find the relevant neo4j.conf entries below:

```
dbms.security.auth_enabled=true
dbms.security.log_successful_authentication=true
dbms.security.auth_provider=ldap
dbms.security.ldap.host=ldaps://example.com:636 
dbms.security.ldap.authentication.user_dn_template=CN={0},OU={0},DC=eg,DC=com
dbms.security.ldap.authorization.user_search_base=OU={0},DC=eg,DC=com
dbms.security.ldap.authorization.user_search_filter=(&(objectClass=*)(CN={0}))
dbms.security.ldap.authorization.group_membership_attributes=memberOf
dbms.security.ldap.authorization.group_to_role_mapping=\
  "sample base dn of ldap groups"       = reader; \
  "sample base dn of ldap groups"       = publisher; \
  "sample base dn of ldap groups"       = architect; \
  "sample base dn of ldap groups"       = admin; \
  "sample base dn of ldap groups"       = allowed_role
dbms.security.auth_cache_ttl=1m

```
Optionally i have also tried this:

```
#dbms.security.ldap.authorization.use_system_account=true
#dbms.security.ldap.authorization.system_username=[BaseDN]
#dbms.security.ldap.authorization.system_password=[]
```

> Error i get : The client is unauthorized due to authentication failure.

And there is nothing in the logs for authentication failure i checked below mentioned log files:

debug.log, http.log, neo4j.log, neo4j-service.2017-04-06.log, service-error.log

**Comment by spacecowboy** [comment]
LDAP integration is enterprise only:

https://neo4j.com/docs/operations-manual/current/security/authentication-authorization/

> The features described in this section are available in Neo4j Enterprise Edition.

**Comment by mayankdevops** [comment]
Thanks a lot for the reply. I missed out that line.
Now I am referring to 
https://neo4j.com/docs/operations-manual/current/reference/user-management-community-edition/

I cant find listRoles() under this. So roles are also not supported with community versions ?

Thanks,
-Mayank Gangwal

**Comment by spacecowboy** [comment]
if it's not listed there then it's only in the enterprise version.

You can see it mentioned here: https://neo4j.com/docs/operations-manual/current/reference/procedures/#_procedures_for_native_user_and_role_management

Under the text

> We provide below a list of all available procedures for native user and role management. These procedures are available in Neo4j Enterprise Edition.

**Comment by mayankdevops** [comment]
Thanks for your reply.  
We will be looking for the possibilities for getting the enterprise version soon.
