### ISSUE TITLE
Feature Request: let dbms.procedures() YIELD mode

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j/neo4j#9170]
Currently `dbms.procedures()` YIELDS roles (and only for the enterprise edition), but it would be helpful to YIELD mode as well, which would save from having to decode mode based on roles values.

**Comment by sherfert** [comment]
Thanks for that feature request. It will be evaluated for future work.

**Comment by sherfert** [comment]
The feature will be available in 3.4.0 alpha08 and later
