### ISSUE TITLE
Bug in latest BOLT Python Driver [ api.py - def _disconnect(self, sync) ]

### ISSUE THREAD

**Issue by gonzaedu61** [neo4j/neo4j#9176]
After upgrading the library to its latest version a couple of days ago my programs stopped working. I followe up on the error trace and realized that a couple of "None" value checks were missing in the above referenced method. I adjusted it adding a couple of lines and now everything works fine. Please verify and update the code accordingly if I am not wrong. Here the adjusted code with the added lines in bold:

    def _disconnect(self, sync):
        if self._connection **is not None**:
            if sync:
                self._connection.sync()
            **if self._connection is not None:**
                self._connection.in_use = False
                self._connection = None
                self._connection_access_mode = None

**Comment by chrisvest** [comment]
Please raise this issue on the Python driver repository: https://github.com/neo4j/neo4j-python-driver
