### ISSUE TITLE
Eclipse memory analyzer suspect memory leak in neo4j

### ISSUE THREAD

**Issue by GAURAVJAYSWAL** [neo4j/neo4j#9210]
java.lang.Thread @ 0x6c0328660 MuninnPageCache[1]-FlushTask Thread
10,000	120	640,000	832
\
<Java Local>, parkBlocker org.neo4j.io.pagecache.impl.muninn.MuninnPageCache @ 0x6c03287d8
10,000	80	640,000	2,804,936
.\
pages org.neo4j.io.pagecache.impl.muninn.MuninnPage[700412] @ 0x6c0000000
10,000	2,801,664	640,000	2,804,440
![screenshot from 2017-04-13 15-54-16](https://cloud.githubusercontent.com/assets/19775539/25001108/801424e6-2061-11e7-9a2f-54e3ce833705.png)
![screenshot from 2017-04-13 15-54-04](https://cloud.githubusercontent.com/assets/19775539/25001109/80170ad0-2061-11e7-8218-4051f0552b94.png)

## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests.  If you have questions on how to use Neo4j, please ask on [StackOverflow](http://stackoverflow.com/questions/tagged/neo4j) instead of creating an issue here.

If you want to make a feature request then there is no guideline, so feel free to stop reading and open an issue. If you have a bug report however, please continue reading.

To help us understand your issue, please specify important details, primarily:

- Neo4j version: X.Y.Z
- Operating system: (for example Windows 95/Ubuntu 16.04)
- API/Driver: (for example Cypher/Java API/Python driver vX.Y.Z)
- **Steps to reproduce**
- Expected behavior
- Actual behavior

Additionally, include (as appropriate) log-files, stacktraces, and other debug output.

## Example bug report

I discovered that when I mount `data/` to a volume on my host, and then stop the container, the `write.lock` is not removed as well as a number of other files not being cleaned up properly.

**Neo4j Version:** 3.0M03  
**Operating System:** Ubuntu 15.10  
**API:** Docker

### Steps to reproduce
1. Pull the image: `docker pull neo4j/neo4j:3.0.0-M03`
2. Create a directory on the host that will be a mount for the data: `mkdir /home/neo4j-data`
3. Start a new container that mounts to this directory: `docker run -d --name neo4j-test -p 7474:7474 -v /home/neo4j:/data neo4j/neo4j:3.0.0-M03`
4. Navigate to the `write.lock` file located in the directory: `/data/databases/graph.db/schema/label/lucene/labelStore/1/`
5. Stop the container: `docker stop neo4j-test`

### Expected behavior
`write.lock` should be removed now.

### Actual behavior
`write.lock` is still present and preventing access by other programs.

**Comment by chrisvest** [comment]
@GAURAVJAYSWAL Please add more description as to why you believe this is a memory leak.

**Comment by GAURAVJAYSWAL** [comment]
I'm getting this error in neo4j message.log 
2017-04-17 05:22:27.466+0000 WARN  [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 510ms.
2017-04-17 05:25:27.965+0000 WARN  [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 445ms.
2017-04-17 05:28:28.519+0000 WARN  [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 502ms.
2017-04-17 05:31:29.032+0000 WARN  [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 458ms.
2017-04-17 05:32:20.829+0000 WARN  [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 523ms.
2017-04-17 05:32:23.367+0000 WARN  [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 535ms.

And, When I have analyzed heap dump in eclipse memory analyzer, It's the suspect memory leak in neo4j... there is two task, which is stuck flush task and eviction tasks...

**Comment by chrisvest** [comment]
Those log lines only say that the JVM is paused for half a second every few minutes. They don't appear to be getting better or worse.

The Eclipse MAT Leak Suspects report is very simple: it just ranks the GC roots by their retained set size. We currently spend a lot of heap on page cache meta-data. It's the biggest heap usage after a fresh start, so it's no surprise to see it on top in your report. The two threads you mention do background work for the page cache.

All of this looks normal for a running database, but you will want to tune your heap size and/or GC parameters to bring the pause times down.
