### ISSUE TITLE
Be able to return NULL last when doing descending sort 

### ISSUE THREAD

**Issue by Artgit** [neo4j/neo4j#9213]
Based on the following question http://stackoverflow.com/questions/43415799/neo4j-cypher-query-sort-order/43416177?noredirect=1#comment73896042_43416177 I'd like to request a new feature in Neo4j to be able to return NULL last when doing descending sort. Thanks.

**Comment by nikuelias** [comment]
+1

**Comment by systay** [comment]
Good idea. Would you mind raising this against this repo instead: https://github.com/opencypher/openCypher/issues

This is where the language semantics is worked on.

**Comment by Artgit** [comment]
Thanks for your answer. I have created a following ticket there: https://github.com/opencypher/openCypher/issues/238
