### ISSUE TITLE
Feature Request: Conditional MATCH based on parameters

### ISSUE THREAD

**Issue by senica** [neo4j/neo4j#9219]
This might be more specific to drivers than to neo4j itself. 

- I had a situation arise where I want to use `MATCH` only *if* a passed in parameter exists and is not null.
- I don't want to use `OPTIONAL MATCH` because I want the query to stop (fail) if the passed in parameter is not null but the value doesn't exist in the database.
- I don't want to use `FOREACH` *hacks* because I want to use the resulting variables of the `MATCH` query.

I'll show an example as if using the nodejs driver
```
db.run(`
  // MATCH (u:user {name: $name}) - This will fail, but I don't want it to as the value is null, so I don't care about the match. I want to continue with my query. 
  // OPTIONAL MATCH (u:user {name: $name}) - pretty much works the same as MATCH in this case, except that if $name has a value, then optional match will just return NULL, whereas I want it to fail if the match does not result in something.
  CASE WHEN exists($name) AND IS NOT NULL THEN
    MATCH (u:user {name: $name})
  END
  RETURN CASE WHEN exists(u) THEN u ELSE NULL END
`, {
  name: null,
})
```

In this case, I would expect that if $name exists and is not null, then a MATCH will be performed with the value passed in. If the match fails, the query will stop execution. 

I think something like this has been proposed, but I haven't seen anything that relates specifically to parameters.

[Here is a SO question of where this feature request arose](http://stackoverflow.com/questions/43481472/if-else-with-cypher-neo4j)

**Comment by InverseFalcon** [comment]
With APOC conditional cypher execution, is this feature request still needed?

**Comment by senica** [comment]
I don't believe so.
