### ISSUE TITLE
Neo4J enterprise trial 3.1.3 and Ldap integration

### ISSUE THREAD

**Issue by mayankdevops** [neo4j/neo4j#9258]
- Neo4j version: Enterprise trial 3.1.3
- Operating system: Windows 7 Enterprise

We are able to connect to using Ldap creds by using the below configs:
```
dbms.security.auth_enabled=true
dbms.security.auth_provider=ldap
dbms.security.ldap.host=ldap://hostname:389
dbms.security.ldap.authentication.mechanism=simple
dbms.security.ldap.authentication.user_dn_template=CN={0},OU=Users,OU=CITY,OU=State,OU=Country,OU=GeoArea,OU=Company,DC=example,DC=com
dbms.security.ldap.authorization.user_search_base=DC=example,DC=com
dbms.security.ldap.authorization.user_search_filter=(sAMAccountName={0})
```
User name to be used in this particular case for me is "FirstName LastName"
_**Issue is what happens if some users does not have same format of Base DN , Suppose a OU is completely not there or something. Or even if City , State, Country changes.
Also is there a way to disable user dn template ?

Also can we logon using our employee ids ? Employee ID is not part of User Base DN (adspath).**_

Thanks,
-Mayank Gangwal

**Comment by Dcanzano** [comment]
regarding logging is employeeID, are you speaking of samAccountname, if so see https://neo4j.com/docs/operations-manual/current/security/authentication-authorization/ldap-integration/#_configure_the_ldap_auth_provider which contains a block on authenticating in with samAccountName.

**Comment by craigtaverner** [comment]
Hopefully the reference to the documentation above answered the question above. If not, please re-open the issue with more details.
