### ISSUE TITLE
Questions about import data

### ISSUE THREAD

**Issue by new94** [neo4j/neo4j#9275]
- Neo4j version: 3.1.3
- Operating system: Ubuntu 16.04
- API/Driver: Java API

I have any questions.

**1.** Could you please give the description of the structure of neo4j files in which data stors? I mean how nodes and relationships are stored in neo4j files?
**2.** Is there any possibility to use another file system for neo4j files like HDFS?
**3.** Can we extend io neo4j to use with another file system?

**Comment by chrisvest** [comment]
Are you trying to achieve some sort of efficient import of data into Neo4j? We have `import-tool` and `neo4j-admin import`, which efficiently consumes CSV files and produces Neo4j graphs that you can start the database on.

We don't have any direct/built-in integration with HDFS, or any other file system that isn't accessed via the OS file system APIs. We have special integrations for CAPI Flash based storage. Extension is technically _possible_ but entirely unsupported, relying on private APIs, and I would recommend not trying to do that unless it's only for academic research purpose.
