### ISSUE TITLE
Connecting Neo4j browser to database on a private subnet

### ISSUE THREAD

**Issue by naisanza** [neo4j/neo4j#9285]
I've been looking for a week now, looking for a way to connect a neo4j-browser to a Neo4j database that sits on the same private subnet 

I haven't been able to find in the  neo4j-browser GitHub repository to find a location to hard code in the server address.

And setting the address through the neo4j-browser requires you to execute the ":server connect" command, however it only works with publicly accessible address spaces

Looking to see if anyone has any ideas

Reference to OP https://github.com/neo4j/neo4j-browser/issues/448

**Comment by jexp** [comment]
You can try :config host: host:port
Perhaps you need to add http, don't remember. The side panel has a config for the bolt:// connection but you don't need it in 3.x

Michael 

Von meinem iPhone gesendet

**Comment by naisanza** [comment]
Update: @jexp it seems that it's just stored in memory, and restarting the neo4j-browser instance resets it back to default. But even if I've added it with `:config host 10.200.0.109:7473` (neo4j-browser and neo4j database are on the same subnet), how do I get past `:server connect`?

I still get the WebSocket connection failure: 

```
N/A: WebSocket connection failure. Due to security constraints in your web browser, the reason for the failure is not available to this Neo4j Driver. Please use your browsers development console to determine the root cause of the failure. Common reasons include the database being unavailable, using the wrong connection URL or temporary network problems. If you have enabled encryption, ensure your browser is configured to trust the certificate Neo4j is configured to use. WebSocket `readyState` is: 3
```

And inspecting the browser, it executes `neo4j-web.min.js:19755` with a request url of `Request URL:wss://http:7687/`

@jexp is there a command to remove an added config option? And also, where is the config file that corresponds to `:config` located in?

**Comment by naisanza** [comment]
Not possible per @oskarhane

```
You need to expose the bolt ports to the outside world to be able to connect
```
https://neo4j-users.slack.com/archives/C192NVBNE/p1493796176467703
