### ISSUE TITLE
Range request causes server to hang

### ISSUE THREAD

**Issue by wjdhamilton** [neo4j/neo4j#9297]
- Neo4j version: 3.1.1
- Operating system: macOS Sierra 10.12.4
- API/Driver: http

This problem was originally discovered using the neo4jrb gem, but I will explain the necessary steps using the neo4j browser. 

```cypher
CREATE (n:NewsItem { title: "Clickbait", story: "Something I made up", posted_on: 1493895053 }) RETURN n
```

Then

```cypher
  MATCH (result_newsitem:`NewsItem`)
  WHERE (result_newsitem.posted_on IN RANGE(1262304000, 1493895053))
  RETURN count(result_newsitem)```
```
- Expected behavior:

The created node is returned

- Actual behavior

The server hangs and cannot be stopped or restarted without killing the process with a level 9 signal.

**Comment by jexp** [comment]
Interesting, I think it works as designed.

This creates a list of 231.591.053 entries which each newsitem is checked against (or rather the index).

The expected query for that would be:

```
  MATCH (result_newsitem:`NewsItem`)
  WHERE 1262304000 <= result_newsitem.posted_on <= 1493895053
  RETURN count(result_newsitem)
```

Which will also use the index but only by passing a range query to the index with lower and upper bound.

But this might be a opportunity for query rewriting.

**Comment by wjdhamilton** [comment]
Sorry to be stupid, but what creates the list of 231.591.053 entries?

**Comment by wjdhamilton** [comment]
Sorry, I think I get it - by entries you mean the `RANGE` keyword creates a list of objects which all the `newsitem` instances are checked against. Right, OK that makes sense. Thank you!

This came from trying to use the Rails idiom of looking things up within a date range.

**Comment by jexp** [comment]
Good point about raising it though 

Von meinem iPhone gesendet

**Comment by sherfert** [comment]
@wjdhamilton Have you been able to reformulate the Cypher query so it does not hang?

**Comment by wjdhamilton** [comment]
It was a while ago, but I think I just used logical operators instead of `RANGE` as @jexp suggested. Sorry, I should have closed the issue.
