### ISSUE TITLE
Neo4j Cypher node filtering by pattern comprehension

### ISSUE THREAD

**Issue by Artgit** [neo4j/neo4j#9329]
I have a following SDN 4 entities:

`Decision`, `Characteristic` and `Value`:

    @NodeEntity
    public class Value extends Votable {
    
    	private final static String SET_FOR = "SET_FOR";
    	private final static String SET_ON = "SET_ON";
    	private final static String CONTAINS = "CONTAINS";
    
    	@Relationship(type = SET_FOR, direction = Relationship.OUTGOING)
    	private Decision decision;
    
    	@Relationship(type = SET_ON, direction = Relationship.OUTGOING)
    	private Characteristic characteristic;
    
    	@Index(unique = false)
    	private Object value;
    
        ...
    }

I have created 3 `Decicion`(`Decicion1`, `Decision2`, `Decisison3`) nodes and 1 `Characteristic`(`Characteristic1`).
For `Decicion1`, `Decicion2` and `Characteristic1` I have created a `Double` `Value`, for example:

    Decision1 + Characteristic1 = Value(500d)
    Decision2 + Characteristic1 = Value(1000d)
    Decicion3 doesn't have any Value on Characteristic1

I need to create a query that will return all `Decision` which have `Value` in the defined range, for example `100 <= value <= 50000`

Based on the example above this query should return `Decision1` and `Decicion2` only.

Right now I have a following query:

    MATCH (parentD)-[:CONTAINS]->(childD:Decision)-[ru:CREATED_BY]->(u:User) 
        WHERE id(parentD) = {decisionId} 
            AND ALL(key IN keys({rangeFilters}) 
                WHERE size(
                    [(childD)<-[:SET_FOR]-(filterValue)-[:SET_ON]->(filterCharacteristic) WHERE id(filterCharacteristic) = toInt(key) AND ({rangeFilters}[key])[0] <= filterValue.value <= ({rangeFilters}[key])[1] | 1]
                ) > 0)  
    RETURN ru, u, childD AS decision SKIP 0 LIMIT 100 

where `rangeFilters` is a `Map<String, Double[]>` where key is a `Characteristic` `ID` and value `new Double[] { new Double(100.d), new Double(50000d) }`

But this query returns all 3 `Decision`, even the `Decision3` that don't have any values associated with `Characteristic1` .

Why the pattern comprehension doesn't work here as expected?

This is an example that highlights the issue: [http://console.neo4j.org/?id=6bv9y5](http://console.neo4j.org/?id=6bv9y5)

Why the only "d1" decision is considered there ?

**Comment by systay** [comment]
Hi!

Sorry for the late reply. Which version of Neo4j are you running this on?

**Comment by Artgit** [comment]
Hi, thanks for your answer. I was using 3.1.3 when created this issue
