### ISSUE TITLE
Neo4j v3.2.0 cursor automatically & randomly switches back to the first position in the editor pane

### ISSUE THREAD

**Issue by aamanlamba** [neo4j/neo4j#9343]
When typing a Cypher query in the Neo4j v3.2 editor, the cursor position occasionally and randomly goes back to the first position in the editor pane, leading to many typing errors and rework,

- Neo4j version: 3.2.0
- Operating system: (for example Windows 95/Ubuntu 16.04): Windows Server 2012
- API/Driver: (for example Cypher/Java API/Python driver : Cypher (Browser v 3.0.1)
- Browser: Google Chrome

- **Steps to reproduce**
  Type a long query, covering multiple lines

- Expected behavior
The text renders correctly, and the cursor does not change position unexpectedly

- Actual behavior
The cursor position occasionally and randomly goes back to the first position in the editor pane

**Comment by whitfa99** [comment]
+1

Neo4j version: 3.2.0

Operating system: Linux Mint 18 front
API/Driver: Cypher (Browser v 3.0.1) +Bolt

Browser: Slimjet  (Chromium-based browser)

**Comment by oskarhane** [comment]
Thanks for the report @aamanlamba!
I'm sorry for the inconvenience, we'll look into this.

There's a separate repo for Neo4j Browser: https://github.com/neo4j/neo4j-browser
Please open an issue there so we track it easier.

I'm closing this issue here.
