### ISSUE TITLE
Aggregation on paths with DISTINCT keyword fails with UnknownError key not found: UNNAMED*

### ISSUE THREAD

**Issue by frant-hartm** [neo4j/neo4j#9347]
### Steps to reproduce

Run cypher query:

`MATCH p=(n)-[*0..1]-()
RETURN COLLECT(DISTINCT p)`

Fails with:
`MATCH p=(n)-[*0..]-()
 RETURN COLLECT(DISTINCT p)
ERROR
Neo.DatabaseError.General.UnknownError
key not found: UNNAMED12`

Note that it doesn't fail when the path doesn't have length limit.

## Expected behaviour

As in previous versions.

## Environment
- Neo4j version: 3.2.0
- Operating system: XUbuntu 16.04
- API/Driver: Cypher/Java API/ neo4j-shell

**Comment by InverseFalcon** [comment]
Likely related to #9336. Noting that the error does not occur if `DISTINCT` is removed.

**Comment by InverseFalcon** [comment]
Workaround in the meantime, prefix query with `CYPHER 3.1`

**Comment by craigtaverner** [comment]
Looks like it will be fixed by https://github.com/neo4j/neo4j/pull/9356

**Comment by fairy3** [comment]
Hi,
do you have fix (patch) for it?

**Comment by fairy3** [comment]
Should I use another Cypher version?

**Comment by jexp** [comment]
It will be part of the next point release so 3.2.1 until then try to prefix your statement with `cypher 3.1 `
