### ISSUE TITLE
":server status" is unknown browser command

### ISSUE THREAD

**Issue by cybersam** [neo4j/neo4j#9348]
When I try to run `:server status` from the neo4j 3.2.0 browser, I get this result:

    Unknown command :server status

**Neo4j Version:** 3.2.0  
**Operating System:** OSX 10.11.16 
**API:** Docker

### Steps to reproduce
1. Run `:server status` from the neo4j 3.2.0 browser,
2. Look at the response

### Expected behavior
Information about the status of the neo4j server

### Actual behavior
    Unknown command :server status

**Comment by oskarhane** [comment]
Hi @cybersam,
Thanks for the report. We are aware of this and it'll be back in the next release. Sorry about the inconvenience.
I'll close this issue here since it belongs to https://github.com/neo4j/neo4j-browser.
Feel free to open a new issue there or take my word for it :)
