### ISSUE TITLE
Database hangs in unusable state for 10~ seconds

### ISSUE THREAD

**Issue by bHacklv** [neo4j/neo4j#9357]
When I start Session->Transaction and create Constraint or Index in it, after trying to drop it twice in a row and catching the exception, the new Session->Transaction can't do anything for first 10~ seconds.
My guess is that it ends up going into some sort of 'recovery' state while deleting records of created Constraint/Index.

**Neo4j Version:** Tested on 3.1.2 & 3.2.0
**Operating System:** Win7

### Steps to reproduce

1. Start Session1
2. Start Transaction1
3. Create UNIQUE CONSTRAINT
4. DROP UNIQUE CONSTRAINT
5. DROP UNIQUE CONSTRAINT + Catch Exception (No such constraint ...)
6. Close Transaction1
7. Close Session1

8. Start Session2
9. Start Transaction2
10. Do READ/WRITE/ANY operation
11. -> reports Transaction timeout with Overtime: N ms.

### Expected behavior
Performs action in Step 10 with no problems

### Actual behavior
If Transaction timeout is set to 2 seconds:
org.neo4j.driver.v1.exceptions.ClientException: Transaction timeout. (Overtime: 9305 ms).

If Transaction timeout is set to 5 seconds:
org.neo4j.driver.v1.exceptions.ClientException: Transaction timeout. (Overtime: 5906 ms).

If Transaction timeout is set to 12 seconds:
Performs action from Step 10.

### test code
```java
import static org.neo4j.graphdb.factory.GraphDatabaseSettings.transaction_timeout;

import org.junit.Rule;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.BlockJUnit4ClassRunner;
import org.neo4j.driver.v1.*;
import org.neo4j.harness.junit.Neo4jRule;

@RunWith(BlockJUnit4ClassRunner.class)
public class NativeSchemaDropTest {

    @Rule
    public Neo4jRule neo4j = new Neo4jRule().withConfig(transaction_timeout.name(), "2s");

    @Test
    public void testDropConstraint() throws Exception {
        try (Driver driver = GraphDatabase.driver(neo4j.boltURI(), Config.build().withEncryptionLevel(Config.EncryptionLevel.NONE).toConfig())) {
            final Session session = driver.session();

            try (final Transaction transaction = session.beginTransaction()) {
                transaction.run("CREATE CONSTRAINT ON (t:Test) ASSERT t.test IS UNIQUE").consume();
                transaction.run("DROP CONSTRAINT ON (t:Test) ASSERT t.test IS UNIQUE").consume();
                transaction.run("DROP CONSTRAINT ON (t:Test) ASSERT t.test IS UNIQUE").consume();
            } catch (final Exception exception) {
                System.out.println("Caught exception " + exception.getMessage());
            }
            session.close();

            final Session session2 = driver.session();
            try (Transaction transaction = session2.beginTransaction()) {
                transaction.run("MATCH (n) RETURN n").consume();
                transaction.success();
            }
        }
    }
}
```

### Neo4j 3.1.0
Performs Actions from Step 10 with no problems (timeout set to 2 seconds)

**Comment by tinwelint** [comment]
I could reproduce this in 3.1, however I tried this in 3.5 now and it works, it neither block nor times out, so it seems to have been fixed.
