### ISSUE TITLE
How can I get all paths of two nodes with java api？

### ISSUE THREAD

**Issue by naniya** [neo4j/neo4j#9361]
How can I get all paths of two nodes with java api？

**Comment by sherfert** [comment]
Hi @naniya 
Such questions are better redirected to Stackoverflow.

You can use a Cypher query for your purpose. It will look like:

`MATCH (n)-[*]-(m) RETURN n,m`

Be aware this operation does not limit the length of the path and can therefore be quite expensive in large graphs. For the Java API in general, consult the manual https://neo4j.com/developer/java/
