### ISSUE TITLE
Browser parsing comments incorrectly

### ISSUE THREAD

**Issue by whitfa99** [neo4j/neo4j#9363]
The new browser seems to parse comments (when on their own line) incorrectly 

**Neo4j Version:** 3.2  
**Operating System:** Linux Mint 18  
**API:** Neo4j Browser 3.0.1 + Bolt

### Steps to reproduce

Run this Cypher statement:

    WITH 1 as One
    //Comment
    RETURN One

### Expected behavior

Output:

    "One"
    1

### Actual behavior

    Invalid input 'n': expected 'r/R' or 'p/P' (line 1, column 22 (offset: 21))
    "WITH 1 as OneRETURN One"

Also, any new lines seem to be stripped (after clicking the executed statement to be populated in the editor):

    WITH 1 as One
    
    RETURN One

becomes

    WITH 1 as One
    RETURN One

Maybe this is my personal preference, but I would rather maintain readability of large statements by retaining these line breaks.

**Comment by oskarhane** [comment]
Thanks for the issue report @whitfa99!
This is however the wrong repository since the Neo4j Browser lives in https://github.com/neo4j/neo4j-browser.
Could you re-open this issue there?
Thanks.

**Comment by whitfa99** [comment]
Thanks for reposting this [here](https://github.com/neo4j/neo4j-browser/pull/530)
