### ISSUE TITLE
Autocompletion for properties with spaces should automatically quote them

### ISSUE THREAD

**Issue by lilianaziolek** [neo4j/neo4j#9366]
## Guidelines
- Neo4j version: 3.2.0
- Operating system: Windows 7/8
- API/Driver: Cypher in browser
- **Steps to reproduce**
Create a label with nodes with property that contains spaces (in my case I'm importing all properties from a CSV where header contains spaces). When using the autocompletion feature in the browser (which is awesome BTW) the properties are picked up, even if they contain spaces (that's good). However, when I select one of them, it does not work as expected.
- Expected behavior
If the property contains a space, it should automatically be quoted, e.g.:
n.`MY PROP WITH SPACE`
(the markdown here does something funny, basically it should be the "angled" quote sign ` around the property name)
- Actual behavior
when selecting the property, the property is inserted "as is" which results in non-compiling cypher like n.MY PROP WITH SPACE

**Comment by oskarhane** [comment]
Thanks, we really appreciate you reporting issues @lilianaziolek. It's great!
As I mentioned in an other issue, could you open an issue for this in the https://github.com/neo4j/neo4j-browser repo instead?
Thanks.

**Comment by lilianaziolek** [comment]
n/p, will do, and will remember that other tracker in the future :)
