### ISSUE TITLE
Starting Neo4j 3.2.0 with APOC apoc-3.1.3.7-all.jar fails to start

### ISSUE THREAD

**Issue by aamanlamba** [neo4j/neo4j#9367]
## Guidelines

- Neo4j version: 3.2.0
- Operating system: Windows Server 2012
- API/Driver: APOC 3.1.37
- **Steps to reproduce**
Place the latest APOC JAR (apoc-3.1.3.7-all.jar) in the plugins folder of Neo4j and start the service
- Expected behavior
Neo4j starts smoothly
- Actual behavior
Neo4j fails to start

Error:

> 2017-05-17 14:24:03.887+0000 INFO  ======== Neo4j 3.2.0 ========
> 2017-05-17 14:24:05.049+0000 INFO  Starting...
> 2017-05-17 14:24:07.768+0000 INFO  Bolt enabled on 0.0.0.0:7687.
> 2017-05-17 14:24:10.129+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.Li
> fecycleManagingDatabase@4e38a98d' was successfully initialized, but failed to start. Please see attached cause exception
> . Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@4e38a98d' was successfully initi
> alized, but failed to start. Please see attached cause exception.
> org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDa
> tabase@4e38a98d' was successfully initialized, but failed to start. Please see attached cause exception.
>         at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
>         at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:219)
>         at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:107)
>         at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:80)
>         at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:28)
> Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase
> @4e38a98d' was successfully initialized, but failed to start. Please see attached cause exception.
>         at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
>         at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
>         at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:211)
>         ... 3 more
> Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, D:\Apps\
> Neo4j CE 3.1.4\data\databases\graph.db
>         at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:209)
>         at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:124)
>         at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:58)
>         at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:89)
>         at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
>         ... 5 more
> Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'apoc.ApocKernelExtensionFactory$ApocLifecycle@7189e
> 656' was successfully initialized, but failed to start. Please see attached cause exception.
>         at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
>         at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
>         at org.neo4j.kernel.extension.KernelExtensions.start(KernelExtensions.java:85)
>         at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
>         at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
>         at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:205)
>         ... 9 more
> Caused by: java.lang.NoSuchMethodError: org.neo4j.kernel.configuration.Config.getParams()Ljava/util/Map;
**>         at apoc.ApocConfiguration.initialize(ApocConfiguration.java:30)
>         at apoc.ApocKernelExtensionFactory$ApocLifecycle.start(ApocKernelExtensionFactory.java:65)**
>         at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
>         ... 14 more
> 2017-05-17 14:24:10.153+0000 INFO  Neo4j Server shutdown initiated by request
> 1
> 

Additionally, include (as appropriate) log-files, stacktraces, and other debug output.

## Example bug report

I discovered that when I mount `data/` to a volume on my host, and then stop the container, the `write.lock` is not removed as well as a number of other files not being cleaned up properly.

**Neo4j Version:** 3.0M03  
**Operating System:** Ubuntu 15.10  
**API:** Docker

### Steps to reproduce
1. Pull the image: `docker pull neo4j/neo4j:3.0.0-M03`
2. Create a directory on the host that will be a mount for the data: `mkdir /home/neo4j-data`
3. Start a new container that mounts to this directory: `docker run -d --name neo4j-test -p 7474:7474 -v /home/neo4j:/data neo4j/neo4j:3.0.0-M03`
4. Navigate to the `write.lock` file located in the directory: `/data/databases/graph.db/schema/label/lucene/labelStore/1/`
5. Stop the container: `docker stop neo4j-test`

### Expected behavior
`write.lock` should be removed now.

### Actual behavior
`write.lock` is still present and preventing access by other programs.

**Comment by chrisvest** [comment]
The first 3 digits of the APOC version has to match the Neo4j version, so you need apoc-3.2.0.x, not apoc-3.1.3.7.

**Comment by aamanlamba** [comment]
Thanks - it looks like APOC has not yet released a matching version for Neo4j 3.2
