### ISSUE TITLE
Suggestion: give ability to switch autocompletion off

### ISSUE THREAD

**Issue by lilianaziolek** [neo4j/neo4j#9371]
Whilst the new autocompletion is generally awesome, I also noticed that it is at times a bit slow - I'm guessing the browser just cannot keep up with my speed of typing sometimes!
The result is that the input box freezes, sometimes jumps around making me type in the wrong place, and overall when I know exactly what I want to type, it simply gets in my way.

It would be great to have a switch that would allow me to switch autocompletion on and off, and when I think and type faster than autocompletion I'd have it off, and when I'm exploring things more slowly I could turn it on.

**Comment by oskarhane** [comment]
Hi and thanks for the feedback @lilianaziolek. 
We are planning to do just that.
Could you open this issue in the https://github.com/neo4j/neo4j-browser repository instead so we can follow it there and close when fixed?
Thanks.

**Comment by lilianaziolek** [comment]
@oskarhane Sure, will do. Should I move the other autocompletion JIRA (for properties with spaces) as well ?
