### ISSUE TITLE
Neo4j v 3.2 build fails on x86

### ISSUE THREAD

**Issue by ketank-new** [neo4j/neo4j#9375]
To help us understand your issue, please specify important details, primarily:

- Neo4j version: v 3.2
- Operating system: ub 16.04, x86
- pre requisites:
sudo apt-get install wget git gcc g++ make openjdk-8-jdk graphviz maven rpm unzip bzip2 nodejs nodejs-legacy npm devscripts debhelper

- **Steps to reproduce**
mvn clean install -DskipBrowser -DskipTests -fn

Can i get inputs on this
I have increased heap size with the below 
 export MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=512m"
	 export JVM_ARGS="-Xms1024m -Xmx1024m"

**********************************************************************

Logs
[INFO] Neo4j .............................................. SUCCESS [04:11 min]
[INFO] Neo4j - Licensing configuration .................... SUCCESS [ 25.239 s]
[INFO] Neo4j - Common ..................................... SUCCESS [ 46.188 s]
[INFO] Neo4j - Resource interface ......................... SUCCESS [  1.129 s]
[INFO] Neo4j - Collections ................................ SUCCESS [  9.689 s]
[INFO] Neo4j - Unsafe Access .............................. SUCCESS [  3.989 s]
[INFO] Neo4j - Primitive Collections ...................... SUCCESS [01:22 min]
[INFO] Neo4j - Graph Database API ......................... SUCCESS [  6.376 s]
[INFO] Neo4j - IO ......................................... SUCCESS [01:06 min]
[INFO] Neo4j - Logging .................................... SUCCESS [  6.972 s]
[INFO] Neo4j - Configuration .............................. SUCCESS [  3.295 s]
[INFO] Neo4j - CSV reading and parsing .................... SUCCESS [  6.216 s]
[INFO] Neo4j - Lucene Index Upgrade ....................... SUCCESS [01:10 min]
[INFO] Neo4j - Native index ............................... SUCCESS [ 26.060 s]
[INFO] Neo4j - Graph Database Kernel ...................... SUCCESS [10:16 min]
[INFO] Neo4j - Command Line ............................... SUCCESS [  8.402 s]
[INFO] Neo4j - Lucene Index ............................... SUCCESS [02:05 min]
[INFO] Neo4j - Import Command Line Tool ................... SUCCESS [03:11 min]
[INFO] Neo4j - Database Management System ................. FAILURE [ 18.879 s] 
[INFO] Neo4j - Graph Algorithms ........................... SUCCESS [ 19.606 s]
[INFO] Neo4j - Code Generator ............................. SUCCESS [ 18.929 s]
[INFO] Neo4j - Community Cypher Build ..................... SUCCESS [01:03 min]
[INFO] Neo4j - Cypher Frontend 3.2 ........................ SUCCESS [03:59 min]
[INFO] Neo4j - Cypher Intermediate Representation 3.2 ..... SUCCESS [ 43.086 s]
[INFO] Neo4j - Cypher Compiler 3.2 ........................ SUCCESS [05:48 min]
[INFO] Neo4j - Cypher ..................................... SUCCESS [10:00 min]
[INFO] Neo4j - Security ................................... SUCCESS [ 21.686 s]
[INFO] SLF4J Neo4j Binding ................................ SUCCESS [  7.284 s]
[INFO] Neo4j - JMX support ................................ SUCCESS [  6.296 s]
[INFO] Neo4j - Usage Data Collection ...................... SUCCESS [ 53.277 s]
[INFO] Neo4j - Monitor Logging ............................ SUCCESS [  5.737 s]
[INFO] Neo4j - Consistency Checker ........................ SUCCESS [05:45 min]
[INFO] Neo4j - Community .................................. SUCCESS [02:32 min]
[INFO] Neo4j - Community .................................. SUCCESS [  0.217 s]
[INFO] Neo4j - Bolt Protocol Version 1 .................... SUCCESS [ 37.743 s]
[INFO] Neo4j - Generic shell .............................. SUCCESS [ 20.012 s]
[INFO] Neo4j - Server API ................................. SUCCESS [  7.479 s]
[INFO] Neo4j - Server ..................................... FAILURE [  7.334 s] 
[INFO] Neo4j - Server Plugin Tests ........................ FAILURE [ 21.953 s]
[INFO] Neo4j - Test Harness ............................... FAILURE [  0.911 s]
[INFO] Neo4j - Procedure Compiler Core .................... SUCCESS [ 26.602 s]
[INFO] Neo4j - Procedure Compiler Parent POM .............. SUCCESS [  0.112 s]
[INFO] Neo4j - Procedure Compiler Integration Tests ....... FAILURE [  6.354 s]
[INFO] Neo4j - Community Build ............................ SUCCESS [  5.745 s]
[INFO] Neo4j - Enterprise Graph Database Kernel Features .. SUCCESS [01:57 min]
[INFO] Neo4j - Enterprise Graph Database Auth Plugin API .. SUCCESS [  0.764 s]
[INFO] Neo4j - Enterprise Graph Database Security Features  SUCCESS [06:47 min]
[INFO] Neo4j - Query Logging .............................. SUCCESS [  3.774 s]
[INFO] Neo4j - Communication Package ...................... SUCCESS [ 55.496 s]
[INFO] Neo4j - Clustering Infrastructure .................. SUCCESS [ 41.343 s]
[INFO] Neo4j - Backup Tool ................................ SUCCESS [03:01 min]
[INFO] Neo4j - Causal Clustering .......................... SUCCESS [01:06 min]
[INFO] Neo4j - Graph DB Monitoring and Management tools ... SUCCESS [  7.668 s]
[INFO] Neo4j - High Availability .......................... SUCCESS [13:11 min]
[INFO] Neo4j - Metrics Kernel Extension ................... SUCCESS [  9.781 s]
[INFO] Neo4j - Enterprise ................................. SUCCESS [06:43 min]
[INFO] Neo4j - Enterprise Cypher Build .................... SUCCESS [  0.578 s]
[INFO] Neo4j - Cypher Compiled Runtime 3.2 ................ SUCCESS [01:02 min]
[INFO] Neo4j Enterprise Cypher ............................ SUCCESS [03:21 min]
[INFO] Neo4j - Enterprise Server .......................... FAILURE [  0.328 s]
[INFO] Neo4j - Enterprise Test Harness .................... FAILURE [  3.647 s]
[INFO] Neo4j - Deferred Locks ............................. SUCCESS [  2.540 s]
[INFO] Neo4j - Cypher Specification Suite Tools ........... FAILURE [ 35.767 s]
[INFO] Neo4j - Cypher Acceptance .......................... FAILURE [  7.541 s]
[INFO] Neo4j - Cypher Compatibility Specification Suite ... FAILURE [  4.035 s]
[INFO] Neo4j - Enterprise Build ........................... SUCCESS [  1.045 s]
[INFO] Neo4j - Integration Tests .......................... FAILURE [  3.575 s]
[INFO] Neo4j - Stress Tests ............................... SUCCESS [  2.194 s]
[INFO] Neo4j - Low Level Tools ............................ FAILURE [02:03 min]
[INFO] Neo4j - Server Assembler ........................... FAILURE [  1.614 s]
[INFO] Neo4j Desktop ...................................... FAILURE [  2.164 s]
[INFO] Neo4j Community - Server Assembler ................. FAILURE [  9.523 s]
[INFO] Neo4j Enterprise - Server Assembler ................ FAILURE [  4.824 s]
[INFO] Neo4j Packaging Build .............................. SUCCESS [  0.074 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

**Comment by ketank-new** [comment]
any inputs on this?

**Comment by chrisvest** [comment]
Your logs omit the part about _why_ it fails.

**Comment by chrisvest** [comment]
Sometimes you get a bad commit where there's a test that consistently fails, and sometimes there's a bug in a test that causes it to be flaky and have non-deterministic false positives. Make sure you're on the latest checkout of the branch, and even then it might take a few tries before it passes.
