### ISSUE TITLE
dbms.allow_format_migration=true overriden by dbms.mode=HA without proper error explanation

### ISSUE THREAD

**Issue by zmarty** [neo4j/neo4j#9392]
**Neo4j Version:** 3.2
**Operating System:** Windows 10 64 bit

### Steps to reproduce
Upgrading from 3.0.6

These settings are both present in the configuration file:
dbms.allow_format_migration=true
dbms.mode=HA

### Expected behavior
The error message should explain that since dbms.mode=HA then you forced dbms.allow_format_migration to be false.

### Actual behavior
ERROR Neo4j cannot be started, because the database files require upgrading and upgrades are disabled in configuration. Please set 'dbms.allow_format_migration' to 'true' in your configuration file and try again

I understand why you are overriding allow_format_migration, but the error message is incorrect.

**Comment by RagnarW** [comment]
Closing due to unsupported version
