### ISSUE TITLE
[Feature] Bundle APOC in the releases

### ISSUE THREAD

**Issue by wadael** [neo4j/neo4j#9394]
- Neo4j version: 3.x
- Operating system: All

### Expected behavior
apoc procedures and functions are available right after installation

### Actual behavior
apoc procedures and functions are not available

I reckon its a lazyness-based feature request. 
However, with around 300 procs and functions filling the lacks of Cypher, hasn't Apoc become part of the crew and be shipped along with neo ?  (puns intended)

**Comment by chrisvest** [comment]
APOC is community maintained. Every procedure we introduce to Neo4j itself will be held to a different standard of quality, testing and compatibility, and thus require more work. For instance, to fix a bug in APOC it requires only releasing a new version of APOC, but a bug in a built-in procedure requires an new release of Neo4j itself. For this reason we'd only consider migrating over individual procedures on a case-by-case basis.

**Comment by wadael** [comment]
Hi Chris,
I think we (users) all add APOC just after install. And yes, I have updated it for a same version of Neo.
I understand the migration process from APOC to official Cypher is not a snap.

In this FR, lazyness is the keyword. 
Bundling the latest available corresponding version will not avoid users to update apoc. 
Just avoid the first install.
Surely, it would impact the stats of apoc downloads but when its possible to avoid to N people to do the same action by doing it at the level above, I think its worth it ...

Just my opinion. Feel free to close this issue.

**Comment by chrisvest** [comment]
Closing this because Neo4j Desktop let's you install APOC with one button click.
