### ISSUE TITLE
Neo4j 3.2 - CALL dbms.listQueries() - Neo.ClientError.Procedure.ProcedureNotFound

### ISSUE THREAD

**Issue by HaakonME** [neo4j/neo4j#9395]
Neo4j version 3.2.0 on Debian GNU/Linux 8.
In Neo4j browser, click star > Common procedures > List running queries > Play-button
I expected to see either running queries or a message saying there were no running queries, but I got an error message.

CALL dbms.listQueries()

Error message: Neo.ClientError.Procedure.ProcedureNotFound

**Comment by HaakonME** [comment]
Also in Neo4j browser under About Neo4j, it says I am running version 3.0.1, but /usr/share/neo4j/bin/neo4j --version
neo4j 3.2.0
which is the latest package I installed.

**Comment by oskarhane** [comment]
Hi, you are running `Neo4j v3.2.0` which includes `Neo4j Browser v3.0.1`. 
Sorry about the confusion.

Are you using Neo4j Community Edition or Enterprise Edition?
If you are using Community, the `CALL dbms.listQueries()` procedure isn't available.
Read more about the different editions: https://neo4j.com/editions/

**Comment by HaakonME** [comment]
Thanks for explanation, I am using the Community edition.
