### ISSUE TITLE
32k limit on label indexes is nowhere documented

### ISSUE THREAD

**Issue by jhb** [neo4j/neo4j#9407]
Neo4j has a known limitation of only allowing 32k characters in a node property - the technical details are in #9331. This limitation is known, and has existed for a while, but is nowhere mentioned.

### Steps to reproduce
See #9331 or https://baach.de/Members/jhb/32-cypher

1. Create a label index on e.g. "text"
2. Create a node with "text" that is longer then 32k
3. See the server crashing, and search the neo4j documentation for a single mentioning of the 32k limit (which seems to be known to the team)

### Expected behavior
Documentation mentions that 32k is the upper limit for property values in label indexes (and legacy indexes), and that values longer than 32766 are either silently truncated (some versions) or will bring the whole server down (e.. 3.2.0), but will not work in any case.

### Actual behavior
Documentation claims that neo4j can do text search, and is silent on the known 32k limit.

**Comment by mariascharin** [comment]
@jhb Thank you and apologies for the very late response!
The documentation has been updated with notes about this limitation in versions 3.2 and onwards.
Cheers,
Maria

**Comment by jhb** [comment]
Could you possibly leave a link to the section of the documentation where the limit is mentioned?  Thanks a lot!
