### ISSUE TITLE
404 error in neo4j

### ISSUE THREAD

**Issue by honeygidwani** [neo4j/neo4j#9412]
Here I am trying to execute shortestPath algorithm in neo4j.

{
        method: 'POST',
        json:true,
        url: 'http://neo4j:admin@localhost:7474/db/data/81/path',
            body:{
            "to" : '/db/data/84',
            "max_depth" : 2,
            "relationships" : {
                "type" : "Meet",
                "direction" : "out"
            },
            "algorithm" : "shortestPath"
        }
    }
The response received is 

error: null
body: {"statusCode":404,"headers":{"date":"Wed, 24 May 2017 05:33:23 GMT","access-control-allow-origin":"*","connection":"close","server":"Jetty(9.2.9.v20150224)"},"request":{"uri":{"protocol":"http:","slashes":true,"auth":"neo4j:admin","host":"localhost:7474","port":"7474","hostname":"localhost","hash":null,"search":null,"query":null,"pathname":"/db/data/81/path","path":"/db/data/81/path","href":"http://neo4j:admin@localhost:7474/db/data/81/path"},"method":"POST","headers":{"authorization":"Basic bmVvNGo6YWRtaW4=","accept":"application/json","content-type":"application/json","content-length":111}}}

Please help me out with this.

**Comment by technige** [comment]
Hi @honeygidwani. The path `/db/data/81/path` shouldn't exist. Do you mean `/db/data/node/81/path` instead?

**Comment by zhenlineo** [comment]
Closing the issue as missing of more feedback to the solution suggested on this issue.
