### ISSUE TITLE
Neo4j Desktop on Windows fails to persist location to .dblocation

### ISSUE THREAD

**Issue by bzikarsky** [neo4j/neo4j#9413]
The launcher of **Neo4j CE 3.2.0 Desktop Edition** on Windows (in this case **Win10 Pro x64**) provides the user with a dialog to chose the location of the database:

![image](https://cloud.githubusercontent.com/assets/225374/26390956/0cda724e-4061-11e7-88fb-36617cb5a279.png)

The problem resolves around the status of the file-chooser-dialog.

### Steps to reproduce
1. Start Neo4j Desktop
2. Chose a non-default database directory 
3. Start server
4. Stop server
5. Exit Neo4j Desktop (Tray-Icon -> Exit to make sure)
6. Start Neo4j Desktop

### Expected behavior
The file-chooser should be configured with the non-standard database-location of step 2.

### Actual behavior
The file-chooser is reset to the default database-location

### Analysis

The functionality for this is actually embedded in Neo4j: https://github.com/neo4j/neo4j/blob/e4d71a6892c12533f1cc8c9f82c60c70ef75da94/packaging/neo4j-desktop/src/main/java/org/neo4j/desktop/model/LastLocation.java

It tries to save the location into `%NEO4J_INSTALL_PATH%/bin/.dblocation`. But since usually Neo4j is installed into a location like `C:\Program Files` with superuser permissions, but neo4j is started by a low-permission user, this file can not be written.

#### Workaround

If `%NEO4J_INSTALL_PATH%/bin/.dblocation` is created with administrative rights and set to user-editable, the dialog works as expected. Note this is only OK with a single-user setup. In a multi-user environment the users would overwrite their DB-location settings.

#### Solution

`%NEO4J_INSTALL_PATH%/bin/.dblocation` should be moved to a user-writable config location such as `%APP_DATA%/Neo4j Community Edition/.dblocation`.

If you agree this the problem/solution I can schedule some time to create a PR/fix for this issue.

**Comment by utkuc** [comment]
This issue was moved to utkuc/neo4j#3

**Comment by chrisvest** [comment]
I'm closing this because Neo4j Desktop has been rewritten and is now a rather different product.
