### ISSUE TITLE
Query planner fails to use index when node name missing

### ISSUE THREAD

**Issue by zmarty** [neo4j/neo4j#9421]
When a node name is not specified in a query, the query planner fails to use indices.

I discovered that when I mount `data/` to a volume on my host, and then stop the container, the `write.lock` is not removed as well as a number of other files not being cleaned up properly.

**Neo4j Version:** 3.2
**Operating System:** Windows 10 64 bit

### Steps to reproduce
Run this query:
(User {id: 'User_12345'})-[:FOLLOWS]->(entity)
RETURN entity.longId

### Expected behavior
Query planner should use the index on the id field like so:
![nodeindex](https://cloud.githubusercontent.com/assets/330396/26418627/c0f27758-4071-11e7-929d-f775d04a3583.PNG)

### Actual behavior
Query planner fails to use index:
![nodescan](https://cloud.githubusercontent.com/assets/330396/26418630/c5ebeff0-4071-11e7-9757-41734cca6902.PNG)

### Workaround
Specify a node name, not only a node type in the query:
(**user**:User {id: 'User_12345'})-[:FOLLOWS]->(entity)
RETURN entity.longId

**Comment by jexp** [comment]
You just forgot the colon in front of the label

Von meinem iPhone gesendet

**Comment by zmarty** [comment]
Yes, you are right.
