### ISSUE TITLE
Query which works well on neo4j 3.0.3 returns error "key not found: UNNAMED*" when work on neo4j 3.2.0

### ISSUE THREAD

**Issue by fairy3** [neo4j/neo4j#9436]
Environment:

- Neo4j version: 3.2.0
- Operating system: Linux 3.10.0-327.13.1.el7.x86_64
- API/Driver: ( Cypher/Java API)

- **Steps to reproduce**
run query:
MATCH ()-[r0:`ACCOUNT_OF`]-() WHERE ID(r0)=145073  WITH STARTNODE(r0) AS n, ENDNODE(r0) AS m MATCH p1 = (n)-[*0..1]-() WITH COLLECT(DISTINCT p1) AS startPaths, m MATCH p2 = (m)-[*0..1]-() WITH startPaths, COLLECT(DISTINCT p2) AS endPaths WITH startPaths + endPaths AS paths UNWIND paths AS p RETURN DISTINCT p

- Expected behavior
as in earlier version, for example:
 (no rows)

- Actual behavior
Neo.DatabaseError.General.UnknownError
        key not found: UNNAMED108 (different numbers)

it causes to cautch exception in my code:
java.lang.RuntimeException: org.neo4j.ogm.exception.TransactionException: key not found:   UNNAMED106
	at org.neo4j.ogm.drivers.bolt.request.BoltRequest.executeRequest(BoltRequest.java:176)
	at org.neo4j.ogm.drivers.bolt.request.BoltRequest.execute(BoltRequest.java:67)
	at org.neo4j.ogm.session.delegates.LoadOneDelegate.load(LoadOneDelegate.java:62)
	at org.neo4j.ogm.session.Neo4jSession.load(Neo4jSession.java:155)

**Comment by InverseFalcon** [comment]
Duplicate of #9347, this is related to variable-length pattern matches when using the DISTINCT keyword, which uses the new pruning var path expander.

This bug is known and a fix is checked in to be released soon with 3.2.1.

In the meantime, prefix the query with `CYPHER 3.1` to avoid the error.

**Comment by fairy3** [comment]
Thanks
