### ISSUE TITLE
Browser broken in Firefox - no internal scrollbar for left pane in 3.2.0

### ISSUE THREAD

**Issue by sammyjava** [neo4j/neo4j#9458]
The left pane is truncated in Firefox under Ubuntu in 3.2.0, with no scrollbar. It works in Chrome under the same Ubuntu.

**Neo4j version:** 3.2.0
**Operating system:** Ubuntu 16.04.2 LTS
**Firefox version:** 53.0.3 (current version from OS repo)

### Steps to reproduce
1. fire up the Neo4j browser in Firefox
2. click the Database Information icon

### Expected behavior
the left pane should be viewable with an internal scrollbar

### Actual behavior
the left pane has no scrollbar, disallowing ability to scroll pane

### Attached screen grab showing browser with no internal scrollbar on left pane

![2017-05-31-132130_1680x1026_scrot](https://cloud.githubusercontent.com/assets/5657219/26650190/dd9e3a56-4605-11e7-85d5-3b8e8174dccf.png)

**Comment by oskarhane** [comment]
Thanks for the report @sammyjava.
There's a separate repository for Neo4j Browser, https://github.com/neo4j/neo4j-browser.

This issue is fixed and will be in the next release: https://github.com/neo4j/neo4j-browser/pull/523
