### ISSUE TITLE
Neo4j 3.2.0 Installation PID bug

### ISSUE THREAD

**Issue by sjishan** [neo4j/neo4j#9467]
Hi, I made a fresh install of Neo4j 3.2.0 in my ec2 instance. As soon as I start the service after installation it says 

`line 411: /var/run/neo4j/neo4j.pid: No such file or directory`

Therefore I added the folder neo4j in `/var/run`.

Although now I am getting a pid assigned when I am running `neo4j start` command but the service is actually not starting. Every time I run the command a new pid is assigned which seems not normal.

I am attaching the debug.log and neo4j.log as TXT files.

[neo4j_log.txt](https://github.com/neo4j/neo4j/files/1045598/neo4j_log.txt)
[debug_log.txt](https://github.com/neo4j/neo4j/files/1045597/debug_log.txt)

**Comment by jennyowen** [comment]
Thanks for reporting this issue, sorry it took so long to address.
This should be fixed by the patch for #11954
