### ISSUE TITLE
Nodes Not Connected to Specified Node

### ISSUE THREAD

**Issue by gptarun** [neo4j/neo4j#9473]
I want to get all the nodes which are not connected to the given node. Suppose I've 5 nodes A,B,C,D,E. Now A->B->C are connected with Is_Friend relationship. Now I want all the nodes which are not connected to A i.e D and E.
I tried this query but it's not working
MATCH (a:Friend{name:"A"})-[:Is_Friend_Of*]->(b:Friend) Match (c:Friend) where not (c)-[:Is_Friend_Of]->(b) return c

Thanks

**Comment by jexp** [comment]
Depending on how big outside your network is you can do:

Collect the neighbourhood and check against it.

```
MATCH path=(a:Friend{name:"A"})-[:Is_Friend_Of*]->(b:Friend)
WHERE NOT (b)-[:Is_Friend_Of]->()
UNWIND nodes(path) as node
WITH collect(distinct node) as nodes
MATCH (n:Friend) WHERE NOT n IN nodes

```
or 

Every node that's not connected to A is also not connected to B C, b/c B and C are connected to A.

```
MATCH (a:Friend{name:"A"})
MATCH (n:Friend) WHERE shortestPath( (n)-[:Is_Friend_Of*]-(a) ) IS NULL
RETURN n

```

**Comment by eebus** [comment]
@tarung1201 
Did it work when using the query above?
