### ISSUE TITLE
Cypher: org.neo4j.cypher.ParameterNotFoundException

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#95]
@bstumm: 'When passing a parameter after a WITH clause, iterating through the ExecutionResult does throw a org.neo4j.cypher.ParameterNotFoundException.

The query where that happens is (problem is the second WHERE):

START n=node(*)
MATCH t<-[:isA]-n<-[nada?:hasPredecessor]-(), n-[?:hasTag]->tag
WHERE nada is NULL and t.name = {typeName}
WITH n, collect(tag.name) as tags
WHERE all(x in {tagNames} where x in tags)
RETURN n'

**Comment by jakewins** [comment]
This was an issue with optional pattern parts, which is no longer supported.
