### ISSUE TITLE
Add support for composite index lookup from Java API

### ISSUE THREAD

**Issue by Tvaroh** [neo4j/neo4j#9508]
Currently, from what I can see, we do only have

```java
Node findNode( Label label, String key, Object value )
```

that is super-limiting when you want to lookup using a composite index.

Is composite index lookup impossible with Java API? If so, please, add one.

**Comment by chrisvest** [comment]
We're focusing on Cypher because it has a rich language for expressing predicates, e.g. ranges, intersect & union, etc. Since you can execute Cypher queries from the Java API, we've decided to punt on extending the Java API.

**Comment by Tvaroh** [comment]
Composite indexes is a core feature enough to be included in the API.
