### ISSUE TITLE
neo4j-admin unexpected output: "unrecognized command: restore"

### ISSUE THREAD

**Issue by davidshumway** [neo4j/neo4j#9512]
Trying to restore from a backup using ```bin/neo4j-admin restore --from=/home/dave/Downloads/k/graph.db```. The program immediately halts with the message: "unrecognized command: restore". Using the downloaded community edition. That is, neo4j is not installed system-wide.

**Neo4j Version:** neo4j-community-3.2.1  
**Operating System:** Fedora 24
**API:** 

### Steps to reproduce
1. Download neo4j community edition.
2. Run the command ```bin/neo4j-admin restore```.

### Expected behavior
Program should not fail prematurely and instead attempt to restore a database.

### Actual behavior
Program fails prematurely and does not attempt to restore a database.

**Comment by martinfurmanski** [comment]
@their Restore is an enterprise feature meant to go together with backup.

In community there is dump/load:
https://neo4j.com/docs/operations-manual/current/tools/dump-load/
