### ISSUE TITLE
Restore browser.remote_content_hostname_whitelist config in community edition

### ISSUE THREAD

**Issue by dhimmel** [neo4j/neo4j#9534]
The Neo4j 3.2 upgrade removed the configuration option for `browser.remote_content_hostname_whitelist` from the community edition. Here's [the source](https://github.com/neo4j/neo4j/blob/f308f766efcd273388dd9b0ebbd420f2d4c39e3f/enterprise/server-enterprise/src/main/java/org/neo4j/server/enterprise/EnterpriseServerSettings.java#L50-L52) for this option. I'm not sure whether this change was intentional, since the [3.2 docs don't specify](https://neo4j.com/docs/operations-manual/3.2/reference/configuration-settings/#config_browser.remote_content_hostname_whitelist) this setting as enterprise only.

`browser.remote_content_hostname_whitelist` has been useful for us to enable custom guides for our [Hetionet Browser](https://neo4j.het.io/browser/). Would it be possible to restore this setting for the community edition?

This issue is referenced in https://github.com/neo4j-contrib/neo4j-guides/issues/14.

**Comment by oskarhane** [comment]
Thanks for the report @dhimmel, this is a regression that'll be fixed.

**Comment by oskarhane** [comment]
This is now fixed with https://github.com/neo4j/neo4j/pull/9615 and will be in the next release.
