### ISSUE TITLE
Upgrade Guava in 3.2 branch (and subsequent ones)

### ISSUE THREAD

**Issue by fbiville** [neo4j/neo4j#9556]
Hello, 

I cannot upgrade `compile-testing` to `0.11` because it pulls Guava 20 and this is incompatible with the current Guava version Neo4j pulls (i.e. Guava 18).

Upgrading `compile-testing` might help fixing [the problem](https://github.com/google/compile-testing/issues/124) on specific procedure compiler test.

I started [a discussion](https://github.com/google/compile-testing/issues/125) with the compile-testing contributors to see if they would be willing to accept to shade Guava on their side, but I think it is not going in that direction :)

Guava has a strict deprecation policy so it would be great if Neo4j could upgrade to the most recent version as often as possible.

I can try to push a PR if you agree with this change (i.e. upgrading to the last version, `22.0`).

**Comment by craigtaverner** [comment]
I notice that cypher internally depends on guava 20, while the procedure compiler depends on guava 18. It would make sense to upgrade to at least 20.

**Comment by Hunterness** [comment]
Hi @fbiville, if you want to make a PR you are welcome to.

**Comment by janekdb** [comment]
@fbiville On the 4.0 branch guava is now at 28.1-jre. Does this allow this issue to be closed or if not closed then updated with changed details?

**Comment by fbiville** [comment]
Thanks for the reminder, but I don't actually remember why I opened the issue in the first place :/
Let me close it and I will re-open it if something comes to mind. Thanks!
