### ISSUE TITLE
Failed casual clastering for neo4j 3.1.4: ports for transaction and raft (both listening and advertising) remain closed and unreachable for other cores

### ISSUE THREAD

**Issue by fairy3** [neo4j/neo4j#9559]
- Neo4j version:3.1.4
- Operating system: (Linux CentOs 7)

- **Steps to reproduce**
  Configure neo4j.conf as follow:
neo4j.conf for 1 (172.16.140.10):
  dbms.connectors.default_listen_address=172.16.140.10
  dbms.connectors.default_advertised_address=172.16.140.10
  dbms.mode=CORE
  causal_clustering.initial_discovery_members=172.16.140.10:5000,172.16.140.11:5000,10.4.4.8:5000
rest parameters remain default

neo4j.conf for 2 (172.16.140.11):
dbms.connectors.default_listen_address=172.16.140.11
  dbms.connectors.default_advertised_address=172.16.140.11
  dbms.mode=CORE
  causal_clustering.initial_discovery_members=172.16.140.10:5000,172.16.140.11:5000,10.4.4.8:5000
rest parameters remain default

neo4j.conf for 3 (10.4.4.8):
dbms.connectors.default_listen_address=10.4.4.8
  dbms.connectors.default_advertised_address=10.4.4.8
  dbms.mode=CORE
  causal_clustering.initial_discovery_members=172.16.140.10:5000,172.16.140.11:5000,10.4.4.8:5000
rest parameters remain default

- Expected behavior
   after running ./neo4j start ports 5000,6000,7000 on each of servers will be open, status=listen and reachable by each other and all 3 servers will be up.

- Actual behavior (from log):
looks like it's stack in attempting to reach clusters's members

From debug log:
Discovery:   listen=10.4.4.8:5000, advertised=10.4.4.8:5000,
	Transaction: listen=10.4.4.8:6000, advertised=10.4.4.8:6000, 
	Raft:        listen=10.4.4.8:7000, advertised=10.4.4.8:7000, 
	Client Connector Addresses: bolt://10.4.4.8:7687,http://10.4.4.8:7474,https://10.4.4.8:7473
]
 INFO  [o.n.c.d.HazelcastCoreTopologyService] Discovering cluster with initial members: [10.4.4.8:5000, 17.16.140.10:5000, 17.16.140.11:5000]
 INFO  [o.n.c.d.HazelcastCoreTopologyService] Attempting to connect to the other cluster members before continuing...
 WARN  [o.n.c.d.HazelcastCoreTopologyService] The server has not been able to connect in a timely fashion to the cluster. Please consult the logs for more details. Rebooting the server may solve the problem.

from neo4j.log:
 INFO  Starting...
INFO  Bolt enabled on 0.0.0.0:7687.
 INFO  Initiating metrics...
INFO  My connection info: [
	Discovery:   listen=10.4.4.8:5000, advertised=10.4.4.8:5000,
	Transaction: listen=10.4.4.8:6000, advertised=10.4.4.8:6000, 
	Raft:        listen=10.4.4.8:7000, advertised=10.4.4.8:7000, 
	Client Connector Addresses: bolt://10.4.4.8:7687,http://10.4.4.8:7474,https://10.4.4.8:7473
]
 INFO  Discovering cluster with initial members: [10.4.4.8:5000, 17.16.140.10:5000, 17.16.140.11:5000]
 INFO  Attempting to connect to the other cluster members before continuing...

When trying netstat -apn | grep 6000 (7000), see that the ports are not open 
When trying cat </dev/tcp/172.16.140.11/6000 or cat </dev/tcp/172.16.140.11/7000 
(the same for 172.16.140.10 and for 10.4.4.8) receive:
-bash: connect: Connection refused
-bash: /dev/tcp/172.16.140.11/6000: Connection refused
althought port 5000 is open and reachable

**Comment by martinfurmanski** [comment]
@fairy3 Those ports are not bound to before the discovery has managed to form/join a cluster. So your issue is that the discovery is not working and you are stuck at that.

**Comment by fairy3** [comment]
Yes, you are right,@martinfurmanski

**Comment by fairy3** [comment]
The issue was solved for version 3.2.2 (discovery bug was fixed) and it really works.

**Comment by martinfurmanski** [comment]
@fairy3 Fantastic! Thanks for reporting back.
