### ISSUE TITLE
Neo4j variable length query getting stuck in version 3.1.1

### ISSUE THREAD

**Issue by ranajyotic** [neo4j/neo4j#9575]
I have a query which is something like this
`MATCH(n:KD {name:'abcd'})-[:HAS]->(m:Entity {name:'efgh'})-[r*]-(o:Entity {name:'ppqa'}) RETURN o`

This will get stuck from code and Neo4j UI (browser). If I replace the r* with r:SOME_RELATION it works fine. I could not get around the issue. This needs to be fixed as variable length relations are very important.

**Comment by jexp** [comment]
Can you at least add a direction or an upper limit to the var-length pattern? Otherwise this might potentially return your full graph.

you can/should also try to match your 3 entities upfront so an index can be used to find them.

**Comment by ranajyotic** [comment]
You are right, that solved the problem.
