### ISSUE TITLE
Not able to find ResourceIterator and ResourceIterable interfaces in graphdb-api

### ISSUE THREAD

**Issue by vinayak91** [neo4j/neo4j#9583]
- Neo4j version: 3.2.1
- Operating system:  Windows 7
- API/Driver: Java API

Issue:
- Until 2.3.11 ResourceIterator and ResourceIterable interfaces were present in kernal jar. I suppose these classes are moved to graphdb-api jar. 
- But now the interfaces are not present in any of the location.

**Comment by chrisvest** [comment]
It's in `neo4j-resource`, which graphdb-api depends on. I would recommend using a dependency manager like Maven, if you are not already. Then these transitive dependencies would be taken care of for you automatically.

**Comment by vinayak91** [comment]
thank you.
