### ISSUE TITLE
apoc.sequence concurrency problem

### ISSUE THREAD

**Issue by lucmos** [neo4j/neo4j#9599]
We're implementing some apoc functions to generate a thread-safe sequence of values, but we're facing problems acquiring a write lock.
Maybe it is related to: https://github.com/neo4j/neo4j/issues/5091

The idea behind is pretty simple, there are two basic functions:

- `apoc.sequence.create`: creates a named "sequence-node" (in single thread) which contains a counter

- `apoc.sequence.next`: takes the right "sequence-node", acquires the lock on it, returns the  current value and increments the counter on the node.

There is also the concept of _sequence provider_: a stateless object (so thread safe) that is called to get the next sequence element. That's how we create custom sequences, not only numerical counters.

The apoc fork with the complete code can be found here: https://github.com/Flegyas/neo4j-apoc-procedures/tree/3.2

This is the failing code (it fails even with the default length):
```Java
@Procedure(mode = Mode.WRITE)
@Description("apoc.sequence.next('sequenceName') - get&increment sequence value using related provider and length as increments number")
@SuppressWarnings("unchecked")
public Stream<ObjectResult> next(@Name("sequenceName") String sequenceName, @Name(value = "length", defaultValue = "1") long length) {
    LinkedList<Object> result = new LinkedList<>();

    try (Transaction tx = db.beginTx()) {
        Node sequenceNode = db.findNode(SEQUENCE_LABEL, NAME_PROPERTY, sequenceName);

        if (sequenceNode == null)
            throw new RuntimeException(String.format("You must create %s (with apoc.sequence.create) before using it!",
                    sequenceName));

        String providerName = (String) sequenceNode.getProperty(PROVIDER_PROPERTY);
        SequenceProvider provider = SEQUENCE_PROVIDER_MAP.get(providerName);

        if (provider == null)
            throw new RuntimeException(String.format("No provider associated with <%s>", sequenceName));

        tx.acquireWriteLock(sequenceNode);

        Object current = sequenceNode.getProperty(provider.propertyName());

        if (length < 1)
            throw new RuntimeException("Length can't be lower than 1!");
        if (length > 1) {
            result = provider.next(current, length - 1);
            result.addFirst(current);

            current = result.getLast();
        } else
            result.add(current);


        sequenceNode.setProperty(provider.propertyName(), provider.next(current));

        tx.success();
    }

    return result.stream().map(ObjectResult::new);
}
```

Here, one of the tests that _sometimes_ fails:

```Java
private static String CREATE_SEQUENCE_QUERY = "CALL apoc.sequence.create($sequence) YIELD node as n return n";
private static String NEXT_VALUE_QUERY = "CALL apoc.sequence.next($sequence) YIELD value as n return n";

@Test
public void testSequenceMultithread() throws Throwable {
    Map<String, Object> params = MapUtil.map("sequence", "TEST2_SEQUENCE");

    TestUtil.testCall(db, CREATE_SEQUENCE_QUERY, params, (row) -> {
    });

    long threadsNumber = 1000;
    ExecutorService executorService = Executors.newFixedThreadPool(50);

    for (int threadNumber = 0; threadNumber < threadsNumber; threadNumber++)
        executorService.submit(() -> TestUtil.testCall(db, NEXT_VALUE_QUERY, params, row -> {
        }));

    executorService.shutdown();
    executorService.awaitTermination(1, TimeUnit.HOURS);

    TestUtil.testCall(db, NEXT_VALUE_QUERY, params, row -> assertEquals(threadsNumber, row.get("n")));
}
```
It _seldom_ fails but, when it does, the test can fail with:
- assertion error expected=n, actual=n-1 (rarely with actual < expected -1)
- exception deadlock detected (it happened just a few times)

Here is an example of one of the errors that it can throw: 

![image_2017-06-30_01-02-55](https://user-images.githubusercontent.com/11019190/27714227-ea4e5a06-5d2f-11e7-843f-d6413f5c2c60.png)

This is what we think about it:

- The write lock should ensure a safe increment even in a multithreaded environment, so the problem shouldn't be there (acquire lock -> read/write -> release)
- It's logically impossible to be in a deadlock acquiring the lock only on one node at time (the same node, so no cyclic deadlock).
- We can't exclude that the problem lies in the test environment because we are not able to reproduce the problem on the embedded one.

So, what's the problem with our code?

**Comment by chrisvest** [comment]
Is it correct that you are trying your code both in embedded mode and in server mode, and that only the server mode sees failures? If so, are you only using community edition in the embedded mode, and enterprise edition in the server mode?

CE and EE use different lock managers by default. The EE lock manager is faster and more scalable on multicore machines, but inherent in its algorithm is a small risk of getting false positives; seeing deadlocks, where there really aren't any. Could this explain what you are seeing? If you set `unsupported.dbms.lock_manager=community` in the `neo4j.conf` on your server, and the problem goes away, then that was probably it.

**Comment by lucmos** [comment]
Hey @chrisvest, we are testing it in two environments:
- With the tests provided by the apoc: here it _sometimes_ fails. These tests use a `newImpermanentDatabase` created from `org.neo4j.test.TestGraphDatabaseFactory`

- With a Java application that uses neo4j community edition in embedded mode, with the apoc plugin: here, it hasn't failed yet.

I see what you are saying. The problem is that the errors aren't only on deadlocks. Most of the time the test simply fails because the returned value isn't the excpected one. (Moreover shouldn't the algorithm see that all deadlocks are on the same node, so no deadlock is possible?)

**Comment by inserpio** [comment]
Ciao @LucaMoschella, good to see you're working on neo4j.
Feel free to reach us for any neo4j related question.
We're the #1 Italian partners, based in Venice and currently developing & maintaining apocs, with @jexp. /cc @albertodelazzari.
Un saluto,
Lorenzo

**Comment by lucmos** [comment]
Hello! Nice to hear that :)
Do you have any idea on what can be the problem? 
It only appears on the test environment of the apoc

**Comment by jexp** [comment]
Did you apply the suggestions I made in your PR apoc and test again @LucaMoschella ?

**Comment by lucmos** [comment]
More or less... we are working on a project so we are a little busy. (we are developing even a geohash plugin: we're using it and it seems to work well enough, it improves the performance compared to spatial)

We tried only to move the write lock, but it doesn't change anything (we use a concurrenthashmap, with a stateless provider.. so it shouldn't be a problem, the lock position I mean)

The problem is that it works well if we don't use the apoc tests. So for the moment we are using it as it is now.

As soon as we finish some works in progress we plan to implement the suggestions that you have made, and test it again on the apoc tests.

**Comment by craigtaverner** [comment]
This issue has been lying dormant for a long time. I assume we can close it. Please re-open it if you are still having troubles.

Also, I noticed that you mentioned building your own geohash. You might take a look at Neo4j 3.4 which uses space-filling curves (a bit more efficient than geohashes, which are z-order curves). The space-filling curves were also implemented in the spatial library, but not as effecient as the one inside Neo4j itself, because Neo4j is using a native GBPTree backing index, while the spatial library backs the space-filling curve (and geohash) with lucene.
