### ISSUE TITLE
can the neo4j community verion support cluster？

### ISSUE THREAD

**Issue by gotheworld** [neo4j/neo4j#9603]
can the neo4j community verion support cluster？ I need to make a cluster, so how to do?

**Comment by InverseFalcon** [comment]
Sorry, clustering features are restricted to enterprise version only. However, there are discounts and/or exceptions for startups, open source, and education use cases, you'll want to [take a look at these options](https://neo4j.com/licensing/) and contact licensing if you have further questions.
