### ISSUE TITLE
Read-only slave  exception: "Can't create index writer in read only mode."

### ISSUE THREAD

**Issue by klichukb** [neo4j/neo4j#9609]
A read-only node fails to start up and join the cluster since it has some pending writes, which it should not have. All the writes are routed to master, which is *not* this node.

### Details:

**Neo4j Version:** 3.2.1 enterprise  
**Operating System:** (Docker) Alpine 3.6. Based off [this image](https://github.com/neo4j/docker-neo4j-publish/blob/ae826519a7acf389396ab6c388fe299c21b41107/3.2.1/enterprise/Dockerfile). Host: Amazon Linux 2016.09.b
**API:** Docker

### Steps to reproduce
1. Create an HA cluster of 3 nodes. One of them `dbms.read_only = true`, `ha.slave_only = true`, `ha.pull_interval = 5s` (lets call it Read node). The rest 2 nodes are eligible for the master role, `ha.tx_push_factor=1` (let's call them R/W nodes), where master pushes to an R/W slave only (due to `fixed_ascending` order and `server_id` policy).
2. Set up backup process directly on the Read node using separate docker container, that runs each hour.
3. Eventually find out that Read node Web UI fails to log you in. Seeing the same error in the docker container that tries to perform backups. Error is

```Creating Neo4j DB backup
Doing full backup...
command failed: Backup failed: java.io.IOException: Database has encountered some problem, please perform necessary action (tx recovery/restart)
```

4. Try to fix this error by changing the memory layout on the Read node, which has less memory for Neo4j due to RAM reservations for the docker that performs backups each hour.
5. After redeploying docker container with new heap size / page cache size, observe failure of the Read node to join the cluster.  See full stack trace attached in `neo4j_readonly_docker.txt`

### Expected behavior
Read node should not possess or claim to possess any pending writes to the cluster. Let alone crashing like this.  This node can only be slave, only read from the R/W nodes. Even if it has some weird writes, I would like to know if there's an option to ignore any write data on this node and obey the writer nodes.

### Actual behavior
Error everytime this node tries to join the cluster using DB it already has on the FS. Could only fix by wiping it's DB and letting it resync from cluster from scratch.

[neo4j.conf.txt](https://github.com/neo4j/neo4j/files/1115088/neo4j.conf.txt)
[neo4j_readonly_docker.txt](https://github.com/neo4j/neo4j/files/1115089/neo4j_readonly_docker.txt)

## POSSIBLE ANSWER (from neo4j slack):

```
dbms.read_only is kinda deprecated so, since node is getting writes from inside cluster, its not really read-only.

> Neo4j has a very long history of single/embedded usage as well as clustered usage and this setting is not really meant for the latter. For example it would not have an impact on where queries would get routed using a routing Bolt driver afaik either.

Such attempt to write is normal functioning of a cluster node even with this read_only (?)

> For read-only, user authorization should be a way to prevent updates.
```

Attached configuration of the Read node and full log of the docker instance.

**Comment by burqen** [comment]
@klichukb Thank you for reporting this issue and the detailed description!

Problem was that the internal label index on the slave was opened in read only mode which means it could not apply any writes at all, not even updates coming from master (which it of course need to stay in sync). The read only property of the slave, as in "I should not accept any external updates", are protected against elsewhere.

This pull request should fix the issue #9650 

Please, let us know if you still experience the same problem with this fix.
