### ISSUE TITLE
Neo4jRule().copyFrom() not working as expected

### ISSUE THREAD

**Issue by NikitaAtPlanOne** [neo4j/neo4j#9622]
Hi,

we are trying to unit test a procedure extension that should do some calculation on existing data. We figured that using the `copyFrom()` method of the `Neo4jRule` would enable us to use data from an existing DB. However, our tests don't work and it looks like the existing data is not used.

We confirmed that the data is actually copied by having a look into the temp dir, but realized that in addition to the copied data, a substructure (databases/graph.db) containing an empty DB is created inside the directory.

We as well had a look at the unit test in the neo4j git repository (https://github.com/neo4j/neo4j/blob/3.1/community/neo4j-harness/src/test/java/org/neo4j/harness/JUnitRuleTest.java) and tried to replicate what is done in the test called:  `shouldRuleWorkWithExsitingDirectory`. For us, it seems like the code inside the evaluate method of the inline Statement is not executed. The asserts there never fire, regardless what we tell them to assert.
The `apply`-Method in Neo4jRule seems to doesn't actually run the statement, but just wraps the statement into another one and returns it. Thus the test `shouldRuleWorkWithExsitingDirectory` reports as successful. 

**Neo4j Version:** 3.1.3
**Operating System:** Windows 7  
**API:** Java

### Steps to reproduce 1
1. Modify the test `shouldRuleWorkWithExsitingDirectory` that can be found in community/neo4j-harness/src/test/java/org/neo4j/harness/JUnitRuleTest.java to, e.g., write something to system out.
2. This is not printed when the test runs.
3. Save the Statement resulting from `ruleWithDirectory.apply(...);` in a variable like: `Statement statement = ruleWithDirectory.apply(...);`
4. Evaluate the Statement: `statement.evaluate()`
5. It will fail in this line `assertEquals( 1, column.get( 0 ) );` meaning the database that is actually used is empty.

### Steps to reproduce 2
Try to use existing data by using the `copyFrom()` method.

### Expected behavior
`new Neo4jRule().copyFrom(new File('/location/of/db/data'))`
should provide a test database with the content given in copyFrom. 

### Actual behavior
- The data is copied, but then an additional file structure with an empty database is created and seems to be used.

**Comment by schierle** [comment]
I can confirm it (neo4j-harness 3.2.2). Would be great to get a fix.

**Comment by Urr4** [comment]
Same problem

**Comment by arsanjea** [comment]
FYI it's still not working. However, I used the following trick to still my goal:
I added the following ```.withConfig("dbms.directories.data", "location/to/existing/data")```, which will use the existing databases/graph.db sub-directory and will load the existing data.

**Comment by zhenlineo** [comment]
Hi, The copyFrom method requires the source directory to have sub-folders `databases/graph.db` in which the source store files are located. We've fixed the test and also changed the API doc of the method about the directory structure requirement.

Thanks very much for reporting this issue to us.
