### ISSUE TITLE
HA Cluster *slave* node not syncing with master till reset

### ISSUE THREAD

**Issue by raviolli** [neo4j/neo4j#9637]
**Neo4j Version:** 3.2.1
**Operating System:** CentOs 7
**API:**  Neo4J

Hi there, My issue is that the *slave* node is not syncing with the master node till I reset it. To make matters even more odd one of the two *slave* nodes works while the other does not. \

Please see logs and conf files. The trouble node is 10.240.0.6 (N2)

https://drive.google.com/a/qedata.io/file/d/0B-qBSiWiiQPkZzhYbFBFZGpUNEE/view?usp=sharing
https://drive.google.com/a/qedata.io/file/d/0B-qBSiWiiQPkb1FYQk04UVFNb3c/view?usp=sharing
https://drive.google.com/a/qedata.io/file/d/0B-qBSiWiiQPkNl9qOHJEU1BKc3M/view?usp=sharing
https://drive.google.com/a/qedata.io/file/d/0B-qBSiWiiQPkZXdIUThrNFdPTW8/view?usp=sharing
https://drive.google.com/a/qedata.io/file/d/0B-qBSiWiiQPkTVd4ZFE4aEY5dHc/view?usp=sharing
https://drive.google.com/a/qedata.io/file/d/0B-qBSiWiiQPkbjd3SDJUanhTeWM/view?usp=sharing

-- edit --
if I change the HA.ID to a lower number on the broken node it works for that node. The problem seems that I have only have 1 master and 1 slave the sync and the 1 slave will be the one with the lowest ha.id.

## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests.  If you have questions on how to use Neo4j, please ask on [StackOverflow](http://stackoverflow.com/questions/tagged/neo4j) instead of creating an issue here.

If you want to make a feature request then there is no guideline, so feel free to stop reading and open an issue. If you have a bug report however, please continue reading.

To help us understand your issue, please specify important details, primarily:

- Neo4j version: X.Y.Z
- Operating system: (for example Windows 95/Ubuntu 16.04)
- API/Driver: (for example Cypher/Java API/Python driver vX.Y.Z)
- **Steps to reproduce**
- Expected behavior
- Actual behavior

Additionally, include (as appropriate) log-files, stacktraces, and other debug output.

## Example bug report

I discovered that when I mount `data/` to a volume on my host, and then stop the container, the `write.lock` is not removed as well as a number of other files not being cleaned up properly.

**Neo4j Version:** 3.0M03  
**Operating System:** Ubuntu 15.10  
**API:** Docker

### Steps to reproduce
1. Pull the image: `docker pull neo4j/neo4j:3.0.0-M03`
2. Create a directory on the host that will be a mount for the data: `mkdir /home/neo4j-data`
3. Start a new container that mounts to this directory: `docker run -d --name neo4j-test -p 7474:7474 -v /home/neo4j:/data neo4j/neo4j:3.0.0-M03`
4. Navigate to the `write.lock` file located in the directory: `/data/databases/graph.db/schema/label/lucene/labelStore/1/`
5. Stop the container: `docker stop neo4j-test`

### Expected behavior
`write.lock` should be removed now.

### Actual behavior
`write.lock` is still present and preventing access by other programs.

**Comment by raviolli** [comment]
Okay The fix is dumb and weird. I set a non default value to:
ha.pull_interval

and it works now.

**Comment by martinfurmanski** [comment]
@raviolli Thanks for reporting. The default is meant to be pulling and it was actually changed by mistake with the 3.1.0 release. I will change it back.

**Comment by martinfurmanski** [comment]
https://github.com/neo4j/neo4j/pull/9639
