### ISSUE TITLE
Neo4j Powershell Module in 3.2.2 is not digitally signed

### ISSUE THREAD

**Issue by aamanlamba** [neo4j/neo4j#9654]
- Neo4j version: 3.2.2
- Operating system: Windows Server 2012 64-bit

- **Steps to reproduce**
  Download the zip file release of Neo4j 3.2.2 and extract to a folder.
Launch Powershell and execute the command 
`Import-Module "D:\Apps\neo4j-community-3.2.1-windows\bin\Neo4j-Management.psd1";`

- Expected behavior
The Neo4j Powershell module is loaded in and the console application can be launched

- Actual behavior

> Error message:
> 
> Import-Module : File ...\bin\Neo4j-Management\Neo4j-Management.psm1 cannot be
> loaded. The file ...\bin\Neo4j-Management\Neo4j-Management.psm1 is not
> digitally signed. You cannot run this script on the current system. For more information about running scripts and
> setting execution policy, see about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170.
> At line:1 char:1
> + Import-Module "D:\Apps\neo4j-community-3.2.1-windows - Load\bin\Neo4j ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : SecurityError: (:) [Import-Module], PSSecurityException
>     + FullyQualifiedErrorId : UnauthorizedAccess,Microsoft.PowerShell.Commands.ImportModuleCommand

The same command works fine in Neo4j 3.2.1

**Comment by aamanlamba** [comment]
Please confirm if this is being resolved in the current release or any fix other than having to run 'unrestricted' scripts.

**Comment by aamanlamba** [comment]
Please note this is still an issue in Neo4j 3.2.5

**Comment by lassewesth** [comment]
Hey @aamanlamba,

I think you have run into https://neo4j.com/docs/operations-manual/current/installation/windows/#powershell-windows - does that help?

There is no difference in the build/ release/ publication process between 3.2.1 and later releases wrt the Powershell module, so I cannot explain why you suddenly see a change.

It is not something we are planning to change either.

Regards,

Lasse

**Comment by aamanlamba** [comment]
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned does not help either, we have moved to using the Windows service option, which has a few other issues
