### ISSUE TITLE
Incorrect editor launch behaviour on OS X

### ISSUE THREAD

**Issue by studentlaw** [neo4j/neo4j#9669]
## Bug Report

Multiple instances of editor application can be launched from the Desktop edition when editing options/configuration files.

## Important details:

**Neo4j version:** 3.2.2 (also in 3.1.0)
**Operating system:** Mac OS X - specifically version 10.11.6

### Steps to reproduce

1. Set BBEdit or other similar text editor as the default editor for .conf and .vmoptions files
2. Run BBEdit (or your chosen text editor)
3. Run Neo4J Community Edition (desktop version)
4. Click on 'Options...'
5. Click on the 'Edit...' button corresponding to the Database Configuration file
6. Click on the 'Edit...' button corresponding to the Java VM Tuning configuration file

### Expected behaviour

The Database Configuration file and the Java VM Tuning configuration files should open in the already-running instance of BBEdit (or other chosen text editor)

### Actual behaviour
A new instance of the text editor is launched for each file, resulting in three separate BBEdit processes

**Comment by chrisvest** [comment]
I'm closing this because Neo4j Desktop is now a very different product, and includes a built-in settings editor.
