### ISSUE TITLE
The onClose method on the java8-Stream of a procedure result is not called

### ISSUE THREAD

**Issue by jexp** [neo4j/neo4j#9674]
... which makes it hard to release resources that the stream holds onto, when the stream is consumed or its iteration is finished for some other reason.

Results are turned into an iterator via `Stream.iterator()` which loses the ability to close the underlying stream. If it was a kind of `ResourceIterator` it might be possible later on to correctly indicate the end of consumption.

https://github.com/neo4j/neo4j/blob/3.3/community/kernel/src/main/java/org/neo4j/kernel/impl/proc/ReflectiveProcedureCompiler.java#L605

**Comment by chrisvest** [comment]
@jexp You link is not pointing to a stable version of the file. Can you check if it's still relevant, and if so, update the link to be stable, e.g. press `y` on the web page with the file, to change to a perma-link that includes the commit of the file that you are looking at.

**Comment by jexp** [comment]
Seems to be fixed here: https://github.com/neo4j/neo4j/commit/1971c322ddaa6421df4aa1394479cfc2a70e6138#diff-1093ccdb2ce7b572eba3a14db2ba5783

Thanks a lot
