### ISSUE TITLE
Implement streaming / back pressure interface on bolt protocol

### ISSUE THREAD

**Issue by pocesar** [neo4j/neo4j#9683]
I opened an issue on the javascript driver about stream and back pressure (which is pretty common in Node.js) but it seems to be an upstream issue that the bolt protocol haven't implemented. If you want the fine bits, it's in here neo4j/neo4j-javascript-driver/issues/271 

Pretty sure all the drivers could benefit of the implementation of back pressure on the driver session itself, with a side connection related to the current session in case streaming is enabled, controlling the flow of the data. Although it could be implemented as a duplex stream, I'm not sure how it would affect the reads (that's the most important part of the streaming behavior), otherwise the protocol would keep working as it's working today, being backward compatible, and sending all the data at once. I have no Java experience, so I have no idea how to make a proposal, so would have to leave to the core devs

**Comment by technige** [comment]
Hi @pocesar - thanks for your thoughts on this. We do have flow control on our roadmap and it would likely appear at some point next year (2019) although the timings are obviously subject to change. At that point, we'd be able to incrementally consume or discard a stream as required from any of the drivers.

**Comment by technige** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Flow control/Back pressure (Pull_n) [?]](https://trello.com/c/T60XILkt/24-flow-control-back-pressure-pulln)

**Comment by davidrapin** [comment]
Hi @technige, any news on this?

**Comment by technige** [comment]
Hi @davidrapin - sadly no more clarity on timings for this yet. It's definitely still on our roadmap though, and will remain there, so it's just a matter of _when_.

**Comment by davidrapin** [comment]
@technige Thank you for your feedback. 

The HTTP API has been deprecated and I expect it to be disabled by default at some point in the future.
The tools we develop rely on backpressure when reading results from Neo4j, and we currently need to use the HTTP API for that (as backpressure is native to HTTP streaming).

I want to make sure that Bolt will implement backpressure *before* the HTTP API is disabled by default.

**Comment by technige** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement flow control and back pressure throughout Bolt stack](https://trello.com/c/T60XILkt/24-implement-flow-control-and-back-pressure-throughout-bolt-stack)

**Comment by technige** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Flow Control, Back Pressure & Reactive Drivers](https://trello.com/c/Q74jCr78/132-flow-control-back-pressure-reactive-drivers)

**Comment by technige** [comment]
To keep this thread up to date: reactive drivers, plus a fully reactive stack all the way through the Cypher engine, will be released as part of Neo4j 4.0.

**Comment by technige** [comment]
Closing this issue as a reactive driver has now been published with Neo4j 4.0.

https://www.npmjs.com/package/neo4j-driver/v/4.0.1
