### ISSUE TITLE
Error message found on Neo4j when trying to clean relationship types

### ISSUE THREAD

**Issue by lenovopast17** [neo4j/neo4j#9694]
Neo4j version: 3.2.2
Operating system: Win10
Issue: Error message found when trying to clean relationship types 

The code that was ran: 

```
WITH 'https://docs.google.com/spreadsheets/u/1/d/1Z5Vo5pbvxKJ5XpfALZXvCzW26Cl4we3OaN73K9Ae5Ss/export?format=csv&gid=1996904412' AS url, 
['LOAN','LOBBIED','SALE','SUPPLIER','SHAREHOLDER','LICENSES','AFFILIATED','TIES','NEGOTIATION','INVOLVED','PARTNER'] AS terms
LOAD CSV WITH HEADERS FROM url AS row WITH terms, row WHERE row.`Entity A Type` = 'Organization' AND row.`Entity B Type` = 'Organization' 
WITH apoc.text.regreplace(toUpper(row.Connection),'\\W+','_') AS type, row, terms WITH head(filter(term IN terms WHERE type CONTAINS term)) AS found, type, row 
RETURN substring(coalesce(found,type),0,30) AS type, count(*), collect(distinct row.Connection)[0..5] AS connections ORDER BY count(*) DESC
```

Error code given: 
Unknown function 'apoc.text.regreplace' (line 6, column 6 (offset: 413))
"WITH apoc.text.regreplace(toUpper(row.Connection),'\\W+','_') AS type, row, terms"
              ^

Does anyone know how to fix this? Thank you very much and much appreciated!

**Comment by sherfert** [comment]
Hi @lenovopast17 . Do you have included APOC as a dependency? What does `RETURN apoc.version()` give you?

**Comment by sherfert** [comment]
No response...
