### ISSUE TITLE
Parameter for relation in @Query

### ISSUE THREAD

**Issue by ranajyotic** [neo4j/neo4j#9695]
I am trying to write a cypher where the relation needs to be parameterized, example
`MATCH(n:Entity {name:{0}})-[r:{1}]->(m:Entity {name:{2}}) RETURN m`
This would throw an exception saying that the { after r: is not supposed to be there. How do I get it to work?

**Comment by sherfert** [comment]
Hi. You can parameterize relationships, but you will need key-value pairs as well. 

This query workd for example:
`MATCH(n:Entity {name:{0}})-[r {name:{1}}]->(m:Entity {name:{2}}) RETURN m`
