### ISSUE TITLE
Weird behaviour of cypher queries with start and match in 2.0.0 M3

### ISSUE THREAD

**Issue by Phil-Ba** [neo4j/neo4j#970]
As discussed here, queries dont behave as expected:
http://stackoverflow.com/questions/17658314/weird-cypher-behaviour-bug
Given following datamodel:

![clipboard01](https://f.cloud.github.com/assets/5018561/802593/f6fdaffa-edcf-11e2-8ec8-650482d4493d.jpg)

This quer should return 9 rows:
START s=node:**types**(className='Supplier'),f=node:**types**(className='Factory')
MATCH (s)-[d:delivers]->(f) 
RETURN s.name,d.price, f.name;

however, this is the result:
5 rows
s.name      d.price f.name
"Amazon"    30      "Köln"
"eBay"        33      "Köln"
"Amazon"    29      "Frankfurt"
"Amazon"    32      "Mannheim"
"Conrad"     27      "Stuttgart"

now oddly enough if I run the same query but dont bind the relationship to a varibale, I get 7 rows

START s=node:**types**(className='Supplier'),f=node:**types**(className='Factory')
MATCH (s)-[delivers]->(f) 
RETURN s.name, f.name;

7 rows
s.name        f.name
"Amazon"    "Köln"
"eBay"         "Köln"
"eBay"         "Frankfurt"
"Amazon"     "Frankfurt"
"eBay"         "Mannheim"
"Amazon"     "Mannheim"
"Conrad"      "Stuttgart"

I guess it is related to this issue https://github.com/neo4j/neo4j/issues/897

**Comment by sherfert** [comment]
Can someone confirm the issue also exists when avoiding the deprecated `START` syntax?

**Comment by sherfert** [comment]
Closing this in lack of a response.
