### ISSUE TITLE
TraversalAStar.findAllPaths return only one path

### ISSUE THREAD

**Issue by ArnaudBarre** [neo4j/neo4j#9713]
I found that the method  findAllPaths of [TraversalAStar](https://github.com/neo4j/neo4j/blob/3.3/community/graph-algo/src/main/java/org/neo4j/graphalgo/impl/path/TraversalAStar.java) returning always one path :
`return Iterables.asIterable( findSinglePath( start, end ) );`

It was working in 2.2 before this [commit](https://github.com/neo4j/neo4j/commit/3c76a34338c964e25530178b92cded7495fcb487#diff-90d123a6cc1d700ab8b04c55011efab0)
 
Is there any reason for not calling ` findPaths( start, end, true )` ?

**Comment by MishaDemianenko** [comment]
Hi @ArnaudBarre  even if framework allows you to do that kind of call A* should be used only to find the best-first path. In case if you need to find multiple paths please use Dijkstra's algorithm.
