### ISSUE TITLE
Neo4j labels broken on enterprise-2.3.8.

### ISSUE THREAD

**Issue by Infiniverse** [neo4j/neo4j#9720]
Using neo4j-enterprise 2.3.8.

Struggling to work out why this has happened:

Uhho, this doesn't look right:

    neo4j-sh (?)$ match (c:Contact) where not c:_Contact return labels(c);
    +-----------+
    | labels(c) |
    +-----------+
    | []        |
    +-----------+
    1 row
    213 ms
    neo4j-sh (?)$ match (c:Contact) where not c:Contact return labels(c);
    +-----------+
    | labels(c) |
    +-----------+
    | []        |
    +-----------+
    1 row
    65 ms
    neo4j-sh (?)$ match (c:Contact) return distinct labels(c);
    +------------------------+
    | labels(c)              |
    +------------------------+
    | ["Contact","_Contact"] |
    | []                     |
    +------------------------+
    2 rows
    206 ms
    
I have a single row that appears to be indexed by a label that it doesn't have.

How did that happen? And, how do I fix it?

Thanks,
Joe

**Comment by jexp** [comment]
Can delete the label store and see if that helps (it's rebuild)
data/graph.db/schema/label/

**Comment by Infiniverse** [comment]
Thanks - we restored from a backup (with minimal lost) and that solved the problem. It's good to know that this is a potential remedy should it happen again.
