### ISSUE TITLE
EntityNotFound during query for all instances of two related types

### ISSUE THREAD

**Issue by khaled83** [neo4j/neo4j#9721]
We have three node types including Label (aka tag) and Project, where each project node can be linked to multiple label nodes and vice versa. We are trying to execute a query to return all labels with their linked projects.

**Neo4j Version:** 3.2
**Operating System:** Neo4j Docker Image 3.2 with Alpine 3.6.2
**API/Driver:** Java API over HTTP Driver

### Steps to reproduce
1. Set up AWS ECS task definition with two containers, first for Sprint Boot (1.5.4.RELEASE) Java app, and second for Neo4j 3.2
2. Add an efs mount point for Neo4j to /var/lib/neo4j/data (mounting works fine)
3. Run service on AWS EC2 with Amazon Linux AMI 2017.03
4. Call an API endpoint on Sprint Boot that executes the following query:
`@Query("MATCH (label:Label)-[]-(project:Project)"`
`+ "RETURN (label:Label)-[]-(project:Project)")`
`public Iterable<Label> findAllWithProjects() throws CypherException;`

### Expected behaviour

Returns an Iterable list of Label nodes mapped into Label domain entities.

### Actual behaviour

1. The query works on development and staging environments.
2. On production, the query is executed as the logs show, but throws the following error:
`Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.neo4j.ogm.exception.CypherException: Error executing Cypher "Neo.ClientError.Statement.EntityNotFound"; Code: Neo.ClientError.Statement.EntityNotFound; Description: Unable to load NODE with id 1207.] with root cause
org.neo4j.ogm.exception.CypherException: Error executing Cypher "Neo.ClientError.Statement.EntityNotFound"; Code: Neo.ClientError.Statement.EntityNotFound; Description: Unable to load NODE with id 1207.`

### Troubleshooting

 1. I deleted `schema/label` folder as advised in post [neo4j EntityNotFound prevents cypher match from working](https://stackoverflow.com/questions/21173724/neo4j-entitynotfound-prevents-cypher-match-from-working)
 2. I executed the same query on production server using HTTP POST to neo4j server and it seems to work.
 3. I tried to look up the node using `http://localhost:7474/db/data/node/1207` but it returns 404 Not Found.
 4. I tried deleting that node from my application, but again its not found. I also executed delete all relations to that node, using multiple queries like:
`MATCH (label:Label)-[r:LABELED_PROJECTS]-(project:Project)
WHERE id(project) = 1207
DELETE r`
I executed a few of these queries with different types of nodes (with id=1207) and returns, but all of them returned empty result.
5. I adjusted the query adding a condition as follows and that makes it work:
`MATCH (label:Label)-[]-(project:Project)`
`WHERE NOT id(project) = 1207 `
`RETURN (label:Label)-[]-(project:Project)`
6. Other parts of the system except three queries are working fine.

**Comment by MishaDemianenko** [comment]
Hi @khaled83, do you still have this problem? If so can you please run consistency checker to verify consistency of your production db and share results with us?

**Comment by MishaDemianenko** [comment]
Closing since the issue was reported quite a while ago and no response from reporter. Feel free to reopen in case you will gonna have some additional information to share.
