### ISSUE TITLE
which neo4j verison match spring-data-neo4j version？and which spring-data-neo4j version support jdk7？

### ISSUE THREAD

**Issue by gotheworld** [neo4j/neo4j#9727]
which neo4j verison match spring-data-neo4j version？and which spring-data-neo4j version support jdk7？

**Comment by michael-simons** [comment]
Please have a look here:

https://community.neo4j.com/t/neo4j-ogm-spring-data-neo4j-spring-boot-compatibility/2760

On JDK 7 you are stuck with Spring Data Neo4j 4.2 and Neo4j-OGM 2.1.x. 

We highly recommend upgrading to a more recent JDK release.

Please reach out on our community site with further question. You could ask them on the given topic abve.
