### ISSUE TITLE
Different favorites for same graph db and server

### ISSUE THREAD

**Issue by mariusconjeaud** [neo4j/neo4j#9729]
Hi everyone,

Just noticed that when I accessed my graph db located in localhost server via Neo4J GUI, the favorites stored in the "Favorites" section were not the same, depending on if I accessed the GUI by typing "127.0.0.1:7474" or "localhost:7474" in Chrome URL bar.
Favorites shown for "127.0.0.1:7474" were those I saved while I was in "127.0.0.1:7474" ; and vice versa. But it's obviously the same db and server !

Note : "Browser sync" function is not activated.

**Comment by oskarhane** [comment]
This is because they are stores in the web browsers local storage, and that storage is isolated to the url you're working on.
The solution is to use browser sync.
