### ISSUE TITLE
Unable to build Neo4j on MacOs

### ISSUE THREAD

**Issue by shivanth** [neo4j/neo4j#9734]
I cloned the latest neo4j source from github and did a `mvn clean install`. 
The build fails while creating tar  on `Neo4j Community - Server Assembler`.

```
 Neo4j - Server Assembler ........................... SUCCESS [ 54.877 s]
[INFO] Neo4j Desktop ...................................... SUCCESS [ 17.606 s]
[INFO] Neo4j Community - Server Assembler ................. FAILURE [  4.286 s]

```
The error reads 
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.5.4:single (community-unix-dist) on project neo4j-community-standalone: Execution community-unix-dist of goal org.apache.maven.plugins:maven-assembly-plugin:2.5.4:single failed: group id '2110994482' is too big ( > 2097151 ). Use STAR or POSIX extensions to overcome this limit -> [Help 1]
```
MacOS version: 10.12 macos Sierra
Neo4j version: Cloned the latest from repo

**Comment by chrisvest** [comment]
Sounds like the checkout directory has an unusually high group number. What's the output of `stat -x community/server/target/`? If it has GID `2110994482` then that's a clue.

**Comment by shivanth** [comment]
Yes, it does have gid 2110994482. But this directory is a newly created directory during the build, not checked out from the repo...

**Comment by chrisvest** [comment]
The TAR format we use don't support such large GIDs. You can modify the pom file to enable the STAR or POSIX extensions like the error message says. I don't know what consequences it would have for compatibility if we made that change in the mainline.

**Comment by shivanth** [comment]
So this would happen on all mac machines ?

**Comment by chrisvest** [comment]
No, it only happens on your machine because you have an unusually high GID. On my system, for instance, my GID is 20 (the `staff` built-in group).

**Comment by shivanth** [comment]
The build is a success after setting

```
 <configuration>
            <tarLongFileMode>posix</tarLongFileMode>
 </configuration>
``` 

within `maven-assembly-plugin` plugin definition.
