### ISSUE TITLE
Noe4j is not running

### ISSUE THREAD

**Issue by Assiam** [neo4j/neo4j#9750]
Hi everyone,

I tried to start my neo4j but I got this warning message 
`
WARNING: Max 1024 open files allowed, minimum of 40000 recommended. See the Neo4j manual.
Started neo4j (pid 31031). It is available at http://0.0.0.0:7474/
There may be a short delay until the server is ready.
See /opt/neo4j-community-3.2.0/logs/neo4j.log for current status.
`
When I see current status : Neo4j is not running

the size of my db : 578 Mo

Thank you

**Comment by eebus** [comment]
@Assiam 
Hello
Have you tried to update to Neo4j 3.2.8 and see if that solves the issue?
