### ISSUE TITLE
Properly handle spaces in configuration file

### ISSUE THREAD

**Issue by gdalecka** [neo4j/neo4j#9757]
If user edits database configuration file manually, spaces around equal sign in a property definition might be present. This should not cause problems with database start/stop/restart or status retrieval.

**Neo4j version:** neo4j-community-3.2.2
**Operating system:** Linux Mint 18

### Steps to reproduce
In neo4j.conf file add line `dbms.directories.import =import` and save changes.
Try to start database:
`$ ./neo4j start`

#### Expected behavior
Space before equals sign is trimmed and database started is successfully.

#### Actual behavior
Error message is returned:
```
./neo4j: line 186: export: `=import': not a valid identifier
```
### Steps to reproduce
In configuration file add line `dbms.memory.heap.initial_size= 512m` and save changes.
Try to start database and check database status afterwards.

#### Expected behavior
Space in property value is trimmed and database starts successfully.

#### Actual behavior
```
$ ./neo4j start
Active database: graph.db
Directories in use:
  home:         /home/gunta/Downloads/latest-neo4j/neo4j-community-3.2.2
  config:       /home/gunta/Downloads/latest-neo4j/neo4j-community-3.2.2/conf
  logs:         /home/gunta/Downloads/latest-neo4j/neo4j-community-3.2.2/logs
  plugins:      /home/gunta/Downloads/latest-neo4j/neo4j-community-3.2.2/plugins
  import:       NOT SET
  data:         /home/gunta/Downloads/latest-neo4j/neo4j-community-3.2.2/data
  certificates: /home/gunta/Downloads/latest-neo4j/neo4j-community-3.2.2/certificates
  run:          /home/gunta/Downloads/latest-neo4j/neo4j-community-3.2.2/run
Starting Neo4j.
WARNING: Max 1024 open files allowed, minimum of 40000 recommended. See the Neo4j manual.
Started neo4j (pid 29018). It is available at http://localhost:7474/
There may be a short delay until the server is ready.
See /home/gunta/Downloads/latest-neo4j/neo4j-community-3.2.2/logs/neo4j.log for current status.
$ ./neo4j status
Neo4j is not running
$ ps ax | grep 29018
29082 pts/4    S+     0:00 grep --color=auto 29018
```
Start did not report error, but database process is not running.

**Comment by utkuc** [comment]
This issue was moved to utkuc/neo4j#1

**Comment by chrisvest** [comment]
@utkuc Please refrain from making comments like that. They make it look like you are officially representing the Neo4j development team, or some other organisation that is offering official support, which is not the case. The comment also make it sound like the discussion about this issue should move to your fork repository, which it should not.

As far as I can gather, you are a group of students who are trying to fix real problems in a real software development project, as part of a school exercise. That by itself is fine, but don't leave comments like this in your upstream project. It causes confusion for others.

**Comment by tinwelint** [comment]
I tried this on 3.5 and it works, so it has been fixed. Closing.
