### ISSUE TITLE
CQL script with :param and comments results in error.

### ISSUE THREAD

**Issue by kodecharlie** [neo4j/neo4j#9758]
- Neo4j version: Neo4j Community Edition 3.2.0
- Operating system: macOS Sierra (10.12.6)

    $ cypher-shell -u neo4j -p <password> < /path/to/script.cql

where script.cql intersperses :param directives with comments (//).

This results in the error:

    Invalid input ':': expected <init> (line 6, column 1 (offset: 95))
    ":param currentTime: timestamp();"
                                                               ^
Curiously, if the :param directive is the 1st line in script.cql, then
everything works!  Only when it follows comments/commands does
there appear to be a parsing issue.

Thanks!

**Comment by Hunterness** [comment]
Hi, is this still an issue in newer versions?

**Comment by Hunterness** [comment]
Since there has been no answer in over a year I'm going to close this issue, if the issue persists please reopen it.

/Therese, Team Cypher
