### ISSUE TITLE
[Feature Request] implement GUI modeling element types to build custom GUI in browser interface

### ISSUE THREAD

**Issue by ponyatov** [neo4j/neo4j#9783]
Maybe some plugins already exists to implement custom web interface to running graph db by adding view/controller nodes&links into this db, and triggers on user interacts.

So connecting to specific http ports, user can view some interactive representation of data in this database, with GUI and interface behavior described in this database itself.

Also I think about automated HTML+JS code generation from application description resides in database itself, so user connects to database will get autogened client code will be run in browser, but this way is in the far far distant future.

**Comment by oskarhane** [comment]
This sounds pretty cool and all, but I don't think this is something we (as in Neo4j, the company) will build.
Feel free to build it yourself by building a server extension.
