### ISSUE TITLE
[Feature Request] different lucene analyzers for indexing and searching

### ISSUE THREAD

**Issue by danielmischler** [neo4j/neo4j#9787]
For certain use cases, e.g. with NGram or EdgeNGram tokenizers, it should be possible to define 2 different analyzers for a manual index, one for the index task and one for the search/query  task.

**Comment by MishaDemianenko** [comment]
Manual indexes as they are now is in support mode only for a long time already and we do not plan to add new features there.

**Comment by danielmischler** [comment]
Will there be a different approach than manual indexes or do we need tasks like this be handled by elasticsearch?
We're currently doing searches via apoc.

**Comment by chrisvest** [comment]
@danielmischler What does it mean for the indexing and the querying to use different analyzers for the same index?

**Comment by danielmischler** [comment]
Here's a description of a situation where the use of two different analyzers can be useful:
https://mchernyavska.wordpress.com/2013/07/13/elasticsearch-why-have-index_analyzer-and-search_analyzer/
It is also referencing: https://stackoverflow.com/questions/15923480/elastic-search-search-analyzer-vs-index-analyzer

**Comment by MishaDemianenko** [comment]
@danielmischler thx!
We have different indexing enhancements in our roadmap that should make it possible to completely drop manual indexes in a lot of use cases
but unfortunately, I can't provide any timelines on that.
And right, apoc is the best option so far.
