### ISSUE TITLE
Neo4j Test Harness - Provide a compatible way to configure `dbms.connector`

### ISSUE THREAD

**Issue by fbiville** [neo4j/neo4j#9795]
**Neo4j Version:** 3.0.x/3.1.x/3.2.x (not tested in 3.3)
**Operating System:** Mac OS 10.12.6 and Ubuntu 14.04 (via Travis CI)
**API:** Neo4j Test Harness

### Steps to reproduce
The issue here is that I want to disable the Bolt connector and the HTTP connector should get a randomly assigned available port.

I do not have easy steps to reproduce yet, I only have a blocked PR on Liquigraph side: https://travis-ci.org/liquigraph/liquigraph/builds/262828605.

From what I understand, the configuration by name is just ignored in 3.0.x and 3.1.x and both default HTTP and Bolt connectors are started, thus interfering with other tests that use the default ports as well.

### Expected behavior
Configuring `dbms.connector` properties by index (`dbms.connector.0...`) OR by name (`dbms.connector.bolt...`) should work in all versions of Neo4j 3.x (or at least, in all latest release of 3.0, 3.1, 3.2 and 3.3 branch).

### Actual behavior
Currently, configuration by index works fine in 3.0.x and 3.1.x but not in 3.2.x.
Configuration by name works fine in 3.2.x but not in 3.0.x and 3.1.x.

**Comment by zhenlineo** [comment]
Hi @fbiville 
Sorry for coming back to you a bit late. But could you explain more about the issue you have?
If you want to config a bolt connector, then you need to specify that the connector is for bolt by stating that `dbms.connector.another_bolt.type=BOLT`. The connector name could be anything you like such as bolt (dbms.connector.bolt.enabled=true) or 0 (dbms.connector.0.enabled=true).

Could you give me some code example to show how you configured the connector, what behaviour you expected and what actually happened?

Could you also try to update if this issue still persists in 3.3 - 3.5 Neo4j versions?


Cheers,
Zhen

**Comment by fbiville** [comment]
Hi @zhenlineo, digging up the old Liquigraph pull-request, it seems I had to configure the connectors differently depending on Neo4j 3.x version (see the short diff here: https://github.com/liquigraph/liquigraph/pull/187/files).

Is there a way that works consistently for all 3.x versions of Neo4j?

**Comment by fbiville** [comment]
It hasn't been a problem in 3.3. I need to test 3.4 and 3.5 though.

**Comment by zhenlineo** [comment]
Hi @fbiville,
Thanks for your quick reply. I feel sorry that you need to test the server version to decide what config option to use in your code. I now see your problem. So by default we turn on bolt connector, while the names of the default bolt connector differs in different versions.

But as 3.1 and 3.0 are EOL now, I probably will not fix this in these two versions. I think we did a refactor work in 3.2 and then we stick to `bolt` and `http` as the default connector names. Pls let me know if you have any problem with later versions.

**Comment by zhenlineo** [comment]
Hi @fbiville ,

I am closing this issue with the assumption that there is no such issue since 3.2 neo4j, which is the oldest version we support today. Please re-open the issue if there is more to this issue.

Cheers,
Zhen
