### ISSUE TITLE
Cypher - DELETE doesn't delete lists

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#98]
@Romiko: 'It would be great to have delete of lists in Cypher, as it will be more efficient than running a foreach loop, especially when the list contains the same relationship multiple times.

Please coudl this feature be added in asap.
Romiko'

**Comment by boggle** [comment]
Could you please give an example of what you'd like to achieve? The elements in a list may be deleted using something like `MATCH ... WITH collect(...) AS list UNWIND list AS elem DELETE elem`

**Comment by Mats-SX** [comment]
Closing as inactive and not planned to be supported.
