### ISSUE TITLE
neo4j-import hanging

### ISSUE THREAD

**Issue by AwesomeLemon** [neo4j/neo4j#9809]
Hello.
I noticed that when I set ``bad-tolerance`` option of ``neo4j-import`` to big values (starting at around 100 000), the process hangs and does nothing for an undefinetely long time.
It happens after third step of import (see sample calls at the end)

Some notes:
1) If there're no 'bad' relationships, the hang doesn't happen
2) All the 'bad' relationships up to the set limit get written to ``bad.long`` (so there're 100 000 records there if ``bad-tolerance == 100 000``, 200 000 when 200 000 and so on.
3) The problem probably isn't caused by the amount of data: if I add missing nodes for relationships (thus working with strictly more data than before), so that there're no 'bad' relationships, everything works fine
4) I'm dealing with ~=10 000 000 nodes and  ~= 36 000 000 relationships in the sample calls below
5) Setting ``--stacktrace true`` changed nothing (so no exception is thrown)
6) The machine isn't running out of RAM (14 GB free), and CPU isn't throttled.

- Neo4j version: 3.2.1
- Operating system:Ubuntu 16.04

Sample calls:
1) ``bad-tolerance`` is small, everything works fine (until it encounters too many problems):
```
user@unit-1039:~/Downloads/neo4j-community-3.2.1$ bin/neo4j-import --into 4twitterimport --nodes "users_header.csv,/tmp/users.csv"  --relationships "follows_header.csv,/tmp/followers.csv" --mode csv --multiline-fields
WARNING: neo4j-import is deprecated and support for it will be removed in a future
version of Neo4j; please use neo4j-admin import instead.

Neo4j version: 3.2.1
Importing the contents of these files into 4twitterimport:
Nodes:
  /home/user/Downloads/neo4j-community-3.2.1/users_header.csv
  /tmp/users.csv
Relationships:
  /home/user/Downloads/neo4j-community-3.2.1/follows_header.csv
  /tmp/followers.csv

Available resources:
  Total machine memory: 31.32 GB
  Free machine memory: 5.28 GB
  Max heap memory : 6.96 GB
  Processors: 8
  Configured max memory: -1626465485.00 B

Nodes, started 2017-08-14 17:00:36.917+0000
[*>:83.95 MB/s----------------------|NODE:91.55 M|PROPERTIES(3)==========|L|v:203.48 MB/s(2)==]11.8M ∆ 982K
Done in 23s 214ms
Prepare node index, started 2017-08-14 17:01:00.440+0000
[*DETECT:249.47 MB----------------------------------------------------------------------------]11.8M ∆ 640K
Done in 3s 812ms
Relationships, started 2017-08-14 17:01:04.258+0000
[>:38.51 MB/s----------------|TYP|*PREPARE(6)==========================|RE|CALCULAT|PRO|v:40.8]2.48M ∆2.44M
Done in 2s 29ms
Error in input data
Caused by:Too many bad entries 1001, where last one was: InputRelationship:
   source: /tmp/followers.csv:2487884
   startNode: 3233079548 (User-ID)
   endNode: 782549300047937536 (User-ID)
   type: Follows
 referring to missing node 782549300047937536

There were bad entries which were skipped and logged into /home/user/Downloads/neo4j-community-3.2.1/4twitterimport/bad.log
```
2) And if ``bad-tolerance`` is 100 000:
```
user@unit-1039:~/Downloads/neo4j-community-3.2.1$ bin/neo4j-import --into 4twitterimport --nodes "users_header.csv,/tmp/users.csv"  --relationships "follows_header.csv,/tmp/followers.csv" --mode csv --multiline-fields --bad-tolerance 100000
WARNING: neo4j-import is deprecated and support for it will be removed in a future
version of Neo4j; please use neo4j-admin import instead.

Neo4j version: 3.2.1
Importing the contents of these files into 4twitterimport:
Nodes:
  /home/user/Downloads/neo4j-community-3.2.1/users_header.csv
  /tmp/users.csv
Relationships:
  /home/user/Downloads/neo4j-community-3.2.1/follows_header.csv
  /tmp/followers.csv

Available resources:
  Total machine memory: 31.32 GB
  Free machine memory: 13.62 GB
  Max heap memory : 6.96 GB
  Processors: 8
  Configured max memory: 5.99 GB

Nodes, started 2017-08-14 17:02:17.485+0000
[*>:87.77 MB/s-------------------------|NODE:91.55 |PROPERTIES(3)==========||v:213.38 MB/s(2)=]11.8M ∆ 573K
Done in 22s 483ms
Prepare node index, started 2017-08-14 17:02:40.076+0000
[*DETECT:249.47 MB----------------------------------------------------------------------------]11.8M ∆8.13M
Done in 3s 692ms
Relationships, started 2017-08-14 17:02:43.775+0000
[>:42.68 MB/s----------|TY|*PREPARE(7)==================|RE|CALCULATE(2)==============|P|v:46.]4.28M ∆ 158K
Done in 3s 505ms

```
... and the cursor at the last line blinks and blinks...

So, could you please investigate the problem, or maybe point me to the place where I'm making a mistake?

**Comment by jalaz** [comment]
+1, I have the same issue

**Comment by MishaDemianenko** [comment]
Hi @AwesomeLemon it's hard to guess the exact reason of slowness here, in the same time it looks like it's related to the amount of bad data that we need to report so my first guess will be that https://github.com/neo4j/neo4j/pull/10302 should improve the situation as soon as it will be merged.
Please let us know if it's not the case.

**Comment by tinwelint** [comment]
Could you provide a thread dump at that moment?

**Comment by AwesomeLemon** [comment]
Sorry, I don't have access to that system and to that data anymore (and probably won't have it in the future).
For reference, I solved the problem by more careful data preparation (so that there were no 'bad' items at all).

**Comment by MishaDemianenko** [comment]
Thanks @AwesomeLemon, apologises that it took that long on our side. Would you mind if we will close this issue then?

**Comment by AwesomeLemon** [comment]
@jalaz in the first comment reported having the same issue, so maybe you could get some info from him.
As for me, I don't mind the issue being closed.

**Comment by MishaDemianenko** [comment]
Hi, @jalaz do you still struggling with this? Can you provide to us some additional info: thread dumps, test case, etc?

**Comment by MishaDemianenko** [comment]
Closing it due to reporter inactivity, please feel free to reopen if it's still a problem.
