### ISSUE TITLE
Setting comma delineated map and property doesn't work

### ISSUE THREAD

**Issue by brian-gates** [neo4j/neo4j#981]
See these two examples:

http://stackoverflow.com/questions/17729347/merge-query-set-map-and-created-property-upon-creation
http://stackoverflow.com/questions/17686010/neo4j-cypher-setting-a-map-and-property-yields-expected-valid-query-body

**Comment by Mats-SX** [comment]
This query (taken from one of the SO questions) now seems to work:

```
MATCH (n:User)
WHERE n.email = "test"
SET n = {data}, n.created = timestamp()
RETURN n
```

Closing this as fixed.
