### ISSUE TITLE
performance of first query slow (disabled cache) - heap problem?

### ISSUE THREAD

**Issue by andip** [neo4j/neo4j#9824]
I discovered the first query I execute via cypher-shell to a recent started neo4j database is running much slower, than subsequent queries. Means, that it took more time until "rows are available". 
Cache was disabled using parameter **dbms.query_cache_size=0** (due to performance test). 

My database does contain 130.000 nodes and 120.000 relationships.
Query does produce a result set of 10.000 rows, with two nodes per row.

My first query does usually need about 140 - 170 ms, wheras my subsequent queries do need 30 - 70 ms. With cache enabled they are running much faster, just to exclude that cache might not be properly disabled.

Since I first thought that this might be problem related to memory management of Java VM, I monitored the memory consumption of neo4j's process. Frequently, but not always, I saw an increase of the heap size, running the first query. Thus, I set parameter **dbms.memory.heap.initial_size large** in neo4j.conf and equal parameter for the VM in neo4j-community.vmoptions large enough to increase heap size, but it does not seem to have an effect on heap size initially allocated to the process. 

Is this a known / resonable behavior? Or does the general performance difference belong to any cpu caches / ssd caches or something else, I do not consider?

Query: MATCH (x:label1)-[:REL*]->(y:label2) RETURN x.column1,y.column1;

- Neo4j version: 3.2.2 (Community Edition) 
- Operating system: Windows 7
- API/Driver: (for example Cypher/Java API/Python driver vX.Y.Z)

**Comment by chrisvest** [comment]
You disabled the query plan cache, so Cypher has to replan your query every time you run it.

This is not the only cache in Neo4j. There are many caches throughout the system as a whole, and there are many layers that warm up at different speed.

For performance, you are usually more interested in the steady state performance, so you need to get the system as a whole to a steady state, and only take the measurements into account that were captured during a steady state.

Depending on the workload, it can take minutes or hours before a system arrives at a steady state. And with a JVM, which is an inherently dynamic system, the state is never really steady anyway, which means that you will get variance over time, and from run to run.

As for the heap, you can attach VisualVM to the JVM and see what heap settings it was given. The `neo4j.conf` file should be the authoritative source of JVM settings for Neo4j.

**Comment by andip** [comment]
Thank you for quick reply. 

Since I just want to benchmark the Neo4j performance compared to another database system regarding a specific structure of connected data, unfortunately I don't have time to wait for a undefined time to get JVM to steady state. So I think it will be the most comparable with another database system, if I use first query only - just to eliminate any performance boosts due to certain caches. 

However, I found out using Java VisualVM that a least that the parameters **-Xms** in file neo4j-community.vmoptions and **dbms.memory.heap.max_size** and **dbms.memory.heap.initial_size** in neo4j.conf do not seem to have an effect on initial heap size used by JavaVM, if I use neo4j-ce.exe to start database.  
I only had success increasing heap size when I execute neo4j-desktop-3.2.2.jar directly and provide java the -Xms parameter, even if the incease does not have an effect on my first query.

**Comment by jexp** [comment]
I agree with @chrisvest you would never benchmark a database in a cold state or with disabled caches. After all the only thing that is relevant is real world performance.

That's why also using neo4j-community doesn't really make sense.
You should also make sure that both the heap as well as the page-cache config are correct and queries are run several times (with parameters) to warm-up.
