### ISSUE TITLE
service info broken on linux for non-owners 

### ISSUE THREAD

**Issue by davidszotten** [neo4j/neo4j#984]
```
vagrant@precise32:~(1)$ /etc/init.d/neo4j-service info
Neo4j Server is not running
vagrant@precise32:~(1)$ sudo /etc/init.d/neo4j-service info
Neo4j Server is running at pid 4404
```

it appears that `checkstatus()` in `/var/lib/neo4j/bin/utils` sends signal `0` to the process, which fails for non-owners, and at which point the script unsets the `NEO4J_PID` variable

**Comment by craigtaverner** [comment]
I suspect this part of the debian scripts has been re-written since then, and no further comments have occurred on this issue, so I'm closing it.
