### ISSUE TITLE
Incorrect Rendering in Browser UI

### ISSUE THREAD

**Issue by Tshimanga** [neo4j/neo4j#9846]
- Neo4j version: 3.2.3 Community Edition
- Operating system: Ubuntu 16.04.3 LTS and Windows 10

- **Steps to reproduce**
   Fresh Install of Ubuntu 16.04 and Neo4j 3.2.3 Community Edition. Connect to a graph. Run queries 
   for some nodes/edges

- Expected behavior
  Browser displays matching subgraph with all relationship firmly secured to their heads and tails.

- Actual behavior
   Many relationships floating without a head, no relationships being displayed, or only one node being displayed

![neo4j-render-issue](https://user-images.githubusercontent.com/16946069/29431334-6c4bcd30-834c-11e7-9038-9cb18c2d5a9b.png)
![neo4j-render-issue2](https://user-images.githubusercontent.com/16946069/29431487-f1b83d6e-834c-11e7-9dfa-205b756e2d90.png)
![neo4j-render-issue3](https://user-images.githubusercontent.com/16946069/29431486-f1b82338-834c-11e7-97d4-eaface5f3e55.png)

**Comment by Tshimanga** [comment]
Update: Seems to occur in graphs migrated from older versions of neo4j. When I create a new graph the problem doesn't occur. When connect to a migrated graph I get the issue.

**Comment by oskarhane** [comment]
We're unable to reproduce this. Please try it in recent versions of neo4j-browser and open an issue on https://github.com/neo4j/neo4j-browser if it still exists.

**Comment by oskarhane** [comment]
We're unable to reproduce this. Please try it in recent versions of neo4j-browser and open an issue on https://github.com/neo4j/neo4j-browser if it still exists.
