### ISSUE TITLE
Internal error - should have used fall back to execute query, but something went horribly wrong

### ISSUE THREAD

**Issue by Alan-R** [neo4j/neo4j#9847]
```
MATCH (Hobbit1)<-[r:FriendsWith { }]-(Hobbit2) where ID(Hobbit1) = 20 AND ID(Hobbit2) = 21
DELETE r
```

ERROR
Neo.DatabaseError.General.UnknownError
Internal error - should have used fall back to execute query, but something went horribly wrong

- **Neo4j version**:  3.2.3
- **Operating system**: Ubuntu 16.04.3 LTS
- **API/Driver**: Web interface
- **To reproduce**: Run this query
- **Expected behavior** - either does nothing, or deletes a relationship
- **Actual Behavior**: Got internal error

Getting rid of the empty {} makes the error go away...

```
Neo4j 3.2.3
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

**Comment by fickludd** [comment]
This issue is fixed by https://github.com/neo4j/neo4j/pull/10214.

**Comment by Alan-R** [comment]
Thanks @OliviaYtterbrink!
