### ISSUE TITLE
[3.2.3] Browser only has "export PNG" and "export CSV"

### ISSUE THREAD

**Issue by jacbar01** [neo4j/neo4j#9850]
Hello,

I just upgraded my Neo4j database from version 3.1.1 to 3.2.3, and I noticed that the browser has lost half of its export options.

- Neo4j version: 3.2.3 CE installed as a service via Chocolatey package
- Operating system: Windows 10 64 bits, Home Edition (French)

Steps to reproduce:

1. Log in to the instance with the browser at http://localhost:7474
2. Expand the database pane
3. Click on a Label to show the first 25 corresponding nodes
4. Move the mouse over the "export" button to see what export options are being offered
 
- Expected behavior:
A drop-down menu showing "export PNG", "export SVG", "export JSON" and "export CSV".

- Actual behavior:
Only two options are being offered: "export PNG" and "export CSV".

It used to work as expected with version 3.1.1 on the exact same browser (Chrome 59.0.3071.115).
I also tested it with the exact same result on IE 11 and Firefox version 47.0.2.

I guess I can use neo4j shell tools to get those export functionalities, but not having them straight from the browser is quite painful.

Regards,
Jacques

**Comment by YuanLIAOcode** [comment]
* Mac 10.12.6
* Neo4j Community Version 3.2.3 & 3.2.1

The Same Problem

Only could export PNG and CSV files from browsers (Chrome, Firefox and Safari)

**Comment by oskarhane** [comment]
Hi, thanks for the report @jacbar01 and @YuanLIAOcode.
Could you raise this issue over at the [Neo4j Browser repo](https://github.com/neo4j/neo4j-browser) please?
