### ISSUE TITLE
Neo4j service on Linux

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#99]
@Alan-R: 'According to the Linux Standard Base specification for init scripts, if you start a service that's started, or stop one that's stopped, the init script should exit with return code zero.

The neo4j-service script doesn't follow the LSB init script spec.  At least for the start case, it complains if it's already started (which is tolerable) but it exits with non-zero return code - which is not tolerable.

The LSB behavior actually makes sense - if you're running a script and you wanted it started, you got what you wanted - so it should not give the same exit code as though the script did not give you what you wanted.

The full set of well-defined exit codes for init scripts can be found here:
http://refspecs.linuxbase.org/LSB_3.1.1/LSB-Core-generic/LSB-Core-generic/iniscrptact.html

In a perfect world, if you might say things like this for starting neo4j:
    Neo4j already running - pid xxx                                                   [with exit code zero of course]
    Neo4j started - pid xxx                                                               [also with exit code zero]
    Neo4j already stopped                                                               [with exit code zero of course]
    Neo4j stopped successfully.                                                       [also with exit code zero]

FWIW, if the script is in /etc/init.d - it _is_ a service script.  Putting service on the end of the name is kinda redundant (and not usually done).  This isn't a bug, but it does make typing service neo4j-service start a lot harder than service neo4j start.
'

**Comment by benbc** [comment]
This is fixed in 3.0.
