### ISSUE TITLE
bug or undocumented feature of variable length relationship?

### ISSUE THREAD

**Issue by bebbi** [neo4j/neo4j#990]
With the default graph setup of console.neo4j.org,

the following query behaves differently with the first relation written as `[:KNOWS]` vs `[:KNOWS*]` or `[:KNOWS*1..]`

    START a=node:node_auto_index(name="Cypher")
    MATCH a<-[:KNOWS*1]-()-[:KNOWS]->b 
    RETURN b

They give the following results

- first: "cypher"
- second and third: "cypher, morpheus, trinity"

The doc (12.2.10. Variable length relationships) seems to imply that they should all be the same.
I was stumbling over this when looking for a match that includes the start node as well. Maybe it's something to document?

**Comment by jakewins** [comment]
This is expected behavior.
