### ISSUE TITLE
memory exception even when there is available memory

### ISSUE THREAD

**Issue by HassanHashemi** [neo4j/neo4j#9914]
it seems that 'dbms.memory.heap.max_size' is not doing what it is supposed to do.

i have a query that updates about 200,000 relations which ends up with 

`There is not enough memory to perform the current task. Please try increasing 'dbms.memory.heap.max_size' in the neo4j configuration`

while i have configured following options to really humongous values:
dbms.memory.heap.initial_size = 160000000000000
dbms.memory.heap.max_size = 160000000000000
dbms.memory.pagecache.size = 5000000000

i also made sure that values are actually being applied by executing 'dbms.listConfig()'

**Comment by jexp** [comment]
remove the spaces before and after the equals sign
use modifier like M or G for Megabytes and Gigabytes

```
dbms.memory.heap.initial_size=16G
dbms.memory.heap.max_size=16G
dbms.memory.pagecache.size=5G
```

**Comment by HassanHashemi** [comment]
@jexp doing that did not make any change also.
still getting MemoryException

this is also the JVM parameters.

![image](https://user-images.githubusercontent.com/6805984/29739592-9cc92096-8a56-11e7-84cb-08bf15f917d8.png)

**Comment by jexp** [comment]
Can you please share your full config file?

**Comment by HassanHashemi** [comment]
Yeah ofc, thanks for reviewing.
here is neo4j-community.vmoptions which is located under 
"C:\Users\admin\AppData\Roaming\Neo4j Community Edition" 
**[Here at gist.github](https://gist.github.com/HassanHashemi/4b69f43b8701eb221a9374608de0d030)**

and here is the neo4j.conf which is located under
"C:\Users\admin\AppData\Roaming\Neo4j Community Edition"
**[here at gist.github](https://gist.github.com/HassanHashemi/b6ba7d027fbc97e08e31bd568402ed95)**

just for sake of completeness here is the neo4j desktop window:

![image](https://user-images.githubusercontent.com/6805984/29744010-2cdc6f1c-8ab1-11e7-8dab-c3f6e9698d1f.png)

**Comment by HassanHashemi** [comment]
any thoughts?

**Comment by jexp** [comment]
From a colleague

> 1) The best option is to make him use the zip-installation. There is still something weird when using that (any changes to dbms.memory.heap.initial_size or dbms.memory.heap.max_size will show up in dbms.listConfig() but will *not* be activated unless you reinstall the service) ... but at least it is consistently weird.
> 2) Only use dbms.memory.heap.initial_size and dbms.memory.heap.max_size in neo4j.conf. Using anything else (either in vmoptions.conf or with dbms.jvm.additional in neo4j.conf) will just confuse/complicate matters.
> 3) I am myself unable to influence the actual memory usage of the neo4j process in the Neo4j CE EXE installation. Regardless of what I do it seems to go for the default

**Comment by HassanHashemi** [comment]
Thanks
Using Neo4j Console fixed the problem.
