### ISSUE TITLE
Cypher query with node label returns empty result

### ISSUE THREAD

**Issue by ddesna** [neo4j/neo4j#9917]
I'm using **Neo4j 2.3.2** and I have the following problem:
When I use node label in my query, like: 
`MATCH (n:NodeLabel) 
WHERE n.foo= "1502" AND n.bar= "642764" RETURN n` 
it returns empty result.

But, when I use the same query without indicate node label, like:
`MATCH (n) WHERE n.foo= "1502" AND n.bar= "642764" RETURN n` 
it returns correctly all nodes matched with the query.

Can someone help me with this issue ?

**Comment by jexp** [comment]
Does your node have the label?

MATCH (n) WHERE n.foo= "1502" AND n.bar= "642764" RETURN n, labels(n)

Perhaps your index is broken?

You can try (on a backup) to delete the directories index and label below `data/databases/graph.db.save/schema/`
They will be recreated at startup.

**Comment by ddesna** [comment]
Thank you for the answer @jexp !
Yes, all nodes have the same label.

Removing schema folder and restarting Neo4j helps.
Now it's working as expected.

But, how I can prevent this issue ? I can't stop and delete this folder in production every time :cry:

**Comment by sherfert** [comment]
Hi @ddesna 
I agree deleting this folder every time seems unreasonable. Have you tried updating to a newer version of neo4j and verify if the issue is gone there? If there is an actual issue with 2.3 it is unlikely going to get fixed.

**Comment by sherfert** [comment]
We haven't heard back in quite a while. Please reopen if necessary.
