### ISSUE TITLE
Boolean type edge property not printing on web browser UI

### ISSUE THREAD

**Issue by alexmloveless** [neo4j/neo4j#9950]
Version:	3.2.3
Edition:	Community
Windows 2007
Size:	913.59 MiB

I have an instance running locally on my laptop. There is a boolean type edge property on all edges in the graph named 'speaker'. When I change the text label displayed from the relationship type to the 'speaker' property the edge label disappears leaving only a small gap in the edge line. To change the edge label I:

- click on the edge property in gray at the top of the current query window
- click on the 'speaker' property at the bottom of the window

Images showing this attached.

If there are any 'hacks' to get around this in the short term it would be appreciated.

Thanks!

![neobug_before](https://user-images.githubusercontent.com/17529516/29915225-06e68c4a-8e33-11e7-964d-58b2e64cdf7e.PNG)
![neobug_other](https://user-images.githubusercontent.com/17529516/29915224-06e6905a-8e33-11e7-9676-066e50fdada3.PNG)
![neobug_after](https://user-images.githubusercontent.com/17529516/29915226-06ea78aa-8e33-11e7-8ade-b78bded720ac.PNG)

**Comment by oskarhane** [comment]
Thanks for the report @alexmloveless!
May I ask you to open the issue over at https://github.com/neo4j/neo4j-browser instead?

I've not found any workarounds, sorry.

**Comment by alexmloveless** [comment]
Done:

https://github.com/neo4j/neo4j-browser/issues/640
