### ISSUE TITLE
 QueryExecutionException: Unable to load NODE with id 118300203  when i execute match cql

### ISSUE THREAD

**Issue by mo9527** [neo4j/neo4j#9957]
my cql : MATCH (n:Person)-[*0..3]-(m:Person) where n.mobile='18602194535' return ID(n) as srcId, n.mobile as src, ID(m) as desId, m.mobile as des limit 5000;

Exeception:
Neo.ClientError.Statement.EntityNotFound
![r s8u 6u bdlyc tpummqv](https://user-images.githubusercontent.com/13432449/29958801-1b4f6702-8f27-11e7-8fdc-d7ab28ad2d65.png)

Why? How I fix it?

**Comment by mo9527** [comment]
but actually this Node is not exists 
![image](https://user-images.githubusercontent.com/13432449/29959066-371e4cb8-8f28-11e7-83cf-a4e928d8a0e3.png)

**Comment by HassanHashemi** [comment]
have you checked that the pattern ` cql : MATCH (n:Person)-[*0..3]-(m:Person)` exists?

**Comment by mo9527** [comment]
Hi
    I have solved this problem . The reason for this problem is some nodes was broken because i forced to stop the database.
   I use the store-utils tool to copy my database,  then the tool delete those broke nodes and relationships.

thanks.
    



felix_21@163.com
 
From: Hassan Hashemi
Date: 2017-09-05 12:31
To: neo4j/neo4j
CC: mo9527; Author
Subject: Re: [neo4j/neo4j] QueryExecutionException: Unable to load NODE with id 118300203 when i execute match cql (#9957)
have you checked that the pattern cql : MATCH (n:Person)-[*0..3]-(m:Person) exists?
